prometheus-xmpp-alerts: 0.4.2 -> 0.4.2 + fixes
NixOS/nixpkgs pull request #100274
Opened 2020-10-11 20:24 UTC by hax404

###### Motivation for this change
Fix 500s that come back when the alertmanager sends alerts

```
prometheus-xmpp-alerts[30888]: ERROR    Error handling request
prometheus-xmpp-alerts[30888]: Traceback (most recent call last):
prometheus-xmpp-alerts[30888]:   File "/nix/store/nlvjjvb9471dbpdj8fhdih0ak90cq9d9-python3.8-aiohttp-3.6.2/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 418, in start
prometheus-xmpp-alerts[30888]:     resp = await task
prometheus-xmpp-alerts[30888]:   File "/nix/store/nlvjjvb9471dbpdj8fhdih0ak90cq9d9-python3.8-aiohttp-3.6.2/lib/python3.8/site-packages/aiohttp/web_app.py", line 458, in _handle
prometheus-xmpp-alerts[30888]:     resp = await handler(request)
prometheus-xmpp-alerts[30888]:   File "/nix/store/n2axls35979gx2aqdfnl0yafnrffl100-prometheus-xmpp-alerts-0.4.2/bin/.prometheus-xmpp-alerts-wrapped", line 141, in serve_alert
prometheus-xmpp-alerts[30888]:     text = '\n--\n'.join(create_message_full(alert))
prometheus-xmpp-alerts[30888]:   File "/nix/store/n2axls35979gx2aqdfnl0yafnrffl100-prometheus-xmpp-alerts-0.4.2/lib/python3.8/site-packages/prometheus_xmpp/__init__.py", line 57, in create_message_full
prometheus-xmpp-alerts[30888]:     alert['annotations']['summary'],
prometheus-xmpp-alerts[30888]: KeyError: 'summary'
prometheus-xmpp-alerts[30888]: INFO     ::1 [11/Oct/2020:20:18:38 +0000] "POST /alert HTTP/1.1" 500 244 "-" "Alertmanager/0.21.0"
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-11 22:55 UTC, maralorn commented
Result of `nixpkgs-review pr 100274` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>prometheus-xmpp-alerts</li>
  </ul>
</details>

2020-10-11 23:00 UTC, maralorn commented
The fix is apparently in this commit: https://github.com/jelmer/prometheus-xmpp-alerts/commit/8b4c2f7bd2c548a751748b913ce0f45b9f49c6ea but I see no harm in just bumping to the newest commit. It includes a commit by @andir ;-) I saw.

This looks fine by me. I am just not sure if there is some other convention for the version name that we should use.

I would like a second opinion on that last point, but ping me, if you don‘t get any more reactions.

2020-10-12 00:19 UTC, mweinelt commented on pkgs/servers/monitoring/prometheus/xmpp-alerts.nix
> +  version = "0.4.2+git";
From the traceback this looks alot like an upstream issue, so the proper course of action would be to report it upstream and have them make a new release.

In the meantime we could apply a patch to fix the situation if you can identify one.

2020-10-12 00:21 UTC, mweinelt requested changes
Please report this issue upstream and have them issue a fixed release.

2020-10-12 02:04 UTC, maralorn commented
@mweinelt The issue is already fixed upstream. (As I pointed to in the commit I linked.)

Do you want to wait with this PR until they have made the next release?

2020-10-12 02:10 UTC, mweinelt commented
I'm saying let's apply the patch and wait for upstream to do a new release. Let's not start doing releases downstream.

2020-10-12 02:14 UTC, maralorn commented
Fair enough.

2020-10-12 07:36 UTC, andir commented
You want at least 0f54da76ecd200887e7f267113b7c6a9cfae43d4 & 500a316a83b5d72c490cb62c3e7f5aa5efc7f5bf from my fork in order to actually be able to use the amtool integration of this. I filed a PR for those just now: https://github.com/jelmer/prometheus-xmpp-alerts/pull/19

2020-10-12 07:41 UTC, andir requested changes

2020-10-12 07:41 UTC, andir commented on pkgs/servers/monitoring/prometheus/xmpp-alerts.nix
> +  propagatedBuildInputs = with pythonPackages; [ slixmpp prometheus_client pytz pyyaml ];
This is wrong. You only need pytz during the check phase. You are also missing the `aiohttp` runtime requirement.

2020-10-24 22:50 UTC, andir commented
While we are waiting for upstream and/or the required fixes you can probably start adding a nixos module based on https://github.com/andir/infra/blob/e078bda5b9dafbfff2216a8e9131ce180196c362/config/servers/mon/xmpp-alerts.nix.

2020-10-29 09:10 UTC, andir commented
Please update to the latest release: https://github.com/jelmer/prometheus-xmpp-alerts/commit/1620e9ea7bb2bfc66f033e35765a996473deabf3

2020-11-26 22:12 UTC, SuperSandro2000 commented
@hax404 ping

2021-05-13 12:31 UTC, maralorn commented
LGTM, but other people in this thread are more familiar with these parts of nixpkgs.

2021-05-13 20:22 UTC, SuperSandro2000 commented on pkgs/servers/monitoring/prometheus/xmpp-alerts.nix
> +buildPythonApplication rec {
```suggestion
buildPythonApplication rec {
```
applying with to the entire scope is an anti pattern.

2021-05-13 20:22 UTC, SuperSandro2000 commented on pkgs/servers/monitoring/prometheus/xmpp-alerts.nix
> +  ++ (with python3Packages; [
```suggestion
  ] ++ (with python3Packages; [
```

2021-05-17 15:20 UTC, mweinelt reviewed
The package looks fine, the module can be migrated further to RFC 42 still, also in a backward compatible way.

2021-05-17 15:20 UTC, mweinelt commented on nixos/modules/services/monitoring/prometheus/xmpp-alerts.nix
> +        for supported Values.
```suggestion
        for supported values.
```

nit :wink:

2021-05-17 15:20 UTC, mweinelt commented on nixos/modules/services/monitoring/prometheus/xmpp-alerts.nix
>      configuration = mkOption {
```suggestion
    settings = mkOption {
```

and then add the following to add a migration path between old and new option.

```
  imports = [
    (mkRenamedOptionModule 
      [ "services" "prometheus" "xmpp-alerts" "configuration" ]
      [ "services" "prometheus" "xmpp-alerts" "settings" ])
  ];
```

2021-05-17 15:20 UTC, mweinelt commented on nixos/modules/services/monitoring/prometheus/xmpp-alerts.nix
> +  configFile = settingsFormat.generate "prometheus-xmpp-alerts.yml" cfg.configuration;
```suggestion
  configFile = settingsFormat.generate "prometheus-xmpp-alerts.yml" cfg.settings;
```

2021-05-18 23:36 UTC, merged