hugs: fix build on darwin
NixOS/nixpkgs pull request #100216
Opened 2020-10-11 08:36 UTC by siraben

###### Motivation for this change
Fix build on darwin. Had to pick some commits from a [repository](https://github.com/FranklinChen/hugs98-plus-Sep2006) that was working on the same issue.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-11 08:47 UTC, symphorien commented on pkgs/development/interpreters/hugs/default.nix
> +  buildInputs = [ gcc ];
you probably meant to use gccStdenv ?

2020-10-11 08:53 UTC, siraben commented on pkgs/development/interpreters/hugs/default.nix
> +  buildInputs = [ gcc ];
Oops, yes.

2020-10-11 09:03 UTC, siraben commented
@symphorien changing `gcc` to `gccStdenv` breaks the binary at runtime, giving

```
./result/bin/hugs 
__   __ __  __  ____   ___      _________________________________________
||   || ||  || ||  || ||__      Hugs 98: Based on the Haskell 98 standard
||___|| ||__|| ||__||  __||     Copyright (c) 1994-2005
||---||         ___||           World Wide Web: http://haskell.org/hugs
||   ||                         Bugs: http://hackage.haskell.org/trac/hugs
||   || Version: September 2006 _________________________________________

Haskell 98 mode: Restart with command line option -98 to enable extensions

Prelude not found on current path: ".:{Home}/lib/hugs/packages/*:/usr/local/lib/hugs/packages/*:{Hugs}/packages/*"

FATAL ERROR: Unable to load prelude
```

2020-10-11 09:32 UTC, symphorien commented
I have no idea why that would cause it, sorry.

2020-10-11 09:35 UTC, siraben commented
@joachifm

2020-10-11 18:57 UTC, siraben commented
@jtojnar could you help take a look as well?

2020-10-11 19:26 UTC, jtojnar commented
gccStdenv would be used in place of regular stdenv, not in buildInputs. 
But what is the issue with Clang exactly?

On Ne, říj 11, 2020 at 11:57, Ben Siraphob <notifications@github.com> 
wrote:
> @jtojnar could you help take a look as well?
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or unsubscribe.
>

2020-10-12 01:57 UTC, siraben commented
@jtojnar here is the issue when I use clang to build
```
$ ./result/bin/hugs
__   __ __  __  ____   ___      _________________________________________
||   || ||  || ||  || ||__      Hugs 98: Based on the Haskell 98 standard
||___|| ||__|| ||__||  __||     Copyright (c) 1994-2005
||---||         ___||           World Wide Web: http://haskell.org/hugs
||   ||                         Bugs: http://hackage.haskell.org/trac/hugs
||   || Version: September 2006 _________________________________________

Haskell 98 mode: Restart with command line option -98 to enable extensions

Prelude not found on current path: ".:{Home}/lib/hugs/packages/*:/usr/local/lib/hugs/packages/*:{Hugs}/packages/*"

FATAL ERROR: Unable to load prelude
```

2021-01-18 13:27 UTC, SuperSandro2000 requested changes

2021-01-18 13:27 UTC, SuperSandro2000 commented on pkgs/development/interpreters/hugs/default.nix
> +    }) ] ++ lib.optionals stdenv.isDarwin [
Please always apply all patches.

2021-01-18 13:27 UTC, SuperSandro2000 commented on pkgs/development/interpreters/hugs/default.nix
> +  buildInputs = [ gcc ];
nativeBuildInputs.

2021-01-18 16:27 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 100216` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>hugs</li>
</ul>
</details>

2021-01-18 16:38 UTC, siraben commented
I'll apply those changes.

2022-11-07 23:52 UTC, SuperSandro2000 commented
Closing due to inactivity from author.

2022-11-07 23:52 UTC, closed without merging