ugtrain: init at v0.4.1
NixOS/nixpkgs pull request #100333
Opened 2020-10-12 13:08 UTC by mtrsk

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-12 13:31 UTC, sikmir commented on pkgs/tools/misc/ugtrain/default.nix
> +    license = licenses.gpl3;
gpl3 is deprecated, consider using gpl3Only or gpl3Plus (https://discourse.nixos.org/t/lib-licenses-gpl3-co-are-now-deprecated/8206/3).

2020-10-12 16:49 UTC, doronbehar requested changes

2020-10-12 16:49 UTC, doronbehar commented on pkgs/tools/misc/ugtrain/default.nix
> +  nativeBuildInputs = [ autoconf automake libtool scanmem ];
Use `autoreconfHook`, instead of both `autoconf` and `automake` (and I think `libtool` as well).

2020-10-12 16:49 UTC, doronbehar commented on pkgs/tools/misc/ugtrain/default.nix
> +  '';
Then I think this won't be needed.

2020-10-12 16:49 UTC, doronbehar commented on pkgs/tools/misc/ugtrain/default.nix
> +  buildInputs = [ binutils pkg-config ];
Why is `binutils` needed?

2020-10-12 16:49 UTC, doronbehar commented on pkgs/tools/misc/ugtrain/default.nix
> +{ stdenv, autoconf, automake, binutils, glib, libtool, pkg-config, scanmem, fetchFromGitHub }:
`glib` not used. Also, it's somewhat common to use lines to separate arguments, and putting the "native" deps first:

```suggestion
{ stdenv
, fetchFromGitHub
, autoreconfHook
, pkg-config
, scanmem
}:
```

2020-10-12 18:21 UTC, doronbehar commented
Result of `nixpkgs-review pr 100333` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ugtrain</li>
  </ul>
</details>

2020-10-12 18:21 UTC, doronbehar commented
Passes `nixpkgs-review` build and `--help` test.

2020-10-12 18:47 UTC, aanderse commented
`pkg-config` belongs in `nativeBuildInputs`.

2020-10-12 18:48 UTC, doronbehar commented
> `pkg-config` belongs in `nativeBuildInputs`.

Good catch.

2020-10-12 21:39 UTC, mtrsk commented
> `pkg-config` belongs in `nativeBuildInputs`.

I get some build errors when removing `pkg-config` from `buildInputs`.

2020-11-27 20:36 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 100333` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ugtrain</li>
  </ul>
</details>

2020-11-27 20:45 UTC, merged