pawn: init at 4.0.5749
NixOS/nixpkgs pull request #100531
Opened 2020-10-14 23:33 UTC by panurg

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-05 23:57 UTC, roberth commented on pkgs/development/compilers/pawn/default.nix
> +      }
@alyssais, how should this be represented?

2020-11-24 16:07 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/384

2020-11-25 19:43 UTC, AndersonTorres requested changes

2020-11-25 19:43 UTC, AndersonTorres commented on pkgs/development/compilers/pawn/default.nix
> +  buildInputs = with pkgs; [ cmake gcc_multi ];
Why not to declare them on function arguments?

Also, `cmake` usually goes in `nativeBuildInputs`.

2020-11-25 19:43 UTC, AndersonTorres commented on pkgs/development/compilers/pawn/default.nix
> +    homepage = https://www.compuphase.com/pawn/pawn.htm;
Put double quotes in the HTTP link strings.

2020-11-25 19:43 UTC, AndersonTorres commented on pkgs/development/compilers/pawn/default.nix
> +  };
A cosmetic whitespace here, please.

2021-01-18 18:50 UTC, SuperSandro2000 requested changes

2021-01-18 18:50 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +  panurg = {
Please put this into a separate commit with the message ``maintainers: add panurg``.

2021-01-18 18:50 UTC, SuperSandro2000 commented on pkgs/development/compilers/pawn/default.nix
> +{ stdenv, fetchzip, pkgs }:
Never input pkgs.

2021-01-18 18:50 UTC, SuperSandro2000 commented on pkgs/development/compilers/pawn/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-01-27 23:45 UTC, AndersonTorres commented
I have tried it but it does not work.

2021-07-29 03:22 UTC, closed without merging