astroid: fix python plugin usage
NixOS/nixpkgs pull request #100642
Opened 2020-10-15 21:03 UTC by oxzi

###### Motivation for this change
Astroid's python-based plugin system was not usable before.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-20 23:37 UTC, SuprDewd approved these changes
LGTM

2020-11-27 09:03 UTC, SuperSandro2000 commented on pkgs/applications/networking/mailreaders/astroid/default.nix
> +    cmake ronn pkgconfig wrapGAppsHook gobject-introspection
```suggestion
    cmake ronn pkg-config wrapGAppsHook gobject-introspection
```

2020-11-27 09:03 UTC, SuperSandro2000 commented on pkgs/applications/networking/mailreaders/astroid/default.nix
> +  enableParallelBuilding = true;
cmake does this automatically.

```suggestion
```

2020-11-27 09:04 UTC, SuperSandro2000 requested changes
Please fix the eval error.

2021-01-10 13:10 UTC, SuperSandro2000 commented on pkgs/applications/networking/mailreaders/astroid/default.nix
> +  ] ++ (if vim == null then [] else [ vim ]);
```suggestion
  ] ++ lib.optionals vim [ vim ]);
```

2021-01-11 22:48 UTC, SuperSandro2000 commented
@oxzi please fix the merge conflict.

2021-01-12 12:49 UTC, oxzi commented
@SuperSandro2000: Thanks, please have another look.

2021-01-13 07:48 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 100642` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>astroid</li>
</ul>
</details>

2021-01-13 07:49 UTC, merged