add darwin support to ssm-session-manager-plugin
NixOS/nixpkgs pull request #101262
Opened 2020-10-21 16:36 UTC by nbr

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-21 22:10 UTC, martinbaillie approved these changes

2020-11-27 01:36 UTC, SuperSandro2000 requested changes

2020-11-27 01:36 UTC, SuperSandro2000 commented on pkgs/applications/networking/cluster/ssm-session-manager-plugin/default.nix
> +  nativeBuildInputs = [ ] ++ stdenv.lib.optionals stdenv.hostPlatform.isLinux [
```suggestion
  nativeBuildInputs = stdenv.lib.optionals stdenv.hostPlatform.isLinux [
```

2020-11-27 01:36 UTC, SuperSandro2000 commented on pkgs/applications/networking/cluster/ssm-session-manager-plugin/default.nix
>      "install -m755 -D usr/local/sessionmanagerplugin/bin/session-manager-plugin $out/bin/session-manager-plugin";
```suggestion
  '' else ''
    install -m755 -D usr/local/sessionmanagerplugin/bin/session-manager-plugin $out/bin/session-manager-plugin
  '';
```

2020-11-30 15:44 UTC, nbr commented
Closing in favor of https://github.com/NixOS/nixpkgs/pull/102103

2020-11-30 15:44 UTC, closed without merging