nuraft: init at 1.1.2
NixOS/nixpkgs pull request #101247
Opened 2020-10-21 11:20 UTC by wheelsandmetal

###### Motivation for this change
Add nuraft lib

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-21 11:45 UTC, AndersonTorres commented on pkgs/development/libraries/nuraft/default.nix
> +  };
```suggestion
  platforms = platforms.linux;
  };
```

2020-10-21 11:45 UTC, AndersonTorres commented on pkgs/development/libraries/nuraft/default.nix
> +    description = "C++ implementation of Raft core logic as a replication library ";
Trailing whitespace.

```suggestion
    description = "C++ implementation of Raft core logic as a replication library";
```

2020-10-21 13:43 UTC, wheelsandmetal commented
Not sure who to set as maintainer

2020-10-23 02:57 UTC, AndersonTorres commented
@wheelsandmetal 

If you are interested in maintain this package, you can add yourself at `maintainers/maintainer-list.nix` and add it to meta.maintainers list, or else just keep the list empty (basically "orphaning" the package).

Also, squash your commits to more meaningful messages. We don't pollut the commit log with small messages as "applying suggested changes" or "fix trailing whitespace". Just the original message "nuraft: init at 1.1.2" suffices.

2020-10-27 14:18 UTC, wheelsandmetal commented
> @wheelsandmetal
> 
> If you are interested in maintain this package, you can add yourself at `maintainers/maintainer-list.nix` and add it to meta.maintainers list, or else just keep the list empty (basically "orphaning" the package).

Sure

> Also, squash your commits to more meaningful messages. We don't pollut the commit log with small messages as "applying suggested changes" or "fix trailing whitespace". Just the original message "nuraft: init at 1.1.2" suffices.

ah didn't know, thanks!

2020-10-28 19:03 UTC, AndersonTorres requested changes
@wheelsandmetal

> > Also, squash your commits to more meaningful messages. We don't pollut the commit log with small messages as "applying suggested changes" or "fix trailing whitespace". Just the original message "nuraft: init at 1.1.2" suffices.
> 
> ah didn't know, thanks!

Split the commits:
- One for "add myself to maintainers"
- The next one "nuraft: init at 1.1.2"

2020-10-29 11:33 UTC, AndersonTorres approved these changes
LGTM, LGTBorg

2020-10-29 12:24 UTC, merged