modules/security/pam.nix: add enableSSHAgentAuthNoHome
NixOS/nixpkgs pull request #102187
Opened 2020-10-30 21:09 UTC by jkarlson

This variant of the old sshAgentAuth is useful, if sudo is
being used by authenticating as the user and not
as root as is the default as user could normally just
edit the ~/.ssh/authorized_keys to get access as root.

###### Motivation for this change
Make pam_ssh_agent_auth useful for sudo default settings

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-30 21:37 UTC, SuperSandro2000 commented on nixos/modules/security/pam.nix
> +          sshAgentAuth. Use this option, when user trying to authenticate
```suggestion
          sshAgentAuth. Use this option, when the user trying to authenticate
```

2020-10-31 07:17 UTC, jkarlson commented on nixos/modules/security/pam.nix
> +          sshAgentAuth. Use this option, when user trying to authenticate
added

2020-10-31 12:09 UTC, lourkeur commented
Tested on sudo on Nightingale. It can prevent sudoing based on just the user-editable files, but you have to be super explicit about it:
```nix
{ lib, ... }:
{
  security.pam.services.sudo = {
    sshAgentAuth = lib.mkForce false;
    sshAgentAuthNoHome = true;
  };
}
```
otherwise you get 2 auth_sufficient lines in /etc/pam.d/sudo. That's because `nixos/modules/security/sudo.nix` enables it for convenience. That is a usability problem in my opinion. This raises the question of what the config generator should do if both sshAgentAuth and sshAgentAuthNoHome are set. I would say it should either inhibit sshAgentAuth and use the stricter setting, or perhaps fail an assert.

2020-10-31 12:34 UTC, jkarlson commented
> Tested on sudo on Nightingale. It can prevent sudoing based on just the user-editable files, but you have to be super explicit about it:
> 
> ```nix
> { lib, ... }:
> {
>   security.pam.services.sudo = {
>     sshAgentAuth = lib.mkForce false;
>     sshAgentAuthNoHome = true;
>   };
> }
> ```
> 
> otherwise you get 2 auth_sufficient lines in /etc/pam.d/sudo. That's because `nixos/modules/security/sudo.nix` enables it for convenience. That is a usability problem in my opinion. This raises the question of what the config generator should do if both sshAgentAuth and sshAgentAuthNoHome are set. I would say it should either inhibit sshAgentAuth and use the stricter setting, or perhaps fail an assert.

note optionalString cfg.sshAgentAuthNoHome not (config.security.pam.enableSSHAgentAuth && cfg.sshAgentAuth) so you don't need to have config.security.pam.enableSSHAgentAuth enabled and you don't get the double entry.

I absolutely dislike the current solution and my solution, I would only have cfg.sshAgentAuth boolean and cfg.sshAgentAuthPath listOf str, but that would break backwards compat, so I proposed this more conservative solution that bypasses the current config.

2020-10-31 12:40 UTC, jkarlson commented
I guess there is backwards compatible solution of making

         ${optionalString cfg.sshAgentAuth
              "auth sufficient ${pkgs.pam_ssh_agent_auth}/libexec/pam_ssh_agent_auth.so file=${lib.concatStringsSep ":" cfg.sshAgentAuthPaths}"}

where default paths would be the old paths and for new style config you would just unset config.security.pam.enableSSHAgentAuth and set paths and boolean however you needed

this would only break configs that had noop config of cfg.sshAgentAuth for some security.pam.services.name, but not config.security.pam.enableSSHAgentAuth, which would be inert

2020-10-31 18:08 UTC, jkarlson commented
This new revision would be my preferred solution (apart from completely dropping config.security.pam.enableSSHAgentAuth completely and the entry on sudo module).

It's to my understanding perfectly backwards compatible apart from people who have only enableSSHAgentAuth = true specified and expect it to have no effect, which is just silly.

2020-11-30 18:14 UTC, Infinisil requested changes
Other than my suggestion and the fact that it needs to be rebased, this looks good to me!

However I'd like @risson to take a look at this one as well, because they've just started reworking the pam module entirely in https://github.com/NixOS/nixpkgs/pull/105319

2020-11-30 18:14 UTC, Infinisil commented on nixos/modules/security/sudo.nix
> +    security.pam.services.sudo = lib.optionalAttrs config.security.pam.enableSSHAgentAuth { sshAgentAuth = true; };
I think it probably makes more sense to move this definition to the `pam.nix` module instead, then option definition and use is in the same file.

2020-11-30 18:17 UTC, jkarlson commented
I see this commit has been sufficiently fixed in ba1fa0c60406a21b933f5cb1625e80ac0da84f50 for me.

2020-11-30 18:19 UTC, closed without merging

2020-11-30 18:19 UTC, jkarlson commented
already fixed by another commit