pdf2htmlEx: remove
NixOS/nixpkgs pull request #102525
Opened 2020-11-02 20:14 UTC by freezeboy

This package is broken since 2018 and the project itself is abandonned
upstream since 2017, so there is no hope to see it evolve

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-02 22:25 UTC, IvarWithoutBones requested changes
LGTM :+1:

2020-11-03 02:20 UTC, SuperSandro2000 approved these changes

2020-11-03 10:05 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/272

2020-11-03 10:23 UTC, danieldk requested changes

2020-11-03 10:23 UTC, danieldk commented on pkgs/top-level/all-packages.nix
> -  pdf2htmlEX = callPackage ../tools/typesetting/pdf2htmlEX { };
Could you please add this attribute to `top-level/aliases.nix`?

2020-11-03 12:17 UTC, danieldk approved these changes

2020-11-03 12:17 UTC, merged

2025-09-12 05:32 UTC, Cryolitia commented
note: re-introduce its fork in https://github.com/NixOS/nixpkgs/pull/433307