miniscript: init at unstable-20201104
NixOS/nixpkgs pull request #102808
Opened 2020-11-04 16:17 UTC by RaghavSood

###### Motivation for this change

Miniscript is a tool to compile and work with the miniscript Bitcoin policy language.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-04 16:23 UTC, SuperSandro2000 commented on pkgs/applications/blockchains/miniscript/default.nix
> +  version = "unstable-20201104";
```suggestion
  version = "unstable-2020-11-04";
```

2020-11-04 16:23 UTC, SuperSandro2000 commented on pkgs/applications/blockchains/miniscript/default.nix
> +    mkdir -p $out/bin
You should execute the pre and post install hooks.

2020-11-04 16:23 UTC, SuperSandro2000 commented on pkgs/applications/blockchains/miniscript/default.nix
> +    description = "Miniscript is a language for writing (a subset of) Bitcoin Scripts in a structured way, enabling analysis, composition, generic signing and more.";
This is description is quite long. It should probably be moved to ``longDescription`` and a shorter one for the short should be used.

2020-11-04 16:38 UTC, RaghavSood commented
@SuperSandro2000 appreciate the quick review, updated

2020-11-05 02:08 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 102808` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>miniscript</li>
  </ul>
</details>

2020-11-06 00:57 UTC, SuperSandro2000 commented
Fails to build on darwin with:

```
building
build flags: SHELL=/nix/store/7kzamk0abm530kkr5v106hnc3cfscwkc-bash-4.4-p23/bin/bash
g++ -O3 -g0 -Wall -std=c++11 -march=native -flto -Ibitcoin bitcoin/util/strencodings.cpp bitcoin/util/spanparsing.cpp bitcoin/script/script.cpp bitcoin/script/miniscript.cpp compiler.cpp main.cpp -o miniscript
/nix/store/7kzamk0abm530kkr5v106hnc3cfscwkc-bash-4.4-p23/bin/bash: g++: command not found
make: *** [Makefile:5: miniscript] Error 127
```

2021-01-18 17:42 UTC, SuperSandro2000 requested changes
also please mark it broken on darwin.

2021-01-18 17:42 UTC, SuperSandro2000 commented on pkgs/applications/blockchains/miniscript/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-05-02 08:35 UTC, closed without merging