hsetroot: Update 1.0.2 →  1.0.5
NixOS/nixpkgs pull request #103465
Opened 2020-11-11 16:25 UTC by SCOTT-HAMILTON

###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/103457

###### Things done
Upgraded hsetroot to 1.0.5

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-11 18:01 UTC, srhb commented
Builds and runs for me. Some notes on the source change: Plenty of repos already use this version according to repology, including FreeBSD ports, Arch, etc. LGTM.

2020-11-11 18:01 UTC, srhb approved these changes

2020-11-11 23:09 UTC, jonringer reviewed
To comply with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) please have the commit message name be of the format
```
<pkg-name>: <subject-line>
```
for more examples, please look at https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

in your case, the commit message should be:
```
hsetroot: 1.0.2 -> 1.0.5
```

otherwise LGTM

2020-11-12 14:11 UTC, AndersonTorres commented
Please, don't use fancy special characters as "→" in commit messages. 

Use `->` instead.

2020-11-12 15:25 UTC, SCOTT-HAMILTON commented
Sorry, I have this bad habit to use some fancy characters as those are easily accessible with my keyboard layout.

2020-11-13 01:12 UTC, AndersonTorres requested changes
Amend the commit message.

2020-11-13 20:03 UTC, AndersonTorres requested changes
The word "Update" in the commit message is redundant. Drop it.

`hsetrooot: 1.0.2 -> 1.0.5`

2020-11-15 07:48 UTC, NinjaTrappeur commented
Result of `nixpkgs-review pr 103465` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hsetroot</li>
  </ul>
</details>

2020-11-15 07:48 UTC, NinjaTrappeur approved these changes

2020-11-15 07:48 UTC, merged

2020-11-15 07:48 UTC, NinjaTrappeur commented
Thanks :)