timescaledb: Move unfree library to separate package to fix the license
NixOS/nixpkgs pull request #103507
Opened 2020-11-11 22:27 UTC by chkno

###### Motivation for this change
Fix the timescaledb license.
Make the Free/Libre/Open Source timescaledb build available.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
    43361488 → 43005136
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

timescaledb maintainers: @volth @marsam

2020-11-12 06:41 UTC, nora-puchreiner requested changes
Please, make the choice explicit.
Defaulting to any one of the choices is counter-intuitive
One might expect unfree version by default having `nixpkgs.config.allowUnfree = true`

2020-11-12 06:41 UTC, nora-puchreiner commented on pkgs/servers/sql/postgresql/ext/timescaledb.nix
> +, build-unfree-tsl ? false }:
```suggestion
, build-unfree-tsl }:
```

2020-11-12 06:41 UTC, nora-puchreiner commented on pkgs/servers/sql/postgresql/packages.nix
>      timescaledb = super.callPackage ./ext/timescaledb.nix { };
```suggestion
    timescaledb = super.callPackage ./ext/timescaledb.nix {  build-unfree-tsl = false; };
```

2020-11-12 08:26 UTC, chkno commented
> Please, make the choice explicit.
> Defaulting to any one of the choices is counter-intuitive
> One might expect unfree version by default having `nixpkgs.config.allowUnfree = true`

Done.  Thanks!

2020-11-24 09:07 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 103507` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>postgresqlPackages.timescaledb (postgresql11Packages.timescaledb)</li>
    <li>postgresqlPackages.timescaledb-tsl (postgresql11Packages.timescaledb-tsl)</li>
  </ul>
</details>

2020-11-24 09:13 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 103507` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>postgresqlPackages.timescaledb (postgresql11Packages.timescaledb)</li>
    <li>postgresqlPackages.timescaledb-tsl (postgresql11Packages.timescaledb-tsl)</li>
  </ul>
</details>

2020-12-02 03:40 UTC, closed without merging