plex: 1.20.3.3483 -> 1.20.3.3517
NixOS/nixpkgs pull request #103917
Opened 2020-11-15 16:34 UTC by badmutex

###### Motivation for this change
New version released.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-17 20:59 UTC, bachp requested changes
Version 1.20.5.3600 is out.

2020-11-17 20:59 UTC, bachp commented on pkgs/servers/plex/raw.nix
> +  version = "1.20.4.3517-ab5e1197c";
```suggestion
  version = "1.20.5.3600-47c0d9038";
```

2020-11-17 20:59 UTC, bachp commented on pkgs/servers/plex/raw.nix
> +    sha256 = "0sw33xy7v2vdg8w099813x8gmdkmfa3j9pfwkc8si9gi238l5rpq";
```suggestion
    sha256 = "0vqsmmgqcvvhxiqaw87qz9fdisyf9smp6ab069dz3nq39x7n9na0";
```

2020-11-18 14:58 UTC, bachp approved these changes

2020-11-18 15:40 UTC, badmutex commented
thanks @bachp!

at this point someone with commit access needs to merge as i don't have those rights.

2020-11-18 18:44 UTC, LnL7 approved these changes

2020-11-18 18:45 UTC, merged