svkbd: init at 0.2.1
NixOS/nixpkgs pull request #104147
Opened 2020-11-18 07:35 UTC by sikmir

###### Motivation for this change
**[svkbd](https://tools.suckless.org/x/svkbd/)** - Simple Virtual Keyboard.

###### Things done
- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-18 19:27 UTC, SuperSandro2000 requested changes

2021-01-18 19:27 UTC, SuperSandro2000 commented on pkgs/tools/X11/svkbd/default.nix
> +assert stdenv.lib.assertOneOf "layout" layout [ "mobile-intl" "mobile-plain" "de" "en" "ru" "sh" "arrows" ];
```suggestion
assert lib.assertOneOf "layout" layout [ "mobile-intl" "mobile-plain" "de" "en" "ru" "sh" "arrows" ];
```

2021-01-18 19:27 UTC, SuperSandro2000 commented on pkgs/tools/X11/svkbd/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-03-16 22:40 UTC, rmcgibbo approved these changes
Built on x86_64-linux and tested the `svkbd-mobile-intl` binary. Works fine.

2021-04-05 22:33 UTC, merged

2021-04-05 23:03 UTC, sternenseemann commented
Reverted in c8870b462514eb27bac22379de26a4a1b7f22589. 

`svkbd` was already added in 2fab56654ba1017ef81695d0c8e83edc55045c7e and that package is even better arguably. Most significantly though having the `svkbd` attribute defined twice in `all-packages.nix` causes a failure at parse time.

Curiously, @SuperSandro2000 even merged both PRs.

2021-04-05 23:04 UTC, SuperSandro2000 commented
I was just victim of stale ofborg checks. :P

> Curiously, @SuperSandro2000 even merged both PRs.

I can't remember all PRs I have merged. There are just to many.