cre2: fix src
NixOS/nixpkgs pull request #104127
Opened 2020-11-18 04:07 UTC by RaghavSood

###### Motivation for this change

#104048

Upstream seems to have retagged to remove the `v` from `v0.3.0`

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-18 22:49 UTC, prusnak requested changes

2020-11-18 22:49 UTC, prusnak commented on pkgs/development/libraries/cre2/default.nix
> +    rev = "${version}";
```suggestion
    rev = version;
```

2020-11-18 22:50 UTC, prusnak requested changes

2020-11-20 13:53 UTC, prusnak commented
Sorry, I just now noticed that the latest is `v0.3.6` which uses "v" in the tag again - can you please update the package to latest instead?

2020-11-20 14:04 UTC, RaghavSood commented
You are right, but interestingly the hash didn't change with 0.3.6 - continues to build locally too, but I'll wait for Hydra as a sanity check

2020-11-20 14:38 UTC, prusnak commented
> You are right, but interestingly the hash didn't change with 0.3.6

That means the sources were not fetched and the old version was used (because you did not change the hash).

1. Replace all digits in hash with "0".
2. Run the build again to obtain the new hash.

2020-11-20 14:45 UTC, RaghavSood commented
I assumed so too, but doing so didn't help - `nix-prefetch-url` also returns the same hash

```
[raghav@t580:~]$ nix-prefetch-url https://github.com/marcomaggi/cre2/archive/v0.3.6.tar.gz --unpack
unpacking...
[0.0 MiB DL]
path is '/nix/store/g8xr4zdzq8n1i4ndp59yi2rdsc0k50p0-v0.3.6.tar.gz'
1h9jwn6z8kjf4agla85b5xf7gfkdwncp0mfd8zwk98jkm8y2qx9q
```

Using a fake hash also results in the same:

```
[raghav@ch-misc:~/nixpkgs/nixpkgs]$ nix-build -A cre2
these derivations will be built:
  /nix/store/98yrcpigphm5lb949037yykl2s3q08hi-source.drv
  /nix/store/gz8s44j6xc34bjp2wxhlpskz5c0p659f-cre2-0.3.6.drv
building '/nix/store/98yrcpigphm5lb949037yykl2s3q08hi-source.drv'...

trying https://github.com/marcomaggi/cre2/archive/v0.3.6.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123  100   123    0     0    523      0 --:--:-- --:--:-- --:--:--   523
100 51119    0 51119    0     0  97741      0 --:--:-- --:--:-- --:--:-- 97741
unpacking source archive /build/v0.3.6.tar.gz
hash mismatch in fixed-output derivation '/nix/store/azixcya4gnmmc8fgp15ggfj7dqwi836c-source':
  wanted: sha256:0000000000000000000000000000000000000000000000000000
  got:    sha256:1h9jwn6z8kjf4agla85b5xf7gfkdwncp0mfd8zwk98jkm8y2qx9q
cannot build derivation '/nix/store/gz8s44j6xc34bjp2wxhlpskz5c0p659f-cre2-0.3.6.drv': 1 dependencies couldn't be built
error: build of '/nix/store/gz8s44j6xc34bjp2wxhlpskz5c0p659f-cre2-0.3.6.drv' failed
```

2020-11-20 14:50 UTC, prusnak commented
That's indeed weird. Maybe the old `v0.3.0` was assigned to the same commit? Anyway, the change works now so all is good to go.

2020-11-20 14:50 UTC, prusnak approved these changes

2020-11-23 08:21 UTC, merged