meme: 2017-09-10 -> 2020-05-28
NixOS/nixpkgs pull request #104398
Opened 2020-11-20 18:08 UTC by fgaz

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-23 10:24 UTC, SuperSandro2000 commented
Can you mention in the commit that you changed it to buildGoModule?

2020-11-23 10:30 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 104398` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>meme</li>
  </ul>
</details>

2020-12-02 13:39 UTC, fgaz commented
@SuperSandro2000 done

2020-12-03 09:40 UTC, SuperSandro2000 requested changes

2020-12-03 09:40 UTC, SuperSandro2000 commented on pkgs/applications/graphics/meme/default.nix
>    pname = "meme-unstable";
```suggestion
  pname = "meme";
```

2020-12-03 09:40 UTC, SuperSandro2000 commented on pkgs/applications/graphics/meme/default.nix
> +  version = "2020-05-28";
```suggestion
  version = "unstable-2020-05-28";
```

2020-12-03 10:06 UTC, fgaz commented on pkgs/applications/graphics/meme/default.nix
>    pname = "meme-unstable";
It was fixed in master, I rebased.

2020-12-03 10:06 UTC, fgaz commented on pkgs/applications/graphics/meme/default.nix
> +  version = "2020-05-28";
Same

2020-12-07 11:34 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 104398` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>meme</li>
  </ul>
</details>

2020-12-07 17:26 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 104398` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>meme</li>
  </ul>
</details>

2020-12-07 17:32 UTC, merged