lib.lists.unique: Switch from recursive function to using a fold
NixOS/nixpkgs pull request #104744
Opened 2020-11-24 05:24 UTC by adisbladis

###### Motivation for this change

This improves performance by ~30-40% for smaller test cases and makes larger cases where my laptop would OOM pass in seconds.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-24 13:11 UTC, Infinisil requested changes

2020-11-24 13:11 UTC, Infinisil commented on lib/lists.nix
>        []
We can also remove this if condition now, because `foldl' f [] [] == []`

2020-11-24 13:21 UTC, Infinisil approved these changes
Looking good!

2020-11-24 13:55 UTC, merged

2020-12-17 15:11 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/tweag-nix-dev-update-5/10560/1