[REVIEW] codefresh: init at 0.73.21
NixOS/nixpkgs pull request #105183
Opened 2020-11-27 22:40 UTC by jshcmpbll

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-27 22:53 UTC, SuperSandro2000 requested changes
Is there a reason why the global nodePackages aren't used?

2020-11-27 22:55 UTC, jshcmpbll commented
@SuperSandro2000  Just unfamiliarity to it. Ill look into it.

2020-11-29 20:46 UTC, jshcmpbll commented
[build.log](https://github.com/NixOS/nixpkgs/files/5612839/build.log)

Errors I am getting when I try to build. :(

2020-12-04 20:54 UTC, jshcmpbll commented
@SuperSandro2000 Following the steps to add a package to nodePackages there were a lot of changes to node-packages.nix. Is that expected and does that mean I have to then validate every nodepackage works after this change?

2020-12-04 23:35 UTC, SuperSandro2000 commented
> @SuperSandro2000 Following the steps to add a package to nodePackages there were a lot of changes to node-packages.nix. Is that expected and does that mean I have to then validate every nodepackage works after this change?
> 

Yeah, we need to update them all at once and no you don't need to test every package.

2021-01-18 00:12 UTC, SuperSandro2000 commented
@jshcmpbll please fix the merge conflict and eval error.

2021-01-18 00:13 UTC, SuperSandro2000 requested changes

2021-01-18 00:13 UTC, SuperSandro2000 commented on pkgs/development/node-packages/composition.nix
> +    inherit (pkgs) stdenv python2 utillinux runCommand writeTextFile;
Please revert this.

2021-01-18 00:13 UTC, SuperSandro2000 commented on pkgs/development/node-packages/node-env.nix
> +{stdenv, nodejs, python2, utillinux, libtool, runCommand, writeTextFile}:
Please revert this.

2021-01-18 00:13 UTC, SuperSandro2000 commented on pkgs/development/node-packages/node-env.nix
> +        ++ stdenv.lib.optional (stdenv.isLinux) utillinux
Please revert this.

2021-01-18 00:13 UTC, SuperSandro2000 commented on pkgs/development/node-packages/node-env.nix
> +          ++ stdenv.lib.optional (stdenv.isLinux) utillinux
Please revert this.

2021-01-18 00:13 UTC, SuperSandro2000 commented on pkgs/development/node-packages/node-env.nix
> +      buildInputs = [ python nodejs ] ++ stdenv.lib.optional (stdenv.isLinux) utillinux ++ buildInputs;
Please revert this.

2021-01-18 00:13 UTC, SuperSandro2000 commented on pkgs/tools/admin/codefresh/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-01-18 00:13 UTC, SuperSandro2000 commented on pkgs/tools/admin/codefresh/default.nix
> +{ yarn2nix-moretea, fetchFromGitHub, stdenv }:
```suggestion
{ yarn2nix-moretea, fetchFromGitHub, lib }:
```

2021-01-19 15:45 UTC, SuperSandro2000 commented
@jshcmpbll we have a merge conflict again. Can you give me a message on IRC when you resolved the merge conflict so that it does not happen again?

2021-01-20 09:43 UTC, jshcmpbll commented
@SuperSandro2000 Merge conflict is fixed.

I dont know node well enough to trouble shoot this error I'm getting. I might see if a coworker of mine can help out but if you have any thoughts id appreciate it. My assumption was that it was just missing `faye-websocket` but even after adding that to `node-packages.json` I still get that error.

```npm WARN read-shrinkwrap This version of npm is compatible with lockfileVersion@1, but npm-shrinkwrap.json was generated for lockfileVersion@0. I'll try to do my best with it!
npm ERR! code ENOTCACHED
npm ERR! request to https://registry.npmjs.org/faye-websocket failed: cache mode is 'only-if-cached' but no cached response available.

npm ERR! A complete log of this run can be found in:
npm ERR!     /build/.npm/_logs/2021-01-20T09_39_31_341Z-debug.log

builder for '/nix/store/3v6g3l1kh86f2r9whk81dbhch4q9z552-node_codefresh-0.74.4.drv' failed with exit code 1
error: build of '/nix/store/3v6g3l1kh86f2r9whk81dbhch4q9z552-node_codefresh-0.74.4.drv' failed```

2021-01-20 13:58 UTC, SuperSandro2000 commented
Did you try regenerating the node packages nix file?

2021-01-26 20:58 UTC, jshcmpbll commented
> Did you try regenerating the node packages nix file?

@SuperSandro2000 
I did, it just looks like this package has some weird and unique dependencies I wasn't aware of.  I have a workaround in place right now.. let me know if thats a valid solution - (the change to default.nix). If not im going to connect with some people over IRC and see if anyone can assist

2021-02-09 05:15 UTC, jshcmpbll commented
@SuperSandro2000 Please review when you have time

2021-02-09 08:49 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 105183` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
</ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>netlify-cli: log <a href="https://termbin.com/izhh">https://termbin.com/izhh</a></li>
  </ul>
</details>
<details>
<summary>
49 packages built:
</summary>
<ul>
<li>antora</li>
<li>bitwarden-cli</li>
<li>castnow</li>
<li>epgstation</li>
<li>fast-cli</li>
<li>flood</li>
<li>joplin</li>
<li>lessc</li>
<li>mastodon-bot</li>
<li>mirakurun</li>
<li>pm2</li>
<li>postcss-cli</li>
<li>pulp</li>
<li>python37Packages.batchspawner</li>
<li>python37Packages.dockerspawner</li>
<li>python37Packages.jupyterhub</li>
<li>python37Packages.jupyterhub-ldapauthenticator</li>
<li>python37Packages.jupyterhub-systemdspawner</li>
<li>python37Packages.jupyterhub-tmpauthenticator</li>
<li>python37Packages.oauthenticator</li>
<li>python38Packages.batchspawner</li>
<li>python38Packages.dockerspawner</li>
<li>python38Packages.jupyterhub</li>
<li>python38Packages.jupyterhub-ldapauthenticator</li>
<li>python38Packages.jupyterhub-systemdspawner</li>
<li>python38Packages.jupyterhub-tmpauthenticator</li>
<li>python38Packages.oauthenticator</li>
<li>python39Packages.batchspawner</li>
<li>python39Packages.dockerspawner</li>
<li>python39Packages.jupyterhub</li>
<li>python39Packages.jupyterhub-ldapauthenticator</li>
<li>python39Packages.jupyterhub-systemdspawner</li>
<li>python39Packages.jupyterhub-tmpauthenticator</li>
<li>python39Packages.oauthenticator</li>
<li>redoc-cli</li>
<li>sloc</li>
<li>styx</li>
<li>thelounge</li>
<li>vimPlugins.coc-git</li>
<li>vimPlugins.coc-json</li>
<li>vimPlugins.coc-metals</li>
<li>vimPlugins.coc-prettier</li>
<li>vimPlugins.coc-rust-analyzer</li>
<li>vimPlugins.coc-stylelint</li>
<li>vimPlugins.coc-vetur</li>
<li>vscode-extensions.matklad.rust-analyzer</li>
<li>vscode-extensions.ms-python.vscode-pylance</li>
<li>vscode-extensions.vadimcn.vscode-lldb</li>
<li>wasm-text-gen</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.jupyterhub:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern ''npm', 'run', 'lessc', '--'' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python38Packages.jupyterhub:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern ''npm', 'run', 'lessc', '--'' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>
python39Packages.jupyterhub:
<details>

Please consider this feature to be alpha.

A substituteInPlace with an unmatched pattern got detected:
```
substituteStream(): WARNING: pattern ''npm', 'run', 'lessc', '--'' doesn't match anything in file 'setup.py'
```

Please check the offending substituteInPlace for typos or changes in source.
</details>

2021-02-13 10:40 UTC, jshcmpbll commented
....

2021-02-14 05:32 UTC, SuperSandro2000 commented
I am talking about the netlify build failure. The other things can be safely ignored.

> netlify-cli: log termbin.com/izhh

2021-02-20 15:40 UTC, closed without merging