Convert Emacs documentation from XML DocBook to Commonmark
NixOS/nixpkgs pull request #105300
Opened 2020-11-29 00:04 UTC by AndersonTorres

https://github.com/NixOS/nixpkgs/issues/105254

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-29 06:08 UTC, taku0 commented on doc/builders/packages/index.xml
> + <xi:include href="emacs.section..xml" />
```suggestion
 <xi:include href="emacs.section.xml" />
```

2020-11-30 18:30 UTC, AndersonTorres commented
@ryantm ping!

2020-11-30 18:44 UTC, ryantm requested changes

2020-11-30 18:44 UTC, ryantm commented on doc/builders/packages/emacs.section.md
> +```
```suggestion
```nix
```

2020-11-30 19:19 UTC, AndersonTorres commented on doc/builders/packages/emacs.section.md
> +```
done

2020-11-30 19:35 UTC, ryantm approved these changes

2020-11-30 19:35 UTC, ryantm commented
@AndersonTorres looks good thanks!

2020-11-30 19:35 UTC, merged

2020-12-04 00:33 UTC, jtojnar commented on doc/builders/packages/emacs.section.md
> +## Configuring Emacs
Looks like anchor is missing here.

2020-12-04 02:42 UTC, ryantm commented on doc/builders/packages/emacs.section.md
> +## Configuring Emacs
Thanks for fixing it!