backblaze: 2.0.2 -> 2.1.0
NixOS/nixpkgs pull request #105390
Opened 2020-11-29 18:48 UTC by freezeboy

###### Motivation for this change

Update b2 tool to latest release and some deps

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-29 19:33 UTC, ryantm requested changes

2020-11-29 19:33 UTC, ryantm commented on pkgs/development/tools/backblaze-b2/default.nix
> +  # Nosetests/pytest are failing on this release
You should say which release, so we don't keep this forever.

2020-11-30 01:11 UTC, SuperSandro2000 requested changes

2020-11-30 01:11 UTC, SuperSandro2000 commented on pkgs/development/tools/backblaze-b2/default.nix
> +  doCheck = false;
```suggestion
  disabledTests = [
    "test_files_headers"
    "test_integration"
  ];
```

2020-11-30 01:11 UTC, SuperSandro2000 commented on pkgs/development/tools/backblaze-b2/default.nix
>      class-registry
```suggestion
    phx-class-registry
```

2020-11-30 01:11 UTC, SuperSandro2000 commented on pkgs/development/python-modules/phx-class-registry/default.nix
> +  doCheck = false;
```suggestion
  disabledTests = [
    "test_branding"
    "test_happy_path"
    "test_len"
  ];
```

2020-11-30 01:12 UTC, SuperSandro2000 commented
And there is already #104807 which does not fail ofborg. Closing this one. Next time please do a quick search.

2020-11-30 01:12 UTC, closed without merging