gnomeExtensions.caffeine: 2020-03-13 -> 37
NixOS/nixpkgs pull request #106254
Opened 2020-12-07 15:14 UTC by rmcgibbo

###### Motivation for this change
Upgrade gnome-shell-extension caffeine to latest release (from ~14 days ago), no longer requires getting the unstable branch.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-12-07 15:28 UTC, SuperSandro2000 requested changes

2020-12-07 15:28 UTC, SuperSandro2000 commented on pkgs/desktops/gnome-3/extensions/caffeine/default.nix
> +    rev = "v37";
```suggestion
    rev = "v${version}";
```

2020-12-07 15:34 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 106254` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gnomeExtensions.caffeine</li>
  </ul>
</details>

2020-12-07 15:35 UTC, emanueleperuffo approved these changes

2020-12-07 19:39 UTC, emanueleperuffo approved these changes

2020-12-08 04:12 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 106254` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gnomeExtensions.caffeine</li>
  </ul>
</details>

2020-12-08 04:13 UTC, merged