sbc: 1.4 -> 1.5
NixOS/nixpkgs pull request #106450
Opened 2020-12-09 14:02 UTC by gebner

###### Motivation for this change

New upstream version.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-12-09 15:59 UTC, gebner commented
Fails on arm :-(

2021-01-18 11:25 UTC, SuperSandro2000 requested changes

2021-01-18 11:25 UTC, SuperSandro2000 commented on pkgs/development/libraries/sbc/default.nix
>    meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-01-18 11:25 UTC, SuperSandro2000 commented on pkgs/development/libraries/sbc/default.nix
>    nativeBuildInputs = [ pkgconfig ];
```suggestion
  nativeBuildInputs = [ pkg-config ];
```

2021-01-18 11:25 UTC, SuperSandro2000 commented on pkgs/development/libraries/sbc/default.nix
>  { stdenv, fetchurl, pkgconfig, libsndfile }:
```suggestion
{ stdenv, fetchurl, pkg-config, libsndfile }:
```

2021-01-18 11:25 UTC, SuperSandro2000 commented
Please target master.

2023-01-14 01:27 UTC, wegank commented
Superseded by #184673.

2023-01-14 01:27 UTC, closed without merging