ledger-live-desktop: fix missing gschema settings
NixOS/nixpkgs pull request #106711
Opened 2020-12-12 06:16 UTC by TheAncientGoat

Similar issue to #89089

###### Motivation for this change
This package crashes on systems without gtk dependencies otherwise, with a ```(ledger-live-desktop:12516): GLib-GIO-ERROR **: 14:14:57.402: No GSettings schemas are installed on the system ``` error otherwise

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-11 23:12 UTC, asymmetric commented
@TheAncientGoat [this](https://github.com/NixOS/nixpkgs/pull/104668/files#diff-79504e99066ccb817007c83ef128705bf2aa35fc97dee10e57d3241f61b364a5R27) actually fixed it for me.

2021-01-12 14:01 UTC, TheAncientGoat commented
> @TheAncientGoat [this](https://github.com/NixOS/nixpkgs/pull/104668/files#diff-79504e99066ccb817007c83ef128705bf2aa35fc97dee10e57d3241f61b364a5R27) actually fixed it for me.

If I'm not mistaken, that's what the wrapGAppsHook according to the discussion here https://github.com/NixOS/nixpkgs/issues/89089#issuecomment-649151165 (and my fix worked - at least for me)

Not sure if the one approach is better than the other, but as there hasn't been any activity on the issue https://github.com/NixOS/nixpkgs/issues/106733 - not sure if I can push this one over the line

2021-07-11 14:24 UTC, asymmetric commented
Still relevant

2021-12-10 18:54 UTC, andresilva commented
@TheAncientGoat any reason why we can't take this PR out of draft so we can merge it? AFAIK the approach in this PR of using `wrapGAppsHook` solves the problem and is the correct solution (https://nixos.org/manual/nixpkgs/stable/#ssec-gnome-hooks). I would approve this PR.

2021-12-11 00:15 UTC, TheAncientGoat commented
@andresilva - no reason on my end besides not being able to find reviewers; will take it out of draft if you're happy with it, thanks

2021-12-12 12:11 UTC, andresilva commented
/marvin opt-in
/status needs_reviewer

2021-12-12 12:25 UTC, andresilva requested changes
Sorry, I only actually looked at the patch now. I'm not sure how this is supposed to be working, you have just defined a variable `extraPkgs` which isn't used anywhere. I think `wrapGAppsHook` cannot be used by the app image builder since it needs to be defined as a native build input. So I suggest you update the PR to instead do the same as [here](https://github.com/NixOS/nixpkgs/pull/104668/files#diff-79504e99066ccb817007c83ef128705bf2aa35fc97dee10e57d3241f61b364a5R25-R28) as suggested by @asymmetric.

2021-12-13 07:02 UTC, TheAncientGoat commented
I'll have a look - not currently using the package because my ledger wasn't being detected anyhow; will give it another go

2021-12-13 08:41 UTC, andresilva commented
The ledger not being detected was fixed recently. Make sure you update nixpkgs before trying again.

2021-12-13 12:13 UTC, TheAncientGoat commented
Hmm, just tested it out while using Gnome - file manager seems to work as expected, don't know if it's a KDE only thing. As I'm using Gnome at the moment I don't have the time to change desktops and triage - if no one else is experiencing the issue I guess we can close?

2021-12-13 13:01 UTC, andresilva commented
I am using i3 and also could not replicate the issue. I used to have the `XDG_DATA_DIRS` fix on my zsh profile since this issue also affected other apps, but I don't anymore and didn't have problems opening the file picker on Ledger Live. @asymmetric if you can't replicate it either then we can probably close this.

2022-03-08 20:18 UTC, closed without merging