pythonPackages.ciscomobilityexpress: init at 0.3.9
NixOS/nixpkgs pull request #107095
Opened 2020-12-17 12:33 UTC by uvNikita

###### Motivation for this change

Fixes import module error when using `cisco_mobility_express` home assistant component: https://github.com/NixOS/nixpkgs/blob/b83e5b85bd373bafb292f56b3869799ebef90ba8/pkgs/servers/home-assistant/component-packages.nix#L116

@mweinelt 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-12-17 15:40 UTC, mweinelt requested changes
Thanks, LGTM.

One nit: The component-packages update is a change to the home-assistant package, and should therefore be in a separate commit `home-assistant: update component-packages`.

2020-12-18 16:34 UTC, uvNikita commented
@mweinelt thanks for the review!

I added commit that updates `component-packages.nix` file.

2020-12-18 17:08 UTC, mweinelt commented
Result of `nixpkgs-review pr 107095` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.ciscomobilityexpress</li>
    <li>python38Packages.ciscomobilityexpress</li>
    <li>python39Packages.ciscomobilityexpress</li>
  </ul>
</details>

2020-12-18 17:08 UTC, mweinelt approved these changes

2020-12-18 17:08 UTC, merged