nixos/gdm: add option to configure monitors.xml
NixOS/nixpkgs pull request #107850
Opened 2020-12-28 22:20 UTC by isobit

This option allows users to configure GDM to respect custom monitor
setups, such as those generated by GNOME in `~/.config/monitors.xml`.
See this section of the ArchWiki GDM page regarding monitor settings:
https://wiki.archlinux.org/index.php/GDM#Setup_default_monitor_settings

The GDM home directory in NixOS is a tmpfs at `/run/gdm`, so the config
is persisted in a similar way to the pulseaudio config, by adding a
systemd tmpfiles rule to symlink it from a generated file written to the
nix store.

Relevant discourse thread: https://discourse.nixos.org/t/gdm-monitor-configuration/6356

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-06 22:54 UTC, isobit commented
I changed the type from `lines` to `nullOr str` to use `null` as the zero value as well as avoid issues with concatenation merging since the option value is expected to be a full XML file. I'm a nixpkgs newbie so definitely let me know if there's a more appropriate type or pattern to use for something like this!

Tested and confirmed working using `nixos-rebuild test -I nixpkgs=<path to my nixpkgs checkout>`.

One other thing I wanted to note is that removing a definition for this option (after setting it and building at least once) won't have an effect until the system is restarted since the rebuild will only remove the tmpfile rule, which doesn't result in the config being unlinked until a fresh tmpfs is created on reboot. Open to suggestions if there's an approach that avoids this or if I should make a note of that behavior somehow.

2021-01-07 21:24 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/gdm-monitor-configuration/6356/3

2021-05-18 12:36 UTC, justinas commented
Prematurely: not stale. I'm interested in this.

2021-09-17 20:39 UTC, tomberek commented
@isobit it would be unexpected for a reboot is necessary unless it it documented. For this reason the tmpfile.rules system is not ideal. Often you'll see an ExecPreStart populating this directory with content. You'll also see the usage of serviceConfig.StateDirectory.

2021-09-18 12:08 UTC, caevee approved these changes
Tested on nixos-21.05 and fixed my issue. Backport would be appreciated.

2021-09-18 17:39 UTC, caevee commented
@NixOS/gnome

2021-09-18 17:41 UTC, fufexan commented
@NixOS/gnome can this be merged with tomberek's recommendations?

2021-09-27 03:04 UTC, VergeDX reviewed
LGTM

2021-11-15 16:44 UTC, rofrol commented
Any news on that?

2022-05-21 17:06 UTC, sandangel commented
Hi, may I ask could we merge this PR?

2022-05-21 17:55 UTC, jtojnar requested changes
Sorry, I feel that this is too niche a feature to warrant a NixOS option. It does not really add anything over users customizing the contents of `/run/gdm/.config/monitors.xml` themselves, other that somewhat obscure documentation that already understaffed GNOME team would have to end up maintaining.

By the way, if you use home-manager through NixOS configuration, you can just do:

```nix
  home-manager.users.gdm = {
    home.file.".config/monitors.xml".text = ''
      <monitors version="2">
        …
      </monitors>
    '';
  };
```

Though note that `gdm` will have to be in `nix.settings.allowed-users` NixOS option in order for the home-manager activation systemd service to be able to run. This is true unless you override the NixOS option, since the option defaults to `[ "*" ]`.

2022-05-21 19:07 UTC, isobit commented
My thought was that the `/run/gdm` home setup was enough of a quirk of the NixOS GDM setup that it would be helpful to have an option that handles the symlinking, if users wanted a system level config (as opposed to `~/.config/monitors.xml`). If you feel strongly though I'm fine closing this and keeping it in my personal config.

2022-05-23 07:26 UTC, sandangel commented
I have the file already in `~/.config/monitors.xml`. But the display was not correct at GDM login screen. that's why I would prefer an option to config GDM resolution.

This is what I have ended up with:

```
  systemd.tmpfiles.rules = [
    ''f+ /run/gdm/.config/monitors.xml - gdm gdm - <monitors version="2"><configuration><logicalmonitor><x>0</x><y>0</y><scale>2</scale><primary>yes</primary><monitor><monitorspec><connector>Virtual-1</connector><vendor>unknown</vendor><product>unknown</product><serial>unknown</serial></monitorspec><mode><width>4112</width><height>2572</height><rate>60.005760192871094</rate></mode></monitor></logicalmonitor></configuration></monitors>''
  ];
```

Using the symlink approach, I still see the link under root user, that's why I use `f+` to have that under `gdm` user.

2023-01-31 02:26 UTC, closed without merging