prometheus-smokeping-prober: init at 0.3.1 from git
NixOS/nixpkgs pull request #107891
Opened 2020-12-29 17:46 UTC by lukegb

###### Motivation for this change

Add https://github.com/SuperQ/smokeping_prober, a Prometheus exporter similar to blackbox exporter but which manages its own ping schedule (and thus is more suitable for continuous monitoring, as a replacement for smokeping).

This uses the version at HEAD from git since a release hasn't been cut in a while and we'd ideally like the recent improvements to go-ping.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-12-29 17:51 UTC, lukegb commented
Result of `nixpkgs-review pr 107891` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>prometheus-smokeping-prober</li>
  </ul>
</details>

2020-12-29 17:58 UTC, lukegb commented
Result of `nixpkgs-review pr 107891` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>prometheus-smokeping-prober</li>
  </ul>
</details>

2020-12-29 18:19 UTC, urbas approved these changes
Tried it out on my Prometheus instance and smokeping worked perfectly. :+1: 

Also, successfully executed tests:
```
$ nix-build -vA pkgs.nixosTests.prometheus-exporters.smokeping
...
test script finished in 11.12s
```

2020-12-29 18:54 UTC, SuperSandro2000 requested changes

2020-12-29 18:54 UTC, SuperSandro2000 commented on pkgs/servers/monitoring/prometheus/smokeping-prober.nix
> +    "-ldflags=${varFlags}"
Please add -s -w to ldflags.

2021-01-01 04:32 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107891` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package blacklisted:
</summary>
<ul>
<li>tests.nixos-functions.nixos-test</li>
</ul>
</details>
<details>
<summary>
1 package built:
</summary>
<ul>
<li>prometheus-smokeping-prober</li>
</ul>
</details>

2021-01-01 04:41 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 107891` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>prometheus-smokeping-prober</li>
  </ul>
</details>

2021-01-01 15:08 UTC, WilliButz approved these changes

2021-01-01 15:08 UTC, merged