new-session-manager: init at 1.4.0
NixOS/nixpkgs pull request #107997
Opened 2020-12-30 22:38 UTC by 6AA4FD

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-12-31 01:44 UTC, SuperSandro2000 requested changes
Please squash the package related commits together.

2020-12-31 01:44 UTC, SuperSandro2000 commented on pkgs/applications/audio/new-session-manager/default.nix
> +  };
```suggestion
  src = fetchFromGitHub {
          owner = "linuxaudio";
          repo = "new-session-manager";
          rev = "v${version}";
          sha256 = "PqOv4tx3NLxL2+GWIUVgL72EQYMyDPIMrAkyby3TZ+0=";
  };

  nativeBuildInputs = [ meson pkg-config ninja ];

  buildInputs = [ liblo libjack2 fltk ];

  hardeningDisable = [ "format" ];
```

2020-12-31 02:54 UTC, 6AA4FD commented
> Please squash the package related commits together.

@SuperSandro2000 done!

2020-12-31 04:58 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +  _6AA4FD = {
Please put this into a separate commit with the message ``maintainers: add _6AA4FD``.

2020-12-31 04:58 UTC, SuperSandro2000 commented on pkgs/applications/audio/new-session-manager/default.nix
> +          sha256 = "PqOv4tx3NLxL2+GWIUVgL72EQYMyDPIMrAkyby3TZ+0=";
```suggestion
    owner = "linuxaudio";
    repo = "new-session-manager";
    rev = "v${version}";
    sha256 = "PqOv4tx3NLxL2+GWIUVgL72EQYMyDPIMrAkyby3TZ+0=";
```

2020-12-31 04:58 UTC, SuperSandro2000 commented on pkgs/applications/audio/new-session-manager/default.nix
> +
```suggestion
  hardeningDisable = [ "format" ];

```

2020-12-31 05:41 UTC, 6AA4FD commented
@SuperSandro2000 done!

2020-12-31 07:45 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107997` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>new-session-manager</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

new-session-manager.log:
<details>
`gpl3` is a deprecated license, check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/audio/new-session-manager/default.nix:24:5:

```
   |
24 |     license = licenses.gpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>

2020-12-31 11:30 UTC, 6AA4FD commented
@SuperSandro2000 done!

2020-12-31 23:57 UTC, SuperSandro2000 commented
@6AA4FD Please fix the merge conflict.

2021-01-01 03:23 UTC, 6AA4FD commented
@SuperSandro2000 done!

2021-01-01 05:00 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107997` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>new-session-manager</li>
</ul>
</details>

2021-01-01 06:14 UTC, siraben approved these changes

2021-01-01 18:52 UTC, merged