python/r2pipe: Fix build
NixOS/nixpkgs pull request #107973
Opened 2020-12-30 15:11 UTC by aszlig

Regression introduced by 6556711c87f42e064ba01deb4c1e0aa917be8d66.

The string start and end quoting styles have changed in the upstream source code between version 1.4.2 and version 1.5.3, so the `checkPhase` now results in the following error:

```
  ======================================================================
  ERROR: native (unittest.loader._FailedTest)
  ----------------------------------------------------------------------
  ImportError: Failed to import test module: native
  Traceback (most recent call last):
    File ".../unittest/loader.py", line 154, in loadTestsFromName
      module = __import__(module_name)
    File "/build/r2pipe-1.5.3/r2pipe/native.py", line 113, in <module>
      class RCore(Structure):  # 1
    File "/build/r2pipe-1.5.3/r2pipe/native.py", line 125, in RCore
      cmd_str, r_core_cmd_str = register(
    File "/build/r2pipe-1.5.3/r2pipe/native.py", line 108, in register
      method = WrappedRMethod(cname, args, ret)
    File "/build/r2pipe-1.5.3/r2pipe/native.py", line 53, in __init__
      r2 = r2lib()
    File "/build/r2pipe-1.5.3/r2pipe/native.py", line 27, in r2lib
      raise ImportError("No native r_core library")
  ImportError: No native r_core library
```

2020-12-30 16:22 UTC, thiagokokada commented
Result of `nixpkgs-review pr 107973` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.r2pipe</li>
    <li>python38Packages.r2pipe</li>
    <li>python39Packages.r2pipe</li>
  </ul>
</details>

2020-12-30 16:24 UTC, thiagokokada reviewed
Can you fix the commit message please? It should be `python3Packages.r2pipe: fix build`.

2020-12-30 18:18 UTC, SuperSandro2000 requested changes
Please change the commit and PR title to ``pythonPackages.r2pipe: Fix build``

2020-12-31 02:33 UTC, aszlig commented
Whoops, sorry, wasn't that awake anymore.

2020-12-31 02:38 UTC, thiagokokada commented
Result of `nixpkgs-review pr 107973` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>python37Packages.r2pipe</li>
    <li>python38Packages.r2pipe</li>
    <li>python39Packages.r2pipe</li>
  </ul>
</details>

2020-12-31 02:38 UTC, thiagokokada approved these changes

2020-12-31 23:30 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review. If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 107973` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.r2pipe</li>
<li>python38Packages.r2pipe</li>
<li>python39Packages.r2pipe</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.r2pipe.log:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.r2pipe.log:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python39Packages.r2pipe.log:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add \'doCheck = false;'` and a `pythonImportsCheck`.

</details>

2020-12-31 23:30 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 107973` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>python37Packages.r2pipe</li>
    <li>python38Packages.r2pipe</li>
    <li>python39Packages.r2pipe</li>
  </ul>
</details>

2021-01-09 09:10 UTC, aszlig commented
@SuperSandro2000: These warnings are all unrelated and not in scope for this PR (if we're going to start improving the package, we're speaking about a complete refactor), so can you please re-review for the scope of this PR?

2021-01-10 00:01 UTC, jonringer approved these changes
LGTM

still an improvement to nixpkgs :)

```
https://github.com/NixOS/nixpkgs/pull/107973

3 packages built:
python37Packages.r2pipe python38Packages.r2pipe python39Packages.r2pipe
```

2021-01-10 00:01 UTC, merged

2021-05-01 07:05 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/github-block-evasion-is-not-acceptable/12763/67