systemd-confinment: move to /var/empty
NixOS/nixpkgs pull request #108028
Opened 2020-12-31 09:41 UTC by Mic92

bind mounting directories into the nix-store breaks nix commands.
In particular it introduces character devices that are not supported
by nix-store as valid files in the nix store. Use `/var/empty` instead
which is designated for these kind of use cases. We won't create any
files beause of the tmpfs mounted.

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-12-31 10:23 UTC, aszlig commented
> In particular it introduces character devices that are not supported by nix-store as valid files in the nix store.

Since those are within the `tmpfs` as you point out, can you give a specific example where this is a problem?

2020-12-31 10:52 UTC, Mic92 commented
> > In particular it introduces character devices that are not supported by nix-store as valid files in the nix store.
> 
> Since those are within the `tmpfs` as you point out, can you give a specific example where this is a problem?

It becomes a problem if the service tries to use nix commands. i.e. I use systemd confinement to run my ci runner in a chroot: https://github.com/Mic92/dotfiles/blob/279819a5d20d281555ab679bae471faa4875eec6/nixos/eve/modules/drone.nix#L73
Also it is a bit faster when building since it saves one derivation and we create this directory with systemd.

2020-12-31 11:19 UTC, aszlig commented
> It becomes a problem if the service tries to use nix commands. i.e. I use systemd confinement to run my ci runner in a chroot: https://github.com/Mic92/dotfiles/blob/279819a5d20d281555ab679bae471faa4875eec6/nixos/eve/modules/drone.nix#L73

Okay, granted, this is indeed a problem, for example if you want to use it to confine Hydra.

> It is general unsound to mount stuff into store paths because it can also confuse nix-store when checking the integrity of derivations or even worse garbage collection.

Those bind mounts are private mounts, so applications not sharing the same namespace are unaffected.

> Also it is a bit faster when building since it saves one derivation and we create this directory with systemd.

Originally I was even [re-using the merged systemd units](https://github.com/headcounter/shabitica/blob/3a3a88d8148234dd3eeec221d3823dd7724d6530/modules/imageproxy.nix#L131) so it would be as "fast" but probably would confuse everyone, so I eventually went for a dedicated empty store path.

The reason why I refrained use `/var/empty` or even temporary paths was that I wanted to make sure that the path is read-only in the first place, even for the root user to prevent accidentally dropping files in that directory. Given that the service will fail whenever the `tmpfs` couldn't be mounted, we can however reasonably assume that something like that will never happen.

2020-12-31 11:20 UTC, aszlig approved these changes

2020-12-31 11:21 UTC, aszlig commented
@ofborg test systemd-confinement

2020-12-31 11:40 UTC, aszlig requested changes
Temporarily blocked, since the test currently fails and the status by ofborg isn't very visible here.

2020-12-31 14:09 UTC, SuperSandro2000 commented
```
--- /nix/store/nfyjixayfsfrr79gx7drijlvkfbvx7db-nixos-test-driver-systemd-confinement/test-script       2020-12-31 11:21:39.900680 +0000
+++ /nix/store/nfyjixayfsfrr79gx7drijlvkfbvx7db-nixos-test-driver-systemd-confinement/test-script       2020-12-31 11:21:40.426911 +0000
@@ -13,11 +13,12 @@
         "chroot-exec ls -l /etc",
         "chroot-exec ls -l /run",
         "chroot-exec chown 65534 /bin",
     )
     machine.succeed(
-        'test "$(chroot-exec id -u)" = 0', "chroot-exec chown 0 /bin",
+        'test "$(chroot-exec id -u)" = 0',
+        "chroot-exec chown 0 /bin",
     )
```

2020-12-31 14:12 UTC, aszlig commented
@SuperSandro2000: That's not the main issue because the test fails with the APIVFS changes of the last systemd update.

2020-12-31 14:54 UTC, aszlig commented
@Mic92: Just ran a working version of the test with this change and it floods the logs with `Failed to create directory at /var/empty/usr: Operation not permitted`. While it didn't create that directory even when running as root, the fact that `systemd` even *tries* to create it is something why we should be paranoid also add an additional check in the test to make sure `/var/empty` stays that way.

Now the only ugliness is the (non-fatal) failure message, which for some reason does not occur when mounting the `tmpfs` inside a store path.

2020-12-31 22:14 UTC, Mic92 commented
> @Mic92: Just ran a working version of the test with this change and it floods the logs with `Failed to create directory at /var/empty/usr: Operation not permitted`. While it didn't create that directory even when running as root, the fact that `systemd` even _tries_ to create it is something why we should be paranoid also add an additional check in the test to make sure `/var/empty` stays that way.
> 
> Now the only ugliness is the (non-fatal) failure message, which for some reason does not occur when mounting the `tmpfs` inside a store path.

How about mounting it read-only?

2021-07-01 06:07 UTC, Mic92 commented
@ofborg test systemd-confinement

2021-07-01 06:09 UTC, Mic92 commented
Tests are working now!

2021-07-01 06:09 UTC, merged