[20.09] Backport zulip: 5.4.3 → 5.5.0
NixOS/nixpkgs pull request #108073
Opened 2020-12-31 19:44 UTC by otavio

(cherry picked from commit bfabe2a17a12d4792ba1a30860f67a9bf6288966)

###### Motivation for this change

Update 20.09 package

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-12-31 19:48 UTC, otavio commented
Result of `nixpkgs-review pr 108073` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zulip</li>
  </ul>
</details>

2020-12-31 19:52 UTC, thiagokokada commented
Result of `nixpkgs-review pr 108073` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zulip</li>
  </ul>
</details>

2020-12-31 19:52 UTC, thiagokokada approved these changes

2021-01-02 19:43 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/322

2021-01-08 19:28 UTC, AndersonTorres requested changes
@otavio 

Don't use fancy non-ASCII characters in the commit message. Use the good old `->`.

2021-01-24 14:59 UTC, otavio commented
This is a cherry pick, so I don't think we should change the original commit.

2021-01-26 01:36 UTC, merged