droidcam: init at 1.6
NixOS/nixpkgs pull request #108346
Opened 2021-01-03 20:27 UTC by suhr

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-03 20:57 UTC, lukegb commented
This doesn't seem to build - https://github.com/NixOS/nixpkgs/pull/108346/checks?check_run_id=1640694049

2021-01-03 21:03 UTC, suhr commented
Yes, that's why it's marked as a draft.

2021-01-03 21:04 UTC, lukegb commented
D'oh, missed that.

2021-01-03 21:41 UTC, SuperSandro2000 requested changes

2021-01-03 21:41 UTC, SuperSandro2000 commented on pkgs/applications/video/droidcam/default.nix
> +    substituteInPlace linux/src/droidcam.c --replace "/opt/droidcam-icon.png" "$out/share/icons/hicolor/droidcam.png"
```suggestion
    substituteInPlace linux/src/droidcam.c \
      --replace "/opt/droidcam-icon.png" "$out/share/icons/hicolor/droidcam.png"
```

2021-01-03 22:37 UTC, collares commented on pkgs/applications/video/droidcam/default.nix
> +  '';
Needs `makeFlagsArray+=("USBMUXD=$(pkg-config --libs --cflags libusbmuxd-2.0)")` too.

2021-01-03 23:03 UTC, collares commented on pkgs/applications/video/droidcam/default.nix
> +  '';
```suggestion
    makeFlagsArray+=("USBMUXD=$(pkg-config --libs --cflags libusbmuxd-2.0)")
  '';
```

2021-01-04 01:30 UTC, jtojnar commented on pkgs/applications/video/droidcam/default.nix
> +    license = licenses.gpl2;
`gpl2` is unclear, use `gpl2Plus` or `gpl2Only`. See https://discourse.nixos.org/t/lib-licenses-gpl3-co-are-now-deprecated/8206 for more details.

2021-01-04 11:58 UTC, suhr commented
Now it compiles and runs.

2021-01-06 00:13 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 108346` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>droidcam</li>
</ul>
</details>

2021-01-06 00:16 UTC, merged