python3Packages.idna: 2.10 -> 3.1
NixOS/nixpkgs pull request #108664
Opened 2021-01-07 12:47 UTC by mweinelt

###### Motivation for this change

https://github.com/kjd/idna/releases/tag/v3.0
https://github.com/kjd/idna/releases/tag/v3.1

Enable tests using pytestCheckHook.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-07 12:55 UTC, mweinelt commented
\rebase-staging

2021-01-07 12:55 UTC, mweinelt commented
/rebase-staging

2021-01-07 15:22 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 108664` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>python3Packages.idna</li>
  </ul>
</details>

2021-01-07 15:22 UTC, SuperSandro2000 approved these changes

2021-01-08 10:22 UTC, FRidh requested changes
This needs to be part of a batch upgrade so it gets tested properly.

2021-01-10 13:03 UTC, SuperSandro2000 commented
> This needs to be part of a batch upgrade so it gets tested properly.

The 3.0 mostly removed python 2.7 support. Should be safe to merge.

2021-03-08 18:50 UTC, mweinelt commented
This change was apparently forgotten during the last python-unstable cycle.

2021-03-24 16:16 UTC, mweinelt commented
86be5aa0ee799a81dfa5e5c31a50921206f0b89f
2bc98c071262d4a0687217a820ff4a314cd6cc59

2021-03-24 16:16 UTC, closed without merging