Remove ambient systemctl dependency from nixos-rebuild
NixOS/nixpkgs pull request #108879
Opened 2021-01-09 18:02 UTC by kreisys

###### Motivation for this change

We wanted to use `nixos-rebuild --target-host` to deploy NixOS configurations from a flake to remote NixOS machines.
However, this fails from both Darwin and non-systemd distros due to the code below which relies on an ambient systemctl being available:
```bash
# If the Nix daemon is running, then use it.  This allows us to use
# the latest Nix from Nixpkgs (below) for expression evaluation, while
# still using the old Nix (via the daemon) for actual store access.
# This matters if the new Nix in Nixpkgs has a schema change.  It
# would upgrade the schema, which should only happen once we actually
# switch to the new configuration.
# If --repair is given, don't try to use the Nix daemon, because the
# flag can only be used directly.
if [ -z "$repair" ] && systemctl show nix-daemon.socket nix-daemon.service | grep -q ActiveState=active; then
    export NIX_REMOTE=${NIX_REMOTE-daemon}
fi
```
As far as I could gather, the `NIX_REMOTE` environment variable is pretty much unnecessary nowadays (it's not even set in any of my environments, NixOS or otherwise) as nix uses other heuristics to determine whether to use the daemon or not. Simply removing this part seems to have resolved our issue without breaking anything else and this seems like a valid use-case.

###### Things done

Remove aforementioned par

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @manveru

2021-01-09 19:30 UTC, SuperSandro2000 requested changes
Please change the title and commit message to ``nixos-rebuild: Remove ambient systemctl dependency``

2021-02-28 10:40 UTC, manveru approved these changes

2021-03-04 06:17 UTC, Mic92 commented
Do you know when this switch to heuristic happened? Just to make sure it does not affect people that downgrade nix.

2021-03-04 08:56 UTC, kreisys commented
> Do you know when this switch to heuristic happened? Just to make sure it does not affect people that downgrade nix.

I just trusted @matthewbauer: https://github.com/NixOS/nix/commit/92f461e4f46b595e3712b41c30b8403905dd8673

2021-03-07 12:12 UTC, Mic92 commented
Ok. Three years sounds fair enough.

2021-03-07 12:13 UTC, Mic92 commented
I think it does not actually matter because nixos-rebuild builds its own nix anyway.

2021-03-07 14:09 UTC, merged