nixos/droidcam: init
NixOS/nixpkgs pull request #109267
Opened 2021-01-13 11:25 UTC by suhr

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-13 11:29 UTC, SuperSandro2000 commented on nixos/modules/programs/droidcam.nix
> +    enable = mkEnableOption "DroidCam client";
Please add a description.

2021-01-13 11:32 UTC, suhr commented on nixos/modules/programs/droidcam.nix
> +    enable = mkEnableOption "DroidCam client";
`mkEnableOption` already provides a description: https://github.com/NixOS/nixpkgs/blob/master/lib/options.nix#L92

2021-01-13 12:24 UTC, aanderse reviewed
Have not tested, but generally LGTM :+1:

Should we add a NixOS test to make sure the kernel module stuff is all working (ie. the app doesn't crash)? Maybe? I'm not sure if that provides much value or not...

2021-01-13 12:24 UTC, aanderse commented on nixos/modules/programs/droidcam.nix
> +  options.services.tox-node = {
typo

2021-03-06 13:18 UTC, bachp requested changes
The module workes after I applied the requested changes.

2021-03-06 13:18 UTC, bachp commented on nixos/modules/programs/droidcam.nix
> +  options.services.droidcam = {
```suggestion
  options.programs.droidcam = {
```

I think this fits better under `programs`

2021-03-06 13:18 UTC, bachp commented on nixos/modules/programs/droidcam.nix
> +  config = lib.mkIf cfg.enable {
```suggestion
  config = lib.mkIf config.programs.droidcam.enable {
```
`cfg` is not defined.

2021-03-07 19:56 UTC, bachp approved these changes

2021-03-12 22:36 UTC, bachp commented
@suhr please squash the commits together

2021-04-05 19:32 UTC, merged