dune_2: 2.7.1 -> 2.8.0
NixOS/nixpkgs pull request #109325
Opened 2021-01-13 22:44 UTC by anmonteiro

###### Motivation for this change
https://github.com/ocaml/dune/releases/tag/2.8.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-13 22:46 UTC, anmonteiro commented
This release includes https://github.com/ocaml/dune/pull/3973, which is especially important to support `ocaml-ng.ocamlPackages_4_12`

2021-01-14 07:04 UTC, SuperSandro2000 commented on pkgs/development/tools/ocaml/dune/2.nix
> -    (fetchpatch {
Please remove fetchpatch from inputs.

2021-01-14 09:59 UTC, vbgl commented
@GrahamcOfBorg build ocamlPackages.mdx

2021-01-14 10:03 UTC, vbgl requested changes
This breaks `mdx`.

2021-01-14 12:15 UTC, marsam commented
dune 2.8.1 was released https://github.com/ocaml/dune/releases/tag/2.8.1

2021-01-14 12:29 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review which does not build all packages (e.g. lumo, tensorflow or pytorch)
If you find some bugs or got suggestions for further things to search or run please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 109325` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>dune-release: log was empty</li>
  </ul>
</details>
<details>
<summary>
39 packages built:
</summary>
<ul>
<li>acgtk</li>
<li>beluga</li>
<li>dot-merlin-reader</li>
<li>dune_2</li>
<li>eff</li>
<li>flow</li>
<li>framac</li>
<li>fstar</li>
<li>google-drive-ocamlfuse</li>
<li>jackline</li>
<li>libbap</li>
<li>libguestfs</li>
<li>liquidsoap</li>
<li>obelisk</li>
<li>ocaml-crunch</li>
<li>ocaml-top</li>
<li>ocamlformat (ocamlformat_0_15_0)</li>
<li>ocamlformat_0_11_0</li>
<li>ocamlformat_0_12</li>
<li>ocamlformat_0_13_0</li>
<li>ocamlformat_0_14_0</li>
<li>ocamlformat_0_14_1</li>
<li>ocamlformat_0_14_2</li>
<li>ocamlformat_0_14_3</li>
<li>opa</li>
<li>orpie</li>
<li>patdiff</li>
<li>python37Packages.bap</li>
<li>python37Packages.guestfs</li>
<li>python38Packages.bap</li>
<li>python38Packages.guestfs</li>
<li>python39Packages.bap</li>
<li>python39Packages.guestfs</li>
<li>reason</li>
<li>satysfi</li>
<li>stog</li>
<li>vagrant</li>
<li>virt-top</li>
<li>why3</li>
</ul>
</details>

2021-01-14 16:19 UTC, anmonteiro commented
@vbgl the mdx failure looks like a broken formatter test, not an actual failure.

2021-01-18 23:06 UTC, anmonteiro commented
@vbgl  Upgraded mdx too which now builds correctly

2021-01-19 07:29 UTC, vbgl commented
Thanks. Merged the `mdx` update as 3ffc05e1dba2874cbb30b1ebc0e3dfe531e06249.

2021-01-19 14:15 UTC, merged