itch: init at version v1.24.0
NixOS/nixpkgs pull request #110012
Opened 2021-01-19 20:26 UTC by Anderssorby

Add setup for itch.io desktop client. From issue #90233

###### Motivation for this change

Attempting to add the itch.io desktop client via the itch-setup utility. See issue #90233.

###### Things done

Tried to base it on other electron app expressions without success. 

Currently it is failing, but I'm hoping someone knows how to fix it.

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ x ] NixOS (fails)
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-19 20:37 UTC, SuperSandro2000 commented on pkgs/games/itch/default.nix
> +  name = "itch-setup-${version}";
```suggestion
stdenv.mkDerivation rec {
  pname = "itch-setup";
  version = "1.24.0";
```

2021-01-19 20:37 UTC, SuperSandro2000 commented on pkgs/games/itch/default.nix
> +    url = "https://github.com/itchio/itch-setup/archive/${version}.tar.gz";
Please use fetchFromGitHub.

2021-01-19 20:37 UTC, SuperSandro2000 commented on pkgs/games/itch/default.nix
> +  ];
```suggestion
  buildInputs = [
    nodejs go glib
  ];
```

2021-01-19 20:37 UTC, SuperSandro2000 commented on pkgs/games/itch/default.nix
> +    license = licenses.mit;
Missing maintainers and platforms.

2021-01-19 20:37 UTC, SuperSandro2000 commented on pkgs/games/itch/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-01-22 08:43 UTC, SuperSandro2000 requested changes

2021-01-22 08:43 UTC, SuperSandro2000 commented on pkgs/games/itch/default.nix
> +stdenv.mkDerivation rec {
```suggestion

stdenv.mkDerivation rec {
```

2021-01-22 08:43 UTC, SuperSandro2000 commented on pkgs/games/itch/default.nix
> +{ stdenv
```suggestion
{ stdenv
, lib
```

2021-01-22 08:43 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  itch = callPackage ../games/itch/default.nix {  };
```suggestion
  itch = callPackage ../games/itch/default.nix { };
```

2021-11-01 00:16 UTC, wackbyte commented
any updates on this?

2022-02-11 01:31 UTC, davidak commented
This PR is superseded by https://github.com/NixOS/nixpkgs/pull/157921.

2022-02-11 01:31 UTC, closed without merging