pytest-order: init at 0.9.3
NixOS/nixpkgs pull request #110141
Opened 2021-01-20 11:12 UTC by jacg

###### Motivation for this change

Package not yet available in nixpkgs

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-20 11:34 UTC, dotlambda requested changes
"Ran 0 tests in 0.000s"

2021-01-20 11:34 UTC, dotlambda commented on pkgs/development/python-modules/pytest-order/default.nix
> +    description = "pytest plugin that allows you to customize the order in which your tests are run";
```suggestion
    description = "Pytest plugin that allows you to customize the order in which your tests are run";
```
https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

2021-01-20 11:35 UTC, dotlambda commented
Will this be used in some other package you're about to create a pull request for? Then it would be nicer to do a single pull request for all of them.

2021-01-20 11:37 UTC, dotlambda requested changes
Commit message and pull request title should start with `pythonPackages`.

2021-01-20 12:07 UTC, jacg commented
> Will this be used in some other package you're about to create a pull request for? 

No. It's used in the tests of some projects I've come across, but those are unlikely to be submitted to `nixpkgs`.

2021-01-20 12:15 UTC, dotlambda commented
> "Ran 0 tests in 0.000s"

You need to run the tests. If they are not distributed on PyPI, you can use `fetchFromGitHub`.

2021-01-20 12:33 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110141` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages built:
</summary>
<ul>
<li>python37Packages.pytest-order</li>
<li>python38Packages.pytest-order</li>
<li>python39Packages.pytest-order</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

python37Packages.pytest-order:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add `'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python38Packages.pytest-order:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add `'doCheck = false;'` and a `pythonImportsCheck`.

</details>
python39Packages.pytest-order:
<details>

Zero tests run by pytest got detected: 'Ran 0 tests in 0.000s'
You have the following options to fix this:
  - Tell pytest(CheckHook) where to find the tests included in the package
  - Check if the GitHub Repo contains tests but they are not shipped with Pypi. If so please switch to `fetchFromGitHub`.
  - If the Packages does not contain any tests add `'doCheck = false;'` and a `pythonImportsCheck`.

</details>

2021-01-20 15:47 UTC, dotlambda requested changes

2021-01-20 15:47 UTC, dotlambda commented on pkgs/development/python-modules/pytest-order/default.nix
> +    pytest-mock
Only `pytest` should be in `propagatedBuildInputs`: https://github.com/mrbean-bremen/pytest-order/blob/v0.9.3/setup.py#L30
The rest should be put into `checkInputs`.

2021-01-20 19:14 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review which is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 110141` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>python37Packages.pytest-order: log <a href="https://termbin.com/j4cd">https://termbin.com/j4cd</a></li>
<li>python38Packages.pytest-order: log <a href="https://termbin.com/8ro2">https://termbin.com/8ro2</a></li>
<li>python39Packages.pytest-order: log <a href="https://termbin.com/8yoy">https://termbin.com/8yoy</a></li>
  </ul>
</details>

2021-01-27 14:50 UTC, jacg commented
There is apparently one pending requested change here, but I cannot find any that requested changes that are unresolved.

2021-01-27 21:05 UTC, jacg commented
After brief discussion with the maintainer of `pytest-order`, a new release (0.9.4) has been made which includes the tests. I have reverted back to using `fetchPypi` and the tests now pass.

2021-01-27 21:25 UTC, dotlambda commented on pkgs/development/python-modules/pytest-order/default.nix
> +  checkPhase = false;
```suggestion
```

2021-01-28 10:17 UTC, merged