nixos/tests/usbguard: init
NixOS/nixpkgs pull request #110389
Opened 2021-01-21 20:18 UTC by tnias

###### Motivation for this change

The usbguard module had no tests before. And I like to have tests for stuff.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-21 21:06 UTC, iblech commented
Awesome! I cannot test (lacking a functioning qemu), but LGTM!

2021-01-22 01:34 UTC, stigtsp requested changes
Tested via `nix-build nixos/tests/usbguard.nix`, looks good!

Could you add `passthru.tests = nixosTests.usbguard;` to `pkgs/os-specific/linux/usbguard/default.nix` as well?

2021-01-22 20:53 UTC, tnias commented
> Could you add `passthru.tests = nixosTests.usbguard;` to `pkgs/os-specific/linux/usbguard/default.nix` as well?

Added to the commit.

2021-01-23 01:03 UTC, stigtsp commented
@GrahamcOfBorg build usbguard.tests

2021-01-23 01:49 UTC, stigtsp approved these changes
Looks good to me, thanks for the contribution!

2021-01-23 01:50 UTC, merged