mark: init at version 3.5
NixOS/nixpkgs pull request #110996
Opened 2021-01-28 07:12 UTC by rguevara84

* A tool for syncing your markdown documentation with Atlassian
  Confluence pages

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-28 08:07 UTC, SuperSandro2000 requested changes

2021-01-28 08:07 UTC, SuperSandro2000 commented on pkgs/tools/text/mark/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  vendorSha256 = "1hvizcg5b3y2qgjiw77rb795xz9w1dzr3b8q2ji48ihll27g9f0m";

  meta = with lib; {
```

2021-01-28 08:07 UTC, SuperSandro2000 commented on pkgs/tools/text/mark/default.nix
> +{ stdenv, buildGoModule, fetchFromGitHub }:
```suggestion
{ lib, stdenv, buildGoModule, fetchFromGitHub }:
```

2021-01-28 08:27 UTC, SuperSandro2000 commented on pkgs/tools/text/mark/default.nix
> +    maintainers = with maintainers; [ rguevara84 ];
Please add yourself to maintainers.nix according to the contribution guide.

2021-01-28 15:19 UTC, kalbasit reviewed
Looking at their Makefile, there's a way to embed the version in the binary by passing `-X main.version=${version}` as ldflags. I'm afk so I don't have the syntax at hand, you can grep nixpkgs for ldflags in files that also has buildGoModule to find an example; Once you get it done, ask mark to display its version to double check that it worked.

2021-01-28 15:19 UTC, kalbasit commented on pkgs/tools/text/mark/default.nix
> +    rev    = "${version}";
```suggestion
    rev    = version;
```

2021-01-28 15:19 UTC, kalbasit commented on pkgs/tools/text/mark/default.nix
> +{ lib, stdenv, buildGoModule, fetchFromGitHub }:
```suggestion
{ lib, buildGoModule, fetchFromGitHub }:
```

I don't believe it's used.

2021-01-28 23:11 UTC, SuperSandro2000 requested changes

2021-01-28 23:11 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +  rguevara84 = {
Please put this into a separate commit with the message ``maintainers: add rguevara84``.

2021-01-30 01:10 UTC, kalbasit commented
@rguevara84 can you squash the init with the pr feedback. At the end you should have two commit, one for adding you as a maintainer and the other for mark init.

2021-01-30 02:39 UTC, kalbasit commented
@GrahamcOfBorg build mark

2021-01-30 02:48 UTC, kalbasit approved these changes

2021-01-30 02:52 UTC, kalbasit commented
```
[nix-shell:~/.cache/nixpkgs-review/pr-110996]$ ./results/mark/bin/mark --version
3.5
```

Looks good.

@SuperSandro2000 PTAL.

2021-01-30 17:53 UTC, merged