nixos/vsftpd: add userlist type
NixOS/nixpkgs pull request #111441
Opened 2021-01-31 11:29 UTC by Scriptkiddi

###### Motivation for this change
#76184

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-01-31 11:54 UTC, yorickvP commented
This individual change is fine, but userlistFile should be filled in from this option as something stronger than a default, to prevent careless overriding. Something like 
`services.vsftpd.userlistFile = lib.mkIf (cfg.userlist != []) (pkgs.writeText "userlist" (concatMapStrings (x: "${x}\n") cfg.userlist);`?

2021-02-05 07:21 UTC, Scriptkiddi commented
@yorickvP like this?

2021-02-06 07:07 UTC, cole-h commented on nixos/modules/services/networking/vsftpd.nix
> +
```suggestion
```

2021-02-06 07:07 UTC, cole-h commented on nixos/modules/services/networking/vsftpd.nix
> +    services.vsftpd.userlistFile = lib.mkIf (cfg.userlist != []) (pkgs.writeText "userlist" (concatMapStrings (x: "${x}\n") cfg.userlist));
Should these be combined?

```
services.vsftpd = {
  userlist = ...;
  userlistFile = ...;
};

2021-04-18 11:58 UTC, yorickvP approved these changes

2021-04-18 12:00 UTC, yorickvP requested changes
I believe the assertion won't work, since we override userListFile in this package if someone sets userList. However, the check will still happen without the assertion since you wouldn't be able to merge in another userListFile.

2022-03-16 06:18 UTC, closed without merging