scientifica: init at v2.1
NixOS/nixpkgs pull request #111569
Opened 2021-02-01 14:38 UTC by fortuneteller2k

[Scientifica](https://github.com/NerdyPepper/scientifica) is a tall, condensed, bitmap font largely based on creep

###### Motivation for this change

Add scientifica font

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-01 14:50 UTC, SuperSandro2000 commented on pkgs/data/fonts/scientifica/default.nix
> +  version = "v2.1";
Versions in nix do not start with the v letter that GitHub suggests to use for versions.

```suggestion
  version = "2.1";
```

2021-02-01 14:50 UTC, SuperSandro2000 commented on pkgs/data/fonts/scientifica/default.nix
> +    url = "https://github.com/NerdyPepper/scientifica/releases/latest/download/${pname}-${version}.tar";
```suggestion
    url = "https://github.com/NerdyPepper/scientifica/releases/latest/download/${pname}-v${version}.tar";
```

2021-02-01 14:50 UTC, SuperSandro2000 commented on pkgs/data/fonts/scientifica/default.nix
> +stdenv.mkDerivation rec {
Fonts are usually no derivation but just a download with a post phase. You should find some other fonts that do it like this.

2021-02-01 14:51 UTC, SuperSandro2000 requested changes

2021-02-01 14:51 UTC, SuperSandro2000 commented on pkgs/data/fonts/scientifica/default.nix
> +
```suggestion

```

2021-02-03 19:25 UTC, neonfuz commented
@fortuneteller2k Why the change from pname and version to just name, and version in a let block? I think nixpkgs prefers pname, you should change that back.

Also I like this font, what is the status of this, waiting on a re-review?

2021-02-03 19:27 UTC, fortuneteller2k commented
> @fortuneteller2k Why the change from pname and version to just name, and version in a let block? I think nixpkgs prefers pname, you should change that back.
> 
> 
> 
> Also I like this font, what is the status of this, waiting on a re-review?

It's waiting on a re-review.

I used `name` because `fetchurl` doesnt let me use `pname` and `version`.

2021-02-03 19:35 UTC, neonfuz commented
Oh yeah my bad, I didn't realize the change to fetchurl, makes sense.

2021-02-03 20:13 UTC, neonfuz commented
I tested this package, it works well. Added to fonts.fonts in system config and it was usable.

2021-02-04 17:40 UTC, merged