Update Haskell package set to Stackage Nightly 2021-02-02 (plus other fixes)
NixOS/nixpkgs pull request #111678
Opened 2021-02-02 20:10 UTC by peti

This PR is test-built by Hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. I'll fix up the remaining errors and merge it on Friday, 2021-02-05 20:00 +01:00. You can watch this live on Twitch at https://www.twitch.tv/peti343.

2021-02-02 20:11 UTC, SuperSandro2000 requested changes

2021-02-02 20:11 UTC, SuperSandro2000 commented on pkgs/development/compilers/ghc/8.10.3.nix
> +  ] ++ stdenv.lib.optionals stdenv.isDarwin [
```suggestion
  ] ++ lib.optionals stdenv.isDarwin [
```

2021-02-02 20:17 UTC, SuperSandro2000 commented
@ofborg eval

2021-02-05 22:45 UTC, merged

2021-02-11 13:16 UTC, maralorn commented
@peti Have you already opened a new PR?

2021-02-12 12:19 UTC, peti commented
Now I have. Tonight, we'll merge https://github.com/NixOS/nixpkgs/pull/112893.