pkgs.tools.security: Update sequoia to the latest release
NixOS/nixpkgs pull request #112162
Opened 2021-02-06 16:09 UTC by nbraud

No change in the libraries, but the sq CLI tool was brought to v0.23.0,
which is it's first release “which is meant for general use”.

2021-02-06 16:16 UTC, nbraud commented
Sorry the version number is awkward, but upstream's scheme just doesn't fit neatly: Sequoia-the-library and its `sq` CLI tool has their own version number scheme, but live in the same repo and are built by the same derivation.

2021-02-06 18:56 UTC, alyssais commented
Since Rust programs using sequoia will bring in their own copy, rather than using this package, I think this package is only really useful for the command line tool. So we should probably use the version of the CLI, rather than the library.

2021-02-06 19:01 UTC, SuperSandro2000 requested changes
Please change the PR title and commit to ``sequoia: 1.0.0 -> 1.0.0-sq0.23.0``

2021-02-06 19:12 UTC, nbraud commented
> Please change the PR title and commit to `sequoia: 1.0.0 -> 1.0.0-sq0.23.0`

Done.  I had already amended the commit message after re-reading `CONTRIBUTING.md` though

2021-02-06 20:27 UTC, alyssais commented
I notice there’s an sq/v0.24.0 tag — should we use that instead?

2021-02-06 20:29 UTC, nbraud commented
> I notice there’s an sq/v0.24.0 tag — should we use that instead?

Thanks, not sure how I missed that  >_>'

2021-02-06 20:47 UTC, alyssais approved these changes

2021-02-06 20:47 UTC, nbraud commented
@alyssais Done, and even added a comment explaining the situation.

2021-02-07 00:49 UTC, merged

2021-02-07 18:36 UTC, minijackson commented
I'm a bit late to the party, sorry about that.

> Since Rust programs using sequoia will bring in their own copy, rather than using this package, I think this package is only really useful for the command line tool. So we should probably use the version of the CLI, rather than the library.

I'm not completely sure about that, the package provides Python bindings. Right now, it doesn't matter much as they do not seem versioned, and they are a [work in progress](https://gitlab.com/sequoia-pgp/sequoia/-/tree/main/ffi/lang/python). But that makes me a bit confused for the future, since multi-output packages don't support having different versions.

Maybe when the bindings are stable, we will need to make a completely separate package for them.

2021-02-17 20:58 UTC, alyssais commented
> I'm a bit late to the party, sorry about that.
>
>> Since Rust programs using sequoia will bring in their own copy,
>> rather than using this package, I think this package is only really
>> useful for the command line tool. So we should probably use the
>> version of the CLI, rather than the library.
>
> I'm not completely sure about that, the package provides Python
> bindings. Right now, it doesn't matter much as they do not seem
> versioned, and they are a [work in
> progress](https://gitlab.com/sequoia-pgp/sequoia/-/tree/main/ffi/lang/python). But
> that makes me a bit confused for the future, since multi-output
> packages don't support having different versions.
>
> Maybe when the bindings are stable, we will need to make a completely
> separate package for them.

Oh, I didn't realise there were also Python bindings.  I think it
depends what upstream decides to do about versioning them.  We can
always ask for them for clarification once they're more stable.