lice: 0.4 -> 0.6
NixOS/nixpkgs pull request #112895
Opened 2021-02-12 12:18 UTC by jorsn

Credits to @mat8913 (https://github.com/NixOS/nixpkgs/issues/75521#issuecomment-566013855).

###### Motivation for this change

lice 0.4 is old and in nixpkgs broken (#75521).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after) **+3.6 MB**
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-12 12:33 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 112895` at 9bc90032 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/60d331066bd46439d1f7be82a5987f5a">lice</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md">no-uri-literals</a>

URI literals are deprecated.
Near pkgs/tools/misc/lice/default.nix:25:16:
```
   |
25 |     homepage = https://github.com/licenses/lice;
   |                ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-explicit-check-phase.md">python-explicit-check-phase</a>

Consider using `pytestCheckHook` in `checkInputs` rather than `checkPhase = "pytest";`.

Near pkgs/tools/misc/lice/default.nix:21:3:
```
   |
21 |   checkPhase = "pytest";
   |   ^
```
</li>
  </ul>
</details>

2021-02-12 12:33 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 112895` at 9bc90032 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/f98ff2cb69fbb18d53ef6f8a922ac398">lice</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md">no-uri-literals</a>

URI literals are deprecated.
Near pkgs/tools/misc/lice/default.nix:25:16:
```
   |
25 |     homepage = https://github.com/licenses/lice;
   |                ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-explicit-check-phase.md">python-explicit-check-phase</a>

Consider using `pytestCheckHook` in `checkInputs` rather than `checkPhase = "pytest";`.

Near pkgs/tools/misc/lice/default.nix:21:3:
```
   |
21 |   checkPhase = "pytest";
   |   ^
```
</li>
  </ul>
</details>

2021-02-12 13:37 UTC, SuperSandro2000 requested changes

2021-02-12 13:37 UTC, SuperSandro2000 commented on pkgs/tools/misc/lice/default.nix
> +  checkPhase = "pytest";
Please use pytestCheckHook.

2021-02-12 13:37 UTC, SuperSandro2000 commented on pkgs/tools/misc/lice/default.nix
> +    homepage = https://github.com/licenses/lice;
```suggestion
    homepage = "https://github.com/licenses/lice";
```

2021-02-12 14:09 UTC, jorsn commented on pkgs/tools/misc/lice/default.nix
> +  checkPhase = "pytest";
fixed it. Thanks!

2021-02-12 14:46 UTC, swflint approved these changes
Assuming @SuperSandro2000's changes are added, LGTM

2021-02-12 23:34 UTC, SuperSandro2000 commented on pkgs/tools/misc/lice/default.nix
> +    description = "Print license based on selection and user options.";
```suggestion
    description = "Print license based on selection and user options";
```

2021-02-15 09:30 UTC, jorsn commented on pkgs/tools/misc/lice/default.nix
> +    description = "Print license based on selection and user options.";
done

2021-02-15 14:03 UTC, swflint approved these changes

2021-02-17 13:27 UTC, SuperSandro2000 requested changes

2021-02-17 13:27 UTC, SuperSandro2000 commented on pkgs/tools/misc/lice/default.nix
```suggestion
```

2021-02-17 13:27 UTC, SuperSandro2000 commented on pkgs/tools/misc/lice/default.nix
> +
```suggestion

```

2021-02-17 13:29 UTC, merged