libical: 3.0.8 -> 3.0.9
NixOS/nixpkgs pull request #113156
Opened 2021-02-14 21:44 UTC by Mic92

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-14 22:57 UTC, SuperSandro2000 requested changes

2021-02-14 22:57 UTC, SuperSandro2000 commented on pkgs/development/libraries/libical/default.nix
> -    (fetchpatch {
Please remove fetchpatch from inputs.

2021-02-15 13:41 UTC, Mic92 commented on pkgs/development/libraries/libical/default.nix
> -    (fetchpatch {
done.

2021-02-15 13:52 UTC, Mic92 commented
@GrahamcOfBorg eval

2021-02-15 13:55 UTC, Mic92 commented
ofborg you are drunk! If I compare the lines in the stacktrace they don't line up with the code from this repo!

2021-02-15 14:01 UTC, merged