ponyc: 0.38.1 -> 0.38.3
NixOS/nixpkgs pull request #113234
Opened 2021-02-15 21:42 UTC by Trundle

###### Motivation for this change
New upstream release. Also switched from libressl to openssl because it
makes using the net_ssl package easier.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-15 22:57 UTC, kamilchm approved these changes

2021-02-15 23:01 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 113234` at ecad01f6 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/094f0201a3a753bde63ba53c7fc56094">pony-corral</a></li></li>
    <li><a href="https://gist.github.com/7dd217e74455dbd7aa4131675b17cb6c">pony-stable</a></li></li>
    <li><a href="https://gist.github.com/3db34c14d9074339416f2e1a29f10072">ponyc</a></li></li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md">no-uri-literals</a>

URI literals are deprecated.
Near pkgs/development/compilers/ponyc/default.nix:27:11:
```
   |
27 |     url = https://github.com/google/benchmark/archive/v1.5.0.tar.gz;
   |           ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md">no-uri-literals</a>

URI literals are deprecated.
Near pkgs/development/compilers/ponyc/default.nix:42:15:
```
   |
42 |         url = https://github.com/google/googletest/archive/release-1.8.1.tar.gz;
   |               ^
```
</li>
  </ul>
</details>

2021-02-16 06:47 UTC, SuperSandro2000 requested changes
Please fix the unquoted urls.

2021-02-17 08:04 UTC, danieldk approved these changes
LGTM. Thanks for fixing the unquoted URLs as well!

2021-02-17 08:04 UTC, merged