swtpm: init at 0.5.2
NixOS/nixpkgs pull request #113362
Opened 2021-02-17 04:06 UTC by baloo

###### Motivation for this change

Goes along with #113361 which introduces a direct dependency

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-17 07:17 UTC, tomberek commented
Result of `nixpkgs-review pr 113362` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

2021-02-17 07:37 UTC, fabaff commented on pkgs/tools/security/libtpms/default.nix
> +    maintainers = [ stdenv.lib.maintainers.baloo ];
```suggestion
  meta = with lib; {
    description = "The libtpms library provides software emulation of a Trusted Platform Module (TPM 1.2 and TPM 2.0)";
    homepage = "https://github.com/stefanberger/libtpms";
    license = licenses.bsd3;
    maintainers = [ maintainers.baloo ];
```

see https://github.com/NixOS/nixpkgs/issues/108938

2021-02-17 07:37 UTC, fabaff commented on pkgs/tools/security/libtpms/default.nix
> +  '';
Perhaps this could be replaced with `autoreconfHook`.

2021-02-17 11:45 UTC, SuperSandro2000 requested changes
missing top level entries.

2021-02-17 11:45 UTC, SuperSandro2000 commented on pkgs/tools/security/swtpm/default.nix
> +    maintainers = [ stdenv.lib.maintainers.baloo ];
```suggestion
    license = lib.licenses.bsd3;
    maintainers = [ lib.maintainers.baloo ];
```

2021-02-17 11:45 UTC, SuperSandro2000 commented on pkgs/tools/security/swtpm/default.nix
> +    aclocal
autoreconfHook?

2021-02-17 11:45 UTC, SuperSandro2000 commented on pkgs/tools/security/swtpm/default.nix
> +    pkgconfig unixtools.netstat expect socat
```suggestion
    pkg-config unixtools.netstat expect socat
```

2021-02-17 16:17 UTC, baloo commented
> missing top level entries.

oops o:)

2021-02-17 22:55 UTC, tomberek approved these changes

2021-02-18 02:55 UTC, SuperSandro2000 requested changes

2021-02-18 02:55 UTC, SuperSandro2000 commented on pkgs/tools/security/libtpms/default.nix
> +  ];
```suggestion
  outputs = [ "out" "lib" "man" "dev" ];
```

2021-02-18 02:55 UTC, SuperSandro2000 commented on pkgs/tools/security/libtpms/default.nix
> +  ];
```suggestion
  ];
  

  buildInputs = [ openssl ];
```

2021-02-18 02:55 UTC, SuperSandro2000 commented on pkgs/tools/security/libtpms/default.nix
> +    homepage = https://github.com/stefanberger/libtpms;
```suggestion
    homepage = "https://github.com/stefanberger/libtpms";
```

2021-02-18 02:55 UTC, SuperSandro2000 commented on pkgs/tools/security/swtpm/default.nix
> +  ];
```suggestion
  outputs = [ "out" "man" ];
```

2021-02-18 12:06 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113362` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>libtpms</li>
<li>swtpm</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
libtpms:
<details>


URI literals are deprecated.
Near pkgs/tools/security/libtpms/default.nix:46:16:

```
   |
46 |     homepage = https://github.com/stefanberger/libtpms;
   |                ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md
</details>
swtpm:
<details>


URI literals are deprecated.
Near pkgs/tools/security/swtpm/default.nix:71:16:

```
   |
71 |     homepage = https://github.com/stefanberger/swtpm;
   |                ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/no-uri-literals.md
Please add a comment on the line above, explaining the purpose of this patch.
Near pkgs/tools/security/swtpm/default.nix:31:5:

```
   |
31 |     ./python-installation.patch
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md
</details>
</details>

2021-02-18 18:28 UTC, baloo commented
Result of `nixpkgs-review pr 113362` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>libtpms</li>
    <li>swtpm</li>
  </ul>
</details>

2021-02-23 00:48 UTC, baloo commented
@SuperSandro2000 anything else I can do on this PR?

2021-02-23 01:42 UTC, SuperSandro2000 commented
> @SuperSandro2000 anything else I can do on this PR?

No, I am just behind with notifications.

2021-02-23 01:42 UTC, merged