top-level/packages-config.nix: Correctly index package subsets delimited by dots
NixOS/nixpkgs pull request #113680
Opened 2021-02-19 11:55 UTC by adisbladis

###### Motivation for this change

Fixes the issue discovered by @Atemu in https://github.com/NixOS/nixpkgs/issues/110348#issuecomment-782010897 where dot delimited subsets were not taken into account.

Note: I haven't tested how this interacts with search at all, I've just assumed it's probably fine. This needs more testing to see what the implications are, hence I've marked it as draft.

cc @garbas 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-19 11:59 UTC, SuperSandro2000 commented on pkgs/tools/misc/nix-direnv/default.nix
> -      --replace "grep" "${gnugrep}/bin/grep" \
The dir-env commit slipped in by accident.

2021-02-19 18:25 UTC, Atemu commented
> I haven't tested how this interacts with search at all

Search have their OOT version of this file to generate the search index; that's where I copied it from actually ;)

2021-02-19 18:29 UTC, Atemu requested changes
Aborts with infinite recursion for me.

Also needs a bit of formatting cleanup and/or refactoring I think ;)

2021-02-21 19:38 UTC, adisbladis commented
Closing this one as I think https://github.com/NixOS/nixpkgs/pull/113713 is clearly better.

2021-02-21 19:38 UTC, closed without merging