gst_all_1.gst-plugins-bad: adds voaacenc support
NixOS/nixpkgs pull request #113822
Opened 2021-02-20 19:43 UTC by baloo

###### Motivation for this change

Adds vo-aacenc packaging and add support for voaacenc in gstreamer-plugins-bad

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-20 22:41 UTC, SuperSandro2000 requested changes

2021-02-20 22:41 UTC, SuperSandro2000 commented on pkgs/development/libraries/vo-aacenc/default.nix
> +}:
```suggestion
{ lib, stdenv, fetchurl }:
```

2021-02-20 22:41 UTC, SuperSandro2000 commented on pkgs/development/libraries/vo-aacenc/default.nix
> +with lib;
```suggestion
```

2021-02-20 22:41 UTC, SuperSandro2000 commented on pkgs/development/libraries/vo-aacenc/default.nix
> +  meta = {
```suggestion
  meta = with lib; {
```

2021-02-22 00:13 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 113822` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
7 packages marked as broken and skipped:
</summary>
<ul>
<li>gnome3.gnome-books</li>
<li>gnome3.gnome-documents</li>
<li>libsForQt512.kdenlive</li>
<li>libsForQt514.kdenlive</li>
<li>openmodelica</li>
<li>termplay</li>
<li>xmonad_log_applet</li>
</ul>
</details>
<details>

  <summary>12 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>citrix_workspace: log was empty</li>
<li>(citrix_workspace_21_01_0): log was empty</li>
<li>citrix_workspace_20_04_0: log was empty</li>
<li>citrix_workspace_20_06_0: log was empty</li>
<li>citrix_workspace_20_09_0: log was empty</li>
<li>citrix_workspace_20_10_0: log was empty</li>
<li>citrix_workspace_20_12_0: log was empty</li>
<li>gnunet-gtk: <a href="https://termbin.com/7dri3">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/5fc311fc9a20d3431a9aeb38513c8c57/raw/index.html">pretty log </a></li>
<li>gtkd: log was empty</li>
<li>ib-controller: log was empty</li>
<li>libsForQt512.dragon: log was empty</li>
<li>tilix: log was empty</li>
  </ul>
</details>
<details>

  <summary>1 package failed to build and are new build failure:</summary>
  <ul>
<li>fractal: <a href="https://termbin.com/q5es">plain log</a>  |  <a href="https://htmlpreview.github.io/?https://gist.githubusercontent.com/SuperSandroBot/8ae198b547e52300b5076afd9673e14d/raw/index.html">pretty log </a></li>
  </ul>
</details>
<details>
<summary>
293 packages built:
</summary>
<ul>
<li>adapta-gtk-theme</li>
<li>almanah</li>
<li>apostrophe</li>
<li>aravis</li>
<li>areca</li>
<li>astroid</li>
<li>audio-recorder</li>
<li>azureus</li>
<li>balsa</li>
<li>baresip</li>
<li>birdfont</li>
<li>bookworm</li>
<li>brasero</li>
<li>brasero-original</li>
<li>bubblemail</li>
<li>byzanz</li>
<li>calls</li>
<li>cawbird</li>
<li>chrome-gnome-shell</li>
<li>cinnamon.cinnamon-common</li>
<li>cinnamon.cinnamon-control-center</li>
<li>cinnamon.cinnamon-gsettings-overrides</li>
<li>cinnamon.cinnamon-screensaver</li>
<li>claws-mail-gtk3</li>
<li>cog</li>
<li>denemo</li>
<li>dropbox-cli</li>
<li>eclipse-mat</li>
<li>eclipses.eclipse-committers</li>
<li>eclipses.eclipse-cpp</li>
<li>eclipses.eclipse-java</li>
<li>eclipses.eclipse-modeling</li>
<li>eclipses.eclipse-platform</li>
<li>eclipses.eclipse-rcp</li>
<li>eclipses.eclipse-rust</li>
<li>eclipses.eclipse-scala-sdk</li>
<li>eclipses.eclipse-sdk</li>
<li>elementary-planner</li>
<li>empathy (gnome3.empathy)</li>
<li>enlightenment.rage</li>
<li>eolie</li>
<li>ephemeral</li>
<li>epiphany (gnome3.epiphany)</li>
<li>evince (gnome3.evince)</li>
<li>evolution</li>
<li>evolution-data-server (gnome3.evolution-data-server ,gnome3.evolution_data_server)</li>
<li>evolution-ews</li>
<li>evolutionWithPlugins</li>
<li>farstream</li>
<li>fcitx5-gtk</li>
<li>fcitx5-with-addons</li>
<li>feedreader</li>
<li>feeds</li>
<li>folks (gnome3.folks)</li>
<li>formiko</li>
<li>gajim</li>
<li>gcompris</li>
<li>gfbgraph (gnome3.gfbgraph)</li>
<li>glade (gnome3.glade)</li>
<li>glom</li>
<li>gmrender-resurrect</li>
<li>gnome-builder</li>
<li>gnome-keysign</li>
<li>gnome-network-displays</li>
<li>gnome-online-accounts (gnome3.gnome-online-accounts ,gnome3.gnome_online_accounts)</li>
<li>gnome-photos (gnome3.gnome-photos)</li>
<li>gnome-podcasts</li>
<li>gnome-recipes</li>
<li>gnome-tour</li>
<li>gnome3.bijiben (gnome3.gnome-notes)</li>
<li>gnome3.cheese</li>
<li>gnome3.devhelp</li>
<li>gnome3.file-roller</li>
<li>gnome3.geary</li>
<li>gnome3.gnome-applets</li>
<li>gnome3.gnome-boxes</li>
<li>gnome3.gnome-calendar</li>
<li>gnome3.gnome-clocks</li>
<li>gnome3.gnome-contacts</li>
<li>gnome3.gnome-control-center (gnome3.gnome_control_center)</li>
<li>gnome3.gnome-flashback</li>
<li>gnome3.gnome-initial-setup</li>
<li>gnome3.gnome-maps</li>
<li>gnome3.gnome-music</li>
<li>gnome3.gnome-online-miners</li>
<li>gnome3.gnome-panel</li>
<li>gnome3.gnome-screenshot</li>
<li>gnome3.gnome-session (gnome3.gnome_session)</li>
<li>gnome3.gnome-shell (gnome3.gnome_shell)</li>
<li>gnome3.gnome-software</li>
<li>gnome3.gnome-sound-recorder</li>
<li>gnome3.gnome-terminal (gnome3.gnome_terminal)</li>
<li>gnome3.gnome-todo</li>
<li>gnome3.gnome-tweaks (gnome3.gnome-tweak-tool)</li>
<li>gnome3.gnome-user-share</li>
<li>grilo-plugins (gnome3.grilo-plugins)</li>
<li>gnome3.gvfs</li>
<li>libgdata (gnome3.libgdata)</li>
<li>libgepub (gnome3.libgepub)</li>
<li>libzapojit (gnome3.libzapojit)</li>
<li>gnome3.nautilus</li>
<li>gnome3.nautilus-python</li>
<li>gnome3.polari</li>
<li>gnome3.pomodoro</li>
<li>gnome3.rygel</li>
<li>gnome3.seahorse</li>
<li>shotwell (gnome3.shotwell)</li>
<li>gnome3.sushi</li>
<li>gnome3.totem</li>
<li>tracker-miners (gnome3.tracker-miners)</li>
<li>webkitgtk (gnome3.webkitgtk)</li>
<li>yelp (gnome3.yelp)</li>
<li>gnomeExtensions.easyScreenCast</li>
<li>gnomeExtensions.gsconnect</li>
<li>gnomeExtensions.night-theme-switcher</li>
<li>gnucash</li>
<li>gnvim</li>
<li>gnvim-unwrapped</li>
<li>gscrabble</li>
<li>gst_all_1.gst-editing-services</li>
<li>gst_all_1.gst-plugins-bad</li>
<li>gst_all_1.gst-rtsp-server</li>
<li>gst_all_1.gst-vaapi</li>
<li>gthumb</li>
<li>gtk4</li>
<li>haskellPackages.reflex-dom</li>
<li>haskellPackages.webkit2gtk3-javascriptcore</li>
<li>ipscan</li>
<li>kicad-small</li>
<li>kicad-unstable-small</li>
<li>libhandy</li>
<li>libreoffice-fresh</li>
<li>libreoffice-fresh-unwrapped</li>
<li>libreoffice-qt</li>
<li>libreoffice-still</li>
<li>libreoffice-unwrapped (libreoffice-still-unwrapped)</li>
<li>libsForQt5.dragon (libsForQt515.dragon ,plasma5Packages.dragon)</li>
<li>libsForQt5.kdenlive (libsForQt515.kdenlive ,plasma5Packages.kdenlive)</li>
<li>libsForQt5.phonon-backend-gstreamer (libsForQt515.phonon-backend-gstreamer ,plasma5Packages.phonon-backend-gstreamer)</li>
<li>libsForQt5.telepathy (libsForQt515.telepathy ,plasma5Packages.telepathy)</li>
<li>libsForQt512.phonon-backend-gstreamer</li>
<li>libsForQt512.telepathy</li>
<li>libsForQt514.dragon</li>
<li>libsForQt514.phonon-backend-gstreamer</li>
<li>libsForQt514.telepathy</li>
<li>liferea</li>
<li>lispPackages.cl-webkit2</li>
<li>lispPackages.nyxt</li>
<li>lollypop</li>
<li>luakit</li>
<li>lutris</li>
<li>lutris-free</li>
<li>lutris-unwrapped</li>
<li>mailnag</li>
<li>mailnagWithPlugins</li>
<li>mapmap</li>
<li>marker</li>
<li>mate.atril</li>
<li>mate.mate-user-guide</li>
<li>mavproxy</li>
<li>meteo</li>
<li>midori-unwrapped</li>
<li>mmex</li>
<li>mopidy-iris</li>
<li>mopidy-local</li>
<li>mopidy-mopify</li>
<li>mopidy-mpd</li>
<li>mopidy-mpris</li>
<li>mopidy-musicbox-webclient</li>
<li>mopidy-scrobbler</li>
<li>mopidy-somafm</li>
<li>mopidy-soundcloud</li>
<li>mopidy-spotify-tunigo</li>
<li>mopidy-subidy</li>
<li>mopidy-tunein</li>
<li>mopidy-youtube</li>
<li>nasc</li>
<li>newsflash</li>
<li>notes-up</li>
<li>nyxt</li>
<li>odpdown</li>
<li>onboard</li>
<li>osmo</li>
<li>pantheon.elementary-calendar</li>
<li>pantheon.elementary-camera</li>
<li>pantheon.elementary-capnet-assist</li>
<li>pantheon.elementary-code</li>
<li>pantheon.elementary-greeter</li>
<li>pantheon.elementary-gsettings-schemas</li>
<li>pantheon.elementary-music</li>
<li>pantheon.elementary-onboarding</li>
<li>pantheon.elementary-photos</li>
<li>pantheon.elementary-session-settings</li>
<li>pantheon.elementary-videos</li>
<li>pantheon.extra-elementary-contracts</li>
<li>pantheon.notes-up</li>
<li>pantheon.switchboard-plug-a11y</li>
<li>pantheon.switchboard-plug-onlineaccounts</li>
<li>pantheon.switchboard-with-plugs</li>
<li>pantheon.wingpanel-applications-menu</li>
<li>pant [...]

2021-02-22 03:40 UTC, baloo commented
Fractal builds fine here:
<details>

```
building
build flags: -j16 -l16
[1/4] Generating resources_gresource with a custom commandes_merge with a custom command
xml-stripblanks preprocessing requested, but XMLLINT is not set, and xmllint is not in PATH
[1/4] Generating cargo-build with a custom command
RELEASE MODE
   Compiling pkg-config v0.3.18
   Compiling libc v0.2.74
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.38
   Compiling autocfg v1.0.0
   Compiling lazy_static v1.4.0
   Compiling memchr v2.3.3
   Compiling cfg-if v0.1.10
   Compiling futures-core v0.3.5
   Compiling slab v0.4.2
   Compiling proc-macro-hack v0.5.18
   Compiling bitflags v1.2.1
   Compiling pin-project-internal v0.4.23
   Compiling futures-sink v0.3.5
   Compiling proc-macro-nested v0.1.6
   Compiling once_cell v1.4.0
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.5
   Compiling autocfg v0.1.7
   Compiling serde_derive v1.0.114
   Compiling serde v1.0.114
   Compiling rand_core v0.4.2
   Compiling log v0.4.11
   Compiling cc v1.0.58
   Compiling typenum v1.12.0
   Compiling ryu v1.0.5
   Compiling siphasher v0.2.3
   Compiling byteorder v1.3.4
   Compiling bytes v0.5.6
   Compiling serde_json v1.0.57
   Compiling fnv v1.0.7
   Compiling gio v0.8.1
   Compiling version_check v0.9.2
   Compiling tinyvec v0.3.3
   Compiling pango v0.8.0
   Compiling pin-project-lite v0.1.7
   Compiling string_cache_shared v0.3.0
   Compiling matches v0.1.8
   Compiling cairo-rs v0.8.1
   Compiling itoa v0.4.6
   Compiling adler v0.2.3
   Compiling proc-macro2 v0.4.30
   Compiling unicode-xid v0.1.0
   Compiling gdk-pixbuf v0.8.0
   Compiling getrandom v0.1.14
   Compiling openssl v0.10.30
   Compiling foreign-types-shared v0.1.1
   Compiling new_debug_unreachable v1.0.4
   Compiling syn v0.15.44
   Compiling gdk v0.12.1
   Compiling atk v0.8.0
   Compiling mac v0.1.1
   Compiling gstreamer v0.15.7
   Compiling httparse v1.3.4
   Compiling native-tls v0.2.4
   Compiling crc32fast v1.2.0
   Compiling ucd-trie v0.1.3
   Compiling gtk v0.8.1
   Compiling precomputed-hash v0.1.1
   Compiling openssl-probe v0.1.2
   Compiling try-lock v0.2.3
   Compiling failure_derive v0.1.8
   Compiling gimli v0.22.0
   Compiling muldiv v0.2.1
   Compiling unicode-segmentation v1.6.0
   Compiling regex-syntax v0.6.18
   Compiling utf-8 v0.7.5
   Compiling byte-tools v0.3.1
   Compiling either v1.5.3
   Compiling subtle v1.0.0
   Compiling ppv-lite86 v0.2.8
   Compiling object v0.20.0
   Compiling tower-service v0.3.0
   Compiling opaque-debug v0.2.3
   Compiling gstreamer-base v0.15.4
   Compiling percent-encoding v2.1.0
   Compiling maplit v1.0.2
   Compiling rustc-demangle v0.1.16
   Compiling encoding_rs v0.8.23
   Compiling percent-encoding v1.0.1
   Compiling unicode-width v0.1.8
   Compiling pangocairo v0.9.0
   Compiling gstreamer-video v0.15.7
   Compiling mime v0.3.16
   Compiling dtoa v0.4.6
   Compiling gstreamer-player v0.15.5
   Compiling gstreamer-pbutils v0.15.1
   Compiling ansi_term v0.11.0
   Compiling fake-simd v0.1.2
   Compiling base64 v0.12.3
   Compiling unchecked-index v0.2.2
   Compiling vec_map v0.8.2
   Compiling strsim v0.8.0
   Compiling ipnet v2.3.0
   Compiling ansi_term v0.12.1
   Compiling entities v1.0.1
   Compiling unicode_categories v0.1.1
   Compiling typed-arena v1.7.0
   Compiling md5 v0.7.0
   Compiling fragile v1.0.0
   Compiling tracing-core v0.1.13
   Compiling thread_local v1.0.1
   Compiling futures-channel v0.3.5
   Compiling futures-task v0.3.5
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling phf_shared v0.7.24
   Compiling unicode-bidi v0.3.4
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling num-bigint v0.2.6
   Compiling num-rational v0.2.4
   Compiling hashbrown v0.8.1
   Compiling indexmap v1.5.0
   Compiling num-complex v0.2.4
   Compiling num-iter v0.1.41
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling miniz_oxide v0.4.0
   Compiling unicode-normalization v0.1.13
   Compiling http v0.2.1
   Compiling foreign-types v0.3.2
   Compiling glib-sys v0.9.1
   Compiling gobject-sys v0.9.1
   Compiling gio-sys v0.9.1
   Compiling pango-sys v0.9.1
   Compiling cairo-sys-rs v0.9.2
   Compiling gstreamer-sys v0.8.1
   Compiling gdk-pixbuf-sys v0.9.1
   Compiling gstreamer-base-sys v0.8.1
   Compiling atk-sys v0.9.1
   Compiling gdk-sys v0.9.1
   Compiling gtk-sys v0.9.2
   Compiling gstreamer-video-sys v0.8.1
   Compiling gstreamer-audio-sys v0.8.1
   Compiling pangocairo-sys v0.10.1
   Compiling gstreamer-pbutils-sys v0.8.1
   Compiling gstreamer-player-sys v0.8.1
   Compiling gspell-sys v0.4.0
   Compiling sourceview4-sys v0.2.0 (https://gitlab.gnome.org/World/Rust/sourceview4-rs.git?rev=fa8819fa7ecbe56f44d951656d3825f468915754#fa8)
   Compiling libhandy-sys v0.5.0
   Compiling futf v0.1.4
   Compiling unicase v2.6.0
   Compiling pest v2.1.3
   Compiling block-padding v0.1.5
   Compiling itertools v0.8.2
   Compiling paste-impl v0.1.18
   Compiling heck v0.3.1
   Compiling textwrap v0.11.0
   Compiling openssl-sys v0.9.58
   Compiling lmdb-sys v0.8.0
   Compiling gettext-sys v0.19.9 (https://github.com/danigm/gettext-rs?branch=no-gettext#61938b9f)
   Compiling rand_xorshift v0.1.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling phf v0.7.24
   Compiling addr2line v0.13.0
   Compiling idna v0.2.0
   Compiling idna v0.1.5
   Compiling tendril v0.4.1
   Compiling http-body v0.3.1
   Compiling aho-corasick v0.7.13
   Compiling linkify v0.3.1
   Compiling twoway v0.2.1
   Compiling pest_meta v2.1.3
   Compiling tracing v0.1.18
   Compiling want v0.3.0
   Compiling paste v0.1.18
   Compiling quote v1.0.7
   Compiling iovec v0.1.4
   Compiling net2 v0.2.34
   Compiling num_cpus v1.13.0
   Compiling time v0.1.43
   Compiling socket2 v0.3.12
   Compiling atty v0.2.14
   Compiling rand_os v0.1.3
   Compiling dirs-sys v0.3.5
   Compiling dbus v0.2.3
   Compiling backtrace v0.3.50
   Compiling url v1.7.2
   Compiling flate2 v1.0.16
   Compiling quote v0.6.13
   Compiling generic-array v0.12.3
   Compiling bytes v0.4.12
   Compiling regex v1.3.9
   Compiling mio v0.6.22
   Compiling rand_core v0.5.1
   Compiling clap v2.33.2
   Compiling loggerv v0.7.2
   Compiling dirs v2.0.2
   Compiling directories v2.0.2
   Compiling mime_guess v2.0.3
   Compiling async-compression v0.3.5
   Compiling digest v0.8.1
   Compiling block-cipher-trait v0.6.2
   Compiling crypto-mac v0.7.0
   Compiling block-buffer v0.7.3
   Compiling rand_chacha v0.2.2
   Compiling tokio v0.2.22
   Compiling locale_config v0.2.3
   Compiling lmdb v0.8.0

   Compiling phf_generator v0.7.24
   Compiling aes-soft v0.3.3
   Compiling block-modes v0.3.3
   Compiling hmac v0.7.1
   Compiling sha2 v0.8.2
   Compiling rand v0.7.3
   Compiling gettext-rs v0.4.2 (https://github.com/danigm/gettext-rs?branch=no-gettext#61938b9f)
   Compiling synstructure v0.12.4
   Compiling pest_generator v2.1.3
   Compiling tokio-util v0.3.1
   Compiling string_cache_codegen v0.4.4
   Compiling phf_codegen v0.7.24
   Compiling aes v0.3.2
   Compiling hkdf v0.8.0
   Compiling num v0.2.1
   Compiling tokio-tls v0.3.1
   Compiling secret-service v1.1.0
   Compiling string_cache v0.7.5
   Compiling html5ever v0.23.0
   Compiling futures-macro v0.3.5
   Compiling thiserror-impl v1.0.20
   Compiling strum_macros v0.18.0
   Compiling pest_derive v2.1.0
   Compiling failure v0.1.8
   Compiling thiserror v1.0.20
   Compiling comrak v0.7.0
   Compiling pin-project v0.4.23
   Compiling futures-util v0.3.5
   Compiling strum v0.18.0
   Compiling futures-executor v0.3.5
   Compiling h2 v0.2.6
   Compiling glib v0.9.3
   Compiling futures v0.3.5
   Compiling tokio-socks v0.2.2
   Compiling url v2.1.1
   Compiling bincode v1.3.1
   Compiling ruma-identifiers v0.17.1
   Compiling either v1.5.99 (https://github.com/danigm/either.git?rev=60c99bc0723491e2dfd42bbe9b485c5f9323e96b#60c [...]

2021-02-24 19:25 UTC, baloo commented
@SuperSandro2000 anything else I can do here?
Thank you

2021-02-26 18:48 UTC, SuperSandro2000 commented
Removing ``gobject-introspection`` caused a regression:

```
Run-time dependency orc-0.4 found: YES 0.4.32
Program orcc found: YES (/nix/store/h666gplxlbp6bx926cwr7cm7vmay37xc-orc-0.4.32-dev/bin/orcc)
Header <gst/gstconfig.h> has symbol "GST_DISABLE_GST_DEBUG" with dependency gstreamer-1.0: NO
Message: GStreamer debug system is enabled
Program python3 found: YES (/nix/store/yl69v76azrz4daiqksrhb8nnmdiqdjg9-python3-3.8.8/bin/python3.8)
Program g-ir-scanner found: YES (/nix/store/9348f0896syjsfsx76kf4vpxgxp003m9-gobject-introspection-1.66.1-dev/bin/g-ir-scanner)
Using 'PKG_CONFIG' from environment with value: 'pkg-config'
Found pkg-config: /nix/store/1m90ppkamm4wk81l7ig65ircwiw7wiaa-pkg-config-wrapper-0.29.2/bin/pkg-config (0.29.2)
Did not find CMake 'cmake'
Found CMake: NO
Build-time dependency gobject-introspection-1.0 found: NO (tried pkgconfig)
gst-libs/gst/audio/meson.build:22:2: ERROR: Dependency "gobject-introspection-1.0" not found, tried pkgconfig
A full log can be found at /build/gst-plugins-bad-1.18.2/build/meson-logs/meson-log.txt
builder for '/nix/store/1rlgmirl51ayivby585f69rvll8wxx0l-gst-plugins-bad-1.18.2.drv' failed with exit code 1
error: build of '/nix/store/1rlgmirl51ayivby585f69rvll8wxx0l-gst-plugins-bad-1.18.2.drv' failed
```

2021-02-26 23:40 UTC, baloo commented
just checking, that was the result of a cross compilation error right?

2021-03-04 19:46 UTC, merged