msitools: 0.98 -> 0.101
NixOS/nixpkgs pull request #113905
Opened 2021-02-21 14:06 UTC by PlushBeaver

###### Motivation for this change

* https://gitlab.gnome.org/GNOME/msitools/-/blob/v0.101/NEWS
* Fixes https://bugzilla.redhat.com/show_bug.cgi?id=1629516

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-21 18:43 UTC, SuperSandro2000 requested changes

2021-02-21 18:43 UTC, SuperSandro2000 commented on pkgs/development/tools/misc/msitools/default.nix
> +  nativeBuildInputs = [ bison gnome3.vala intltool meson ninja pkgconfig ];
```suggestion
  nativeBuildInputs = [ bison gnome3.vala intltool meson ninja pkg-config ];
```

2021-02-21 18:43 UTC, SuperSandro2000 commented on pkgs/development/tools/misc/msitools/default.nix
> +{ lib, stdenv, fetchurl, bison, intltool, glib, meson, ninja, pkgconfig, libgsf, gcab, bzip2, gnome3 }:
```suggestion
{ lib, stdenv, fetchurl, bison, intltool, glib, meson, ninja, pkg-config, libgsf, gcab, bzip2, gnome3 }:
```

2021-02-21 19:05 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 113905` at b7bab58b run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/e7a51846853a1357fcd1869382e882ba">msitools</a></li></li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/development/tools/misc/msitools/default.nix:21:3:
```
   |
21 |   meta = with lib; {
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/development/tools/misc/msitools/default.nix:24:5:
```
   |
24 |     license = [ licenses.gpl2 licenses.lgpl21 ];
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl21` is a deprecated license, check if project uses `lgpl21Plus` or `lgpl21Only` and change `meta.license` accordingly.

Near pkgs/development/tools/misc/msitools/default.nix:24:5:
```
   |
24 |     license = [ licenses.gpl2 licenses.lgpl21 ];
   |     ^
```
</li>
  </ul>
</details>

2021-02-22 02:02 UTC, davidak commented
Result of `nixpkgs-review pr 113905` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>msitools</li>
  </ul>
</details>

2021-02-22 02:07 UTC, davidak commented
@PlushBeaver any idea what is up with `msidiff` and `msidump`? Do they miss the executable flag for some reason? They are bash scripts. Maybe upstream could add them.

```
[nix-shell:~/.cache/nixpkgs-review/pr-113905]$ ll results/msitools/bin/
total 608
-r-xr-xr-x 1 root root  26248 Jan  1  1970 msibuild
-r--r--r-- 1 root root   5484 Jan  1  1970 msidiff
-r--r--r-- 1 root root   3293 Jan  1  1970 msidump
-r-xr-xr-x 1 root root  28192 Jan  1  1970 msiextract
-r-xr-xr-x 1 root root  31912 Jan  1  1970 msiinfo
-r-xr-xr-x 1 root root 479176 Jan  1  1970 wixl
-r-xr-xr-x 1 root root  38896 Jan  1  1970 wixl-heat
```

The other binaries seem to generally work.
```
[nix-shell:~/.cache/nixpkgs-review/pr-113905]$ msiinfo
Usage: msiinfo SUBCOMMAND COMMAND-OPTIONS...

Options:
  -h, --help        Show program usage
  -v, --version     Display program version

Available subcommands:
  help              Show program or subcommand usage
  streams           List streams in a .msi file
  tables            List tables in a .msi file
  extract           Extract a binary stream from an .msi file
  export            Export a table in text form from an .msi file
  suminfo           Print summary information
```

2021-02-22 21:09 UTC, PlushBeaver commented
@davidak Looks like an upstream bug, [sent them an MR](https://gitlab.gnome.org/GNOME/msitools/-/merge_requests/36). 

I'd be satisfied with 0.98 → 0.99 as it fixes the bug I'm hitting. Upstream moved to Meson just in 0.101, so let's wait until they stabilize, then update if need be. Adding myself as a maintainer as I'm going to watch this. Re: nixpkgs-review suggestions on licenses, 0.101 has moved to GPL2+ and LGPL2.1+, but 0.99 hasn't.

2021-02-23 03:36 UTC, davidak approved these changes

2021-02-23 03:37 UTC, merged