vscode-extensions.dracula-theme.theme-dracula: init at 2.22.3
NixOS/nixpkgs pull request #114032
Opened 2021-02-22 20:48 UTC by tbidne

###### Motivation for this change

Add support for Visual Studio Code extension [Dracula Theme](https://marketplace.visualstudio.com/items?itemName=dracula-theme.theme-dracula)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-22 21:07 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 114032` at d4817985 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/24fbeb39aa59693a1a6c76a7d5e65bfb">vscode-extensions.dracula-theme.theme-dracula</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/misc/vscode-extensions/default.nix:193:9:
```
    |
193 |         meta = with lib; {
    |         ^
```
</li>
  </ul>
</details>

2021-02-22 22:44 UTC, tbidne commented
> Result of `nixpkgs-review pr 114032` at [d481798](https://github.com/NixOS/nixpkgs/commit/d481798501166700305495116b60a689364289b8) run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> 1 package built:
> 1 suggestion:
> * warning: [maintainers-missing](https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md)
>   Package does not have a maintainer. Consider adding yourself?
>   Near pkgs/misc/vscode-extensions/default.nix:193:9:
>   ```
>       |
>   193 |         meta = with lib; {
>       |         ^
>   ```

I don't mind being a maintainer, though of course that would require adding myself to `maintainer-list.nix`. Whatever is easiest :slightly_smiling_face: .

2021-02-23 08:44 UTC, SuperSandro2000 requested changes

2021-02-23 08:44 UTC, SuperSandro2000 commented on pkgs/misc/vscode-extensions/default.nix
> +        meta = with lib; {
Please put meta last.

2021-02-23 08:45 UTC, SuperSandro2000 commented
> I don't mind being a maintainer, though of course that would require adding myself to `maintainer-list.nix`. Whatever is easiest slightly_smiling_face .

that check does not really apply to vim or vscode plugins which are very simple. You can ignore it.

2021-02-23 21:10 UTC, SuperSandro2000 commented on pkgs/misc/vscode-extensions/default.nix
> +          description = "Official Dracula Theme. A dark theme for many editors, shells, and more.";
```suggestion
          description = "Dark theme for many editors, shells, and more";
```

2021-02-25 00:16 UTC, merged