caerbannog: init at 0.3
NixOS/nixpkgs pull request #114039
Opened 2021-02-22 22:11 UTC by dotlambda

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-22 23:24 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 114039` at b80207d6 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/99f97ede0664a205c47b89ead7f3e8d4">caerbannog</a></li></li>
    <li><a href="https://gist.github.com/312b2f9ba6c08e7607e0aefe37c93e4c">python37Packages.fuzzyfinder</a></li></li>
    <li><a href="https://gist.github.com/a02e9f836c956024e23f7c7eb2feaee0">python38Packages.fuzzyfinder</a></li></li>
    <li><a href="https://gist.github.com/470319f795ec427902f904d1de83bdd4">python39Packages.fuzzyfinder</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `stdenv`.
Near pkgs/applications/misc/caerbannog/default.nix:2:3:
```
  |
2 | , stdenv
  |   ^
```
</li>
  </ul>
</details>

2021-02-23 08:41 UTC, SuperSandro2000 requested changes

2021-02-23 08:41 UTC, SuperSandro2000 commented on pkgs/applications/misc/caerbannog/default.nix
> +  format = "other";
```suggestion
  version = "0.3";
  format = "other";
```

2021-02-23 08:41 UTC, SuperSandro2000 commented on pkgs/applications/misc/caerbannog/default.nix
> +    rev = "0.3";
```suggestion
    rev = version;
```

2021-02-23 08:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/fuzzyfinder/default.nix
> +  ];
Please add a pythonImportsCheck.

2021-02-23 09:15 UTC, dotlambda commented on pkgs/development/python-modules/fuzzyfinder/default.nix
> +  ];
It's an application, not a module.

2021-02-23 13:58 UTC, merged