trafficserver: init at 9.0.0
NixOS/nixpkgs pull request #114116
Opened 2021-02-23 13:24 UTC by heroku-miraheze

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-23 14:03 UTC, AndersonTorres commented
Also include the `all-packages.nix` file modification.

2021-02-23 14:04 UTC, heroku-miraheze commented
Included.

2021-02-23 14:06 UTC, AndersonTorres commented
Squash the commits you did.

2021-02-23 14:08 UTC, heroku-miraheze commented
Is not an easy, merge it now.

2021-02-23 14:10 UTC, fabaff commented
Duplicate of #114090 ?

2021-02-23 14:10 UTC, heroku-miraheze commented
No.

2021-02-23 14:10 UTC, heroku-miraheze commented
I am going to close the duplicate now.

2021-02-23 14:11 UTC, heroku-miraheze commented
Closed original.

2021-02-23 14:11 UTC, heroku-miraheze commented
And merge it now.

2021-02-23 14:14 UTC, grahamc commented
Sorry @heroku-miraheze, this attitude of demanding merges isn't how we operate here. If you'd like to have things merged right away, I'd encourage you to maintain your own fork of Nixpkgs. If you'd like to collaborate and cooporate with our community, then please behave accordingly.

2021-02-23 14:18 UTC, heroku-miraheze commented
Done. When the last check is ended, merge it.

2021-02-23 14:19 UTC, AndersonTorres commented
> Done. When the last check is ended, merge it.

Nope. The bot is not a final arbiter of code quality.

2021-02-23 14:20 UTC, heroku-miraheze commented
But we need Traffic Server in NixPkgs.

2021-02-23 14:23 UTC, AndersonTorres commented
It doesn't imply we are forced to commit a low-quality code merely because __we need trafficserver__.

2021-02-23 14:24 UTC, grahamc commented
@AndersonTorres Don't worry about convincing, I don't think anyone with merge bit will be bullied in to merging poor quality work.

2021-02-23 14:27 UTC, dotlambda requested changes

2021-02-23 14:27 UTC, dotlambda commented on pkgs/servers/trafficserver/default.nix
> +    maintainers = with maintainers; [ "joaquinito2051" ];
```suggestion
    maintainers = with maintainers; [ joaquinito2051 ];
```
You need to add yourself to `maintainers/maintainer-list.nix`.

2021-02-23 14:29 UTC, dotlambda commented
> * [x]  Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

at least not the bit about commit messages

2021-02-23 14:33 UTC, heroku-miraheze commented
Updated all, now, when the last check is ended, merge it.

2021-02-23 14:34 UTC, adisbladis commented
> Updated all, now, when the last check is ended, merge it.

Stop demanding your changes getting merged.

If you want things merged collaborate with the people reviewing your PR instead. 
That's the only way forward.

2021-02-23 14:35 UTC, heroku-miraheze commented
I am collaborating with people.

2021-02-23 14:36 UTC, adisbladis commented
You obviously still haven't read https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md which states how commit messages should look like.

2021-02-23 14:49 UTC, heroku-miraheze commented
I cannot review collaborators, because i am from Windows.

2021-02-23 14:52 UTC, dotlambda commented
> I cannot review collaborators, because i am from Windows.

It does not make sense for you to contribute if you cannot even test your own pull requests.

2021-02-24 09:25 UTC, heroku-miraheze commented
Hello again, i need to review contributors, but i am from Windows, and you need to wait until install NixOS.

2021-02-24 09:37 UTC, heroku-miraheze commented
Installed, wait...

2021-02-24 11:12 UTC, heroku-miraheze commented
##### Reviewed points

- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on ARCHITECTURE
- [x] executables tested on ARCHITECTURE
- [x] all depending packages build

##### Possible improvements

##### Comments

2021-02-24 11:14 UTC, heroku-miraheze commented
https://gist.github.com/heroku-miraheze/e0f485bbe071289a9ba8199f104ab3a3

2021-02-24 11:34 UTC, etu requested changes
I probably would merge this code in this state if it wasn't for the bad commit history.

The commit history doesn't follow the https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md guidelines.

2021-02-24 11:35 UTC, heroku-miraheze reviewed
Reviewed

2021-02-24 12:42 UTC, dotlambda commented
> * [x]  executables tested on ARCHITECTURE

Which distro did you use? I get
```
/nix/store/dgdzy2hp8iw3h9k3i04j4plb0ylmy4m7-trafficserver-9.0.0/bin/trafficserver: line 108: sed: command not found
This script needs to be ported to this OS
```
It seems like this software will be of no use on NixOS without upstream support.

2021-02-24 12:53 UTC, heroku-miraheze commented
I use Ubuntu.

2021-02-25 02:23 UTC, AndersonTorres commented
The `trafficserver` is a shell script that uses a lot of that "classic elegant hackery" and many assumptions about FHS distros.

It would be really cool if we ported it to NixOS.

2021-03-21 04:08 UTC, SuperSandro2000 requested changes

2021-03-21 04:08 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  trafficserver = callPackage ../servers/trafficserver {};
```suggestion
  trafficserver = callPackage ../servers/trafficserver { };
```

2021-03-21 04:08 UTC, SuperSandro2000 commented on pkgs/servers/trafficserver/default.nix
> +    zlib.dev
Those belong into buildInputs and autoconf should pick them up then.

2021-05-03 09:49 UTC, closed without merging

2021-07-11 09:05 UTC, Kreyren commented
> You obviously still haven't read https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md which states how commit messages should look like.

FWIW based on my interactions with him on matrix he's not english speaker and there is a language barrier for him to understand those guidelines.

2021-07-16 09:06 UTC, khrj commented
> this attitude of demanding merges isn't how we operate here

(adding on to the previous comment) The author probably didn't intend to be demanding, but just came off that way because of whatever translation service they're using