js_of_ocaml: 3.8.0 -> 3.9.1
NixOS/nixpkgs pull request #114263
Opened 2021-02-24 18:03 UTC by anmonteiro

###### Motivation for this change
https://github.com/ocsigen/js_of_ocaml/releases/tag/3.9.1

OCaml 4.12 compatibility

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-24 18:40 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 114263` at 60e09f11 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/79a961a16a787dca490425cad0340073">acgtk</a></li></li>
  </ul>
</details>
<details>
  <summary>7 packages built:</summary>
  <ul>
    <li><a href="https://gist.github.com/bd4db4a858c9dcbac3963faf7028a62f">dune-release</a></li></li>
    <li><a href="https://gist.github.com/1cd8a8fe11e2cb78eb812d1c11c58ac3">eff</a></li></li>
    <li><a href="https://gist.github.com/0d98c89754f161bcd6bdcb4641e62e40">framac</a></li></li>
    <li><a href="https://gist.github.com/8bd9fd76c78b9968a49c4713674e8285">jackline</a></li></li>
    <li><a href="https://gist.github.com/f4bbd7e0f2445e358c5b7902120006bf">ocaml-crunch</a></li></li>
    <li><a href="https://gist.github.com/2a20a7a12e39f984bc3146c760bfac95">stog</a></li></li>
    <li><a href="https://gist.github.com/7c84864dd86fed355dadcec96c677977">why3</a></li></li>
  </ul>
</details>

2021-02-24 20:21 UTC, vbgl commented
@GrahamcOfBorg build ocamlPackages.eliom

2021-02-24 20:26 UTC, vbgl requested changes
This breaks `eliom` (future version 6.14.0 should be compatible with jsoo 3.9).

2021-03-24 15:14 UTC, sternenseemann commented
#117482

2021-03-26 07:44 UTC, vbgl commented
Subsumed by #117482

2021-03-26 07:44 UTC, closed without merging