webwormhole: init at git-2021-01-16
NixOS/nixpkgs pull request #114269
Opened 2021-02-24 19:18 UTC by bbigras

###### Motivation for this change

Note that the git repo says:

> THIS PROJECT IS STILL IN EARLY DEVELOPMENT IT USES EXPERIMENTAL
> CRYPTOGRAPHIC LIBRARIES AND IT HAS NOT HAD ANY KIND OF SECURITY
> OR CRYPTOGRAPHY REVIEW THIS SOFTWARE MIGHT BE BROKEN AND UNSAFE

but a download link is displayed on https://webwormhole.io/ so ¯\_(ツ)_/¯

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-24 19:19 UTC, bbigras commented
/marvin opt-in
/status needs_reviewer

2021-02-24 19:33 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 114269` at 0c70077f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/eb3f7eaeda4795a9bf7fa86a93662713">webwormhole</a></li></li>
  </ul>
</details>

2021-02-25 11:13 UTC, SuperSandro2000 requested changes

2021-02-25 11:13 UTC, SuperSandro2000 commented on pkgs/tools/networking/webwormhole/default.nix
> +  version = "git-2021-01-16";
```suggestion
  version = "unstable-2021-01-16";
```

2021-02-27 01:24 UTC, merged