sameboy: 0.13.6 -> 0.14
NixOS/nixpkgs pull request #114583
Opened 2021-02-27 19:05 UTC by NieDzejkob

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-27 19:23 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 114583` at 1aa90bbb run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/353e7fe9e652d0e289714f0b673f080a">sameboy</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/patch-phase.md">patch-phase</a>

`patchPhase` should not be overridden, use `postPatch` instead.

Near pkgs/misc/emulators/sameboy/default.nix:22:3:
```
   |
22 |   patchPhase = ''
   |   ^
```
</li>
  </ul>
</details>

2021-02-27 20:22 UTC, NieDzejkob commented
Thanks, fixed the suggestion.

2021-02-27 23:32 UTC, SuperSandro2000 requested changes

2021-02-27 23:32 UTC, SuperSandro2000 commented on pkgs/misc/emulators/sameboy/default.nix
> +                "DATA_DIR=$(out)/share/sameboy/" ];
```suggestion
  makeFlags = [
    "CAN_INSTALL=true"
    "CONF=release"
    "DATA_DIR=$(out)/share/sameboy/"
    "PREFIX=$(out)"
  ];
```

2021-02-27 23:32 UTC, SuperSandro2000 commented on pkgs/misc/emulators/sameboy/default.nix
>      sed 's@"libgtk-3.so"@"${gtk3}/lib/libgtk-3.so"@g' -i OpenDialog/gtk.c
This should use substituteInPlace.

2021-02-27 23:38 UTC, NieDzejkob commented on pkgs/misc/emulators/sameboy/default.nix
>      sed 's@"libgtk-3.so"@"${gtk3}/lib/libgtk-3.so"@g' -i OpenDialog/gtk.c
Pushed a fix.

2021-03-01 15:41 UTC, NieDzejkob commented
What's the status on this PR? Is it blocked on me or review?

2021-03-01 16:48 UTC, SuperSandro2000 commented
> What's the status on this PR? Is it blocked on me or review?

I just have 900 GitHub notifications and didn't look at them the last two days.

2021-03-01 17:03 UTC, merged

2021-03-01 17:35 UTC, NieDzejkob commented
On Mon Mar 1, 2021 at 5:48 PM CET, Sandro wrote:
> > What's the status on this PR? Is it blocked on me or review?
>
> I just have 900 GitHub notifications and didn't look at them the last two days. 

Totally understandable!Have a nice day.