yara: 4.0.1 -> 4.0.5
NixOS/nixpkgs pull request #114562
Opened 2021-02-27 14:03 UTC by roblabla

###### Motivation for this change

Latest libyara has some new API changes that are necessary to build an app I'm trying to package (imhex).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-02-27 14:23 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 114562` at 282f0f3a run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li><a href="https://gist.github.com/d7515f2575a0cc8155460a7c507e5c92">yara</a></li></li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/security/yara/default.nix:39:3:
```
   |
39 |   meta = with lib; {
   |   ^
```
</li>
  </ul>
</details>

2021-02-27 14:38 UTC, fabaff requested changes
Requires an update of the hash. The current change still builds 4.0.1.

```bash
...ew/pr-114562]$ ./results/yara/bin/yara -v
4.0.1
```

2021-02-27 15:40 UTC, roblabla commented
Oof, sorry about that, haven't used nixos in a while :sweat_smile: 

So I managed to update it properly, but hit a small bug. It appears that the build breaks when static libraries are disabled (which nixos does automatically). This got fixed in master, but the latest release, 4.0.5, still has the problem. See https://github.com/VirusTotal/yara/commit/52e6866023b9aca26571c78fb8759bc3a51ba6dc. So I added the `dontDisableStatic = false;` attribute with a comment explaining what's up.

2021-02-28 19:51 UTC, SuperSandro2000 commented on pkgs/tools/security/yara/default.nix
> +  # Current yara master already has a fix for it, see commit 52e6866. On the
Can we just fetch the patch instead?

2021-02-28 20:03 UTC, roblabla commented on pkgs/tools/security/yara/default.nix
> +  # Current yara master already has a fix for it, see commit 52e6866. On the
Done!

2021-03-03 23:54 UTC, SuperSandro2000 commented on pkgs/tools/security/yara/default.nix
> +    sha256 = "0dy8jf0pdn0wilxffff6pqjxg7icxkwax09w54np87gl9p00f5rk";
```suggestion
    sha256 = "1gkdll2ygdlqy1f27a5b84gw2bq75ss7acsx06yhiss90qwdaalq";
```

2021-03-07 03:00 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 114562` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>yara</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
yara:
<details>


warning: maintainers-missing
Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/security/yara/default.nix:53:3:

```
   |
53 |   meta = with lib; {
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md
</details>
</details>

2021-03-07 03:00 UTC, merged