ocamlPackages: Init ppx_cstubs at 0.6.1.1, add ppxlib 0.22.0, add ppx_deriving 5.2.1
NixOS/nixpkgs pull request #115291
Opened 2021-03-06 21:17 UTC by osener

###### Motivation for this change

Add new package [ppx_cstubs](https://github.com/fdopen/ppx_cstubs/), update its dependency ppxlib, and update ppx_deriving

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-07 01:03 UTC, SuperSandro2000 approved these changes
Please format the commit messages in style ``ocamlPackages.ppx_cstubs : Init at 0.6.1.1``

2021-03-07 01:05 UTC, SuperSandro2000 requested changes

2021-03-07 01:05 UTC, SuperSandro2000 commented on pkgs/development/ocaml-modules/ppx_cstubs/default.nix
> +  src = fetchurl {
Please use fetchFromGitHub.

2021-03-07 01:05 UTC, SuperSandro2000 commented on pkgs/development/ocaml-modules/ppx_cstubs/default.nix
> +    (ppxlib.override { version = "0.22.0"; })
Please move the override to pkgs/top-level/ocaml-packages.nix.

2021-03-07 01:05 UTC, SuperSandro2000 commented on pkgs/development/ocaml-modules/ppx_cstubs/default.nix
> +    };
```suggestion
  meta = with lib; {
    homepage = "https://github.com/fdopen/ppx_cstubs";
    description = "Preprocessor for easier stub generation with ocaml-ctypes";
    license = licenses.mit;
    maintainers = [ maintainers.osener ];
  };
```

2021-03-07 01:05 UTC, SuperSandro2000 commented on pkgs/development/ocaml-modules/ppx_deriving/default.nix
> +    sha256 = "11h75dsbv3rs03pl67hdd3lbim7wjzh257ij9c75fcknbfr5ysz9";
```suggestion
    sha256 = "11h75dsbv3rs03pl67hdd3lbim7wjzh257ij9c75fcknbfr5ysz9";
    useOMP2 = true;
```

2021-03-07 01:05 UTC, SuperSandro2000 commented on pkgs/development/ocaml-modules/ppx_deriving/default.nix
> +    (if params.useOMP2 or true
```suggestion
    (if params.useOMP2
```

2021-03-07 01:05 UTC, SuperSandro2000 commented on pkgs/top-level/ocaml-packages.nix
> +    ppx_cstubs = callPackage ../development/ocaml-modules/ppx_cstubs {};
```suggestion
    ppx_cstubs = callPackage ../development/ocaml-modules/ppx_cstubs { };
```

2021-03-08 10:40 UTC, osener commented
@SuperSandro2000 Thanks for the review! I've applied your suggestions.

2021-03-08 11:07 UTC, vbgl approved these changes

2021-03-10 22:53 UTC, SuperSandro2000 reviewed
diff LGTM, not sure if it is ocaml wise LGTM

2021-03-11 07:28 UTC, merged