python3: 3.8 -> 3.9
NixOS/nixpkgs pull request #116304
Opened 2021-03-14 11:19 UTC by FRidh

###### Motivation for this change

Change the default interpreter in Nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-14 11:20 UTC, FRidh commented
Tested locally with 9ac0881ba68b999c36308bcae4f95b034e24a372.

2021-03-14 11:45 UTC, dotlambda requested changes

2021-03-14 11:45 UTC, dotlambda commented on doc/languages-frameworks/python.section.md
> +Versions 2.7, 3.6, 3.7, 3.8 and 3.8 of the CPython interpreter are available as
```suggestion
Versions 2.7, 3.6, 3.7, 3.8 and 3.9 of the CPython interpreter are available as
```

2021-03-14 11:45 UTC, dotlambda commented on doc/languages-frameworks/python.section.md
>  `python39`. The attribute `python` maps to `python2`. The PyPy interpreters
This seems to have been wrong before this change.

2021-03-14 15:49 UTC, SuperSandro2000 commented
I am not sure if we should wait a little longer. There are quite some packages which are disabled on python39.

2021-07-13 08:56 UTC, vcunat commented
The version has been switched, but I think at least some part of these docs changes is still missing from current NixPkgs.

2021-07-15 07:01 UTC, FRidh commented
Done in https://github.com/NixOS/nixpkgs/pull/128634

2021-07-15 07:01 UTC, closed without merging