bepasty: 0.5.0 -> 1.0.0
NixOS/nixpkgs pull request #116429
Opened 2021-03-15 15:12 UTC by pinpox

###### Motivation for this change
https://github.com/NixOS/nixpkgs/issues/116326

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-15 15:14 UTC, dotlambda requested changes
You need to update `sha256`.

2021-03-15 15:25 UTC, pinpox commented
@dotlambda can you help me out? how do I get the sha256 for pypi references?

2021-03-15 15:39 UTC, SuperSandro2000 commented
> @dotlambda can you help me out? how do I get the sha256 for pypi references?

use nix-update or invalidate it and put the one in nix-build expected.

2021-03-15 16:32 UTC, dotlambda commented
> use nix-update or invalidate it and put the one in nix-build expected.

Invalidating meaning replacing e.g. a leading 1 with a 0.
For PyPI, you get also get it from https://pypi.org/project/bepasty/#copy-hash-modal-9b2695cc-eba4-41ec-9369-d9bf4bdaaeda.

2021-03-15 18:20 UTC, pinpox commented
> > use nix-update or invalidate it and put the one in nix-build expected.
> 
> Invalidating meaning replacing e.g. a leading 1 with a 0.
> For PyPI, you get also get it from https://pypi.org/project/bepasty/#copy-hash-modal-9b2695cc-eba4-41ec-9369-d9bf4bdaaeda.

I say the hashes shown on pypi.org, but they have they have the wrong length:
Old hash: 1y3smw9620w2ia4zfsl2svb9j7mkfgc8z1bzjffyk1w5vryhwikh
pypy : ae06ffc4562f678e09506c3e4587c955f83ab2d13fcbf62363a5d2c0edf64247

EDIT: I updated the hash with `nix-update` as @SuperSandro2000  suggested, shoud be right now.

2021-03-15 20:53 UTC, dotlambda requested changes
```
  ERROR: Could not find a version that satisfies the requirement XStatic-asciinema-player (from bepasty)
  ERROR: No matching distribution found for XStatic-asciinema-player
```

2021-03-16 00:06 UTC, pinpox commented
@dotlambda I copied one of the existing pypi modules and adapted it. Not very experienced with python packaging, hope I got that right. There where two libs missing.

2021-03-16 08:06 UTC, dotlambda requested changes
Since Font Awesome is already packaged in Nixpkgs, we should make use of https://xstatic.readthedocs.io/en/latest/packaging.html#notes-for-linux-or-other-os-package-maintainers for it.

We could also add a `checkPhase` that runs a little Python script:
```py
from xstatic.main import XStatic
__import__('xstatic.pkg', fromlist=['font-awesome'])
```

2021-03-16 08:06 UTC, dotlambda commented
Btw, you need to have exactly one commit per package.

2021-06-16 20:50 UTC, makefu requested changes
after these changes bepasty builds again, however i have not yet tested it

2021-06-16 20:50 UTC, makefu commented on pkgs/development/python-modules/xstatic-asciinema-player/default.nix
> +  };
```patch
diff --git a/pkgs/development/python-modules/xstatic-asciinema-player/default.nix b/pkgs/development/python-modules/xstatic-asciinema-player/default.nix
index e281f67387a..7605a2aabf5 100644
--- a/pkgs/development/python-modules/xstatic-asciinema-player/default.nix
+++ b/pkgs/development/python-modules/xstatic-asciinema-player/default.nix
@@ -6,7 +6,8 @@ buildPythonPackage rec {
 
 
   src = fetchPypi {
-    inherit pname version;
+    pname = "XStatic-asciinema-player";
+    inherit version;
     sha256 = "c80e960b4ebb4adf360e6e92b5a08a756ad106198d7a6b307ad20ef22a1d7dcc";
   };
```

2021-06-16 20:50 UTC, makefu commented on pkgs/tools/misc/bepasty/default.nix
> +        });
The override must be deleted. bepasty uses now boostrap4 (which is what we have in the repo)

2021-06-16 20:54 UTC, makefu commented
when running `bepasty-server`:
```
[nix-shell:~/.cache/nixpkgs-review/pr-116429-1/nixpkgs]$ /nix/store/f33bd2pzfdq1753zsn2f63hvmz1fg3q3-python3.8-bepasty-1.0.0/bin/bepasty-server --port 9999
Error processing line 3 of /nix/store/wcl7qma99g31s3c78zvxlqcfkxpavj9d-python3.8-XStatic-1.0.2/lib/python3.8/site-packages/XStatic-1.0.2-py3.8-nspkg.pth:

  Traceback (most recent call last):
    File "/nix/store/66fbv9mmx1j4hrn9y06kcp73c3yb196r-python3-3.8.9/lib/python3.8/site.py", line 169, in addpackage
      exec(line)
    File "<string>", line 1, in <module>
    File "<frozen importlib._bootstrap>", line 553, in module_from_spec
  AttributeError: 'NoneType' object has no attribute 'loader'

Remainder of file ignored
 * Starting bepasty server...
 * Serving Flask app "bepasty.app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:9999/ (Press CTRL+C to quit)
127.0.0.1 - - [16/Jun/2021 22:52:26] "GET / HTTP/1.1" 200 -
```
there are some errors regarding xstatic, however it may not be an issue here? the page looks okay when loading it:
![image](https://user-images.githubusercontent.com/115218/122292052-d6bdbb80-cef5-11eb-879a-ccc6e9f2355b.png)

2021-06-16 22:57 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xstatic-font-awesome/default.nix
> +  pname = "XStatic-Font-Awesome";
```suggestion
  pname = "xstatic-font-awesome";
```
attr and pname should match most of the time.

2021-06-16 22:57 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xstatic-font-awesome/default.nix
> +    inherit pname version;
```suggestion
    pname = "XStatic-Font-Awesome";
    inherit version;
```

2022-04-08 19:25 UTC, Lassulus commented
So what's up here?

2022-04-09 18:22 UTC, makefu commented
for me it looks good, i guess we can merge?

2022-04-09 21:44 UTC, Lassulus commented
Result of `nixpkgs-review pr 116429` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages failed to build:</summary>
  <ul>
    <li>bepasty</li>
    <li>python38Packages.xstatic-asciinema-player</li>
    <li>python39Packages.xstatic-asciinema-player</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.xstatic-font-awesome</li>
    <li>python39Packages.xstatic-font-awesome</li>
  </ul>
</details>

2022-04-09 21:44 UTC, Lassulus commented
does not look very good :D

2022-04-11 06:55 UTC, pinpox commented
Sorry, I don't currently have the time to continue on this PR. Anybody is welcome to pick it up

2023-06-14 13:12 UTC, closed without merging