pythonPackages.fipy: 3.4.1 -> 3.4.2.1
NixOS/nixpkgs pull request #116567
Opened 2021-03-17 00:03 UTC by wd15

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-17 00:11 UTC, wd15 commented
Result of `nixpkgs-review pr 116567` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.fipy</li>
    <li>python39Packages.fipy</li>
  </ul>
</details>

2021-03-17 10:08 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 116567` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>python38Packages.fipy</li>
<li>python39Packages.fipy</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python38Packages.fipy:
<details>


warning: duplicate-check-inputs
Dependencies listed in `propagatedBuildInputs` should not be repeated in `checkInputs`.

Detected duplicates:

- gmsh-4.8.0

Near pkgs/development/python-modules/fipy/default.nix:45:5:

```
   |
45 |     checkInputs = not_darwin_inputs;
   |     ^
```

Near pkgs/development/python-modules/fipy/default.nix:33:5:

```
   |
33 |     propagatedBuildInputs = [
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/duplicate-check-inputs.md
warning: unused-argument
Unused argument: `fetchPypi`.
Near pkgs/development/python-modules/fipy/default.nix:3:3:

```
  |
3 | , fetchPypi
  |   ^
```
</details>
</details>

2021-03-17 19:36 UTC, SuperSandro2000 requested changes

2021-03-17 19:36 UTC, SuperSandro2000 commented on pkgs/development/python-modules/fipy/default.nix
>      ] ++ lib.optionals isPy27 [ pysparse ] ++ not_darwin_inputs;
```suggestion
    ] ++ lib.optionals isPy27 [ pysparse ]
      ++ lib.optionals !stdenv.isDarwin [ gmsh ];
```

2021-03-17 19:36 UTC, SuperSandro2000 commented on pkgs/development/python-modules/fipy/default.nix
>  in
and now this can be removed.

2021-03-17 19:51 UTC, wd15 commented on pkgs/development/python-modules/fipy/default.nix
>      ] ++ lib.optionals isPy27 [ pysparse ] ++ not_darwin_inputs;
done

2021-03-17 19:51 UTC, wd15 commented on pkgs/development/python-modules/fipy/default.nix
>  in
done

2021-03-22 12:45 UTC, wd15 commented
This should be ready to merge now.

2021-04-06 01:11 UTC, SuperSandro2000 commented on pkgs/development/python-modules/fipy/default.nix
> +    ++ lib.optionals (! stdenv.isDarwin) [ gmsh ];
```suggestion
  ++ lib.optionals (!stdenv.isDarwin) [ gmsh ];
```

2021-04-06 09:59 UTC, merged