libplctag: init at v2.3.5
NixOS/nixpkgs pull request #116552
Opened 2021-03-16 21:10 UTC by storvik

###### Motivation for this change

Add library libplctag. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-16 21:39 UTC, SuperSandro2000 requested changes

2021-03-16 21:39 UTC, SuperSandro2000 commented on pkgs/development/libraries/libplctag/default.nix
> +  };
```suggestion
  src = fetchurl {
    url = "https://github.com/libplctag/libplctag/archive/v${version}.tar.gz";
    sha256 = "16azdxyl82js17xcav7v23zvi64w72181wylj489zim9x5h5sxsr";
  };
  
  nativeBuildInputs = [ cmake ];
```

2021-03-16 21:39 UTC, SuperSandro2000 commented on pkgs/development/libraries/libplctag/default.nix
> +    license = [ licenses.lgpl2Plus licenses.mpl20 ];
```suggestion
    license = with licenses; [ lgpl2Plus mpl20 ];
```

2021-03-16 21:39 UTC, SuperSandro2000 commented on pkgs/development/libraries/libplctag/default.nix
> +    maintainers = [ maintainers.petterstorvik ];
```suggestion
    maintainers = with maintainers; [ petterstorvik ];
```

2021-03-16 21:39 UTC, SuperSandro2000 commented on pkgs/development/libraries/libplctag/default.nix
> +    url = "https://github.com/libplctag/libplctag/archive/v${version}.tar.gz";
Please use fetchFromGitHub.

2021-03-16 21:54 UTC, storvik commented
Thanks for feedback @SuperSandro2000, changes have been committed.

2021-03-18 23:06 UTC, SuperSandro2000 requested changes

2021-03-18 23:06 UTC, SuperSandro2000 commented on pkgs/development/libraries/libplctag/default.nix
> +    repo = "libpcltag";
```suggestion
    repo = "libplctag";
```

2021-03-19 17:37 UTC, merged