flawfinder: init at 2.0.15
NixOS/nixpkgs pull request #117417
Opened 2021-03-23 23:29 UTC by fabaff

###### Motivation for this change
Tool to examines C/C++ source code for security flaws

http://dwheeler.com/flawfinder

Related to #81418

Fixes #117382

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-23 23:32 UTC, fabaff commented
Result of `nixpkgs-review pr 117417` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flawfinder</li>
  </ul>
</details>

2021-03-23 23:43 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 117417` at 90894a7d run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>flawfinder</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/development/tools/flawfinder/default.nix:23:3:
```
   |
23 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `coreutils`.
Near pkgs/development/tools/flawfinder/default.nix:3:3:
```
  |
3 | , coreutils
  |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `makeWrapper`.
Near pkgs/development/tools/flawfinder/default.nix:6:3:
```
  |
6 | , makeWrapper
  |   ^
```
</li>
  </ul>
</details>

2021-03-24 07:22 UTC, fabaff commented
Result of `nixpkgs-review pr 117417` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>flawfinder</li>
  </ul>
</details>

2021-03-24 15:42 UTC, SuperSandro2000 requested changes

2021-03-24 15:42 UTC, SuperSandro2000 commented on pkgs/development/tools/flawfinder/default.nix
> +    url = "http://dwheeler.com/flawfinder/flawfinder-${version}.tar.gz";
```suggestion
    url = "https://dwheeler.com/flawfinder/flawfinder-${version}.tar.gz";
```

2021-03-24 15:42 UTC, SuperSandro2000 commented on pkgs/development/tools/flawfinder/default.nix
> +    homepage = "http://dwheeler.com/flawfinder/";
```suggestion
    homepage = "https://dwheeler.com/flawfinder/";
```

2021-03-24 21:47 UTC, fabaff commented on pkgs/development/tools/flawfinder/default.nix
> +    url = "http://dwheeler.com/flawfinder/flawfinder-${version}.tar.gz";
Updated, thanks.

2021-03-24 21:47 UTC, fabaff commented on pkgs/development/tools/flawfinder/default.nix
> +    homepage = "http://dwheeler.com/flawfinder/";
Updated, thanks.

2021-03-26 17:07 UTC, merged