ocaml-ng.ocamlPackages_4_12.js_of_ocaml: 3.8.0 -> 3.9.1
NixOS/nixpkgs pull request #117482
Opened 2021-03-24 15:13 UTC by sternenseemann

eliom is kind of holding back our update of js_of_ocaml. Since
js_of_ocaml 3.8.0 is not available for 4.12, let's update js_of_ocaml
for 4.12 only for now, since we wouldn't be able to support eliom there
anyways.

This unbreaks a lot of packages because --with-js_of_ocaml defaults to
true for a lot of packages, leading to a lot of breakage due to packages
like mtime. Updating js_of_ocaml is much simpler than conditionally
disabling the flag for 4.12.

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-24 15:15 UTC, sternenseemann commented
@ofborg build ocamlPackages.eliom ocaml-ng.ocamlPackages_4_12.js_of_ocaml ocaml-ng.ocamlPackages_4_12.mtime

2021-03-24 21:40 UTC, sternenseemann commented
@ofborg build ocamlPackages.eliom ocaml-ng.ocamlPackages_4_12.js_of_ocaml ocaml-ng.ocamlPackages_4_12.mtime

2021-03-25 07:45 UTC, vbgl requested changes
I don’t adhere to the reasoning behind this PR. IMHO it is less complex and more useful to fix #114263 and update jsoo for all versions of OCaml.

2021-03-25 10:25 UTC, sternenseemann commented
> I don’t adhere to the reasoning behind this PR. IMHO it is less complex and more useful to fix #114263 and update jsoo for all versions of OCaml.

Fair enough. I just noticed that upstream has a patch for eliom already, just no new release. Until that happens we can just fetchpatch it and update js_of_ocaml for all versions.

2021-03-25 10:26 UTC, sternenseemann commented
@ofborg build ocamlPackages.eliom

2021-03-26 07:43 UTC, merged

2021-03-26 07:43 UTC, vbgl commented
Thank you very much!