GNOME 40 fixups
NixOS/nixpkgs pull request #117535
Opened 2021-03-24 23:08 UTC by maxeaubrey

###### Motivation for this change
For #117081

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-24 23:35 UTC, SuperSandro2000 requested changes

2021-03-24 23:35 UTC, SuperSandro2000 commented on pkgs/desktops/gnome-3/apps/gnome-calendar/default.nix
> -    (fetchpatch {
Please remove fetchpatch from inputs.

2021-03-24 23:35 UTC, SuperSandro2000 commented on pkgs/desktops/gnome-3/core/gnome-session/default.nix
> -    (fetchpatch {
Please remove fetchpatch from inputs.

2021-03-25 00:02 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 117535` at a275df65 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages skipped due to time constraints:</summary>
  <ul>
    <li>gnome3.gnome-calendar</li>
    <li>gnome3.gnome-session (gnome3.gnome_session)</li>
    <li>pantheon.elementary-session-settings</li>
  </ul>
</details>
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>cantarell-fonts</li>
    <li>orca (gnome3.orca)</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/data/fonts/cantarell-fonts/default.nix:34:5:
```
   |
34 |     maintainers = with lib.maintainers; [ ];
   |     ^
```
</li>
  </ul>
</details>

2021-03-25 05:42 UTC, merged

2021-03-25 05:42 UTC, jtojnar commented
Thanks.