alertmanager-irc-relay: init at 0.3.0
NixOS/nixpkgs pull request #117759
Opened 2021-03-27 06:56 UTC by ymatsiuk

###### Motivation for this change
closes #117178

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-27 07:29 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 117759` at 036f61fc run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>alertmanager-irc-relay</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `stdenv`.
Near pkgs/servers/monitoring/alertmanager-irc-relay/default.nix:1:8:
```
  |
1 | { lib, stdenv, buildGoModule, fetchFromGitHub }:
  |        ^
```
</li>
  </ul>
</details>

2021-03-27 22:10 UTC, SuperSandro2000 requested changes

2021-03-27 22:10 UTC, SuperSandro2000 commented on pkgs/servers/monitoring/alertmanager-irc-relay/default.nix
> +  pname = "alertmanager-irc-relay";
```suggestion
buildGoModule rec {
  pname = "alertmanager-irc-relay";
```

2021-03-27 22:10 UTC, SuperSandro2000 commented on pkgs/servers/monitoring/alertmanager-irc-relay/default.nix
> +
One new line to much.

2021-03-27 22:10 UTC, SuperSandro2000 commented on pkgs/servers/monitoring/alertmanager-irc-relay/default.nix
> +    platforms = platforms.unix;
```suggestion
```

set by buildGoModule to this exact value.

2021-04-08 07:55 UTC, ymatsiuk commented
@SuperSandro2000 is there anything that blocks this from merging?

2021-04-12 00:10 UTC, merged