add new i3wm package: i3-auto-laout
NixOS/nixpkgs pull request #117870
Opened 2021-03-28 09:01 UTC by Mephistophiles

###### Motivation for this change
Adding a new layout helper for i3wm.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-28 16:41 UTC, SuperSandro2000 requested changes
You forgot to include the package.

2021-03-28 16:41 UTC, SuperSandro2000 commented on pkgs/applications/window-managers/i3/auto-layout.nix
> +    maintainers = [ ];
Adding yourself as a maintainer is required.

2021-03-28 16:41 UTC, SuperSandro2000 commented on pkgs/applications/window-managers/i3/auto-layout.nix
> +    rev = "v0.2";
This should reuse version.

2021-03-28 16:41 UTC, SuperSandro2000 commented on pkgs/applications/window-managers/i3/auto-layout.nix
> +{ lib, rustPlatform, pkgs, pkg-config }:
```suggestion
{ lib, rustPlatform, pkg-config }:
```

2021-03-28 18:25 UTC, Mephistophiles commented on pkgs/applications/window-managers/i3/auto-layout.nix
> +    rev = "v0.2";
Done

2021-03-28 18:26 UTC, Mephistophiles commented
> You forgot to include the package.

Oops, fixed. Thanks for the review!

2021-03-28 19:18 UTC, dotlambda requested changes
Commit message and pull request title have a typo.

2021-03-28 19:18 UTC, dotlambda commented on pkgs/applications/window-managers/i3/auto-layout.nix
> +{ lib, rustPlatform, fetchFromGitHub, pkg-config }:
```suggestion
{ lib, rustPlatform, fetchFromGitHub }:
```

2021-03-28 19:30 UTC, Mephistophiles commented
> Commit message and pull request title have a typo.

Fixed, thanks!

2021-03-31 11:19 UTC, dotlambda requested changes
Does it build for you?

2021-03-31 11:19 UTC, dotlambda commented on pkgs/applications/window-managers/i3/auto-layout.nix
> +    rev = "v{version}";
```suggestion
    rev = "v${version}";
```

2021-03-31 12:33 UTC, Mephistophiles commented
> Does it build for you?

Oh, sorry, the result was cached from the previous build. Fixed and tested on the clean build.

2021-03-31 13:36 UTC, merged

2021-03-31 15:36 UTC, Mephistophiles commented
Thanks for the review!