gmni{,srv}: init at 2021-03-26
NixOS/nixpkgs pull request #118056
Opened 2021-03-30 12:12 UTC by jb55

- gmni: init at 2021-03-26
- gmnisrv: init at 2021-03-26

2021-03-30 12:31 UTC, SuperSandro2000 requested changes
if you are using mailcap just for mime-types it can be replaced with https://github.com/NixOS/nixpkgs/blob/master/pkgs/data/misc/mime-types/default.nix.

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/servers/gemini/gmnisrv/default.nix
> +  meta = with lib; {
```suggestion
  buildInputs = [ openssl mailcap scdoc ];

  meta = with lib; {
```

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/servers/gemini/gmnisrv/default.nix
> +    license = licenses.gpl3;
gpl3Only or gpl3Plus?

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/servers/gemini/gmnisrv/default.nix
> +  src = fetchFromSourcehut {
```suggestion
  version = "unstable-2021-03-26";

  src = fetchFromSourcehut {
```

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/servers/gemini/gmnisrv/default.nix
> +  MIMEDB = "${mailcap}/etc/mime.types";
```suggestion
  };

  MIMEDB = "${mailcap}/etc/mime.types";
```

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/gmni/default.nix
> +    license = licenses.gpl3;
gpl3Only or gpl3Plus?

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/gmni/default.nix
> +  meta = with lib; {
```suggestion
  buildInputs = [ bearssl scdoc ];

  meta = with lib; {
```

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/gmni/default.nix
> +  nativeBuildInputs = [ pkg-config ];
```suggestion
  };

  nativeBuildInputs = [ pkg-config ];
```

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/gmni/default.nix
> +  src = fetchFromSourcehut {
```suggestion
  version = "unstable-2021-03-26";

  src = fetchFromSourcehut {
```

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/gmni/default.nix
> +{stdenv, lib, fetchFromSourcehut, pkg-config, bearssl, scdoc}:
```suggestion
{ stdenv, lib, fetchFromSourcehut, pkg-config, bearssl, scdoc }:
```

2021-03-30 12:31 UTC, SuperSandro2000 commented on pkgs/servers/gemini/gmnisrv/default.nix
> +{stdenv, lib, fetchFromSourcehut, pkg-config, openssl, mailcap, scdoc}:
```suggestion
{ stdenv, lib, fetchFromSourcehut, pkg-config, openssl, mailcap, scdoc }:
```

2021-03-30 12:38 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 118056` at 43956f38 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/48f42016ba01d162075c79e2b8795c52">gmnisrv</a></li>
  </ul>
</details>
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>gmni</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/servers/gemini/gmnisrv/default.nix:18:5:
```
   |
18 |     license = licenses.gpl3;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/applications/networking/browsers/gmni/default.nix:17:5:
```
   |
17 |     license = licenses.gpl3;
   |     ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

2021-03-30 14:45 UTC, bsima commented
> 1 package failed to build:
>   - gmnisrv

Idk why this is failing.... works on my machine...

```
hash mismatch in fixed-output derivation '/nix/store/3x2sr2197wl8ni9bmgaf33lnj3jmaahj-source':
  wanted: sha256:1n0iiz6gd3dmv1r7i6437zmrv0vim69fc0haqfvagd4y20hy5s8z
  got:    sha256:1d9rjx0s092yfzjxd2yvzixhqgg883nlnmsysgp21w75n2as354n
```

Both of these sha's work for me... I seem to recall that there are some weird bugs with the nix tarball cache, and maybe this is an instance of such?

Anyway I'll use the `1d9rjx` sha that the build server wants.

2021-03-30 15:15 UTC, SuperSandro2000 commented
> Both of these sha's work for me... I seem to recall that there are some weird bugs with the nix tarball cache, and maybe this is an instance of such?

This is not a bug but a feature. You have locally cached both tarballs but others cannot reproduce them.

2021-03-30 15:16 UTC, SuperSandro2000 commented
> I think gpl3Only? Really not sure what the differences are, the texts of each license on spdx.org look exactly the same to me...

if the project declares somewhere ``or later``. Most likely this is in source or in the readme, not the license itself.

2021-03-31 17:37 UTC, SuperSandro2000 requested changes

2021-03-31 17:37 UTC, SuperSandro2000 commented on pkgs/servers/gemini/gmnisrv/default.nix
> +  name = "gmnvisrv";
```suggestion
  pname = "gmnvisrv";
```

2021-03-31 17:37 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/gmni/default.nix
> +  name = "gmni";
```suggestion
  pname = "gmni";
```

2021-03-31 20:41 UTC, jb55 commented
On Wed, Mar 31, 2021 at 10:37:33AM -0700, Sandro wrote:
>@SuperSandro2000 requested changes on this pull request.
>  pname = "gmnvisrv";
>  pname = "gmni";

good catch, thanks. pushed a fix for these

2021-03-31 23:11 UTC, bsima commented on pkgs/servers/gemini/gmnisrv/default.nix
> +  pname = "gmnvisrv";
ah I typo'd, there's an extra `v`

```diff
-gmnvisrv
+gmnisrv
```

2021-04-01 01:37 UTC, jb55 commented
On Wed, Mar 31, 2021 at 04:11:49PM -0700, Ben Sima wrote:
***@***.*** commented on this pull request.
>+stdenv.mkDerivation rec {
>+  pname = "gmnvisrv";

Might have been me in last amend. Fixed.

2021-04-01 11:55 UTC, merged