gem-config.mathematical: add lasem to rpath
NixOS/nixpkgs pull request #118110
Opened 2021-03-30 20:32 UTC by dcbaker

###### Motivation for this change

This is #87832 rebased on current master, with merge conflicts resolved (which were caused simply by renamed import). As the rebase was absolutely trivial, I've left @Twey's authorship intact

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-03-30 21:59 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 118110` at 4841a233 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>476 packages marked as broken and skipped:</summary>
  <ul>
    <li>agdaPackages.iowa-stdlib</li>
    <li>aldor</li>
    <li>aqemu</li>
    <li>atom-beta</li>
    <li>autotrace</li>
    <li>awsebcli</li>
    <li>bareos</li>
    <li>bonfire</li>
    <li>cassandra_2_1</li>
    <li>cassandra_2_2</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>12437 packages skipped due to time constraints:</summary>
  <ul>
    <li>DisnixWebService</li>
    <li>EBTKS</li>
    <li>Fabric (python38Packages.Fabric)</li>
    <li>MIDIVisualizer</li>
    <li>R</li>
    <li>Sylk</li>
    <li>_1password-gui</li>
    <li>abcl</li>
    <li>abiword</li>
    <li>accountsservice</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>22 packages built successfully:</summary>
  <ul>
    <li>asciidoctor</li>
    <li>cargo</li>
    <li>git</li>
    <li>git-latexdiff</li>
    <li>git-recent</li>
    <li>git-test</li>
    <li>kakounePlugins.powerline-kak</li>
    <li>python38Packages.betamax</li>
    <li>python38Packages.cryptography</li>
    <li>python38Packages.factory_boy</li>
    <li>python38Packages.flask</li>
    <li>python38Packages.flask_sqlalchemy</li>
    <li>python38Packages.pyftpdlib</li>
    <li>python38Packages.pyopenssl</li>
    <li>python38Packages.pytest-localserver</li>
    <li>python38Packages.requests</li>
    <li>python38Packages.responses</li>
    <li>python38Packages.service-identity</li>
    <li>python38Packages.sphinx</li>
    <li>python38Packages.trustme</li>
    <li>python38Packages.urllib3</li>
    <li>python38Packages.werkzeug</li>
  </ul>
</details>

2021-03-31 00:39 UTC, SuperSandro2000 commented
/rebase staging

2021-03-31 01:22 UTC, SuperSandro2000 requested changes
Can't we put patchelf into nativeBuildInputs?

2021-03-31 01:22 UTC, SuperSandro2000 commented on pkgs/development/ruby-modules/gem-config/default.nix
>          "$soPath"
```suggestion
      ${patchelf}/bin/patchelf --replace-needed liblasem.so liblasem-0.4.so "$soPath"
```

2021-03-31 01:22 UTC, SuperSandro2000 commented on pkgs/development/ruby-modules/gem-config/default.nix
>        ${patchelf}/bin/patchelf \
```suggestion
```

2021-03-31 01:22 UTC, SuperSandro2000 commented on pkgs/development/ruby-modules/gem-config/default.nix
> +        "$soPath"
```suggestion
        ${patchelf}/bin/patchelf --set-rpath "${lib.makeLibraryPath [ lasem glib cairo ]}:$rpath" "$soPath"
```

2021-03-31 21:07 UTC, dcbaker commented
I think that's addressed the review comments. I did a quick test and everything seems to be working still.

2021-04-01 22:54 UTC, SuperSandro2000 commented
> I think that's addressed the review comments. I did a quick test and everything seems to be working still.

and I before checked that the library is really missing and the name of the library in nixpkgs is differnet.

2021-04-01 22:54 UTC, merged