squashfs-tools-ng: 1.0.4 -> 1.1.0
NixOS/nixpkgs pull request #118284
Opened 2021-04-01 21:15 UTC by alyssais

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-04-01 21:36 UTC, SuperSandro2000 requested changes
other than that the diff LGTM

2021-04-01 21:36 UTC, SuperSandro2000 commented on pkgs/tools/filesystems/squashfs-tools-ng/default.nix
> +{ stdenv, lib, fetchurl, doxygen, graphviz, perl, pkgconfig
Please revert that change as it fails ofborg no aliases check.

2021-04-01 21:36 UTC, SuperSandro2000 commented on pkgs/tools/filesystems/squashfs-tools-ng/default.nix
> +  nativeBuildInputs = [ doxygen graphviz pkgconfig perl ];
same here.

2021-04-01 21:43 UTC, alyssais commented
Oh, thanks for catching the pkgconfig thing -- I wrote the patch in an
old version of Nixpkgs and then copied it to a recent one.  Oops. :)

2021-04-01 21:45 UTC, alyssais commented
@SuperSandro2000 would you mind checking whether this is still broken on Darwin?

2021-04-02 16:20 UTC, SuperSandro2000 commented
> @SuperSandro2000 would you mind checking whether this is still broken on Darwin?

yeah
```
Undefined symbols for architecture x86_64:
  "_utimensat", referenced from:
      _set_attribs in rdsquashfs-restore_fstree.o
ld: symbol(s) not found for architecture x86_64
```

2021-04-02 16:20 UTC, merged