betterdiscordctl: 1.7.0 -> 1.7.1
NixOS/nixpkgs pull request #118361
Opened 2021-04-02 20:38 UTC by IvarWithoutBones

###### Motivation for this change
Bump the package, and removing the patch adding nix support as this was merged upstream.

Thank you to @ObserverOfTime for informing me this was released :)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-04-02 20:47 UTC, iAmMrinal0 commented
Result of `nixpkgs-review pr 118361` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>betterdiscordctl</li>
  </ul>
</details>

2021-04-02 22:19 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 118361` at c283daf3 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>betterdiscordctl</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/tools/misc/betterdiscordctl/default.nix:16:3:
```
   |
16 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/tools/misc/betterdiscordctl/default.nix:1:33:
```
  |
1 | { lib, stdenv, fetchFromGitHub, fetchpatch }:
  |                                 ^
```
</li>
  </ul>
</details>

2021-04-03 00:08 UTC, SuperSandro2000 requested changes

2021-04-03 00:08 UTC, SuperSandro2000 commented on pkgs/tools/misc/betterdiscordctl/default.nix
> -    (fetchpatch { # Required till https://github.com/bb010g/betterdiscordctl/pull/67 is merged upstream.
Please remove fetchpatch from inputs.

2021-04-03 07:39 UTC, ObserverOfTime commented
Coincidentally, can you verify whether the new [beta installer](https://github.com/BetterDiscord/Installer) works OOTB and maybe package that one too later?

2021-04-03 13:48 UTC, IvarWithoutBones commented
> Incidentally, can you verify whether the new [beta installer](https://github.com/BetterDiscord/Installer) works OOTB and maybe package that one too later?

I'll work on package that later, thanks for letting me know!

2021-04-03 13:48 UTC, IvarWithoutBones commented on pkgs/tools/misc/betterdiscordctl/default.nix
> -    (fetchpatch { # Required till https://github.com/bb010g/betterdiscordctl/pull/67 is merged upstream.
@SuperSandro2000 fixed :)

2021-04-05 00:49 UTC, merged