Add “place-cursor-at” package to “release-20.09”
NixOS/nixpkgs pull request #118845
Opened 2021-04-08 19:36 UTC by unclechu

###### Motivation for this change

In current `master` it was just picked from `haskellPackages` in top-level packages (see #118598). But in `release-20.09` this package wasn’t picked from Hackage yet (see failed attempt to backport #118626). So this MR just directly pins the version from the source repo. 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-04-08 19:44 UTC, SuperSandro2000 commented
Please follow https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#backporting-changes to backport a commit.

2021-04-08 19:51 UTC, unclechu commented
@SuperSandro2000 Please read the description. It is impossible to simply backport it (see #118626).

2021-04-08 21:01 UTC, sternenseemann requested changes

2021-04-08 21:54 UTC, unclechu commented on pkgs/applications/misc/place-cursor-at/default.nix
> +callPackage src {}
@sternenseemann It’s now fixed. Please check.

2021-04-12 19:56 UTC, unclechu commented
@sternenseemann Are there any more changes I’m supposed to make? What would be an acceptance criteria?

2021-04-15 09:21 UTC, sternenseemann commented
can you wrap the mkDerivation with justStaticExecutables? Should save on runtime closure possibly.

2021-04-15 16:28 UTC, unclechu commented
@sternenseemann for some reason it fails:

``` sh
nix run -I nixpkgs=. nixpkgs.place-cursor-at -c place-cursor-at
```
```
error: anonymous function at .../nixpkgs/pkgs/development/haskell-modules/generic-builder.nix:13:1 called with unexpected argument 'mkDerivation', at .../nixpkgs/lib/customisation.nix:69:16
```

I just took the flags that `justStaticExecutables` sets and added them to the derivation. Would this be okay?

2021-04-15 16:32 UTC, sternenseemann commented
Sure, doesn't really matter that much for this backport. Can you squash the commits?

2021-04-15 16:48 UTC, unclechu commented
@sternenseemann Squashed.

2021-04-15 20:01 UTC, sternenseemann commented
Can you also adjust the commit message according to [this](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes)?

2021-04-15 20:22 UTC, unclechu commented
@sternenseemann Done

2021-04-15 20:34 UTC, merged