refactor pam-u2f: add keysPath, verbose, fix docs about u2f_keys path
NixOS/nixpkgs pull request #11886
Opened 2015-12-22 21:54 UTC by spinus

* change enableU2F option to U2F.* set
* add U2F.keysPath - specifies where u2f_keys file is located
* add U2F.verbose - display message when waiting for u2f device
* fix documentation about default u2f_keys locations

2015-12-22 23:02 UTC, copumpkin commented on nixos/modules/security/pam.nix
> +      U2F = {
Not a fan of starting the module name with uppercase, but am not sure if we have any official guidelines on that.

2015-12-22 23:03 UTC, copumpkin commented on nixos/modules/security/pam.nix
> +          default = config.security.pam.U2F.enabled;
Isn't this a circular default? Or what am I missing?

2015-12-22 23:04 UTC, spinus commented on nixos/modules/security/pam.nix
> +          default = config.security.pam.U2F.enabled;
:) yup.

2015-12-22 23:05 UTC, copumpkin commented
Why the duplicate module?

2015-12-22 23:07 UTC, spinus commented on nixos/modules/security/pam.nix
> +      U2F = {
I'm big fan of "this-notation" or "this_notation" but I'm not sure we want that here. Some packages are using this convention, but I didn't see that for options.

Here I followed something like, camelCase but if the first letter is big I'm making it smaller just for naming sake. the same I would do if the name would started with API I wouldn't do apiSomething.

But I can use whatever convention is agreed :-)

2015-12-22 23:07 UTC, copumpkin commented on nixos/modules/security/pam.nix
> +      U2F = {
https://github.com/Yubico/pam-u2f Yubico themselves seem to have no trouble keeping it lowercase

2015-12-22 23:10 UTC, spinus commented on nixos/modules/security/pam.nix
> +      U2F = {
True.
Is that good occasion to move that decision to mailing list or ticket and make some naming convention agreements? I saw one ticket about that but as far as I remember it stucked.

2015-12-22 23:10 UTC, spinus commented
What do you mean?

2015-12-23 14:05 UTC, copumpkin commented
@spinus as far as I can tell, you have two copies of all the U2F options, first in the `let` block, and then in the final returned attrset. They have identical (as far as I can eyeball) documentation, types, and names.

2015-12-23 14:20 UTC, spinus commented
The reason for this is (I guess), the "top" layer works as defaults for all pam services, the other one is per service.

example:
```
config.security.pam.U2F.enabled = True
config.security.pam.services.<name?>.U2F.enabled=False
```
So you can enable it globally and disable for particular modules.
For each service there is the same set of options which get defaults from "global" services config.
It was like that before but only one option was passed down the hole and the name was different. My idea is to unify this names to understand that you are changing the same thing (previously the names were enabledU2F and u2fAuth, so not only different name but different naming convention as well).

The problem I have here, I have no idea how to grab description from "outer" scope the same I grabbed the default value so I copy pasted as "good" start :)

2016-01-05 21:36 UTC, spinus commented
hey, can we move it a little? What I should do/fix to make this happen?

2016-01-11 21:14 UTC, spinus commented
@copumpkin hey, updated the name (U2F -> u2f), is it better now?

2016-01-23 03:11 UTC, spinus commented
@philandstuff @edolstra @obadz do you think this is good direction? Any idea how I could use description only once in current situation (I know I could extract it level up as variable, but that would be confusing probably)

2016-03-11 21:58 UTC, jagajaga commented
ping @copumpkin

2016-11-04 15:49 UTC, spacekitteh commented
@grahamc security :)

2016-11-28 03:59 UTC, fpletz requested changes

2016-11-28 03:59 UTC, fpletz commented on nixos/modules/security/pam.nix
> +        enabled = mkOption {
The attribute shoud be called `enable` like in every other module.

2016-11-28 03:59 UTC, fpletz commented on nixos/modules/security/pam.nix
> +      };
Both `u2f` options should be generated by a function instead auf copy-paste.

2016-11-28 03:59 UTC, fpletz commented on nixos/modules/security/pam.nix
> +                 '';
Wrong indention.

2016-11-28 12:38 UTC, spinus commented on nixos/modules/security/pam.nix
> +      };
@fpletz now, one year after I pushed that, I know lot more about nix :-) I try to refactor.

Thank you for your review.

2017-01-16 20:39 UTC, jb55 commented
status of this?

2017-01-17 00:08 UTC, spinus commented
@jb55 waits for me to refactor it, my current estimation is I'll take a look in next 2 weeks.

2017-03-24 12:19 UTC, makefu commented
any update on this? would love to see this in master 👍

2017-03-25 20:45 UTC, spinus commented
Yeah, I started working on it again in January, but during that year stuff has changed a little and I started doing it again rather then rebasing or anything. In the meantime I stuck somewhere there (I had a problem with nix expression evaluation). 

I was also wondering if the name should be changed to yubico (from u2f). Yubico has pam module named u2f but it looks like yubikey is supported but I'm not sure if that is universal or not. If it's universal, it's kine of unfortunate that default key files are named yubikey. What do you think?

2017-03-25 21:24 UTC, jb55 commented
Tomasz Czyż <notifications@github.com> writes:

> I was also wondering if the name should be changed to yubico (from u2f). Yubico has pam module named u2f but it looks like yubikey is supported but I'm not sure if that is universal or not. If it's universal, it's kine of unfortunate that default key files are named yubikey. What do you think?

It is universal, I have a trezor which works with pam-u2f.

2017-03-25 21:27 UTC, spinus commented
@jb55 thanks for info. In that case I'll just continue to refactor it as u2f. If I won't finish it to the end of mid-April, I'll post what I have until then and maybe somebody can continue.

2017-03-25 21:35 UTC, spinus commented
btw, I was thinking about writing a test for that module but I have no idea how to test that in the vm without the key :-) Any idea how we can test that module?

2017-04-18 01:43 UTC, spinus commented
OK, I understood a little better the structure in pam.nix and tried to extend it rather than changing convention like in my previous PR. So security.pam.u2f defines the options and they are set for all applications that use pam. Particular pam applications can use of not u2f by setting u2fAuth attribute (looks like that's how all other modules are set).

I added few (but not all) pam-u2f options.
I added really bad test, probably would be nice to have "software" device and do proper test like in oath module, but I'm not that familiar with u2f and don't have time to dive into it now. If anyone could provide any input I'm happy to implement proper test.

Please review :)

2017-05-03 00:35 UTC, jb55 commented
Tomasz Czyż <notifications@github.com> writes:
> Please review :)

I got around to testing this today. It seems to work for the initial
login and password prompts, but for some reason it breaks systemd user
services...

2017-05-08 18:31 UTC, spinus commented
@jb55 could you describe a little more the use case? I'll try to test that and fix.

2017-05-08 19:24 UTC, jb55 commented
Sure, if I remember correctly all I did was set it to `required` and
tried logging in. That worked fine but I noticed redshift wasn't
running. So I tried `systemctl start --user redshift` and I got an
error. I didn't have time to look into it further.

We could merge this and open a separate issue, as it seemed to work fine
other than that small hiccup.

2017-05-08 21:12 UTC, spinus commented
ah no, I would like not to break anything what is working, give me some time, I'll try to test it or even write test case or try to look if it's possible to limit u2f module to affect only "human" users (if it's affecting system users or whatever)

2017-05-23 16:02 UTC, ixmatus commented
I wanted to give my encouragement for this PR and that I'm willing to help if needed and where my spare time permits.

2018-10-22 03:20 UTC, spinus commented
@fpletz please take a look

2018-10-22 03:23 UTC, spinus commented
@fpletz please take a look

2019-01-22 02:39 UTC, kalbasit requested changes

2019-01-22 02:39 UTC, kalbasit commented on nixos/modules/security/pam.nix
> +        default = config.security.pam.u2f.enable;
can you please update https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/rename.nix to reflect this rename?

2019-01-22 02:39 UTC, kalbasit commented on nixos/modules/security/pam.nix
> +      authfile = mkOption {
can you add a new line between options? See above (same file) for examples.

2019-01-22 17:32 UTC, kalbasit requested changes

2019-01-22 17:32 UTC, kalbasit commented on nixos/modules/security/pam.nix
> +        default = "required";
It's currently set to `sufficient`, setting it to `required` might unexpectedly change the behavior for everyone. Please set this back to `sufficient`

2019-01-22 17:36 UTC, kalbasit requested changes

2019-01-22 17:36 UTC, kalbasit commented on nixos/tests/pam-u2f.nix
> +        debug=true;
please leave a space around the `=` signs

2019-01-22 17:36 UTC, kalbasit commented on nixos/tests/pam-u2f.nix
> +
nitpick: remove newline.

2019-01-28 03:25 UTC, closed without merging