Update git-review to 2.0.0
NixOS/nixpkgs pull request #118942
Opened 2021-04-09 22:26 UTC by packetizeme

###### Motivation for this change
* Updates git-review to latest version
* Fixes build error due to dependency on old version of six library

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-04-09 22:47 UTC, packetizeme commented
git-review 2.0.0 did remove python 2.7 support: [relevant upstream change](https://opendev.org/opendev/git-review/commit/375750389562bcd8d8e018eb9163b5b0979fbff1)

2021-04-10 19:35 UTC, MetaDark commented
Result of `nixpkgs-review pr 118942` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>git-review</li>
  </ul>
</details>

2021-04-10 19:35 UTC, MetaDark approved these changes
Thanks, @packetizeme! I just tested this out, and it looks good to me. I was using a stale RSS source and I just updated it to https://pypi.org/rss/project/git-review/releases.xml, so this shouldn't go a month with updating anymore.

This should close https://github.com/NixOS/nixpkgs/issues/119037.

2021-04-10 19:47 UTC, MetaDark requested changes
Oh, actually, I just realized that you change the commit message to `git-review: 1.28.0 -> 2.0.0` to follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)

2021-04-11 03:00 UTC, MetaDark approved these changes
Thanks

2021-04-11 03:04 UTC, packetizeme commented
> Oh, actually, I just realized that you should change the commit message to `git-review: 1.28.0 -> 2.0.0` to follow [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)

Thanks for catching this, I'll admit that I only just skimmed the contributing guidelines. Awesome to hear that you'll be monitoring changes in a way more likely to catch them quickly - thank you for your work maintaining this!

2021-04-11 04:43 UTC, merged