python3Packages.tables: fix build, add tests
NixOS/nixpkgs pull request #119258
Opened 2021-04-12 19:05 UTC by drewrisinger

###### Motivation for this change

While trying to open a HDF5 file via ``python3Packages.pandas``, realized that pandas' HDF5 functionality was broken b/c ``python3Packages.tables`` wasn't importing.

The main failure I was having was due to setuptools not being installed at runtime, but also noticed that tests weren't being run.
Trying to run the tests found that ``tables`` wasn't compatible with ``hdf5 v1.10.7`` (https://github.com/PyTables/PyTables/issues/845).

I know this probably needs a little bit of work/cleanup, just wanted to get some opinions on this.

Things tried:
* [x] building tables with hdf5 v1.10.7. See https://github.com/PyTables/PyTables/issues/845.
* [x] building tables with hdf5 v1.10.6. This didn't work, but I don't remember exact issue.
* [x] building tables with hdf5 v1.10.5. This did work.

Improvements:
* Update website address to HTTPS
* Add ``pythonImportsCheck``
* Run tests (via ``pytestCheckHook``)
* Add myself as maintainer

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-04-12 19:14 UTC, SuperSandro2000 commented
> so maybe we just revert the version of hdf5_1_10 to v1.10.5?

We already pulled in patches for 1.10.5 so reverting it is also work at this point.

2021-04-12 19:56 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 119258` at d4684190 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>59 packages marked as broken and skipped:</summary>
  <ul>
    <li>mlflow-server</li>
    <li>python38Packages.arviz</li>
    <li>python38Packages.caffe</li>
    <li>python38Packages.clifford</li>
    <li>python38Packages.cnvkit</li>
    <li>python38Packages.dask-gateway</li>
    <li>python38Packages.dask-jobqueue</li>
    <li>python38Packages.dask-ml</li>
    <li>python38Packages.dask-mpi</li>
    <li>python38Packages.dask-xgboost</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/98c5fd32a4894a614ea0d481f48a9afd">python39Packages.influxdb</a></li>
  </ul>
</details>
<details>
  <summary>307 packages skipped due to time constraints:</summary>
  <ul>
    <li>aiodnsbrute</li>
    <li>apache-airflow</li>
    <li>backblaze-b2</li>
    <li>check_systemd</li>
    <li>checkov</li>
    <li>conan</li>
    <li>cq-editor</li>
    <li>csvs-to-sqlite (python38Packages.csvs-to-sqlite)</li>
    <li>deja-dup</li>
    <li>dpt-rp1-py</li>
    <li>...</li>
  </ul>
</details>
<details>
  <summary>32 packages built successfully:</summary>
  <ul>
    <li>graph-cli</li>
    <li>python38Packages.Quandl (python38Packages.quandl)</li>
    <li>python38Packages.apptools</li>
    <li>python38Packages.bkcharts</li>
    <li>python38Packages.drms</li>
    <li>python38Packages.flammkuchen</li>
    <li>python38Packages.huggingface-hub</li>
    <li>python38Packages.influxdb</li>
    <li>python38Packages.mplfinance</li>
    <li>python38Packages.pandas</li>
    <li>python38Packages.partd</li>
    <li>python38Packages.phik</li>
    <li>python38Packages.pyezviz</li>
    <li>python38Packages.pytrends</li>
    <li>python38Packages.rapidfuzz</li>
    <li>python38Packages.seaborn</li>
    <li>python38Packages.tables</li>
    <li>python38Packages.tqdm</li>
    <li>python38Packages.vega_datasets</li>
    <li>python38Packages.vidstab</li>
    <li>python38Packages.yfinance</li>
    <li>python39Packages.bkcharts</li>
    <li>python39Packages.huggingface-hub</li>
    <li>python39Packages.mplfinance</li>
    <li>python39Packages.pandas</li>
    <li>python39Packages.partd</li>
    <li>python39Packages.pyezviz</li>
    <li>python39Packages.pytrends</li>
    <li>python39Packages.seaborn</li>
    <li>python39Packages.tables</li>
    <li>python39Packages.tqdm</li>
    <li>python39Packages.yfinance</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `python`.
Near pkgs/development/python-modules/tables/default.nix:7:3:
```
  |
7 | , python
  |   ^
```
</li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement.

2021-04-12 21:24 UTC, SuperSandro2000 requested changes
Please combine this PR into 2 or maybe 3 commits.

2021-04-27 09:01 UTC, FRidh commented
libminc also uses 1.10 https://github.com/NixOS/nixpkgs/pull/119572. More packages may show up.
Check with @bcdarwin for libminc if reverting version is OK. If it works for libminc then I'd say go ahead.

2021-04-28 14:56 UTC, drewrisinger commented
@bcdarwin gave consent for rolling back hdf5 by a patch-version in https://github.com/NixOS/nixpkgs/pull/119572#issuecomment-828040669. ``libminc`` builds fine locally.

2021-04-30 14:54 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 119258` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
38 packages marked as broken and skipped:
</summary>
<ul>
<li>mlflow-server</li>
<li>python38Packages.arviz</li>
<li>python38Packages.clifford</li>
<li>python38Packages.dask-jobqueue</li>
<li>python38Packages.dask-xgboost</li>
<li>python38Packages.dftfit</li>
<li>python38Packages.geopandas</li>
<li>python38Packages.lammps-cython</li>
<li>python38Packages.mlflow</li>
<li>python38Packages.mlxtend</li>
<li>python38Packages.optuna</li>
<li>python38Packages.osmnx</li>
<li>python38Packages.pymatgen-lammps</li>
<li>python38Packages.pymc3</li>
<li>python38Packages.rl-coach</li>
<li>python38Packages.shap</li>
<li>python38Packages.skorch</li>
<li>python38Packages.textacy</li>
<li>python38Packages.tiledb</li>
<li>python38Packages.trackpy</li>
<li>python39Packages.basemap</li>
<li>python39Packages.dask-jobqueue</li>
<li>python39Packages.dask-xgboost</li>
<li>python39Packages.geopandas</li>
<li>python39Packages.google-cloud-automl</li>
<li>python39Packages.google-cloud-bigquery</li>
<li>python39Packages.google-cloud-monitoring</li>
<li>python39Packages.lammps-cython</li>
<li>python39Packages.mlflow</li>
<li>python39Packages.mlxtend</li>
<li>python39Packages.optuna</li>
<li>python39Packages.osmnx</li>
<li>python39Packages.pymatgen-lammps</li>
<li>python39Packages.rl-coach</li>
<li>python39Packages.skorch</li>
<li>python39Packages.textacy</li>
<li>python39Packages.tiledb</li>
<li>python39Packages.trackpy</li>
</ul>
</details>
<details>

  <summary>58 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>apache-airflow: log was empty</li>
<li>backblaze-b2: log was empty</li>
<li>conan: log was empty</li>
<li>ocrmypdf: log was empty</li>
<li>python38Packages.aplpy: log was empty</li>
<li>python38Packages.apptools: log was empty</li>
<li>python38Packages.asdf: log was empty</li>
<li>python38Packages.cnvkit: log was empty</li>
<li>python38Packages.dask-image: log was empty</li>
<li>python38Packages.drms: log was empty</li>
<li>python38Packages.envisage: log was empty</li>
<li>python38Packages.graspologic: log was empty</li>
<li>python38Packages.imgaug: log was empty</li>
<li>python38Packages.ipydatawidgets: log was empty</li>
<li>python38Packages.labelbox: log was empty</li>
<li>python38Packages.mask-rcnn: log was empty</li>
<li>python38Packages.mayavi: log was empty</li>
<li>python38Packages.pygmt: log was empty</li>
<li>python38Packages.pymatgen: log was empty</li>
<li>python38Packages.pyregion: log was empty</li>
<li>python38Packages.pytest-astropy: log was empty</li>
<li>python38Packages.pytorch-metric-learning: log was empty</li>
<li>python38Packages.pywick: log was empty</li>
<li>python38Packages.radio_beam: log was empty</li>
<li>python38Packages.reproject: log was empty</li>
<li>python38Packages.spacy: log was empty</li>
<li>python38Packages.spectral-cube: log was empty</li>
<li>python38Packages.sumo: log was empty</li>
<li>python38Packages.sunpy: log was empty</li>
<li>python38Packages.tablib: log was empty</li>
<li>python38Packages.xgboost: log was empty</li>
<li>python39Packages.aplpy: log was empty</li>
<li>python39Packages.apptools: log was empty</li>
<li>python39Packages.asdf: log was empty</li>
<li>python39Packages.cnvkit: log was empty</li>
<li>python39Packages.dask-image: log was empty</li>
<li>python39Packages.drms: log was empty</li>
<li>python39Packages.envisage: log was empty</li>
<li>python39Packages.imgaug: log was empty</li>
<li>python39Packages.ipydatawidgets: log was empty</li>
<li>python39Packages.labelbox: log was empty</li>
<li>python39Packages.mask-rcnn: log was empty</li>
<li>python39Packages.mayavi: log was empty</li>
<li>python39Packages.nilearn: log was empty</li>
<li>python39Packages.pygmt: log was empty</li>
<li>python39Packages.pymatgen: log was empty</li>
<li>python39Packages.pyregion: log was empty</li>
<li>python39Packages.pytest-astropy: log was empty</li>
<li>python39Packages.pytorch-metric-learning: log was empty</li>
<li>python39Packages.pywick: log was empty</li>
<li>python39Packages.radio_beam: log was empty</li>
<li>python39Packages.reproject: log was empty</li>
<li>python39Packages.spacy: log was empty</li>
<li>python39Packages.spectral-cube: log was empty</li>
<li>python39Packages.sumo: log was empty</li>
<li>python39Packages.sunpy: log was empty</li>
<li>python39Packages.tablib: log was empty</li>
<li>python39Packages.xgboost: log was empty</li>
  </ul>
</details>
<details>

  <summary>16 packages failed to build and are new build failures:</summary>
  <ul>
<li>deja-dup: log was empty</li>
<li>duplicity: log was empty</li>
<li>duply: log was empty</li>
<li>home-assistant: log was empty</li>
<li>noto-fonts-emoji: log was empty</li>
<li>nrfutil: log was empty</li>
<li>python38Packages.baselines: log was empty</li>
<li>python38Packages.ignite: log was empty</li>
<li>python38Packages.streamz: log was empty</li>
<li>python39Packages.baselines: log was empty</li>
<li>python39Packages.dask-glm: log was empty</li>
<li>python39Packages.qiskit: log was empty</li>
<li>python39Packages.qiskit-aqua: log was empty</li>
<li>sage: log was empty</li>
<li>sageWithDoc: log was empty</li>
<li>tts: log was empty</li>
  </ul>
</details>
<details>
<summary>
336 packages built:
</summary>
<ul>
<li>EBTKS</li>
<li>aiodnsbrute</li>
<li>appdaemon</li>
<li>bicgl</li>
<li>bicpl</li>
<li>check_systemd</li>
<li>checkov</li>
<li>clevercsv (python38Packages.clevercsv)</li>
<li>conglomerate</li>
<li>cq-editor</li>
<li>csvs-to-sqlite (python38Packages.csvs-to-sqlite)</li>
<li>deepdiff (python38Packages.deepdiff)</li>
<li>dpt-rp1-py</li>
<li>evdevremapkeys</li>
<li>evillimiter</li>
<li>ezminc</li>
<li>ffmpeg-normalize</li>
<li>gdown (python38Packages.gdown)</li>
<li>gnome-keysign</li>
<li>graph-cli</li>
<li>hdf5_1_10</li>
<li>inormalize</li>
<li>jellyfin-mpv-shim</li>
<li>kaggle (python38Packages.kaggle)</li>
<li>keepkey_agent (python38Packages.keepkey_agent)</li>
<li>ldeep</li>
<li>ledger_agent (python38Packages.ledger_agent)</li>
<li>libminc</li>
<li>lieer</li>
<li>luigi</li>
<li>magic-wormhole (python38Packages.magic-wormhole)</li>
<li>manim</li>
<li>mapproxy</li>
<li>mathlibtools (python38Packages.mathlibtools)</li>
<li>minc_tools</li>
<li>minc_widgets</li>
<li>mnemosyne</li>
<li>mni_autoreg</li>
<li>n3</li>
<li>oobicpl</li>
<li>papis (python38Packages.papis)</li>
<li>past-time</li>
<li>plex-mpv-shim</li>
<li>python38Packages.Quandl (python38Packages.quandl)</li>
<li>python38Packages.acoustics</li>
<li>python38Packages.afdko</li>
<li>python38Packages.aioinflux</li>
<li>python38Packages.aiosmb</li>
<li>python38Packages.altair</li>
<li>python38Packages.ansible-kernel</li>
<li>python38Packages.ansible-runner</li>
<li>python38Packages.atomman</li>
<li>python38Packages.b2sdk</li>
<li>python38Packages.basemap</li>
<li>python38Packages.batchgenerators</li>
<li>python38Packages.bkcharts</li>
<li>python38Packages.caffe</li>
<li>python38Packages.cartopy</li>
<li>python38Packages.catboost</li>
<li>python38Packages.cirq</li>
<li>python38Packages.cufflinks</li>
<li>python38Packages.dask</li>
<li>python38Packages.dask-gateway</li>
<li>python38Packages.dask-glm</li>
<li>python38Packages.dask-ml</li>
<li>python38Packages.dask-mpi</li>
<li>python38Packages.datasets</li>
<li>python38Packages.datashader</li>
<li>python38Packages.dipy</li>
<li>python38Packages.distributed</li>
<li>python38Packages.dnachisel</li>
<li>python38Packages.duckdb</li>
<li>python38Packages.fastparquet</li>
<li>python38Packages.ffmpeg-progress-yield</li>
<li>python38Packages.flammkuchen</li>
<li>pyth [...]

2021-05-24 23:09 UTC, drewrisinger commented
ping

2021-05-25 01:38 UTC, merged