python310: fix build on darwin
NixOS/nixpkgs pull request #119921
Opened 2021-04-20 05:07 UTC by marsam

###### Motivation for this change
Fixes https://github.com/NixOS/nixpkgs/issues/119772

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-04-21 08:51 UTC, emilazy commented
Thanks! Maybe it’d be more future‐proof to use `pythonAtLeast "3.7"`, unless there’s any realistic expectation of these patches becoming unnecessary in a near‐future release?

2021-05-01 19:01 UTC, lukegb commented
> Thanks! Maybe it’d be more future‐proof to use `pythonAtLeast "3.7"`, unless there’s any realistic expectation of these patches becoming unnecessary in a near‐future release?

I don't think so. I just bumped [the issue](https://bugs.python.org/issue34027) in an attempt to get it moving again though.

2021-05-01 19:01 UTC, lukegb requested changes
> Thanks! Maybe it’d be more future‐proof to use `pythonAtLeast "3.7"`

Yeah, I think this is reasonable. That way it becomes a more obvious build failure if these don't apply.

> unless there’s any realistic expectation of these patches becoming unnecessary in a near‐future release?

I don't think so. I just bumped [the issue](https://bugs.python.org/issue34027) in an attempt to get it moving again though.

2021-06-20 00:09 UTC, lukegb approved these changes

2021-06-21 09:26 UTC, merged