remote-touchpad: init at 1.0.1
NixOS/nixpkgs pull request #120127
Opened 2021-04-22 00:36 UTC by schnusch

###### Motivation for this change

Add [remote-touchpad](https://github.com/unrud/remote-touchpad) to nixpkgs to easily control the PC's mouse from a smartphone.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-04-22 00:55 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 120127` at d8abbf3e run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>remote-touchpad</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl3` is a deprecated license, please check if project uses `gpl3Plus` or `gpl3Only` and change `meta.license` accordingly.

Near pkgs/tools/inputmethods/remote-touchpad/default.nix:29:5:
```
   |
29 |     license = licenses.gpl3;
   |     ^
```
</li>
  </ul>
</details>

2021-04-22 01:40 UTC, SuperSandro2000 commented on pkgs/tools/inputmethods/remote-touchpad/default.nix
> +     sha256 = "0zmbn4s3yhcgmijc96vja7zj2sh6q0nkybhqy0fwz6sqzk8hq02x";
```suggestion
    owner = "unrud";
    repo = pname;
    rev = "v${version}";
    sha256 = "0zmbn4s3yhcgmijc96vja7zj2sh6q0nkybhqy0fwz6sqzk8hq02x";
```

2021-04-22 01:40 UTC, SuperSandro2000 commented on pkgs/tools/inputmethods/remote-touchpad/default.nix
> +    license = licenses.gpl3Plus;
Missing maintainer.

2021-04-22 01:40 UTC, SuperSandro2000 commented on pkgs/tools/inputmethods/remote-touchpad/default.nix
> +    homepage = "https://github.com/unrud/${pname}";
```suggestion
    homepage = "https://github.com/unrud/remote-touchpad";
```

2021-04-22 02:17 UTC, hjones2199 requested changes

2021-04-22 02:17 UTC, hjones2199 commented on pkgs/tools/inputmethods/remote-touchpad/default.nix
> +  };
```suggestion
    platforms = platforms.linux;
  };
```
Upstream doesn't appear to have OSX bindings available.

2021-04-23 16:27 UTC, hjones2199 approved these changes

2021-04-24 05:39 UTC, SuperSandro2000 requested changes

2021-04-24 05:39 UTC, SuperSandro2000 commented on pkgs/tools/inputmethods/remote-touchpad/default.nix
> +    license = licenses.gpl3Plus;
You missed this.

2021-04-25 12:13 UTC, merged