mympd: 6.10.0 -> 7.0.2
NixOS/nixpkgs pull request #120273
Opened 2021-04-22 22:00 UTC by Kranzes

###### Motivation for this change
Bump to latest version at the time of making this RP.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-04-22 22:14 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 120273` at 379a37ff run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>mympd</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `mongoose`.
Near pkgs/applications/audio/mympd/default.nix:11:3:
```
   |
11 | , mongoose
   |   ^
```
</li>
  </ul>
</details>

2021-04-22 23:04 UTC, SuperSandro2000 requested changes

2021-04-22 23:04 UTC, SuperSandro2000 commented on pkgs/applications/audio/mympd/default.nix
>  , mongoose
```suggestion
```

2021-04-23 10:53 UTC, fufexan commented
Result of `nixpkgs-review pr 120273` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mympd</li>
  </ul>
</details>

2021-04-23 18:40 UTC, merged

2021-04-23 18:40 UTC, doronbehar commented
Thanks!