pythonPackages.pytmx: 3.24.0 -> 3.25.0
NixOS/nixpkgs pull request #121485
Opened 2021-05-02 09:46 UTC by oxzi

###### Motivation for this change
Version bump to the latest release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-02 10:17 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 121485` at 10525ace run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.pytmx</li>
    <li>python39Packages.pytmx</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/pytmx/default.nix:31:5:
```
   |
31 |     license = licenses.lgpl3;
   |     ^
```
</li>
  </ul>
</details>

2021-05-02 11:15 UTC, dotlambda requested changes
License should be `lgpl3Plus`.

Would be nice:
```nix
pythonImportsCheck = [
  "pytmx.pytmx"
  "pytmx.util_pygame"
  "pytmx.util_pyglet"
  "pytmx.util_pysdl2"
];
```

2021-05-02 12:06 UTC, oxzi commented
@dotlambda: Thanks for your feedback. I altered the PR accordingly.

2021-05-02 12:40 UTC, dotlambda commented on pkgs/development/python-modules/pytmx/default.nix
>      # The release was not git tagged.
https://github.com/bitcraft/pytmx/issues/147

2021-05-03 09:07 UTC, dotlambda requested changes

2021-05-03 09:07 UTC, dotlambda commented on pkgs/development/python-modules/pytmx/default.nix
> +  version = "3.25.0";
```suggestion
  version = "3.25";
```

2021-05-03 09:07 UTC, dotlambda commented on pkgs/development/python-modules/pytmx/default.nix
> +    rev = "070680418e832e1d85643e13fcd0f577d7ca6798";
```suggestion
    rev = version;
```

2021-05-03 17:03 UTC, oxzi commented
@dotlambda: Thanks for bringing the maintainer to tag the releases. I have updated the pull request.

2021-05-03 17:15 UTC, merged