siege: 4.0.8 -> 4.0.9
NixOS/nixpkgs pull request #121784
Opened 2021-05-05 10:22 UTC by fabaff

###### Motivation for this change
Update to latest upstream release 4.0.9

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-05 10:47 UTC, dotlambda reviewed
Can we add https://www.joedog.org/siege-home/ as homepage?

2021-05-05 17:02 UTC, diogox approved these changes

2021-05-05 20:26 UTC, fabaff commented
> Can we add https://www.joedog.org/siege-home/ as homepage?

Thanks, added.

2021-05-05 20:34 UTC, dotlambda requested changes

2021-05-05 20:34 UTC, dotlambda commented on pkgs/tools/networking/siege/default.nix
> +    homepage = "    homepage = "https://github.com/Instagram/libcst";";
```suggestion
    homepage ="https://www.joedog.org/siege-home/";
```

2021-05-06 16:36 UTC, fabaff commented on pkgs/tools/networking/siege/default.nix
> +    homepage = "    homepage = "https://github.com/Instagram/libcst";";
Ups, that went completely wrong.

2021-05-06 17:02 UTC, dotlambda approved these changes

2021-05-06 19:47 UTC, merged