prism: init at 0.1.1
NixOS/nixpkgs pull request #121869
Opened 2021-05-06 01:21 UTC by paperdigits

###### Motivation for this change
To include this package in nixpkgs

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-06 04:42 UTC, mkg20001 requested changes

2021-05-06 04:42 UTC, mkg20001 commented on pkgs/applications/video/prism/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-05-06 04:42 UTC, mkg20001 commented on pkgs/applications/video/prism/default.nix
> +{ stdenv, buildGoModule, fetchFromGitHub }:
```suggestion
{ stdenv, lib, buildGoModule, fetchFromGitHub }:
```

2021-05-07 14:50 UTC, SuperSandro2000 commented on pkgs/applications/video/prism/default.nix
> +  vendorSha256 = "sha256:1mkd1s9zgzy9agy2rjjk8wfdga7nzv9cmwgiarfi4xrqzj4mbaxq";
```suggestion
    sha256 = "0q7q7aj3fm45bnx6hgl9c1ll8na16x6p7qapr0c4a6dhxwd7n511";
  };

  vendorSha256 = "1mkd1s9zgzy9agy2rjjk8wfdga7nzv9cmwgiarfi4xrqzj4mbaxq";
```

2021-05-08 19:34 UTC, merged