sublime-merge: 2047 -> 2054; sublime-merge-dev: 2046 -> 2053
NixOS/nixpkgs pull request #121803
Opened 2021-05-05 13:38 UTC by victorluft

###### Motivation for this change
Upstream changelogs:
[stable](https://www.sublimemerge.com/download)
[dev](https://www.sublimemerge.com/dev)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-05 14:12 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 121803` at 54cf404b run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>sublime-merge</li>
    <li>sublime-merge-dev</li>
  </ul>
</details>

2021-05-27 01:17 UTC, neilmayhew commented
Upstream is at 2056 now.

2021-05-27 01:24 UTC, neilmayhew commented
I upgraded my editor + merge bundle license today and the current sublime-merge in nixpkgs (2047) won't accept the new Sublime4 license format. I've temporarily upgraded to 2056 using an overlay, but it would be good to get this into the repo asap.

2021-05-27 01:33 UTC, neilmayhew requested changes
Newer upstream versions and hashes

2021-05-27 01:33 UTC, neilmayhew commented on pkgs/applications/version-management/sublime-merge/default.nix
> +    sha256 = "0j5ck9w1m8dyxwywqaqb6m40siq5wmpdh2b0fpp1mscp858hp7jk";
2056 / 08472214kazx9fdw7y8gy0bp63mqxcpa79myn2w95wdp0mrlr119

2021-05-27 01:33 UTC, neilmayhew commented on pkgs/applications/version-management/sublime-merge/default.nix
> +    sha256 = "1c7p6fzqanmr1iv2j7s8x8x496iz24pgmwhzjdzn5xl9cgxrkz1w";
2055 / 0f5qmxs5cqgdp7gav223ibjwbcrh8bszk1yg1a6hpz8s8j3icvdi

2021-05-27 01:34 UTC, victorluft commented
thanks, updated to latest now

2021-05-27 01:55 UTC, merged