nixos/mosquitto: fix escaping, types, allow multiple listeners
NixOS/nixpkgs pull request #121888
Opened 2021-05-06 06:40 UTC by pennae

###### Motivation for this change

the mosquitto module interpolates stuff into shell scripts without escaping, which is a bit sad when you try to configure a literal password that contains a `'`. also some types are weird, and there's no overwhelming need to restrict the module to only one listener.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-06 08:10 UTC, nagy commented on nixos/modules/services/networking/mosquitto.nix
> +        type = types.int;
```suggestion
        type = types.port;
```
?

2021-05-15 15:06 UTC, pennae commented
maybe the module would benefit from being rewritten completely? there's a lot it currently cannot do (like enabling client cert authentication on only one listener), and the password file generation is pretty wonky one way or other. we don't really validate the config either, even though we could.

2021-05-20 21:31 UTC, pennae commented
took a good long look at rewriting the module. due to deficiencies in the mosquitto config parser we'd have to do *a lot* of validation in the module, requiring one an option definition for almost every option mosquitto has. if that sounds like a good idea we can do that, but honestly we'd rather not.

2021-05-21 10:13 UTC, peterhoeg commented
> took a good long look at rewriting the module. due to deficiencies in the mosquitto config parser we'd have to do a lot of validation in the module

I'm in favour on the minimum amount of work required to get it going.

2021-05-21 19:33 UTC, pennae commented
rewrote the module a little. only very lightly tested and just the first thing that actually ran the test, will probably change quite a few things still.

2021-05-22 17:36 UTC, pennae commented
okay, this is the general idea now. is this acceptable?

not quite happy with having freeform settings as extra attributes per level instead of having them on the same level as the other options, but putting them on the same level makes validation hard. if there's a way to query all freeform options of a submodule validation would be easy, but haven't found anything of the sort :(

2021-05-27 05:17 UTC, peterhoeg commented
You've put in a ton of effort @pennae - I need to take some time out to go through this properly and in detail to give it the attention it deserves. This will realistically only happen this weekend.

2021-05-27 22:43 UTC, pennae commented
no rush, and no worries. if it's bad it's bad, effort or no :D

2021-06-04 00:47 UTC, pennae commented
don't want to be pushy, but is there a chance we'll get a review this weekend?

2021-06-04 01:16 UTC, peterhoeg commented
I plan to take a look this weekend.

2021-06-04 01:25 UTC, pennae commented
thank you! :+1:

2021-06-14 08:29 UTC, pennae commented
@peterhoeg heya, it's totally fine if you don't have the time to review! if that is so, is there someone else who could take that over?

2021-06-15 05:32 UTC, peterhoeg commented
Hey, no, sorry, I haven't. And realistically it isn't going to happen any week night (during the week). It's not cool to leave you hanging when you've put in all this effort. I *will* get to it but yes if anybody else wants to take a stab, please do.

2021-06-18 23:06 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/548

2021-07-21 15:49 UTC, pennae commented
friendly ping

2021-09-26 17:57 UTC, pennae commented
i guess the total lack of anything happening is a good sign that we should just abandon this.

2021-10-01 19:26 UTC, tomberek requested changes
Breaking changes would make release notes helpful. Goal would be to merge prior to the next release cycle.

2021-10-01 20:06 UTC, pennae commented
added release notes, reran tests (all pass).

2021-10-16 16:02 UTC, tomberek requested changes
The home-assistant NixOS tests now do not evaluate.

2021-10-16 16:38 UTC, pennae commented
rebased, fixed home-assistant test to use the new config format. succeeds here :)

2021-10-22 19:59 UTC, tomberek approved these changes

2021-10-22 20:06 UTC, merged