base16-universal-manager: init at 1.0
NixOS/nixpkgs pull request #121995
Opened 2021-05-07 07:19 UTC by jo1gi

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-07 14:24 UTC, lourkeur requested changes
##### Reviewed points

- [x] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [ ] package build on ARCHITECTURE
- [ ] executables tested on ARCHITECTURE
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.platforms` is set
- [x] `meta.maintainers` is set
- [x] build time only dependencies are declared in `nativeBuildInputs`
- [x] source is fetched using the appropriate function
- [x] phases are respected **NA**
- [x] patches that are remotely available are fetched with `fetchpatch` **NA**

##### Possible improvements
please see review comments

##### Comments

2021-05-07 20:00 UTC, lourkeur approved these changes
LGTM

2021-05-08 19:38 UTC, SuperSandro2000 commented on pkgs/applications/misc/base16-universal-manager/default.nix
> +  meta = with lib; {
```suggestion
buildGoModule rec {
  pname = "base16-universal-manager";
  version = "1.0";

  src = fetchFromGitHub {
    owner = "pinpox";
    repo = "base16-universal-manager";
    rev = "v${version}";
    sha256 = "11kal7x0lajzydbc2cvbsix9ympinsiqzfib7dg4b3xprqkyb9zl";
  };

  vendorSha256 = "19rba689319w3wf0b10yafydyz01kqg8b051vnijcyjyk0khwvsk";

  meta = with lib; {
```

2021-05-08 19:38 UTC, SuperSandro2000 commented on pkgs/applications/misc/base16-universal-manager/default.nix
> +    platforms = platforms.unix;
```suggestion
```

buildGoModule defaults to the right subset of unix.

2021-05-27 01:50 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +  jo1gi = {
Please add yourself as a maintainer by adding an alphabetically sorted entry to `maintainers/maintainer-list.nix` and commit this change into a separate commit with the message ``maintainers: add jo1gi``.

2021-06-09 10:55 UTC, merged