Add meta.mainProgram for my maintained packages
NixOS/nixpkgs pull request #122021
Opened 2021-05-07 12:14 UTC by fortuneteller2k

###### Motivation for this change
So `nix run` works for the `unstable-yyyy-mm-dd` packages.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-07 12:35 UTC, legendofmiracles commented
There should be another solution for `nix run` not working with this specific version formatting

2021-05-07 14:35 UTC, SuperSandro2000 requested changes
Doesn't this default to pname? I think adding this to every package is redundant and it should default to it if it doesn't already.

2021-05-07 20:07 UTC, Ma27 commented
`pname` is IIRC an implementation detail of `nixpkgs` and `name` is the attribute exposed via the `builtins.derivation` primitive, hence the issue.

But unless I'm missing something, this isn't needed on every package you just touched, e.g. `exa`:

```
→ nix run nixpkgs#exa
COPYING      doc        lib          nixos  README.md  result-1    result-doc       vde1.ctl
default.nix  flake.nix  maintainers  pkgs   result     result-dev  result-terminfo
```

2021-05-07 21:50 UTC, fortuneteller2k commented
Rebased to only include the packages that truly need it.

2021-05-08 19:36 UTC, SuperSandro2000 commented on pkgs/applications/window-managers/neocomp/default.nix
> +    mainProgram     = pname;
That is the default which we do not need to set.

2021-05-10 23:38 UTC, merged