python3Packages.fastapi: fix build
NixOS/nixpkgs pull request #122457
Opened 2021-05-10 14:38 UTC by dotlambda

###### Motivation for this change
https://github.com/tiangolo/fastapi/pull/2335 was merged.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-10 15:19 UTC, mweinelt commented
> This will be available in FastAPI 0.65.0, released in a couple of hours.

Let's give the author a few hours here.

2021-05-10 16:20 UTC, dotlambda commented on pkgs/development/python-modules/json-logging/default.nix
> +    "test_api_example" # network access
This is really strange.

2021-05-10 16:25 UTC, dotlambda commented on pkgs/development/python-modules/json-logging/default.nix
> +    "test_api_example" # network access
Did urllib3 somehow strange in Python 3.9 in a way such that local networking doesn't work in the sandbox anymore?
```
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7ffff50a5f70>: Failed to establish a new connection: [Errno 111] Connection refused
```
cc @FRidh @jonringer

2021-05-11 16:12 UTC, AluisioASG requested changes
LGTM, save for the leftover `pythonAtLeast`.

2021-05-11 16:12 UTC, AluisioASG commented on pkgs/development/python-modules/json-logging/default.nix
> +, pythonAtLeast
```suggestion
```

2021-05-11 16:31 UTC, AluisioASG approved these changes

2021-05-11 17:50 UTC, AluisioASG approved these changes

2021-05-11 17:56 UTC, costrouc approved these changes

2021-05-11 19:14 UTC, merged