(numworks-epsilon): 15.3.2 -> 15.5.0
NixOS/nixpkgs pull request #122760
Opened 2021-05-12 19:53 UTC by erikbackman

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-12 20:44 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 122760` at fa21cccb run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>numworks-epsilon</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/science/math/numworks-epsilon/default.nix:41:5:
```
   |
41 |     ./0001-ion-linux-makerules.patch
   |     ^
```
</li>
  </ul>
</details>

2021-05-12 21:03 UTC, SuperSandro2000 requested changes
Please use nix-update instead.

2021-05-12 21:03 UTC, SuperSandro2000 commented on pkgs/applications/science/math/numworks-epsilon/update.sh
> +update-source-version numworks-epsilon "$latestVersion"
```suggestion
```

2021-05-12 21:03 UTC, SuperSandro2000 commented on pkgs/applications/science/math/numworks-epsilon/default.nix
> +  };
```suggestion
```

2021-05-13 09:36 UTC, erikbackman commented
> Please use nix-update instead.

Good to know :+1:

2021-05-17 17:16 UTC, merged