treewide: remove nand0p as maintainer
NixOS/nixpkgs pull request #122994
Opened 2021-05-14 14:10 UTC by mweinelt

###### Motivation for this change

While looking at the sphinx package (#122189) I noticed it was heavily
undermaintained, which is when we noticed nand0p has been inactive for
roughly 18 months. It is therefore prudent to assume they will not be
maintaining their packages, modules and tests.

- Their last contribution to nixpkgs was in 2019/12
- On 2021/05/08 I wrote them an email to the address listed in the
  maintainer-list, which they didn't reply to.

E-Mail contents: 
https://gist.github.com/mweinelt/4c2ffbb8214e58a7630b3da68e8c45a0

Open questions:
- How long do we want to wait for them to reply?
- Should we remove the maintainer handle as well?

What was done:
```
find pkgs -iname "*.nix" -exec sed -i 's/nand0p //' {} \\;
find nixos -iname "*.nix" -exec sed -i 's/nand0p //' {} \\;
```

cc @dotlambda @vcunat 

###### Things done

- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-14 14:24 UTC, dotlambda requested changes

2021-05-14 14:24 UTC, dotlambda commented on pkgs/tools/graphics/flam3/default.nix
> +    maintainers = [ maintainers.];
```suggestion
    maintainers = with maintainers; [ ];
```

2021-05-15 19:35 UTC, SuperSandro2000 approved these changes

2021-05-15 19:40 UTC, dotlambda commented
> * How long do we want to wait for them to reply?

Why can always revert, so I see no reason to wait too long.



> * Should we remove the maintainer handle as well?

It's only fair to @nand0p to do so, as his personal data shouldn't be lingering around for no reason.

2021-05-16 14:20 UTC, mweinelt commented
Done

2021-05-16 17:32 UTC, dotlambda approved these changes

2021-05-16 23:39 UTC, SuperSandro2000 commented
@mweinelt please fix the merge conflict.

2021-05-16 23:51 UTC, mweinelt commented
Done

2021-05-17 00:18 UTC, merged