nixos/postgresqlBackup: allow defining multiple times to start at
NixOS/nixpkgs pull request #123006
Opened 2021-05-14 16:18 UTC by mweinelt

###### Motivation for this change

Allow setting one, multiple, or no startAt times.

https://github.com/NixOS/nixpkgs/pull/111427#issuecomment-774582365

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-14 17:21 UTC, dotlambda requested changes

2021-05-14 17:21 UTC, dotlambda commented on nixos/modules/services/backup/postgresql-backup.nix
> +        type = with types; (either (listOf str) str);
```suggestion
        type = with types; either (listOf str) str;
```

2021-05-14 18:41 UTC, mweinelt commented on nixos/modules/services/backup/postgresql-backup.nix
> +        type = with types; (either (listOf str) str);
Thanks!

2021-05-14 19:01 UTC, dotlambda approved these changes

2021-05-16 08:33 UTC, talyz approved these changes

2021-05-18 23:54 UTC, merged