diffoscope: fix build
NixOS/nixpkgs pull request #124175
Opened 2021-05-23 17:10 UTC by Ma27

###### Motivation for this change
ZHF #122042
Failing Hydra build: https://hydra.nixos.org/build/143815905

Currently the diff-check for `.mp3`-files is failing. The only reason
for that is that right now is that there are too spaces too much on the
last line[1].

[1] https://salsa.debian.org/reproducible-builds/diffoscope/-/blob/175/tests/data/mp3_expected_diff

cc @NixOS/release-engineers 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-23 17:31 UTC, Mindavi commented
Has the output of the tool changed that does the mp3 diffs? I don't see anything relevant on their issue tracker, but I guess it would be good if upstream could fix this too somehow

2021-05-23 17:44 UTC, Ma27 commented
I don't think so. According to Hydra, `ffmpeg` wasn't updated in the time window where the build started to fail. However this also looks more like output from `diffoscope` itself. Maybe we've changed e.g. some formatting library in our python set?

2021-05-23 18:10 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 124175` at e3f05415 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>diffoscopeMinimal</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/tools/misc/diffoscope/default.nix:29:5:
```
   |
29 |     ./ignore_links.patch
   |     ^
```
</li>
  </ul>
</details>

2021-05-23 22:17 UTC, risicle commented
Their implementation looks like it pretty much just does direct output from ffprobe (https://salsa.debian.org/reproducible-builds/diffoscope/-/blob/master/diffoscope/comparators/ffprobe.py) for every line after a "Metadata:" line is found.

2021-05-23 22:56 UTC, danielfullmer commented
Hydra started failing because this PR https://github.com/NixOS/nixpkgs/pull/121042 was merged yesterday which turns on `enableBloat` for the default `diffoscope` package--and ffmpeg/ffprobe is only included if `enableBloat` is.

Still, I recall testing `enableBloat` with diffoscope working not too long ago, so the underlying test failure has probably been caused by something else recently updated.

2021-05-24 00:51 UTC, danielfullmer requested changes
Underlying issue was caused by ffmpeg 4.3.2 -> 4.4 update: 72354f8ec17b76e70faf2f6b1f1e7ae9a3b9e3c5

Also filed an issue upstream: https://salsa.debian.org/reproducible-builds/diffoscope/-/issues/258

The workaround in this PR is fine with me, we'd just need to add a comment with a short explanation of the issue.

2021-05-24 01:58 UTC, SuperSandro2000 commented on pkgs/tools/misc/diffoscope/default.nix
> +    sed -e 's/  Stream/Stream/g' -i tests/data/mp3_expected_diff
Please use substituteInPlace because sed will silently fail.

2021-05-24 09:11 UTC, Ma27 commented
@danielfullmer hmm, Hydra's scmdiff didn't show me that, probably because it tends to behave a bit weird when staging commits are relevant that were merged just before the build started. But thanks for the investigation!

2021-05-24 09:17 UTC, Ma27 commented on pkgs/tools/misc/diffoscope/default.nix
> +    sed -e 's/  Stream/Stream/g' -i tests/data/mp3_expected_diff
Fixed!

2021-05-24 23:17 UTC, danielfullmer approved these changes

2021-05-25 02:36 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 124175` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
2 packages built:
</summary>
<ul>
<li>diffoscope</li>
<li>diffoscopeMinimal</li>
</ul>
</details>

2021-05-25 02:36 UTC, merged

2021-05-26 20:43 UTC, Ma27 commented
Manually backported as 25eaf1083fefb27f4b575cf16d42b6299c081ade.