expat: 2.2.10 -> 2.4.1 (CVE-2013-0340)
NixOS/nixpkgs pull request #124212
Opened 2021-05-23 23:25 UTC by hartwork

- Superseds #122275
- Targets `staging` because of @prusnak's comment https://github.com/NixOS/nixpkgs/pull/122275#issuecomment-835737257
- Blog post about the related release: https://blog.hartwork.org/posts/cve-2013-0340-billion-laughs-fixed-in-expat-2-4-0/
- Upstream change log: https://github.com/libexpat/libexpat/blob/R_2_4_1/expat/Changes
- If anyone wants to take over this pull request, please go ahead

###### Motivation for this change
Security fixes (CVE-2013-0340)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-24 02:03 UTC, SuperSandro2000 requested changes

2021-05-24 02:03 UTC, SuperSandro2000 commented on pkgs/development/libraries/expat/default.nix
>  let
```suggestion
```

2021-05-24 02:03 UTC, SuperSandro2000 commented on pkgs/development/libraries/expat/default.nix
>    name = "expat-${version}";
```suggestion
stdenv.mkDerivation rec {
  pname = "expat";
  version = "2.4.1";
```

2021-05-27 03:38 UTC, SuperSandro2000 commented
@ofborg build expat

2021-05-31 10:37 UTC, hartwork commented
@SuperSandro2000 any news?

2021-06-01 06:19 UTC, Mindavi commented
[Changelog](https://github.com/libexpat/libexpat/blob/R_2_4_1/expat/Changes) seems fine, build for x86-64 has passed.

Diff LGTM

2021-06-03 15:04 UTC, SuperSandro2000 commented
@ofborg build expat

2021-06-09 08:23 UTC, hartwork commented
@SuperSandro2000 if there are no mode changes needed on my side, could you approve the PR so the it no longer communicates "not ready" to the rest of the world? If there are changes needed, how can I help to make CI happy?

2021-06-09 13:49 UTC, SuperSandro2000 commented
> if there are no more changes needed on my side, could you approve the PR so the it no longer communicates "not ready" to the rest of the world?

That doesn't really matter is not blocking any merge.

2021-06-09 13:50 UTC, SuperSandro2000 commented on pkgs/development/libraries/expat/default.nix
>    outputs = [ "out" "dev" ]; # TODO: fix referrers
I think we need to add

```
postPatch = ''
  patchShebangs configure
'';

to fix aarch64.

2021-06-09 13:50 UTC, SuperSandro2000 commented on pkgs/development/libraries/expat/default.nix
>    '';
Those patchShebangs can be combined.

2021-06-09 13:57 UTC, hartwork commented on pkgs/development/libraries/expat/default.nix
>    '';
Can do

2021-06-09 14:07 UTC, hartwork commented
> That doesn't really matter is not blocking any merge.

I respectfully disagree. It communicates something in 2 seconds that otherwise takes manual work from each viewer to falsify. If you need someone to do it for, please do it for me. Thank you :pray:

2021-06-12 19:16 UTC, SuperSandro2000 commented
> I respectfully disagree. It communicates something in 2 seconds that otherwise takes manual work from each viewer to falsify.

Yeah, you are completely right but I normally have so many notifications that I am overwhelmed by them.

> If you need someone to do it for, please do it for me. Thank you 🙏

The PR is not LGTM.

2021-06-12 19:16 UTC, SuperSandro2000 approved these changes

2021-06-12 19:17 UTC, merged