postgresqlPackages.pg_rational: init at 0.0.2
NixOS/nixpkgs pull request #124257
Opened 2021-05-24 12:41 UTC by netcrns

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-05-24 13:27 UTC, netcrns commented
Result of `nixpkgs-review pr 124257` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>postgresqlPackages.pg_rational (postgresql11Packages.pg_rational)</li>
  </ul>
</details>

2021-05-26 01:39 UTC, marsam requested changes

2021-05-26 01:39 UTC, marsam commented on pkgs/top-level/aliases.nix
> +  pg_rational = postgresqlPackages.pg_rational;
It's not necessary to add an alias to `postgresqlPackages` here.
```suggestion
```
Those `postgresqlPackages` aliases are kept only for backwards compatibility

2021-05-26 01:50 UTC, marsam approved these changes

2021-05-26 02:07 UTC, merged