Added support to create uboot for orangepi zero2
NixOS/nixpkgs pull request #124440
Opened 2021-05-25 23:58 UTC by novmar

###### Motivation for this change
This is support to create u- boot for orange pi zero2. Created with assistence of samueldr

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).
- [ ] Tested on orange pi zero 2

2021-05-26 00:07 UTC, samueldr requested changes
We'll neeed three PRs:

 - armTrustedFirmware*: 2.4 -> 2.5
 - armTrustedFirmwareAllwinnerH616: init
 - ubootOrangePiZero2: init


Additionally, armTrustedFirmwareAllwinnerH616 is missing from `all-packages.nix`.

2021-05-26 00:07 UTC, samueldr commented on pkgs/misc/uboot/default.nix
> +    BL31 = "${armTrustedFirmwareAllwinner}/bl31.bin";
Wrong TF-A in use.

```suggestion
    BL31 = "${armTrustedFirmwareAllwinnerH616}/bl31.bin";
```

2021-06-04 22:14 UTC, samueldr commented
The changes here seems alright, one issue though, the commits :)

We'll neeed two distinct **commits**, with those titles/first lines

 - armTrustedFirmwareAllwinnerH616: init
 - ubootOrangePiZero2: init

Do you have someone (else) you can ask for help about learning about git interactive rebase, so you can cleanup the history in a proper way? I guess if your a good autodidact you can also search online about git interactive rebase.

2021-06-04 23:15 UTC, closed without merging

2021-06-04 23:33 UTC, novmar commented
redone in https://github.com/NixOS/nixpkgs/pull/125743 because of  my terrible git skills