qdl: init at 20210506
NixOS/nixpkgs pull request #125188
Opened 2021-06-01 09:52 UTC by musfay

qdl: init at 20210506

###### Motivation for this change
A great tool to flash system images to Qualcomm devices.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Added a release notes entry if the change is major or breaking
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-01 10:19 UTC, samuelgrf requested changes

2021-06-01 10:19 UTC, samuelgrf commented on pkgs/tools/misc/qdl/default.nix
> +    maintainers = with maintainers; [ ];
Needs a maintainer.

2021-06-01 10:19 UTC, samuelgrf commented on pkgs/tools/misc/qdl/default.nix
> +  installPhase = ''
```suggestion
  installPhase = ''
    runHook preInstall
```

2021-06-01 10:19 UTC, samuelgrf commented on pkgs/tools/misc/qdl/default.nix
> +    install -Dm755 ./qdl $out/bin/qdl
```suggestion
    install -Dm755 ./qdl $out/bin/qdl
    runHook postInstall
```

2021-06-01 10:19 UTC, samuelgrf commented on pkgs/tools/misc/qdl/default.nix
> +  version = "20210506";
```suggestion
  version = "unstable-2021-05-06";
```

2021-06-01 12:36 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 125188` at 6462ae8e run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>qdl</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/tools/misc/qdl/default.nix:16:3:
```
   |
16 |   installPhase = ''
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/maintainers-missing.md">maintainers-missing</a>

Package does not have a maintainer. Consider adding yourself?

Near pkgs/tools/misc/qdl/default.nix:24:5:
```
   |
24 |     maintainers = with maintainers; [ ];
   |     ^
```
</li>
  </ul>
</details>

2021-06-01 13:20 UTC, musfay commented
@samuelgrf Should I add myself to `maintainer-list.nix` with this PR or create a new one?

2021-06-01 13:53 UTC, samuelgrf commented
@musfay In this PR.
It should be done in a seperate commit with the message `maintainers: add <name-here>`, also make sure that commit comes before the one adding the package.

2021-06-01 14:09 UTC, samuelgrf commented on pkgs/tools/misc/qdl/default.nix
> +    description = "A tool to flash images to Qualcomm devices.";
```suggestion
    description = "Tool for flashing images to Qualcomm devices";
```
See https://nixos.org/manual/nixpkgs/unstable/#var-meta-description .

2021-06-01 14:40 UTC, samuelgrf commented on pkgs/tools/misc/qdl/default.nix
> +    description = "Tool to flash images to Qualcomm devices";
```suggestion
    description = "Tool for flashing images to Qualcomm devices";
```
The grammar seems wrong.

2021-06-01 15:08 UTC, samuelgrf commented
Result of `nixpkgs-review pr 125188` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>qdl</li>
  </ul>
</details>

2021-06-01 15:15 UTC, samuelgrf approved these changes
LGTM 👍

2021-06-02 10:38 UTC, sikmir commented on pkgs/tools/misc/qdl/default.nix
> +    install -Dm755 ./qdl $out/bin/qdl
```suggestion
    install -Dm755 ./qdl -t $out/bin
```

2021-06-04 09:17 UTC, merged