ocamlPackages.tls: 0.13.1 -> 0.13.2
NixOS/nixpkgs pull request #125882
Opened 2021-06-06 00:50 UTC by superherointj

ocamlPackages.tls: 0.13.1 -> 0.13.2

2021-06-06 01:14 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 125882` at 977b37b9 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>dune-release</li>
    <li>jackline</li>
  </ul>
</details>

2021-06-07 13:06 UTC, sternenseemann requested changes
Updating to 0.13.2 only makes sense if you add the `tls-async` package as well since that is the only notable change between 0.13.1 and 0.13.2.

2021-06-07 13:06 UTC, sternenseemann commented on pkgs/development/ocaml-modules/tls/default.nix
> +  checkInputs = [
Needs `randomconv` as well now, apparently.

<https://github.com/mirleft/ocaml-tls/compare/v0.13.1...v0.13.2#diff-4e4385427f3692f3a121bc8d987899d17f5a6090784b51f47b76423cfbd4a358R39>

2021-06-07 13:07 UTC, sternenseemann commented
Also can you please do reformats in separate commits in the future? Formatting changes make changes much more cumbersome to review.

2021-06-17 09:51 UTC, superherointj commented
@ofborg eval

2021-06-18 06:57 UTC, vbgl commented on pkgs/development/ocaml-modules/tls/default.nix
> -    url = "https://github.com/mirleft/ocaml-tls/releases/download/v${version}/tls-v${version}.tbz";
This URL was the right one.

2021-06-18 07:03 UTC, superherointj commented on pkgs/development/ocaml-modules/tls/default.nix
> -    url = "https://github.com/mirleft/ocaml-tls/releases/download/v${version}/tls-v${version}.tbz";
Done

2021-06-18 10:13 UTC, sternenseemann commented
opam additionally lists as dependencies:

* ptime
* x509
* ppx_jane (not sure if nativeBuildInputs or propagatedBuildInputs though)

2021-06-18 10:44 UTC, merged