ocamlPackages.cstruct-async: init 6.0.0
NixOS/nixpkgs pull request #126116
Opened 2021-06-07 19:53 UTC by superherointj

ocamlPackages.cstruct-async: init 6.0.0

This is a dependency of `tls-async`. #125882

2021-06-14 02:23 UTC, vbgl requested changes
Please wait for #126803 (to avoid conflict and avoid breaking evaluation).

2021-06-14 02:23 UTC, vbgl commented on pkgs/development/ocaml-modules/cstruct/async.nix
> +  inherit (cstruct) src version meta minimumOCamlVersion useDune2;
```suggestion
  inherit (cstruct) src version meta useDune2;
```

2021-06-17 08:53 UTC, superherointj commented on pkgs/development/ocaml-modules/cstruct/async.nix
> +    async
Done

2021-06-17 08:53 UTC, superherointj commented on pkgs/development/ocaml-modules/cstruct/async.nix
> +{ lib, buildDunePackage, cstruct, async }:
Done

2021-06-17 08:53 UTC, superherointj commented on pkgs/development/ocaml-modules/cstruct/async.nix
> +  inherit (cstruct) src version meta minimumOCamlVersion useDune2;
Done

2021-06-17 09:46 UTC, merged