vscode-extensions.Gleam.gleam: init at 1.3.0
NixOS/nixpkgs pull request #126329
Opened 2021-06-09 08:42 UTC by OliverEvans96

Two minor points I'm uncertain about:
- "Gleam.gleam" is capitalized in the VSCode Marketplace unique ID, but most (all?) other nix vscode-extensions seem to be lowercase.
- Version discrepancy: v1.2.0 vs v1.3.0 - see https://github.com/gleam-lang/vscode-gleam/issues/13

###### Motivation for this change

Gleam support for VSCode

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-09 11:51 UTC, happysalada commented
Result of `nixpkgs-review pr 126329` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

2021-06-09 11:54 UTC, happysalada commented
This is only my opinion, but I would say, leave the package name lowercase and inside the publisher and name, you can use the right casing. I don't think it brings anything to have a package name having some uppercase and some lowercase.

Other than that, interesting version issue, let's wait to see what happened there.

2021-06-10 18:59 UTC, SuperSandro2000 requested changes

2022-06-01 18:42 UTC, sharno commented
@OliverEvans96 
Do you have time to address the reviews to finish this PR?
Or shall I fork your repo and pick it up?

2022-06-03 04:27 UTC, OliverEvans96 commented
@sharno I would finish it myself, but I'm a bit preoccupied right now with family things, and don't have much spare attention. If you  have some free cycles to knock it out, I would definitely appreciate it! Otherwise, I'll come back to it when I get a chance.

2023-03-18 21:35 UTC, superherointj commented
Please fix merge conflict.

2023-04-16 12:30 UTC, SuperSandro2000 commented
Closing due to being stale

2023-04-16 12:30 UTC, closed without merging