whitesur-icon-theme: init at 2021-05-20
NixOS/nixpkgs pull request #126491
Opened 2021-06-10 15:12 UTC by Icy-Thought

###### Motivation for this change
Add `Whitesur-icon-theme` to nixpkgs for the sake of reducing the effort required by the user to install an icon theme.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-10 15:48 UTC, fufexan commented on maintainers/maintainer-list.nix
> +    githubId = "53710398";
```suggestion
    githubId = 53710398;
```

2021-06-10 15:51 UTC, NobbZ requested changes
Please also add to an appropriate "index file" at `pkgs/top-level`.

2021-06-10 18:44 UTC, SuperSandro2000 requested changes

2021-06-11 05:07 UTC, Icy-Thought commented on pkgs/data/icons/whitesur-icon-theme/default.nix
> +    # Change icon color for dark theme
I was not able to output the default colors (bright + dark) from the installation script and therefore followed the installation script to make the icon theme work with one of the two choices. 

Judging between dark vs bright colors, I concluded that dark colors was more fit compared to brighter colors even though the change is not as big as one would think.

This change is reversible and if you desire for the dark colors to be replaced with default brighter once, then that shall be the color of the icons in this package.

2021-06-11 05:14 UTC, Icy-Thought commented on pkgs/data/icons/whitesur-icon-theme/default.nix
> +    license = licenses.gpl3;
gpl3Only seems like the obvious choice due to our inability to determine the future license of this project.

2021-06-11 12:24 UTC, 06kellyjac commented on pkgs/data/icons/whitesur-icon-theme/default.nix
> +    license = licenses.gpl3;
Waiting on clarification from creator: https://github.com/vinceliuice/WhiteSur-icon-theme/issues/62

2021-06-11 12:37 UTC, Icy-Thought commented on pkgs/data/icons/whitesur-icon-theme/default.nix
> +    license = licenses.gpl3;
Wrote that in the matrix chat, forgot to update here. 
Appreciate it!

2021-06-11 13:06 UTC, vinceliuice commented on pkgs/data/icons/whitesur-icon-theme/default.nix
> +    license = licenses.gpl3;
gpl3Plus

2021-06-11 18:22 UTC, Icy-Thought commented on pkgs/data/icons/whitesur-icon-theme/default.nix
> +    # Change icon color for dark theme
Re-configured to output two themes (default + dark) instead of one dark theme.

2021-06-13 18:39 UTC, fufexan requested changes

2021-06-13 18:39 UTC, fufexan commented on pkgs/data/icons/whitesur-icon-theme/default.nix
> +    done
```suggestion
    done
    
    runHook postInstall
```

2021-06-13 19:13 UTC, fufexan approved these changes

2021-06-13 19:14 UTC, fufexan requested changes

2021-06-13 19:14 UTC, fufexan commented on pkgs/data/icons/whitesur-icon-theme/default.nix
> +
```suggestion

```

2021-06-13 19:44 UTC, Icy-Thought commented
Re-submitting due to horrible rebase attempt.. :/

2021-06-13 19:44 UTC, closed without merging