python3Packages.angrcli: init at 1.1.1
NixOS/nixpkgs pull request #126515
Opened 2021-06-10 17:57 UTC by fabaff

###### Motivation for this change
Python modules to allow easier interactive use of angr

https://github.com/fmagin/angr-cli

Related to #81418

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-10 18:29 UTC, fabaff commented
Result of `nixpkgs-review pr 126515` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.angrcli</li>
    <li>python39Packages.angrcli</li>
  </ul>
</details>

2021-06-10 18:37 UTC, SuperSandro2000 requested changes, later dismissed

2021-06-10 18:37 UTC, SuperSandro2000 commented on pkgs/top-level/python-packages.nix
> +  angrcli = callPackage ../development/python-modules/angrcli { };
```suggestion
  angrcli = callPackage ../development/python-modules/angrcli {
    inherit (pkgs) coreutils;
  };
```

2021-06-10 18:37 UTC, SuperSandro2000 commented on pkgs/development/python-modules/angrcli/default.nix
> +    pkgs.coreutils
```suggestion
    coreutils
```

2021-06-10 18:37 UTC, SuperSandro2000 commented on pkgs/development/python-modules/angrcli/default.nix
> +      --replace "/bin/ls" "${pkgs.coreutils}/bin/ls"
```suggestion
      --replace "/bin/ls" "${coreutils}/bin/ls"
```

2021-06-10 18:37 UTC, SuperSandro2000 commented on pkgs/development/python-modules/angrcli/default.nix
> +, pkgs
```suggestion
, coreutils
```

2021-06-11 01:54 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 126515` at fbf7ca73 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li><a href="https://gist.github.com/c47ad975282af7e777b573cfd44ef611">python38Packages.angrcli</a></li>
    <li><a href="https://gist.github.com/e5b33fcfe8cf3cd7ad36f61a70289186">python39Packages.angrcli</a></li>
  </ul>
</details>

Note that build failures [may predate](https://github.com/nix-community/hydra-check) this PR, and could be nondeterministic or hardware dependent.
Please exercise your independent judgement. Does something look off? Please file an [issue](https://github.com/rmcgibbo/r-rmcgibbo/issues) or reach out on IRC.

2021-06-17 15:29 UTC, fabaff commented on pkgs/top-level/python-packages.nix
> +  angrcli = callPackage ../development/python-modules/angrcli { };
Thanks, change.

2021-06-17 17:01 UTC, fabaff commented
Result of `nixpkgs-review pr 126515` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.angrcli</li>
    <li>python39Packages.angrcli</li>
  </ul>
</details>

2021-06-17 20:41 UTC, jonringer reviewed
I don't see a cli command export..
```
$ tree -L 2 ./results/python38Packages.angrcli/
./results/python38Packages.angrcli/
├── lib
│   └── python3.8
└── nix-support
    └── propagated-build-inputs
```

Can we get upstream to export a proper `entry_points`?

2021-10-31 08:19 UTC, fabaff commented
> Can we get upstream to export a proper entry_points?

I'm not sure how active upstream is as there as not much action lately. I think it's definitely worth looking into the matter.

2021-10-31 08:52 UTC, fabaff commented
Result of `nixpkgs-review pr 126515` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python38Packages.angrcli</li>
    <li>python39Packages.angrcli</li>
  </ul>
</details>

2021-10-31 08:53 UTC, merged