Skytemple
NixOS/nixpkgs pull request #126676
Opened 2021-06-12 15:16 UTC by marius851000

###### Motivation for this change
I wanted to use the patch functionallity, but it appeared to not work.

###### Things done
Packaged armips (used to apply patch)
made a patch for skytemple-files (merged upstream) to ensure that file copied from the nix store to the temporary directory is writable by the program.

tested the application of some patches

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-12 15:23 UTC, SuperSandro2000 requested changes

2021-06-12 15:23 UTC, SuperSandro2000 commented on pkgs/development/python-modules/skytemple-files/default.nix
> +    (fetchurl {
You must use fetchpatch here and update the has.

2021-06-12 19:03 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 126676` at 8b364280 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>7 packages built successfully:</summary>
  <ul>
    <li>python38Packages.skytemple-dtef</li>
    <li>python38Packages.skytemple-files</li>
    <li>python38Packages.skytemple-ssb-debugger</li>
    <li>python39Packages.skytemple-dtef</li>
    <li>python39Packages.skytemple-files</li>
    <li>python39Packages.skytemple-ssb-debugger</li>
    <li>skytemple</li>
  </ul>
</details>

2021-06-12 20:34 UTC, xfix requested changes
Tested patches funcitonality, it works after this change.

2021-06-12 20:34 UTC, xfix commented on pkgs/development/compilers/armips/default.nix
> +  installPhase = ''
Please run install hooks, see https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md.

2021-06-13 11:19 UTC, xfix approved these changes

2021-06-15 00:46 UTC, merged