eplot: 2.07 -> 2.09
NixOS/nixpkgs pull request #126937
Opened 2021-06-15 11:34 UTC by SCOTT-HAMILTON

###### Motivation for this change
Closes https://github.com/NixOS/nixpkgs/issues/126925

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

## Pinging maintainer
@bjornfor

2021-06-15 13:30 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 126937` at d3441eae run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>eplot</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/tools/graphics/eplot/default.nix:22:3:
```
   |
22 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

2021-06-15 15:39 UTC, bjornfor requested changes
The sources must be updated.

I see that I made this package with unstable URLs (because there was nothing else). Perhaps we can fetch something from github now? And ping upstream about tagging.

2021-06-16 01:45 UTC, SuperSandro2000 requested changes

2021-06-16 01:45 UTC, SuperSandro2000 commented on pkgs/tools/graphics/eplot/default.nix
> +  name = "eplot-2.09";
```suggestion
  pname = "eplot";
  version = "2.09";
```

2021-06-16 01:45 UTC, SuperSandro2000 commented on pkgs/tools/graphics/eplot/default.nix
>      homepage = "http://liris.cnrs.fr/christian.wolf/software/eplot/";
```suggestion
    homepage = "https://perso.liris.cnrs.fr/christian.wolf/software/eplot/";
```

2021-06-18 11:58 UTC, merged

2021-06-18 15:57 UTC, bjornfor commented
Sources were not updated.