xlockmore: add preConfigure to compile with DPMS support
NixOS/nixpkgs pull request #127051
Opened 2021-06-16 08:05 UTC by romanofski

###### Motivation for this change

The `xlock` command can switch the display off if it supports DPMS but the 
command shipped with NixOS does not support it.

The build of xlockmore produced only the minimum set of features. DPMS
support, Xinerama etc was disabled because the changes in the postPatch
step were never applied by re-running autoconf.

Furthermore, DPMS was not supported because it couldn't find the
`dpms.h` header file in order to compile the support for DPMS features.

This patch adds an additional `preConfigure` step in which we run
`autoconf` to apply the changes of `configure.ac` to the `configure`
script. The patch also uses the `libXext.dev` `buildInput` in order to
allow access to the right header files.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-16 16:04 UTC, SuperSandro2000 requested changes
Can we use autoreconfHook?

2021-06-16 22:52 UTC, romanofski commented
> Can we use autoreconfHook?

Cheers for the pointer. Will check!

2021-06-17 08:47 UTC, romanofski commented
Updated commit message and use `autoreconfHook`. Much better. Thank you!

2021-06-17 12:24 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 127051` at ddb625d3 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>xlockmore</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/misc/screensavers/xlockmore/default.nix:37:5:
```
   |
37 |     license = licenses.gpl2;
   |     ^
```
</li>
  </ul>
</details>

2021-06-18 08:30 UTC, merged