idasen: init at 0.7.1
NixOS/nixpkgs pull request #127495
Opened 2021-06-19 20:41 UTC by newAM

###### Motivation for this change

Add [idasen](https://github.com/newAM/idasen)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-19 20:49 UTC, newAM commented
Whoops, sorry about that CI failure, I accidentally included a line I should not have when I was staging.

2021-06-20 16:23 UTC, SuperSandro2000 requested changes

2021-06-20 16:23 UTC, SuperSandro2000 commented on pkgs/development/python-modules/idasen/default.nix
> +buildPythonPackage rec {
```suggestion
}:

buildPythonPackage rec {
```

2021-06-20 16:23 UTC, SuperSandro2000 commented on pkgs/development/python-modules/idasen/default.nix
> +  doCheck = true;
```suggestion
```

thats the default

2021-06-20 16:23 UTC, SuperSandro2000 commented on pkgs/development/python-modules/idasen/default.nix
> +    pytest
```suggestion
    pytestCheckHook
```

2021-06-20 16:23 UTC, SuperSandro2000 commented on pkgs/development/python-modules/idasen/default.nix
> +  checkPhase = "pytest";
```suggestion
```

2021-06-20 16:32 UTC, newAM commented
Made the requested changes, thanks for the review!

2021-06-20 18:02 UTC, merged