tuna: init at 0.15
NixOS/nixpkgs pull request #127656
Opened 2021-06-21 11:24 UTC by elohmeier

###### Motivation for this change
Tuna is a useful tool to analyze and modify Linux threads.

###### Things done
Added Tuna and dependent Python libraries.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-21 12:51 UTC, SuperSandro2000 requested changes

2021-06-21 12:51 UTC, SuperSandro2000 commented on pkgs/development/python-modules/python-ethtool/default.nix
> +  patchPhase = ''
```suggestion
  postPatch = ''
```

2021-06-21 12:51 UTC, SuperSandro2000 commented on pkgs/development/python-modules/python-ethtool/default.nix
> +  nativeBuildInputs = [ pkg-config ];
Missing pythonImportsCheck.

2021-06-21 12:51 UTC, SuperSandro2000 commented on pkgs/development/python-modules/python-ethtool/default.nix
> +    license = licenses.gpl2Plus;
Missing maintainer.

2021-06-21 12:53 UTC, SuperSandro2000 requested changes

2021-06-21 12:53 UTC, SuperSandro2000 commented on pkgs/development/python-modules/python-ethtool/default.nix
> +, setuptools_scm
```suggestion
```

2021-06-21 12:53 UTC, SuperSandro2000 commented on pkgs/development/python-modules/python-ethtool/default.nix
> +, nettools
```suggestion
, pkg-config
, nettools
```

2021-06-22 08:01 UTC, elohmeier commented on pkgs/development/python-modules/python-ethtool/default.nix
> +, nettools
Thanks, updated.

2021-06-22 13:22 UTC, merged