ibus-engines.rime: 1.4.0 -> 1.5.0
NixOS/nixpkgs pull request #128181
Opened 2021-06-26 10:53 UTC by pmeiyu

###### Motivation for this change

Update ibus-engines.rime to 1.5.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2021-06-26 14:59 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 128181` at 41bdfe56 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>ibus-engines.rime</li>
    <li>rime-data</li>
  </ul>
</details>

2021-06-26 16:09 UTC, SuperSandro2000 requested changes

2021-06-26 16:09 UTC, SuperSandro2000 commented on pkgs/data/misc/rime-data/fetchSchema.nix
> +# Generated using https://gist.github.com/pmeiyu/c09a8f9547c9a0cdb0e1f610d41c0138
Please put this file into nixpkgs.

2021-06-26 16:09 UTC, SuperSandro2000 commented on pkgs/data/misc/rime-data/default.nix
> +  patchPhase = ''
```suggestion
  postPatch = ''
```

2021-07-01 06:22 UTC, pmeiyu commented
@SuperSandro2000 Ping.

2021-07-04 00:38 UTC, merged