[21.05] sway: 1.6 -> 1.6.1, wlroots: 0.13.0 -> 0.14.0, libdrm: 2.4.105 -> 1.4.106
NixOS/nixpkgs pull request #128459
Opened 2021-06-27 20:14 UTC by Ma27

###### Motivation for this change

Backport PR for #128036, #127897 and #123519 (not so sure about the last one, I decided to update it as well to hopefully fix #127413 locally).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-06-28 10:31 UTC, primeos commented
Not sure if this is really a good idea. Maybe we should wait a bit to see if anyone on nixos-unstable experiences any regressions with wlroots 0.14? I also thought you wanted to test this for ~10 days first (https://github.com/NixOS/nixpkgs/issues/127413#issuecomment-869134761) - or was that just for that issue and not the backport? Additionally I though we intended to backport the wlroots update as `wlroots_0_14` (https://github.com/NixOS/nixpkgs/pull/128036#issuecomment-868341743) or are you against that idea?

The `libdrm` update is also a bit scary (lots of rebuilds) but at least I've never heard of any `libdrm` regressions since I started maintaining it a few releases ago or so.

Anyway, just some things to consider, this isn't a hard objection / veto.

PS: Ideally we should also state the reason: "4. When the reason to backport is not obvious from the original commit message, use git cherry-pick -xe <original commit> and add a reason."

2021-06-28 10:55 UTC, Ma27 commented
> I also thought you wanted to test this for ~10 days first (#127413 (comment)) - or was that just for that issue and not the backport? Additionally I though we intended to backport the wlroots update as wlroots_0_14 (#128036 (comment)) or are you against that idea?


Absolutely! Just thought I'd open it now to give other people on 21.05 the same opportunity. To make that clear, I decided to mark it as draft. (Note: I expected it to be a bit more work to backport this which is another reason why this branch exists :))

> The libdrm update is also a bit scary (lots of rebuilds) but at least I've never heard of any libdrm regressions since I started maintaining it a few releases ago or so.

My thinking was kinda simple (and perhaps dumb) here: the crash I've seen happened in a communication between sway and libdrm, so updating it to the latest version was something I wanted to try out and it works fine for me.

But as I said in the original post, I'm not so sure if that's a good idea, so we can leave it out, of course.

2021-07-02 18:59 UTC, Ma27 commented
I removed the `libdrm`-update since it hasn't solved my problem (I'm currently trying out various WLR_* settings). `sway` with a newer wlroots worked fine regardless.

2021-07-07 21:29 UTC, Ma27 commented
The (more, but currently less frequent) crashes I see were already an issue on sway 1.6, apart from that I don't see any issues with sway 1.6.1/wlroots 0.14.0 on 21.05. Because of that I'm going to mark it as ready for review now.

2021-07-08 02:01 UTC, AndersonTorres requested changes

2021-07-08 02:01 UTC, AndersonTorres commented on pkgs/applications/window-managers/cagebreak/default.nix
> +      # Add fixes for wlroots 0.14.0
Redundant comment.

2021-07-08 02:01 UTC, AndersonTorres commented on pkgs/applications/window-managers/labwc/default.nix
> +      # output: access texture width/height directly
Redundant?

2021-07-08 07:43 UTC, Ma27 commented
> Redundant comment.

Yeah, I really don't want to change commits during a backport though unless it's strictly needed.

2021-07-08 11:46 UTC, primeos requested changes
This PR currently contains both `libdrm: 2.4.105 -> 2.4.106` and a commit which reverts that update so I'd say we should certainly drop both (even though it doesn't really change the end result).

And what's the current state on this?:
> Additionally I though we intended to backport the wlroots update as wlroots_0_14 (#128036 (comment)) or are you against that idea?

Currently this PR doesn't use that approach. If we don't want to use that approach it might make sense to drop wlroots 0.13 entirely like on `nixos-unstable`: https://github.com/NixOS/nixpkgs/issues/118838

Anyway, I'm fine with both approaches so this is mainly a question because no explicit decision was made so far (apart from the diff).

> Edit: before anybody considers a merge here, an ACK from @primeos should be awaited :)

I'll give this an ACK then in case anyone wants to merge it ;) I haven't done any testing and don't use NixOS 21.05 but the idea and diff LGTM (although certainly not risk free, there are a few changes that could be considered "breaking" but hopefully it won't affect any actual setups in a meaningful way). Other than the two libdrm commits this should already be ok.

2021-07-08 12:58 UTC, primeos commented
https://octodon.social/@emersion/106544587943751964
> Alright, I think I fixed all known wlroots 0.14.0 regressions. Some were pretty tricky. 0.14.1 coming soon!

Just as an FYI (not sure if it's worth it to wait for wlroots 0.14.1 before merging this or not).

2021-07-08 14:30 UTC, merged

2021-07-11 18:08 UTC, primeos commented
@Ma27 if you're interested we could/should also backport #129667 (should be fine to go directly into `staging-next-21.05` so that it lands together with this PR once #129778 is merged).