kustomize_3: init at 3.10.0
NixOS/nixpkgs pull request #128593
Opened 2021-06-29 05:47 UTC by starcraft66

###### Motivation for this change

Kustomize 4 has a lot of breaking changes so it is desirable to keep the last version of Kustomize 3 available for installation in nixpkgs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-06-29 23:46 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  kustomize_3 = callPackage ../development/tools/kustomize/3.10.0.nix { };
```suggestion
  kustomize_3 = callPackage ../development/tools/kustomize/3.nix { };
```

2021-06-29 23:47 UTC, SuperSandro2000 requested changes

2021-06-29 23:47 UTC, SuperSandro2000 commented on pkgs/development/tools/kustomize/3.10.0.nix
> +    maintainers = with maintainers; [ carlosdagos vdemeester periklis zaninime Chili-Man saschagrunert ];
```suggestion
    maintainers = with maintainers; [ carlosdagos vdemeester zaninime Chili-Man saschagrunert ];
```

2021-06-29 23:47 UTC, SuperSandro2000 commented on pkgs/development/tools/kustomize/3.10.0.nix
> +    '';
```suggestion
  ldflags = let t = "sigs.k8s.io/kustomize/api/provenance"; in [
    "-s -w"
    "-X ${t}.version=${version}"
    "-X ${t}.gitCommit=${rev}"
  ];
```

2021-06-30 08:15 UTC, vdemeester reviewed
LGTM 👍🏼

2021-06-30 22:34 UTC, merged