python3Packages.mip: init at 1.13.0
NixOS/nixpkgs pull request #128896
Opened 2021-07-01 16:18 UTC by danielbarter

###### Motivation for this change

adding mip to the python package library

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-01 16:22 UTC, dotlambda requested changes

2021-07-01 16:22 UTC, dotlambda commented on pkgs/development/python-modules/mip/default.nix
> +    description = "MIP is a collection of tools for Mixed-Integer Linear programs.";
```suggestion
    description = "Ccollection of tools for Mixed-Integer Linear programs";
```
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md

2021-07-01 16:22 UTC, dotlambda commented on pkgs/development/python-modules/mip/default.nix
> +  buildInputs = [ setuptools_scm cffi ];
```suggestion
  buildInputs = [ setuptools-scm cffi ];
```

2021-07-01 16:22 UTC, dotlambda commented on pkgs/development/python-modules/mip/default.nix
> +  doCheck = false;
Why?

2021-07-02 06:25 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 128896` at 550444d9 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.mip</li>
    <li>python39Packages.mip</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/python-include-tests.md">python-include-tests</a>

Consider adding a `checkPhase` for tests, or if not feasible, `pythonImportsCheck`.

Near pkgs/development/python-modules/mip/default.nix:26:0:
```
   |
26 |     description = "Collection of tools for Mixed-Integer Linear programs";
   | ^
```
</li>
  </ul>
</details>

2021-08-25 11:27 UTC, SuperSandro2000 commented on pkgs/development/python-modules/mip/default.nix
> +  buildInputs = [ setuptools-scm zlib cffi ];
cffi belongs into nativeBuildInputs.

2021-09-14 04:07 UTC, samuela commented on pkgs/development/python-modules/mip/default.nix
> +  };
Why not fetchFromGitHub and then run the test suite?

2021-11-12 16:38 UTC, SuperSandro2000 commented
Closing due to no response from author in a while.

2021-11-12 16:38 UTC, closed without merging