gitlint: override requirements
NixOS/nixpkgs pull request #129169
Opened 2021-07-03 19:24 UTC by fabaff

###### Motivation for this change
Upstream is pinning their requirements and this causes build issues. 

Fixes #128998

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-03 19:37 UTC, fabaff commented
Result of `nixpkgs-review pr 129169` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitlint</li>
  </ul>
</details>

2021-07-05 22:28 UTC, polygon commented
Since there is a derivation for Click 7.1.2, would it make sense to use this one? I've managed to do that by changing all-packages.nix like so:

```
gitlint = python3Packages.callPackage ../tools/misc/gitlint {
  click = python3Packages.callPackage ../development/python-modules/click/7.nix { };
};
```

2021-07-05 23:13 UTC, ethancedwards8 commented
> Since there is a derivation for Click 7.1.2, would it make sense to use this one? I've managed to do that by changing all-packages.nix like so:
> 
> ```
> gitlint = python3Packages.callPackage ../tools/misc/gitlint {
>   click = python3Packages.callPackage ../development/python-modules/click/7.nix { };
> };
> ```

I believe this would be the correct way to do it.

2021-07-05 23:56 UTC, SuperSandro2000 commented
> Since there is a derivation for Click 7.1.2, would it make sense to use this one? I've managed to do that by changing all-packages.nix like so:
> 
> ```
> gitlint = python3Packages.callPackage ../tools/misc/gitlint {
>   click = python3Packages.callPackage ../development/python-modules/click/7.nix { };
> };
> ```

overwriteAttr is the preferred way for applications and we try very hard to not have multiple versions of pythonPackages because mixing them causes issues.

2021-07-06 00:08 UTC, dotlambda requested changes
Please use
```
python3.override {
  packageOverrides = ...
}
```

2021-07-08 16:42 UTC, fabaff commented
Result of `nixpkgs-review pr 129169` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>gitlint</li>
  </ul>
</details>

2021-07-08 17:13 UTC, ethancedwards8 commented
Hey @fabaff feel free to add yourself as a maintainer. You're clearly more knowledgeable (and active) than me, I would've had no clear where to start fixing this.

2021-07-08 22:51 UTC, SuperSandro2000 commented on pkgs/tools/misc/gitlint/default.nix
>      homepage = "http://jorisroovers.github.io/gitlint";
```suggestion
    homepage = "https://jorisroovers.com/gitlint/";
```

2021-07-09 10:47 UTC, fabaff commented on pkgs/tools/misc/gitlint/default.nix
>      homepage = "http://jorisroovers.github.io/gitlint";
Updated, thanks.

2021-07-09 12:44 UTC, merged