cargo-audit: 0.14.1 -> 0.15.0
NixOS/nixpkgs pull request #129191
Opened 2021-07-03 22:52 UTC by fabaff

###### Motivation for this change
Update to latest upstream release 0.15.0

Change log: https://github.com/RustSec/rustsec/blob/main/cargo-audit/CHANGELOG.md#0150-2021-07-01

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-04 00:15 UTC, lovesegfault requested changes, later dismissed
Please don't reformat packages you don't maintain while bumping.

The listed maintainer has the say when it comes to styling, and it inflates diffs unnecessarily.

Also, what happened to the `rev` line?

2021-07-04 01:01 UTC, SuperSandro2000 commented
> Please don't reformat packages you don't maintain while bumping.

> and it inflates diffs unnecessarily.

I don't have a problem with that.

> The listed maintainer has the say when it comes to styling

Maintainer does not really grant you any special role, duties or responsibilities. Some people have strong feelings about this but usually I would just merge this as is without any intervention.

2021-07-04 01:26 UTC, lovesegfault commented
> > The listed maintainer has the say when it comes to styling
> 
> Maintainer does not really grant you any special role, duties or responsibilities. Some people have strong feelings about this but usually I would just merge this as is without any intervention.

Unless this changed and I'm not aware, that's actually not true. The listed maintainers both have a burden to actually maintain the package (for example by getting notified/pinged/cc'd on every single issue involving the package) and have the privilege of choosing how the Nix code looks.

You seem to be suggesting that being listed as a maintainer of a package is essentially meaningless, and I do not think that is true. For as long as I have contributed to the project it has been the case that reformatting a derivation that you do not "own" (i.e. explicitly maintain) is considered in poor taste / to be avoided.

Regardless, if your goal is to "bump a package" you should do only as much as you require to achieve that. Reformatting stuff detracts from the goal of your PR. If you are dead set on changing how the package was written, then just put that in a separate commit.

2021-07-04 01:38 UTC, SuperSandro2000 commented
> The listed maintainers both have a burden to actually maintain the package (for example by getting notified/pinged/cc'd on every single issue involving the package) and have the privilege of choosing how the Nix code looks.

That is not happening for a vast majority of the packages. Most packages are being maintained by the very active contributors which are not everywhere maintainer because it does not scale. We are not yet dropping inactive maintainers and the barrier to entry to become a maintainer is very low which usually means if people drop nixpkgs/NixOS or stop using the package the packages they added are left behind.

2021-07-04 04:02 UTC, siraben commented
@SuperSandro2000 The formatting changes seem unnecessary here. I think they should be reverted as they do not add additional value and create code churn.

2021-07-04 04:03 UTC, siraben commented
Result of `nixpkgs-review pr 129191` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cargo-audit</li>
  </ul>
</details>

2021-07-05 10:09 UTC, merged

2021-07-05 10:09 UTC, SuperSandro2000 commented
> @SuperSandro2000 The formatting changes seem unnecessary here. I think they should be reverted as they do not add additional value and create code churn.

Saw that comment to late. Not going to revert anything.

2021-07-05 14:23 UTC, siraben commented
Please keep this in mind for the future.

2021-07-05 16:05 UTC, fabaff commented
Unfortunately, there are different opinions on formatting (readability, ordering, using `nixpkgs-fmt`, etc.) and what changes to include in a single PR. Usually it depends on the reviewer. If the reviewer don't like a change then I'm happy to revert it/update it/split it out.

I hope that someday there will be a "black-isort" thing which will take care about the formatting one time for all :wink: 

In the "Python packages" domain the agreement seems to be that putting inputs on their own line make it easier to perform reviews in the futures. Sure, the cost is that at one point this change has to be included.