[21.05] yggdrasil: add 0.4
NixOS/nixpkgs pull request #129326
Opened 2021-07-05 14:03 UTC by bbigras

###### Motivation for this change

The protocol from 0.4 is not compatible with 0.3, but "we don't want to force migrations on stable".

(Adapted from from commit 7265334f1ab7726e8cbda4670e77c31b42fb5665)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-05 15:56 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 129326` at a3991ef9 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>yggdrasil_0_4</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/tools/networking/yggdrasil/0.4.nix:38:5:
```
   |
38 |     license = licenses.lgpl3;
   |     ^
```
</li>
  </ul>
</details>

2021-07-06 13:42 UTC, bbigras commented
/marvin opt-in
/status needs_reviewer

2021-07-07 08:08 UTC, ehmry commented
I think its fine to replace version 0.3. I've been pushing each release of Zerotier down to the release branch for the same reason.

2021-07-07 11:06 UTC, kevincox requested changes

2021-07-07 11:06 UTC, kevincox commented on pkgs/tools/networking/yggdrasil/0.4.nix
> +{ lib, buildGoModule, fetchFromGitHub, nixosTests }:
Is it possible to just parametrize this file instead of copying the entire config? Also it seems like it would just be best to replace 0.3.

2021-07-07 11:06 UTC, kevincox commented on pkgs/tools/networking/yggdrasil/0.4.nix
> +  passthru.tests.basic = nixosTests.yggdrasil;
Isn't this just testing 0.3?

2021-07-07 16:53 UTC, kevincox approved these changes

2021-07-07 16:54 UTC, bbigras commented
I made the changes to update to 0.4 instead. Thank you both.

2021-07-07 16:58 UTC, kevincox commented
Result of `nixpkgs-review pr 129326` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>yggdrasil</li>
  </ul>
</details>

2021-07-07 17:22 UTC, kevincox commented
I'm not sure why that package is failing, building it manually works:

```
% nix-build -A nixos-install-tools
/nix/store/3yq7q4pwqzgz5p58qr57d58g0hmgip1c-nixos-install-tools-21.05.git.9508a9abaa1M
```

2021-07-07 17:22 UTC, merged

2021-07-07 17:23 UTC, bbigras commented
Thanks!