Allow Phosh to use geoclue
NixOS/nixpkgs pull request #129630
Opened 2021-07-08 09:50 UTC by tomfitzhenry

###### Motivation for this change
Allow Phosh to use geoclue, per https://gitlab.freedesktop.org/geoclue/geoclue/-/commit/a9aea6a4948e2ff9ec5ff066cf20dac069c0d3a0 .

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-08 14:56 UTC, SuperSandro2000 requested changes
Please follow the contributing guide when naming commits.

2021-07-08 23:58 UTC, tomfitzhenry commented
> SuperSandro2000 changed the title Allow Phosh to use geoclue nixos/geoclue2: allow Phosh to use geoclue

Thanks, my bad!

2021-08-07 05:09 UTC, tomfitzhenry commented
Are there any other ways this PR can be improved? @SuperSandro2000 @zhaofengli

2021-08-07 10:09 UTC, SuperSandro2000 commented
I don't really review services.

2021-08-10 07:49 UTC, zhaofengli commented
Sorry, completely forgot about this one :cry: Diff looks reasonable, but I'm not sure how I can test that it's working. I tried GNOME Maps but somehow it got my location without me seeing any kind of dialog from Phosh (the geoclue agent).

2021-08-10 13:17 UTC, aanderse commented
Sorry... I don't know much about this or have any way to test it. Doesn't @Infinisil know something about `geoclue`? Or @dasJ... they might.

2021-09-28 10:19 UTC, tomfitzhenry commented
I've lost context/state on this, sorry!

2021-09-28 10:19 UTC, closed without merging