rPackages.R_cache: fix build
NixOS/nixpkgs pull request #129746
Opened 2021-07-09 11:05 UTC by tomcur

Disable R.cache checks as it tries to write to home folder storage in its tests.

###### Motivation for this change

Prior to this change the build fails with:

```
$ nix-build -A rPackages.R_cache
this derivation will be built:
  /nix/store/35wf9bdk9pnfi53b7vsh85ky25ny749p-r-R.cache-0.15.0.drv
...
* installing *source* package 'R.cache' ...
...
Warning in normalizePath("~") :
  path[1]="/homeless-shelter": No such file or directory
Error: package or namespace load failed for 'R.cache':
 .onLoad failed in loadNamespace() for 'R.cache', details:
  call: mkdirs.default(parent, mustWork = mustWork, maxTries = maxTries,
  error: Failed to create directory (tried 5 times), most likely because of lack of file permissions (directory '' exists but nothing beyond): /homeless-shelter
```

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-09 11:32 UTC, SuperSandro2000 commented
Can we set $HOME to a temporary directory to run the tests anyway?

2021-07-09 14:05 UTC, tomcur commented
@SuperSandro2000 That works too. Rather than an ad-hoc fix for this specific package I've extended `r-modules` to more easily fix this for other packages in the future, too. If this looks good we can squash and merge.

2021-09-21 12:14 UTC, jbedo requested changes
This is great, we can resolve a bunch of failing builds with this. Can you squash down to two commits fixing:

1. the typo
2. introducing the home override?

The original R_cache package is fixed in a different way and so can be removed from the packagesRequiringHome list, but there are others with this issue that can be used for testing (e.g., `R_filesets`).

2021-10-11 07:23 UTC, merged

2021-10-11 07:23 UTC, jbedo commented
Thanks for your contribution!