Open vm tools 11.3.0
NixOS/nixpkgs pull request #129978
Opened 2021-07-11 23:39 UTC by kjeremy

###### Motivation for this change

Enables KMS for Wayland and installs the proper udev rules.

Fixes #102388
Fixes #45751

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-12 00:00 UTC, kjeremy commented
I tested this on nixos 21.05 and it fixed my resolution problems in vmware.

2021-07-12 00:31 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 129978` at 42ea61bc run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>open-vm-tools</li>
    <li>open-vm-tools-headless</li>
  </ul>
</details>
<details>
  <summary>4 suggestions:</summary>
  <ul>
    <li>warning: unused-argument

Unused argument: `fetchpatch`.
Near pkgs/applications/virtualization/open-vm-tools/default.nix:1:62:
```
  |
1 | { stdenv, lib, fetchFromGitHub, makeWrapper, autoreconfHook, fetchpatch,
  |                                                              ^
```
</li>
    <li>warning: unused-argument

Unused argument: `linux-pam`.
Near pkgs/applications/virtualization/open-vm-tools/default.nix:5:3:
```
  |
5 |   linux-pam, libdrm, udev,
  |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/virtualization/open-vm-tools/default.nix:69:5:
```
   |
69 |     license = licenses.gpl2;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

rpcsvc-proto is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/virtualization/open-vm-tools/default.nix:24:3:
```
   |
24 |   buildInputs = [ fuse glib icu libdnet libdrm libmspack libtirpc openssl pam procps rpcsvc-proto udev xercesc ]
   |   ^
```
</li>
  </ul>
</details>

2021-07-12 01:21 UTC, SuperSandro2000 requested changes
@ofborg eval

2021-07-12 01:21 UTC, SuperSandro2000 commented on pkgs/applications/virtualization/open-vm-tools/default.nix
>      ++ lib.optional (!withX) "--without-x";
```suggestion
  configureFlags = [
    "--without-kernel-modules"
    "--without-xmlsecurity"
    "--with-udev-rules-dir=${placeholder "out"}/lib/udev/rules.d"
  ] ++ lib.optional (!withX) "--without-x";
```

2021-07-12 01:21 UTC, SuperSandro2000 commented on pkgs/applications/virtualization/open-vm-tools/default.nix
> -    (fetchpatch {
Please remove the unused fetchpatch from inputs.

2021-07-14 00:14 UTC, SuperSandro2000 commented on pkgs/applications/virtualization/open-vm-tools/default.nix
>    withX ? true }:
```suggestion
{ stdenv, lib, fetchFromGitHub, makeWrapper, autoreconfHook
, bash, fuse, libmspack, openssl, pam, xercesc, icu, libdnet, procps, libtirpc, rpcsvc-proto
, libX11, libXext, libXinerama, libXi, libXrender, libXrandr, libXtst
, pkg-config, glib, gdk-pixbuf-xlib, gtk3, gtkmm3, iproute2, dbus, systemd, which
, libdrm, udev
, withX ? true
}:
```

2021-07-14 01:26 UTC, merged

2021-07-14 11:40 UTC, kjeremy commented
Do I have to create a PR to get this into 21.05 or does it roll in eventually?

2021-07-14 13:14 UTC, Mic92 commented
It does not but only if one adds a lable like this one.

2021-07-14 13:19 UTC, ajs124 commented
"Update pkgs/applications/virtualization/open-vm-tools/default.nix" I doubt that commit message is according to our contribution guidelines

2021-07-14 13:30 UTC, Mic92 commented
This seems to originate from github's ui. A squash on merge would have solved that but than also some of the git history would have been lost.

2021-07-14 13:31 UTC, Mic92 commented
It would be nice if github's ui would allow to amend a commit or create a fixup instead of a new commit.