python3Packages.ev3dev2: init at 2.1.0
NixOS/nixpkgs pull request #130274
Opened 2021-07-15 13:25 UTC by angustrau

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-15 14:07 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 130274` at 42137fe7 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.ev3dev2</li>
    <li>python39Packages.ev3dev2</li>
  </ul>
</details>

2021-07-15 17:17 UTC, SuperSandro2000 requested changes

2021-07-15 17:17 UTC, SuperSandro2000 commented on pkgs/development/python-modules/ev3dev2/default.nix
> +  prePatch = ''
```suggestion
  postPatch = ''
```

2021-07-15 17:17 UTC, SuperSandro2000 commented on pkgs/development/python-modules/ev3dev2/default.nix
> +    description = "v2.x Python language bindings for ev3dev";
```suggestion
    description = "Python language bindings for ev3dev";
```

2021-07-16 06:38 UTC, jonringer commented on pkgs/development/python-modules/ev3dev2/default.nix
> +    python3 -W ignore::ResourceWarning tests/api_tests.py
```suggestion
    ${python.interpreter} -W ignore::ResourceWarning tests/api_tests.py
```
to support alt interpreters

2021-07-17 18:57 UTC, merged