Adds Rubik font v2.200
NixOS/nixpkgs pull request #130217
Opened 2021-07-14 19:49 UTC by kuzzmi

###### Motivation for this change

I am a huge fan of Rubik font and would like to add it to nixpkgs for everybody to use.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Tested on a fresh NixOS installation both through Home Manager and from NixOS main configuration file
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-15 21:39 UTC, SuperSandro2000 requested changes
Please follow the contributing guide:
- name the commit ``rubik-font: init at 2.200``
- add an entry to top-level.nix
- do not reference the nixpkgs channel but instead add the inputs separately

2021-07-15 21:39 UTC, SuperSandro2000 commented on pkgs/data/fonts/rubik/rubik.nix
> +with import <nixpkgs> {};
```suggestion
{ stdenv, ... }:
```

2021-07-15 21:39 UTC, SuperSandro2000 commented on pkgs/data/fonts/rubik/rubik.nix
> +
```suggestion
```

2021-07-15 21:39 UTC, SuperSandro2000 commented on pkgs/data/fonts/rubik/rubik.nix
> +    description = "Rubik Fonts";
```suggestion
    description = "Rubik Font - is a 5 weight Roman + Italic family.";
```

2021-07-25 18:51 UTC, kuzzmi commented
@SuperSandro2000 

I updated my commit with all three requested changes.  
Also, I added the font package to `top-level/all-packages.nix`, not sure tho if that is the one I had to update.

2021-08-05 07:56 UTC, merged