Added krunner-symbols
NixOS/nixpkgs pull request #130588
Opened 2021-07-19 01:57 UTC by hqurve

###### Motivation for this change
I would like to use the addon as it is very convenient. 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-19 02:03 UTC, hqurve commented
I'm not sure how to label this, but I tested the package in a virtual machine by adding it to systemPackages and calling with `libsForQt5.callPackage`.

2021-07-19 02:14 UTC, urlordjames commented
See [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md), you need to add yourself to `maintainers/maintainer-list.nix` (in a separate commit) then add yourself to `meta.maintainers`.

2021-07-19 02:22 UTC, urlordjames commented on pkgs/desktops/plasma-5/3rdparty/addons/krunner-symbols.nix
> +    license = licenses.gpl3;
Fairly sure `licenses.gpl3` is deprecated, I believe you're supposed to use `licenses.gpl3Only` or `licenses.gpl3Plus` now.

2021-07-19 15:14 UTC, urlordjames reviewed
I would also squash these commits down to two (one adding yourself to the maintainer list and the other with all the rest of the changes).

2021-07-19 15:14 UTC, urlordjames commented on pkgs/desktops/plasma-5/3rdparty/addons/krunner-symbols.nix
> +  prePatch = ''
I would leave some comment explaining the purpose of this.

2021-07-20 15:36 UTC, SuperSandro2000 requested changes

2021-07-20 15:36 UTC, SuperSandro2000 commented on pkgs/desktops/plasma-5/3rdparty/addons/krunner-symbols.nix
> +  prePatch = ''
```suggestion
  postPatch = ''
```

2021-07-20 15:36 UTC, SuperSandro2000 commented on pkgs/desktops/plasma-5/3rdparty/addons/krunner-symbols.nix
> +    sed -i 's,LOCATION_DESKTOP,KDE_INSTALL_KSERVICES5DIR,' CMakeLists.txt
```suggestion
    # change cmake flag names to output using the correct qt-plugin prefix and  kservice location
    substituteInPlace CMakeLists.txt \
      --replace "LOCATION_DESKTOP" "KDE_INSTALL_KSERVICES5DIR" \
      --replace "LOCATION_PLUGIN" "KDE_INSTALL_PLUGINDIR"
```

2021-07-20 15:36 UTC, SuperSandro2000 commented on pkgs/desktops/plasma-5/3rdparty/addons/krunner-symbols.nix
> +    sed -i 's,/usr/share/config/krunner-symbol,'$out'/share/config/krunner-symbol,' symbols.cpp
```suggestion
    substituteInPlace symbols.cpp \
      --replace "/usr/share/config/krunner-symbol" "$out'/share/config/krunner-symbol"
```

2021-07-20 15:36 UTC, SuperSandro2000 commented on pkgs/desktops/plasma-5/3rdparty/addons/krunner-symbols.nix
> +stdenv.mkDerivation rec {
```suggestion
}:

stdenv.mkDerivation rec {
```

2021-07-20 15:36 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +  hqurve = {
Please add yourself as a maintainer by adding an alphabetically sorted entry to `maintainers/maintainer-list.nix` and commit this change into a separate commit with the message ``maintainers: add NAME`` into this PR.

2021-07-22 07:45 UTC, merged

2022-02-18 01:22 UTC, aanderse commented
@hqurve is there anything special I have to do to be able to use this? I added this to my `environment.systemPackages` but the plugin never showed up in `krunner`.

2022-02-18 10:27 UTC, hqurve commented
Yes you just add it to `environment.systemPackages` and it should appear (I dont recall if a restart is necessary)
![Screenshot from 2022-02-18 06-26-10](https://user-images.githubusercontent.com/53281855/154664962-edff184f-38c2-42f4-9df4-f5a006a94e34.png)

In fact I have it added through home-manager using `home.packages` and it also works,

2022-02-23 02:02 UTC, aanderse commented
Something must have been funky with my desktop... it only worked after logging out and then logging back in. Thanks!