Patch mysql connector
NixOS/nixpkgs pull request #130734
Opened 2021-07-20 08:51 UTC by neosimsim

###### Motivation for this change
python module mysql-conncetor fails to build on darwin (macOS) https://github.com/NixOS/nixpkgs/issues/130376.

###### Things done
Compared with last successful version and found out there was a version bump of mysql-connector which add a strange commit https://github.com/mysql/mysql-connector-python/commit/d1e89fd3d7391084cdf35b0806cb5d2a4b413654 for macOS distributions. Reverting this commit makes the derivatoin work again.

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-20 08:52 UTC, neosimsim commented
Closes #130376

2021-07-20 09:05 UTC, turion commented on pkgs/development/python-modules/mysql-connector/default.nix
> +    # mysql-connector overrides MACOSX_DEPLOYMENT_TARGET to 11.
Is there an upstream issue we could link? If not, one should probably be created.

2021-07-20 09:05 UTC, turion commented on pkgs/development/python-modules/mysql-connector/default.nix
> +    maintainers = with lib.maintainers; [ turion neosimsim ];
```suggestion
    maintainers = with lib.maintainers; [
      neosimsim
      turion
    ];
```
I vaguely remember that some people prefer this style.

2021-07-20 09:06 UTC, turion commented
The commit messages should start with `pythonPackages.mysql-connector:` I believe

2021-07-20 09:30 UTC, SuperSandro2000 requested changes
Please update the commit name.

2021-07-20 09:30 UTC, SuperSandro2000 commented on pkgs/development/python-modules/mysql-connector/default.nix
> +    ];
```suggestion
    maintainers = with lib.maintainers; [ neosimsim turion ];
```

2021-07-20 10:28 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 130734` at 41328f83 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.mysql-connector</li>
    <li>python39Packages.mysql-connector</li>
  </ul>
</details>

2021-07-20 11:11 UTC, turion commented on pkgs/development/python-modules/mysql-connector/default.nix
> +    # I guess this patch might be removed once stdenv.targetPlatform.darwinSdkVersion
Just a comment: I'm not so sure about that. With the next version bump after that, it will be out of sync again and fail.

2021-07-20 11:11 UTC, turion approved these changes

2021-09-06 08:50 UTC, turion approved these changes

2021-09-06 08:59 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/399

2021-09-08 22:35 UTC, merged