zen-kernels: 5.12.14 -> 5.12.19
NixOS/nixpkgs pull request #131034
Opened 2021-07-22 07:06 UTC by michaeladler

###### Motivation for this change

This fixes CVE-2021-33909

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-22 08:30 UTC, SuperSandro2000 commented
@TredwellGit should we bump the zen-kernels in the regular updates, too?

2021-07-22 11:12 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 131034` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
9 packages marked as broken and skipped:
</summary>
<ul>
<li>linuxPackages_zen.anbox</li>
<li>linuxPackages_zen.ixgbevf</li>
<li>linuxPackages_zen.mxu11x0</li>
<li>linuxPackages_zen.ndiswrapper</li>
<li>linuxPackages_zen.phc-intel</li>
<li>linuxPackages_zen.r8125</li>
<li>linuxPackages_zen.rtl8723bs</li>
<li>linuxPackages_zen.sch_cake</li>
<li>linuxPackages_zen.tbs</li>
</ul>
</details>
<details>

  <summary>3 packages failed to build and are new build failures:</summary>
  <ul>
<li>linuxPackages_zen.amdgpu-pro: log was empty</li>
<li>linuxPackages_zen.nvidia_x11_legacy340: log was empty</li>
<li>linuxPackages_zen.nvidia_x11_vulkan_beta: log was empty</li>
  </ul>
</details>
<details>
<summary>
78 packages built:
</summary>
<ul>
<li>linuxPackages_zen.acpi_call</li>
<li>linuxPackages_zen.akvcam</li>
<li>linuxPackages_zen.apfs</li>
<li>linuxPackages_zen.asus-wmi-sensors</li>
<li>linuxPackages_zen.batman_adv</li>
<li>linuxPackages_zen.bbswitch</li>
<li>linuxPackages_zen.bcc</li>
<li>linuxPackages_zen.bpftrace</li>
<li>linuxPackages_zen.broadcom_sta</li>
<li>linuxPackages_zen.can-isotp</li>
<li>linuxPackages_zen.chipsec</li>
<li>linuxPackages_zen.cpupower</li>
<li>linuxPackages_zen.cryptodev</li>
<li>linuxPackages_zen.ddcci-driver</li>
<li>linuxPackages_zen.digimend</li>
<li>linuxPackages_zen.dpdk-kmods</li>
<li>linuxPackages_zen.ena</li>
<li>linuxPackages_zen.evdi</li>
<li>linuxPackages_zen.facetimehd</li>
<li>linuxPackages_zen.fwts-efi-runtime</li>
<li>linuxPackages_zen.gcadapter-oc-kmod</li>
<li>linuxPackages_zen.hid-nintendo</li>
<li>linuxPackages_zen.hyperv-daemons</li>
<li>linuxPackages_zen.intel-speed-select</li>
<li>linuxPackages_zen.isgx</li>
<li>linuxPackages_zen.it87</li>
<li>linuxPackages_zen.jool</li>
<li>linux_zen (linuxPackages_zen.kernel)</li>
<li>linuxPackages_zen.kvmfr</li>
<li>linuxPackages_zen.lttng-modules</li>
<li>linuxPackages_zen.mba6x_bl</li>
<li>linuxPackages_zen.mbp2018-bridge-drv</li>
<li>linuxPackages_zen.mwprocapture</li>
<li>linuxPackages_zen.netatop</li>
<li>linuxPackages_zen.nvidia_x11</li>
<li>linuxPackages_zen.nvidia_x11_beta</li>
<li>linuxPackages_zen.nvidia_x11_legacy390</li>
<li>linuxPackages_zen.nvidiabl</li>
<li>linuxPackages_zen.oci-seccomp-bpf-hook</li>
<li>linuxPackages_zen.openafs (linuxPackages_zen.openafs_1_8)</li>
<li>linuxPackages_zen.openafs_1_9</li>
<li>linuxPackages_zen.openrazer</li>
<li>linuxPackages_zen.perf</li>
<li>linuxPackages_zen.ply</li>
<li>linuxPackages_zen.r8168</li>
<li>linuxPackages_zen.rtl8188eus-aircrack</li>
<li>linuxPackages_zen.rtl8192eu</li>
<li>linuxPackages_zen.rtl8812au</li>
<li>linuxPackages_zen.rtl8814au</li>
<li>linuxPackages_zen.rtl8821au</li>
<li>linuxPackages_zen.rtl8821ce</li>
<li>linuxPackages_zen.rtl8821cu</li>
<li>linuxPackages_zen.rtl88x2bu</li>
<li>linuxPackages_zen.rtl88xxau-aircrack</li>
<li>linuxPackages_zen.rtw88 (linuxPackages_zen.rtlwifi_new)</li>
<li>linuxPackages_zen.rtw89</li>
<li>linuxPackages_zen.sysdig</li>
<li>linuxPackages_zen.system76</li>
<li>linuxPackages_zen.system76-acpi</li>
<li>linuxPackages_zen.system76-io</li>
<li>linuxPackages_zen.systemtap</li>
<li>linuxPackages_zen.tmon</li>
<li>linuxPackages_zen.tp_smapi</li>
<li>linuxPackages_zen.turbostat</li>
<li>linuxPackages_zen.tuxedo-keyboard</li>
<li>linuxPackages_zen.usbip</li>
<li>linuxPackages_zen.v4l2loopback</li>
<li>linuxPackages_zen.v86d</li>
<li>linuxPackages_zen.veikk-linux-driver</li>
<li>linuxPackages_zen.vendor-reset</li>
<li>linuxPackages_zen.vhba</li>
<li>linuxPackages_zen.virtualbox</li>
<li>linuxPackages_zen.virtualboxGuestAdditions</li>
<li>linuxPackages_zen.x86_energy_perf_policy</li>
<li>linuxPackages_zen.xmm7360-pci</li>
<li>linuxPackages_zen.xpadneo</li>
<li>linuxPackages_zen.zenpower</li>
<li>linuxPackages_zen.zfs (linuxPackages_zen.zfsStable ,linuxPackages_zen.zfsUnstable)</li>
</ul>
</details>

2021-07-22 16:02 UTC, Atemu requested changes
Please bump both of our zen-kernels and use the newest release (i.e. lqx2)

2021-07-22 16:04 UTC, Atemu commented
@SuperSandro2000 no. Their release lags behinds significantly (the regular kernels shouldn't be held back by that) and releases aren't always stable when they come out.

2021-07-23 06:05 UTC, michaeladler commented
Closing this in favor of https://github.com/NixOS/nixpkgs/pull/131113 which also addresses lqx2

2021-07-23 06:05 UTC, closed without merging