tools/{text/typesetting}: replace name with pname&version
NixOS/nixpkgs pull request #131709
Opened 2021-07-27 17:39 UTC by Stunkymonkey

###### Motivation for this change
#103997

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-08-01 21:32 UTC, Stunkymonkey commented
anybody an idea, what is causing the massive rebuilds here?

2021-08-02 03:44 UTC, davidak commented
>anybody an idea, what is causing the massive rebuilds here?

maybe psutils, but not sure

could you just rebase to use staging or would that cause merge conflicts when staging is merged back?

2021-08-02 09:14 UTC, Stunkymonkey commented
maybe we can merge `psutils` separately #132398.

2021-08-02 11:11 UTC, Stunkymonkey commented
@ofborg eval

2021-08-02 14:37 UTC, SuperSandro2000 requested changes
also please target staging

2021-08-02 14:37 UTC, SuperSandro2000 commented on pkgs/tools/text/catdocx/default.nix
> +  version = "2017-01-02";
```suggestion
  version = "unstable-2017-01-02";
```

2021-08-02 14:37 UTC, SuperSandro2000 commented on pkgs/tools/text/mpage/default.nix
> +    url = "http://www.mesa.nl/pub/mpage/mpage-${version}.tgz";
```suggestion
    url = "https://www.mesa.nl/pub/mpage/mpage-${version}.tgz";
```

2021-08-02 14:37 UTC, SuperSandro2000 commented on pkgs/tools/text/yaml-merge/default.nix
> +  version = "2016-02-16";
```suggestion
  version = "unstable-2016-02-16";
```

2021-08-02 14:37 UTC, SuperSandro2000 commented on pkgs/tools/typesetting/hevea/default.nix
> +    url = "http://pauillac.inria.fr/~maranget/hevea/distri/hevea-${version}.tar.gz";
```suggestion
    url = "https://pauillac.inria.fr/~maranget/hevea/distri/hevea-${version}.tar.gz";
```

2021-08-02 15:23 UTC, jonringer commented
for rebasing, you can do:
```
common=$(git merge-base origin/master origin/staging)
git rebase --onto=$common HEAD~4 # or however many commits you want to carry over
git push ... ... --force
```
then change the base branch to the relevant branch.

2021-08-02 17:54 UTC, Stunkymonkey commented
I forgot to change the base in the PR itself.

2021-08-03 00:39 UTC, davidak commented
Result of `nixpkgs-review pr 131709` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>diffstat</li>
  </ul>
</details>

2021-08-03 00:40 UTC, davidak commented
Building this would lead to download more than 50 GB of sources. I don't have that much free space and i don't think it's useful.

So should we just merge this after reviewing the code changes?

I have tested one package to see if it generally evaluates.

2021-08-03 00:47 UTC, davidak approved these changes
Changes look good.

2021-08-04 19:23 UTC, merged