unixcw: fix qt wrapping
NixOS/nixpkgs pull request #131816
Opened 2021-07-28 12:58 UTC by rbrewer123

###### Motivation for this change
xcwcp gave a qt error and failed to start.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-07-29 21:44 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 131816` at 2a90cf13 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>unixcw</li>
  </ul>
</details>
<details>
  <summary>3 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-patch-comment.md">missing-patch-comment</a>

Consider adding a comment explaining the purpose of this patch on the line preceeding.
Near pkgs/applications/radio/unixcw/default.nix:10:5:
```
   |
10 |     ./remove-use-of-dlopen.patch
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/build-tools-in-build-inputs.md">build-tools-in-build-inputs</a>

pkg-config is a build tool so it likely goes to `nativeBuildInputs`, not `buildInputs`.

Near pkgs/applications/radio/unixcw/default.nix:12:3:
```
   |
12 |   buildInputs = [libpulseaudio alsa-lib pkg-config qt5.qtbase];
   |   ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/applications/radio/unixcw/default.nix:34:5:
```
   |
34 |     license = licenses.gpl2;
   |     ^
```
</li>
  </ul>
</details>

2021-07-30 13:05 UTC, SuperSandro2000 requested changes

2021-07-30 13:05 UTC, SuperSandro2000 commented on pkgs/applications/radio/unixcw/default.nix
>    buildInputs = [libpulseaudio alsa-lib pkg-config qt5.qtbase];
```suggestion
  buildInputs = [ libpulseaudio alsa-lib pkg-config qtbase ];
```

2021-07-30 13:05 UTC, SuperSandro2000 commented on pkgs/applications/radio/unixcw/default.nix
> +{lib, mkDerivation, fetchurl, libpulseaudio, alsa-lib , pkg-config, qt5}:
```suggestion
{ lib, mkDerivation, fetchurl, libpulseaudio, alsa-lib , pkg-config, qtbase }:

```

2021-08-03 03:31 UTC, merged