powercap: init at c993fb1da1bba5c2cd2860c1aa6c3916b4de77e4
NixOS/nixpkgs pull request #132337
Opened 2021-08-01 17:13 UTC by rowanG077

###### Motivation for this change
I8kutils was not packaged. This is a simple utility that allows fan control on most Dell laptops.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-08-01 22:48 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 132337` at cd7aa40e run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>i8kutils</li>
  </ul>
</details>
<details>
  <summary>2 suggestions:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md">unclear-gpl</a>

`gpl2` is a deprecated license, please check if project uses `gpl2Plus` or `gpl2Only` and change `meta.license` accordingly.

Near pkgs/os-specific/linux/i8kutils/default.nix:26:5:
```
   |
26 |     license = licenses.gpl2;
   |     ^
```
</li>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/missing-phase-hooks.md">missing-phase-hooks</a>

`installPhase` should probably contain `runHook preInstall` and `runHook postInstall`.

Near pkgs/os-specific/linux/i8kutils/default.nix:16:3:
```
   |
16 |   installPhase = ''
   |   ^
```
</li>
  </ul>
</details>

2021-08-21 03:20 UTC, hrhino requested changes

2021-08-21 03:20 UTC, hrhino commented on pkgs/os-specific/linux/i8kutils/default.nix
> +  version = "c993fb1da1bba5c2cd2860c1aa6c3916b4de77e4";
use date-based version please, if they don't have releases/tags
```suggestion
  version = "unstable-2021-03-30";
```

2021-08-21 03:20 UTC, hrhino commented on pkgs/os-specific/linux/i8kutils/default.nix
> +    sed "s|i8kfan       /usr/bin/i8kfan|i8kfan       $out/bin/i8kfan|g" i8kmon > $out/bin/i8kmon
```suggestion
    substitute ./i8kfan $out/bin/i8kfan --replace "/usr/bin/i8kctl" "$out/bin/i8kctl"
    substitute ./i8kmon $out/bin/i8kmon --replace "/usr/bin/i8kfan" "$out/bin/i8kfan"
```

2021-08-21 03:20 UTC, hrhino commented on pkgs/os-specific/linux/i8kutils/default.nix
> +    license = licenses.gpl2Plus;
had me going for a second -- the `COPYING` file in that repo is GPLv3 but the headers do say "2 or later"... weird...

2021-08-21 03:22 UTC, hrhino commented
Also, I have a Dell Precision M6800 and running `ik8ctl` gives me what I assume is sane output:
```
[nix-shell:~/.cache/nixpkgs-review/pr-132337/nixpkgs]$ i8kctl 
1.0 A16 (null) 51 0 1 0 2307 -1 -1
```
but (even as root) this doesn't appear to affect the fan speed at all:
```
[nix-shell:~/.cache/nixpkgs-review/pr-132337/nixpkgs]$ sudo i8kctl fan 2 2
0 1
[nix-shell:~/.cache/nixpkgs-review/pr-132337/nixpkgs]$ sudo i8kctl fan 2 2
0 1
```

Am I holding it wrong?

2025-10-29 15:23 UTC, closed without merging