Elemen desktop location fix
NixOS/nixpkgs pull request #132765
Opened 2021-08-05 10:05 UTC by happysalada

###### Motivation for this change

upon running element desktop there is the following error in the terminal
```
Fetching translation json for locale: en
Could not fetch translation json for locale: 'en' Error: Cannot find module './i18n/strings/en.json'
```

I've also run nixpkgs-fmt, hope that's not a problem.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Relase notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-08-05 10:39 UTC, SuperSandro2000 commented on pkgs/applications/networking/instant-messengers/element/element-desktop.nix
>      cp $out/share/element/electron/lib/i18n/strings/en_EN.json $out/share/element/electron/lib/i18n/strings/en-us.json
```suggestion
    cp $out/share/element/electron/lib/i18n/strings/en_EN.json $out/share/element/electron/lib/i18n/strings/en-us.json
    ln -s $out/share/element/electron/lib/i18n/strings/en{,-us}.json
```

2021-08-05 13:11 UTC, yu-re-ka requested changes
Doesn't build, see my suggested change

2021-08-05 13:11 UTC, yu-re-ka commented on pkgs/applications/networking/instant-messengers/element/element-desktop.nix
> +    ln -s $out/share/element/electron/lib/i18n/strings/en{,-us}.json
```suggestion
    ln -s $out/share/element/electron/lib/i18n/strings/en{-us,}.json
```

2021-08-05 17:00 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 132765` at 1f1de628 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>element-desktop</li>
    <li>element-desktop-wayland</li>
  </ul>
</details>

2021-08-06 02:00 UTC, happysalada commented
I've squashed the commits, I'm testing one more time locally just in case.
Thank you both for the reviews!

2021-08-06 05:20 UTC, merged