battop: init a version v0.2.4
NixOS/nixpkgs pull request #133012
Opened 2021-08-07 12:11 UTC by hdhog

###### Motivation for this change

Helpful tool for view power consumption on laptop

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-08-08 04:04 UTC, SuperSandro2000 requested changes
The package is missing a top level entry.
please follow the contributing guide when creating our commits.

2021-08-08 04:04 UTC, SuperSandro2000 commented on pkgs/tools/system/battop/default.nix
> +rustPlatform.buildRustPackage rec {
```suggestion
{ lib, stdenv, fetchFromGitHub, rustPlatform, installShellFiles }:

rustPlatform.buildRustPackage rec {
```

2021-08-08 04:04 UTC, SuperSandro2000 commented on pkgs/tools/system/battop/default.nix
> +  doCheck = false;
Why did you disable tests?

2021-08-08 04:04 UTC, SuperSandro2000 commented on pkgs/tools/system/battop/default.nix
> +    description = ''
```suggestion
    description = "...";
    longDescription = ''
```
please set a short description.

2021-08-08 04:04 UTC, SuperSandro2000 commented on pkgs/tools/system/battop/default.nix
> +    mainProgram = "battop";
```suggestion
```
both are defaults.

2021-08-12 16:39 UTC, hdhog commented on pkgs/tools/system/battop/default.nix
> +    mainProgram = "battop";
i removed it

2021-08-12 16:41 UTC, hdhog commented on pkgs/tools/system/battop/default.nix
> +  doCheck = false;
it's my mistake, fixed

2021-08-15 16:01 UTC, hdhog reviewed
ok i fixed it

2021-08-21 13:24 UTC, merged