nixos/v2ray: add an option for specifying v2ray package used in the systemd service
NixOS/nixpkgs pull request #133700
Opened 2021-08-13 05:35 UTC by poscat0x04

###### Motivation for this change
To use a v2ray package with overridden GeoIP data in the systemd service.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-08-14 08:25 UTC, poscat0x04 commented
@servalcatty

2021-09-12 14:03 UTC, servalcatty requested changes

2021-09-12 14:03 UTC, servalcatty commented on nixos/modules/services/networking/v2ray.nix
> +        default = pkgs.v2ray;
Please also set `defaultText`.

2021-10-08 04:15 UTC, bobby285271 commented
@ofborg test v2ray

2021-10-08 04:38 UTC, merged