psst: init at 318e069
NixOS/nixpkgs pull request #134921
Opened 2021-08-20 06:04 UTC by matthias-t

###### Motivation for this change

Fixes #115155. This won't build until `rustc` 1.54.0 is merged.

Tangentially, I resorted to `fetchgit` since `fetchFromGitHub` seemingly fails to fetch the minivorbis submodule, even with `fetchSubmodules = true`. Could somebody reproduce or investigate this?

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-08-20 10:43 UTC, SuperSandro2000 requested changes

2021-08-20 10:43 UTC, SuperSandro2000 commented on pkgs/applications/audio/psst/default.nix
> +
Final new line to much.

2021-08-20 10:43 UTC, SuperSandro2000 commented on pkgs/applications/audio/psst/default.nix
> +    platforms = lib.platforms.all;
```suggestion
  meta = with lib; {
    description = "Fast and multi-platform Spotify client with native GUI";
    homepage = "https://github.com/jpochyla/psst";
    license = licenses.mit;
    platforms = platforms.all;
```
Missing maintainer.

2021-08-20 10:43 UTC, SuperSandro2000 commented on pkgs/applications/audio/psst/default.nix
> +    url = "https://github.com/jpochyla/${pname}";
```suggestion
    url = "https://github.com/jpochyla/psst";
```
Stop substituting every occurrences of pname and use fetchFromGitHub.

2021-08-20 10:43 UTC, SuperSandro2000 commented on pkgs/applications/audio/psst/default.nix
> +  version = builtins.substring 0 7 rev;
Use unstable-XXXX-XX-XX format.

2021-08-20 10:43 UTC, SuperSandro2000 commented on pkgs/applications/audio/psst/default.nix
> +{ lib, rustPlatform, fetchFromGitHub, pkg-config, dbus, fetchgit, ... }:
```suggestion
{ lib, rustPlatform, fetchFromGitHub, pkg-config, dbus, fetchgit }:
```

2021-08-20 13:41 UTC, figsoda commented
> Tangentially, I resorted to `fetchgit` since `fetchFromGitHub` seemingly fails to fetch the minivorbis submodule, even with `fetchSubmodules = true`. Could somebody reproduce or investigate this?

I can't reproduce this. I tested with this:

```nix
(import <nixpkgs> {}).fetchFromGitHub {
  owner = "jpochyla";
  repo = "psst";
  rev = "318e069ca85d0f58358d9bc8d879ecdd4d4ec0ea";
  sha256 = "0i18i4d1l0vkzz21jwfxhshp3p0w5q8q1dlxlf39b0jjxsgx78qk";
  fetchSubmodules = true;
}
```

2021-08-23 10:28 UTC, SuperSandro2000 requested changes

2021-08-23 10:28 UTC, SuperSandro2000 commented on pkgs/applications/audio/psst/default.nix
> +    platforms = platforms.all;
```suggestion
```

ste by buildRustPackage

2021-08-23 10:30 UTC, SuperSandro2000 commented
> Tangentially, I resorted to fetchgit since fetchFromGitHub seemingly fails to fetch the minivorbis submodule, even with fetchSubmodules = true. Could somebody reproduce or investigate this?

You need to invalidate the hash.

2021-08-28 08:22 UTC, matthias-t commented
Yes, OfBorg runs into [the same](https://logs.nix.ci/?key=nixos/nixpkgs.134921&attempt_id=33707804-a0a7-4de8-bbdc-eec9590ba20a). That's odd, for me the fetcher seems to have succeeded:

<details>
<summary><code>nix-build -A psst</code></summary>
<pre lang="console">
these derivations will be built:
  /nix/store/0v062f8dszz1m7hhm6r0ln5wys1x2g09-psst-unstable-2021-08-19.drv
building '/nix/store/0v062f8dszz1m7hhm6r0ln5wys1x2g09-psst-unstable-2021-08-19.drv'...
unpacking sources
unpacking source archive /nix/store/487dnkc4zgxzqy26pz022yv9ac0dq294-source
source root is source
Executing cargoSetupPostUnpackHook
unpacking source archive /nix/store/mp39hnipp70i4l9avbdzasby2hlkby0j-psst-unstable-2021-08-19-vendor.tar.gz
Finished cargoSetupPostUnpackHook
patching sources
Executing cargoSetupPostPatchHook
Validating consistency between /build/source//Cargo.lock and /build/psst-unstable-2021-08-19-vendor.tar.gz/Cargo.lock
Finished cargoSetupPostPatchHook
configuring
building
Executing cargoBuildHook
++ env CC_x86_64-unknown-linux-gnu=/nix/store/4xs1xyj8728yvh9y5v6ji819kwgfy2fv-gcc-wrapper-10.3.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/4xs1xyj8728yvh9y5v6ji819kwgfy2fv-gcc-wrapper-10.3.0/bin/c++ CC_x86_64-unknown-linux-gnu=/nix/store/4xs1xyj8728yvh9y5v6ji819kwgfy2fv-gcc-wrapper-10.3.0/bin/cc CXX_x86_64-unknown-linux-gnu=/nix/store/4xs1xyj8728yvh9y5v6ji819kwgfy2fv-gcc-wrapper-10.3.0/bin/c++ cargo build -j 4 --target x86_64-unknown-linux-gnu --frozen --release
   Compiling proc-macro2 v1.0.28
   Compiling unicode-xid v0.2.2
   Compiling syn v1.0.74
   Compiling serde v1.0.127
   Compiling serde_derive v1.0.127
[...]
</pre>
</details>

```console
$ nix-store -qR /nix/store/0v062f8dszz1m7hhm6r0ln5wys1x2g09-psst-unstable-2021-08-19.drv
[...]
/nix/store/1270kx4q69baf21zagcdsjksc402rfjz-psst-unstable-2021-08-19-vendor.tar.gz.drv
[...]
```

```console
$ nix-store -q /nix/store/1270kx4q69baf21zagcdsjksc402rfjz-psst-unstable-2021-08-19-vendor.tar.gz.drv
/nix/store/mp39hnipp70i4l9avbdzasby2hlkby0j-psst-unstable-2021-08-19-vendor.tar.gz
```

2021-08-28 13:03 UTC, fabianhjr commented
Do you have sandboxing enabled?

2021-08-28 20:50 UTC, matthias-t commented
I do, according to `nix-info -m`.

2021-09-19 20:56 UTC, ethancedwards8 commented
Any progress on this?

2021-09-20 10:10 UTC, matthias-t commented
The fetch didn't fail because of sandboxing, it failed because the remote couldn't find the commit. I'm not sure why exactly nix was attempting to fetch commit `30aa0baa` on the `psst` branch of the druid repo, but it [appears](https://github.com/jpochyla/druid/commit/30aa0baa) to no longer be part of the branch, supposedly after a force-push. Whatever may have occured exactly, the build should now succeed. However, the application fails for me on wayland with a blank small square window and:

```
(psst-gui:141599): Gtk-CRITICAL **: 12:05:18.310: gtk_window_set_default_size: assertion 'width >= -1' failed
```

2021-09-27 15:30 UTC, glittershark commented
Result of `nixpkgs-review pr 134921` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>psst</li>
  </ul>
</details>

2021-09-27 15:30 UTC, glittershark commented
^ that was with sandboxing enabled, fwiw

2021-09-27 15:42 UTC, figsoda commented
looks like darwin build needs: AppKit CoreFoundation CoreGraphics CoreText CoreVideo Foundation MediaPlayer QuartzCore Security

aarch64-linux build also failed, I don't know what the error messages mean, maybe it just doesn't support it

2021-09-27 20:51 UTC, figsoda requested changes

2021-09-27 20:51 UTC, figsoda commented on pkgs/applications/audio/psst/default.nix
> +    Foundation MediaPlayer QuartzCore Security ]);
can you please inherit these inside `all-packages.nix`?
```suggestion
    ++ lib.optionals stdenv.isDarwin [
      AppKit CoreFoundation CoreGraphics CoreText CoreVideo
      Foundation MediaPlayer QuartzCore Security
    ];
```

2021-09-27 20:51 UTC, figsoda commented on pkgs/applications/audio/psst/default.nix
> +  buildInputs = [ gtk3 glib gdk-pixbuf cairo pango dbus ]
i think some or all of these are only needed for linux, but I'm not sure

2021-11-16 18:27 UTC, SuperSandro2000 commented on pkgs/applications/audio/psst/default.nix
> +    fetchSubmodules = true;
The package has no submodules.

2021-11-16 18:27 UTC, SuperSandro2000 commented on pkgs/applications/audio/psst/default.nix
> +gdk-pixbuf, cairo , pango, dbus, stdenv, darwin ? null }:
```suggestion
gdk-pixbuf, cairo , pango, dbus, stdenv }:
```

2022-02-24 21:10 UTC, matthias-t commented
I'm no longer interested in this, feel free to take over.

2022-07-28 04:16 UTC, figsoda commented
psst is now in nixpkgs
https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/applications/audio/psst/default.nix

2022-07-28 04:16 UTC, closed without merging