python: mpldatacursor: init at 0.7.1
NixOS/nixpkgs pull request #135534
Opened 2021-08-24 09:30 UTC by bzizou

###### Motivation for this change

Prerequisite for HP2P (https://github.com/NixOS/nixpkgs/pull/96998)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-08-24 10:01 UTC, fabaff reviewed
Could you please update the commit messages? Should looks like `python3Packages: mpldatacursor: init at 0.7.1`. Thanks

2021-08-24 10:01 UTC, fabaff commented on pkgs/development/python-modules/mpldatacursor/default.nix
> +}
```suggestion
  };
}
```

2021-08-24 13:09 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 135534` at 7e6f2ba1 run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built successfully:</summary>
  <ul>
    <li>python38Packages.mpldatacursor</li>
    <li>python39Packages.mpldatacursor</li>
  </ul>
</details>

2021-08-24 21:11 UTC, SuperSandro2000 requested changes
Also please name the commit ``python39Packages.mpldatacursor: init at 0.7.1``.

2021-08-24 21:11 UTC, SuperSandro2000 commented on pkgs/development/python-modules/mpldatacursor/default.nix
> +  propagatedBuildInputs = [ matplotlib  ];
```suggestion
  propagatedBuildInputs = [ matplotlib ];
```

2021-08-24 21:11 UTC, SuperSandro2000 commented on pkgs/development/python-modules/mpldatacursor/default.nix
> +  doCheck = false;
Can we fetch from github instead?

2021-08-25 06:59 UTC, bzizou commented on pkgs/development/python-modules/mpldatacursor/default.nix
> +  doCheck = false;
Sure!

2021-08-25 11:34 UTC, markuskowa commented
@GrahamcOfBorg build python3Packages.mpldatacursor

2021-08-25 11:35 UTC, markuskowa approved these changes

2021-08-25 11:37 UTC, merged