WIP: bluespec: unstable-2021.03.29 -> 2021.07
NixOS/nixpkgs pull request #135711
Opened 2021-08-25 22:36 UTC by jcumming

###### Motivation for this change

There is finally a bsc release! Let's use it. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

###### Things todo

This isn't quite done yet -- the [testsuite](https://github.com/B-Lang-org/bsc-testsuite) got merged into this repo, and I haven't quite got it working yet -- `longTests` is still WIP, but the smoke tests still work.

2021-08-27 20:07 UTC, thoughtpolice requested changes
> After about 15 attempts to build `bsc` and run the whole testsuite in the same derivation, maybe I should split them?
> 
> That way I could debug all of the hard coded paths, etc in the testsuite without having to rebuilt the compiler every time.
> 
> Thoughts?

Sorry, but I'm afraid I'm against this. Mostly because almost nobody else I can think of does such a thing, and it's largely just a kludge to get `nix-build` to work more efficiently for the few people maintaining it. I don't advise doing such a thing just to make personal iterations faster. Such a scheme also makes it harder for third parties to understand why the expression is structured that way; occasionally people do come along and look at things, after all.

My suggestion for this is process is:

- Leave the testsuite off for now. We can fix it later in a further PR. It wasn't enabled previously and I don't consider this a regression for that reason.
- We should be fixing these things upstream in the bsc repo, and making our needs as clear as possible. Ideally, we should actually aim to fix as many of the "tidy ups" in `default.nix` here upstream, as well, outside of the testsuite. I had some changes to do some of this, but needless to say they've fallen by the wayside (for one, the whole build system could use a rewrite, basically...)
- Then, one of two things happens:
  - Any changes that need to go into `bsc` can be packported here, if we want the current release to pass CI. I suspect this will probably just mean applying a lot of `.patch` files that modify `./testsuite` and not much else.
  - Or, we can just wait until the next Bluespec release which will be in January (so version `2022.01`.) This will pick up those changes naturally. It also gives us a concrete window to aim for all changes to be upstreamed by.

I also think some of the problem can be fixed by investigating parallelism in the test suite harness too, but I haven't done so. Really, the whole bluespec build system needs a bunch of work. I think directing that effort upstream is better in the long run.

If you're happy just specifying `doCheck = false;` as I suggested above, I'm happy to approve this otherwise, I think. I'd at least rather not accept the `longTests` parts if they don't work; the smoke is just a single trivial compilation, so honestly I'd say just leaving that out is fine too.

2021-08-27 23:28 UTC, SuperSandro2000 commented on pkgs/development/compilers/bluespec/default.nix
> +, incrtcl, tcl, tk, verilog, xorg, yices, zlib, ghc, asciidoctor, tex # docs
Please revert this. It will get formatted like it was before in the future anyway.

2021-08-27 23:28 UTC, SuperSandro2000 commented on pkgs/development/compilers/bluespec/default.nix
> +    ghc.withPackages (g: (with g; [ old-time regex-compat syb split ]));
```suggestion
  ghcWithPackages = ghc.withPackages (g: (with g; [ old-time regex-compat syb split ]));
```

2021-08-29 20:45 UTC, thoughtpolice approved these changes

2021-08-31 21:53 UTC, merged