os-specific/linux: replace name with pname&version
NixOS/nixpkgs pull request #135921
Opened 2021-08-27 14:48 UTC by Stunkymonkey

###### Motivation for this change

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-08-27 16:21 UTC, Ericson2314 approved these changes

2021-08-27 19:36 UTC, r-burns approved these changes
Yeah I think the check error message is misleading. `cachix: CppStdException "Exception: path '/nix/store/rl1bm7f6z36yvjrmwny1wz4lrnq1nm9i-python3.9-watchdog-2.1.4' is not valid; type: nix::InvalidPath"` happened because python3.pkgs.watchdog failed to build as a dependency of the manual. (Might have run out of resources or timed out)

However python3.pkgs.watchdog builds locally for me, so LGTM.

2021-08-27 23:56 UTC, SuperSandro2000 commented on pkgs/os-specific/linux/fswebcam/default.nix
> +    url = "https://www.sanslogic.co.uk/fswebcam/files/${lib.replaceStrings ["."] [""] version}.tar.gz";
```suggestion
    url = "https://www.sanslogic.co.uk/fswebcam/files/fswebcam-${lib.replaceStrings ["."] [""] version}.tar.gz";
```

2021-08-28 05:09 UTC, Ericson2314 requested changes
Ah good catch @SuperSandro2000

2021-08-28 20:44 UTC, Mic92 commented on pkgs/os-specific/linux/afuse/default.nix
>    src = fetchurl {
Look like this predates `fetchFromGithHub`

2021-08-29 02:49 UTC, bobby285271 commented on pkgs/os-specific/linux/afuse/default.nix
> +    sha256 = "06i855h8a1w2jfly2gfy7vwhb2fp74yxbf3r69s28lki2kzwjar6";
Nit: indent.

```suggestion
    owner = "pcarrier";
    repo = "afuse";
    rev = "v${version}";
    sha256 = "06i855h8a1w2jfly2gfy7vwhb2fp74yxbf3r69s28lki2kzwjar6";
```

2021-09-05 01:43 UTC, merged