ssh-key-confirmer: init at 0.1
NixOS/nixpkgs pull request #139228
Opened 2021-09-23 20:49 UTC by oxzi

###### Motivation for this change
This PR adds the quite new [ssh-key-confirm](https://github.com/benjojo/ssh-key-confirmer) tool in its first release to the nixpkgs.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-09-23 21:16 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 139228` at 1eedbcaa run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built successfully:</summary>
  <ul>
    <li>ssh-key-confirmer</li>
  </ul>
</details>
<details>
  <summary>1 suggestion:</summary>
  <ul>
    <li>warning: <a href="https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/name-and-version.md">name-and-version</a>

Did you mean to pass `pname` instead of `name` to `mkDerivation`?

Near pkgs/tools/networking/ssh-key-confirmer/default.nix:4:3:
```
  |
4 |   name = "ssh-key-confirmer";
  |   ^
```

Near pkgs/tools/networking/ssh-key-confirmer/default.nix:5:3:
```
  |
5 |   version = "0.1";
  |   ^
```
</li>
  </ul>
</details>

2021-09-27 17:07 UTC, figsoda requested changes

2021-09-27 17:07 UTC, figsoda commented on pkgs/tools/networking/ssh-key-confirmer/default.nix
> +  name = "ssh-key-confirmer";
```suggestion
  pname = "ssh-key-confirmer";
```

2021-09-27 17:07 UTC, figsoda commented on pkgs/tools/networking/ssh-key-confirmer/default.nix
> +  vendorSha256 = "0v9yw6v8fj6dqgbkks4pnmvxx9b7jqdy7bn7ywddk396sbsxjiqa";
upstream makefile includes these ldflags
https://github.com/benjojo/ssh-key-confirmer/blob/v0.1/Makefile#L11
```suggestion
  vendorSha256 = "0v9yw6v8fj6dqgbkks4pnmvxx9b7jqdy7bn7ywddk396sbsxjiqa";
  
  ldflags = [ "-s" "-w" ];
```

2021-10-02 12:09 UTC, oxzi commented
@figsoda: Thanks for your review. I have updated the PR accordingly.

2021-10-02 14:26 UTC, figsoda commented
Result of `nixpkgs-review pr 139228` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ssh-key-confirmer</li>
  </ul>
</details>

2021-10-02 14:26 UTC, figsoda approved these changes

2021-10-02 14:26 UTC, merged

2021-10-02 16:26 UTC, oxzi commented
Thanks for merging (: