pythonPackages.jaeger-client: init 4.6.1
NixOS/nixpkgs pull request #139316
Opened 2021-09-24 11:40 UTC by superherointj

* pythonPackages.zc_buildout: 2.13.4 -> 3.0.0b2
* pythonPackages.martian: init 1.4
* pythonPackages.z3c_testsetup: init 0.8.4
* pythonPackages.zest_releaser: init 6.22.1
* pythonPackages.threadloop: init 1.0.2
* pythonPackages.jaeger-client: init 4.6.1

This is a dependency of `sygnal` (#137092) and some other applications (popped up as inner dependency at OpenStack too).
I'm breaking into a different PR for sanity.

## Tests

* Tests here are specifically tricky because:
  * `zc.recipe.egg` is *broken*. (Python seems to have moved on from that.)
  * `z3c_testsetup` tests have ~+65 missing deps.
  * On `threadloop`, I think tests can be fixed, but I don't know how.
  * On `zest_releaser`, maybe tests can be fixed too but I don't know how.

2021-09-24 14:06 UTC, r-rmcgibbo commented
Result of `nixpkgs-review pr 139316` at fb1b834f run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages built successfully:</summary>
  <ul>
    <li>python38Packages.jaeger-client</li>
    <li>python38Packages.martian</li>
    <li>python38Packages.threadloop</li>
    <li>python38Packages.z3c-checkversions</li>
    <li>python38Packages.z3c_testsetup</li>
    <li>python38Packages.zc_buildout</li>
    <li>python38Packages.zest_releaser</li>
    <li>python39Packages.jaeger-client</li>
    <li>python39Packages.martian</li>
    <li>python39Packages.threadloop</li>
    <li>python39Packages.z3c-checkversions</li>
    <li>python39Packages.z3c_testsetup</li>
    <li>python39Packages.zc_buildout</li>
    <li>python39Packages.zest_releaser</li>
  </ul>
</details>

2021-10-05 20:36 UTC, superherointj commented on pkgs/top-level/python-packages.nix
> +  zest_releaser = callPackage ../development/python-modules/zest_releaser { };
Will fix.

2021-10-05 20:41 UTC, SuperSandro2000 requested changes

2021-10-05 20:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/zest_releaser/default.nix
> +    downloadPage = "https://pypi.org/project/zest.releaser/";
You don't need to set it, it is optional and mostly used for proprietary packages but if you already set it we can keep it.

2021-10-05 20:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/z3c_testsetup/default.nix
> +  doCheck = false; # Missing too many dependencies: zope.app.testing +25; zope.app.zcmlfiles +40.
over 40 packages!?

2021-10-05 20:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/threadloop/default.nix
> +  # ];
Please don't comment those. Either remove them or keep them uncommented.

2021-10-05 20:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/threadloop/default.nix
> +  #   coveralls
```suggestion
```

2021-10-05 20:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/threadloop/default.nix
> +  #   pytest-cov
```suggestion
```

2021-10-05 20:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/zest_releaser/default.nix
> +, test_setup
How is this packaged used in zest_releaser? I can't find any usage in the repo but I did not dig very deep. I think our best option would be to try to remove it if it is easily possible as it seems to be very dead.

2021-10-05 20:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/jaeger-client/default.nix
> +  #   codecov
```suggestion
```

2021-10-05 20:41 UTC, SuperSandro2000 commented on pkgs/development/python-modules/jaeger-client/default.nix
> +  #   coverage
```suggestion
```

2021-10-05 22:04 UTC, superherointj commented on pkgs/development/python-modules/z3c_testsetup/default.nix
> +  doCheck = false; # Missing too many dependencies: zope.app.testing +25; zope.app.zcmlfiles +40.
Yes, each dependency has other dependencies...
https://github.com/zopefoundation/zope.app.zcmlfiles/blob/master/setup.py

2021-10-21 23:22 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/613

2021-10-22 16:48 UTC, merged