got: init at 0.60
NixOS/nixpkgs pull request #139453
Opened 2021-09-25 16:39 UTC by wahjava

###### Motivation for this change

`got` ([Game of Trees](https://gameoftrees.org/)) is a VCS which uses git repositories as its backing store.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-09-28 22:59 UTC, qbit commented
Nice! I was able to clone / checkout some repos without issue! LGTM

2021-09-29 14:19 UTC, alyssais commented
Two small notes, but otherwise looks good to me:

- We usually use `installCheckPhase` rather than `checkPhase` for smoke tests like you have here, and custom phases should run the pre and post hooks, e.g. `runHook preInstallCheck`.

- [Arguments should be listed in the order they are used, with the exception of `lib,` which always goes first.](https://nixos.org/manual/nixpkgs/unstable/#sec-syntax)

2021-09-30 15:22 UTC, SuperSandro2000 commented on pkgs/applications/version-management/got/default.nix
> +      "A version control system which prioritizes ease of use and simplicity over flexibility";
```suggestion
    description = "A version control system which prioritizes ease of use and simplicity over flexibility";
```

2021-10-01 02:21 UTC, figsoda requested changes

2021-10-01 02:21 UTC, figsoda commented on pkgs/applications/version-management/got/default.nix
> +  '';
```suggestion
  installCheckPhase = ''
    runHook preInstallCheck
    test "$($out/bin/got --version)" = '${pname} "${version}"'
    runHook postInstallCheck
  '';
```

2021-10-01 02:21 UTC, figsoda commented on pkgs/applications/version-management/got/default.nix
> +      on the same repository.'';
```suggestion
      on the same repository.
    '';
```

2021-10-04 01:36 UTC, figsoda commented
Result of `nixpkgs-review pr 139453` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>got</li>
  </ul>
</details>

2021-10-04 01:36 UTC, figsoda approved these changes

2021-10-04 01:37 UTC, merged