mopidy-jellyfin: Init at 1.0.0
NixOS/nixpkgs pull request #140131
Opened 2021-10-01 08:27 UTC by pstn

###### Motivation for this change
We have excellent jellyfin and mopidy support. Leaving out the adapter between the two would be a shame.

ping @eyJhb  since you were interested.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-01 11:06 UTC, pstn commented
Tested working locally in my own setup with jellyfin and mopidy.

2021-11-08 15:45 UTC, rski requested changes

2021-11-08 15:45 UTC, rski commented on pkgs/applications/audio/mopidy/jellyfin.nix
> +  version = "1.0.0";
the latest release on pypi is 1.0.2

2021-11-16 16:19 UTC, rski commented
looks fine by me but I don't have perms to submit it. As a final nit, i'd suggest changing the PR subject from 1.0.0 to reflect the new version

2021-11-18 23:00 UTC, fabaff commented on pkgs/applications/audio/mopidy/jellyfin.nix
> +  pname = "Mopidy-Jellyfin";
At some point in time those packages should be renamed to follow the new guidelines.

2021-12-27 17:23 UTC, merged