hushboard: init at 2021-03-17
NixOS/nixpkgs pull request #140682
Opened 2021-10-05 21:21 UTC by sersorrel

###### Motivation for this change
[Hushboard](https://kryogenix.org/code/hushboard/) mutes your microphone automatically while typing.

This is the first derivation I'm contributing to Nixpkgs, it could undoubtedly be better.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-05 21:33 UTC, SuperSandro2000 commented on pkgs/applications/audio/hushboard/default.nix
> +  version = "2021-03-17";
```suggestion
  version = "unstable-2021-03-17";
```

2021-10-05 21:33 UTC, SuperSandro2000 commented on pkgs/applications/audio/hushboard/default.nix
> +    sed -i "s@ctypes.util.find_library('libpulse') or 'libpulse.so.0'@'${libpulseaudio}/lib/libpulse.so.0'@" hushboard/_pulsectl.py
Please use substituteInPlace

2021-10-06 03:54 UTC, AndersonTorres requested changes

2021-10-06 03:54 UTC, AndersonTorres commented on pkgs/applications/audio/hushboard/default.nix
> +  version = "unstable-2021-03-17";
```suggestion
  version = "0.pre+unstable=2021-03-17";
```

(Shameless plug to future https://github.com/NixOS/rfcs/pull/107; feel free to accept or reject it)

2021-10-06 03:57 UTC, AndersonTorres requested changes

2021-10-06 03:57 UTC, AndersonTorres commented on pkgs/applications/audio/hushboard/default.nix
> +, wrapGAppsHook
Put these lists in alphabetical order, except for the three first lines. It helps reading the code.

Do the same on the other lists as well.

2021-10-06 03:57 UTC, legendofmiracles commented on pkgs/applications/audio/hushboard/default.nix
> +    cp snap/gui/hushboard.desktop $out/share/applications
```suggestion
    copyDesktopIcons snap/gui/hushboard.desktop
```
Add `copyDesktopIcons` as a input and to nativeBuildInputs

2021-10-11 19:42 UTC, merged