giada: 0.16.4 -> 0.18.2
NixOS/nixpkgs pull request #140628
Opened 2021-10-05 15:27 UTC by 0x4A6F

###### Motivation for this change
Upgrade to [0.18.2](https://github.com/monocasual/giada/releases/tag/v0.18.2) incorporating these [changes](https://github.com/monocasual/giada/compare/v0.16.4...v0.18.2).

- [ ] Waiting for a release with https://github.com/monocasual/giada/pull/509

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-05 17:12 UTC, SuperSandro2000 requested changes

2021-10-05 17:12 UTC, SuperSandro2000 commented on pkgs/applications/audio/giada/default.nix
> +    # Using https://github.com/monocasual/giada/pull/509 till a new release is done.
Please clarify that we are using that commit on master, not the fork itself.

2021-10-05 17:12 UTC, SuperSandro2000 commented on pkgs/applications/audio/giada/default.nix
> +  version = "0.18.2";
This needs to be in the unstable format.

2021-10-05 17:12 UTC, SuperSandro2000 commented on pkgs/applications/audio/giada/default.nix
> +    fetchSubmodules = true;
Is nlohmann/json devendored?

2021-10-05 17:12 UTC, SuperSandro2000 commented on pkgs/applications/audio/giada/default.nix
> +        src/{core/kernelMidi,gui/elems/config/tabMidi,utils/ver}.cpp
Can we use substituteInPlace instead? Also please use / or | as a delimiter for sed.

2021-10-05 19:24 UTC, 0x4A6F commented
Thanks, updated.

2021-10-21 10:32 UTC, tobiasBora commented
Seems to solve https://github.com/NixOS/nixpkgs/issues/142178 thanks! To get input, you just need to enable it in the configuration file. I just have a strange "larsen" effect when I try to register audio, but I guess I first need to learn how to use the software ^^

2021-10-21 17:36 UTC, merged