python3Packages.slugid: init 2.0.0
NixOS/nixpkgs pull request #141409
Opened 2021-10-12 20:34 UTC by milahu

###### Motivation for this change
cos why not ...

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-12 20:52 UTC, SuperSandro2000 requested changes

2021-10-12 23:28 UTC, mweinelt requested changes

2021-10-14 06:31 UTC, milahu commented
> cos why not ...

cos the [slugid](https://github.com/taskcluster/slugid.py/blob/main/slugid/slugid.py) "library" has only 20 lines of code, which can be reduced to 16 lines

(the current `default.nix` has 28 lines)

```py
# Licensed under the Mozilla Public Licence 2.0.
# https://www.mozilla.org/en-US/MPL/2.0
import sys, uuid, base64

def _ascii(s):
    if sys.version_info.major != 2 and isinstance(s, bytes):
        return s.decode('ascii')
    return s

def encode(uuid_):
    return _ascii(base64.urlsafe_b64encode(uuid_.bytes)[:-2])

def decode(slug):
    return uuid.UUID(bytes=base64.urlsafe_b64decode(_ascii(slug) + '=='))

def v4():
    return encode(uuid.uuid4())

def nice():
    s = v4()
    if s[0] == '-' or s[0] == '_':
      s[0] = 'f'
    return s
```

2021-11-15 12:06 UTC, SuperSandro2000 commented on pkgs/development/python-modules/slugid/default.nix
> +  doCheck = false; # has no tests
```suggestion
  doCheck = false; # has no tests

  pythonImportsCheck = [
    "slugid"
  ];

```

2021-11-15 13:30 UTC, merged