alpnpass: init at 0.1
NixOS/nixpkgs pull request #141468
Opened 2021-10-13 08:07 UTC by raboof

###### Motivation for this change

A useful companion to e.g. Wireshark. Leaving the payloads untouched while still keeping the ALPN intact makes it fill a niche not yet covered by other tools like mitmproxy and sslsplit.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-13 08:44 UTC, SuperSandro2000 requested changes

2021-10-13 08:48 UTC, fabaff reviewed
Opinionated change: Separate the different "block" with a blank line to improve the readability for humans.

2022-04-18 12:38 UTC, raboof commented
still relevant

2022-04-21 14:06 UTC, SuperSandro2000 requested changes

2022-04-21 14:20 UTC, raboof commented
Result of `nixpkgs-review pr 141468` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>alpnpass</li>
  </ul>
</details>

2022-04-21 14:31 UTC, raboof commented
Thanks, I hadn't noticed upstream has since tagged a release, updated the PR!

2022-04-21 23:50 UTC, merged