awslimitchecker: init at 12.0.0
NixOS/nixpkgs pull request #141518
Opened 2021-10-13 14:59 UTC by zakame

###### Motivation for this change

https://github.com/jantman/awslimitchecker is script and python package to check your AWS service limits and usage.

~This PR as stands currently will not build, since it still has some missing dependencies, each to follow in their own PRs in a little while:~

- [x] versionfinder
- [x] onetimepass
- [x] timecop

There is a small patch to `awslimitchecker.version` to use only the hard-coded version information, somewhat making the `versionfinder` dependency redundant, as otherwise we'd need a run-time dependency on `pytest` for `versionfinder` to behave correctly - I suspect there's a bug somewhere in between.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-14 04:51 UTC, zakame commented
Please label for Hacktoberfest once accepted :pray:

2021-10-16 10:53 UTC, zakame commented
Result of `nixpkgs-review pr 141518` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>awslimitchecker</li>
  </ul>
</details>

2021-10-16 17:39 UTC, SuperSandro2000 requested changes

2021-11-16 12:55 UTC, merged

2021-11-29 15:37 UTC, zakame commented
Thanks @SuperSandro2000 ! 🎉