[staging] mesa: include /run/opengl-driver/lib in gbm path
NixOS/nixpkgs pull request #141768
Opened 2021-10-15 13:36 UTC by jonringer

###### Motivation for this change
Follow up to: https://github.com/NixOS/nixpkgs/pull/141685#issuecomment-944078514

This should allow for non-mesa dri gdm backends to be discovered.
E.g. nvidia's new gdm backend

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-15 20:39 UTC, primeos requested changes
I've tested the Mesa update and pushed it to staging-next (our staging workflow is too slow for Mesa): 5957e9f06466f898cfc1ea4b1611a7b559e103a9

The Mesa commit after the force-push contains unrelated changes: https://github.com/NixOS/nixpkgs/pull/141768/commits/6c846ce7dfe27e29eb7add00dd15b68ef4e74822
You can simply drop the update commit now ;)

2021-10-15 22:02 UTC, primeos requested changes
Sorry for the 2nd iteration, I'm currently a bit low on time :o

2021-11-06 17:17 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/nvidia-users-testers-requested-sway-on-nvidia-steam-on-wayland/15264/30

2021-11-10 08:01 UTC, colemickens commented
closing in favor of #145319. Please take a look at it.

2021-11-10 08:01 UTC, closed without merging