systemd: add musl patches
NixOS/nixpkgs pull request #141980
Opened 2021-10-17 11:28 UTC by yu-re-ka

###### Motivation for this change

Fixes build of pkgsMusl.systemdMinimal and pkgsMusl.systemd.

This might be controversial, but it would be a big step towards building full NixOS systems against musl.

These patches are applied conditionally on purpose: They are not checked to be properly guarded. They should not block future systemd upgrades.

Also see the original RFC discussion around musl systemd: https://github.com/NixOS/rfcs/blob/master/rfcs/0023-musl-libc.md#systemd

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-17 11:46 UTC, andir commented
Who will be in charge of rebasing these? I certainly won't be doing that. A regular Systemd upgrade is already very involved for us.

2021-10-17 12:57 UTC, alyssais commented
This is excellent work, thank you.  It'll be especially helpful for users relying on static binaries with systemd/udev dependencies.  I'll be more than happy to help maintain it going forward, and as you've noted, it won't create any extra work for systemd/glibc maintainers.  It shouldn't be too much work for Nixpkgs musl users, either, since the patchset is maintained by another project.

A couple of questions:

* Is Yocto the right upstream to use for these?  I thought it was OpenEmbedded: https://cgit.openembedded.org/openembedded-core/tree/meta/recipes-core/systemd/systemd
* What's musl.diff?  Why are the changes in there not taken care of by the OpenEmbedded/Yocto musl patchset?

2021-10-17 15:23 UTC, alyssais requested changes

2021-10-17 19:50 UTC, alyssais requested changes

2021-10-18 12:49 UTC, alyssais approved these changes

2021-10-19 13:39 UTC, illdefined approved these changes

2021-10-20 09:38 UTC, merged

2021-11-29 22:54 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/libudev-as-static-library/16272/7