nixos/apache-kafka: add mirrormaker options
NixOS/nixpkgs pull request #142078
Opened 2021-10-18 11:25 UTC by itihas

###### Motivation for this change

Kafka clusters can be mirrored (wholly or in part) using a tool provided in the package. Options to run it as a systemd service, and configure which topics are mirrored, have been created.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-20 15:01 UTC, illustris requested changes
Couldn't check if the mirrormaker service can actually mirror data yet, but these changes are needed for it to build successfully.

2021-11-04 07:03 UTC, itihas commented on nixos/modules/services/misc/apache-kafka/mirrormaker.nix
> +        streams = mkOption { type = int; description = "number of consumer threads"; default = 1; };
did so

2021-11-04 07:08 UTC, itihas commented
> do you mind including a trivial test? even something as simple as launching an instance, and showing a port was bound is quite beneficial from a review perspective

done; I added to the existing nixos/tests/kafka.nix. The service now mirrors a topic to a second kafka cluster, where the message must show up.

2021-11-08 06:26 UTC, itihas commented
UM. sorry.

2022-02-08 09:07 UTC, closed without merging