python3Packages.certbot-dns-google: init at 1.20.0
NixOS/nixpkgs pull request #142574
Opened 2021-10-22 14:23 UTC by jpetrucciani

###### Motivation for this change

I would like to be able to use the GCP DNS plugin for Certbot to provision new LetsEncrypt certificates!

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [X] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-29 15:48 UTC, SuperSandro2000 requested changes

2021-10-29 18:33 UTC, jpetrucciani commented on pkgs/development/python-modules/certbot-dns-google/default.nix
> +  sourceRoot = "source/${pname}";
I had just followed what other plugins appeared to do. I've swapped it for all plugins now.

2021-10-29 18:34 UTC, jpetrucciani commented on pkgs/development/python-modules/certbot-dns-google/default.nix
> +    certbot
I believe this is needed as the library exists within the codebase of certbot - this is also done within the other plugins

2021-10-29 18:36 UTC, jpetrucciani commented
@SuperSandro2000 addressed most of your comments, and applied some of that to the other certbot plugins in nixpkgs to keep it consistent. Also rebased off of master - however, now it seems to be broken on Darwin, at least when I try locally. I'm currently building it on a linux amd64 env

2021-10-29 18:42 UTC, jpetrucciani commented
Works fine on Linux amd64! Do we normally wait for a fix upstream to something like BS4 before merging something like this?

2021-10-29 18:51 UTC, jonringer reviewed
I would separate these changes into two commits, as there's really 2 "logical" changes being done here

To comply with [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes) please have the commit message name be of the format
```
<pkg-name>: <subject-line>
```
for more examples, please look at https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes

in your case, the commit message should be:
```
python3Packages.certbot-dns-google: init at 1.20.0
python3Packages.certbot-dns-*: lint
```

2021-10-29 18:55 UTC, jpetrucciani commented
@jonringer Thanks for the review! I can separate the commits here (also I think both links in your comment may be broken - they 404 for me at the moment)

2021-10-30 18:39 UTC, jonringer commented
> @jonringer Thanks for the review! I can separate the commits here (also I think both links in your comment may be broken - they 404 for me at the moment)

oh yea, it was moved. thanks

2021-10-30 19:56 UTC, jonringer approved these changes
LGTM

Result of nixpkgs-review pr 142574 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)<details>  <summary>9 packages built:</summary>  <ul>    <li>certbot-full</li>    <li>python38Packages.certbot-dns-cloudflare</li>    <li>python38Packages.certbot-dns-google</li>    <li>python38Packages.certbot-dns-rfc2136</li>    <li>python38Packages.certbot-dns-route53</li>    <li>python39Packages.certbot-dns-cloudflare</li>    <li>python39Packages.certbot-dns-google</li>    <li>python39Packages.certbot-dns-rfc2136</li>    <li>python39Packages.certbot-dns-route53</li>  </ul></details>

2021-10-30 19:56 UTC, merged