qgis: 3.16.10 → 3.16.12
NixOS/nixpkgs pull request #142685
Opened 2021-10-23 19:15 UTC by imincik

###### Motivation for this change

Motivation for this change is to update QGIS to the latest LTS (Long Term Support) version.

###### Things done

* This PR is updating QGIS LTS (Long Term Support) from version 3.16.10 to the latest 3.16.12
* This PR also drops [fc1ac8bef8dcc3194857ecd32519aca4867b4fa1 patch](https://github.com/qgis/QGIS/commit/fc1ac8bef8dcc3194857ecd32519aca4867b4fa1.patch) which is now included in 3.16.12 release. `fetchpatch` code snipped was left in code, commented out as an example in case another patches will be needed in the future. 

I successfully tested built app (`nix-build -A qgis`) on my NixOS 21.05 system with QGIS project test datasets

```
nixpkgs/code git:(qgis-3.16.12) ./result/bin/qgis
```
![screen-imincik-2021-10-23-21_13_20](https://user-images.githubusercontent.com/476346/138568684-1473ab40-e196-4649-8bae-436096f8b768.png)

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-10-23 19:57 UTC, dotlambda requested changes
Please remove `patches` and `fetchpatch`.

2021-11-11 14:20 UTC, sikmir commented
3.16.13 is out.

2021-11-14 04:48 UTC, dotlambda requested changes
`fetchpatch` should be removed from arguments

2021-11-14 17:32 UTC, lsix commented
I have created #145969 which updates qgis to 3.16.13 instead. I guess it should replace this PR.

2021-11-14 19:55 UTC, imincik commented
Thanks @lsix . I am closing this PR in favor of #145969 .

2021-11-14 19:55 UTC, closed without merging