percona: add some tools and new versions
NixOS/nixpkgs pull request #144578
Opened 2021-11-04 04:51 UTC by mkg20001

###### Motivation for this change

Add some tools and new versions of percona SQL server

// cc @dpausp 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/#sec-conf-file))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-11-11 14:09 UTC, SuperSandro2000 commented on pkgs/servers/sql/percona/5.6.x.nix
> +# Note: zlib is not required; MySQL can use an internal zlib.
Does this mean we can remove it from buildInputs?

2021-11-11 14:11 UTC, SuperSandro2000 requested changes
Can we use a common nix file instead of copying?

2021-11-11 14:11 UTC, SuperSandro2000 commented on pkgs/servers/sql/percona/5.6.x.nix
>    prePatch = ''
```suggestion
  postPatch = ''
```

2021-11-11 14:11 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  percona-server80 = callPackage ../servers/sql/percona/8.0.x.nix { };
```suggestion
  percona-server56 = callPackage ../servers/sql/percona/5.6.nix { };
  percona-server57 = callPackage ../servers/sql/percona/5.7.nix { };
  percona-server80 = callPackage ../servers/sql/percona/8.0.nix { };
```

2021-11-11 14:11 UTC, SuperSandro2000 commented on pkgs/tools/admin/innotop/default.nix
> +    patchShebangs .
Which files do need patching or which directory of files?

2021-11-11 14:11 UTC, SuperSandro2000 commented on pkgs/tools/admin/innotop/default.nix
> +    maintainers = with maintainers; [ ];
Please add yourself to maintainers.

2021-11-11 14:11 UTC, SuperSandro2000 commented on pkgs/servers/sql/percona/8.0.nix
> +    maintainers = with maintainers; [ ];
Please add yourself to maintainers.

2021-11-11 14:11 UTC, SuperSandro2000 commented on pkgs/servers/sql/percona/8.0.nix
> +  prePatch = ''
```suggestion
  postPatch = ''
```

2021-11-11 14:11 UTC, SuperSandro2000 commented on pkgs/servers/sql/percona/5.7.nix
> +  prePatch = ''
```suggestion
  postPatch = ''
```

2022-05-15 03:21 UTC, closed without merging

2022-07-07 00:47 UTC, ajs124 commented
Why was this closed?