kubecolor: init at 0.0.20
NixOS/nixpkgs pull request #146742
Opened 2021-11-20 10:44 UTC by ivankovnatsky

###### Motivation for this change

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-11-20 13:15 UTC, legendofmiracles requested changes

2021-11-20 13:15 UTC, legendofmiracles commented on pkgs/applications/networking/cluster/kubecolor/default.nix
> +    description = "colorizes kubectl output";
```suggestion
    description = "Colorizes kubectl output";
```

2021-11-20 13:15 UTC, legendofmiracles commented on pkgs/applications/networking/cluster/kubecolor/default.nix
> +  version = "v0.0.20";
```suggestion
  version = "0.0.20";
```

2021-11-20 13:15 UTC, legendofmiracles commented on pkgs/applications/networking/cluster/kubecolor/default.nix
> +    rev = version;
```suggestion
    rev = "v${version}";
```

2021-11-20 14:26 UTC, ivankovnatsky commented
Let me squash it, please.

2021-11-20 16:52 UTC, legendofmiracles commented
Result of `nixpkgs-review pr 146742` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kubecolor</li>
  </ul>
</details>

Doesn't print any output when running with any args, but it builds

2021-11-20 16:52 UTC, legendofmiracles approved these changes

2021-12-20 18:46 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/665

2021-12-20 18:52 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/425

2021-12-21 01:36 UTC, merged