citra: add build options
NixOS/nixpkgs pull request #147190
Opened 2021-11-23 21:36 UTC by SuperSamus

###### Motivation for this change
Why not?

###### Things done

- I'm not sure if all of these options should be true by default. Should I respect Citra's CMakeLists.txt defaults or the more stuff is true the better?
- That assert maybe is overkill, if one simply has both options true the only effect is that FDK won't be enabled.
- I changed one option name. It's technically a breaking change, but I doubt that anyone overrode that option.
- `-DCITRA_USE_BUNDLED_FFMPEG=OFF` has been removed because it's already off if you are not building on Windows.
- `alsa-lib` was doing nothing here.
- Is `libusb` being devendored if it's just being put in buildInputs?

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-11-25 01:33 UTC, IvarWithoutBones requested changes
Just a few comments 😊

2021-11-25 01:33 UTC, IvarWithoutBones commented on pkgs/misc/emulators/citra/default.nix
> -    "-DCITRA_USE_BUNDLED_FFMPEG=OFF"
Why was this line removed?

2021-11-25 01:33 UTC, IvarWithoutBones commented on pkgs/misc/emulators/citra/default.nix
>      sed -n 's,^ *path = \(.*\),\1,p' .gitmodules | while read path; do
This does the same thing as the `substituteInPlace` above, but if I recall correctly it's broken. Let's remove it.

2021-11-25 11:34 UTC, SuperSamus commented
Done.
What about the remaining questions? (The overkill assert, whether `libusb` is devendored, and the breaking change)

2021-11-25 20:29 UTC, IvarWithoutBones commented
Apologies about answering the questions a bit later than code review, I got busy the other day.

> I'm not sure if all of these options should be true by default. Should I respect Citra's CMakeLists.txt defaults or the more stuff is true the better?

I'd say the more stuff the better. Closure size isn't massively effected, so having CI build this with support for as much stuff as possible makes sense to me.

> I changed one option name. It's technically a breaking change, but I doubt that anyone overrode that option.

I think that should be fine, as you said it probably won't affect anyone.

> That assert maybe is overkill, if one simply has both options true the only effect is that FDK won't be enabled.

IMO can't hurt to have it, it can potentially save a fair bit of debugging.

> I didn't put any option for ENABLE_QT_TRANSLATION.

Why not?

> Is libusb being devendored if it's just being put in buildInputs?

Yes! See https://github.com/citra-emu/citra/blob/324e88d6e08ab8bc95671e6ba8011fc8812ac2c9/CMakeLists.txt#L205.

2021-11-25 20:32 UTC, IvarWithoutBones approved these changes
LGTM! I'm really happy seeing citra get some love. thanks for the work!

2021-11-25 21:17 UTC, SuperSamus commented
I didn't put `ENABLE_QT_TRANSLATION` because I didn't know what dependency it needed.
I should have just taken a look at Yuzu.

2021-11-25 21:37 UTC, SuperSamus commented
I found out that if I build without Qt, Citra won't find the GPU drivers:
```
libGL error: MESA-LOADER: failed to open radeonsi: /nix/store/kgzhnlza09sw2kzzvmp3jp0bypsglqkp-libdrm-2.4.108/lib/libdrm_nouveau.so.2: undefined symbol: drmCloseBufferHandle (search paths /run/opengl-driver/lib/dri, suffix _dri)
libGL error: failed to load driver: radeonsi
libGL error: MESA-LOADER: failed to open swrast: /nix/store/kgzhnlza09sw2kzzvmp3jp0bypsglqkp-libdrm-2.4.108/lib/libdrm_nouveau.so.2: undefined symbol: drmCloseBufferHandle (search paths /run/opengl-driver/lib/dri, suffix _dri)
libGL error: failed to load driver: swrast
X Error of failed request:  BadValue (integer parameter out of range for operation)
  Major opcode of failed request:  149 (GLX)
  Minor opcode of failed request:  3 (X_GLXCreateContext)
  Value in failed request:  0x0
  Serial number of failed request:  100
  Current serial number in output stream:  101
```

I should have tested for this...
Why is it looking for `radeonsi` and not `amdgpu` though?

2021-12-02 18:54 UTC, SuperSamus commented
I rebased, and the issue is gone.
No idea why.

2021-12-27 17:29 UTC, abbradar approved these changes

2021-12-27 17:29 UTC, merged