systemd: pid1 crash fix + 249.7 update
NixOS/nixpkgs pull request #147354
Opened 2021-11-25 11:31 UTC by martinetd

###### Motivation for this change

Fixes #147103 (pid1 crash)

While backporting the patch I noticed we weren't up to date, so also updated along the way.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-11-25 11:35 UTC, SuperSandro2000 reviewed
Does rebasing the patches actually do anything? patches can be applied if the hunks have offsets.

2021-11-25 11:40 UTC, martinetd commented
> Does rebasing the patches actually do anything? patches can be applied if the hunks have offsets.

Other than removing two patches it didn't seem to do anything, no; this was mostly done to make sure it applies (and some apply method fail on fuzz offset so I wasn't sure about this part)
Happy to remove the rebase noise

2021-11-25 11:44 UTC, martinetd commented
I've removed the rebase altogether, it'll probably need further updating when systemd unfreezes after release while this patch will always stay valid (at least until/if it's also backported upstream)

2021-11-25 13:05 UTC, arianvp commented
> I've removed the rebase altogether, it'll probably need further updating when systemd unfreezes after release while this patch will always stay valid (at least until/if it's also backported upstream)

I do not think the freeze applies to minor  / bugfix bumps.

2021-11-25 13:07 UTC, flokli requested changes
Like in https://github.com/NixOS/nixpkgs/pull/146573#issuecomment-975771662, we shouldn't ship these patches downstream, but poke upstream to release it in systemd-stable.

2021-11-25 13:23 UTC, martinetd commented
> Like in #146573 (comment), we shouldn't ship these patches downstream, but poke upstream to release it in systemd-stable.

I see. There were other such patches so I didn't think too much about it, I've asked upstream about it in the systemd PR

2021-11-25 21:30 UTC, flokli commented
> > Like in #146573 (comment), we shouldn't ship these patches downstream, but poke upstream to release it in systemd-stable.
> 
> I see. There were other such patches so I didn't think too much about it, I've asked upstream about it in the systemd PR

For curious ones: That's https://github.com/systemd/systemd/pull/21498#issuecomment-979211583.

2021-12-12 14:24 UTC, Ma27 commented
> Does rebasing the patches actually do anything? patches can be applied if the hunks have offsets.

For the future, I disagree: keeping patches up-to-date reduces the risk of them being unappliable in the future (if the differences around the change become too large).

@flokli I see this is in systemd-stable, but not yet in a release. Do you think it's sufficient to wait for another stable v249 or should we merge this?

(@martinetd I *think* this should go to staging btw).

2021-12-13 11:49 UTC, andir commented
> > Does rebasing the patches actually do anything? patches can be applied if the hunks have offsets.
> 
> For the future, I disagree: keeping patches up-to-date reduces the risk of them being unappliable in the future (if the differences around the change become too large).

Adding what I wrote on Matrix some time ago:
We should always (at least on major versions) rebase these patches to avoid running into issues with applying them on the next version.

The issue with patch files vs. a git repository is that the patch files have a limited set of context around each change. If that context isn't suffient anymore the patches fail to apply. My workflow for new systemd versions is typically:
 * checkout the old systemd version in a Git repostiry
 * git am all the patches
 * interactive rebase to new git tag
 * `git format-patch` and replace the files in the repo.
 * 
This has been going smooth so far.

2021-12-14 15:22 UTC, flokli commented
> @flokli I see this is in systemd-stable, but not yet in a release. Do you think it's sufficient to wait for another stable v249 or should we merge this?

Upstream wanted to wait for some other patches, but I haven't seen anything more getting cherry-picked. I poked them for the tag in https://github.com/systemd/systemd/pull/21498#issuecomment-993652492.

2022-02-02 23:00 UTC, closed without merging