modules/nix-daemon: Amend daemon(CPU|IO)Sched(Policy|Class) description
NixOS/nixpkgs pull request #147497
Opened 2021-11-26 12:57 UTC by illdefined

###### Motivation for this change

Suggest appropriate values for various types of systems and add some
formatting.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [21.11 Release Notes (or backporting 21.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2111-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-11-26 21:46 UTC, samueldr requested changes
Otherwise looks good!

Thanks for the quick turnaround, and the good write-up!

2021-11-26 21:46 UTC, samueldr commented on nixos/modules/services/misc/nix-daemon.nix
> +          systems that experience only intermittend phases of high I/O load,
```suggestion
          systems that experience only intermittent phases of high I/O load,
```

2021-11-26 21:46 UTC, samueldr commented on nixos/modules/services/misc/nix-daemon.nix
> +          systems that experience only intermittend phases of high CPU load,
```suggestion
          systems that experience only intermittent phases of high CPU load,
```

2021-11-27 12:20 UTC, illdefined commented
Thanks for the corrections.

2021-12-10 10:30 UTC, merged