ocamlPackages.jsonrpc: 1.8.3 → 1.9.1
NixOS/nixpkgs pull request #149397
Opened 2021-12-07 16:36 UTC by vbgl

###### Motivation for this change

Support for OCaml 4.13.

cc maintainers @symphorien @marsam

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-12-07 19:07 UTC, symphorien commented
did you try with an ocaml 4.12 project ?
I get `foo.cmi seems to be compiled with OCaml 4.12. But this instance of Merlin handles OCaml 4.13`

2021-12-07 19:10 UTC, symphorien commented
according to opam metadata, we should use:
1.4.1 for ocaml 4.06 to 4.11
1.9.0 for ocaml 4.12
1.9.1 for ocaml 4.13

2021-12-07 19:11 UTC, symphorien requested changes
see above

2021-12-07 21:04 UTC, vbgl commented
Thanks for testing. I’ve thus amended the changes to use 1.9.0 with OCaml 4.12 and 1.9.1 with OCaml 4.13, as suggested.

2021-12-09 14:27 UTC, symphorien approved these changes
Thanks

2021-12-09 14:27 UTC, merged

2021-12-09 14:34 UTC, vbgl commented
Does this deserve to be backported to 21.11?

2021-12-09 18:34 UTC, symphorien commented
good idea. bumping 1.8.3 to 1.9.0 for ocamlPackage_4_12 is a breaking change, so this part must be left out. I opened a PR at https://github.com/NixOS/nixpkgs/pull/149896