your-editor: 1206 -> 1303
NixOS/nixpkgs pull request #149675
Opened 2021-12-08 17:15 UTC by uniquepointer

###### Motivation for this change
Major version update of yed.

###### Things done
We got MacOS version working, started tagging as promised, changed repo from user to the organization, but aside from that not a whole lot on the nix side of things, a lot on the yed side of things though.
If you want to read yed specific patch notes follow [this link.](https://github.com/your-editor/yed/blob/1303/CHANGELOG.md)

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-12-08 18:07 UTC, figsoda requested changes
changelog could be added to meta too

2021-12-08 18:07 UTC, figsoda commented on pkgs/applications/editors/your-editor/default.nix
> +    rev = "1b044e5704fcf8de142ae1d5a6eb45728f0d91a2";
releases seems to be tagged now
```suggestion
    rev = version;
```

2021-12-08 18:07 UTC, figsoda commented on pkgs/applications/editors/your-editor/default.nix
> +
```suggestion
```

2021-12-08 18:07 UTC, figsoda commented on pkgs/applications/editors/your-editor/default.nix
> +{ lib, gccStdenv, fetchFromGitHub }:
if this is required, maybe it would be better to override it inside all-packages.nix

2021-12-08 18:32 UTC, uniquepointer commented
Cleaned up everything and squashed accordingly :}

2021-12-08 19:18 UTC, figsoda commented on pkgs/applications/editors/your-editor/default.nix
> +    changelog = "https://github.com/your-editor/yed/blob/1303/CHANGELOG.md";
```suggestion
    changelog = "https://github.com/your-editor/yed/blob/${version}/CHANGELOG.md";
```

2021-12-08 19:19 UTC, figsoda commented
Also can you amend your commit message to `your-editor: 1206 -> 1303`?

2021-12-08 21:56 UTC, uniquepointer commented
done!

2021-12-09 01:55 UTC, figsoda approved these changes

2021-12-09 01:55 UTC, figsoda commented
Result of `nixpkgs-review pr 149675` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>your-editor</li>
  </ul>
</details>

2021-12-09 01:55 UTC, merged

2021-12-09 04:38 UTC, uniquepointer commented
thank you!