jitsi-meet: Mitigate CVE-2021-44228
NixOS/nixpkgs pull request #150021
Opened 2021-12-10 09:42 UTC by yayayayaka

###### Motivation for this change
This commit mitigates a remote code execution vulnerability in the log4j
library.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-12-10 09:46 UTC, yu-re-ka commented
More information on the vulnerability: https://www.lunasec.io/docs/blog/log4j-zero-day/

2021-12-10 09:46 UTC, xfix approved these changes

2021-12-10 09:47 UTC, yu-re-ka commented
Strictly the commit message(s) should be `nixos/jitsi-videobridge: ...`, `nixos/jicofo: ...` and so on, because this changes the module not the package

2021-12-10 09:54 UTC, yayayayaka commented
Alright.

2021-12-10 10:00 UTC, yu-re-ka commented
I'm not sure if jibri and jicofo actually use Log4j, but better safe than sorry

2021-12-10 10:00 UTC, yu-re-ka approved these changes

2021-12-10 10:06 UTC, xfix commented
Actually, good point, I don't think jibri and jicofo actually use Log4j, checked that JARs, no trace of Log4j.

2021-12-10 10:08 UTC, xfix commented
jitsi-videobridge2 uses Log4j, Jibri and Jicofo don't. I think it would make sense to restrict the change to jitsi-videobridge2 only.

2021-12-10 10:09 UTC, mmilata approved these changes

2021-12-10 10:10 UTC, xfix requested changes
I think commits other than "nixos/jitsi-videobridge: Mitigate CVE-2021-44228" can be removed, as those programs don't use Log4J, and as such are unaffected by the vulnerability.

2021-12-10 10:16 UTC, merged

2021-12-10 10:16 UTC, yayayayaka commented
Thanks @xfix for your review. I have removed the other commits.

2021-12-10 18:09 UTC, dotlambda commented
Shouldn't this also be backported to 21.05?

2021-12-11 18:43 UTC, ius commented
> Shouldn't this also be backported to 21.05?

According to [upstream](https://community.jitsi.org/t/cve-2021-44228-and-jitsi-components/108844):
> Jitsi-videobridge instances older than 2.1-504 (May 2021) with callstats enabled should be updated to 2.1-504 or newer.

Which doesn't affect any of NixOS' supported channels. Accordingly this mitigation doesn't seem necessary after all.

([Additional info](https://github.com/jitsi/jitsi-videobridge/issues/1773#issuecomment-991312292))