pythonPackages.ete3: init at 3.1.2
NixOS/nixpkgs pull request #150972
Opened 2021-12-16 14:16 UTC by delehef

###### Motivation for this change

The ETE toolkit is a reference python library for manipulation of phylogenetic trees in Newick or Phyloxml.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? **No**
- [x] Tested **package tests are broken; tested with `pythonImportsCheck`**
- [x] Tested compilation of all packages that depend on this change **no packages depend on this change**
- [x] Tested basic functionality of all **library files**
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-01-24 20:27 UTC, IvarWithoutBones requested changes
Also, could you run `nixpkgs-fmt` on this?

2022-01-24 20:27 UTC, IvarWithoutBones commented on pkgs/development/python-modules/ete3/default.nix
> +    license = licenses.gpl3;
`gpl3Only` or `gpl3Plus`?

2022-01-24 20:27 UTC, IvarWithoutBones commented on pkgs/development/python-modules/ete3/default.nix
> +  meta = with lib; {
`meta.maintainers` seems to be missing

2022-01-25 11:56 UTC, delehef commented
Thanks for your comments; I fixed them in the last commits.

2022-01-31 19:55 UTC, IvarWithoutBones requested changes
Just one more nit, suprised `nixpkgs-fmt` didn't catch it.

Also, could you squash your commits, so that you only have two? Something like
```commit
maintainers: add delehef
python3Packages.ete3: init at 3.1.2
```
would be perfect :)

2022-01-31 19:55 UTC, IvarWithoutBones commented on pkgs/development/python-modules/ete3/default.nix
> +  src = fetchPypi {
```suggestion
  version = "3.1.2";
  
  src = fetchPypi {
```

2022-02-01 08:49 UTC, delehef commented
Should be alright now!

2022-02-03 23:46 UTC, IvarWithoutBones commented
When running nixpkgs-review on this, i got a missing module error when trying to execute `bin/ete3`: `ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'`. Nix-code wise though, this looks good to me :relaxed:

2022-02-04 01:01 UTC, delehef commented
Indeed, I was able to reproduce the error. Turns out that `nixpkgs-review rev master` setup two instances of ete3 (`/nix/store/XXX-python3.10-ete3-3.1.2/bin/ete3` & `/nix/store/YYY-python3.9-ete3-3.1.2/bin/ete3`) for Python 3.9 & 3.10, and that the highest one in `$PATH` is the one for Python 3.10.

However, for some reason, when importing numpy in Python 3.10, it calls upon numpy for 3.9, which you can observe by running `import numpy` in `python3.10` in the very same environment. Python 3.9 still imports its own numpy though, and thus does not meet the same problem.

Finally, calling directly ete for Python 3.9 (`/nix/store/YYY-python3.9-ete3-3.1.2/bin/ete3` or `/nix/store/ZZZ/bin/ete3
`) fails with a `cannot import name 'TextFace' from 'ete3'` – which is expected as I didn't enable Qt5 support by default.

I'm not sure if this problem is stemming from my side or from `nixpkgs-review`, as I confess I arrive at the very fringe of my Nix competences.

2022-03-13 19:06 UTC, delehef commented
Bump?

2022-04-09 09:56 UTC, delehef commented
Bump again?

2022-09-06 12:39 UTC, onny commented
Result of `nixpkgs-review pr 150972` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.ete3</li>
    <li>python39Packages.ete3</li>
  </ul>
</details>

2022-09-06 12:39 UTC, merged

2022-09-06 12:39 UTC, onny commented
Thank you!