kubergrunt: init at 0.7.11
NixOS/nixpkgs pull request #151509
Opened 2021-12-21 05:49 UTC by psibi

This is a helper utility which allows to configure EKS clusters etc.

Tested it locally on a NixOS machine:

``` shellsession
❯ kubergrunt help
Usage: kubergrunt [--loglevel] [--help] command [options] [args]

A CLI tool to help setup and manage a Kubernetes cluster.

Commands:

   eks      Helper commands to configure EKS.
   k8s      Helper scripts for managing Kubernetes resources directly.
   tls      Helper commands to manage TLS certificate key pairs as Kubernetes Secrets.
   help, h  Shows a list of commands or help for one command
```

###### Motivation for this change

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-12-26 21:15 UTC, IvarWithoutBones requested changes
I only have a few formatting suggestions for consistency with the rest of nixpkgs, functionality wise this LGTM :+1: 

Result of `nixpkgs-review pr 151509` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kubergrunt</li>
  </ul>
</details>

2021-12-26 21:15 UTC, IvarWithoutBones commented on pkgs/applications/networking/cluster/kubergrunt/default.nix
> +      "Collection of commands to fill in the gaps between Terraform, Helm, and Kubectl";
```suggestion
    description = "Collection of commands to fill in the gaps between Terraform, Helm, and Kubectl";
```

2021-12-26 21:15 UTC, IvarWithoutBones commented on pkgs/applications/networking/cluster/kubergrunt/default.nix
> +buildGoModule rec {
```suggestion
{ buildGoModule, lib, fetchFromGitHub }:

buildGoModule rec {
```

2021-12-27 02:41 UTC, psibi commented
@IvarWithoutBones Thanks for the feedback, addressed. Is there any tool which automatically does the formatting according to what's preferred in nixpkgs ? I used `nixfmt` (https://github.com/serokell/nixfmt) to do the initial formatting.

2021-12-27 12:44 UTC, IvarWithoutBones commented
Yes, There's `nixpkgs-fmt` (https://github.com/nix-community/nixpkgs-fmt) which helps out a lot.

 Also, would you mind squashing the commits? Other than that, this PR looks good to me :)

2021-12-28 02:36 UTC, psibi commented
@IvarWithoutBones Thanks, done.

2021-12-28 13:17 UTC, legendofmiracles approved these changes
Builds and prints help menu
LGTM

2021-12-28 13:19 UTC, merged