home-manager: 2021-03-21 -> 2021-12-25
NixOS/nixpkgs pull request #152243
Opened 2021-12-26 15:45 UTC by JulesdeCube

###### Motivation for this 

bump `home-manager` version to last one.

A pull request already exist but was never merge and is now outdated #139980.

this use home-manager `master` to not depend on nixos version. as suggested by https://github.com/NixOS/nixpkgs/pull/139980#issuecomment-931493774 in the previous merge request.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-12-28 05:54 UTC, davidak requested changes
you missed the `version`

2021-12-28 13:58 UTC, davidak commented
thanks. can you squash the commits?

you can use `git commit --amend` to not create a new commit, but edit the last commit

2021-12-29 18:36 UTC, JulesdeCube commented
It's fix

2021-12-30 02:30 UTC, davidak commented
Result of `nixpkgs-review pr 152243` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>home-manager</li>
  </ul>
</details>

2021-12-30 02:33 UTC, davidak commented
hmm, it seem not to work

```
[nix-shell:~/.cache/nixpkgs-review/pr-152243]$ home-manager
/nix/store/xzl95q6n5cn95ifxmp00qhdxc4k1f6rm-home-manager-2021-12-25/bin/home-manager: line 12: @HOME_MANAGER_LIB@: No such file or directory
```

shouldn't those be replaced by the build?

```
#!/nix/store/iqprjr5k5385bhf1dzj07zwd5p43py1n-bash-5.1-p12/bin/bash

# Prepare to use tools from Nixpkgs.
PATH=@DEP_PATH@${PATH:+:}$PATH

set -euo pipefail

export TEXTDOMAIN=home-manager
export TEXTDOMAINDIR=@OUT@/share/locale

# shellcheck disable=1091
source @HOME_MANAGER_LIB@
...
```

2021-12-31 05:40 UTC, JulesdeCube commented
normally it good now (thanks to guide for my first time).

2021-12-31 07:01 UTC, davidak commented
Result of `nixpkgs-review pr 152243` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>home-manager</li>
  </ul>
</details>

2021-12-31 07:05 UTC, davidak commented
thank you. i still get errors

```
building '/nix/store/vzna59knldckaqkg9a2777m5hjmvhsw7-home-manager-2021-12-25.drv'...
builder for '/nix/store/vzna59knldckaqkg9a2777m5hjmvhsw7-home-manager-2021-12-25.drv' failed with exit code 127; last 10 log lines:
  unpacking source archive /nix/store/lpl4wa13lgzyl6wx12s5q33xwh04viv0-source
  source root is source
  patching sources
  configuring
  no configure script, doing nothing
  installing
  install: creating directory '/nix/store/c5ymkcnjqnn216rkwqc1zxsiyp1jspg3-home-manager-2021-12-25'
  install: creating directory '/nix/store/c5ymkcnjqnn216rkwqc1zxsiyp1jspg3-home-manager-2021-12-25/bin'
  '/nix/store/lpl4wa13lgzyl6wx12s5q33xwh04viv0-source/home-manager/home-manager' -> '/nix/store/c5ymkcnjqnn216rkwqc1zxsiyp1jspg3-home-manager-2021-12-25/bin/home-manager'
  /nix/store/lwcfw5vyjlzrs35k1hanv21j1q2s5c5w-stdenv-linux/setup: line 1375: msgfmt: command not found
cannot build derivation '/nix/store/j7p83k8fqpb11kc9hc4mpjsx6arnlrnz-review-shell.drv': 1 dependencies couldn't be built
error: build of '/nix/store/j7p83k8fqpb11kc9hc4mpjsx6arnlrnz-review-shell.drv' failed

Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/152243

1 package failed to build:
home-manager
```

2021-12-31 11:38 UTC, JulesdeCube commented
it's fix

2021-12-31 19:58 UTC, davidak commented
Result of `nixpkgs-review pr 152243` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>home-manager</li>
  </ul>
</details>

2021-12-31 20:02 UTC, davidak commented
Now it seem to work, great!

```
[nix-shell:~/.cache/nixpkgs-review/pr-152243-2]$ home-manager --version
22.05
```

To make sure it really works i will rebuild my system in a VM, but not today.

2022-01-01 19:02 UTC, davidak approved these changes
Changes look good

Builds, works

Tested in nixpkgs-review shell and built vm from my system to see if changes are applied correctly. system is using bash

2022-01-01 19:02 UTC, merged

2022-01-01 19:31 UTC, JulesdeCube commented
@davidak thank you for your help.
#139980 need to be close (the version is out dated by this pr)