python38Packages.homeassistant: build homeassistant package (proposal)
NixOS/nixpkgs pull request #152331
Opened 2021-12-27 10:45 UTC by graham33

This creates homeassistant as an importable package, to be used outside of the
home-assistant server package (for example in external custom components).

I have something similar in my NUR for building custom components, so I
thought it would be worth trying to upstream it.  I'm not sure if this is the cleanest
way to do it, but I experimented with some alternatives (e.g. using
`toPythonModule`) and this seemed to be the simplest option overall.

###### Motivation for this change

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-12-27 12:43 UTC, mweinelt commented
Can you explain what you need this for? I'm not aware of any components, that need to `import homeassistant`.

2021-12-27 17:00 UTC, graham33 commented
It's for custom integrations which are outside of the main Home Assistant source tree for various reasons, e.g. https://github.com/alandtse/tesla which I have packaged in my NUR and might think about upstreaming. I also develop one myself  https://github.com/graham33/hass-smartbox.

2021-12-27 17:24 UTC, mweinelt commented
I think you are misunderstanding how custom components are integrated.

Home Assistant allows you to drop custom components into a `custom_components` directory below your config directory, it will import these automatically.

2021-12-27 17:48 UTC, graham33 commented
That's right, but if you want to run the tests and use things like https://github.com/MatthewFlamm/pytest-homeassistant-custom-component you need to have it as an importable package outside of the HA installation.

2021-12-27 17:49 UTC, graham33 commented
I have some simple code for installing custom components that might be worth exploring separately.

2021-12-27 18:14 UTC, mweinelt commented
> I have some simple code for installing custom components that might be worth exploring separately.

Ideally it would boil down to something like

```
  services.home-assistant.customComponents = [ pkgs.custom_component_foo` ];
```

And the output would be linked into the appropriate directory.

2021-12-27 19:48 UTC, dotlambda requested changes
We can't expose Home Assistant inside `pythonPackages` because of the overrides. Use `toPythonModule` if you need it anyway.

2021-12-28 10:00 UTC, graham33 commented
Ah, good point I had forgotten about the overrides. It's a shame they have to exist! I'll decline this PR and have another look at this along with the custom integrations.

2021-12-28 10:01 UTC, closed without merging

2021-12-28 10:11 UTC, dotlambda commented
We could expose a package `home-assistant.python.pkgs.homeassistant`.

2021-12-29 08:54 UTC, graham33 commented
@dotlambda that would be great.  I'm currently doing that using `toPythonModule` and adding it in to `packageOverrides` for the home-assistant app derivation.

Not sure what the cleanest way to do this from within the derivation is - it'd be a shame to have to factor out the whole thing into a variable, perhaps there's a good way to get at a `self` from within it?

2022-01-03 21:01 UTC, graham33 commented
> > I have some simple code for installing custom components that might be worth exploring separately.
> 
> Ideally it would boil down to something like
> 
> ```
>   services.home-assistant.customComponents = [ pkgs.custom_component_foo` ];
> ```
> 
> And the output would be linked into the appropriate directory.

@mweinelt I have something like this in my own config, see:
* https://github.com/graham33/nur-packages/blob/master/modules/home-assistant-extras/default.nix#L9-L14
* https://github.com/graham33/nur-packages/blob/master/pkgs/build-support/build-home-assistant-custom-component/default.nix
* https://github.com/graham33/nur-packages/blob/master/pkgs/tesla-custom-component/default.nix

Maybe this could be improved into something that could be upstreamed, I'd be happy to work on it.  LMK what you think.