Disable MEMPROF on aarch64+musl
NixOS/nixpkgs pull request #152323
Opened 2021-12-27 07:08 UTC by angerman

if either of SANITIZER, XRAY or MEMPROF is enabled, we may see
```
[  4%] Building CXX object lib/sanitizer_common/CMakeFiles/RTSanitizerCommonNoHooks.aarch64.dir/sanitizer_linux.cpp.o
/build/source/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp: In function 'bool __sanitizer::Aarch64GetESR(ucontext_t*, __sanitizer::u64*)':
/build/source/compiler-rt/lib/sanitizer_common/sanitizer_linux.cpp:1814:35: error: cannot convert 'long double*' to '__sanitizer::u8*' {aka 'unsigned char*'} in initialization
 1814 |   u8 *aux = ucontext->uc_mcontext.__reserved;
      |             ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~
      |                                   |
      |                                   long double*
```

during the build as we are trying to build sanitizer_common files.

2022-01-04 18:26 UTC, primeos requested changes
The commit message should be prefixed with `llvmPackages_13.compiler-rt: `. If this is also required for `llvmPackages_git.compiler-rt` you should add it there as well - otherwise it will be missing again for `llvmPackages_14`. Other than that the diff looks fine to me. Thanks.

Btw: I'm only adding new LLVM versions for Chromium. For a proper review @Ericson2314 and @sternenseemann should be pinged (AFAIK - IIRC this doesn't work inside a review comment). CI should also ping all LLVM maintainers if the commit message is prefixed correctly.

2022-01-04 18:39 UTC, sternenseemann commented
By chance ran into this today as well, <https://github.com/NixOS/nixpkgs/pull/153463>, just ended up disabling it for musl in general, can you test if that PR fixes the problem for you? I'd prefer not to introduce another conditional.

I also ended up disabling the ORC runtime, but seems like this builds with musl?

2022-01-05 01:42 UTC, angerman commented
@sternenseemann fairly certain #153463 would fix this as well.

2022-01-05 01:42 UTC, closed without merging

2022-01-05 01:42 UTC, angerman commented
@sternenseemann 
> seems like this builds with musl?

It appears so. Yes.