tdesktop: 3.1.11 -> 3.3.0
NixOS/nixpkgs pull request #152702
Opened 2021-12-30 13:41 UTC by MrMebelMan

###### Motivation for this change
Update to a new version

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2021-12-30 13:49 UTC, MrMebelMan commented
![image](https://user-images.githubusercontent.com/15896005/147757655-f106d4be-c53f-41a6-a795-bb6ce0352178.png)
I've encountered this issue while trying to test the new version, but I'm not sure what to do about it 👉👈

2021-12-30 14:35 UTC, Kranzes commented
TDesktop now depends on qt6, which is not available in nixpkgs currently.
See: https://github.com/NixOS/nixpkgs/pull/141883

2021-12-30 14:50 UTC, VergeDX commented
Yes, but we can disabled the Qt6 feature by adding `"-DDESKTOP_APP_QT6=OFF"` to `cmakeFlags`.
I tried to update and meets some issues, I will checkout the update tomorrow : )

2021-12-30 14:52 UTC, VergeDX requested changes
Try to add `"-DDESKTOP_APP_QT6=OFF"` in `cmakeFlags` : )

2021-12-31 02:03 UTC, VergeDX commented
3.4.0 is released, I quickly tried it and seems everything is ok.
Please update to the latest, and skip qt6 requirement while building.

2021-12-31 07:38 UTC, MrMebelMan commented
Updated to 3.4.0. Everything seems to work well, thanks @Kranzes & @VergeDX :heart:

2021-12-31 07:41 UTC, VergeDX approved these changes

2021-12-31 09:11 UTC, VergeDX requested changes

2021-12-31 09:11 UTC, VergeDX commented on pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix
> +  version = "3.4.0";
3.4.1 just release, that was fast xD.

2021-12-31 11:26 UTC, Kranzes commented
Add a TODO comment above where you disabled QT6, something like "Remove once QT6 is available in nixpkgs".

2021-12-31 11:36 UTC, MrMebelMan commented
Jesus

2021-12-31 14:32 UTC, 1000101 commented on pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix
> +    sha256 = "1397rsb1srzzfvbbqafhpf1jpx8iz13vj8y6gyq44gr9zq54iwcm";
```suggestion
    sha256 = "0sgfhicb81a5cn05f9zi7333kwh76qbnija1fyw0cxrrwap9d73m";
```
Sirs, this is `3.4.0`'s hash.

2021-12-31 14:33 UTC, 1000101 commented on pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix
> +    sha256 = "1397rsb1srzzfvbbqafhpf1jpx8iz13vj8y6gyq44gr9zq54iwcm";
```suggestion
    sha256 = "1397rsb1srzzfvbbqafhpf1jpx8iz13vj8y6gyq44gr9zq54iwcm";
```
Sirs, this is 3.4.0's hash.

2021-12-31 14:33 UTC, 1000101 commented on pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix
> +    sha256 = "1397rsb1srzzfvbbqafhpf1jpx8iz13vj8y6gyq44gr9zq54iwcm";
```suggestion
    sha256 = "0sgfhicb81a5cn05f9zi7333kwh76qbnija1fyw0cxrrwap9d73m";
```
Sirs, this is 3.4.0's hash.

2021-12-31 14:35 UTC, MrMebelMan commented on pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix
> +    sha256 = "1397rsb1srzzfvbbqafhpf1jpx8iz13vj8y6gyq44gr9zq54iwcm";
oh no

2021-12-31 15:34 UTC, 1000101 commented
Result of `nixpkgs-review pr 152702` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tdesktop</li>
  </ul>
</details>

2021-12-31 19:20 UTC, MrMebelMan commented
> IT WOKZ
> 
> Result of `nixpkgs-review pr 152702` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 1 package built:

DIKI

2021-12-31 19:26 UTC, MrMebelMan commented
Happy COVID-22, sirs! :tada:

2022-01-01 00:48 UTC, VergeDX commented
3.4.2 plz xD

2022-01-01 08:29 UTC, 1000101 commented
> 3.4.2 plz xD

Now that's some agile development!

3.4.1:
>     Bug fixes and other minor improvements.

3.4.2:
>     Bug fixes and other minor improvements.

3.4.3:
WEN

2022-01-02 12:27 UTC, MrMebelMan commented
WHY ARE YOU DOING THIS TO ME

2022-01-02 12:28 UTC, 1000101 commented
> WHY ARE YOU DOING THIS TO ME

@MrMebelMan commit it before it lays more versions

2022-01-02 12:46 UTC, MrMebelMan commented
![shouldnt](https://user-images.githubusercontent.com/15896005/147876172-4dcbeb9f-d961-4ed3-8ece-66dc6d596207.png)

2022-01-02 14:06 UTC, 1000101 commented
Result of `nixpkgs-review pr 152702` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tdesktop</li>
  </ul>
</details>

2022-01-02 14:08 UTC, VergeDX approved these changes

2022-01-02 14:08 UTC, 1000101 approved these changes

2022-01-02 14:54 UTC, VergeDX commented
The aarch64 build failed with internal complier error (ICE).
Idk what happened, I'll check out this tomorrow : (

2022-01-03 09:50 UTC, VergeDX commented
The default cc of aarch64 is gcc9 (x86_64 on is gcc10), which caused the ICE.
I switch to gcc10Stdenv and compile it in arm64 Drone CI, it seems the error disappeared.

The commit: https://github.com/VergeDX/nixpkgs/commit/687d6cc5da37725834991c268ea2d7523140d401#diff-a45a9e94415ea5231fbac619e3eca6614b75e730f93f5986c163fc9304242517R69
The CI log: https://cloud.drone.io/VergeDX/actions-nix/9/1/2

2022-01-03 13:18 UTC, 1000101 commented
@GrahamcOfBorg build tdesktop

2022-01-03 13:35 UTC, ajs124 commented
> The default cc of aarch64 is gcc9 (x86_64 on is gcc10), which caused the ICE. I switch to gcc10Stdenv and compile it in arm64 Drone CI, it seems the error disappeared.

For reference #108305

2022-01-03 15:13 UTC, MrMebelMan commented
Thanks @VergeDX, u da boss

2022-01-03 19:43 UTC, 1000101 approved these changes

2022-01-03 21:48 UTC, 1000101 commented
Merge it before OH NOES https://github.com/telegramdesktop/tdesktop/releases/tag/v3.4.3

2022-01-04 00:34 UTC, VergeDX requested changes

2022-01-04 00:34 UTC, VergeDX commented on pkgs/applications/networking/instant-messengers/telegram/tdesktop/default.nix
> +
Maybe we can add a comment here:
`Aarch64 default gcc9 will cause ICE. For reference #108305`

2022-01-04 05:11 UTC, MrMebelMan commented
We need to hurry, comerades - 3.4.4 is brewing ![image](https://user-images.githubusercontent.com/15896005/148011671-046aa14b-e1eb-4bdc-a060-d5a5c3465b8d.png)

2022-01-04 06:26 UTC, VergeDX approved these changes

2022-01-04 12:24 UTC, 1000101 commented
Result of `nixpkgs-review pr 152702` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tdesktop</li>
  </ul>
</details>

2022-01-04 12:33 UTC, 1000101 approved these changes

2022-01-04 12:43 UTC, merged