nextflow: init at 21.10.6
NixOS/nixpkgs pull request #152961
Opened 2021-12-31 16:09 UTC by Etjean

###### Motivation for this change
Addition of [nextflow](https://github.com/nextflow-io/nextflow).

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-01-24 20:23 UTC, IvarWithoutBones requested changes

2022-01-24 20:23 UTC, IvarWithoutBones commented on pkgs/development/interpreters/nextflow/default.nix
> +  buildInputs = [jre wget which];
For consistency with the rest of nixpkgs:
```suggestion
  nativeBuildInputs = [ makeWrapper ];
  buildInputs = [ jre wget which ];
```
btw, you can automatically do trivial formatting stuff with `nixpkgs-fmt`.

2022-01-24 20:23 UTC, IvarWithoutBones commented on pkgs/development/interpreters/nextflow/default.nix
> +    mv $src $out/bin/$pname
```suggestion
    install -Dm755 $src $out/bin/nextflow
```
Usage of `pname` here makes it a bit harder to read IMO, with no benefits.

2022-01-24 20:23 UTC, IvarWithoutBones commented on pkgs/development/interpreters/nextflow/default.nix
> +  wrapProgram $out/bin/${pname} --prefix PATH : ${lib.makeBinPath buildInputs}
Indentation seems off:
```suggestion
    wrapProgram $out/bin/nextflow --prefix PATH : ${lib.makeBinPath buildInputs}
```

2022-01-24 20:23 UTC, IvarWithoutBones commented on pkgs/development/interpreters/nextflow/default.nix
> +    longDescription = "Nextflow is a bioinformatics workflow manager that enables the development of portable and reproducible workflows. It supports deploying workflows on a variety of execution pla
```suggestion
    longDescription = ''
      Nextflow is a bioinformatics workflow manager that enables the development of portable and reproducible workflows. 
      It supports deploying workflows on a variety of execution platforms including local, HPC schedulers, AWS Batch, Google Cloud Life Sciences, and Kubernetes. 
      Additionally, it provides support for manage your workflow dependencies through built-in support for Conda, Docker, Singularity, and Modules. 
    '';
```

2022-01-24 20:23 UTC, IvarWithoutBones commented on pkgs/development/interpreters/nextflow/default.nix
> +    maintainers = [maintainers.Etjean];
```suggestion
    maintainers = [ maintainers.Etjean ];
```

2022-01-24 20:23 UTC, IvarWithoutBones commented on pkgs/development/interpreters/nextflow/default.nix
> +  meta = with lib; {
Could you add `meta.mainProgram`?

2022-01-25 09:32 UTC, Etjean commented
Thanks for the review @IvarWithoutBones, I incorporated all suggestions.

2022-01-31 20:12 UTC, IvarWithoutBones requested changes
Just a few more suggestions :)

2022-02-10 20:15 UTC, IvarWithoutBones approved these changes
LGTM, thanks for the work :+1: 

Result of `nixpkgs-review pr 152961` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>nextflow</li>
  </ul>
</details>

Binary also shows usage

2022-02-10 20:15 UTC, merged