id3tool: init at 1.2a
NixOS/nixpkgs pull request #157290
Opened 2022-01-29 15:09 UTC by danielb2

###### Motivation for this change

Add derivation for https://github.com/NixOS/nixpkgs/issues/157008

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-01-29 20:00 UTC, jansol commented
Consider adding yourself in `meta.maintainers` if you're planning to make sure the derivation stays intact.

2022-01-29 20:07 UTC, jansol commented
Consider adding yourself in `meta.maintainers` if you're planning to make sure the derivation stays intact.

2022-01-29 21:33 UTC, danielb2 commented
> Consider adding yourself in `meta.maintainers` if you're planning to make sure the derivation stays intact.

what does this mean? In what way would it become damaged if I'm not in the maintainers?

2022-01-29 21:43 UTC, jansol commented
It could for example stop building as a result of a compiler update, or the source URL could get retired.

2022-01-29 21:48 UTC, danielb2 commented
I'm OK to be off the list. Thanks.

2022-09-05 12:36 UTC, onny commented
@ofborg build id3tool

2023-06-02 21:44 UTC, drupol requested changes
Hi !

I'm a new committer and I'm doing some kind of cleanup.

Would you be kind to make the necessary changes so we can move forward?

2023-06-02 21:44 UTC, drupol commented on pkgs/applications/audio/id3tool/default.nix
> +    sha256 = "eQjWbFqr4qU66AGegjT0IxSF2Avksv5yydBAE8/xyuw=";
```suggestion
    hash = "sha256-eQjWbFqr4qU66AGegjT0IxSF2Avksv5yydBAE8/xyuw=";
```

2023-06-02 21:44 UTC, drupol commented on pkgs/applications/audio/id3tool/default.nix
> +{ lib, stdenv, fetchurl }:
```suggestion
{ lib, stdenvNoCC, fetchurl }:
```

2023-06-02 21:44 UTC, drupol commented on pkgs/applications/audio/id3tool/default.nix
> +stdenv.mkDerivation {
```suggestion
stdenvNoCC.mkDerivation {
```

2023-06-02 21:44 UTC, drupol requested changes

2023-06-02 21:44 UTC, drupol commented on pkgs/applications/audio/id3tool/default.nix
> +    maintainers = with maintainers; [  ];
Consider adding yourself as a maintainer.

2023-06-02 22:17 UTC, danielb2 commented
I'm closing this because I keep hearing about adding myself as a maintainer, it's taken over a year, and it's not worth hearing about this anymore. Clearly no one else cares, or it would have been merged.

2023-06-02 22:17 UTC, closed without merging