ioztat: init at 1.1.0
NixOS/nixpkgs pull request #157344
Opened 2022-01-30 03:11 UTC by numinit

###### Motivation for this change

Relatively new package for monitoring ZFS dataset performance.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-02-05 20:58 UTC, 0x4A6F requested changes
Thanks for this porting effort.

2022-02-05 20:58 UTC, 0x4A6F commented on pkgs/tools/filesystems/ioztat/default.nix
> +, python3 }:
Small formatting nitpick: keep `}:` on a separate line.
You can try out `nixpkgs-fmt`.

2022-02-09 21:47 UTC, 0x4A6F requested changes

2022-02-12 04:45 UTC, numinit commented on pkgs/tools/filesystems/ioztat/default.nix
> +stdenv.mkDerivation rec {
ioztat is not set up like a normal Python application. There's no setup.py or requirements, it's just a script with a python shebang.

2022-02-12 13:23 UTC, 0x4A6F requested changes

2022-02-12 13:23 UTC, 0x4A6F commented on pkgs/tools/filesystems/ioztat/default.nix
> +    platforms = [ platforms.linux platforms.freebsd ];
`meta.platforms` should be removed or correctly set with `platforms = with lib.platforms; linux ++ freebsd;`:
```
nix-build -A pkgs.ioztat
error: Package ‘ioztat-1.1.0’ in /nixpkgs/pkgs/tools/filesystems/ioztat/default.nix:38 is not supported on ‘x86_64-linux’, refusing to evaluate.

       a) To temporarily allow packages that are unsupported for this system, you can use an environment variable
          for a single invocation of the nix tools.

            $ export NIXPKGS_ALLOW_UNSUPPORTED_SYSTEM=1

       b) For `nixos-rebuild` you can set
         { nixpkgs.config.allowUnsupportedSystem = true; }
       in configuration.nix to override this.

       c) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
         { allowUnsupportedSystem = true; }
       to ~/.config/nixpkgs/config.nix.
(use '--show-trace' to show detailed location information)
```

2022-02-21 01:42 UTC, 0x4A6F approved these changes
```
1 package built:
ioztat
```

2022-02-21 01:43 UTC, merged