Add jack support
NixOS/nixpkgs pull request #157782
Opened 2022-02-02 02:03 UTC by Aidan-Chelig

qemu has had jack support since version 5.1

###### Motivation for this change

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-02-02 06:22 UTC, pennae commented
welcome! i see you've opened two PRs for this, both for 21.11. that's not how we usually do things for new features, those are supposed to go to unstable (ie the master branch) first and then be backported to a stable release once they've been merged there.

2022-02-02 10:15 UTC, 06kellyjac requested changes

2022-02-02 10:15 UTC, 06kellyjac commented on pkgs/applications/virtualization/qemu/default.nix
> +    + lib.optionalString pulseSupport "jack,";
```suggestion
    + lib.optionalString jackSupport "jack,";
```

2022-02-02 10:26 UTC, zowoq commented
Looks like a dupe of https://github.com/NixOS/nixpkgs/pull/153188?

2022-02-03 09:58 UTC, lheckemann commented
Closing in favour of #153188 which implements this correctly

2022-02-03 09:58 UTC, closed without merging