polypane: init at 8.0.0
NixOS/nixpkgs pull request #158159
Opened 2022-02-04 21:13 UTC by zoedsoupe

###### Motivation for this change
Polypane is a stand-alone browser that target web developers providing a rich support for responsive and acessible web developing tools.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-02-07 00:44 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/polypane/default.nix
> +    ln -s $out/bin/${name} $out/bin/${pname}
```suggestion
    ln -s $out/bin/${pname}-${version} $out/bin/${pname}
```

2022-02-07 00:44 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/polypane/default.nix
> +  name = "${pname}-${version}";
```suggestion
```

2022-02-07 00:44 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/polypane/default.nix
> +{ lib, fetchurl, appimageTools, pkgs }:
```suggestion
{ lib, fetchurl, appimageTools }:
```

2022-02-07 13:10 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/polypane/default.nix
> +    The stand-alone browser for ambitious developers that want to build responsive, accessible and performant websites in a fraction of the time it takes with other browsers.
```suggestion
      The stand-alone browser for ambitious developers that want to build responsive, accessible and performant websites in a fraction of the time it takes with other browsers.
```

2022-02-07 13:11 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/polypane/default.nix
> +    maintainers = with maintainers; [ zoedsoupe ];
```suggestion
    maintainers = with maintainers; [ zoedsoupe ];
```

2022-02-07 13:12 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> -  matdsoupe = {
You also need to update https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/earthly/default.nix#L40

2022-02-07 13:12 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/polypane/default.nix
> +    license = with licenses.unfree;
```suggestion
    license = licenses.unfree;
```´
this should fix the syntax errror.

2022-02-07 15:56 UTC, SuperSandro2000 commented
@ofborg eval

2022-03-08 12:00 UTC, SuperSandro2000 commented
@zoedsoupe can you please do your commits like it is described in the contributing document? If so ofborg will also trigger the build.

@ofborg build polypane

2022-03-09 02:55 UTC, zoedsoupe commented
> @zoedsoupe can you please do your commits like it is described in the contributing document? If so ofborg will also trigger the build.
> 
> @ofborg build polypane

Of course!!

2022-03-09 16:49 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> -  matdsoupe = {
Please put this into a separate commit with the message ``maintainers: update NAME`` and sort it alphabetically.

2022-03-09 16:50 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/polypane/default.nix
> +in appimageTools.wrapType2 {
I also wouldn't mind if that would be rec but not required...

2022-03-09 16:50 UTC, SuperSandro2000 commented on pkgs/applications/networking/browsers/polypane/default.nix
> +      --replace 'Exec=AppRun' 'Exec=${pname}'
..and we wouldn't substitute pname wherever possible.

2022-10-03 19:09 UTC, SuperSandro2000 requested changes

2022-10-03 19:09 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +      longkeyid = "rsa4096/0x1E1E889CDBD6A315";
```suggestion
```

2022-10-03 19:51 UTC, merged