sketchybar: init at 2.4.3
NixOS/nixpkgs pull request #158754
Opened 2022-02-09 07:36 UTC by azuwis

###### Motivation for this change

Add new package `sketchybar`, a highly customizable macOS status bar replacement.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-02-10 03:05 UTC, reckenrode commented
Result of `nixpkgs-review pr 158754` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>sketchybar</li>
  </ul>
</details>

2022-02-10 03:06 UTC, reckenrode commented
Result of `nixpkgs-review pr 158754` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

2022-02-11 09:37 UTC, azuwis commented
> I have no clue how nix works, but I think this misses the code signature step I use in the brew formula: https://github.com/FelixKratz/homebrew-formulae/blob/82f2990b8828723644a5c6732165c92e1e3d26c2/sketchybar.rb#L28. Else not all permissions can be given to the process appropriately.

Nix handle code signing automatically.

2022-02-11 14:21 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/724

2022-02-16 16:21 UTC, SuperSandro2000 requested changes

2022-02-16 16:21 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/sketchybar/default.nix
> +    inherit (src.meta) homepage;
```suggestion
    homepage = "https://github.com/FelixKratz/SketchyBar";
```
I can click on this link,

2022-02-16 16:21 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/sketchybar/default.nix
> +  '';
```suggestion
  makeFlags = [
    target
  ];
```
We do not want to overwrite the default flags.

2022-02-16 16:21 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/sketchybar/default.nix
> +  }.${stdenv.hostPlatform.system};
```suggestion
  }.${stdenv.hostPlatform.system} or throw "Unsupported system: ${system}";
```

otherwise eval fails on linux.

2022-02-17 01:44 UTC, azuwis commented
All suggestions applied.

2022-02-17 12:41 UTC, merged