Make fetchFromGitHub overridable
NixOS/nixpkgs pull request #158968
Opened 2022-02-10 13:43 UTC by piegamesde

###### Motivation for this change

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-02-11 12:02 UTC, mweinelt commented
That would be very neat to have. I'm not aware of the downsides so I'm requesting some people to review this instead of me.

2022-02-11 13:18 UTC, roberth commented
This was also discussed before https://github.com/NixOS/nixpkgs/pull/158018 was updated to the change that it is now. The performance cost can be estimated as around 0.5%. I think that's not a lot, but it is something we won't get back.
It's based on the eval performance report from the commit statuses, ignoring time (noisy), looking at gc numbers, which are a reasonable proxy for time.

2022-12-22 17:38 UTC, RaitoBezarius commented
Are we still interested into having this?

2022-12-22 20:17 UTC, piegamesde commented
Yes but I won't be the one fighting for it

2022-12-22 21:32 UTC, RaitoBezarius approved these changes
I believe that having this around, even if it does cost +0,5 % in heap size, will save more time for users.

2022-12-22 21:35 UTC, Mindavi commented
What would be a usecase for this?

2022-12-22 21:36 UTC, RaitoBezarius commented
> What would be a usecase for this?

Doing: `pkgs.x.overrideAttrs (old: { src = old.src.override { sha256 = "xxx"; } })` rather than rebuilding the whole fetchFromX signature.

2022-12-22 22:21 UTC, mweinelt commented
Overriding the rev/hash, but keeping the owner/repo.

2022-12-23 12:02 UTC, ncfavier requested changes
I don't have very strong opinions on this, although I feel like the intended use case overlaps with the reason https://github.com/NixOS/nixpkgs/pull/119942 was introduced.

---------------

I do have comments on implementation though: the `makeOverridable` calls should be added to `pkgs/build-support/foo` rather than `all-packages.nix`. This has two advantages:
- we get to keep `fetchFoo.override` (which is different from the added `(fetchFoo { ... }).override`)
- putting less logic in `all-packages.nix` is always good

For example, `fetchgithub/default.nix` would look like this:
```nix
{ lib, fetchgit, fetchzip }:

lib.makeOverridable (
/* rest of the file */
)
```

2022-12-23 19:38 UTC, infinisil commented
I'd also like to see some tests for this, to make sure both `.override` and `.overrideAttrs` work for both the fetcher itself and the result.

2022-12-23 20:24 UTC, ncfavier commented
(The fetcher itself wouldn't have an `overrideAttrs` since it's not a derivation.)

2022-12-24 14:51 UTC, Atemu commented
I've just bumped into something where I could use this.

If you yourself have a derivation where you want to make the source overridable, a workaround is to use `src = (lib.makeOverridable fetchgit) { ... };`.

2022-12-27 11:52 UTC, piegamesde commented
The interactions with #119942 are certainly interesting, although I don't think this PR is completely obsoleted by it. Take the common use case where I want to override version + source hash.

- Formerly: You need to override the version field and the complete source attribute `.overrideAttrs (old: rec { version = "42"; src = fetchFromGitHub { inherit version; owner = …; repo = …; hash = …; }; })`
- With #119942: Overriding the version will also override it in the source fetcher, but this does not help you because you still have to update the hash. So same as above
- With this PR: you can override only the source hash and version, but still need to do the version twice `.overrideAttrs (old: rec { version = "42"; src = old.src.override { inherit version; hash = …; }; })`
- With both: the following should work `.overrideAttrs (old: { version = "42"; src = old.src.override { hash = …; }; })`

2023-04-22 20:40 UTC, piegamesde commented
I sure hope "ofborg-eval" does a full evaluation, because I have no way of testing all those fetchers.

@ncfavier I updated the design according to your review

2023-05-07 19:59 UTC, merged

2023-05-16 16:09 UTC, piegamesde commented
@pschyska I unfortunately don't know much about nix-prefetch and how it works, and I have trouble associating these error messages with an explanation how this patch may have caused them.

I think there already existed a couple of overridable fetchers before this patch, although I have forgotten which ones. You could try what happens with these, as a control.

2023-05-16 19:39 UTC, ncfavier commented
nix-prefetch seems to rely on `lib.functionArgs`, and this PR makes `lib.functionArgs pkgs.fetchFromGitHub` empty. Not sure why yet.

2023-05-16 20:05 UTC, mweinelt commented
> I think this breaks [msteen's nix-prefetch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix-prefetch/default.nix?rgh-link-date=2023-05-16T15%3A59%3A18Z).

Aside: Last updated in 2021. Time to migrate to nurl.

2023-05-16 20:26 UTC, pschyska-2 commented
> > I think this breaks [msteen's nix-prefetch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix-prefetch/default.nix?rgh-link-date=2023-05-16T15%3A59%3A18Z).
> 
> Aside: Last updated in 2021. Time to migrate to nurl.

I would happily migrate, if I could.

2023-05-16 20:28 UTC, pschyska commented
> > I think this breaks [msteen's nix-prefetch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix-prefetch/default.nix?rgh-link-date=2023-05-16T15%3A59%3A18Z).
> 
> Aside: Last updated in 2021. Time to migrate to nurl.

I would happily migrate, if I could.

2023-05-16 20:46 UTC, mweinelt commented
> > > I think this breaks [msteen's nix-prefetch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix-prefetch/default.nix?rgh-link-date=2023-05-16T20%3A28%3A44Z).
> > 
> > 
> > Aside: Last updated in 2021. Time to migrate to nurl.
> 
> I would happily migrate, if I could.

What prevents you? https://github.com/nix-community/nurl#supported-fetchers

2023-05-17 03:41 UTC, fbewivpjsbsby commented
nurl not support `fetchurl` now.

> > > > I think this breaks [msteen's nix-prefetch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix-prefetch/default.nix?rgh-link-date=2023-05-16T20%3A28%3A44Z).
> > > 
> > > 
> > > Aside: Last updated in 2021. Time to migrate to nurl.
> > 
> > 
> > I would happily migrate, if I could.
> 
> What prevents you? https://github.com/nix-community/nurl#supported-fetchers

2023-05-17 03:41 UTC, fbewivpjsbsby commented
> > > > I think this breaks [msteen's nix-prefetch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix-prefetch/default.nix?rgh-link-date=2023-05-16T20%3A28%3A44Z).
> > > 
> > > 
> > > Aside: Last updated in 2021. Time to migrate to nurl.
> > 
> > 
> > I would happily migrate, if I could.
> 
> What prevents you? https://github.com/nix-community/nurl#supported-fetchers

nurl not support fetchurl now.

2023-05-17 08:55 UTC, pschyska commented
> > > > I think this breaks [msteen's nix-prefetch](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/package-management/nix-prefetch/default.nix?rgh-link-date=2023-05-16T20%3A28%3A44Z).
> > > 
> > > 
> > > Aside: Last updated in 2021. Time to migrate to nurl.
> > 
> > 
> > I would happily migrate, if I could.
> 
> What prevents you? https://github.com/nix-community/nurl#supported-fetchers

As I wrote, I'm a nvfetcher user, not a direct nix-prefetch user. It's up to @berberman to make a decision to migrate. I think they are investigating it though.

2023-05-17 09:02 UTC, ncfavier commented
Looks like there's prior art https://github.com/NixOS/nixpkgs/pull/134272

2023-08-28 22:07 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/overrideattrs-not-taking-effect-how-to-override-fetchfromgithub-and-more/32298/1