soundux: init at 0.2.7
NixOS/nixpkgs pull request #160181
Opened 2022-02-15 15:42 UTC by pasqui23

###### Motivation for this change

###### Things done

Builds fails with 
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking sources
unpacking source archive /nix/store/hsa0gdqr6qzfzvnwbnmhbzg6dy844ygf-source
source root is source
@nix { "action": "setPhase", "phase": "patchPhase" }
patching sources
@nix { "action": "setPhase", "phase": "configurePhase" }
configuring
fixing cmake files...
cmake flags: -DCMAKE_FIND_USE_SYSTEM_PACKAGE_REGISTRY=OFF -DCMAKE_FIND_USE_PACKAGE_REGISTRY=OFF -DCMAKE_EXPORT_NO_PACKAGE_REGISTRY=ON -DCMAKE_BUILD_TYPE=Release -DCMAKE_SKIP_BUILD_RPATH=ON -DBUILD_TESTING=OFF -DCMAKE_INSTALL_LOCALEDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/share/locale -DCMAKE_INSTALL_LIBEXECDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/libexec -DCMAKE_INSTALL_LIBDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/lib -DCMAKE_INSTALL_DOCDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/share/doc/soundux -DCMAKE_INSTALL_INFODIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/share/info -DCMAKE_INSTALL_MANDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/share/man -DCMAKE_INSTALL_OLDINCLUDEDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/include -DCMAKE_INSTALL_INCLUDEDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/include -DCMAKE_INSTALL_SBINDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/sbin -DCMAKE_INSTALL_BINDIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/bin -DCMAKE_INSTALL_NAME_DIR=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7/lib -DCMAKE_POLICY_DEFAULT_CMP0025=NEW -DCMAKE_OSX_SYSROOT= -DCMAKE_FIND_FRAMEWORK=LAST -DCMAKE_STRIP=/nix/store/pja9g36cy32z3d51942jqk91a6l2d5nv-gcc-wrapper-10.3.0/bin/strip -DCMAKE_RANLIB=/nix/store/sga0l55gm9nlwglk79lmihwb2bpv597j-binutils-2.35.2/bin/ranlib -DCMAKE_AR=/nix/store/sga0l55gm9nlwglk79lmihwb2bpv597j-binutils-2.35.2/bin/ar -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_COMPILER=g++ -DCMAKE_INSTALL_PREFIX=/nix/store/kv11q43l4rgvn4p1kyqkp0fd0k2d2v9l-soundux-0.2.7 -DCMAKE_BUILD_TYPE=Release 
-- The C compiler identification is GNU 10.3.0
-- The CXX compiler identification is GNU 10.3.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /nix/store/pja9g36cy32z3d51942jqk91a6l2d5nv-gcc-wrapper-10.3.0/bin/gcc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /nix/store/pja9g36cy32z3d51942jqk91a6l2d5nv-gcc-wrapper-10.3.0/bin/g++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD
-- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found PipeWire: /nix/store/zjskbzxb7ab9mkb7dnrhxfjq3nyn757a-pipewire-0.3.45-lib/lib/libpipewire-0.3.so (found version "0.3.45") 
-- Found X11: /nix/store/y33ngsql2d5mg57j231gk8c90347xy3b-xorgproto-2021.5/include   
-- Looking for XOpenDisplay in /nix/store/6pdb0rz2w2hsfsy66kwrbz67jd424wv7-libX11-1.7.2/lib/libX11.so;/nix/store/a3yw11i2iskvr1zx2za4mwrj9sawq7hz-libXext-1.3.4/lib/libXext.so
-- Looking for XOpenDisplay in /nix/store/6pdb0rz2w2hsfsy66kwrbz67jd424wv7-libX11-1.7.2/lib/libX11.so;/nix/store/a3yw11i2iskvr1zx2za4mwrj9sawq7hz-libXext-1.3.4/lib/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found PkgConfig: /nix/store/r255i42fsinsmjpywxzj8rsav51vx4b5-pkg-config-wrapper-0.29.2/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libwnck-3.0'
--   Found libwnck-3.0, version 40.0
Package libpcre was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre', required by 'glib-2.0', not found
Package libpcre was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre', required by 'glib-2.0', not found
Package libpcre was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre', required by 'glib-2.0', not found
Package libpcre was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpcre.pc'
to the PKG_CONFIG_PATH environment variable
Package 'libpcre', required by 'glib-2.0', not found
[31mCMake Error at CMakeLists.txt:72 (add_subdirectory):
  The source directory

    /build/source/src/ui/impl/webview/lib/webviewpp

  does not contain a CMakeLists.txt file.

[0m
[31mCMake Error at CMakeLists.txt:73 (add_subdirectory):
  The source directory

    /build/source/lib/nativefiledialog-extended

  does not contain a CMakeLists.txt file.

[0m
[31mCMake Error at CMakeLists.txt:74 (add_subdirectory):
  The source directory

    /build/source/lib/tiny-process-library

  does not contain a CMakeLists.txt file.

[0m
[31mCMake Error at CMakeLists.txt:75 (add_subdirectory):
  The source directory

    /build/source/lib/backward-cpp

  does not contain a CMakeLists.txt file.

[0m
[31mCMake Error at CMakeLists.txt:76 (add_subdirectory):
  The source directory

    /build/source/lib/traypp

  does not contain a CMakeLists.txt file.

[0m
[31mCMake Error at CMakeLists.txt:77 (add_subdirectory):
  The source directory

    /build/source/lib/guardpp

  does not contain a CMakeLists.txt file.

[0m
[31mCMake Error at CMakeLists.txt:78 (add_subdirectory):
  The source directory

    /build/source/lib/lockpp

  does not contain a CMakeLists.txt file.

[0m
[31mCMake Error at CMakeLists.txt:80 (add_backward):
  Unknown CMake command "add_backward".

[0m
-- Configuring incomplete, errors occurred!
See also "/build/source/build/CMakeFiles/CMakeOutput.log".
See also "/build/source/build/CMakeFiles/CMakeError.log".
```

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release not [...]

2022-02-16 08:03 UTC, Slabity commented
@pasqui23 - A short while ago I took the derivation from an [older PR](https://github.com/NixOS/nixpkgs/pull/129571) for soundux and fixed it up to compile and work on my system. It might help if you're going to try and get it brought into the repo:

```nix
{
  lib, stdenv, fetchFromGitHub, cmake, ninja, pkg-config, makeWrapper, wrapGAppsHook,
  libappindicator-gtk3, openssl, pipewire, pulseaudio, webkitgtk, xorg,
  libpulseaudio, libwnck3,
  downloaderSupport ? true, ffmpeg, youtube-dl
}:

let
  downloaderPath = lib.makeBinPath [ffmpeg youtube-dl ];
  # Soundux loads pipewire, pulse and libwnck optionally during runtime
  dynamicLibraries = lib.makeLibraryPath [libpulseaudio pipewire libwnck3 ];
in
stdenv.mkDerivation rec {
  pname = "soundux";
  version = "0.2.7";

  src = fetchFromGitHub {
    owner = "Soundux";
    repo = "Soundux";
    rev = version;
    fetchSubmodules = true;
    sha256 = "15kd9vl7inn8zm5cqzjkb6zb9xk2xxwpkm7fx1za3dy9m61sq839";
  };

  cmakeFlags = [ "-DCMAKE_BUILD_TYPE=Release" ];

  dontWrapGApps = true;

  installPhase = ''
    mkdir -p $out/opt $out/bin
    cp -r dist soundux-${version} $out/opt
  '';

  postFixup = ''
    makeWrapper $out/opt/soundux-${version} $out/bin/soundux \
      --prefix LD_LIBRARY_PATH ":" ${dynamicLibraries} \
      "''${gappsWrapperArgs[@]}" \
      ${lib.optionalString downloaderSupport "--prefix PATH \":\" " + downloaderPath}
  '';

  nativeBuildInputs = [ cmake ninja pkg-config makeWrapper wrapGAppsHook ];
  buildInputs = [
    libappindicator-gtk3
    openssl
    pipewire
    pulseaudio
    webkitgtk
    xorg.libX11
    xorg.libXtst
  ];

  meta = with lib; {
    homepage = "https://soundux.rocks/";
    description = "cross-platform soundboard";
    license = licenses.gpl3Only;
    platforms = platforms.linux;
  };
}
```

2022-02-16 10:47 UTC, pasqui23 commented
@Slabity Sorry even with your fix still does not compile

2022-02-17 04:37 UTC, Slabity commented
> @Slabity Sorry even with your fix still does not compile

Strange. That derivation builds for me and lets me run it without any issue.

2022-02-23 20:10 UTC, pasqui23 commented
Ok @Slabity my mistake. Now it builds and run perfectly

2022-04-09 19:08 UTC, yshym reviewed
Package file should be formatted with [nixpkgs-fmt](https://github.com/nix-community/nixpkgs-fmt)

2022-04-09 19:12 UTC, yshym commented on pkgs/applications/audio/soundux/default.nix
> +
Would you please add `desktopItem` attribute here (check [discord package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/instant-messengers/discord/linux.nix#L97-L105) for example)

2022-04-09 19:16 UTC, yshym commented on pkgs/applications/audio/soundux/default.nix
> +
You'll also need to create `share` directory and create a symlink to it like [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/networking/instant-messengers/discord/linux.nix#L94)

2022-04-10 12:46 UTC, yshym commented on pkgs/applications/audio/soundux/default.nix
> +    exec = binaryName;
```suggestion
    exec = pname;
```
`binaryName` does not exist. We can just use `pname` here

2022-04-10 12:46 UTC, yshym commented on pkgs/applications/audio/soundux/default.nix
> +    categories = [ "Multimedia" ];
```suggestion
    categories = [ "Audio" ];
```
There is no such category (check [registered categories](https://specifications.freedesktop.org/menu-spec/latest/apa.html)). We can just use `Audio` here

2022-04-10 12:46 UTC, yshym commented on pkgs/applications/audio/soundux/default.nix
> +    mkdir -p $out/opt $out/bin
```suggestion
    mkdir -p $out/{opt,bin,share}
```
This line can be simplified. And we can also create `share` directory here

2022-04-10 12:46 UTC, yshym commented on pkgs/applications/audio/soundux/default.nix
> +    mkdir -p $out/share/
```suggestion
```
This line is not needed after we change the first line of the `installPhase` (see previous comment)

2022-04-10 12:46 UTC, yshym commented on pkgs/applications/audio/soundux/default.nix
> +  ];
```suggestion
  buildInputs = with xorg; [
    libappindicator-gtk3
    openssl
    pipewire
    pulseaudio
    webkitgtk
    libX11
    libXtst
  ];
```

2022-04-17 18:30 UTC, dali99 requested changes
@Slabity What was your fix? as far as I can tell what you posted is just, exactly my package https://github.com/NixOS/nixpkgs/commit/4943cd25b5c76a7d376d46166bfe97f34a1cad9d but with the maintainer field removed.

The reason the original PR wasn't merged was because the libraries used needed to be devendored, you'll have to do that as well if you want this merged.

In it's current form this is 99% my work anyways though lol, and most of the things commented on previously were already covered by the final version in the aforementiond PR (https://github.com/NixOS/nixpkgs/pull/129571)

I applaud you for picking up the mantle and don't at all mind. But you should be careful about these things in the future since it's important that you actually hold legal copyright over the work you try to commit. (And the line for how much you can copy, and how complex that can be is generally fairly poorly defined)

2022-04-17 19:38 UTC, Slabity commented
@dali99 - Uh... I think I screwed up my copy-paste because I definitely added a lot more dependencies in mine to fix some linking issues and get all the additional features I wanted. And it doesn't look like I removed the maintainer field. Here's what I have in my repo at the moment:

```nix
{
  lib, stdenv, fetchFromGitHub, cmake, ninja, pkg-config, makeWrapper, wrapGAppsHook,
  libappindicator-gtk3, pcre, openssl, pipewire, pulseaudio, webkitgtk, xorg, utillinux,
  libpulseaudio, libwnck3, libselinux, libsepol, libthai, libdatrie,
  libxkbcommon, epoxy, dbus_tools,
  downloaderSupport ? true, ffmpeg, youtube-dl
}:

let
  downloaderPath = lib.makeBinPath [ffmpeg youtube-dl ];
  # Soundux loads pipewire, pulse and libwnck optionally during runtime
  dynamicLibraries = lib.makeLibraryPath [libpulseaudio pipewire libwnck3 ];
in
stdenv.mkDerivation rec {
  pname = "soundux";
  version = "0.2.7";

  src = fetchFromGitHub {
    owner = "Soundux";
    repo = "Soundux";
    rev = version;
    fetchSubmodules = true;
    sha256 = "15kd9vl7inn8zm5cqzjkb6zb9xk2xxwpkm7fx1za3dy9m61sq839";
  };

  cmakeFlags = [ "-DCMAKE_BUILD_TYPE=Release" ];

  dontWrapGApps = true;

  installPhase = ''
    mkdir -p $out/opt $out/bin
    cp -r dist soundux-${version} $out/opt
  '';

  postFixup = ''
    makeWrapper $out/opt/soundux-${version} $out/bin/soundux \
      --prefix LD_LIBRARY_PATH ":" ${dynamicLibraries} \
      "''${gappsWrapperArgs[@]}" \
      ${lib.optionalString downloaderSupport "--prefix PATH \":\" " + downloaderPath}
  '';

  nativeBuildInputs = [ cmake ninja pkg-config makeWrapper wrapGAppsHook ];
  buildInputs = [
    libappindicator-gtk3
    openssl
    libselinux
    libsepol
    libthai
    libdatrie
    utillinux
    pcre
    pipewire
    pulseaudio
    webkitgtk
    xorg.libX11
    xorg.libXtst
    xorg.libXdmcp
    libxkbcommon
    epoxy
    dbus_tools
  ];

  meta = with lib; {
    homepage = "https://soundux.rocks/";
    description = "cross-platform soundboard";
    license = licenses.gpl3Only;
    platforms = platforms.linux;
    maintainers = with maintainers; [ dandellion ];
  };
}
```

Sorry for the mixup, I wasn't intending to get my changes committed at all. I just happened to see this PR and thought I'd link to the older one since it was closer to working.

2022-04-17 19:47 UTC, dali99 commented
No worries, everything after the first section was mainly aimed at @pasqui23 anyways :)

2022-04-18 18:01 UTC, dali99 reviewed
By devendoring we refer to building without these libraries coming from the soundux source: https://github.com/Soundux/Soundux/tree/0.2.7/lib  and rather being packaged directly in nixpkgs

2022-04-25 10:20 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/827

2022-04-25 12:27 UTC, gador requested changes
Please rebase. If you want me to check again later and build the package, give me a ping.

2022-04-25 12:27 UTC, gador commented on pkgs/applications/audio/soundux/default.nix
> +    maintainers = with maintainers; [ dandellion ];
Is it intentional that you are not listed as maintainer?

2022-04-25 15:26 UTC, SuperSandro2000 commented on pkgs/applications/audio/soundux/default.nix
> +      ${lib.optionalString downloaderSupport "--prefix PATH \":\" " + downloaderPath}
```suggestion
      ${lib.optionalString downloaderSupport "--prefix PATH \":\" ${lib.makeBinPath [ ffmpeg youtube-dl ]}"}
```

2022-04-25 15:26 UTC, SuperSandro2000 commented on pkgs/applications/audio/soundux/default.nix
> +      --prefix LD_LIBRARY_PATH ":" ${dynamicLibraries} \
```suggestion
    # Soundux loads pipewire, pulse and libwnck optionally during runtime
    makeWrapper $out/opt/soundux-${version} $out/bin/soundux \
      --prefix LD_LIBRARY_PATH ":" ${lib.makeLibraryPath [ libpulseaudio pipewire libwnck3 ]} \
```

2022-04-25 15:26 UTC, SuperSandro2000 commented on pkgs/applications/audio/soundux/default.nix
> +stdenv.mkDerivation rec {
```suggestion
stdenv.mkDerivation rec {
```

2022-04-25 15:26 UTC, SuperSandro2000 commented on pkgs/applications/audio/soundux/default.nix
> +    fetchSubmodules = true;
Vendoring so many libraries is not great.

2022-04-25 15:26 UTC, SuperSandro2000 commented on pkgs/applications/audio/soundux/default.nix
> +    cp -r dist soundux-${version} $out/opt
Does this need to be opt?

2022-04-25 18:09 UTC, dali99 requested changes
Your devendoring commit does not devendor.

See my prior comment on what we mean when we say that

2022-04-26 09:49 UTC, gador commented
Result of `nixpkgs-review pr 160181` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>soundux</li>
  </ul>
</details>

2022-05-05 00:57 UTC, PAI5REECHO commented
I couldn't get this to run due to some EGL issues:
```
[00:56:35] [success] Config read
[00:56:35] [success] LibWnck found - Icon support is enabled

(soundux-0.2.7:342196): Gdk-WARNING **: 20:56:35.822: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface ?org.freedesktop.portal.Settings? on object at path /org/freedesktop/portal/desktop

(soundux-0.2.7:342196): Wnck-WARNING **: 20:56:35.841: libwnck is designed to work in X11 only, no valid display found
[00:56:35] [warning] Failed to get default screen!
[00:56:35] [failure] Could not create IconFetcher instance
[00:56:35] [message] Connected to PipeWire ("pipewire-0") on version "0.3.49"
[00:56:36] [warning] Path "/home/me/audio-clips" does not exist
[00:56:36] [message] Using DISPLAY :0
[00:56:36] [warning] Failed to find iconPath for tray icon
Could not determine the accessibility bus address

(WebKitWebProcess:342222): Gdk-WARNING **: 20:56:36.348: Failed to read portal settings: GDBus.Error:org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.portal.Settings” on object at path /org/freedesktop/portal/desktop
EGLDisplay Initialization failed: EGL_NOT_INITIALIZED
Cannot create EGL context: invalid display (last error: EGL_SUCCESS)
```

2022-05-14 11:00 UTC, milahu commented
> EGLDisplay Initialization failed: EGL_NOT_INITIALIZED

see also #169201

2023-01-26 00:47 UTC, NickCao commented
superseded by https://github.com/NixOS/nixpkgs/pull/185858

2023-01-26 00:47 UTC, closed without merging