Electron cash fix update
NixOS/nixpkgs pull request #160607
Opened 2022-02-18 11:53 UTC by nyanloutre

###### Motivation for this change

Update electron-cash and add patch from pull request to remove qdarkstyle version pin

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-02-18 12:25 UTC, oxalica requested changes
The PR title should also be like `electron-cash: update and fix build`.

2022-02-18 12:25 UTC, oxalica commented on pkgs/applications/misc/electron-cash/default.nix
> +      url = "https://github.com/Electron-Cash/Electron-Cash/pull/2396.patch";
Please don't use the PR diff URL. They are not deterministic and may cause build failure later. Use commit diff URL instead:
- `https://github.com/Electron-Cash/Electron-Cash/commit/086c7f797f60e9f7c84bc622d867c98cb3b743ee.patch`
- `https://github.com/Electron-Cash/Electron-Cash/commit/8d0aa028e1665196e6c8643eae1fbf9fae33e9f4.patch`

Also, let's add a comment for the PR URL before `fetchpatch`.

2022-03-13 08:17 UTC, oxalica commented
Is this PR still active?

2022-03-21 15:34 UTC, Lassulus commented
superseded by https://github.com/NixOS/nixpkgs/pull/165123

2022-03-21 15:34 UTC, closed without merging