ani-cli: init at v1.9
NixOS/nixpkgs pull request #163384
Opened 2022-03-08 22:48 UTC by skykanin

###### Description of changes
Adds the [ani-cli](https://github.com/pystardust/ani-cli) tool

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-13 12:09 UTC, OPNA2608 requested changes
Result of `nixpkgs-review pr 163384` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ani-cli</li>
  </ul>
</details>

Result of `nixpkgs-review pr 163384` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ani-cli</li>
  </ul>
</details>

2022-03-13 12:09 UTC, OPNA2608 commented on pkgs/applications/video/ani-cli/default.nix
> +    cp ani-cli $out/bin
```suggestion
    install -Dm755 {,$out/bin/}ani-cli
```

2022-03-13 12:09 UTC, OPNA2608 commented on pkgs/applications/video/ani-cli/default.nix
> +    maintainers = with lib.maintainers; [ skykanin ];
```suggestion
  meta = with lib; {
    homepage = "https://github.com/pystardust/ani-cli";
    description = "A cli tool to browse and play anime";
    license = licenses.gpl3Plus;
    maintainers = with maintainers; [ skykanin ];
```

2022-03-13 12:09 UTC, OPNA2608 commented on pkgs/applications/video/ani-cli/default.nix
> +    ];
```suggestion
    platforms = platforms.unix;
```

?

2022-03-24 18:17 UTC, OPNA2608 requested changes

2022-03-24 18:17 UTC, OPNA2608 commented on pkgs/applications/video/ani-cli/default.nix
> +}
```suggestion
}
```

2022-03-24 18:17 UTC, OPNA2608 commented on pkgs/applications/video/ani-cli/default.nix
> +stdenv.mkDerivation rec {
I think you could use `stdenvNoCC` here because there's nothing to compile?

2022-03-24 18:17 UTC, OPNA2608 commented on pkgs/applications/video/ani-cli/default.nix
> +, openssl, mpv, aria2 }:
```suggestion
{ fetchFromGitHub
, makeWrapper
, stdenv
, lib
, gnugrep
, gnused
, curl
, openssl
, mpv
, aria2
}:
```

Formatting aside, removed unused `config` input. See previous comment regarding `stdenv` or `stdenvNoCC`.

2022-03-27 13:35 UTC, SuperSandro2000 commented on pkgs/applications/video/ani-cli/default.nix
> +      }
```suggestion
      --prefix PATH : ${lib.makeBinPath [ gnugrep gnused curl openssl mpv aria2 ]}
```

2022-03-27 13:35 UTC, SuperSandro2000 commented on pkgs/applications/video/ani-cli/default.nix
> +    install -Dm755 {,$out/bin/}ani-cli
```suggestion
    install -Dm755 ani-cli $out/bin/ani-cli
```

2022-03-27 13:38 UTC, SuperSandro2000 commented on pkgs/applications/video/ani-cli/default.nix
> +  dontBuild = true;
We only disable those if they cause problems.

2022-03-27 13:44 UTC, OPNA2608 commented on pkgs/applications/video/ani-cli/default.nix
> +  dontBuild = true;
Source? Pretty sure we can just use them when there's nothing to configure/build.

2022-03-27 18:13 UTC, merged