mokutil: init at 0.5.0
NixOS/nixpkgs pull request #163434
Opened 2022-03-09 11:33 UTC by NickCao

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-09 20:13 UTC, papojari commented
Result of `nixpkgs-review pr 163434` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mokutil</li>
  </ul>
</details>

2022-03-09 20:18 UTC, papojari requested changes

2022-03-09 20:18 UTC, papojari commented on pkgs/tools/security/mokutil/default.nix
> +    license = lib.licenses.gpl3Only;
```suggestion
    license = lib.licenses.gpl3Plus;
```
The source code says GPL v3 or any later version. https://github.com/lcp/mokutil/blob/master/src/keyring.c

2022-03-09 20:18 UTC, papojari commented on pkgs/tools/security/mokutil/default.nix
> +    maintainers = with lib.maintainers; [ nickcao ];
```suggestion
  meta = with lib; {
    homepage = "https://github.com/lcp/mokutil";
    description = "The utility to manipulate machines owner keys which managed in shim";
    license = licenses.gpl3Only;
    maintainers = with maintainers; [ nickcao ];
```

2022-03-10 15:50 UTC, papojari approved these changes

2022-03-10 15:50 UTC, papojari commented on pkgs/tools/security/mokutil/default.nix
> +stdenv.mkDerivation rec {
```suggestion

stdenv.mkDerivation rec {
```

2022-03-10 15:51 UTC, papojari commented on pkgs/tools/security/mokutil/default.nix
> +stdenv.mkDerivation rec {
meant to request changes not approve

2022-03-10 16:29 UTC, papojari requested changes
Also this works for all platforms, right?

2022-03-10 16:29 UTC, papojari commented on pkgs/tools/security/mokutil/default.nix
> +    description = "The utility to manipulate machines owner keys which managed in shim";
```suggestion
    description = "Utility to manipulate machines owner keys";
```
This is shorter and it's also the same as the description in the man page.

2022-03-10 17:07 UTC, papojari commented
Result of `nixpkgs-review pr 163434` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mokutil</li>
  </ul>
</details>

2022-03-10 17:07 UTC, papojari approved these changes

2022-03-10 17:14 UTC, papojari commented
##### Reviewed points

- [ ] package path fits guidelines
- [ ] package name fits guidelines
- [ ] package version fits guidelines
- [ ] package build on ARCHITECTURE
- [ ] executables tested on ARCHITECTURE
- [ ] `meta.description` is set and fits guidelines
- [ ] `meta.license` fits upstream license
- [ ] `meta.platforms` is set
- [ ] `meta.maintainers` is set
- [ ] build time only dependencies are declared in `nativeBuildInputs`
- [ ] source is fetched using the appropriate function
- [ ] phases are respected

2022-03-11 09:03 UTC, bobby285271 commented
@ofborg build mokutil

2022-03-11 09:18 UTC, merged