README: white logo for dark mode
NixOS/nixpkgs pull request #163407
Opened 2022-03-09 05:23 UTC by ryantm

Before:
![image](https://user-images.githubusercontent.com/4804/157377833-055d2acd-9ba6-47bf-91cb-217482bfd16b.png)
![image](https://user-images.githubusercontent.com/4804/157377870-1f7e24d3-64eb-496a-8f46-8f1e96ae6be2.png)

After:
![image](https://user-images.githubusercontent.com/4804/157377956-a9d4f13a-e065-403a-824a-9466140adcaa.png)
![image](https://user-images.githubusercontent.com/4804/157377920-bda6eb22-9ffd-4819-b59c-e0f1fb8f11b4.png)

One unavoidable downside to this is the link to the image includes # anchors that are GitHub specific. Like https://nixos.org#gh-light-mode-only I think it is still worth the tradeoff of making it look good on dark mode. This thread may eventually contain information when GitHub improves this https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981/97

2022-03-09 08:40 UTC, wamserma commented
I'd prefer keeping the blueish colour of the flake and only inverting the text colour.

2022-03-09 14:14 UTC, ryantm commented
> I'd prefer keeping the blueish colour of the flake and only inverting the text colour.

This isn't the repo to discuss that. This is the current official dark background logo. You can go to https://github.com/NixOS/nixos-artwork/ to work on that aspect.

2022-03-09 14:39 UTC, 06kellyjac approved these changes
A nice change for now. We can always update it with the colours if we change that later

2022-03-09 22:12 UTC, samueldr requested changes
It feels a bit too "in-your-face" to not limit the width. Let's put back the previously used value.

Yes, the logo is wider than 500px, and it's good, since it means that on higher DPI systems the extra pixels available are used.

2022-03-09 22:12 UTC, samueldr commented on README.md
> +    <img src="https://raw.githubusercontent.com/NixOS/nixos-homepage/master/logo/nixos-hires.png" alt="NixOS logo"/>
```suggestion
    <img src="https://raw.githubusercontent.com/NixOS/nixos-homepage/master/logo/nixos-hires.png" width="500px" alt="NixOS logo"/>
```

2022-03-09 22:12 UTC, samueldr commented on README.md
> +    <img src="https://raw.githubusercontent.com/NixOS/nixos-artwork/master/logo/nixos-white.png" alt="NixOS logo"/>
```suggestion
    <img src="https://raw.githubusercontent.com/NixOS/nixos-artwork/master/logo/nixos-white.png" width="500px" alt="NixOS logo"/>
```

2022-03-10 00:08 UTC, ryantm commented on README.md
> +    <img src="https://raw.githubusercontent.com/NixOS/nixos-homepage/master/logo/nixos-hires.png" alt="NixOS logo"/>
I made them both be 500px!

2022-03-10 00:08 UTC, ryantm commented on README.md
> +    <img src="https://raw.githubusercontent.com/NixOS/nixos-artwork/master/logo/nixos-white.png" alt="NixOS logo"/>
I made them both be 500px!

2022-03-10 03:04 UTC, samueldr approved these changes

2022-03-10 03:09 UTC, merged