python: gb-io: init at 0.1.0
NixOS/nixpkgs pull request #163919
Opened 2022-03-12 23:16 UTC by dlesl

###### Description of changes

https://pypi.org/project/gb-io/

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-23 23:42 UTC, IvarWithoutBones commented on pkgs/development/python-modules/gb-io/default.nix
> +}
You should add the  `meta` attribute

2022-03-23 23:42 UTC, IvarWithoutBones commented on pkgs/development/python-modules/gb-io/default.nix
> +    name = "${pname}-${version}";
Bit nicer to read i think:
```suggestion
    name = "gb-io-${version}";
```

2022-03-23 23:44 UTC, IvarWithoutBones commented
Thanks for the PR! I've left a few suggestions :blush:

2022-03-27 10:29 UTC, SuperSandro2000 requested changes
The commit must be `python310Packages.gb-io: init at 0.1.0`.

2022-04-14 20:57 UTC, SuperSandro2000 commented on pkgs/development/python-modules/gb-io/default.nix
> +    platforms = platforms.unix;
```suggestion
```

that is the default

2022-04-14 21:12 UTC, SuperSandro2000 commented on pkgs/development/python-modules/gb-io/default.nix
> +
```suggestion

  checkPhase = ''
    python -m unittest discover
  '';

  pythonImportsCheck = [ "gb_io" ];

```

see https://github.com/althonos/gb-io.py/blob/main/.github/workflows/test.yml

2022-04-16 00:26 UTC, merged