Add pandoc-include
NixOS/nixpkgs pull request #164552
Opened 2022-03-17 08:26 UTC by ppenguin

###### Description of changes

[`pandoc-include`](https://github.com/DCsunset/pandoc-include) is a python-based pandoc filter to allow file and header includes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-17 08:49 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/pandoc-omatic-and-filters-install-location-issues/18179/2

2022-03-19 16:45 UTC, rnhmjoj commented
I believe this should be considered an application, i.e. not intended to be imported and used in a python program.
If so, you should use `buildPythonApplication` instead and move the definition to `pkgs/top-level/all-packages.nix`.

This is what the manual says about it:

> The buildPythonApplication function is practically the same as buildPythonPackage. The main purpose of this function is to build a Python package where one is interested only in the executables, and not importable modules. For that reason, when adding this package to a python.buildEnv, the modules won’t be made available.

> All Python packages reside in pkgs/top-level/python-packages.nix and all applications elsewhere.

2022-03-26 23:13 UTC, rnhmjoj requested changes
A couple more suggestions, sorry If I didn't report them earlier.

2022-03-26 23:13 UTC, rnhmjoj commented on pkgs/tools/misc/pandoc-include/default.nix
> +  doCheck = false;
If the package has no check phase you don't need to disable it: Nix will simply skip it.
The repository does have tests, but need pandoc and latex which seems a bit excessive.
As a lightweight alternative you can do:
```suggestion
  pythonImportsCheck = [ "pandoc_include.main" ];
```

2022-03-26 23:13 UTC, rnhmjoj commented on pkgs/tools/misc/pandoc-include/default.nix
> +    description = "Pandoc filter to allow file and header includes.";
The convention is to *not* have a final period in the description.

2022-03-27 15:25 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 164552` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>pandoc-include</li>
</ul>
</details>

2022-03-27 15:25 UTC, merged