rclone: prefix PATH of fuse
NixOS/nixpkgs pull request #164894
Opened 2022-03-19 20:05 UTC by nagy

###### Description of changes
This is needed because `rclone` makes use of `fusermount` when mounting filesystems.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-19 22:05 UTC, ckiee requested changes
Psst. https://github.com/nixos/nixpkgs/blob/1d3edd77efd72a36ce2508d3ba19de3c35452483/pkgs/tools/filesystems/gocryptfs/default.nix#L54-L55
```
[nix-shell:~/.cache/nixpkgs-review/pr-164894]$ RCLONE_CONFIG=/home/ckie/git/nixfiles/secrets/rclone-config rclone mount gdrive:bokkusu-postgres bleh
2022/03/20 00:05:19 mount helper error: fusermount: mount failed: Operation not permitted
2022/03/20 00:05:19 Fatal error: failed to mount FUSE fs: fusermount: exit status 1
```

2022-03-19 22:22 UTC, nagy commented
Thank you, I have adapted it. I only tested it from within a systemd service, where it worked.

2022-03-20 18:45 UTC, merged

2023-01-05 02:57 UTC, oxalica commented
So the PATH suffix is only used when `/run/wrappers` is not accessible, but the process has root permission to mount/umount, yes? Then `rclone` needs `fusermount` in the first place, rather than calling `mount(2)` directly? IIRC, the existence of `fusermount` (as an SUID binary) is to enable non-root users to mount/umount FUSE.

2023-01-08 22:01 UTC, nagy commented
> So the PATH suffix is only used when /run/wrappers is not accessible, but the process has root permission to mount/umount, yes? 

I dont know about the first part, but yes to the second part. I was using rclone inside a systemd service and it complained about not being able to find `fusermount`. This issue is known and documented here https://rclone.org/commands/rclone_mount/#systemd . 

> Since mounting requires the fusermount program, rclone will use the fallback PATH of /bin:/usr/bin in this scenario. Please ensure that fusermount is present on this PATH.

> Then rclone needs fusermount in the first place, rather than calling mount(2) directly? 

I dont know, you would have to ask the rclone dev team. Did this PR cause any problems for you ?

2023-01-10 18:58 UTC, oxalica commented
> I was using rclone inside a systemd service and it complained about not being able to find `fusermount`. This issue is known and documented here https://rclone.org/commands/rclone_mount/#systemd .
> 
> > Since mounting requires the fusermount program, rclone will use the fallback PATH of /bin:/usr/bin in this scenario. Please ensure that fusermount is present on this PATH.

Thanks for the explanation. So it do calls `fusermount` in practice and the PATH is necessary.

> > Then rclone needs fusermount in the first place, rather than calling mount(2) directly?
> 
> I dont know, you would have to ask the rclone dev team. Did this PR cause any problems for you ?

Not really any problems. I just found this PR suspicious when doing #209128.