Add package `fig`
NixOS/nixpkgs pull request #164990
Opened 2022-03-20 15:47 UTC by opeik

###### Description of changes

Added package `fig` for macOS.

###### Things done

- Added `pkgs/development/tools/fig/default.nix`
- Added `fig` to `pkgs/top-level/all-packages.nix`

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-27 09:51 UTC, SuperSandro2000 requested changes

2022-03-27 09:51 UTC, SuperSandro2000 commented on pkgs/development/tools/fig/default.nix
> +  meta = with lib; {
Meta should always be last.

2022-03-27 09:51 UTC, SuperSandro2000 commented on pkgs/development/tools/fig/default.nix
> +  binname = "fig-darwin-universal";
```suggestion
```

2022-03-27 09:51 UTC, SuperSandro2000 commented on pkgs/development/tools/fig/default.nix
> +  appname = "Fig";
```suggestion
```

2022-03-27 09:51 UTC, SuperSandro2000 commented on pkgs/development/tools/fig/default.nix
> +    makeWrapper $out/Applications/${appname}.app/Contents/MacOS/${binname} $out/bin/${pname}
```suggestion
  sourceRoot = "Fig.app";
  nativeBuildInputs = [ makeWrapper undmg unzip ];
  installPhase = ''
    runHook preInstall
    mkdir -p $out/Applications/Fig.app $outbin
    cp -R . $out/Applications/Fig.app
    makeWrapper $out/Applications/Fig.app/Contents/MacOS/fig-darwin-universal $out/bin/fig
```

2022-09-13 09:11 UTC, arjan-s commented
Fix also supports Linux now (in beta, but still). Would it be doable to integrate that into this package?

2023-06-07 14:08 UTC, drupol requested changes
Dear @opeik 

Do you plan to update this PR ?

Feel free to close it if you don't.

Thanks

2023-06-07 15:01 UTC, opeik commented
Apologies, no, I don't. I ended up using the nix-darwin homebrew integration.

2023-06-07 15:01 UTC, closed without merging

2023-06-07 15:13 UTC, drupol commented
Fair enough, thanks for closing the PR.