pyside2: make qtwebengine optional
NixOS/nixpkgs pull request #165042
Opened 2022-03-21 00:54 UTC by dali99

###### Description of changes

[python3Packages.pyside2: allow disabling qtwebengine](https://github.com/NixOS/nixpkgs/commit/c70fd5470d226cbd151b3792fc5917ea5ece1c12)

Building without qtwebengine reduces closure size by quite a bit and compile times by ̃~50% (?)
qtwebengine is also notoriously slow to compile, so allowing programs to build without it speeds up rebuilds without the binary cache significantly (10x)

I also experimented with disabling the other modules in pyside2 but they only sum to ~1MB extra in closure size (and like 30 minutes less in compile time) on this computer.

This reduces closure size by like only 7% in hydrus

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-21 00:56 UTC, dali99 commented
cutter freecad napari onionshare patray pyside2 pyside2 pyside2-tools pyside2-tools python3.10-magicgui python3.10-napari python3.10-tumpa python3.9-hydrus python3.9-magicgui python3.9-napari python3.9-tumpa sl1-to-photon syncplay seem to be the only packages using pyside2, maybe some of them can be converted into the one without the webengine as well

2022-03-22 09:41 UTC, FRidh requested changes
The rule of thumb in Nixpkgs is to split a package instead of building variants. If I am correct, just moving the *.so into a separate output and exposing it as a package would be sufficient.

2022-03-22 13:28 UTC, dali99 commented
The main point was to not have to built the entirety of chromium whenever it gets updated, (which happens almost every upgrade cycle for hydrus, delaying testing for days). Splitting the output would reduce closure size, but afaik wouldnt reduce compile times.

Additionally it seems to use the configurephase to autodetect present libraries which could be problematic if we then just "remove" parts of it by splitting? (I don't know). The output is pretty complicated:
<details>
result
├── include
│   └── PySide2
│       ├── dynamicqmetaobject.h
│       ├── feature_select.h
│       ├── pyside2_global.h
│       ├── pysideclassinfo.h
│       ├── pyside.h
│       ├── pysidemacros.h
│       ├── pysidemetafunction.h
│       ├── pysideproperty.h
│       ├── pysideqenum.h
│       ├── pysideqflags.h
│       ├── pysidesignal.h
│       ├── pysidestaticstrings.h
│       ├── pysideweakref.h
│       ├── QtCharts
│       │   └── pyside2_qtcharts_python.h
│       ├── QtConcurrent
│       │   └── pyside2_qtconcurrent_python.h
│       ├── QtCore
│       │   └── pyside2_qtcore_python.h
│       ├── QtGui
│       │   ├── pyside2_qtgui_python.h
│       │   └── qpytextobject.h
│       ├── QtHelp
│       │   └── pyside2_qthelp_python.h
│       ├── QtLocation
│       │   └── pyside2_qtlocation_python.h
│       ├── QtMultimedia
│       │   └── pyside2_qtmultimedia_python.h
│       ├── QtMultimediaWidgets
│       │   └── pyside2_qtmultimediawidgets_python.h
│       ├── QtNetwork
│       │   └── pyside2_qtnetwork_python.h
│       ├── QtOpenGL
│       │   └── pyside2_qtopengl_python.h
│       ├── QtOpenGLFunctions
│       │   └── pyside2_qtopenglfunctions_python.h
│       ├── QtPositioning
│       │   └── pyside2_qtpositioning_python.h
│       ├── QtPrintSupport
│       │   └── pyside2_qtprintsupport_python.h
│       ├── QtQml
│       │   └── pyside2_qtqml_python.h
│       ├── QtQuick
│       │   └── pyside2_qtquick_python.h
│       ├── QtQuickWidgets
│       │   └── pyside2_qtquickwidgets_python.h
│       ├── QtScript
│       │   └── pyside2_qtscript_python.h
│       ├── QtScriptTools
│       │   └── pyside2_qtscripttools_python.h
│       ├── QtSensors
│       │   └── pyside2_qtsensors_python.h
│       ├── QtSql
│       │   └── pyside2_qtsql_python.h
│       ├── QtSvg
│       │   └── pyside2_qtsvg_python.h
│       ├── QtTest
│       │   └── pyside2_qttest_python.h
│       ├── QtUiTools
│       │   └── pyside2_qtuitools_python.h
│       ├── QtWebChannel
│       │   └── pyside2_qtwebchannel_python.h
│       ├── QtWebEngine
│       │   └── pyside2_qtwebengine_python.h
│       ├── QtWebEngineCore
│       │   └── pyside2_qtwebenginecore_python.h
│       ├── QtWebEngineWidgets
│       │   └── pyside2_qtwebenginewidgets_python.h
│       ├── QtWebSockets
│       │   └── pyside2_qtwebsockets_python.h
│       ├── QtWidgets
│       │   └── pyside2_qtwidgets_python.h
│       ├── QtX11Extras
│       │   └── pyside2_qtx11extras_python.h
│       ├── QtXml
│       │   └── pyside2_qtxml_python.h
│       ├── QtXmlPatterns
│       │   └── pyside2_qtxmlpatterns_python.h
│       └── signalmanager.h
├── lib
│   ├── cmake
│   │   └── PySide2-5.15.2
│   │       ├── PySide2Config.cmake
│   │       ├── PySide2Config.cpython-39-x86_64-linux-gnu.cmake
│   │       ├── PySide2ConfigVersion.cmake
│   │       ├── PySide2Targets.cmake
│   │       └── PySide2Targets-release.cmake
│   ├── libpyside2.cpython-39-x86_64-linux-gnu.so -> libpyside2.cpython-39-x86_64-linux-gnu.so.5.15
│   ├── libpyside2.cpython-39-x86_64-linux-gnu.so.5.15 -> libpyside2.cpython-39-x86_64-linux-gnu.so.5.15.2
│   ├── libpyside2.cpython-39-x86_64-linux-gnu.so.5.15.2
│   ├── pkgconfig
│   │   └── pyside2.pc
│   └── python3.9
│       └── site-packages
│           └── PySide2
│               ├── _config.py
│               ├── _git_pyside_version.py
│               ├── __init__.py
│               ├── QtCharts.cpython-39-x86_64-linux-gnu.so
│               ├── QtConcurrent.cpython-39-x86_64-linux-gnu.so
│               ├── QtCore.cpython-39-x86_64-linux-gnu.so
│               ├── QtGui.cpython-39-x86_64-linux-gnu.so
│               ├── QtHelp.cpython-39-x86_64-linux-gnu.so
│               ├── QtLocation.cpython-39-x86_64-linux-gnu.so
│               ├── QtMultimedia.cpython-39-x86_64-linux-gnu.so
│               ├── QtMultimediaWidgets.cpython-39-x86_64-linux-gnu.so
│               ├── QtNetwork.cpython-39-x86_64-linux-gnu.so
│               ├── QtOpenGL.cpython-39-x86_64-linux-gnu.so
│               ├── QtOpenGLFunctions.cpython-39-x86_64-linux-gnu.so
│               ├── QtPositioning.cpython-39-x86_64-linux-gnu.so
│               ├── QtPrintSupport.cpython-39-x86_64-linux-gnu.so
│               ├── QtQml.cpython-39-x86_64-linux-gnu.so
│               ├── QtQuick.cpython-39-x86_64-linux-gnu.so
│               ├── QtQuickWidgets.cpython-39-x86_64-linux-gnu.so
│               ├── QtScript.cpython-39-x86_64-linux-gnu.so
│               ├── QtScriptTools.cpython-39-x86_64-linux-gnu.so
│               ├── QtSensors.cpython-39-x86_64-linux-gnu.so
│               ├── QtSql.cpython-39-x86_64-linux-gnu.so
│               ├── QtSvg.cpython-39-x86_64-linux-gnu.so
│               ├── QtTest.cpython-39-x86_64-linux-gnu.so
│               ├── QtUiTools.cpython-39-x86_64-linux-gnu.so
│               ├── QtWebChannel.cpython-39-x86_64-linux-gnu.so
│               ├── QtWebEngineCore.cpython-39-x86_64-linux-gnu.so
│               ├── QtWebEngine.cpython-39-x86_64-linux-gnu.so
│               ├── QtWebEngineWidgets.cpython-39-x86_64-linux-gnu.so
│               ├── QtWebSockets.cpython-39-x86_64-linux-gnu.so
│               ├── QtWidgets.cpython-39-x86_64-linux-gnu.so
│               ├── QtX11Extras.cpython-39-x86_64-linux-gnu.so
│               ├── QtXml.cpython-39-x86_64-linux-gnu.so
│               └── QtXmlPatterns.cpython-39-x86_64-linux-gnu.so
├── nix-support
│   └── propagated-build-inputs
└── share
    └── PySide2
        ├── glue
        │   ├── qtcharts.cpp
        │   ├── qtcore.cpp
        │   ├── qtgui.cpp
        │   ├── qtmultimedia.cpp
        │   ├── qtnetwork.cpp
        │   ├── qtopengl.cpp
        │   ├── qtprintsupport.cpp
        │   ├── qtqml.cpp
        │   ├── qtquick.cpp
        │   ├── qtscript.cpp
        │   ├── qtuitools.cpp
        │   ├── qtwebenginewidgets.cpp
        │   ├── qtwidgets.cpp
        │   ├── qtxml.cpp
        │   └── qtxmlpatterns.cpp
        └── typesystems
            ├── core_common.xml
            ├── datavisualization_common.xml
            ├── glue
            │   ├── plugins.h
            │   ├── qeasingcurve_glue.cpp
            │   ├── qeasingcurve_glue.h
            │   └── qscript_value_iterator_glue.cpp
            ├── gui_common.xml
            ├── opengl_common.xml
            ├── openglfunctions_common.xml
            ├── typesystem_charts.xml
            ├── typesystem_concurrent.xml
            ├── typesystem_core_common.xml
            ├── typesystem_core_mac.xml
            ├── typesystem_core_win.xml
            ├── typesystem_core_x11.xml
            ├── typesystem_core.xml
            ├── typesystem_gui_common.xml
            ├── typesystem_gui_mac.xml
            ├── typesystem_gui_win.xml
            ├── typesystem_gui_x11.xml
            ├── typesystem_gui.xml
            ├── typesystem_help.xml
            ├── typesystem_location.xml
            ├── typesystem_multimedia_common.xml
            ├── typesystem_multimedia_forward_declarations.xml
            ├── typesystem_multimediawidgets.xml
            ├── typesystem_multimedia.xml
            ├── typesystem_network.xml
            ├── typesystem_openglfunctions_modifications1_0_compat.xml
            ├── typesystem_openglfunctions_modifications1_0.xml
            ├── typesystem_openglfunctions_modifications1_1_compat.xml
            ├── typesystem_openglfunctions_modifications1_1.xml
            ├── typesystem_openglfunctions_modifications1_2_compat.xml
            ├── typesystem_openglfunctions_modifications1_3_compat.xml
            ├─ [...]

2022-03-23 03:15 UTC, SuperSandro2000 commented on pkgs/development/python-modules/pyside2/default.nix
> +  enableQtwebengine ? true }:
```suggestion
, cmake, ninja, qt5, shiboken2,
, enableQtwebengine ? true
}:
```

2022-03-23 03:15 UTC, SuperSandro2000 commented on pkgs/development/python-modules/pyside2/default.nix
>  { python, fetchurl, lib, stdenv,
```suggestion
{ python, fetchurl, lib, stdenv
```

2022-03-23 03:15 UTC, SuperSandro2000 commented on pkgs/development/python-modules/pyside2/default.nix
> +, cmake, ninja, qt5, shiboken2,
```suggestion
, cmake, ninja, qt5, shiboken2
```

2023-06-27 13:55 UTC, closed without merging