bin: init at 2.0.0
NixOS/nixpkgs pull request #165488
Opened 2022-03-23 19:19 UTC by w4

###### Description of changes

Adds the `bin` package and service, a barebones pastebin that can run with no configuration. The "official" https://bin.gy/ is currently running on NixOS but there has been a couple of requests to move this to Nixpkgs.

https://github.com/w4/bin

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
  - [x] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-24 21:27 UTC, lovesegfault commented
Please call the top-level attr something other than just `bin` if you can? I imagine merging something like this might bite a lot of users that do things like:
```Nix
{ pkgs, ... }:
let
  bin = pkgs.callPackage ./my-bin { };
in
{
  foo = with pkgs; [
    bin
    python
    node
  ];
}
```

2022-03-27 13:00 UTC, SuperSandro2000 requested changes
Yeah, we need to find another name. `bin-paste`?

2022-03-27 13:00 UTC, SuperSandro2000 commented on pkgs/servers/bin/default.nix
> +    ++ lib.optionals stdenv.isDarwin [ darwin.apple_sdk.frameworks.Security ];
```suggestion
  buildInputs = lib.optionals stdenv.isDarwin [ Security ];
```

2022-03-27 13:00 UTC, SuperSandro2000 commented on pkgs/servers/bin/default.nix
> +    description = "a paste bin.";
```suggestion
    description = "Paste bin";
```

2022-03-27 13:00 UTC, SuperSandro2000 commented on pkgs/servers/bin/default.nix
> +  LIBCLANG_PATH="${llvmPackages.libclang}/lib";
```suggestion
  LIBCLANG_PATH = "${llvmPackages.libclang}/lib";
```

2022-03-27 13:00 UTC, SuperSandro2000 commented on pkgs/servers/bin/default.nix
> +rustPlatform.buildRustPackage rec {
```suggestion
{ lib, stdenv, rustPlatform, fetchFromGitHub, llvmPackages, Security }:

rustPlatform.buildRustPackage rec {
```

2022-03-27 13:00 UTC, SuperSandro2000 commented on pkgs/servers/bin/default.nix
> +    rev = "057ed640ee503469fe4c3b0c164aa1b1bffc6cc6";
```suggestion
    rev = "v${version}";
```

2022-03-28 13:29 UTC, w4 commented
Good point, @lovesegfault - thanks for spotting that!

Thanks for the review @SuperSandro2000, I've applied your suggestions in [6eb3f99..85a4772](https://github.com/NixOS/nixpkgs/compare/6eb3f9965671a7e54155f461bf406ae7f73cc493..85a47720687aba1f78d07051401653b300712448).

I've renamed the top-level package in nixpkgs to bin-paste, I've left the service as `bin` though, please let me know if that's alright.

Thanks again

2022-03-28 14:58 UTC, SuperSandro2000 commented
> Edit: I've had to revert [the change from `darwin.apple_sdk.frameworks.Security` to `Security`](https://github.com/NixOS/nixpkgs/pull/165488#discussion_r835904230) as it resulted in errors

You need something similar to the following snippet in all-packages.

```
qtwebview = callPackage ../modules/qtwebview.nix {
  inherit (darwin.apple_sdk.frameworks) CoreFoundation WebKit;
};
```

2022-03-28 15:25 UTC, w4 commented
Ah, that makes sense! All done, thanks @SuperSandro2000

2022-04-24 00:49 UTC, aanderse commented
Sorry for the delay. Modules looks fine. Can you please split your change into 2 commits though? 1 for adding yourself to the maintainer list, and everything else can go into the other commit. Thanks!

2022-08-21 14:33 UTC, hacker1024 commented
@w4 are you able to split the change?

2022-11-19 16:51 UTC, hacker1024 commented
@w4?

2022-12-03 14:30 UTC, w4 commented
Apologies for the delay, this is done now.

2023-04-01 23:59 UTC, SuperSandro2000 commented on nixos/modules/services/web-apps/bin-paste.nix
> +      type = types.int;
```suggestion
      type = types.ints.positive;
```

2023-04-01 23:59 UTC, SuperSandro2000 commented on nixos/modules/services/web-apps/bin-paste.nix
> +      type = types.int;
```suggestion
      type = types.ints.positive;
```

2023-04-01 23:59 UTC, SuperSandro2000 commented on nixos/modules/services/web-apps/bin-paste.nix
> +    package = mkOption {
Please use mkPackageOption

2024-11-12 21:39 UTC, closed without merging