vokoscreen-ng: 3.0.8 -> 3.1.0
NixOS/nixpkgs pull request #165785
Opened 2022-03-25 20:35 UTC by kamilchm

###### Description of changes

https://linuxecke.volkoh.de/vokoscreen/vokoscreen-changes.html

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-25 22:15 UTC, Artturin commented on pkgs/applications/video/vokoscreen-ng/linux-support-installation-target.patch
> -Seulement dans b: patch.patch
can we fetchpatch the arch patch https://github.com/archlinux/svntogit-community/blob/packages/vokoscreen/trunk/0001-Add-better-integration-for-Linux.patch

2022-07-31 03:54 UTC, 3nprob requested changes
Needs `pipewire` as `buildInput` to start properly in Wayland.

2022-07-31 03:54 UTC, 3nprob commented on pkgs/applications/video/vokoscreen-ng/default.nix
> +, wayland
```suggestion
, pipewire
, wayland
```

2022-07-31 03:54 UTC, 3nprob commented on pkgs/applications/video/vokoscreen-ng/default.nix
> +    wayland
```suggestion
    pipewire
    wayland
```

2022-07-31 05:33 UTC, 3nprob commented
Getting this on wayland (qtile, xdg-portal-wlr):
```
Warning: Couldn't get reply ((null):0, (null))
Warning: Error:  "No such interface “org.freedesktop.portal.ScreenCast” on object at path /org/freedesktop/portal/desktop" ((null):0, (null))
```

config:

```
  services = {
    greetd = {
      enable = true;
       settings = rec {
         default_session = {
           command = "${pkgs.greetd.tuigreet}/bin/tuigreet --time --cmd '/home/user/.config/qtile/qtile-run.sh ${pkgs.qtile}/bin/qtile start -b wayland'";
           user = "user";
         };
       };
     };
    dbus = {
        enable = true;
        packages = with pkgs; [ upower dconf gnome2.GConf ];
    };
   xserver = {
      enable = false;
      displayManager = {
        gdm = {
          enable = false;
          wayland = true;
        };
        defaultSession = "none+qtile";
      };
  }
  xdg = {
    portal = {
      wlr.enable = true;
      enable = true;
      extraPortals = with pkgs; [
        xdg-desktop-portal-wlr
      ];
      gtkUsePortal = true;
    };
  };
```

`/home/user/.config/qtile/qtile-run.sh`

```
#!/bin/sh
export XDG_SESSION_TYPE=wayland
export XDG_SESSION_DESKTOP=qtile
export XDG_CURRENT_DESKTOP=qtile

source $HOME/.config/wayland_enablement.sh

systemd-cat --identifier=qtile $@ -l DEBUG
```

2024-01-22 01:38 UTC, luzpaz commented
This can be closed since current stable is 3.8.0  
https://github.com/NixOS/nixpkgs/blob/031c7524250b8c1a5e8accc04920f63d0c95fbdc/pkgs/applications/video/vokoscreen-ng/default.nix#L24

2024-01-22 20:08 UTC, closed without merging