joystickwake: autostart
NixOS/nixpkgs pull request #166271
Opened 2022-03-29 15:39 UTC by SuperSamus

###### Description of changes

The autostart file from `joystickwake` was not in the correct location, now it is. (Taken from `caffeine-ng`.)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-03-30 01:00 UTC, SuperSandro2000 commented on pkgs/tools/games/joystickwake/default.nix
> +    cp -r $out/lib/python*/site-packages/etc $out/etc
```suggestion
    cp -r $out/${python3.sitePackages}/etc $out/etc
```

2022-03-31 08:32 UTC, bertof requested changes
Hi. It needs some minor changes. Then it should be ready for merge.

2022-03-31 08:32 UTC, bertof commented on pkgs/tools/games/joystickwake/default.nix
> +    ln -s $out/lib/python*/site-packages/etc $out/etc
```suggestion
    ln -s $out/${python3.sitePackages}/etc $out/etc
```

2022-03-31 13:24 UTC, bertof approved these changes

2022-04-11 10:21 UTC, merged