APC-Temp-fetch: init at 0.0.1
NixOS/nixpkgs pull request #166409
Opened 2022-03-30 12:30 UTC by zseri

###### Description of changes

A cli application for fetching battery temperature from different network-attached UPS devices.
(written by myself, but I wasn't able to come up with any good way to unit-test it)
Doesn't contain any "native" compiled python extensions, thus pure python.
Also exports a python module which allows access to all extracted information (some UPS status pages are easily parsable and usually contain more info than just battery temperature)

Side note about dependencies: I'm not entirely sure if `nativeBuildInputs = [setuptools];` is the correct way to integrate setuptools. Currently this package doesn't contain tests, otherwise I would've added `pytestCheckHook` to `checkInputs`.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-04-26 23:42 UTC, jonringer commented on pkgs/top-level/python-packages.nix
> +  APC-Temp-fetch = callPackage ../development/python-modules/APC-Temp-fetch { };
Please normalize the attribute name. According to the [python contributing guidelines](https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#contributing-guidelines-contributing-guidelines), package names within nix should follow [PEP 0503](https://www.python.org/dev/peps/pep-0503/#normalized-names)

2022-04-27 04:39 UTC, jonringer reviewed
please PEP 503 the file path as well. Sorry for the other round trip

2022-05-24 22:42 UTC, SuperSandro2000 commented on pkgs/top-level/python-packages.nix
> +  apc-temp-fetch = callPackage ../development/python-modules/apc-temp-fetch { };
If it is not used as a dependency in other packages we don't need or want this entry to be more free what we do with the package.

2022-05-24 22:42 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  apc-temp-fetch = with python39.pkgs; toPythonApplication apc-temp-fetch;
```suggestion
  apc-temp-fetch = with python3.pkgs; toPythonApplication apc-temp-fetch;
```

2022-05-25 20:45 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  apc-temp-fetch = with python39.pkgs; toPythonApplication apc-temp-fetch;
We want to use this construct...

2022-05-25 20:45 UTC, SuperSandro2000 commented on pkgs/development/python-modules/apc-temp-fetch/default.nix
> +in
...to avoid this.

2022-05-25 20:45 UTC, SuperSandro2000 requested changes
.

2022-06-09 18:38 UTC, SuperSandro2000 commented on pkgs/development/python-modules/apc-temp-fetch/default.nix
> +  ];
I don't tink we need this.

2022-06-09 20:20 UTC, SuperSandro2000 requested changes
Please move the file out of python-modules and under tools/misc or similar. python-modules directory must only contain packages that are under pythonPackages.

2022-06-09 20:35 UTC, merged