postgresql: remove 10.x
NixOS/nixpkgs pull request #167047
Opened 2022-04-03 15:47 UTC by ajs124

###### Description of changes
See commit messages.
Will go EOL (shortly) before the release of 22.11

###### Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-04-03 19:09 UTC, dasJ approved these changes

2022-04-08 01:31 UTC, mweinelt approved these changes

2022-04-08 02:01 UTC, marsam commented
IMHO I would remove it for the 22.11 release, not for 22.05.

2022-04-08 10:21 UTC, ajs124 commented
> IMHO I would remove it for the 22.11 release, not for 22.05.

Fair enough, I just want to avoid shipping an unsupported release, like we did with postgres 9.6 in 21.11.

We can just add this to 22.11 blockers, so we don't forget about it and wait a few months.

2022-05-04 06:21 UTC, ivan approved these changes

2022-05-09 14:05 UTC, davidak requested changes
Please add alias for removed package

https://nixos.org/manual/nixpkgs/stable/#submitting-changes-deprecating-packages

2022-08-01 17:31 UTC, superherointj commented
@ajs124 Please, fix the conflict. And add alias as `davidak` suggested.

2022-08-01 23:46 UTC, superherointj approved these changes

2022-08-01 23:47 UTC, superherointj commented
@davidak Do you approve now?

2022-08-02 10:38 UTC, ajs124 commented
@superherointj @marsam, _the maintainer of this package_, requested we keep this around until support actually ends. So whether @davidak approves or not doesn't really matter IMO.

2022-08-15 12:13 UTC, vcunat commented
I read it more like this change shouldn't get into 22.05, but merging this PR won't do that anymore.

2022-10-07 02:32 UTC, marsam approved these changes
LGTM. Thank you!

2022-10-07 02:32 UTC, merged