python3Packages.twisted: Patch HTTP request smuggling issue
NixOS/nixpkgs pull request #167415
Opened 2022-04-05 21:06 UTC by mweinelt

Fixes HTTP request smuggling in HTTP/1.1 server and proxy
implementation caused by insufficient validation of HTTP request headers.

Fixes: CVE-20222-24801

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-04-07 20:05 UTC, risicle requested changes
Note the conditional `patchPhase` means the build only tries to apply this on non-linux, where it appears to not apply due to missing `src/twisted/web/newsfragments` files.

2022-04-07 20:11 UTC, mweinelt commented
Yeah, I noticed this as well in #167558. Too tired to look into this further right now.

2022-04-08 21:41 UTC, risicle approved these changes
Looks quite sensible - the change to the actual code is relatively small.

Got the tests working just enough to ensure the newly added tests and changed tests all pass on nixos x86_64 & macos 10.15

2022-04-08 21:42 UTC, risicle commented
(also built `txtorcon` `treq` `txamqp` `txaio` `txrequests` `magic-wormhole` `scrapy` `cassandra-driver` `klein` `thrift` on nixos x86_64 & macos 10.15)

2022-04-12 18:01 UTC, merged