Document interaction between `networking.useNetworkd` and `systemd.networkd.enable`
NixOS/nixpkgs pull request #167871
Opened 2022-04-08 13:10 UTC by asymmetric

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-04-08 18:13 UTC, dasJ requested changes

2022-04-08 18:13 UTC, dasJ commented on nixos/modules/system/boot/networkd.nix
> +        This also enables <option>systemd.networkd</option>.
```suggestion
        This also sets <option>systemd.networkd.enable</option>.
```

2022-04-09 13:01 UTC, asymmetric commented
I decided to do it like it's done in [other](https://github.com/NixOS/nixpkgs/tree/aea844573e114442b5f35acc209f4e10d67e0698/nixos/modules/services/backup/tsm.nix#L14) [places](https://github.com/NixOS/nixpkgs/tree/aea844573e114442b5f35acc209f4e10d67e0698/nixos/modules/programs/turbovnc.nix#L22)

2022-12-02 14:48 UTC, ncfavier requested changes

2022-12-02 14:48 UTC, ncfavier commented on nixos/modules/system/boot/networkd.nix
> +        This also enables <option>systemd.networkd.enable</option>.
```suggestion
        This also enables {option}`systemd.networkd.enable`.
```

2022-12-03 09:52 UTC, ncfavier approved these changes

2022-12-03 09:53 UTC, ncfavier commented
Please remove trailing whitespace

2022-12-03 14:00 UTC, ncfavier commented
Please fix typos in the commit message

2022-12-04 15:19 UTC, asymmetric commented
Eagled eyes! Done.

2022-12-04 15:24 UTC, merged