storm: switch to python3
NixOS/nixpkgs pull request #169669
Opened 2022-04-22 01:39 UTC by armeenm

###### Description of changes
Basic binary testing works okay, but it would be nice if someone could test more thoroughly. Unfortunately, it seems the maintainers are AWOL: https://github.com/NixOS/nixpkgs/pull/165376.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.05 Release Notes (or backporting 21.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2205-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-04-22 12:54 UTC, gador commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 169669` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>storm</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
storm:
<details>

got build log for '/nix/store/k07i6bx66q4pkl0kxchwmmicn5sm7bh1-apache-storm-2.3.0' from 'daemon'
When evaluating attribute ‘storm’:
warning: fixup-phase
`fixupPhase` should not be overridden, use `postFixup` instead.

Near pkgs/servers/computing/storm/default.nix:30:3:

```
   |
30 |   fixupPhase = ''
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/fixup-phase.md
</details>
</details>

2022-05-09 07:18 UTC, davidak commented
Result of `nixpkgs-review pr 169669` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>storm</li>
  </ul>
</details>

2022-05-09 07:23 UTC, davidak commented
This does not look too well...

```
[nix-shell:~/.cache/nixpkgs-review/pr-169669]$ results/storm/bin/storm --version
Traceback (most recent call last):
  File "/home/davidak/.cache/nixpkgs-review/pr-169669/results/storm/bin/storm.py", line 1493, in <module>
    main()
  File "/home/davidak/.cache/nixpkgs-review/pr-169669/results/storm/bin/storm.py", line 1489, in main
    raw_args.func(raw_args)
AttributeError: 'Namespace' object has no attribute 'func'
```

```
[nix-shell:~/.cache/nixpkgs-review/pr-169669]$ results/storm/bin/storm version
Traceback (most recent call last):
  File "/home/davidak/.cache/nixpkgs-review/pr-169669/results/storm/bin/storm.py", line 1493, in <module>
    main()
  File "/home/davidak/.cache/nixpkgs-review/pr-169669/results/storm/bin/storm.py", line 1489, in main
    raw_args.func(raw_args)
  File "/home/davidak/.cache/nixpkgs-review/pr-169669/results/storm/bin/storm.py", line 1458, in version
    exec_storm_class(
  File "/home/davidak/.cache/nixpkgs-review/pr-169669/results/storm/bin/storm.py", line 236, in exec_storm_class
    storm_log_dir = confvalue("storm.log.dir", storm_config_opts=storm_config_opts,
  File "/home/davidak/.cache/nixpkgs-review/pr-169669/results/storm/bin/storm.py", line 90, in confvalue
    output = subprocess.Popen(command, stdout=subprocess.PIPE).communicate()[0]
  File "/nix/store/01kia41csjia67pry1rv828i9pvnnqfq-python3-3.9.12/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/nix/store/01kia41csjia67pry1rv828i9pvnnqfq-python3-3.9.12/lib/python3.9/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'java'
```

These issues should be fixed first before touching it again.

2022-05-09 07:23 UTC, davidak requested changes
does not work

2024-12-18 16:15 UTC, wegank commented
Done in https://github.com/NixOS/nixpkgs/pull/305407.

2024-12-18 16:15 UTC, closed without merging