invidious: unstable-2022-05-11 -> unstable-2022-06-04
NixOS/nixpkgs pull request #176392
Opened 2022-06-05 12:51 UTC by schnusch

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-07-11 17:53 UTC, applePrincess commented
Result of `nixpkgs-review pr 176392` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>invidious</li>
  </ul>
</details>

2022-07-11 17:53 UTC, applePrincess approved these changes

2022-07-11 17:58 UTC, applePrincess commented
![screenshot](https://user-images.githubusercontent.com/17154507/178327737-4146547d-b5dd-4675-9d19-235bda423e58.png)

Change looks good to me. ofborg is complaining about cosmopolitan team which is completely unrelated to this PR.

2022-07-11 19:30 UTC, infinisil requested changes

2022-07-11 19:30 UTC, infinisil commented on pkgs/servers/invidious/update.sh
> +videojs_new_sha256=$(nix --extra-experimental-features nix-command hash path --type sha256 --base32 "$git_dir/assets/videojs")
```suggestion
videojs_new_sha256=$(nix-hash --type sha256 --base32 "$git_dir/assets/videojs")
```

Let's use stable commands when possible

2022-07-12 00:13 UTC, infinisil approved these changes

2022-07-12 00:13 UTC, merged