hedgedoc: 1.9.0 -> 1.9.3
NixOS/nixpkgs pull request #178129
Opened 2022-06-18 10:33 UTC by drupol

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-06-18 15:18 UTC, drupol commented
@WilliButz Could you help on this? I'm unable to build this thing locally.

2022-06-18 17:35 UTC, drupol commented
@GrahamcOfBorg build hedgedoc

2022-07-07 09:50 UTC, drupol commented
@GrahamcOfBorg build hedgedoc

2022-07-07 10:17 UTC, drupol commented
@GrahamcOfBorg build hedgedoc

2022-07-19 15:41 UTC, drupol commented
@GrahamcOfBorg build hedgedoc

2022-07-19 16:31 UTC, winterqt requested changes
Please edit the message of your first commit to follow the commit name guidelines, i.e. `hedgedoc: add missing dependency to update script` or similar.

2022-07-20 07:58 UTC, Minion3665 requested changes
Unfortunately that commit message still doesn't quite work as it has a period at the end. [Please read the commit message guidelines for more info](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes)
> For consistency, there should not be a period at the end of the commit message's summary line (the first line of the commit message).

2022-07-20 08:00 UTC, drupol commented
Fixed.

2022-07-20 16:44 UTC, winterqt requested changes
Can you please drop the capital on the first word in the commit message (`A` -> `a`)? Thanks!

2022-07-20 16:53 UTC, drupol commented
Fixed

2022-07-21 09:54 UTC, merged

2022-07-23 22:22 UTC, SuperSandro2000 commented
This PR wasn't tested on a real system, right? The build instructions changed and the editor cannot be loaded after this update. Going to fix it myself.

2022-07-23 22:37 UTC, drupol commented
I locally tested the thing, everything seems right at first sight. Today when deploying in production. We noticed that there was an issue. I asked in the hedgedoc matrix and our build procedure is wrong. We have to use yarn instead of npm. I tried to do it, but I have the same issue locally. Help is very welcome at https://github.com/NixOS/nixpkgs/pull/182607

2022-07-23 22:39 UTC, winterqt commented
> We have to use yarn instead of npm.

@drupol [We are using yarn](https://github.com/NixOS/nixpkgs/blob/2d372784634e224c5a629d80a19705af655fbc7d/pkgs/servers/web-apps/hedgedoc/default.nix#L34), so not sure what they meant by this.

2022-07-23 22:41 UTC, drupol commented
> > We have to use yarn instead of npm.
> 
> @drupol [We are using yarn](https://github.com/NixOS/nixpkgs/blob/2d372784634e224c5a629d80a19705af655fbc7d/pkgs/servers/web-apps/hedgedoc/default.nix#L34), so not sure what they meant by this.

The build phase uses npm commands.

2022-07-23 23:11 UTC, SuperSandro2000 commented
> The build phase uses npm commands.

`npm build` is an alias to `npm run build` which is the same for `yarn build` and `yarn run build`. Also building the sqlite3 extension is also the same. Something is wrong with building hedgedoc itself or webpack.

2022-07-23 23:24 UTC, SuperSandro2000 commented
Our hedgedoc includes this file which upstream does not. Something with our vendoring is wrong.

webpack:///node_modules/js-yaml/dist/js-yaml-exposed.mjs

2022-07-24 00:42 UTC, SuperSandro2000 commented
fixed in #182643