etesync-dav fix missing dependencies
NixOS/nixpkgs pull request #178402
Opened 2022-06-21 05:19 UTC by jasom

setuptools and pysocks are both needed for this to work

Fixes #178385

###### Description of changes

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-07-12 04:22 UTC, mfossen commented
LGTM, tested on NixOS unstable.

2022-07-13 12:25 UTC, alapshin commented
This works for me on NixOS unstable.

We also have https://github.com/NixOS/nixpkgs/pull/178358 that addresses same problems

2022-08-18 08:23 UTC, thyol commented
##### Reviewed points

- [x] package build on x86_64
- [x] executables tested on x86_64

2022-09-14 15:04 UTC, thyol commented
@ofborg eval

2022-10-02 13:11 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/1228

2022-10-02 17:08 UTC, SuperSandro2000 requested changes

2022-10-02 17:08 UTC, SuperSandro2000 commented on pkgs/applications/misc/etesync-dav/default.nix
> +        checkPhase = ":";
```suggestion
        doCheck = false;
```

2022-10-08 12:09 UTC, thyol commented
@jasom A patch for the proposed changes. d3d0dad0f648caa59377fd3bca9d7cfad2949ad6

@SuperSandro2000 Under which circumstance should we update the python werkzeug package for everybody?

2022-10-09 10:11 UTC, SuperSandro2000 commented
Werkzeug is already at version 2.2.2, so that shouldn't be a problem.

@ofborg eval

2022-10-20 12:27 UTC, thyol commented
This is at the moment broken because of https://github.com/etesync/etebase-py/issues/38

2023-03-16 22:55 UTC, Alch-Emi commented
The mentioned issue has since been closed, is it possible to move forward with this?  I'd do it myself, but I'm struggling to get my dev environment set up for working on the main `nixpkgs` repo ;-;

2023-03-17 13:00 UTC, closed without merging