nixos/matrix-synapse: update docs
NixOS/nixpkgs pull request #178858
Opened 2022-06-24 10:47 UTC by Ma27

###### Description of changes
* Update attribute names in code examples (* -> settings.*).
* Demonstrate how to pass the ACME certs to synapse rather than using
  self-signed certificates.
* Update values for `/.well-known/matrix/{client,server}`:
  * By default you only declare `m.homeserver` and `m.identity_server`[1].
  * The server now uses the default federation port `8448`. Also added a
    note that `/server` is probably not necessary if `server_name` is
    equal to the domain. `8448` also does TLS properly because the ACME
    certs are used.
* Use `nix-shell -p` rather than `nix run` because the example won't
  work with the current default Nix.
* Update config values for `element-web`.
* Fix link to `element-web` security considerations.

[1] https://spec.matrix.org/latest/client-server-api/#getwell-knownmatrixclient

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-06-24 11:42 UTC, mweinelt commented
Synapse has a new config documentation that we should reference in the settings option. 
https://matrix-org.github.io/synapse/latest/usage/configuration/config_documentation.html

2022-06-24 14:14 UTC, dali99 commented
Do note that upstream recommends running everything through a reverse proxy https://matrix-org.github.io/synapse/latest/reverse_proxy.html with something like nginx doing the SSL-termination for both federation and client

2022-06-24 14:15 UTC, SuperSandro2000 reviewed
Can we convert the doc to markdown?

2022-06-24 14:15 UTC, SuperSandro2000 commented on nixos/modules/services/matrix/synapse.xml
> +  <link linkend="opt-networking.firewall.allowedTCPPorts">networking.firewall.allowedTCPPorts</link> = [ 80 443 8448 ];
Isn't it pretty common to use 443 and a reverse proxy? I think we should propose that in the docs.

2022-06-25 22:24 UTC, Ma27 commented
Updated accordingly.

Also demonstrated how to not store the registration secret in the store and decided to use callout lists to explain parts of the synapse expression.

2022-06-25 23:03 UTC, dali99 commented on nixos/modules/services/matrix/synapse.xml
> +     This is usually needed for homeserver discovery (from e.g. another server).
The biggest deal here is to enable logging in with matrix ids. it's used by clients, not by other servers

2022-06-25 23:05 UTC, dali99 commented on nixos/modules/services/matrix/synapse.xml
> +     here, see also the <link linkend='ex-matrix-synapse-rev-default'>section about Element</link>.
Maybe add that this is for security reasons, CORS headers require different domains for proper protection

2022-06-25 23:06 UTC, dali99 commented on nixos/modules/services/matrix/synapse.xml
> +     here, see also the <link linkend='ex-matrix-synapse-rev-default'>section about Element</link>.
Oh you did never mind

2022-06-28 09:49 UTC, Ma27 commented
ping @dali99

2022-06-28 11:05 UTC, D4ndellion requested changes
Looks good for a base configuration!

Only thing is that you should also proxy `/_synapse/client` since it is used for things like password resets and SSO

2022-07-04 12:31 UTC, dali99 approved these changes

2022-07-04 14:56 UTC, merged