topgrade: fix build on darwin
NixOS/nixpkgs pull request #179880
Opened 2022-07-02 08:53 UTC by XYenon

###### Description of changes

Fix [topgrade](https://github.com/r-darwish/topgrade) on darwin by downgrade the `notify-rust` crate version.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-07-04 11:26 UTC, SuperSandro2000 requested changes

2022-07-04 11:26 UTC, SuperSandro2000 commented on pkgs/tools/misc/topgrade/default.nix
> +  cargoPatches = lib.optionals stdenv.isDarwin [ ./darwin-cargo-lock.patch ];
Please make this patch unconditional. Also we should upstream this rather than vendoring it.

2022-07-04 11:26 UTC, SuperSandro2000 commented on pkgs/tools/misc/topgrade/default.nix
> +    else "sha256-otn0XvZ0wufD+4mCGSM0hevKM+wWSvFVCKtTu/5m1uA=";
When we make the patch not conditional we don't need this. This is also ugly to update.

2022-07-04 11:26 UTC, SuperSandro2000 commented on pkgs/tools/misc/topgrade/default.nix
> +    maintainers = with maintainers; [ xyenon SuperSandro2000 ];
```suggestion
    maintainers = with maintainers; [ SuperSandro2000 xyenon ];
```

2022-07-05 12:18 UTC, merged

2022-07-05 13:06 UTC, XYenon commented
> Can you please try to upstream this so that we can drop the patch with the next release?

It can be compiled correctly without nix on darwin. It looks like the real problem should be in the apple sdk provided by nix, this patch is just a trick to bypass it. So maybe it is not a good idea to commit it to the upstream.