cro-mag-rally: init at 3.0.0
NixOS/nixpkgs pull request #179978
Opened 2022-07-03 06:28 UTC by luxferresum

###### Description of changes

Add [Cro-Mag Rally](https://github.com/jorio/CroMagRally) package.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-07-03 13:32 UTC, azahi requested changes
Works fine but I have a couple of nitpicks. Also, I think you should add an XDG desktop [file](https://github.com/jorio/CroMagRally/blob/master/packaging/cromagrally.desktop) as well.

2022-07-03 13:32 UTC, azahi commented on pkgs/games/cro-mag-rally/default.nix
> +    ];
```suggestion
    license = licenses.cc-by-sa-40;
```

2022-07-03 13:32 UTC, azahi commented on pkgs/games/cro-mag-rally/default.nix
> +  ];
```suggestion
  nativeBuildInputs = [ cmake makeWrapper ];
```

2022-07-03 13:32 UTC, azahi commented on pkgs/games/cro-mag-rally/default.nix
> +  ];
```suggestion
  buildInputs = [ SDL2 ];
```

2022-07-07 12:56 UTC, luxferresum commented
> I think you should add an XDG desktop

honestly I'm not sure how to; and we dont have them for the other ex-pangeasoft-games (otto-matic, nanosaur, bugdom) either, so idk.

2022-07-07 13:28 UTC, azahi commented
Something like this (I didn't test that):
```nix
postInstall = ''
  install -Dm644 $src/packaging/cromagrally.desktop $out/share/applications/cromagrally.desktop
  install -Dm644 $src/packaging/cromagrally-desktopicon.png $out/share/pixmaps/cromagrally-desktopicon.png
'';
```

2024-02-01 23:10 UTC, h7x4 commented on pkgs/by-name/cr/cro-mag-rally/package.nix
> +    repo = pname;
I do not think the repository name that we happen to pull the source from should depend on the package name. Removing this removes the need for the `rec` statement as well. The unstable version should also include the last published version: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-naming

```suggestion
stdenv.mkDerivation {
  pname = "CroMagRally";
  version = "3.0.0-unstable-2023-05-21";

  src = fetchFromGitHub {
    owner = "jorio";
    repo = "CroMagRally";
```

2024-02-01 23:10 UTC, h7x4 commented on pkgs/by-name/cr/cro-mag-rally/package.nix
> +    mkdir -p "$out/bin"
This is handled by the `-D` in `install`

```suggestion
```

2024-02-01 23:10 UTC, h7x4 commented on pkgs/by-name/cr/cro-mag-rally/package.nix
> +    homepage = "https://github.com/jorio/CroMagRally";
There seems to be a sort of changelog here

```suggestion
    homepage = "https://github.com/jorio/CroMagRally";
    changelog = "https://github.com/jorio/CroMagRally/releases"
```

2024-02-01 23:13 UTC, h7x4 commented
(Also, feel free to ping someone or request a reviewer or two when this much time passes without interaction. This PR has been as good as ready for quite some time now, I think it's long overdue)

2024-02-02 14:31 UTC, yayayayaka reviewed
Diff looking good overall. Built and started the game. Weird game :laughing: 

With the nitpicks applied, I would be willing to boop the merge button.

2024-02-02 14:42 UTC, luxzeitlos commented
@yayayayaka I think it looks good now?

2024-02-03 12:31 UTC, azahi approved these changes

2024-02-03 12:32 UTC, merged