Rust docs: Compiling a single workspace member
NixOS/nixpkgs pull request #180322
Opened 2022-07-06 07:28 UTC by itsfarseen

Motivation: https://discourse.nixos.org/t/using-buildrustcrate-to-build-a-project-within-a-cargo-workspace/15672/10

###### Description of changes
Docs update

2023-06-29 16:34 UTC, Janik-Haag commented
Pinging @NixOS/documentation-team for review

2023-06-29 16:36 UTC, Janik-Haag requested changes
this looks good to me except for the nitpick

2023-06-29 16:36 UTC, Janik-Haag commented on doc/languages-frameworks/rust.section.md
> +
```suggestion
```
there is one new line too much

2023-06-30 15:20 UTC, fricklerhandwerk approved these changes
Should be fine modulo possibly the anchor. What's really weird is that the entire section doesn't have a complete listing documenting all the parameters. But that's not your fault.

2023-06-30 15:20 UTC, fricklerhandwerk commented on doc/languages-frameworks/rust.section.md
> +### Cargo Workspaces {#workspaces}
```suggestion
### Cargo Workspaces {#cargo-workspaces}
```


Almost sure the anchors are global. @pennae?

2023-07-18 09:50 UTC, Janik-Haag commented
Can you squash the commits so we only have one called `docs: rust compiling a single workspace member` and remove the trailing white space so we can merge this?

2025-04-01 14:24 UTC, closed without merging