graphia: 2.2 -> 3.0
NixOS/nixpkgs pull request #180745
Opened 2022-07-08 17:02 UTC by onny

###### Description of changes

update and fix build for package `graphia`

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-07-09 01:57 UTC, AndersonTorres approved these changes

2022-07-09 01:57 UTC, AndersonTorres commented on pkgs/top-level/all-packages.nix
> +  graphia = libsForQt514.callPackage ../applications/science/misc/graphia { };
```suggestion
  graphia = libsForQt514.callPackage ../applications/science/misc/graphia { 
    stdenv = gcc10Stdenv;
  };
```

2022-07-09 09:00 UTC, onny commented
Thank you @AndersonTorres, fixed it :)

2022-07-09 11:34 UTC, AndersonTorres requested changes

2022-07-09 11:34 UTC, AndersonTorres commented on pkgs/applications/science/misc/graphia/default.nix
> +# Using gcc 10 because this fails to build with gcc 11
I believe this comment should be in `all-packages.nix`.

2022-07-10 16:03 UTC, onny commented
Thank you, fixed :)

2022-07-10 20:59 UTC, AndersonTorres commented
ofborg complains with `file breakpad-sigstksz.patch not found`.

2022-07-11 11:42 UTC, onny commented
@AndersonTorres ups, fixed now :)

2022-07-12 14:01 UTC, merged