libagar: init at 1.5
NixOS/nixpkgs pull request #18070
Opened 2016-08-28 22:12 UTC by RamKromberg

###### Motivation for this change

A gui toolkit ported to make sure bsdbuild works fine. It turned out worth while since it exposed multiple issues that had to be sorted through.

Low priority but was necessary to test things out.

Note: Obviously, depends on bsdbuild getting merged first...

###### Things done

- [x] Tested using sandboxing
  ([nix.useChroot](http://nixos.org/nixos/manual/options.html#opt-nix.useChroot) on NixOS,
    or option `build-use-chroot` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Note: Seems there's a bug in i3wm with bad widget positioning. xfce shows agartest works fine.

2016-09-05 21:42 UTC, RamKromberg commented
hold off merging please... docdev failing for some reason. trying without now.

2016-09-08 14:19 UTC, joachifm commented
Why would I want to install the tests separately?

2016-09-08 14:21 UTC, joachifm commented
If you want to prevent building on Hydra, use `hydraPlatforms = []`. The priority system has to do with how collisions are resolved.

2016-09-08 15:49 UTC, RamKromberg commented
> Why would I want to install the tests separately?

agartest isn't unit tests. It's a demo. A separate binary that showcases the different widget for you to test the correct operations of the library and test out themes and the likes.

Practically speaking, It's useless if someone just wants to run a program that happens to depend on agar.

> If you want to prevent building on Hydra, use hydraPlatforms = []. The priority system has to do with how collisions are resolved.

Ops! I'll get right on it. Though, I'd much preferred if hydra would just prioritized it lower on the queue instead. There's not a whole lot of stuff out there using it (an ebook reader there... a CAD program here...) and none of those are in Nix so I wouldn't want to burden hydra needlessly but at the same time I want it to at least give it a courtesy compile if it has nothing better to do :D

2016-09-17 15:59 UTC, RamKromberg commented
Switched from _groff_ to _mandoc_. _libagar.devdoc_ rendered with readable and good quality docs by both _man-db_'s and _mandoc_'s _man_. Also, ```nix-build nixos/release.nix --attr manual --show-trace``` & ```nix-build ./pkgs/top-level/release.nix --attr tarball --show-trace``` run without error as well.

2016-09-19 00:26 UTC, groxxda commented on pkgs/development/libraries/libagar/default.nix
> +  version = srcs.version;
`inherit (srcs) version src` looks cleaner. Then you could also inline the `import`

2016-09-19 00:26 UTC, groxxda commented on pkgs/development/libraries/libagar/default.nix
> +  hydraPlatforms = [];
IMHO you should remove this if it does not take too much time

2016-09-19 00:28 UTC, groxxda commented on pkgs/development/libraries/libagar/default.nix
> +    description = "A cross-platform GUI toolkit.";
No dot at the end of description

2016-09-19 00:32 UTC, groxxda requested changes
The comments are also valid for the tests file.
Another option to two separate derivations would be to move the tests to a separate output (have a look at multiple outputs documentation), but I believe that only makes sense if their build script supports building everything in one go

2016-09-19 03:55 UTC, RamKromberg commented on pkgs/development/libraries/libagar/default.nix
> +  version = srcs.version;
k

2016-09-19 03:56 UTC, RamKromberg commented on pkgs/development/libraries/libagar/default.nix
> +  hydraPlatforms = [];
more then happy to oblige :)

2016-09-19 03:57 UTC, RamKromberg commented on pkgs/development/libraries/libagar/default.nix
> +    description = "A cross-platform GUI toolkit.";
sorry keep forgetting about those pesky dots... Someone really should submit a nixfmt to the review process ;)

2016-10-01 11:42 UTC, merged

2016-10-01 11:42 UTC, Mic92 commented
Thanks!

2016-10-01 23:38 UTC, RamKromberg commented
Thanks you :)