link to wiki's Sway entry, nontrivial info there
NixOS/nixpkgs pull request #181436
Opened 2022-07-14 05:29 UTC by aaronchall

###### Description of changes
Link to wiki's Sway entry as this information in the manual is otherwise not very helpful at accomplishing what it implies is a trivial modification. This link would have saved me quite a lot of time.

###### Things done

Literally nothing as it's one line of doc.

2022-07-15 09:39 UTC, teutat3s approved these changes

2022-07-18 04:56 UTC, winterqt requested changes
Please run `nixos/doc/md-to-db.sh`.

2022-07-21 23:35 UTC, aaronchall commented
> Please run `nixos/doc/md-to-db.sh`.
Is that to me? If not who to? If to me... I'll try! :)

2022-07-22 00:06 UTC, winterqt commented
@aaronchall Yup, that was to you. Run it, squash, and force push. That's why the manual build is failing -- you have to update both the source Markdown files and the generated DocBook files.

2024-10-17 16:46 UTC, teutat3s approved these changes
```
❯ nix-build nixos/release.nix -A manual.x86_64-linux
```
builds fine here.

2024-10-17 17:26 UTC, mweinelt requested changes

2024-10-17 17:26 UTC, mweinelt commented on nixos/doc/manual/configuration/wayland.chapter.md
> +and related options (see the [wiki's Sway entry](https://nixos.wiki/wiki/Sway)).
Not that wiki.

2024-10-21 18:26 UTC, closed without merging