lensm: init at 0.0.2
NixOS/nixpkgs pull request #182296
Opened 2022-07-21 02:19 UTC by viraptor

###### Description of changes

Include `lensm` package. See https://github.com/loov/lensm for project details.
Darwin compilation should work, but I don't know how to resolve it, so marked broken for now.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-07-21 02:52 UTC, winterqt requested changes
Please add `stdenv` to the arguments set, so `meta` evaluates.

2022-07-21 05:41 UTC, viraptor commented
Thanks, "I'll just add this small thing before pushing" strikes again :D

2022-07-21 15:24 UTC, winterqt requested changes

2022-07-21 22:46 UTC, viraptor commented on pkgs/development/tools/lensm/default.nix
> +    broken = stdenv.isDarwin; # unknown compilation issues
Added, thanks.

2022-07-23 21:06 UTC, winterqt commented
Did you build for Darwin with the sandbox enabled or disabled? I have it enabled, and I can't even get to the error you got about CoreFoundation since an "internal error in Security.framework" is getting in my way when fetching the dependencies 😕

2022-07-23 23:04 UTC, viraptor commented
Ah, that's weird. I didn't even get to checking with sandboxing. Tried without and the built seems to ignore most frameworks (foundation, metal, etc.)

2023-12-23 12:10 UTC, katexochen commented
Hey @viraptor, any plans to continue work on this? Otherwise I'd be interested in picking this up. Is there anything missing beside the darwin failure?

2024-10-29 08:16 UTC, closed without merging