mpd: fix 0.23.8 on darwin
NixOS/nixpkgs pull request #182299
Opened 2022-07-21 03:16 UTC by ylh

- 0.23.8 includes https://github.com/MusicPlayerDaemon/MPD/commit/c975d8b94316c86bf5950ed3abeba394e1263677
- said change fixes deprecation warnings introduced in the 12.0 sdk, using definitions from the 12.0 sdk
- nixpkgs uses 10.12 and 11.0, neither of which are the 12.0 sdk
- this will gracefully degrade into a no-op when that changes

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-07-22 02:21 UTC, smancill requested changes
Please rebase and push a single commit, as explained in the docs: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-hotfixing-pull-requests

2022-07-22 13:13 UTC, ylh commented
✓

2022-07-22 16:14 UTC, smancill commented
Result of `nixpkgs-review pr 182299` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>mpd</li>
    <li>mpd-small</li>
  </ul>
</details>

2022-07-22 16:20 UTC, smancill commented
It builds for me on Darwin, but I cannot approve since I am a bit lost about `stdenv.hostPlatform.darwinSdkVersion` (if it should be `targetPlatform` or `hostPlatform`), since no other package seems to use it.

2022-07-22 17:37 UTC, ylh commented
`targetPlatform` seems to be appropriate going by https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/xcbuild/wrapper.nix

2022-07-23 14:00 UTC, merged

2022-08-16 11:04 UTC, bvlj commented
Would it be possible to backport this patch to `nixpkgs-22.05-darwin`?
Right now the mpd package is broken in that branch