[DRAFT] python310Packages.doit: 0.35.0 -> 0.36.0
NixOS/nixpkgs pull request #183087
Opened 2022-07-27 10:20 UTC by onny

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-07-28 22:52 UTC, risicle commented on pkgs/development/python-modules/doit/default.nix
> +    pytest = callPackage ./tests.nix { };
Suggest using the self-override pattern discussed for `bsuite` rather than the slightly odd dummy-package approach.

2022-07-29 18:26 UTC, SuperSandro2000 commented on pkgs/development/python-modules/configclass/default.nix
> +  buildInputs = [ mergedict ];
This either needs to be nativeBuildInputs or propagatedBuildInputs

2022-07-29 18:27 UTC, SuperSandro2000 commented on pkgs/development/python-modules/doit-py/default.nix
> +  buildInputs = [
```suggestion
  propagatedBuildInputs = [
```

2022-07-29 18:27 UTC, SuperSandro2000 commented on pkgs/development/python-modules/doit-py/default.nix
> +
```suggestion
```
we don't want to run linters

2022-07-29 18:27 UTC, SuperSandro2000 commented on pkgs/development/python-modules/doit/tests.nix
> +    pyflakes
```suggestion
```

2022-08-05 12:00 UTC, SuperSandro2000 requested changes
Can you please rebase on master? The doit is there already and causes ofborg to fail.

2022-08-05 12:31 UTC, onny commented
@SuperSandro2000 rebased

2022-08-05 18:29 UTC, SuperSandro2000 requested changes
Can you please locally test your changes?

2022-08-05 18:29 UTC, SuperSandro2000 commented on pkgs/development/python-modules/doit/default.nix
> +, importlib-metadata
```suggestion
```

2022-08-07 07:27 UTC, onny commented
@SuperSandro2000 Oh sorry somehow missed that. Should be fixed now :)

2022-08-07 09:29 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 183087` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package marked as broken and skipped:
</summary>
<ul>
<li>zerobin</li>
</ul>
</details>
<details>
<summary>
10 packages built:
</summary>
<ul>
<li>doit (python310Packages.doit)</li>
<li>python310Packages.Nikola</li>
<li>python310Packages.configclass</li>
<li>python310Packages.doit-py</li>
<li>python310Packages.mergedict</li>
<li>python39Packages.Nikola</li>
<li>python39Packages.configclass</li>
<li>python39Packages.doit</li>
<li>python39Packages.doit-py</li>
<li>python39Packages.mergedict</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python39Packages.doit:
<details>

got build log for '/nix/store/6iq2dczfl479n7101ib8sanw9s23wr09-python3.9-doit-0.36.0' from 'daemon'
When evaluating attribute ‘python39Packages.doit’:
warning: duplicate-check-inputs
Dependencies listed in `propagatedBuildInputs` should not be repeated in `checkInputs`.

Detected duplicates:

- python3.9-cloudpickle-2.1.0

Near pkgs/development/python-modules/doit/default.nix:37:3:

```
   |
37 |   checkInputs = [
   |   ^
```

Near pkgs/development/python-modules/doit/default.nix:30:3:

```
   |
30 |   propagatedBuildInputs = [
   |   ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/duplicate-check-inputs.md
</details>
</details>

2022-08-07 09:29 UTC, SuperSandro2000 reviewed
otherwise LGTM

2022-08-07 09:29 UTC, SuperSandro2000 commented on pkgs/development/python-modules/doit/default.nix
> +    cloudpickle
```suggestion
```
duplicated with propagatedBuildInputs

2022-08-07 09:46 UTC, onny commented
Good catch @SuperSandro2000, fixed it :)

2022-08-13 02:41 UTC, merged

2022-08-13 17:01 UTC, SuperSandro2000 commented on pkgs/development/python-modules/doit/default.nix
> +    pyflakes
We do not want to run linters in checkPhase