volatility: 2.6.1 -> unstable-2020-12-12, fix the build
NixOS/nixpkgs pull request #184782
Opened 2022-08-02 09:25 UTC by emilytrau

###### Description of changes

Volatility is a memory forensics tool. Although it has been superseded by volatility3, volatility2 still sees regular use. As python2 support is dropping from its dependencies, this will need further future maintenance  as long as the tool is yet to be obsoleted. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-08-07 14:46 UTC, pbsds commented
Result of `nixpkgs-review pr 184782` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>volatility</li>
  </ul>
</details>

2022-08-07 14:46 UTC, pbsds requested changes

2022-08-07 14:46 UTC, pbsds commented on pkgs/tools/security/volatility/default.nix
>    doCheck = false;
```suggestion
  doCheck = false;
  pythonImportsCheck = [ "volatility" ];
```

2022-08-07 14:46 UTC, pbsds commented on pkgs/development/python2-modules/openpyxl/default.nix
> +  doCheck = false;
```suggestion
  doCheck = false;
  pythonImportsCheck = [ "openpyxl" ];
```

2022-08-16 22:34 UTC, pbsds approved these changes

2022-10-02 11:40 UTC, JJJollyjim commented
+1, volatility2 is still useful, tested this PR and it works well.

2022-10-08 07:13 UTC, erdnaxe commented
Result of `nixpkgs-review pr 184782` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>volatility</li>
  </ul>
</details>

---

Volatility2 is still useful for forensic security. IIRC Volatility3 has a different feature set.

2023-03-02 13:18 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/854

2023-03-03 17:42 UTC, SuperSandro2000 requested changes
python2 is EOL. Has the tool been ported to python3?

2023-03-03 17:42 UTC, SuperSandro2000 commented on pkgs/development/python2-modules/openpyxl/default.nix
> +  checkInputs = [ pytest ];
Please use pytestCheckHook

2023-03-03 17:42 UTC, SuperSandro2000 commented on pkgs/development/python2-modules/openpyxl/default.nix
> +  doCheck = false;
Why not download from bitbucket instead?

2023-03-04 12:45 UTC, JJJollyjim commented
No, Volatility only supports Python 2. Volatility3 was meant to be the python3 port but it is less useful and less popular.

2023-03-13 22:12 UTC, mweinelt commented
We are well past the time, where we support adding new python2 packages. In fact at this point we only support python2 as a build time dependency, not as a runtime dependency.

2023-03-13 22:12 UTC, closed without merging