mysql-shell: resolve locale-setting error
NixOS/nixpkgs pull request #185123
Opened 2022-08-04 10:55 UTC by aaronjheng

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-09-23 03:52 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/1205

2022-09-23 16:58 UTC, SuperSandro2000 requested changes
But why is this required? This variable is set on NixOS and on other systems needs to be managed by something like home-manager.

2022-09-23 16:58 UTC, SuperSandro2000 commented on pkgs/development/tools/mysql-shell/default.nix
> +    wrapProgram $out/bin/mysqlsh --set PYTHONPATH "${pythonPath}" \
```suggestion
    wrapProgram $out/bin/mysqlsh \
      --set PYTHONPATH "${pythonPath}" \
```

2022-09-24 02:20 UTC, aaronjheng commented
I'm using nix on Ubuntu. Runing mysql-shell without `LOCALE_ARCHIVE` set, I get the following warning:
```
Cannot set LC_ALL to locale en_US.UTF-8: No such file or directory
```

2022-10-03 19:44 UTC, SuperSandro2000 commented
Then this must be fixed in your installation because this problem will occur with way more packages.

2022-10-03 19:44 UTC, closed without merging

2022-10-07 03:35 UTC, aaronjheng commented
The following packages use the same approach:
* mixxx
* sublimetext3-bin
* sublimetext4-bin
* cplex
* sublime-merge
* guake
* fluxboxlauncher

@SuperSandro2000