zee: init at `0.3.2`
NixOS/nixpkgs pull request #185449
Opened 2022-08-06 18:29 UTC by booklearner

###### Description of changes

Add the `zee` editor to nixpkgs, https://github.com/zee-editor/zee

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

<img width="597" alt="Screen Shot 2022-08-06 at 2 28 13 PM" src="https://user-images.githubusercontent.com/103979114/183261476-62fd6033-d215-4de5-921a-d2cdb184a9de.png">

2022-08-07 14:15 UTC, figsoda requested changes
ofborg build is failing because the [build script](https://github.com/zee-editor/zee/blob/v0.3.2/zee/build.rs) is trying to [access the internet](https://github.com/zee-editor/zee/blob/v0.3.2/zee-grammar/src/builder.rs#L95), which should be able to be avoided by [setting `ZEE_DISABLE_GRAMMAR_BUILD`](https://github.com/zee-editor/zee/blob/v0.3.2/zee/build.rs#L8)

2022-08-07 14:15 UTC, figsoda commented on pkgs/applications/editors/zee/default.nix
> +{ lib, stdenv, fetchFromGitHub, rustPlatform, openssl, pkg-config, Security }:
> [Arguments should be listed in the order they are used, with the exception of lib, which always goes first.](https://nixos.org/manual/nixpkgs/stable/#sec-syntax)

```suggestion
{ lib, rustPlatform, fetchFromGitHub, pkg-config, openssl, stdenv, Security }:
```

2022-08-07 14:15 UTC, figsoda commented on pkgs/applications/editors/zee/default.nix
> +    rev = "107347474c6e63a6be6e8b1f4415f3270a92b2dc";
tag name is always preferred when it's available
```suggestion
    rev = "v${version}";
```

2022-08-07 14:24 UTC, figsoda commented
having [revision_changed}(https://github.com/zee-editor/zee/blob/v0.3.2/zee-grammar/src/builder.rs#L94) as false would also skip the git fetch, i think that explains why it builds on darwin but not linux and that should be a better fix then what I said earlier

2022-08-07 16:20 UTC, booklearner commented
Gotcha, thank you @figsoda! I'll push the requested changes up shortly.

2022-08-07 22:41 UTC, booklearner commented
I've actually disabled installing grammars at build time, since this is something that takes into account a user configuration (choosing which grammars to install) I think it's preferable to leave that up to the user

i.e. https://github.com/zee-editor/zee/tree/v0.3.2#syntax-highlighting
```
zee --build
```

2022-08-08 12:57 UTC, figsoda commented
Result of `nixpkgs-review pr 185449` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>zee</li>
  </ul>
</details>

2022-08-08 12:57 UTC, figsoda approved these changes

2022-08-08 12:57 UTC, merged