dmlive: init at unstable-2022-06-05
NixOS/nixpkgs pull request #186398
Opened 2022-08-13 07:42 UTC by NickCao

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-08-24 23:38 UTC, jian-lin requested changes
LGTM

2022-08-24 23:38 UTC, jian-lin commented on pkgs/applications/video/dmlive/default.nix
> +    wrapProgram "$out/bin/dmlive" --prefix PATH : "${lib.makeBinPath [ mpv ffmpeg ]}"
`nodejs` is also needed, see https://github.com/THMonster/dmlive/blob/fd4fa1859f05350658db598a50d29f59d22b55a1/src/utils/mod.rs#L32

2022-08-24 23:38 UTC, jian-lin commented on pkgs/applications/video/dmlive/default.nix
> +    description = "Tools to play live stream with danmaku";
```suggestion
    description = "A tool to play and record live streams with danmaku";
```

2022-08-24 23:38 UTC, jian-lin commented on pkgs/applications/video/dmlive/default.nix
> +  version = "unstable-2022-06-05";
new commits are available

2022-08-25 13:03 UTC, jian-lin approved these changes

2022-08-25 19:37 UTC, SuperSandro2000 commented on pkgs/applications/video/dmlive/default.nix
> +  buildInputs = [ openssl ];
Can you try to fix the darwin build by adding ``Security`` framework for darwin only?

2022-08-26 20:44 UTC, merged