rapidjson: add gtest to buildInputs, fix cross compilation, add valgr…
NixOS/nixpkgs pull request #186559
Opened 2022-08-14 02:49 UTC by NickCao

…ind to checkInputs, remove custom checkPhase

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] riscv64-linux (cross)
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-08-14 04:48 UTC, dotlambda commented
Gtest isn't needed at runtime, so this doesn't make sense to me. Can't we just set `doCheck = false` when cross compiling?
I remember not including valgrind for some reason. Maybe some tests are flaky?

2022-08-14 04:51 UTC, NickCao commented
What's broken is actually the notion of `checkInputs`, for now `checkInputs` are added to `nativeBuildInputs`, but `gtest` should be in `buildInputs`, anyway as there's no reference to `gtest` in the final output, there would be no `gtest` in the closure, adding `gtest` to `buildInputs` would do no harm. And I ran several native builds, the tests all passed.

2022-08-14 16:18 UTC, dotlambda commented on pkgs/development/libraries/rapidjson/default.nix
> +  buildInputs = [ gtest ];
```suggestion

  buildInputs = lib.optionals doCheck [
    gtest
  ];
```

2022-08-14 16:18 UTC, dotlambda commented on pkgs/development/libraries/rapidjson/default.nix
> +  checkInputs = [ valgrind ];
```suggestion

  checkInputs = [
    valgrind
  ];
```

2022-08-15 01:04 UTC, NickCao commented
`rapidjson`, `pkgsStatic.rapidjson`, `pkgsCross.riscv64.rapidjson` all builds.

2023-01-23 02:54 UTC, dotlambda requested changes
You should add `gtest` to `buildInputs` again.

2023-01-23 03:02 UTC, NickCao commented
rechecked that rapidjson, pkgsStatic.rapidjson, pkgsCross.riscv64.rapidjson all builds.

2023-01-23 03:06 UTC, NickCao commented
@ofborg build rapidjson  pkgsStatic.rapidjson

2023-01-25 02:04 UTC, NickCao commented
@dotlambda ping

2023-01-27 00:24 UTC, merged