srb2, srb2kart: refactor
NixOS/nixpkgs pull request #187320
Opened 2022-08-18 17:53 UTC by luis-caldas

###### Description of changes

Removed the WAD patches on both packages, a simple wrap using the argument `SRB2WADDIR` solved the problem.
Added desktop items to both packages.
Moved the data files into their own derivation.
Data files from srb2 were not from the official package, now they are and I've left an option to use the old data files.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-08-18 17:55 UTC, luis-caldas commented
@zeratax

2022-08-21 03:16 UTC, SuperSandro2000 requested changes

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +  mainName = "srb2kart";
```suggestion
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    pname = "${mainName}-data";
```suggestion
    pname = "srb2kart-data";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +  pname = mainName;
```suggestion
  pname = "srb2kart";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    icon = mainName;
```suggestion
    exec = pname;
    icon = pname;
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +  mainName = "srb2";
```suggestion
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    pname = "${mainName}-data";
```suggestion
    pname = "srb2kart-data";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +  fixVersion = builtins.replaceStrings ["."] [""] version;
```suggestion
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +  pname = mainName;
```suggestion
  pname = "srb2kart";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +  repo = "SRB2";
```suggestion
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +      url = "https://github.com/${owner}/${repo}/releases/download/${repo}_release_${version}/${repo}-v${fixVersion}-Full.zip";
```suggestion
      url = "https://github.com/STJr/SRB2/releases/download/SRB2_release_${version}/${repo}-v${lib.replaceStrings ["."] [""] version}-Full.zip";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    inherit description;
```suggestion
    description = "Sonic Robo Blast 2 is a 3D Sonic the Hedgehog fangame based on a modified version of Doom Legacy";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +
```suggestion
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    buildInputs = [ unzip ];
```suggestion

```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    pname = "${mainName}-mazmazz-data";
```suggestion
    pname = "srb2-mazmazz-data";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    buildInputs = [ p7zip ];
```suggestion
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +  mVersion = "2.2.5";
```suggestion
  mazmazzVersion = "2.2.5";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +  };
```suggestion

```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    srcs = [ mAssets.main mAssets.optional ];
```suggestion
```
This is unused if unpackPhase is bein overwritten.

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    inherit owner repo;
Please revert

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    makeWrapper
makeWrapper goes into nativeBuildInputs

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    icon = mainName;
```suggestion
    exec = "srb2";
    icon = "srb2";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +  desktopLink = makeDesktopItem rec {
```suggestion
  desktopItems = [
    (makeDesktopItem rec {
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    cp /build/source/srb2.png $out/share/icons/.
Please use relative paths.

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2/default.nix
> +    mkdir -p $out/bin $out/share $out/share/applications $out/share/pixmaps $out/share/icons
```suggestion
    mkdir -p $out/bin $out/share/applications $out/share/pixmaps $out/share/icons
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
```suggestion
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    buildInputs = [ p7zip ];
```suggestion
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +      url = "https://github.com/${owner}/${repo}/releases/download/v${version}/srb2kart-v${fixVersion}-Installer.exe";
```suggestion
      url = "https://github.com/STJr/Kart-Public/releases/download/v${version}/srb2kart-v${lib.replaceStrings ["."] [""] version}-Installer.exe";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +      7z -y x "''${src}"
```suggestion
      7z -y x "${src}"
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    makeWrapper
makeWrapper goes into nativeBUildInputs

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +  desktopLink = makeDesktopItem rec {
```suggestion
  desktopItems = [
    (makeDesktopItem rec {
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    mkdir -p $out/bin $out/share $out/share/applications $out/share/pixmaps $out/share/icons
```suggestion
    mkdir -p $out/bin $out/share/applications $out/share/pixmaps $out/share/icons
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    ln -s ${desktopLink}/share/applications/* $out/share/applications
Please use copyDesktopItems

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    cp /build/source/srb2.png $out/share/icons/srb2kart.png
Use relative paths

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    inherit description;
```suggestion
    description = "SRB2Kart is a classic styled kart racer";
```

2022-08-21 03:16 UTC, SuperSandro2000 commented on pkgs/games/srb2kart/default.nix
> +    comment = description;
```suggestion
    comment = meta.description;
```

2022-12-15 17:21 UTC, pinkcreeper100 commented
@luis-caldas are you still interested in this pr?

2022-12-20 22:42 UTC, zeratax approved these changes

2023-04-11 15:25 UTC, SuperSandro2000 commented
can you please rebase?

2023-04-12 06:11 UTC, pinkcreeper100 commented
@SuperSandro2000 the author of this pr seems to be inactive apart from on their own repos

2023-04-12 19:32 UTC, closed without merging