jtdx: init at 159
NixOS/nixpkgs pull request #188003
Opened 2022-08-23 11:14 UTC by CesarGallego

###### Description of changes

JTDX is forked from  WSJT-X, a computer  program  dedicated to amateur
radio communication using very weak signals. 

JTDX is widely used among ham-radio operators for its user friendliness and documentation. 

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

We tested the main user binary with a ham-radio device, and by proxy the rest of binaries that are used by the main binary.

2022-12-12 18:15 UTC, mattmelling commented
Result of `nixpkgs-review pr 188003` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>jtdx</li>
    <li>jtdxhamlib</li>
  </ul>
</details>

2022-12-12 18:24 UTC, mattmelling requested changes

2022-12-12 18:24 UTC, mattmelling commented on pkgs/development/libraries/jtdxhamlib/default.nix
> +    automake
will this work with autoreconfHook instead of separate autoconf/automake deps?

2022-12-12 18:24 UTC, mattmelling commented on pkgs/applications/radio/jtdx/default.nix
> +  buildInputs = [ fftw fftwFloat libusb1 qtbase qtmultimedia qtserialport boost jtdxhamlib ];
Is it absolutely necessary to use the jtdxhamlib? AIUI, this was forked due to changes in hamlib 4 - have you tried this with hamlib 3? Both hamlib3 and hamlib 4 are in nixpkgs.

2022-12-12 18:24 UTC, mattmelling commented on pkgs/applications/radio/jtdx/default.nix
> +  version = "2.2.159";
Is this a tag? Can it be used as the rev in `fetchFromGitHub` (e.g. `rev = "v${version}";`)?

2024-01-01 02:33 UTC, AndersonTorres commented
Closing as uninterested.

2024-01-01 02:33 UTC, closed without merging