pg_repack: init at 1.3.4
NixOS/nixpkgs pull request #18820
Opened 2016-09-21 17:53 UTC by danbst

###### Motivation for this change
pg_repack is a great extension for removing bloat from databases online. It supports postgresqls up to 9.5. In my case, it reduced database size from 70G to 40G without downtime.

It should be used as postgresql plugin. e.g.:
```
    services.postgresql.extraPlugins = [ pkgs.pg_repack ];
```

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] OS X
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-09-21 18:03 UTC, groxxda commented on pkgs/servers/sql/postgresql/pg_repack/default.nix
> +      inherit (postgresql.meta) plarforms;
typo: platforms

2016-09-21 18:03 UTC, groxxda commented on pkgs/servers/sql/postgresql/pg_repack/default.nix
> +    src = fetchurl {
Please use `fetchFromGitHub` if possible

2016-09-21 18:04 UTC, groxxda requested changes

2016-09-22 04:13 UTC, danbst commented on pkgs/servers/sql/postgresql/pg_repack/default.nix
> +      inherit (postgresql.meta) plarforms;
auch. Wish there would be linter for such things

2016-09-22 20:46 UTC, lethalman commented
Looks good to me, thanks.

2016-09-22 20:46 UTC, merged