Updated hugin to version 2016.2.0
NixOS/nixpkgs pull request #18831
Opened 2016-09-22 01:29 UTC by paperdigits

###### Motivation for this change

Updated hugin to the newest release.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-09-22 11:57 UTC, lsix requested changes
As for #18830 and #18832, please update your commit message.

See http://nixos.org/nixpkgs/manual/#idm140737319364512 for commit naming scheme.

2016-09-22 15:48 UTC, paperdigits commented
You're right, sorry about that, I'll fix them tonight!

On September 22, 2016 4:57:59 AM PDT, Lancelot SIX <notifications@github.com> wrote:
>lsix requested changes on this pull request.
>
>As for #18830 and #18832, please update your commit message.
>
>See http://nixos.org/nixpkgs/manual/#idm140737319364512 for commit
>naming scheme.
>
>
>
>-- 
>You are receiving this because you were mentioned.
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/pull/18831#pullrequestreview-1126263

2016-09-23 00:24 UTC, paperdigits commented
@lsix I've updated my commit message.

2016-10-02 21:39 UTC, rycee commented
Rebased into master in commit 0223ab8fa943f56ea12818087aa023decd849c71. Thanks for the contribution!

2016-10-02 21:39 UTC, closed without merging