nixos/oci-containers: wait for network before starting container
NixOS/nixpkgs pull request #188795
Opened 2022-08-29 10:01 UTC by Sohalt

Without `ìmageFile` set, the service needs to download the image from
the registry. If the network is not up in time, the service tries to
restart rapidly until it fails.

It's a bit unfortunate, because once the image is downloaded, there is no need to delay startup of the container until after the network is available. Maybe a better approach would be to increase the number of retries? Or implement manual retry logic in the `preStart` script?

###### Description of changes

Wait for `network-online.target` when `imageFile` is not set.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-08-31 18:51 UTC, ck3d requested changes

2022-08-31 18:51 UTC, ck3d commented on nixos/modules/virtualisation/oci-containers.nix
> +    after = lib.optionals (cfg.backend == "docker") [ "docker.service" "docker.socket" ] ++ lib.optionals (container.imageFile != null) [ "network-online.target" ] ++ dependsOn;
The dependency between imageFile and target is not obvious. Can you please add a comment.

2022-09-25 16:54 UTC, ck3d approved these changes
LGTM

2023-01-20 01:11 UTC, NickCao approved these changes

2023-01-20 01:11 UTC, merged