hunspell: 1.7.0 -> 1.7.1
NixOS/nixpkgs pull request #188827
Opened 2022-08-29 17:11 UTC by riceicetea

###### Description of changes

changelog:
https://github.com/hunspell/hunspell/releases/tag/v1.7.1

fixes CVE-2019-16707: https://nvd.nist.gov/vuln/detail/CVE-2019-16707
(this was previously patched in nixpkgs, now upstream fixed it)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-08-29 20:23 UTC, SuperSandro2000 requested changes
Please revert all the formatting changes. They do not follow the nixpkgs standard.

2022-08-29 20:23 UTC, SuperSandro2000 commented on pkgs/development/libraries/hunspell/default.nix
> -    (fetchpatch {
Please remove the unused fetchpatch from inputs.

2022-08-30 06:12 UTC, riceicetea commented
I am sorry. I left Alejandra on and didn't notice :/ will fix.

2022-08-30 13:38 UTC, riceicetea commented
New PR: https://github.com/NixOS/nixpkgs/pull/188972

2022-08-30 13:38 UTC, closed without merging

2022-08-30 14:39 UTC, SuperSandro2000 commented
Why did you do a new PR?

2022-08-30 15:29 UTC, riceicetea commented
Is it a big deal? It was easier to revert the changes that way.

2022-08-30 15:34 UTC, SuperSandro2000 commented
yes, in the future please force push PRs. Otherwise (review) comments might get lost and it is harder to follow the changes.