novnc: correctly install and point to `websockify`
NixOS/nixpkgs pull request #188901
Opened 2022-08-30 01:52 UTC by dwf

`utils/novnc_proxy` tries to download and run the `websockify` package in the directory where the script is located, which doesn't work because the nix store is read-only. This patches the script to point to nix-installed `websockify`.

As it's logically a separate change I separated this and ##188897 into separate PRs. I'll need to rebase this once #188897 is submitted.

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-09-26 01:43 UTC, dwf commented
@NeverBehave Any thoughts on this one?

2022-09-26 01:56 UTC, dwf commented
@AndersonTorres Similarly, you might be an appropriate second reviewer for this PR.

2022-09-29 00:56 UTC, dwf commented
@applePrincess Likewise, mind giving this a look?

2022-09-29 01:40 UTC, AndersonTorres commented
> As it's logically a separate change I separated this and #https://github.com/NixOS/nixpkgs/pull/188897 into separate PRs. I'll need to rebase this once https://github.com/NixOS/nixpkgs/pull/188897 is submitted.

Wait, are these changes somehow dependent?

2022-09-29 01:43 UTC, AndersonTorres requested changes

2022-09-29 22:59 UTC, dwf commented on pkgs/applications/networking/novnc/default.nix
> +{ lib, pkgs, stdenv, substituteAll, fetchFromGitHub }:
Done.

2022-09-29 22:59 UTC, dwf commented on pkgs/applications/networking/novnc/default.nix
> +  patches = with pkgs.python3Packages; [
Done.

2022-09-29 23:00 UTC, dwf commented
> Wait, are these changes somehow dependent?

They aren't, they're just so close by that I'm betting on a merge conflict. Maybe git will pleasantly surprise me.

2022-09-30 00:16 UTC, AndersonTorres commented
Rebase

2022-09-30 00:31 UTC, dwf commented
Done. I concatenated to the list rather than simply added an element to make it clear that the `with` statement is scoped/meant for to the first part, not sure if this is considered good style or not.

2022-10-01 01:26 UTC, AndersonTorres commented
Next time you can concentrate related commits in a single PR.

2022-10-01 01:26 UTC, merged