cemu-ti: 1.3 -> unstable-2022-06-29
NixOS/nixpkgs pull request #188939
Opened 2022-08-30 08:49 UTC by luc65r

###### Description of changes

Renamed from `cemu` to `cemu-ti`.

Fixes https://github.com/NixOS/nixpkgs/issues/188193.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-08-31 19:46 UTC, azahi requested changes

2022-08-31 19:46 UTC, azahi commented on pkgs/applications/science/math/cemu-ti/default.nix
>      license = licenses.gpl3;
While we are at it: https://discourse.nixos.org/t/lib-licenses-gpl3-co-are-now-deprecated/8206

2022-10-30 23:21 UTC, thiagokokada commented on pkgs/applications/science/math/cemu-ti/default.nix
>      license = licenses.gpl3;
```suggestion
    license = licenses.gpl3Plus;
```

2022-10-30 23:28 UTC, thiagokokada commented
Result of `nixpkgs-review pr 188939` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cemu-ti</li>
  </ul>
</details>

2022-10-30 23:28 UTC, thiagokokada approved these changes

2022-10-30 23:28 UTC, thiagokokada commented
Don't know how to actually test the program, but I ran here and it seems to works fine.

2022-10-31 00:36 UTC, merged

2022-10-31 01:07 UTC, winterqt commented
We should probably include something in the changelog about this rename/the emulator replacing it, even if nobody has depended on it in months. cc @mweinelt, thoughts?

2022-10-31 09:16 UTC, thiagokokada commented
> We should probably include something in the changelog about this rename/the emulator replacing it, even if nobody has depended on it in months. cc @mweinelt, thoughts?

Makes sense, maybe it is better to do this in #198590 though.

2022-11-08 16:38 UTC, SuperSamus commented
Should #114509 also be closed?