jq: Fix CVE-2015-8863 and CVE-2016-4074
NixOS/nixpkgs pull request #18908
Opened 2016-09-24 00:57 UTC by aneeshusa

###### Motivation for this change

Part of #18856.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] OS X
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

jq has not had a release since August 2015, so use the latest version
from git. CVE-2015-8863 has a fix committed to the current master, while
CVE-2016-4074 has not had a fix committed to master, so add a separate
patch for that.

I manually confirmed that the CVEs are fixed in the resulting binary.

2016-09-24 23:53 UTC, fpletz commented on pkgs/development/tools/jq/default.nix
> +  version = "something";
This is not a valid version.

2016-09-24 23:54 UTC, fpletz commented on pkgs/development/tools/jq/default.nix
> +  # but no release has been made since then (latest release was last year)
Why do you fetch the master? For stability it would be more useful to pick the relevant patches from master until there is a new release. You can use `fetchpatch` to avoid committing those to nixpkgs.

2016-09-24 23:54 UTC, fpletz commented on pkgs/development/tools/jq/default.nix
> +  patches = [ ./CVE-2016-4074.patch ];
Where does this patch come from?

2016-09-24 23:55 UTC, fpletz requested changes

2016-09-25 00:50 UTC, aneeshusa commented on pkgs/development/tools/jq/default.nix
> +  version = "something";
Sorry, I had pushed an old version by mistake.

2016-09-25 00:53 UTC, aneeshusa commented on pkgs/development/tools/jq/default.nix
> +  # but no release has been made since then (latest release was last year)
The latest jq release was last August, and there have been numerous changes in between. I've never been a fan of "backporting culture" and I wouldn't feel comfortable blindly extracting a patch and applying it without studying the source in depth to see more precisely what has changed.

2016-09-25 00:53 UTC, aneeshusa commented on pkgs/development/tools/jq/default.nix
> +  patches = [ ./CVE-2016-4074.patch ];
Updated to use fetchpatch.

2016-09-25 05:25 UTC, fpletz commented on pkgs/development/tools/jq/default.nix
> +  # but no release has been made since then (latest release was last year)
But yet you blindly package a development version without knowing if it is stable and safe to use? I'm also not a big fan of backporting to previous versions but sticking to released versions is good practice. If the project doesn't even do maintenance releases it's not safe to assume that it their master is always stable in my experience.

2016-09-25 05:50 UTC, aneeshusa commented on pkgs/development/tools/jq/default.nix
> +  # but no release has been made since then (latest release was last year)
In this case it seems the 1.6 release is delayed and they are recommending to use master:
- https://github.com/stedolan/jq/issues/1243#issuecomment-249399788
- https://github.com/stedolan/jq/issues/1239#issuecomment-248303846

I also took a closer look at the patches and they are smaller than I thought, so I will investigate if backporting to 1.5 is feasible.

2016-09-25 06:12 UTC, aneeshusa commented
Updated to stay on v1.5, although IMO the development version would also be fine.

2016-09-25 06:19 UTC, Mic92 commented
Related to: https://github.com/NixOS/nixpkgs/issues/18856

2016-09-25 13:10 UTC, fpletz commented on pkgs/development/tools/jq/default.nix
> +  # but no release has been made since then (latest release was last year)
Hmm, I see. In that case it could make sense to use the master. But we should review the changes in master and do some tests before using that version. Do you know why 1.6 is delayed? Is that due to a bug that could be a dealbreaker?

2016-09-25 13:12 UTC, fpletz approved these changes

2016-09-25 13:14 UTC, fpletz commented
I'll merge this for now. If you are confident the git master is indeed okay, please open another PR. Thanks for your work!

2016-09-25 13:14 UTC, merged

2018-06-27 09:19 UTC, fatbearinc commented
Have both of these CVEs been fixed? Looking at:

https://nvd.nist.gov/vuln/detail/CVE-2016-4074#VulnChangeHistorySection

seems to indicate that the CVEs still apply to jq version 1.5. Is this correct?

2018-07-17 02:54 UTC, aneeshusa commented
@fatbearinc jq 1.5 is not safe, but this PR pulls in two patches for jq 1.5 for the CVEs, so the jq package in Nixpkgs is patched against both CVEs.

2018-07-17 21:53 UTC, fpletz commented
I also just reconfirmed that we are indeed applying the correct patches to fix both CVEs. :+1: