Vulkan: 1.3.224.0 -> 1.3.224.1
NixOS/nixpkgs pull request #189290
Opened 2022-09-01 15:14 UTC by PedroHLC

###### Description of changes

> This SDK release fixes the following issues in release 1.3.224.0:
>
>    A fix to the Profiles Toolset merge script for a failure in which it may fail to create a VkDevice using the Profiles library on systems expected to be supported.
>    A Fix for a crash in NVidia Best Practices while checking for efficient use of vkCmdSetDepthCompareOp()
>    Fix handling of the Vulkan property, subgroupSize by the profiles library and layer.
>
From: https://vulkan.lunarg.com/doc/sdk/1.3.224.1/linux/release_notes.html

We could save user's bandwidth since https://github.com/NixOS/nixpkgs/pull/187918 is still in staging-next, and lots of packages just received a dummy version bump.

###### Things done

Tested building `vulkan-tools`, which built `vulkan-headers`, `vulkan-loader`, and `glslang`. Building `vulkan-tools-lunarg` builds `vulkan-validation-layers`, that builds the spirv stack. I've built `vulkan-extension-layer` and that closed the testing...

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-09-01 21:01 UTC, lovesegfault commented
Up to @vcunat on whether landing this straight to staging-next is okay or not. Usually, we just suck it up and wait for another staging cycle 🤷

2022-09-01 23:41 UTC, Atemu approved these changes
Ran vkcube

2022-09-02 00:27 UTC, superherointj approved these changes
All Vulkan packages listed builds for me. But I have not built/tested downstream.

2022-09-04 17:16 UTC, SuperSandro2000 requested changes, later dismissed
Please follow the [contributing guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes) when naming your commits.

Also are you sure that the hashes did not change in some places?

2022-09-04 17:46 UTC, PedroHLC commented
> Please follow the [contributing guide](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes) when naming your commits.

Hi Sandro, how are you?

This naming trend [didn't start with me](https://github.com/NixOS/nixpkgs/commits/master/pkgs/development/libraries/vulkan-headers/default.nix), but I could rename it to "vulkan-sdk", "vulkan-*", or if we go strictly by a real package name split it in multiple commits.
 
> Also are you sure that the hashes did not change in some places?

Yes, each one of them, this bump is just a fix for the profiling layers, and does not add new functionality to the vulkan api. Lunarg probably bumps the version for maintaining their versioning assertion convention as seen in the Vulkan SDK White Paper. (We also have some versioning depending assertions there)

2022-09-04 21:10 UTC, Atemu commented
@PedroHLC they likely meant `Vulkan` -> `vulkan`.

2022-09-05 11:26 UTC, vcunat commented
> whether landing this straight to staging-next is okay or not

For the past few days, no `*-linux` builder has worked on Hydra, so right now I'd be careful.

2022-09-06 16:45 UTC, lovesegfault commented
Let's just go the normal staging route.

2022-09-06 16:46 UTC, merged

2022-09-06 22:52 UTC, SuperSandro2000 commented
> @PedroHLC they likely meant `Vulkan` -> `vulkan`.

No, I didn't. Each package should receive its own commit according to the contributing guide. This would also trigger ofborg for every package.

2022-09-07 05:18 UTC, vcunat commented
It would probably not be true (save user's bandwidth), as most `staging-next` iterations are huge rebuilds either way.  (stdenv or something else very down gets rebuilt)