add jsbeautifier
NixOS/nixpkgs pull request #18958
Opened 2016-09-25 19:30 UTC by 41px

###### Motivation for this change

This little beautifier will reformat and reindent bookmarklets, ugly JavaScript, unpack scripts packed by Dean Edward’s popular packer, as well as deobfuscate scripts processed by javascriptobfuscator.com.

https://github.com/beautify-web/js-beautify

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-09-25 19:40 UTC, FRidh commented on pkgs/development/python-modules/jsbeautifier/default.nix
> +stdenv.mkDerivation rec {
this is a python package. Please use `buildPythonPackage` and put the whole expression in `python-packages.nix`. Check the expressions in that file to see how it should be used.

2016-09-25 19:40 UTC, FRidh requested changes

2016-09-25 20:19 UTC, 41px commented
I had to add editorconfig.

2016-09-25 20:46 UTC, FRidh commented
you might want to go through the contributing guidelines as well

2016-09-25 20:47 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +
whitespace

2016-09-25 20:48 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    src = pkgs.fetchgit {
PyPI is the preferred source

2016-09-25 20:48 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +
whitespace

2016-09-25 20:48 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +      homepage = "http://editorconfig.org";
urls are special and do not need quotations

2016-09-25 20:49 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    buildInputs = with self; [ editorconfig pytest six ];
Are you sure it needs six only during building, and not during run-time?
Also, did you check whether the tests are actually run with all interpreter versions?

2016-09-25 20:49 UTC, FRidh requested changes

2016-09-26 19:56 UTC, kevincox approved these changes

2016-09-26 20:04 UTC, FRidh commented
As I pointed out before, please go through the contributing guidelines. All changes need to be in logical units (commits) and named according to the guidelines.

2016-09-26 20:22 UTC, 41px commented
I can delete it and recreate it with the contributing guidelines.

Le 26 sept. 2016 10:05 PM, "Frederik Rietdijk" <notifications@github.com> a
écrit :

> As I pointed out before, please go through the contributing guidelines.
> All changes need to be in logical units (commits) and named according to
> the guidelines.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/18958#issuecomment-249681464>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABB1AjHzULbSxdOKf0geugw10WMpvm7Kks5quCVrgaJpZM4KF-0g>
> .
>

2016-10-01 09:11 UTC, FRidh commented
ping

2016-10-02 15:04 UTC, apeyroux commented
see #19163

2016-10-02 15:04 UTC, closed without merging