libxslt: fix cross compilation
NixOS/nixpkgs pull request #189766
Opened 2022-09-04 19:20 UTC by yvesf

###### Description of changes
Fixes #189764 

###### Things done

- ✔️ `nix build .#pkgsCross.aarch64-multiplatform.libxslt` (fixed)
- ✔️ `nix build .#libxslt` (no change)

2022-09-04 19:36 UTC, SuperSandro2000 reviewed
If this triggers less than 500+ rebuilds please targer master

2022-09-04 21:08 UTC, OPNA2608 requested changes

2022-09-04 21:08 UTC, OPNA2608 commented on pkgs/development/libraries/libxslt/default.nix
> +    "--without-python"
https://github.com/NixOS/nixpkgs/blob/bb961e670f16adf5a9ccae96b82edfd9881fd730/lib/strings.nix#L663-L672

```suggestion
    (lib.withFeatureAs pythonSupport "python" python)
```

2022-09-05 14:14 UTC, SuperSandro2000 commented on pkgs/development/libraries/libxslt/default.nix
> +    "--without-python"
@OPNA2608 great catch!

2022-09-06 01:53 UTC, IvarWithoutBones approved these changes

2022-09-06 05:30 UTC, merged