gcsfuse: init at v0.19.0
NixOS/nixpkgs pull request #18980
Opened 2016-09-26 15:01 UTC by MostAwesomeDude

###### Motivation for this change

The gcsfuse tool mounts Google Cloud Storage buckets using FUSE. It is not included in the Google Cloud SDK, so it must be packaged separately.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-09-26 16:01 UTC, Mic92 commented on pkgs/tools/filesystems/gcsfuse/default.nix
> +  version = "81281027";
If there is no release, use the following format: `<year>-<month>-<day>` instead of the git commit.

2016-09-26 16:03 UTC, Mic92 commented on pkgs/tools/filesystems/gcsfuse/default.nix
> +  meta = {
well, this need also to be filled: At least: license, maintainer, homepage and description

2016-09-26 18:33 UTC, kevincox commented on pkgs/tools/filesystems/gcsfuse/default.nix
> +  goDeps = null;
To be very nit-picky can you remove "apparently" isn't not necessary.

Also the current practice appears to be just not providing this field. I would prefer the constancy..

2016-09-26 18:34 UTC, kevincox commented on pkgs/tools/filesystems/gcsfuse/default.nix
> +{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:
Only `buildGoPackage` and `fetchgit` are used. Can you please remove the others?

2016-09-26 18:34 UTC, kevincox requested changes
Looks good in general. With the touchups should be mergable.

2016-09-29 14:35 UTC, Mic92 commented on pkgs/tools/filesystems/gcsfuse/default.nix
> +  propagatedBuildInputs = [ fuse ];
Does it really use libfuse? I thought has go comes with is own implementation: https://github.com/GoogleCloudPlatform/gcsfuse/blob/master/internal/fs/fs.go#L29

2016-09-29 14:48 UTC, MostAwesomeDude commented on pkgs/tools/filesystems/gcsfuse/default.nix
> +  propagatedBuildInputs = [ fuse ];
Technically, no; this is to ensure that `fusermount` is within arms' reach. I'm removing it here.

2016-09-29 14:55 UTC, merged