immudb: init at 1.3.2
NixOS/nixpkgs pull request #190109
Opened 2022-09-07 09:22 UTC by dit7ya

###### Description of changes

immudb is a database with built-in cryptographic proof and verification. It tracks changes in sensitive data and the integrity of the history will be protected by the clients, without the need to trust the database. It can operate both as a key-value store, and/or as relational database (SQL).

https://github.com/codenotary/immudb

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-09-08 02:37 UTC, AndersonTorres requested changes
Format this code.

2022-09-10 21:49 UTC, AndersonTorres requested changes

2022-09-10 21:49 UTC, AndersonTorres commented on pkgs/servers/nosql/immudb/default.nix
> +let
```suggestion

let
```

2022-09-10 21:49 UTC, AndersonTorres commented on pkgs/servers/nosql/immudb/default.nix
> +in
```suggestion

in
```

2022-09-10 21:49 UTC, AndersonTorres commented on pkgs/servers/nosql/immudb/default.nix
> +  src = fetchFromGitHub {
```suggestion

  src = fetchFromGitHub {
```

2022-09-10 21:49 UTC, AndersonTorres commented on pkgs/servers/nosql/immudb/default.nix
> +    '';
```suggestion
  postInstall = ''
    mkdir -p share/completions
    for executable in immudb immuclient immuadmin; do
        for shell in bash fish zsh; do
        $out/bin/$executable completion $shell > share/completions/$executable.$shell
        installShellCompletion share/completions/$executable.$shell
      done
    done
  '';
```

2022-09-11 11:42 UTC, viraptor reviewed
Result of `nixpkgs-review pr 190109` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>immudb</li>
  </ul>
</details>

Apart from the style change requests, it looks ok to me.

2022-09-15 02:51 UTC, AndersonTorres requested changes
And this ends the cosmetical part. Otherwise LGTM.

2022-09-15 02:51 UTC, AndersonTorres commented on pkgs/servers/nosql/immudb/default.nix
> +    '';
Indent the code:

```suggestion
  postInstall = ''
    mkdir -p share/completions
    for executable in immudb immuclient immuadmin; do
      for shell in bash fish zsh; do
        $out/bin/$executable completion $shell > share/completions/$executable.$shell
        installShellCompletion share/completions/$executable.$shell
      done
    done
  '';
```

2022-09-15 02:51 UTC, AndersonTorres commented on pkgs/servers/nosql/immudb/default.nix
> +
```suggestion
```

2022-09-17 13:28 UTC, AndersonTorres approved these changes
LGTM

2022-09-17 13:28 UTC, merged