ps3netsrv: init at 1.1.0
NixOS/nixpkgs pull request #19035
Opened 2016-09-28 11:14 UTC by makefu

###### Motivation for this change

Tool was not yet available in nixpkgs and requires a few non-standard quirks to install correctly.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-09-28 15:57 UTC, joachifm commented on pkgs/servers/ps3netsrv/default.nix
> +{ stdenv, fetchgit, clang, makeWrapper, gnugrep }:
`clang` and `makeWrapper` appear to be unused.

2016-09-28 20:22 UTC, makefu commented on pkgs/servers/ps3netsrv/default.nix
> +{ stdenv, fetchgit, clang, makeWrapper, gnugrep }:
you are right, they are relicts from building the nix expression. fixed

2016-09-28 20:39 UTC, Mic92 commented on pkgs/servers/ps3netsrv/default.nix
> +    platforms = stdenv.lib.platforms.linux;
according to github this also runs on Mac OS X and FreeBSD.

2016-09-28 20:57 UTC, makefu commented on pkgs/servers/ps3netsrv/default.nix
> +    platforms = stdenv.lib.platforms.linux;
unfortunately i have no way to test on these and therefore i have hesitated to add more platforms than i can test myself.

2016-09-29 13:36 UTC, rasendubi requested changes

2016-09-29 13:36 UTC, rasendubi commented on pkgs/servers/ps3netsrv/default.nix
> +  buildPhase = "make CXX=g++";
This will fail with clang. Use `make CXX=$CXX` instead.

2016-09-29 13:37 UTC, rasendubi commented on pkgs/servers/ps3netsrv/default.nix
> +  name = "ps3netsrv-${version}";
`version` can be inlined.

2016-09-29 13:43 UTC, makefu commented on pkgs/servers/ps3netsrv/default.nix
> +  buildPhase = "make CXX=g++";
i will test this locally but i remember i had some issues with clang.

2016-09-29 13:43 UTC, makefu commented on pkgs/servers/ps3netsrv/default.nix
> +  name = "ps3netsrv-${version}";
@rasendubi what exactly does this mean? do you have an example?

2016-09-29 13:47 UTC, joachifm commented on pkgs/servers/ps3netsrv/default.nix
> +  name = "ps3netsrv-${version}";
You can specify the version within `name` without a separate attribute.

2016-09-29 13:53 UTC, rasendubi commented on pkgs/servers/ps3netsrv/default.nix
> +  nativeBuildInputs = [ gnugrep ];
Not needed

2016-09-29 14:05 UTC, makefu commented on pkgs/servers/ps3netsrv/default.nix
> +  nativeBuildInputs = [ gnugrep ];
fixed

2016-09-29 14:29 UTC, merged

2016-09-29 17:23 UTC, makefu commented
Thanks everyone for reviewing my 31 lines of code, i really appreciate it :+1:

2016-09-29 21:00 UTC, Mic92 commented
31 LOCs == 32 Bugs?

2016-09-30 10:10 UTC, makefu commented
@Mic92 not sure if i would describe each comment as a bug though