bean-add: init at 76945c320e6f028223e4420956c80c421c4fe74a
NixOS/nixpkgs pull request #19083
Opened 2016-09-29 15:11 UTC by matthiasbeyer

###### Motivation for this change

Utility for `beancount` which helps entering entries.

We should propably wait for https://github.com/simon-v/bean-add/issues/2 to be solved before merging this PR,...

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-09-29 16:00 UTC, matthiasbeyer commented
As said in https://github.com/simon-v/bean-add/issues/2, this should be a python 3 package, so I updated it.

Also as said in https://github.com/simon-v/bean-add/issues/2, one cannot call `bean-add` on an empty file, so I guess this can be merged.

2016-09-29 16:02 UTC, Mic92 commented on pkgs/applications/office/beancount/bean-add.nix
> +  src = fetchgit {
please use fetchFromGithub here.

2016-09-29 16:02 UTC, Mic92 commented
ping @FRidh

2016-09-29 16:05 UTC, Mic92 commented on pkgs/applications/office/beancount/bean-add.nix
> +  name = "bean-add-${version}";
```
name = "bean-add-2016-09-29";
```

2016-09-29 17:12 UTC, FRidh requested changes

2016-09-29 17:12 UTC, FRidh commented on pkgs/applications/office/beancount/bean-add.nix
> +    sed -i "s,/usr/bin/python,/usr/bin/env python," bean-add
shebangs will have been patched, except if they're strings somewhere in the files.

2016-09-29 17:15 UTC, FRidh requested changes

2016-09-29 17:15 UTC, FRidh commented on pkgs/applications/office/beancount/bean-add.nix
> +{ stdenv, fetchFromGitHub, pkgs, python3Packages }:
no pkgs here

2016-09-29 17:19 UTC, FRidh commented
so this isn't a setuptools/distutils package. In that case, you might just want to use `stdenv.mkDerivation` and call `wrapPythonProgram`.

2016-09-29 17:34 UTC, matthiasbeyer commented
@FRidh What do I have to bring in scope for `wrapPythonProgram` ?

2016-09-29 17:35 UTC, FRidh commented
pythonXXPackages.wrapPython

2016-09-29 17:37 UTC, matthiasbeyer commented
As `buildInputs = []` ?

2016-09-29 17:40 UTC, FRidh commented
yep

2016-09-29 17:42 UTC, matthiasbeyer commented
This gets me a `wrapPythonProgram not found` in the build output.(Going to push the commit now).

2016-09-29 17:49 UTC, FRidh commented
oh it has to be wrapPythonPrograms, note the s

2016-09-29 17:57 UTC, FRidh requested changes
squash, and rename commit (use the date) and then it should be fine

2016-09-30 07:35 UTC, matthiasbeyer commented
I get

```
./result/bin/bean-add: /nix/store/f31svzv73raxhplzb3kmf2jrcds5ln4b-bean-add-2016-09-29/bin/.bean-add-wrapped: /usr/bin/python: bad interpreter: No such file or directory
./result/bin/bean-add: line 3: /nix/store/f31svzv73raxhplzb3kmf2jrcds5ln4b-bean-add-2016-09-29/bin/.bean-add-wrapped: Success
```

despite the `wrapPythonPrograms` call.

2016-09-30 07:41 UTC, FRidh commented
python3 is also needed as a buildInput

2016-09-30 07:42 UTC, FRidh commented
if I am correct just using patchShebangs should already work as well, instead of wrapPythonPrograms, but I am not sure about that.

2016-09-30 07:58 UTC, matthiasbeyer commented
@FRidh no, `patchShebangs` also yields: `bash: ./result/bin/bean-add: /usr/bin/python: Defekter Interpreter: No such file or directory`

2016-09-30 07:59 UTC, matthiasbeyer commented
Adding `python` to the `buildInputs` doesn't work either.

2016-09-30 08:00 UTC, FRidh commented
wrapPythonPrograms is used without arguments

2016-09-30 08:06 UTC, matthiasbeyer commented
Having `python` in `buildInputs`, calling `wrapPythonPrograms` without arguments still yields a defect interpreter path. :cry:

2016-09-30 08:06 UTC, FRidh commented
ok, I got it working now, and now I understand why I had a similar problem before. Let me open a PR to your branch

2016-09-30 08:06 UTC, matthiasbeyer commented
Awesome :tada:

2016-09-30 08:09 UTC, FRidh commented
patchShebangs cannot patch a /usr/bin/python to a Python 3 path, only /usr/bin/python3. Is there a reason you choose Python 3?

2016-09-30 08:11 UTC, matthiasbeyer commented
No, not really. Is a `Signed-off-by:` line in the commit message with your data okay for you?

2016-09-30 08:12 UTC, matthiasbeyer commented
Hm... now it cannot find `readline`...

2016-09-30 08:14 UTC, matthiasbeyer commented
@FRidh Oh no: https://github.com/simon-v/bean-add/commit/7f47d16ba2e124a1c3aef748d10575f18cbad9e9 - they require python3 now. :dog: I guess I will finish this package now, then squash and then update the package to the latest master of the repository and fix it for it (within this PR).

2016-10-01 12:12 UTC, matthiasbeyer commented
Updated to latest master of the repository, now things work.

@FRidh thanks for your help!

2016-10-01 12:27 UTC, FRidh commented
If you modify the commit message to use the date instead of the commit revision then its ok

2016-10-02 14:45 UTC, merged

2016-10-02 14:45 UTC, Mic92 commented
Thanks.

2016-10-02 14:55 UTC, matthiasbeyer commented
Thank **you** for your help! :smile: