Add `programs.ecryptfs` for mount wrappers
NixOS/nixpkgs pull request #190944
Opened 2022-09-12 15:45 UTC by nh2

The `ecryptfs` package refers to the setuid wrapper paths ([here](https://github.com/NixOS/nixpkgs/blob/dd1f4d982445a7d1b1869baa42f8f0f9bc606714/pkgs/tools/security/ecryptfs/default.nix#L22-L23)), but they do not exist so far in NixOS.

Without this change, `ecryptfs-setup-private` and `ecryptfs-mount-private` fail with error:

```
/nix/store/bqwhqhhr8j6ds4008i8bj5iha88najxp-ecryptfs-111/bin/.ecryptfs-setup-private-wrapped: line 443: /run/wrappers/bin/mount.ecryptfs_private: No such file or directory
```

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-01-26 17:19 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/1756

2023-01-27 00:11 UTC, SuperSandro2000 requested changes

2023-01-27 00:11 UTC, SuperSandro2000 commented on nixos/modules/programs/ecryptfs.nix
> +    enable = mkEnableOption "ecryptfs setuid mount wrappers";
```suggestion
    enable = mkEnableOption (lib.mdDoc "ecryptfs setuid mount wrappers");
```

2023-09-05 18:56 UTC, nh2 commented
@SuperSandro2000 Thanks, please take another look!

2023-09-05 20:50 UTC, SuperSandro2000 approved these changes

2023-09-05 23:14 UTC, merged