Init phetch
NixOS/nixpkgs pull request #191715
Opened 2022-09-17 22:40 UTC by felixalbrigtsen

###### Description of changes

Added package phetch(https://github.com/xvxx/phetch), a gopher client written in rust.
The dependencies are patched to work with openssl in nixpkgs. 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-09-18 16:42 UTC, dali99 requested changes

2022-09-18 16:42 UTC, dali99 commented on maintainers/maintainer-list.nix
> +    matrix = "felixalb:pvv.ntnu.no";
```suggestion
    matrix = "@felixalb:pvv.ntnu.no";
```

2022-09-18 20:40 UTC, dali99 requested changes
You have to squash your commits together so that there are only two, one for adding the maintainer, and one for adding the package.

you can use interactive rebase and fixups to accomplish this

2022-09-18 20:40 UTC, dali99 commented on pkgs/applications/networking/gopher/phetch/default.nix
> +  doCheck = false;
The tests don't even compile, but the program works. You might want to add a comment as to why the tests are disabled.

2023-01-19 21:11 UTC, pbsds approved these changes
LGTM

2023-01-20 21:48 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/1016/36

2023-01-21 23:23 UTC, h7x4 approved these changes

2023-01-22 10:42 UTC, dali99 approved these changes

2023-01-26 18:04 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/1757

2023-01-27 00:23 UTC, SuperSandro2000 commented on pkgs/applications/networking/gopher/phetch/default.nix
> +    install -m644 doc/phetch.1 $man/share/man/man1
```suggestion
    installMagPage doc/phetch.1
```

2023-01-27 00:24 UTC, SuperSandro2000 commented on pkgs/applications/networking/gopher/phetch/default.nix
> +    license = "licenses.mit";
```suggestion
    license = licenses.mit;
```

2023-04-11 21:06 UTC, SuperSandro2000 commented
@ofborg eval

2023-04-11 21:54 UTC, merged