lsof-4.89: fixed for Darwin.
NixOS/nixpkgs pull request #19222
Opened 2016-10-04 13:56 UTC by jhhuh

###### Motivation for this change

Previously, building 'lsof-4.89' was broken in Darwin system. To fix that, 1) 'ncurses' is added as a build-dependency, and 2)  'dfile.patch' is provided to fix two minor bugs found in 'dialect/darwin/libproc/dfile.c'.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-10-04 14:22 UTC, copumpkin commented on pkgs/development/tools/misc/lsof/dfile.patch
> +-	    putchar(`,');
How did this ever work?

2016-10-04 14:55 UTC, Mic92 commented
some stylistic nitpicks:

```patch
diff --git a/pkgs/development/tools/misc/lsof/default.nix b/pkgs/development/tools/misc/lsof/default.nix
index 0095f85..238823b 100644
--- a/pkgs/development/tools/misc/lsof/default.nix
+++ b/pkgs/development/tools/misc/lsof/default.nix
@@ -1,11 +1,10 @@
-{ stdenv, fetchurl }:
-let pkgs = import <nixpkgs> {};
-in
+{ stdenv, fetchurl, ncurses }:
+
 stdenv.mkDerivation rec {
   name = "lsof-${version}";
   version = "4.89";
 
-  buildInputs = [ pkgs.ncurses ];
+  buildInputs = [ ncurses ];
 
   src = fetchurl {
     urls =
@@ -25,10 +24,12 @@ stdenv.mkDerivation rec {
   };
 
   unpackPhase = "tar xvjf $src; cd lsof_*; tar xvf lsof_*.tar; sourceRoot=$( echo lsof_*/); ";
-  
+
   patches = [ ./dfile.patch ];
 
-  preBuild = "sed -i Makefile -e 's/^CFGF=/&	-DHASIPv6=1/;' -e s/-lcurses/-lncurses/ ;";
+  preBuild = ''
+    sed -i Makefile -e 's/^CFGF=/& -DHASIPv6=1/;' -e 's/-lcurses/-lncurses/'
+  '';
 
   configurePhase = ''
     # Stop build scripts from searching global include paths
```

2016-10-04 14:58 UTC, Mic92 commented on pkgs/development/tools/misc/lsof/default.nix
> +    # export LSOF_INCLUDE=/$(md5sum <(echo $name) | awk '{print $1}')
do we want this on other platforms?

2016-10-04 15:36 UTC, adnelson commented on pkgs/development/tools/misc/lsof/default.nix
> +let pkgs = import <nixpkgs> {};
pkgs should be added as an argument to the function; otherwise a new and potentially different nixpkgs will be instantiated here

2016-10-04 15:36 UTC, adnelson commented on pkgs/development/tools/misc/lsof/default.nix
> +    # export LSOF_INCLUDE=/$(md5sum <(echo $name) | awk '{print $1}')
I did this one; we could just direct it to `/dev/null` (the `md5sum` call is just meant to create a file that we're confident doesn't exist). Basically it's to stop lsof from importing global system paths. And yes, we'll want to keep it unless we get around that some other way.

2016-10-04 15:48 UTC, matthewbauer requested changes

2016-10-04 15:48 UTC, matthewbauer commented on pkgs/development/tools/misc/lsof/dfile.patch
> +-	    putchar(`,');
It didn't.

2016-10-04 15:48 UTC, matthewbauer commented on pkgs/development/tools/misc/lsof/default.nix
> +  preBuild = "sed -i Makefile -e 's/^CFGF=/&	-DHASIPv6=1/;' -e s/-lcurses/-lncurses/ ;";
Shouldn't this be "postPatch" phase?

2016-10-04 19:54 UTC, Mic92 commented on pkgs/development/tools/misc/lsof/default.nix
> +  preBuild = "sed -i Makefile -e 's/^CFGF=/&	-DHASIPv6=1/;' -e s/-lcurses/-lncurses/ ;";
there is no Makefile yet in postPatch, when I tested it.

2016-10-04 21:38 UTC, jhhuh commented on pkgs/development/tools/misc/lsof/dfile.patch
> +-	    putchar(`,');
I was curious about that, too.

2016-10-04 21:51 UTC, jhhuh commented on pkgs/development/tools/misc/lsof/default.nix
> +    # export LSOF_INCLUDE=/$(md5sum <(echo $name) | awk '{print $1}')
@Mic92, thanks for pointing it out. Actually, I was not sure about the purpose of that line, but now @adnelson's comment below made it a bit more clear.

By assigning no value, it defaults to '/usr/include', and it makes it successfully compiled on OS X.

Is compiling with a header file outside of nix world a bad practice? If so, I should find out another way.

2016-10-04 21:53 UTC, jhhuh commented on pkgs/development/tools/misc/lsof/default.nix
> +let pkgs = import <nixpkgs> {};
Thanks, @adnelson. You're absolutely right. This is my first PR to nixpkgs. Please consider it a beginner's mistake :)

2016-10-04 23:18 UTC, jhhuh commented on pkgs/development/tools/misc/lsof/default.nix
> +  preBuild = "sed -i Makefile -e 's/^CFGF=/&	-DHASIPv6=1/;' -e s/-lcurses/-lncurses/ ;";
@Mic92, I found the same thing. Unless postConfigure is turned on, preBuild seems to be the only reasonable place for this line.

2016-10-04 23:21 UTC, jhhuh commented on pkgs/development/tools/misc/lsof/default.nix
> +    # export LSOF_INCLUDE=/$(md5sum <(echo $name) | awk '{print $1}')
@adnelson Yes, OK. I just tested `export LSOF_INCLUDE=${stdenv.libc}/include`. It worked well on OS X, and I believe it should in other platforms as well.

2016-10-06 12:50 UTC, jhhuh commented
Now PR is updated reflecting the reviewer's comments.

2016-10-06 13:29 UTC, jhhuh commented on pkgs/development/tools/misc/lsof/default.nix
> +    # export LSOF_INCLUDE=/$(md5sum <(echo $name) | awk '{print $1}')
Oops, 'stdenv.libc' is missing on linux. Now I changed it to 'stdenv.cc.libc'.

2016-10-06 18:38 UTC, merged