tinyfugue: init at 50b8
NixOS/nixpkgs pull request #19224
Opened 2016-10-04 15:08 UTC by KibaFox

###### Motivation for this change

Add tinyfugue, a terminal UI, screen oriented, MUD client.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-10-04 20:33 UTC, joachifm requested changes
Needs a license, but otherwise LGTM

2016-10-04 20:33 UTC, joachifm commented on pkgs/games/tinyfugue/default.nix
> +  meta = {
Please specify a `license` attribute.

2016-10-04 21:49 UTC, KibaFox commented on pkgs/games/tinyfugue/default.nix
> +  meta = {
@joachifm I've added the `license` attribute on line 33.

2016-10-04 21:50 UTC, KibaFox commented
@joachifm - Thank you for taking the time to review my pull request!  I've updated my pull request with the license.

2016-10-04 22:08 UTC, joachifm approved these changes

2016-10-04 22:08 UTC, merged

2016-10-04 22:08 UTC, joachifm commented
Thanks!

2016-10-05 17:31 UTC, KibaFox commented
Thank you for approving my changes, @joachifm!

I got a message back from the Hydra Build Daemon that says it's failing for the Darwin platform.  Would you know if there's a way to test changes on Macs without having any Apple hardware?

2016-10-05 17:41 UTC, joachifm commented
@KibaFox I'm unaware of any way of testing on darwin (but then again I know nothing about that platform). I think it's acceptable to disable darwin hydra builds and wait until a darwin user contributes a fix.

As far as I can tell, the error is due to use of a legacy typedef (`caddr_t`) which shouldn't be too hard to fix, but then there may be other problems.

2016-10-05 18:15 UTC, Mic92 commented
I am currently downloading this box here: https://github.com/AndrewDryga/vagrant-box-osx
maybe I can test more stuff on os x then.

2016-10-06 14:35 UTC, KibaFox commented
Thanks!  I'll give that a try.  It may be a little bit before I have time to set that up.