pgpdump: init at v0.31
NixOS/nixpkgs pull request #19257
Opened 2016-10-05 14:30 UTC by primeos

###### Motivation for this change

Adding a new package that will help analyzing OpenPGP packets.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Add the package "pgpdump" at version v0.31 under the category
"tools/security", add it to the top-level package collection and set
myself as the maintainer (I added myself to lib/maintainers.nix).

I have tested this package under NixOS and Gentoo+Nix.

2016-10-05 14:45 UTC, groxxda requested changes

2016-10-05 14:45 UTC, groxxda commented on pkgs/tools/security/pgpdump/default.nix
> +  version = "v0.31";
version must start with a digit

2016-10-05 14:45 UTC, groxxda commented on pkgs/tools/security/pgpdump/default.nix
> +  src = fetchurl {
you could use `fetchFromGitHub`

2016-10-05 15:54 UTC, primeos commented on pkgs/tools/security/pgpdump/default.nix
> +  src = fetchurl {
Thanks :+1: 

I fixed the version (I'm now prefixing the 'v' in `rev = "v${version}"` - hope thats ok) and I switched to `fetchFromGitHub`.

2016-10-05 17:09 UTC, qknight commented
please to a:
`rebase -i HEAD~3`

and squash both of your commits into **one** commit to have a nice history

2016-10-06 01:05 UTC, rasendubi reviewed
Otherwise, looks good. Remove the dot, squash commits and it's good to go.

Tested on NixOS -- works fine.

2016-10-06 01:35 UTC, primeos commented on pkgs/tools/security/pgpdump/default.nix
> +    description = "A PGP packet visualizer.";
Whoops, I actually added the dot after reading trough CONTRIBUTING.md - I sometimes tend to miss negations...

2016-10-06 01:43 UTC, primeos commented
Should be fine now (I squashed the commits and did a rebase onto NixOS:master) , thanks for all the help :smile:

2016-10-06 11:03 UTC, merged