Allow cross-compiling libphonenumber.
NixOS/nixpkgs pull request #192661
Opened 2022-09-23 19:41 UTC by devwout

The following previously failed and now succeeds.

    nix-build -A pkgsCross.aarch64-multiplatform.libphonenumber .

When compiling natively, the result is the same as before.

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-09-24 08:28 UTC, bjornfor commented
Please put the package name first in the commit subject: "libphonenumber: fix cross-compilation"

2022-10-16 20:32 UTC, Mindavi commented
@ofborg build pkgsCross.aarch64-multiplatform.libphonenumber

I really doubt that gtest belongs in buildInputs, maybe it should be listed in checkInputs?

2022-10-23 19:48 UTC, Mindavi requested changes
Ofborg has trouble with the cross-compilation, could you check? Also still think that gtest doesn't belong in buildInputs, maybe it should be in checkInputs.

2022-10-31 11:21 UTC, delroth commented
> Ofborg has trouble with the cross-compilation, could you check?

The cross-compilation worked on the x86_64-linux worker FWIW, on the other ones it failed due to a dependency (icu4c). I wouldn't block on this, it seems like an unrelated issue and the x86_64-linux pkgsCross build should be enough to cover this particular PR.

(Also, given that it's been 8 days, a rebase might just fix it magically.)

+1 re: gtest in buildInputs vs. checkInputs, if that doesn't cause the build to fail at configure time (required dep).

2022-10-31 21:51 UTC, Mindavi approved these changes
I tried normal compilation, also with strictDeps, without any issues. SInce tests are not executed when cross-compiling anyway it doesn't matter.

I do suggest enabling doCheck to actually ensure tests are executed (during native compilation), but that can be in a follow-up IMO, since it's not that much in scope for this PR.

Cross works too on my machine and I see ofborg looks happier now :).

2022-10-31 21:52 UTC, merged