sqlite: disable obsolete features at compile-time
NixOS/nixpkgs pull request #192877
Opened 2022-09-25 11:16 UTC by asymmetric

###### Description of changes

These compile-time options are [recommended by upstream](https://www.sqlite.org/compile.html#omit_shared_cache), and reduce library size while also increasing performance.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-09-26 01:30 UTC, AndersonTorres commented
Given the huge number of rebuild, please rebase this to staging.

2022-09-26 09:27 UTC, asymmetric commented
@AndersonTorres Done. Should OfBorg be triggered again?

2022-09-27 01:05 UTC, AndersonTorres commented
It should be automatic.

Nonetehless ofborg complains it is not building at all.

2022-09-27 01:06 UTC, AndersonTorres commented
@ofborg eval

2022-10-01 14:08 UTC, AndersonTorres commented
@ofborg eval nixUnstable

2022-10-01 14:08 UTC, AndersonTorres commented
@ofborg eval

2022-10-13 20:16 UTC, vcunat requested changes
Unfortunately, by my testing this would break build of `python3Packages.freezegun` and consequently many other packages.  That would need to get addressed before merging.

2022-10-13 20:18 UTC, vcunat commented
The error log isn't very revealing:
```
____________________ ERROR collecting tests/test_sqlite3.py ____________________
ImportError while importing test module '/build/freezegun-1.2.2/tests/test_sqlite3.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/g6kxnmy0j1xg8cvwhhjgiqwkp9bysdnl-python3-3.10.7/lib/python3.10/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_sqlite3.py:3: in <module>
    import sqlite3
/nix/store/g6kxnmy0j1xg8cvwhhjgiqwkp9bysdnl-python3-3.10.7/lib/python3.10/sqlite3/__init__.py:57: in <module>
    from sqlite3.dbapi2 import *
/nix/store/g6kxnmy0j1xg8cvwhhjgiqwkp9bysdnl-python3-3.10.7/lib/python3.10/sqlite3/dbapi2.py:27: in <module>
    from _sqlite3 import *
E   ModuleNotFoundError: No module named '_sqlite3'
=========================== short test summary info ============================
ERROR tests/test_sqlite3.py
```

2022-10-13 20:23 UTC, asymmetric commented
Unfortunately I don’t have time to investigate these puzzling downstream errors, so closing.

2022-10-13 20:23 UTC, closed without merging