sxhkd-git: init at revision from 2016-08-29
NixOS/nixpkgs pull request #19350
Opened 2016-10-08 04:26 UTC by cedeel

###### Motivation for this change
Added git version of sxhkd, the simple hotkey daemon for X.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-10-08 05:36 UTC, fpletz commented
Please note that the package should be include unstable rather than git in the name according to our package naming policy at https://nixos.org/nixpkgs/manual/#sec-package-naming.

> If a package is not a release but a commit from a repository, then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format. Also append "unstable" to the name - e.g., "pkgname-unstable-2014-09-23".

2016-10-08 13:05 UTC, primeos requested changes
Can you change the commit message to "sxhkd-unstable: init at 2016-08-29"?

2016-10-08 13:07 UTC, primeos commented on pkgs/applications/window-managers/sxhkd/git.nix
> +    homepage = http://github.com/baskerville/sxhkd/;
I would use `inherit (src.meta) homepage;`

2016-10-08 13:10 UTC, primeos commented on pkgs/applications/window-managers/sxhkd/git.nix
> +    homepage = http://github.com/baskerville/sxhkd/;
Whoops, my tab crashed and I lost this comment - couldn't edit my previous review... :o

2016-10-08 16:10 UTC, cedeel commented
Changed to `-unstable` everywhere. Not sure how to `inherit (src.meta) homepage;`

2016-10-08 17:01 UTC, primeos commented
Just put it inside the meta set e.g.:
```
meta = with stdenv.lib; {
  description = "Simple X hotkey daemon (git version)";
  inherit (src.meta) homepage;
  license = licenses.bsd2;
  platforms = platforms.linux;
};
```
The rest looks good as far as I can tell :wink:

2016-10-08 22:03 UTC, Mic92 commented
Is there a reason not to use a released version? https://github.com/baskerville/sxhkd/releases

2016-10-09 00:21 UTC, cedeel commented
@primeos Amended as per your recommendation, thanks.

@Mic92 A few fixes have gone in since March. I am sure that I'm not the only one who would want them.

2016-10-22 09:48 UTC, merged

2016-10-22 09:48 UTC, Mic92 commented
Thanks!