gogs: init at v0.9.97
NixOS/nixpkgs pull request #19361
Opened 2016-10-08 16:15 UTC by schneefux

I updated #13566 to the latest release and improved the code a bit. Fixes SSH authentication and repository mirroring.

Not tested yet:
  * [x] PAM _disabled_
  * [ ] MySQL/Postgres setup

cc @valeriangalliat @kamilchm @yorickvP

2016-10-08 17:28 UTC, primeos requested changes

2016-10-08 17:28 UTC, primeos commented on pkgs/applications/version-management/gogs/default.nix
> +  version = "v0.9.97";
> The version part of the name attribute must start with a digit (following a dash) — e.g., "hello-0.3.1rc2". [nixpkgs manual - 10.2. Package naming](https://nixos.org/nixpkgs/manual/#sec-package-naming)

I made the same mistake a few days ago...

2016-10-08 17:28 UTC, primeos commented on pkgs/applications/version-management/gogs/default.nix
> +    rev = "${version}";
You could use `rev = "v${version}";` :wink:

2016-10-09 10:51 UTC, schneefux commented on pkgs/applications/version-management/gogs/default.nix
> +  version = "v0.9.97";
@primeos @groxxda `v` is removed.

2016-10-09 15:09 UTC, Mic92 commented on pkgs/applications/version-management/gogs/deps.nix
> +    goPackagePath = "github.com/mattn/go-sqlite3";
this probably needs the sqlite package

2016-10-09 17:57 UTC, LnL7 commented on pkgs/applications/version-management/gogs/default.nix
> +      --replace '#!/usr/bin/env %s\n' "#!${bash}/bin/bash\\n#%s\\n"
This doesn't look right, you probably want to use `${coreutils}/bin/env` here

2016-10-09 18:02 UTC, LnL7 commented on pkgs/applications/version-management/gogs/default.nix
> +  buildFlags = "-tags"
`buildFlags` should be a list if you specify multiple arguments, then you don't have to worry about the space prefix.

2016-10-10 12:57 UTC, schneefux commented on pkgs/applications/version-management/gogs/deps.nix
> +    goPackagePath = "github.com/mattn/go-sqlite3";
It works fine without.
Other packages ([1](https://github.com/NixOS/nixpkgs/blob/98a9d815e05dd56aba0f9040d96092335cd90444/pkgs/shells/elvish/default.nix), [2](https://github.com/NixOS/nixpkgs/blob/98a9d815e05dd56aba0f9040d96092335cd90444/pkgs/development/tools/textql/default.nix)) that depend on `go-sqlite3` also don't include it.

2016-10-10 16:14 UTC, schneefux commented on pkgs/applications/version-management/gogs/default.nix
> +      --replace '#!/usr/bin/env %s\n' "#!${bash}/bin/bash\\n#%s\\n"
Thanks!

2016-10-12 10:18 UTC, schneefux commented
After updating and garbage collection, pushing fails with an error like `remote: hooks/update: line 3: /nix/store/53skjfhn19djc5mljp6vhr5mjm1gznnj-go1.7-gogs-v0.9.97-bin/bin/gogs: No such file or directory`
As stated in [Gogs' troubleshooting section](https://gogs.io/docs/intro/troubleshooting.html) the admin needs to rewrite all hooks via the admin panel when the Gogs binary path changes. How to deal with this or how do you notify the user?

2016-10-15 18:18 UTC, Mic92 commented
@schneefux this will happen after every upgrade, right?

2016-10-16 09:17 UTC, schneefux commented
@Mic92 Yes/No. After an update, the hooks will use the old Gogs version until the user does `nix-collect-garbage`, and then it will fail.

2016-10-22 09:46 UTC, Mic92 commented
@schneefux could be those hooks fixed in the module on service restart?

2016-10-22 11:29 UTC, schneefux commented
@Mic92 not as far as I know. I just opened an issue [here](https://github.com/gogits/gogs/issues/3796).

2016-10-22 12:44 UTC, Mic92 commented
@schneefux the alternative would be sed....

2016-10-22 15:34 UTC, schneefux commented
@Mic92 
> the alternative would be sed regexp.

What do you think about
```bash
HOOKS=$(find ${gogs.repositoryRoot} -mindepth 4 -maxdepth 4 -type f -wholename "*git/hooks/*")
sed -i 's,"/nix/store/[a-z0-9.-]+/bin/gogs,${gogs.bin}/bin/gogs,g' $HOOKS
sed -i 's,"/nix/store/[a-z0-9.-]+/bin/env,${coreutils.bin}/bin/env,g' $HOOKS
sed -i 's,"/nix/store/[a-z0-9.-]+/bin/perl,${perl.bin}/bin/perl,g' $HOOKS
```
?

2016-10-22 17:03 UTC, Mic92 commented
@schneefux by default only the `update` hook containing gogs should by affected, right?

2016-11-05 19:20 UTC, schneefux commented
> by default only the update hook containing gogs should by affected, right?

Yes, but I think it's better to update all hooks - for example if a user copies the `post-update.sample` hook.
I added the sed expressions to the module's preStart: https://github.com/NixOS/nixpkgs/pull/19363

2017-01-20 08:33 UTC, rnhmjoj commented
What's the status on this? Is there something needed to be done? I'd love to see this merged.

2017-01-20 18:42 UTC, schneefux commented
Updated to latest release
It's been running fine for months on my server, together with the module (#19363).

2017-01-20 18:48 UTC, LnL7 commented
I lost track of this, I'll test this after my other stuff is done building.

2017-01-20 19:47 UTC, LnL7 approved these changes

2017-01-20 19:47 UTC, merged

2017-01-21 00:02 UTC, rnhmjoj commented
Thanks you!