vscode-extensions.streetsidesoftware.code-spell-ch: 2.3.1 -> 2.7.3
NixOS/nixpkgs pull request #193938
Opened 2022-10-01 16:35 UTC by x10an14

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-10-03 16:07 UTC, datafoo reviewed
Looks good to me.

However, why not updating to the latest version 2.10.0 (https://marketplace.visualstudio.com/items/streetsidesoftware.code-spell-checker/changelog)?

2022-10-03 17:04 UTC, x10an14 commented
> However, why not updating to the latest version 2.10.0 (https://marketplace.visualstudio.com/items/streetsidesoftware.code-spell-checker/changelog)?

I didn't check marketplace manually, I just moused over the prompt(s) I got in VS Codium.

Can fix in ~1h or so.

2022-10-04 07:30 UTC, datafoo commented
> I didn't check marketplace manually, I just moused over the prompt(s) I got in VS Codium.
> 
> Can fix in ~1h or so.

Thank you! Can you update the  commit message and the PR message accordingly?

2022-10-04 07:34 UTC, x10an14 commented
> Thank you! Can you update the commit message and the PR message accordingly?

/derp... Ofc

2022-10-04 08:13 UTC, datafoo requested changes

2022-10-04 08:13 UTC, datafoo commented on pkgs/applications/editors/vscode/extensions/default.nix
> +          sha256 = "FeYkSML6QYtuIHIbAovOqlPwkKfNkHr7IdMCWwkynQ0=";
https://nixos.wiki/wiki/Nix_Hash

```suggestion
          sha256 = "sha256-FeYkSML6QYtuIHIbAovOqlPwkKfNkHr7IdMCWwkynQ0=";
```

2022-10-04 11:24 UTC, datafoo commented
Thank you. It looks good to me :+1:

2022-10-04 11:31 UTC, datafoo approved these changes

2022-10-04 13:37 UTC, merged

2022-10-06 08:30 UTC, datafoo commented
I did what the bot was asking and created PR https://github.com/NixOS/nixpkgs/pull/194723