openfire: fix service expression
NixOS/nixpkgs pull request #19453
Opened 2016-10-11 14:33 UTC by ryantrinkle

These bindings are necessary in the service expression below.

2016-10-11 14:34 UTC, ryantrinkle commented
@globin It looks like this code was removed in 88292fdf09960e9cb8e3c063a6b95ac4284222ec, but I think it's necessary.  Any objection to merging this?

2016-10-11 15:47 UTC, fpletz requested changes

2016-10-11 15:47 UTC, fpletz commented on nixos/modules/services/networking/openfire.nix
> +  inherit (pkgs) jre openfire coreutils which gnugrep gawk gnused;
Actually, only `openfire` is used in the systemd service below. Please just change the occurrence below to `pkgs.openfire` and we'll merge. ;)

2016-10-19 15:07 UTC, ryantrinkle commented
@fpletz Good call!  I missed the 'with' expression.

2016-10-24 09:35 UTC, merged