hugo: 0.102.3 -> 0.104.3
NixOS/nixpkgs pull request #194829
Opened 2022-10-06 23:12 UTC by Et7f3

###### Description of changes

Should I enable the check they succeed on my machine but I didn't commit.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`) (The test suite succeed)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-10-07 15:06 UTC, Et7f3 commented
Why rebuild zero I changed the sha ?

2022-10-08 12:44 UTC, bobby285271 commented
> Why rebuild zero I changed the sha?

Actually because this is a duplicate of #194587 :see_no_evil:

2022-10-08 15:45 UTC, Et7f3 commented
Ok and what about the check ? They successfully ran on x86_64-darwin should I enable them ?

2022-10-08 15:56 UTC, bobby285271 commented
I don't know, we can try do that and see if ofborg is happy on all four platforms. If the test runs well, not flaky and does not take too much time / resource to run we surely can do that.

2022-11-29 18:03 UTC, Frostman commented
Result of `nixpkgs-review pr 194829` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hugo</li>
  </ul>
</details>

2022-11-29 18:06 UTC, Frostman approved these changes

2023-01-22 00:00 UTC, wegank commented
@ofborg build hugo hugo.passthru.tests

2023-01-23 07:48 UTC, wegank requested changes
No tests were run.

2026-09-04 00:28 UTC, GraysonTinker commented
Done in #361975

2026-09-04 00:28 UTC, closed without merging