Added package for dehydrated.
NixOS/nixpkgs pull request #19651
Opened 2016-10-18 14:57 UTC by pstn

###### Motivation for this change
I want to create native nixos options for let's encrypt including automated cert renewal. This is the simplest tool for the job.

###### Things done

- [x ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x ] NixOS
   - [ ] OS X
   - [ ] Linux
- [x ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-10-18 15:39 UTC, pstn commented
Possible mergers: @fpletz @FRidh (?)

2016-10-18 17:04 UTC, fpletz requested changes
Note that there is also a `security.acme` NixOS module that does what you're trying to implement. Unfortunately, we chose to go with `simp_le` which sadly is unmaintained now. Moreover, it doesn't support the dns-01 challenge type which wasn't available when we built the module.

I've also created a nix expression for building dehydrated last weekend but never pushed it to nixpkgs because I wanted to rewrite the `security.acme` module to use dehydrated. Unfortunately, I found that it probably won't be too easy to maintain backwards-compatibility because some of the options are geared towards simp_le and dehydrated uses other formats and paths for account keys and cert private keys.

It would probably okay to change some options and recreate account keys, but the paths for certs and the private key should stay the same (fullchain.pem, key.pem). Are you willing to give it a shot? Just ask me here or in IRC if you have questions.

2016-10-18 17:04 UTC, fpletz commented on pkgs/tools/admin/dehydrated/default.nix
> +    rev = "ec49a4433b48a7bc8f178d06dad3f55cff24bdf3";
Please create a new `version` attribute in the `mkDerivation` call and re-use it in `name` and for a tag in `rev` instead of a commit hash.

2016-10-18 17:04 UTC, fpletz commented on pkgs/tools/admin/dehydrated/default.nix
> +    cp -a CHANGELOG $out/
The docs are a bit useless at these locations because users wouldn't find it there. If there is no manpage it's better to not copy them for now.

2016-10-18 17:04 UTC, fpletz commented on pkgs/tools/admin/dehydrated/default.nix
> +    wrapProgram "$out/bin/dehydrated" --prefix PATH : "${stdenv.lib.makeBinPath [ curl openssl ]}"
Have you checked that dehydrated works? In my expression, I have:

```
    wrapProgram $out/bin/dehydrated \
      --set PATH ${stdenv.lib.makeBinPath [
        openssl coreutils gnused gnugrep diffutils curl gawk
      ]}
```

2016-10-18 17:04 UTC, fpletz commented on pkgs/tools/admin/dehydrated/default.nix
> +    description = "This is a client for signing certificates with an ACME-server (currently only provided by letsencrypt) implemented as a relatively simple bash-script.";
The description should only be a few words describing the package, not a full sentence with a dot.

What about `description = "letsencrypt/acme client implemented as a shell-script";`?

2016-10-18 17:04 UTC, fpletz commented on pkgs/tools/admin/dehydrated/default.nix
> +  buildInputs = [ makeWrapper ];
`makeWrapper` should be in `nativeBuildInputs`.

2016-10-18 17:31 UTC, fpletz commented on pkgs/tools/admin/dehydrated/default.nix
> +    wrapProgram "$out/bin/dehydrated" --prefix PATH : "${stdenv.lib.makeBinPath [ curl openssl ]}"
Ah, right, I was using a pure nix-shell.

2016-10-18 18:08 UTC, pstn commented on pkgs/tools/admin/dehydrated/default.nix
> +  buildInputs = [ makeWrapper ];
I get a 

    /nix/store/wls1rsq5hp6hd3qpgdlxifj21synm7v6-stdenv/setup: line 884: wrapProgram: command not found

when I don't include this line, so it isn't (?)

2016-10-20 10:52 UTC, Mic92 commented
This tools tries to create files inside its directory (see BASEDIR). This fails because nix store is readonly.

2016-10-20 11:14 UTC, pstn commented
It needs to be supplied with a config file to change the BASEDIR. The config file will be generated by the nixos service definitions.

2016-10-20 11:32 UTC, merged

2016-10-20 11:32 UTC, Mic92 commented
Thanks!