odamex, springLobby: migrate to wxGTK32
NixOS/nixpkgs pull request #198552
Opened 2022-10-29 23:11 UTC by wegank

###### Description of changes

As in the title.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-10-31 08:31 UTC, mgttlinger requested changes
As maintainer of the urbackup client, I tested that and it seems to work, however several other packages failed to build as result of this PR:
```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/198552

10 packages failed to build:
perl534Packages.AlienWxWidgets perl534Packages.AppMusicChordPro perl534Packages.Wx perl534Packages.WxGLCanvas perl536Packages.AlienWxWidgets perl536Packages.AppMusicChordPro perl536Packages.Wx perl536Packages.WxGLCanvas slic3r springLobby
```

2022-10-31 13:05 UTC, wegank commented
@mgttlinger Removed the Perl commit. However, I don't have `springLobby` failing on my side. Could you please test again?

2022-11-01 07:25 UTC, mgttlinger commented
> @mgttlinger Removed the Perl commit. However, I don't have `springLobby` failing on my side. Could you please test again?

Yes, sadly it still fails:
```
Link to currently reviewing PR:
https://github.com/NixOS/nixpkgs/pull/198552

1 package failed to build:
springLobby

14 packages built:
boinc dolphin-emu electricsheep fityk flamerobin lenmus lutris lutris-free odamex pwsafe sooperlooper urbackup-client xchm xylib
```

I'm using `nixpkgs-review` to review this.

2022-11-01 13:50 UTC, wegank commented
@mgttlinger Alright. Removed springLobby from the PR.

2022-11-01 14:02 UTC, mgttlinger commented
Now there is only a broken package:
```
1 package marked as broken and skipped:
dolphinEmu

14 packages built:
boinc dolphin-emu electricsheep fityk flamerobin lenmus lutris lutris-free odamex pwsafe sooperlooper urbackup-client xchm xylib
```

2022-11-01 14:04 UTC, wegank commented
Wait, but `dolphinEmu = dolphin-emu;` in `pkgs/top-level/aliases.nix` ...

2022-11-02 14:32 UTC, wegank commented
@ofborg build dolphinEmu

2022-11-02 14:47 UTC, wegank commented
@mgttlinger I think it's more of a false alarm.

2022-11-03 08:00 UTC, mgttlinger requested changes
Otherwise, the changes look good to me.

2022-11-03 11:29 UTC, wegank commented on pkgs/games/odamex/default.nix
> +    license = lib.licenses.gpl2Plus;
Done.

2022-11-08 12:22 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/1382

2022-11-08 23:54 UTC, SuperSandro2000 reviewed
due to all the formatting changes it is not easy to know the actual changes. I didn't notice anything else though.

2022-11-08 23:54 UTC, SuperSandro2000 commented on pkgs/applications/science/misc/boinc/default.nix
> +    platforms = platforms.linux; # arbitrary choice
```suggestion
    platforms = platforms.linux;
```

2022-11-08 23:54 UTC, SuperSandro2000 commented on pkgs/games/spring/default.nix
> +, python ? null
```suggestion
, jdk
, python
```

2022-11-15 13:47 UTC, Luflosi commented
The changes to BOINC LGTM.

2022-11-23 22:08 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/1460

2022-11-24 13:20 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 198552` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>14 packages built:</summary>
  <ul>
    <li>boinc</li>
    <li>dolphin-emu</li>
    <li>electricsheep</li>
    <li>fityk</li>
    <li>flamerobin</li>
    <li>lenmus</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>odamex</li>
    <li>pwsafe</li>
    <li>sooperlooper</li>
    <li>urbackup-client</li>
    <li>xchm</li>
    <li>xylib</li>
  </ul>
</details>

2022-11-24 13:21 UTC, merged