emacs: add tzdata as dependency and set tzdir env var
NixOS/nixpkgs pull request #199163
Opened 2022-11-02 13:54 UTC by bnikolic

Emacs uses tzdata for up-to-date timezone information. Fixes e.g., https://discourse.nixos.org/t/home-manager-not-respecting-system-tz/12135

###### Description of changes

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-11-02 15:45 UTC, Atemu reviewed
Why do we need tzdata in the buildInputs?

Why doesn't Emacs just use the system tzdata?

Also, my Emacs correctly reports my time zone, I can't reproduce the bug.

2022-11-03 09:33 UTC, bnikolic commented
You can see the effect of missing tzdata by e.g. evaluating:  (current-time-zone nil "America/New_York")  .  It should give current offset and timezone in New York (EDT at time of writing). In Nix emacs without the patch I get (0 "America"), so zero offset and incorrect timezone abbreviation.   

Since the tzdata package is present in nixpkgs and in used in various derivations I assume there is a demand for the precise zoneinfo that it provides?

2022-11-03 09:44 UTC, Atemu commented
> You can see the effect of missing tzdata by e.g. evaluating: (current-time-zone nil "America/New_York") . It should give current offset and timezone in New York (EDT at time of writing). In Nix emacs without the patch I get (0 "America"), so zero offset and incorrect timezone abbreviation.

Could you add this explanation to the commit message?

On my NixOS machine though, `(current-time-zone nil "America/New_York")` evals to `(-14400 "EDT")`.

> Since the tzdata package is present in nixpkgs and in used in various derivations I assume there is a demand for the precise zoneinfo that it provides?

I'm asking why it's in buildInputs. You're already wrapping emacs with the env var. buildInputs is for things that Emacs' build process uses.

2022-11-03 10:40 UTC, bnikolic commented
Right, buildInputs was in case there is also a compile-time check for the timezones directory as is done in some other packages. But I've tested this and it seems there isn't, so I'll revise this to only wrap

2022-11-04 11:31 UTC, Atemu requested changes
Patch and commit message are good now.

I'm still unable to reproduce this issue on NixOS however and I still think our Emacs should just use the system tzdata rather than using env vars.

2022-11-07 11:28 UTC, bnikolic commented
I'm using nixpkgs on a non-NixOS system. I could setup the environment so that nix emacs looks into the host zoneinfo but that would break isolation and would mean Nix emacs has to have same version of zoneinfo as host. That would not be end of the world... but if tzdata package is already in nixpkgs seems cleaner to use the version properly declared in Nix?

2022-11-07 14:57 UTC, Atemu commented
The thing is that, on my NixOS system, it does look up the zoneinfo from the system; without any env var wrapping.

I'm not advocating for wrapping emacs with the env var explicitly setting zoneinfo to somwhere, I'm advocating for not setting the env var at all.

2022-11-14 03:24 UTC, adisbladis commented
I'm a huge :-1: on setting env vars in the wrapper for Emacs unless it's the absolute last resort.

I personally use exwm and start everything through emacs, this would pollute child programs too.
The same goes for a shell in your development environments.

Emacs isn't your typical software, it launches other software and everything we set in the environment is inherited.

> I'm still unable to reproduce this issue on NixOS however and I still think our Emacs should just use the system tzdata rather than using env vars.

:+1:

2023-07-08 02:58 UTC, adisbladis commented
I'm closing this as:
- It's stale
- The env var approach will possibly break other software

2023-07-08 02:58 UTC, closed without merging