Update beamPackages.hex to 0.14.0
NixOS/nixpkgs pull request #19994
Opened 2016-10-30 14:13 UTC by ankhers

###### Motivation for this change

Update to the latest version of the hex package

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] OS X
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-10-30 14:15 UTC, sternenseemann requested changes

2016-10-30 14:15 UTC, sternenseemann commented on pkgs/development/beam-modules/hex/default.nix
> +        rev = "cd6111d29b67bb9db8e6844bef568e65ca4c32a1";
I think you can just use `${version}` here which fetches the tag `v0.14.0` which is exactly what you want. Then updating is less of a hassle.

2016-10-30 19:57 UTC, ericbmerritt commented
looks good to me. Though it needs to be tested in the ecosystem.

2016-10-30 21:14 UTC, Mic92 commented
@ericbmerritt I am not familiar with the erlang ecosystem, what kind of breakage do you expect?

2016-10-30 21:16 UTC, ericbmerritt commented
I am not really expecting breakage, but the ecosystem is way more convoluted than it needs to be at the moment. I suggest that you run `nix-build -A beamPackages` in the root and see what happens. It takes a bit of time, but builds every package. If this doesn't break anything, you are golden if it does then try the same command on a bare master. If it passes there then this introduces some breakage that you should fix.

2016-10-30 22:12 UTC, ankhers commented
When running that command, I get the following error

`error: anonymous function at /Users/USER/work/personal/nixpkgs/pkgs/development/beam-modules/hex-packages.nix:1550:9 called without required argument ‘redix_0_3_6’, at /Users/USER/work/personal/nixpkgs/lib/customisation.nix:56:12`

I get that on OSX and my NixOS VM.

2016-11-02 16:50 UTC, ankhers commented
Just to be clear, I get the same result on master branch as well as this one.

2016-11-08 15:14 UTC, ankhers commented
Just wondering where this stands?

2016-11-08 15:21 UTC, grahamc commented
I ran nox-review on this against the current unstable channel and it builds just fine, with the only changed package being hexnix.

2016-11-14 15:46 UTC, ankhers commented
Is there anything else that needs to be done for this to be merged?

2016-11-15 05:54 UTC, merged