ocaml-ptime: init at 0.8.2
NixOS/nixpkgs pull request #20090
Opened 2016-11-02 13:42 UTC by sternenseemann

###### Motivation for this change

Dependency of `jackline` which I want to package.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] OS X
   - [ ] Linux
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2016-11-02 15:14 UTC, sternenseemann commented
Builds:

* [x] `ocamlPackages`
* [x] `ocamlPackages_4_02`
* [ ] `ocamlPackages_4_03`

2016-11-02 19:21 UTC, vbgl commented
You may want to look at the derivation for `topkg`, and make your `buildPhase` and `installPhase` similar to its: use `-I …` instead of a symlink; move (or link) the result directory to where it is expected by the nixpkgs version of `findlib`.

2016-11-02 20:09 UTC, sternenseemann commented
@vbgl Thank you, I will have a look at it.

2016-11-02 22:54 UTC, sternenseemann commented
@vbgl I updated it. That is clearly better.

2016-11-03 08:19 UTC, vbgl commented
The `installPhase` of `ptime` is not correct yet: you need to move or symlink the `$out/lib/ptime` directory to `$out/lib/ocaml/${ocaml.version}/site-lib`; otherwise, you won’t be able to use that package (at least, `ocamlfind` won’t find it).

2016-11-03 09:06 UTC, sternenseemann commented
@vbgl Thank you, I fixed it. Is this only an issue if using `opam-installer`?

2016-11-03 10:59 UTC, sternenseemann commented
Note: This PR depends on #20086, otherwise `opam` does not build.

2016-11-03 11:18 UTC, Profpatsch requested changes

2016-11-03 11:18 UTC, Profpatsch commented on pkgs/development/ocaml-modules/x509/default.nix
> +    license = stdenv.licenses.bsd2;
stdenv.licenses → stdenv.lib.licenses

2016-11-03 11:37 UTC, sternenseemann commented on pkgs/development/ocaml-modules/x509/default.nix
> +    license = stdenv.licenses.bsd2;
Fixed, thank you!

2016-11-03 11:38 UTC, sternenseemann commented on pkgs/development/ocaml-modules/ptime/default.nix
> +    ocaml pkg/pkg.ml build --with-js_of_ocaml false
Fixed. It is possible with `-I` as @vbgl pointed out earlier.

2016-11-03 12:03 UTC, Profpatsch requested changes

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/applications/networking/instant-messengers/jackline/default.nix
> +    description = "terminal-based XMPP client purely in OCaml";
All descriptions start with a capital letter and end with a `.`.

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/astring/default.nix
> +    description = "Alternative String module for OCaml";
`.`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/cstruct/default.nix
> + async_p4 ? null, lwt ? null, camlp4, ppx_tools ? null}:
It’ a lot nicer to explicitly create switches for those, then sane defaults can be enforced directly in the package function:

```nix
{ asyncSupport ? false, async_p4 ? null
, … }:

with stdenv.lib;
assert asyncSupport -> async_p4 != null;
…
  configureFlags = optional asyncSupport async_p4 ++ …
```

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/cstruct/default.nix
> +  checkTarget = "test";
needed?

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/erm_xmpp/0.3.nix
> +    description = "OCaml based XMPP implementation (fork)";
.

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/nocrypto/default.nix
> +{ stdenv, buildOcaml, fetchFromGitHub, ocaml, findlib, cstruct, type_conv, zarith, ounit, ocaml_oasis, ppx_sexp_conv, lwt ? null}:
see above cf. `null`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/notty/default.nix
> +{stdenv, buildOcaml, fetchFromGitHub, findlib, result, uucp, uuseg, uutf, lwt ? null}:
`null`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/uutf/default.nix
> -assert stdenv.lib.versionAtLeast ocaml.version "3.12";
`minimumSupportedOcamlVersion`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/applications/networking/instant-messengers/jackline/default.nix
> +assert stdenv.lib.versionAtLeast ocamlPackages.ocaml.version "4.02.2";
`minimumSupportedOcamlVersion`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/cstruct/default.nix
>  assert stdenv.lib.versionAtLeast (stdenv.lib.getVersion ocaml) "4.01";
`minimumSupportedOcamlVersion`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/nocrypto/default.nix
>  assert stdenv.lib.versionAtLeast ocaml.version "4.01";
`minimumSupportedOcamlVersion`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/notty/default.nix
> +  propagatedBuildInputs = [ lwt result uucp uuseg uutf ];
Aren’t those normal ocamlPackages?

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/notty/default.nix
> +    description = "Declarative terminal graphics for OCaml";
.

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/otr/default.nix
> +  doCheck = true;
needed?

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/otr/default.nix
> +    description = "Off-the-record (OTR) messaging protocol, purely in OCaml";
.

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/ptime/default.nix
> +  propagatedBuildInputs = [ result ];
buildInputs?

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/ptime/default.nix
> +    description = "POSIX time for OCaml";
.

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/tls/default.nix
> +{stdenv, buildOcaml, fetchFromGitHub, findlib, ocamlbuild, ocaml_oasis, ppx_tools, ppx_sexp_conv, result, x509, nocrypto, cstruct, lwt ? null}:
`null`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/tls/default.nix
> +  checkTarget = "test";
needed?

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/tls/default.nix
> +    description = "TLS in pure OCaml";
.

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/uuseg/default.nix
> +  name = "${pname}";
name = pname;

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/uutf/default.nix
> +  name = "${pname}";
`name = pname;`

2016-11-03 12:03 UTC, Profpatsch commented on pkgs/development/ocaml-modules/x509/default.nix
> +  configurePhase = "./configure --prefix $out $configureFlags";
Isn’t the prefix set automatically?

2016-11-03 12:22 UTC, sternenseemann commented on pkgs/development/ocaml-modules/cstruct/default.nix
> +  checkTarget = "test";
Yes.

2016-11-03 12:24 UTC, sternenseemann commented on pkgs/development/ocaml-modules/notty/default.nix
> +  propagatedBuildInputs = [ lwt result uucp uuseg uutf ];
Could you elaborate a bit?

2016-11-03 12:24 UTC, sternenseemann commented on pkgs/development/ocaml-modules/uutf/default.nix
> -assert stdenv.lib.versionAtLeast ocaml.version "3.12";
Is already used here.

2016-11-03 12:26 UTC, sternenseemann commented on pkgs/development/ocaml-modules/ptime/default.nix
> +  propagatedBuildInputs = [ result ];
No, is correct like this.

2016-11-03 12:26 UTC, sternenseemann commented on pkgs/development/ocaml-modules/tls/default.nix
> +  checkTarget = "test";
Yes.

2016-11-03 12:27 UTC, sternenseemann commented on pkgs/development/ocaml-modules/x509/default.nix
> +  configurePhase = "./configure --prefix $out $configureFlags";
Yes, but as `--prefix=$out` which `./configure` of this package can not parse.

2016-11-03 12:33 UTC, sternenseemann commented on pkgs/development/ocaml-modules/cstruct/default.nix
> + async_p4 ? null, lwt ? null, camlp4, ppx_tools ? null}:
Good point

2016-11-03 12:52 UTC, Profpatsch commented on pkgs/development/ocaml-modules/cstruct/default.nix
> +  checkTarget = "test";
doCheck as well?

2016-11-03 12:53 UTC, Profpatsch commented on pkgs/development/ocaml-modules/notty/default.nix
> +  propagatedBuildInputs = [ lwt result uucp uuseg uutf ];
Was about the propagated vs normal build inputs, apparently ocaml needs some packages propagated.

2016-11-03 13:07 UTC, sternenseemann commented on pkgs/development/ocaml-modules/notty/default.nix
> +  propagatedBuildInputs = [ lwt result uucp uuseg uutf ];
Yeah, indeed. If a package's interface is used in the module, it needs the package propagated, I guess.

2016-11-03 13:23 UTC, sternenseemann commented
@vbgl What do you think, do we still have to keep the checks for `lwt`? It seems to build fine with all ocaml versions.

2016-11-03 14:59 UTC, Profpatsch approved these changes

2016-11-03 15:02 UTC, merged

2016-11-04 07:38 UTC, vbgl commented
Reverting commit  32e86a3 fixes the `core_kernel` build. However, this breaks `nocrypto-0.5.3`. Should we revert this whole PR, which apparently deserves more testing?

2016-11-04 11:09 UTC, Profpatsch commented
@vbgl yes, let’s do that. OcamlPackages is still in an extremely unstable state.

2016-11-04 16:44 UTC, vbgl commented on pkgs/applications/networking/instant-messengers/jackline/default.nix
> +    description = "terminal-based XMPP client purely in OCaml";
[CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md) reads: “`meta.description` should […] Not have a dot at the end”

2016-11-04 16:51 UTC, vbgl commented
@sternenseemann would you like to open a new PR, or preferably (IMHA) several PRs, so that we can review and test independent changes independently.

Concerning `ptime` two nitpicking remarks: you don’t need to define `ocaml-version` as you can directly refer to `ocaml.version`; the `meta.description` should not end with a dot.

2016-11-04 17:47 UTC, sternenseemann commented
@vbgl sounds like a plan!