Add notmuch-mailmover package
NixOS/nixpkgs pull request #201203
Opened 2022-11-14 16:43 UTC by archer-65

###### Description of changes

This changes add `notmuch-mailmover`, a tool to move `notmuch` tagged mails into IMAP folders. This package is based on `afew`'s MailMover one, but easier (and more flexible) to configure.
[Homepage](https://github.com/michaeladler/notmuch-mailmover/)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-11-14 16:53 UTC, michaeladler commented
Being the author I guess I should maintain this package too if it's accepted :) So feel free to add me to the maintainer list if you like.

2022-11-14 16:57 UTC, archer-65 commented
> Being the author I guess I should maintain this package too if it's accepted :) So feel free to add me to the maintainer list if you like.

Done! I pinged you appositely :)

2022-11-15 07:59 UTC, michaeladler approved these changes

2022-11-15 09:54 UTC, archer-65 commented
Should we backport to 22.05?
@michaeladler

2022-11-15 09:57 UTC, michaeladler commented
I don't think so. 22.11 is in the currently in the making, so it could end up there if we are lucky or quick enough :)

2022-11-23 23:07 UTC, archer-65 commented
Any chance to see this package in 22.11?

2022-11-25 07:56 UTC, michaeladler commented
Probably best to ping someone with merge permissions on Matrix.

2022-12-03 15:01 UTC, RaitoBezarius commented on pkgs/applications/networking/mailreaders/notmuch/notmuch-mailmover.nix
> +{
This is not correctly formatted, it should be:
```
{ notmuch
, lib
, stdenv
, etc.
}:
```
(please take a look to the other files)

2022-12-03 15:01 UTC, RaitoBezarius commented on pkgs/applications/networking/mailreaders/notmuch/notmuch-mailmover.nix
> +  buildInputs = [notmuch];
`buildInputs = [ notmuch ];`

2022-12-03 15:01 UTC, RaitoBezarius commented on pkgs/applications/networking/mailreaders/notmuch/notmuch-mailmover.nix
> +    maintainers = with maintainers; [michaeladler archer-65];
`[ michaeladler archer-65 ]`

2022-12-03 15:01 UTC, RaitoBezarius requested changes
Once the minor formatting things are done, I can merge it. :)

2022-12-03 15:10 UTC, archer-65 reviewed
Done

2022-12-03 15:16 UTC, RaitoBezarius approved these changes

2022-12-04 14:38 UTC, merged