Improving systemd unit description
NixOS/nixpkgs pull request #20177
Opened 2016-11-05 08:21 UTC by spacekitteh

###### Motivation for this change
Makes cjdns actually require networking.

2016-11-05 14:23 UTC, groxxda commented
Why is the bindsTo needed?

2016-11-05 14:33 UTC, spacekitteh commented
Because it requires networking to be up before it can create a connection. If you have a slow-starting network connection, then cjdns will fail if it's started too soon after starting networking.

If networking goes down, then having cjdns running is pointless; I'm also not sure if it can even re-establish a connection after losing the network yet.

2016-11-07 06:29 UTC, groxxda commented
`networking.target` gives no guarantee that networking is _up_. You might want to depend on `network-online.target`

2016-11-07 06:34 UTC, groxxda commented
```
systemctl list-dependencies sleep.target --reverse --type=target --all 
sleep.target
● ├─systemd-hibernate.service
● │ └─hibernate.target
● ├─systemd-hybrid-sleep.service
● │ └─hybrid-sleep.target
● └─systemd-suspend.service
●   └─suspend.target
```
Depending on `sleep.target` should suffice, since the other three will pull in `sleep.target`

2016-11-08 01:40 UTC, spacekitteh commented
I guess I could just disable start rate limiting. I'll give that a try.

2016-11-08 02:11 UTC, spacekitteh commented
Well, it works now. \o/ I squashed the commits.

2016-11-08 06:57 UTC, MostAwesomeDude approved these changes
LGTM

I haven't tested but the submitter says that it works for them, so that works for me.

2016-11-10 02:33 UTC, grahamc commented
@groxxda what do you think of the current state?

2016-11-10 08:52 UTC, groxxda commented
I don't use cjdns so I cannot say anything about the issues @spacekitteh experienced.
At least the upstream service file does not require network-online, and I don't understand why this is needed here.

I don't know why ordering after network-online does not work, that may be a bug in the networking module. Of course I'd favor fixing the real issue and not working around it in clients with unlimited restarts, but that's just my opinion.
If it was broken before and works like this, it's clearly an improvement..

2016-11-10 12:27 UTC, spacekitteh commented
Is it good to merge?

2016-11-10 14:46 UTC, edolstra commented
Note my comment about systemd unit descriptions.

2016-11-10 15:20 UTC, spacekitteh commented
@edolstra Where?

2016-11-10 22:17 UTC, Mic92 commented on nixos/modules/services/networking/cjdns.nix
> +      postStop = "${config.systemd.package}/bin/systemctl systemctl reset-failed cjdns-restart.service";
`systemctl systemctl` is wrong in:

```
${config.systemd.package}/bin/systemctl systemctl reset-failed cjdns-restart.service
```

2016-11-10 22:18 UTC, Mic92 commented on nixos/modules/services/networking/cjdns.nix
> +          ${config.systemd.package}/bin/systemctl systemctl reset-failed cjdns.service
same as below

2016-11-10 22:28 UTC, Mic92 commented on nixos/modules/services/networking/cjdns.nix
> +      onFailure = ["cjdns-restart.service"];
Why is that needed?

2016-11-10 22:36 UTC, Mic92 commented
I don't think an attacker can perform an MITM: cjdns does end-to-end encryption based on addresses.

2016-11-10 22:37 UTC, Mic92 commented
@cjdelisle is it possible to implement a signal handler for SIGUSR2 to just reconnect to its peers? That would make the cjdns-restart.service cleaner IMHO.

2016-11-11 01:05 UTC, spacekitteh commented on nixos/modules/services/networking/cjdns.nix
> +      onFailure = ["cjdns-restart.service"];
Becuase cjdns requires the network to actually be online.

2016-11-11 01:08 UTC, spacekitteh commented on nixos/modules/services/networking/cjdns.nix
> +      postStop = "${config.systemd.package}/bin/systemctl systemctl reset-failed cjdns-restart.service";
Whoops, I forgot to remove that line

2016-11-11 20:48 UTC, Mic92 commented on nixos/modules/services/networking/cjdns.nix
> +      onFailure = ["cjdns-restart.service"];
From understanding this is the job of `Restart = "always";`, which does the same, right?

2016-11-12 13:32 UTC, grahamc requested changes

2016-11-12 13:32 UTC, grahamc commented on nixos/modules/services/networking/cjdns.nix
> +        "
Looks like this should either be a single-line string, or use
```
script = ''
  double single quotes
'';
```

2016-11-12 13:42 UTC, spacekitteh commented on nixos/modules/services/networking/cjdns.nix
> +        "
After rethinking I just deleted the -restart service altogether.

2016-11-28 03:08 UTC, grahamc commented
Merged in 0ea07968588f172538647c2f28bef03fdc90f0b2, thank you for your effort and time on this :)

2016-11-28 03:10 UTC, spacekitteh commented
\o/

2016-11-28 03:10 UTC, closed without merging