django_1_5: remove
NixOS/nixpkgs pull request #20195
Opened 2016-11-05 18:33 UTC by cko

###### Motivation for this change
Django 1.5 is no longer developed and should therefor be removed (see: https://www.djangoproject.com/download/)

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-11-05 18:46 UTC, FRidh commented
cc @lsix

2016-11-08 01:53 UTC, fpletz commented
As  this version of Django has security vulnerabilities and is not maintained by upstream anymore it should also be removed from 16.09.

2016-11-08 21:44 UTC, lsix commented
Hi (sorry for late reply).

At first sight, it looks good to me. Dropping django-1.5 would be nice. Maybe each individual updates can be separated into individual commits. I’ll review that PR properly ASAP (I have very limited access to my computer those days).

2016-11-14 08:29 UTC, lsix requested changes
Hi, thanks for the PR.

Could it be possible to:
- explicitly keep `django` as a [propagated] build input of `graphite_web`,
- separate the work in one commit for each affected derivation?

With that, it will be OK for me.

2016-11-14 08:29 UTC, lsix commented on pkgs/top-level/python-packages.nix
> +    propagatedBuildInputs = with self; [ django_tagging whisper pycairo ldap memcached ];
Even if `django_tagging` has `django` as a propagated build input, `django` should be listed as direct build dependency of graphite_web.

2016-11-14 21:53 UTC, cko commented
[x] done

2016-11-23 20:38 UTC, merged