systems/architecture: bump default architecture to westmere
NixOS/nixpkgs pull request #202526
Opened 2022-11-23 14:03 UTC by SuperSandro2000

Compile everything by default with SSE4.2, AVX, etc to gain free performance. This also removes support for any CPU older than westmere.

TODO:
- [ ] Do we want to enable this?
- [ ] Do all the hydra builders support this?
- [ ] Write a changelog entry

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-11-23 14:05 UTC, SuperSandro2000 commented
Just drafting so that no one merges it by accident but I still want feedback and discuss this.

2022-11-23 14:06 UTC, K900 commented
RHEL is on x86_64-v2 by default now: https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level

2022-11-23 14:07 UTC, K900 commented
Also we should probably add the x86_64-vX feature levels instead of using uarch names, because we want the featureset without the uarch specific codegen.

2022-11-23 15:38 UTC, NickCao commented
> The baseline is mostly defined by the gcc-N package, which is configured to produce baseline binaries when options like -march= are not used. - https://wiki.debian.org/ArchitectureSpecificsMemo#Architecture_baselines

Is that what this change does?

2022-11-24 14:53 UTC, thiagokokada commented
`x86-64-v2` (this PR) should be safe-ish to enable and brings a good performance boost.

I think Arch uses `x86-64-v3` (`haswell`), but maybe this is too much.

2022-11-24 15:13 UTC, SamLukeYes commented
> `x86-64-v2` (this PR) should be safe-ish to enable and brings a good performance boost.
> 
> I think Arch uses `x86-64-v3` (`haswell`), but maybe this is too much.

AFAIK, most of Arch packages are still using `x86-64`, though `x86_64_v3` architecture was added to [devtools](https://gitlab.archlinux.org/archlinux/devtools). [The RFC](https://gitlab.archlinux.org/archlinux/rfcs/-/blob/master/rfcs/0002-march.rst) is to keep both `x86_64` and `x86_64_v3` packages, instead of bumping the default architecture.

2022-11-27 22:21 UTC, SuperSandro2000 commented
> Also we should probably add the x86_64-vX feature levels instead of using uarch names, because we want the featureset without the uarch specific codegen.

I added a suggestion from me to this PR.

> Is that what this change does?

Yes, on first look.

> `x86_64_v3` packages, instead of bumping the default architecture.

We are currently not doing this because it would be equivalent of adding a new architecture because we would build everything twice.

2022-11-28 08:42 UTC, QuantMint commented
Some more cpu features shoul be added: POPCNT, LAHF-SAHF, CMPXCHG16B...
 https://en.wikipedia.org/wiki/X86-64#Microarchitecture_levels

2022-11-28 11:09 UTC, thiagokokada approved these changes
LGTM.

IMO, we should merge this ASAP to get early feedback on what it is going to break.

2022-11-28 11:21 UTC, K900 commented
Another one: https://www.phoronix.com/news/openSUSE-Tumbleweed-x86-64-v2

2022-11-28 11:21 UTC, K900 commented
Also, looks like we're still not actually setting `-march` with this, which we probably should do.

2022-11-28 11:26 UTC, NickCao commented
> Also, looks like we're still not actually setting `-march` with this, which we probably should do.

If we can configure our compilers to do that (produce baseline binaries when options like -march= are not used) by default, this would be redundant.

2022-11-29 00:32 UTC, SuperSandro2000 commented
> Some more cpu features should be added: POPCNT, LAHF-SAHF, CMPXCHG16B...

I am not sure if this will change much because I think gcc is already implying that but I'll leave the definitive answer to people that know a lot more than me about compilers.

> Also, looks like we're still not actually setting `-march` with this, which we probably should do.

Do you think we need to set ``nixpkgs.hostPlatform.gcc.march/mtune``?

2022-11-29 08:31 UTC, QuantMint commented
> > Some more cpu features should be added: POPCNT, LAHF-SAHF, CMPXCHG16B...
> 
> I am not sure if this will change much because I think gcc is already implying that but I'll leave the definitive answer to people that know a lot more than me about compilers.
> 
> > Also, looks like we're still not actually setting `-march` with this, which we probably should do.
> 
> Do you think we need to set `nixpkgs.hostPlatform.gcc.march/mtune`?
> 
> Going to undraft to collect more feedback because most of the open questions I cannot comfortable answer.
> 
> From my local testing I so far only found some breakages in already brittle python packages with comments like `round to 4 digests because that works for aarch64-linux` and some strange interaction with znver3 but at this point I am sure I messed something in my hacky configuration up.

Setting march would be a good idea, because in that case you can just set: [-march=x86-64-v2](https://gcc.gnu.org/onlinedocs/gcc/x86-Options.html)

2022-11-29 17:31 UTC, vcunat commented
> Do you think we need to set ``nixpkgs.hostPlatform.gcc.march/mtune``?

I like generic `mtune`, as we tend to default to relatively recent GCC.

>  As new processors are deployed in the marketplace, the behavior of this option will change.  Therefore, if you upgrade to a newer version of GCC, code generation controlled by this option will change to reflect the processors that are most common at the time that version of GCC is released.

2022-11-29 18:14 UTC, SuperSandro2000 commented
```
gcc -march=x86-64-v2 -Q --help=target | rg -e march -e mtune
  -march=                               x86-64-v2
  -mtune-ctrl=
  -mtune=                               generic
  Known valid arguments for -march= option:
  Known valid arguments for -mtune= option:
```

2022-11-29 18:43 UTC, SuperSandro2000 commented on lib/systems/architectures.nix
> +  };
I am not sure if we need those now at all after I added the microarchitecture levels to inferiors

2022-11-29 18:54 UTC, SuperSandro2000 commented on lib/systems/architectures.nix
> +  };
After realizing that we need those in inferiors there is no longer a usecase for this.

2022-11-29 18:55 UTC, SuperSandro2000 commented on lib/systems/platforms.nix
> +      arch = "x86_64-v2";
Nice, this is now by default set. I still think we should backport a different commit to add ``gcc-x86_64-v1`` and ``gcc-x86_64-v1`` system features to older releases to make remote builds easier possible.

2022-11-29 18:58 UTC, K900 commented on lib/systems/architectures.nix
> +    # Microarchitecture levels
Maybe link the ABI doc here so it's easier to cross-reference in the future?

2022-11-29 18:59 UTC, K900 approved these changes
LGTM other than the minor nit. Let's do this.

2022-11-29 19:13 UTC, vcunat commented
> Do all the hydra builders support this?

All x86 HW on Hydra.nixos.org is recent.  The oldest is probably a Skylake machine used for the `metrics` job.  (Obviously, if builder features would be required, that would need some re-deploys.)

2022-11-29 19:25 UTC, thiagokokada approved these changes

2022-11-29 19:38 UTC, lucasew approved these changes

2022-11-29 19:52 UTC, SuperSandro2000 commented
We have a problem already demonstrated by ofborg:

```
error: a 'x86_64-linux' with features {gccarch-x86_64-v2} is required to build '/nix/store/1d3i945hp1cgiwnrb50y80ps7d69qc29-python-setup-hook.sh.drv', but I am a 'x86_64-linux' with features {benchmark, big-parallel, kvm, nixos-test}
```

I am not sure how to properly solve this.

2022-11-29 20:02 UTC, vcunat commented
It would be possible to extend the default set in `nixos/modules/services/misc/nix-daemon.nix`, but that would probably need some advance time.  I expect it might be better to assume v2 by default for this purpose.

2022-11-29 20:25 UTC, SuperSandro2000 commented
> (There's probably just this chicken-egg problem, according to the code in `nix-daemon.nix`.

Yes

I just discovered another problem: The gcc used in bootstrap stage0 is to old to know about x86_64-v2 (or znver2)


```
 ▶ nix log /nix/store/rc71dmi1y059z137pn4vgnf9mr90grvh-expand-response-params.drv
https://cache.nixos.org/vjvl14cl72pdf2vhkzkfz2l4sjzl7j94.narinfo
https://nix-community.cachix.org/vjvl14cl72pdf2vhkzkfz2l4sjzl7j94.narinfo
https://tum-dse.cachix.org/vjvl14cl72pdf2vhkzkfz2l4sjzl7j94.narinfo
unpacking sources
patching sources
configuring
no configure script, doing nothing
building
cc1: error: bad value ('x86_64-v2') for '-march=' switch
cc1: note: valid arguments to '-march=' switch are: nocona core2 nehalem corei7 westmere sandybridge corei7-avx ivybridge core-avx-i haswell core-avx2 broadwell skylake skylake-avx512 cannonlake icelake-client icelake-server bonnell atom silvermont slm knl knm x86-64 eden-x2 nano nano-1000 nano-2000 nano-3000 nano-x2 eden-x4 nano-x4 k8 k8-sse3 opteron opteron-sse3 athlon64 athlon64-sse3 athlon-fx amdfam10 barcelona bdver1 bdver2 bdver3 bdver4 znver1 btver1 btver2 native; did you mean 'x86-64'?
```

I think we would need at least gcc11 in boostrapping. I also just discovered that x86-64-v1 is x86-64.

So what do we do now? Do we want to disable gcc.arch in boostrapping?

2022-11-29 20:34 UTC, thiagokokada commented
> So what do we do now? Do we want to disable gcc.arch in boostrapping?


I don't think there is any reason to set `-march` during bootstrap. It is not like this will be the compiler that will be used to build the packages.

2022-11-29 20:41 UTC, vcunat commented
Some of the packages built by that compiler will get retained into the final package set, as it is now.  For example, `glibc`.

2022-11-29 21:23 UTC, SuperSandro2000 commented
Found the problem. x86**-**64 not underscore

2022-11-29 21:26 UTC, PedroHLC commented
> We could use march westmere and mtune generic instead.

This could help with packages hard-coded to build on older GCCs.

2022-11-30 23:23 UTC, SuperSandro2000 commented
It evaled 🎉

2022-12-01 09:16 UTC, QuantMint commented
> Found one problem. x86 **-** 64 not underscore
> 
> We could use march westmere and mtune generic instead.
> 
> Edit: or not
> 
> ```diff
> --- old 2022-11-29 22:25:32.132595592 +0100
> +++ new 2022-11-29 22:25:48.454569891 +0100
> @@ -24,7 +24,7 @@
>    -mamx-int8                       [disabled]
>    -mamx-tile                       [disabled]
>    -mandroid                        [disabled]
> -  -march=                          x86-64-v2
> +  -march=                          westmere
>    -masm=                           att
>    -mavx                            [disabled]
>    -mavx2                           [disabled]
> @@ -130,7 +130,7 @@
>    -mpc32                           [disabled]
>    -mpc64                           [disabled]
>    -mpc80                           [disabled]
> -  -mpclmul                         [disabled]
> +  -mpclmul                         [enabled]
>    -mpcommit                        [disabled]
>    -mpconfig                        [disabled]
>    -mpku                            [disabled]
> ```

We should use nehalem instead of westmere, it's one instruction closer to x86-64-v2:
```diff
❯ diff westmere nehalem
27c27
<   -march=                     		westmere
---
>   -march=                     		nehalem
133c133
<   -mpclmul                    		[enabled]
---
>   -mpclmul                    		[disabled]
187c187
<   -mtune=                     		westmere
---
>   -mtune=                     		nehalem
```

2022-12-01 09:18 UTC, K900 commented
Maybe we should update the bootstrap GCC instead? This should allow us to get GCC 11 on aarch64 too (though the underlying issue is still not resolved).

2022-12-01 12:10 UTC, SuperSandro2000 commented
> We should use nehalem instead of westmere, it's one instruction closer to x86-64-v2:

Good catch!

> Maybe we should update the bootstrap GCC instead?

Lets do that in a follow step. So far we do not know if this even work completely and bumping the bootstrap things is always a bit more involved.

2022-12-01 14:33 UTC, QuantMint requested changes
I still see two problems:
1) aes is not present in **any** Microarchitecture level, but here it is included in 3 of them, it should be removed. Not even building with -march=nehalem enables aes:
```
gcc -march=nehalem -mtune=generic -Q --help=target

-maes                       		[disabled]
```
2) LAHF-SAHF, CMPXCHG16B.. etc should be enabled too. In fact: 
gcc -msse3 -mssse3 -msse4.2 -msse4.1 -Q --help=target
```
  -msahf                      		[disabled]
  -mcx16                      		[disabled]
...
```

2022-12-01 22:39 UTC, SuperSandro2000 commented
> aes is not present in **any** Microarchitecture level, but here it is included in 3 of them, it should be removed. Not even building with -march=nehalem enables aes:

>     2. LAHF-SAHF, CMPXCHG16B.. etc should be enabled too. In fact:
>        gcc -msse3 -mssse3 -msse4.2 -msse4.1 -Q --help=target

This is not for what that list is used for. It does not directly map to march or mtune and also does not impact it. The main purpose of it is to feed predicates at the end of the file and turn on aes if the processor supports it. This is then used as a boolean ``stdenv.hostPlatform.avx2Support`` inside of a package.

Since --march=broadwell also does not enable the aes but it is listed above I just keep it like it is right now. If it turns out to be a problem we can change it in staging-next or the next staging run.

2022-12-02 07:50 UTC, QuantMint approved these changes

2022-12-02 09:14 UTC, thiagokokada approved these changes

2022-12-03 16:00 UTC, vcunat commented
> `x86-64-v2` (this PR) should be safe-ish to enable and brings a good performance boost.

Does anyone have a reference about the performance boost?

I looked through threads around OpenSUSE and RHEL, without really finding any interesting measurements ([SPEC](https://jamborm.github.io/spec-2022-07-29-levels/index.html) isn't interesting to me for this purpose).  I fear that the difference for practical workloads might be non-measurable, except some very specific cases.  I mean, performance is about the only positive thing that can come from this PR, right?

2022-12-04 11:29 UTC, SuperSandro2000 commented
I only have a system fully compiled with march=skylake. First of all booting seems to be way faster on zfs with a luks beneath. Both systems used nearly the same flack.lock with the exception of some build fixes.
```diff
--- none    2022-12-04 12:11:01.707783764 +0100
+++ skylake 2022-12-04 12:21:26.912490938 +0100
@@ -1,2 +1,2 @@
-Startup finished in 13.787s (firmware) + 2.206s (loader) + 11.297s (kernel) + 2.295s (userspace) = 29.587s
-graphical.target reached after 2.295s in userspace.
+Startup finished in 6.539s (firmware) + 1.525s (loader) + 11.370s (kernel) + 2.240s (userspace) = 21.675s
+graphical.target reached after 2.240s in userspace.
``` 

I don't have any other idea how to provide meaningful other results that are not purely benchmarks.

2022-12-04 12:47 UTC, Shawn8901 commented
> I only have a system fully compiled with march=skylake. First of all booting seems to be way faster on zfs with a luks beneath. Both systems used nearly the same flack.lock with the exception of some build fixes.
> 
> ```diff
> --- none    2022-12-04 12:11:01.707783764 +0100
> +++ skylake 2022-12-04 12:21:26.912490938 +0100
> @@ -1,2 +1,2 @@
> -Startup finished in 13.787s (firmware) + 2.206s (loader) + 11.297s (kernel) + 2.295s (userspace) = 29.587s
> -graphical.target reached after 2.295s in userspace.
> +Startup finished in 6.539s (firmware) + 1.525s (loader) + 11.370s (kernel) + 2.240s (userspace) = 21.675s
> +graphical.target reached after 2.240s in userspace.
> ```
> 
> Also add a small difference for me entering the encryption password. Not sure how meaningful that data is. Could also be that my method was not very reproducible.
> 
> I don't have any other idea how to provide meaningful other results that are not purely benchmarks.
> 
> For compiling gcc-11: nixos-unstable: 30m 30s nixos-unstable-simd with march skylake: 35m 45s

Possibly a stupid question, but do you use that PR branch directly or something else which does include other commits from staging? I wanted to try that for a znver2 but fail on libxcrypt (where you pointed out that there are some changes on staging). I haven't invested to much time yet and currently cannot provide error logs (as I am not at home) but thought maybe a quick question could help me out there.
Thanks in advance and thanks for the work to bring a newer architecture level to the binary cache ♥️

2022-12-04 18:18 UTC, SuperSandro2000 commented
I used this branch https://github.com/SuperSandro2000/nixpkgs/compare/nixos-unstable...SuperSandro2000:nixpkgs:nixos-unstable-simd which indeed contains commits for libxcrypt which are right now only on staging.

2022-12-17 11:39 UTC, RaitoBezarius approved these changes

2022-12-17 11:39 UTC, RaitoBezarius commented
@SuperSandro2000 Is there anything preventing us from merging this PR? Thank you a lot!

2022-12-22 12:00 UTC, vcunat commented
> For compiling gcc-11:
nixos-unstable: 30m 30s
nixos-unstable-simd with march skylake: 35m 45s

Maybe I'm being stupid, but the numbers sound like slow-down, not speed-up.

2022-12-22 13:07 UTC, Artturin commented
> > For compiling gcc-11:
> > nixos-unstable: 30m 30s
> > nixos-unstable-simd with march skylake: 35m 45s
> 
> Maybe I'm being stupid, but these numbers sound like slow-down, not speed-up.

Compilation times may be slower for some packages, I'd be interested in the compile times of what that gcc compiles

2022-12-22 20:20 UTC, samueldr commented
> Compile everything by default with SSE4.2 to gain free performance.

Was this assertion verified? How much are we talking?

Furthermore, do we have an idea of how popular or how unpopular the CPU generations left behind are with our users? I'm thinking mainly about server-ish hardware, e.g. inexpensive colocated server offers, re-purposed older computers. Desktop and laptops from Core i[0] and before are not really likely to be still in use, I suppose.

How likely are we to suddenly make NixOS unusable on someone's deployment?

Do we have a migration path to prevent activating a generation that can't be used on a incompatible hardware? It would be awkward if a remote system *that may not have proper remote console access* is updated and now suddenly can't run the software.

Shouldn't this go through an RFC beforehand?

2022-12-23 07:21 UTC, SuperSandro2000 commented
> Maybe I'm being stupid, but these numbers sound like slow-down, not speed-up.

The numbers are not representative. They are over one build each and there might be other factors involved that influenced them.

> Was this assertion verified? How much are we talking?

Generally you can say depends. Some software benefits majorly from being compiled with newer instructions while others sees no change.

> Furthermore, do we have an idea of how popular or how unpopular the CPU generations left behind are with our users?

No, we have nothing like debian popcon.

> How likely are we to suddenly make NixOS unusable on someone's deployment?

Should be pretty unlikely. We are talking about CPUs from the core 2 duo era, before the i branding was a thing. The better Xeon CPUs have a whopping 4 threads and max 16 GB of RAM across all slots.

> Do we have a migration path to prevent activating a generation that can't be used on a incompatible hardware? It would be awkward if a remote system that may not have proper remote console access is updated and now suddenly can't run the software.

No, like for any other software update or change we do. This is already a gamble with every update and eventually it will fail. Right now nothing prevents programs from enabling sse3/4 or avx in their build scripts and some already do that.

> Shouldn't this go through an RFC beforehand?

I am not volunteering for that.

2022-12-23 08:04 UTC, samueldr commented
> > Was this assertion verified? How much are we talking?
> 
> Generally you can say depends. Some software benefits majorly from being compiled with newer instructions while others sees no change.

So this is done without any metrics for benefits, got it. I don't mind the change if there is a good rationale and actual day-to-day gains, but otherwise it sounds like cargo-culting and/or superstition.

> > Furthermore, do we have an idea of how popular or how unpopular the CPU generations left behind are with our users?
> 
> No, we have nothing like debian popcon.
> 
> > How likely are we to suddenly make NixOS unusable on someone's deployment?
> 
> Should be pretty unlikely. We are talking about CPUs from the core 2 duo era, before the i branding was a thing. The better Xeon CPUs have a whopping 4 threads and max 16 GB of RAM across all slots.

This includes the very start of the `i` branding, unless for some reason Nehalem, which is older than Westmere, doesn't count... it is unclear. I'm going from the PR description which states *older than Westmere*.

Though this is exactly the kind of hardware I expect to see sitting as the way older system running one's on-the-cheap NAS or home server. Not everyone is upgrading every few years and left with recent hardware to run as a home server.

This is also the kind of hardware that was heavily advertised by some cloud operators, and still is! I can start renting a "fresh new" (used) dedicated server without SSE4.x support without actually searching for it. In fact it's the first result from that vendor. *Atom N2800*, cedarview, is newer than Westmere by approximately a year, and yet still doesn't support SSE4.

> Also this won't happen suddenly. unstable is unstable and breakages can and happened in the past and for a stable update people are expected to read the changelog and this change is the first entry.

This will happen suddenly. The change will happen suddenly. The whole world will be rebuilt. What may not be sudden is software that stops working. It will not include any sort of verification that requires the CPU to have the required instructions.

So in many ways, unless I'm wrong, this is way worse, since things will appear to work after an update, but some things will throw `SIGILL` hapazardly. A clear "this CPU cannot run this software" would be preferable here.

And "unstable is unstable" is a bad take. Its name is a shame, but it should be named *rolling*, which is rolling-up changes to the next release. For all intents and purpose, it is a rolling release, and should be treated as always green. Breakage is not fine.

Another way to see this, while you say "this won't happen suddenly", this will happen for the next release, so within six months someone with such hardware will have no way forward, even on stable. Suddenly at release time they are left with about a month of updates to figure out a solution.

> > Do we have a migration path to prevent activating a generation that can't be used on a incompatible hardware? It would be awkward if a remote system that may not have proper remote console access is updated and now suddenly can't run the software.
> 
> No, like for any other software update or change we do. This is already a gamble with every update and eventually it will fail. Right now nothing prevents programs from enabling sse3/4 or avx in their build scripts and some already do that.

And yes, this is already an issue. We've had software fail to build hapazardly with `SIGILL` since it built on older hardware than dependencies did on our diverse builders previously.

So since we already have a problem with unbounded impurities from the ambiant environment, it's fine to now break it in another way? This is a weird leap of logic, unless I'm missing what you meant here.

> > Shouldn't this go through an RFC beforehand?
> 
> I am not volunteering for that.

Right, but shouldn't this go through an RFC beforehand?

2022-12-23 12:58 UTC, thiagokokada commented
> This is also the kind of hardware that was heavily advertised by some cloud operators, and still is! I can start renting a "fresh new" (used) dedicated server without SSE4.x support without actually searching for it. In fact it's the first result from that vendor. Atom N2800, cedarview, is newer than Westmere by approximately a year, and yet still doesn't support SSE4.

Would be curious to know which distros this cloud operators supports. Like someone said above, RHEL already dropped `x86_64-v2` it seems, and considering they're one of the slowest moving distros out there I would assume others distros already did the same or will do soon(TM).

2022-12-23 16:00 UTC, RaitoBezarius commented
RHEL rationale: https://developers.redhat.com/blog/2021/01/05/building-red-hat-enterprise-linux-9-for-the-x86-64-v2-microarchitecture-level#background_of_the_x86_64_microarchitecture_levels
Archlinux RFC: https://gitlab.archlinux.org/archlinux/rfcs/-/merge_requests/2/diffs (mentions of improvements)
OpenSUSE: https://www.theregister.com/2022/11/30/opensuse_drops_x86_32/

Here: https://www.theregister.com/AMP/2022/07/26/suse_adaptable_linux_platform/ it is said x86_64-v2 processors are around ~2008-2011. 

In my personal experience of homelabbing and cloud providers (famous Atom processors), those processors are in circulation, taking a PowerEdge R710 (which are now VERY old, power hungry, etc.), the processors in there are also of Nehalem generation.

Certainly, PowerEdge 2850 (Intel Xeon SL8MA TD428 for example.) and similar servers are not going to support NixOS with this change.

But I am in favor of getting those machines recycled honestly, I am not sure keeping them around is benefitting anyone, be it electricity, ecology, maintenance people, inherit risk of having them in your assets.

That being said, on my NextCloud virtual machine on an x86_64-v3 baremetal server (PowerEdge R720), I do spend a lot of time in the kernel doing `crypto_aes_encrypt` (measured with `perf`). I think having a `aes-ni`-enabled OpenSSL would bring "easy" improvements though I did not measure them yet.

If we do decide to stay on x86_64, I would argue, given the fact that everyone who switched to that level, *including enterprise distributions*, the burden of the proof, i.e. collecting the fact that there are still too many offerings for this machine and potential actual users, are on the people who want to maintain this status-quo.

Of course, our alternatives could be:

- to duplicate the jobsets if we can get more hands and money to have builders for that, but if we could do that, I would spend that money on getting x86_64-v3.
- offering a non-rolling release Hydra for x86_64 (sounds reasonable to me)

etc.

2022-12-23 16:06 UTC, RaitoBezarius commented
@SuperSandro2000 Could we split the changes and upstream on master the bare minimum to support the final switch (without introducing unwanted changes?)?

I would like to make it easy to propagate the switch and try it.

2022-12-30 19:16 UTC, SuperSandro2000 commented
> So this is done without any metrics for benefits

Do you have a suggestion how to get some meaningful metrics? We could do some benchmarks but they are meaningless for day to day usage. I don't think you can generally say this will improve things in every possible scenario but overhaul it should have a positive impact. 

> 'm going from the PR description which states _older than Westmere_.

forgot to update that

> Though this is exactly the kind of hardware I expect to see sitting as the way older system running one's on-the-cheap NAS or home server. Not everyone is upgrading every few years and left with recent hardware to run as a home server.

I also expect those systems to not have enough RAM to evaluate themselves and need to be remotely deployed.

> This is also the kind of hardware that was heavily advertised by some cloud operators, and still is! I can start renting a "fresh new" (used) dedicated server without SSE4.x support without actually searching for it. In fact it's the first result from that vendor. _Atom N2800_, cedarview, is newer than Westmere by approximately a year, and yet still doesn't support SSE4.

Which? One of the best price/performance provider in Germany, Hetzner, is giving out skylake for their virtual machines. I also checked ovh and the oldest server I could find had a CPU from 2011.

> This will happen suddenly. The change will happen suddenly. The whole world will be rebuilt. What may not be sudden is software that stops working. It will not include any sort of verification that requires the CPU to have the required instructions.

For other major breaking changes we also only wrote an entry into the changelog, unless I am forgetting one where we took special care to handle it.

We could add a check to the activation script to just fail if the cpu is to old.

> So in many ways, unless I'm wrong, this is way worse, since things will appear to work after an update, but some things will throw `SIGILL` hapazardly. A clear "this CPU cannot run this software" would be preferable here.

Then people did not read the changelog. Also after this PR it is clear what the oldest supported CPU arch is. Right now it is unclear and in reality some software already is not working on old hardware.

> Right, but shouldn't this go through an RFC beforehand?

I like to spend my time on other tasks where I directly feel the impact instead of spending on discussions. 

> to duplicate the jobsets if we can get more hands and money to have builders for that, but if we could do that, I would spend that money on getting x86_64-v3.

I personally think this would be a waste of builders and storage if we duplicate everything.

> Could we split the changes and upstream on master the bare minimum to support the final switch (without introducing unwanted changes?)?

#208398 not much, we still have 4 commits in this PR.

2023-01-01 23:55 UTC, blitz commented
From the discussion, I see the following points:

- We lack a good set of benchmarks. :)
- It would be nice, if people could try the different settings for their own workloads.
- There is still a bit of 10+ years hardware in service that would be affected. The upgrade experience for those people would be poor.
- Forcing people to throw away hardware sucks for the environment. Giving people less efficient software also sucks for the environment.

Personally, I think one way forward would be:

Make different default optimization settings easy to try out (like @RaitoBezarius said). Otherwise, it's hard to get any data. Then make an informed decision based on that.

2023-01-19 08:28 UTC, surfaceflinger commented
I think doing it like Arch folks plan to is better. Instead of dropping x86-64-v1, make caches for both. Also, instead of -v2 it would be better to jump straight to -v3 which supports eg. AVX2. Benchmark results comparing v1, v2 and v3 are on [Arch mailing list](https://lists.archlinux.org/pipermail/arch-general/2021-March/048739.html)

2023-01-19 09:28 UTC, vcunat commented
We can't keep making all binaries for both.  It would be way too expensive, in comparison to the advantages.

2023-01-19 09:42 UTC, surfaceflinger commented
> We can't keep making all binaries for both. It would be way too expensive, in comparison to the advantages.

Sadly, that's expected. I guess what would be left from my idea is comparing gcc-built and llvm-built -v2. But I don't have resources to do that :(

2023-01-20 13:29 UTC, SuperSandro2000 commented
> We lack a good set of benchmarks. :)

The problem with benchmarks is, that they do not represent real world and any benchmark that uses multi step instructions from the last 15 years will show a significant difference. Based on our test selection this will either bring the performance boost of the century or not change anything at all.

> It would be nice, if people could try the different settings for their own workloads.

Not possible without a complete rebuild. replaceRuntimeDependencies is also not an option because it forces hydra to build packages at evaluation time.

> There is still a bit of 10+ years hardware in service that would be affected.

We are talking about 15+ years. Nehalem is from 2008.

> We can't keep making all binaries for both. It would be way too expensive, in comparison to the advantages.

Yes, we would waste a lot of compute and storage on that. I think it is feasible to build unstable-small or only stdenv to make using older versions less painful though.

> my idea is comparing gcc-built -v2 and llvm-built -v2. But I don't have resources to do that :(

That is out of scope of this PR and won't solve the problems we are discussing. Many programs for linux expect gcc and llvm has subtle differences that would require manual fixing.

---


NixOS is a fast moving distro, especially compared to LTS enterprise Distros like Ubuntu, Suse or RedHat. If they can bump the default architecture, then we can do it, too.

2023-01-20 14:04 UTC, vcunat commented
> If they can bump the default architecture, then we can do it, too.

IIRC Suse will keep providing all binaries for older machines as well, so IMHO that's a key difference.  (I don't recall situation in other distros.)

2023-01-21 15:36 UTC, rodrgz commented
> Yes, we would waste a lot of compute and storage on that. I think it is feasible to build unstable-small or only stdenv to make using older versions less painful though.
> 
> >

I think it is enough for the scenarios in which these old servers will be used.

2023-01-27 07:12 UTC, Shawn8901 commented
About the question with the bootstrapping `-march`,[ this commit](https://github.com/NixOS/nixpkgs/commit/82226d83bc1e45476851897defafcbbc61ba79ac) add the microarchitectures also to the cc-wrapper logic (which is not a bad idea anyways), and that seems to solve the bootstrapping issue on my setup. 
I am currently building some x86-64-v3 to play around. Before i had a commit which removed the `-march` and `-mtune` from the boostrapping phase, but i wasnt really happy with that.

2023-02-12 23:27 UTC, SuperSamus commented on nixos/doc/manual/release-notes/rl-2305.section.md
> +- On x86 platforms nixpkgs is now build by default with the `x86_64-v2` microarchitecture level.
"built" instead of "build"

2023-02-18 16:45 UTC, SuperSandro2000 commented on nixos/doc/manual/release-notes/rl-2305.section.md
> +- On x86 platforms nixpkgs is now build by default with the `x86_64-v2` microarchitecture level.
```suggestion
- On x86 platforms nixpkgs is now built by default with the `x86_64-v2` microarchitecture level.
```

2023-02-18 16:46 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/best-practice-to-automaticly-build-all-installed-packages-to-put-them-into-a-binary-cache/25527/6

2023-02-19 07:26 UTC, peterhoeg commented
This change would mean I need to replace my firewall. It's not the end of the world of course, but I am definitely in the "let's get some numbers"-camp before moving ahead with this.

And asking people how they "feel" things are before and after this change is completely and utterly worthless. 

To me, this comes down to:

1. either we can measure the resulting performance boost (and as it turns out, some workloads seem to be slower too, so we absolutely need to know what those are), or
2. we have architectural reasons for doing this

If it's none of the above, what exactly do we gain?

2023-04-26 11:57 UTC, Atemu commented
Drafting since this is not currently mergable from a community perspective.

2023-05-06 09:07 UTC, amjoseph-nixpkgs commented
> Nehalem was chosen because the bootstrap gcc is to old to know westmere.

Now that we have the bootstrap files totally isolated from the built stdenv, we can one set of `-march=` flags when calling the bootstrap compiler and a different set when calling `xgcc` and `stdenv.cc`.

This is now possible because we never link binaries built by the bootstrap compiler to binaries built by `xgcc` or `stdenv.cc`.

So, if it is useful to you, you can ignore the bootstrap gcc constraint.

2023-06-14 16:43 UTC, Flakebi commented
For what it’s worth, I wanted to know how fast I can get made a `-march=znver3` to compile clang.
My benchmark – compiling SuperTuxKart (2 runs) – went from 30 s (clang compiled in default stdenv) to 31 s (clang compiled in stdenv with znver3).

At least in this case, there wasn’t much to gain.

2023-06-14 19:21 UTC, Shawn8901 commented
The gain(s), if any, aren't likely in compile time. As znver3 has another instruction set, which may result in "faster" execution time in some cases. Interesting benefits are likely on all those SIMD. As example this PR (defaulting to x86-64-v2) would enable compilation with SSE3 instructions. There are usecases that will possibly benefit in runtime execution if that instructions are usable. 
If there is a measurable and reliable performance increase 
on the daily jobs is another question. (Which was the main discussion on the PR so far). Because enabling that instructions will result that older CPUs without those instructions will not be able to run the code.

Tho that is not really related to this PR as znverX is already possible (even without that PR) but it's not the default (which i obviously a good idea, as not everyone has a znver3 compatible CPU), but you can still use that by setting GCC arch with the respective value, but you will result in compile everything by yourself when setting that globally.

2023-06-14 20:06 UTC, Flakebi commented
To clarify, I did compare the _runtime performance_ of an application compiled with gcc and znver3.
That application happened to be clang (because compilation is where I care most about performance). The flags I passed to clang to compile SuperTuxKart were the same in both cases I compared.

I was hoping that any improvement I see with znver3 is at least as good as x86-64-v2, which should be a subset/more general optimizations.
Apparently, clang is not a workload that benefits from that.

2023-06-14 20:09 UTC, K900 commented
The difference between v2 and higher feature levels is mostly vector extensions, so it's to be expected a compiler (which is mostly pointer chasing) doesn't gain much here.

2023-07-29 13:32 UTC, peterhoeg commented
Here are some benchmarks from arch where the person running it kindly did a tl;dr which I am pasting here:

    - there is no or negligible performance benefit of *-march=nehalem*, which corresponds to x86_64-v2,

    - there is a moderate benefit of *-march=haswell* (x86_64-v3) - of around 10%-20% as compared to baseline for the tests performed

Link: https://lists.archlinux.org/pipermail/arch-general/2021-March/048739.html

I know it's a sample size of 1, but I would argue that the burden of proof with regards to demonstrating any benefit now lies with those proposing this change. The argument that "well, everyone else is doing it" doesn't carry much weight in this.

2023-07-29 13:50 UTC, peterhoeg commented
One thing I forgot (apologies for the comment spam) is if we do start looking at potential benefits and *where* we stand to gain something from this (full disclosure: I'm very much not a compiler guy).

1. either the act of building software is faster because the compilers benefit from this (use less energy, can get critical fixes shipped faster, can build more with less and so on), or
2. the resulting software runs faster (or uses fewer resources) - who doesn't like free speed?

I would imagine, that most of the software that really stands to benefit already has optimizations for various cpus/cpu features where we would gain nothing from fiddling with the baseline flags.

So could we compile variants of the compilers with a better baseline and use that when available? This way there would be no sudden breakage for end users?

2023-07-29 13:56 UTC, vcunat commented
You can't do this "when available" that easily.  What would people with older computers do?  **Impurely** switch their compiler variant?  Or would we compile everything twice (e.g. base + -v3)?

2023-07-29 14:13 UTC, RaitoBezarius commented
> Here are some benchmarks from arch where the person running it kindly did a tl;dr which I am pasting here:
> 
> ```
> - there is no or negligible performance benefit of *-march=nehalem*, which corresponds to x86_64-v2,
> 
> - there is a moderate benefit of *-march=haswell* (x86_64-v3) - of around 10%-20% as compared to baseline for the tests performed
> ```
> 
> Link: [lists.archlinux.org/pipermail/arch-general/2021-March/048739.html](https://lists.archlinux.org/pipermail/arch-general/2021-March/048739.html)
> 
> I know it's a sample size of 1, but I would argue that the burden of proof with regards to demonstrating any benefit now lies with those proposing this change. The argument that "well, everyone else is doing it" doesn't carry much weight in this.

This was mentioned in https://github.com/NixOS/nixpkgs/pull/202526#issuecomment-1364066124 :).
It is not sufficient though.

> I would imagine, that most of the software that really stands to benefit already has optimizations for various cpus/cpu features where we would gain nothing from fiddling with the baseline flags.

> So could we compile variants of the compilers with a better baseline and use that when available? This way there would be no sudden breakage for end users?

Someone needs to do the rigorous work of looking into which packages benefit the most currently, see Guix prior art on that.

2023-07-29 14:50 UTC, peterhoeg commented
>  Or would we compile everything twice (e.g. base + -v3)?

Compile the compilers twice and abuse FOD…

I said it was an idea - not that it was a *good* idea.

2023-07-31 21:38 UTC, amjoseph-nixpkgs commented
> (full disclosure: I'm very much not a compiler guy).

There's a bit of a Schrodinger's Developer problem here; the people who really care about this stuff are already building everything themselves.

My `nix` is patched to remove the Hydra key, so I don't really care.

2023-08-28 19:22 UTC, kjeremy commented
It looks like CentOS is investigating what a jump to v3 might look like: https://blog.centos.org/2023/08/centos-isa-sig-performance-investigation/

2023-08-28 23:26 UTC, sergv commented
I'd be intrerested to revisit reasons of other distros for switching to x86-64-v2, e.g. RedHat. Do they apply in NixOs' case? Or are they completely unapplicable to the NixOs? It's "do it because everyone else is doing it" kind of argument, but my point is why is everyone else doing it? They stand dropping support for old hardware just like NixOs does but still they decide to go ahead. What makes NixOs's situation different from everyone else's?

2023-08-28 23:29 UTC, RaitoBezarius commented
Right now, in NixOS, we decided to postpone as no one came with compelling
evidence that v2 provides serious benefits.

I am trying to assemble a recent unstable v2 and v3 system and build a
"relevant" benchmark to see what's going on.

But it takes time and resources.

In the meantime, there's no reason to break older hardware I suppose.

Le mar. 29 août 2023 à 02:26, Sergey Vinokurov ***@***.***> a
écrit :

> I'd be intrerested to revisit reasons of other distros for switching to
> x86-64-v2, e.g. RedHat. Do they apply in NixOs' case? Or are they
> completely unapplicable to the NixOs? It's "do it because everyone else is
> doing it" kind of argument, but my point is why is everyone else doing it?
> They stand dropping support for old hardware just like NixOs does but still
> they decide to go ahead. What makes NixOs's situation different from
> everyone else's?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/202526#issuecomment-1696558456>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACMZRHTFF4Y6VGVGFERS2TXXUSKRANCNFSM6AAAAAASI77324>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-08-29 06:05 UTC, vcunat commented
AFAIK the other distros don't do it without replacement and still provide also binaries for older CPUs.  This PR's proposal didn't do that.  (And actually I don't think this is worth doubling build and storage costs for the x86 infra parts.)

2023-09-05 17:05 UTC, Nyabinary commented
https://www.phoronix.com/news/CentOS-ISA-Experiment-Perform
CentOS is looking at v3 **baseline**

2023-09-05 17:07 UTC, K900 commented
As I said on Matrix, CentOS can afford to do that because CentOS has very long release cycles, so people on CentOS N-1 will remain supported for many years to come. For NixOS, the switchover would take _at most_ 6 months, which is not nearly enough time to cut off support for all pre-2015 hardware.

2023-09-06 12:27 UTC, lucasew commented
Isn't there some kind of cflag to automatically create variants that use these features and decide in runtime which function sets will be used?

The examples cited here [1] have like explicit definitions but is there something that can kind of ramp up to more recent instructions?

For example, a math heavy library could generate more than one variant of loop heavy objects and some kind of logic to decide at runtime using the CPUID instruction which code variant will run.

IDK tbh if this is possible in single file binaries. The common approach for BLAS-like libraries for example is to generate a dynamic library for each variant then decide at runtime which one to dlopen.

[1] https://lwn.net/Articles/691932/

2023-11-23 18:03 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/pre-rfc-moving-nixos-x86-64-baseline-to-x86-64-v3/35924/2

2023-11-23 19:30 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/pre-rfc-gradual-transition-of-nixos-x86-64-baseline-to-x86-64-v3-with-an-intermediate-step-to-x86-64-v2/35924/1

2024-04-30 04:24 UTC, LDprg commented
Any news on this? Would really like to see a v2 baseline for Nixos.

2024-04-30 06:51 UTC, Atemu commented
See the discourse thread above.

To summarise:

To our current knowledge, there is no *good data* that proves a benefit from bumping to x86_64-v2. There might be a benefit but we don't actually know whether it exists or not. If it exits, it will be rather small though. (Note that there is a decent amount of bad data on this.)

There is no good data on how many users a bump beyond x86_64-v1 would exclude either. Anectdata suggests that there are at least some.

IMHO, this bump will require an RFC. Perhaps we should close this to signal this a bit clearer.

2024-04-30 07:29 UTC, LDprg commented
What about duplicated nixos channels (at least for stable), where one is the generic one and the other is compiled with x86-64-v3? This wouldn't deprecate any platform and it is also the way cachyos handles this.

The problem with selectively compiling packages with x86-64-v3, which could improve the most, is that if I for example compile gcc this will retrigger a recompilation of my whole system. I did not find a way around this problem.

Maybe there should be a flag to prevent such rebuild at the cost of reproducability?

2024-04-30 07:33 UTC, K900 commented
We do not have the hardware to build multiple channels. You can use `system.replaceRuntimeDependency` if you really want to. But also, x86_64-v3 also does not improve things much, and we can likely get very close in terms of performance with some dynamic dispatch.

2024-04-30 07:33 UTC, closed without merging