Add protobuf 3.1.0
NixOS/nixpkgs pull request #20291
Opened 2016-11-09 21:08 UTC by nlewo

###### Motivation for this change
Add the latest version of protobuf and keep older one since some projects requires some specific protobuf version.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-11-09 21:21 UTC, bachp commented on pkgs/top-level/all-packages.nix
> +  protobuf3_1 = lowPrio (callPackage ../development/libraries/protobuf/3.1.nix { });
Why is this marked as low prio?

2016-11-10 00:56 UTC, fpletz requested changes
Looks good overall, but please change the title of the second commit to "protobuf3_1: init at 3.1.0" to comply with our guidelines in the nixpkgs manual.

2016-11-10 00:57 UTC, fpletz commented on pkgs/top-level/all-packages.nix
> +  protobuf3_1 = lowPrio (callPackage ../development/libraries/protobuf/3.1.nix { });
`lowPrio` means that the binaries (in this case protoc) will have a lower prio than those from other store paths if more than one are referenced in the same environment.

2016-11-10 07:06 UTC, nlewo commented on pkgs/top-level/all-packages.nix
> +  protobuf3_1 = lowPrio (callPackage ../development/libraries/protobuf/3.1.nix { });
It was marked as low prio because 3.0.0 was marked as low prio... I finally unmark the latest version (3.1.0).

2016-11-10 07:58 UTC, nlewo commented
The CI failed is due to #20307. I will rebase if #20307 is merged to make CI happy.

2016-11-11 12:45 UTC, rasendubi commented on pkgs/development/libraries/protobuf/generic-v3.nix
> +{ stdenv, version, src
Could it take `version` and `sha256` instead of full `src`? (That would simplify calls to the functions.)

2016-11-12 08:30 UTC, nlewo commented on pkgs/development/libraries/protobuf/generic-v3.nix
> +{ stdenv, version, src
Done for v3.x. Not applied for v2.x since src fetch methods are not identical across minor versions.
Thanks for your comment.

2016-11-12 11:12 UTC, rasendubi approved these changes

2016-11-15 08:52 UTC, nlewo commented
@fpletz I applied your requested changes.

2016-11-15 12:14 UTC, merged

2016-11-15 12:14 UTC, rasendubi commented
@nlewo thank you!