vndr: init at 20161110-cf8678f
NixOS/nixpkgs pull request #20318
Opened 2016-11-10 20:47 UTC by vdemeester

###### Motivation for this change

[vndr](https://github.com/LK4D4/vndr) is a simple *golang* vendoring tool, which is inspired by docker vendor script that I tend to use on several projects.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] <del>Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`</del>
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

2016-11-10 21:02 UTC, kevincox approved these changes

2016-11-10 21:02 UTC, kevincox commented on pkgs/development/tools/vndr/default.nix
> +  version = "20161110-${stdenv.lib.strings.substring 0 7 rev}";
I think you can use `lib.substring` here.

2016-11-10 21:02 UTC, kevincox commented on pkgs/development/tools/vndr/default.nix
> +    licence = stdenv.lib.licenses.asl20;
I think you can drop the `stdenv` from both of these.

2016-11-10 21:17 UTC, kevincox requested changes

2016-11-10 21:17 UTC, kevincox commented on pkgs/development/tools/vndr/default.nix
> +  src = fetchgit {
Please use `fetchFromGitHub`

2016-11-22 13:38 UTC, vdemeester commented
/ping @kevincox

2016-11-22 14:01 UTC, fpletz approved these changes

2016-11-24 19:44 UTC, kevincox approved these changes

2016-11-24 19:44 UTC, kevincox commented
Looks good to me, I would like to see this merged.

2017-01-12 17:40 UTC, merged