seamly2d: init at 2022-08-15.0339
NixOS/nixpkgs pull request #203614
Opened 2022-11-29 14:31 UTC by WhittlesJr

###### Description of changes

Adds Seamly2D and its companion application, SeamlyMe. This is a vector-based fashion pattern drafting application. It is a fork of Valentina, which is already packaged for NixOS by @jfrankenau

This is my second PR. The first one was rebased funny and automatically pulled in a ton of reviewers. It got closed and locked.

https://seamly.net/
https://github.com/FashionFreedom/Seamly2D

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [22.11 Release Notes (or backporting 22.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2211-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-19 20:17 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/1575

2022-12-20 14:55 UTC, SuperSandro2000 requested changes

2022-12-20 14:55 UTC, SuperSandro2000 commented on pkgs/applications/graphics/seamly2d/default.nix
> +with lib;
Please don't use with over the entire filr

2022-12-20 14:55 UTC, SuperSandro2000 commented on pkgs/applications/graphics/seamly2d/default.nix
> +    addOpenGLRunpath
Goes to nativeBuildInputs

2022-12-20 14:55 UTC, SuperSandro2000 commented on pkgs/applications/graphics/seamly2d/default.nix
> +    gcc
Part of stdenv

2022-12-20 14:55 UTC, SuperSandro2000 commented on pkgs/applications/graphics/seamly2d/default.nix
> +    xvfb-run
Native

2022-12-20 14:55 UTC, SuperSandro2000 commented on pkgs/applications/graphics/seamly2d/default.nix
> +    fontconfig
Also nativeBuildInputs

2022-12-20 14:55 UTC, SuperSandro2000 commented on pkgs/applications/graphics/seamly2d/default.nix
> +    ccache
Also native and probably not useful for nix. I would suggest to remove it.

2022-12-20 14:55 UTC, SuperSandro2000 commented on pkgs/applications/graphics/seamly2d/default.nix
> +  enableParallelBuilding = true;
Already set by qmake

2022-12-20 14:55 UTC, SuperSandro2000 commented on pkgs/applications/graphics/seamly2d/default.nix
> +    gzip -9c dist/debian/seamly2d.1 > $out/share/man/man1/seamly2d.1.gz
Automatically done in fixupPhase

2023-02-24 16:40 UTC, WhittlesJr commented
@SuperSandro2000 , thank you very much for the review. I apologize for the late followup. I have implemented the changes you requested in a separate commit. If you approve, I'll squash it down.

2023-04-01 22:28 UTC, merged