solfege: add gdk-pixbuf to nativeBuildInputs
NixOS/nixpkgs pull request #203892
Opened 2022-12-01 09:02 UTC by jariji

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-01 11:19 UTC, bobby285271 commented
Hi, you also need to add it into args (i.e. somewhere in line 1-6) to make CI happy. But since this [builds fine on hydra](https://hydra.nixos.org/job/nixpkgs/trunk/solfege.x86_64-linux), it will be nice to provide more information for us, e.g.:

- What problem you are experiencing / why this is needed
- Why `nativeBuildInputs` and not `buildInputs`

in the "Description of changes" of your PR template and your commit message

2022-12-02 23:22 UTC, bjornfor commented
@jariji: I see you've fixed the code (good!), but could you also do what @bobby285271 mentioned?

> [...] to provide more information for us, e.g.:
>
> * What problem you are experiencing / why this is needed
> * [...]
>
> in the "Description of changes" of your PR template and your commit message

I tested solfege just now (on master and release-22.11), just tried detecting a few intervals, and it seemed to work fine, so I wonder what gdk-pixbuf is needed for.

2022-12-02 23:23 UTC, bjornfor requested changes
Please squash commits, and add a line in the one commit message why this is needed.

2022-12-03 10:29 UTC, bjornfor commented on pkgs/misc/solfege/default.nix
> -
Unrelated (and unwanted?) whitespace change.

2022-12-03 10:30 UTC, bjornfor commented
@jariji: What's the startup error? It works fine for me (on NixOS), both on master branch and release-22.11.

2022-12-03 10:34 UTC, jariji commented
```
Traceback (most recent call last):
  File "/nix/store/vaiag1zhpi2xagjmlqx4aib0c63mmjpp-solfege-3.23.4/share/solfege/solfege/startup.py", line 128, in start_gui
    solfege.win = w = MainWin(options, datadir)
  File "/nix/store/vaiag1zhpi2xagjmlqx4aib0c63mmjpp-solfege-3.23.4/share/solfege/solfege/mainwin.py", line 126, in __init__
    stock.SolfegeIconFactory(self, datadir)
  File "/nix/store/vaiag1zhpi2xagjmlqx4aib0c63mmjpp-solfege-3.23.4/share/solfege/solfege/stock.py", line 79, in __init__
    self.add_icons(d)
  File "/nix/store/vaiag1zhpi2xagjmlqx4aib0c63mmjpp-solfege-3.23.4/share/solfege/solfege/stock.py", line 35, in add_icons
    iconset = Gtk.IconSet(GdkPixbuf.Pixbuf.new_from_file(os.path.join(self.datadir, filename)))
gi.repository.GLib.GError: gdk-pixbuf-error-quark: Couldn’t recognize the image file format for file “/nix/store/vaiag1zhpi2xagjmlqx4aib0c63mmjpp-solfege-3.23.4/share/solfege/graphics/solfege.svg”
```

2022-12-03 10:42 UTC, bjornfor approved these changes

2022-12-03 10:46 UTC, bjornfor commented
Ah, that issue might be hidden for me because I use NixOS / GNOME. I tried to reproduce with `env -i ./result/bin/solfege`, but that failed with `RuntimeError: Gtk couldn't be initialized. Use Gtk.init_check() if you want to handle this case.`

2022-12-03 10:47 UTC, merged