adds protoc-gen-[prost, prost-crate, prost-serde, tonic]
NixOS/nixpkgs pull request #203836
Opened 2022-12-01 00:13 UTC by SitAAAx

###### Description of changes

protoc-gen-prost: init at 0.2.1
protoc-gen-prost-crate: init at 0.3.1
protoc-gen-prost-serde: init at 0.2.1
protoc-gen-tonic: init at 0.2.1

Protobuf plugins for generating Rust (inclusive gRPC) code.

The code of all mentioned packages lives at: https://github.com/neoeinstein/protoc-gen-prost
Their crates - which are used for packaging - come from:
https://crates.io/crates/protoc-gen-prost
https://crates.io/crates/protoc-gen-prost-crate
https://crates.io/crates/protoc-gen-prost-serde
https://crates.io/crates/protoc-gen-tonic

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-07-13 10:23 UTC, felschr requested changes
I'd like to see these plugins in nixpkgs, are you still interested and willing to update the PR to the latest package versions?

Please split up the commits into one for changing the maintainer list & one for each package following the format described in [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md):
`maintainers: add sitaaax`
`protoc-gen-prost: init at 0.2.3`, etc.

You can also add me as maintainer as I'm interested in keeping these up-to-date & working.

2023-07-13 10:23 UTC, felschr commented on pkgs/development/tools/protoc-gen-prost-crate/default.nix
> +    homepage = "https://github.com/neoeinstein/protoc-gen-prost";
```suggestion
    homepage = "https://github.com/neoeinstein/protoc-gen-prost";
    changelog = "https://github.com/neoeinstein/protoc-gen-prost/blob/main/CHANGELOG.md";
```

and for the other packages as well.

2023-07-13 10:23 UTC, felschr commented on pkgs/development/tools/protoc-gen-prost-crate/default.nix
> +  cargoBuildFlags = ["--bin" pname];
```suggestion
  cargoBuildFlags = [ "--bin" pname ];
```

Just to keep the style consistent within the file.

2023-07-14 08:05 UTC, SitAAAx commented
> Please split up the commits into one for changing the maintainer list & one for each package following the format described in [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md): `maintainers: add sitaaax` `protoc-gen-prost: init at 0.2.3`, etc.

Sorry, saw this comment after pushing the updates. Will change it after finishing my day job.

> You can also add me as maintainer as I'm interested in keeping these up-to-date & working.

Sure, will add you.

2023-07-14 17:52 UTC, SitAAAx commented
Restructured commits hopefully as requested.
Removed `cargoBuildFlags` and `nativeBuildInputs` because they do not seem to have an effect on the output.
Used back then https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/tools/protoc-gen-rust/default.nix as template.
But I am still new to nix packaging and can not say if I am doing something wrong.
Please bear with me.

2023-07-15 12:02 UTC, felschr commented
Result of `nixpkgs-review pr 203836` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>protoc-gen-prost</li>
    <li>protoc-gen-prost-crate</li>
    <li>protoc-gen-prost-serde</li>
    <li>protoc-gen-tonic</li>
  </ul>
</details>

2023-07-15 12:09 UTC, felschr approved these changes
Looks good to me.
I've tested the `protoc-gen-prost-crate` plugin with buf code generation and it works as expected.

2023-07-15 12:12 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1021

2023-07-15 21:43 UTC, merged