nixos/bluetooth: add input and network service configs
NixOS/nixpkgs pull request #204653
Opened 2022-12-05 16:17 UTC by ymatsiuk

###### Description of changes
Fixes #204418 
CC: @jbit for testing this out.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-05 17:24 UTC, fgaz commented on nixos/modules/services/hardware/bluetooth.nix
> +      cfgFmt.generate "network.conf" (recursiveUpdate defaults cfg.network);
According to #204418 this won't work

> BlueZ loads input.conf from a hardcoded path

We need a symlink in the package, like the one for main.conf

2022-12-06 15:47 UTC, fgaz requested changes
This needs to be tested before merging

2022-12-06 15:47 UTC, fgaz commented on nixos/modules/services/hardware/bluetooth.nix
> +      cfgFmt.generate "network.conf" (recursiveUpdate defaults cfg.network);
`defaults` here refers to `main.conf` defaults

2022-12-07 10:16 UTC, fgaz approved these changes
The code looks good.  @jbit can you help with testing?

2022-12-07 10:54 UTC, jbit commented
> The code looks good. @jbit can you help with testing?

Yup! I was in the middle of rebuilding my system with this change when I received  your message :smile: 

The change works great on my setup, thanks @ymatsiuk for taking a look at my issue report so quickly!

I'm not sure if there are automated tests you want me to run, but I tried the manual way as detailed below.

**Testing:**

I used a local nixpkgs checkout with `1d61d168a6fe30eb42c02fff8a097a5c224c7ec9` cherry picked on top.

After rebuilding, I ended up with a bluez package with the expected new symlinks:
```console
# ls -l /nix/store/gk5nwc6ilvgl5da96xkfgffc460y1x6g-bluez-5.64/etc/bluetooth/
total 0
lrwxrwxrwx 1 root root 25 Jan  1  1970 input.conf -> /etc/bluetooth/input.conf
lrwxrwxrwx 1 root root 24 Jan  1  1970 main.conf -> /etc/bluetooth/main.conf
lrwxrwxrwx 1 root root 27 Jan  1  1970 network.conf -> /etc/bluetooth/network.conf
```

I manually created a `/etc/bluetooth/input.conf` file filled with only `failure`, ran `systemctl restart bluetooth`, and looked at `journalctl -u bluetooth`, which contained an error proving the bluetoothd is actually processing the `input.conf` file.
```
Dec 07 21:37:05 catbag bluetoothd[569459]: profiles/input/manager.c:load_config_file() Parsing /nix/store/gk5nwc6ilvgl5da96xkfgffc460y1x6g-bluez-5.64/etc/bluetooth/input.conf failed: 
Key file contains line “failure” which is not a key-value pair, group, or comment
```

I then added the following to my `configuration.nix` file:
```
  hardware.bluetooth = {
    enable = true;
    powerOnBoot = true;
    input = { General = { IdleTimeout = 1; }; };
  };
```

Which resulted a `/etc/bluetooth/input.conf` file with the contents:
```
[General]
IdleTimeout=1
```

After restarting the bluetooth daemon again, my input devices now go to sleep after one minute of inactivity.

**Result**

Everything works as expected. :+1: from me

2023-01-12 08:23 UTC, fgaz commented
it's about time i merge this :)

2023-01-12 08:24 UTC, merged