gradle_4, gradle_5: remove
NixOS/nixpkgs pull request #205388
Opened 2022-12-10 00:28 UTC by tjni

###### Description of changes

Usages of these have been cleaned up in `nixpkgs`, and these old versions have not been updated in awhile.

Fixes #205455.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-10 08:09 UTC, tjni commented
The openjfx11 changes can be superseded by https://github.com/NixOS/nixpkgs/pull/205169.

2022-12-10 12:18 UTC, lorenzleutgeb requested changes
@tjni Good idea. #205169 skips Gradle 5 (last release 2019-11-01) which is super old as well, and Gradle 6, which is not the most recent version. That's better than just going from 4 to 5. So I'd say, let us wait for that PR, then update this one.

2022-12-13 20:14 UTC, tjni commented
Sweet, https://github.com/NixOS/nixpkgs/pull/205169 has been merged onto `staging`. I'm planning to wait for it to reach `master` in a few weeks, because I don't see any value in stacking this on top of it. By that time, https://github.com/NixOS/nixpkgs/pull/205841 might be in as well, and then we can repurpose this PR to remove both Gradle 4 and Gradle 5.

2023-01-18 06:08 UTC, liff approved these changes

2023-01-18 16:55 UTC, lorenzleutgeb approved these changes

2023-01-23 23:09 UTC, merged