scrcpy: 1.24 -> 1.25
NixOS/nixpkgs pull request #207242
Opened 2022-12-22 12:36 UTC by msfjarvis

###### Description of changes

https://github.com/Genymobile/scrcpy/releases/tag/v1.25

Notably this release brings compatibility with Android 13 and adds desktop entries.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-22 15:14 UTC, SubhrajyotiSen commented
Result of `nixpkgs-review pr 207242` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>scrcpy</li>
  </ul>
</details>

2022-12-22 15:33 UTC, SubhrajyotiSen approved these changes

2022-12-25 20:33 UTC, markuskowa commented
This breaks the `x86_64-darwin` build?

2022-12-26 04:29 UTC, msfjarvis commented
> This breaks the `x86_64-darwin` build?

Should be fixed

2022-12-26 11:05 UTC, markuskowa requested changes

2022-12-26 11:05 UTC, markuskowa commented on pkgs/misc/scrcpy/default.nix
> +  '' + lib.optionals stdenv.isLinux ''
```suggestion
  '' + lib.optionalString stdenv.isLinux ''
```

2022-12-26 11:05 UTC, markuskowa commented on pkgs/misc/scrcpy/default.nix
> +      --replace "/bin/bash" "${bash}/bin/bash"
```suggestion
      --replace "/bin/bash" "${runtimeShell}"
```

2022-12-26 21:18 UTC, markuskowa approved these changes

2022-12-26 21:18 UTC, merged