xteve: init at 2.2.0
NixOS/nixpkgs pull request #207509
Opened 2022-12-24 03:21 UTC by NRHelmi

###### Description of changes
I nix packaged `xTeVe` and added it to my plex setup, I thought that might be useful to add it to `nixpkgs`.
`xTeVe` is an M3U proxy server for Plex DVR and Emby Live TV

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-24 06:26 UTC, JamieMagee commented
Result of `nixpkgs-review pr 207509` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>xteve</li>
  </ul>
</details>

2022-12-24 14:43 UTC, AndersonTorres requested changes

2022-12-24 14:43 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +  version = "2.2.0.200";
Move this inside the `buildGoModule` expression.

2022-12-24 14:43 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +    '';
```suggestion
    description = "M3U Proxy for Plex DVR and Emby Live TV";
```

2022-12-24 14:43 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +    sha256 = "sha256-hD4GudSkGZO41nR/CgcMg/SqKjpAO1yJDkfwa8AUges=";
```suggestion
    hash = "sha256-hD4GudSkGZO41nR/CgcMg/SqKjpAO1yJDkfwa8AUges=";
```

2022-12-24 14:43 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +    maintainers = with maintainers; [ ];
Usually we require that you (aka the package creator) list yourself as maintainer here.

However, I will suppose you are not interested on take this role. 
In this case, for the sake of completeness, please add myself (`AndersonTorres`) as maintainer.

2022-12-24 14:43 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +  inherit version;
```suggestion
  version = "2.2.0.200";
```

2022-12-24 14:43 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +    inherit owner repo;
```suggestion
    owner = "xteve-project";
    repo  = "xTeVe";
```

2022-12-31 01:40 UTC, AndersonTorres requested changes

2022-12-31 01:40 UTC, AndersonTorres commented on maintainers/maintainer-list.nix
> +  nrhelmi = {
Isolate this modification in a separate commit. No need for a new PR.

2022-12-31 01:40 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +{ lib, buildGoModule, fetchFromGitHub }:
... and join the rest in the next PR, with the title:

`xteve: init at 2.2.0.200`

2023-01-02 00:44 UTC, AndersonTorres requested changes

2023-01-02 00:44 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +    maintainers = with maintainers; [ nrhelmi AndersonTorres ];
Squash/merge this commit, **with this exact title**:

```xteve: init at 2.2.0.200```

2023-01-19 09:53 UTC, AndersonTorres commented
Now squash the commits into two - one for the new maintainer, other for the new package.

2023-01-22 14:08 UTC, NRHelmi commented
@AndersonTorres can you give it another check ? BTW is there any documentation on steps (commit policies) to add a new package to nixpkgs ?

2023-01-22 14:52 UTC, AndersonTorres requested changes
Again:
Your pull request has eight commits. Reduce it to only two:

1. The first commit adds yourself to maintainers list
2. The second effectively adds the package

You can do this by using `git rebase` facility.

2023-01-22 14:52 UTC, AndersonTorres commented on pkgs/servers/xteve/default.nix
> +    maintainers = with maintainers; [ nrhelmi AndersonTorres ];
```suggestion
    maintainers = with maintainers; [ nrhelmi ];
```

2023-01-22 15:08 UTC, AndersonTorres commented
> BTW is there any documentation on steps (commit policies) to add a new package to nixpkgs ?

What exactly you want to know? The barriers to add packages to Nixpkgs are very low when compared to other package databases. It just needs someone with free time to revise and test.

2023-01-22 23:28 UTC, AndersonTorres commented
Third time:

Your pull request has nine commits. Reduce it to only two:

1. The first commit adds yourself to maintainers list
2. The second effectively adds the package

You can do this by using `git rebase` facility.

2023-01-26 02:56 UTC, AndersonTorres commented
Ping.

2023-01-26 03:03 UTC, NRHelmi commented
> Ping.

Hi @AndersonTorres sorry didn't get a chance to look into will do during this weekend

2023-01-29 17:45 UTC, NRHelmi commented
@AndersonTorres  closing this PR and moving the changes to https://github.com/NixOS/nixpkgs/pull/213411

2023-01-29 17:45 UTC, closed without merging