bottles: fix gstreamer for 32 bit
NixOS/nixpkgs pull request #207687
Opened 2022-12-25 12:59 UTC by SuperSamus

###### Description of changes

Should fix #207641. I didn't test, so does it fix the problem @m911t?
(Also, maybe I should add `gst-libav` and `gst-vaapi`?)

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-25 15:51 UTC, m911t commented
I'm still a beginner @ nixOS, how can I test this?

2022-12-25 16:00 UTC, SuperSamus commented
```bash
nix-build -A bottles https://github.com/NixOS/nixpkgs/archive/pull/207687/head.tar.gz
```

2022-12-25 18:43 UTC, SuperSandro2000 requested changes

2022-12-25 18:43 UTC, SuperSandro2000 commented on pkgs/applications/misc/bottles/fhsenv.nix
> +      (with pkgs.pkgsi686Linux.gst_all_1; [ gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad ])
```suggestion
      with gst_all_1; [ gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad ]
      ++ (with pkgsi686Linux.gst_all_1; [ gst-plugins-base gst-plugins-good gst-plugins-ugly gst-plugins-bad ])
```

2022-12-25 18:43 UTC, SuperSandro2000 commented on pkgs/applications/misc/bottles/fhsenv.nix
> +, pkgs
```suggestion
, gst_all_1
, pkgsi686Linux
```

2022-12-25 19:56 UTC, m911t commented
@SuperSamus great news, it works. I have sound on oblivion again.

2022-12-29 17:38 UTC, m911t commented
bump, this is a pretty big fix for stuff that depends on gstreamer

2023-01-03 05:41 UTC, m911t commented
I think the last commit broke it again? Reinstalled nixOS and the audio doesnt work again

2023-01-03 11:35 UTC, SuperSamus commented
@m911t Did you build Bottles with
```bash
nix-build -A bottles https://github.com/NixOS/nixpkgs/archive/pull/207687/head.tar.gz
```
and launched it with the path returned? (`/nix/store/1zd5figf0v0mw7gkaa2hsgl8zc804cnw-bottles/bin/bottles`)

2023-01-03 12:33 UTC, m911t commented
yeah, that's how i played oblivion for a while and it's the same thing I did now

Sent from Proton Mail mobile

-------- Original Message --------
On Jan 3, 2023, 6:35 AM, SuperSamus wrote:

> ***@***.***(https://github.com/m911t) Did you build Bottles with
>
> nix-build -A bottles https://github.com/NixOS/nixpkgs/archive/pull/207687/head.tar.gz
>
> and launched it with the path returned? (/nix/store/1zd5figf0v0mw7gkaa2hsgl8zc804cnw-bottles/bin/bottles)
>
> —
> Reply to this email directly, [view it on GitHub](https://github.com/NixOS/nixpkgs/pull/207687#issuecomment-1369667588), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/ASZZMNR2BRD7M74G54MYC33WQQFIVANCNFSM6AAAAAATI7IQGM).
> You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-01-03 14:43 UTC, m911t commented
still doesnt work... I noticed that the runner is now Soda 7.0-8 but I don't think that could affect this. 
![image](https://user-images.githubusercontent.com/78878262/210379634-0bbe41f8-a052-42a7-9edf-aa5a28778159.png)

2023-01-03 19:27 UTC, m911t commented
still doesnt work... I noticed that the runner is now Soda 7.0-8 but I don't think that could affect this.
![image](https://user-images.githubusercontent.com/78878262/210379634-0bbe41f8-a052-42a7-9edf-aa5a28778159.png)

2023-01-16 15:06 UTC, SuperSamus commented
I give up. I tried too many things, and none of them work.
And yet, launching Oblivion from Steam (as a non-Steam game) has no audio problem. Looking at Steam's `fhsenv.nix` I couldn't find anything special regarding GStreamer.

2023-01-16 15:06 UTC, closed without merging