mattermost: 7.5.1 -> 7.5.2
NixOS/nixpkgs pull request #208185
Opened 2022-12-29 03:15 UTC by numinit

###### Description of changes

Mattermost v7.5.2 contains low to medium severity level security fixes. [Upgrading](https://docs.mattermost.com/upgrade/upgrading-mattermost-server.html) to this release is recommended. Details will be posted on our [security updates page](https://mattermost.com/security-updates/) 30 days after release as per the [Mattermost Responsible Disclosure Policy](https://mattermost.com/security-vulnerability-report/).

https://docs.mattermost.com/install/self-managed-changelog.html#release-v7-5-feature-release

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-29 03:17 UTC, numinit commented on pkgs/servers/mattermost/default.nix
> +    "-X github.com/mattermost/mattermost-server/v6/model.BuildEnterpriseReady=false"
All the build info is empty in NixOS 22.11, this fixes it:

```
$ ./result/bin/mattermost version
Version: 7.5.2
Build Number: 7.5.2-nixpkgs
Build Date: 1970-01-01
Build Hash: v7.5.2
Build Enterprise Ready: false
```

2022-12-29 04:11 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/1619

2022-12-29 10:57 UTC, Kranzes commented
Why does it not go into master directly?

2022-12-29 14:55 UTC, SuperSandro2000 requested changes

2022-12-29 14:55 UTC, SuperSandro2000 commented on pkgs/servers/mattermost/default.nix
> +  gitRev = "v${version}";
```suggestion
```

2022-12-29 14:55 UTC, SuperSandro2000 commented on pkgs/servers/mattermost/default.nix
> +    rev = gitRev;
```suggestion
    rev = "v${version}";
```

2022-12-29 14:55 UTC, SuperSandro2000 commented on pkgs/servers/mattermost/default.nix
> +    "-X github.com/mattermost/mattermost-server/v6/model.BuildHash=${gitRev}"
```suggestion
    "-X github.com/mattermost/mattermost-server/v6/model.BuildHash=v${version}"
```

2022-12-29 20:44 UTC, numinit commented
> Why does it not go into master directly?

Per the [staging workflow](https://github.com/NixOS/rfcs/blob/master/rfcs/0026-staging-workflow.md) it appears this is where security fixes go since this is a stabilization fix that will be backported to 22.11.

2022-12-30 13:34 UTC, Artturin commented on pkgs/servers/mattermost/default.nix
> +    "-X github.com/mattermost/mattermost-server/v6/model.BuildHashEnterprise=v${gitRev}"
gitRev isn't set

2022-12-30 13:34 UTC, Artturin commented
> > Why does it not go into master directly?
> 
> Per the [staging workflow](https://github.com/NixOS/rfcs/blob/master/rfcs/0026-staging-workflow.md?rgh-link-date=2022-12-29T20%3A44%3A53Z) it appears this is where security fixes go since this is a stabilization fix that will be backported to 22.11.

less than 500 rebuilds can go in to master

2022-12-30 15:02 UTC, SuperSandro2000 commented
> Per the [staging workflow](https://github.com/NixOS/rfcs/blob/master/rfcs/0026-staging-workflow.md?rgh-link-date=2022-12-29T20%3A44%3A53Z) it appears this is where security fixes go since this is a stabilization fix that will be backported to 22.11.

Only mass rebuilds go to staging and mass rebuild **with** security fixes go to staging-next.

2022-12-30 19:41 UTC, numinit commented
Ah, good to know. Thanks, I'll rebase.

2023-01-01 22:29 UTC, LeSuisse approved these changes
nixpkgs-review happy on x86_64, test succeeds and no surprise in the changelog.

Result of `nixpkgs-review pr 208185` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mattermost</li>
  </ul>
</details>

2023-01-01 22:30 UTC, merged