Audit logging extension for postgres
NixOS/nixpkgs pull request #208250
Opened 2022-12-29 15:43 UTC by idontgetoutmuch

###### Description of changes

Audit logging extension for Postgres: https://github.com/pgaudit/pgaudit

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-29 15:44 UTC, idontgetoutmuch commented
@balsoft as discussed, if you could take a look that would be great

2022-12-29 15:49 UTC, balsoft commented
Please, make sure your PR name and commit messages conform to CONTRIBUTING.md: https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes

It should be along the lines of `postgresqlPackages.pgaudit: init at 1.5.1`

2022-12-29 15:50 UTC, balsoft approved these changes
Diff LGTM

2023-01-20 14:12 UTC, ajs124 requested changes

2023-01-20 14:12 UTC, ajs124 commented on pkgs/servers/sql/postgresql/ext/pgaudit.nix
> +{ lib, stdenv, fetchFromGitHub, kerberos, openssl, postgresql }:
```suggestion
{ lib, stdenv, fetchFromGitHub, libkrb5, openssl, postgresql }:
```
`kerberos` is an alias, so this won't evaluate without them

2023-01-20 14:12 UTC, ajs124 commented on pkgs/servers/sql/postgresql/ext/pgaudit.nix
> +  buildInputs = [ kerberos openssl postgresql ];
```suggestion
  buildInputs = [ libkrb5 openssl postgresql ];
```
same here

2023-01-31 10:58 UTC, merged