ispc: Add aarch64-linux and aarch64-darwin platforms
NixOS/nixpkgs pull request #208397
Opened 2022-12-30 19:15 UTC by Munksgaard

According to https://ispc.github.io/ispc.html#selecting-the-compilation-target, aarch64 is supported.

###### Description of changes

Added aarch64-linux and aarch64-darwin platforms as targets for ispc. These are supported according to the [documentation](https://ispc.github.io/ispc.html#selecting-the-compilation-target). I don't actually have access to an aarch64 platform right now, so I haven't been able to test the changes.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2022-12-30 20:07 UTC, athas approved these changes

2022-12-30 21:31 UTC, athas approved these changes

2022-12-31 10:03 UTC, Munksgaard commented
Rebase on master

2022-12-31 10:27 UTC, athas approved these changes

2023-01-03 08:17 UTC, wegank requested changes
aarch64-linux build fails on Hydra.

2023-01-03 08:20 UTC, athas commented
The error is due to the derivation always using the sse2 backend for its tests, which is obviously not going to work on ARM.  We should use a different backend on ARM.  Maybe [this line](https://github.com/NixOS/nixpkgs/blob/454e81780251b7d241a150e941e73573dbca25bc/pkgs/development/compilers/ispc/default.nix#L5) should be made conditional on the architecture.

2023-01-03 08:36 UTC, Munksgaard commented
I've updated the PR with a conditional on testedTargets. Let's see if that works...

2023-01-03 09:04 UTC, Munksgaard commented
Looks like it works!

2023-01-03 09:11 UTC, athas approved these changes

2023-01-03 09:12 UTC, wegank approved these changes

2023-01-03 13:47 UTC, merged