python3Packages.afdko: 3.9.0 -> 3.9.2
NixOS/nixpkgs pull request #210181
Opened 2023-01-11 10:42 UTC by onny

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-01-11 11:28 UTC, sternenseemann reviewed
I expect this needs to go to staging.

2023-01-11 11:28 UTC, sternenseemann commented on pkgs/development/python-modules/afdko/default.nix
> +  '';
```suggestion
  FORCE_SYSTEM_LIBXML2 = true;
```

2023-01-11 11:28 UTC, sternenseemann commented
@ofborg build noto-fonts-emoji

2023-01-11 13:57 UTC, onny commented
@sternenseemann Thank you, done :)

2023-01-11 14:59 UTC, sternenseemann commented
@ofborg build python3Packages.afdko.tests noto-fonts-emoji python3Packages.pygments

2023-01-11 16:55 UTC, mweinelt requested changes
Some nits.

2023-01-11 16:55 UTC, mweinelt commented on pkgs/development/python-modules/afdko/default.nix
> +  version = "3.9.2";
```suggestion
  version = "3.9.2";
  format = "pyproject";
```

Move the format up here.

2023-01-11 16:55 UTC, mweinelt commented on pkgs/development/python-modules/afdko/default.nix
> +    sha256 = "sha256-3JEnQbS4CtZEqAb+/ngqkO+nv9SZ0Zi8sPJLyW+tQ9w=";
```suggestion
    hash = "sha256-3JEnQbS4CtZEqAb+/ngqkO+nv9SZ0Zi8sPJLyW+tQ9w=";
```

2023-01-11 16:55 UTC, mweinelt commented on pkgs/development/python-modules/afdko/default.nix
>      description = "Adobe Font Development Kit for OpenType";
```suggestion
    changelog = "https://github.com/adobe-type-tools/afdko/blob/${version}/NEWS.md";
    description = "Adobe Font Development Kit for OpenType";
```

2023-01-11 16:55 UTC, mweinelt commented on pkgs/development/python-modules/fonttools/default.nix
> +  version = "4.38.0";
```suggestion
  version = "4.38.0";
  format = "setuptools";
```

Add explicit format.

2023-01-11 16:55 UTC, mweinelt commented on pkgs/development/python-modules/fonttools/default.nix
> +    sha256 = "sha256-cdZI2kwR3zzS6eiiXGpeHIp+kgPCPEsTOSTV60pODTM=";
```suggestion
    hash = "sha256-cdZI2kwR3zzS6eiiXGpeHIp+kgPCPEsTOSTV60pODTM=";
```

2023-01-11 16:55 UTC, mweinelt commented on pkgs/development/python-modules/lxml/default.nix
> +  version = "4.9.2";
```suggestion
  version = "4.9.2";
  format = "setuptools";
```

2023-01-11 16:55 UTC, mweinelt commented on pkgs/development/python-modules/lxml/default.nix
> +    sha256 = "sha256-IHuTlcDbrZHvS6Gtx48IkznVU+9WxZT9XHUZf8M1WOE=";
```suggestion
    hash = "sha256-IHuTlcDbrZHvS6Gtx48IkznVU+9WxZT9XHUZf8M1WOE=";
```

2023-01-12 11:04 UTC, sternenseemann approved these changes

2023-01-12 13:25 UTC, merged