vscode: 1.6.1 -> 1.7.2
NixOS/nixpkgs pull request #21033
Opened 2016-12-10 01:12 UTC by xwvvvvwx

###### Motivation for this change

Update vscode to the latest stable version

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-12-10 04:12 UTC, matthewbauer requested changes
I am getting:

output path ‘/nix/store/sf7wb7i30hd94d4qpx3z43cff75kmvk9-VSCode-darwin-stable.zip’ has sha256 hash ‘1chl84scngpxdmcmzbciiz50j459xdcjbpcv4vpm5061gfp5qnh9’ when ‘1a1mxmvai2yz0gzmac6nrm5mqrxa2ypwrhf0k8qjim4cbv1cj5h2’ was expected

on OS X.

2016-12-10 09:31 UTC, xwvvvvwx commented
ow :disappointed: 

I'm sorry for that I don't have an osx system here to test with. 

How come the CI passed if it fails for you?
I used `nix-hash --base32 --sha256 <unpacked_dir>` to generate the hashes on 32bit linux and osx, was that wrong?

Should I just update the commit with the expected hash you got on osx?

2016-12-11 14:49 UTC, uralbash commented
Linux32: 0n49c6m53vbmhvrb8q0lxqa77r7kivn4n542k8y62bii8hi19ixc
Linux64: 0l3n20rvgrxk2j9962wqmprjz7lnvldkp0yw26yfxl99yvrph68f
Darwin: 1chl84scngpxdmcmzbciiz50j459xdcjbpcv4vpm5061gfp5qnh9

2016-12-11 21:10 UTC, xwvvvvwx commented
@uralbash thanks!

So I can avoid the same mistake in the future, how should I generate these hashes?

2016-12-12 04:50 UTC, uralbash commented
@xwvvvvwx I use ``nix-prefetch-url`` like this:
```bash
$ nix-prefetch-url 'https://az764295.vo.msecnd.net/stable/07d663dc1bd848161edf4cd4ce30cce410d3d877/code-stable-code_1.5.1-1473369468_i386.tar.gz'
```

2016-12-12 07:30 UTC, uralbash approved these changes

2016-12-12 16:39 UTC, xwvvvvwx commented
@uralbash thanks for all the help! ☺️

2016-12-15 11:04 UTC, merged

2016-12-15 11:04 UTC, Mic92 commented
Thanks!