shell_cmds: init at 198
NixOS/nixpkgs pull request #21133
Opened 2016-12-13 23:05 UTC by matthewbauer

###### Motivation for this change

This adds Apple's shell_cmds which contains the following binaries:
- alias
- apply
- basename
- bg
- cd
- chroot
- command
- date
- dirname
- echo
- env
- false
- fc
- fg
- getopt
- getopts
- groups
- hash
- hexdump
- hostname
- id
- jobs
- jot
- kill
- killall
- lastcomm
- locate
- locate.bigram
- locate.code
- logname
- mktemp
- nice
- nohup
- od
- path_helper
- printenv
- printf
- pwd
- read
- renice
- script
- seq
- shlock
- sleep
- systime
- tee
- time
- true
- type
- ulimit
- umask
- unalias
- uname
- users
- wait
- what
- whereis
- which
- who
- whoami
- xargs
- yes

These are **disabled** currently because they don't build:
- sh
- w
- test
- find
- su

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

fixes #11707

2016-12-14 10:15 UTC, LnL7 requested changes
looks good, apart from the osx version

2016-12-14 10:15 UTC, LnL7 commented on pkgs/os-specific/darwin/apple-source-releases/default.nix
> +      shell_cmds    = "198";
The version of [10.11.6](https://opensource.apple.com/release/os-x-10116.html) is shell_cmds-187, I think this one is from 10.12.1.

2016-12-14 10:15 UTC, LnL7 commented on pkgs/os-specific/darwin/apple-source-releases/shell_cmds/default.nix
> +      --replace "FCBA168714A146D000AA698B /* PBXTargetDependency */," ""
Does this generally work between versions?

2016-12-14 19:30 UTC, matthewbauer commented on pkgs/os-specific/darwin/apple-source-releases/shell_cmds/default.nix
> +      --replace "FCBA168714A146D000AA698B /* PBXTargetDependency */," ""
Sadly, no.

2016-12-15 03:18 UTC, matthewbauer commented on pkgs/os-specific/darwin/apple-source-releases/default.nix
> +      shell_cmds    = "198";
good catch. should be fixed

2016-12-15 16:52 UTC, LnL7 approved these changes

2016-12-15 16:53 UTC, merged

2016-12-15 16:54 UTC, copumpkin commented
Wonderful, thanks!

2016-12-15 16:56 UTC, LnL7 commented
Also noticed that `xcbuild` doesn't have metadata so hydra didn't build it.