add graphite-cli package
NixOS/nixpkgs pull request #211604
Opened 2023-01-19 16:31 UTC by jrobsonchase

###### Description of changes

Simple node2nix package, with some minor metadata fixups.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-01-19 18:41 UTC, AndersonTorres requested changes

2023-01-19 18:41 UTC, AndersonTorres commented on pkgs/development/tools/graphite-cli/default.nix
> +{ pkgs }:
```suggestion
{ pkgs, lib }:
```

2023-01-19 18:41 UTC, AndersonTorres commented on pkgs/development/tools/graphite-cli/default.nix
> +    license = "AGPL";
```suggestion
    license = lib.licenses.agpl3Plus;
```

2023-01-19 18:41 UTC, AndersonTorres commented on pkgs/development/tools/graphite-cli/default.nix
> +    description = "Graphite is a fast, simple code review platform designed for engineers who want to write and review smaller pull requests, stay unblocked, and ship faster.";
```suggestion
    description = "Fast, simple code review platform designed for engineers who want to write and review smaller pull requests, stay unblocked, and ship faster";
```

According to Contributing.md

2023-01-24 16:39 UTC, AndersonTorres commented
Now squash these commits into one.

2023-01-25 10:42 UTC, AndersonTorres commented
Again, use `git rebase` to squash the commits into only one.

2023-01-25 13:15 UTC, AndersonTorres requested changes
Again, use `git rebase` to squash the commits into only one.

2023-02-23 20:55 UTC, ryantm commented
It appears that this is already in nixpkgs under `nodePackages.graphite-cli`. Since this is a user-facing CLI tool, it would be nice to add it to the top level so hydra builds it though. So maybe just have an entry like `graphite-cli = nodePackages.graphite-cli` in all-packages?

2023-03-21 22:08 UTC, jrobsonchase commented
Cool, thanks for the useful suggestion @ryantm!

2023-03-22 01:52 UTC, AndersonTorres requested changes
Reword the commit:

`nodePackages.graphite-cli: bring to top-level`

Besides, LGTM

2023-03-22 18:56 UTC, ryantm commented
Result of `nixpkgs-review pr 211604` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>graphite-cli</li>
  </ul>
</details>

2023-03-22 18:56 UTC, merged