studio-link: init at 21.0.7
NixOS/nixpkgs pull request #213010
Opened 2023-01-27 20:03 UTC by fooker

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-01-28 12:45 UTC, JulienMalka reviewed
This only works for linux while it seems macOS is also supported by studio-link. How difficult would it be to build for source ? Otherwise we could maybe fetch a different url if on darwin ?

2023-01-30 11:46 UTC, fooker commented
> This only works for linux while it seems macOS is also supported by studio-link. How difficult would it be to build for source ? Otherwise we could maybe fetch a different url if on darwin ?

I've looked into building it from source - and it is a total PITA. I do not even understand the way the software is build.

There are two builds for MacOS available. I don't know which to choose or how to decide this.

2023-05-09 11:36 UTC, JulienMalka commented
Ok, if building from source is not an option could we try distribution the macos binaries as well ? 
Like chromedriver does it for example : https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/development/tools/selenium/chromedriver/default.nix

2023-05-09 11:37 UTC, JulienMalka commented
Ok, if building from source is not an option could we try distribution the macos binaries as well ? 
Like chromedriver does it for example : https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/development/tools/selenium/chromedriver/default.nix

2023-05-09 11:40 UTC, JulienMalka commented
Ok, if building from source is not an option could we try distribution the macos binaries as well ? 
Like chromedriver does it for example : https://github.com/NixOS/nixpkgs/blob/nixos-22.11/pkgs/development/tools/selenium/chromedriver/default.nix

2023-05-09 11:43 UTC, JulienMalka commented
Sorry for the duplicates github is acting out

2023-07-30 16:41 UTC, doronbehar requested changes

2023-07-30 16:41 UTC, doronbehar commented on pkgs/applications/audio/studio-link/default.nix
> +    description = "High quality Audio-over-IP Connections";
License missing. It'd also be nice to include a link to source code, if available, for non German speakers.

2023-07-30 16:41 UTC, doronbehar commented
Also, merge conflict.

2025-02-06 11:24 UTC, donovanglover commented
Marking as draft due to inactivity. Please rebase if still relevant. Otherwise feel free to close the PR.

2025-02-07 07:41 UTC, doronbehar commented
No need to keep open PRs from 2023 that their OP doesn't respond IMO. Feel free to open a new PR.

2025-02-07 07:41 UTC, closed without merging