paperless-ngx: 1.11.3 -> 1.12.2
NixOS/nixpkgs pull request #213489
Opened 2023-01-30 01:55 UTC by mweinelt

https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.12.0
https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.12.1
https://github.com/paperless-ngx/paperless-ngx/releases/tag/v1.12.2

And we now build the ui from source.

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-01-30 19:26 UTC, erikarvstedt commented on nixos/modules/services/misc/paperless.nix
> +        if [[ -f "${cfg.dataDir}/.1_12_document_reindex" ]]: then
Should be `if [[ ! -f ...`.

2023-01-30 19:27 UTC, erikarvstedt commented on nixos/modules/services/misc/paperless.nix
> +          echo "Reindixing documents once, required after the 1.12.x upgrade"
Reind**e**xing

2023-01-30 21:46 UTC, mweinelt commented
Ok, rundown of what I did.

- The frontend is now available in a separate derivation through `paperless-ngx.frontend`
- Started to selectively copy content into `$out`, specifically left out
  - `docs` (probably needs to be built using mkdocs, but then into a dedicated output)
  - `docker
  - `scripts` (systemd units and docker startup script)
- Dropped the tests and its samples from the final package to save 14 MB, we're now at ~41.5 MB
  - 34 MB Frontend
  - 7.5 MB Backend

2023-01-30 22:11 UTC, erikarvstedt commented on pkgs/applications/office/paperless-ngx/default.nix
> +    factory_boy
`factory_boy` is already in this list.

2023-01-30 22:18 UTC, mweinelt commented on pkgs/applications/office/paperless-ngx/default.nix
> +    factory_boy
Fixup pushed.

2023-01-31 00:09 UTC, erikarvstedt approved these changes
- [x] `nixosTests.paperless` succeeds on `x86_64-linux`
- [x] I've manually tested the frontend in a container-based deployment, adding a few docs and checking their consumption

2023-01-31 11:26 UTC, gador commented
- [x] nixpkgs-review shows no errors
- [x] `nix-build -A nixosTests.paperless` succeeds 
- [x] running paperless within a Gnome VM works just fine. Adding and saving documents as well

2023-01-31 11:26 UTC, gador approved these changes

2023-01-31 11:29 UTC, erikarvstedt requested changes
Please hold off merging; I'm investigating an issue with the reindexing.

2023-01-31 13:48 UTC, erikarvstedt approved these changes

2023-01-31 14:23 UTC, SuperSandro2000 approved these changes
diff LGTM

2023-01-31 15:36 UTC, merged