opentsdb: 2.4.0 -> 2.4.1
NixOS/nixpkgs pull request #213485
Opened 2023-01-30 01:17 UTC by dotlambda

###### Description of changes
https://github.com/OpenTSDB/opentsdb/releases/tag/v2.4.1

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-01-30 11:13 UTC, LeSuisse requested changes
opentsdb seems to work as expected

2023-01-30 11:13 UTC, LeSuisse commented on pkgs/tools/misc/opentsdb/default.nix
> +    chmod +x build-aux/fetchdep.sh.in
Do we need this?

2023-01-30 11:13 UTC, LeSuisse commented on pkgs/tools/misc/opentsdb/default.nix
> +  include = {
Maybe it would be preferable to use `fetchMavenArtifact` or URLs using `mirror://maven/` instead of the direct `https://repo1.maven.org/maven2/`

2023-01-30 15:29 UTC, dotlambda commented on pkgs/tools/misc/opentsdb/default.nix
> +    chmod +x build-aux/fetchdep.sh.in
Yes, `patchShebangs` only works with executable files.

2023-02-03 03:30 UTC, hlolli approved these changes
from what I can see fetchmavenartifact behaves exactly the same, it's cleaner, but I'm not sure why it was needed for this PR. Still lgtm that part.

2023-02-03 03:41 UTC, dotlambda commented
> I'm not sure why it was needed for this PR

Because in the `preBuild` step where I'm doing `ln -s` I rely on the filename being exactly the same as on Maven.

2023-02-03 03:43 UTC, dotlambda commented
> from what I can see fetchmavenartifact behaves exactly the same

It does behave exactly the same unless `classifier` is set. I checked that that is not the case anywhere in Nixpkgs.

2023-02-03 14:26 UTC, hlolli commented
> > from what I can see fetchmavenartifact behaves exactly the same
> 
> It does behave exactly the same unless `classifier` is set. I checked that that is not the case anywhere in Nixpkgs.

I do allow passing it in my tool that uses fetchmavenartifact
https://github.com/hlolli/clj2nix/blob/master/src/clj2nix/core.clj#L58-L77

I wonder if I would need to change something

2023-02-03 14:28 UTC, hlolli commented
there was also the dollar sign that had to be accounted for
https://github.com/hlolli/clj2nix/issues/10
Maybe I test this PR later today with clj2nix

2023-02-05 03:04 UTC, hlolli commented
So I finally got around to test your fetchMavenArtifact changes, and they are fine!

I tested

```
fetchMavenArtifact {
      inherit repos;
      artifactId = "javafx-base";
      groupId = "org.openjfx";
      sha512 = "4f0d4cdd354204acced0a0a9c3537bf2aa534e24e84c3e7a75fcf5d749adb9ccc5a3b1d5584e8491f59dce54682be828accac09f5a3f456f72665b5591584f34";
      version = "14";
      classifier = "mac";
    };
  ```
   And it fetches the correct jar
   ```
   these 3 derivations will be built:
  /nix/store/6h2ia3z6mflyf3z8n32gxyswq3qn76nq-org_openjfx_javafx-base-14.jar.drv
  /nix/store/y24vdxrrn0ysis6akc3c878hb0y4msyk-org_openjfx_javafx-base-14.jar.drv
  /nix/store/1lgn8fsylbcxj7a005q16jmkd7hak8ih-clj2nixTest.drv
building '/nix/store/6h2ia3z6mflyf3z8n32gxyswq3qn76nq-org_openjfx_javafx-base-14.jar.drv'...
building '/nix/store/y24vdxrrn0ysis6akc3c878hb0y4msyk-org_openjfx_javafx-base-14.jar.drv'...

trying http://jcenter.bintray.com/org/openjfx/javafx-base/14/javafx-base-14-mac.jar

trying http://jcenter.bintray.com/org/openjfx/javafx-base/14/javafx-base-14.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (56) Recv failure: Connection reset by peer
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (52) Empty reply from server

trying https://repo1.maven.org/maven2/org/openjfx/javafx-base/14/javafx-base-14.jar

trying https://repo1.maven.org/maven2/org/openjfx/javafx-base/14/javafx-base-14-mac.jar
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   302  100   302    0     0   2826      0 --:--:-- --:--:-- --:--:--  2849
100  733k  100  733k    0     0  3305k      0 --:--:-- --:--:-- --:--:-- 3319k
building '/nix/store/1lgn8fsylbcxj7a005q16jmkd7hak8ih-clj2nixTest.drv'...
building
/nix/store/pql27y38342rrs3r2krrrd2m6avap3w9-clj2nixTest
```

LGTM!

2023-02-05 03:09 UTC, merged