hhpc: init at 0.3.1
NixOS/nixpkgs pull request #21363
Opened 2016-12-22 17:38 UTC by nico202

###### Motivation for this change
unclutter does not work well for me (see https://wiki.archlinux.org/index.php/unclutter "known bugs").
hhpc is lightweight and does its job.

2016-12-23 10:32 UTC, pSub requested changes

2016-12-23 10:32 UTC, pSub commented on pkgs/tools/misc/hhpc/default.nix
> +  meta = with stdenv.lib; {
Please add the license (3-clause BSD).

2016-12-23 10:32 UTC, pSub commented on pkgs/tools/misc/hhpc/default.nix
> +  buildInputs = [ xorg.libX11 pkgconfig ];
Please add pkgconfig to nativeBuildInputs instead of buildInputs. See eg. https://nixos.org/wiki/CrossCompiling

2016-12-26 11:38 UTC, nico202 commented on pkgs/tools/misc/hhpc/default.nix
> +  buildInputs = [ xorg.libX11 pkgconfig ];
always asked what was nativeBuildInput for, thanks :)

2016-12-26 11:39 UTC, nico202 commented on pkgs/tools/misc/hhpc/default.nix
> +  meta = with stdenv.lib; {
sorry, I used unclutter as a base and did not noticed it was missing there, too

2016-12-26 11:45 UTC, nico202 commented on pkgs/tools/misc/hhpc/default.nix
> +  meta = with stdenv.lib; {
#21425 Add the licence to unclutter

2016-12-26 18:28 UTC, grahamc approved these changes

2016-12-27 13:08 UTC, rasendubi approved these changes

2016-12-27 13:09 UTC, merged

2016-12-27 13:11 UTC, rasendubi commented
(built and tested on NixOS with sandboxing)