Darwin gtk2/pygtk quartz backend
NixOS/nixpkgs pull request #21382
Opened 2016-12-23 21:41 UTC by johbo

###### Motivation for this change

I wanted to use a pygtk based application on darwin and noticed that it relied on the X11 backend of gtk which leads to trouble in multi screen setups (lost windows out of screen). Using the quartz backend also leads to a nicer display of the applications.

This Pull Request adjust GTK2 based on the work from #20658. I aimed to keep the changes to the GTK2 Derivation as close as possible to the other PR. The main change is that I added the CoreText dependencies to cairo and pango, so that fonts are actually visible.

Due to #12346 starting the applications still needs a twist by using something like `DYLD_FRAMEWORK_PATH=/System/Library/Frameworks`.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-12-23 21:42 UTC, johbo commented
Regarding the binaries I've tested `gtk-demo` and `pygtk-demo`, those worked fine.

2016-12-24 00:34 UTC, johbo commented
I've done some more experiments, it appears to me as if ApplicationServices should go into the propagatedBuildInputs of cairo.

2016-12-24 13:16 UTC, vbgl commented
This breaks `gnome2.gtksourceview`. It now reports the following error.

```
checking for IGE_MAC... no
configure: error: Package requirements (ige-mac-integration) were not met:

No package 'ige-mac-integration' found
```

You may need to package some extra libraries (https://github.com/rhult/ige-mac-integration).

2016-12-24 15:04 UTC, johbo commented
Uh, it might cause a few more issues like that I guess. I'll try to add ige-mac-integration and make things work.

2016-12-25 00:05 UTC, johbo commented
@vbgl think I got the gtksourceview issue figured out. Do you have any suggestions how I could best check how much this change might affect other packages?

2016-12-25 17:54 UTC, vbgl commented
Indeed, `gtksourceview` now builds. But this PR breaks `coqide`, `inkscape`, `zim`: they build but crash on startup.

2016-12-26 23:55 UTC, LnL7 commented
@johbo nox-review and https://github.com/NixOS/nixpkgs/issues/19045#issuecomment-256920869

2016-12-27 10:35 UTC, johbo commented
Hmm, it seems that all gtk2 based applications will suffer from https://github.com/NixOS/nixpkgs/issues/12346 until we get that sorted. I wonder if it would be better to make this gtk2 change opt-in and build by default for X11 until that's solved.

2017-01-05 23:37 UTC, matthewbauer requested changes
These changes look good! It probably should be merged into staging first though.

Once this gets into master I can work on merging #20658 again.

2017-01-05 23:37 UTC, matthewbauer commented on pkgs/desktops/gnome-2/desktop/gtksourceview/default.nix
> +    ./0001-Change-IgeMacIntegration-to-GtkOSXApplication.patch
Can you use fetchpatch for these?

2017-01-05 23:37 UTC, matthewbauer commented on pkgs/development/libraries/librsvg/default.nix
> +, bzip2, libcroco, libintlOrEmpty, darwin
This shouldn't be needed.

2017-01-07 16:36 UTC, johbo commented
I'll rebase this quickly

2017-01-07 16:46 UTC, johbo commented on pkgs/desktops/gnome-2/desktop/gtksourceview/default.nix
> +    ./0001-Change-IgeMacIntegration-to-GtkOSXApplication.patch
Thanks for the hint, was not yet aware of it. I'll try to use it for both patches.

2017-01-07 20:18 UTC, matthewbauer commented
cc @lnl7 @copumpkin

2017-01-07 20:38 UTC, LnL7 approved these changes

2017-01-07 20:55 UTC, LnL7 commented
Looks like about ~1400 packages will rebuild, I think that's still ok to do on master.

2017-01-07 21:41 UTC, matthewbauer approved these changes

2017-01-07 23:18 UTC, merged