Prometheus exporters
NixOS/nixpkgs pull request #21422
Opened 2016-12-26 06:22 UTC by MostAwesomeDude

###### Motivation for this change

I started using Prometheus recently and I needed to export some stuff.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This all appears to work; https://graphs.matador.cloud/dashboard/db/web-status shows off the nginx and Varnish support, while https://graphs.matador.cloud/dashboard/db/storage-overview uses JSON scraping.

2016-12-26 08:38 UTC, Mic92 requested changes

2016-12-26 08:38 UTC, Mic92 commented on pkgs/servers/monitoring/prometheus/varnish-exporter.nix
> +  rev = "218cffa79f9b56de6a21a9244d74bdc2ec089473";
Is there a reason not to use a released version here? https://github.com/jonnenauha/prometheus_varnish_exporter/releases

2016-12-26 08:38 UTC, Mic92 commented on pkgs/servers/monitoring/prometheus/varnish-exporter.nix
> +  src = fetchgit {
fetchFromGitHub is preferred here.

2016-12-26 08:38 UTC, Mic92 commented on pkgs/servers/monitoring/prometheus/varnish-exporter.nix
> +    license = lib.licenses.mit;
Do you want to maintain this package?

2016-12-26 08:38 UTC, Mic92 commented on nixos/modules/services/monitoring/prometheus/nginx-exporter.nix
> +          ${concatStringsSep " \\\n  " cfg.extraFlags}
script is unnecessary here. Please use `ExecStart` directly.

2016-12-26 08:38 UTC, Mic92 commented on nixos/modules/services/monitoring/prometheus/varnish-exporter.nix
> +          ${concatStringsSep " \\\n  " cfg.extraFlags}
Same here. The `PATH` can be extended using the `path` property.

2016-12-26 08:38 UTC, Mic92 commented on pkgs/servers/monitoring/prometheus/json-exporter.nix
> +  version = "20160913-${stdenv.lib.strings.substring 0 7 rev}";
Please use the following version scheme for packages with releases: `prometheus-json-exporter-unstable-2016-09-13`

2016-12-26 08:38 UTC, Mic92 commented on nixos/modules/services/monitoring/prometheus/json-exporter.nix
> +          ${concatStringsSep " \\\n  " cfg.extraFlags}
same here: `script` -> `ExecStart`

2016-12-26 08:38 UTC, Mic92 commented on pkgs/servers/monitoring/prometheus/json-exporter.nix
> +  src = fetchgit {
`fetchFromGitHub`

2017-01-09 06:25 UTC, fpletz approved these changes
Thanks! Great work! :+1:

But could you please squash your fixes into the previous commits?

2017-01-09 14:20 UTC, globin commented
Cleaned this up a bit and added stuff we had lying around in our fork.

2017-01-09 14:20 UTC, merged