python3Packages.accelerate: init at 0.16.0
NixOS/nixpkgs pull request #214694
Opened 2023-02-05 06:48 UTC by YodaEmbedding

###### Description of changes

Initialize `python3Packages.accelerate`.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
  - [ ] (Release notes changes) Ran `nixos/doc/manual/md-to-db.sh` to update generated release notes
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-02-05 08:06 UTC, dotlambda reviewed
Please add `format` and `pythonImportsCheck`.

2023-02-05 08:06 UTC, dotlambda commented on pkgs/development/python-modules/accelerate/default.nix
> +    pytest
```suggestion
    pytestCheckHook
```

2023-02-05 08:06 UTC, dotlambda commented on pkgs/development/python-modules/accelerate/default.nix
> +    license = with lib.licenses; [ asl20 ];
```suggestion
    license = lib.licenses.asl20;
```

2023-02-05 08:06 UTC, dotlambda commented on pkgs/development/python-modules/accelerate/default.nix
> +    sha256 = "sha256-0T4w8+bev7Rsrae5Ma+FVgYZtqaoOdDK/uq27XxqSY0=";
```suggestion
    hash = "sha256-0T4w8+bev7Rsrae5Ma+FVgYZtqaoOdDK/uq27XxqSY0=";
```

2023-02-05 18:15 UTC, dotlambda requested changes
Tests fail with
```
ModuleNotFoundError: No module named 'evaluate'`
```
and
```
ModuleNotFoundError: No module named 'datasets'
```

2023-02-05 18:15 UTC, dotlambda commented on pkgs/development/python-modules/accelerate/default.nix
> +, pytorch
```suggestion
, torch
```
`pytorch` is just an alias

2023-02-05 18:17 UTC, dotlambda commented
If you call your commit `python310Packages.accelerate: init at 0.16.0` then ofborg will automatically build the package for you.

2023-04-26 14:31 UTC, kira-bruneau commented
Added in https://github.com/NixOS/nixpkgs/commit/71e8e2148d920ba6a1db6f64e94cf135620c4923

2023-04-26 14:31 UTC, closed without merging