update rivet, kakoune, add fastnlo, sherpa, mcgrid
NixOS/nixpkgs pull request #21528
Opened 2016-12-30 19:26 UTC by veprbl

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2016-12-30 19:48 UTC, grahamc requested changes
Just a little typo I think, but looks great. I love seeing these HEP tools in Nixpkgs.

2016-12-30 19:48 UTC, grahamc commented on pkgs/applications/science/physics/sherpa/default.nix
> +    description = "Simulation of High-Energy Reactions of PArticles in lepton-lepton, lepton-photon, photon-photon, lepton-hadron and hadron-hadron collisions";
> PArticles

2016-12-30 22:03 UTC, veprbl commented on pkgs/applications/science/physics/sherpa/default.nix
> +    description = "Simulation of High-Energy Reactions of PArticles in lepton-lepton, lepton-photon, photon-photon, lepton-hadron and hadron-hadron collisions";
S,H,E,R,PA :)

2016-12-31 03:36 UTC, grahamc commented on pkgs/applications/science/physics/sherpa/default.nix
> +    description = "Simulation of High-Energy Reactions of PArticles in lepton-lepton, lepton-photon, photon-photon, lepton-hadron and hadron-hadron collisions";
... D,E,R,PA. Thank you :)

2016-12-31 03:36 UTC, grahamc approved these changes

2016-12-31 03:36 UTC, merged