rubyfmt: init at 0.8.1
NixOS/nixpkgs pull request #215651
Opened 2023-02-10 08:26 UTC by bobvanderlinden

###### Description of changes

This adds the rubyfmt tool; a formatter for Ruby files.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-02-10 11:23 UTC, AndersonTorres approved these changes

2023-02-11 10:53 UTC, bobvanderlinden commented
Thanks for the review :+1:

2023-02-11 11:23 UTC, AndersonTorres commented
Ofborg is failing on many platforms.

2023-05-06 20:18 UTC, AndersonTorres requested changes

2023-05-06 20:18 UTC, AndersonTorres commented on pkgs/development/tools/rubyfmt/default.nix
> +    (cd librubyfmt/ruby_checkout && autoreconf --install --force --verbose && ./configure)
```suggestion
    pushd librubyfmt/ruby_checkout 
    autoreconf --install --force --verbose 
    ./configure
    popd
```

2023-05-06 20:18 UTC, AndersonTorres commented on pkgs/development/tools/rubyfmt/default.nix
> +    platforms = platforms.unix;
```suggestion
```

2023-05-06 20:18 UTC, AndersonTorres commented on pkgs/development/tools/rubyfmt/default.nix
> +    repo = pname;
```suggestion
    repo = "rubyfmt";
```

2023-05-07 19:43 UTC, bobvanderlinden commented
@ofborg build rustfmt

2023-05-07 19:48 UTC, bobvanderlinden commented
@ofborg build rubyfmt

2023-05-07 19:49 UTC, bobvanderlinden commented
Ugh 😅 mixed up the build command for ofborg.

Thanks @AndersonTorres for your feedback. I've incorporated your suggestions 👍

2023-08-01 02:05 UTC, kirillrdy commented on pkgs/development/tools/rubyfmt/default.nix
> +  version = "0.8.1";
0.9.5 is out, but no need to delay merging this

2023-08-01 10:40 UTC, merged

2023-08-01 10:41 UTC, kirillrdy commented
:+1: