nixos/appservice-discord: customizable `package`
NixOS/nixpkgs pull request #215696
Opened 2023-02-10 16:17 UTC by fee1-dead

###### Description of changes

Changed the `matrix-appservice-discord` module to allow customizing the package.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-02-10 16:56 UTC, pacien requested changes
Hi, this patch doesn't seem to work for me.
Did you test this locally?

I'm not opposed to adding this option.
However I've read multiple times that the preferred way of doing this is through an overlay when there is no alternative packages in nixpkgs.

2023-02-10 16:56 UTC, pacien commented on nixos/modules/services/matrix/appservice-discord.nix
> +        example = literalExpression "config.package";
Example value doesn't make sense.

2023-02-10 16:56 UTC, pacien commented on nixos/modules/services/matrix/appservice-discord.nix
> +      package = mkOption {
Please set the default package.

2023-02-10 16:56 UTC, pacien commented on nixos/modules/services/matrix/appservice-discord.nix
> +          ${config.package}/bin/matrix-appservice-discord \
This and other references should use `cfg` instead of `config` to refer to this module's configuration.

2023-02-10 17:05 UTC, fee1-dead commented
> Did you test this locally?

No.. sorry for that, I didn't know how to test a module change but now I have read the manual, and I have tested it now.

2023-02-10 17:05 UTC, fee1-dead commented on nixos/modules/services/matrix/appservice-discord.nix
> +        example = literalExpression "config.package";
I've remove the example.

2023-02-11 19:26 UTC, pacien approved these changes
Patch looks good to me!

2023-02-13 01:50 UTC, merged