gossa: init at 0.2.2
NixOS/nixpkgs pull request #217698
Opened 2023-02-22 14:32 UTC by dsymbol

###### Description of changes
Added the [gossa](https://github.com/pldubouilh/gossa) fast and simple multimedia fileserver.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-02-23 16:11 UTC, azahi requested changes

2023-02-23 16:11 UTC, azahi commented on maintainers/maintainer-list.nix
> +  };
Adding yourself as a maintainer should be a separate commit.

2023-02-23 16:11 UTC, azahi commented on pkgs/applications/networking/gossa/default.nix
> +  };
Please use `fetchFromGitHub`.

2023-02-23 16:11 UTC, azahi commented on pkgs/applications/networking/gossa/default.nix
> +    description = "A fast and simple multimedia fileserver ";
```suggestion
    description = "A fast and simple multimedia fileserver";
```

2023-02-23 16:11 UTC, azahi commented on pkgs/applications/networking/gossa/default.nix
> +buildGoPackage rec {
It's preferred to use `buildGoModule` if possible.

2023-02-24 09:57 UTC, azahi commented on pkgs/applications/networking/gossa/default.nix
> +  doCheck = false;
Why is this disabled? If there's a reason, you should include it in the comment.

2023-02-24 20:37 UTC, azahi requested changes
Looks good, only one thing left.

2023-02-24 20:37 UTC, azahi commented on pkgs/applications/networking/gossa/default.nix
> +
#177698
```suggestion

ldflags = [ "-s" "-w" ];

```

2023-02-25 18:50 UTC, azahi requested changes
Apparently the tests were failing because we can't run them in a sandboxed environment. Can you please replace your derivation with this [file](https://gist.github.com/azahi/72a4fe518a92cf7b718e6338c24e453c). I think I handled all issues in there.

2023-02-25 19:35 UTC, dsymbol commented
Seemed to be working for me previously. However, there was a discussion on the Nix discourse regarding network tests not working properly in the sandboxed environment. Thank you for taking the time to review this PR multiple times. :)

2023-02-26 21:03 UTC, azahi approved these changes

2023-02-26 21:04 UTC, merged