Update ExprTk to tag 0.0.2
NixOS/nixpkgs pull request #217617
Opened 2023-02-22 03:20 UTC by ArashPartow

2023-02-22 05:23 UTC, ArashPartow commented
@schuelermine when you have a moment can you please review and merge this PR.

2023-02-22 05:39 UTC, schuelermine commented
I'm currently not at my PC so I can't build it, I will review soon!

2023-02-22 14:24 UTC, schuelermine requested changes
The hash was incorrect, it should be `sha256-ZV5nS6wEbKfzXhfXEtVlkwaEtxpTOYQaGlaxKx3FIvE=` (not just the format is different).
The commit message should be formatted as `exprtk: unstable-2021-12-31 -> unstable-2023-01-01`.

2023-02-22 22:34 UTC, schuelermine approved these changes

2023-02-23 11:28 UTC, schuelermine commented
(I don't have permissions to merge)

2023-02-23 21:35 UTC, ArashPartow commented
@wegank /  @NickCao  when you have a moment can you please review and merge this PR

2023-02-23 21:37 UTC, wegank commented on pkgs/development/libraries/exprtk/default.nix
> +    hash  = "sha256-ZV5nS6wEbKfzXhfXEtVlkwaEtxpTOYQaGlaxKx3FIvE=";
```suggestion
    repo = "exprtk";
    rev = "f46bffcd6966d38a09023fb37ba9335214c9b959";
    hash = "sha256-ZV5nS6wEbKfzXhfXEtVlkwaEtxpTOYQaGlaxKx3FIvE=";
```

2023-02-23 21:43 UTC, wegank commented on pkgs/development/libraries/exprtk/default.nix
> +  version = "unstable-2023-01-01";
```suggestion
  version = "0.0.2";
```

2023-02-23 21:44 UTC, wegank commented on pkgs/development/libraries/exprtk/default.nix
> +    hash  = "sha256-ZV5nS6wEbKfzXhfXEtVlkwaEtxpTOYQaGlaxKx3FIvE=";
```suggestion
    repo = "exprtk";
    rev = version;
    hash = "sha256-ZV5nS6wEbKfzXhfXEtVlkwaEtxpTOYQaGlaxKx3FIvE=";
```

2023-02-23 21:44 UTC, wegank commented on pkgs/development/libraries/exprtk/default.nix
>  stdenv.mkDerivation {
```suggestion
stdenv.mkDerivation rec {
```

2023-02-24 01:41 UTC, schuelermine approved these changes

2023-02-24 10:32 UTC, wegank commented
Also, please squash the commits, thanks!

2023-02-25 14:56 UTC, schuelermine requested changes
commit message should now end in "-> 0.0.2"

2023-02-25 14:57 UTC, schuelermine commented
Sorry :/

2023-03-02 06:10 UTC, wegank commented
@ofborg eval

2023-03-02 07:31 UTC, merged