Dependencies for realms-wiki
NixOS/nixpkgs pull request #21873
Opened 2017-01-14 00:11 UTC by Mic92

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-01-14 09:36 UTC, Mic92 commented
I will put all packages into seperate files.

2017-01-15 13:11 UTC, Mic92 commented
@FRidh I also move out packages out of python-packages.nix here. Can you take a look at some packages and tell me whether you agree on the way I pull in python packages into the scope into external packages.

2017-01-15 15:46 UTC, FRidh requested changes
Thanks for moving out those packages Just one more change is needed. Aside from that it looks good to me!

2017-01-15 15:46 UTC, FRidh commented on pkgs/development/python-modules/dulwich.nix
> +, pkgs, gevent, geventhttpclient, mock, fastimport }:
not the package set `pkgs` but individual packages

2017-01-15 16:28 UTC, Mic92 commented on pkgs/development/python-modules/dulwich.nix
> +, pkgs, gevent, geventhttpclient, mock, fastimport }:
How can I avoid shadowing of packages from `pkgs` by python packages with the same name in this case?

2017-01-15 16:33 UTC, FRidh commented on pkgs/development/python-modules/dulwich.nix
> +, pkgs, gevent, geventhttpclient, mock, fastimport }:
You can explicitly pass the package to `callPackage`, e.g. `inherit (pkgs) git;`,

2017-01-18 17:31 UTC, Mic92 commented on pkgs/development/python-modules/dulwich.nix
> +, pkgs, gevent, geventhttpclient, mock, fastimport }:
the reasoning behind passing individual packages is to make it easier to overwrite them?

2017-01-18 19:37 UTC, globin commented
@FRidh is specifying python packages in seperate files the prefered syle now?

2017-01-18 19:55 UTC, FRidh commented
The file is getting way too big, and the history is also not  useful, so yes.

2017-01-19 11:23 UTC, merged