Fuchsia Pop
NixOS/nixpkgs pull request #221034
Opened 2023-03-13 18:31 UTC by mrtuxa

###### Description of changes

added Fuchsia Pop cursor theme

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-03-13 18:47 UTC, Zaechus requested changes
Also please change the PR title to reflect the [contributing guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#submitting-changes).

2023-03-13 18:47 UTC, Zaechus commented on maintainers/maintainer-list.nix
> +  }
```suggestion
  };
```
Forgot a semicolon

2023-03-13 18:47 UTC, Zaechus commented on pkgs/desktops/cursor/fuchsia-pop/default.nix
> +}
```suggestion
}

```
No newline at end of file

2023-03-13 18:47 UTC, Zaechus commented on pkgs/top-level/all-packages.nix
> +  fuchsia-pop = callPackage ../cursor/fuchsia-pop
```suggestion

  fuchsia-pop = callPackage ../cursor/fuchsia-pop
```

2023-03-13 18:47 UTC, Zaechus commented on pkgs/desktops/cursor/fuchsia-pop/default.nix
> +  '';
```suggestion
  installPhase = ''
    runHook preInstall
    mkdir -p $out/share/icons
    cp -r ./Fuchsia-Pop* $out/share/icons
    runHook postInstall
  '';
```
Formatting

2023-03-13 18:47 UTC, Zaechus commented on pkgs/desktops/cursor/fuchsia-pop/default.nix
> +  src =  fetchurl {
Looks like the repo has instructions to build from source. Maybe try that instead?

2023-03-13 20:34 UTC, Shawn8901 commented on pkgs/top-level/all-packages.nix
> +  fuchsia-pop = callPackage ../cursor/fuchsia-pop
```suggestion
  fuchsia-pop = callPackage ../cursor/fuchsia-pop { };
```

doesnt it also need the `{ };`?

2023-03-14 03:58 UTC, Zaechus commented on pkgs/top-level/all-packages.nix
> +  fuchsia-pop = callPackage ../cursor/fuchsia-pop
You're right I missed that.

2023-03-29 08:15 UTC, closed without merging