dspdfviewer: init at 1.15.1
NixOS/nixpkgs pull request #221152
Opened 2023-03-14 10:30 UTC by e1mo

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-18 21:39 UTC, doronbehar requested changes
I'd also recommend using `pkgs/by-name`.

2023-10-18 21:39 UTC, doronbehar commented on pkgs/applications/office/dspdfviewer/default.nix
> +{ stdenv
It's very uncommon to put `stdenv` first. Many people recommend using `lib` first, and `stdenv` afterwards.

2023-10-18 21:39 UTC, doronbehar commented on pkgs/applications/office/dspdfviewer/default.nix
> +    qt5.qtbase
You can use `libsForQt5.qtbase` etc as well.

2023-10-18 21:39 UTC, doronbehar commented on pkgs/applications/office/dspdfviewer/default.nix
> +    "\${qtWrapperArgs[@]}"
The more common pattern you see in Nixpkgs is `''${qtWrapperArgs[@]}`, but if it's working I guess it'd OK.

2023-10-18 21:39 UTC, doronbehar commented on pkgs/applications/office/dspdfviewer/default.nix
> +    "-DDCMAKE_BUILD_TYPE=Release"
Isn't this set by default? By `cmake.setupHook`? Also, is there a typo here?

2023-10-18 21:39 UTC, doronbehar commented on pkgs/applications/office/dspdfviewer/default.nix
> +    "-DCMAKE_CXX_FLAGS_INIT=\"-Wno-error=deprecated-declarations\" "
Is upstream aware of these deprecation issue? If not, it'd be nice to notify them, and in any case put a link to an upstream issue.

2023-10-18 21:39 UTC, doronbehar commented on pkgs/applications/office/dspdfviewer/default.nix
> +    platforms = [ "x86_64-linux" "aarch64-linux" ]; # Offborg builds fail on aarch64-darwin, x86_64-darwin. I'm unable to test/debug this
I'd do this:

```suggestion
    platforms = platforms.all;
    broken = stdenv.isDarwin; # Ofborg builds fail on darwin. Don't have the resources to test/debug this.
```

2023-10-18 21:39 UTC, doronbehar commented on pkgs/applications/office/dspdfviewer/default.nix
> +stdenv.mkDerivation rec {
I recommend the modern `stdenv.mkDerivation(finalAttrs: {`.

2025-02-06 12:08 UTC, donovanglover commented
If you are still interested in this PR, please rebase. Otherwise feel free to close it.

2025-02-07 07:40 UTC, doronbehar commented
No need to keep open PRs from 2023 that their OP doesn't respond IMO. Feel free to open a new PR.

2025-02-07 07:40 UTC, closed without merging