Nikola CMS: init -> 7.8.3
NixOS/nixpkgs pull request #22147
Opened 2017-01-25 21:58 UTC by leenaars

###### Motivation for this change

Nikola is quite a popular and advanced python-based CMS, similar to Lektor.
It required a lot of updates to dependencies, and some new python dependencies, all of which are included.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-01-25 22:28 UTC, globin commented
Could you move the dependencies to seperate files in `pkgs/development/python-modules/` and just call them from `python-packages.nix`. This will eventually happen with all the dependencies, the file is simply getting to large and this will make it easier to handle (git log, merge conflicts, etc.)

2017-01-25 23:13 UTC, fpletz commented on pkgs/top-level/python-packages.nix
> +      license     = "MIT";
Please use `licenses.mit` here.

2017-01-30 17:07 UTC, FRidh requested changes
Are you going to maintain these Python packages?

2017-01-30 17:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    doCheck = false;
include a reason why you disable them

2017-01-30 17:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    propagatedBuildInputs = with self; [ cloudpickle pyinotify pytest ];
does it need pytest during runtime??

2017-01-30 17:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    # ImportError: No module named tests
ok...and how come? Should the test runner be invoked differently, or are tests simply missing? Just stating there was an importerror is not sufficient.

2017-01-30 17:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    doCheck = false;
why?

2017-01-30 17:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    };
are tests working?

2017-01-30 17:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    doCheck = false;
why?

2017-01-30 17:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    doCheck = false;
why?

2017-01-30 17:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
>      doCheck = !isPyPy;  # one check fails with pypy
if its only one test, and the test is broken, then surely we can just disable that one test?

2017-05-16 06:42 UTC, FRidh commented
status update?

2017-10-11 12:17 UTC, closed without merging