remote-exec: init at 1.13.2
NixOS/nixpkgs pull request #221907
Opened 2023-03-18 22:17 UTC by pbsds

###### Description of changes

This is a nice tool to have working on remote machines.
It is essentially a `rsync`-run command-`rsync` flow.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-03-18 22:20 UTC, pbsds commented
@ofborg build remote-exec

2023-03-19 04:12 UTC, AndersonTorres requested changes, later dismissed

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +    platform = platforms.all;
```suggestion
```

The correct name is `platforms`.
Also we don't set platforms on Python packages (except for restricting them).

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +    description = "Work with remote hosts seamlessly via rsync and ssh. Code locally, build and execute remotely";
```suggestion
    description = "Work with remote hosts seamlessly via rsync and ssh";
```

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +  ];
```suggestion
```

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +
```suggestion

  nativeBuildInputs = [
    rsync
  ];

```

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +    hash  = "sha256-xaxkN6XukV9HiLYehwVTBZB8bUyjgpfg+pPfAGrOkgo=";
```suggestion
    owner = "remote-cli";
    repo = "remote";
    rev = "refs/tags/v${version}";
    hash = "sha256-xaxkN6XukV9HiLYehwVTBZB8bUyjgpfg+pPfAGrOkgo=";
```

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +    pydantic
```suggestion
    pydantic
    toml
```

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +# check
```suggestion
```

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +# runtime
```suggestion
```

2023-03-19 04:12 UTC, AndersonTorres commented on pkgs/tools/misc/remote-exec/default.nix
> +, pydantic
```suggestion
, pydantic
, toml
```

2023-06-20 12:59 UTC, AndersonTorres requested changes

2023-06-23 01:26 UTC, AndersonTorres commented
Is this supposed not to run on Darwin?

2023-06-23 20:36 UTC, pbsds commented
Hmm, the x86_64-darwin test seems to fail to react to a inotify file event, while aarch64-darwin produces an event when there should be none.

The offending function `execute_on_file_change` uses the `watchdog` library, where this this specific functionality has been marked bad on darwin in [watchdog/default.nix](https://github.com/NixOS/nixpkgs/blob/ecb441f22067ba1d6312f4932a7c64efa8d19a7b/pkgs/development/python-modules/watchdog/default.nix#L95-L96).
That comments has since been removed on unstable, but that test remains disabled on darwin.

@ofborg build remote-exec

2023-06-24 01:11 UTC, merged