stripe-cli: 1.10.3 -> 1.13.2
NixOS/nixpkgs pull request #222154
Opened 2023-03-20 08:56 UTC by mikroskeem

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-03-20 13:01 UTC, 06kellyjac approved these changes
One comment but LGTM

2023-03-20 13:24 UTC, mikroskeem commented on pkgs/top-level/all-packages.nix
> +    buildGoModule = buildGo119Module;
`buildGoModule` points to `buildGo120Module` right now. I think it can be dropped until next problems arise yeah.

2023-03-20 14:53 UTC, SuperSandro2000 approved these changes

2023-03-21 00:48 UTC, SuperSandro2000 requested changes
a test wants to connect to the internet 

```
--- FAIL: TestConflictWithPluginCommand (0.00s)
    resources_test.go:29: 
                Error Trace:    /build/source/pkg/cmd/resources_test.go:29
                Error:          Received unexpected error:
                                Get "https://stripe.jfrog.io/artifactory/stripe-cli-plugins-local/plugins.toml": dial tcp: lookup stripe.jfrog.io on [::1]:53: read udp [::1]:46227->[::1]:53: read: connection refused
                Test:           TestConflictWithPluginCommand
stripe version master
stripe version master
stripe version master
FAIL
FAIL    github.com/stripe/stripe-cli/pkg/cmd    0.070s
FAIL
error: builder for '/nix/store/a02rxdpizq5y7r42lxhlpwqg87p89ipa-stripe-cli-1.13.12.drv' failed with exit code 1;
```

2023-03-21 16:42 UTC, merged