Initial commit adding the `polybar' package
NixOS/nixpkgs pull request #22222
Opened 2017-01-28 02:52 UTC by crough

Polybar is a nice X11 status bar in the vein of i3bar or xmobar.

https://github.com/jaagr/polybar

There's still a lot I have to do to get this ready to be merged (for instance, adding all of the `meta` property)-- willing to take any feedback, as I've not committed to nixpkgs before.

##### Reviewed points

- [ ] package path fits guidelines
- [ ] package name fits guidelines
- [ ] package version fits guidelines
- [ ] package build on ARCHITECTURE
- [ ] executables tested on ARCHITECTURE
- [ ] `meta.description` is set and fits guidelines
- [ ] `meta.license` fits upstream license
- [ ] `meta.platforms` is set
- [ ] `meta.maintainers` is set
- [ ] build time only dependencies are declared in `nativeBuildInputs`
- [ ] source is fetched using the appropriate function
- [ ] phases are respected
- [ ] patches that are remotely available are fetched with `fetchpatch`

##### Possible improvements

- [ ] Is there an easier way to maintain optional dependencies?
- [ ] Is there any way to read the `config.environment` setting on NixOS?

##### Comments

2017-02-05 18:59 UTC, afldcr commented
Fairly sure I'm read to have this merged in, provided tests start passing.

2017-02-13 19:12 UTC, asymmetric requested changes
Small issues, otherwise works great! :+1:

2017-02-13 19:31 UTC, asymmetric commented on pkgs/applications/misc/polybar/default.nix
> +    nativeBuildInputs = [
I think this should simply be `buildInputs`. `nativeBuildInputs` is used when cross-compiling, which isn't the case here.

2017-02-16 16:54 UTC, afldcr commented on pkgs/applications/misc/polybar/default.nix
> +    src = fetchgit {
Sadly fetchFromGitHub doesn't include submodules, which causes the build process to break.

2017-02-16 16:54 UTC, afldcr commented on pkgs/applications/misc/polybar/default.nix
> +      fetchSubmodules = true;
Fixed!

2017-02-17 01:49 UTC, merged