aichat: init at 0.8.0
NixOS/nixpkgs pull request #222232
Opened 2023-03-20 18:03 UTC by mwdomino

###### Description of changes
This PR adds `aichat` from https://github.com/sigoden/aichat at v0.8.0.

Still a new nixpkgs contributor but I've tested this locally and all appears to work. I followed the relevant guides for packaging Rust applications to land on this format.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-03-20 22:19 UTC, KiruyaMomochi commented
Result of `nixpkgs-review pr 222232` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>aichat</li>
  </ul>
</details>

2023-03-26 14:25 UTC, dit7ya commented on pkgs/tools/misc/aichat/default.nix
> +    rev = "v0.8.0";
```suggestion
    rev = "v${version}";
```

2023-03-26 14:27 UTC, dit7ya requested changes
Hi @mwdomino, welcome to nixpkgs!

Please ensure that,

1. There is a separate commit for adding yourself as a maintainer with the commit message - `maintainers: add mwdomino`
2. The other commit message reads: `aichat: init at 0.8.0`

I am interested in maintaining this package.

2023-03-26 14:27 UTC, dit7ya commented on pkgs/tools/misc/aichat/default.nix
> +    sha256 = "sha256-E/QslRDeifFHlHUELv9rYHjfCAB1yXXiXlWOyPNkfps=";
```suggestion
    hash = "sha256-E/QslRDeifFHlHUELv9rYHjfCAB1yXXiXlWOyPNkfps=";
```

2023-03-26 14:27 UTC, dit7ya commented on pkgs/tools/misc/aichat/default.nix
> +  cargoSha256 = "sha256-7TTHBeZ68G6k5eHBL1zDGsYiTyx27fBbN7Rl9AiZTng=";
```suggestion
  cargoHash = "sha256-7TTHBeZ68G6k5eHBL1zDGsYiTyx27fBbN7Rl9AiZTng=";
```

2023-03-26 14:27 UTC, dit7ya commented on pkgs/tools/misc/aichat/default.nix
> +    maintainers = [ maintainers.mwdomino ];
```suggestion
    maintainers = with maintainers; [ mwdomino ];
```

2023-03-26 14:54 UTC, mwdomino commented
Thanks a ton for the feedback @dit7ya! I've rebased with your suggestions included, let me know if there's anything else you'd like to see changed.

2023-03-26 15:54 UTC, dit7ya commented
Please rebase on current master (that will solve the merge conflict) and force push. Also, ~~`aichat: init at v0.8.0`~~ --> `aichat: init at 0.8.0`.

2023-03-26 17:05 UTC, mwdomino commented
Gotcha, rebased and updated again :)

2023-03-28 11:37 UTC, dit7ya commented
@mwdomino, I think you need to add the following to resolve the darwin build failures

```nix

  nativeBuildInputs = [
    pkg-config
  ];

  buildInputs = lib.optionals stdenv.isDarwin [
    darwin.apple_sdk.frameworks.CoreFoundation
    darwin.apple_sdk.frameworks.Security
  ];
```

2023-03-28 14:31 UTC, mwdomino commented
Awesome, thanks for the tips. I tested this on my Macbook and after adding `pkgs` it seems to fix the build and the app seemed to be working well on Darwin.

2023-03-28 14:39 UTC, dit7ya reviewed
Ah, I forgot to mention `pkg-config` at the top level.

2023-03-28 14:39 UTC, dit7ya commented on pkgs/tools/misc/aichat/default.nix
> +  ];
```suggestion
  nativeBuildInputs = [
    pkg-config
  ];
```

2023-03-28 14:39 UTC, dit7ya commented on pkgs/tools/misc/aichat/default.nix
> +{ pkgs, lib, rustPlatform, fetchFromGitHub }:
```suggestion
{ lib, rustPlatform, fetchFromGitHub, pkg-config }:
```

2023-03-28 19:32 UTC, mwdomino commented
We'll get through this eventually! Updated around your last comments :)

2023-03-29 07:00 UTC, dit7ya requested changes
My bad once again, so sorry. Forgot to mention `stdenv` and `darwin`.

I have tested the following on `x86_64-linux` only - but the definition is correct.

```nix
{ lib
, stdenv
, darwin
, rustPlatform
, fetchFromGitHub
, pkg-config
}:

rustPlatform.buildRustPackage rec {
  pname = "aichat";
  version = "0.8.0";

  src = fetchFromGitHub {
    owner = "sigoden";
    repo = "aichat";
    rev = "v${version}";
    hash = "sha256-E/QslRDeifFHlHUELv9rYHjfCAB1yXXiXlWOyPNkfps=";
  };

  cargoHash = "sha256-7TTHBeZ68G6k5eHBL1zDGsYiTyx27fBbN7Rl9AiZTng=";

  nativeBuildInputs = [
    pkg-config
  ];

  buildInputs = lib.optionals stdenv.isDarwin [
    darwin.apple_sdk.frameworks.CoreFoundation
    darwin.apple_sdk.frameworks.Security
  ];

  meta = with lib; {
    description = "Chat with gpt-3.5/chatgpt in terminal.";
    homepage = "https://github.com/sigoden/aichat";
    license = licenses.mit;
    maintainers = with maintainers; [ mwdomino ];
  };
}
```

2023-03-29 20:20 UTC, dit7ya approved these changes
LGTM. Thanks for your contribution!

2023-04-01 06:26 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/885

2023-04-01 19:24 UTC, bbigras commented
@SuperSandro2000

2023-04-01 22:39 UTC, SuperSandro2000 requested changes
also please rebase

2023-04-01 22:39 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  aichat = callPackage ../tools/misc/aichat { };
Please sort this

2023-04-03 02:31 UTC, mwdomino commented
@SuperSandro2000 - rebased and sorted the package list, thanks for the review

2023-04-05 18:46 UTC, bbigras approved these changes

2023-04-06 01:34 UTC, bbigras commented
friendly ping @SuperSandro2000

2023-04-06 13:47 UTC, merged