linux: fix error with IR remotes
NixOS/nixpkgs pull request #223459
Opened 2023-03-27 23:59 UTC by lorenz

###### Description of changes
Support for IR remotes was originally introduced in NixOS in 2013 with [1]. This worked fine until 2018 with the release of Linux 4.16 which contained [2], which removed the default-enable on the IR decoders. This means that kernels since then build with RC_DEVICES enabled, but RC_DECODERS disabled:
```
CONFIG_RC_DEVICES=y
```

This breaks IR remote support and also leads to the following error on every bootup when such a device is present as devices have a default keymap which uses a protocols decoder, but these decoders are not available:
```
rc_core: Loaded IR protocol module ir-rc6-decoder, but protocol rc-6 still not available
```

Fix this by also enabling RC_DECODERS in the kernel configuration.

[1] https://github.com/NixOS/nixpkgs/commit/b7ccfc258abce98f999035dac83b821360016ac4
[2] https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=22756ae7319b0afc2a80fbdec365a6976a1ad350

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-04-01 14:18 UTC, bjornfor requested changes
LGTM, but must target staging branch due to the amount of rebuilds.

2023-04-01 14:36 UTC, bjornfor approved these changes

2023-04-10 19:40 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2056

2023-04-12 23:15 UTC, lorenz commented
Pinging @Atemu @RaitoBezarius as you've merged recent changes to this config

2023-04-13 06:23 UTC, Atemu approved these changes

2023-04-13 06:25 UTC, merged