nixos/tests/installer: test /boot on ZFS
NixOS/nixpkgs pull request #223412
Opened 2023-03-27 16:07 UTC by Luflosi

###### Description of changes
Let's test / on ZFS and /boot on ZFS in separate tests since the GRUB integration for ZFS seems to be not very well maintained.
If the test breaks in the future it's easier to figure out that ZFS on /boot is at fault and either fix the issue or disable the test.
The new test creates a ZFS pool where all features not compatible with GRUB2 are disabled. The dataset is then mounted on /boot and we check that the installer correctly generates a bootable configuration.
Try to use as many ZFS features as possible to verify that GRUB can handle them.

This PR adds a test to have some more confidence in the change proposed in #195805.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-03-27 19:57 UTC, RaitoBezarius requested changes, later dismissed
Context is needed on the ZFS semantic change, other than that, LGTM, thank you for getting this test :).

2023-03-27 19:57 UTC, Luflosi commented on nixos/modules/tasks/filesystems/zfs.nix
> +        "zfs/compatibility.d".source =  "${cfgZfs.package}/share/zfs/compatibility.d/";
Ok, yeah.

2023-03-27 19:57 UTC, RaitoBezarius commented
Also, sorry probably due to me, conflicts. :)

2023-12-07 12:11 UTC, Luflosi commented
Apparently the `"zfs/compatibility.d".source =  "${cfgZfs.package}/share/zfs/compatibility.d/";` line isn't needed for some reason, see https://github.com/NixOS/nixpkgs/pull/262982#issuecomment-1845193141.

2023-12-07 13:24 UTC, Luflosi commented
cc @misuzu @ElvishJerricco and @RaitoBezarius
cc @Mic92 since you wrote https://github.com/NixOS/nixpkgs/pull/262982#discussion_r1370012618.

2023-12-07 18:52 UTC, misuzu approved these changes
An interesting choice of FS combinations, but I suppose it's fine. Both tests passed for me.

2023-12-07 19:11 UTC, Luflosi commented
Would you prefer a different combination of filesystems? Perhaps ZFS for both / and /boot?
My reasoning for doing it this way is that I want to test both scenarios separately and keep the respective other filesystem as boring as possible.

2023-12-07 19:15 UTC, adamcstephens commented
As long as upstream has documentation showing using a boot zfs pool, we should test it. This PR seems to fulfill that need. https://openzfs.github.io/openzfs-docs/Getting%20Started/NixOS/Root%20on%20ZFS.html

2023-12-14 07:41 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1313

2023-12-28 15:25 UTC, merged