coqPackages.HoTT: 8.16 -> 8.17
NixOS/nixpkgs pull request #223765
Opened 2023-03-29 15:31 UTC by Alizter

We bump the HoTT library to 8.17 and switch to using Dune for the build.

I attempted to include the 8.10 - 8.13 builds but I couldn't get autoconf to work the way I wanted so I gave up in the end.

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-03-29 15:35 UTC, Alizter commented
Result of `nixpkgs-review pr 223765` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

2023-03-29 20:51 UTC, Alizter commented on pkgs/development/coq-modules/HoTT/default.nix
> +  useDune = lib.versions.isEq "8.17" coq.coq-version;
Maybe I should say "HoTT library for Coq 8.17 and onwards will use dune2?

2023-03-29 20:53 UTC, Alizter commented on pkgs/development/coq-modules/HoTT/default.nix
> +      null;
That was a mistake, let me fix.

2023-03-29 20:54 UTC, vbgl commented on pkgs/development/coq-modules/HoTT/default.nix
> +  useDune = lib.versions.isEq "8.17" coq.coq-version;
I just find surprising to test for equality when you explain that 8.17 is a lower bound.

2023-03-29 20:59 UTC, vbgl commented on pkgs/development/coq-modules/HoTT/default.nix
> +      null;
My comment still apply after your “fix”.

2023-03-29 21:00 UTC, Alizter commented on pkgs/development/coq-modules/HoTT/default.nix
> +  useDune = lib.versions.isEq "8.17" coq.coq-version;
Ah I see what you mean. I was going to put a range originally but this didn't make sense so I changed it to isEq. I've now changed it to isLe.

2023-03-29 21:01 UTC, vbgl commented on pkgs/development/coq-modules/HoTT/default.nix
> +  useDune = lib.versions.isEq "8.17" coq.coq-version;
Cool. Thank.

2023-03-29 21:01 UTC, Alizter commented on pkgs/development/coq-modules/HoTT/default.nix
> +      null;
This is what nixpkgs-fmt gives. I can change it back, but it is easier to use a formatter typically.

2023-03-29 22:16 UTC, langston-barrett approved these changes

2023-03-30 10:07 UTC, vbgl requested changes
This breaks `coqPackages.HoTT` (sic).

2023-03-30 18:05 UTC, vbgl approved these changes
Thanks.

2023-03-30 18:05 UTC, merged