workflows: check NixOS/Nixpkgs manual builds for PRs to stable
NixOS/nixpkgs pull request #224148
Opened 2023-03-31 23:58 UTC by lilyinstarlight

###### Description of changes

Right now PRs to stable (backport or otherwise) do not build the manuals and so it is possible such a backport could break the manual builds when they change between stable/unstable

This updates the GHA workflow definition to also build the manual on PRs to `release-*`. I tested it on my nixpkgs fork and the workflow did correctly run

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-04-01 00:00 UTC, zowoq requested changes
It's intentionally disabled for release branches. 

As a github action can't start another github action the automated backport PR won't start a build of the nixos manual. 

I realise it would have helped in your case as it was a manual backport but it doesn't help for the majority of PRs.

2023-04-01 00:08 UTC, winterqt commented
Does it actively hinder any of the automated back ports? If not, I'd say let's just go for it; the more mistakes we can catch the better IMO.

2023-04-01 00:10 UTC, zowoq commented
People see it on their manual backport PRs and expect the same thing on the automated PRs.

A better solution is move both of the manual builds (nixpkgs/nixos) to ofborg.

2023-04-02 13:22 UTC, lilyinstarlight commented
> A better solution is move both of the manual builds (nixpkgs/nixos) to ofborg.

Can you say that here then, where it was decided to leave the functionality as GitHub Actions rather than implementing in OfBorg? https://github.com/NixOS/ofborg/pull/609

> As a github action can't start another github action the automated backport PR won't start a build of the nixos manual.

Side note, but this is obviously solvable since you can dispatch a workflow with a PR number parameter against the PR commit from the backport workflow (to get the manual workflows to show up and run the same on automated PRs), but I understand that doing this in OfBorg is less hacky and just the better solution

2023-04-02 13:24 UTC, lilyinstarlight commented
> People see it on their manual backport PRs and expect the same thing on the automated PRs.

(As another side note, but I expected it for all non-automated PRs so it is surprising behavior regardless of whether or not it happens for automated PRs)

2023-07-17 00:28 UTC, lilyinstarlight commented
Closing in favor of NixOS/ofborg#609

2023-07-17 00:28 UTC, closed without merging