gitx: init at 0.23
NixOS/nixpkgs pull request #225130
Opened 2023-04-07 08:26 UTC by yamashitax

###### Description of changes

Add package [GitX](https://gitx.github.io) as per [package request](https://github.com/NixOS/nixpkgs/issues/222533). 

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-04-10 03:46 UTC, yamashitax commented
@toonn Sorry for the ping. My pull request did not get a reviewer assigned to it, and you were in the `darwin` maintainer team. 🙇

2023-04-11 15:15 UTC, toonn reviewed
Is `GitX` open source software? What's the motivation for not building from source?

(FYI you can ping nixos/darwin-maintainers instead, that should get eyes on your work quicker : ) )

2023-04-11 22:33 UTC, yamashitax commented
> Is `GitX` open source software? 
Yes.
> What's the motivation for not building from source?
Lack of research on my part.

Do you think you could point me in the right direction for building an obj-c package?

> (FYI you can ping nixos/darwin-maintainers instead, that should get eyes on your work quicker : ) )

Thanks!

2023-04-13 12:22 UTC, toonn commented
I don't have any examples no. Grepping around Nixpkgs it should be possible to find something.

2023-04-17 06:09 UTC, natsukium commented
I am unfamiliar with building with Xcode, but you might want to use `xcodebuild`.
If it is difficult, you can add it as `gitx-bin`.
Also, `gitx` seems to be a darwin-specific application and should be added to `pkgs/os-specific/darwin`.

2023-06-02 21:30 UTC, drupol requested changes

2023-06-02 21:30 UTC, drupol commented on pkgs/applications/version-management/gitx/default.nix
> +stdenv.mkDerivation rec {
I think we should use the `finalAttrs` pattern here.

Let me share a couple of useful links regarding this:

1. History: https://discourse.nixos.org/t/avoid-rec-expresions-in-nixpkgs/8293
2. Documentation: https://nixos.org/manual/nixpkgs/unstable/#mkderivation-recursive-attributes
3. Recent example of implementation: https://github.com/NixOS/nixpkgs/compare/17f96f7b978e61576cfe16136eb418f74fab9952..9e6ea843e473d34d4f379b8b0d8ef0425a06defe

2023-06-02 21:30 UTC, drupol commented on pkgs/applications/version-management/gitx/default.nix
> +  };
Can we add the `platform` attribute with its appropriate value in here?

2023-09-14 13:09 UTC, toonn reviewed
If this does not get merged before #244152, it would be nice if it could use `extractDarwinApp`.

2024-03-02 23:37 UTC, yamashitax commented on pkgs/os-specific/darwin/gitx-bin/default.nix
> +    platforms = platforms.darwin;
@toonn 

> The former keeps Hydra from spending time on building and caching a binary.

This applies to only binary files, and - as you indicated - is something that should be avoided whenever we are not building from source, I assume?

> The latter is useful for those who want insights into where software comes from.

Interesting, thank you for the tip.

2025-06-09 20:49 UTC, closed without merging