wluma: 4.1.2 -> 4.2.0
NixOS/nixpkgs pull request #226427
Opened 2023-04-16 09:20 UTC by linyinfeng

###### Description of changes

Update `wluma` to [4.2.0](https://github.com/maximbaz/wluma/releases/tag/4.2.0).

Explanation of two small modifications:

1. After updating the source, `Cargo.lock` and hashes, the package failed to build, complaining `...ld: cannot find -lvulkan: No such file or directory`. So I add `vulkan-loader` to `buildInputs` to fix this issue.

2. Then test `wluma` with `capturer = "wlroots"`, it will panic with `NoWaylandLib`,
   ```
   thread 'predictor-embedded' panicked at 'called `Result::unwrap()` on an `Err` value: NoWaylandLib', src/frame/capturer/wlroots.rs:70:49
   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
   ```
   So I add `wayland` to `LD_LIBRARY_PATH` to fix this issue. 

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wluma</li>
  </ul>
</details>

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-27 14:54 UTC, rodrgz requested changes
I also wonder if `stdenv` and `llvmPackages` are necessary...

2023-06-28 05:43 UTC, linyinfeng commented on pkgs/tools/wayland/wluma/default.nix
>    meta = with lib; {
Thanks for your review! I added the changelog URL, removed `stdenv` and `llvmPackages`, and rebased the commit to the master branch.

2023-06-28 13:00 UTC, rodrgz approved these changes

2023-06-28 13:09 UTC, rodrgz approved these changes

2023-06-29 05:15 UTC, merged