[riscv] isl 0.20 has an ancient config.guess and fails to build on riscv
NixOS/nixpkgs pull request #227383
Opened 2023-04-21 03:28 UTC by kangaroo

###### Description of changes

Add autoreconfHook to isl, to fix issue 226578.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-04-21 06:14 UTC, NickCao approved these changes
diff LGTM, did not test.

2023-04-21 18:02 UTC, amjoseph-nixpkgs approved these changes
@kangaroo, thank you for taking the time (and doing the rebuilds) to track this down and fixing it.  This is the right solution for this kind of problem.

@vcunat, is it okay to merge this to `staging`?

Built on:
- [ ] `x86_64-linux`
- [x] `powerpc64le-linux`
- [ ] `aarch64-linux`
- [ ] `mips64el-linux` (cross from `x86_64-linux`)

2023-04-21 19:23 UTC, Artturin commented
commit msg should follow CONTRIBUTING.md

2023-04-21 22:16 UTC, kangaroo commented
Commit msg was updated

2023-04-22 19:21 UTC, vcunat commented
If I have any concerns, it's about the impact on the "length" of our linux stdenv bootstrapping.

2023-04-22 21:11 UTC, leifhelm approved these changes

2023-04-26 03:20 UTC, kangaroo commented
Can we merge this?

2023-04-26 10:08 UTC, amjoseph-nixpkgs commented
> Can we merge this?

It may have to wait until after the 23.05 release.

This PR triggers a rebuild of every single package in the entirety of nixpkgs.  That is a massive amount of recompiling in order to fix a problem on a platform for which Hydra does not generate binaries.

2023-04-26 10:16 UTC, vcunat commented
That's not an issue.  `stdenv` will be rebuilt regardless due to other changes.

2023-04-26 10:40 UTC, vcunat commented
A simple option might be to add the dependency optionally, only on platforms where it might be needed.  (or at least exclude platforms where we care about bootstrap speed)

2023-04-26 10:46 UTC, amjoseph-nixpkgs commented
Yeah this could get ugly.  `autoconf` needs `gettext`, which takes an eternity to compile (serial build process, one core used at most).

Before this PR nothing needs autoconf until we get to `gawk` (i.e. building our own, not the one from the bootstrapFiles) or `glibc`'s special `python3` -- both of those are after `xgcc`, but `isl` is before.

So this would add a completely new copy of: `autoconf`, `libtool`, `automake`, `gettext`, `m4`, `zlib`, and `texinfo`.



> A simple option might be to add the dependency optionally, only on platforms where it might be needed. (or at least exclude platforms where we care about bootstrap speed)

Yeah I think that's the way to go.

2023-04-26 10:50 UTC, amjoseph-nixpkgs commented on pkgs/development/libraries/isl/generic.nix
> +  nativeBuildInputs = [ autoreconfHook ];
```suggestion
  # Note: isl is used very early in the bootstrap process, so including
  # autoreconfHook here as a dependency triggers a lot of extra builds.
  # So we include it only where needed (old autoconf did not understand RiscV)
  nativeBuildInputs = lib.optionals stdenv.hostPlatform.isRiscV && lib.versionOlder version "0.24" [ autoreconfHook ];
```

2023-04-26 16:00 UTC, vcunat requested changes

2023-04-26 16:00 UTC, vcunat commented on pkgs/development/libraries/isl/generic.nix
> +  nativeBuildInputs = lib.optionals stdenv.hostPlatform.isRiscV && lib.versionOlder version "0.24" [ autoreconfHook ];
The conditional needs parentheses, as noticed by OfBorg.

2023-04-28 08:41 UTC, 0x4A6F approved these changes
Built on:
- [x] `riscv64-linux` (native build took 10h54m23s on VisionFive 2)

2023-04-28 09:26 UTC, merged

2023-04-28 14:18 UTC, vcunat commented on pkgs/development/libraries/isl/generic.nix
> +  nativeBuildInputs = lib.optionals (stdenv.hostPlatform.isRiscV && lib.versionOlder version "0.24") [ autoreconfHook ];
I don't think it's economical in this case.  Lots of other riscv breakages can be introduced and not found until built for riscv.