keepalived: 1.2.19 -> 1.3.2
NixOS/nixpkgs pull request #22754
Opened 2017-02-13 18:37 UTC by mbrgm

2017-02-13 20:59 UTC, vrthra commented on pkgs/tools/networking/keepalived/default.nix
> +  buildInputs = [ openssl ];
Does passing pkgconfig here, allow removal of the preConfigure export of PKG_CONFIG?

2017-02-13 21:00 UTC, vrthra commented on pkgs/tools/networking/keepalived/default.nix
>    src = fetchurl {
fetchFromGitHub may be a better option here since it is more specialized.

2017-02-14 07:52 UTC, mbrgm commented on pkgs/tools/networking/keepalived/default.nix
> +  buildInputs = [ openssl ];
It does.

2017-02-14 15:17 UTC, vrthra commented
Verified on NixOS Linux. I think this PR is ready for merging.

2017-02-14 21:25 UTC, fpletz requested changes

2017-02-14 21:25 UTC, fpletz commented on pkgs/tools/networking/keepalived/default.nix
> -{ stdenv, fetchurl, openssl, net_snmp, libnl }:
Why did you remove support libnl and net_snmp? Sounds generally useful to me. Though libnl should only be enabled if this is build on Linux.

2017-02-14 21:25 UTC, fpletz commented on pkgs/tools/networking/keepalived/default.nix
> +  buildInputs = [ openssl pkgconfig ];
pkgconfig should be in nativeBuildInputs.

2017-02-16 22:08 UTC, joachifm commented
Looks like all review comments have been attended to.

2017-02-16 22:08 UTC, merged