yarsi: init at 0.1.0
NixOS/nixpkgs pull request #227619
Opened 2023-04-22 13:57 UTC by mrtuxa

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-04-23 08:48 UTC, QJoly commented
(Be careful, I'm a noob)

You need to squash your commits

2023-04-23 21:15 UTC, AndersonTorres requested changes

2023-04-23 21:15 UTC, AndersonTorres commented on pkgs/tools/misc/yarsi/default.nix
> +
```suggestion
  cargoHash = "sha256-yr43w53SrdFR2LhYwt6lh4mdNV98vc8XEAFn2JUsfn8=";
```

2023-04-23 21:15 UTC, AndersonTorres commented on pkgs/tools/misc/yarsi/default.nix
> +    sha256 = "sha256-jyiKB2VdCRUzLjD8XaFQOIkgI6gE8uM0ztx4vqd6SrM=";
```suggestion
    hash = "sha256-jyiKB2VdCRUzLjD8XaFQOIkgI6gE8uM0ztx4vqd6SrM=";
```

2023-04-23 21:15 UTC, AndersonTorres commented on pkgs/tools/misc/yarsi/default.nix
> +    description = "Yet another rust system info fetch. ";
```suggestion
    description = "Yet another rust system info fetch";
```

2023-04-24 11:12 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  yarsi = callPackage ../tools/misc/yarsi { };
Please sort this entry into a category and there alphabetically.

2023-04-24 11:12 UTC, SuperSandro2000 commented on pkgs/tools/misc/yarsi/default.nix
> +  meta = with lib; {
```suggestion
  cargoHash = "sha256-yr43w53SrdFR2LhYwt6lh4mdNV98vc8XEAFn2JUsfn8=";

  meta = with lib; {
```

2023-05-03 20:06 UTC, AndersonTorres requested changes

2023-05-03 20:06 UTC, AndersonTorres commented on pkgs/top-level/all-packages.nix
> +  yarsi = callPackage ../tools/misc/yarsi { };
Merge this commit with the other.

2023-05-06 05:18 UTC, AndersonTorres requested changes
Remember to cleanup whitespaces.

Run `git diff --check` to see them.

2023-05-06 05:18 UTC, AndersonTorres commented on pkgs/tools/misc/yarsi/default.nix
> +    sha256 = "sha256-jyiKB2VdCRUzLjD8XaFQOIkgI6gE8uM0ztx4vqd6SrM=";
```suggestion
    hash = "sha256-jyiKB2VdCRUzLjD8XaFQOIkgI6gE8uM0ztx4vqd6SrM=";
```

2023-05-06 05:18 UTC, AndersonTorres commented on pkgs/tools/misc/yarsi/default.nix
> +}
```suggestion
}

```

2023-05-06 13:35 UTC, SuperSandro2000 requested changes

2023-05-06 13:35 UTC, SuperSandro2000 commented on pkgs/tools/misc/yarsi/default.nix
> +
```suggestion

  buildInputs = with darwin.apple_sdk.frameworks; [ SystemConfiguration ];

```

2023-05-06 13:35 UTC, SuperSandro2000 commented on pkgs/tools/misc/yarsi/default.nix
> +{ lib, rustPlatform, fetchCrate }:
```suggestion
{ lib, rustPlatform, fetchCrate, darwin }:
```

2023-08-27 11:12 UTC, closed without merging