kbd: 2.0.3 -> 2.0.4
NixOS/nixpkgs pull request #22793
Opened 2017-02-14 14:53 UTC by rnhmjoj

###### Motivation for this change
The unicode_{start,stop} scripts fail due to a hardcoded path.
I patched that and also updated the package.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using (nope, it's a mass rebuild)
- [x] Tested execution of all binary files
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-02-28 22:02 UTC, rnhmjoj commented
bump

2017-03-05 11:22 UTC, matthiasbeyer requested changes

2017-03-05 11:22 UTC, matthiasbeyer commented on pkgs/os-specific/linux/kbd/default.nix
> +  version = "2.0.4";
The hash didn't change with the package update? I doubt that! :smile:

2017-03-05 15:10 UTC, rnhmjoj commented on pkgs/os-specific/linux/kbd/default.nix
> +  version = "2.0.4";
Oops

2017-03-06 13:55 UTC, grahamc commented
Applied in 0577020929

2017-03-06 13:55 UTC, closed without merging

2017-03-06 13:55 UTC, grahamc commented
Thank you!

2017-07-07 22:03 UTC, rnhmjoj commented
What happened to this change?

2017-07-09 04:25 UTC, therealpxc commented
It looks like these changes are not in fact present in master. @matthiasbeyer @grahamc can we reopen this? It includes fixes for a couple scripts which are currently broken (see the referencing pull request above).

2017-07-09 09:23 UTC, matthiasbeyer commented
I have no rights to reopen this.

2017-07-09 10:40 UTC, rnhmjoj commented
I can make a new one. What is 0577020929 anyway?

2017-07-11 14:51 UTC, therealpxc commented
Did you ever make the new PR? I'd like to see your changes merged. I'm tired of everything wanting to rebuild from source! :-)

2017-07-11 14:58 UTC, rnhmjoj commented
I was waiting from @grahamc to reply but I guess I'll go on.