ocaml-angstrom: init at 0.3.0
NixOS/nixpkgs pull request #22921
Opened 2017-02-17 22:20 UTC by sternenseemann

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-02-18 08:10 UTC, vbgl requested changes

2017-02-18 08:10 UTC, vbgl commented on pkgs/development/ocaml-modules/angstrom/default.nix
> +
`ocplib-endian` is already propagated by `cstruct`, so not needed here.

2017-02-18 08:10 UTC, vbgl commented on pkgs/development/ocaml-modules/angstrom/default.nix
> +    license = stdenv.license.bsd3;
There is no `stdenv.license` attribute, but there is a `stdenv.lib.licenses` one.

2017-02-18 09:21 UTC, sternenseemann commented
@vbgl Thanks for your review! I have fixed your points.

2017-02-18 10:22 UTC, volth commented on pkgs/development/ocaml-modules/angstrom/default.nix
> +{ stdenv, fetchFromGitHub, ocaml, cstruct, ocplib-endian, result, findlib, ocaml_oasis }:
if ```ocplib-endian``` is not used below, it could be omited here

2017-02-18 13:12 UTC, sternenseemann commented on pkgs/development/ocaml-modules/angstrom/default.nix
> +{ stdenv, fetchFromGitHub, ocaml, cstruct, ocplib-endian, result, findlib, ocaml_oasis }:
Done!

2017-02-19 01:12 UTC, vbgl approved these changes

2017-02-19 01:12 UTC, merged