libdbusmenu: require glib-2.0 in pkg-config
NixOS/nixpkgs pull request #229404
Opened 2023-05-02 05:17 UTC by ralismark

###### Description of changes

libdbusmenu-glib has headers which include `<glib.h>`, but does not declare glib as a dependency. This causes include errors if you try to build with just libdbusmenu-glib.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-28 22:21 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2376

2023-06-29 14:00 UTC, SuperSandro2000 commented on pkgs/development/libraries/libdbusmenu/default.nix
> +    '')
Please move into a file

2023-07-02 15:06 UTC, SuperSandro2000 requested changes
otherwise the patch does not apply

2023-07-02 15:06 UTC, SuperSandro2000 commented on pkgs/development/libraries/libdbusmenu/requires-glib.patch
> + Libs: -L''${libdir} -ldbusmenu-glib
```suggestion
 Libs: -L${libdir} -ldbusmenu-glib
```

2023-07-02 15:06 UTC, SuperSandro2000 commented on pkgs/development/libraries/libdbusmenu/requires-glib.patch
> + Cflags: -I''${includedir}/libdbusmenu-glib-0.4
```suggestion
 Cflags: -I${includedir}/libdbusmenu-glib-0.4
```

2023-07-05 03:22 UTC, ralismark commented
@SuperSandro2000 oops sorry! fixed that

2023-07-05 12:29 UTC, merged