mailpile: 0.4.1 -> 0.5.2
NixOS/nixpkgs pull request #23058
Opened 2017-02-21 21:28 UTC by spinus

###### Motivation for this change

New version of mailpile is out, current version is waaaay to old.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-02-21 21:31 UTC, spinus commented
I a problem with upgrading this package, I can't build it properly. There is no issues when I run "python setup.py bdist_wheel" when I run this manually outside of nixpkgs tree. Maybe someone knows what the issue could be and what is potential solution?

2017-02-22 00:48 UTC, Mic92 commented on pkgs/applications/networking/mailreaders/mailpile/default.nix
>    src = fetchgit {
this should be upgraded to `fetchFromGithub`.

2017-02-22 06:18 UTC, fpletz commented on pkgs/applications/networking/mailreaders/mailpile/default.nix
>    src = fetchgit {
The repo uses git submodules which aren't included in the Github tarball.

2017-02-22 08:13 UTC, Mic92 commented
Build is fixed now, but the released pre-release is still to old. At least gpg integration did not work for me. Probably a commit which include this https://github.com/mailpile/Mailpile/pull/1621 is required.

2017-02-22 11:22 UTC, spinus commented
@Mic92 thank you for fixing it, I'll try to work on it.

2017-02-22 12:42 UTC, FRidh commented on pkgs/applications/networking/mailreaders/mailpile/default.nix
>    patchPhase = ''
I think its better to have `postPatch` here. That way one can still pass in patches.

2017-03-01 09:02 UTC, spinus commented on pkgs/applications/networking/mailreaders/mailpile/default.nix
>    patchPhase = ''
done

2017-03-01 09:02 UTC, spinus commented on pkgs/applications/networking/mailreaders/mailpile/default.nix
>    src = fetchgit {
hmm, I moved to fetchFromGitHub but it still building, I'll try to verify later if it's working

2017-03-01 09:04 UTC, spinus commented
it looks like this packages was not released for a long time, I just used master for now. Any ideas if we should keep latest officially released one or stick with master? (maybe we should have 0.5.2 and master as unstable package)

2017-03-01 09:14 UTC, FRidh commented
> (maybe we should have 0.5.2 and master as unstable package)

Yes.

2017-03-01 09:14 UTC, Mic92 commented
@spinus if this is required to get gpg working, I am ok with that. Also mailpile is still in early development.

2017-03-02 00:17 UTC, spinus commented
I wrote to mailpile developers to ask about little clarification on that, here is what I've got:

> If you can, please remove 0.5.2 from NixOS. It is very buggy and
> has serious known security vulnerabilities.
> 
> There will be a release candidate for 1.0 sometime this year;
> until then I am asking the community to please NOT package
> Mailpile at all, as packages will give a false expectation of
> stability, will attract the wrong kind of user and will
> ultimately disappoint people.
> 

So the question is, should we remove mailpile from nixos as it's not ready yet, or we want to keep it anyway (in this case I assume we should clearly communicate that this software is not ready to be used "in production"). What do you think people?
> I know that's not what people want to hear, but that's the
> current state of things.

2017-03-02 06:58 UTC, FRidh commented
Simple, remove it, the maintainer is very clear about it...

2017-03-02 08:08 UTC, BjarniRunar commented
Thanks @FRidh and @spinus for reaching out! Please feel free to be in touch at any time if you have questions, this should only be a temporary situation.

2017-03-06 13:51 UTC, grahamc commented
Can we get a list of these known vulnerabilities, then:

1. set `meta.knownVulnerabilities` on 17.03, unstable
2. mark it as broken on 16.09

2017-03-06 15:52 UTC, BjarniRunar commented
I don't have a curated list of vulnerabilities; I have a bug tracker full of open and closed issues, some of which almost certainly have a security impact.

2017-03-06 15:55 UTC, BjarniRunar commented
Basically, you've now demonstrated *exactly* why I'm asking this not be packaged. We don't have the stability, processes or resources to support that. It should never have been packaged in the first place. The only "consolation" is that those old releases were so buggy that I'd be amazed if anyone ever managed to use them for anything of import.

2017-03-06 22:58 UTC, grahamc commented
I've marked it as broken in our stable distribution: 8605d317d1

2017-03-06 23:03 UTC, grahamc commented
Removing it is a bit tricky due to the service, but would happily merge a PR doing that.

I marked it as insecure on next-stable (17.03, 85b47bbd5e) and unstable (6111f6a756) just in case the removal doesn't happen.

2017-03-10 12:35 UTC, FRidh requested changes

2017-03-10 12:35 UTC, FRidh commented on pkgs/applications/networking/mailreaders/mailpile/default.nix
> +  version = "0.5.x-git-master-20170301";
```
pname = "mailpile";
version = "unstable-2017-03-01";
name = "${pname}-${version}";
```

2017-03-10 12:37 UTC, FRidh commented
I've mentioned one more improvement in case one do wants to get it in. Merging this upgrade I don't mind now that it is marked as insecure.

2017-04-07 20:25 UTC, spinus commented
ok, as mailpile is marked as insecure and there is advice not to releases for anything below 1.0 I assume we can close that

2017-04-07 20:25 UTC, closed without merging