Hiawatha: Init at 10.5
NixOS/nixpkgs pull request #23060
Opened 2017-02-21 21:54 UTC by ndowens

###### Motivation for this change
Add Hiawatha server to repo

###### Things done

- [ x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x ] Tested execution of all binary files (usually in `./result/bin/`)
- [x ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-02-21 21:55 UTC, ndowens commented
@cillianderoiste Ok here is the new PR, sorry; better safe than sorry :)

2017-02-21 23:41 UTC, Mic92 commented
next time it is better to do a `git push --force origin hiawatha` rather then opening a new pull request, because the reviews get lost otherwise.

2017-02-21 23:42 UTC, Mic92 commented on pkgs/servers/http/hiawatha/default.nix
> +enableSSL ? false,
Is enabling tls by default not reasonable for a webserver?

2017-02-21 23:49 UTC, ndowens commented
@Mic92 

> next time it is better to do a git push --force origin hiawatha rather then opening a new pull request, because the reviews get lost otherwise.

I usually do. Like the way I do it is usually rebase git to squash commits and drop when i have too. But in between I synced upstream to my copy and it messed it up to where I seen other people's commits

2017-02-21 23:51 UTC, Mic92 commented on pkgs/servers/http/hiawatha/default.nix
> +  buildPhase =  "cmake";
Is using `buildPhase` required here? I remembered cmake to be automatically detected if added as a `buildInput`.

2017-02-21 23:52 UTC, Mic92 commented on pkgs/servers/http/hiawatha/default.nix
> -enableSSL ? false,
Is enabling tls by default not reasonable for a webserver?

2017-02-21 23:57 UTC, ndowens commented
@Mic92 there we go :)

2017-02-22 06:17 UTC, fpletz requested changes
What's up with the indention? It's not even consistent. :-1:

2017-02-22 09:31 UTC, Mic92 commented
I already have fix indention for this pull request, but apparently it was removed by a force push again.

2017-02-22 10:44 UTC, ndowens commented
@fpletz sorry for indentation , thought it was better, started using vim again so maybe its indentation will be better when I open this nix file with it. 

@Mic92. Hmm I don't think I forced pushed after you or anything but it looks like it has changed a little since I last seen it. Looking at he time commit was pushed, I was asleep so I know I didn't force push it

2017-02-22 20:46 UTC, ndowens commented
@fpletz, @Mic92 Fixed indentation through VIM, so maybe it will be acceptable now :D 🤞

2017-02-23 07:48 UTC, LnL7 commented on pkgs/servers/http/hiawatha/default.nix
> +pkgs, libxslt, zlib, libxml2,
you don't need to go through pkgs, `openssl` is available in the callPackage scope.

2017-02-23 20:43 UTC, ndowens commented on pkgs/servers/http/hiawatha/default.nix
> +pkgs, libxslt, zlib, libxml2,
Done @LnL7

2017-02-26 12:10 UTC, closed without merging

2017-02-26 12:11 UTC, Mic92 commented
I also fixed some other issues like pid directory and so on.