ptask: init at 1.0.0
NixOS/nixpkgs pull request #23062
Opened 2017-02-21 22:34 UTC by spacefrogg

###### Motivation for this change

- Adds a simple GTK GUI for managing taskwarrior tasks

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-02-22 06:14 UTC, fpletz requested changes
You forgot to add the package to `pkgs/top-level/all-packages.nix`.

2017-02-22 06:14 UTC, fpletz commented on pkgs/applications/misc/ptask/default.nix
> +  buildInputs = [ pkgconfig makeWrapper gtk3 json_c ];
`pkgconfig` and `makeWrapper` are `nativeBuildInputs`.

2017-02-24 10:22 UTC, matthiasbeyer requested changes
Overall it looks good, besides my two annotations.

2017-02-24 10:22 UTC, matthiasbeyer commented on pkgs/applications/misc/ptask/default.nix
> +{ stdenv, fetchurl, pkgconfig, makeWrapper, gtk3, json_c, taskwarrior }:
You have taskwarrior here in the input of the function, but not in any buildinputs.

2017-02-24 10:22 UTC, matthiasbeyer commented on pkgs/applications/misc/ptask/tw-version.patch
> ++	    || !strcmp(ver, "2.5.1"))
I can see why we need this patch, but I would really opt for contributing this upstream as well... I'm not sure why there is still the `2.5.0` version in here... Maybe both work? Have you tested it?

2017-02-24 14:56 UTC, spacefrogg commented on pkgs/applications/misc/ptask/default.nix
> +{ stdenv, fetchurl, pkgconfig, makeWrapper, gtk3, json_c, taskwarrior }:
It appears in the call to `wrapProgram` as it is a run-time dependency.

2017-02-24 15:00 UTC, spacefrogg commented on pkgs/applications/misc/ptask/tw-version.patch
> ++	    || !strcmp(ver, "2.5.1"))
I haven't had the time yet to contribute it upstream. `ptask` has a `--force` switch to circumvent this switch, but this obviously degrades usability. It does work, though, as 2.5.1 is a maintenance release. I would leave the patch until it is fixed upstream. As `ptask` is meant to be a graphical interface, it does not make a lot of sense to force the user to go back to the terminal to make it work.

2017-03-09 10:39 UTC, spacefrogg commented
@fpletz, @matthiasbeyer  Are we good to merge, now? I think I addressed all concerns.

2017-03-09 10:47 UTC, matthiasbeyer approved these changes

2017-03-18 16:21 UTC, merged