python3Packages.lmfit: init at 1.2.1
NixOS/nixpkgs pull request #230865
Opened 2023-05-09 12:47 UTC by nomeata

###### Description of changes

Adds a new python package. Yay, more packages!

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable: Unit tests run, basic usage works.
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-05-09 14:20 UTC, nomeata commented
Upstream confirms that the skipped test cases are ok to skip: https://github.com/lmfit/lmfit-py/issues/878

2023-05-10 23:36 UTC, onny commented on pkgs/development/python-modules/lmfit/default.nix
> +
```suggestion
```

2023-05-11 06:16 UTC, mweinelt requested changes

2023-05-11 06:16 UTC, mweinelt commented on pkgs/development/python-modules/lmfit/default.nix
> +}:
Please unpack these to one item per line.

2023-05-11 06:16 UTC, mweinelt commented on pkgs/development/python-modules/lmfit/default.nix
> +  format = "setuptools";
Slight preference towards pyproject build, as it is more future-proof.

Requires `setuptools` and `setuptools-scm` in `nativeBuildInputs`. Not `wheel`, putting it in there is cargo culting.

2023-05-11 06:16 UTC, mweinelt commented on pkgs/development/python-modules/lmfit/default.nix
> +    pytest-cov
We generally don't run coverage related tests. Remove this package and substitute the --cov argument here: https://github.com/lmfit/lmfit-py/blob/master/setup.cfg#L99

2023-05-11 07:47 UTC, nomeata commented
Thanks for the review and suggestions!

2023-05-11 10:22 UTC, onny commented
Result of `nixpkgs-review pr 230865` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python310Packages.lmfit</li>
    <li>python310Packages.lmfit.dist</li>
    <li>python311Packages.lmfit</li>
    <li>python311Packages.lmfit.dist</li>
  </ul>
</details>

2023-05-11 10:22 UTC, merged

2023-05-11 10:22 UTC, onny commented
Thank you!