getoptions: Don't require busybox on macOS
NixOS/nixpkgs pull request #230869
Opened 2023-05-09 13:27 UTC by ryansch

###### Description of changes

I made the dependency on busybox conditional as it does not exist on macOS in nixpkgs.
I also changed the `checkTarget` to remove `check` based on [upstream](https://github.com/ko1nksm/getoptions/blob/a6c2df16302a2d0cd4cafb5396ef3421b2c3a1aa/.github/workflows/test.yml#L24) (this caused the tests to pass for me).

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-05-09 13:27 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/cant-use-getoptions-on-macos/27971/6

2023-05-09 18:01 UTC, matrss requested changes
- `nix run nixpkgs#nixpkgs-review -- pr 230869` ran without issues
- building on NixOS `x86_64-linux` works fine
- resulting executables seem to function, although I do not have a proper project to test them on ATM

Apart from the one suggestion this looks good to me. Thank you for the contribution!

2023-05-09 20:04 UTC, ryansch commented on pkgs/tools/misc/getoptions/default.nix
> +  nativeCheckInputs = [ shellcheck shellspec ksh mksh yash zsh ]
Good catch!

2023-05-10 08:08 UTC, matrss approved these changes

2023-05-11 19:34 UTC, merged