wapp: init at 1.0
NixOS/nixpkgs pull request #231178
Opened 2023-05-10 22:06 UTC by nat-418

###### Description of changes

Wapp is a framework for writing web applications in Tcl

Homepage: https://wapp.tcl-lang.org/home/doc/trunk/README.md

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-05-11 12:00 UTC, natsukium requested changes
Don't forget to add this to `top-level/all-packages.nix`.

2023-05-11 12:00 UTC, natsukium commented on pkgs/development/libraries/wapp/default.nix
> +  version = "1.0";
I couldn't find the version 1.0 tag, which one is it?

2023-05-11 12:00 UTC, natsukium commented on pkgs/development/libraries/wapp/default.nix
> +    description = "Wapp is a framework for writing web applications in Tcl";
```suggestion
    description = "A framework for writing web applications in Tcl";
```
> For brevity, don’t repeat the name of package — just describe what it does.
https://nixos.org/manual/nixpkgs/stable/#var-meta-description

2023-05-11 12:04 UTC, nat-418 commented on pkgs/development/libraries/wapp/default.nix
> +  };
Ok I will change that.

2023-05-11 12:06 UTC, nat-418 commented on pkgs/development/libraries/wapp/default.nix
> +    platforms = platforms.unix;
I suppose it could run on Windows but I have not tested it.

2023-05-13 09:30 UTC, natsukium commented on pkgs/development/libraries/wapp/default.nix
> +  version = "1.0";
OK, then the version should be `unstable-YYYY-MM-DD`.

2023-05-16 13:16 UTC, natsukium commented on pkgs/development/libraries/wapp/default.nix
> +  '';
```suggestion
  installPhase = ''
    runHook preInstall
    
    mkdir -p $out/lib/wapp
    cp $src $out/lib/wapp/wapp.tcl
    cat <<EOF > $out/lib/wapp/pkgIndex.tcl
    package ifneeded wapp 1.0 [list source [file join \$dir wapp.tcl]]
    EOF
    
    runHook postInstall
  '';
```

This is not an `unpackPhase`.
Perhaps it should be defined as `installPhase`.

2023-05-16 13:16 UTC, natsukium commented on pkgs/development/libraries/wapp/default.nix
> +    platforms = platforms.all;
```suggestion
```
`platforms.all` is the default and is not needed.

2023-05-17 10:36 UTC, natsukium commented
If you want to fetch a single file with `fetchurl`, you may need to set `dontUnpack = true`.

2023-05-17 13:15 UTC, natsukium commented
Result of `nixpkgs-review pr 231178` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wapp</li>
  </ul>
</details>

2023-05-18 15:06 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2233

2023-05-19 16:46 UTC, merged