init backgroundremover at 0.2.1
NixOS/nixpkgs pull request #231295
Opened 2023-05-11 13:52 UTC by JayRovacsek

###### Description of changes

This change set implements the backgroundremover python package and requisite dependencies that do not currently exist within nixpkgs.
Backgroundremover is a package to remove backgrounds from images and video and the homepage can be found [here](https://github.com/nadermx/backgroundremover)

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [X] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [X] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Result of `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` run on x86-linux [1](https://github.com/Mic92/nixpkgs-review)

<details><summary>6 packages added:</summary><p>

- python3.10-backgroundremover
- python3.10-commandlines
- python3.10-hsh
- python3.10-PyMatting
- python3.11-commandlines
- python3.11-hsh

</p></details>

<details><summary>12 packages built:</summary><p>

- python310Packages.backgroundremover
- python310Packages.backgroundremover.dist
- python310Packages.commandlines
- python310Packages.commandlines.dist
- python310Packages.hsh
- python310Packages.hsh.dist
- python310Packages.pymatting
- python310Packages.pymatting.dist
- python311Packages.commandlines
- python311Packages.commandlines.dist
- python311Packages.hsh
- python311Packages.hsh.dist

</p></details>

Result of `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review) - note this is under remote builders

<details><summary>6 packages added:</summary><p>

- python3.10-backgroundremover
- python3.10-commandlines
- python3.10-hsh
- python3.10-PyMatting
- python3.11-commandlines
- python3.11-hsh

</p></details>

<details><summary>12 packages built:</summary><p>

- python310Packages.backgroundremover
- python310Packages.backgroundremover.dist
- python310Packages.commandlines
- python310Packages.commandlines.dist
- python310Packages.hsh
- python310Packages.hsh.dist
- python310Packages.pymatting
- python310Packages.pymatting.dist
- python311Packages.commandlines
- python311Packages.commandlines.dist
- python311Packages.hsh
- python311Packages.hsh.dist

</p></details>

Will add nixpkgs-review outputs from aarch64 and x86_64 darwin as soon as I can

2023-05-11 14:16 UTC, JayRovacsek commented
Ah, just noticed; this closes https://github.com/NixOS/nixpkgs/issues/230522 :+1:

2023-05-11 16:35 UTC, AndersonTorres commented
How dare you tell your contribution follows CONTRIBUTING guide?

2023-05-11 17:08 UTC, RaitoBezarius commented
> How dare you tell your contribution follows CONTRIBUTING guide?
> 
> Have you ever read any code from this repo?

Please be more respectful of contributors, if you cannot afford to be nice, please do not review or comment.
This is needlessly aggressive.

2023-05-11 17:09 UTC, JulienMalka requested changes
Hello @JayRovacsek, thanks for your contribution.
You'll need to split it as 1 separate commit for each package added, and follow the proper commit naming convention that you can find in the contributing guide :)

2023-05-11 17:26 UTC, lucasew requested changes
some standard stuff

change the name of this pr to `backgroundremover: init at 0.2.1`

and after that put each change in it's own commit (I start with `git reset --soft HEAD~1` then I start building the commits)

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/backgroundremover/default.nix
> +{ buildPythonPackage, fetchPypi, lib, certifi, charset-normalizer, ffmpeg-python
Write this parameters in this form:
```
{ parameter1
, parameter2
, parameter3
}:
```

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/backgroundremover/default.nix
> +buildPythonPackage rec {
Blank line between the parameters and the function call

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/backgroundremover/default.nix
> +  name = pname;
remove name, use pname only

name is calculated as "${pname}-${version}" automatically

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/backgroundremover/default.nix
> +    maintainers = with maintainers; [ jayrovacsek ];
`maintainers = [ maintainers.jayrovacsek ];`

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/backgroundremover/default.nix
> +    gdown
sort the list

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/commandlines/default.nix
> +    maintainers = with maintainers; [ jayrovacsek ];
same maintainer thing as the other file

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/commandlines/default.nix
> +  name = pname;
remove `name`, same reason as the other file

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/commandlines/default.nix
> +  meta = with lib; {
meta is the last thing

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/commandlines/default.nix
> +  src = fetchPypi {
src right below version

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/hsh/default.nix
> +  meta = with lib; {
meta is the last thing

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/hsh/default.nix
> +  src = fetchPypi {
src right after version

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/hsh/default.nix
> +  propagatedBuildInputs = [ commandlines ];
this right after src

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/pymatting/default.nix
> +  name = pname;
remove name

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/pymatting/default.nix
> +  meta = with lib; {
meta at the end

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/pymatting/default.nix
> +  src = fetchPypi {
src after version

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/pymatting/default.nix
> +  propagatedBuildInputs = [ numpy pillow numba scipy ];
this after src

2023-05-11 17:26 UTC, lucasew commented on pkgs/development/python-modules/pymatting/default.nix
> +  doCheck = false;
check stuff is after nativeBuildInputs

2023-05-11 17:32 UTC, lucasew commented
BTW pro-tip: it's more convenient to run nixpkgs-review with the `--post-result` flag instead of pasting the output in the PR description.

I use that a lot to pipeline the reviews here, sometimes I can't actually review, but I can test if it builds.

2023-05-11 17:38 UTC, lucasew commented
Result of `nixpkgs-review pr 231295` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python310Packages.backgroundremover</li>
    <li>python310Packages.backgroundremover.dist</li>
    <li>python310Packages.commandlines</li>
    <li>python310Packages.commandlines.dist</li>
    <li>python310Packages.hsh</li>
    <li>python310Packages.hsh.dist</li>
    <li>python310Packages.pymatting</li>
    <li>python310Packages.pymatting.dist</li>
    <li>python311Packages.commandlines</li>
    <li>python311Packages.commandlines.dist</li>
    <li>python311Packages.hsh</li>
    <li>python311Packages.hsh.dist</li>
  </ul>
</details>

2023-05-11 18:07 UTC, alyssais commented
@lucasew I think this level of style nitpicking is excessive.  We don't have that level of consistent style across the project, and even the [style rules we do have in the manual](https://nixos.org/manual/nixpkgs/unstable/#sec-syntax) are not widely followed.  Because we don't have a consistent style, being too strict about style can be very offputting for contributors, because one reviewer might tell them style should be one way, and another will tell them something different, which is very arbitrary from the contributor's point of view.

2023-05-11 18:24 UTC, lucasew commented
I agree with you. Some stuff is kinda C++y where people enforce different patterns that sometimes even conflict with each other. I think we need to work towards a written document or something like that with the consensus of the whole community. With that some kind of linter can be used to automate this part. A nitbot xD.

2023-05-11 22:38 UTC, JayRovacsek commented
Extremely big thank you to all of the constructive feedback - I'll address all comments and update this pull request as soon as I can.

Apologies for the singular commit for multiple package additions - this was a misunderstanding on my part from feedback within the unofficial Discord server but I am more than happy to resolve this issue which might alleviate what I suspect the issue @AndersonTorres is trying to raise (plus feedback [here](https://github.com/NixOS/nixpkgs/pull/224579) which likely marries up to the same issue of a singular commit)

I'll on-board all the recommended  style/format changes you've made @lucasew - I'm extremely keen on keeping consistency with the current style and had naively applied a simple `nixfmt` and `deadnix` run across the change-set here.

Again, thanks all :heart: :+1:

2023-05-14 22:45 UTC, JayRovacsek commented
Hi all, I recognise the above problems can be resolved via some git-fu, I however lack the skills to achieve this and have placed my fork of nixpkgs into a bad state to create more pull requests. I am going to close this request, but will reopen a request with all of the above changes applied and commit messages correct.
I'll link this request in that request and vice-versa once it is created shortly.

Again, thanks all for the feedback :heart:

2023-05-14 22:45 UTC, closed without merging

2023-05-14 23:13 UTC, JayRovacsek commented
As described in last comment, please find the new pull request here: https://github.com/NixOS/nixpkgs/pull/231950

2023-05-14 23:42 UTC, JayRovacsek commented
Result of `nixpkgs-review pr 231295` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python310Packages.backgroundremover</li>
    <li>python310Packages.backgroundremover.dist</li>
    <li>python310Packages.commandlines</li>
    <li>python310Packages.commandlines.dist</li>
    <li>python310Packages.hsh</li>
    <li>python310Packages.hsh.dist</li>
    <li>python310Packages.pymatting</li>
    <li>python310Packages.pymatting.dist</li>
    <li>python311Packages.commandlines</li>
    <li>python311Packages.commandlines.dist</li>
    <li>python311Packages.hsh</li>
    <li>python311Packages.hsh.dist</li>
  </ul>
</details>