imaginer: 0.1.3 -> 0.1.5
NixOS/nixpkgs pull request #231479
Opened 2023-05-12 14:10 UTC by 0xMRTT

###### Description of changes

Imaginer is an app for generating pictures with AI (GTK4/LibAdwaita)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-05-12 15:33 UTC, teto requested changes
you should change the hash too else it's still using 1.3

2023-05-12 23:26 UTC, teto commented
ci fails and running the nixkpkgs-review program `nixpkgs-review pr 231479` failed similarly. on x8-64 I got `sha256-1x5ebPdJFX7JDiakl278XLecEND9QKIw1QnFLEiMXJU=` as correct sha

2023-05-13 01:39 UTC, figsoda commented
@ofborg eval

2023-05-20 15:45 UTC, dawidd6 commented
https://github.com/ImaginerApp/Imaginer/releases/tag/v0.2.1 is available now.

2024-03-23 18:05 UTC, SuperSandro2000 commented on pkgs/applications/misc/imaginer/default.nix
> +    hash = "sha256-041liw80q824mgfgh4zsz41kssz13apxkxyhipdg89hyx6k8gl5p=";
```suggestion
    hash = "sha256-t9CHpukeJvTajdD32a8a4Ws9A/n6E/jcq0QgDBCPNBA=";
```

2025-09-29 13:30 UTC, iedame commented
As per https://github.com/NixOS/nixpkgs/pull/433807 I am closing this PR since it is not relevant anymore since package is not available.

2025-09-29 13:30 UTC, closed without merging