cmake: remove fixCmakeFiles
NixOS/nixpkgs pull request #232522
Opened 2023-05-17 23:19 UTC by SuperSandro2000

Rewriting /usr and /opt to /var/empty is no longer necessary since the sandbox was introduced. It also introduced unexpected side effects and changes paths like $out/etc/opt/ to $out/etc/var/empty/

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-05-18 13:13 UTC, bjornfor commented
Nice, this should fix https://github.com/NixOS/nixpkgs/issues/24215.

2023-07-06 13:41 UTC, vcunat commented
I'm not a darwin person, but AFAIK sandbox is still not enabled in there by default and `/usr` and `/opt` paths seem in use on those systems (for non-nix stuff).

2023-07-06 13:54 UTC, vcunat commented
On `*-linux` I wouldn't expect significant fallout from this, at least.

2023-07-06 14:05 UTC, vcunat commented
Actually, on `*-linux` I see risk for use cases like `nix-shell` on non-NixOS.

2023-07-11 03:42 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/making-a-development-flake-for-bespoke-synth/29988/19

2023-07-23 22:13 UTC, SuperSandro2000 commented
> Actually, on `*-linux` I see risk for use cases like `nix-shell` on non-NixOS.

hmmm, not sure if we can just chance that and hope for the best?



> I'm not a darwin person, but AFAIK sandbox is still not enabled in there by default and `/usr` and `/opt` paths seem in use on those systems (for non-nix stuff).

Can someone more firm in darwin comment on that?

2023-07-23 22:20 UTC, reckenrode commented
MacPorts and Homebrew (aarch64-darwin) both put stuff in `/opt`. Homebrew (x86_64-darwin) puts stuff in `/usr/local`. The sandbox is not enabled by default on Darwin, so my concern would be that those things could get picked up accidentally.

2024-01-14 17:19 UTC, SuperSandro2000 commented
> Actually, on `*-linux` I see risk for use cases like `nix-shell` on non-NixOS.

I think this is acceptable as this was creating lots of subtle bugs and sometimes evening installing files into void.



> The sandbox is not enabled by default on Darwin, so my concern would be that those things could get picked up accidentally without it.

but that's also true for any other PATH and those lines of code caused probably more breakages than they fixed and didn't work like expected in the first place anyway.

2024-02-19 19:37 UTC, K900 commented
I really just want to kill it. Can we please kill it.

2024-02-20 00:00 UTC, l0b0 approved these changes

2024-02-20 02:55 UTC, ElvishJerricco requested changes
@K900 It is not acceptable to make things worse on Darwin just because you don't care.

2024-02-20 03:48 UTC, Samasaur1 commented
Given that the sandbox is off by default on Darwin (which seems to be because it doesn't work well enough), this PR would introduce a huge amount of impurities on Darwin. This would be the case not only for users who have Homebrew and/or MacPorts installed alongside Nix, but for any Darwin user, since the system puts files in `/usr` as well.

To me, this seems like a change that would be a huge detriment to users of Nix on Darwin while providing comparatively little benefit to other Nix users

2024-02-20 07:30 UTC, K900 commented
I think I know why the hook is there now. These are the results of applying it to cmake itself: https://gist.github.com/K900/1da3c1e5e1a46ae1dd5c413f9ec35b1d

2024-02-20 07:59 UTC, ElvishJerricco commented
@K900 Thank you. First we need to fix that particular problem you've mentioned, and then let's try to figure out the impact of a PR like this before we merge such a thing.

2024-02-20 19:52 UTC, SuperSandro2000 commented
> Given that the sandbox is off by default on Darwin (which seems to be because it doesn't work well enough), this PR would introduce a huge amount of impurities on Darwin. This would be the case not only for users who have Homebrew and/or MacPorts installed alongside Nix, but for any Darwin user, since the system puts files in `/usr` as well.
> 
> To me, this seems like a change that would be a huge detriment to users of Nix on Darwin while providing comparatively little benefit to other Nix users

If this seems to be only useful on darwin, why not make it a darwin only thing and on Linux we just rely on the sandbox?

2024-02-21 17:55 UTC, Samasaur1 commented
> > Given that the sandbox is off by default on Darwin (which seems to be because it doesn't work well enough), this PR would introduce a huge amount of impurities on Darwin. This would be the case not only for users who have Homebrew and/or MacPorts installed alongside Nix, but for any Darwin user, since the system puts files in `/usr` as well.
> > To me, this seems like a change that would be a huge detriment to users of Nix on Darwin while providing comparatively little benefit to other Nix users
> 
> If this seems to be only useful on darwin, why not make it a darwin only thing and on Linux we just rely on the sandbox?

That seems reasonable to me. And if the Darwin sandbox does reach a point where it is effective and can be enabled by default, this PR could be revisited on Darwin.

2024-02-21 22:29 UTC, bjornfor commented
How will this affect building inside nix-shell on non-NixOS?

2024-02-22 07:17 UTC, K900 commented
It will not.

2024-05-27 16:28 UTC, alexfmpe commented
Aaaah so that's what was going on. 

> changes paths like $out/etc/opt/ to $out/etc/var/empty/

Ran into one of these myself during what would otherwise be a maintenance bump of a package because `src/opt` is a folder with source files there and paths got rewritten to `src/var/empty`. A lot of head-scratching later I find this issue and the `dontFixCmake = true;` fix.

Since this PR seems a ways from being merged, maybe a quick win would be making the sed expression more specific?
https://github.com/NixOS/nixpkgs/blob/a292058564022422d26461512a1fd18bdd4f87ec/pkgs/by-name/cm/cmake/setup-hook.sh#L10

I'm not sure exactly which characters are allowed in filepaths, but at the very least `[a-zA-Z0-9]*/opt` shouldn't be matched right?

2024-05-28 05:33 UTC, K900 commented
FWIW I think the way to fix this is to proceed with the approach in https://github.com/NixOS/nixpkgs/pull/290170. I even got a Hydra jobset for it, but never got around to investigating the failures: https://hydra.nixos.org/jobset/nixpkgs/pr-290170-cmake-hook-shenanigans

2024-05-28 07:32 UTC, SuperSandro2000 commented
The bills failures there are random failures/time outs.

2024-05-28 07:32 UTC, K900 commented
Not all of them, though a lot of them are in fact garbage.

2024-08-13 14:11 UTC, philiptaron commented
@K900 any insights from the above Hydra run?

2024-08-13 14:12 UTC, K900 commented
Everything explodes really badly, notably cmake itself. Someone needs to go through cmake and fix it, and then we can continue.

2024-08-13 14:26 UTC, philiptaron commented
@SuperSandro2000, should this then be marked draft or closed? Seems this proposed way forward has some serious thorns.

2024-08-30 04:16 UTC, reckenrode commented
> but that's also true for any other PATH and those lines of code caused probably more breakages than they fixed and didn't work like expected in the first place anyway.

It is, but the Darwin module bundled with CMake searches those locations by default. It would be nice if it could be made not to do that (even if it doesn’t address every possible problem).

> Also aren't the builds run under a different user even outside the sandbox? If that can't write to there, we should be safe, otherwise this seems like a big glaring issue that affects darwin in general.

The concern wasn’t about writing to those locations. It’s that packages installed with other package managers could be picked up instead of those provided by nixpkgs (e.g., enabling unwanted/unexpected features or causing other problems).

This actually is causing problems for the Darwin refactor. I have a workaround unless this lands first, but I wouldn’t mind a patch or fixup to address the default search paths including other package managers on Darwin.

2024-10-25 00:52 UTC, reckenrode commented
After working on https://github.com/NixOS/nixpkgs/pull/346043 and testing https://github.com/NixOS/nixpkgs/pull/349555, I would support undoing at least the `/usr` mangling.

On Darwin, `/usr/include` doesn’t exist, and `/usr/lib` barely contains anything. Using the SDK as a sysroot maps those locations to `$SDKROOT/usr/include` and `$SDKROOT/usr/lib`, but `fixCmakeFiles` interferes with that. The .NET build needs to link against Swift frameworks, so it attempts to add `-L/usr/lib/swift` to the library path, but that gets mangled to `-L/var/empty/lib/swift`, causing the build to fail to link `libswiftFoundation.dylib` after https://github.com/NixOS/nixpkgs/pull/349555.

2024-10-25 00:54 UTC, emilazy commented
I think that we could reasonably specialize it to `/usr/(local|X11)`  without losing anything and fixing a large portion of the problems here.

2024-10-25 01:08 UTC, emilazy commented
After some discussion on Matrix, we came up with the idea that, since `-I/foo` and `-L/foo` will look under the SDK root first on Darwin, we could simply ensure that our SDK packages (or a separate stub directory we layer on) contain empty `{usr/,opt/}{,local/,X11/}{lib,include}` hierarchies. That should ensure that the common compiler tools don’t access anything leaky even with the sandbox off, and allow us to massively reduce the blast radius of getting rid of this hack.

2025-09-11 19:53 UTC, emilazy commented
Finally got around to tackling this: https://github.com/NixOS/nixpkgs/pull/442167. I no longer consider the purity problems very relevant – at least I don’t believe it makes sense to pay such a high cost to address them only for CMake. However, the patch there should achieve the vast majority of the benefit at a fraction of the cost.

2025-09-12 13:38 UTC, SuperSandro2000 commented
Thanks emily! I am going to close this PR since I do not plan to continue it when others already picked it up.

2025-09-12 13:38 UTC, closed without merging