hieroglyph: init at 0.7.1
NixOS/nixpkgs pull request #23251
Opened 2017-02-27 22:13 UTC by juliendehos

###### Motivation for this change

Generate HTML presentations from plain text sources using python Sphinx.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-03-01 09:28 UTC, cillianderoiste commented
It looks pretty good to me @juliendehos, but I noticed some things you could improve:

1. Add yourself as a maintainer
2. Add a comment to explain why tests are disabled
3. Specify the version separately from the name

2017-03-01 23:05 UTC, juliendehos commented
Ok, fixed.
I don't know why tests fail; error messages are not very helpful...

2017-03-05 10:07 UTC, FRidh requested changes

2017-03-05 10:07 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +  hieroglyph = buildPythonPackage (rec {
please move this expression to `pkgs/development/python-modules/hieroglyph/default.nix`

2017-03-05 23:13 UTC, juliendehos commented on pkgs/top-level/python-packages.nix
> +  hieroglyph = buildPythonPackage (rec {
ok, done

2017-03-25 12:00 UTC, merged