linux: allow to specify extra module build dependencies
NixOS/nixpkgs pull request #232861
Opened 2023-05-19 17:15 UTC by phip1611

###### Description of changes

I'm not sure if this is the right approach but this is definitely necessary. Otherwise, it won't be possible to build (out of tree) modules written in Rust.

For example, "rustc" and "rust-bindgen" are required to be present in very specific versions for Linux's early Rust support. Hence, it is handy to optionally pass such deps.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-05-19 17:52 UTC, figsoda commented
@ofborg eval

2023-05-21 12:08 UTC, phip1611 commented
I really don't know what it takes to make the Kernel build in Nix DO NOT drop CONFIG_RUST=y.
On top of the changes in this PR, I've added `RUSTC=$(which rustc) BINDGEN=$(which bindgen) scripts/rust_is_available.sh -v` to the postPatch hook and could verify that this script succeeds. 

However, the resulting `.config`-file of the kernel build (see #232859) ALWAYS drops all options with `RUST`. If I use a similar build environment directly in a shell without nix-build but just a nix-shell, it works fine...


--
ping @SuperSandro2000 - Could you help me plase?

2023-05-21 15:06 UTC, SuperSandro2000 commented on pkgs/os-specific/linux/kernel/manual-config.nix
> +  extra-build-dependencies ? []
```suggestion
  # Additional native build dependencies.
  # For example, "rustc" and "rust-bindgen" are required to be present in very specific versions for Linux's early Rust support.
  extraNativeBuildInputs ? []
```

2023-05-21 15:06 UTC, SuperSandro2000 commented on pkgs/os-specific/linux/kernel/manual-config.nix
> +  ++ extra-build-dependencies;
```suggestion
  ++ extraNativeBuildInputs;
```

2023-05-21 15:06 UTC, SuperSandro2000 commented on pkgs/os-specific/linux/kernel/manual-config.nix
> +      ++ extra-build-dependencies
```suggestion
      ++ extraNativeBuildInputs
```

2023-05-22 08:27 UTC, alyssais requested changes
This doesn't "enable Rust" at all.  It just adds a redundant way for a caller to override dependencies.  Packages should know their own dependencies, not force the caller to decide what they are.  If, in some special situation, the caller does need to override dependencies, they can already do that with `overrideAttrs`.

If you want to add Rust support for kernels to Nixpkgs, just add the dependencies normally.  You could gate it behind the existing `features` parameter to avoid adding the dependencies to kernels without useful Rust code in them, and then we can enable it by default once there are actual user-observable features that need Rust.

2023-05-22 09:33 UTC, alyssais commented
No, I mean that the expression in manual-config.nix should add the Rust dependencies itself, like it already does for every other dependency of the kernel.

2023-05-22 09:36 UTC, phip1611 commented
How will it then be possible to pass in very specific versions of rustc and rust-bindgen except for using an nixpkgs overlay?

2023-05-22 10:05 UTC, alyssais commented
Well, we have the same `override` mechanism available that every other package has.

> Again, the kernel build is very picky about specific versions of those tools. At least for the early Rust support. Will be more relaxed in a year or so.

Is it actually? The kernel documentation says

> Newer versions may or may not work because the kernel depends on some unstable Rust features, for the moment.

Is this actually a problem in practice?  Are there any problems when using the versions of Rust and bindgen in Nixpkgs?

2023-05-23 09:20 UTC, phip1611 commented
> Is this actually a problem in practice? Are there any problems when using the versions of Rust and bindgen in Nixpkgs?

Yes, it is. For example, with the latest Rust-for-Linux state and the latest nixpkgs state, the build fails as rust-bindgen is too new. However, if I downgrade rust-bindgen to an older version, (0.61 instead of 0.63), it works.

2023-05-23 09:49 UTC, alyssais commented
AIUI Rust drivers are likely to start showing up in 6.5 or 6.6, so unless the bindgen version requirements are going to relax _very_ soon, we're going to want Rust enabled by default even with the requirements for special versions.  There's not a lot of time until then, and I don't expect much to change, so we might as well start working towards having Rust enabled by default now.  There's no point making everybody that wants to use it write the same code out of tree.

We should revisit https://github.com/NixOS/nixpkgs/pull/179581 and introduce a package for whatever bindgen version is currently required by Linux, and then have the Linux build enable Rust by default.

2023-05-23 09:49 UTC, alyssais commented
(I've changed my mind somewhat about the `features` parameter — I don't think there's much reason not to just enable Rust by default.)

2023-05-23 09:56 UTC, phip1611 commented
At the moment, I'm still fighting the problem that `manualConfig` always discards `CONFIG_RUST=y`, but only for nixpkgs/master. On nixpkgs/22.11. this doesn't happen. Will update the PR soon accordingly.

2023-05-24 09:16 UTC, phip1611 commented
> One issue that this PR still has is that bindgen builds against the wrong clang version.

To be precisely: Also passing in a valid `rust-bindgen` from the outside doesn't work. `make rustavailable` works in the `postPatch` step but fails in the `configurePhase` step. It always uses the internal bindgen.

The line `make $makeFlags "''${makeFlagsArray[@]}" oldconfig` is the reason where `make $makeFlags "''${makeFlagsArray[@]}" rustavailable` fails.

I don't know the exact details but providing a specific `kernel-rust-bindgen` within nixpkgs will be the right thing to do.

2023-07-13 07:47 UTC, phip1611 commented
Closing in favor of https://github.com/NixOS/nixpkgs/pull/234311

2023-07-13 07:47 UTC, closed without merging