srb2: 2.2.10 -> 2.2.11
NixOS/nixpkgs pull request #233085
Opened 2023-05-20 20:03 UTC by donovanglover

Fixes #203224
Fixes #232984
Based on #187320

###### Description of changes

- Changelog: https://github.com/STJr/SRB2/releases/tag/SRB2_release_2.2.11
- Replaced mazmazz assets with official assets
- CMake patch reverts https://github.com/STJr/SRB2/commit/036d5cce406ee0112ec109181ce58221a4cb06e8 to avoid depending on [`cpm-cmake`](https://github.com/cpm-cmake/CPM.cmake)

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-05-22 17:29 UTC, tomodachi94 requested changes
Looks good for the most part.

2023-05-22 20:36 UTC, donovanglover commented on pkgs/games/srb2/default.nix
> +    ./cmake.patch
Sure! I simplified the patch since it didn't need to be a full revert and added a comment above it.

2023-07-03 18:53 UTC, tomodachi94 requested changes
Lgtm, just some minor nits.

2023-07-03 18:53 UTC, tomodachi94 commented on pkgs/games/srb2/default.nix
> +    sha256 = "sha256-tyiXivJWjNnL+4YynUV6k6iaMs8o9HkHrp+qFj2+qvQ=";
```suggestion
    hash = "sha256-tyiXivJWjNnL+4YynUV6k6iaMs8o9HkHrp+qFj2+qvQ=";
```

2023-07-03 18:53 UTC, tomodachi94 commented on pkgs/games/srb2/default.nix
> +      sha256 = "sha256-KsJIkCczD/HyIwEy5dI3zsHbWFCMBaCoCHizfupFoWM=";
```suggestion
      hash = "sha256-KsJIkCczD/HyIwEy5dI3zsHbWFCMBaCoCHizfupFoWM=";
```

2023-07-03 20:10 UTC, donovanglover commented on pkgs/games/srb2/default.nix
> +    sha256 = "sha256-tyiXivJWjNnL+4YynUV6k6iaMs8o9HkHrp+qFj2+qvQ=";
Changed

2023-07-03 20:11 UTC, donovanglover commented on pkgs/games/srb2/default.nix
> +      sha256 = "sha256-KsJIkCczD/HyIwEy5dI3zsHbWFCMBaCoCHizfupFoWM=";
Changed

2023-07-03 20:26 UTC, tomodachi94 approved these changes
Lgtm. Thank you for contributing!

2023-07-07 22:21 UTC, zeratax approved these changes

2023-07-16 13:18 UTC, merged