nixos/legit: init
NixOS/nixpkgs pull request #233619
Opened 2023-05-23 13:50 UTC by ratsclub

###### Description of changes

Add [legit](https://github.com/icyphox/legit), a web frontend for git, package and module.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.05 Release Notes (or backporting 22.11 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-05-23 16:10 UTC, AndersonTorres reviewed
Reorganize the commit history.

2023-05-23 16:10 UTC, AndersonTorres commented on pkgs/applications/version-management/legit-web/default.nix
> +
```suggestion

```

2023-05-23 16:10 UTC, AndersonTorres commented on pkgs/applications/version-management/legit-web/default.nix
> +  vendorSha256 = "sha256-RAUSYCtP4rcJ2zIBXfPAEZWD1VSfr3d4MrmUMiPpjK8=";
```suggestion
  vendorHash = "sha256-RAUSYCtP4rcJ2zIBXfPAEZWD1VSfr3d4MrmUMiPpjK8=";
```

2023-05-23 16:10 UTC, AndersonTorres commented on nixos/tests/legit.nix
> +  meta.maintainers = [ ratsclub ];
```suggestion
  meta.maintainers = [ lib.maintainers.ratsclub ];
```

2023-05-23 16:10 UTC, AndersonTorres commented on nixos/tests/legit.nix
> +
```suggestion
```

2023-05-23 19:16 UTC, thiagokokada commented on nixos/modules/services/networking/legit.nix
> +    };
```suggestion
    package = mkPackageOptionMD pkgs "legit-web" { };
```

2023-05-24 11:28 UTC, AndersonTorres commented
Split the commits according to the modules affected.
- one for inclusion of the program itself
- other for the NixOS module
- another for the NixOS tests

2023-05-24 12:49 UTC, ratsclub commented
@AndersonTorres is this how you expected the commits to be?

2023-05-24 12:52 UTC, thiagokokada approved these changes

2023-05-24 12:59 UTC, AndersonTorres requested changes
Minor fixups; besides, looks good enough.

2023-05-24 17:30 UTC, AndersonTorres commented
This should be some legacy code expecting extra options. It deserves further investigation, but not now.

2023-05-24 17:34 UTC, AndersonTorres requested changes

2023-05-24 17:34 UTC, AndersonTorres commented on nixos/modules/services/networking/legit.nix
> +{ config, lib, pkgs }:
```suggestion
{ config, lib, pkgs, ... }:
```

Here the ellipsis are needed.

2023-05-24 17:34 UTC, AndersonTorres commented on nixos/modules/services/networking/legit.nix
> +  service = "legit";
```suggestion
```

Unneeded.

2023-05-24 17:34 UTC, AndersonTorres commented on nixos/tests/legit.nix
> +import ./make-test-python.nix ({ lib, pkgs }:
```suggestion
import ./make-test-python.nix ({ lib, pkgs, ... }:
```

2023-05-25 00:12 UTC, AndersonTorres requested changes

2023-05-25 00:12 UTC, AndersonTorres commented on pkgs/applications/version-management/legit-web/default.nix
> +, ...
```suggestion
```

Removing this line causes any problem?

2023-05-25 15:27 UTC, AndersonTorres approved these changes

2023-05-25 15:28 UTC, AndersonTorres commented
Ping me 2 days for merge.

2023-05-27 16:20 UTC, merged