docopt.cpp: init at 0.6.2
NixOS/nixpkgs pull request #23400
Opened 2017-03-02 18:07 UTC by knedlsepp

###### Motivation for this change
docopt.cpp is an awesome alternative to Boost.Program_options.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [x] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-03-02 21:52 UTC, ndowens requested changes

2017-03-02 21:52 UTC, ndowens commented on pkgs/development/libraries/docopt_cpp/default.nix
> +
cmake should be in nativeBuildInputs

2017-03-02 21:52 UTC, ndowens commented on pkgs/development/libraries/docopt_cpp/default.nix
> +  meta = with stdenv.lib; {
no need of writing stdenv.lib in license and platforms when you do meta = with stdenv.lib

2017-03-03 07:58 UTC, knedlsepp commented
@ndowens: Thanks for the review. I removed the stdenv.lib redundancy and made both cmake and python (which is used only for the unit tests) compile time dependencies.

2017-03-03 08:01 UTC, knedlsepp commented
Oh wait. I get it, python shouldn't be a nativeBuildInput. I'll change that back.

2017-03-03 10:49 UTC, ndowens approved these changes

2017-03-04 11:48 UTC, fpletz commented
@knedlsepp If python is only used for the tests it should be in nativeBuildInputs. :smile:

2017-03-04 15:32 UTC, knedlsepp commented
@fpletz: I'm new to cross compiling and confused. When the library is built, it is built in a way that it can be run on some target system. Why do we need the test-dependencies built for the host system? Can the build host even run the cross-compiled tests?

2017-03-08 17:12 UTC, knedlsepp commented
@fpletz: Could you shed some light on why python belongs into nativeBuildInputs?

2017-03-08 17:37 UTC, ndowens commented
If it isn't needed by the actual program to run and only for build, then it is only a builddep that goes in native

Sent from my iphone

On Mar 8, 2017, 11:12 AM -0600, Josef Kemetmüller <notifications@github.com>, wrote:
>
> @fpletz (https://github.com/fpletz): Could you shed some light on why python belongs into nativeBuildInputs?
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://github.com/NixOS/nixpkgs/pull/23400#issuecomment-285104178), or mute the thread (https://github.com/notifications/unsubscribe-auth/AAHL7xTbY68IzCixrBzjWPFjuesYvfS0ks5rjuGRgaJpZM4MRVSd).
>
>
>

2017-03-09 08:02 UTC, knedlsepp commented
Well it is actually used to run it, but only during the checkPhase, so it's not perfectly obvious to me.

2017-03-25 10:41 UTC, joachifm commented
What about the build error https://travis-ci.org/NixOS/nixpkgs/jobs/207280770

2017-03-27 10:34 UTC, knedlsepp commented
@joachifm: Oh. Thanks for pointing that out!

2017-03-27 10:47 UTC, knedlsepp commented
@joachifm: I forced an LD_LIBRARY_PATH during the checkPhase, so the unit test binaries can properly find the library. What's your opinion on the native v. non-native issue?

2017-03-27 11:16 UTC, joachifm commented
Putting python in `nativeBuildInputs` make sense insofar that it runs on the build machine (native here refers to the build machine).

I agree with your point that if code generated for the host cannot run on the build machine, then the build machine cannot perform tests that involve executing said code, without some sort of compatibility mechanism.  As far as Hydra is concerned, I think it's always the case that build=host (at least such that host code can run on build).

2017-03-27 14:21 UTC, knedlsepp commented
Ok. Thanks for your clarifications.

2017-03-27 20:28 UTC, merged