smile: init at 2.3.0
NixOS/nixpkgs pull request #235355
Opened 2023-06-01 08:59 UTC by foo-dogsquared

###### Description of changes

Add [Smile](https://smile.mijorus.it/), an emoji picker for Linux.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-03 03:16 UTC, foo-dogsquared commented
Updated the package to 2.3.1. Also updated the package file a bit. This should also fix the error from ofborg build.

2023-09-30 16:47 UTC, oluceps commented
Run result on gnome wayland.
```
> ./smile 

(process:4127576): Gdk-WARNING **: 00:40:06.509: No such backend: *
Traceback (most recent call last):
  File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/bin/.smile-wrapped", line 45, in <module>
    from smile import main
  File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/share/smile/smile/main.py", line 9, in <module>
    from .Picker import Picker
  File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/share/smile/smile/Picker.py", line 24, in <module>
    from .components.CustomTagEntry import CustomTagEntry
  File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/share/smile/smile/components/CustomTagEntry.py", line 4, in <module>
    from .CustomPopover import CustomPopover
  File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/share/smile/smile/components/CustomPopover.py", line 5, in <module>
    gi.require_version('Adw', '1')
  File "/nix/store/bybx4aya78qc5bw8yb94bsiayh3afmxx-python3.10-pygobject-3.44.1/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace Adw not available
```

As the last review shows, missing dependencies. Add `libadwaita` into `buildInputs` could solve this.

2023-10-07 10:15 UTC, foo-dogsquared commented
> Run result on gnome wayland.
> 
> ```
> > ./smile 
> 
> (process:4127576): Gdk-WARNING **: 00:40:06.509: No such backend: *
> Traceback (most recent call last):
>   File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/bin/.smile-wrapped", line 45, in <module>
>     from smile import main
>   File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/share/smile/smile/main.py", line 9, in <module>
>     from .Picker import Picker
>   File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/share/smile/smile/Picker.py", line 24, in <module>
>     from .components.CustomTagEntry import CustomTagEntry
>   File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/share/smile/smile/components/CustomTagEntry.py", line 4, in <module>
>     from .CustomPopover import CustomPopover
>   File "/nix/store/lv38n9bb0s5n2h2jvwv90f714ic52a39-smile-2.3.1/share/smile/smile/components/CustomPopover.py", line 5, in <module>
>     gi.require_version('Adw', '1')
>   File "/nix/store/bybx4aya78qc5bw8yb94bsiayh3afmxx-python3.10-pygobject-3.44.1/lib/python3.10/site-packages/gi/__init__.py", line 126, in require_version
>     raise ValueError('Namespace %s not available' % namespace)
> ValueError: Namespace Adw not available
> ```
> 
> As the last review shows, missing dependencies. Add `libadwaita` into `buildInputs` could solve this.

Thanks for looking out. I just rebased this to recent revisions from master branch and updated it to 2.8.1. Please have a look again.

2023-10-20 09:57 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1176

2023-10-20 21:15 UTC, pbsds requested changes
Runs fine

Result of `nixpkgs-review pr 235355` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>smile</li>
  </ul>
</details>

The file `/share/smile/smile/smile.in` is executable and has the shebang `#!@PYTHON@`. One of those is likely not intentional.

2023-10-20 21:15 UTC, pbsds commented on pkgs/by-name/sm/smile/package.nix
> +, lib
```suggestion
{ lib
```

2024-05-25 07:03 UTC, closed without merging

2024-05-25 07:03 UTC, Aleksanaa commented
Done in https://github.com/NixOS/nixpkgs/pull/284708