telegram-desktop: 4.8.1 -> 4.8.3
NixOS/nixpkgs pull request #235535
Opened 2023-06-02 07:33 UTC by NickCao

###### Description of changes

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-02 16:26 UTC, drupol approved these changes

2023-06-02 16:26 UTC, drupol commented on pkgs/applications/networking/instant-messengers/telegram/telegram-desktop/default.nix
> +    sha256 = "1xpmkv8lix3iifn96cx3fcd8nv58jpygl406l9ay47fia543vy3y";
How about using `hash` next time?

2023-06-02 16:27 UTC, NickCao commented on pkgs/applications/networking/instant-messengers/telegram/telegram-desktop/default.nix
> +    sha256 = "1xpmkv8lix3iifn96cx3fcd8nv58jpygl406l9ay47fia543vy3y";
We can do it this time.

2023-06-02 16:28 UTC, drupol approved these changes
Good for me after eval is done!

2023-06-02 18:46 UTC, drupol requested changes

2023-06-02 18:46 UTC, drupol commented on pkgs/applications/networking/instant-messengers/telegram/telegram-desktop/default.nix
> +    hash = "1xpmkv8lix3iifn96cx3fcd8nv58jpygl406l9ay47fia543vy3y";
Indeed, the hash is invalid here and needs to be recalculated.

2023-06-03 04:29 UTC, drupol approved these changes

2023-06-03 04:29 UTC, merged