nixos/activation: Add pre-switch checks
NixOS/nixpkgs pull request #236375
Opened 2023-06-06 23:43 UTC by jmbaur

###### Description of changes

Add an option for shell script fragments that are ran before switching to a new NixOS system configuration (pre installation of bootloader or system activation). Also add a new subcommand for
switch-to-configuration called "check" that will cause the program to always exit after checks are ran.

Fixes #169820

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-28 04:03 UTC, ktrinh-anduril commented
any movements on this? This is a pretty important feature to have especially since NixOS is on so many targets now

2023-08-28 19:58 UTC, ktrinh-anduril approved these changes
lgtm

2023-09-23 03:53 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2678

2024-07-18 02:48 UTC, jmbaur commented
@ofborg test switchTest switchTestNg

2024-07-18 02:56 UTC, jmbaur commented
@ofborg test switchTest switchTestNg

2024-11-19 01:31 UTC, jmbaur commented
@ofborg test switchTest switchTestNg

2024-11-21 20:43 UTC, ConnorBaker approved these changes
This should have been merged ages ago.

EDIT: Looks like the recent rebase broke something.

2024-11-21 20:55 UTC, ConnorBaker requested changes
`switchTestNg` fails:

```console
vm-test-run-switch-test> machine # [   12.400333] nixos[1057]: finished switching to system configuration /nix/store/9658x4bx9cn567a04776bg9qwsbw95qr-nixos-system-other-test
vm-test-run-switch-test> (finished: must succeed: /nix/store/69vika84p4i1qpgvnqaqrmnd2hqr38dh-stderr-runner /nix/store/9658x4bx9cn567a04776bg9qwsbw95qr-nixos-system-other-test/bin/switch-to-configuration test, in 1.23 seconds)
vm-test-run-switch-test> subtest: pre-switch checks
vm-test-run-switch-test> machine: must succeed: /nix/store/69vika84p4i1qpgvnqaqrmnd2hqr38dh-stderr-runner /nix/store/9658x4bx9cn567a04776bg9qwsbw95qr-nixos-system-other-test/bin/switch-to-configuration check
vm-test-run-switch-test> machine # Usage: switch-to-configuration [check|switch|boot|test|dry-activate]
vm-test-run-switch-test> machine # check:        run pre-switch checks and exit
vm-test-run-switch-test> machine # switch:       make the configuration the boot default and activate now
vm-test-run-switch-test> machine # boot:         make the configuration the boot default
vm-test-run-switch-test> machine # test:         activate the configuration, but don't make it the boot default
vm-test-run-switch-test> machine # dry-activate: show what would be done if this configuration were activated
vm-test-run-switch-test> machine # 
vm-test-run-switch-test> machine: output:
vm-test-run-switch-test> Test "pre-switch checks" failed with error: "command `/nix/store/69vika84p4i1qpgvnqaqrmnd2hqr38dh-stderr-runner /nix/store/9658x4bx9cn567a04776bg9qwsbw95qr-nixos-system-other-test/bin/switch-to-configuration check` failed (exit code 1)"
vm-test-run-switch-test> cleanup
vm-test-run-switch-test> kill machine (pid 9)
vm-test-run-switch-test> qemu-kvm: terminating on signal 15 from pid 6 (/nix/store/px2nj16i5gc3d4mnw5l1nclfdxhry61p-python3-3.12.7/bin/python3.12)
vm-test-run-switch-test> kill vlan (pid 7)
vm-test-run-switch-test> (finished: cleanup, in 0.01 seconds)
error: builder for '/nix/store/541460imnjxn66pvfx3jiqp1gd43k9l0-vm-test-run-switch-test.drv' failed with exit code 1
```

2024-11-21 21:12 UTC, ConnorBaker approved these changes
Fix applied in latest, tests pass.

2024-11-23 01:33 UTC, merged