janusgraph: use upstream binary scripts
NixOS/nixpkgs pull request #237644
Opened 2023-06-13 22:01 UTC by jlesquembre

###### Description of changes

Upstream provides a binary script to compute the classpath, use it instead of creating our own script.

With this change, the CLI documentation: https://docs.janusgraph.org/operations/server/#starting-a-janusgraph-server also applies to the nixpkgs package.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

ping @ners

2023-06-13 22:03 UTC, ners approved these changes

2023-06-14 06:54 UTC, ners approved these changes
I've already approved! Silly ofborg.

2023-06-14 08:38 UTC, jlesquembre commented
thanks @ners , I noticed that the `scripts` directory is also necessary , added it to the install script

2023-06-19 09:05 UTC, jlesquembre commented
@ners I did some updates to this PR:
- Added the dependencies required by the bash script, and prepend those to PATH in the wrapper script
- Since we required jdk11, which is not the default jdk in nixpkgs, I think it makes more sense to use `jdk11_headless` instead of `jdk11`

2023-06-27 10:43 UTC, ners requested changes
Given that they require such nontrivial dependencies, I'm not so sure I like the upstream scripts over the one I originally generated.

IMO we're better off keeping this package's run scripts manageable and moving the service semantics into a separate layer, e.g. a NixOS module with systemd.

2023-06-27 14:04 UTC, jlesquembre commented
IMO it is still preferable to use upstream scripts instead of writing a custom one. In this case, the required binaries are quite common.

I added a test to check for missing  binaries.

 If we want to add a NixOS service, we still have to create a wrapper for the script, and makes more sense to do it in the package, since we have access to the script in the `src`. Currently, the script is not part of the derivation outputs, and a future NixOS service needs to call `fetchzip` again.

2026-06-30 19:53 UTC, closed without merging