Submit/synadm version bump
NixOS/nixpkgs pull request #237796
Opened 2023-06-14 17:02 UTC by andreiz

###### Description of changes
Bump synadm version to 0.41.3 to integrate a bug fix

###### Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-14 17:05 UTC, emilylange requested changes
Please remove the release note entry and squash your commits into a single one titled `synadm: 0.41.2 -> 0.41.3`.
Thank you! :)

2023-06-14 17:05 UTC, emilylange commented on nixos/doc/manual/release-notes/rl-2311.section.md
> +- `matrix-synapse-tools.synadm` updated to 0.41.3 following a break of some of the CLI commands.
```suggestion
```

Not needed

2023-06-14 19:23 UTC, andreiz commented
Yes, sorry, I fat-fingered it. Will update with the proper commit shortly.

2023-06-14 19:32 UTC, emilylange commented
@ofborg build matrix-synapse.tools.synadm

2023-06-14 22:25 UTC, andreiz commented
Is it normal for aarch64-darwin check to be running for almost 3 hours?

2023-06-15 11:42 UTC, merged

2023-06-15 11:42 UTC, mweinelt commented
Thank you!