cfitsio: 3.21 -> 3.41
NixOS/nixpkgs pull request #23778
Opened 2017-03-12 01:42 UTC by ndowens

###### Motivation for this change
Update

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-03-12 09:02 UTC, vbgl commented
`cfitsio` no longer builds on darwin: “ld: symbol(s) not found for architecture i386”. The full error can be read in the travis log.

2017-03-17 10:31 UTC, matthiasbeyer requested changes
Commit message is IMO not appropriate.

Could you split this up into two commits: one for the package update and one for the platform change? Also - please add a short note in the second commit why the platform change is necessary.

2017-03-17 21:47 UTC, ndowens commented
@matthiasbeyer There we go, had to reset to old commit and redo it, which closed PR, but got it fixed now :)

2017-03-18 10:29 UTC, matthiasbeyer approved these changes

2017-03-19 17:51 UTC, merged