pharo: old -> 10.0.5
NixOS/nixpkgs pull request #237892
Opened 2023-06-15 09:52 UTC by jthulhu

###### Description of changes

The Pharo packages were waaaaay outdated (~10 years old). This is a first attempt to update the packages.

 - [ ] Pharo launcher: the launcher has been deleted from the repo, but hasn't been updated, because the version previously packaged is not compatible with the newly packaged Pharo (at least, I haven't been able to make it work)
 - [ ] Pharo VMs:
   - [X] Spur 64: this has been packaged to version 10.0.5 (which is the latest version available, not to be confused with the version of the Pharo image).
   - [ ] Spur 32: this hasn't been packaged; it *shouldn't* be hard (just changing the source url and the checksum), but it hasn't been done.
   - [X] Cog 32: this is obsolete, so it has been entirely removed.  
 
For this reason, the availability of the Pharo packaged has regressed (only linux x86_64 is supported in this PR).

While this builds and works, any attempt at using Cairo will throw an exception. This should be fixed.

**Important**: the previous maintainer has been removed from the maintainer list, since this packaged was clearly not maintained anymore.

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-16 07:14 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/how-to-download-from-url-while-packaging-for-nixpkgs/29159/1

2023-06-20 20:44 UTC, Mindavi commented on pkgs/development/pharo/default.nix
> +      This package provides the executable VM. You should probably not care
Is this part of the description relevant? Also, bug reports should go to the maintainer first before going upstream :)

2023-06-20 20:44 UTC, Mindavi commented on pkgs/development/pharo/default.nix
> +    cat >"$out/bin/pharo" <<EOF
This should be possible using wrapProgram / makeWrapper. See the nixpkgs manual and other derivations for some info

2023-08-02 17:13 UTC, drupol requested changes
Hi !

Thanks for your contribution.

I've left some comments, left me know if this is clear enough.

2023-08-03 06:29 UTC, drupol requested changes
Thanks for implementing the changes.

Last thing, could you sort alphabetically the lambda parameters, the buildInputs, nativeBuildInputs and the meta attributes ?

Don't forget to squash your commits so that this PR only contains 1 single commit.

2023-08-03 06:29 UTC, drupol commented on pkgs/development/pharo/default.nix
> +    platforms = [ "x86_64-linux" ];
```suggestion
    platforms = lib.platforms.linux;
```

2023-08-03 07:14 UTC, drupol requested changes
I forgot one last nit.

I usually recommend to use `makeBinaryWrapper` by default since it has a much better compatibility with Darwin platforms.

2023-08-03 07:14 UTC, drupol commented on pkgs/development/pharo/default.nix
> +, makeWrapper
```suggestion
, makeBinaryWrapper
```

2023-08-03 07:14 UTC, drupol commented on pkgs/development/pharo/default.nix
> +    makeWrapper
```suggestion
    makeBinaryWrapper
```

2023-08-03 07:36 UTC, drupol reviewed
LGTM now.

I see that you removed a bunch of entries (pharo-vms, pharo-cog32, etc etc)... shoudln't you add something in `aliases.nix` to let the users know that they doesn't exist anymore? And eventually a message in the release note ?

2023-08-03 07:49 UTC, drupol commented
Here's [an example](https://github.com/NixOS/nixpkgs/pull/237824/commits/8a02abacab074e9c2a9ca8af64faeb703d893dac) on how to add an entry in the release note.

The file you need to edit is `nixos/doc/manual/release-notes/rl-2311.section.md`

2023-08-03 08:03 UTC, drupol commented
Could you please rebase your PR so there's only one commit?

2023-08-03 14:00 UTC, RaitoBezarius commented
> @drupol I'm not sure if I properly rebased, now it looks like it wants to merge 68 commits... I merged from `master`, then I rebased to move my commit to the end.

You failed your rebase and pinged other people, please remove those commits.

2023-08-03 14:13 UTC, RaitoBezarius commented
> I'm not too sure how to resolve this merge. If I simply merge, that makes 2 commits and git refuses to amend the previous commit. If I try to rebase, it forcefully inserts commits from master into my branch.

Read the CONTRIBUTING guide on mass pings and retargetting, it is relevant to the problem I imagine.

2023-08-03 14:29 UTC, drupol commented
Hi,

Here's a couple of steps that should help you fixing the current issue:

0. `cd /home/.../nixpkgs`
1. `git checkout master`
2. `git remote add upstream git@github.com:NixOS/nixpkgs.git`
3. `git fetch --all`
4. `git reset upstream/master --hard`
5. `git push`
6. `git checkout update-pharo`
7. `git rebase master`
8. `git push -f`

2023-08-03 15:21 UTC, drupol approved these changes
LGTM !

2023-08-03 16:20 UTC, merged