pfetch-rs: init at 2.7.0
NixOS/nixpkgs pull request #237819
Opened 2023-06-14 20:14 UTC by Gobidev

This PR adds a new package for pfetch-rs, a rewrite of the pfetch system information tool in Rust.

It also adds myself as a maintainer of this package.

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-14 20:51 UTC, Lord-Valen requested changes
Please split the change to maintainers/maintainer-list.nix into its own separate commit called `maintainers: add gobidev`.

Two commits total:

`maintainers: add gobidev`
`pfetch-rs: init at 2.7.0`

2023-06-14 20:51 UTC, Lord-Valen commented on pkgs/tools/misc/pfetch-rs/default.nix
> +  pname = "pfetch";
```suggestion
  pname = "pfetch-rs";
```

2023-06-14 20:51 UTC, Lord-Valen commented on pkgs/tools/misc/pfetch-rs/default.nix
> +    repo = "pfetch-rs";
```suggestion
    repo = pname;
```

2023-06-15 07:40 UTC, Gobidev commented
I added the requested changes

2023-06-15 21:51 UTC, Lord-Valen commented
Result of `nixpkgs-review pr 237819` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>pfetch-rs</li>
  </ul>
</details>

2023-06-15 21:53 UTC, Lord-Valen commented
Works as expected on x86_64-linux.

2023-06-15 21:53 UTC, Lord-Valen approved these changes

2023-06-17 16:23 UTC, drupol requested changes

2023-06-17 16:23 UTC, drupol commented on pkgs/tools/misc/pfetch-rs/default.nix
> +    sha256 = "0b5300g7q9f07pcr5vy42v6wgb8sk6glai3kb5pj7f9ilq87mmr8";
Use `hash` in place of `sha256` please.

2023-06-17 20:44 UTC, drupol approved these changes

2023-06-17 20:44 UTC, drupol commented
@GrahamcOfBorg build pfetch-rs

2023-06-21 02:05 UTC, Lord-Valen approved these changes

2023-06-21 03:05 UTC, merged