qownnotes: add tests
NixOS/nixpkgs pull request #237933
Opened 2023-06-15 13:43 UTC by pbek

###### Description of changes

This adds CLI and UI tests for QOwnNotes.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-15 15:31 UTC, pbek commented on nixos/tests/qownnotes.nix
> +    timeout = 1800;
Yes, it is. Thank you!

2023-06-15 15:31 UTC, pbek commented on nixos/tests/qownnotes.nix
> +    services.xserver.enable = true;
Thank you!

2023-06-15 15:35 UTC, pbek commented on nixos/tests/qownnotes.nix
> +    };
No, thank you!

2023-06-15 15:35 UTC, pbek commented on nixos/tests/qownnotes.nix
> +        machine.wait_for_console_text("QOwnNotes server listening on port 22222")
Great idea, thank you!

2023-06-15 15:41 UTC, NickCao commented
> @NickCao, thanks a lot for your feedback! All pushed now. Any more suggestions?

Nothing particular from me, let's see if others have any ideas.

2023-06-15 16:01 UTC, pbek commented
Result of `nixpkgs-review pr 237933` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

2023-06-15 16:03 UTC, pbek commented
> Result of nixpkgs-review pr 237933 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

I wonder if nixpkgs-review built the tests, the package or both...

2023-06-15 16:05 UTC, illustris approved these changes
Only a minor suggestions. Looks good otherwise.

2023-06-15 16:05 UTC, illustris commented on nixos/tests/qownnotes.nix
> +        ${aliceDo "qownnotes >&2 &"}
```suggestion
        ${aliceDo "qownnotes"}
```
same as above

2023-06-15 16:05 UTC, NickCao commented
@ofborg test qownnotes

2023-06-16 02:00 UTC, AndersonTorres requested changes

2023-06-16 06:19 UTC, pbek commented on nixos/tests/qownnotes.nix
> +import ./make-test-python.nix ({ pkgs, ...} :
Thank you very much!

2023-06-16 06:22 UTC, pbek commented
Thank you for your feedback, @AndersonTorres!

2023-06-16 12:33 UTC, wineee commented
Set `passthru.tests`  can help us automatically trigger this test when upgrading the package
An example is: https://github.com/NixOS/nixpkgs/blob/4c8ca604aef8204145c185c89cc52ee54dd7fc1a/pkgs/applications/window-managers/cage/default.nix#LL43C2-L43C18

2023-06-16 12:34 UTC, wineee approved these changes

2023-06-16 12:43 UTC, pbek commented
@wineee, thank you! I'll add that with the `qownnotes: 23.6.4 -> 23.6.5` update. 😉

2023-06-16 12:44 UTC, NickCao commented
@ofborg test qownnotes

2023-06-16 12:47 UTC, merged

2023-06-16 12:58 UTC, pbek commented
Thank you all for your valuable insight!