rwedid
NixOS/nixpkgs pull request #237942
Opened 2023-06-15 14:27 UTC by Janik-Haag

###### Description of changes

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes (or backporting 23.05 Release notes)](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#generating-2305-release-notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [x] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-15 14:48 UTC, emilylange commented on nixos/doc/manual/release-notes/rl-2311.section.md
> +- [rwedid](https://codeberg.org/ral/rwedid), A tool to read and write EDID data over an I2C bus. Available as [programs.rwedid](#opt-programs.river.enable).
```suggestion
- [rwedid](https://codeberg.org/ral/rwedid), A tool to read and write EDID data over an I2C bus. Available as [programs.rwedid](#opt-programs.rwedid.enable).
```

2023-07-14 19:42 UTC, yu-re-ka commented
I don't think we need an own NixOS module for this. Users can easily add the package to `services.udev.packages` if they wish this behavior.

2023-07-14 19:44 UTC, yu-re-ka commented on nixos/modules/hardware/rwedid.nix
> +      package = lib.mkPackageOptionMD pkgs "rwedid" { };
We don't usually include a `.package` option in NixOS modules, unless there are multiple options available.

2023-07-14 19:45 UTC, Janik-Haag commented
I can remove the module if you want me to, It also creates a group. And wireshark basically does the same.

2023-07-15 17:17 UTC, emilylange requested changes

2023-07-15 17:17 UTC, emilylange commented on pkgs/tools/video/rwedid/default.nix
> +    license = licenses.mit;
```suggestion
    license = licenses.mit;
    platforms = platforms.linux;
```

Seems to be Linux-only software (as it requires a Linux kernel module).

2023-07-15 17:24 UTC, emilylange commented
No no @Janik-Haag, please keep the module.
@yu-re-ka suggested removing the `package` option (`package = lib.mkPackageOptionMD pkgs "rwedid" { };`) specifically. Not the module in itself.

I think there is just a misunderstanding here.

2023-07-15 18:01 UTC, yu-re-ka commented
> No no @Janik-Haag, please keep the module.

No, I also suggested removing the module, since it basically just creates a shortcut to express two lines in one. See my earlier comment.

If each package with udev rules gets its own module, we would have a lot of modules. Just to name a few: ddcutil, sparrow, mixxx, roomeqwizard, limesuite, uhd.
This would bloat nixos eval a lot, and in our current state each new nixos module increases the eval time of all nixos systems, no matter if they use the module or not.

> And wireshark basically does the same.

No, the wireshark module creates an suid wrapper.
But `adb` would be an example of a module that does exactly this.

But then also these udev rules are not really specific to rwedid. Maybe this specific udev rule should be included unconditionally on all nixos systems, so that users can easily get access to i2c devices by joining a group?

2023-07-15 18:26 UTC, emilylange commented
Whoops, sorry, my bad^^

2023-07-16 02:20 UTC, Janik-Haag commented
>But then also these udev rules are not really specific to rwedid. Maybe this specific udev rule should be included unconditionally on all nixos systems, so that users can easily get access to i2c devices by joining a group?

I would say I'm not experienced enough with i2c to judge that, I just copied the ddcutil i2c udev rules and they worked fine with the hardware. 

> Seems to be Linux-only software (as it requires a Linux kernel module).

Yeah you are right, the kernel module isn't really a problem but it uses linux only rust crates so..

I don't have really have hard feelings about the module, I can also just add a longDescription attribute that explains people they have to add the group and also install the package with `services.udev.packages =with pkgs; [ rwedid ];` that's what I usually tell other people when they have a package that needs some special settings set to work to make it a better user experience is better.

2023-08-20 20:15 UTC, Janik-Haag commented
what is keeping this from getting merged?

2023-08-21 17:25 UTC, emilylange approved these changes

2023-08-21 17:25 UTC, merged