pythonnet: 2.5.2 -> 3.0.1
NixOS/nixpkgs pull request #238601
Opened 2023-06-19 15:21 UTC by mdarocha

###### Description of changes

Updates that also fixes broken build. Also add `clr-loader` package since it's a new dependency.

Helps with https://github.com/NixOS/nixpkgs/issues/234775, since it switches building to .NET Core.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-19 20:08 UTC, mdarocha commented
@ofborg build python310Packages.pythonnet

2023-06-19 20:26 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2347

2023-06-19 21:19 UTC, SuperSandro2000 requested changes
otherwise patches might no longer apply

2023-06-19 21:19 UTC, SuperSandro2000 commented on pkgs/development/python-modules/clr-loader/default.nix
> +  prePatch = ''
```suggestion
  postPatch = ''
```

2023-06-19 21:19 UTC, SuperSandro2000 commented on pkgs/development/python-modules/pythonnet/default.nix
> +  prePatch = ''
```suggestion
  postPatch = ''
```

2023-06-21 12:23 UTC, SuperSandro2000 commented
@ofborg build python310Packages.clr-loader python310Packages.pythonnet

2023-06-21 12:40 UTC, merged