python3Packages.metawear: init at 1.0.8
NixOS/nixpkgs pull request #238630
Opened 2023-06-19 18:23 UTC by StepBroBD

###### Description of changes

python3Packages.metawear: init at 1.0.8

metawear
- https://pypi.org/project/metawear/
- https://github.com/mbientlab/metawear-sdk-python

dependency [warble](https://github.com/NixOS/nixpkgs/pull/238628)
- https://github.com/NixOS/nixpkgs/pull/238628

```shell
$ nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"
2 packages built:
python310Packages.metawear python311Packages.metawear
```

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-20 16:28 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2351

2023-06-21 17:15 UTC, SuperSandro2000 commented on pkgs/development/python-modules/metawear/default.nix
> +
```suggestion
```

2023-06-21 17:39 UTC, StepBroBD commented
> Why are they vendoring nlohman json?

Looks like it's a dependency for their sensor firmware

https://github.com/mbientlab/MetaWear-SDK-Cpp/blob/f67699e5c7eb64401a68157f553f9585e3857a6a/src/metawear/dfu/cpp/file_operations.cpp#L10

2023-07-01 19:02 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2383

2023-07-02 13:05 UTC, SuperSandro2000 commented
> Looks like it's a dependency for their sensor firmware

I was more asking in the direction if we can unvendor that and use ours?

2023-07-02 13:05 UTC, SuperSandro2000 requested changes

2023-07-02 13:05 UTC, SuperSandro2000 commented on pkgs/development/python-modules/metawear/default.nix
> +    gcc11
Can we avoid this if we use our nlohmann_json?

2023-07-07 17:30 UTC, StepBroBD commented
Thanks for the review!

> I was more asking in the direction if we can unvendor that and use ours?

Just changed it, gcc11 -> gcc, unvendored their version of nlohmann_json and using nixpkgs's nlohmann_json.

2023-07-07 17:45 UTC, StepBroBD commented
On x86_64-linux:
```shell
$ nix run nixpkgs#nixpkgs-review -- pr 238630
2 packages added:
python310Packages.metawear (init at 1.0.8) python311Packages.metawear (init at 1.0.8)
4 packages built:
python310Packages.metawear python310Packages.metawear.dist python311Packages.metawear python311Packages.metawear.dist
```

2023-07-07 20:33 UTC, SuperSandro2000 commented on pkgs/development/python-modules/metawear/default.nix
> +    gcc
gcc should be contained in the stdenv

2023-07-07 20:33 UTC, SuperSandro2000 commented on pkgs/development/python-modules/metawear/default.nix
> +    cat MetaWear-SDK-Cpp/src/metawear/dfu/cpp/file_operations.cpp
```suggestion
```

2023-07-07 20:33 UTC, SuperSandro2000 commented on pkgs/development/python-modules/metawear/default.nix
> +
```suggestion
    # remove vendored nlohmann_json
    rm MetaWear-SDK-Cpp/src/metawear/dfu/cpp/json.hpp
```

2023-07-07 20:33 UTC, SuperSandro2000 commented on pkgs/development/python-modules/metawear/default.nix
> +    platforms = [ "aarch64-linux" "x86_64-linux" ];
```suggestion
    platforms = stdenv.isLinux;
```

2023-07-07 21:14 UTC, StepBroBD commented
Fixed, on x86_64-linux:

```shell
$ nix run nixpkgs#nixpkgs-review -- pr 238630
2 packages added:
python310Packages.metawear (init at 1.0.8) python311Packages.metawear (init at 1.0.8)
4 packages built:
python310Packages.metawear python310Packages.metawear.dist python311Packages.metawear python311Packages.metawear.dist
```

2023-07-11 14:44 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2416

2023-07-11 21:38 UTC, SuperSandro2000 commented
@ofborg build python310Packages.metawear

2023-07-11 22:10 UTC, merged