ra-multiplex: init at 0.2.2
NixOS/nixpkgs pull request #239157
Opened 2023-06-22 09:48 UTC by NorfairKing

###### Description of changes

A packaging of https://github.com/pr2502/ra-multiplex

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-27 00:47 UTC, tomodachi94 approved these changes
Lgtm.

2023-06-27 04:18 UTC, oxalica requested changes

2023-06-27 04:18 UTC, oxalica commented on pkgs/development/tools/rust/ra-multiplex/default.nix
> +    sha256 = "sha256-Hf4Gj9eXEP4gXiqNV4Jq0oiGLX3DtDF9At1feEZ+bUE=";
No need to dup hash algorithm names.
```suggestion
    hash = "sha256-Hf4Gj9eXEP4gXiqNV4Jq0oiGLX3DtDF9At1feEZ+bUE=";
```

2023-06-27 04:18 UTC, oxalica commented on pkgs/development/tools/rust/ra-multiplex/default.nix
> +  # We make two extra scripts:
Where are these scripts from? They do not seem to be required, and are not mentioned upstream. If they are just to make *YOU* easier to use, they should go to your personal profile.

2023-06-27 04:18 UTC, oxalica commented on pkgs/top-level/all-packages.nix
> +  ra-multiplex = callPackage ../development/tools/rust/ra-multiplex/default.nix {};
Please sorted it alphabetically.

2023-06-27 04:18 UTC, oxalica commented on pkgs/development/tools/rust/ra-multiplex/default.nix
> +  cargoSha256 = "sha256-Z0ul50LeSb3qhdfuvRYvNAExtfH8y2+IkKLtqtlaL9E=";
```suggestion
  cargoHash = "sha256-Z0ul50LeSb3qhdfuvRYvNAExtfH8y2+IkKLtqtlaL9E=";
```

2023-06-29 18:57 UTC, oxalica approved these changes
> It's not clear in which range you want me to sort this. I put it next to rust-analyzer before, so now I put it above rustfmt.

I meant in the part where most of them are rust tools. I'd put it between `ravedude` and `rhack`. But the list is not strictly sorted in the first place, so it does not matter much.

Besides this, diff LGTM.

2023-07-12 18:32 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1020

2023-07-12 23:12 UTC, SuperSandro2000 reviewed
not sure if we should wrap rust-analyzer

2023-07-12 23:12 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  ra-multiplex = callPackage ../development/tools/rust/ra-multiplex/default.nix {};
```suggestion
  ra-multiplex = callPackage ../development/tools/rust/ra-multiplex {};
```

2023-07-12 23:12 UTC, SuperSandro2000 commented on pkgs/development/tools/rust/ra-multiplex/default.nix
> +  };
```suggestion
}:

rustPlatform.buildRustPackage {
  pname = "ra-multiplex";
  version = "0.2.2";

  src = fetchFromGitHub {
    owner = "pr2502";
    repo = "ra-multiplex";
    rev = "dcb5f83890cb91016b0a1590cc1b732606bb6ec1";
    hash = "sha256-Hf4Gj9eXEP4gXiqNV4Jq0oiGLX3DtDF9At1feEZ+bUE=";
  };

  cargoHash = "sha256-MeUtkPjOsL1kQ2W0Q1/OqhKDVXs4cECkATHISpyfp9U=";
```

2023-07-18 11:37 UTC, SuperSandro2000 commented
> > not sure if we should wrap rust-analyzer
> 
> I don't understand what you mean by this. Could you elaborate?

The tool requires rust-analyzer to be present in PATH https://github.com/pr2502/ra-multiplex#how-to-use

We can use wrapProgram to make sure that is always present in PATH and people don't need to configure that. see https://github.com/NixOS/nixpkgs/blob/684c17c429c42515bafb3ad775d2a710947f3d67/doc/languages-frameworks/ruby.section.md#packaging-executables-that-require-wrapping-packaging-executables-that-require-wrapping for an example

2023-07-18 11:56 UTC, SuperSandro2000 commented
> We can use wrapProgram to make sure that is always present in PATH and people don't need to configure that. see

I have ammended that

2023-07-18 22:24 UTC, merged