tmuxp: fix shell completion generation
NixOS/nixpkgs pull request #239493
Opened 2023-06-24 00:42 UTC by otavio

###### Description of changes

tmuxp 1.17+ uses shtab to generate the shell completion. This commit adapts the code to properly generate the shell completion module.

A side effect of use of shtab is that fish is not supported so it has been removed from postInstall.

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-24 01:07 UTC, AndersonTorres requested changes

2023-06-24 01:07 UTC, AndersonTorres commented on pkgs/tools/misc/tmuxp/default.nix
> +    pypkgs.shtab
I suggest to remove this pypkgs "macro"

2023-06-24 12:38 UTC, otavio commented on pkgs/tools/misc/tmuxp/default.nix
> +    pypkgs.shtab
Fixed.

2023-06-24 13:38 UTC, marsam approved these changes

2023-06-24 22:26 UTC, AndersonTorres commented
fix the conflicts

2023-06-25 12:10 UTC, AndersonTorres commented
Removing the approval label since the code became unmergeable afterwards.

2023-06-26 11:43 UTC, otavio commented
@AndersonTorres the PR is now rebased.

2023-06-26 13:36 UTC, merged