homebank: 5.5.6 -> 5.6.3
NixOS/nixpkgs pull request #239582
Opened 2023-06-24 12:51 UTC by frlan

###### Description of changes

Update 5.5.6 -> 5.6.3

This MR updates also the URL where to download the source package.  There were many versions in beetween, but the ChangeLog can be found at http://homebank.free.fr/ChangeLog 

This MR will also make #219722 obsolete. 

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- x ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-26 18:26 UTC, drupol requested changes

2023-06-29 07:55 UTC, frlan commented on pkgs/applications/office/homebank/default.nix
> -
Any link to docu how to generated it? Wasn't able to find it

2023-06-29 07:59 UTC, drupol commented on pkgs/applications/office/homebank/default.nix
> -
I'm just saying that removing a line here is not required and you should not do it.

2023-06-29 11:32 UTC, drupol commented
I'll set this PR in `draft` until things are solved.

2023-07-01 15:08 UTC, frlan commented
@drupol  Thanks for the input -- much appreciated!

I'm closing this one and will update with some for .5 minor release

2023-07-01 15:08 UTC, closed without merging

2023-07-01 16:03 UTC, drupol commented
Cool, ping me when it's done, I'll review it.