dotnet: misc fixes
NixOS/nixpkgs pull request #239622
Opened 2023-06-24 18:00 UTC by corngood

###### Description of changes

I'm still working on #239382, but I'm going to have to try a different approach to nuget sources, so I decided to pull out all the various fixes I've accumulated.

###### Things done

- allow `lockFile` to be specified in nuget-deps, so things like roslyn can customise it without breaking fetch-deps.
- add script to run all fetch-deps: `nix-shell maintainers/scripts/update-dotnet-lockfiles.nix` 
- fix crash in nix-prefetch-url via fetch-deps when TMPDIR was set to an empty string
- use a temporary file to atomically replace fetch-deps output
- disable fetch-deps on packages without lockfiles (e.g. tools)
- fix an error in nuget-to-nix when no packages are restored
- remove extended-deps from roslyn

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-24 18:01 UTC, corngood commented
This could have been a bunch of separate PRs.  Anyone have a preference on that?

2023-06-24 18:04 UTC, corngood commented
@mdarocha I see you added pkgs/development/compilers/roslyn/extended-deps.nix, but it appears to be unnecessary now.  Could it have something to do with which platform fetch-deps is run on?  Maybe I'll try to bisect it...

2023-06-24 18:11 UTC, corngood commented
Result of `nixpkgs-review pr 239622` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>42 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>BeatSaberModManager</li>
    <li>alttpr-opentracker</li>
    <li>audiobookshelf</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>git-credential-manager</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>kavita</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>nuget-to-nix</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>ps3-disc-dumper</li>
    <li>roslyn</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>space-station-14-launcher</li>
    <li>tone</li>
    <li>wasabibackend</li>
    <li>xivlauncher</li>
  </ul>
</details>

2023-06-24 18:30 UTC, mdarocha requested changes
LGTM, just have a couple small suggestions. I'm fine with this being one large PR, but you may consider splitting out the update script changes into a separate PR.

2023-06-24 18:48 UTC, corngood commented on pkgs/applications/version-management/git-credential-manager/update.sh
> +$(nix-build ../../../.. -A git-credential-manager.fetch-deps --no-out-link)
That's reasonable, but not really related to this change.  I'm just removing all the explicit deps.nix paths.

2023-06-24 18:56 UTC, corngood commented on pkgs/build-support/dotnet/build-dotnet-module/default.nix
> +        trap exitTrap EXIT
Oops.  That was a merge error and definitely shouldn't have been in that commit.

I'll take it out.  However, I do believe that `INT` and `TERM` are redundant in bash when you handle `EXIT`.

2023-06-24 19:55 UTC, corngood commented on maintainers/scripts/update-dotnet-lockfiles.nix
> +        % nix-shell maintainers/scripts/update-dotnet-lockfiles.nix
yeah, you currently need to allow some insecure/nonfree stuff in order to create all the lockfiles.

2023-06-24 19:56 UTC, corngood commented on pkgs/build-support/dotnet/build-dotnet-module/default.nix
> +          else builtins.trace "temp ${pname}" ''$(mktemp -t "${pname}-deps-XXXXXX.nix")'';
No, good catch.  I was trying to make sure none of the existing packages were hitting that path.  I'll take it out and read over everything again.

2023-06-24 20:06 UTC, corngood commented on maintainers/scripts/update-dotnet-lockfiles.nix
> +
any particular reason for this?  this script was inspired by update.nix, and it's not like that.

2023-06-24 20:16 UTC, raphaelr commented on maintainers/scripts/update-dotnet-lockfiles.nix
> +
`{}:` declares a function with zero arguments, there's no reason to do this until we need to add arguments.

2023-06-24 20:26 UTC, corngood commented on maintainers/scripts/update-dotnet-lockfiles.nix
> +
Comment added.  Let me know what you think.

2023-06-24 20:27 UTC, corngood commented on pkgs/build-support/dotnet/build-dotnet-module/default.nix
> +        lockFile = nugetDeps;
I did that change, but I went with `sourceFile` in mkNugetDeps, because `nugetDepsFile` seemed redundant there.

2023-06-24 20:29 UTC, corngood commented
Result of `nixpkgs-review pr 239622` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>42 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>BeatSaberModManager</li>
    <li>alttpr-opentracker</li>
    <li>audiobookshelf</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>git-credential-manager</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>kavita</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>nuget-to-nix</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>osu-lazer</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>ps3-disc-dumper</li>
    <li>roslyn</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>space-station-14-launcher</li>
    <li>tone</li>
    <li>wasabibackend</li>
    <li>xivlauncher</li>
  </ul>
</details>

2023-06-24 20:49 UTC, mdarocha approved these changes

2023-06-24 22:11 UTC, corngood commented
For reference, here's the total diffs if you run all the `fetch-deps` right now:

```diff
diff --git a/pkgs/development/tools/misc/netcoredbg/deps.nix b/pkgs/development/tools/misc/netcoredbg/deps.nix
index a073c98d5d4..8f0c3fbbeaa 100644
--- a/pkgs/development/tools/misc/netcoredbg/deps.nix
+++ b/pkgs/development/tools/misc/netcoredbg/deps.nix
@@ -8,19 +8,19 @@
   (fetchNuGet { pname = "Microsoft.CodeAnalysis.CSharp.Scripting"; version = "2.3.0"; sha256 = "121dhnfjd5jzm410dk79s8xk5jvd09xa0w5q3lbpqc7bs4wxmq4p"; })
   (fetchNuGet { pname = "Microsoft.CodeAnalysis.Scripting.Common"; version = "2.3.0"; sha256 = "11f11kvgrdgs86ykz4104jx1iw78v6af48hpdrhmr7y7h5334ziq"; })
   (fetchNuGet { pname = "Microsoft.CSharp"; version = "4.4.0"; sha256 = "1niyzqqfyhvh4zpxn8bcyyldynqlw0rfr1apwry4b3yrdnjh1hhh"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim"; version = "7.0.410101"; sha256 = "0az67ay2977gyksh039lamap2a7jcr4c8df4imqrdaqx1ksir993"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-arm"; version = "7.0.410101"; sha256 = "1x5iilp2436w2pjp9c29xwj6vlq4z43qhprz35yxvfzhg0vdsg0l"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-arm64"; version = "7.0.410101"; sha256 = "1zbrcr5iydbbyb48w2wksbckjgddd74z6xczcsb5b0gvyqra85sn"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-musl-arm"; version = "7.0.410101"; sha256 = "179xp33f6aaaf775m673ij1zzrkfk7a07jmm7hcna9nb4ils04yg"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-musl-arm64"; version = "7.0.410101"; sha256 = "0gjyw14ppwsy22c0f0ckxj6gan8gq8sk564bm762jgbvpj9w6br2"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-musl-x64"; version = "7.0.410101"; sha256 = "00yk3b7pygprgm53nlv9l6grrbykrv6dg27jmhw431dnv978wcqd"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-x64"; version = "7.0.410101"; sha256 = "1k3182xh0a6fc8j5vspi0qx75has4gwydcr2hrbrapc2x850xq0z"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.osx-arm64"; version = "7.0.410101"; sha256 = "06mqqj2bpvqqaxh0hfa580m6db213zy349k0x8ah34whzp3bgphk"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.osx-x64"; version = "7.0.410101"; sha256 = "0yxlb8k935i0yc3cxl996bnk86b4qghlqmmjrv4s8mc5qai351ws"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.win-arm"; version = "7.0.410101"; sha256 = "10ad931l9vrz3sc4xjyndak8p3wi5gl92r37yp7smjx8ik09azma"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.win-arm64"; version = "7.0.410101"; sha256 = "1xd85r13qbk6awbrnp2q4a5vvcpwl7rw62s404rxrl4ghy2a43xz"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.win-x64"; version = "7.0.410101"; sha256 = "1zlamjlv1s4d40sf08bbr6c7157lgchcla9x2g911ac0mnh8qqbf"; })
-  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.win-x86"; version = "7.0.410101"; sha256 = "0sk3akxgb1vw03fkj59m3n90j6v0a5g4px83h2llda8p5q729zbr"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim"; version = "7.0.430602"; sha256 = "01h2fs89341mfk4fan3zmd3s2nk64cj6fvdavsm63m2y9fzgpm6i"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-arm"; version = "7.0.430602"; sha256 = "1sjdh7lcw2vjbc1wwv4y5wmflq1bdijarh1l1df1li01p8l3711v"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-arm64"; version = "7.0.430602"; sha256 = "0nydf468p5n4yrf8k47kpw7wd08sxsxm6s5va7348fr0ni93m751"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-musl-arm"; version = "7.0.430602"; sha256 = "1a1q82bs3i4fks73vd3iajdznp2kypfsv0gqmkw3ab66n2k7prjc"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-musl-arm64"; version = "7.0.430602"; sha256 = "1hs0mzr8kfi8qnzkq2r7y6q125fsfrmj71xifhcp5rv77wsbrrjy"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-musl-x64"; version = "7.0.430602"; sha256 = "1mifdfjka1xjkk6bgdpp45na869dv024d67c1vmgbi1vv4an4a1w"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.linux-x64"; version = "7.0.430602"; sha256 = "16ww0q8d3vnv1kag27mk438qjxpj237jwbgm2lwxzwgdaamrydga"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.osx-arm64"; version = "7.0.430602"; sha256 = "1qgzzyjki2r261r2m8k8y8k384ivbgl4vb1w6v0f6jl296rdszp0"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.osx-x64"; version = "7.0.430602"; sha256 = "0nmjh43jzfkpggy2h76k0573hygnqdiafdagwp9ivg2991ffs3b1"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.win-arm"; version = "7.0.430602"; sha256 = "0x1yq65zjayvhvr9syvc51b5ghggayijfhd31ykqfbsk7abvs0pa"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.win-arm64"; version = "7.0.430602"; sha256 = "07ark78lgv1l72d2c5bm4ykmh7ga39218ibdrvsnizagmkpxmkf6"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.win-x64"; version = "7.0.430602"; sha256 = "1jcc48x4azw7qzpxr126cn7b2r93vv8313x8d5j06i278zx56bav"; })
+  (fetchNuGet { pname = "Microsoft.Diagnostics.DbgShim.win-x86"; version = "7.0.430602"; sha256 = "0hgba9r567i949lzr6q7lx8wj5lmnwqn4833c8pbqlyp0gr4sbn2"; })
   (fetchNuGet { pname = "Microsoft.NETCore.Platforms"; version = "1.1.0"; sha256 = "08vh1r12g6ykjygq5d3vq09zylgb84l63k49jc4v8faw9g93iqqm"; })
   (fetchNuGet { pname = "Microsoft.NETCore.Targets"; version = "1.1.0"; sha256 = "193xwf33fbm0ni3idxzbr5fdq3i2dlfgihsac9jj7whj0gd902nh"; })
   (fetchNuGet { pname = "NETStandard.Library"; version = "2.0.3"; sha256 = "1fn9fxppfcg4jgypp2pmrpr6awl3qz1xmnri0cygpkwvyx27df1y"; })
diff --git a/pkgs/games/BeatSaberModManager/deps.nix b/pkgs/games/BeatSaberModManager/deps.nix
index 64115dd683e..8364a1939af 100644
--- a/pkgs/games/BeatSaberModManager/deps.nix
+++ b/pkgs/games/BeatSaberModManager/deps.nix
@@ -2,22 +2,23 @@
 # Please dont edit it manually, your changes might get overwritten!
 
 { fetchNuGet }: [
-  (fetchNuGet { pname = "Avalonia"; version = "11.0.999-cibuild0030643-beta"; sha256 = "0bcc3h5hxy8mfkgxn07vnnq2rn8whn2gx3d67lmlpm01r16rndyc"; url = "https://pkgs.dev.azure.com/AvaloniaUI/aa84306f-2981-47b9-8206-edb3bed6250d/_packaging/5ebc1fbc-7d49-4641-8a57-d18c55ed6602/nuget/v3/flat2/avalonia/11.0.999-cibuild0030643-beta/avalonia.11.0.999-cibuild0030643-beta.nupkg"; })
+  (fetchNuGet { pname = "Avalonia"; version = "11.0.999-cibuild0036218-beta"; sha256 = "02nsmz69jc38rh73vb7gvagfxy1wipdmgc75ddgjag17xraip5r6"; url = "https://pkgs.dev.azure.com/AvaloniaUI/aa84306f-2981-47b9-8206-edb3bed6250d/_packaging/5ebc1fbc-7d49-4641-8a57-d18c55ed6602/nuget/v3/flat2/avalonia/11.0.999-cibuild0036218-beta/avalonia.11.0.999-cibuild0036218-beta.nupkg"; })
   (fetchNuGet { pname = "Avalonia.Angle.Windows.Natives"; version = "2.1.0.2023020321"; sha256 = "1az4s1g22ipak9a3xfh55z2h3rm6lpqh7svbpw6ag4ysrgsjjsjd"; })
-  (fetchNuGet { pname = "Avalonia.Controls.ColorPicker"; version = "11.0.999-cibuild0030643-beta"; sha256 = "06n0c8dyh1q4a97nm31vyr8b6jzcq8nvvligwzp4xaxdwhkphg2x"; url = "https://pkgs.dev.azure.com/AvaloniaUI/aa84306f-2981-47b9-8206-edb3bed6250d/_packaging/5ebc1fbc-7d49-4641-8a57-d18c55ed6602/nuget/v3/flat2/avalonia.controls.colorpicker/11.0.999-cibuild0030643-beta/avalonia.controls.colorpicker.11.0.999-cibuild0030643-beta.nupkg"; })
-  (fetchNuGet { pname = "Avalonia.Controls.DataGrid"; version = "11.0.999-cibuild0030643-beta"; sha256 = "1vfkbjy9fl24i6skn02wgr047579x4a1liiw79qwbkx7mgvw9pvn"; url = "https://pkgs.dev.azure.com/AvaloniaUI/aa84306f-2981-47b9-8206-edb3bed6250d/_packaging/5ebc1fbc-7d49-4641-8a57-d18c55ed6602/nuget/v3/flat2/avalonia.controls.datagrid/11.0.999-cibuild0030643-beta/avalonia.controls.datagrid.11.0.999-cibuild0030643-beta.nupkg"; })
-  (fetchNuGet { pname = "Avalonia.Desktop"; version = "11.0.999-cibuild0030643-beta"; sha256 = "0nh6hdw07hwq92n0m1sx7qxwp4ccqash5f8sivj3lflx786s9i5f"; url = "https://pkgs.dev.azure.com/AvaloniaUI/aa84306f-2981-47b9-8206-edb3bed6250d/_packaging/5ebc1fbc-7d49-4641-8a57-d18c55ed6602/nuget/v3/flat2/avalonia.desktop/11.0.999-cibuild0030643-beta/avalonia.desktop.11.0.999-cibuild0030643-beta.nupkg"; })
-  (fetchNuGet { pname = "Avalonia.Diagnostics"; version = "11.0.999-cibuild0030643-beta"; sha256 = " [...]

2023-06-24 22:18 UTC, corngood commented on maintainers/scripts/update-dotnet-lockfiles.nix
> +
Sorry, I misread your suggestion and thought you were asking for the whitespace to be removed.  Fixed.

2023-06-25 01:40 UTC, corngood commented
@mdarocha, 6c639e869c1fa420c707724eeba107a5017df0d2 is where roslyn started picking up the sdk dependency.  I guess that makes sense, so I'm comfortable with removing extended-deps now.

2023-06-25 20:59 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/999

2023-06-26 11:54 UTC, corngood commented on maintainers/scripts/update-dotnet-lockfiles.nix
> +        % nix-shell maintainers/scripts/update-dotnet-lockfiles.nix
@raphaelr I believe this is the only outstanding comment.  I've been setting `NIXPKGS_ALLOW_INSECURE=1` to deal with it.

2023-06-26 12:34 UTC, mdarocha approved these changes

2023-06-26 12:54 UTC, raphaelr approved these changes

2023-06-28 21:41 UTC, merged