citrix-receiver: New upstream release
NixOS/nixpkgs pull request #23975
Opened 2017-03-17 02:38 UTC by neilmayhew

###### Motivation for this change

This unfree package requires the user to download a tarball manually and insert it into the store with `nix-prefetch-url file:///...`. However, the release that the current version of the Nix pkg is built from is no longer easy to find on the download site. This change updates the derivation to use the current upstream release.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-03-17 16:50 UTC, ndowens requested changes
Change commit msg saying pkgname: OLDVERSION -> NEWVERSION

2017-03-17 16:51 UTC, ndowens commented
Also change title of PR to new commit msg

2017-03-18 00:33 UTC, obadz commented
Sadly I get an SSL error with the new version "A network error occured (SSL error 4)". No problem with 13.4…

2017-03-18 01:18 UTC, obadz commented
Looks like issue comes from upstream: http://discussions.citrix.com/topic/385459-ssl-error-with-135-works-with-134/

2017-03-24 23:25 UTC, veprbl commented
Well, there is no way to download 13.4.0 anymore. Is there?

2017-03-24 23:42 UTC, obadz commented
There is, see 17bfb6a08a0f77124bbe96e2908076c821bdeb46

2017-03-24 23:44 UTC, veprbl commented
@obadz Aha. Thank you!

2017-04-30 20:51 UTC, 7c6f434c commented
So, is 13.5.0 broken? Should this be merged or closed (waiting for 13.5.1 or 13.6.0)?

2017-07-26 17:46 UTC, jensbin commented
Citrix receiver 13.6.0 was released on 11th July and seems to be stable.
https://github.com/NixOS/nixpkgs/pull/27664

2017-07-31 12:16 UTC, 7c6f434c commented
If 13.4 is better than 13.6, and the same issue is in 13.5, should this be closed as well with «upstream issues» as a reason?

2017-08-05 16:35 UTC, obadz commented
Sure.

2017-08-05 16:35 UTC, closed without merging