evdi: unstable-20231013 -> 1.13.1
NixOS/nixpkgs pull request #239883
Opened 2023-06-26 07:47 UTC by jensbin

###### Description of changes

- Pull request to update evdi to 1.13.1
- Needed to use with Linux kernel >= 6.2

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-26 10:56 UTC, Janik-Haag reviewed
I'm not famirly with how to test this package, we will have to wait until @eyJhb does so.
Code  looks good to me.

2023-06-27 16:25 UTC, drupol requested changes
LGTM, just a minor change to apply.

Regarding for testing this package, I'll pass it to someone else as well.

2023-06-27 16:25 UTC, drupol commented on pkgs/os-specific/linux/evdi/default.nix
> +    sha256 = "sha256-Or4hhnFOtC8vmB4kFUHbFHn2wg/NsUMY3d2Tiea6YbY=";
```suggestion
    hash = "sha256-Or4hhnFOtC8vmB4kFUHbFHn2wg/NsUMY3d2Tiea6YbY=";
```

2023-06-27 17:45 UTC, jensbin commented
Verified with:
- HP G5 Universal Dock
- HP Thunderbolt Dock G4

2023-06-27 17:47 UTC, Janik-Haag commented
Can you provide instructions on how to verify that I have access to usb c/thunderbolt docs and a laptop that supports those, just don't know how to test this package?

2023-06-27 17:53 UTC, drupol commented
Shouldn't we be using version 1.14.0 ? https://github.com/DisplayLink/evdi/tags

2023-06-27 17:54 UTC, jensbin commented
Very high-level: Attaching to a displaylink docking station w/o `evdi` (this package) and `displaylink` (the other package) does not show any output. Because of missing proprietary displaylink software.

Instruction how to enable display on nixos are on that wiki: https://nixos.wiki/wiki/Displaylink

With these instructions the monitor signal is getting through the displaylink of the dock.

There are a couple of changes listed in evdi and displaylink changelog, the most obvious is that the version <1.13.1 does not compile with kernels >6.1

2023-06-27 17:55 UTC, jensbin commented
> Shouldn't we be using version 1.14.0 ? https://github.com/DisplayLink/evdi/tags

The current supported and bundled version by the needed displaylink daemon is 1.13.1.
1.14.0 might be supported by the next displaylink software.

2023-06-27 17:56 UTC, drupol commented
Ok, fair enough.

could you please fix the commit log message to match the PR title and I'll merge this.

2023-06-27 18:04 UTC, drupol approved these changes

2023-06-27 18:45 UTC, merged