haskellPackages: update stackage and hackage
NixOS/nixpkgs pull request #240387
Opened 2023-06-28 17:48 UTC by maralorn

### This Merge

This PR is the regular merge of the `haskell-updates` branch into `master`.

This branch is being continually built and tested by hydra at https://hydra.nixos.org/jobset/nixpkgs/haskell-updates. You may be able to find an up-to-date Hydra build report at [cdepillabout/nix-haskell-updates-status](https://github.com/cdepillabout/nix-haskell-updates-status).

We roughly aim to merge these `haskell-updates` PRs at least once every two weeks. See the @NixOS/haskell [team calendar](https://cloud.maralorn.de/apps/calendar/p/H6migHmKX7xHoTFa) for who is currently in charge of this branch.

### haskellPackages Workflow Summary

Our workflow is currently described in [`pkgs/development/haskell-modules/HACKING.md`](https://github.com/NixOS/nixpkgs/blob/haskell-updates/pkgs/development/haskell-modules/HACKING.md).

The short version is this:
* We regularly update the Stackage and Hackage pins on `haskell-updates` (normally at the beginning of a merge window).
* The community fixes builds of Haskell packages on that branch.
* We aim at at least one merge of `haskell-updates` into `master` every two weeks.
* We only do the merge if the [`mergeable`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/mergeable) job is succeeding on hydra.
* If a [`maintained`](https://hydra.nixos.org/job/nixpkgs/haskell-updates/maintained) package is still broken at the time of merge, we will only merge if the maintainer has been pinged 7 days in advance. (If you care about a Haskell package, become a maintainer!)

More information about Haskell packages in nixpkgs can be found [in the nixpkgs manual](https://nixos.org/manual/nixpkgs/unstable/#haskell).

---

This is the follow-up to #236431. Come to [#haskell:nixos.org](https://matrix.to/#/#haskell:nixos.org) if you have any questions.

2023-07-03 21:47 UTC, sternenseemann commented
* https://github.com/vmchale/jacinda/pull/2
* https://github.com/jgm/gitit/pull/688

2023-07-08 05:36 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/bump-haskellpackages-to-ghc-9-4-lts-21-in-nixpkgs/30146/1

2023-07-08 06:36 UTC, cdepillabout commented
### [haskell-updates build report from hydra](https://hydra.nixos.org/jobset/nixpkgs/haskell-updates)
*evaluation [1797386](https://hydra.nixos.org/eval/1797386) of nixpkgs commit [0dfb578](https://github.com/NixOS/nixpkgs/commits/0dfb5782e76c3a28a91f84c3342561aec23ec6c2) as of 2023-07-08 06:13 UTC*

:red_circle: **Branch not mergeable**
  * `mergeable` jobset failed.
  * `maintained` jobset failed.

#### Build summary

 | Platform | Failed :x: | DependencyFailed :heavy_exclamation_mark: | OutputLimitExceeded :warning: | TimedOut :hourglass::no_entry_sign: | HydraFailure :construction: | Success :heavy_check_mark: | 
 | --- | --- | --- | --- | --- | --- | --- | 
 | [aarch64-darwin :green_apple:](https://hydra.nixos.org/eval/1797386?filter=.aarch64-darwin) | 456 | 304 |  | 206 | 11 | 5607 | 
 | [aarch64-linux :iphone:](https://hydra.nixos.org/eval/1797386?filter=.aarch64-linux) | 448 | 333 | 20 | 1 |  | 5872 | 
 | [x86_64-darwin :apple:](https://hydra.nixos.org/eval/1797386?filter=.x86_64-darwin) | 473 | 304 |  | 32 |  | 5784 | 
 | [x86_64-linux :penguin:](https://hydra.nixos.org/eval/1797386?filter=.x86_64-linux) | 443 | 334 |  | 1 |  | 5915 | 
#### Maintained Linux packages with build failure
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226411162) [[:penguin::x:]](https://hydra.nixos.org/build/226182387) [arion](https://hydra.nixos.org/eval/1797386?filter=arion) @roberth
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226413188) [[:penguin::x:]](https://hydra.nixos.org/build/226168576) [haskellPackages.arion-compose](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.arion-compose) @roberth
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226420498) [[:penguin::x:]](https://hydra.nixos.org/build/226177872) [haskellPackages.binrep](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.binrep) @raehik
- [ ] [cabal-install](https://hydra.nixos.org/eval/1797386?filter=cabal-install) @sternenseemann
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226422651) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370112) [toplevel](https://hydra.nixos.org/eval/1797386?filter=cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226419215) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370066) [haskell.packages.ghc8107](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc8107.cabal-install)
  - [[:iphone::x:]](https://hydra.nixos.org/build/226415402) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370101) [haskell.packages.ghc884](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc884.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226411732) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370093) [haskell.packages.ghc902](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc902.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226416069) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370100) [haskell.packages.ghc924](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc924.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226413974) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370121) [haskell.packages.ghc925](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc925.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226417531) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370008) [haskell.packages.ghc926](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc926.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226418703) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370049) [haskell.packages.ghc927](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc927.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226414693) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226369993) [haskell.packages.ghc928](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc928.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226420969) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370076) [haskell.packages.ghc945](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc945.cabal-install)
  - [[:iphone::warning:]](https://hydra.nixos.org/build/226423514) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370070) [haskell.packages.ghc962](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc962.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226420571) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370090) [haskellPackages](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.cabal-install)
- [ ] [cachix](https://hydra.nixos.org/eval/1797386?filter=cachix) @domenkozar
  - [[:iphone::x:]](https://hydra.nixos.org/build/226410262) [[:penguin::x:]](https://hydra.nixos.org/build/226410030) [toplevel](https://hydra.nixos.org/eval/1797386?filter=cachix)
  - [[:iphone::x:]](https://hydra.nixos.org/build/226419398) [[:penguin::x:]](https://hydra.nixos.org/build/226410051) [haskellPackages](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.cachix)
- [ ] [dhall-lsp-server](https://hydra.nixos.org/eval/1797386?filter=dhall-lsp-server) @Gabriella439
  - [[:iphone::x:]](https://hydra.nixos.org/build/226423366) [[:penguin::x:]](https://hydra.nixos.org/build/226362771) [toplevel](https://hydra.nixos.org/eval/1797386?filter=dhall-lsp-server)
  - [[:iphone::x:]](https://hydra.nixos.org/build/226414759) [[:penguin::x:]](https://hydra.nixos.org/build/226362576) [haskellPackages](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.dhall-lsp-server)
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226419029) [[:penguin::x:]](https://hydra.nixos.org/build/226171622) [haskellPackages.espial](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.espial) @dalpd
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226412980) [[:penguin::x:]](https://hydra.nixos.org/build/226180699) [haskellPackages.hasura-ekg-core](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.hasura-ekg-core) @Lassulus
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226415714) [[:penguin::x:]](https://hydra.nixos.org/build/226173420) [haskellPackages.hevm](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.hevm) @arcz
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226416847) [[:penguin::x:]](https://hydra.nixos.org/build/226181161) [haskellPackages.irc-core](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.irc-core) @Kiwi
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226420016) [[:penguin::x:]](https://hydra.nixos.org/build/226169728) [haskellPackages.matrix-client](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.matrix-client) @maralorn
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226419677) [[:penguin::x:]](https://hydra.nixos.org/build/226179132) [haskellPackages.monad-bayes](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.monad-bayes) @turion
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226419733) [[:penguin::x:]](https://hydra.nixos.org/build/226174054) [haskellPackages.monad-schedule](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.monad-schedule) @turion
- [ ] [nvfetcher](https://hydra.nixos.org/eval/1797386?filter=nvfetcher) @berberman
  - [[:iphone::x:]](https://hydra.nixos.org/build/226919832) [[:penguin::x:]](https://hydra.nixos.org/build/226919872) [toplevel](https://hydra.nixos.org/eval/1797386?filter=nvfetcher)
  - [[:iphone::x:]](https://hydra.nixos.org/build/226919869) [[:penguin::x:]](https://hydra.nixos.org/build/226919834) [haskellPackages](https://hydra.nixos.org/eval/179 [...]

2023-07-08 06:36 UTC, cdepillabout commented
### [haskell-updates build report from hydra](https://hydra.nixos.org/jobset/nixpkgs/haskell-updates)
*evaluation [1797386](https://hydra.nixos.org/eval/1797386) of nixpkgs commit [0dfb578](https://github.com/NixOS/nixpkgs/commits/0dfb5782e76c3a28a91f84c3342561aec23ec6c2) as of 2023-07-08 06:13 UTC*

:red_circle: **Branch not mergeable**
  * `mergeable` jobset failed.
  * `maintained` jobset failed.

#### Build summary

 | Platform | Failed :x: | DependencyFailed :heavy_exclamation_mark: | OutputLimitExceeded :warning: | TimedOut :hourglass::no_entry_sign: | HydraFailure :construction: | Success :heavy_check_mark: | 
 | --- | --- | --- | --- | --- | --- | --- | 
 | [aarch64-darwin :green_apple:](https://hydra.nixos.org/eval/1797386?filter=.aarch64-darwin) | 456 | 304 |  | 206 | 11 | 5607 | 
 | [aarch64-linux :iphone:](https://hydra.nixos.org/eval/1797386?filter=.aarch64-linux) | 448 | 333 | 20 | 1 |  | 5872 | 
 | [x86_64-darwin :apple:](https://hydra.nixos.org/eval/1797386?filter=.x86_64-darwin) | 473 | 304 |  | 32 |  | 5784 | 
 | [x86_64-linux :penguin:](https://hydra.nixos.org/eval/1797386?filter=.x86_64-linux) | 443 | 334 |  | 1 |  | 5915 | 
#### Maintained Linux packages with build failure
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226411162) [[:penguin::x:]](https://hydra.nixos.org/build/226182387) [arion](https://hydra.nixos.org/eval/1797386?filter=arion) @roberth
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226413188) [[:penguin::x:]](https://hydra.nixos.org/build/226168576) [haskellPackages.arion-compose](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.arion-compose) @roberth
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226420498) [[:penguin::x:]](https://hydra.nixos.org/build/226177872) [haskellPackages.binrep](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.binrep) @raehik
- [ ] [cabal-install](https://hydra.nixos.org/eval/1797386?filter=cabal-install) @sternenseemann
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226422651) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370112) [toplevel](https://hydra.nixos.org/eval/1797386?filter=cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226419215) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370066) [haskell.packages.ghc8107](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc8107.cabal-install)
  - [[:iphone::x:]](https://hydra.nixos.org/build/226415402) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370101) [haskell.packages.ghc884](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc884.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226411732) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370093) [haskell.packages.ghc902](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc902.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226416069) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370100) [haskell.packages.ghc924](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc924.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226413974) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370121) [haskell.packages.ghc925](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc925.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226417531) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370008) [haskell.packages.ghc926](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc926.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226418703) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370049) [haskell.packages.ghc927](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc927.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226414693) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226369993) [haskell.packages.ghc928](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc928.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226420969) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370076) [haskell.packages.ghc945](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc945.cabal-install)
  - [[:iphone::warning:]](https://hydra.nixos.org/build/226423514) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370070) [haskell.packages.ghc962](https://hydra.nixos.org/eval/1797386?filter=haskell.packages.ghc962.cabal-install)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/226420571) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/226370090) [haskellPackages](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.cabal-install)
- [ ] [cachix](https://hydra.nixos.org/eval/1797386?filter=cachix) @domenkozar
  - [[:iphone::x:]](https://hydra.nixos.org/build/226410262) [[:penguin::x:]](https://hydra.nixos.org/build/226410030) [toplevel](https://hydra.nixos.org/eval/1797386?filter=cachix)
  - [[:iphone::x:]](https://hydra.nixos.org/build/226419398) [[:penguin::x:]](https://hydra.nixos.org/build/226410051) [haskellPackages](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.cachix)
- [ ] [dhall-lsp-server](https://hydra.nixos.org/eval/1797386?filter=dhall-lsp-server) @Gabriella439
  - [[:iphone::x:]](https://hydra.nixos.org/build/226423366) [[:penguin::x:]](https://hydra.nixos.org/build/226362771) [toplevel](https://hydra.nixos.org/eval/1797386?filter=dhall-lsp-server)
  - [[:iphone::x:]](https://hydra.nixos.org/build/226414759) [[:penguin::x:]](https://hydra.nixos.org/build/226362576) [haskellPackages](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.dhall-lsp-server)
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226419029) [[:penguin::x:]](https://hydra.nixos.org/build/226171622) [haskellPackages.espial](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.espial) @dalpd
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226412980) [[:penguin::x:]](https://hydra.nixos.org/build/226180699) [haskellPackages.hasura-ekg-core](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.hasura-ekg-core) @Lassulus
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226415714) [[:penguin::x:]](https://hydra.nixos.org/build/226173420) [haskellPackages.hevm](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.hevm) @arcz
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226416847) [[:penguin::x:]](https://hydra.nixos.org/build/226181161) [haskellPackages.irc-core](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.irc-core) @Kiwi
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226420016) [[:penguin::x:]](https://hydra.nixos.org/build/226169728) [haskellPackages.matrix-client](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.matrix-client) @maralorn
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226419677) [[:penguin::x:]](https://hydra.nixos.org/build/226179132) [haskellPackages.monad-bayes](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.monad-bayes) @turion
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/226419733) [[:penguin::x:]](https://hydra.nixos.org/build/226174054) [haskellPackages.monad-schedule](https://hydra.nixos.org/eval/1797386?filter=haskellPackages.monad-schedule) @turion
- [ ] [nvfetcher](https://hydra.nixos.org/eval/1797386?filter=nvfetcher) @berberman
  - [[:iphone::x:]](https://hydra.nixos.org/build/226919832) [[:penguin::x:]](https://hydra.nixos.org/build/226919872) [toplevel](https://hydra.nixos.org/eval/1797386?filter=nvfetcher)
  - [[:iphone::x:]](https://hydra.nixos.org/build/226919869) [[:penguin::x:]](https://hydra.nixos.org/build/226919834) [haskellPackages](https://hydra.nixos.org/eval/179 [...]

2023-07-13 15:25 UTC, ncfavier commented
lambdabot *should* be fixed by the next hackage update.

2023-07-14 14:09 UTC, ysangkok requested changes

2023-07-14 14:09 UTC, ysangkok commented on pkgs/development/haskell-modules/configuration-ghc-9.6.x.nix
> +  http-api-data = doDistribute self.http-api-data_0_6; # allows base >= 4.18
Misleading comment, [0.5.1](https://hackage.haskell.org/package/http-api-data-0.5.1) also allows base 4.18

2023-07-14 14:09 UTC, ysangkok commented on pkgs/development/haskell-modules/configuration-ghc-9.0.x.nix
>    singleton-bool = doJailbreak super.singleton-bool;
This shouldn't be needed since singleton-bool has supported GHC 9.0 since v0.1.5 from 2021.

2023-07-14 14:09 UTC, ysangkok commented on pkgs/development/haskell-modules/configuration-ghc-9.4.x.nix
>    singleton-bool = doJailbreak super.singleton-bool;
`stackage.yaml` has v0.1.6 which allows base-4.17 (GHC 9.4). So this shouldn't be needed.

2023-07-14 14:09 UTC, ysangkok commented on pkgs/development/haskell-modules/configuration-ghc-9.4.x.nix
>    splitmix = doJailbreak super.splitmix;
`stackage.yaml` has v0.1.0.4 which even allows GHC 9.6. So this shouldn't be needed for GHC 9.4.

2023-07-14 14:09 UTC, ysangkok commented on pkgs/development/haskell-modules/configuration-ghc-9.0.x.nix
>    lukko = doJailbreak super.lukko;
v0.1.1.3 from stackage.yaml even allows GHC 9.6 in [revision 4](https://hackage.haskell.org/package/lukko-0.1.1.3/revisions/). So this shouldn't be needed.

2023-07-14 14:17 UTC, ysangkok commented on pkgs/development/haskell-modules/configuration-ghc-9.4.x.nix
>    some = doJailbreak super.some;
Shouldn't be needed as stackage.yaml has v1.0.4.1 which allows base-4.17

2023-07-15 00:36 UTC, maralorn commented
@ysangkok Thank you for your review. For these kinds of sensible fixes PRs against the haskell-updates branch would be highly appreciated.

2023-07-26 12:53 UTC, roberth commented
I expect that the arion build will be fixed by a base bump that I've just released to hackage.

2023-08-08 22:57 UTC, maralorn commented
Last Call! We plan to merge this PR very soon. All packages which are broken at that point will be marked as broken. Please speak up if that is a problem for you!

This is the list of maintained broken packages from the last completed hydra evaluation (https://github.com/cdepillabout/nix-haskell-updates-status/tree/75d79e5a0fe2bd3a01595ba18cf8efede4549b89)

#### Maintained Linux packages with build failure
- [ ] [dhall-lsp-server](https://hydra.nixos.org/eval/1798340?filter=dhall-lsp-server) @Gabriella439
  - [[:iphone::x:]](https://hydra.nixos.org/build/229240685) [[:penguin::x:]](https://hydra.nixos.org/build/229237910) [toplevel](https://hydra.nixos.org/eval/1798340?filter=dhall-lsp-server)
  - [[:iphone::x:]](https://hydra.nixos.org/build/229218282) [[:penguin::x:]](https://hydra.nixos.org/build/229224969) [haskellPackages](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.dhall-lsp-server)
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/229240146) [[:penguin::x:]](https://hydra.nixos.org/build/229221131) [haskellPackages.hasura-ekg-core](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.hasura-ekg-core) @Lassulus
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/229238581) [[:penguin::x:]](https://hydra.nixos.org/build/229223966) [haskellPackages.irc-core](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.irc-core) @Kiwi
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/229237967) [[:penguin::x:]](https://hydra.nixos.org/build/229223681) [haskellPackages.monad-bayes](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.monad-bayes) @turion
- [ ] [nvfetcher](https://hydra.nixos.org/eval/1798340?filter=nvfetcher) @berberman
  - [[:iphone::x:]](https://hydra.nixos.org/build/230309088) [[:penguin::x:]](https://hydra.nixos.org/build/230309097) [toplevel](https://hydra.nixos.org/eval/1798340?filter=nvfetcher)
  - [[:iphone::x:]](https://hydra.nixos.org/build/230309080) [[:penguin::x:]](https://hydra.nixos.org/build/230309096) [haskellPackages](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.nvfetcher)
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/229314257) [[:penguin::x:]](https://hydra.nixos.org/build/229314247) [haskellPackages.patat](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.patat) @dalpd
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/229236438) [[:penguin::x:]](https://hydra.nixos.org/build/229222526) [haskellPackages.releaser](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.releaser) @maralorn
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/229222023) [[:penguin::x:]](https://hydra.nixos.org/build/229233592) [haskellPackages.shellify](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.shellify) @danielrolls
- [ ] [[:iphone::x:]](https://hydra.nixos.org/build/230565053) [[:penguin::x:]](https://hydra.nixos.org/build/230565702) [haskellPackages.typed-spreadsheet](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.typed-spreadsheet) @Gabriella439
- [ ] [weeder](https://hydra.nixos.org/eval/1798340?filter=weeder) @maralorn
  - [[:iphone::x:]](https://hydra.nixos.org/build/229227953) [[:penguin::x:]](https://hydra.nixos.org/build/229235370) [haskell.packages.ghc8107](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc8107.weeder)
  - [[:iphone::x:]](https://hydra.nixos.org/build/229222496) [[:penguin::x:]](https://hydra.nixos.org/build/229217622) [haskell.packages.ghc902](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc902.weeder)
  - [[:iphone::x:]](https://hydra.nixos.org/build/229240056) [[:penguin::x:]](https://hydra.nixos.org/build/229239391) [haskell.packages.ghc924](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc924.weeder)
  - [[:iphone::x:]](https://hydra.nixos.org/build/229243714) [[:penguin::x:]](https://hydra.nixos.org/build/229236342) [haskell.packages.ghc925](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc925.weeder)
  - [[:iphone::x:]](https://hydra.nixos.org/build/229233425) [[:penguin::x:]](https://hydra.nixos.org/build/229229401) [haskell.packages.ghc926](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc926.weeder)
  - [[:iphone::x:]](https://hydra.nixos.org/build/229224088) [[:penguin::x:]](https://hydra.nixos.org/build/229223205) [haskell.packages.ghc927](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc927.weeder)
  - [[:iphone::x:]](https://hydra.nixos.org/build/229219258) [[:penguin::x:]](https://hydra.nixos.org/build/229244526) [haskell.packages.ghc928](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc928.weeder)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/229241457) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/229222199) [haskell.packages.ghc945](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc945.weeder)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/229229468) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/229220983) [haskell.packages.ghc962](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc962.weeder)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/229228133) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/229233837) [haskellPackages](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.weeder)
#### Maintained Linux packages with failed dependency
- [ ] [[:iphone::heavy_exclamation_mark:]](https://hydra.nixos.org/build/230569175) [[:penguin::heavy_exclamation_mark:]](https://hydra.nixos.org/build/230565580) [haskellPackages.binrep](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.binrep) @raehik
- [ ] [[:iphone::heavy_exclamation_mark:]](https://hydra.nixos.org/build/229231259) [[:penguin::heavy_exclamation_mark:]](https://hydra.nixos.org/build/229226340) [haskellPackages.blockfrost-client](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.blockfrost-client) @sorki
- [ ] [[:penguin::heavy_exclamation_mark:]](https://hydra.nixos.org/build/230567709) [haskellPackages.bytepatch](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.bytepatch) @raehik
- [ ] [[:iphone::heavy_exclamation_mark:]](https://hydra.nixos.org/build/229224117) [[:penguin::heavy_exclamation_mark:]](https://hydra.nixos.org/build/229220214) [haskellPackages.cabal-flatpak](https://hydra.nixos.org/eval/1798340?filter=haskellPackages.cabal-flatpak) @thielema
- [ ] [cabal2nix](https://hydra.nixos.org/eval/1798340?filter=cabal2nix) @sternenseemann
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/230405440) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/230405453) [toplevel](https://hydra.nixos.org/eval/1798340?filter=cabal2nix)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/229233115) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/229233861) [haskell.packages.ghc8107](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc8107.cabal2nix)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/229235485) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/229232737) [haskell.packages.ghc884](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc884.cabal2nix)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/229235083) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/229226868) [haskell.packages.ghc902](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc902.cabal2nix)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/229217642) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/229227919) [haskell.packages.ghc924](https://hydra.nixos.org/eval/1798340?filter=haskell.packages.ghc924.cabal2nix)
  - [[:iphone::heavy_check_mark:]](https://hydra.nixos.org/build/229234672) [[:penguin::heavy_check_mark:]](https://hydra.nixos.org/build/229218291) [haskell.packages.ghc925](https://hydra.nixos.org/eval/1798340?filter= [...]

2023-08-10 07:05 UTC, sternenseemann commented
For inline-c-cpp (cachix, …) on darwin we should solve https://github.com/NixOS/nixpkgs/issues/248304, but downgrading to 0.5.0.0 can be a stop gap solution.

2023-08-15 10:24 UTC, raehik commented
`text-icu` and dependency errors on it should be fixed once cabal2nix uses https://github.com/NixOS/cabal2nix/commit/0365d9b77086d26ca5197fb48019cedbb0dce5d2 (unsure if it's connected to the Hackage release)

2023-08-17 08:25 UTC, merged

2023-08-21 15:20 UTC, SuperSandro2000 commented
Can someone please fix hadolint?

2023-08-21 16:00 UTC, sternenseemann commented
@SuperSandro2000 The test suite of spdx doesn't pass with base >= 4.17, it seems, so we'll have to ask that upstream for a fix.