python3Packages.pdfposter: fix build pin pypdf2
NixOS/nixpkgs pull request #240414
Opened 2023-06-28 21:08 UTC by kirillrdy

###### Description of changes

pdfposter is not compatible with pypdf3, but given its mainly used as application should be safe to overwrite pypdf

here is upstream MR to migrate to pypdf3
https://gitlab.com/pdftools/pdfposter/-/merge_requests/7

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-06-28 21:14 UTC, kirillrdy commented
Result of `nixpkgs-review pr 240414` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python310Packages.pdfposter</li>
    <li>python310Packages.pdfposter.dist</li>
  </ul>
</details>

2023-06-28 21:14 UTC, kirillrdy commented
cc @laikq @mweinelt

2023-06-28 21:38 UTC, mweinelt commented
We cannot use overrides within the python package set, as that causes conflicts when packages introduce different versions of the same package into the same python environment.

2023-06-28 21:55 UTC, kirillrdy commented
> We cannot use overrides within the python package set, as that causes conflicts when packages introduce different versions of the same package into the same python environment.
> 
> While that might seem unlikely, we don't make exceptions in such cases.

yes, I understand.
From first glance it looks like pdfposter is mean to be used as application,  in which case it probably shouldnt be in python-modules. if thats the case then overrides should be fine.

2023-06-28 21:57 UTC, mweinelt commented
Yep, looks like an application to me as well.

2023-06-29 11:21 UTC, FRidh approved these changes

2023-06-30 14:51 UTC, wamserma requested changes
only a small request, otherwise LGTM

2023-06-30 21:21 UTC, kirillrdy commented on pkgs/applications/misc/pdfposter/default.nix
> +      pypdf2 = super.pypdf2.overridePythonAttrs (oldAttrs: rec {
yep, makes sense, done

2023-06-30 21:58 UTC, merged