leptonica: from 1.83.0 -> to 1.83.1 - https://github.com/DanBloomberg/leptonica/compare/1.83.0...1.83.1
NixOS/nixpkgs pull request #240706
Opened 2023-06-30 10:52 UTC by JoeRu

###### Description of changes
There are some major errors in leptonica 1.83.0 which leaded to an non-function of all tesseract packages. Refactored url due to maintainer switch of release.
- see https://github.com/DanBloomberg/leptonica/compare/1.83.0...1.83.1
- 

###### Things done

- Built on platform(s)
  - [X ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [X ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-07-01 21:26 UTC, drupol requested changes

2023-07-01 21:26 UTC, drupol commented on pkgs/development/libraries/leptonica/default.nix
> +    sha256 = "sha256-jxhhXgdDr3339QmFxzDfzwyTVIBz0fVmIeQVaotU090=";
```suggestion
    hash = "sha256-jxhhXgdDr3339QmFxzDfzwyTVIBz0fVmIeQVaotU090=";
```

2023-07-01 21:28 UTC, drupol commented
Thanks for your contribution. I added a minor comment.

Could you please fix it and squash all your commits into one single commit ?

You commit log message needs to be: `leptonica: 1.83.0 -> 1.83.1`

2023-07-02 14:43 UTC, closed without merging

2023-07-02 16:14 UTC, drupol commented
@JoeRu is everything ok ?

2023-07-02 16:40 UTC, JoeRu commented
Just to dump to squash. 🙀

2023-07-02 16:43 UTC, JoeRu commented
Created a new pr. https://github.com/NixOS/nixpkgs/pull/241121

2023-07-02 16:50 UTC, drupol commented
Let me know if you need some assistance.