clilol: init at 1.0.4
NixOS/nixpkgs pull request #240994
Opened 2023-07-02 00:11 UTC by qbit

clilol is command line tool for interacting with omg.lol services.

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-03 14:41 UTC, FliegendeWurst requested changes
`clilol --version` outputs `clilol version dev`. I think this line needs to be patched: https://git.mcornick.dev/mcornick/clilol/src/branch/main/cmd/root.go#L69

2023-11-03 14:41 UTC, FliegendeWurst commented on pkgs/applications/networking/clilol/default.nix
> +    description = "a CLI for omg.lol";
```suggestion
    description = "CLI for omg.lol";
```

2023-11-03 18:05 UTC, qbit commented on pkgs/applications/networking/clilol/default.nix
> +    description = "a CLI for omg.lol";
fixed.

2023-11-03 18:05 UTC, qbit commented
> `clilol --version` outputs `clilol version dev`. I think this line needs to be patched: https://git.mcornick.dev/mcornick/clilol/src/branch/main/cmd/root.go#L69

We can set it with ldflags :D (it's set now)

2023-11-03 23:20 UTC, FliegendeWurst approved these changes

2023-11-03 23:20 UTC, FliegendeWurst commented on pkgs/applications/networking/clilol/default.nix
> +    maintainers = [ maintainers.qbit ];
```suggestion
    maintainers = [ maintainers.qbit ];
    mainProgram = "clilol";
```
I think this is the default (= pname), but surprisingly many packages set it explicitly.

2023-11-06 22:19 UTC, FliegendeWurst commented on pkgs/applications/networking/clilol/default.nix
> +    maintainers = [ maintainers.qbit ];
Actually, it appears that mainProgram is mandatory for new packages per https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#meta-attributes.

2024-11-07 16:35 UTC, FliegendeWurst requested changes

2024-11-07 16:35 UTC, FliegendeWurst commented on pkgs/applications/networking/clilol/default.nix
Should be in pkgs/by-name

2024-11-07 16:35 UTC, FliegendeWurst commented on pkgs/applications/networking/clilol/default.nix
> +  };
```suggestion
  src = fetchFromGitHub {
    owner = "mcornick";
    repo = "clilol";
    rev = "v${version}";
    hash = "";
  };
```

2026-03-26 16:53 UTC, closed without merging