gnuapl: 1.6 -> 1.7
NixOS/nixpkgs pull request #24114
Opened 2017-03-20 08:37 UTC by lsix

See http://lists.gnu.org/archive/html/info-gnu/2017-03/msg00007.html
for release announcement.

###### Motivation for this change

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-03-20 09:55 UTC, ndowens requested changes
Remove with stdenv.lib; from meta and move to top then you can then remove stdenv.libbfrom optionals and optionalString

2017-03-21 06:45 UTC, vbgl commented
@ndowens What is the rationale for such a refactoring? As it stands, this update looks good to me.

2017-03-21 09:47 UTC, ndowens commented
It is just cosmetic thing I like to do, mostly just to use stdenv.lib once vs several times

2017-03-21 09:49 UTC, lsix commented
I have no problem doing the refactoring. I’ll to that tonight.

2017-03-21 10:28 UTC, mdaiter commented
@lsix @ndowens should we leave refactoring to another PR?

2017-03-21 11:07 UTC, ndowens commented
I don't know why wait to do another PR just for cosmetic change?

Sent from my iphone

On Mar 21, 2017, 5:28 AM -0500, Matthew Daiter <notifications@github.com>, wrote:
>
> @lsix (https://github.com/lsix) @ndowens (https://github.com/ndowens) should we leave refactoring to another PR?
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://github.com/NixOS/nixpkgs/pull/24114#issuecomment-288036465), or mute the thread (https://github.com/notifications/unsubscribe-auth/AAHL753Qk6YyaxCIiq-ew498grq0KM--ks5rn6ZMgaJpZM4MiI2-).
>
>
>

2017-03-21 11:10 UTC, mdaiter commented
@ndowens it primarily makes bookkeeping easier.

2017-03-21 12:58 UTC, ndowens commented
Idk. If you change it and commit with msg cosmetic change or so that is bookkeeping IMO and can be split to fix something if it had to be

Sent from my iphone

On Mar 21, 2017, 6:10 AM -0500, Matthew Daiter <notifications@github.com>, wrote:
>
> @ndowens (https://github.com/ndowens) it primarily makes bookkeeping easier.
>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub (https://github.com/NixOS/nixpkgs/pull/24114#issuecomment-288046779), or mute the thread (https://github.com/notifications/unsubscribe-auth/AAHL78aOl_oVZ5YAIqU_m_4wkT4XSJodks5rn7AZgaJpZM4MiI2-).
>
>
>

2017-03-21 20:02 UTC, Mic92 commented on pkgs/development/interpreters/gnu-apl/default.nix
>    buildInputs = [ readline gettext ncurses ];
"--disable-dependency-tracking" is added by default to configure.

2017-03-22 13:58 UTC, lsix commented on pkgs/development/interpreters/gnu-apl/default.nix
>    buildInputs = [ readline gettext ncurses ];
I also do not see strong reason to keep the `"--disable-silent-rules"` (darwin only, but default behavior of automake). I’m going to drop it all together.

2017-03-22 14:27 UTC, fpletz approved these changes

2017-03-31 05:33 UTC, merged