lbrynet: init at 0.9.1
NixOS/nixpkgs pull request #24110
Opened 2017-03-20 07:24 UTC by benley

###### Motivation for this change
https://lbry.io/news/20000-illegal-college-lectures-rescued

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2017-03-21 19:59 UTC, Mic92 requested changes

2017-03-21 19:59 UTC, Mic92 commented on pkgs/top-level/python-packages.nix
> +  base58 = buildPythonPackage rec {
can you store new python packages in `./pkgs/development/python-modules` and only reference them here? This is the new policy as the file has grown too big.

2017-03-21 19:59 UTC, Mic92 commented on pkgs/top-level/python-packages.nix
> +    srcs = pkgs.fetchurl {
Does `fetchPypi` works here?

2017-03-21 19:59 UTC, Mic92 commented on pkgs/top-level/python-packages.nix
> +    src = pkgs.fetchurl {
Does `fetchPypi` works here?

2017-03-21 19:59 UTC, Mic92 commented on pkgs/top-level/python-packages.nix
> +    src = pkgs.fetchurl {
see above

2017-03-21 19:59 UTC, Mic92 commented on pkgs/top-level/python-packages.nix
> +    src = pkgs.fetchurl {
see above

2017-03-21 19:59 UTC, Mic92 commented on pkgs/top-level/python-packages.nix
> +    src = pkgs.fetchurl {
see above.

2017-03-21 19:59 UTC, Mic92 commented on pkgs/top-level/python-packages.nix
> +    src = pkgs.fetchurl {
see above

2017-03-21 20:00 UTC, benley commented on pkgs/top-level/python-packages.nix
> +  base58 = buildPythonPackage rec {
Oh yes definitely, I would prefer it that way.  I thought things were moving in the opposite direction!

2017-05-03 06:17 UTC, FRidh commented
This has been inactive for some time so I am closing this.

2017-05-03 06:17 UTC, closed without merging