grimblast: init at unstable-2023-06-17
NixOS/nixpkgs pull request #241197
Opened 2023-07-03 01:12 UTC by donovanglover

###### Description of changes

Adds https://github.com/hyprwm/contrib/tree/main/grimblast

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-02 20:11 UTC, jtbx approved these changes
LGTM

2023-09-23 02:20 UTC, donovanglover commented
@Misterio77 @fufexan Would love to get grimblast in nixpkgs and would appreciate a review. Let me know if I should add you as co-authors and/or maintainers as well.

2023-09-23 07:46 UTC, fufexan reviewed
Looks alright in the current state (my fault for keeping the upstream derivation in such a bad shape). I've updated the upstream derivation, and it should be better-suited for nixpkgs now.

Also, I'll let you be the maintainer here ;)

2023-09-24 15:02 UTC, fufexan approved these changes

2023-09-25 22:03 UTC, Misterio77 requested changes
Some feedback:
- Use sourceRoot instead of cd'ing during buildPhase
- Don't default hyprland to null (we do it on hypr-contrib to avoid having to consume the hyprland flake)
- Wrap with hyprpicker to allow for the `--freeze` functionality

2023-09-25 22:03 UTC, Misterio77 commented on pkgs/by-name/gr/grimblast/package.nix
> +stdenvNoCC.mkDerivation {
```suggestion
stdenvNoCC.mkDerivation (finalAttrs: {
```

So that we can use it on `sourceRoot`.

2023-09-25 22:03 UTC, Misterio77 commented on pkgs/by-name/gr/grimblast/package.nix
> +}
```suggestion
})
```

2023-09-25 22:03 UTC, Misterio77 commented on pkgs/by-name/gr/grimblast/package.nix
> +}:
```suggestion
, hyprpicker
}:
```

2023-09-26 03:11 UTC, donovanglover commented
Thanks, fixed all

2023-09-26 10:44 UTC, Misterio77 approved these changes
LGTM

2023-09-26 23:47 UTC, Artturin commented on pkgs/by-name/gr/grimblast/package.nix
> +    scdoc
scdoc is usually run during the build so nativeBuildInputs

2023-09-26 23:47 UTC, Artturin commented on pkgs/by-name/gr/grimblast/package.nix
> +
```suggestion

  strictDeps = true;
```

2023-09-26 23:58 UTC, donovanglover commented
Fixed thanks!

2023-09-27 17:21 UTC, merged