Add xontrib pkgs
NixOS/nixpkgs pull request #241386
Opened 2023-07-04 02:16 UTC by greg-hellings

###### Description of changes

Add xontrib packages that improve on basic functionality of the Xonsh shell. This is the list of xontribs maintained by the same people who produce Xonsh itself.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-07-04 13:33 UTC, mweinelt commented
> python310Modules.xontrib-jupyter: init at 0.3.0

should be python310Packages.

2023-07-04 13:34 UTC, SuperSandro2000 requested changes
All comments especially xontrib-whole-word-jumping apply to all packages.

2023-07-04 13:34 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xontrib-whole-word-jumping/remove-xonsh-dependency.patch
> ++dependencies = ["prompt_toolkit>=3.0.29"]
Please use substituteInPlace instead so we can avoid rebasing the patch

2023-07-04 13:34 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xontrib-whole-word-jumping/default.nix
> +    homepage = "https://github.com/xonsh/${name}";
```suggestion
    homepage = "https://github.com/xonsh/xontrib-whole-word-jumping";
```
please use clickable links

2023-07-04 13:34 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xontrib-whole-word-jumping/default.nix
> +    pytest
```suggestion
    pytestCheckHook
```

2023-07-04 13:34 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xontrib-whole-word-jumping/default.nix
> +    repo = name;
```suggestion
    repo = "xontrib-whole-word-jumping";
```

2023-07-04 13:34 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xontrib-whole-word-jumping/default.nix
> +  name = "xontrib-whole-word-jumping";
```suggestion
  pname = "xontrib-whole-word-jumping";
```

2023-07-04 13:34 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xontrib-jupyter/default.nix
> +
```suggestion
```

2023-07-04 13:34 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xontrib-jupyter/default.nix
> +  version = "0.3.0";
```suggestion
  version = "0.3.0";
  format = "pyproject";
```

2023-07-04 13:34 UTC, SuperSandro2000 commented on pkgs/development/python-modules/xontrib-fish-completer/default.nix
> +    pytest
```suggestion
    pytestCheckHook
```

2023-07-04 13:39 UTC, mweinelt requested changes
Reviewed one package as an example of the changes required for most packages.

But my primary concern is that these are not generic python libraries used outside of xonsh, so they should not live in `pkgs/development/python-modules` or `pkgs/top-level/python-packages.nix`.

They should likely land in an environment managed within `pkgs/shells/xonsh`.

2023-07-04 13:39 UTC, mweinelt commented on pkgs/development/python-modules/xontrib-abbrevs/default.nix
> +  ];
```suggestion
  nativeBuildInputs = [
    pytestCheckHook
    xonsh
  ];
```

Always rely on the hook, if possible. Applies to all packages.

2023-07-04 13:39 UTC, mweinelt commented on pkgs/development/python-modules/xontrib-abbrevs/default.nix
> +    homepage = "https://github.com/xonsh/${name}";
Developers tend to open this link from within their editor, so a substitution here is not a good idea.

2023-07-04 13:39 UTC, mweinelt commented on pkgs/development/python-modules/xontrib-abbrevs/default.nix
> +    description = "Command abbreviations. This expands input words as you type.";
```suggestion
  meta = with lib; {
    changelog = "...";
    description = "Command abbreviations. This expands input words as you type.";
```

Do these package have changelogs you could reference?

2023-07-04 13:39 UTC, mweinelt commented on pkgs/development/python-modules/xontrib-abbrevs/default.nix
> +  format = "pyproject";
`format` should appear directly after `version`.

2023-07-04 13:39 UTC, mweinelt commented on pkgs/development/python-modules/xontrib-abbrevs/default.nix
> +    sha256 = "sha256-DrZRIU5mzu8RUzm0jak/Eo12wbvWYusJpmqgIAVwe00=";
```suggestion
    hash = "sha256-DrZRIU5mzu8RUzm0jak/Eo12wbvWYusJpmqgIAVwe00=";
```

We use `hash`, as the SRI hash already encodes the hash type.

2023-07-04 13:39 UTC, mweinelt commented on pkgs/development/python-modules/xontrib-abbrevs/default.nix
> +  ];
Move patches directly below the `src` attribute.

2023-07-14 16:15 UTC, greg-hellings commented
OK, I think I have incorporated all of the feedback on the initial version of the PR.

All of the xontribs are moved to `pkgs.xonsh.xontribs.*`.
You can build a custom xonsh with a set of xontribs by using `pkgs.xonsh.withXontribs (x: [ x.xontrib-vox x.xontrib-bashisms])` and similar.
The unwrapped Xonsh package now lives in shells/xonsh/unwrapped.nix

Anyone using the plain `pkgs.xonsh` derivation should not be interrupted, and should still have the functionality of `vox` included. Prior to 0.14.0 vox was included in core Xonsh.

2023-07-23 22:38 UTC, SuperSandro2000 commented on pkgs/shells/xonsh/xontribs/xontrib-whole-word-jumping/default.nix
> +  preCheck = "export HOME=/tmp";
```suggestion
  preCheck = ''
    export HOME=$TMPDIR
  '';
```
or use mktemp -d

2023-07-23 22:39 UTC, SuperSandro2000 reviewed
please apply the other comment to all files

2023-07-23 22:39 UTC, SuperSandro2000 commented on pkgs/shells/xonsh/default.nix
>  }:
```suggestion
{ python3 }:
```

2024-01-21 04:43 UTC, greg-hellings commented
I've updated this with the feedback that had been given on formatting, variable usage, etc. I've also updated the version to 0.14.4 from 0.14.0.

2024-02-26 16:50 UTC, greg-hellings commented
Update to 0.15.0 now complete.

2024-03-07 15:25 UTC, greg-hellings commented
Now updated to 0.15.1.

I'd love to get some sort of solid up/down decision on this. Not having xontribs natively handled by the existing package since they were introduced in 0.14.0 is a significant nuisance as core functionality of the package was moved into the xontribs.

2024-03-09 18:54 UTC, AndersonTorres commented
Elocubrations:

I fell that this approach for creating a new "scope block" is becoming inconsistent.
Call me pedantic, but since, roughly speaking, xontribs are to xonsh what modules are for a kernel, I believe xontribs should be treated as standalone packages.

Further, that coordination between xonsh and xontribs should happen via NixOS or Home Manager module system.

2024-04-10 04:12 UTC, greg-hellings commented
@AndersonTorres I'm not sure it's appropriate to handle them as standalone packages. Because of the way Xonsh detects plugins, they cannot be complete Python packages (i.e. they are forbidden from creating the `__init__.py` file in the root of the xontrib directory because Xonsh creates that. Although they are distributed as Python packages, they are not able to be installed and used independently as a result.

I am happy to contribute a module if that would be a better place than the `withXontribs` model which I shamelessly pulled from Python. But I'm not sure that putting the Xontrib packages in their own space is appropriate, either, as they are completely useless in the absence of Xonsh. Installable, yes. But useful, no.

2024-04-11 17:11 UTC, AndersonTorres commented
Understood. In this sense it is reasonable to treat the xontribs as sub-packages under `passthru.xontribs`.

On the other hand, I think we should not "force" NixOS over the user. I approve the NixOS additions, however it does not look nice to remove the wrappers we were using before...

(or am I confusing something?)

2024-04-24 19:26 UTC, greg-hellings commented
Hmm, so this wasn't necessarily intentional but what happened is that this PR changes the unwrapped version to the default version and moves the functionality of adding `extraPackages` into the module. I will restore it to the former behavior.

2024-04-25 20:08 UTC, greg-hellings commented
Availability of the unwrapped version has been restored, and I have revved the base package to its latest release as of this week.

2024-07-03 10:28 UTC, drmikecrowe commented
Is there interest in gathering more xontrib's into this PR?  I have another 5-6 that can be added if that would be acceptable

2024-07-03 13:53 UTC, greg-hellings commented
> Is there interest in gathering more xontrib's into this PR? I have another 5-6 that can be added if that would be acceptable

I am rebasing this PR on top of the current 0.17.0 branch, testing it more extensively, and adding a few more xontribs that I also use (most frequently xonsh-direnv). I would welcome expanding it with any others that you might have as well.

2024-07-03 23:45 UTC, AndersonTorres requested changes

2024-07-03 23:45 UTC, AndersonTorres commented on pkgs/by-name/xo/xonsh/xontribs/xonsh-direnv/default.nix
> +  version = "1.7.0";
Instead of this bulk inclusion, why not including one by one?
This should not be so hard, and also will be helpful in future bisections.

2024-07-05 09:59 UTC, drmikecrowe commented
> > Is there interest in gathering more xontrib's into this PR? I have another 5-6 that can be added if that would be acceptable
> 
> I am rebasing this PR on top of the current 0.17.0 branch, testing it more extensively, and adding a few more xontribs that I also use (most frequently xonsh-direnv). I would welcome expanding it with any others that you might have as well.

I have a PR to your repo and the `add_xontrib_pkgs` branch for review.  LMK how else I can help

2025-02-13 20:18 UTC, closed without merging