cde: init at 0.1
NixOS/nixpkgs pull request #24225
Opened 2017-03-22 22:54 UTC by rlupton20

###### Motivation for this change
`CDE` was an attempt to capture a binary and all it's dependencies, to create a portable package - it works by monitoring system calls and grabbing any files that are mentioned. It's quite an old package and doesn't seem to have moved much recently, but it still works well.

It works particularly well with `nix`, because you can use it along with `nix-shell` to create standalone tarballs for software that isn't available on old systems (which is more or less how I can across this - just installing `nix` wasn't an option).

Allows a mini `nix` to be transported to other systems in a neat way.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-03-22 23:56 UTC, ndowens requested changes

2017-03-22 23:56 UTC, ndowens commented on pkgs/tools/package-management/cde/default.nix
> +    url = "https://github.com/pgbovine/CDE.git";
Use fetchFromGitHub

2017-03-23 23:04 UTC, ndowens approved these changes

2017-03-23 23:09 UTC, rlupton20 commented on pkgs/tools/package-management/cde/default.nix
> +    url = "https://github.com/pgbovine/CDE.git";
Thanks for fixing - was planning on doing it tomorrow evening but you beat me to it :smile:.

2017-03-23 23:09 UTC, ndowens commented
😀

2017-03-25 02:52 UTC, merged