pineflash: init at 0.5.1
NixOS/nixpkgs pull request #243312
Opened 2023-07-13 18:05 UTC by Janik-Haag

###### Description of changes
github.com/spagett1/pineFlash/

###### Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I have some problems with dfu-util when trying to flash a pinecil with pineflash it complaints about not finding dfu-util no matter iif I put it into buildInputs, nativeBuildInputs or propagatedBuildInputs what does work is spawning a nix-shell like that: `nix-shell -p dfu-util` and then opening pineflash from that nix-shell. I'm guessing this is caused by some wired behavior of $PATH but I don't know.

2023-07-14 06:09 UTC, Janik-Haag commented
#227474 has to get merged before this one since blisp is needed to flash the pincil v2

2023-11-05 14:44 UTC, Luflosi commented
blisp is now packaged. Does anything else need to be done before this PR is ready for merging?

2023-11-08 20:53 UTC, danjujan requested changes
My suggestions for the latest version.

2023-11-10 14:23 UTC, Janik-Haag commented
Thanks for the review and the ping, I'll try to work on it this weekend :D

2023-11-12 16:16 UTC, Janik-Haag commented
I applied your suggested patches and building works fine, but executing `./result/bin/pineflash` results in `A massive error occured, not sure whats goin on here.` and funnily enough exit code 0. Do you have a idea why that happens?

2023-11-12 20:37 UTC, Janik-Haag commented
Hmm I'm on Nixos unstable with sway

2023-12-09 20:00 UTC, danjujan approved these changes

2023-12-09 20:53 UTC, Luflosi requested changes
How about moving this from `pkgs/tools/misc/pineflash/default.nix` to `pkgs/by-name/pi/pineflash/package.nix`? Then you don't need to change `pkgs/top-level/all-packages.nix`.

2023-12-09 21:39 UTC, Janik-Haag commented
> Any news? Had the time to test pineflash in hyperland and sway. Works fine here.

I wonder whats different on your host. I tried bisecting egui earlier but to no avail all the hello_world examples even the one from the 0.21 release fail with:
```
Failed to initialize any backend! Wayland status: NoWaylandLib X11 status: LibraryOpenError(OpenError { kind: Library, detail: "opening library failed (libX11.so.6: cannot open shared object file: No such file or directory); opening library failed (libX11.so: cannot open shared object file: No such file or directory)" })
```

> How about moving this from pkgs/tools/misc/pineflash/default.nix to pkgs/by-name/pi/pineflash/package.nix? Then you don't need to change pkgs/top-level/all-packages.nix.

There will be a pr with automated tooling to do this. No need for extra manual labor

2023-12-14 12:55 UTC, mweinelt commented
```
❯ ./result/bin/pineflash
A massive error occured, not sure whats goin on here.
```

2024-02-26 06:35 UTC, NovaViper commented
I tried this on NixOS unstable running KDE Plasma 5.27.10; I also got the `A massive error occured, not sure whats goin on here.` error too

2024-02-26 21:46 UTC, Janik-Haag commented
updated, but still getting the same error on wayland :(

2024-02-27 05:51 UTC, NovaViper commented
I actually got a different error this time, same system. I also forgot to mention in my previous comment that my desktop is using X11 and not Wayland
```
A massive error occured, not sure whats goin on here:
 Found no glutin configs matching the template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: WINDOW, api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }. error: Error { raw_code: None, raw_os_message: None, kind: NotFound }
```

2024-02-27 09:20 UTC, Luflosi commented
I'm also getting
```
A massive error occured, not sure whats goin on here: 
 Found no glutin configs matching the template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: WINDOW, api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }. error: Error { raw_code: None, raw_os_message: None, kind: NotFound }
```
I'm running GNOME with Wayland.

2024-02-28 05:17 UTC, NovaViper commented
Hey I gave it a try once again after updating it and it's still erroring out on X11
```
A massive error occured, not sure whats goin on here:
 Found no glutin configs matching the template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: WINDOW, api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }. error: Error { raw_code: None, raw_os_message: None, kind: NotFound }
```

2024-02-28 21:40 UTC, Janik-Haag commented
I guess this is a upstream error and not one with our packaging but not sure.

2024-05-04 20:22 UTC, danjujan reviewed
Upstream reworked its wayland code.

2024-05-05 11:31 UTC, Luflosi commented
With the new version I'm still getting the error :(
```
A massive error occured, not sure whats goin on here: 
 Found no glutin configs matching the template: ConfigTemplate { color_buffer_type: Rgb { r_size: 8, g_size: 8, b_size: 8 }, alpha_size: 8, depth_size: 0, stencil_size: 0, num_samples: None, min_swap_interval: None, max_swap_interval: None, config_surface_types: ConfigSurfaceTypes(WINDOW), api: None, transparency: false, single_buffering: false, stereoscopy: None, float_pixels: false, max_pbuffer_width: None, hardware_accelerated: None, max_pbuffer_height: None, native_window: None }. Error: Error { raw_code: None, raw_os_message: None, kind: NotFound }
```
I get the same error when I rebase the PR on top of the version of Nixpkgs I'm currently running on my NixOS system (5c24cf2f0a12ad855f444c30b2421d044120c66f) I also tried rebasing on top of the latest master with the same result.

2024-12-30 19:32 UTC, acuteaangle commented
Whoops. I just found this PR.
I had opened gh-369458.

The 0 exit status with no stack trace was in part an [upstream bug](https://github.com/Spagett1/pineflash/issues/57#issuecomment-1686110530), which should be [fixed](https://github.com/Spagett1/pineflash/pull/83) in the next version.

`strace` revealed it to be crashing after searching for `libxkbcommon-x11.so` and `libGL.so`; adding those to buildInputs and rpath resolved that specific issue.

How should we go about merging these? My PR doesn’t have the desktop icons currently, and has not been tested on Darwin, but functions for me on `x86_64-linux`.

Note: The license is now out of date here, it was changed to [gpl2Only](https://github.com/Spagett1/pineflash/blob/master/LICENSE).

2025-01-22 22:02 UTC, closed without merging