gruvbox-gtk-theme rev bump
NixOS/nixpkgs pull request #244163
Opened 2023-07-18 13:49 UTC by cch000

###### Description of changes

Updated the rev to the latest one

###### Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-07-18 15:10 UTC, Gerg-L commented
Please squash and rename your commits and rename the PR

2023-07-18 15:12 UTC, Gerg-L commented
Something like `gruvbox-gtk-theme: 2022-12-09 -> 2023-5-26`

2023-07-18 17:35 UTC, cch000 commented
Done

2023-07-18 20:47 UTC, Gerg-L commented
Builds for me on `x86_64-linux`
LGTM

2023-07-18 20:48 UTC, Gerg-L approved these changes

2023-07-19 14:56 UTC, AndersonTorres requested changes

2023-07-19 14:56 UTC, AndersonTorres commented on pkgs/data/themes/gruvbox-gtk-theme/default.nix
> +  version = "unstable-2023-5-26";
```suggestion
  version = "unstable-2023-05-26";
```

2023-07-19 16:45 UTC, AndersonTorres requested changes

2023-07-19 16:45 UTC, AndersonTorres commented on pkgs/data/themes/gruvbox-gtk-theme/default.nix
> +    sha256 = "sha256-Y+6HuWaVkNqlYc+w5wLkS2LpKcDtpeOpdHnqBmShm5Q=";
```suggestion
    hash = "sha256-Y+6HuWaVkNqlYc+w5wLkS2LpKcDtpeOpdHnqBmShm5Q=";
```

2023-07-20 16:22 UTC, Gerg-L approved these changes

2023-07-20 16:24 UTC, Gerg-L commented
The only other thing I can see is that `rec` is dead code

2023-07-20 16:34 UTC, cch000 commented
> The only other thing I can see is that `rec` is dead code

removed it

2023-07-20 16:53 UTC, AndersonTorres approved these changes
LGTM, waiting ofborg to merge.

2023-07-20 18:51 UTC, Gerg-L approved these changes

2023-07-20 20:34 UTC, merged