apktool: 2.8.0 -> 2.8.1 and use free aapt
NixOS/nixpkgs pull request #245029
Opened 2023-07-23 12:51 UTC by linsui

###### Description of changes

The android sdk is licensed under an unfree license but the aapt from Google Maven is [licensed under Apache-2.0 only](https://maven.google.com/web/index.html#com.android.tools.build:aapt2:8.0.2-9289358). So I extract it there for a free aapt package. This also decrease the closure size of apktool from 2.2G to 599.5M.

Since apktool is free now, the unfree flag in diffoscope is not needed anymore.

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-07-25 10:05 UTC, AndersonTorres requested changes

2023-07-25 10:05 UTC, AndersonTorres commented on pkgs/development/tools/aapt/default.nix
> +        } else throw "Unsupport platform";
```suggestion
        } else throw "Unsupport platform: ${stdenv.system}";
```

2023-07-25 10:05 UTC, AndersonTorres commented on pkgs/development/tools/aapt/default.nix
> +  installPhase = ''
Don't forget `runHook`s

2023-07-25 10:05 UTC, AndersonTorres commented on pkgs/development/tools/aapt/default.nix
> +    sourceProvenance = with sourceTypes; [ binaryBytecode ];
```suggestion
```

2023-07-25 10:05 UTC, AndersonTorres commented on pkgs/development/tools/aapt/default.nix
> +  };
```suggestion
    sourceProvenance = with lib.sourceTypes; [ binaryBytecode ];
  };
```

2023-07-25 10:05 UTC, AndersonTorres commented on pkgs/development/tools/aapt/default.nix
> +    platforms = with platforms; unix;
```suggestion
    license = lib.licenses.asl20;
    maintainers = with lib.maintainers; [ linsui ];
    platforms = lib.platforms.unix;
```

2023-07-25 10:05 UTC, AndersonTorres commented on pkgs/development/tools/aapt/default.nix
> +  meta = with lib; {
```suggestion
  meta = {
```

2023-07-25 12:20 UTC, AndersonTorres approved these changes

2023-07-26 01:05 UTC, NickCao approved these changes
Nice work!

2023-07-26 01:05 UTC, merged