nuclear: 0.6.6 -> 0.6.27
NixOS/nixpkgs pull request #245680
Opened 2023-07-27 07:51 UTC by NotAShelf

###### Description of changes

- Bumped nuclear package version from 0.6.6 to 0.6.27
- Cleaned package structure
- Added NotAShelf to maintainers

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-01 20:24 UTC, eclairevoyant requested changes

2023-08-01 20:24 UTC, eclairevoyant commented on pkgs/applications/audio/nuclear/default.nix
> +  name = "nuclear";
```suggestion
  pname = "nuclear";
```

2023-08-01 20:24 UTC, eclairevoyant commented on pkgs/applications/audio/nuclear/default.nix
> +    url = "https://github.com/nukeop/nuclear/releases/download/v${version}/${name}-v${version}.AppImage";
```suggestion
    url = "https://github.com/nukeop/nuclear/releases/download/v${version}/${pname}-v${version}.AppImage";
```

2023-08-01 20:24 UTC, eclairevoyant commented on pkgs/applications/audio/nuclear/default.nix
>    appimageContents = appimageTools.extract { inherit name src; };
```suggestion
  appimageContents = appimageTools.extract { inherit pname src; };
```

2023-08-01 20:24 UTC, eclairevoyant commented on pkgs/applications/audio/nuclear/default.nix
> +      --replace 'Exec=AppRun' 'Exec=${name}'
use pname

2023-08-01 20:24 UTC, eclairevoyant commented on pkgs/applications/audio/nuclear/default.nix
>    inherit name src;
```suggestion
  inherit pname src;
```

2023-08-01 20:24 UTC, eclairevoyant commented on pkgs/applications/audio/nuclear/default.nix
> +    sha256 = "sha256-vCtGuId2yMVIQrMZcjN1i2buV4sah2qKupbr4LhqMbA=";
```suggestion
    hash = "sha256-vCtGuId2yMVIQrMZcjN1i2buV4sah2qKupbr4LhqMbA=";
```

2023-08-02 06:00 UTC, NotAShelf commented
Should be good now.

2023-08-02 06:27 UTC, eclairevoyant requested changes
couple other changes oops, with these it builds and runs properly

2023-08-02 06:27 UTC, eclairevoyant commented on pkgs/applications/audio/nuclear/default.nix
> +  appimageContents = appimageTools.extract { inherit pname src; };
```suggestion
  appimageContents = appimageTools.extract { inherit pname version src; };
```

2023-08-02 06:27 UTC, eclairevoyant commented on pkgs/applications/audio/nuclear/default.nix
> +  inherit pname src;
```suggestion
  inherit pname version src;
```

2023-08-02 07:07 UTC, NotAShelf commented
Alright, pushed the changes. Afraid I do not have the bandwidth to build the package right now, so it's worth nothing it's untested on my behalf.

2023-08-02 07:29 UTC, eclairevoyant approved these changes

2023-08-10 15:52 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/where-did-you-get-stuck-in-the-nix-ecosystem-tell-me-your-story/31415/18

2023-08-10 19:39 UTC, merged