djenrandom: init at 1.0
NixOS/nixpkgs pull request #245757
Opened 2023-07-27 15:34 UTC by ORichterSec

Add djenrandom as a package. djenrandom is a tool to generate random data.

###### Description of changes

###### Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-10 20:29 UTC, nikstur commented
Result of `nixpkgs-review pr 245757` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>djenrandom</li>
  </ul>
</details>

2023-08-10 20:31 UTC, nikstur requested changes
Looks pretty good. Only the `sha256` has to be changed to `hash` the rest of my comments are just nits. 

I can't cross compile the derivation to aarch64. Idk if that's important to you.

2023-08-10 20:31 UTC, nikstur commented on pkgs/tools/misc/djenrandom/default.nix
> +    license = with lib.licenses; [ gpl2Only ];
```suggestion
    license = lib.licenses.gpl2Only;
```

2023-08-10 20:31 UTC, nikstur commented on pkgs/tools/misc/djenrandom/default.nix
> +    sha256 = "sha256-r5UT8z8vvFZDffsl6CqBXuvBaZ/sl1WLxJi26CxkpAw=";
```suggestion
    hash = "sha256-r5UT8z8vvFZDffsl6CqBXuvBaZ/sl1WLxJi26CxkpAw=";
```

2023-08-10 20:31 UTC, nikstur commented on pkgs/tools/misc/djenrandom/default.nix
> +    cp djenrandom $out/bin
nit:
```suggestion
    install -D djent $out/bin/djent
```

2023-08-10 20:31 UTC, nikstur commented on pkgs/tools/misc/djenrandom/default.nix
> +    description = "A C program to generate random data using several random models, with parameterized non uniformities and flexible output formats";
nit: Use multiline strings '' '' and wrap the string at a sensible point

2023-08-11 14:10 UTC, ORichterSec commented on pkgs/tools/misc/djenrandom/default.nix
> +    cp djenrandom $out/bin
Also changed

2023-08-11 14:23 UTC, ORichterSec commented on pkgs/tools/misc/djenrandom/default.nix
> +    sha256 = "sha256-r5UT8z8vvFZDffsl6CqBXuvBaZ/sl1WLxJi26CxkpAw=";
This is also changed now

2023-08-11 14:36 UTC, ORichterSec commented
> Looks pretty good. Only the `sha256` has to be changed to `hash` the rest of my comments are just nits.
> 
> I can't cross compile the derivation to aarch64. Idk if that's important to you.
The source code is x86 specific. I have changed `meta.platforms` to reflect this. Thanks for the comment.

2023-08-24 14:47 UTC, RaitoBezarius commented on pkgs/tools/misc/djenrandom/default.nix
> +    #djenrandom uses x86 specific instructions, therefore we can only compile for the x86 architechture
```suggestion
    # djenrandom uses x86 specific instructions, therefore we can only compile for the x86 architechture
```

2023-08-25 09:32 UTC, ORichterSec commented on pkgs/tools/misc/djenrandom/default.nix
> +    #djenrandom uses x86 specific instructions, therefore we can only compile for the x86 architechture
It is now changed how you suggested.

2023-08-25 09:33 UTC, ORichterSec commented
Compilation on x86_64-darwin succeeds now too (see: https://github.com/NixOS/nixpkgs/pull/245757/checks?check_run_id=16208011189).

2023-09-13 09:45 UTC, nikstur approved these changes

2023-09-13 09:52 UTC, RaitoBezarius approved these changes

2023-09-13 09:53 UTC, merged