mitm6: init at 0.3.0
NixOS/nixpkgs pull request #246382
Opened 2023-07-31 16:37 UTC by Arcayr

## Description of changes

Adds a package for [mitm6](https://github.com/dirkjanm/mitm6), a DHCPv6 network spoofing application along the lines of [Responder](https://github.com/NixOS/nixpkgs/pull/241754).

Referenced in #81418.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-07-31 18:29 UTC, hax404 commented
That is right. Just add yourself in a second commit.

2023-08-04 19:22 UTC, AndersonTorres requested changes

2023-08-04 19:22 UTC, AndersonTorres commented on maintainers/maintainer-list.nix
> +  arcayr = {
Put this commit before all others, because this is a dependency of the other one.

2023-08-04 19:22 UTC, AndersonTorres commented on pkgs/tools/security/mitm6/default.nix
> +  meta = with lib; {
Do not use nested `lib`.

```suggestion
  meta = {
```

2023-08-04 19:22 UTC, AndersonTorres commented on pkgs/tools/security/mitm6/default.nix
> +    maintainers = with maintainers; [ arcayr ];
```suggestion
    maintainers = with lib.maintainers; [ arcayr ];
```

2023-08-04 19:22 UTC, AndersonTorres commented on pkgs/tools/security/mitm6/default.nix
> +    license = licenses.gpl2;
```suggestion
    license = lib.licenses.gpl2Plus;
```

2023-08-05 17:58 UTC, AndersonTorres requested changes

2023-08-05 17:58 UTC, AndersonTorres commented on pkgs/tools/security/mitm6/default.nix
> +python3.pkgs.buildPythonApplication rec {
```suggestion
}:

python3.pkgs.buildPythonApplication rec {
```

2023-08-05 17:58 UTC, AndersonTorres commented on pkgs/tools/security/mitm6/default.nix
> +  propagatedBuildInputs = with python3.pkgs; [
Here I will ask the Python gurus of Nixpkgs: it is OK to pick dependencies from python3.pkgs instead of declaring them?

2023-08-08 11:39 UTC, AndersonTorres approved these changes
Ping me 36 hours to merge.

2023-08-08 11:41 UTC, AndersonTorres commented
> AFAIK Nix is lazily computed, so this shouldn't be a performance impact. 

The m,any issues of `with` are well known. But using it in "one line expressions" is acceptable, while nesting `with`s is not.

2023-08-10 10:47 UTC, fabaff commented
Result of `nixpkgs-review pr 246382` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>mitm6</li>
    <li>mitm6.dist</li>
  </ul>
</details>

2023-08-10 10:57 UTC, fabaff approved these changes
- [x] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.maintainers` is set
- [x] package builds (see https://github.com/NixOS/nixpkgs/pull/246382#issuecomment-1672990654)
- [ ] all depending packages build
- [x] tested on x86_64

```bash
...ew/pr-246382-1]$ sudo ./results/mitm6/bin/mitm6 
Starting mitm6 using the following configuration:
Primary adapter: wlp3s0 [3d:11:71:21:70:f4]
IPv4 address: 192.168.111.115
[...]
```

Looks good to me.

2023-08-10 14:44 UTC, natsukium commented on pkgs/tools/security/mitm6/default.nix
> +    license = lib.licenses.gpl2Plus;
```suggestion
    license = lib.licenses.gpl2Only;
```
see https://github.com/dirkjanm/mitm6/blob/8e75884ab7c690d422b7da759c2f6d5426d8ef46/setup.py#L16

2023-08-10 14:44 UTC, natsukium commented on pkgs/tools/security/mitm6/default.nix
> +  doCheck = false;
While you are at it, would you please add a comment on the reason for `doCheck = false`?

2023-08-12 00:43 UTC, natsukium approved these changes

2023-08-12 00:43 UTC, merged