vrrtest: init at 2.1.0
NixOS/nixpkgs pull request #247396
Opened 2023-08-05 21:07 UTC by justinlime

## Description of changes

https://github.com/Nixola/VRRTest

init for VRRTest, a simplistic program designed to help you test the 
variable refresh rate functionality on your monitor.

## Things done

Tested on nixos as well as a fresh fedora virtual machine with nix installed under a single user.

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-05 21:57 UTC, jtbx approved these changes
LGTM :+1:

2023-08-06 02:36 UTC, jtbx commented
I don't know if this is necessary or not but I think you should put phase hooks in buildPhase.

2023-08-06 05:32 UTC, LudovicoPiero commented
Result of `nixpkgs-review pr 247396` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>vrrtest</li>
  </ul>
</details>

2023-08-06 11:43 UTC, justinlime commented
> I don't know if this is necessary or not but I think you should put phase hooks in buildPhase.

Couldnt hurt, done

2023-08-06 20:42 UTC, AndersonTorres requested changes

2023-08-06 22:15 UTC, justinlime commented on pkgs/tools/video/vrrtest/default.nix
> +    rev = "79bd724e24f551471a9f86513e3bd4f820ac1739";
Because version 2.1.0 was not published as a release as far as I could tell, even though the only the only update is copyright/readme update.

2023-08-06 22:16 UTC, justinlime commented on pkgs/tools/video/vrrtest/default.nix
> +    zip -9 -r vrrtest.love .
zips the repo as a .love file, which is executed by the love engine

2023-08-06 23:04 UTC, AndersonTorres commented on pkgs/tools/video/vrrtest/default.nix
> +    zip -9 -r vrrtest.love .
So I conclude love runs zip files. Fine, then.

2023-08-06 23:07 UTC, AndersonTorres requested changes

2023-08-06 23:07 UTC, AndersonTorres commented on pkgs/tools/video/vrrtest/default.nix
> +    rev = "79bd724e24f551471a9f86513e3bd4f820ac1739";
```suggestion
    rev = "v${finalAttrs.version}";
```

2023-08-06 23:07 UTC, AndersonTorres commented on pkgs/tools/video/vrrtest/default.nix
> +    mainProgram = "vrrtest";
Put this in alphabetical order.

2023-08-06 23:07 UTC, AndersonTorres commented on pkgs/tools/video/vrrtest/default.nix
> +    platforms = platforms.all;
```suggestion
    inherit (love.meta) platforms;
```

2023-08-07 10:42 UTC, justinlime commented on pkgs/tools/video/vrrtest/default.nix
> +    rev = "79bd724e24f551471a9f86513e3bd4f820ac1739";
Done

2023-08-07 10:43 UTC, justinlime commented on pkgs/tools/video/vrrtest/default.nix
> +    mainProgram = "vrrtest";
Done

2023-08-07 10:43 UTC, justinlime commented on pkgs/tools/video/vrrtest/default.nix
> +    platforms = platforms.all;
Done

2023-08-07 13:40 UTC, AndersonTorres approved these changes
Ping me 36 hours to merge.

2023-08-09 17:26 UTC, justinlime commented
> Ping me 36 hours to merge.

Ping

2023-08-10 00:42 UTC, merged