waypaper: init at 1.2
NixOS/nixpkgs pull request #248147
Opened 2023-08-09 14:06 UTC by TotalChaos05

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-09 16:17 UTC, OPNA2608 requested changes
Additionally, please switch to the `finalAttrs` pattern if `buildPythonApplication` supports it (not tested): https://nixos.org/manual/nixpkgs/unstable/#mkderivation-recursive-attributes

What it more or less boils down to:
```nix
python3.pkgs.buildPythonApplication rec {
  version = "1.2";

  src = fetchFromGitHub {
    rev = "refs/tags/${version}";
  };

  meta = with lib; {
    changelog = "https://github.com/anufrievroman/waypaper/releases/tag/${version}";
  };
}
```
becomes
```nix
python3.pkgs.buildPythonApplication (finalAttrs: {
  version = "1.2";

  src = fetchFromGitHub {
    rev = "refs/tags/${finalAttrs.version}";
  };

  meta = with lib; {
    changelog = "https://github.com/anufrievroman/waypaper/releases/tag/${finalAttrs.version}";
  };
})
```

2023-08-09 17:27 UTC, TotalChaos05 commented
should all be fixed now, thanks for the review !

2023-08-09 17:37 UTC, OPNA2608 requested changes
Oh also, please move the change to `maintainers/maintainer-list.nix` into a separate commit that preceeds the `waypaper: init` one. Check the history of that file for commit title examples.

2023-08-09 17:37 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +  # has no tests
Spacing.
```suggestion
  ];

  # has no tests
```

2023-08-09 17:37 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +  '';
Order (`longDescription` is usually kept right under `description`), indentation.

```suggestion
    description = "GUI wallpaper setter for Wayland-based window managers";
    longDescription = ''
      GUI wallpaper setter for Wayland-based window managers that works as a frontend for popular backends like swaybg and swww.

      If wallpaper does not change, make sure that swaybg or swww is installed.
    '';
    homepage = "https://github.com/anufrievroman/waypaper";
    license = licenses.gpl3Only;
    maintainers = with maintainers; [ totalchaos ];
```

2023-08-09 17:37 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +    rev = "refs/tags/${version}";
```suggestion
    rev = "refs/tags/${finalAttrs.version}";
```

2023-08-09 17:37 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +    changelog = "https://github.com/anufrievroman/waypaper/releases/tag/${version}";
```suggestion
    changelog = "https://github.com/anufrievroman/waypaper/releases/tag/${finalAttrs.version}";
```

2023-08-09 17:56 UTC, TotalChaos05 commented
it should be fixed now, do i need to rename the pr because i added me as a maintainer?

2023-08-09 18:05 UTC, OPNA2608 commented
No, current name is fine.

2023-08-09 18:07 UTC, OPNA2608 requested changes

2023-08-09 18:07 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +
```suggestion
```

2023-08-09 18:24 UTC, TotalChaos05 commented
also, editorconfig said i needed the newline at the end.

2023-08-09 18:33 UTC, OPNA2608 requested changes

2023-08-09 18:33 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +    rev = "refs/tags/${finalAttrs.version}";
```suggestion
    rev = "refs/tags/${version}";
```

2023-08-09 18:33 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +    changelog = "https://github.com/anufrievroman/waypaper/releases/tag/${finalAttrs.version}";
```suggestion
    changelog = "https://github.com/anufrievroman/waypaper/releases/tag/${version}";
```

2023-08-09 18:33 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +})
```suggestion
}
```

2023-08-09 19:22 UTC, OPNA2608 approved these changes
Result of `nixpkgs-review pr 248147` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>waypaper</li>
    <li>waypaper.dist</li>
  </ul>
</details>

---

Checked on aarch64-linux under Miriway WM, LGTM.

2023-08-09 19:27 UTC, OPNA2608 requested changes

2023-08-09 19:27 UTC, OPNA2608 commented on pkgs/applications/misc/waypaper/default.nix
> +  };
Actually looking at OfBorg attempting to build this on macOS, this should prolly be limited to Linux (even if it builds on Darwin, I don't think there's any use for it on there):
```suggestion
    platforms = platforms.linux;
  };
```

2023-08-09 21:18 UTC, OPNA2608 approved these changes
I *think* now we're good.

2023-08-11 10:15 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1057

2023-08-11 15:09 UTC, merged