ssh-tpm-agent: init at unstable-2023-08-12
NixOS/nixpkgs pull request #249404
Opened 2023-08-15 21:42 UTC by stigtsp

## Description of changes

Adds the new experimental `ssh-tpm-agent` package, allowing ssh users to easily authenticate with keys sealed by their TPM2 chip.

Todo:
- [ ] Fix failing tests
- [ ] Maybe wait for newer release

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-15 21:42 UTC, stigtsp commented
@Foxboron ^^

2023-08-21 07:38 UTC, Foxboron commented
After discussing it with @stigtsp the idea is to wait for a `1.0.0` release and keep the PR available for people that want to test `ssh-tpm-agent`.

2024-03-04 18:20 UTC, stigtsp commented
@RaitoBezarius Hi! A certain fox noticed that you had some options for ssh-tpm-agent in your config. I'm thinking to set up NixOS options for this as well - likely in a later PR. Would you be interested in reviewing?

https://github.com/RaitoBezarius/nixos-home/blob/master/ssh/tpm-agent.nix

2024-03-04 18:42 UTC, RaitoBezarius commented
> @RaitoBezarius Hi! A certain fox noticed that you had some options for ssh-tpm-agent in your config. I'm thinking to set up NixOS options for this as well - likely in a later PR. Would you be interested in reviewing?
> 
> https://github.com/RaitoBezarius/nixos-home/blob/master/ssh/tpm-agent.nix 

Of course! I didn't know this certain fox was okay with 0.3.0 :>

2024-03-05 11:18 UTC, Foxboron commented
> Of course! I didn't know this certain fox was okay with 0.3.0 :>

After implementing the ASN.1 TPM keys I don't really need to lock down the key format anymore. So it should be fine as the key would probably not need to be upgraded in the future.

2024-03-07 11:15 UTC, Foxboron commented
@stigtsp You want to pull this patch fwiw, https://github.com/Foxboron/ssh-tpm-agent/commit/65d5a501bf1ce7f358006ad48af0c2c85f459d1c

2024-03-07 11:21 UTC, stigtsp commented
> @stigtsp You want to pull this patch fwiw, [Foxboron/ssh-tpm-agent@65d5a50](https://github.com/Foxboron/ssh-tpm-agent/commit/65d5a501bf1ce7f358006ad48af0c2c85f459d1c)

Should we bump it to the next releaee

> @stigtsp You want to pull this patch fwiw, [Foxboron/ssh-tpm-agent@65d5a50](https://github.com/Foxboron/ssh-tpm-agent/commit/65d5a501bf1ce7f358006ad48af0c2c85f459d1c)

Are you planning a new release soon? Would prefer to update this PR to that if it's not far off.

2024-03-07 11:28 UTC, Foxboron commented
@stigtsp I can do a bugfix release this weekend probably.

2024-03-11 09:07 UTC, Foxboron commented
https://github.com/Foxboron/ssh-tpm-agent/releases/tag/v0.3.1

should be fine.

2024-03-25 16:03 UTC, stigtsp commented
Tested this a bit more, and it works for me. 

@RaitoBezarius Any showstoppers to merging this you think?

2024-03-27 02:18 UTC, adamcstephens requested changes
This looks good to me except it’s missing `meta.mainProgram`

2024-03-27 02:28 UTC, stigtsp commented
> This looks good to me except it’s missing `meta.mainProgram`

Thanks, added.

2024-03-27 02:41 UTC, adamcstephens approved these changes

2024-03-27 03:21 UTC, merged

2024-03-27 16:35 UTC, adamcstephens commented
Here's a simple HM config (easily translated to nixos). I'm actually not going to use this for now because I need to load other keys into the agent and this agent, like yubikey-agent, doesn't support that.

```
home.packages = [ pkgs.ssh-tpm-agent ];
systemd.user.services.ssh-tpm-agent = {
  Unit.PartOf = [ "default.target" ];

  Service = {
    Type = "simple";
    ExecStart = "${lib.getExe pkgs.ssh-tpm-agent} -l %t/ssh-agent";
    RestartSec = 3;
    Restart = "on-abort";
  };

  Install.WantedBy = [ "default.target" ];
};
```

2024-03-27 16:41 UTC, Foxboron commented
@adamcstephens 

Look at the proxy support.

https://github.com/Foxboron/ssh-tpm-agent?tab=readme-ov-file#proxy-support

2024-03-27 18:27 UTC, adamcstephens commented
@Foxboron thanks! i missed that in the readme.