etlegacy: fix and refactor
NixOS/nixpkgs pull request #250249
Opened 2023-08-19 20:36 UTC by drupol

Hello,

I'm unable to run `etlegacy` on my machine, I get the following error log:

```
❯ etl.x86_64
tty]*** buffer overflow detected ***: terminated
*** buffer overflow detected ***: terminated
DOUBLE SIGNAL FAULT: Received signal 6, exiting...
*** buffer overflow detected ***: terminated
DOUBLE SIGNAL FAULT: Received signal 6, exiting...
*** buffer overflow detected ***: terminated
DOUBLE SIGNAL FAULT: Received signal 6, exiting...
*** buffer overflow detected ***: terminated
DOUBLE SIGNAL FAULT: Received signal 6, exiting...
...
DOUBLE SIGNAL FAULT: Received signal 6, exiting...
*** buffer overflow detected ***: terminated
DOUBLE SIGNAL FAULT: Received signal 6, exiting...
*** buffer overflow detected ***: terminated
fish: Job 1, 'etl.x86_64' terminated by signal SIGSEGV (Address boundary error)
~ ✘
```

This PR:

- [x] Fix the aforementioned issue
- [x] Remove unused `runCommand` argument
- [x] Add myself as maintainer
- [x] Reduce amount of local vars
- [x] Refactor `fetchAsset` function
- [x] Remove `fakeGit`
- [x] Build server and client
- [x] Update `cmakeFlags` and change default install directories
- [x] Disable `fortify` to have fully working binaries

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-19 20:44 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/1016/69

2023-08-20 09:14 UTC, bjornfor commented
> etlegacy: remove mainProgram attribute 

It's not removing it though, just refactoring.

2023-08-20 09:16 UTC, ashleyghooper requested changes
Hi @drupol 
thanks for your suggested changes. Many of them look okay, and adding the dedicated server is a good move, but I'd like to discuss a few of them. See comments in the review.

Also, I'm keen to hear your thoughts on how we support for other platforms than Linux `x86_64`. Especially Linux `i686` and Darwin.

2023-08-20 16:00 UTC, drupol commented on pkgs/games/etlegacy/default.nix
> -    '';
Fair enough, going to revert my change.

2023-08-20 16:01 UTC, drupol commented on pkgs/games/etlegacy/default.nix
> +    rm -rf $out/share/applications/com.etlegacy.ETLegacy.x86_64.desktop
You're right, I've skipped the `x86_64` in the filename, going to make an adjustment.

2023-08-20 16:02 UTC, drupol commented on pkgs/games/etlegacy/default.nix
> -    else "etl.x86_64";
Fair enough, going to leave the `.<arch>` in the next iteration and use their desktop file.

2023-08-20 16:02 UTC, drupol commented on pkgs/games/etlegacy/default.nix
> -  '';
Going to restore this as well.

2023-08-20 16:03 UTC, drupol commented
Thanks for the detailed review, I'm going to start working on them in one hour.

2023-08-20 17:18 UTC, drupol commented
I think I've addressed everything, could you please check again?

2023-08-20 20:08 UTC, ashleyghooper commented on pkgs/games/etlegacy/default.nix
> -    '';
Thanks for that. Previously I think there was a suggestion we could talk to upstream about getting an upstream change to make this unnecessary. I guess it's there to make it clear to people who compile themselves and might have modified things that they're running a version that could potentially be unstable when playing online.

2023-08-21 10:22 UTC, ashleyghooper approved these changes

2023-08-21 10:42 UTC, merged

2023-08-21 10:42 UTC, drupol commented
Youhou ! thanks !