git: 2.41.0 -> 2.42.0
NixOS/nixpkgs pull request #250675
Opened 2023-08-22 05:47 UTC by kashw2

## Description of changes

change log: https://github.com/git/git/blob/v2.42.0/Documentation/RelNotes/2.42.0.txt

added myself as a maintainer as I'd love to help in the process of keeping this package functioning and up to date.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-22 10:18 UTC, yayayayaka requested changes
Thanks for your contribution! :heart: 

This PR has to target the `staging` branch as it would cause a mass rebuild. A deeper explanation about the staging workflow can be found in the [Staging section](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#staging) of the [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

To change the target branch to `staging`, follow the steps outlined in the [Rebasing between branches](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging) section.

2023-08-22 10:28 UTC, kashw2 commented on pkgs/applications/version-management/git/default.nix
> +    maintainers = with lib.maintainers; [ primeos wmertens globin kashw2 ];
split into separate commit (https://github.com/NixOS/nixpkgs/pull/250675/commits/9124084e5ac5a31968e4b6f63e322d6bf2530866)

2023-08-22 10:31 UTC, kashw2 commented
Hi @yayayayaka, I've changed the targeted branch for this PR to `staging` and have rebased upon `upstream/staging`, then pushing the head to the my branch.

2023-08-28 07:16 UTC, yayayayaka approved these changes

2023-09-02 00:47 UTC, merged