blackshades: 2.4.9 -> 2.5.1
NixOS/nixpkgs pull request #251027
Opened 2023-08-23 19:47 UTC by McSinyx

## Description of changes

[Compatibility update for the latest Zig compiler with a few bug fixes](https://git.sr.ht/~cnx/blackshades/refs/2.5.1)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-23 23:49 UTC, antonmosich reviewed
Result of `nixpkgs-review pr 251027` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>blackshades</li>
  </ul>
</details>

Please consider also adding the `meta.mainProgram` attribute while at it.
I was not able to get it running on my machine, but that might be due to my nearly broken graphical setup at the moment.

2023-08-26 12:50 UTC, AndersonTorres requested changes

2023-08-26 12:50 UTC, AndersonTorres commented on pkgs/games/blackshades/default.nix
> +    mainProgram = finalAttrs.pname;
```suggestion
    mainProgram = "blackshades";
```

2023-08-28 14:45 UTC, AndersonTorres approved these changes

2023-08-31 16:59 UTC, merged

2023-09-01 00:08 UTC, McSinyx commented
Thanks!