lsd: 0.23.1 -> 1.0.0, modernise packages, thin out maintainers
NixOS/nixpkgs pull request #251831
Opened 2023-08-27 18:57 UTC by SuperSandro2000

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-08-27 22:26 UTC, marsam requested changes

2023-08-27 22:26 UTC, marsam commented on pkgs/tools/misc/lsd/default.nix
>      owner = "Peltoche";
```suggestion
    owner = "lsd-rs";
```

2023-08-27 22:26 UTC, marsam commented on pkgs/tools/misc/lsd/default.nix
> +    hash = "sha256-FY1odcKBl7zJ+MxfohkmC1e45fPQK3MKB3orQdCRpA4=";
The hash needs to be updated

2023-08-27 22:26 UTC, marsam commented on pkgs/tools/misc/lsd/default.nix
>      homepage = "https://github.com/Peltoche/lsd";
```suggestion
    homepage = "https://github.com/lsd-rs/lsd";
```

2023-08-28 11:51 UTC, SuperSandro2000 commented on pkgs/tools/misc/lsd/default.nix
> +    hash = "sha256-FY1odcKBl7zJ+MxfohkmC1e45fPQK3MKB3orQdCRpA4=";
whopsie 😓

2023-08-28 12:52 UTC, marsam commented on pkgs/tools/misc/lsd/default.nix
Would you mind adding the following?
```nix
buildInputs = lib.optionals stdenv.isDarwin [ darwin.apple_sdk.frameworks.Security ];
```
Besides that, LGTM

2023-08-29 01:11 UTC, marsam approved these changes

2023-08-29 01:12 UTC, merged