[staging] coreutils: 9.3 -> 9.4
NixOS/nixpkgs pull request #252165
Opened 2023-08-29 16:14 UTC by dasJ

Changelog: https://savannah.gnu.org/news/?id=10505

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-07 11:58 UTC, vcunat requested changes
Fails to build on aarch64-linux
```
patching sources
sed: can't read ./tests/tail-2/assert.sh: No such file or directory
/nix/store/wwlxdnf6xpfg5hlrjykry6w7p8pihv7j-bootstrap-stage4-stdenv-linux/setup: line 148: pop_var_context: head of shell_variables not a function context
```

2023-09-10 06:21 UTC, vcunat requested changes

2023-09-10 06:21 UTC, vcunat commented on pkgs/tools/misc/coreutils/default.nix
> +    sha256 = "sha256:08q4b0w7mwfxbqjs712l6wrwl2ijs7k50kssgbryg9wbsw8g98b1";
This branch has gotten all weird.  9.0 -> 9.1 instead of 9.3 -> 9.4 &ndash; and the hash format.

2023-11-19 21:15 UTC, closed without merging

2023-11-19 21:15 UTC, Artturin commented
Closing in favour of https://github.com/NixOS/nixpkgs/pull/264215 as this branch seems messed up