wonderdraft: init at 1.1.7.3
NixOS/nixpkgs pull request #253035
Opened 2023-09-03 03:03 UTC by IGJoshua

## Description of changes
This PR adds a package for the dungeon mapping tool Wonderdraft by Megasploot.

I'm adding myself as a maintainer for this package, I hope that's alright. I also have another PR for Wonderdraft. #253034

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-03 08:12 UTC, nagy requested changes
The part in `maintainer-list.nix` needs to be in a separate commit. You can find good examples of the commit message in the history of that file https://github.com/NixOS/nixpkgs/commits/master/maintainers/maintainer-list.nix .

2023-09-03 13:20 UTC, IGJoshua commented
I've made updates to this PR, I think it's ready for consideration again, pending the checks.

2023-09-03 13:42 UTC, nagy requested changes

2023-09-03 13:42 UTC, nagy commented on pkgs/applications/graphics/wonderdraft/default.nix
> +  name = "wonderdraft-${version}";
Use `pname = "wonderdraft";`

2023-09-03 13:42 UTC, nagy commented on pkgs/applications/graphics/wonderdraft/default.nix
> +    platforms = platforms.linux;
I think `platforms = [ "x86_64-linux" ];` is more appropriate.

2023-09-03 13:42 UTC, nagy commented on pkgs/applications/graphics/wonderdraft/default.nix
> +    maintainers = with maintainers; [ jsusk ];
Can you add `sourceProvenance = with sourceTypes; [ binaryNativeCode ];`?

2023-09-03 17:08 UTC, nagy requested changes

2023-09-03 17:08 UTC, nagy commented on pkgs/applications/graphics/wonderdraft/default.nix
> +    mkdir -p $out/bin
I forgot to say that this needs `runHook preInstall` at the beginning and `runHook postInstall` at the end. After that, its fine.

2023-09-04 11:09 UTC, nagy approved these changes

2023-09-09 18:55 UTC, kip93 commented on pkgs/top-level/all-packages.nix
> +  wonderdraft = callPackage ../applications/graphics/wonderdraft {  };
Please use the new by-name structure.

2023-09-09 19:19 UTC, wegank commented on pkgs/top-level/all-packages.nix
> +  wonderdraft = callPackage ../applications/graphics/wonderdraft {  };
Done.

2023-09-09 21:27 UTC, marsam approved these changes

2023-09-09 21:41 UTC, merged