Init Treedome Package
NixOS/nixpkgs pull request #253047
Opened 2023-09-03 05:09 UTC by tengkuizdihar

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-03 07:57 UTC, nagy requested changes
Thanks, can you follow the guidelines for the commit message at https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions ?

2023-09-03 08:25 UTC, nagy commented on pkgs/applications/misc/treedome/default.nix
> +  installPhase = ''
This needs `runHook preInstall` and `runHook postInstall`.

2023-09-03 08:26 UTC, nagy commented on pkgs/applications/misc/treedome/default.nix
> +    maintainers = with maintainers; [ tengkuizdihar ];
Can you add `mainProgram = "treedome";` ?

2023-09-03 09:28 UTC, tengkuizdihar commented
Will do, sorry this shouldve been a draft pr lol, its not ready yet im
still tinkering with it

On Sun, 3 Sept 2023, 15:26 Daniel Nagy, ***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In pkgs/applications/misc/treedome/default.nix
> <https://github.com/NixOS/nixpkgs/pull/253047#discussion_r1314174915>:
>
> > +    runHook postBuild
> +  '';
> +
> +  installPhase = ''
> +    mkdir -p $out/bin/
> +    mkdir -p $out/share/
> +
> +    cp target/release/bundle/deb/treedome_0.0.0_amd64/data/usr/bin/treedome $out/bin/treedome
> +    cp -R target/release/bundle/deb/treedome_0.0.0_amd64/data/usr/share/** $out/share/
> +  '';
> +
> +  meta = with lib; {
> +    description = "A local-first, encrypted, note taking application with tree-like structures, all written and saved in markdown.";
> +    homepage = "https://gitlab.com/treedome/treedome";
> +    license = licenses.gpl3Plus;
> +    maintainers = with maintainers; [ tengkuizdihar ];
>
> Can you add mainProgram = "treedome"; ?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/253047#pullrequestreview-1608453975>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AFIOKCU4DL6FWK7743VZKMTXYQ5NBANCNFSM6AAAAAA4JB65AY>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2023-09-04 07:48 UTC, kilianar commented on pkgs/applications/misc/treedome/default.nix
> +    description = "A local-first, encrypted, note taking application with tree-like structures, all written and saved in markdown.";
The description should not include a period at the end. See https://nixos.org/manual/nixpkgs/stable/#var-meta-description

2023-12-29 03:08 UTC, tengkuizdihar commented
oh no

2023-12-29 03:08 UTC, closed without merging