jimtcl: Fix cross compilation and allow disable of SDL
NixOS/nixpkgs pull request #253638
Opened 2023-09-06 14:26 UTC by Cynerd

Jimtcl is dependency of OpenOCD that does not need SDL. For some embedded systems it is beneficial to not pull in graphics related dependencies to reduce the size. The second reason is that right now SDL_gfx is not cross compiling and thus OpenOCD can't be cross compiled either.

This also fixes cross compilation of Jimtcl itself. The attempt to cross compile resulted in:
```
  No installed jimsh or tclsh, building local bootstrap jimsh0
```
The solution here is to add jimtcl to native build dependencies in case of cross compilation.

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-06 17:51 UTC, fgaz commented
> The solution here is to add jimtcl to native build dependencies in case of cross compilation

we could use tcl instead. it has less dependencies and is deeper in the dependency graph

2023-09-07 07:23 UTC, Cynerd commented
> > The solution here is to add jimtcl to native build dependencies in case of cross compilation
> 
> we could use tcl instead. it has less dependencies and is deeper in the dependency graph. We could even add it unconditionally

That is a good idea... done.

2023-09-09 19:07 UTC, fgaz commented
Look like that broke darwin

```
timer-3.2 ERR TimerHandlerEventProc procedure: multiple timers
/private/tmp/nix-build-jimtcl-0.82.drv-0/source/tests/timer.test:61:Error test failure
Expected: {80 {80 240} {80 240 400}}
Got     : {80 {80 240 400} {80 240 400}}
```

Looks like this could be a bug either in tcl or jimtcl. I guess we should report it upstream and meanwhile bootstrap through jimtcl like you did initially

2023-09-10 08:02 UTC, Cynerd commented
I reverted the fixup.

2023-09-16 23:27 UTC, Artturin commented on pkgs/development/interpreters/jimtcl/default.nix
> +  ] ++ (lib.optional (stdenv.buildPlatform != stdenv.hostPlatform) buildPackages.jimtcl);
```suggestion
  ] ++ lib.optionals (stdenv.buildPlatform != stdenv.hostPlatform) [ 
    jimtcl
  ];
```

Splicing already gets us the buildPackages version


All the parentheses added in this pr are unnecessary

2023-09-16 23:30 UTC, Artturin commented
> Look like that broke darwin
> 
> ```
> timer-3.2 ERR TimerHandlerEventProc procedure: multiple timers
> /private/tmp/nix-build-jimtcl-0.82.drv-0/source/tests/timer.test:61:Error test failure
> Expected: {80 {80 240} {80 240 400}}
> Got     : {80 {80 240 400} {80 240 400}}
> ```
> 
> Looks like this could be a bug either in tcl or jimtcl. I guess we should report it upstream and meanwhile bootstrap through jimtcl like you did initially

the error is still happening

2023-09-17 08:26 UTC, fgaz commented
Upstream provided a fix: https://github.com/msteveb/jimtcl/issues/282#issuecomment-1718405499

We can try applying it and going back to tcl

2023-09-18 09:50 UTC, Cynerd commented
I added the patch from the upstream. Hopefully, it will fix darwin.

2023-09-18 10:53 UTC, fgaz commented
Seems like the patch depends on https://github.com/msteveb/jimtcl/commit/d6ce55ad7e01a51acb8a2a909383366ecc89d0b2

We can try applying that too, or (probably better) we can just disable that test for now.

2023-09-18 10:56 UTC, fgaz commented
@Artturin you're on darwin right? Could you try to build jimtcl with src set to [this branch](https://github.com/msteveb/jimtcl/tree/tests-timer-reliability) so we can let upstream know if the patch works?

2023-09-18 12:24 UTC, Cynerd commented
> We can try applying that too, or (probably better) we can just disable that test for now, as suggested by upstream.

I just removed the problematic test file for now.

2023-09-24 15:27 UTC, fgaz requested changes
One last change, then please --autosquash your fixups

2023-09-24 15:27 UTC, fgaz commented on pkgs/development/interpreters/jimtcl/default.nix
> +    tcl
Let's make this unconditional as previously agreed

2023-09-24 15:47 UTC, Artturin commented
> @Artturin you're on darwin right? Could you try to build jimtcl with src set to [this branch](https://github.com/msteveb/jimtcl/tree/tests-timer-reliability?rgh-link-date=2023-09-18T10%3A56%3A13Z) so we can let upstream know if the patch works?

I am not on darwin, I only looked at ofborg CI

2023-10-15 15:07 UTC, fgaz approved these changes
Thanks!

2023-10-15 15:07 UTC, merged