Fix #252741 build error in pytorch-pfn-extras
NixOS/nixpkgs pull request #253845
Opened 2023-09-07 12:07 UTC by jnboehm

Due to mismatched dependency on the onnx version.  See https://github.com/NixOS/nixpkgs/issues/252741

## Description of changes

The package fails to build currently because there is an issue with to mismatched versions on onnx.  This pull request removes onnx and associated tests from the package for the time being.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-07 17:00 UTC, samuela approved these changes
diff LGTM I'm happy to merge once nixpkgs-review comes back clean

2023-09-08 06:59 UTC, nagy requested changes
Can you also please follow the commit message conventions at https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions?

2023-09-09 04:39 UTC, natsukium commented
Result of `nixpkgs-review pr 253845` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages failed to build:</summary>
  <ul>
    <li>python310Packages.ffcv</li>
    <li>python310Packages.ffcv.dist</li>
    <li>python310Packages.pytorch-pfn-extras</li>
    <li>python310Packages.pytorch-pfn-extras.dist</li>
    <li>python311Packages.pytorch-pfn-extras</li>
    <li>python311Packages.pytorch-pfn-extras.dist</li>
  </ul>
</details>

2023-09-11 17:00 UTC, samuela commented
```
E       RuntimeError: DataLoader worker (pid 880) is killed by signal: Aborted.
```
looks like it got oom killed or something like that?

2023-09-13 02:54 UTC, lelgenio commented
Result of `nixpkgs-review pr 253845` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built:</summary>
  <ul>
    <li>python310Packages.ffcv</li>
    <li>python310Packages.ffcv.dist</li>
    <li>python310Packages.pytorch-pfn-extras</li>
    <li>python310Packages.pytorch-pfn-extras.dist</li>
    <li>python311Packages.pytorch-pfn-extras</li>
    <li>python311Packages.pytorch-pfn-extras.dist</li>
  </ul>
</details>

2023-09-14 22:05 UTC, samuela commented
@wegank why did you mark this as draft? o/w looks ready to go?

2023-09-15 13:59 UTC, wegank commented
@ofborg build python310Packages.pytorch-pfn-extras python310Packages.pytorch-pfn-extras

2023-11-19 11:21 UTC, Artturin commented
`python3Packages.pytorch-pfn-extras` builds on master

2023-11-19 11:21 UTC, closed without merging