nixos/users-groups: rename passwordFile in hashedPasswordFile
NixOS/nixpkgs pull request #254080
Opened 2023-09-08 19:22 UTC by rnhmjoj

## Description of changes

This avoids the possible confusion with `passwordFile` being the file version of `password`, while it should contain the password hash.

Fixes issue #165858.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
-  Tested via
  - [x] [nixosTests.simple]
  - [x] [nixosTests.shadow]
  - [x] [nixosTests.mutableUsers]
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-08 19:25 UTC, rnhmjoj commented
Note: unfortunately it's not possible to use `mkRenamedOptionModule` because the option is in a submodule.

2023-09-08 22:10 UTC, MinerSebas requested changes

2023-09-08 22:10 UTC, MinerSebas commented on nixos/modules/config/users-groups.nix
> +      };
This should use `mkRenamedOptionModule` instead of manually creating this Option and Warning on usage.

2023-09-08 22:11 UTC, MinerSebas approved these changes

2023-09-09 10:21 UTC, lheckemann commented
I love it, this rename is well overdue. Thanks for doing it!

It _is_ possible to use `mkRenamedOptionModule` within a submodule by placing it in the `imports` of the submodule -- the network-interfaces module does this, for instance:

https://github.com/NixOS/nixpkgs/blob/50468ccfc81b17856873a8b3caaeb0d755bebb9e/nixos/modules/tasks/network-interfaces.nix#L347

That said, the warnings that this raises aren't clear about _which_ instance the old option is used in, so it's not ideal anyway and I think I prefer the approach you've used here.

2023-09-11 17:29 UTC, pennae approved these changes
looks good, but since this requires a bit more machinery than a "simple" rename maybe we should attach a timeout to it? something like `This legacy option will be removed in 24.11.` or something like that.

(we're carrying a bunch of renames we probably should've dropped ages ago, getting into the habit of making clear *when* that'll happen sounds like a good idea)

2023-09-11 17:42 UTC, rnhmjoj commented
> we're carrying a bunch of renames we probably should've dropped ages ago, getting into the habit of making clear when that'll happen sounds like a good idea

This should probably be an RFC. While it's great that you can skip years worth of NixOS updates and the config still works, realistically nobody cares after 4/5 releases, so yes, there should be an expiration date.
I wouldn't start with this option specifically, though.

2023-09-11 17:51 UTC, merged

2023-09-13 08:05 UTC, 1sixth commented
This somehow breaks my setup. I've been using something similiar to:

```nix
users = {
  mutableUsers = false;
  users.testuser = {
    isNormalUser = true;
    passwordFile = (
      pkgs.writeText "passwordFile"
        # Generated by `mkpasswd -m sha-512`
        "$6$bolIheW9TRtd9EQl$D/qx.cNyFiy4xoHFBWyJO.p3AUY86/4WjvWD3nkxedPVx9xH7v1V6qqgBztXCZtCTHEOrHFCC1ROxktM2K7CD0"
    ).outPath;
  };
};
```

After this PR my `/etc/shadow` looks like this:

```
*REDACTED*
testuser:!:1::::::
*REDACTED*
```

I tried replacing `passwordFile` with `hashedPasswordFile`, but `/etc/shadow` is still the same.

2023-09-13 08:52 UTC, rnhmjoj commented
I'm a bit puzzled, I just renamed the option and added a warning.

2023-09-13 08:59 UTC, rnhmjoj commented
Ah, damn: I missed that the update-users-groups.pl script refers directly to the old option name.
I'm not sure how the tests passed despite this...

2023-09-13 08:59 UTC, dunxen commented
> This somehow breaks my setup.

FWIW, I've been looking around at what might have broken my similar setup and I can't understand why it would be this PR (it's just a rename) but it's the only one touching users/passwords I can find since a few days ago. Seems it has to do with `users.mutableUsers = false` though as everything is fine with that removed (true). Probably deserves a separate issue to not continue discussion on a closed PR, but can't find what may have caused it.

2023-09-13 10:03 UTC, rnhmjoj commented
Fix in https://github.com/NixOS/nixpkgs/pull/254919. It would be great if you could test with your config that it solves the problem.