bun: install completions
NixOS/nixpkgs pull request #254162
Opened 2023-09-09 03:45 UTC by ryanccn

## Description of changes

Adds zsh and fish completions for [bun](https://bun.sh/).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-09 05:52 UTC, DAlperin approved these changes

2023-09-09 09:16 UTC, wegank commented
@ofborg build bun bun.passthru.tests

2023-09-09 09:24 UTC, wegank commented on pkgs/development/web/bun/default.nix
> +  postInstall = ''
```suggestion
  postPhases = [ "postPatchelf" ];
  postPatchelf = lib.optionalString (stdenvNoCC.buildPlatform.canExecute stdenvNoCC.hostPlatform) ''
```

2023-09-09 11:55 UTC, wegank requested changes
`adopt suggestion` -> `bun: adopt suggestion` in the commit message.

2023-09-15 13:19 UTC, cdmistman requested changes

2023-09-15 13:19 UTC, cdmistman commented on pkgs/development/web/bun/default.nix
> +      --fish $completions_dir/bun.fish
bun also has [bash completions](https://github.com/oven-sh/bun/blob/main/completions/bun.bash), can you add those too please?

2023-09-15 13:46 UTC, cdmistman approved these changes
```sh
$ nix shell --refresh github:ryanccn/nixpkgs/bun-completions#bun -c zsh
$ . $(dirname $(which bun))/../share/zsh/site-functions/_bun
$ bun install --ver<tab>
```

works!

2023-09-16 19:34 UTC, wegank approved these changes

2023-09-18 09:14 UTC, happysalada commented
ofborg showed a failure on x86_64-darwin, but just confirmed it builds fine.

2023-09-18 09:14 UTC, merged