libsmi: init at 0.5.0
NixOS/nixpkgs pull request #25433
Opened 2017-05-02 11:29 UTC by pajowu

###### Motivation for this change

Add libsmi

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-02 14:15 UTC, joachifm requested changes

2017-05-02 14:15 UTC, joachifm commented on pkgs/tools/misc/libsmi/default.nix
> +    desc = "A Library to Access SMI MIB Information";
`desc -> description`

Please indicate a `license` and `homepage` as well

2017-05-02 14:15 UTC, joachifm commented on pkgs/top-level/all-packages.nix
> +  libsmi = callPackage ../tools/misc/libsmi { };
Libraries typically go under `development/libraries`.

2017-05-02 14:15 UTC, joachifm commented
Thank you. I've added a few notes for you to consider.

2017-05-03 09:30 UTC, pajowu commented
Thank you, I added the things you mentioned

2017-05-04 13:16 UTC, joachifm approved these changes

2017-05-04 23:13 UTC, merged

2017-05-04 23:13 UTC, joachifm commented
Merged. Thank you