emmet-language-server: init at v2.2.0
NixOS/nixpkgs pull request #255524
Opened 2023-09-16 19:37 UTC by stnley

## Description of changes
Adding package https://github.com/olrtg/emmet-language-server

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-24 05:59 UTC, t4ccer requested changes

2023-09-24 05:59 UTC, t4ccer commented on pkgs/development/tools/language-servers/emmet-language-server/default.nix
> +  version = "v2.2.0";
```suggestion
  version = "2.2.0";
```
Version should be just a number, no `v` prefix, see https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-naming

2023-09-24 05:59 UTC, t4ccer commented on pkgs/development/tools/language-servers/emmet-language-server/default.nix
> +    repo = pname;
```suggestion
    repo = "emmet-language-server";
```
Usually the change of `pname` shouldn't influence the change in source. More info https://github.com/nix-community/nixpkgs-lint/issues/21

2023-09-24 05:59 UTC, t4ccer commented on pkgs/development/tools/language-servers/emmet-language-server/default.nix
> +    rev = version;
```suggestion
    rev = "v${version}";
```
Once you get rid of `v` from version, you must add it here to match the tag

2023-09-24 05:59 UTC, t4ccer commented on pkgs/development/tools/language-servers/emmet-language-server/default.nix
> +    maintainers = with maintainers; [ ];
You should add yourself to maintainers

2023-09-24 05:59 UTC, t4ccer commented on pkgs/development/tools/language-servers/emmet-language-server/default.nix
> +    description = "A language server for emmet.io ";
```suggestion
    description = "A language server for emmet.io";
```
Remove the trailing space

2023-09-24 05:59 UTC, t4ccer commented on pkgs/development/tools/language-servers/emmet-language-server/default.nix
> +, fetchpatch
```suggestion
```
You don't seem to be using it anywhere

2023-09-24 15:31 UTC, stnley commented
@t4ccer Thanks for the review. Should I squash those changes into 1 commit (with init message) then force push?

2023-09-24 17:49 UTC, t4ccer commented
Yes please. You can see https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions for details, but all changes for one "unit" should be in a single commit

2023-09-24 19:25 UTC, stnley commented
Resolved notes from review and pushed new commits.

2023-09-29 15:42 UTC, stnley commented
@t4ccer Just checking to see if the new changes look good

2023-09-29 19:26 UTC, t4ccer commented
Oh one more thing. The commit message should say `emmet-language-server: init at 2.2.0` (without `v`)

2023-09-29 20:10 UTC, stnley commented
@t4ccer Right! Fixed and pushed once again

2023-09-30 01:30 UTC, t4ccer approved these changes
LGTM! You'd need to wait for someone with write access to look again and merge though

2023-12-01 12:59 UTC, emilytrau approved these changes
Apologies for the delay! Thank you for your contribution

2023-12-01 12:59 UTC, merged