olivetin: init at 2023.03.25
NixOS/nixpkgs pull request #256045
Opened 2023-09-19 07:01 UTC by FrancescoDeSimone

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-19 10:15 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/error-building-go-package/32740/2

2023-10-03 08:45 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2713

2023-10-13 16:06 UTC, bbigras commented on pkgs/tools/admin/olivetin/default.nix
> +  src = fetchurl {
isn't it better to use `fetchFromGitHub`?

2023-10-13 16:06 UTC, bbigras commented on pkgs/tools/admin/olivetin/default.nix
> +  os = "linux";
Those 2 variables are not really needed

2023-10-13 16:07 UTC, bbigras commented on pkgs/tools/admin/olivetin/default.nix
> +    description = "OliveTin gives safe and simple access to predefined shell commands from a web interface.";
```suggestion
    description = "OliveTin gives safe and simple access to predefined shell commands from a web interface";
```

> Don’t include a period at the end.

2023-10-16 18:19 UTC, h7x4 requested changes

2023-10-16 18:19 UTC, h7x4 commented on pkgs/tools/admin/olivetin/default.nix
> +  '';
```suggestion
  installPhase = ''
    runHook preInstall
    
    install -Dm555 OliveTin $out/bin/
    
    runHook postInstall
  '';
```

2023-10-16 18:19 UTC, h7x4 commented on nixos/modules/services/admin/olivetin.nix
> +        type = types.str;
```suggestion
        type = types.path;
```

2023-10-16 18:19 UTC, h7x4 commented on nixos/modules/services/admin/olivetin.nix
> +  };
```suggestion
      package = mkPackageOptionMD pkgs "olivetin" { };
```

2023-10-16 18:19 UTC, h7x4 commented on nixos/modules/services/admin/olivetin.nix
> +      "d '${cfg.dataDir}' 0700 ${cfg.user} ${cfg.group} - -"
Are you planning to remove the `dataDir` every time the service shuts down?

2023-10-16 18:19 UTC, h7x4 commented on nixos/modules/services/admin/olivetin.nix
> +    };
```suggestion
    networking.firewall.allowedTCPPorts = mkIf cfg.openFirewall [ 1340 ];
```

2023-10-16 18:19 UTC, h7x4 commented on nixos/modules/services/admin/olivetin.nix
> +        ExecStart = "${cfg.package}/bin/OliveTin -configdir='${cfg.dataDir}'";
If you set `meta.mainProgram`, you could do this:

```suggestion
        ExecStart = "${lib.getExe cfg.package} -configdir='${cfg.dataDir}'";
```

2023-10-16 18:19 UTC, h7x4 commented on nixos/modules/services/admin/olivetin.nix
> +  options = {
I find it a bit weird that there aren't any `settings` option with a yaml freeformat here. The upstream project seems to have a [bunch of settings that the user of the module might want to set](https://github.com/OliveTin/OliveTin#quickstart-reference-for-configyaml)

2023-10-16 18:19 UTC, h7x4 commented on pkgs/tools/admin/olivetin/default.nix
> +stdenv.mkDerivation rec {
Would you be okay with rewriting this to build from source using `buildGoModule`? Right now we're only able to build for 64-bit linux, but the go compiler supports building for both 64 bit and 32 bit linux and darwin.

2023-10-16 18:19 UTC, h7x4 commented on nixos/modules/services/admin/olivetin.nix
> +      description = "OliveTin";
If you're gonna have a description at all, it should probably be something more descriptive

2023-10-16 18:19 UTC, h7x4 commented on nixos/modules/services/admin/olivetin.nix
> +        Group = cfg.group;
There are no such options `config.services.olivetin.user` and `config.services.olivetin.group`?

2025-05-26 18:05 UTC, closed without merging