azure-image: remove qemu-220
NixOS/nixpkgs pull request #25661
Opened 2017-05-09 23:56 UTC by puffnfresh

We don't need this according to #16437

###### Motivation for this change

Fixing old issues.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-10 01:22 UTC, fpletz commented
@fadenb Do you have time to test this? :slightly_smiling_face:

2017-05-10 07:43 UTC, fadenb commented
I believe it is missing the  -o force_size option. See https://github.com/NixOS/nixpkgs/pull/25197#issuecomment-297228314 and the other comments. I can test this later today.

2017-05-19 11:47 UTC, fadenb requested changes
I finally found the time to test this PR. As expected the produced image was not accepted by Azure:

        The VHD for disk 'nixosVMelasticosdisk' with blob https://somename.blob.core.windows.net/graylog-images/nixosVM-elastic-0-osdisk.vhd has an unsupported virtual size of 30720.375 MB. The size must be a whole number in (MBs).

2018-03-09 11:41 UTC, fadenb commented
(just stumbled on this PR again)
@puffnfresh: Should we close this PR as the initial test I did last year failed to produce usable output?

2018-04-21 20:19 UTC, matthewbauer requested changes
merge conflict/see @fadenb's concerns

2018-04-26 08:14 UTC, colemickens commented
Per this comment, https://bugs.launchpad.net/qemu/+bug/1490611/comments/39, you need to add `force_size` to the options.

I'm working on some other Azure changes, including this. I'll send some PRs if it all works out. Apologies for not being more detailed in the Issue that triggered this...

2018-05-13 18:14 UTC, fadenb commented
@colemickens: Sorry, I can not remember exactly what I did back then. I suspect I tested that combination as I did quite a few tests but I am not sure.

2018-05-13 19:17 UTC, colemickens commented
@fadenb It's alright. I've been creating and using new images myself using the mainline `qemu`. I'll try to isolate the qemu change from my other changes and send it as a PR at least.

2018-06-12 09:35 UTC, Mic92 commented
we merged https://github.com/NixOS/nixpkgs/pull/41881 instead.

2018-06-12 09:35 UTC, closed without merging