Borealis cursors
NixOS/nixpkgs pull request #256799
Opened 2023-09-23 01:57 UTC by argrat

## Description of changes

Added Borealis cursors, a cursor theme using a custom color palette inspired by boreal colors.

## Things done

- Built on platform(s)
  - [*] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [*] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I have built the package locally and it works as intended.

2023-09-23 07:53 UTC, nagy requested changes
Can you also use commit messages as described in the guidelines? https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions

2023-09-23 07:53 UTC, nagy commented on pkgs/top-level/all-packages.nix
> +  borealis-cursors = callPackage ../data/icons/borealis-cursors { };
Can you use the new by-name structure https://github.com/NixOS/nixpkgs/tree/master/pkgs/by-name#name-based-package-directories ?

2023-09-24 10:33 UTC, nagy commented on pkgs/by-name/bo/borealis-cursors/package.nix
> +    rev = "d61a5e82ddb03341766d7e3d60065ad435300991";
Is there a reason why you cannot use the tag itself as the rev?

2023-09-27 22:17 UTC, nagy requested changes
Also please change your PR title to `borealis-cursors: init at 2.0`.

2023-09-27 22:17 UTC, nagy commented on pkgs/by-name/bo/borealis-cursors/package.nix
> +stdenvNoCC.mkDerivation {
You should use `stdenvNoCC.mkDerivation(finalAttrs: { ` here, so that you can reuse the `version` attribute down in the `src` attribute.

2023-09-28 08:32 UTC, nagy approved these changes

2023-10-08 17:15 UTC, wegank commented on pkgs/by-name/bo/borealis-cursors/package.nix
> +    sha256 = "1f8fcixzr2y4wc1dhamc885mbnasq5gri6x1hb01yvv98d9k5a6n";
```suggestion
    hash = "sha256-1qgyU0Npbx/AgqGbmF/BWtlVC0KsKtgC48SL/HtkDrk=";
```

2023-10-08 17:15 UTC, wegank commented on pkgs/by-name/bo/borealis-cursors/package.nix
> +    description = "Cursor theme using a custom color palette inspired by boreal colors.";
```suggestion
    description = "Cursor theme using a custom color palette inspired by boreal colors";
```

2023-10-30 03:44 UTC, eclairevoyant requested changes
Looks good overall.
One note, because this is a new package, can we squash the last 2 commits into the init commit?

2023-11-04 19:03 UTC, FliegendeWurst approved these changes

2023-11-04 19:05 UTC, merged