darwin: trash 0.9.0
NixOS/nixpkgs pull request #25713
Opened 2017-05-11 19:50 UTC by jbaum98

###### Motivation for this change

Add the [`trash` command](https://github.com/ali-rantakari/trash) for darwin.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] macOS
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-12 14:32 UTC, pSub requested changes

2017-05-12 14:32 UTC, pSub commented on pkgs/os-specific/darwin/trash/default.nix
> +    rev = "f68ad25a02e24cc58eb8ef9a493d6dc0122bcd8f";
It would be better to use a release-tag instead of the revision. As there is no release-tag for 0.9.0 could you please ask the Author to create one?

2017-05-12 14:32 UTC, pSub commented on pkgs/os-specific/darwin/trash/default.nix
> +  meta = {
Please provide more metainformation.

2017-11-15 22:09 UTC, c0bw3b commented
@jbaum98 Are you still working on adding this package to Nix?

2017-11-15 22:11 UTC, jbaum98 commented
I'm still waiting on the author to create a 0.9.0 release tag.

2017-11-16 07:32 UTC, pSub commented
If the author is that unresponsive we can also add it using the commit-hash. Could you rebase and add more meta-information (desription, license)?

2018-01-12 03:01 UTC, jbaum98 commented
I think I added the meta data you asked for, can we get this merged or is there more to do?

2018-01-12 08:34 UTC, merged