cosmo: init at 0.18.4
NixOS/nixpkgs pull request #257247
Opened 2023-09-25 11:20 UTC by rvolosatovs

## Description of changes

Add `cosmo`, the CLI for https://cosmonic.com/, which is based on open-source https://github.com/wasmCloud/wasmcloud CNCF sandbox project

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-09-25 11:32 UTC, rvolosatovs commented
@ofborg build cosmo

2023-09-26 08:53 UTC, Janik-Haag commented
Result of `nixpkgs-review pr 257247` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cosmo</li>
  </ul>
</details>

2023-10-09 06:43 UTC, ocfox requested changes
Other than the weird format and lengthy description, LGTM!

2023-10-09 06:43 UTC, ocfox commented on pkgs/development/tools/cosmo/default.nix
> +    '';
Don't forget the runHook.

2023-10-09 06:44 UTC, ocfox commented
Result of `nixpkgs-review pr 257247` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cosmo</li>
  </ul>
</details>

2023-10-09 08:37 UTC, rvolosatovs commented
> Other than the weird format and lengthy description, LGTM!

What do you mean by the "weird format"?

2023-10-09 09:52 UTC, ocfox commented
> What do you mean by the "weird format"?

The code format is not quite in the form normally used by nixpkgs.

2023-11-09 09:59 UTC, rvolosatovs commented
Rebased to address a merge conflict, could someone take a look?

2024-06-11 21:44 UTC, pbsds commented on pkgs/development/tools/cosmo/default.nix
> +      platforms = with platforms; linux ++ darwin ++ windows;
platforms has a lot more systems strings than what you have hashes for

2024-06-11 21:44 UTC, pbsds commented on pkgs/development/tools/cosmo/default.nix
> +}: let
```suggestion
}: 
let
```

2024-06-11 21:44 UTC, pbsds commented on pkgs/development/tools/cosmo/default.nix
> +  stdenvNoCC.mkDerivation rec {
```suggestion
in
stdenvNoCC.mkDerivation rec {
```

and dedent the rest

2024-06-11 21:44 UTC, pbsds commented on pkgs/development/tools/cosmo/default.nix
> +    or (throw "Unsupported system: ${system}");
```suggestion
  hashes = {
    aarch64-darwin = "sha256-Nk/mhtgdOISc9JbnZAEQ/g6ubie+SnRM729zpG6/lo4=";
    aarch64-linux = "sha256-lPXbbF/Zr1+XRB04KxnVt7DxpJCN5xCinTxPDDg4h2Y=";
    x86_64-darwin = "sha256-tCjhQXsfyePHHeTz3zoz+dp9MPGo7ST1bGQjaM1OBgk=";
    x86_64-linux = "sha256-bwvOJAr0KoAI808OaGZB5uhG1J0dzrodr3ZXK5/9S7Q=";
    x86_64-windows = "sha256-3W/QzY7jcVxGkHsEsfNyhvDzca2TC/sTxN5/AOFZz/g=";
  }
```

2024-06-11 21:44 UTC, pbsds commented on pkgs/development/tools/cosmo/default.nix
> +        ;
```suggestion
      hash =  hashes.${system} or (throw "Unsupported system: ${system}");
```

2024-06-11 21:44 UTC, pbsds commented on pkgs/development/tools/cosmo/default.nix
> +      platforms = with platforms; linux ++ darwin ++ windows;
```suggestion
      platforms = lib.attrNames hashes;
```

2024-06-11 21:44 UTC, pbsds commented on pkgs/top-level/all-packages.nix
> +  cosmo = callPackage ../development/tools/cosmo { };
please migrate to by-name

2024-06-11 21:44 UTC, pbsds commented on pkgs/development/tools/cosmo/default.nix
> +      ;
```suggestion
    inherit version;
```

2024-12-02 14:32 UTC, closed without merging