seth: init at 0.5.0
NixOS/nixpkgs pull request #25736
Opened 2017-05-12 13:08 UTC by dbrock

###### Motivation for this change

Seth is a command-line utility for working with the Ethereum blockchain. It is a dependency for some other Ethereum-related programs as well as being useful in its own right.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-12 14:28 UTC, pSub requested changes

2017-05-12 14:28 UTC, pSub commented on pkgs/applications/altcoins/seth.nix
> +  buildInputs = [makeWrapper];
makeWrapper should be a nativeBuildInput

2017-05-13 15:51 UTC, dbrock commented on pkgs/applications/altcoins/seth.nix
> +  buildInputs = [makeWrapper];
@pSub Thanks, fixed!

2017-05-14 13:26 UTC, pSub approved these changes

2017-05-14 13:26 UTC, pSub commented
Looks good to me. Could you squash your change into a single commit?

2017-05-14 22:28 UTC, dbrock commented
@pSub Done, thanks a lot.

2017-05-15 05:59 UTC, merged