spacy: added Explosion AI spaCy, thinc and related tools
NixOS/nixpkgs pull request #25791
Opened 2017-05-15 01:16 UTC by sdll

###### Motivation for this change

Making NLP analysis easier with Nix.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-15 06:38 UTC, FRidh requested changes
- Looks good overall
- Remove meta.platforms
- Preferably use fetchPypi
- Do not commit whitespace changes in `python-packages.nix`

2017-05-15 06:38 UTC, FRidh commented on pkgs/development/python-modules/cymem.nix
> +    platforms = platforms.unix;
don't set platforms in Python packages. The function already takes care of that.

2017-05-15 06:38 UTC, FRidh commented on pkgs/development/python-modules/ftfy.nix
> +    nose
It needs pytest and nose, but uses unittest as runner? That's odd.

2017-05-15 06:38 UTC, FRidh commented on pkgs/development/python-modules/ftfy.nix
> +  src = fetchurl {
fetchPypi

2017-05-15 06:38 UTC, FRidh commented on pkgs/development/python-modules/murmurhash.nix
> +   cython
This is not a runtime dependency, or is it?

2017-05-15 10:18 UTC, sdll commented
@FRidh, thank you very much for your review!

 I have made requested changes and cleaned up the code, removing whitespace trimming in python-packages.nix.

 With regards to murmurhash, cython is a build dependency, as you can see [here](https://github.com/explosion/murmurhash/blob/master/requirements.txt).

2017-05-15 10:33 UTC, FRidh commented
> With regards to murmurhash, cython is a build dependency, as you can see here.

A requirements.txt file doesn't say much, because its not used when building a package with setuptools, unless its explicitly read and added to e.g.  `install_requires`. Looking at the `setup.py` file it seems it is only required to run setup and perform the build. 

If a package is only used during build and install time, then it should be added to `buildInputs`. If it is needed at runtime or when another package that depends on it is build, it should be added to `propagatedBuildInputs`.

2017-05-15 10:47 UTC, sdll commented
@FRidh, thank you for teaching me something new today!

I have changed ftfy to make Travis CI builds work for GNU/Linux and OS X.

 I have also changed murmurhash build inputs as requested.

2017-05-15 17:00 UTC, sdll commented
@FRidh, I moved recipes to satisfy the 'package/default.nix' format, as well as replaced `with rec {....}` with `let ... in`. 

OS X seems to time out, could you please tell me how I can decrease the build time? My first idea was to set `doCheck = false;` in some recipes exclusively for OS X, is there a way to do it?

2017-05-15 17:10 UTC, FRidh commented
@sdll you can ignore Travis. While it is sometimes useful, we cannot really rely on it.

2017-05-15 18:04 UTC, sdll commented
@FRidh, is there anything else I need to change? Is the tag "needs: clean-up" still relevant?

2017-05-15 20:08 UTC, sdll commented
@FRidh, I have updated the recipe ftfy, the testing issue was fixed (see https://github.com/LuminosoInsight/python-ftfy/issues/75)

2017-05-17 11:14 UTC, sdll commented
@FRidh, 

Travis CI on OS X seems to fail again due to the same error as in https://github.com/NixOS/nixpkgs/pull/25804:
```
pyemd/emd.cpp:458:10: fatal error: 'vector' file not found
```
Similarly, do you think we should try to fix it by specifying GCC_INSTALL_HOME?
See a similar question discussed here: ysshao/LLVM-Tracer#7

Is there a deeper problem with how clang c++ headers are treated in the OS X build of Nix?

2017-07-28 14:18 UTC, FRidh commented
@knedlsepp is this related to #27649? (I'm just diving through old PR's)

2017-07-28 14:27 UTC, knedlsepp commented
@FRidh: Seems highly likely. I'll try to rework my PR asap, so we can merge.

2017-08-13 20:26 UTC, FRidh commented
This needs a minor rebase. I successfully built the 2.7 version of spacy but the 3.6 hang during building.

2017-08-13 20:41 UTC, FRidh commented
I've pushed this to master.

2017-08-19 20:19 UTC, closed without merging

2018-09-25 02:48 UTC, JonathanReeve commented
Great work! Any idea how to install the data using Nix? (E.g. `en_core_web_lg`?)