platformio: 6.1.6 -> 6.1.11
NixOS/nixpkgs pull request #258358
Opened 2023-10-01 08:25 UTC by FliegendeWurst

## Description of changes

Simple bugfix updates, I believe.
https://github.com/platformio/platformio-core/releases/tag/v6.1.11
https://github.com/platformio/platformio-core/releases/tag/v6.1.10
https://github.com/platformio/platformio-core/releases/tag/v6.1.9
https://github.com/platformio/platformio-core/releases/tag/v6.1.8
https://github.com/platformio/platformio-core/releases/tag/v6.1.7

Fixes #255476

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`
```
3 packages updated:
esphome platformio platformio-core (6.1.6 → 6.1.11)
6 packages built:
esphome esphome.dist platformio platformio-core platformio-core.dist platformio-core.udev
```
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-01 15:16 UTC, FliegendeWurst commented
> Seems to now require `click`.

It is already included in the `propagatedBuildInputs` of platformio and esphome. I am not sure why it doesn't find it.

2023-10-01 15:30 UTC, SuperSandro2000 approved these changes

2023-10-01 16:06 UTC, mweinelt requested changes
No.

2023-12-22 00:13 UTC, JamieMagee commented
Superseded by #274574

2023-12-22 00:13 UTC, closed without merging