mawled: init at 20170517
NixOS/nixpkgs pull request #25858
Opened 2017-05-17 14:40 UTC by amiloradovsky

A minimalist window manager written in Dale.
Mawled is a basic X11 tiling window manager, inspired by XMonad, though with fewer features.

###### Motivation for this change

It has been requested.

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2017-05-20 10:23 UTC, Mic92 commented on pkgs/applications/window-managers/mawled/default.nix
> +    # The Dale port is currently present only on these platforms
You do not have to make this explicit. hydra will not built this package, if the buildInputs are not available on the target platform. 

```
platforms = platforms.linux;
``

should be good to go.

2017-05-20 10:26 UTC, Mic92 commented
How would I test this windowmanager?

```
$ mawled                                                                                                  
Error: serial 45, ec 522, rc 1080, mc 37431696, rid 246
```

2017-05-20 16:55 UTC, amiloradovsky commented
@Mic92 To be honest, I didn't actually tested it extensively, because it would require to disable my current DE (to execute `~/.xsession`). I only

- saw that error message(s) when tried to run it right from the DE -- that's no surprise
- observed that pressing Alt+P, or any other reserved keybinding, makes it fail -- as expected
- plus, people reported that it indeed works, on NixOS

But now, as I tried to actually use it as the WM (on another machine), i.e. via disabling a desktop manager and starting it from the terminal, I couldn't.

- On an amd64 laptop it doesn't fail, doesn't show the errors, or any reaction at all...
- In Qemu (i686), it crashed with segfailt

To recap, maybe I was too quick with opening the PR and it's still buggy as hell.
But I'd like to someone else confirm that it indeed behaves this way, and not just me forgetting to set some options. @jb55 ?

2018-04-21 20:54 UTC, matthewbauer commented
@GrahamcOfBorg build mawled

2018-04-21 20:55 UTC, GrahamcOfBorg commented
No attempt on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.25858&attempt_id=11929430-6ded-4f74-a8dc-eefc4752803c)

The following builds were skipped because they don't evaluate on x86_64-linux: mawled

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `mawled' because:
[31;1merror:[0m while evaluating 'callPackageWith' at [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/lib/customisation.nix[0m:113:35, called from [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/pkgs/top-level/all-packages.nix[0m:1321:12:
while evaluating 'makeOverridable' at [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/lib/customisation.nix[0m:72:24, called from [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/lib/customisation.nix[0m:117:8:
while evaluating anonymous function at [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/pkgs/applications/window-managers/mawled/default.nix[0m:1:1, called from [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/lib/customisation.nix[0m:74:12:
while evaluating 'mkDerivation' at [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/pkgs/stdenv/generic/make-derivation.nix[0m:15:5, called from [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/pkgs/applications/window-managers/mawled/default.nix[0m:5:4:
value is a string while a list was expected, at [1m/home/ofborg/ofborg1/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-7c6f434c1/pkgs/stdenv/generic/make-derivation.nix[0m:78:95

```
</p></details>

2018-04-21 20:55 UTC, GrahamcOfBorg commented
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.25858&attempt_id=08b1105d-a9b5-4dca-8624-adf6ad1645b5)

The following builds were skipped because they don't evaluate on x86_64-darwin: mawled

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `mawled' because:
error: while evaluating 'callPackageWith' at /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix:113:35, called from /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/top-level/all-packages.nix:1321:12:
while evaluating 'makeOverridable' at /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix:72:24, called from /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix:117:8:
while evaluating anonymous function at /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/applications/window-managers/mawled/default.nix:1:1, called from /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix:74:12:
while evaluating 'mkDerivation' at /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/stdenv/generic/make-derivation.nix:15:5, called from /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/applications/window-managers/mawled/default.nix:5:4:
value is a string while a list was expected, at /private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/stdenv/generic/make-derivation.nix:78:95

```
</p></details>

2018-04-21 20:55 UTC, GrahamcOfBorg commented
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.25858&attempt_id=3e511405-7491-465a-a122-5588d9705370)

The following builds were skipped because they don't evaluate on aarch64-linux: mawled

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `mawled' because:
[31;1merror:[0m while evaluating 'callPackageWith' at [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/lib/customisation.nix[0m:113:35, called from [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/pkgs/top-level/all-packages.nix[0m:1321:12:
while evaluating 'makeOverridable' at [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/lib/customisation.nix[0m:72:24, called from [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/lib/customisation.nix[0m:117:8:
while evaluating anonymous function at [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/pkgs/applications/window-managers/mawled/default.nix[0m:1:1, called from [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/lib/customisation.nix[0m:74:12:
while evaluating 'mkDerivation' at [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/pkgs/stdenv/generic/make-derivation.nix[0m:15:5, called from [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/pkgs/applications/window-managers/mawled/default.nix[0m:5:4:
value is a string while a list was expected, at [1m/var/lib/gc-of-borg/nix-test-rs-25/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-25/pkgs/stdenv/generic/make-derivation.nix[0m:78:95

```
</p></details>

2018-04-21 20:58 UTC, matthewbauer requested changes
See @GrahamcOfBorg eval issue

2019-05-18 18:24 UTC, c0bw3b commented
Stalled

2019-05-18 18:24 UTC, closed without merging