manual: add "declarative package management" section
NixOS/nixpkgs pull request #25955
Opened 2017-05-21 03:27 UTC by matthewbauer

This section gives some details on how to setup an "environment"
without having to go through NixOS (although it could be used there
too). I’ve tried to make it straightforward and have a kind of
"tutorial" feel. Not sure if that’s appropriate for the manual, so any
recommended changes would be helpful.

Also the section might not be totally appropriate, but this is a fairly general use case, I think.

2017-05-21 12:08 UTC, Ericson2314 commented
Night there be a wiki migration issue this fixes?

2017-05-21 20:11 UTC, LnL7 commented on doc/configuration.xml
> +        aspell
I think it might be better to stick to 2 or 3 packages for the examples.

2017-05-21 20:36 UTC, vcunat commented
Just for record, I personally prefer using simple attrmaps instead of `buildEnv`; I find that more flexible and better working together with `nix-env`.  Still, in general I do find it useful to document such howto/cookbook/best-practice stuff.

2017-05-22 01:40 UTC, matthewbauer commented
> Just for record, I personally prefer using simple attrmaps instead of buildEnv

Do you have an example of your setup? My understanding was you could never get man pages/info pages setup correctly without ```extraOutputsToInstall```.

2017-05-23 10:25 UTC, vcunat commented
Correct; I *do* consider #24717 a bug.  It's still possible to map over the custom set and amend `meta.outputsToInstall`, as an example workaround.

2017-07-02 11:53 UTC, 0xABAB commented on doc/configuration.xml
> +      which gets rid of the extra stuff in the profile.
`not linking the extra stuff (like <insert concrete non-matching file path>) in the profile.` (feel free to modify slightly if what I am saying is not correct, the point I want to make is that it's vague)

2017-07-02 11:55 UTC, 0xABAB commented on doc/configuration.xml
> +      defaults for a user environment, getting rid of the clutter. If you are
`defaults for a clutter free user environment` is shorter.

2017-07-02 11:56 UTC, 0xABAB commented on doc/configuration.xml
> +      <filename>~/.nix-profile</filename> to make sure everything is there that
-`that we wanted`

2017-07-02 11:59 UTC, 0xABAB commented on doc/configuration.xml
> +      we wanted. Discerning readers will note that some files are missing. Look
A fairly long paragraph to make a simple point. Spending words to tell the user is super smart, might be attractive to the latent narcissists , but I count them as waste.

2017-07-02 12:01 UTC, 0xABAB commented on doc/configuration.xml
> +      This provides us with some useful documentation for using our packages.
This line doesn't add anything.

2017-07-02 12:02 UTC, 0xABAB commented on doc/configuration.xml
> +      However, if we actually want those manpages to be detected by man, we need
To make man detect our written manpages...

2017-07-02 12:03 UTC, 0xABAB commented on doc/configuration.xml
> +      to set up our environment. This can also be managed within Nix
Overloading the word environment makes it harder to read.

2017-07-02 12:05 UTC, 0xABAB commented on doc/configuration.xml
> +if [ -d $HOME/.nix-profile/etc/profile.d ]; then
Not quoting $HOME makes baby Jezus cry. It's better to replace it with `~`.

2017-07-02 12:06 UTC, 0xABAB commented on doc/configuration.xml
> +  for i in $HOME/.nix-profile/etc/profile.d/*.sh; do
Same

2017-07-02 12:06 UTC, 0xABAB commented on doc/configuration.xml
> +    if [ -r $i ]; then
Quotes

2017-07-02 12:06 UTC, 0xABAB commented on doc/configuration.xml
> +      . $i
Quotes

2017-07-02 12:07 UTC, 0xABAB commented on doc/configuration.xml
> +      Now just run <literal>source $HOME/.profile</literal> and you can starting
`~`

2017-07-02 12:10 UTC, 0xABAB commented on doc/configuration.xml
> +      Configuring GNU info is a little bit trickier than man pages. To work
Qualifications about difficulty are a waste of words. 

To let GNU Info display our <info pages/documentation/whatever> it needs this information indexed in a database, which is done as followed:

2017-07-02 12:11 UTC, 0xABAB commented on doc/configuration.xml
> +                $out/bin/install-info $i $out/share/info/dir
Quotes

2017-07-02 12:12 UTC, 0xABAB commented on doc/configuration.xml
> +      <literal>postBuild</literal> tells Nixpkgs to run a command after building
Nixpkgs doesn't really run anything. Please rewrite to be correct.

2017-07-02 12:15 UTC, 0xABAB commented on doc/configuration.xml
> +      installed info pages to <literal>dir</literal> which is GNU info's default
GNU Info (see https://www.gnu.org/software/texinfo/manual/info-stnd/info-stnd.html)

2017-07-02 12:16 UTC, 0xABAB commented on doc/configuration.xml
> +      environment to give the <literal>install-info</literal> command.
`to give` is unspecific language.

2017-07-02 12:17 UTC, 0xABAB commented on doc/configuration.xml
> +      packages like Nix have multiple outputs for things like documentation (see
DocBook is a hyperlinked format, so just link to the section.

2017-07-02 12:20 UTC, 0xABAB commented on doc/configuration.xml
> +
Please define what is understood by an environment.

2017-07-02 12:22 UTC, 0xABAB requested changes
Thanks for taking the time to write documentation, but I have quite some comments.

2017-07-16 20:50 UTC, grahamc commented
Merging, this is better than what is there. Thank you.

2017-07-16 20:50 UTC, merged