minetest-mapserver: init at 4.7.0
NixOS/nixpkgs pull request #259915
Opened 2023-10-09 05:50 UTC by zeuner

## Description of changes

This package provides a web-based real-time mapserver for minetest voxel game servers: https://github.com/minetest-mapserver/mapserver/blob/master/readme.md

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-09 07:00 UTC, cafkafk reviewed
code lgtm, sending result of nixpkgs-review when done.

2023-10-09 07:01 UTC, cafkafk commented
Result of `nixpkgs-review pr 259915` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>minetest-mapserver</li>
  </ul>
</details>

2023-10-09 07:02 UTC, cafkafk approved these changes
seems to build fine, didn't test with a `world.mt`

2023-10-09 07:15 UTC, zeuner commented
> seems to build fine, didn't test with a `world.mt`

Works for me. The binary must be called from the directory where `world.mt` resides.

2023-10-10 06:50 UTC, nlewo requested changes
Otherwise, lgtm.

2023-10-10 06:50 UTC, nlewo commented on maintainers/maintainer-list.nix
> +    email = "nix@quidecco.pl";
Could you add your github nickname also? (could be convenient for automation and other to find you on github)

2023-10-10 06:50 UTC, nlewo commented on pkgs/by-name/mi/minetest-mapserver/package.nix
> +    rev = "refs/tags/v${version}";
```suggestion
    rev = "v${version}";
```

2023-10-10 08:52 UTC, zeuner commented on pkgs/by-name/mi/minetest-mapserver/package.nix
> +    rev = "refs/tags/v${version}";
Ok, this also works.

2023-10-11 06:08 UTC, nlewo commented on maintainers/maintainer-list.nix
> +    email = "nix@quidecco.pl";
hehe, I unrderstand!

2023-10-11 06:13 UTC, nlewo requested changes
Could you squash your lastest commit with the commit introducing the software (in order to only have 2 commits)?

2023-10-11 10:17 UTC, zeuner commented
> Could you squash your lastest commit with the commit introducing the software (in order to only have 2 commits)?

Of course!

2023-10-11 20:16 UTC, nlewo approved these changes
Thank you.

2023-10-11 20:16 UTC, merged