jitterentropy-rngd: init at 1.2.8
NixOS/nixpkgs pull request #260275
Opened 2023-10-10 19:01 UTC by thillux

Add jitterentropy-rngd, a tool similar to rng-tools. While not necessarily needed, it is useful for those who want to strengthen their kernel entropy input pool by periodic insertion of an independent source.

The entropy source is a NIST SP800-90B compliant
non-physical true RNG source on most systems.
See the jitterentropy documentation for details
(http://chronox.de/jent/doc/CPU-Jitter-NPTRNG.pdf).

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-19 16:19 UTC, h7x4 requested changes
Seems pretty cool. Just a few nits here and there

2023-10-19 20:07 UTC, h7x4 commented on nixos/modules/services/security/jitterentropy-rngd.nix
> +    systemd.packages = [ cfg.package ];
Nevermind, I read `environment.packages`. Feel free to mark as resolved

2023-10-19 20:10 UTC, thillux commented on nixos/modules/services/security/jitterentropy-rngd.nix
> +    systemd.packages = [ cfg.package ];
This is not the purpose of this line. It makes systemd services already contained in the package available for the module.

2023-10-19 20:11 UTC, thillux commented on nixos/modules/services/security/jitterentropy-rngd.nix
> +    systemd.services."jitterentropy".wantedBy = [ "basic.target" ];
Without such a line, the upstream service is not enabled. Being consistent with the upstream service was therefore by purpose.

2023-10-19 21:47 UTC, nikstur approved these changes
Looks good. If you fix the editor config this can be merged.

2023-10-19 21:50 UTC, h7x4 approved these changes

2023-10-19 21:53 UTC, nikstur commented
@ofborg build jitterentropy-rngd

2023-10-20 07:47 UTC, thillux commented
> Looks good. If you fix the editor config this can be merged.

Oh gosh, I'm just too stupid to use correct editor settings when working on different projects with different coding style and language :) Thanks for the hint.

2023-10-20 08:03 UTC, thillux commented
Nevermind, I installed EditorConfig into my editor. None of my other projects should interfere.

2023-10-21 08:02 UTC, thillux commented
@nikstur I fixed the editor config check.

2023-10-21 17:10 UTC, merged