haskell.compiler.ghc*Binary: fix globbing
NixOS/nixpkgs pull request #260410
Opened 2023-10-11 10:51 UTC by ncfavier

Fix the `--package-db="$out/lib/"ghc-*/package.conf.d` glob (this does not do what you think!).

Disable `nullglob` as it seems incompatible with the way globs are used throughout those files, and caused some errors to be silently ignored.

2023-10-13 15:43 UTC, sternenseemann approved these changes

2023-10-15 12:56 UTC, sternenseemann requested changes
We actually need to check for

- `"$out"/lib/ghc-*/lib/package.conf.d` (hadrian) and
- `"$out"/lib/ghc-*/package.conf.d` (make)

and use whichever exists, since there is a mix between what was used to build the bindists here.

2023-10-16 06:34 UTC, sternenseemann approved these changes

2023-10-16 06:35 UTC, sternenseemann commented
Interesting that we have hadrian bindists in the earlier binary GHCs, but none of the hadrian specific of the 9.2.4 one. A mystery to ponder some other time… Thanks!

2023-10-18 20:32 UTC, maralorn commented
Am I correct in assuming, that we merge this the next time we want to do a full set rebuild?

2023-10-22 00:57 UTC, merged