Feedreader 2.0
NixOS/nixpkgs pull request #26090
Opened 2017-05-25 15:36 UTC by edwtjo

###### Motivation for this change

Didn't push this package addition since it needs to add vala bindings for gnome_online_accounts.

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-06-02 16:21 UTC, jluttine commented
This is great, I'm really excited about getting FeedReader to NixOS. However, I tried this PR but I get the following error:
```
[ DEBUG ] write login data
[ DEBUG ] OwnCloud URL: https://somedomain.com/index.php/apps/news/api/v1-2/

(feedreader:11338): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files

(feedreader:11338): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
** Message: Remote error from secret service: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.secrets was not provided by any .service files
[ ERROR ] OwncloudNewsUtils: setPassword: The name org.freedesktop.secrets was not provided by any .service files
[ DEBUG ] LoginPage: status = FEED_READER_LOGIN_RESPONSE_ALL_EMPTY
[ DEBUG ] MainWindow: show error bar - errorCode = 5
[ DEBUG ] MainWindow: show error bar
[ DEBUG ] DBusConnection: setOffline
```
I can't add ownCloud account, it just prints this into terminal and tells me to give login details in the GUI although I've given them. I'm using KDE if that matters. Do I need to do something?

2017-06-15 04:55 UTC, edwtjo commented
Are you running any application providing `org.freedesktop.service` like `gnome-keyring`? I'm unsure what the KDE equivalent is, perhaps KWallet?

2017-11-23 18:00 UTC, jtojnar commented
@jluttine Try adding `services.dbus.packages = with pkgs; [ gnome3.dconf ];` to your `configuration.nix`.

2017-11-23 18:06 UTC, jtojnar commented
@edwtjo The vala support was enabled in https://github.com/NixOS/nixpkgs/pull/30093.

2017-11-23 18:30 UTC, jtojnar requested changes

2017-11-23 18:30 UTC, jtojnar commented on pkgs/applications/networking/feedreaders/feedreader/default.nix
> +    cmake curl gettext glib json_glib libaccounts-glib libnotify libsecret
We want to put things like `cmake` and `gettext` to `nativeBuildInputs`.

2017-11-23 18:30 UTC, jtojnar commented on pkgs/applications/networking/feedreaders/feedreader/default.nix
> +  buildPhase = ''
The `buildPhase` should not be necessary thanks to `cmake` setup hook.

2017-11-23 18:30 UTC, jtojnar commented on pkgs/applications/networking/feedreaders/feedreader/default.nix
> +      wrapProgram "$exe" \
Add `wrapGAppsHook` to `nativeBuildInputs` to populate the variables automatically.

2017-11-23 18:30 UTC, jtojnar commented on pkgs/applications/networking/feedreaders/feedreader/default.nix
> +    glib-compile-schemas $out/share/gsettings-schemas/${name}/glib-2.0/schemas
Schemas are customarily compiled in `postInstall` phase.

2018-01-12 20:28 UTC, jtojnar commented
I updated the package to 2.0.2. There were some build issues that needed patching (https://github.com/jangernert/FeedReader/issues/593, https://github.com/jangernert/FeedReader/issues/410) and also a runtime issue of missing `org.gnome.FeedReader.Daemon` dbus service. We could create a NixOS module for that but it was removed on master so we would probably better wait for a next version.

2018-02-25 09:31 UTC, jluttine commented
I tested this branch now. I added `services.dbus.packages = with pkgs; [ gnome3.dconf ];` as suggested. When I launch FeedReader, it looks like this:

![image](https://user-images.githubusercontent.com/2195834/36639928-186cf774-1a1f-11e8-94fa-1bd34cd9773e.png)

Just plain empty window, nothing to do.

This is what shows up in the terminal:

```
$ feedreader
[ INFO  ] Everything is logged. Used to debug!
[ INFO  ] FeedReader 2.0.2
[ DEBUG ] MainWindow: setupCSS
[ DEBUG ] ContentPage: setup FeedList
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] UpdateButton: update status
[ DEBUG ] UpdateButton: setSensitive true
[ DEBUG ] MainWindow: determining state
[ DEBUG ] Opening Database: /home/jluttine/.local/share/feedreader/data/feedreader-04.db
[ ERROR ] dbErrorLog: 283: recovered 22 frames from WAL file /home/jluttine/.local/share/feedreader/data/feedreader-04.db-wal
[ DEBUG ] database already initialized
[ DEBUG ] SELECT count(*) FROM main.articles
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.categories
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.feeds
[ DEBUG ] count 0
[ DEBUG ] SELECT count(*) FROM main.tags
[ DEBUG ] count 0
[ DEBUG ] MainWindow: show login
[ DEBUG ] MainWindow: show error bar - errorCode = 8
[ DEBUG ] MainWindow: dont show error bar
[ DEBUG ] HeaderBar: setButtonsSensitive false
[ DEBUG ] UpdateButton: setSensitive false
[ DEBUG ] DBusConnection: setOffline
[ DEBUG ] FeedList: new FeedList
[ DEBUG ] initCollapseCategories
[ DEBUG ] FeedList: restore selected row: 
[ DEBUG ] FeedList: restoreSelectedRow: no selected row found, selectin default
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList
[ DEBUG ] ContentPage: new Feed selected
[ DEBUG ] HeaderBar: showArticleButtons true
[ DEBUG ] ContentPage.newArticleList

(feedreader:3233): dconf-WARNING **: failed to commit changes to dconf: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name ca.desrt.dconf was not provided by any .service files
```

2018-02-25 12:00 UTC, jtojnar commented
@jluttine Actually, I think the dconf needs to be in `systemPackages`. Not sure why `services.dbus.packages` is not working.

2018-02-25 12:17 UTC, jluttine commented
Thanks, however the window still looks the same. Empty.

2018-03-06 09:48 UTC, edwtjo commented
@jtojnar I'm not following, what important NixOS module was removed?

2018-03-06 10:38 UTC, jtojnar commented
@edwtjo not NixOS module, the FeedReader service was removed: https://github.com/jangernert/FeedReader/pull/560

2018-05-22 23:53 UTC, jtojnar commented
Updated and cleaned up the package, it should be good to go.

2018-05-22 23:53 UTC, jtojnar approved these changes

2018-05-23 01:17 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.26090&attempt_id=2c9ff1db-4f15-4f01-8456-1377f1c122b3)

Attempted: feedreader

<details><summary>Partial log (click to expand)</summary><p>

```
cannot build derivation '/nix/store/0v52gfmcssizvg75ykm37ll335gir2ij-gst-plugins-bad-1.14.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/lr1691944p5f5qins2vq03c6nzrnsz75-hook.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/bvj3yvhiqjpz4xwbqnpjz6qk1dga19bw-icon-naming-utils-0.8.90.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/d7pljd0ldk2zzprlmixhgc6invf20d53-adwaita-icon-theme-3.28.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/bsh3smym4a5a9qp5p6wqb0205sq4lj17-geoclue-2.4.7.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/slpjr07jmvn16z5jsps14zbcvpiavc09-libpeas-1.22.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/smzf06jwqrh8nx81634vs03id25xzs28-webkitgtk-2.20.2.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/yaq79zw3n1840mpvffk21wjbybxvkqwr-gnome-online-accounts-3.28.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/pc4fwf7js2g1s930g8p4j25jsfmjb1fh-FeedReader-2.2.drv': 4 dependencies couldn't be built
error: build of '/nix/store/pc4fwf7js2g1s930g8p4j25jsfmjb1fh-FeedReader-2.2.drv' failed
```
</p></details>

2018-05-23 01:38 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.26090&attempt_id=c9ea8923-aea3-4f74-8b62-9a2ab9fc050c)

Attempted: feedreader

<details><summary>Partial log (click to expand)</summary><p>

```
  CC       src/systemd/src/basic/libsystemd_nm_la-io-util.lo
  CC       src/systemd/src/basic/libsystemd_nm_la-mempool.lo
building of '/nix/store/ix61k6cjbyiink6h8g5lj7gdzrh3cmg5-network-manager-1.10.6.drv' timed out after 3600 seconds
cannot build derivation '/nix/store/9bhjkrblgnx98wjrpfv6px9cfdsgpzpv-libproxy-0.4.15.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/akjabf7nyv33bvpv8r3d9lrxcgp4d96z-glib-networking-2.56.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/hl5906g3vvmpzmwplc1yli6pj4mds08b-geoclue-2.4.7.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/l5izkdan7pals84rkl1d2g5yjps0fwjx-webkitgtk-2.20.2.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/7aib3lv4zrxkvxcdm502nl7lxr28dc0w-gnome-online-accounts-3.28.0.drv': 3 dependencies couldn't be built
cannot build derivation '/nix/store/lrp0s0jyhlvk2l8pgwhn9i14qgdzc5f0-FeedReader-2.2.drv': 4 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/lrp0s0jyhlvk2l8pgwhn9i14qgdzc5f0-FeedReader-2.2.drv' failed
```
</p></details>

2018-05-23 17:34 UTC, merged