scantailor-universal: init at 0.2.14
NixOS/nixpkgs pull request #260983
Opened 2023-10-14 03:19 UTC by unclamped

## Description of changes
Adds [scantailor-universal](https://github.com/trufanov-nok/scantailor-universal), a fork based on Enhanced+Featured+Master versions of ScanTailor to the pkgs

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] For non-Linux: Is `sandbox = true` set in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-15 12:54 UTC, azahi requested changes
Welcome to Nixpkgs. We use 2 spaces for indentation, so please fix that. Please also format the module inputs section like it's done in other packages, i.e. `, mkDerivation` (comma comes first). If you are looking for a formatting tool, you can use [nixpkgs-fmt](https://github.com/nix-community/nixpkgs-fmt).

2023-10-15 12:54 UTC, azahi commented on pkgs/applications/graphics/scantailor/universal.nix
> +      license = licenses.gpl3;
https://discourse.nixos.org/t/lib-licenses-gpl3-co-are-now-deprecated/8206

2023-10-15 12:54 UTC, azahi commented on pkgs/applications/graphics/scantailor/universal.nix
> +      sha256 = "sha256-n8NbokK+U0FAuYXtjRJcxlI1XAmI4hk5zV3sF86hB/s=";
```suggestion
      hash = "sha256-n8NbokK+U0FAuYXtjRJcxlI1XAmI4hk5zV3sF86hB/s=";
```

2023-10-15 19:31 UTC, unclamped commented
> We use 2 spaces for indentation, so please fix that.
Dangit! I was 100% sure I had fixed that. My bad.

As for the rest of the changes, do I fix each thing in its own commit or do I just end up squashing them all into the original commit? Also, do I mark you as a co-author of the changes or not?

2023-10-15 19:42 UTC, azahi commented
> As for the rest of the changes, do I fix each thing in its own commit or do I just end up squashing them all into the original commit? 

Yes, it's the preferred way, unless you need to split up a big PR.

> Also, do I mark you as a co-author of the changes or not?

No, that's not necessary.

2023-10-15 22:41 UTC, azahi requested changes

2023-10-15 22:41 UTC, azahi commented on pkgs/applications/graphics/scantailor/universal.nix
This file is still incorrectly formatted.

2023-10-15 22:41 UTC, azahi commented on pkgs/applications/graphics/scantailor/universal.nix
> +, libcanberra }:
```suggestion
, libcanberra 
}:
```

2023-10-16 00:24 UTC, unclamped commented on pkgs/applications/graphics/scantailor/universal.nix
> +, libcanberra }:
:smiling_face_with_tear:

2023-10-16 00:48 UTC, unclamped commented
alright I actually used the formatting tool this time, thought I wouldn't need it because I thought that was the only change left to do, oops

2023-10-16 09:22 UTC, azahi requested changes

2023-10-16 09:22 UTC, azahi commented on pkgs/applications/graphics/scantailor/universal.nix
> +    platforms = platforms.unix;
Almost there. Only one nitpick left.

```suggestion
    platforms = platforms.unix;
    mainProgram = "scantailor-universal-cli";
```

2023-10-16 22:49 UTC, unclamped commented
![image](https://github.com/NixOS/nixpkgs/assets/104658278/f7e0461c-0b91-4363-b994-64f37ca8eef4)
should be all good

2023-10-16 23:24 UTC, azahi commented
Result of `nixpkgs-review pr 260983` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>scantailor-universal</li>
  </ul>
</details>

2023-10-16 23:24 UTC, azahi approved these changes

2023-10-16 23:25 UTC, merged