steam: Added extraEmulators option to chroot env.
NixOS/nixpkgs pull request #26190
Opened 2017-05-28 18:15 UTC by izuk

###### Motivation for this change

I like to use steam to run all my games, including ones that work through dosbox.  This lets me include dosbox in the chroot environment, by doing this in config.nix:

`steam = pkgs.steam.override {  extraEmulators = [ pkgs.dosbox ]; };`

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [X] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-30 07:01 UTC, FRidh commented
why `extraEmulators`? You can add any package here, so it would make more sense to say `extraPkgs`. But then you have to be more specific and say (e.g. with a comment) where those extra packages are added to.

2017-05-30 21:59 UTC, izuk commented
`extraPkgs` is fine.  Can you point me to an example of the kind of comment you mean?

2017-06-01 16:36 UTC, izuk commented
*ping*

2017-06-02 15:03 UTC, abbradar commented
@FRidh to be honest I also didn't fully get what you meant by this comment -- perhaps to mention somewhere about existence of this option?

2017-06-02 15:15 UTC, FRidh commented
An `extraPkgs` option would add extra packages...but where? Looking at buildFHSUserEnv there's targetPkgs and multiPkgs. In this case, `extraPkgs` will be added to both so it is less relevant.

2017-06-02 15:16 UTC, abbradar commented
@FRidh Ah, got it! I think we can either make two arguments (`extraPkgs` + `extraMultiPkgs`) or leave one and add them to `targetPkgs` (with a comment then).

2017-06-02 16:59 UTC, izuk commented
PTAL; I've changed it to extraPkgs and added a comment.

2017-06-02 17:01 UTC, abbradar requested changes

2017-06-02 17:01 UTC, abbradar commented on pkgs/games/steam/chrootenv.nix
> +, extraPkgs ? [ ] # extra packages to add to targetPkgs and multiPkgs
Please make this a function:

`extraPkgs ? pkgs: []`

Also, they actually would be added only to `targetPkgs`.

2017-06-02 17:01 UTC, abbradar commented on pkgs/games/steam/chrootenv.nix
> +      ++ extraPkgs;
And here pass `pkgs` to the function: `extraPkgs pkgs`.

This way you will use the same package set `buildFHSEnv` passes to the function above.

2017-06-02 17:15 UTC, izuk commented on pkgs/games/steam/chrootenv.nix
> +, extraPkgs ? [ ] # extra packages to add to targetPkgs and multiPkgs
Done (I think).

2017-06-02 17:19 UTC, merged

2017-06-02 17:19 UTC, abbradar commented
Thanks and sorry for taking a long time!

2017-06-02 17:20 UTC, izuk commented
No problem.  Now I can get back to playing Tie Fighter.