calibre: fix RPATH
NixOS/nixpkgs pull request #26201
Opened 2017-05-29 05:24 UTC by calvertvl

###### Motivation for this change

Resolve build failure reported in #26140 .

###### Things done

- [X] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] Linux
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-05-29 05:27 UTC, calvertvl commented
Is there a good place to document the debugging process for these RPATH errors? I've put my notes on the process here: https://gist.github.com/calvertvl/010af38ba1512332fd4543470b086a73

2017-05-29 06:43 UTC, FRidh commented
@calvertvl it might fit on the new wiki

2017-05-29 06:45 UTC, FRidh requested changes

2017-05-29 06:45 UTC, FRidh commented on pkgs/applications/misc/calibre/default.nix
> +    for entry in $out/lib/calibre/calibre/plugins/*.so; do
can you add a comment explaining why you're doing this and refer from there to this issue

2017-05-29 12:49 UTC, mdorman commented
I appreciate the work you've done, but my own, parallel investigation leads me to believe this is a symptom of a deeper failure.  I say this because it seems to me that those files should all have had their RPATH entries cleaned already. Looking at the output of the build:

Given a build that errors out with:
```
[q[pchecking for references to /tmp/nix-build-calibre-2.84.0.drv-0 in /nix/store/660jkyw5nx05pdlb2jipplahrsdsyzkh-calibre-2.84.0...
RPATH of binary /nix/store/660jkyw5nx05pdlb2jipplahrsdsyzkh-calibre-2.84.0/lib/calibre/calibre/plugins/libheadless.so contains a forbidden reference to /tmp/nix-build-calibre-2.84.0.drv-0
```
If you search for libheadless.so elsewhere in the build log, you should find:
```
[q[ppost-installation fixup
[pshrinking RPATHs of ELF executables and libraries in /nix/store/660jkyw5nx05pdlb2jipplahrsdsyzkh-calibre-2.84.0
shrinking /nix/store/660jkyw5nx05pdlb2jipplahrsdsyzkh-calibre-2.84.0/lib/calibre/calibre/plugins/libheadless.so
```
That is, supposedly their RPATH entries have already been scrubbed.

So it seems to me that the right answer is, instead of adding special-cased code to the build for this particular package, to figure out why that first pass isn't being effective?

2017-05-29 13:04 UTC, dezgeg commented
It would be solved by having https://github.com/NixOS/patchelf/commit/48143414941d91016efca2b0ef6f32475d6eaa75 in a patchelf release, which still hasn't happened.

2017-05-29 13:04 UTC, mdorman commented
I appreciate the work you've done, but my own, parallel investigation leads me to believe this is a symptom of a deeper failure.  I say this because it seems to me that those files should all have had their RPATH entries cleaned already. Looking at the output of the build:

Given a build that errors out with:
```
[q[pchecking for references to /tmp/nix-build-calibre-2.84.0.drv-0 in /nix/store/660jkyw5nx05pdlb2jipplahrsdsyzkh-calibre-2.84.0...
RPATH of binary /nix/store/660jkyw5nx05pdlb2jipplahrsdsyzkh-calibre-2.84.0/lib/calibre/calibre/plugins/libheadless.so contains a forbidden reference to /tmp/nix-build-calibre-2.84.0.drv-0
```
If you search for libheadless.so elsewhere in the build log, you should find:
```
[q[ppost-installation fixup
[pshrinking RPATHs of ELF executables and libraries in /nix/store/660jkyw5nx05pdlb2jipplahrsdsyzkh-calibre-2.84.0
shrinking /nix/store/660jkyw5nx05pdlb2jipplahrsdsyzkh-calibre-2.84.0/lib/calibre/calibre/plugins/libheadless.so
```
That is, supposedly their RPATH entries have already been scrubbed.

So it seems to me that the right answer is, instead of adding special-cased code to the build for this particular package, to figure out why that first pass isn't being effective?

2017-05-29 14:21 UTC, calvertvl commented
@mdorman: note that --shrink-rpath only removes rpaths where needed dependencies are not found. It does not scrub rpaths as such.

In this case, --shrink-rpath is ineffective because one or more of the libraries it's looking for is still available at the /tmp path.

Also note that @dezgeg's comment indicates that the next patchelf release will resolve the issue, which would allow this to be done properly tree-wide.

2017-05-29 14:27 UTC, mdorman commented
#26209 is an alternative approach that is more analogous to the fixes used elsewhere in the tree (see, for instance, cbdcc20e77).

2017-05-29 20:08 UTC, vcunat commented
Hmm, yes, this particular PR may actually introduce runtime dependencies where only build-time deps are necessary.  I didn't check if it happens, but even if it doesn't it might silently happen in future.  The other PR seems safer to me, at least in this respect.

2017-05-30 06:57 UTC, calvertvl commented
I will admit that this solution is perhaps a bit of overkill; the other PR is less so, though it could result in another RPATH error in the future (and this one would not, at least not due to RPATHs in /tmp).

@vcunat, can you confirm that I understand the patchelf behavior correctly (as described below)? If I am correct, your concern doesn't seem to apply unless there is a bug in patchelf.

The patchelf command added to the installPhase by this PR doesn't change the needed libraries, only the RPATHs to check for them, so if any of the paths has none of the needed libraries, they would be stripped during the fixup phase when `patchelf --shrink-rpath` is run (patchelf manpage: --shrink-rpath only keeps needed libraries).

As such, the only way I can see that a build-time dependency could be added as a runtime dependency is if both had the same RPATH...which effectively means that even the other PR would have this behavior, as a needed dependency would already be present at that path in any case.

It is entirely possible for a specific library to only need a subset of the build inputs at runtime, but again the unnecessary remaining paths would be removed from the full set generated from the build inputs, unless I am somehow misinterpreting the patchelf manpage or it is materially wrong in this regard.

2017-05-30 07:22 UTC, vcunat commented
Ah, right, I didn't realize there would (still) be the other patchelf running *afterwards*.

So the only remaining risk I can see is if calibre linked to library from some other path, though that doesn't seem too likely.  Well, *both* PRs seem OK to me :-)

2017-05-30 15:05 UTC, calvertvl commented
I know I saw the method used in this PR for packages provided as binary, and it's pretty much the only way to make those work. 

For a package that is built by nix, I'm not sure what makes more sense.

The question is, which one is better for a built package? I think uniformity of implementation is the better choice, but I'm not familiar with enough packages where such a step is necessary to be able to say what that means.

2017-06-05 05:16 UTC, closed without merging