openra: Add release- prefix to version string
NixOS/nixpkgs pull request #262324
Opened 2023-10-20 15:54 UTC by mikatammi

Change version string to have prefix `release-`. This fixes "Server is running an incompatible version.", when trying to play against official builds of the OpenRA.

## Description of changes

openra: Add release- prefix to version string

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`): Tested basic multiplayer functionality against OpenRA running on macOS
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-20 16:07 UTC, mikatammi commented
Note: I tested this on top of the 20231010 version

2023-10-20 19:21 UTC, mdarocha requested changes

2023-10-20 19:25 UTC, mikatammi commented on pkgs/games/openra/build-engine.nix
> +    make VERSION=release-${version} version
What would be a good way to check it?

2023-10-20 19:27 UTC, mikatammi commented on pkgs/games/openra/build-engine.nix
> +    make VERSION=release-${version} version
Maybe we can just use ${engine.build} ?

2023-10-20 20:11 UTC, mikatammi commented on pkgs/games/openra/build-engine.nix
> +    make VERSION=release-${version} version
Changed to `${engine.build}-${version}`

2023-10-21 07:52 UTC, mdarocha approved these changes

2023-10-21 13:20 UTC, merged