gh-ost: init at 1.0.36
NixOS/nixpkgs pull request #26313
Opened 2017-06-01 22:16 UTC by polynomial

###### Motivation for this change

The gh-ost utility can be used to manipulate MySQL databases and we would like to use it on our NixOS machines.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-06-02 15:27 UTC, FRidh requested changes
Aside from exceptional cases we build from source in Nixpkgs.

2017-06-02 19:58 UTC, polynomial commented
@FRidh thanks for the feedback, I changed the approach and re-tested. Please let me know if there is anything else.

2017-06-02 21:26 UTC, Mic92 commented on pkgs/tools/misc/gh-ost/default.nix
> +        platforms = platforms.linux;
Do you want to maintain this package?

2017-06-02 21:49 UTC, polynomial commented on pkgs/tools/misc/gh-ost/default.nix
> +        platforms = platforms.linux;
Sure, although I felt weird adding myself as a maintainer with such minimal work done! (: I am fine either way.

2017-06-02 22:24 UTC, volth commented on pkgs/tools/misc/gh-ost/default.nix
> +    let attrs' = builtins.removeAttrs attrs ["version" "sha256"]; in
is ```attrs'``` always empty ?

2017-06-03 01:48 UTC, grahamc commented on pkgs/tools/misc/gh-ost/default.nix
> +  gh-ost = generic {
I think this format of `gh-ost = generic ...` business is quite complex, when we're only likely to package one version of `gh-ost` at a time. Can you simplify to only provide one, remove the generic complexity?

2017-06-08 22:09 UTC, polynomial commented on pkgs/tools/misc/gh-ost/default.nix
> +  gh-ost = generic {
Thanks for the feedback and sorry for the delay. I will remove!

2017-06-08 22:10 UTC, polynomial commented
Updated per feedback and re-tested on NixOS. Thanks.

2017-06-08 23:05 UTC, volth commented on pkgs/tools/misc/gh-ost/default.nix
> +  });
round brackets look needless

2017-06-08 23:05 UTC, volth commented on pkgs/tools/misc/gh-ost/default.nix
> +      inherit sha256;
why inherit, not a direct value here?

2017-06-08 23:05 UTC, volth commented on pkgs/tools/misc/gh-ost/default.nix
> +    inherit goPackagePath;
why inherit, not a direct value here?

2017-08-13 21:11 UTC, merged