fishnet: 2.5.1 -> 2.7.1
NixOS/nixpkgs pull request #263247
Opened 2023-10-24 23:39 UTC by dmytrokyrychuk

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-24 23:46 UTC, dmytrokyrychuk commented
Builds and runs with `doCheck = false`. Otherwise fails because `Stockfish/src/${nnueFile}` somehow disappears from the source directory during the build (it's still there after `postPatch`), which causes [`make net`](https://github.com/official-stockfish/Stockfish/blob/0024133b08777b578c1036eb1e4a36343b7fa1bb/src/Makefile#L932-L937) to fail trying to download the file.

2023-10-25 20:28 UTC, dmytrokyrychuk commented
I added a line to copy the nnue file again after the build so that the checks that happen next don't fail.

@tu-maurice can please review this?

2023-10-26 16:20 UTC, icewind1991 commented
Note that whatever caused fishnet to be marked as only supporting x86_64 doesn't seem to be an issue anymore, everything is working fine on on aarch64-linux.

So the platforms limitation can probably be removed.

2023-10-26 16:21 UTC, icewind1991 approved these changes
All works as expected

2023-10-26 19:08 UTC, dmytrokyrychuk commented
I found the autoPatchelfHook issue at #113930. Since autoPatchelfHook is no longer used, I will remove the platform restriction.

2023-10-27 15:59 UTC, dmytrokyrychuk commented
The package is actually [not building ](https://github.com/NixOS/nixpkgs/pull/263247/checks?check_run_id=18101130236) on darwin, I will limit the platforms to aarch64-linux and x86_64-linux

2023-10-28 05:47 UTC, tu-maurice requested changes

2023-10-28 05:47 UTC, tu-maurice commented on pkgs/servers/fishnet/default.nix
> +    platforms = [ "aarch64-linux" "x6_64-linux" ];
Should be x86_64

2023-10-28 11:19 UTC, dmytrokyrychuk commented on pkgs/servers/fishnet/default.nix
> +    platforms = [ "aarch64-linux" "x6_64-linux" ];
Good catch!

2023-10-29 18:58 UTC, tu-maurice approved these changes
Looks good to me. Ran it a few hours witohut issue.

2023-10-31 14:03 UTC, merged