python3Packages.simplicial: init at 1.0.1
NixOS/nixpkgs pull request #263448
Opened 2023-10-25 22:07 UTC by zmberber

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-25 22:11 UTC, pinpox approved these changes

2023-10-26 10:20 UTC, mweinelt requested changes

2023-10-26 10:20 UTC, mweinelt commented on pkgs/development/python-modules/simplicial/default.nix
> +    pytestCheckHook
The `wheel` package is unnecessary here, as it is provided by the build-backend.

The `pytestCheckHook` needs to go into `nativeCheckinputs`. Please create that list below `pythonImportsCheck`.

2023-10-26 10:20 UTC, mweinelt commented on pkgs/development/python-modules/simplicial/default.nix
> +    homepage = "git@github.com:simoninireland/simplicial.git";
```suggestion
    homepage = "https://github.com/simoninireland/simplicial";
```

Homepage links should be something people can navigate to.

2023-10-26 10:20 UTC, mweinelt commented on pkgs/development/python-modules/simplicial/default.nix
> +  meta = with lib; {
```suggestion
  meta = with lib; {
    changelog = "https://github.com/simoninireland/simplicial/blob/v${version}/HISTORY";
```

Setting up a pattern for the changelog URL allows tools to automatically pick that up on updates.

2023-10-26 10:20 UTC, mweinelt commented on pkgs/development/python-modules/simplicial/default.nix
> +    maintainers = with maintainers; [ ];
As discussed we require maintainers for newly submitted packages. Please create your maintainer handle in a separate commit before this one, but still in this PR.

2024-03-21 10:30 UTC, closed without merging