talosctl: ping golang
NixOS/nixpkgs pull request #264136
Opened 2023-10-29 09:22 UTC by kirillrdy

## Description of changes

fixes https://github.com/NixOS/nixpkgs/issues/264127

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-10-29 09:38 UTC, flokli requested changes
`nix-build -A talosctl` builds for me on nixpkgs master (7484c3dd1ad8c29f4ad3c120c3f356f8e60b45ff), and the commit right before this PR (e00ef8492703d682133f630815ba566e8f72010d) - so this doesn't seem to fix anything.

2023-10-29 09:51 UTC, kirillrdy commented
@flokli indeed you are right !

2023-11-03 20:13 UTC, kirillrdy commented
looks like what we failed to do last time is check vendored modules

with go 1.21 modules content is not "stable"

nix-build -A talosctl.goModules --check

2023-11-03 20:14 UTC, flokli commented on pkgs/top-level/all-packages.nix
> +  talosctl = callPackage ../applications/networking/cluster/talosctl { buildGoModule =  buildGo120Module; };
Can you add this to a separate line?

2023-11-03 20:17 UTC, kirillrdy commented on pkgs/top-level/all-packages.nix
> +  talosctl = callPackage ../applications/networking/cluster/talosctl { buildGoModule =  buildGo120Module; };
done

2023-11-03 21:36 UTC, flokli approved these changes

2023-11-03 21:37 UTC, merged