blockbench: Make compatible with NIXOS_OZONE_WL
NixOS/nixpkgs pull request #264654
Opened 2023-10-31 19:18 UTC by IogaMaster

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-02 03:25 UTC, eclairevoyant requested changes

2023-11-02 03:25 UTC, eclairevoyant commented on pkgs/applications/graphics/blockbench-electron/default.nix
> +      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--enable-features=UseOzonePlatform --ozone-platform=wayland}}" \
```suggestion
      --add-flags "\''${NIXOS_OZONE_WL:+\''${WAYLAND_DISPLAY:+--ozone-platform-hint=auto --enable-features=WaylandWindowDecorations}}" \
```

2023-11-02 05:08 UTC, ckiee commented
Out of scope for me since I don't use wayland currently.

2023-11-02 15:33 UTC, IogaMaster commented
s have someone else that can test for me

2023-11-02 15:38 UTC, ckiee commented
You can go ahead and apply&rebase @eclairevoyant's review, it seems to be the current consensus on what flags to pass[^1]. I'll test on a nested sway once we're there.

[^1]: [arch wiki](https://wiki.archlinux.org/title/Wayland#Command_line_flags) and it's more popular in nixpkgs.

2023-11-02 16:40 UTC, IogaMaster commented
I though so, I copied from another package that used this instead

2024-03-16 07:41 UTC, TomaSajt commented
Superseded by https://github.com/NixOS/nixpkgs/pull/279795

2024-03-16 07:41 UTC, closed without merging