toggl: init at 7.4.45
NixOS/nixpkgs pull request #26510
Opened 2017-06-10 22:51 UTC by spinus

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-06-10 22:52 UTC, spinus commented
It does not compile, I'm not sure what's missing. Maybe somebody with qt exp could take a look?

2017-06-10 23:52 UTC, volth commented on pkgs/misc/toggl/default.nix
> +}
please add ```meta``` with program's description and website

2017-06-11 00:12 UTC, spinus commented on pkgs/misc/toggl/default.nix
> +}
If I manage to compile it sure I will :-)

2017-06-11 11:48 UTC, Mic92 commented
This does not seem qt related, but it seems to ship its own openssl library

```
cp: cannot stat 'third_party/openssl/*so*': No such file or directory
```

2017-06-11 14:23 UTC, spinus commented
@Mic92 thanks for checking, LnL took a look and helped me identify some issues yesterday, I fixed some stuff, but still need to fix few.

2017-06-30 20:31 UTC, joachifm commented on pkgs/misc/toggl/default.nix
> +  name = "toggl";
The name should contain a version string.

2017-06-30 20:32 UTC, joachifm commented on pkgs/misc/toggl/default.nix
> +    command -v perl
What does this accomplish?

2017-07-01 14:01 UTC, spinus commented on pkgs/misc/toggl/default.nix
> +    command -v perl
It checks if perl is available

2017-07-01 14:02 UTC, spinus commented on pkgs/misc/toggl/default.nix
> +  name = "toggl";
Thanks, I'll fix this.
but it's still non working package...

2017-07-03 07:32 UTC, Mic92 commented on pkgs/misc/toggl/default.nix
> +    command -v perl
But why is this necessary? It is clearly passed as in buildInputs.

2017-07-04 23:23 UTC, spinus commented on pkgs/misc/toggl/default.nix
> +    command -v perl
it's probably not, I had an issue when build mechanism wanted perl  but couldn't find that, so I added this line to make sure it's there. I'll def remove that before merge, after this is "buildable".

2018-09-08 22:34 UTC, ryantm requested changes
Please add the version to the name and delete unnecessary perl check.

2018-09-08 23:44 UTC, yegortimoshenko commented
Also see https://github.com/NixOS/nixpkgs/blob/93f5e20ef5cfe382ef8f3c38a691144f12a32b1d/pkgs/applications/misc/toggldesktop/default.nix.

2018-09-09 09:43 UTC, spinus commented
@yegortimoshenko thanks, closing.

2018-09-09 09:43 UTC, closed without merging