python311Packages.line-profiler: 4.0.2 -> 4.1.2; rename from line_profiler
NixOS/nixpkgs pull request #265256
Opened 2023-11-03 16:10 UTC by natsukium

## Description of changes

part of #245383 

Changelog: https://github.com/pyutils/line_profiler/blob/v4.1.2/CHANGELOG.rst

and add two dependencies
- python311Packages.xdoctest: init at 1.1.2
  - https://github.com/Erotemic/xdoctest
- python311Packages.ubelt: init at 1.3.4
  - https://github.com/Erotemic/ubelt

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-03 16:17 UTC, natsukium commented
Result of `nixpkgs-review pr 265256` at 67bb6d90 run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>6 packages built successfully:</summary>
  <ul>
    <li>python310Packages.line-profiler</li>
    <li>python310Packages.ubelt</li>
    <li>python310Packages.xdoctest</li>
    <li>python311Packages.line-profiler</li>
    <li>python311Packages.ubelt</li>
    <li>python311Packages.xdoctest</li>
  </ul>
</details>

2023-11-10 10:58 UTC, mweinelt requested changes

2023-11-10 10:58 UTC, mweinelt commented on pkgs/development/python-modules/ubelt/default.nix
> +    rev = "refs/tagsv${version}";
```suggestion
    rev = "refs/tags/v${version}";
```

2023-11-10 12:42 UTC, mweinelt commented
Result of `nixpkgs-review pr 265256` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>12 packages built:</summary>
  <ul>
    <li>python310Packages.line-profiler</li>
    <li>python310Packages.line-profiler.dist</li>
    <li>python310Packages.ubelt</li>
    <li>python310Packages.ubelt.dist</li>
    <li>python310Packages.xdoctest</li>
    <li>python310Packages.xdoctest.dist</li>
    <li>python311Packages.line-profiler</li>
    <li>python311Packages.line-profiler.dist</li>
    <li>python311Packages.ubelt</li>
    <li>python311Packages.ubelt.dist</li>
    <li>python311Packages.xdoctest</li>
    <li>python311Packages.xdoctest.dist</li>
  </ul>
</details>

2023-11-10 12:43 UTC, mweinelt approved these changes

2023-11-11 18:40 UTC, merged