feather: init at 2.5.2
NixOS/nixpkgs pull request #265694
Opened 2023-11-05 17:14 UTC by surfaceflinger

## Description of changes

Added a package for [Feather Wallet](https://featherwallet.org/). Based on #186382 which seems stale now.

Wayland required fixing by setting QT_PLUGIN_PATH and QT_QPA_PLATFORM_PLUGIN_PATH.

 - [x] Works with my Ledger
 - [x] Tested with my own Monero node
 - [x] Tested embedded TOR and connected to a remote onion node
 - [x] Made a churn transaction

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-06 01:14 UTC, OPNA2608 requested changes
I don't have a Monero wallet, so I cannot confirm full functionality, but the GUI launches on x86_64-linux X11 & aarch64-linux Wayland. Some suggestions.

2023-11-06 09:55 UTC, OPNA2608 commented on pkgs/by-name/fe/feather/package.nix
> +  ];
Build is now done. Adding `qtwayland` to `buildInputs` and removing these seems to work well enough under Miriway. Can you confirm this under whatever setup you're using?

2023-11-06 11:24 UTC, surfaceflinger commented on pkgs/by-name/fe/feather/package.nix
> +  ];
oh, weird, didn't work for me as far as I remember, I'll check again after work today

2023-11-08 11:41 UTC, OPNA2608 approved these changes
Result of `nixpkgs-review pr 265694` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>feather</li>
  </ul>
</details>

---

Some things I wouldn't say are worth blocking over, but perhaps still good to mention / talk about.

CMake says there are disabled tests which could be enabled, but [upstream says](https://github.com/feather-wallet/feather/blob/135f1987c9548372a111c276962ac1a67ddc00c7/MAINTENANCE.md)

> Feather does not currently have a test suite (apart from the tests in the Monero submodule), this is a WIP.

…so not sure if enabling them makes sense, or how much effort it would take to get them working.

2023-11-08 20:44 UTC, surfaceflinger commented on pkgs/by-name/fe/feather/package.nix
> +
That's so cool, thanks

2023-11-09 07:59 UTC, OPNA2608 approved these changes
Stuck on the weak ARM hardware so can't test building, but OfBorg is fine & the version test runs so LGTM!

2023-11-10 00:24 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1217

2023-11-22 14:59 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1245

2023-11-22 16:09 UTC, pbsds commented
Result of `nixpkgs-review pr 265694` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>feather</li>
  </ul>
</details>

- [x] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package builds on x86_64-linux
- [x] executables tested on x86_64-linux
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.platforms` is set
- [x] `meta.maintainers` is set
- [x] build time only dependencies are declared in `nativeBuildInputs`
- [x] source is fetched using the appropriate function
- [x] the list of `phases` is not overridden
- [x] when a phase (like `installPhase`) is overridden it starts with `runHook preInstall` and ends with `runHook postInstall`.
- [x] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [x] patches that are remotely available are fetched rather than vendored

LGTM, thanks!

2023-11-22 16:09 UTC, merged