boot/activation: move /run/booted-system creation into actiovation sc…
NixOS/nixpkgs pull request #265866
Opened 2023-11-06 15:27 UTC by SuperSandro2000

…ript

to be easily accessible for different boot style systems like NixOS-WSL. Since the creation is earlier as before this should be save with no regressions.

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-06 16:19 UTC, roberth requested changes
Easier perhaps, but less precise. How bad is the alternative?

2023-12-10 01:56 UTC, SuperSandro2000 commented
I don't have an idea for alternatives tbh.

2023-12-10 03:00 UTC, roberth commented
The best alternative is to keep it as is.
Setting the symlink is a responsibility of stage 2, and not the activation script.
WSL is a stage 2, among other things, so it must implement this.
I suppose you could refactor stage 2 into a library + program?

2023-12-10 04:09 UTC, SuperSandro2000 commented
> Setting the symlink is a responsibility of stage 2, and not the activation script.

Why though? Shouldn't we do as much as late as possible to have the full environment already?

---

Yeah, having some library around those things would allow us to activate what we need without needing to copy paste things.

2024-07-09 14:09 UTC, closed without merging