guetzli: init at  1.0.1
NixOS/nixpkgs pull request #26595
Opened 2017-06-15 11:58 UTC by seppeljordan

###### Motivation for this change
It would be nice to have guetzli inside nixpkgs

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"` *does not apply*
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-06-15 13:09 UTC, pSub requested changes

2017-06-15 13:09 UTC, pSub commented on pkgs/applications/graphics/guetzli/default.nix
> +  buildInputs = [ libpng pkgconfig ];
`pkgconfig` is a `nativeBuildInput`.

2017-06-15 13:09 UTC, pSub commented on pkgs/applications/graphics/guetzli/default.nix
> +  src = fetchgit {
Please use `fetchFromGitHub` like so, if it is possible to get rid of `fetchSubmodules = true`:
`src = fetchFromGitHub {
  owner = "google";
  repo = "guetzli";
  rev = "v${version}"
  sha256 = "…";
}`

To be able to do that, you have to declare `version` separately and make the attribute set recursive.

2017-06-15 13:53 UTC, seppeljordan commented
@pSub done

2017-07-02 11:00 UTC, 0xABAB approved these changes

2017-07-02 11:01 UTC, merged