ufetch: init at 0.3
NixOS/nixpkgs pull request #266274
Opened 2023-11-08 13:48 UTC by mrtnvgr

## Description of changes

This PR adds [ufetch](https://gitlab.com/jschx/ufetch) to nixpkgs

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-12-11 20:18 UTC, Mindavi commented on pkgs/by-name/uf/ufetch/package.nix
> +    mainProgram = pname;
```suggestion
    mainProgram = "ufetch";
```

2023-12-11 20:21 UTC, Mindavi commented
I tried this package out and it seems to run for quite a while. Afterwards this is the output:

```
[nix-shell:~/.cache/nixpkgs-review/pr-266274]$ time ./results/ufetch/bin/ufetch 
./results/ufetch/bin/ufetch: line 12: /nix/store/zx8aqgdy735qzk81glfwil6mbi6ddqb1-coreutils-9.4/bin/ls: Argument list too long

    \\   \\ //    user@nixos-asus
   ==\\___\\/ //  OS:        24.05.20231201.91050ea (Uakari)
     //    \\//   KERNEL:    Linux 6.6.3
  ==//      //==  UPTIME:    4 days 23:21
   //\\____//     PACKAGES:  0
  // /\\   \\==   SHELL:     bash
    // \\   \\    DE:        KDE

real    0m2.972s
user    0m1.299s
sys     0m1.309s
```

(Seems like there's some caching since the first run was a lot slower than subsequent runs)

2023-12-11 20:25 UTC, Mindavi commented
For fun, I tried to find a better command. This command may work better than `ls /nix/store/*`: `find /nix/store/ -maxdepth 1 -type d | wc -l`. Output for me is: `74041` (which isn't really the amount of packages anyway, but at least the command is equivalent)

2024-01-02 02:24 UTC, jschx commented
Hi, I'm the author of ufetch. Here's my attempt at a fix:

```
#!/bin/sh

for profile in $NIX_PROFILES; do
  if [ -d "$profile" ]; then
    packages="$((packages + $(nix-store -q --requisites "$profile" | wc -l)))"
  fi
done

echo "$packages"
```

Try it out and see if it matches your expectations. If it looks good, I can make the change and tag a new release.

2024-11-18 12:17 UTC, FliegendeWurst requested changes

2024-11-18 12:17 UTC, FliegendeWurst commented on pkgs/by-name/uf/ufetch/package.nix
> +{ stdenvNoCC, fetchFromGitLab, lib }:
Please format with the new formatter.

2024-11-18 12:17 UTC, FliegendeWurst commented on pkgs/by-name/uf/ufetch/package.nix
> +    maintainers = with maintainers; [ mrtnvgr ];
```suggestion
  meta = {
    description = "Tiny system info for Unix-like operating systems";
    homepage = "https://gitlab.com/jschx/ufetch";
    license = lib.licenses.mit;
    platforms = lib.platforms.linux;
    mainProgram = "ufetch";
    maintainers = with lib.maintainers; [ mrtnvgr ];
```

2024-11-18 15:03 UTC, phanirithvij commented
@jschx it is possible that [`guix`](https://search.nixos.org/options?channel=unstable&show=services.guix.enable) nixos module could be enabled, and that adds a few paths to $NIX_PROFILES

```shell
echo $NIX_PROFILES
/run/current-system/sw /nix/var/nix/profiles/default /etc/profiles/per-user/rithvij /home/rithvij/.local/state/nix/profile /nix/profile /home/rithvij/.nix-profile
/home/rithvij/.guix-profile /home/rithvij/.guix-home/profile /guix/current
```

so I get this error

```bash
for profile in $NIX_PROFILES; do
  if [ -d "$profile" ]; then
    packages="$((packages + $(nix-store -q --requisites "$profile" | wc -l)))"
...

error: path '/gnu/store/92m08pzpcfsilkv2mrs7cdwc8v67y8qv-profile' is not in the Nix store
```

2024-11-21 09:32 UTC, FliegendeWurst commented on pkgs/by-name/uf/ufetch/package.nix
> +    install -Dm755 ufetch-nixos $out/bin/ufetch
I think it would be good to install the other variants too. nixpkgs can also be used on other distros.

2024-11-21 14:21 UTC, phanirithvij commented
`packages="$((packages + $( (nix-store -q --requisites "$profile" 2>/dev/null || printf '') | wc -l)))"`
Should fix the issue about guix I raised above.

2024-11-23 05:46 UTC, phanirithvij approved these changes
```console
$ nix build github:nixos/nixpkgs/refs/pull/266274/merge#ufetch --no-link --print-out-paths
/nix/store/b0s1y3li207i9qnm6ayl06xkh479ljpw-ufetch-0.3
$ time nix run github:nixos/nixpkgs/refs/pull/266274/merge#ufetch

    \\   \\ //    rithvij@iron
   ==\\___\\/ //  OS:        25.05pre-git (Warbler)
     //    \\//   KERNEL:    Linux 6.6.62
  ==//      //==  UPTIME:    3:54
   //\\____//     PACKAGES:  3340
  // /\\   \\==   SHELL:     bash
    // \\   \\    DE:        KDE


real    0m0.576s
user    0m0.251s
sys     0m0.105s

# alpine-distrobox
$  /nix/store/b0s1y3li207i9qnm6ayl06xkh479ljpw-ufetch-0.3/bin/ufetch-alpine

        /\            rithvij@iron
       /  \           OS:        Alpine Linux
      / /\ \  /\      KERNEL:    Linux 6.6.62
     / /  \ \/  \     UPTIME:    3:57
    / /    \ \/\ \    PACKAGES:  383
   / / /|   \ \ \ \   SHELL:     bash
  /_/ /_|    \_\ \_\  DE:        KDE

# arch-distrobox
$ /nix/store/b0s1y3li207i9qnm6ayl06xkh479ljpw-ufetch-0.3/bin/ufetch-arch

        /\         rithvij@iron
       /  \        OS:        Arch Linux
      /\   \       KERNEL:    Linux 6.6.62
     /  __  \      UPTIME:    3 hours, 58 minutes
    /  (  )  \     PACKAGES:  230
   / __|  |__\\    SHELL:     bash
  /.`        `.\   DE:        KDE

$ gh pr checkout 266274
$ nix-build -E 'with import <nixpkgs> {}; let p = callPackage ./pkgs/by-name/uf/ufetch/package.nix {}; in p.override { osName = "arch"; full = false; }'
/nix/store/iv3sw1i7md8c78zvz0nvsbppapdxbdrf-ufetch-0.3

# arch-distrobox
$ /nix/store/iv3sw1i7md8c78zvz0nvsbppapdxbdrf-ufetch-0.3/bin/ufetch

        /\         rithvij@iron
       /  \        OS:        Arch Linux
      /\   \       KERNEL:    Linux 6.6.62
     /  __  \      UPTIME:    4 hours, 15 minutes
    /  (  )  \     PACKAGES:  230
   / __|  |__\\    SHELL:     bash
  /.`        `.\   DE:        KDE

```

I cheated using distrobox but it should be no different from the real distros.

2024-11-23 11:22 UTC, Mindavi approved these changes

2024-11-23 11:24 UTC, FliegendeWurst approved these changes

2024-11-23 18:46 UTC, JohnRTitor approved these changes

2024-11-23 18:47 UTC, JohnRTitor commented on pkgs/by-name/uf/ufetch/0001-optimize-packages-command.patch
CC @jschx

2024-11-23 18:48 UTC, JohnRTitor commented
@ofborg build ufetch

2024-11-23 19:22 UTC, jschx commented
Merged the patch and tagged v0.4. Thanks everyone, this is really neat! :)

2024-11-23 19:37 UTC, phanirithvij commented on pkgs/by-name/uf/ufetch/0001-optimize-packages-command.patch
So a minor oopsie I made here, `printf ''` or `true` doesn't matter really, initially I had `printf ''` and later changed it to true.
Since a tag has been made, let's live with printf, the command output is the same no matter what.

```console
$ true | wc -l
0
$ printf '' | wc -l
0
```

2024-11-23 19:45 UTC, phanirithvij commented on pkgs/by-name/uf/ufetch/0001-optimize-packages-command.patch
@mrtnvgr you can do https://gist.github.com/phanirithvij/1884eb1d3817be4b8fd00c434eee0bbf for 0.4 (just for convinience, you may ignore this)

not able to use github to suggest changes, the ui is behaving oddly.

2024-11-23 21:34 UTC, merged

2024-11-23 21:34 UTC, Mindavi commented
Let's not block this any further

2024-11-24 03:34 UTC, phanirithvij commented
#358611