nixos/plasma5: enable dconf by default
NixOS/nixpkgs pull request #266234
Opened 2023-11-08 09:53 UTC by SuperSamus

## Description of changes

Many applications expect for `dconf`  to be enabled.

Example of issue caused by missing `dconf`: https://github.com/NixOS/nixpkgs/issues/226766#issuecomment-1512845210

This option is enabled by default on basically every desktop environment, even on minimalistic WMs such as Sway.

(Reprise of #196017)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-16 09:56 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/2927

2023-11-16 23:32 UTC, SuperSandro2000 requested changes

2023-11-16 23:32 UTC, SuperSandro2000 commented on nixos/modules/services/x11/desktop-managers/plasma5.nix
> +      programs.dconf.enable = true;
yes, some programs like paprefs require this to work

2023-11-16 23:32 UTC, SuperSandro2000 commented on nixos/modules/services/x11/desktop-managers/plasma5.nix
> +      services.gnome.glib-networking.enable = true;
I think every program that is not working without this is missing something in its wrapper.

2023-11-17 10:49 UTC, SuperSamus commented
Removed the `glib-networking` change. It's only `dconf` now.

2023-11-17 21:24 UTC, SuperSandro2000 approved these changes

2023-12-04 21:23 UTC, merged