maintainers-list.nix: Document (current) invitation process, add get-maintainer.sh
NixOS/nixpkgs pull request #267084
Opened 2023-11-12 17:36 UTC by nbraud

## Description of changes

- Add `maintainers/scripts/get-maintainer.sh` to query `maintainers-list.nix`
  It supports querying by exact match against a maintainer's handle or any of the documented attributes of `maintainers.${handle}`.

- Document the [RFC 39] invitation process to [nixpkgs-maintainers] as it stands now.

- ~~Add new `reinvite-maintainers.yml` workflow, which:~~
  - triggers on comments on #234293, from non-bot users, that contain “invite me” ;
  - checks whether the GitHub user is present in `maintainers-list.nix` (taken from branch `master`) ;
  - invites the user to the [nixpkgs-maintainers] team, created by [RFC 39] ;
  - replies (if successful) to the user, informing them they were invited to the team.

[nixpkgs-maintainers]: https://github.com/orgs/NixOS/teams/nixpkgs-maintainers
[RFC 39]: https://github.com/NixOS/rfcs/blob/master/rfcs/0039-unprivileged-maintainer-teams.md#summary

## Things done

- Tested `get-maintainer.nix`
  - [x] all selectors work, on both existing maintainers and negative queries ;
  - [x] the script always exits with a non-zero exit code when no match was found.
  The latter allows the workflow to more-easily check whether a match exists.

- ~~`reinvite-maintainers.yml` isn't tested yet~~
  I guess the only way to do so would be to test it on a dummy org?

2023-11-15 09:02 UTC, zimbatm reviewed
Great initiative and the workflow makes sense. The logic will probably need to be moved to the bot that invites maintainers due to the security restrictions of GHA.

2023-11-15 21:06 UTC, infinisil commented
I feel like there's a good chance for this to become out of sync or slightly different from the RFC 39 implementation that does the initial invites.

A self-serve page does sound a lot easier though. If that exists we could have some very simple automation that posts a comment in PRs adding to the `maintainer-list.nix`, telling people to visit the page to get invited. This way we wouldn't need the continuously-running service anymore.

A small worry is that this wouldn't conform with RFC 39 anymore, which [specified how the automation should be done](https://github.com/NixOS/rfcs/blob/master/rfcs/0039-unprivileged-maintainer-teams.md#team-automation). So to do this right it should be another RFC to override the old one. Probably not a bad idea tbh, makes sure we don't miss anything. It would be entirely uncontroversial though, so I think this could be very quick.

If you're up for the task, I think this would be great to have, a PoC along with an RFC.

2023-11-16 17:12 UTC, zimbatm commented
@nbraud deploying an app seems better indeed. This will allow us to direct people to maintainers.nixos.org (or bikeshed later) to check their status and add themselves. The app would also either have to re-implement, or re-use the code of RFC39 so it doesn't get out of sync. If you're up for it then let's go.

2023-11-23 16:12 UTC, mkg20001 commented on maintainers/scripts/get-maintainer.sh
> +    die "usage: '$0' [selector] value"
maybe an example would be good

2023-11-29 11:58 UTC, mkg20001 approved these changes

2023-12-03 00:21 UTC, infinisil requested changes

2023-12-05 18:22 UTC, infinisil requested changes

2023-12-05 18:22 UTC, infinisil commented on maintainers/scripts/README.md
> +`get-maintainer.sh [selector] [value]` returns a JSON object describing
```suggestion
`get-maintainer.sh [selector] value` returns a JSON object describing
```

`value` is not optional

2023-12-05 18:22 UTC, infinisil commented on maintainers/scripts/README.md
> +
An example would be really helpful here, once with the default and once with another selector

2023-12-05 18:22 UTC, infinisil commented on maintainers/scripts/README.md
> +### `get-maintainer.sh`
Something this is missing is the motivation for why we need this. Can you describe the use case for this script here?

2023-12-06 22:25 UTC, infinisil commented on maintainers/scripts/README.md
> +### `get-maintainer.sh`
Still good to write this down, but I just had a need for this script myself! Had to find out what the GitHub handle of somebody on Matrix was :D

2023-12-06 22:27 UTC, infinisil commented on maintainers/scripts/README.md
> +and supporting data or nixlang files as needed.
```suggestion
This folder contains various executable scripts for nixpkgs maintainers,
and supporting data or nixlang files as needed.
These scripts generally aren't a stable interface and may changed or be removed.
```

I think generally files in the source shouldn't be relied upon, so just emphasising this here.

2023-12-07 16:05 UTC, infinisil commented on maintainers/scripts/README.md
> +`get-maintainer.sh [selector] [value]` returns a JSON object describing
Oh I'm just suggesting to not have the `[]` brackets. That usually indicates optional fields in the CLI, whereas if you don't have them it indicates a required field.

2023-12-07 16:07 UTC, infinisil commented on maintainers/scripts/README.md
> +### `get-maintainer.sh`
Ah yeah you're right, but yes that text would be great to add!

2023-12-08 01:55 UTC, infinisil approved these changes
Awesome, this is looking great! I'm really glad we got some docs going for the maintainer scripts :heart:

2023-12-08 01:57 UTC, merged