flask-restplus: update to 0.10
NixOS/nixpkgs pull request #26714
Opened 2017-06-19 15:01 UTC by siddharthist

###### Motivation for this change
Tested and working

###### Things done

- [x] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-06-22 05:30 UTC, FRidh requested changes

2017-06-22 05:30 UTC, FRidh commented on pkgs/development/python-modules/flask-restplus/default.nix
> +  propagatedBuildInputs = [ flask six jsonschema pytz aniso8601 flask-restful ];
you added itself to `propagatedBuildInputs`

2017-06-23 16:57 UTC, siddharthist commented on pkgs/development/python-modules/flask-restplus/default.nix
> +  propagatedBuildInputs = [ flask six jsonschema pytz aniso8601 flask-restful ];
Ah, what a ridiculous mistake! Thanks for the catch.

2017-06-23 17:08 UTC, siddharthist commented on pkgs/development/python-modules/flask-restplus/default.nix
> +  propagatedBuildInputs = [ flask six jsonschema pytz aniso8601 flask-restful ];
Wait, I don't think I did. You may be referring to `flask-restful`? These are different projects:
 * https://github.com/flask-restful/flask-restful
 * https://github.com/noirbizarre/flask-restplus

2017-06-23 17:18 UTC, FRidh commented on pkgs/development/python-modules/flask-restplus/default.nix
> +  propagatedBuildInputs = [ flask six jsonschema pytz aniso8601 flask-restful ];
AHH, indeed, my bad.

2017-06-23 17:19 UTC, merged