martin: 0.9.1 → 0.10.0
NixOS/nixpkgs pull request #267315
Opened 2023-11-13 22:20 UTC by sikmir

## Description of changes
[Changelog](https://github.com/maplibre/martin/releases)

## Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-14 07:52 UTC, imincik commented
That's a very interesting tool. I didn't know about it. Thanks for packaging !

2023-11-19 08:13 UTC, sikmir commented
`protoc` binary needs to be patched or replaced with one from nixpkgs:
```
failed to spawn command `"/build/martin-0.10.0-vendor.tar.gz/protoc-bin-vendored-linux-aarch_64/bin/protoc"
```

2023-12-09 19:59 UTC, sikmir commented
@nixos/rust Could you advise a proper way to fix it?

2023-12-09 20:03 UTC, winterqt commented
Either patch martin to not use this crate, or symlink our binaries (from `buildPackages`) into the respective directories.

2023-12-09 21:32 UTC, sikmir commented
> Either patch these binaries, patch martin to not use this crate, or symlink our binaries (from `buildPackages`) into the respective directories.

I've tried to patch the binary or symlink to nixpkgs `protoc`, but I've got:
```sh
martin> error: the listed checksum of `/build/martin-0.11.3-vendor.tar.gz/protoc-bin-vendored-linux-x86_64/bin/protoc` has changed:
martin> expected: 239cd7cc1888c8855bc2a7ed571d4af3cb9d255fde86b78c1fc1cdabf9248c14
martin> actual:   636f4f115e97302cda39133d3714414ea41cfd5c415d9da2c060e080fd3e8775
martin> directory sources are not intended to be edited, if modifications are required then it is recommended that `[patch]` is used with a forked copy of the source
```
`cargoHash` remained the same.

2024-06-25 22:08 UTC, das-g requested changes
That's inconsistent.

2024-06-25 22:08 UTC, das-g commented on pkgs/servers/geospatial/martin/default.nix
> +  version = "0.14.0";
Commit message of d687067b807b1c78d21f7bed0d0c9db5a52404b2 indicates version `0.13.0`, but title of this draft PR and content of d687067b807b1c78d21f7bed0d0c9db5a52404b2 both indicate `0.14.0`.

2024-06-27 16:14 UTC, imincik commented
Is this PR still draft ?

2024-06-27 17:32 UTC, sikmir commented
> Is this PR still a draft ?

`protoc` binary needs to be patched or replaced with one from nixpkgs:
```
failed to spawn command `"/build/martin-0.10.0-vendor.tar.gz/protoc-bin-vendored-linux-aarch_64/bin/protoc"
```

I still don't know how to do it.

2025-07-28 08:18 UTC, sikmir commented
Looks like there is no problem with protoc after latest update.

2025-11-19 08:20 UTC, sikmir commented
[1.0.0](https://github.com/maplibre/martin/releases/tag/martin-v1.0.0) is out!

2026-03-01 14:59 UTC, sikmir commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 267315`
Commit: `24e8227d880c2e69509fc26ec4769b0111589477`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>martin</li>
    <li>nixpkgs-manual</li>
  </ul>
</details>

2026-03-07 13:44 UTC, imincik commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review-gha`](https://github.com/Defelo/nixpkgs-review-gha)

Command: `nixpkgs-review pr 267315`
Commit: [`ba62e6b273c1c0b1dafd2f9c10ab3ac2ee69d202`](https://github.com/NixOS/nixpkgs/commit/ba62e6b273c1c0b1dafd2f9c10ab3ac2ee69d202) ([subsequent changes](https://github.com/NixOS/nixpkgs/compare/ba62e6b273c1c0b1dafd2f9c10ab3ac2ee69d202..pull/267315/head))
Merge: [`4dbbbcc15166af628db927931cef7a9cb9517103`](https://github.com/NixOS/nixpkgs/commit/4dbbbcc15166af628db927931cef7a9cb9517103)

Logs: https://github.com/imincik/nixpkgs-review-gha/actions/runs/22799707536

<details><summary>Download packages from cache:</summary><ul>
<li><details><summary><code>x86_64-linux</code></summary>

```shell
nix-store -r --add-root nixpkgs-pr-267315-x86_64-linux \
  --option binary-caches 'https://cache.nixos.org/ https://imincik-nixpkgs-review-gha.cachix.org' \
  --option trusted-public-keys '
  cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  imincik-nixpkgs-review-gha.cachix.org-1:vbkvABMrxmQ+ObRDwmF2qaLIEhGHdbF4MwXtOPU8Jmk=
  ' \
  /nix/store/fqlnimhvpi2zd99cg2y2c8yqjhqbrmw9-martin-1.3.1
```
</details></li>
<li><details><summary><code>aarch64-linux</code></summary>

```shell
nix-store -r --add-root nixpkgs-pr-267315-aarch64-linux \
  --option binary-caches 'https://cache.nixos.org/ https://imincik-nixpkgs-review-gha.cachix.org' \
  --option trusted-public-keys '
  cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  imincik-nixpkgs-review-gha.cachix.org-1:vbkvABMrxmQ+ObRDwmF2qaLIEhGHdbF4MwXtOPU8Jmk=
  ' \
  /nix/store/k6sgbgcwzbfd9c7x4g0c1ka6hifhwf2m-martin-1.3.1
```
</details></li>
<li><details><summary><code>x86_64-darwin</code></summary>

```shell
nix-store -r --add-root nixpkgs-pr-267315-x86_64-darwin \
  --option binary-caches 'https://cache.nixos.org/ https://imincik-nixpkgs-review-gha.cachix.org' \
  --option trusted-public-keys '
  cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  imincik-nixpkgs-review-gha.cachix.org-1:vbkvABMrxmQ+ObRDwmF2qaLIEhGHdbF4MwXtOPU8Jmk=
  ' \
  /nix/store/migjb43c3pb3iskz5ag9gw05l4vhq8ry-martin-1.3.1
```
</details></li>
<li><details><summary><code>aarch64-darwin</code></summary>

```shell
nix-store -r --add-root nixpkgs-pr-267315-aarch64-darwin \
  --option binary-caches 'https://cache.nixos.org/ https://imincik-nixpkgs-review-gha.cachix.org' \
  --option trusted-public-keys '
  cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
  imincik-nixpkgs-review-gha.cachix.org-1:vbkvABMrxmQ+ObRDwmF2qaLIEhGHdbF4MwXtOPU8Jmk=
  ' \
  /nix/store/l8bpym3rw53ib1l3dnbfazimqw17yhq8-martin-1.3.1
```
</details></li>
</ul></details>


---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>martin</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>martin</li>
  </ul>
</details>

---
### `x86_64-darwin` (sandbox = relaxed)
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>martin</li>
  </ul>
</details>

---
### `aarch64-darwin` (sandbox = relaxed)
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>martin</li>
  </ul>
</details>

2026-03-15 15:57 UTC, Mic92 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 267315`
Commit: `e27430dc30fec1697c3a28890256cd8d88ff0f63`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>martin</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>martin</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>martin</li>
  </ul>
</details>

2026-03-15 16:03 UTC, merged