s3proxy: init
NixOS/nixpkgs pull request #267421
Opened 2023-11-14 10:27 UTC by camelpunch

## Description of changes

S3Proxy allows you to access various storage backends using the AWS S3 API. It's very useful for nix users who want to use non-S3-compatible blobstores as a binary cache.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-25 09:02 UTC, camelpunch commented
Looks like the Ofborg failure was due to lack of disk space. Is there a way to re-run?

2024-02-17 17:21 UTC, DataHearth commented
@camelpunch Hey! Before a reviewer comes by, your commits doesn't match the [commit convention](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) :slightly_smiling_face: . You should squash them to get a single commit `s3proxy: init at 2.1.0` :+1:

2024-02-17 17:31 UTC, DataHearth requested changes

2024-02-17 17:31 UTC, DataHearth commented on pkgs/by-name/s3/s3proxy/package.nix
> +    inherit hash;
```suggestion
}:
maven.buildMavenPackage {
  pname = "s3proxy";
  version = "2.1.0";
  mvnHash = "sha256-85mE/pZ0DXkzOKvTAqBXGatAt8gc4VPRCxmEyIlyVGI=";

  src = fetchFromGitHub {
    hash = "sha256-GhZPvo8wlXInHwg8rSmpwMMkZVw5SMpnZyKqFUYLbrE=";
```

2024-02-17 17:31 UTC, DataHearth commented on pkgs/by-name/s3/s3proxy/package.nix
> +    inherit hash;
I don't think defining `version`, `mvnHash` and  `hash` as parameter is a good way to define your package. The standard way I can think is merge everything inside the `buildMavenPackage` scope and set the `hash` inside the `fetchFromGithub` :+1: .

2024-02-17 17:31 UTC, DataHearth commented on pkgs/by-name/s3/s3proxy/package.nix
> +  };
```suggestion
  meta = with lib; {
    description = "Access other storage backends via the S3 API";
    homepage = "https://github.com/gaul/s3proxy";
    changelog = "https://github.com/gaul/s3proxy/releases/tag/s3proxy-${version}";
    license = licenses.asl20;
    maintainers = with maintainers; [ camelpunch ];
  };
```

2024-02-17 20:51 UTC, camelpunch commented
Thanks for the feedback @DataHearth !

2024-02-22 22:06 UTC, camelpunch commented
Thanks @SuperSandro2000. I've applied your suggestions, and fixed up the result. It makes sense to not 'pun' the `pname` - it's coincidental naming if the executable has the same name etc.

2024-02-22 23:51 UTC, merged