tree-wide: mark rpm dependents broken on darwin
NixOS/nixpkgs pull request #268572
Opened 2023-11-19 20:24 UTC by katexochen

Support by rpm for darwin got removed in https://github.com/NixOS/nixpkgs/pull/196350.

This will be fixed once apple_sdk > 13.0 is available and we can check for that version.

Not sure if I got every package that (transitively) depends on rpm. Is there any good way to check this?

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-20 13:23 UTC, reckenrode approved these changes
Looks good from a Darwin perspective.

2023-11-20 16:14 UTC, malt3 approved these changes

2023-11-20 16:19 UTC, msanft approved these changes

2023-11-20 17:49 UTC, vcunat requested changes, later dismissed
Can we explain why this is even needed?  AFAIK it's acting transitively
```
$ nix eval -f. --argstr system x86_64-darwin apkg.outPath
error: Package ‘rpm-4.18.1’ in pkgs/tools/package-management/rpm/default.nix:72 is not available on the requested hostPlatform:
```

2023-11-20 17:57 UTC, katexochen commented
Maybe I understood things wrong. I'm trying to fix these evaluation errors thrown by hydra:
https://hydra.nixos.org/jobset/nixpkgs/trunk#tabs-errors
```
in job ‘libmodulemd.x86_64-darwin’:
error:
       … while calling the 'deepSeq' builtin

         at /nix/store/0555ml133awcl3gyl5v0lh93hbp3nngh-source/lib/customisation.nix:288:7:

          287|     in if drv == null then null else
          288|       lib.deepSeq drv' drv';
             |       ^
          289|

       … while evaluating the attribute 'outPath'

         at /nix/store/0555ml133awcl3gyl5v0lh93hbp3nngh-source/lib/customisation.nix:277:13:

          276|           value = commonAttrs // {
          277|             outPath = output.outPath;
             |             ^
          278|             drvPath = output.drvPath;

       (stack trace truncated; use '--show-trace' to show the full trace)

       error: Failed to evaluate rpm-4.18.1: «unsupported»: is not available on the requested hostPlatform:
         hostPlatform.config = "x86_64-apple-darwin"
         package.meta.platforms = [
           "aarch64-linux"
           "armv5tel-linux"
           "armv6l-linux"
           "armv7a-linux"
           "armv7l-linux"
           "i686-linux"
           "loongarch64-linux"
           "m68k-linux"
           "microblaze-linux"
           "microblazeel-linux"
           "mips-linux"
           "mips64-linux"
           "mips64el-linux"
           "mipsel-linux"
           "powerpc64-linux"
           "powerpc64le-linux"
           "riscv32-linux"
           "riscv64-linux"
           "s390-linux"
           "s390x-linux"
           "x86_64-linux"
         ]
         package.meta.badPlatforms = [ ]
```

2023-11-20 18:04 UTC, vcunat commented
Right, the amount of eval warnings is a long-standing problem.  I don't know off the top of my head what's the best approach here.  Maybe this PR really is the best one.

2023-11-20 19:10 UTC, Artturin commented
This is incorrect, set `badPlatforms` in rpm to make it and it's dependants not show up on hydra https://ryantm.github.io/nixpkgs/stdenv/meta/#var-meta-badPlatforms

2023-11-21 07:45 UTC, katexochen commented
> This is incorrect, the proper way seems to be setting `badPlatforms` in rpm to make it and it's dependants not show up on hydra https://ryantm.github.io/nixpkgs/stdenv/meta/#var-meta-badPlatforms

Thanks @Artturin, this looks like the thing I want to do. Do I also need to add darwin back under `platforms` when setting `badPlatforms = platforms.darwin;` ?

2023-11-21 08:06 UTC, vcunat commented
I think you should not add it.

2023-11-24 12:27 UTC, Artturin commented
There should be a comment about when darwin can be readded

2023-11-24 20:30 UTC, merged

2023-11-24 20:32 UTC, Artturin commented
Let's see if it works but we should not do this for each individual package which isn't supported on some platform.

2023-11-24 22:09 UTC, katexochen commented
> Let's see if it works but we should not do this for each individual package which isn't supported on some platform. Instead, the root issue should be fixed.

So what is/was the root cause in your opinion?

2023-11-28 09:50 UTC, katexochen commented
Seems like the fix didn't work, the evaluation errors are still there: https://hydra.nixos.org/eval/1802300#tabs-errors

2024-06-04 20:23 UTC, rb2k commented
It's been a while and I'm vaguely sorry to necromance this PR, but I am just doing some digging into what it would take to get microdnf to compile again and this is probably one of the best places for people to find this information :)

Upstream can be built on darwin again in 4.19.1.1:
https://github.com/rpm-software-management/rpm/issues/2807

So if this gets upgraded, this might be build-able again. Maybe I can convince some of my colleagues to take a look.

2024-06-09 23:52 UTC, reckenrode commented
It’s possible, but it may also still require a newer SDK than is available currently in nixpkgs. I’m going to be working on a refactor and update for 24.11, but that’s not ready (or started) yet.