multipass: fix submodule fetching
NixOS/nixpkgs pull request #268557
Opened 2023-11-19 19:09 UTC by dawidd6

## Description of changes

`mulitpass` currently fails to build from source: https://hydra.nixos.org/build/241500327

Relevant portion of log:
```
error: Server does not allow request for unadvertised object 090e6a054d6283b144d20f5783852b95eade90ee
fatal: Fetched in submodule path '3rd-party/xz-decoder/xz-embedded', but it did not contain 090e6a054d6283b144d20f5783852b95eade90ee. Direct fetching of that commit failed.
error: Server does not allow request for unadvertised object 090e6a054d6283b144d20f5783852b95eade90ee
fatal: Fetched in submodule path '3rd-party/xz-decoder/xz-embedded', but it did not contain 090e6a054d6283b144d20f5783852b95eade90ee. Direct fetching of that commit failed.
```

Setting `leaveDotGit` fixes this and what it basically does is removing `--depth 1` flag passed to `git`, so instead of `git submodule update --init --recursive --progress --depth 1` (producing above error), we do `git submodule update --init --recursive --progress` (success).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-19 22:35 UTC, dawidd6 commented
I don't know what's happening, each build hydra reports different hash for the source. This does not seem to happen for me locally.

2023-11-20 07:14 UTC, jnsgruk commented
Yeh I don't think using `leaveDotGit` is going to work, but you might be able to fetch the sub module upfront and sub it in (similar to how the grpc sub module is bought in)?

2023-11-20 09:04 UTC, jnsgruk commented
Hmm, okay I see that won't work either. I was taking a look around at some similar issues earlier and came up with the following that seems to work:

https://github.com/NixOS/nixpkgs/compare/master...jnsgruk:nixpkgs:fix-multipass-build-submodule-fail

@RaitoBezarius does that seem like a reasonable workaround?

2023-11-20 09:20 UTC, dawidd6 commented
> Hmm, okay I see that won't work either. I was taking a look around at some similar issues earlier and came up with the following that seems to work:
> 
> [master...jnsgruk:nixpkgs:fix-multipass-build-submodule-fail](https://github.com/NixOS/nixpkgs/compare/master...jnsgruk:nixpkgs:fix-multipass-build-submodule-fail)

Aaand I've got a different hash trying to build that locally :smile: 

```
error: hash mismatch in fixed-output derivation '/nix/store/n2lr32ky8f25f67jzrxzzx5wp2ip03nm-source.drv':
         specified: sha256-L2B1obutp18HALRDupwTfFig67C/TOOBS8usFmIktsQ=
            got:    sha256-c+RuK0jso+g3EYd/pMk4BEiU7dQ8fI4tSqWjK4biFNs=
error: 1 dependencies of derivation '/nix/store/gb606ni5jclylbla1lsp6bcj7nli93hy-multipass-1.12.2.drv' failed to build
```

2023-11-20 09:30 UTC, jnsgruk commented
Oops, I forgot a `cd $out`. Latest commit here seems to be deterministic for me! https://github.com/NixOS/nixpkgs/commit/2b17b55ef45f441ddae314dbb20d628462801e79

2023-11-20 09:40 UTC, dawidd6 commented
Indeed it works! Thanks for help, I'll update this PR with your commit.

2023-11-20 10:27 UTC, jnsgruk approved these changes
LGTM, thanks!

2023-11-20 10:57 UTC, SuperSandro2000 requested changes
while we are at it we should fix some of the vendoring. We should at least the anno dominion old libssh they are using https://github.com/canonical/multipass/blob/main/.gitmodules#L7C8-L8C1

Same with yaml-cpp. If the one patch they have applied is not upstream yet, we should fetch that instead.

2023-11-20 21:50 UTC, jnsgruk commented
> while we are at it we should fix some of the vendoring. We should at least the anno dominion old libssh they are using https://github.com/canonical/multipass/blob/main/.gitmodules#L7C8-L8C1
> 
> 
> 
> Same with yaml-cpp. If the one patch they have applied is not upstream yet, we should fetch that instead.

What's the best way to go about that, by adding more into the postFetch block?

Perhaps we could follow up with a separate PR? I'm happy to take that on separately if need be, but if you've got a similar example that would be great 😄

2023-11-20 22:19 UTC, merged

2023-11-21 12:58 UTC, SuperSandro2000 commented
> What's the best way to go about that, by adding more into the postFetch block?

If the problem they are fixed is a general problem of the library and fixing a bug we could think about adding it to the package in nixpkgs. Otherwise we could work with overlays or we could decide that the patch is not really required and just drop it.




> Perhaps we could follow up with a separate PR?

sure



> if you've got a similar example that would be great 😄

I don't have on in mind right now.