zfs: 2.2.0 -> 2.2.1; zfsUnstable: 2.2.1-unstable-2023-10-21 -> 2.2.1
NixOS/nixpkgs pull request #269097
Opened 2023-11-22 01:57 UTC by amarshall

## Description of changes

https://github.com/openzfs/zfs/releases/tag/zfs-2.2.1

Notably:

> We recommend that anyone running zfs-2.2.0 to please update to this release. Gentoo users have identified a block cloning bug (https://github.com/openzfs/zfs/issues/15526) that can result in data corruption in zfs-2.2.0. To workaround this, zfs-2.2.1 disables block cloning by default (see https://github.com/openzfs/zfs/pull/15529 and https://github.com/openzfs/zfs/commit/479dca51c66a731e637bd2d4f9bba01a05f9ac9f). Users running the 2.1.x branch or older are unaffected, as block cloning is a 2.2.x-only feature.

## Things done

`nix-build -A zfs.passthru.tests`, and am also running with this patch on x86_64-linux.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2023-11-22 02:54 UTC, adamcstephens requested changes
This release adds support for 6.6 kernels. Please update the versions above.

2023-11-22 07:08 UTC, kirillrdy commented
Result of `nixpkgs-review pr 269097` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages marked as broken and skipped:</summary>
  <ul>
    <li>libvmi</li>
    <li>rubyPackages_2_7.ruby-libvirt</li>
  </ul>
</details>
<details>
  <summary>91 packages built:</summary>
  <ul>
    <li>appvm</li>
    <li>booster</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev (ceph-dev.dev)</li>
    <li>ceph.doc (ceph-dev.doc)</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man (ceph-dev.man)</li>
    <li>check_zfs</li>
    <li>collectd</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>docker-machine-kvm</li>
    <li>docker-machine-kvm2</li>
    <li>easysnap</li>
    <li>gnome.gnome-boxes</li>
    <li>guestfs-tools</li>
    <li>haskellPackages.libvirt-hs</li>
    <li>haskellPackages.libvirt-hs.doc</li>
    <li>libguestfs</li>
    <li>librenms</li>
    <li>libvirt</li>
    <li>libvirt-glib</li>
    <li>libvirt-glib.dev</li>
    <li>libvirt-glib.devdoc</li>
    <li>linuxKernel.packages.linux_4_19.zfs (linuxKernel.packages.linux_4_19.zfsStable)</li>
    <li>linuxPackages_4_19_hardened.zfs (linuxKernel.packages.linux_4_19_hardened.zfs ,linuxPackages_4_19_hardened.zfsStable)</li>
    <li>linuxKernel.packages.linux_5_10.zfs (linuxKernel.packages.linux_5_10.zfsStable)</li>
    <li>linuxPackages_5_10_hardened.zfs (linuxKernel.packages.linux_5_10_hardened.zfs ,linuxPackages_5_10_hardened.zfsStable)</li>
    <li>linuxKernel.packages.linux_5_15.zfs (linuxKernel.packages.linux_5_15.zfsStable)</li>
    <li>linuxPackages_5_15_hardened.zfs (linuxKernel.packages.linux_5_15_hardened.zfs ,linuxPackages_5_15_hardened.zfsStable)</li>
    <li>linuxKernel.packages.linux_5_4.zfs (linuxKernel.packages.linux_5_4.zfsStable)</li>
    <li>linuxPackages_5_4_hardened.zfs (linuxKernel.packages.linux_5_4_hardened.zfs ,linuxPackages_5_4_hardened.zfsStable)</li>
    <li>linuxPackages.zfs (linuxKernel.packages.linux_6_1.zfs ,linuxPackages.zfsStable)</li>
    <li>linuxPackages_hardened.zfs (linuxPackages_6_1_hardened.zfs ,linuxPackages_hardened.zfsStable)</li>
    <li>linuxKernel.packages.linux_6_5.zfs (linuxKernel.packages.linux_6_5.zfsStable)</li>
    <li>linuxPackages_6_5_hardened.zfs (linuxKernel.packages.linux_6_5_hardened.zfs ,linuxPackages_6_5_hardened.zfsStable)</li>
    <li>linuxPackages_latest.zfs (linuxKernel.packages.linux_6_6.zfs ,linuxPackages_latest.zfsStable)</li>
    <li>linuxPackages_latest-libre.zfs (linuxKernel.packages.linux_latest_libre.zfs ,linuxPackages_latest-libre.zfsStable)</li>
    <li>linuxPackages-libre.zfs (linuxKernel.packages.linux_libre.zfs ,linuxPackages-libre.zfsStable)</li>
    <li>linuxPackages_lqx.zfs (linuxKernel.packages.linux_lqx.zfs ,linuxPackages_lqx.zfsStable)</li>
    <li>linuxPackages_testing_bcachefs.zfs (linuxKernel.packages.linux_testing_bcachefs.zfs ,linuxPackages_testing_bcachefs.zfsStable)</li>
    <li>linuxPackages_xanmod.zfs (linuxKernel.packages.linux_xanmod.zfs ,linuxPackages_xanmod.zfsStable)</li>
    <li>linuxPackages_xanmod_latest.zfs (linuxKernel.packages.linux_xanmod_latest.zfs ,linuxPackages_xanmod_latest.zfsStable ,linuxPackages_xanmod_stable.zfs ,linuxPackages_xanmod_stable.zfsStable)</li>
    <li>linuxPackages_zen.zfs (linuxKernel.packages.linux_zen.zfs ,linuxPackages_zen.zfsStable)</li>
    <li>mgmt</li>
    <li>minikube</li>
    <li>minishift</li>
    <li>multipass</li>
    <li>nixops_unstable</li>
    <li>nixops_unstable.dist</li>
    <li>partition-manager</li>
    <li>perl536Packages.SysVirt</li>
    <li>perl536Packages.SysVirt.devdoc</li>
    <li>perl538Packages.SysVirt</li>
    <li>perl538Packages.SysVirt.devdoc</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.guestfs.dist</li>
    <li>python310Packages.libvirt</li>
    <li>python310Packages.libvirt.dist</li>
    <li>python310Packages.py-libzfs</li>
    <li>python310Packages.py-libzfs.dist</li>
    <li>python311Packages.guestfs</li>
    <li>python311Packages.guestfs.dist</li>
    <li>python311Packages.libvirt</li>
    <li>python311Packages.libvirt.dist</li>
    <li>python311Packages.py-libzfs</li>
    <li>python311Packages.py-libzfs.dist</li>
    <li>qemu_full</li>
    <li>qemu_full.debug</li>
    <li>qemu_full.ga</li>
    <li>rubyPackages.ruby-libvirt (rubyPackages_3_1.ruby-libvirt)</li>
    <li>rubyPackages_3_2.ruby-libvirt</li>
    <li>rubyPackages_3_3.ruby-libvirt</li>
    <li>sambaFull (samba4Full)</li>
    <li>sambaFull.dev (samba4Full.dev)</li>
    <li>sambaFull.man (samba4Full.man)</li>
    <li>sanoid</li>
    <li>vagrant</li>
    <li>virt-manager</li>
    <li>virt-manager-qt</li>
    <li>virt-manager.dist</li>
    <li>virt-top</li>
    <li>virt-viewer</li>
    <li>zfs (zfsStable)</li>
    <li>zfs.dev (zfsStable.dev)</li>
    <li>zfstools</li>
    <li>zpool-auto-expand-partitions</li>
    <li>zxfer</li>
  </ul>
</details>

2023-11-22 08:20 UTC, Mic92 commented
We also should bump unstable to the same version: https://github.com/NixOS/nixpkgs/blob/3ac3a21f7918b09440debc526a4a3003d6f9edaa/pkgs/os-specific/linux/zfs/unstable.nix
Otherwise it's actually older than stable.

2023-11-22 08:25 UTC, Mic92 commented
```
From 40e9f366584d143e1b748e95c0b668b4842e7499 Mon Sep 17 00:00:00 2001                                                                
From: =?UTF-8?q?J=C3=B6rg=20Thalheim?= <joerg@thalheim.io>                                                                            
Date: Wed, 22 Nov 2023 09:23:11 +0100                                                                                                 
Subject: [PATCH] zfsUnstable: 2.2.0 -> 2.2.1                                                                                          
MIME-Version: 1.0                                                                                                                     
Content-Type: text/plain; charset=UTF-8                                                                                               
Content-Transfer-Encoding: 8bit                                                                                                       
                                                                                                                                      
Signed-off-by: Jörg Thalheim <joerg@thalheim.io>                                                                                      
---                                                                                                                                   
 pkgs/os-specific/linux/zfs/unstable.nix | 9 ++++-----                                                                                
 1 file changed, 4 insertions(+), 5 deletions(-)

diff --git a/pkgs/os-specific/linux/zfs/unstable.nix b/pkgs/os-specific/linux/zfs/unstable.nix
index 9c7e14c31bf3..18d1ae7f9d17 100644
--- a/pkgs/os-specific/linux/zfs/unstable.nix
+++ b/pkgs/os-specific/linux/zfs/unstable.nix
@@ -12,21 +12,20 @@ in
 callPackage ./generic.nix args {
   # check the release notes for compatible kernels
   kernelCompatible = if stdenv'.isx86_64 || removeLinuxDRM
-    then kernel.kernelOlder "6.6"
+    then kernel.kernelOlder "6.7"
     else kernel.kernelOlder "6.2";
 
   latestCompatibleLinuxPackages = if stdenv'.isx86_64 || removeLinuxDRM
-    then linuxKernel.packages.linux_6_5
+    then linuxKernel.packages.linux_6_6
     else linuxKernel.packages.linux_6_1;
 
   # this package should point to a version / git revision compatible with the latest kernel release
   # IMPORTANT: Always use a tagged release candidate or commits from the
   # zfs-<version>-staging branch, because this is tested by the OpenZFS
   # maintainers.
-  version = "2.2.1-unstable-2023-10-21";
-  rev = "95785196f26e92d82cf4445654ba84e4a9671c57";
+  version = "2.2.1";
 
-  sha256 = "sha256-s1sdXSrLu6uSOmjprbUa4cFsE2Vj7JX5i75e4vRnlvg=";
+  sha256 = "sha256-2Q/Nhp3YKgMCLPNRNBq5r9U4GeuYlWMWAsjsQy3vFW4=";
 
   isUnstable = true;
 }
-- 
2.42.0
```

2023-11-22 13:03 UTC, terinjokes approved these changes

2023-11-22 19:23 UTC, RaitoBezarius commented
Our tests are not passing, can someone look into them?

2023-11-23 06:09 UTC, eadwu commented
Looks like it might be still broken and/or even more broken.
https://github.com/openzfs/zfs/issues/15533

The fix appears to maybe be unrelated to block cloning (module parameter).

2023-11-23 14:36 UTC, Mic92 commented
> `zfs{,unstable}.passthru.tests` pass for me on x86_64-linux, so I cannot replicate the ofborg failure.

Those tests also worked for me yesterday.

2023-11-23 15:12 UTC, eadwu commented
Ah sorry, the tuneable is meant to resolve the data corruption from block cloning (if it is from block cloning) https://github.com/openzfs/zfs/issues/15526#issuecomment-1823737998.

v2.2.1 surfaces another problem (on a specific setup) which does not seem to be related.

2023-11-23 15:32 UTC, RaitoBezarius commented
I opened https://github.com/NixOS/nixpkgs/pull/269452 related to this. If you want to continue maintaining the 2.2.x series, please step up in that PR so I can add you. I am not planning to address the 2.2.x series situation as a maintainer of ZFS as I am effectively removing myself from 2.2.x.

2023-11-25 17:00 UTC, gaykitty commented
FYI https://nvd.nist.gov/vuln/detail/CVE-2023-49298

2023-11-25 17:34 UTC, qubitnano commented
2.2.1 affects users with zfs on LUKS, see https://github.com/openzfs/zfs/issues/15533

Reverting the commit mentioned in https://github.com/openzfs/zfs/issues/15533#issuecomment-1824963319 seems to fix it but only the user who bisected it confirmed it so far.

2023-11-26 01:50 UTC, adamcstephens commented
I'm hesitant to adopt https://github.com/openzfs/zfs/issues/15526 even though this was patch was applied in `zfs_2_1`. While this may be the patch that is accepted, I am not the person to make that decision. As this bug has been around for a long time, and only become more common with recent changes, I propose we instead roll back those recent changes.

My recommendation would be to proceed with 2.2.1, which disables block cloning, and follow Gentoo in patching `zfs_dmu_offset_next_sync=0` back to the default. Their patch is here: https://gitweb.gentoo.org/repo/gentoo.git/tree/sys-fs/zfs-kmod/files/zfs-kmod-2.2.1-Disable-zfs_dmu_offset_next_sync-tunable-by-default.patch

These two should hopefully be enough to calm some fears while upstream has a chance to fix the underlying bug.

2023-11-26 02:01 UTC, adamcstephens approved these changes
At a minimum, I think we need to bump this version to disable block cloning. Then if we want to patch, my thoughts are here: https://github.com/NixOS/nixpkgs/pull/269465#issuecomment-1826466074

2023-11-26 22:55 UTC, adamcstephens approved these changes
I've been running this 2.2.1 since originally opened.

2023-11-26 23:14 UTC, merged