mpvScripts.videoclip: init at unstable-2023-11-01
NixOS/nixpkgs pull request #269272
Opened 2023-11-22 20:08 UTC by ayes-web

## Description of changes

Add [videoclip](https://github.com/Ajatt-Tools/videoclip)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2023-11-23 04:18 UTC, eclairevoyant submitted a review, later dismissed

2023-11-23 04:18 UTC, eclairevoyant commented on pkgs/applications/video/mpv/scripts/videoclip.nix
> +,
```suggestion
```

2023-11-23 04:18 UTC, eclairevoyant commented on pkgs/applications/video/mpv/scripts/videoclip.nix
> +      --replace wl-copy ${lib.getBin wl-clipboard}/bin/wl-copy
```suggestion
      --replace wl-copy ${lib.getExe' wl-clipboard "wl-copy"}
```

2023-11-23 04:18 UTC, eclairevoyant commented on pkgs/applications/video/mpv/scripts/videoclip.nix
> +      --replace wl-copy ${lib.getBin wl-clipboard}/bin/wl-copy
also please keep the pre/post patch hooks

2023-11-23 04:18 UTC, eclairevoyant commented on pkgs/applications/video/mpv/scripts/videoclip.nix
> +    license = licenses.gpl3;
please use a valid identifier (gpl3Only or gpl3Plus as per upstream)

2023-11-23 04:18 UTC, eclairevoyant commented on pkgs/applications/video/mpv/scripts/videoclip.nix
> +    description = "Easily create videoclips with mpv.";
```suggestion
    description = "Easily create videoclips with mpv";
```

never end desc with a period as per nixpkgs manual

2023-11-23 04:18 UTC, eclairevoyant commented on pkgs/applications/video/mpv/scripts/videoclip.nix
> +    maintainers = with maintainers; [ ayes-web ];
are you added to the maintainers list? if not please do so in the first commit, then init this paxkage in the second commit

2024-05-01 10:50 UTC, nicoonoclaste requested changes
Thanks a lot for the contribution!  :purple_heart: 

This could likely be simplified using [`buildLua`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/video/mpv/scripts/buildLua.nix), a build helper in `mpvScripts`

2024-05-01 14:32 UTC, nicoonoclaste approved these changes
Just an errant colon to clean up, which I can do myself  ;3

2024-05-01 14:34 UTC, merged