pureref: download source automatically
NixOS/nixpkgs pull request #270689
Opened 2023-11-28 16:24 UTC by Misterio77

Mentioned in https://github.com/NixOS/nixpkgs/issues/250520

## Description of changes

Download the appimage through a runCommand FOD, instead of requireFile. [Inspired by the AUR package](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=pureref) 

The download form requires a key to download. Just curl the download page, grep it out, and we're good to go.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

### Priorities

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-02-22 19:06 UTC, ElnuDev approved these changes
LGTM sorry for the long delay, I've been busy with uni and didn't manage to get to this until now. Sorry for the delay!

2024-02-24 18:14 UTC, W-Y-R commented
Hello, @Misterio77! Sorry for the ping, but could you please merge this?

2024-02-24 19:06 UTC, Misterio77 commented
Hey @W-Y-R! No prob!

I'm afraid I don't have the commiter bit. So we'll need one to merge this.

2024-03-25 23:39 UTC, ElnuDev commented
Requested review from someone with commit perms on the #pr-review-request channel on [the Discord](https://discord.gg/w8ZK4gdK9a), hopefully we can get this merged soon. Again, sorry for the unresponsiveness earlier.

2024-03-26 00:41 UTC, eclairevoyant requested changes

2024-03-26 00:41 UTC, eclairevoyant commented on pkgs/applications/graphics/pureref/default.nix
> +    outputHash = "05naywdgykqrsgc3xybskr418cyvbx7vqs994yv9w8zf98gxvbvm";
```suggestion
    outputHash = "sha256-da/dH0ruI562JylpvE9f2zMUSJ56+T7Y0xlP/xr3yhY=";
```
using SRI hash (preferred)

2024-03-26 00:41 UTC, eclairevoyant commented on pkgs/applications/graphics/pureref/default.nix
> +    buildInputs = [ curl gnugrep cacert ];
```suggestion
    nativeBuildInputs = [ curl gnugrep cacert ];
```
curl and grep are binaries, and cacert needs to be in `nativeBuildInputs` for the nix setup hook

2024-03-26 12:00 UTC, eclairevoyant approved these changes

2024-03-26 19:10 UTC, ElnuDev approved these changes

2024-03-29 05:02 UTC, merged