Update pulseaudio module
NixOS/nixpkgs pull request #270677
Opened 2023-11-28 15:52 UTC by lgoette

## Description of changes

- Change pulseaudio module to set permission of pulse's home directory to 755 when running in "systemWide" mode
-> The start-script of the pulseaudio daemon changes the permission to 755, but this gets reset on rebuild (with changes not regarding pulseaudio, so the daemon is not restarted)
-> with the `homeMode` option, this gets set to 755 on rebuild

-> Fixes Issue, described in [#114399](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/issues/114399)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [23.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) (or backporting [23.05 Release notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md))
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [x] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-11-29 19:01 UTC, lgoette commented
I know, it sounds weird to give a home directory 755 permissions but this is actually intended by pulseaudio as you can see here:
https://gitlab.freedesktop.org/pulseaudio/pulseaudio/-/blob/master/src/pulsecore/core-util.c#L1759-1783
Pulse sets the permission to 755 when running in system-wide mode and sets it to 700 otherwise.

2023-11-29 22:40 UTC, AndersonTorres requested changes
Reword the commit message:

```
nixos/pulseaudio: set permission of pulse home directory

Closes #114399
```

2023-11-29 22:40 UTC, AndersonTorres commented on nixos/doc/manual/release-notes/rl-2405.section.md
> +  Fixes [Issue#114399](https://github.com/NixOS/nixpkgs/issues/114399).
```suggestion
- The `hardware.pulseaudio` module now sets permission of pulse user home directory to 755 when running in "systemWide" mode. It fixes [issue 114399](https://github.com/NixOS/nixpkgs/issues/114399).
```

2023-11-30 01:35 UTC, AndersonTorres approved these changes

2023-12-01 04:48 UTC, merged