schildichat-{web,desktop}: remove due to lack of maintenance
NixOS/nixpkgs pull request #272270
Opened 2023-12-05 14:27 UTC by yu-re-ka

## Description of changes

Fixes #267618

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2023-12-05 19:06 UTC, Kloenk approved these changes
LGTM, can be added later again if upstream releases new versions

2023-12-06 12:03 UTC, sefidel requested changes
Agree with the decision here, LGTM other than the typo on the aliases file.

2023-12-06 12:09 UTC, sefidel commented
I've closed #267618 as it was a hacky solution with lingering wayland problems.

2023-12-07 10:36 UTC, sivizius commented on pkgs/top-level/aliases.nix
> +  schildichat-desktop = throw "'schildichat-desktop' has been removed as it is unmaintained and does not receive security fixes.\nPlease participate in upstream discussion on getting out new releases
Maybe:

```nix
inherit (lib.genAttrs 
  [ "schildichat-web" "schildichat-desktop" ] 
  (name: throw '''
    '${name}' has been removed as it is unmaintained and does not receive security fixes.
    Please participate in upstream discussion on getting out new releases:
    https://github.com/SchildiChat/schildichat-desktop/issues/212
    https://github.com/SchildiChat/schildichat-desktop/issues/215''')
  ) schildichat-web schildichat-desktop; # Added 2023-12-05
```

or less dirty:

```nix
} // lib.genAttrs 
  [ "schildichat-web" "schildichat-desktop" ] 
  (name: throw '''
    '${name}' has been removed as it is unmaintained and does not receive security fixes.
    Please participate in upstream discussion on getting out new releases:
    https://github.com/SchildiChat/schildichat-desktop/issues/212
    https://github.com/SchildiChat/schildichat-desktop/issues/215''') # Added 2023-12-05
// {

2023-12-07 12:48 UTC, yayayayaka approved these changes
Agree with the decision, LGTM and willing to boop the merge button.

2023-12-07 16:23 UTC, merged

2023-12-10 18:43 UTC, TheArcaneBrony commented
Hi, I just wanted to drop in that SchildiChat works fine if you override the package like this:
```
(
  schildichat-desktop.override {
    electron = pkgs.electron;
  }
)
```

Could this be seen as an alternative solution?

2023-12-11 16:06 UTC, Kloenk commented
> Hi, I just wanted to drop in that SchildiChat works fine if you override the package like this:
> 
> ```
> (
>   schildichat-desktop.override {
>     electron = pkgs.electron;
>   }
> )
> ```
> 
> Could this be seen as an alternative solution?

This would still leave you with `CVE-2023-37259`