treewide: Fix appimageTools breakages, use pname instead of name
NixOS/nixpkgs pull request #273719
Opened 2023-12-12 07:04 UTC by pbsds

## Description of changes

depends on and fixes #271071

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2023-12-23 23:23 UTC, eclairevoyant requested changes
caught a few changes to fix (double checked against the desktop files)

2023-12-23 23:23 UTC, eclairevoyant commented on pkgs/applications/misc/golden-cheetah-bin/default.nix
> -    mv $out/bin/${pname}-${version} $out/bin/GoldenCheetah
```suggestion
    mv $out/bin/${pname} $out/bin/GoldenCheetah
```

2023-12-23 23:23 UTC, eclairevoyant commented on pkgs/applications/science/biology/jbrowse/default.nix
> -    mv $out/bin/jbrowse-${version} $out/bin/jbrowse-desktop
```suggestion
    mv $out/bin/jbrowse $out/bin/jbrowse-desktop
```

2023-12-23 23:23 UTC, eclairevoyant commented on pkgs/applications/video/lbry/default.nix
> -    mv $out/bin/${name} $out/bin/lbry
```suggestion
    mv $out/bin/${pname} $out/bin/lbry
```

2024-01-23 14:04 UTC, jbgi commented
Rebased version of this pr in #283222.

2024-04-21 15:08 UTC, pbsds commented
These fixes has been moved back into https://github.com/NixOS/nixpkgs/pull/271071.

thanks for your review @eclairevoyant, it's been addressed in https://github.com/NixOS/nixpkgs/pull/271071 :)

2024-04-21 15:08 UTC, closed without merging