Backport wamr release 23.11
NixOS/nixpkgs pull request #274072
Opened 2023-12-13 21:25 UTC by ereslibre

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2023-12-14 07:58 UTC, ereslibre commented
Result of `nixpkgs-review pr 274072` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wamr</li>
  </ul>
</details>

2023-12-14 07:59 UTC, ereslibre commented
Result of `nixpkgs-review pr 274072` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wamr</li>
  </ul>
</details>

2023-12-14 07:59 UTC, ereslibre commented
Result of `nixpkgs-review pr 274072` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wamr</li>
  </ul>
</details>

2023-12-20 22:30 UTC, pbsds commented
FYI, adding the label `backport release-23.11` to #273129 would've caused a bot to create this PR for you.

2023-12-20 22:33 UTC, pbsds approved these changes
waiting for ofborg

2023-12-20 22:43 UTC, ereslibre commented
> FYI, adding the label backport release-23.11 to https://github.com/NixOS/nixpkgs/pull/273129 would've caused a bot to create this PR for you. This label can be added after merge

Thanks for the suggestion. Unfortunately in this case, the backport is not clean due to a missing intermediate backport.

2023-12-21 00:08 UTC, pbsds commented
Ah, while diving through the git blame i didn't see that the final PR i arrived at didn't have the darwin fix.

2023-12-22 14:48 UTC, emilylange requested changes, later dismissed
The release notes list multiple breaking changes, and we usually don't backport such.

https://github.com/bytecodealliance/wasm-micro-runtime/releases/tag/WAMR-1.3.0

Is there something I am missing? :)
A reason why you would like this to be backported nonetheless? @ereslibre

2023-12-22 15:13 UTC, ereslibre commented
> Is there something I am missing? :)

No really. I think you are right in general about the breaking changes notice. However, we are only providing the `iwasm` executable in our derivation and the only change relative to it `guest::host` when mapping files and directories, which is the expected behavior on other WebAssembly CLI runtimes (e.g. `wasmtime` or `wasmedge`).

However I understand that we should not backport if acting by the book. I have no strong reasons to backport either at this time other than "keep the latest release on release-23.11", so I'm good closing this PR.

2024-01-06 19:41 UTC, risicle commented
We should perhaps revisit this backport given CVE-2023-52284.

If there are compatibility problems with backporting the bump, the patch, https://github.com/bytecodealliance/wasm-micro-runtime/commit/6382162711a9cfaedc63de9065b0bc6eda8123f3 does apply (after some hacking due to `sourceRoot`-relativeness) and build. Though it would be nice to have some tests on this package if we were going to go down that route.

2024-01-06 19:46 UTC, ereslibre commented
Thank you for the heads up @risicle. Reopened.

2024-01-07 01:16 UTC, emilylange commented
Hi, sorry, I won't be able to find time for this any time soon.
Hope you can find someone else who looks into this.

2024-01-07 10:33 UTC, ereslibre commented
All things considered, I'd go ahead and merge this backport. We are not installing headers on this derivation, so breaking changes related to the API are a non-issue for us.

2024-01-10 21:32 UTC, LeSuisse approved these changes
Should be fine. Outside of security fix there is a bunch of bugfixes we should probably have anyway.

I ran `iwasm` with some modules I usually run with `wasmtime`, everything looks good.


Result of `nixpkgs-review pr 274072` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wamr</li>
  </ul>
</details>

2024-01-10 21:32 UTC, merged