ipfs: fix #27414 - fusermount": executable file not found
NixOS/nixpkgs pull request #27437
Opened 2017-07-16 22:30 UTC by apeyroux

###### Motivation for this change

A proposal to fix #27414 

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (`$SRC/result-bin/bin/ipfs mount -f $HOME/ipfs/ -n $HOME/ipns/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-07-17 00:47 UTC, fpletz requested changes
This does not the the issue. You have to create a wrapper script using `makeWrapper` in `nativeBuildInputs` and `wrapProgram $out/bin/ipfs --prefix PATH : "${stdenv.lib.makeBinPath [ fusermount ]}"` in `preFixup` hook.

Just grep for wrapProgram for examples. Please test your changes with for instance `nix-shell -I nixpkgs=/path/to/your/nixpkgs --pure -p ipfs`. :)

2017-07-17 06:28 UTC, bennofs commented
Note that `fusermount` is a `SUID` executable, so `stdenv.lib.makeBinPath [fusermount]` will probably not work. Or does `ipfs` always run as root?

2017-07-17 07:56 UTC, apeyroux commented
In the pre fixup hook, it does not find the ipfs binary. Is this the right hook to use or I missed something?

```nix
nativeBuildInputs = [ makeWrapper ];
preFixup = ''
  wrapProgram $out/bin/ipfs --prefix PATH : "${stdenv.lib.makeBinPath [ fuse ]}"
'';
```

```
post-installation fixup
mv: cannot stat '/nix/store/hcvhgkp6zvkydzj2ssx0a2myxjzp5dr0-ipfs-0.4.10/bin/ipfs': No such file or directory
```

2017-07-17 22:38 UTC, fpletz commented
@bennofs Oh, yeah, right, so this should rather be solved by the NixOS module?

@apeyroux Sorry, you would have to use `$bin` instead of `$out` for `wrapProgram`. But as @bennofs this is indeed no the correct solution.

I'm wondering now why you even have this problem as the security wrappers module at `nixos/modules/security/wrappers/default.nix` already unconditionally adds the `fusermount` wrapper and thus makes it available on every NixOS system.

2017-07-18 08:05 UTC, apeyroux commented
With : 

```nix
nativeBuildInputs = [ makeWrapper ];

preFixup = ''
  wrapProgram $bin/bin/ipfs --prefix PATH : "${stdenv.lib.makeBinPath [ fuse ]}"
'';
```
build is ok but I have this error : 

```
nix-shell -I nixpkgs=/home/alex/src/nixpkgs --pure -p ipfs
ipfs mount -f /tmp/ipfs -n /tmp/ipns
Error: fuse failed to access mountpoint /tmp/ipfs 
```

In strace "ipfs mount", there are `futex(0x1460b10, FUTEX_WAIT, 0, NULL)   = -1 EAGAIN (Resource temporarily unavailable)` ...

> [...]
> [pid 10209] getsockname(4,  <unfinished ...>
> [pid 10215] futex(0xc4201d8510, FUTEX_WAIT, 0, NULL <unfinished ...>
> [pid 10209] <... getsockname resumed> {sa_family=AF_INET, sin_port=htons(45100), sin_addr=inet_addr("127.0.0.1")}, [112->16]) = 0
> [pid 10209] getpeername(4, {sa_family=AF_INET, sin_port=htons(5001), sin_addr=inet_addr("127.0.0.1")}, [112->16]) = 0
> [pid 10209] setsockopt(4, SOL_TCP, TCP_NODELAY, [1], 4) = 0
> [pid 10209] setsockopt(4, SOL_SOCKET, SO_KEEPALIVE, [1], 4) = 0
> [pid 10209] setsockopt(4, SOL_TCP, TCP_KEEPINTVL, [30], 4) = 0
> [pid 10209] setsockopt(4, SOL_TCP, TCP_KEEPIDLE, [30], 4) = 0
> [pid 10209] futex(0xc4201d8510, FUTEX_WAKE, 1) = 1
> [pid 10215] <... futex resumed> )       = 0
> [pid 10215] futex(0xc4204fe910, FUTEX_WAKE, 1) = 1
> [pid 10209] write(4, "POST /api/v0/mount?encoding=json"..., 251 <unfinished ...>
> [pid 10214] <... futex resumed> )       = 0
> [...]
> [pid 10209] futex(0xc42002e910, FUTEX_WAIT, 0, NULL <unfinished ...>
> [pid 10215] <... read resumed> 0xc42029c000, 4096) = -1 EAGAIN (Resource temporarily unavailable)
> [pid 10215] futex(0xc4201d8510, FUTEX_WAIT, 0, NULL <unfinished ...>
> [pid 10214] <... pselect6 resumed> )    = 0 (Timeout)
> [...]
> Error: fuse failed to access mountpoint /tmp/ipfs
> [...]

and tcpdump return ipfs daemon return 500 with a POST on 127.0.0.1:5001

> G...G...POST /api/v0/mount?encoding=json&f=%2Ftmp%2Fipfs&n=%2Ftmp%2Fipns&stream-channels=true HTTP/1.1
> Host: 127.0.0.1:5001
> User-Agent: /go-ipfs/0.4.10/
> Connection: close
> Content-Length: 0
> Content-Type: application/octet-stream
> Accept-Encoding: gzip
> 
> 09:44:32.756757 IP localhost.commplex-link > localhost.45832: Flags [P.], seq 1:457, ack 252, win 350, options [nop,nop,TS val1191458217 ecr 1191456494], length 456
> E...c.@.@..8..............M.m......^.......
> G.5.G...HTTP/1.1 500 Internal Server Error
> Access-Control-Allow-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
> Access-Control-Expose-Headers: X-Stream-Output, X-Chunked-Output, X-Content-Length
> Content-Type: application/json
> Server: go-ipfs/0.4.10
> Trailer: X-Stream-Error
> Vary: Origin
> Date: Tue, 18 Jul 2017 07:44:32 GMT
> Connection: close
> Transfer-Encoding: chunked
> 42
> {"Message":"fuse failed to access mountpoint /tmp/ipfs","Code":0}

`ipfs daemon` return this log : 

> 09:51:54.739 ERROR       node: error mounting: fusermount: exit status 1 mount_unix.go:87
> 09:51:54.739 ERROR       node: error mounting: fusermount: exit status 1 mount_unix.go:91

https://github.com/ipfs/go-ipfs/blob/master/fuse/node/mount_unix.go#L87
https://github.com/ipfs/go-ipfs/blob/master/fuse/node/mount_unix.go#L91

The err1 and err2 refer to the two files : 

https://github.com/ipfs/go-ipfs/blob/master/fuse/ipns/mount_unix.go
https://github.com/ipfs/go-ipfs/blob/master/fuse/readonly/mount_unix.go

Maybe the "cmd = exec.Command("fusermount", "-u", point)" problem? - https://github.com/ipfs/go-ipfs/blob/master/fuse/mount/mount.go#L46

2017-08-30 18:30 UTC, globin commented
ping @mguentner

2018-04-21 20:11 UTC, matthewbauer commented
Fixed in #29133

2018-04-21 20:11 UTC, closed without merging