verdict: init at 1.4.2
NixOS/nixpkgs pull request #277172
Opened 2023-12-27 20:55 UTC by bcdarwin

## Description of changes

Init verdict, a small package for computations involving 2- and 3-d regions.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [NA] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [NA] (Package updates) Added a release notes entry if the change is major or breaking
  - [NA] (Module updates) Added a release notes entry if the change is significant
  - [NA] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2023-12-28 08:37 UTC, soispha requested changes
Could you move the package to `pkgs/by-name/ve/`?

2023-12-28 14:54 UTC, bcdarwin commented
> Could you move the package to `pkgs/by-name/ve/`?

sure, done.

2023-12-28 19:30 UTC, soispha approved these changes

2023-12-30 22:38 UTC, onemoresuza commented
# Reviewed points

Result of `nixpkgs-review pr 277172` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>verdict</li>
  </ul>
</details>

# Reviewed points

- [X] package path fits guidelines
- [X] package name fits guidelines
- [X] package version fits guidelines
- [X] package builds on x86_64-linux
- [ ] executables tested on x86_64-linux
	- N/A: Package is a library with no binaries besides `.so` files
- [X] `meta.description` is set and fits guidelines
- [X] `meta.license` fits upstream license
- [X] `meta.platforms` is set
- [X] `meta.maintainers` is set
- [X] build time only dependencies are declared in `nativeBuildInputs`
- [X] source is fetched using the appropriate function
- [X] the list of `phases` is not overridden
- [ ] when a phase (like `installPhase`) is overridden it starts with `runHook preInstall` and ends with `runHook postInstall`.
	- N/A: No phase is overwritten
- [ ] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
	- N/A: No patch is applied
- [ ] patches that are remotely available are fetched rather than vendored
	- N/A: No patch is applied

# Possible improvements

1. Just a minor nitpick: There's no need to use `refs/tags/${finalAttrs.version}`; just `finalAttrs.version` would be enough.

2023-12-30 22:38 UTC, onemoresuza commented on pkgs/by-name/ve/verdict/package.nix
> +    rev = "refs/tags/${finalAttrs.version}";
```suggestion
    rev = finalAttrs.version;
```

2023-12-30 22:39 UTC, onemoresuza approved these changes

2024-01-06 13:49 UTC, merged