mfcl5750dw: init at 3.5.1-1
NixOS/nixpkgs pull request #277781
Opened 2023-12-30 19:57 UTC by qdlmcfresh

Add CUPS driver for Brother MFC-L5750DW printer

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2023-12-30 20:14 UTC, qdlmcfresh commented
Result of nixpkgs-review pr 277781 run on x86_64-linux:
```
1 package built:
mfcl5750dw
```

2024-05-20 22:15 UTC, Pandapip1 requested changes
Please move this into `pkgs/by-name`.

2024-05-20 22:51 UTC, qdlmcfresh commented
> Please move this into `pkgs/by-name`.

Ok im happy to do that, but any comment on why?

2024-05-21 16:04 UTC, Pandapip1 commented
> Ok im happy to do that, but any comment on why?

It's now preferred over `pkgs/misc`.

2024-10-27 10:41 UTC, qdlmcfresh commented
> Please move this into `pkgs/by-name`.

i moved the package and rebased against master

2024-10-28 01:34 UTC, Pandapip1 requested changes

2024-10-28 01:34 UTC, Pandapip1 commented on pkgs/by-name/mf/mfcl5750dw/package.nix
> +  '';
```suggestion
  srcs = [
    (fetchurl {
      name = "mfcl5750dwcupswrapper";
      url = "https://download.brother.com/welcome/dlf102614/mfcl5750dwcupswrapper-${version}.i386.deb";
      sha256 = "afe6d18e17d26348f3b8a4f9a003107984940c429a7dd193054303a21f5e65b5";
    })
    (fetchurl {
      name = "mfcl5750dwlpr";
      url = "https://download.brother.com/welcome/dlf102613/mfcl5750dwlpr-${version}.i386.deb";
      sha256 = "b1b9c1f9ae8522a65fdd2db1e760aed835807ba593d001ac5471635a157cd1f1";
    })
  ];
  unpackPhase = ''
    runHook preUnpack
    for src in $srcs; do
      dpkg-deb -x $src .
    done
    runHook postUnpack
  '';
```

2024-10-28 01:34 UTC, Pandapip1 commented on pkgs/by-name/mf/mfcl5750dw/package.nix
> +    url = "https://download.brother.com/welcome/dlf102614/mfcl5750dwcupswrapper-${version}.i386.deb";
Can I confirm that fetching the `i386` version is correct for all the arches?

2024-10-28 01:34 UTC, Pandapip1 commented on pkgs/by-name/mf/mfcl5750dw/package.nix
> +  runtimeDeps = [
This list should be added to `buildInputs`, and `buildInputs` should be used instead.

2024-10-28 01:34 UTC, Pandapip1 commented on pkgs/by-name/mf/mfcl5750dw/package.nix
> +    homepage = "http://www.brother.com/";
```suggestion
    homepage = "https://www.brother.com/";
```

2024-10-31 01:31 UTC, Pandapip1 approved these changes
While I'm not particularly happy with the way the derivation is organized, it doesn't require any changes.

2024-12-15 11:46 UTC, FliegendeWurst approved these changes

2024-12-15 11:46 UTC, merged