renode-unstable: init at 1.14.0+20231229gita76dac0ae, renode: init at 1.14.0
NixOS/nixpkgs pull request #277761
Opened 2023-12-30 18:01 UTC by otavio

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2023-12-30 18:19 UTC, otavio commented
If @katyo and @thoughtpolice are interested in co-maintaining it, they are more than welcome. Would either of you be interested in doing so?

2023-12-30 22:18 UTC, AndersonTorres requested changes

2023-12-30 22:18 UTC, AndersonTorres commented on pkgs/by-name/re/renode/package.nix
> +
```suggestion
```

2023-12-30 22:18 UTC, AndersonTorres commented on pkgs/by-name/re/renode/package.nix
> +
```suggestion
```

2023-12-30 22:18 UTC, AndersonTorres commented on pkgs/by-name/re/renode/package.nix
> +
```suggestion
```

2023-12-30 22:18 UTC, AndersonTorres commented on pkgs/by-name/re/renode/package.nix
> +, unstableVersion ? false
A better name:

```suggestion
, buildUnstable ? false
```

Or even better, 

```suggestion
, buildVariant ? "stable" # can be "unstable" or "stable"
```

2023-12-30 22:18 UTC, AndersonTorres commented on pkgs/by-name/re/renode/package.nix
> +  passthru.updateScript =
Usually it goes at the end of expression before meta

2023-12-30 22:18 UTC, AndersonTorres commented on pkgs/by-name/re/renode/package.nix
> +  installPhase = ''
runHooks

2023-12-30 22:18 UTC, AndersonTorres commented on pkgs/by-name/re/renode/package.nix
> +    cat > $out/bin/renode <<EOF
I believe makeWrappers are more apropriate.

2023-12-30 22:25 UTC, AndersonTorres commented on pkgs/by-name/re/renode-unstable/package.nix
> +renode'.overrideAttrs (finalAttrs: _: {
```suggestion
(renode.override { 
  inherit unstableVersion; 
}).overrideAttrs (finalAttrs: _: {
```

2023-12-31 10:15 UTC, thiagokokada approved these changes

2023-12-31 10:15 UTC, merged