masterpdfeditor: Added masterpdfeditor
NixOS/nixpkgs pull request #27790
Opened 2017-07-31 06:54 UTC by CMCDragonkai

###### Motivation for this change

Added masterpdfeditor.

###### Things done

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I had some code here for 32 bit, but since I don't have a 32 bit machine I can't test the build of it. What's the right way to specify that this package is only for 64 bit?

I tested this on nix-shell, but not part of main nixpkgs.

2017-07-31 07:26 UTC, FRidh requested changes
- See Spotify e.g. on how to specify the derivation is available only for one arch.
- do test build with `nix-build -A masterpdeditor`. `nix-shell` sets some additional env vars so it is not entirely the same.
- update the commit title according to the guidelines

2017-07-31 07:26 UTC, FRidh commented on pkgs/applications/misc/masterpdfeditor/default.nix
> +    sha1 = {
sha1 is no longer considered secure. Use sha256 or above.

2017-07-31 07:26 UTC, FRidh commented on pkgs/applications/misc/masterpdfeditor/default.nix
> +        sha1 = sha1;
inherit both

2017-07-31 07:26 UTC, FRidh commented on pkgs/top-level/all-packages.nix
> +  masterpdfeditor = callPackage ../applications/misc/masterpdfeditor {
I think you're supposed to use `libsForQt5.callPackage`

2017-07-31 07:26 UTC, FRidh commented on pkgs/applications/misc/masterpdfeditor/default.nix
> +      "x86_64-linux" = "http://get.code-industry.net/public/master-pdf-editor-${version}_qt5.amd64.tar.gz";
get rid of the set if you only support one arch

2017-07-31 07:39 UTC, CMCDragonkai commented
I'm getting errors like this now:

```
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
zsh: abort      masterpdfeditor4
```

This didn't happen inside nix-shell.

2017-07-31 07:39 UTC, CMCDragonkai commented on pkgs/applications/misc/masterpdfeditor/default.nix
> +      "x86_64-linux" = "http://get.code-industry.net/public/master-pdf-editor-${version}_qt5.amd64.tar.gz";
Decided to leave it out, since I can't test whether the 32 bit build works.

2017-07-31 07:40 UTC, CMCDragonkai commented on pkgs/top-level/all-packages.nix
> +  masterpdfeditor = callPackage ../applications/misc/masterpdfeditor {
Ok that fills in the qtbase and qtsvg dependencies, but something is still broken with xcb. It didn't happen with nix-shell.

2017-07-31 07:48 UTC, CMCDragonkai commented
Ok looks like I might need `libQt5DBus.so.5` or `libqxcb.so`

2017-07-31 07:55 UTC, CMCDragonkai commented
@FRidh So I did build it with `nix-build`. But with a slightly different default.nix file. And this worked without the above error.

```
{ pkgs ? import <nixpkgs> {} }:
  with pkgs;
  let
    version = "4.2.70";
    url = {
      "i686-linux" = "http://get.code-industry.net/public/master-pdf-editor-${version}_i386.tar.gz";
      "x86_64-linux" = "http://get.code-industry.net/public/master-pdf-editor-${version}_qt5.amd64.tar.gz";
    }."${stdenv.system}";
    sha1 = {
      "i686-linux" = "bfd8af8d68f52619504c83ea23e4dbe962a386d8";
      "x86_64-linux" = "1c7ffc8858ef5034d6f29f4ee783bc8fb4478fb5";
    }."${stdenv.system}";
    libs = {
      "i686-linux" = [
        stdenv.cc.cc
        glibc
        sane-backends
        qt4
        xorg.libXext
        xorg.libX11
        xorg.libXdmcp
        xorg.libXau
        xorg.libxcb
      ];
      "x86_64-linux" = [
        stdenv.cc.cc
        glibc
        sane-backends
        qt5.qtbase
        qt5.qtsvg
        xorg.libXext
        xorg.libX11
        xorg.libXdmcp
        xorg.libXau
        xorg.libxcb
      ];
    }."${stdenv.system}";
  in
    stdenv.mkDerivation {
      name = "masterpdfeditor-${version}";
      src = fetchurl {
        url = url;
        sha1 = sha1;
      };
      libPath = stdenv.lib.makeLibraryPath libs;
      dontStrip = true;
      installPhase = ''
        mkdir -pv $out/bin
        cp -v masterpdfeditor4 $out/bin/masterpdfeditor4
        cp -v masterpdfeditor4.png $out/bin/masterpdfeditor4.png
        cp -v -r stamps $out/bin/stamps
        cp -v -r templates $out/bin/templates
        cp -v -r lang $out/bin/lang
        cp -v -r fonts $out/bin/fonts
        patchelf --interpreter "$(cat $NIX_CC/nix-support/dynamic-linker)" \
                 --set-rpath $libPath \
                 $out/bin/masterpdfeditor4
      '';
      meta = {
        description = "Master PDF Editor";
        homepage = "https://code-industry.net/free-pdf-editor/";
        license = stdenv.lib.licenses.unfreeRedistributable;
        platforms = stdenv.lib.platforms.linux;
        maintainers = stdenv.lib.maintainers.cmcdragonkai;
      };
    }
```

2017-07-31 08:05 UTC, CMCDragonkai commented
https://github.com/NixOS/nixpkgs/issues/15498

2017-07-31 08:05 UTC, CMCDragonkai commented
https://github.com/NixOS/nixpkgs/issues/24256

2017-07-31 08:17 UTC, CMCDragonkai commented
According to those issues, this may not be an issue with the nix expression I wrote, but something to do with the way nixos/nixpkgs organises its qt plugins. And I'm not sure how to invocate masterpdfeditor4 with the correct qt plugins. It appears there was a fix in master to solve this somehow, but I've got a filled `QT_PLUGIN_PATH` env variable pointing mostly to qt4 plugins, not qt5.

2017-08-01 16:36 UTC, CMCDragonkai commented
So this expression worked for you?

I don't understand what you mean by not being able to run qt applications
from the nix store.

On 2 Aug 2017 2:31 AM, "Frederik Rietdijk" <notifications@github.com> wrote:

> @CMCDragonkai <https://github.com/cmcdragonkai> Qt applications cannot be
> run from the store anymore, but need to be installed to a profile or ran
> from a nix-shell. Testing it from a profile (e.g. nix-env -iA
> masterpdfeditor) is the right approach. I quickly installed and ran it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/27790#issuecomment-319424513>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AAnHHR0QT689U9WCFtYoYIryKWGPcyQgks5sT1LYgaJpZM4On-Ey>
> .
>

2017-08-01 16:40 UTC, FRidh commented
I meant the following doesn't work:
```
$(nix-build -A masterpdfeditor)/bin/masterpdfeditor4
```
whereas
```
$ nix-env -iA masterpdfeditor -f . && masterpdfeditor4

```
should.

Note that running it from the store did work for me, but I suppose that's because I have a Plasma desktop with the same version of Qt.

2017-08-01 16:42 UTC, FRidh commented
The underlying issue is, if I am correct, that Qt now uses `propagatedUserEnvPkgs`, therefore depending on packages in your profile.

2017-08-02 02:58 UTC, CMCDragonkai commented
I had the exact opposite experience to yours. My nix-build works for 
masterpdfeditor4, but my nix-env doesn't properly install 
masterpdfeditor, possibly due to the links I posted above something to 
do with impurity in QT applications currently.


On 08/02/2017 02:41 AM, Frederik Rietdijk wrote:
>
> I meant the following doesn't work:
>
> |$(nix-build -A masterpdfeditor)/bin/masterpdfeditor4 |
>
> whereas
>
> |$ nix-env -iA masterpdfeditor -f . && masterpdfeditor4 |
>
> should.
>
> Note that running it from the store did work for me, but I suppose 
> that's because I have a Plasma desktop with the same version of Qt.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/NixOS/nixpkgs/pull/27790#issuecomment-319427050>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe-auth/AAnHHZ-mpNNPsLgMgIQcyV4aQUmmn89kks5sT1UcgaJpZM4On-Ey>.
>

2017-08-12 09:14 UTC, CMCDragonkai commented
Can anybody who has more experience with QT apps review this?

2017-10-16 10:12 UTC, flokli commented
@CMCDragonkai, @FRidh: I rebased this on latest master and tried executing, both using `nix-shell` and directly from the nix store. In both cases, it complained like this:

```
# nix-shell -p masterpdfeditor -I nixpkgs=$PWD --run "masterpdfeditor4"
This application failed to start because it could not find or load the Qt platform plugin "xcb"
in "".

Reinstalling the application may fix this problem.
/run/user/1000/nix-shell.zggzXe/rc: line 1: 29223 Aborted                 masterpdfeditor4
```

Did anything change by now in how QT applications should be wrapped?

2017-10-16 12:11 UTC, CMCDragonkai commented
It did work inside a nix shell before. But I'm not sure about how Qt apps are meant to work.

2017-11-01 21:27 UTC, flokli commented
As described by @ttuegel in [#30977](https://github.com/NixOS/nixpkgs/issues/30977#issuecomment-340955321), Qt applications currently don't seem to work when being run from `nix-shell` without a QT user environment in place, so that could have been my issue.

After having some dependent qt applications in my user environment, I was able to execute masterpdfeditor by `$(nix-build -A masterpdfeditor)/bin/masterpdfeditor4`, and also when adding it to my home environment (without the other qt application being pulled in).

I bumped to the latest version `4.3.61`, and added myself as maintainer. Also patched and added the `.desktop` file from there.

@CMCDragonkai could you give my [masterpdfeditor branch](https://github.com/flokli/nixpkgs/tree/masterpdfeditor) a try and if good push into this PR?

2017-11-02 04:27 UTC, CMCDragonkai commented
Your changes look good. The masterpdfeditor here does work on my machine, just not inside nix-shell, and only after I ran nix-build. So it looks like we kind of know what the problem is. Is there a way that you can push your changes into this PR? Or how would I pull in your changes into this PR into a combined PR?

2017-11-02 05:33 UTC, CMCDragonkai commented
I think I can pull in your branch and merge it into this PR.

2017-11-02 05:39 UTC, CMCDragonkai commented
@flokli Oh I can't do that, because you didn't fork from this PR, so I cannot cleanly merge your changes into this PR's branch. Instead your branch contains everything, so you should submit a PR and this PR can be closed in favour of yours.

2017-11-02 05:43 UTC, orivej commented
@CMCDragonkai If you agree with his changes, `git reset --hard his-branch` and `git push --force` it.

2017-11-02 05:43 UTC, CMCDragonkai commented
@flokli I just tried your branch installing masterpdfeditor from there, the build worked, but running the program results in:

```
Cannot mix incompatible Qt library (version 0x50901) with this library (version 0x50902)
zsh: abort      masterpdfeditor4
```

Looks like it requires some update to Qt. My current system nixpkgs commit is 8fefa85f5cc95a99c78776fdfb971deff3592cab while your branch is later.

2017-11-02 05:48 UTC, CMCDragonkai commented
@orivej Thanks for the tip. I did that now.

2017-11-02 06:14 UTC, orivej commented
It is great for PDF forms indeed. However, `stamps/`, `templates/` etc. should go to `$out/opt/masterpdfeditor/`, not to `$out/bin/`. (For example, this is where `dropbox` and `vagrant` go.) Then `$out/opt/masterpdfeditor/masterpdfeditor4` should be symlinked into `$out/bin/`.

2017-11-02 09:54 UTC, flokli commented
@orivej I already tried if it could be made to load assets from $out/share/$pname, but seems it has to come from next to the binary. I moved everything and added the symlink as suggested. @CMCDragonkai will push shortly.

2017-11-02 13:51 UTC, orivej approved these changes
That's perfect, thank you!

2017-11-04 10:15 UTC, CMCDragonkai commented
Hey is this going to be pulled in?

2017-11-04 20:19 UTC, merged