rust: use lld on pkgsStatic aarch64
NixOS/nixpkgs pull request #278798
Opened 2024-01-04 23:51 UTC by yu-re-ka

## Description of changes

Fixes https://github.com/NixOS/nixpkgs/issues/254454 https://github.com/NixOS/nixpkgs/issues/264687

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-01-05 11:49 UTC, alyssais commented
Can't this target master?

2024-01-05 12:18 UTC, yu-re-ka commented
Indeed it can

2024-01-05 18:50 UTC, alyssais requested changes

2024-01-05 18:50 UTC, alyssais commented on pkgs/build-support/rust/lib/default.nix
> +    isAarch64Static = platform: platform.isAarch64 && platform.isMusl && platform.isStatic;
It's _probably_ not musl-specific, right?  The issue is just static libraries not having dependency information, as I understand it.  But we wouldn't want to link with lld on Darwin, so maybe

```suggestion
    shouldUseLLD = platform: platform.isAarch64 && platform.isStatic && !platform.isDarwin;
```

I also think we need some explanation of why we're using lld, I guess with a link to the issue.

2024-01-05 18:50 UTC, alyssais commented on pkgs/build-support/rust/lib/default.nix
> +    linkerForHost = if isAarch64Static stdenv.targetPlatform then "${buildPackages.lld}/bin/ld.lld" else ccForHost;
We should check whether stdenv's linker is lld already, so we don't unnecessarily override it with a potentially different version.  Something like

```suggestion
    linkerForHost = if isAarch64Static stdenv.targetPlatform && !stdenv.cc.bintools.isLLVM then "${buildPackages.lld}/bin/ld.lld" else ccForHost;
```

2024-01-05 18:54 UTC, alyssais commented on pkgs/build-support/rust/lib/default.nix
> +    linkerForHost = if isAarch64Static stdenv.targetPlatform then "${buildPackages.lld}/bin/ld.lld" else ccForHost;
(And also for the target.)

2024-01-07 20:19 UTC, yu-re-ka commented
I have added the requested changes

2024-01-09 14:26 UTC, alyssais approved these changes

2024-01-15 21:34 UTC, merged