libguestfs with appliance by default
NixOS/nixpkgs pull request #278954
Opened 2024-01-05 16:42 UTC by minijackson

## Description of changes

This removes the package 'libguestfs-with-appliance', and adds the package 'libguestfsMinimal' without the appliance.

This makes nixpkgs packages use the appliance by default,
which fixes the user experienc of having the "no appliance" error
message in certain cases, for example the 'guestmount' command, and
running 'diffoscope' on disk images.

I'm proposing this because I just kept running into #37540-style issues, often without an easy way out (e.g. diffoscope using the guestfs Python package).

This also re-enables building the libguestfs with appliance on Hydra.

Note: the appliance was disabled by default in #56448 (cc @grahamc if you think this PR is acceptable), and disabled on Hydra a long time ago in ac52817bd90881acf2d27ffca834c78b27551601. We should test if Hydra is fine with it now, but I'm not sure how.

cc @offlinehacker 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [x] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>13 packages built:</summary>
  <ul>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>diffoscopeMinimal</li>
    <li>diffoscopeMinimal.dist</li>
    <li>diffoscopeMinimal.man</li>
    <li>libguestfs</li>
    <li>libguestfsMinimal</li>
    <li>python310Packages.guestfs</li>
    <li>python310Packages.guestfs.dist</li>
    <li>python311Packages.guestfs</li>
    <li>python311Packages.guestfs.dist</li>
    <li>vagrant</li>
  </ul>
</details>

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-01-05 18:27 UTC, wegank requested changes
`libguestfs-appliance` is not compatible with non-x86 platforms, so this PR breaks `diffoscope` on aarch64-linux.

2024-01-05 22:03 UTC, minijackson commented
@wegank good catch! Do you know if it's just our package, or if the upstream code really isn't compatible with other architectures?

2024-01-05 22:15 UTC, wegank commented
I am not aware of how other distros do, but our own `libguestfs-appliance` simply fetches and extracts the prebuilt appliance from upstream (which is x86).

2024-01-05 23:11 UTC, minijackson commented
I'll work on building the appliance from source, then. I think I'm close to succeeding, but there's still a weird issue where `augeas.c` can't find a libxml2 include…

2024-03-27 10:41 UTC, Et7f3 commented
@minijackson I am also interested in supermin support. Have you a branch/something I could look at and try to fix ?

2024-03-27 19:14 UTC, minijackson commented
@Et7f3 I've pushed what I have in the `guestfs-default-appliance-wip` branch of my fork:

https://github.com/minijackson/nixpkgs/tree/guestfs-default-appliance-wip

But it's more complicated than I initially thought. Building the appliance is about building a small image of a given Linux distribution, with some tools installed.

How `supermin` does it is by using the host's package manager to create a small rootfs, and install extra packages in it. The call to the host's package manager needs internet connection, and assumes the host is configured with repos and such.

That doesn't work for us. I think the best we could do would be to create our own small NixOS appliance with the same tools installed, and the same init script.

For more info in the libguestfs source code:

- `m4/guestfs-appliance.m4` search for the `--with-distro` option
- `appliance/Makefile.am` search for:
  - the `HAVE_RPM` conditional
  - the `guestfsd.deps` target
- `appliance/packagelist.in`
- `appliance/make.sh.in` (the script that builds the appliance)
- `appliance/init` (the init script for the appliance)

On another note, I don't think `supermin` can work on NixOS without either upstream support for NixOS, or using something like Distrobox. But both would only work in the Nix sandbox by using a fixed-output derivation and fixed repos (like CentOS/Rocky's *vault* repos), or by using impure derivations.

Thanks for reaching out, I'm quite busy these days, but still open for discussion if you're still interested.

2025-02-11 17:03 UTC, malte-v commented
I've made a PR using this approch here: https://github.com/NixOS/nixpkgs/pull/381224

2025-10-01 09:32 UTC, minijackson commented
Superseeded

2025-10-01 09:32 UTC, closed without merging