QT5.6: Fixes compile error with wrong LD env variable
NixOS/nixpkgs pull request #27940
Opened 2017-08-04 16:52 UTC by bkchr

QT uses -Wl linker flags and these flags only work with gcc/g++
and not with LD directly.

###### Motivation for this change

###### Things done

Please check what applies. Note that these are not hard requirements but merely serve as information for reviewers.

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-08-05 10:09 UTC, globin requested changes

2017-08-05 10:09 UTC, globin commented on pkgs/development/libraries/qt-5/5.6/qtbase/default.nix
> +    export LD=$GCC
This shoukd be $CC otherwise this will break with `clang`

2017-08-05 12:39 UTC, bkchr commented
Fixed :)

2017-08-05 14:12 UTC, NeQuissimus approved these changes

2017-08-06 08:11 UTC, FRidh requested changes
Still seems to fail with
```
/build/qtbase-opensource-src-5.6.2/lib/libQt5Bootstrap.a(qlatincodec.o):(.data.rel.ro._ZTI12QLatin1Codec[_ZTI12QLatin1Codec]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
/build/qtbase-opensource-src-5.6.2/lib/libQt5Bootstrap.a(qlatincodec.o):(.data.rel.ro._ZTI13QLatin15Codec[_ZTI13QLatin15Codec]+0x0): undefined reference to `vtable for __cxxabiv1::__si_class_type_info'
collect2: error: ld returned 1 exit status
```

2017-08-06 08:11 UTC, FRidh commented on pkgs/development/libraries/qt-5/5.6/qtbase/default.nix
> +    // We need to set LD to CC or otherwise we get nasty compile errors
invalid comment, `#`

2017-08-07 09:43 UTC, bkchr commented
Now it finally should work! First I hard $GCC and replaced that with $CC, but it needed to be $CXX. :) On my laptop it compiled now with my latest commit.

2017-08-07 11:04 UTC, FRidh approved these changes

2017-08-07 11:04 UTC, merged