clang6Stdenv, clang-tools_6, clang_6, lld_6, lldb_6, llvm_6: remove
NixOS/nixpkgs pull request #279581
Opened 2024-01-08 10:54 UTC by trofi

Remove all the aliases for `llvmPackages_6` except the `llvmPackages_6` itself.

We can remove `llvmPackages_6` once last two users are gone:

- vimPlugins: https://github.com/NixOS/nixpkgs/pull/279576
- beignet: https://github.com/NixOS/nixpkgs/pull/279578

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-01-08 19:29 UTC, philiptaron requested changes
one edit requested

2024-01-08 19:29 UTC, philiptaron commented on pkgs/top-level/aliases.nix
> +  llvm_6 = throw "llvm_7 has been removed from nixpkgs"; # Added 2023-11-19
this one is wrong

2024-01-08 19:37 UTC, trofi commented on pkgs/top-level/aliases.nix
> +  llvm_6 = throw "llvm_7 has been removed from nixpkgs"; # Added 2023-11-19
Good catch! Thank you! Fixed as:

```diff
--- a/pkgs/top-level/aliases.nix
+++ b/pkgs/top-level/aliases.nix
@@ -603 +603 @@ mapAliases ({
-  llvm_6 = throw "llvm_7 has been removed from nixpkgs"; # Added 2023-11-19
+  llvm_6 = throw "llvm_6 has been removed from nixpkgs"; # Added 2024-01-08
```

2024-01-10 19:18 UTC, sternenseemann approved these changes

2024-01-10 21:02 UTC, philiptaron approved these changes
Love it.

2024-01-10 22:11 UTC, merged