Create qbittorrent nox service
NixOS/nixpkgs pull request #279716
Opened 2024-01-09 00:11 UTC by camilosampedro

## Description of changes

WIP, while I'm filling data for the PR

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-01-14 22:06 UTC, camilosampedro commented
I was able to test it on a clean install inside of a QEMU VM, but the whole VM seems to crash when I run the review command:

```
nix-shell -p nixpkgs-review --run "nixpkgs-review pr 279716"
```

This crashes the VM even when running without `sudo` permissions. I wonder if this is a bug and if there's anything to do about it.

2024-01-29 16:03 UTC, ambroisie requested changes
What about a `downloadDir`? Is there any specific setup necessary there?

2024-01-29 16:03 UTC, ambroisie commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +    ];
Use `systemd.tmpfiles.settings`.

2024-01-29 16:03 UTC, ambroisie commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +    systemd.services.qbittorrent-nox = {
Same note about renaming the service

```suggestion
    systemd.services.qbittorrent = {
```

2024-01-29 16:03 UTC, ambroisie commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +      path = [ cfg.package ];
Not needed, better served by systemd's service hardening options.

2024-01-29 16:03 UTC, ambroisie commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +      # preStart = preStart;
Dead code.

2024-01-29 16:03 UTC, ambroisie commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +    environment.systemPackages = [ cfg.package ];
Why?

2024-01-29 16:03 UTC, ambroisie commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +        uid = config.ids.uids.qbittorrent-nox;
As explained, please refrain from adding more `uid`/`gid` values to NixOS.

```suggestion
```

2024-01-29 16:03 UTC, ambroisie commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +        gid = config.ids.gids.qbittorrent-nox;
Same remark as for `uid`.

```suggestion
```

2024-01-29 16:05 UTC, ambroisie commented
I'm also unsure whether we still need to use `lib.mdDoc` (maybe for backporting? I will have to check).

I would also argue that `with lib;` over the whole file is over-reaching. I'd be fine with using it in the `options = ...` block though.

2024-02-06 07:57 UTC, nu-nu-ko commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +with lib;
you should avoid this kind of use of with to address https://github.com/NixOS/nixpkgs/issues/208242 for this module.

use inherits where you find yourself excessively reusing `lib.foo`

2024-02-06 07:57 UTC, nu-nu-ko commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +        dataDir = mkOption {
is a dataDir true here for qbit, profiles seems to be the way it manages itself, a profilesdir commandline option is available.

2024-02-06 07:57 UTC, nu-nu-ko commented on nixos/modules/services/torrent/qbittorrent-nox.nix
> +            --webui-port=${toString cfg.web.port} \
neither port options should be done with the command line options, qbittorrent has  a configuration file we can define these in, we know where its state will be after all

2024-02-06 08:06 UTC, nu-nu-ko commented
seems i should have looked harder before i started on this, see https://github.com/NixOS/nixpkgs/commit/69fa9574a7ebd9ace9a5ef917555b7f02b113907
differences between our work now are
1. qBittorrent.conf options thanks to `gendeepINI` ( thanks [eclairevoyant](https://github.com/eclairevoyant) )
2. I'm missing `openFirewall` ( i want to include in config values here )
3. I'm missing a type for the configs options.
4. I apply much more service hardening.

I'll draft my own PR if I can get `openFirewall` done in an acceptable way myself.
open to however you may want to work with this or not, would love to have the config options available with nix instead of expecting the user to write a file out themselves etc.

as reference for how my module can be used right now i have a working use case in my systems repo [here](https://github.com/nu-nu-ko/crystal/blob/main/mods/services/qbit.nix)

would also appreciate your insight as another current qbit user / someone who wants a service module for it.
as well as testing on `aarch-64`

2024-02-08 00:20 UTC, camilosampedro commented
@nu-nu-ko Thank you for working on those changes, and sorry I've been absent these past days.

I'd be ok with you opening your PR, using that as the actual PR that introduces this service, and I can help testing it on my machine.

Let me know and I'll close this PR.

2024-02-11 03:18 UTC, nu-nu-ko commented
I've created https://github.com/NixOS/nixpkgs/pull/287923 with the current issues listed, I have only somewhat addressed the read write directorys and open ports issues as defaults should be filled in properly.

please ensure that PR has the same goal and functionality as you do here before closing anything, thank you.

2024-02-17 00:03 UTC, camilosampedro commented
@nu-nu-ko Your PR seems to be following my goal. I'll be doing some tests and commenting on that PR. I'll close this PR for now

2024-02-17 00:03 UTC, closed without merging