immich-cli: 0.41.0 -> 2.0.6
NixOS/nixpkgs pull request #279832
Opened 2024-01-09 13:28 UTC by pineapplehunter

## Description of changes
Updates immich-cli to version 2.0.6
The immich cli version is different from immich repo, so version is imported from package.json.

closes #274787

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-01-09 18:02 UTC, cole-h commented
@ofborg eval

2024-01-09 21:12 UTC, dotlambda requested changes
Please ask upstream to separately tag CLI releases if they don't share a version number.

2024-01-09 21:12 UTC, dotlambda commented on pkgs/tools/misc/immich-cli/default.nix
> +{ lib, buildNpmPackage, fetchFromGitHub }:
Let's not make unnecessary changes.
```suggestion
{ lib
, buildNpmPackage
, fetchFromGitHub
}:

```

2024-01-09 21:12 UTC, dotlambda commented on pkgs/tools/misc/immich-cli/default.nix
> +  version = (builtins.fromJSON (builtins.readFile "${src}/cli/package.json")).version;
This is an *import from derivation* which is not allowed in nixpkgs.

2024-01-09 21:12 UTC, dotlambda commented on pkgs/tools/misc/immich-cli/default.nix
> +    changelog = "https://github.com/immich-app/immich/releases/tag/v${immich_version}";
```suggestion
    changelog = "https://github.com/immich-app/immich/releases/tag/${src.rev}";
```

2024-01-09 21:12 UTC, dotlambda commented on pkgs/tools/misc/immich-cli/default.nix
> +  immich_version = "1.92.1";
```suggestion
```

2024-01-09 21:12 UTC, dotlambda commented on pkgs/tools/misc/immich-cli/default.nix
> +    rev = "v${immich_version}";
```suggestion
    rev = "v1.92.1";
```

2024-01-10 00:25 UTC, pineapplehunter commented
Thanks for the review! Updated the code.

> Please ask upstream to separately tag CLI releases if they don't share a version number.

I was not falimiar with the import from derivation case. (I kind of asumed that if it compiles, it is okay.)
Iwill see if I could ask for the cli version numbers, but for now, is it best to just hard code the version numbers?

2024-01-10 12:29 UTC, dotlambda commented
> for now, is it best to just hard code the version numbers?

Yes, but `rev`should point to the actual commit at which the version was published on NPM rather than the most recent immich version.

2024-01-10 12:31 UTC, dotlambda commented on pkgs/tools/misc/immich-cli/default.nix
> -
Why remove this line?

2024-01-10 12:31 UTC, dotlambda commented on pkgs/tools/misc/immich-cli/default.nix
> +    changelog = "https://github.com/immich-app/immich/releases/tag/v1.92.1";
This doesn't list the CLI changes.

2024-01-12 06:54 UTC, pineapplehunter commented
@dotlambda Thanks again for the review!
I got the exact commit that is used when it was uploaded to npm, so this should be the same as using the version on npm.

2024-01-12 10:17 UTC, dotlambda approved these changes

2024-01-12 13:45 UTC, merged