iio-oscilloscope: init at 0.17
NixOS/nixpkgs pull request #280521
Opened 2024-01-12 14:55 UTC by chuangzhu

## Description of changes

GTK+ based oscilloscope application for interfacing with various IIO devices

https://wiki.analog.com/resources/tools-software/linux-software/iio_oscilloscope

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-31 09:33 UTC, FliegendeWurst commented on pkgs/by-name/ii/iio-oscilloscope/package.nix
> +    maintainers = with maintainers; [ chuangzhu ];
Add `platforms = linux;`.

Build fails on darwin.

2024-11-01 10:44 UTC, FliegendeWurst requested changes

2024-11-01 10:44 UTC, FliegendeWurst commented on pkgs/by-name/ii/iio-oscilloscope/package.nix
> +  wrapGAppsHook,
```suggestion
  wrapGAppsHook3,
```

2024-11-01 10:44 UTC, FliegendeWurst commented on pkgs/by-name/ii/iio-oscilloscope/package.nix
> +    wrapGAppsHook
```suggestion
    wrapGAppsHook3
```

2024-11-01 11:35 UTC, FliegendeWurst commented
By the way, there is another PR for this package: #322262

2024-11-01 11:54 UTC, FliegendeWurst commented on pkgs/by-name/ii/iio-oscilloscope/package.nix
> +# libad9166,
Why are these commented out?

2024-11-01 11:54 UTC, FliegendeWurst commented on pkgs/by-name/ii/iio-oscilloscope/package.nix
> +# libad9166,
Nevermind, I see now that libad9166 is not packaged in nixpkgs yet.

2024-11-21 09:06 UTC, FliegendeWurst approved these changes

2024-12-01 11:19 UTC, Aleksanaa approved these changes

2024-12-01 11:19 UTC, merged