python3Packages.colour-science: init at 0.4.4
NixOS/nixpkgs pull request #280956
Opened 2024-01-14 15:48 UTC by Laurent2916

## Description of changes

Hey!

This PR adds the `colour` package by colour-science (https://github.com/colour-science/colour). Since the package's name conflicts with an existing package named `colour` by vaab (https://github.com/vaab/colour already in nixpkgs), I named this new package `colour-science`.

I disabled some tests, some of them are very (very) slow, and 4 others are not passing (they fail to read/write an EXR file, I couldn't find a fix).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-30 17:04 UTC, FliegendeWurst requested changes
There is a test failure:
```
colour/quality/tests/test_cqs.py:51:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<function assert_allclose.<locals>.compare at 0x7fff0d37eca0>, array(64.11186441005214), array(64.11182201566285))
kwds = {'equal_nan': True, 'err_msg': '', 'header': 'Not equal to tolerance rtol=1e-07, atol=1e-07', 'verbose': True}

    @wraps(func)
    def inner(*args, **kwds):
        with self._recreate_cm():
>           return func(*args, **kwds)
E           AssertionError:
E           Not equal to tolerance rtol=1e-07, atol=1e-07
E
E           Mismatched elements: 1 / 1 (100%)
E           Max absolute difference: 4.2394389282662814e-05
E           Max relative difference: 6.612569718000784e-07
E            x: array(64.11186441005214)
E            y: array(64.11182201566285)
```

2024-10-30 17:04 UTC, FliegendeWurst commented on pkgs/development/python-modules/colour-science/default.nix
> +  format = "pyproject";
```suggestion
  pyproject = true;
```

2024-11-02 11:19 UTC, Laurent2916 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 280956`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python311Packages.colour-science</li>
    <li>python311Packages.colour-science.dist</li>
  </ul>
</details>

2024-11-02 11:21 UTC, Laurent2916 commented
Hi @FliegendeWurst!
That's quite peculiar :thinking:, what's architecture, and how did you launch the tests ?

2024-11-02 11:28 UTC, FliegendeWurst commented
> Hi @FliegendeWurst!
> That's quite peculiar :thinking:, what's your architecture, and how did you launch the tests ?

Also x86_64 Linux. I simply ran nix-shell -p python3Packages...

2024-11-02 12:26 UTC, FliegendeWurst reviewed
Tests pass now.

2024-11-18 17:51 UTC, FliegendeWurst requested changes

2024-11-18 17:51 UTC, FliegendeWurst commented on pkgs/development/python-modules/colour-science/default.nix
> +  disabled = python3.pkgs.pythonOlder "3.9";
```suggestion
  disabled = pythonOlder "3.9";
```

2024-11-18 17:51 UTC, FliegendeWurst commented on pkgs/development/python-modules/colour-science/default.nix
> +  nativeBuildInputs = with python3.pkgs; [
```suggestion
  nativeBuildInputs = [
```
These should all be listed in the package inputs.
Same below.

2024-11-18 17:51 UTC, FliegendeWurst commented on pkgs/development/python-modules/colour-science/default.nix
> +    description = "Colour Science for Python";
```suggestion
    description = "Algorithms and datasets for colour science";
```

2024-11-28 14:58 UTC, FliegendeWurst commented on pkgs/development/python-modules/colour-science/default.nix
> +  nativeBuildInputs = [
```suggestion
  build-system = [
```

2024-11-28 14:58 UTC, FliegendeWurst commented on pkgs/development/python-modules/colour-science/default.nix
> +  propagatedBuildInputs = [
```suggestion
  dependencies = [
```

2024-11-28 14:58 UTC, FliegendeWurst commented on pkgs/development/python-modules/colour-science/default.nix
> +  nativeCheckInputs = [
The tests take ~100 CPU-hours. I am not sure what our (Hydra's) limits are.

2025-07-07 22:38 UTC, axelkar commented
@FliegendeWurst Are you available to maintain the package?

2025-10-01 07:44 UTC, FliegendeWurst commented
Not really, I'm not familiar with it

2026-02-19 21:31 UTC, closed without merging