typst-preview: 0.9.2 -> 0.10.5
NixOS/nixpkgs pull request #281245
Opened 2024-01-16 00:28 UTC by berberman

## Description of changes

Closes #280865

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-01-16 08:49 UTC, drupol requested changes
Hello,

Thanks for this massive update! I left some comments, let me know if this is clear enough.

2024-01-16 08:49 UTC, drupol commented on pkgs/by-name/ty/typst-preview/package.nix
> +, libgit2, openssl, zlib, stdenv, darwin }:
Can we keep one line per dependency please?

2024-01-16 08:49 UTC, drupol commented on pkgs/by-name/ty/typst-preview/package.nix
> +  buildInputs = [ libgit2 openssl zlib ] ++ lib.optionals stdenv.isDarwin [
Can you please revert this change?

2024-01-16 08:49 UTC, drupol commented on pkgs/by-name/ty/typst-preview/package.nix
> +  nativeBuildInputs = [ pkg-config ];
Can you please revert this change?

2024-01-16 08:49 UTC, drupol commented on pkgs/by-name/ty/typst-preview/package.nix
> +    packageResolutions = { typst-dom = dom; };
Can we define `dom` just before using it? It's easier to read and understand.

2024-01-17 07:03 UTC, drupol approved these changes

2024-01-17 08:30 UTC, drupol commented
@GrahamcOfBorg build typst-preview

2024-01-17 09:53 UTC, merged

2024-01-17 15:22 UTC, wackbyte commented
thanks!