Graphite
NixOS/nixpkgs pull request #28297
Opened 2017-08-15 14:21 UTC by apeschar

###### Motivation for this change

* Graphite 1.0.2 is newer.
* This also fixes carbonRelay and carbonAggregate services, that specified a PIDFile in a non-existent RuntimeDirectory.
* `django_tagging_0_3` was only used by the older Graphite, so can be removed. (I suppose.)

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-08-15 14:49 UTC, FRidh requested changes

2017-08-15 14:49 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    propagatedBuildInputs = with self; [ django_1_8 (django_tagging.override { django = django_1_8; }) whisper pycairo ldap memcached pytz urllib3 cairocffi scandir pyparsing ];
No overriding within the package set. All Django packages will need to depend just on `django`, and not on a specific version. If you application needs a specific version, then you need to override the whole Python package set when deploying it.

2017-08-15 14:59 UTC, apeschar commented on pkgs/top-level/python-packages.nix
> +    propagatedBuildInputs = with self; [ django_1_8 (django_tagging.override { django = django_1_8; }) whisper pycairo ldap memcached pytz urllib3 cairocffi scandir pyparsing ];
When deploying it -> you mean in the service?

2017-08-15 15:08 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    propagatedBuildInputs = with self; [ django_1_8 (django_tagging.override { django = django_1_8; }) whisper pycairo ldap memcached pytz urllib3 cairocffi scandir pyparsing ];
yes

2017-08-25 05:24 UTC, apeschar commented
@FRidh:

* graphite_web now uses just django and django_tagging
* django is overridden in the pythonPackages that is used in the service

This means the 'stock' pythonPackages.graphite_web doesn't build, since it relies on Django 1.8. Is that expected?

2018-04-21 20:33 UTC, matthewbauer requested changes
Resolve merge conflicts

2018-04-22 06:42 UTC, FRidh commented
We are moving Python expressions out of `pkgs/top-level/python-packages.nix` into `pkgs/development/python-modules/<module>/default.nix`. 

Please move the expression there, and call it from `pkgs/top-level/python-packages.nix` using `callPackage ../development/python-modules/<package> { };`.

2018-04-22 06:43 UTC, FRidh commented
@apeschar yes, that can be fine.

2018-04-23 04:26 UTC, apeschar commented
This was already done in another pull request, so no longer relevant.

2018-04-23 04:26 UTC, closed without merging