xremap: init at 0.8.14
NixOS/nixpkgs pull request #283278
Opened 2024-01-23 18:03 UTC by 0x4A6F

## Description of changes

Add [xremap](https://github.com/k0kubun/xremap) a key remapper for X11 and Wayland.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-01-23 18:05 UTC, 0x4A6F commented
Sorry pbar1, I haven't noticed #173106.

2024-02-03 20:31 UTC, jtbx requested changes
KDE support (replaces #286064)

2024-02-03 20:31 UTC, jtbx commented on pkgs/by-name/xr/xremap/package.nix
> +, wayland
```suggestion
, wayland

, kdeSupport ? true
```

2024-02-03 20:31 UTC, jtbx commented on pkgs/by-name/xr/xremap/package.nix
> +  cargoHash = "sha256-ABzt8PMsas9+NRvpgtZlsoYjjvwpU8f6lqhceHxq91M=";
```suggestion
  cargoHash = "sha256-ABzt8PMsas9+NRvpgtZlsoYjjvwpU8f6lqhceHxq91M=";

  cargoBuildFlags = lib.optional kdeSupport "--features kde";
```

2024-11-18 18:30 UTC, 0x4A6F commented on pkgs/by-name/xr/xremap/package.nix
> +    rev = "v${version}";
Not according to https://nixos.org/manual/nixpkgs/stable/#fetchfromgithub

2024-11-29 09:07 UTC, Aleksanaa commented on pkgs/by-name/xr/xremap/package.nix
> +    platforms = platforms.linux;
```suggestion
  meta = {
    description = "Key remapper for X11 and Wayland";
    homepage = "https://github.com/k0kubun/xremap";
    changelog = "https://github.com/k0kubun/xremap/blob/${src.rev}/CHANGELOG.md";
    license = lib.licenses.mit;
    mainProgram = "xremap";
    maintainers = with lib.maintainers; [ _0x4A6F ];
    platforms = lib.platforms.linux;
```

2024-11-29 09:07 UTC, Aleksanaa commented on pkgs/by-name/xr/xremap/package.nix
> +    ++ lib.optional x11Support "--features x11";
https://nixos.org/manual/nixpkgs/unstable/#cargo-features

2025-09-11 07:50 UTC, hakan-demirli commented
Superseded by https://github.com/NixOS/nixpkgs/pull/383512

2025-09-11 07:50 UTC, closed without merging