arc_unpacker: apply AUR patch that fixes build on GCC 13
NixOS/nixpkgs pull request #283791
Opened 2024-01-25 15:33 UTC by mfrischknecht

`arc_unpacker` fails to build with GCC 13 because GCC stopped transitively including `cstdint` in a lot of scenarios. While the project is inactive (the repository has been archived on GitHub), the Arch Linux user repository already contains a patch that fixes this issue.

AUR patch: https://aur.archlinux.org/cgit/aur.git/plain/include_cstdint.patch?h=arc_unpacker-git
Failing Hydra build: https://hydra.nixos.org/build/246193581
Hydra log: https://hydra.nixos.org/build/246193581/nixlog/1

Relevant log excerpt:
```
[  0%] Building CXX object CMakeFiles/libau.dir/src/algo/crypt/aes.cc.o
In file included from /build/source/build/../src/algo/crypt/aes.h:20,
                 from /build/source/src/algo/crypt/aes.cc:18:
/build/source/build/../src/types.h:25:16: error: 'uint8_t' does not name a type
   25 |     using u8 = uint8_t;
      |                ^~~~~~~
/build/source/build/../src/types.h:22:1: note: 'uint8_t' is defined in header '<cstdint>'; did you forget to '#include <cstdint>'?
   21 | #include <vector>
  +++ |+#include <cstdint>
   22 | 
```

## Description of changes

Pulled in the AUR patch via `fetchpatch`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-02-01 18:14 UTC, midchildan requested changes

2024-02-05 17:10 UTC, mfrischknecht commented on pkgs/tools/archivers/arc_unpacker/default.nix
> +      url = "https://aur.archlinux.org/cgit/aur.git/plain/include_cstdint.patch?h=arc_unpacker-git";
Sorry for the delay; I've squashed the change into the original commit. Thanks! :)

2024-02-09 00:39 UTC, a-n-n-a-l-e-e commented
aarch64-darwin [fails](https://logs.ofborg.org/?key=nixos/nixpkgs.283791&attempt_id=fd5ea2bb-0fb5-415f-9dff-55d30640d3b3) to build.

2024-02-10 18:01 UTC, mfrischknecht commented
> aarch64-darwin [fails](https://logs.ofborg.org/?key=nixos/nixpkgs.283791&attempt_id=fd5ea2bb-0fb5-415f-9dff-55d30640d3b3) to build.

@a-n-n-a-l-e-e Do you know a good way on how to approach these failures? I see that the issue lies with two failing tests.
I don't have any darwin boxes I could use to easily run repeated tests to try and figure out what the cause might be. The log outputs don't seem very informative.

Instinctively, my first two questions regarding the failed tests would be if they are deterministic or flaky and whether the failures also happen with older GCC versions -- both of which are hard to check without a possibility to quickly trigger new builds.

2024-02-10 21:11 UTC, a-n-n-a-l-e-e commented
@mfrischknecht i think just stating that the build was broken prior to the gcc13 fix and marking aarch64-darwin as broken due to the unit test failures is fine. i guess, really, just acknowledging the failure and stating that this change is still a step in the right direction -- eg: nixpkgs is better with than without this change -- seems fine too.

2024-02-11 21:31 UTC, mfrischknecht commented
@a-n-n-a-l-e-e Thanks! :) I've added and squashed the `broken`  annotation into the commit: https://github.com/NixOS/nixpkgs/commit/d439d93c01e51131b862b9641dcdb21c203d4630

2024-02-12 00:30 UTC, merged