nixos/mautrix-discord: init
NixOS/nixpkgs pull request #284421
Opened 2024-01-28 05:08 UTC by robintown

## Description of changes

mautrix-discord has already been packaged, but as of yet no NixOS module has been provided. This is the same module that I've revived from https://github.com/NixOS/nixpkgs/pull/200462, but now with expanded hardening.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-01-28 22:06 UTC, raspher commented
Result of `nixpkgs-review pr 284421` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>

2024-02-06 07:43 UTC, nu-nu-ko commented on nixos/modules/services/matrix/mautrix-discord.nix
> +      enable = mkEnableOption (mdDoc "Matrix to Discord hybrid puppeting/relaybot bridge");
`lib.mdDoc` is now just an alias and can be safely removed everywhere.
see https://github.com/NixOS/nixpkgs/commit/d36f950d405369abca5144b14a201bc25c4a080a and https://github.com/NixOS/nixpkgs/pull/237557

2024-02-06 07:43 UTC, nu-nu-ko commented on nixos/modules/services/matrix/mautrix-discord.nix
> +        type = with types; listOf str;
is `with` really useful here? `type = listOf lib.types.str;` should work.

2024-02-06 07:43 UTC, nu-nu-ko commented on nixos/modules/services/matrix/mautrix-discord.nix
> +with lib;
you should avoid this kind of use of with to address https://github.com/NixOS/nixpkgs/issues/208242 for this module.

use inherits where you find yourself excessively reusing `lib.foo`

2024-02-06 07:43 UTC, nu-nu-ko commented on nixos/modules/services/matrix/mautrix-discord.nix
> +          ${cfg.package}/bin/mautrix-discord \
`${lib.getExe cfg.package}` would be nice.

2024-02-06 07:43 UTC, nu-nu-ko commented on nixos/modules/services/matrix/mautrix-discord.nix
> +        ${pkgs.yq}/bin/yq -y ".appservice.as_token = $(${pkgs.yq}/bin/yq .as_token ${registrationFile}) | .appservice.hs_token = $(${pkgs.yq}/bin/yq .hs_token ${registrationFile})" ${settingsFile} >
similarly `lib.getExe` would be better here, especially if `yq` already has `meta.mainProgram` set.

2024-02-08 07:39 UTC, fsnkty approved these changes
Looks good to me, thanks!

2024-02-14 14:39 UTC, robintown commented
@azahi / @rrix, might one of you be willing to give this another review given your interest in https://github.com/NixOS/nixpkgs/pull/200462?

2024-02-15 10:31 UTC, azahi requested changes
You forgot to add the test file to `nixos/tests/all-tests.nix`. Other than that, LGTM.

2024-02-15 14:24 UTC, azahi approved these changes

2024-03-06 06:18 UTC, Rutherther commented
Hello, I have a few notes, 

1. It seems that there is mkIf cfg.enable twice in the code, that looks unnecessary to me.

2. Notice for example the mautrix whatsapp bridge service copies the config first to data dir via envsubst. This allows to pass in secrets via the environment file. That can be useful for the login shared secrets etc. Also thanks to it being before registration generation you can pass something else to the config for generation of registration. The way its in this service it looks like this won't be possible.

3. Also, would it make sense to make the dataDir configurable?

2024-03-19 15:18 UTC, Rutherther commented
I have recently Made pr with mautrix-meta service that has data dir configurable, so you can take a look. #926718

2024-05-04 10:02 UTC, Jo-Blade commented
Hello ! Is there anything new about this module ? Can I use it safely on my homeserver ?
Do you need some help to fix issues otherwise ?

2025-02-05 03:03 UTC, kira-bruneau commented
It looks like a new PR was opened: #355025. It has more options defined, but it's missing a test.

I'd normally give preference to this PR since it was opened first, but @robintown it looks like you haven't been responding to any of the latest comments and there are merge conflicts.

@robintown Are you still interested in maintaining this? I'll go ahead with merging #355025 if I don't hear anything back within the next week.

2025-07-07 01:42 UTC, sumnerevans commented
Closing this as superseded by #404871.

2025-07-07 01:42 UTC, closed without merging