haskell infra: Make sure packages get custom stdenv
NixOS/nixpkgs pull request #28478
Opened 2017-08-22 19:21 UTC by Ericson2314

###### Motivation for this change

The big question is whether stdenv should just be part of `self`, just as it is included in all-packages.

###### Things done

- [ ] Tested using sandboxing
  ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS,
    or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file)
    on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-08-22 19:23 UTC, peti requested changes
I don't understand what problem this change tries to solve.

2017-08-22 19:33 UTC, Ericson2314 commented
@peti one of the goals of 74f5fe50 was to allow passing in a custom stdenv, which would be used for `genericBuilder`'s `mkDerivation` call. That does work, but if packages take `stdenv` as an argument for any reason, they'll get the default one instead, that remedies it.

I use custom stdenvs to fix the sierra issue without rebuilding GHC to hard-code a different C toolchain.

2017-08-22 20:04 UTC, shlevy approved these changes

2017-08-22 20:09 UTC, peti commented
@Ericson2314, I am sorry, but I still don't understand. Where exactly would you like to override `stdenv` and why is that not possible today?

2017-08-22 20:18 UTC, peti commented
Are you aware that `hackage-packages.nix` binds `stdenv` as an argument? Haskell packages in Nixpkgs never need `stdenv` as an argument -- it's always in scope. No lookup in `self` takes place.

2017-08-22 20:31 UTC, Ericson2314 commented
@peti 

> Where exactly would you like to override stdenv 

Since `74f5fe5`,
```nix
call Package makePackageSet { stdenv = ... }
```

> Are you aware that hackage-packages.nix binds stdenv as an argument?

What about stand-alone `cabal2nix`? `stdenv` would be unbound unless it is a set-pattern parameter.

2017-08-22 21:01 UTC, peti commented
Yes, expressions generated by `cabal2nix` need a `stdenv` argument, but the only place they ever use it is to access `stdenv.lib.licenses`. Arguably, we could change that code of take `lib` as an argument rather than `stdenv`, but in any case it should make no difference for your use case, no?

2017-08-22 21:09 UTC, Ericson2314 commented
@peti What I've done is https://github.com/NixOS/nixpkgs/compare/master...obsidiansystems:more-sierra-hack#diff-209cb9d64e0f91ce90d31759e43bba01R48 That could be rewritten, but I'd think that if `callPackage` provides self, which it will because of the `pkgs` in `mkScope`'s definition, it might as well provide the right one.

2017-08-22 22:33 UTC, Ericson2314 commented
@peti Also consider

1. People do still write haskell derivations by hand

2. We could perhaps get rid of those 3 outer arguments in `haskell-packages.nix`, making there more obviously be one source of truth.

2017-09-05 09:14 UTC, merged

2017-09-05 19:35 UTC, Ericson2314 commented
@peti Thanks!