graphite-cli: add fish completion
NixOS/nixpkgs pull request #285364
Opened 2024-01-31 20:45 UTC by diegs

## Description of changes

Adds fish completion to graphite-cli package.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-02-05 19:14 UTC, diegs commented
@dotlambda you previously updated graphite-cli. I'm not sure how to add a reviewer these days? I checked the contributing.md but didn't se anything. Thanks.

2024-02-05 20:49 UTC, dotlambda commented
@diegs Wanna take over maintainership of this package?

2024-02-05 21:47 UTC, dotlambda requested changes
The content of `$out/share/fish/vendor_completions.d/gt.fish` is
```
UNCAUGHT EXCEPTION: spawn git ENOENT
UNCAUGHT EXCEPTION: Error: spawn git ENOENT
    at ChildProcess._handle.onexit (node:internal/child_process:286:19)
    at onErrorNT (node:internal/child_process:484:16)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
```

2024-02-06 20:37 UTC, diegs commented
@dotlambda thanks, looks like git had to be available and the pager has to be disabled too for some reason :-/

The content of $out/share/fish/vendor_completions.d/gt.fish is now:

```
### Installation: gt fish >> ~/.config/fish/completions/gt.fish
# git helpers adapted from fish git completion
function __fish_git_local_branches
    command git for-each-ref --format='%(refname:strip=2)' refs/heads/ 2>/dev/null
end

function __fish_git_remote_branches
    command git for-each-ref --format="%(refname:strip=3)" refs/remotes/ 2>/dev/null
end

# graphite helpers
function __gt_command_completions
    set -lx SHELL (type -p fish)
    set -l command (commandline -opc)
    # uncomment to include options, e.g. -q, --help
    # $command --get-yargs-completions
    # uncomment to exclude options (default)
    $command --get-yargs-completions | string replace -r '\-.*' ''
end

# disable file completions for the entire command
complete -c gt -f

# add completions as provided by CLI
complete -c gt -a "(__gt_command_completions)"

# commands that take branches
complete -c gt -x -n "__fish_seen_subcommand_from checkout co bco delete dl rename rn onto --onto -o tr utr track untrack" -a "(__fish_git_local_branches)"

# gt downstack get takes remote branches
complete -c gt -x -n "__fish_seen_subcommand_from ds dsg get g" -n "__fish_seen_subcommand_from get dsg" -a "(__fish_git_remote_branches)"
```

I'm not a nixpkgs maintainer of everything. I could consider taking over this one if there's a good onboarding path though!

2024-02-06 20:56 UTC, dotlambda reviewed
Please squash.

2024-02-06 20:59 UTC, dotlambda commented
> I'm not a nixpkgs maintainer of everything. I could consider taking over this one if there's a good onboarding path though!

https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md defines what the role of a maintainer is. Basically the you'd be pinged whenever the package is updated or otherwise changed. That's useful because we need PR reviewers who actually use the software.

2024-02-06 22:30 UTC, diegs commented on pkgs/by-name/gr/graphite-cli/package.nix
> +      --fish <(GT_PAGER= $out/bin/gt fish) \
when I ran without that, the fish completion script is truncated with

```
WARNING: Tried to send output to your pager (less) but encountered an error.
You can change your configured pager or disable paging: gt user pager --help
ERROR: Command failed with error exit code 127:
less 
```

2024-02-06 22:51 UTC, dotlambda commented on pkgs/by-name/gr/graphite-cli/package.nix
> +      --fish <(GT_PAGER= $out/bin/gt fish) \
Oh you're right.

2024-02-07 00:05 UTC, dotlambda approved these changes

2024-02-07 00:05 UTC, merged

2024-02-07 00:06 UTC, diegs commented
Thank you for the detailed review and the link, I'll look at the maintainer role and follow up with you.