opensubdiv: Add metal support
NixOS/nixpkgs pull request #286053
Opened 2024-02-03 11:55 UTC by expenses

## Description of changes

Hi, I'm new to Nix and it's pretty late here so I'm just writing this as an initial PR. Building OpenUSD on MacOS requires that opensubdiv is built with Metal support but it's not currently enabled in the package. I'm not sure what `# don’t have metal in apple sdk` means as this appears to be false. `MetalKit` is used instead of just `Metal` as `simd/simd.h` is required.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
-  [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-02-07 09:02 UTC, expenses commented
I've been using this branch for a while now and I think these changes are good to go.

2024-02-07 09:09 UTC, expenses commented
These changes have allowed me to build openusd on macos using https://github.com/expenses/openusd-minimal-nix/commit/82cc8da1c7594da75f3b46b71b88a515b53033d2. The python openusd packages will take more work as they build things like QT.

2024-02-16 07:49 UTC, Samasaur1 approved these changes
Seems reasonable to me, and opensubdiv builds on aarch64-darwin for me

2024-02-16 09:30 UTC, drupol requested changes
Hi !

Thanks for your contribution.

I've left some comments, let me know if this is clear enough. I know that these changes are not related to adding `Metal` support, but it would definitely be super nice to improve that part.

2024-02-16 09:30 UTC, drupol commented on pkgs/development/libraries/opensubdiv/default.nix
>      ++ lib.optional (openclSupport && !stdenv.isDarwin) ocl-icd
```suggestion
    ++ lib.optionals (openclSupport && !stdenv.isDarwin) [ ocl-icd ]
```

2024-02-16 09:30 UTC, drupol commented on pkgs/development/libraries/opensubdiv/default.nix
>      ];
```suggestion
    ++ lib.optionals cudaSupport [
      cudaPackages.cuda_cudart
    ];
```

2024-02-16 10:37 UTC, expenses commented
> I've left some comments, let me know if this is clear enough. I know that these changes are not related to adding `Metal` support, but it would definitely be super nice to improve that part.

Fair enough!

2024-02-16 10:38 UTC, drupol requested changes
Thanks for implementing the changes! It definitely LGTM now.

Last thing, could you please rewrite your commit log message so it matches the PR title, and squash the two commits into one.

2024-02-16 23:45 UTC, SomeoneSerge approved these changes

2024-02-16 23:46 UTC, SomeoneSerge commented on pkgs/development/libraries/opensubdiv/default.nix
> -      "-DNO_METAL=1" # don’t have metal in apple sdk
Let's maybe make this explicit as the other options, `(cmakeBool "NO_METAL" (!stdenv.isDarwin))`

2024-02-16 23:48 UTC, SomeoneSerge commented on pkgs/development/libraries/opensubdiv/default.nix
> +    ++ lib.optionals stdenv.isDarwin (with darwin.apple_sdk.frameworks; [OpenCL Cocoa CoreVideo IOKit AppKit AGL MetalKit ])
Nit: might as well split the list since touching the line. This way if frameworks are added or removed in the future the diff is more granular

2024-02-17 01:26 UTC, expenses commented
> Last thing, could you please rewrite your commit log message so it matches the PR title, and squash the two commits into one.

Is this standard practice for this repo? Normally I use githubs squash-and-merge option for this.

2024-02-17 05:26 UTC, drupol commented
Please rewrite your commit log message according to the contributor guide. In the end there should be only 1 commit.

2024-02-17 05:55 UTC, drupol commented
Please mind the case.

2024-02-17 05:56 UTC, drupol commented
Here's a good place to get started: https://nix.dev/contributing/how-to-contribute.html

2024-02-17 06:10 UTC, expenses commented
> Please mind the case.

I'm not sure what you mean. Should opensubdiv be cased as `OpenSubdiv` or `Opensubdiv` or `opensubdiv`? Should metal be cased as `Metal` or `metal`? The commit conventions don't mention this. Ultimately I think that's up to the merger to change and nitpick if they wish.

2024-02-17 06:15 UTC, drupol commented
It should be `opensubdiv`. See https://search.nixos.org/packages?channel=23.11&show=opensubdiv&from=0&size=50&sort=relevance&type=packages&query=opensubdiv

And no, it's not up to the merger to do the nitpick. There are rules (even if I don't like the word) to follow, and if your PR doesn't match them it will be closed at some point.

We require contributors to be very precise and careful with those details so that the ci in place on Github is able to trigger the build and tests related to the package you're trying to update.

2024-02-17 16:58 UTC, drupol approved these changes
Thanks for implementing the changes.

2024-02-17 16:58 UTC, merged

2024-02-18 03:24 UTC, expenses commented on pkgs/development/libraries/opensubdiv/default.nix
Ah good to know