vscode-extensions.continue.continue: init at 0.8.12
NixOS/nixpkgs pull request #289289
Opened 2024-02-16 14:18 UTC by Raroh73

## Description of changes

Adds continue extension for VS Code.

Link: https://marketplace.visualstudio.com/items?itemName=Continue.continue

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-02-19 12:05 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/3471

2024-02-20 13:36 UTC, Raroh73 commented
Marked as draft because one of users found problems with how current version of extension works on NixOS.

2024-02-20 14:59 UTC, icodeforyou-dot-net commented
The one user would be me in this case, :smiley:  but I'd be much in favor of getting this into nixpkgs once we figured out what the problem and/or workaround is.

2024-02-24 21:18 UTC, icodeforyou-dot-net commented
I'd say it basically works now as far as I can tell, at least on x86-Linux.

2024-02-24 23:02 UTC, drupol requested changes

2024-02-24 23:02 UTC, drupol commented on pkgs/applications/editors/vscode/extensions/default.nix
> +            --replace 'await showTutorial();' '//await showTutorial();'
```suggestion
            --replace-fail 'await showTutorial();' '//await showTutorial();'
```

2024-02-25 10:12 UTC, drupol approved these changes

2024-02-25 16:37 UTC, merged