wstunnel-rust: init at 9.2.2
NixOS/nixpkgs pull request #289652
Opened 2024-02-18 03:45 UTC by Aleksanaa

## Description of changes

The Rust rewrite of [wstunnel](https://search.nixos.org/packages?channel=unstable&show=wstunnel&from=0&size=50&sort=relevance&type=packages&query=wstunnel) from the same author. The version of Haskell may no longer be maintained. I don't know if the new version is fully compatible with the old one, so I dare not replace it directly.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-02-18 06:49 UTC, kirillrdy commented
i wonder if we can hijack the name 

https://repology.org/project/wstunnel/versions 

cc @alyaeanyx

2024-02-18 09:58 UTC, alyaeanyx commented
Not sure whether hijacking the name is a good idea. Judging from a quick look at the new readme of wstunnel, the command line options are partially compatible (for instance -L remains the same), so scripts using wstunnel might break in unexpected ways a while after the update. IMO the best approach to this situation would be to first merge this PR, and then remove the old package and rewire the wstunnel module to the new version in a separate PR.

2024-02-18 10:01 UTC, kirillrdy commented
> Not sure whether hijacking the name is a good idea. Judging from a quick look at the new readme of wstunnel, the command line options are partially compatible (for instance -L remains the same), so scripts using wstunnel might break in unexpected ways a while after the update. IMO the best approach to this situation would be to first merge this PR, and then remove the old package and rewire the wstunnel module to the new version in a separate PR.

yes, sorry, hijacking is actually is a terrible idea from nixpkgs point of view, but from external point of view, both arch and void are somehow using wstunnel, either they never had haskell implementation or they reused the name

2024-02-18 10:05 UTC, alyaeanyx commented
Yep, a quick look St the respective repositories tells me that neither had the original Haskell version in the first place

2024-03-19 14:03 UTC, SuperSandro2000 commented
wstunnel no longer builds on nixos-unstable, so we probably should hijack the name with a release not entry, remove the old package and update the module.

2024-03-19 14:03 UTC, SuperSandro2000 commented on pkgs/by-name/ws/wstunnel-rust/package.nix
> +  version = "9.2.2";
Please update to https://github.com/erebe/wstunnel/releases/tag/v9.2.4

2024-03-19 14:04 UTC, SuperSandro2000 requested changes
please adjust the module, too as mentioned in the comment above

2024-03-19 14:04 UTC, SuperSandro2000 commented on pkgs/by-name/ws/wstunnel-rust/package.nix
> +    homepage = "https://github.com/erebe/wstunnel";
```suggestion
    homepage = "https://github.com/erebe/wstunnel";
    changelog = "https://github.com/erebe/wstunnel/releases/tag/${src.rev}";
```

2024-03-19 14:04 UTC, SuperSandro2000 commented on pkgs/by-name/ws/wstunnel-rust/package.nix
> +    platforms = platforms.unix;
```suggestion
```
that is the default for buildRustPackage

2024-06-14 05:09 UTC, closed without merging