dotnet-sdk_8: 8.0.101 -> 8.0.201, dotnet-sdk_7: 7.0.405 -> 7.0.406, dotnet-sdk: 6.0.418 -> 6.0.419
NixOS/nixpkgs pull request #289808
Opened 2024-02-18 18:58 UTC by raphaelr

## Description of changes

https://github.com/dotnet/core/blob/main/release-notes/8.0/8.0.2/8.0.2.md  
https://github.com/dotnet/core/blob/main/release-notes/7.0/7.0.16/7.0.16.md  
https://github.com/dotnet/core/blob/main/release-notes/6.0/6.0.27/6.0.27.md

Fixes CVE-2024-21386, CVE-2024-21404

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>98 packages built:</summary>
  <ul>
    <li>ArchiSteamFarm</li>
    <li>BeatSaberModManager</li>
    <li>alttpr-opentracker</li>
    <li>audiobookshelf</li>
    <li>avalonia-ilspy</li>
    <li>azure-functions-core-tools</li>
    <li>bililiverecorder</li>
    <li>boogie</li>
    <li>btcpayserver</li>
    <li>btcpayserver-altcoins</li>
    <li>celeste64</li>
    <li>certdump</li>
    <li>csharp-ls</li>
    <li>csharpier</li>
    <li>csharprepl</li>
    <li>dafny</li>
    <li>denaro</li>
    <li>depotdownloader</li>
    <li>discordchatexporter-cli</li>
    <li>dotnet-aspnetcore</li>
    <li>dotnet-aspnetcore_7</li>
    <li>dotnet-aspnetcore_8</li>
    <li>dotnet-runtime</li>
    <li>dotnet-runtime_7</li>
    <li>dotnet-runtime_8</li>
    <li>dotnet-sdk</li>
    <li>dotnet-sdk_7</li>
    <li>dotnet-sdk_8</li>
    <li>eventstore</li>
    <li>fable</li>
    <li>famistudio</li>
    <li>fantomas</li>
    <li>formula</li>
    <li>fsautocomplete</li>
    <li>galaxy-buds-client</li>
    <li>git-credential-manager</li>
    <li>github-runner</li>
    <li>godot3-mono</li>
    <li>godot3-mono-debug-server</li>
    <li>godot3-mono-export-templates</li>
    <li>godot3-mono-headless</li>
    <li>godot3-mono-headless.dev</li>
    <li>godot3-mono-headless.man</li>
    <li>godot3-mono-server</li>
    <li>godot3-mono.dev</li>
    <li>godot3-mono.man</li>
    <li>ilspycmd</li>
    <li>inklecate</li>
    <li>jackett</li>
    <li>jellyfin</li>
    <li>jetbrains.rider</li>
    <li>kavita</li>
    <li>knossosnet</li>
    <li>libation</li>
    <li>lidarr</li>
    <li>marksman</li>
    <li>mqttmultimeter</li>
    <li>msbuild</li>
    <li>naps2</li>
    <li>nbxplorer</li>
    <li>netcoredbg</li>
    <li>networkminer</li>
    <li>nuget-to-nix</li>
    <li>omnisharp-roslyn</li>
    <li>openra</li>
    <li>opentabletdriver</li>
    <li>openutau</li>
    <li>osu-lazer</li>
    <li>parabolic</li>
    <li>pbm</li>
    <li>pinta</li>
    <li>pre-commit</li>
    <li>pre-commit.dist</li>
    <li>prowlarr</li>
    <li>ps3-disc-dumper</li>
    <li>pupdate</li>
    <li>python311Packages.clr-loader</li>
    <li>python311Packages.clr-loader.dist</li>
    <li>python311Packages.pythonnet</li>
    <li>python311Packages.pythonnet.dist</li>
    <li>python312Packages.clr-loader</li>
    <li>python312Packages.clr-loader.dist</li>
    <li>python312Packages.pythonnet</li>
    <li>python312Packages.pythonnet.dist</li>
    <li>radarr</li>
    <li>readarr</li>
    <li>roslyn</li>
    <li>roslyn-ls</li>
    <li>ryujinx</li>
    <li>scarab</li>
    <li>slskd</li>
    <li>sonarr</li>
    <li>space-station-14-launcher</li>
    <li>tone</li>
    <li>torrentstream</li>
    <li>vintagestory</li>
    <li>wasabibackend</li>
    <li>xivlauncher</li>
  </ul>
</details>

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-02-19 09:23 UTC, konradmalik approved these changes
tested roslyn-ls, works fine

2024-02-19 17:01 UTC, mdarocha requested changes
Add `Microsoft.ILLink.Tasks` to the predefined nuget package list in `update.sh` if it's not yet added.

For packages that have had their `deps.nix` updated, it seems like they use multiple SDK versions at the same time. To use the global nuget packages so that they are independant of dotnet version updates, set `dotnet-sdk = dotnetCorePackages.combinePackages [ <list of required sdk packages> ]` for them. Ie. for `fsautocomplete`, set both `sdk_6_0` and `sdk_7_0`

2024-02-20 12:24 UTC, mdarocha approved these changes

2024-02-20 13:06 UTC, corngood approved these changes

2024-02-20 16:05 UTC, konradmalik approved these changes

2024-02-21 03:52 UTC, corngood requested changes

2024-02-21 03:52 UTC, corngood commented on pkgs/development/compilers/dotnet/update.sh
> +      "Microsoft.NET.ILLink.Tasks"
I think you need to make this version >= 8.  I did something similar here:

https://github.com/NixOS/nixpkgs/pull/190129/commits/b37cdccf9bcbd6bbd0fdc3f00883849e432f831c

But it probably won't get merged before this PR.

2024-02-21 03:52 UTC, corngood commented on pkgs/development/compilers/dotnet/update.sh
> +      "Microsoft.NET.ILLink.Tasks"
Error handling is currently a bit broken, so I'm not sure what will actually happen.

This is my attempt to fix the error handling: https://github.com/NixOS/nixpkgs/pull/190129/commits/6d9273e352bb0936db32784a292aa4201d335e4c

2024-02-21 03:52 UTC, corngood commented on pkgs/development/compilers/dotnet/update.sh
> +      "Microsoft.NET.ILLink.Tasks"
This doesn't actually break anything on 6 because it's (currently) the last package.  However on 7, all the `ILCompiler` packages are missing.

2024-02-21 04:30 UTC, corngood commented on pkgs/development/compilers/dotnet/update.sh
> +      "Microsoft.NET.ILLink.Tasks"
I made a PR with my update script changes: #290351

2024-02-24 10:35 UTC, LeSuisse commented
Can you rebase and resolve the conflicts so we can merge this? Thanks :+1:

2024-02-26 20:29 UTC, corngood commented
This is still missing packages in the 6/7 sdk version files (take a look at the end of the diffs), as I mentioned in my review.

I fixed that up and made #291656.  I also added a test for single-file compilation, which would have caught the missing ILLink package dependency.

2024-02-26 20:44 UTC, raphaelr commented
Yeah, i'll take a look

2024-03-03 14:39 UTC, closed without merging