KdeApplications: 17.08.0 --> 17.08.1
NixOS/nixpkgs pull request #29117
Opened 2017-09-08 14:27 UTC by bkchr

###### Motivation for this change
nox-review still running.

@ttuegel 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-09-09 16:19 UTC, ttuegel requested changes
Everything looks good, but please retitle your commit to match convention, i.e. `kdeApplications: 17.08.0 -> 17.08.1`.

2017-09-10 18:54 UTC, bkchr commented
Updated :)

2017-09-11 10:09 UTC, ttuegel approved these changes

2017-09-11 10:09 UTC, merged

2017-09-11 10:09 UTC, ttuegel commented
Thanks!