Add package river-filtile
NixOS/nixpkgs pull request #291392
Opened 2024-02-25 17:08 UTC by pkulak

## Description of changes

Added a new layout manager for the River window manager:

https://github.com/pkulak/filtile

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

Reviewed: 291198 and 291242

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-02-25 17:36 UTC, pkulak commented
> Have you tried to run this package?

Yeah, I ran it with nix-build and then ran the resulting binary. Couldn't find any docs on how to do it purely with the code written, so I did it with `with import <nixpkgs> {};` instead. But at least one guide I found recommended that strategy...

2024-02-25 18:33 UTC, IogaMaster requested changes
## Commit standard
Commits for package initialization must follow this convention:
`pkg-name: init at <version>` so in this case your commit must be.
`river-filtile: init at 1.1.0`

## Maintainer Status
It is preferred that the packages you add have a maintainer.
Consider adding yourself?

## File structure
Consider adding the package to `pkgs/by-name/ri/river-filtile/package.nix`.
If not use the `callPackage` in the `pkgs/top-level/all-packages.nix` function to include your contribution into the nixpkgs package set.

2024-02-25 18:38 UTC, IogaMaster commented
> > Have you tried to run this package?
> 
> Yeah, I ran it with nix-build and then ran the resulting binary. Couldn't find any docs on how to do it purely with the code written, so I did it with `with import <nixpkgs> {};` instead. But at least one guide I found recommended that strategy...

If your package is included into `pkgs/top-level/all-packages.nix` then you can run `nix run .#river-filtile`. You also need flakes enabled.

2024-02-25 19:06 UTC, AndersonTorres commented
Typically we test a package by running

```shell
[~/Desktop]$ nix build --show-trace --print-build-logs <nixpkgs local root>#<package name>
```

where

- `<nixpkgs local root>`  is the full path of the directory of your local Nixpkgs clone (where you will find `flake.nix`) **without** the ending slash `/`;
- `<package name>` is the name you gave to the package.
  - Usually it is the same name you put on `<nixpkgs local root>/pkgs/top-level/all-packages.nix`, like:
     ```nix
        river-filtile = callPackage ../applications/misc/river-filtile/default.nix { };
     ```

    or the most  typical alternative

     ```nix
        river-filtile = callPackage ../applications/misc/river-filtile { };
     ```

Since RFC 140, this is largely simplified: instead of using `pkgs/applications/misc/river-filtile/default.nix`, you throw this same file into `pkgs/by-name/ri/river-filtile/package.nix` (and **do not touch** all-packages.nix).

**Warning**: always `git add .` before running the building command above.

2024-02-25 19:10 UTC, AndersonTorres commented
Another style of test suite we run is `nixpkgs-review`:

```
[~/Desktop]$ nix run <nixpkgs local root>#nixpkgs-review -- pr 291392
```

The number 291392 is, precisely, the number of PR you opened.

2024-02-25 19:11 UTC, pkulak commented
Thanks so much, guys! I have to run off, but I will have all these changes done tonight.

2024-02-25 19:12 UTC, AndersonTorres requested changes

2024-02-25 19:12 UTC, AndersonTorres commented on pkgs/applications/misc/river-filtile/default.nix
> +{ lib
Move this file to `pkgs/by-name/ri/river-filtile/package.nix`

2024-02-25 22:04 UTC, IogaMaster requested changes

2024-02-25 22:06 UTC, IogaMaster reviewed
Other than that seems to work great!

This review has been done with [warden](https://github.com/iogamaster/warden), please report any issues!


<details><summary>Packages built</summary>
<p>

✅ river-filtile

### `nix-info -m` 
 - system: `"x86_64-linux"`
 - host os: `Linux 6.1.77, NixOS, 24.05 (Uakari), 24.05.20240216.5863c27`
 - multi-user?: `yes`
 - sandbox: `relaxed`
 - version: `nix-env (Nix) 2.19.3`
 - nixpkgs: `/etc/nix/inputs/nixpkgs`



</p>
</details>

2024-02-25 22:07 UTC, pkulak commented on maintainers/maintainer-list.nix
> +  pkulak = {
Separate commit, or separate pr?

2024-02-25 22:09 UTC, IogaMaster commented on maintainers/maintainer-list.nix
> +  pkulak = {
Separate commit :)

2024-02-25 22:23 UTC, IogaMaster approved these changes
LGTM!
Thanks for joining the nixpkgs family! We hope to see you around :wink:

2024-02-26 00:08 UTC, pkulak commented
Thanks again for walking me through it. It'll be more easier next time. :D

2024-02-26 16:47 UTC, AndersonTorres approved these changes
Result of `nixpkgs-review pr 291392` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>river-filtile</li>
  </ul>
</details>

2024-03-10 02:21 UTC, pkulak commented
Just bumped the version.

Maybe silly question, but with two approvals, does this get merged now?

2024-03-10 02:37 UTC, AndersonTorres commented
There are no set-in-stone requirement, but yes, two approvals is a strong indication for merge.

However, we need to seek a committer. I will ping on Discourse.

Save the link below on your bookmarks!

https://discourse.nixos.org/t/prs-already-reviewed/2617

2024-03-10 02:37 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1517

2024-03-10 04:07 UTC, pkulak commented
Thanks!

2024-04-16 14:06 UTC, pinpox commented
Minor nitpick: PR should be named `river-filtile: init at 1.2.1`, otherwise LGTM!

2024-04-16 14:06 UTC, pinpox commented
Result of `nixpkgs-review pr 291392` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>river-filtile</li>
  </ul>
</details>

2024-04-16 14:06 UTC, pinpox approved these changes

2024-05-02 11:00 UTC, merged