prismlauncher: 8.0 -> 8.1
NixOS/nixpkgs pull request #293073
Opened 2024-03-03 19:30 UTC by Scrumplex

## Description of changes

https://github.com/PrismLauncher/PrismLauncher/releases/tag/8.1

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-03-03 20:12 UTC, getchoo requested changes
we should probably add this as well to prevent issues with prism reporting a version differing from what we've set in the expression again

```nix
{
  passthru.tests.version = testers.testVersion {
    package = prismlauncher-unwrapped;
  };
}
```

2024-03-03 20:12 UTC, getchoo commented on pkgs/games/prismlauncher/default.nix
> +  version = "8.1";
```suggestion
  version = "8.2";
```

2024-03-03 20:12 UTC, getchoo commented on pkgs/games/prismlauncher/default.nix
> +    hash = "sha256-bO6xN1a4eOBKCBkn6lBwekO24JakkPW362UgZee/KMQ=";
```suggestion
    hash = "sha256-4VsoxZzi/EfEsnDvvwzg2xhj7j5B+k3gvaSqwJFDweE=";
```

2024-03-03 20:26 UTC, Scrumplex commented
the version test won't work for now, as the application needs some Qt platform plugin (i.e. wayland or xcb) to run

2024-03-03 23:47 UTC, getchoo commented
Result of `nixpkgs-review pr 293073` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>prismlauncher</li>
    <li>prismlauncher-qt5</li>
    <li>prismlauncher-qt5-unwrapped</li>
    <li>prismlauncher-unwrapped</li>
  </ul>
</details>

2024-03-03 23:47 UTC, getchoo approved these changes

2024-03-04 07:47 UTC, Minion3665 commented on pkgs/games/prismlauncher/default.nix
> +, testers
don't want to block on this, but I guess we don't need to include testers if we're not using `testVersion` mentioned earlier... otherwise all good

2024-03-04 09:00 UTC, Minion3665 approved these changes

2024-03-04 13:33 UTC, merged