Incus: Added openvswitch integration to incus service
NixOS/nixpkgs pull request #294754
Opened 2024-03-10 14:54 UTC by cmspam

If it is to be used with openvswitch, Incus requires access to the openvswitch binaries in its path, and should be started after ovs-vswitchd.service

## Description of changes
Two changes are made to the systemd service.

1. If virtualisation.vswitch is enabled, we will start incus after ovs-vswitchd.service
2. If virtualisation.vswitch is enabled, we will add virtualisation.vswtich.package to PATH

This resolves the path issues which prevent incus from deleting unnecessary virtual interfaces described here:
https://github.com/NixOS/nixpkgs/issues/290427

Apologies in advance if anything was implemented incorrectly. They are simple changes so I hope they're fine.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-03-10 15:24 UTC, adamcstephens commented
Thanks! Would you be willing to write a nixosTest for the openvswitch and incus integration?

2024-03-10 16:30 UTC, adamcstephens commented
You can see the existing tests here: https://github.com/NixOS/nixpkgs/tree/master/nixos/tests/incus

the test should exercise the integration between the two to make sure incus is working with ovs and vice versa. 

we’ll want a separate test for this, so we can add it as a test for the openvswitch package too. 

Feel free to drop in #lxc:nixos.org on matrix if you need any assistance, or ask here.

2024-03-10 19:19 UTC, cmspam commented
> You can see the existing tests here: https://github.com/NixOS/nixpkgs/tree/master/nixos/tests/incus
> 
> Run tests with `nix-build -A nixosTests.incus.preseed` for example.
> 
> the test should exercise the integration between the two to make sure incus is working with ovs and vice versa.
> 
> we’ll want a separate test for this, so we can add it as a test for the openvswitch package too.
> 
> Feel free to drop in #lxc:nixos.org on matrix if you need any assistance, or ask here.

I have looked over the tests. My initial idea would be to take the preseed test ( https://github.com/NixOS/nixpkgs/blob/master/nixos/tests/incus/preseed.nix ), but create the bridge using openvswitch. This should theoretically confirm that openvswitch integration is working, at least to the extent of creating a bridge which uses openvswitch. If openvswitch is not enabled, it should fail.

Is this kind of implementation what you're looking for?

2024-03-10 20:40 UTC, cmspam commented
Please see this pull request for the test:
https://github.com/NixOS/nixpkgs/pull/294819

I can confirm that it fails at present (incus can't find openvswitch binaries), but passes without issue with openvswitch in incus's path.

2024-03-10 21:36 UTC, adamcstephens requested changes

2024-03-10 21:36 UTC, adamcstephens commented on nixos/modules/virtualisation/incus.nix
>        requires = [
Please also add to requires.

2024-03-10 21:37 UTC, adamcstephens commented
You can add the tests commit to this branch, or we can merge this and then you'll need to rebase that PR.

2024-03-10 21:43 UTC, cmspam commented
> You can add the tests commit to this branch, or we can merge this and then you'll need to rebase that PR.

OK, I also added the tests to this branch. I will close the pull request for the tests.

2024-03-11 12:33 UTC, adamcstephens requested changes
The test file cannot be accessed currently, it will need to be added to `nixos/tests/incus/default.nix` similar to the other tests.

Please make sure you're testing the changes locally. This change does not currently eval.

It would be best if you could rebase and squash all these commits, including the fix below, into a single commit.

2024-03-11 12:33 UTC, adamcstephens commented on nixos/modules/virtualisation/incus.nix
>        path = lib.mkIf config.boot.zfs.enabled [
```suggestion
      path = lib.optional config.boot.zfs.enabled [
```

2024-03-11 12:39 UTC, adamcstephens commented
You can also [auto-close the issue if you use the github link format](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)

2024-03-11 22:44 UTC, cmspam commented
> The test file cannot be accessed currently, it will need to be added to `nixos/tests/incus/default.nix` similar to the other tests.
> 
> Please make sure you're testing the changes locally. This change does not currently eval.
> 
> It would be best if you could rebase and squash all these commits, including the fix below, into a single commit.

My apologies. I had things configured incorrectly when testing. Thank you for the fix.
I have tested everything, and rebased and squash as you requested.

2024-03-12 00:45 UTC, adamcstephens commented
This looks good, but unfortunately you'll need to make one more change. The commit message will need to be reworded to meet convention. https://github.com/NixOS/nixpkgs/blob/master/nixos/README.md#commit-conventions

Perhaps something like:

> nixos/incus: add openvswitch integration and test

2024-03-12 01:06 UTC, cmspam commented
> This looks good, but unfortunately you'll need to make one more change. The commit message will need to be reworded to meet convention. https://github.com/NixOS/nixpkgs/blob/master/nixos/README.md#commit-conventions
> 
> Perhaps something like:
> 
> > nixos/incus: add openvswitch support

OK, it's fixed. Sorry I overlooked too many things in the process and waste much of your time. It was a good learning experience for me. Perhaps we are finally there?

2024-03-12 02:56 UTC, adamcstephens approved these changes

2024-03-12 02:56 UTC, merged

2024-03-12 02:57 UTC, adamcstephens commented
Thanks for your contribution. :) It wasn't a waste in my opinion, and we all had to learn the details of packaging for nixpkgs to get here.

2024-03-12 16:57 UTC, azahi commented
Looks like this PR introduced a regression for ZFS on `nixpkgs-unstable`. It currently errors out for me when I try to `nixos-switch`:
```
       error: A definition for option `systemd.services.incus.path."[definition 1-entry 1]"' is not of type `package or string'. Definition values:
       - In `/nix/store/xcadl56qxa44l2z40aabfsi1adlgn62y-source/nixos/modules/virtualisation/incus.nix':
           [
             <derivation zfs-user-2.2.3>
             "/nix/store/m2wcww4zhbkymywbihxgnp40adkmfm06-zfs-user-2.2.3/lib/udev"
           ]
```

Reverting this hunk seems to fix the issue:
```diff
diff --git i/nixos/modules/virtualisation/incus.nix w/nixos/modules/virtualisation/incus.nix
index 74217b2411ac..347cadd6a2e5 100644
--- i/nixos/modules/virtualisation/incus.nix
+++ w/nixos/modules/virtualisation/incus.nix
@@ -177,11 +177,10 @@ in
         "network-online.target"
       ];
 
-      path = lib.optional config.boot.zfs.enabled [
+      path = lib.mkIf config.boot.zfs.enabled [
         config.boot.zfs.package
         "${config.boot.zfs.package}/lib/udev"
-      ]
-        ++ lib.optional config.virtualisation.vswitch.enable config.virtualisation.vswitch.package;
+      ];
 
       environment = lib.mkMerge [ {
         # Override Path to the LXC template configuration directory
```

2024-03-12 17:01 UTC, azahi commented
Oh, I figured it out. It should be `lib.optionas`, not `lib.optional`.