python3Packages.pre-commit-po-hooks: init at 1.7.3
NixOS/nixpkgs pull request #295568
Opened 2024-03-13 10:08 UTC by yajo

## Description of changes
Packaged it.

@moduon MT-1075

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-01 11:56 UTC, FliegendeWurst requested changes

2024-11-01 11:56 UTC, FliegendeWurst commented on pkgs/development/python-modules/pre-commit-po-hooks/default.nix
> +  disabled = pythonOlder "3.6";
```suggestion
```
We don't have that old Python versions in nixpkgs.

2024-11-01 11:56 UTC, FliegendeWurst commented on pkgs/development/python-modules/pre-commit-po-hooks/default.nix
> +, buildPythonPackage
Please format with the official formatter.

2024-11-01 11:56 UTC, FliegendeWurst commented on pkgs/development/python-modules/pre-commit-po-hooks/default.nix
> +    maintainers = with maintainers; [ yajo ];
```suggestion
  meta = {
    description = "Hooks for pre-commit useful working with PO files";
    homepage = "https://github.com/mondeja/pre-commit-po-hooks";
    license = lib.licenses.bsd3;
    maintainers = with lib.maintainers; [ yajo ];
```

2024-11-06 10:47 UTC, yajo commented
All attended.

2024-11-06 11:25 UTC, FliegendeWurst approved these changes

2024-11-06 11:25 UTC, FliegendeWurst commented on pkgs/development/python-modules/pre-commit-po-hooks/default.nix
> +    repo = pname;
```suggestion
    repo = "pre-commit-po-hooks";
```
#277994

2024-11-07 10:25 UTC, natsukium requested changes

2024-11-07 10:25 UTC, natsukium commented on pkgs/development/python-modules/pre-commit-po-hooks/default.nix
> +  nativeBuildInputs = [ pytestCheckHook ];
```suggestion
  nativeCheckInputs = [ pytestCheckHook ];
```

2024-11-07 10:30 UTC, natsukium commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 295568`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python311Packages.pre-commit-po-hooks</li>
    <li>python312Packages.pre-commit-po-hooks</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python311Packages.pre-commit-po-hooks</li>
    <li>python312Packages.pre-commit-po-hooks</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python311Packages.pre-commit-po-hooks</li>
    <li>python312Packages.pre-commit-po-hooks</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>python311Packages.pre-commit-po-hooks</li>
    <li>python312Packages.pre-commit-po-hooks</li>
  </ul>
</details>

2024-11-07 11:30 UTC, natsukium approved these changes
LGTM, thanks.

2024-12-15 21:59 UTC, merged