dipc: init at 1.0.0
NixOS/nixpkgs pull request #296404
Opened 2024-03-16 12:35 UTC by ByteSudoer

## Description of changes

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-03-17 18:31 UTC, lolbinarycat requested changes

2024-03-17 18:31 UTC, lolbinarycat commented on pkgs/by-name/di/dipc/package.nix
> +  pname = "depc";
typo?

2024-03-17 18:31 UTC, lolbinarycat commented on pkgs/by-name/di/dipc/package.nix
> +}
```suggestion
  };
}
```

2024-03-17 18:31 UTC, lolbinarycat commented on pkgs/by-name/di/dipc/package.nix
> +    license = licenses.free;
```suggestion
    license = with licenses; [ mit free ];
```

not actually entirely sure how to model this correctly

2024-03-17 18:38 UTC, ByteSudoer commented
@lolbinarycat Thank you for pointing out to those typos. Everything has been fixed as suggested.

2024-03-17 18:41 UTC, lolbinarycat requested changes
few more issues

2024-03-17 18:41 UTC, lolbinarycat commented on pkgs/by-name/di/dipc/package.nix
> +    description = "Convert your favorite images and wallpapers with your favorite color palettes/themes ";
```suggestion
    description = "Convert your favorite images and wallpapers with your favorite color palettes/themes";
```

2024-03-17 18:41 UTC, lolbinarycat commented on pkgs/by-name/di/dipc/package.nix
> +  meta = with lib; {
```suggestion
  cargoHash = "sha256-t+G8eQufZPge9vyz6jdET7PZ76eQkCyPt0m2CYzIuD0=";

  meta = with lib; {
```

2024-03-17 18:44 UTC, ByteSudoer commented
Fixed. It 's quite strange that the formatter could not delete out those extra empty lines. Thx again

2024-03-17 18:48 UTC, lolbinarycat commented
ok, looks good, do you think you could squash the commits and make them fit [the commit conventions](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions)?

there should be one commit adding yourself as a maintainer, and one commit adding the package.

2024-03-17 18:52 UTC, ByteSudoer commented
@lolbinarycat  I think squashing the commits would require a new pull request and that would force the rebuild on every task for the CI/CD chain

2024-03-17 18:58 UTC, lolbinarycat commented
if you use `git push --force` it will update the existing PR (however, the old commits will disappear, so make sure everything is correct before you do)

the hard part is getting your local state setup properly, apparently this is doable with `git rebase -i`.  personally i always ended up doing things manually with `git format-patch` and `git am`

before trying to rebase, you can use `git branch -c` to create a backup of the pre-rebase branch.

2024-03-17 18:59 UTC, lolbinarycat approved these changes

2024-03-20 00:24 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/3656

2024-03-20 02:34 UTC, quantenzitrone requested changes

2024-03-20 02:34 UTC, quantenzitrone commented on pkgs/by-name/di/dipc/package.nix
> +    license = with licenses; [ mit free ];
```suggestion
    license = with licenses; [ mit asl20 ];
```
> dipc is dual-licensed under the terms of both the MIT License and the Apache License 2.0
> 
> SPDX-License-Identifier: MIT OR Apache-2.0

2024-03-20 03:12 UTC, quantenzitrone commented
Result of `nixpkgs-review pr 296404` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>dipc</li>
  </ul>
</details>

2024-03-20 03:18 UTC, ByteSudoer commented
Thx for pointing that out. I will fix it as soon as possible.

2024-03-20 22:45 UTC, lolbinarycat approved these changes

2024-03-20 23:59 UTC, quantenzitrone commented
Result of `nixpkgs-review pr 296404` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dipc</li>
  </ul>
</details>

2024-03-20 23:59 UTC, quantenzitrone approved these changes

2024-03-23 16:28 UTC, SuperSandro2000 requested changes, later dismissed
Please clean up the commit history according to the contributing guide.

2024-03-23 22:01 UTC, ByteSudoer commented
@SuperSandro2000 I squashed the commits based on the descriptions in the contribution guidelines. Sorry for the inconvenience. I will re-request a review. Thx

2024-03-23 22:11 UTC, lolbinarycat approved these changes

2024-03-26 18:12 UTC, lolbinarycat approved these changes

2024-03-27 10:13 UTC, merged