thrift: 0.18.1 -> 0.19.0
NixOS/nixpkgs pull request #296770
Opened 2024-03-17 21:59 UTC by anthonyroussel

## Description of changes

https://github.com/apache/thrift/compare/v0.18.1...v0.19.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-03-18 16:34 UTC, bjornfor commented
Result of `nixpkgs-review pr 296770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>32 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>databricks-sql-cli</li>
    <li>databricks-sql-cli.dist</li>
    <li>python311Packages.apache-beam</li>
    <li>python311Packages.apache-beam.dist</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>python311Packages.databricks-sql-connector</li>
    <li>python311Packages.databricks-sql-connector.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.farm-haystack</li>
    <li>python311Packages.farm-haystack.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
    <li>python311Packages.tensorflow-datasets</li>
    <li>python311Packages.tensorflow-datasets.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.databricks-sql-connector</li>
    <li>python312Packages.databricks-sql-connector.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
    <li>worldengine-cli</li>
    <li>worldengine-cli.dist</li>
  </ul>
</details>
<details>
  <summary>493 packages failed to build:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile (apacheHttpdPackages_2_4.mod_tile)</li>
    <li>arrow-cpp</li>
    <li>arrow-glib</li>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev (ceph-dev.dev)</li>
    <li>ceph.doc (ceph-dev.doc)</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man (ceph-dev.man)</li>
    <li>cloudcompare</li>
    <li>csvkit</li>
    <li>csvkit.dist</li>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>deface</li>
    <li>deface.dist</li>
    <li>easyocr (python311Packages.easyocr)</li>
    <li>easyocr.dist (python311Packages.easyocr.dist)</li>
    <li>entwine</li>
    <li>gdal (python311Packages.gdal)</li>
    <li>gmt</li>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradio3_8</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.grnet</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gnuradio3_8Packages.osmosdr.dev</li>
    <li>gnuradio3_8Packages.rds</li>
    <li>gnuradio3_9</li>
    <li>gnuradio3_9Packages.grnet</li>
    <li>gnuradio3_9Packages.osmosdr</li>
    <li>gnuradio3_9Packages.osmosdr.dev</li>
    <li>gnuradioPackages.osmosdr</li>
    <li>gnuradioPackages.osmosdr.dev</li>
    <li>gplates</li>
    <li>grass</li>
    <li>haskellPackages.hgdal</li>
    <li>haskellPackages.hgdal.doc</li>
    <li>home-assistant-component-tests.dremel_3d_printer</li>
    <li>home-assistant-component-tests.environment_canada</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>intensity-normalization (python311Packages.intensity-normalization)</li>
    <li>intensity-normalization.dist (python311Packages.intensity-normalization.dist)</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>merkaartor</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>mysql-workbench</li>
    <li>napari (python311Packages.napari)</li>
    <li>napari.dist (python311Packages.napari.dist)</li>
    <li>octavePackages.mapping</li>
    <li>ome_zarr (python311Packages.ome-zarr)</li>
    <li>ome_zarr.dist (python311Packages.ome-zarr.dist)</li>
    <li>open-interpreter (python311Packages.open-interpreter)</li>
    <li>open-interpreter.dist (python311Packages.open-interpreter.dist)</li>
    <li>openai-whisper (python311Packages.openai-whisper)</li>
    <li>openai-whisper.dist (python311Packages.openai-whisper.dist)</li>
    <li>openorienteering-mapper</li>
    <li>paraview</li>
    <li>parquet-tools</li>
    <li>parquet-tools.dist</li>
    <li>pdal</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>perl538Packages.Tirex</li>
    <li>perl538Packages.Tirex.devdoc</li>
    <li>python311Packages.accelerate</li>
    <li>python311Packages.accelerate.dist</li>
    <li>python311Packages.agate-sql</li>
    <li>python311Packages.agate-sql.dist</li>
    <li>python311Packages.albumentations</li>
    <li>python311Packages.albumentations.dist</li>
    <li>python311Packages.anthropic</li>
    <li>python311Packages.anthropic.dist</li>
    <li>python311Packages.aplpy</li>
    <li>python311Packages.aplpy.dist</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argos-translate-files.dist</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.argostranslate.dist</li>
    <li>python311Packages.autofaiss</li>
    <li>python311Packages.autofaiss.dist</li>
    <li>python311Packages.awkward</li>
    <li>python311Packages.awkward.dist</li>
    <li>python311Packages.awswrangler</li>
    <li>python311Packages.awswrangler.dist</li>
    <li>python311Packages.batchgenerators</li>
    <li>python311Packages.batchgenerators.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.caffe</li>
    <li>python311Packages.caffe.bin</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python311Packages.casa-formats-io</li>
    <li>python311Packages.casa-formats-io.dist</li>
    <li>python311Packages.cf-xarray</li>
    <li>python311Packages.cf-xarray.dist</li>
    <li>python311Packages.chromadb</li>
    <li>python311Packages.chromadb.dist</li>
    <li>python311Packages.cleanlab</li>
    <li>python311Packages.cleanlab.dist</li>
    <li>python311Packages.clifford</li>
    <li>python311Packages.clifford.dist</li>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.correctionlib</li>
    <li>python311Packages.correctionlib.dist</li>
    <li>python311Packages.crate</li>
    <li>python311Packages.crate.dist</li>
    <li>python311Packages.ctranslate2</li>
    <li>python311Packages.ctranslate2.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.dask</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.dask-gateway</li>
    <li>python311Packages.dask-gateway.dist</li>
    <li>python311Packages.dask-glm</li>
    <li>python311Packages.dask-glm.dist</li>
    <li>python311Packages.dask-histogram</li>
    <li>python311Packages.dask-histogram.dist</li>
    <li>python311Packages.dask-image</li>
    <li>python311Packages.dask-image.dist</li>
    <li>python311Packages.dask-jobqueue</li>
    <li>python311Packages.dask-jobqueue.dist</li>
    <li>python311Packages.dask-ml</li>
    <li>python311Packages.dask-ml.dist</li>
    <li>python311Packages.dask-mpi</li>
    <li>python311Packages.dask-mpi.dist</li>
    <li>python311Packages.dask-yarn</li>
    <li>python311Packages.dask-yarn.dist</li>
    <li>python311Packages.dask.dist</li>
    <li>python311Packages.datafusion</li>
    <li>python311Packages.datafusion.dist</li>
    <li>python311Packages.datasets</li>
    <li>python311Packages.datasets.dist</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.datashader.dist</li>
    <li>python311Packages.db-dtyp [...]

2024-03-18 16:41 UTC, bjornfor requested changes
> 493 packages failed to build:

Looks like thrift itself fails, and then all dependees are marked as failed too.

2024-03-18 20:52 UTC, anthonyroussel commented
Fixed the failing locales tests on *-linux platforms.
`glibLocales` was required in nativeCheckInputs.

I still have to investigate why the `python_test` test is failing.

2024-04-07 19:20 UTC, anthonyroussel commented
Update thrift to 0.20: https://github.com/apache/thrift/compare/v0.18.1...v0.20.0

2024-04-17 20:12 UTC, anthonyroussel commented
Rebased against master

2024-04-28 03:59 UTC, tobim commented
Result of `nixpkgs-review pr 296770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>44 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>databricks-sql-cli</li>
    <li>databricks-sql-cli.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>python311Packages.apache-beam</li>
    <li>python311Packages.apache-beam.dist</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>python311Packages.clifford</li>
    <li>python311Packages.clifford.dist</li>
    <li>python311Packages.databricks-sql-connector</li>
    <li>python311Packages.databricks-sql-connector.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.farm-haystack</li>
    <li>python311Packages.farm-haystack.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
    <li>python311Packages.tensorflow-datasets</li>
    <li>python311Packages.tensorflow-datasets.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.clifford</li>
    <li>python312Packages.clifford.dist</li>
    <li>python312Packages.databricks-sql-connector</li>
    <li>python312Packages.databricks-sql-connector.dist</li>
    <li>python312Packages.farm-haystack</li>
    <li>python312Packages.farm-haystack.dist</li>
    <li>python312Packages.sunpy</li>
    <li>python312Packages.sunpy.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
    <li>worldengine-cli</li>
    <li>worldengine-cli.dist</li>
  </ul>
</details>
<details>
  <summary>441 packages failed to build:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile (apacheHttpdPackages_2_4.mod_tile)</li>
    <li>arrow-cpp</li>
    <li>arrow-glib</li>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>ceph (ceph-dev)</li>
    <li>ceph-client</li>
    <li>ceph-csi</li>
    <li>ceph.dev (ceph-dev.dev)</li>
    <li>ceph.doc (ceph-dev.doc)</li>
    <li>libceph (ceph.lib ,libceph.dev ,libceph.doc ,libceph.lib ,libceph.man)</li>
    <li>ceph.man (ceph-dev.man)</li>
    <li>cloudcompare</li>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>entwine</li>
    <li>gdal (python311Packages.gdal)</li>
    <li>gmt</li>
    <li>gnss-sdr</li>
    <li>gnuradio</li>
    <li>gnuradio3_8</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.grnet</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gnuradio3_8Packages.osmosdr.dev</li>
    <li>gnuradio3_8Packages.rds</li>
    <li>gnuradio3_9</li>
    <li>gnuradio3_9Packages.grnet</li>
    <li>gnuradio3_9Packages.osmosdr</li>
    <li>gnuradio3_9Packages.osmosdr.dev</li>
    <li>gnuradioPackages.osmosdr</li>
    <li>gnuradioPackages.osmosdr.dev</li>
    <li>gplates</li>
    <li>grass</li>
    <li>haskellPackages.hgdal</li>
    <li>haskellPackages.hgdal.doc</li>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>merkaartor</li>
    <li>mlflow-server</li>
    <li>mlflow-server.dist</li>
    <li>mysql-workbench</li>
    <li>napari (python311Packages.napari)</li>
    <li>napari.dist (python311Packages.napari.dist)</li>
    <li>octavePackages.mapping</li>
    <li>ome_zarr (python311Packages.ome-zarr)</li>
    <li>ome_zarr.dist (python311Packages.ome-zarr.dist)</li>
    <li>open-interpreter (python311Packages.open-interpreter)</li>
    <li>open-interpreter.dist (python311Packages.open-interpreter.dist)</li>
    <li>openorienteering-mapper</li>
    <li>paraview</li>
    <li>parquet-tools</li>
    <li>parquet-tools.dist</li>
    <li>pdal</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>perl538Packages.Tirex</li>
    <li>perl538Packages.Tirex.devdoc</li>
    <li>python311Packages.accelerate</li>
    <li>python311Packages.accelerate.dist</li>
    <li>python311Packages.anthropic</li>
    <li>python311Packages.anthropic.dist</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argos-translate-files.dist</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.argostranslate.dist</li>
    <li>python311Packages.autofaiss</li>
    <li>python311Packages.autofaiss.dist</li>
    <li>python311Packages.awkward</li>
    <li>python311Packages.awkward.dist</li>
    <li>python311Packages.awswrangler</li>
    <li>python311Packages.awswrangler.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python311Packages.chromadb</li>
    <li>python311Packages.chromadb.dist</li>
    <li>python311Packages.cleanlab</li>
    <li>python311Packages.cleanlab.dist</li>
    <li>python311Packages.coffea</li>
    <li>python311Packages.coffea.dist</li>
    <li>python311Packages.correctionlib</li>
    <li>python311Packages.correctionlib.dist</li>
    <li>python311Packages.ctranslate2</li>
    <li>python311Packages.ctranslate2.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.dask-awkward</li>
    <li>python311Packages.dask-awkward.dist</li>
    <li>python311Packages.dask-image</li>
    <li>python311Packages.dask-image.dist</li>
    <li>python311Packages.datafusion</li>
    <li>python311Packages.datafusion.dist</li>
    <li>python311Packages.datasets</li>
    <li>python311Packages.datasets.dist</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.datashader.dist</li>
    <li>python311Packages.db-dtypes</li>
    <li>python311Packages.db-dtypes.dist</li>
    <li>python311Packages.dbt-bigquery</li>
    <li>python311Packages.dbt-bigquery.dist</li>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.django-bootstrap4</li>
    <li>python311Packages.django-bootstrap4.dist</li>
    <li>python311Packages.dvc-hdfs</li>
    <li>python311Packages.dvc-hdfs.dist</li>
    <li>python311Packages.embedding-reader</li>
    <li>python311Packages.embedding-reader.dist</li>
    <li>python311Packages.evaluate</li>
    <li>python311Packages.evaluate.dist</li>
    <li>python311Packages.fastai</li>
    <li>python311Packages.fastai.dist</li>
    <li>python311Packages.fastembed</li>
    <li>python311Packages.fastembed.dist</li>
    <li>python311Packages.faster-whisper</li>
    <li>python311Packages.faster-whisper.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.google-cloud-bigquery</li>
    <li>python311Packages.google-cloud-bigquery.dist</li>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python311Packages.gymnasium</li>
    <li>python311Packages.gymnasium.dist</li>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
    <li>python311Packages.influxdb3-python</li>
    <li>python311Packages.influxdb3-python.dist</li>
    [...]

2024-07-12 18:46 UTC, anthonyroussel commented
@ofborg build thrift

2024-07-12 21:00 UTC, anthonyroussel commented
Result of `nixpkgs-review pr 296770` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>49 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>gplates</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>python311Packages.apache-beam</li>
    <li>python311Packages.apache-beam.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.cleanlab</li>
    <li>python311Packages.cleanlab.dist</li>
    <li>python311Packages.databricks-sql-connector</li>
    <li>python311Packages.databricks-sql-connector.dist</li>
    <li>python311Packages.haystack-ai</li>
    <li>python311Packages.haystack-ai.dist</li>
    <li>python311Packages.libretranslate</li>
    <li>python311Packages.libretranslate.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.tinygrad</li>
    <li>python311Packages.tinygrad.dist</li>
    <li>python311Packages.vqgan-jax</li>
    <li>python311Packages.vqgan-jax.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.apache-beam</li>
    <li>python312Packages.apache-beam.dist</li>
    <li>python312Packages.bsuite</li>
    <li>python312Packages.bsuite.dist</li>
    <li>python312Packages.haystack-ai</li>
    <li>python312Packages.haystack-ai.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.tinygrad</li>
    <li>python312Packages.tinygrad.dist</li>
    <li>python312Packages.txtai</li>
    <li>python312Packages.txtai.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
    <li>sumo</li>
    <li>vpv</li>
    <li>whisper-ctranslate2</li>
    <li>whisper-ctranslate2.dist</li>
  </ul>
</details>
<details>
  <summary>133 packages failed to build:</summary>
  <ul>
    <li>browsr</li>
    <li>browsr.dist</li>
    <li>dbx</li>
    <li>dbx.dist</li>
    <li>gnuradio</li>
    <li>gnuradio3_8</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.grnet</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gnuradio3_8Packages.osmosdr.dev</li>
    <li>gnuradio3_8Packages.rds</li>
    <li>gnuradio3_9</li>
    <li>gnuradio3_9Packages.grnet</li>
    <li>gnuradio3_9Packages.osmosdr</li>
    <li>gnuradio3_9Packages.osmosdr.dev</li>
    <li>gnuradioPackages.osmosdr</li>
    <li>gnuradioPackages.osmosdr.dev</li>
    <li>mapnik</li>
    <li>octavePackages.mapping</li>
    <li>open-interpreter (python312Packages.open-interpreter)</li>
    <li>open-interpreter.dist (python312Packages.open-interpreter.dist)</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>pentestgpt</li>
    <li>pentestgpt.dist</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>perl538Packages.Tirex</li>
    <li>perl538Packages.Tirex.devdoc</li>
    <li>python311Packages.awswrangler</li>
    <li>python311Packages.awswrangler.dist</li>
    <li>python311Packages.cohere</li>
    <li>python311Packages.cohere.dist</li>
    <li>python311Packages.datashader</li>
    <li>python311Packages.datashader.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.intake</li>
    <li>python311Packages.intake.dist</li>
    <li>python311Packages.jupysql</li>
    <li>python311Packages.jupysql.dist</li>
    <li>python311Packages.langchain</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.langchain-community</li>
    <li>python311Packages.langchain-community.dist</li>
    <li>python311Packages.langchain-core</li>
    <li>python311Packages.langchain-core.dist</li>
    <li>python311Packages.langchain-text-splitters</li>
    <li>python311Packages.langchain-text-splitters.dist</li>
    <li>python311Packages.langchain.dist</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.layoutparser.dist</li>
    <li>python311Packages.litellm</li>
    <li>python311Packages.litellm.dist</li>
    <li>python311Packages.llmx</li>
    <li>python311Packages.llmx.dist</li>
    <li>python311Packages.momepy</li>
    <li>python311Packages.momepy.dist</li>
    <li>python311Packages.open-interpreter</li>
    <li>python311Packages.open-interpreter.dist</li>
    <li>python311Packages.optimum</li>
    <li>python311Packages.optimum.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.outlines</li>
    <li>python311Packages.outlines.dist</li>
    <li>python311Packages.pandas-stubs</li>
    <li>python311Packages.pandas-stubs.dist</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.pdfplumber.dist</li>
    <li>python311Packages.python-mapnik</li>
    <li>python311Packages.python-mapnik.dist</li>
    <li>python311Packages.rio-tiler</li>
    <li>python311Packages.rio-tiler.dist</li>
    <li>python311Packages.rioxarray</li>
    <li>python311Packages.rioxarray.dist</li>
    <li>python311Packages.streamz</li>
    <li>python311Packages.streamz.dist</li>
    <li>python311Packages.vector</li>
    <li>python311Packages.vector.dist</li>
    <li>python311Packages.ydata-profiling</li>
    <li>python311Packages.ydata-profiling.dist</li>
    <li>python312Packages.autofaiss</li>
    <li>python312Packages.autofaiss.dist</li>
    <li>python312Packages.awswrangler</li>
    <li>python312Packages.awswrangler.dist</li>
    <li>python312Packages.cohere</li>
    <li>python312Packages.cohere.dist</li>
    <li>python312Packages.folium</li>
    <li>python312Packages.folium.dist</li>
    <li>python312Packages.ibis-framework</li>
    <li>python312Packages.ibis-framework.dist</li>
    <li>python312Packages.langchain</li>
    <li>python312Packages.langchain-chroma</li>
    <li>python312Packages.langchain-chroma.dist</li>
    <li>python312Packages.langchain-community</li>
    <li>python312Packages.langchain-community.dist</li>
    <li>python312Packages.langchain-core</li>
    <li>python312Packages.langchain-core.dist</li>
    <li>python312Packages.langchain-text-splitters</li>
    <li>python312Packages.langchain-text-splitters.dist</li>
    <li>python312Packages.langchain.dist</li>
    <li>python312Packages.layoutparser</li>
    <li>python312Packages.layoutparser.dist</li>
    <li>python312Packages.litellm</li>
    <li>python312Packages.litellm.dist</li>
    <li>python312Packages.llmx</li>
    <li>python312Packages.llmx.dist</li>
    <li>python312Packages.momepy</li>
    <li>python312Packages.momepy.dist</li>
    <li>python312Packages.optimum</li>
    <li>python312Packages.optimum.dist</li>
    <li>python312Packages.osmnx</li>
    <li>python312Packages.osmnx.dist</li>
    <li>python312Packages.outlines</li>
    <li>python312Packages.outlines.dist</li>
    <li>python312Packages.pandas-stubs</li>
    <li>python312Packages.pandas-stubs.dist</li>
    <li>python312Packages.pdfplumber</li>
    <li>python312Packages.pdfplumber.dist</li>
    <li>python312Packages.rio-tiler</li>
    <li>python312Packages.rio-tiler.dist</li>
    <li>python312Packages.rioxarray</li>
    <li>python312Packages.rioxarray.dist</li>
    <li>python312Packages.streamz</li>
    <li>python312Packages.streamz.dist</li>
    <li>python312Packages.vector</li>
    <li>python312Packages.vector.dist</li>
    <li>python312Packages.ydata-profiling</li>
    <li>python312Packages.ydata-profiling.dist</li>
    <li>visidata</li>
    <li>visidata.dist</li>
  </ul>
</details>
<details>
  <summary>293 packages built:</summary>
  <ul>
    <li>arrow-cpp</li>
    <l [...]

2024-07-12 21:05 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4242

2024-07-14 19:29 UTC, gador commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 296770` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
128 packages marked as broken and skipped:
</summary>
<ul>
<li>chatgpt-retrieval-plugin</li>
<li>chatgpt-retrieval-plugin.dist</li>
<li>khoj</li>
<li>khoj.dist</li>
<li>python311Packages.apache-beam</li>
<li>python311Packages.apache-beam.dist</li>
<li>python311Packages.dalle-mini</li>
<li>python311Packages.dalle-mini.dist</li>
<li>python311Packages.databricks-sql-connector</li>
<li>python311Packages.databricks-sql-connector.dist</li>
<li>python311Packages.dm-sonnet</li>
<li>python311Packages.dm-sonnet.dist</li>
<li>python311Packages.fastai</li>
<li>python311Packages.fastai.dist</li>
<li>python311Packages.haystack-ai</li>
<li>python311Packages.haystack-ai.dist</li>
<li>python311Packages.k-diffusion</li>
<li>python311Packages.k-diffusion.dist</li>
<li>python311Packages.llama-index</li>
<li>python311Packages.llama-index-agent-openai</li>
<li>python311Packages.llama-index-agent-openai.dist</li>
<li>python311Packages.llama-index-cli</li>
<li>python311Packages.llama-index-cli.dist</li>
<li>python311Packages.llama-index-core</li>
<li>python311Packages.llama-index-core.dist</li>
<li>python311Packages.llama-index-embeddings-gemini</li>
<li>python311Packages.llama-index-embeddings-gemini.dist</li>
<li>python311Packages.llama-index-embeddings-google</li>
<li>python311Packages.llama-index-embeddings-google.dist</li>
<li>python311Packages.llama-index-embeddings-huggingface</li>
<li>python311Packages.llama-index-embeddings-huggingface.dist</li>
<li>python311Packages.llama-index-embeddings-ollama</li>
<li>python311Packages.llama-index-embeddings-ollama.dist</li>
<li>python311Packages.llama-index-embeddings-openai</li>
<li>python311Packages.llama-index-embeddings-openai.dist</li>
<li>python311Packages.llama-index-graph-stores-nebula</li>
<li>python311Packages.llama-index-graph-stores-nebula.dist</li>
<li>python311Packages.llama-index-graph-stores-neo4j</li>
<li>python311Packages.llama-index-graph-stores-neo4j.dist</li>
<li>python311Packages.llama-index-graph-stores-neptune</li>
<li>python311Packages.llama-index-graph-stores-neptune.dist</li>
<li>python311Packages.llama-index-indices-managed-llama-cloud</li>
<li>python311Packages.llama-index-indices-managed-llama-cloud.dist</li>
<li>python311Packages.llama-index-legacy</li>
<li>python311Packages.llama-index-legacy.dist</li>
<li>python311Packages.llama-index-llms-ollama</li>
<li>python311Packages.llama-index-llms-ollama.dist</li>
<li>python311Packages.llama-index-llms-openai</li>
<li>python311Packages.llama-index-llms-openai-like</li>
<li>python311Packages.llama-index-llms-openai-like.dist</li>
<li>python311Packages.llama-index-llms-openai.dist</li>
<li>python311Packages.llama-index-multi-modal-llms-openai</li>
<li>python311Packages.llama-index-multi-modal-llms-openai.dist</li>
<li>python311Packages.llama-index-program-openai</li>
<li>python311Packages.llama-index-program-openai.dist</li>
<li>python311Packages.llama-index-question-gen-openai</li>
<li>python311Packages.llama-index-question-gen-openai.dist</li>
<li>python311Packages.llama-index-readers-database</li>
<li>python311Packages.llama-index-readers-database.dist</li>
<li>python311Packages.llama-index-readers-file</li>
<li>python311Packages.llama-index-readers-file.dist</li>
<li>python311Packages.llama-index-readers-json</li>
<li>python311Packages.llama-index-readers-json.dist</li>
<li>python311Packages.llama-index-readers-llama-parse</li>
<li>python311Packages.llama-index-readers-llama-parse.dist</li>
<li>python311Packages.llama-index-readers-s3</li>
<li>python311Packages.llama-index-readers-s3.dist</li>
<li>python311Packages.llama-index-readers-twitter</li>
<li>python311Packages.llama-index-readers-twitter.dist</li>
<li>python311Packages.llama-index-readers-txtai</li>
<li>python311Packages.llama-index-readers-txtai.dist</li>
<li>python311Packages.llama-index-readers-weather</li>
<li>python311Packages.llama-index-readers-weather.dist</li>
<li>python311Packages.llama-index-vector-stores-chroma</li>
<li>python311Packages.llama-index-vector-stores-chroma.dist</li>
<li>python311Packages.llama-index-vector-stores-google</li>
<li>python311Packages.llama-index-vector-stores-google.dist</li>
<li>python311Packages.llama-index-vector-stores-postgres</li>
<li>python311Packages.llama-index-vector-stores-postgres.dist</li>
<li>python311Packages.llama-index-vector-stores-qdrant</li>
<li>python311Packages.llama-index-vector-stores-qdrant.dist</li>
<li>python311Packages.llama-index.dist</li>
<li>python311Packages.llama-parse</li>
<li>python311Packages.llama-parse.dist</li>
<li>python311Packages.openllm</li>
<li>python311Packages.openllm.dist</li>
<li>python311Packages.private-gpt</li>
<li>python311Packages.private-gpt.dist</li>
<li>python311Packages.shimmy</li>
<li>python311Packages.shimmy.dist</li>
<li>python311Packages.skrl</li>
<li>python311Packages.skrl.dist</li>
<li>python311Packages.spacy</li>
<li>python311Packages.spacy-loggers</li>
<li>python311Packages.spacy-loggers.dist</li>
<li>python311Packages.spacy-lookups-data</li>
<li>python311Packages.spacy-lookups-data.dist</li>
<li>python311Packages.spacy-transformers</li>
<li>python311Packages.spacy-transformers.dist</li>
<li>python311Packages.spacy.dist</li>
<li>python311Packages.tensorflow-datasets</li>
<li>python311Packages.tensorflow-datasets.dist</li>
<li>python311Packages.textacy</li>
<li>python311Packages.textacy.dist</li>
<li>python311Packages.textnets</li>
<li>python311Packages.textnets.dist</li>
<li>python311Packages.vllm</li>
<li>python311Packages.vllm.dist</li>
<li>python311Packages.wandb</li>
<li>python311Packages.wandb.dist</li>
<li>python311Packages.worldengine</li>
<li>python311Packages.worldengine.dist</li>
<li>python312Packages.apache-beam</li>
<li>python312Packages.apache-beam.dist</li>
<li>python312Packages.haystack-ai</li>
<li>python312Packages.haystack-ai.dist</li>
<li>python312Packages.openllm</li>
<li>python312Packages.openllm.dist</li>
<li>python312Packages.txtai</li>
<li>python312Packages.txtai.dist</li>
<li>python312Packages.vllm</li>
<li>python312Packages.vllm.dist</li>
<li>python312Packages.worldengine</li>
<li>python312Packages.worldengine.dist</li>
<li>whisper-ctranslate2</li>
<li>whisper-ctranslate2.dist</li>
<li>worldengine-cli</li>
<li>worldengine-cli.dist</li>
</ul>
</details>
<details>

  <summary>42 packages failed to build and already failed to build on hydra master:</summary>
  <ul>
<li>browsr: <a href="https://termbin.com/fcv3">plain log</a></li>
<li>cloudcompare: log was empty</li>
<li>jetbrains.rider: <a href="https://termbin.com/zxtk">plain log</a></li>
<li>open-interpreter: log was empty</li>
<li>python311Packages.awswrangler: log was empty</li>
<li>python311Packages.cohere: log was empty</li>
<li>python311Packages.datashader: log was empty</li>
<li>python311Packages.django-bootstrap4: log was empty</li>
<li>python311Packages.django-bootstrap5: log was empty</li>
<li>python311Packages.dvc-hdfs: log was empty</li>
<li>python311Packages.folium: log was empty</li>
<li>python311Packages.intake: log was empty</li>
<li>python311Packages.layoutparser: log was empty</li>
<li>python311Packages.llmx: log was empty</li>
<li>python311Packages.mmcv: log was empty</li>
<li>python311Packages.mmengine: <a href="https://termbin.com/myvw">plain log</a></li>
<li>python311Packages.momepy: log was empty</li>
<li>python311Packages.open-interpreter: <a href="https://termbin.com/htez">plain log</a></li>
<li>python311Packages.osmnx: log was empty</li>
<li>python311Packages.outlines: <a href="https://termbin.com/0lon">plain log</a></li>
<li>python311Packages.pandas-stubs: <a href="https://termbin.com/rjsj">plain log</a></li>
 [...]

2024-07-26 08:00 UTC, tobim commented
Can you please `git am` this commit to fix cross and static builds:
```patch
From 4163bfa593bfefe2d5b74b646bba638a9305f5b0 Mon Sep 17 00:00:00 2001
From: Tobias Mayer <tobim@fastmail.fm>
Date: Thu, 25 Jul 2024 22:04:41 +0200
Subject: [PATCH] thrift: fix cross

---
 pkgs/by-name/th/thrift/package.nix | 24 +++++++++++-------------
 1 file changed, 11 insertions(+), 13 deletions(-)

diff --git a/pkgs/by-name/th/thrift/package.nix b/pkgs/by-name/th/thrift/package.nix
index 2686aa181b18..c638b6bd3d1e 100644
--- a/pkgs/by-name/th/thrift/package.nix
+++ b/pkgs/by-name/th/thrift/package.nix
@@ -9,6 +9,7 @@
 , cmake
 , pkg-config
 , bison
+, pkgsBuildHost
 , flex
 , glibcLocales
 , nix-update-script
@@ -27,6 +28,8 @@ stdenv.mkDerivation (finalAttrs: {
     hash = "sha256-cwFTcaNHq8/JJcQxWSelwAGOLvZHoMmjGV3HBumgcWo=";
   };
 
+  strictDeps = true;
+
   # Workaround to make the Python wrapper not drop this package:
   # pythonFull.buildEnv.override { extraLibs = [ thrift ]; }
   pythonPath = [];
@@ -36,17 +39,15 @@ stdenv.mkDerivation (finalAttrs: {
     cmake
     flex
     pkg-config
-    python3
-    python3.pkgs.setuptools
+    (python3.pythonOnBuildForHost.withPackages (ps: [
+      ps.setuptools
+      ps.tornado
+      ps.twisted
+    ]))
   ];
 
   buildInputs = [
     boost
-  ] ++ lib.optionals (!static) [
-    (python3.withPackages (ps: [
-      ps.tornado
-      ps.twisted
-    ]))
   ];
 
   propagatedBuildInputs = [
@@ -77,16 +78,13 @@ stdenv.mkDerivation (finalAttrs: {
   cmakeFlags = [
     (lib.cmakeBool "BUILD_JAVASCRIPT" false)
     (lib.cmakeBool "BUILD_NODEJS" false)
-
-    # FIXME: Fails to link in static mode with undefined reference to
-    # `boost::unit_test::unit_test_main(bool (*)(), int, char**)'
-    (lib.cmakeBool "BUILD_TESTING" (!static))
     (lib.cmakeBool "WITH_STATIC_LIB" static)
+    (lib.cmakeBool "Boost_USE_STATIC_LIBS" static)
     (lib.cmakeBool "OPENSSL_USE_STATIC_LIBS" static)
+  ] ++ lib.optionals (!stdenv.buildPlatform.canExecute stdenv.hostPlatform) [
+    "-DTHRIFT_COMPILER=${pkgsBuildHost.thrift}/bin/thrift"
   ];
 
-  doCheck = !static;
-
   nativeCheckInputs = [
     glibcLocales
   ];
-- 
2.45.2

```

With the above change applied:

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>32 packages marked as broken and skipped:</summary>
  <ul>
    <li>chatgpt-retrieval-plugin</li>
    <li>chatgpt-retrieval-plugin.dist</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>python311Packages.apache-beam</li>
    <li>python311Packages.apache-beam.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.haystack-ai</li>
    <li>python311Packages.haystack-ai.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.outlines</li>
    <li>python311Packages.outlines.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.apache-beam</li>
    <li>python312Packages.apache-beam.dist</li>
    <li>python312Packages.haystack-ai</li>
    <li>python312Packages.haystack-ai.dist</li>
    <li>python312Packages.openllm</li>
    <li>python312Packages.openllm.dist</li>
    <li>python312Packages.outlines</li>
    <li>python312Packages.outlines.dist</li>
    <li>python312Packages.txtai</li>
    <li>python312Packages.txtai.dist</li>
    <li>python312Packages.vllm</li>
    <li>python312Packages.vllm.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
  </ul>
</details>
<details>
  <summary>186 packages failed to build:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile</li>
    <li>cloudcompare</li>
    <li>entwine</li>
    <li>gdal (python312Packages.gdal)</li>
    <li>gmt</li>
    <li>gnuradio3_8</li>
    <li>gnuradio3_8Packages.ais</li>
    <li>gnuradio3_8Packages.grnet</li>
    <li>gnuradio3_8Packages.limesdr</li>
    <li>gnuradio3_8Packages.osmosdr</li>
    <li>gnuradio3_8Packages.osmosdr.dev</li>
    <li>gnuradio3_8Packages.rds</li>
    <li>gplates</li>
    <li>grass</li>
    <li>jetbrains.mps</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>merkaartor</li>
    <li>mysql-workbench</li>
    <li>octavePackages.mapping</li>
    <li>open-interpreter (python312Packages.open-interpreter)</li>
    <li>open-interpreter.dist (python312Packages.open-interpreter.dist)</li>
    <li>open-webui</li>
    <li>open-webui.dist</li>
    <li>openorienteering-mapper</li>
    <li>paraview</li>
    <li>pdal</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>perl538Packages.Tirex</li>
    <li>perl538Packages.Tirex.devdoc</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python311Packages.chromadb</li>
    <li>python311Packages.chromadb.dist</li>
    <li>python311Packages.cleanlab</li>
    <li>python311Packages.cleanlab.dist</li>
    <li>python311Packages.dask-ml</li>
    <li>python311Packages.dask-ml.dist</li>
    <li>python311Packages.django-bootstrap4</li>
    <li>python311Packages.django-bootstrap4.dist</li>
    <li>python311Packages.django-bootstrap5</li>
    <li>python311Packages.django-bootstrap5.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.gdal</li>
    <li>python311Packages.geodatasets</li>
    <li>python311Packages.geodatasets.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.graphrag</li>
    <li>python311Packages.graphrag.dist</li>
    <li>python311Packages.ibis-framework</li>
    <li>python311Packages.ibis-framework.dist</li>
    <li>python311Packages.inequality</li>
    <li>python311Packages.inequality.dist</li>
    <li>python311Packages.langchain-chroma</li>
    <li>python311Packages.langchain-chroma.dist</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.layoutparser.dist</li>
    <li>python311Packages.libpysal</li>
    <li>python311Packages.libpysal.dist</li>
    <li>python311Packages.mapclassify</li>
    <li>python311Packages.mapclassify.dist</li>
    <li>python311Packages.mmcv</li>
    <li>python311Packages.mmcv.dist</li>
    <li>python311Packages.mmengine</li>
    <li>python311Packages.mmengine.dist</li>
    <li>python311Packages.momepy</li>
    <li>python311Packages.momepy.dist</li>
    <li>python311Packages.morecantile</li>
    <li>python311Packages.morecantile.dist</li>
    <li>python311Packages.open-interpreter</li>
    <li>python311Packages.open-interpreter.dist</li>
    <li>python311Packages.optimum</li>
    <li>python311Packages.optimum.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.pandas-stubs</li>
    <li>python311Packages.pandas-stubs.dist</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.pdfplumber.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
    <li>python311Packages.pygmt</li>
    <li>python311Packages.pygmt.dist</li>
    <li>python311Packages.pyogrio</li>
    <li>python311Packages.pyogrio.dist</li>
    <li>python311Packages.python-mapnik</li>
    <li>python311Packages.python-mapnik.dist</li>
    <li>python311Packages.rasterio</li>
    <li>python311Packages.rasterio.dist</li>
    <li>python311Packages.rio-tiler</li>
    <li>python311Packages.rio-tiler.dist</li>
    <li>python311Packages.rioxarray</li>
    <li>python311Packages.rioxarray.dist</li>
    <li>python311Packages.tinygrad</li>
    <li>python311Packages.tinygrad. [...]

2024-07-27 10:03 UTC, anthonyroussel commented
@tobim Thanks, I pushed your commit to fix cross compilation.

2024-07-27 10:04 UTC, anthonyroussel commented
Also had to run nixfmt-rfc-style on the pkgs/by-name/th/thrift/package.nix
Otherwise the pipeline will fail.

2025-06-28 16:11 UTC, sikmir commented
FYI https://github.com/NixOS/nixpkgs/pull/374710

2025-07-24 21:19 UTC, anthonyroussel commented
Stall PR. See https://github.com/NixOS/nixpkgs/pull/374710

2025-07-24 21:19 UTC, closed without merging