Xinetd
NixOS/nixpkgs pull request #29699
Opened 2017-09-23 14:19 UTC by fare

###### Motivation for this change

xinetd has internal services that some legacy software uses, and that I enable at home.

###### Things done

I actually tested my renaming xinetd to MYxinetd and importing using imports in my configuration.nix.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] Linux
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-09-23 14:20 UTC, fare commented
Sorry, my initial push contained updates to gambit and gerbil that are not to be included in this PR (waiting for gambit release to push something stable). I pushed --force an update with just the xinetd updates.

2017-09-26 03:45 UTC, peterhoeg commented
There's a lot of raw text in there - I suggest creating a function that generates the text for the services instead.

2018-04-21 20:29 UTC, matthewbauer requested changes
See @peterhoeg's comments

2018-04-22 11:57 UTC, fare commented
Yes, I need to address these issues indeed.

2018-11-22 08:00 UTC, 7c6f434c commented
(triage) should this be closed until someone has time to do the refactoring?

2018-11-22 18:45 UTC, fare commented
Closing for now. I will reopen later, if I find time to work on it again...

2018-11-22 18:45 UTC, closed without merging