Init gtkhash
NixOS/nixpkgs pull request #298192
Opened 2024-03-22 22:43 UTC by ByteSudoer

## Description of changes

Description: A cross-platform desktop utility for computing message digests or checksums.
Homepage: https://github.com/gtkhash/gtkhash
Changelog: https://github.com/gtkhash/gtkhash/blob/master/ChangeLog
## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-03-23 00:08 UTC, AndersonTorres requested changes

2024-03-23 03:57 UTC, AndersonTorres requested changes

2024-03-23 03:57 UTC, AndersonTorres commented on pkgs/by-name/gt/gtkhash/package.nix
> +  buildInputs = [
```suggestion
  ];

  buildInputs = [
```

2024-03-23 03:57 UTC, AndersonTorres commented on pkgs/by-name/gt/gtkhash/package.nix
> +
```suggestion

  strictDeps = true;

```

2024-03-23 03:57 UTC, AndersonTorres commented on pkgs/by-name/gt/gtkhash/package.nix
> +  };
```suggestion
    platforms = platforms.unix;
  };
```

2024-03-24 10:36 UTC, AndersonTorres requested changes
Besides, LMTM (Looks Mergeable To Me)

2024-03-24 10:36 UTC, AndersonTorres commented on maintainers/maintainer-list.nix
> +  ByteSudoer = {
Reword this commit:

```
maintainers: add ByteSudoer
```

2024-03-25 01:55 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/3686

2024-03-27 04:15 UTC, Aleksanaa commented on pkgs/by-name/gt/gtkhash/package.nix
> +    license = with licenses; [ gpl2Plus ];
```suggestion
    license = licenses.gpl2Plus;
```

2024-03-27 04:15 UTC, Aleksanaa commented on pkgs/by-name/gt/gtkhash/package.nix
> +    homepage = "https://github.com/gtkhash/gtkhash";
```suggestion
    homepage = "https://gtkhash.org";
```

2024-03-27 04:15 UTC, Aleksanaa commented on pkgs/by-name/gt/gtkhash/package.nix
> +    cmake
Please make sure cmake is required. Meson complaints about missing cmake all the time, even if it doesn't have to find dependencies with it.

2024-03-27 23:45 UTC, merged

2024-03-29 21:51 UTC, Thatoo commented
Sorry to disturb but I'm curious to understand how it works.
Why https://hydra.nixos.org/build/254428676#tabs-summary is saying it has been cancelled by user?

2024-03-30 11:59 UTC, SuperSandro2000 commented
That's probably to free up build capacity on hydra. Just wait a bit until https://hydra.nixos.org/build/254652962 is done

2024-04-04 14:56 UTC, Thatoo commented
could it be backported to 23.11?

2024-04-07 13:45 UTC, AndersonTorres commented
> @SuperSandro2000  could it be backported to 23.11?

Feel free to cherry-pick it manually.

2024-04-07 16:50 UTC, Thatoo commented
What do you mean by "cherry-pick it manually" ?

2024-04-08 01:04 UTC, AndersonTorres commented
Backports in Nixpkgs are done by `git cherry-pick` commits from Master to Release branches.