ethercat: init at 1.6.0-rc1
NixOS/nixpkgs pull request #298581
Opened 2024-03-24 09:36 UTC by stv0g

## Description of changes

This PR adds a new package for the [IgH EtherCAT Master for Linux](https://etherlab.org/ethercat).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-03-25 19:07 UTC, a-n-n-a-l-e-e reviewed
for some reason i am getting hash mismatch errors trying to build.

- can use autoreconfHook which provides libtool, automake, and bootstrap script.
- license is gpl2Plus (there is an or later clause)
- changelog should point to the tag not master
- hash mismatch

<details><summary>suggested diffs</summary>

```diff
diff --git a/pkgs/by-name/et/ethercat/package.nix b/pkgs/by-name/et/ethercat/package.nix
index 7ddf3bd7022d..3e65d5cda9cb 100644
--- a/pkgs/by-name/et/ethercat/package.nix
+++ b/pkgs/by-name/et/ethercat/package.nix
@@ -1,8 +1,6 @@
-{ autoconf
-, automake
+{ autoreconfHook
 , cmake
 , lib
-, libtool
 , pkg-config
 , stdenv
 , fetchFromGitLab
@@ -15,17 +13,13 @@ stdenv.mkDerivation (finalAttrs: {
   src = fetchFromGitLab {
     owner = "etherlab.org";
     repo = "ethercat";
-    rev = finalAttrs.version;
-    hash = "sha256-f6NGQVOP9mqb10b+KAFyVsM3fRRj0sL3FpyWsWMKYbM=";
+    rev = "refs/tags/${finalAttrs.version}";
+    hash = "sha256-kzyA6h0rZFEROLcFZoU+2fIQ/Y0NwtdPuliKDbwkHrE=";
   };
 
   separateDebugInfo = true;
 
-  nativeBuildInputs = [ autoconf automake libtool pkg-config ];
-
-  preConfigure = ''
-    bash ./bootstrap
-  '';
+  nativeBuildInputs = [ autoreconfHook pkg-config ];
 
   configureFlags = [
     "--enable-userlib=yes"
@@ -37,8 +31,8 @@ stdenv.mkDerivation (finalAttrs: {
   meta = with lib; {
     description = "IgH EtherCAT Master for Linux";
     homepage = "https://etherlab.org/ethercat";
-    changelog = "https://gitlab.com/etherlab.org/ethercat/-/blob/master/NEWS";
-    license = licenses.gpl2Only;
+    changelog = "https://gitlab.com/etherlab.org/ethercat/-/blob/${finalAttrs.version}/NEWS";
+    license = licenses.gpl2Plus;
     maintainers = with maintainers; [ stv0g ];
     platforms = [ "x86_64-linux" ];
   };
```

</details>

2024-03-26 10:59 UTC, a-n-n-a-l-e-e requested changes
the changes requested in https://github.com/NixOS/nixpkgs/pull/298581#pullrequestreview-1958569216 have not been implemented. (click `suggested diffs` to see the diff). thx.

2024-03-26 22:57 UTC, stv0g commented
@a-n-n-a-l-e-e Oh sorry, I forgot to stage the changes before committing.

2024-03-27 00:41 UTC, a-n-n-a-l-e-e approved these changes
LGTM.

note there is now a merge-bot https://github.com/NixOS/nixpkgs-merge-bot one can use to trigger commits from the automated updater.

2024-03-27 00:41 UTC, merged

2024-04-05 11:18 UTC, 17steen commented
I see that this package does not contain the kernel modules, so not sure if it closes #274191 and if it will actually support communicating with ethercat devices

2024-04-09 22:50 UTC, stv0g commented
@17steen I've created another PR to add the missing kernel modules #302959