outline: Add localRootDir to ReadWritePaths
NixOS/nixpkgs pull request #298892
Opened 2024-03-25 10:39 UTC by Pizmovc

The service can't write to the localRootDir if its set outside of its state directory, thus we have to manually mark it as writable.

## Description of changes
The service did not work out-of-the-box for me when uploading images to the wiki. I've added the `localRootDir` to the `ReadWritePaths` and this fixed the issue.

I'm not sure if the inclusion needs to be conditional, but I don't think there is anything wrong with the proposed change (to make writable all the time).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

---

CC maintainers of the package:  @cab404 @yrd @xanderio

2024-03-27 13:12 UTC, xanderio commented
@Pizmovc Are you using local file storage? If this is the case your change makes sens.

2024-03-27 14:20 UTC, Pizmovc commented
Yes, I do.

On March 27, 2024 2:13:07 PM GMT+01:00, Alexander Sieg ***@***.***> wrote:
>@Pizmovc Are you using local file storage? If this is the case your change makes sens.
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/pull/298892#issuecomment-2022734622
>You are receiving this because you were mentioned.
>
>Message ID: ***@***.***>

2024-03-28 14:44 UTC, xanderio approved these changes

2024-03-28 15:00 UTC, yrd requested changes
Thanks, just one small thing:

2024-03-28 15:03 UTC, Pizmovc commented on nixos/modules/services/web-apps/outline.nix
> +        ReadWritePaths = cfg.storage.localRootDir;
Ah yes, good point. I'll fix it.

2024-03-28 20:55 UTC, Pizmovc commented on nixos/modules/services/web-apps/outline.nix
> +        ReadWritePaths = cfg.storage.localRootDir;
Fixed with 4a46f0d. Thanks for the feedback 🙇

2024-04-01 16:26 UTC, yrd approved these changes

2024-04-01 16:48 UTC, merged

2024-04-08 12:47 UTC, xanderio commented
This change cause the unit to fail as systemd wants to link the `data` directory which may not exist on installations using S3 for storage. 

```
outline.service: Failed to set up mount namespacing: /run/systemd/mount-rootfs/var/lib/outline/data: No such file or directory
outline.service: Failed at step NAMESPACE spawning /nix/store/3h3xc68ly7qh8nd2azp2lbd7pdw0zmpl-unit-script-outline-pre-start/bin/outline-pre-start: No such file or directory
```

2024-04-08 12:54 UTC, cab404 commented
> This change cause the unit to fail as systemd wants to link the `data` directory which may not exist on installations using S3 for storage.
> 
> ```
> outline.service: Failed to set up mount namespacing: /run/systemd/mount-rootfs/var/lib/outline/data: No such file or directory
> outline.service: Failed at step NAMESPACE spawning /nix/store/3h3xc68ly7qh8nd2azp2lbd7pdw0zmpl-unit-script-outline-pre-start/bin/outline-pre-start: No such file or directory
> ```

Ooof. Should I mkIf it?

2024-04-08 12:57 UTC, cab404 commented
```
        ReadWritePaths = lib.mkIf (cfg.storage.storageType == "local") [ cfg.storage.localRootDir ];
```