Add Ogen package
NixOS/nixpkgs pull request #299164
Opened 2024-03-26 11:54 UTC by dz0ny

## Description of changes

OpenAPI v3 code generator for go. https://github.com/ogen-go/ogen

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-03-26 17:27 UTC, liff requested changes
The package should be placed in `pkgs/by-name/og/ogen`, see [quick start](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#quick-start-to-adding-a-package). At the moment it won’t even attempt to build since there’s no entry in `all-packages.nix`.

There should also be a maintainer.

The commit and pull request title should be: `ogen: init at 1.0.0`, see [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions).

2024-03-26 17:27 UTC, liff commented on pkgs/tools/networking/ogen/default.nix
> +}:
You should import the dependencies directly, not use them via `pkgs`:

```suggestion
{ buildGoModule
, fetchFromGitHub
, lib
,
}:
```

2024-03-26 17:27 UTC, liff commented on pkgs/tools/networking/ogen/default.nix
> +  doCheck = false;
Looks like the package builds fine even with checks enabled, so this could be removed.

2024-03-26 17:27 UTC, liff commented on pkgs/tools/networking/ogen/default.nix
> +    hash = "sha256-wIcxICfBY5YHVqKHtHd2wzcaDmkzgp7eD6zEvnsRaIU=";
Got a has mismatch:

```
         specified: sha256-wIcxICfBY5YHVqKHtHd2wzcaDmkzgp7eD6zEvnsRaIU=
            got:    sha256-khUY8PQ12p0slleidysZiGWyZNX3XCxwD55lfRDCwew=
```

2024-03-26 17:27 UTC, liff commented on pkgs/tools/networking/ogen/default.nix
> +  vendorHash = "sha256-EL8FcAnDMekHBIDRdGqQO4JNESjGC7MQ5aUcDkRqrbg=";
Another mismatch:

```
         specified: sha256-EL8FcAnDMekHBIDRdGqQO4JNESjGC7MQ5aUcDkRqrbg=
            got:    sha256-kHfp77jKPBt+EKAc52nXdqR4TJ3OVj7mqo4vfv2XelQ=
```

2024-03-26 17:27 UTC, liff commented on pkgs/tools/networking/ogen/default.nix
> +  };
Suggest you add the following meta attributes:

- [changelog](https://nixos.org/manual/nixpkgs/stable/#var-meta-changelog),
- [license](https://nixos.org/manual/nixpkgs/stable/#var-meta-license),
- [maintainers](https://nixos.org/manual/nixpkgs/stable/#var-meta-maintainers),
- [mainProgram](https://nixos.org/manual/nixpkgs/stable/#var-meta-mainProgram) and
- [platforms](https://nixos.org/manual/nixpkgs/stable/#var-meta-platforms).

2024-07-22 15:06 UTC, seanrmurphy commented
@dz0ny - I also packaged this on my local machine and was using it - was gonna make PR but found that you had already started; do you plan on finalizing this? I'd be ok with being a maintainer also if you like...

2024-07-23 11:38 UTC, seanrmurphy commented
Hey @dz0ny - thanks for moving this forward!

Looks like you're not listed as a maintainer in `maintainer-list.nix` so I guess you haven't been through this before. (I'm still pretty new here also tbh).

For this to be approved, it will need to comprise exactly 2 commits, one which adds you to the maintainers list (assuming you're willing to take responsibility for maintaining this package) and one for the introduction of the package itself.

The comments of @liff also need to be addressed - the metadata needs to be complete and the package file needs to be put in `pkgs/by-name/og/ogen`.

I'm happy to help out here if required - just lemme know.

2024-08-17 16:15 UTC, seanrmurphy commented
@dz0ny - I've done some work on this in [this branch](https://github.com/seanrmurphy/nixpkgs/tree/add-ogen) - if you like, you can just copy that into your branch and move it forward.

If you wanna move this forward, you prob need to figure out if you're willing to take responsibility for maintaining this - I am willing to do that, so the two of us could be maintainers. If you wanna do that, you prob need to add another commit to the branch which adds you to the maintainers list.

2024-08-18 08:22 UTC, dz0ny commented
> @dz0ny - I've done some work on this in [this branch](https://github.com/seanrmurphy/nixpkgs/tree/add-ogen?rgh-link-date=2024-08-17T16%3A15%3A27Z) - if you like, you can just copy that into your branch and move it forward.
> 
> If you wanna move this forward, you prob need to figure out if you're willing to take responsibility for maintaining this - I am willing to do that, so the two of us could be maintainers. If you wanna do that, you prob need to add another commit to the branch which adds you to the maintainers list.

No go ahead, I don't have time.

2024-08-19 08:19 UTC, seanrmurphy commented
> > @dz0ny - I've done some work on this in [this branch](https://github.com/seanrmurphy/nixpkgs/tree/add-ogen?rgh-link-date=2024-08-17T16%3A15%3A27Z) - if you like, you can just copy that into your branch and move it forward.
> > If you wanna move this forward, you prob need to figure out if you're willing to take responsibility for maintaining this - I am willing to do that, so the two of us could be maintainers. If you wanna do that, you prob need to add another commit to the branch which adds you to the maintainers list.
> 
> No go ahead, I don't have time.

Ok - I will close this PR and open a new one based on my branch.

Let me know if you're interested in being a maintainer when you have more time.

2024-08-19 08:19 UTC, closed without merging