treewide: gate `elfutils` on `lib.meta.availableOn stdenv.hostPlatform elfutils`
NixOS/nixpkgs pull request #299250
Opened 2024-03-26 17:11 UTC by philiptaron

## Description of changes

In #298177, @alyssais pointed out that:

> `stdenv.isLinux` is not a sufficient check for whether `elfutils` is supported, because it's not supported on static Linux.

I went through every mention of elfutils and any that were gated on `stdenv.isLinux` are moved to `lib.meta.availableOn stdenv.hostPlatform elfutils`, just as #298177 did for `glib`.

There are many other ungated uses of `elfutils`, and I didn't touch those.

I've targeted staging for this PR out of an abundance of caution, though it ought to be a pure refactor.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2024-03-27 13:13 UTC, alyssais commented
Any idea what the source of the rebuilds is?

2024-03-27 14:42 UTC, philiptaron commented
> Any idea what the source of the rebuilds is?

I didn't initially, but I think I do now: it's the order of the libraries being different in the buildInputs list. The list is ordered, and this jiggles it!

2024-03-27 14:48 UTC, philiptaron reviewed
I split the commit into 7 different commits, then used `nixpkgs-review rev` on each of them to see what the rebuild counts were.

2024-03-27 14:48 UTC, philiptaron commented on pkgs/applications/misc/opencpn/default.nix
> +  ] ++ lib.optionals (lib.meta.availableOn stdenv.hostPlatform elfutils) [
This one causes a rebuild because the order of the libraries is different.

2024-03-27 14:48 UTC, philiptaron commented on pkgs/applications/science/electronics/nvc/default.nix
> +  ] ++ lib.optionals (lib.meta.availableOn stdenv.hostPlatform elfutils) [
This one does not cause a rebuild

2024-03-27 14:48 UTC, philiptaron commented on pkgs/development/compilers/gnat-bootstrap/default.nix
> +  ] ++ lib.optionals (lib.meta.availableOn stdenv.hostPlatform elfutils) [
Causes a rebuild due to order differences.

2024-03-27 14:48 UTC, philiptaron commented on pkgs/development/libraries/gstreamer/core/default.nix
> +  ] ++ lib.optionals (lib.meta.availableOn stdenv.hostPlatform elfutils) [
Does not cause a rebuild

2024-03-27 14:48 UTC, philiptaron commented on pkgs/development/libraries/mesa/default.nix
> +    ++ lib.optionals stdenv.isLinux [ libomxil-bellagio libva-minimal udev lm_sensors ]
Causes a rebuild

2024-03-27 14:48 UTC, philiptaron commented on pkgs/development/libraries/qt-6/modules/qtmultimedia.nix
> +    ++ lib.optionals stdenv.hostPlatform.isLinux [ libpulseaudio alsa-lib wayland libXrandr libva ]
Causes a rebuild.

2024-03-27 14:48 UTC, philiptaron commented on pkgs/tools/package-management/rpm/default.nix
> +    ++ lib.optional (lib.meta.availableOn stdenv.hostPlatform elfutils) elfutils;
Does not cause a rebuild

2024-04-01 16:04 UTC, philiptaron commented
Resolved merge conflict and split into separate commits (to make potential additional merge conflicts easier.)

2024-04-02 08:42 UTC, alyssais requested changes

2024-04-02 16:57 UTC, philiptaron commented
Right you are. Resolved.

2024-04-02 22:10 UTC, merged