Initial Prometheus DNSSEC Exporter package, module and test
NixOS/nixpkgs pull request #299230
Opened 2024-03-26 15:43 UTC by SebastianWendel

Prometheus DNSSEC Exporter package, module and test

## Description of changes

This PR introduces the `prometheus-dnssec-exporter` package and its accompanying NixOS module `services.prometheus.exporters.dnssec` to the Nixpkgs collection. The [prometheus-dnssec-exporter](https://github.com/chrj/prometheus-dnssec-exporter) is a tool designed to check the validity and expiration of DNSSEC signatures and expose these metrics for Prometheus, making it a valuable asset for monitoring the health and security of DNS infrastructure.

## Things done

- Added `prometheus-dnssec-exporter` package, allowing users to easily deploy this tool in a Nix environment.
- Created a NixOS module `services.prometheus.exporters.dnssec`, facilitating simple configuration and deployment of the service within NixOS systems.
- Implemented a NixOS test for the `services.prometheus.exporters.dnssec` module to ensure its correct operation and integration within the NixOS ecosystem.

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2024-03-26 16:03 UTC, eclairevoyant requested changes
Thanks for the contribution! Some changes I noticed below.

Also, please ensure to follow our [commit message guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions), and have a separate initial commit for adding yourself as a maintainer (i.e. this should be 3 commits: maintainer, package, then the module).

2024-03-26 16:08 UTC, eclairevoyant commented on nixos/modules/services/monitoring/prometheus/exporters/dnssec.nix
> +        ExecStart = "${startScript}/bin/prometheus-dnssec-exporter-start";
```suggestion
        ExecStart = lib.getExe startScript;
```

2024-03-26 16:08 UTC, eclairevoyant commented on pkgs/by-name/pr/prometheus-dnssec-exporter/package.nix
> +  version = "b638685ed8d5919a88b45e85b3aec702f0fcc393";
```suggestion
  version = "0-unstable-2023-03-05";
```

2024-03-26 16:08 UTC, eclairevoyant commented on pkgs/by-name/pr/prometheus-dnssec-exporter/package.nix
> +{ lib, buildGoModule, fetchFromGitHub, nixosTests }:
```suggestion
{ lib, buildGoModule, fetchFromGitHub }:
```

2024-03-26 16:27 UTC, closed without merging

2024-03-29 09:45 UTC, SebastianWendel commented
@eclairevoyant thanks for taking the time to give me useful feedback! 
I accidentally messed up my setup and branch, which ended up in a new PR:
https://github.com/NixOS/nixpkgs/pull/299946

I hope it's a good fit this time.