evdi: 1.14.1-unstable-2024-01-30 -> 1.14.2
NixOS/nixpkgs pull request #299660
Opened 2024-03-28 06:28 UTC by jensbin

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-03-28 20:23 UTC, lolbinarycat commented
result of `nixpkgs-review` on x86_64-linux:

18 packages built:
linuxKernel.packages.linux_4_19.evdi linuxKernel.packages.linux_5_10.evdi linuxPackages_5_10_hardened.evdi linuxKernel.packages.linux_5_15.evdi linuxPackages_5_15_hardened.evdi linuxKernel.packages.linux_5_4.evdi linuxKernel.packages.linux_6_1.evdi linuxPackages_6_1_hardened.evdi linuxPackages.evdi linuxPackages_hardened.evdi linuxKernel.packages.linux_6_7.evdi linuxPackages_6_7_hardened.evdi linuxPackages_latest.evdi linuxPackages_latest-libre.evdi linuxPackages-libre.evdi linuxPackages_xanmod.evdi linuxPackages_xanmod_latest.evdi linuxPackages_zen.evdi

2024-04-07 15:08 UTC, anthonyroussel commented on pkgs/os-specific/linux/evdi/default.nix
> +stdenv.mkDerivation (finalAttrs: rec {
```suggestion
stdenv.mkDerivation (finalAttrs: {
```

2024-04-07 15:09 UTC, anthonyroussel commented
Result of `nixpkgs-review pr 299660` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
3 packages marked as broken and skipped:
</summary>
<ul>
<li>linuxKernel.packages.linux_6_7.evdi</li>
<li>linuxKernel.packages.linux_6_7_hardened.evdi</li>
<li>linuxPackages_6_7_hardened.evdi</li>
</ul>
</details>
<details>
<summary>
19 packages built:
</summary>
<ul>
<li>linuxKernel.packages.linux_4_19.evdi</li>
<li>linuxPackages_4_19_hardened.evdi (linuxKernel.packages.linux_4_19_hardened.evdi)</li>
<li>linuxKernel.packages.linux_5_10.evdi</li>
<li>linuxPackages_5_10_hardened.evdi (linuxKernel.packages.linux_5_10_hardened.evdi)</li>
<li>linuxKernel.packages.linux_5_15.evdi</li>
<li>linuxPackages_5_15_hardened.evdi (linuxKernel.packages.linux_5_15_hardened.evdi)</li>
<li>linuxKernel.packages.linux_5_4.evdi</li>
<li>linuxPackages_5_4_hardened.evdi (linuxKernel.packages.linux_5_4_hardened.evdi)</li>
<li>linuxKernel.packages.linux_6_1.evdi</li>
<li>linuxPackages_6_1_hardened.evdi (linuxKernel.packages.linux_6_1_hardened.evdi)</li>
<li>linuxPackages.evdi (linuxKernel.packages.linux_6_6.evdi)</li>
<li>linuxPackages_hardened.evdi (linuxPackages_6_6_hardened.evdi)</li>
<li>linuxPackages_latest.evdi (linuxKernel.packages.linux_6_8.evdi)</li>
<li>linuxPackages_latest-libre.evdi (linuxKernel.packages.linux_latest_libre.evdi)</li>
<li>linuxPackages-libre.evdi (linuxKernel.packages.linux_libre.evdi)</li>
<li>linuxPackages_lqx.evdi (linuxKernel.packages.linux_lqx.evdi)</li>
<li>linuxPackages_xanmod.evdi (linuxKernel.packages.linux_xanmod.evdi)</li>
<li>linuxPackages_xanmod_latest.evdi (linuxKernel.packages.linux_xanmod_latest.evdi ,linuxPackages_xanmod_stable.evdi)</li>
<li>linuxPackages_zen.evdi (linuxKernel.packages.linux_zen.evdi)</li>
</ul>
</details>

2024-04-07 18:28 UTC, anthonyroussel commented
@ofborg build linuxPackages.evdi linuxPackages_hardened.evdi linuxPackages_latest.evdi

2024-04-08 15:34 UTC, anthonyroussel approved these changes

2024-04-09 08:20 UTC, jensbin commented
@toastal: I know it doesn't help too much. For me it compiles successfully and works with the following kernel packages:
pkgs.linuxPackages_xanmod_latest → 6.7.12
pkgs.linuxPackages_zen → 6.8.2
pkgs.linuxPackages_latest → 6.8.4

2024-04-09 08:32 UTC, jensbin commented
The PR to fix the casting is in https://github.com/DisplayLink/evdi/pull/460

I can change the PR here to add the patch:

```
patches = [
  (fetchpatch {
    url = "https://patch-diff.githubusercontent.com/raw/DisplayLink/evdi/pull/460.patch";
    hash = "sha256-pCktuoDF20j+x/ax4Ye/WDdP3c5h9i6krTmpRs9AtXE=";
  })
];
```

2024-04-11 18:02 UTC, lolbinarycat commented on pkgs/os-specific/linux/evdi/default.nix
> +    rev = "v${version}";
you should never do `repo = finalAttrs.pname`, as this may cause overridden packages to fail to build!

2024-04-11 18:10 UTC, lolbinarycat requested changes
see #277994 for why `finalAttrs.pname` should not be used.

2024-04-11 18:10 UTC, lolbinarycat commented on pkgs/os-specific/linux/evdi/default.nix
> +    repo = finalAttrs.pname;
```suggestion
    repo = "evdi";
```

using finalAttrs here will cause overrides that change `pname` to fail to build.

2024-04-11 18:53 UTC, anthonyroussel commented
They released 1.14.4 just a few hours ago

* https://github.com/DisplayLink/evdi/releases/tag/v1.14.4
* https://github.com/DisplayLink/evdi/compare/v1.14.3...v1.14.4

2024-04-16 20:16 UTC, pbsds commented
Result of `nixpkgs-review pr 299660` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>linuxPackages_latest-libre.evdi (linuxKernel.packages.linux_latest_libre.evdi)</li>
    <li>linuxPackages-libre.evdi (linuxKernel.packages.linux_libre.evdi)</li>
  </ul>
</details>
<details>
  <summary>17 packages built:</summary>
  <ul>
    <li>linuxKernel.packages.linux_4_19.evdi</li>
    <li>linuxPackages_4_19_hardened.evdi (linuxKernel.packages.linux_4_19_hardened.evdi)</li>
    <li>linuxKernel.packages.linux_5_10.evdi</li>
    <li>linuxPackages_5_10_hardened.evdi (linuxKernel.packages.linux_5_10_hardened.evdi)</li>
    <li>linuxKernel.packages.linux_5_15.evdi</li>
    <li>linuxPackages_5_15_hardened.evdi (linuxKernel.packages.linux_5_15_hardened.evdi)</li>
    <li>linuxKernel.packages.linux_5_4.evdi</li>
    <li>linuxPackages_5_4_hardened.evdi (linuxKernel.packages.linux_5_4_hardened.evdi)</li>
    <li>linuxKernel.packages.linux_6_1.evdi</li>
    <li>linuxPackages_6_1_hardened.evdi (linuxKernel.packages.linux_6_1_hardened.evdi)</li>
    <li>linuxPackages.evdi (linuxKernel.packages.linux_6_6.evdi)</li>
    <li>linuxPackages_hardened.evdi (linuxPackages_6_6_hardened.evdi)</li>
    <li>linuxPackages_latest.evdi (linuxKernel.packages.linux_6_8.evdi)</li>
    <li>linuxPackages_lqx.evdi (linuxKernel.packages.linux_lqx.evdi)</li>
    <li>linuxPackages_xanmod.evdi (linuxKernel.packages.linux_xanmod.evdi)</li>
    <li>linuxPackages_xanmod_latest.evdi (linuxKernel.packages.linux_xanmod_latest.evdi ,linuxPackages_xanmod_stable.evdi)</li>
    <li>linuxPackages_zen.evdi (linuxKernel.packages.linux_zen.evdi)</li>
  </ul>
</details>

failures are expected: https://hydra.nixos.org/build/256420502 and https://hydra.nixos.org/build/256423699

2024-04-16 20:16 UTC, merged