python3Packages.hydrogram: init at 0.1.4
NixOS/nixpkgs pull request #299966
Opened 2024-03-29 11:03 UTC by tholoo

## Description of changes

Init hydrogram, an Sleek, advanced, and asynchronous Telegram MTProto API framework in Python, designed for fluid user and bot interactions.
https://github.com/hydrogram/hydrogram

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-04 08:58 UTC, fabaff commented on pkgs/development/python-modules/hydrogram/default.nix
> +    rev = "v${version}";
Helps to avoid branch/tag confusion.

```suggestion
    rev = "refs/tags/v${version}";
```

2024-05-18 21:56 UTC, lucasew commented on pkgs/development/python-modules/hydrogram/default.nix
> +
Add a update script so r-ryantm can try to update the package. It's easier to maintain later and updates can be deployed much faster.

`passthru.updateScript = gitUpdater { rev-prefix = "v"; };`

should do the trick.

2024-05-18 21:59 UTC, lucasew commented
Result of `nixpkgs-review pr 299966` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.hydrogram</li>
    <li>python311Packages.hydrogram.dist</li>
    <li>python312Packages.hydrogram</li>
    <li>python312Packages.hydrogram.dist</li>
  </ul>
</details>

2024-11-14 18:05 UTC, FliegendeWurst requested changes

2024-11-23 11:17 UTC, Aleksanaa commented
@ofborg build python311Packages.hydrogram python312Packages.hydrogram

2024-11-23 11:52 UTC, natsukium commented on pkgs/development/python-modules/hydrogram/default.nix
> +
```suggestion
```
`buildPythonPackage` sets `passthru.updateScript` by default.
https://github.com/NixOS/nixpkgs/blob/fc26d5c5649c9b4499c651485491c019df12765a/pkgs/development/interpreters/python/mk-python-derivation.nix#L310-L315

2024-11-24 15:57 UTC, FliegendeWurst commented
@ofborg build python312Packages.hydrogram

2024-11-25 06:04 UTC, merged