`nixosOptionsDoc.optionsMarkdown`: init, with anchors
NixOS/nixpkgs pull request #300309
Opened 2024-03-30 19:06 UTC by roberth

## Description of changes

This adds a new `optionsMarkdown` attribute, that's compatible with the HTML (and DocBook) outputs.

This functionality needs anchor _syntax_, which is not part of the CommonMark specification, as of version 0.31.2.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-01 19:58 UTC, pennae requested changes

2024-04-21 22:15 UTC, roberth commented
>  it would make sense to have a function that encapsulates commonmark-plus-extensions in some way.

I agree, but I couldn't find a good place to put that function. For that I blame the structure of `nixosOptionsDoc`.
I'd like to replace it by a "normal" library that doesn't put an arbitrary set of parameters into the closure of an attrset.
While originally i was hoping to make a quick prototype of that, I ended up in rabbit hole https://github.com/NixOS/nixpkgs/pull/305847.

2025-01-02 20:07 UTC, roberth commented
I've opened https://github.com/NixOS/nixpkgs/pull/370352 to replace this without force pushing.
Thank you @pennae for the review

2025-01-02 20:07 UTC, closed without merging

2025-01-02 20:10 UTC, roberth commented on nixos/lib/make-options-doc/default.nix
> +  '';
In https://github.com/NixOS/nixpkgs/pull/370352 I avoid this duplication by introducing `extraArgs` which can be overridden. That's much simpler and doesn't cause duplication.

2025-01-02 20:13 UTC, roberth commented on pkgs/tools/nix/nixos-render-docs/src/nixos_render_docs/options.py
> +}
It now reuses that routine. I agree it's not a great transform, lacking injectivity, but it's the one that's been used all this time in DocBook and HTML option docs.
A better transform could be added by extending the enum in https://github.com/NixOS/nixpkgs/pull/370352, if anyone wants or needs that.

2025-01-02 20:17 UTC, roberth commented on pkgs/tools/nix/nixos-render-docs/src/nixos_render_docs/options.py
> +        return '.'.join([to_id(x) for x in loc])
Compatibility is my explicit goal with the `legacy` anchor style. I think I've done a good job at reusing existing code in https://github.com/NixOS/nixpkgs/pull/370352. A line of code like this is unavoidable for that. Better anchor styles can be added, as mentioned.