cargo-lambda: 1.0.1 -> 1.2.0
NixOS/nixpkgs pull request #301304
Opened 2024-04-03 17:38 UTC by ederoyd46

## Description of changes

Updated cargo-lambda version to 1.2.0 https://github.com/cargo-lambda/cargo-lambda/releases/tag/v1.2.0

I could not get the package to build with cargoLock, so I've changed in favour of using cargoHash. I also had to skip 2 additional tests to get the package to build. Would appreciate @taylor1791 or @calavera validating if this is acceptable.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [X] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-07 03:03 UTC, taylor1791 commented
I built and ran this locally to confirm that the binary still works.

@calavera Nix sandboxing prevents tests from accessing the network. All of those tests make requests to github to try and download (https://github.com/cargo-lambda/default-template/archive/refs/heads/main.zip.

@ederoyd46 Others usually ask me to squash and follow the [commit convention](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions) `cargo-lambda: 1.0.1 -> 1.2.0`.

2024-04-07 18:28 UTC, Ma27 requested changes
If it builds fine w/o a vendored Cargo.lock that's preferable anyways. Please make sure to delete said Cargo.lock though from nixpkgs.

2024-04-09 08:10 UTC, ederoyd46 commented
> If it builds fine w/o a vendored Cargo.lock that's preferable anyways. Please make sure to delete said Cargo.lock though from nixpkgs.

Cargo.lock removed as requested.

2024-04-10 14:23 UTC, Ma27 approved these changes

2024-04-10 14:23 UTC, merged