dockerTools.streamLayeredImage: make `/tmp`
NixOS/nixpkgs pull request #301755
Opened 2024-04-05 07:36 UTC by ryota-ka

## Description of changes

Make `/tmp` directory while building a Docker image with `pkgs.dockerTools.streamLayeredImage`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-07 14:14 UTC, roberth requested changes
This changes all images to have a `/tmp`, even ones that don't need them.
Each unnecessary "capability" reduces the security of an image, and for a number of images, this will be the first writable directory.

Furthermore if we were to go down this path, `streamLayeredImage` would have to grow an unbounded number of features, eventually encompassing a large part of core NixOS. This would entail a loss of efficiency and flexibility, because the lower level primitive operation would be gone.

I'd prefer a solution where we either reuse modules of NixOS (for a really high-level and standardized interface), or something like `shadowSetup` where it's the caller's responsibility to pass it in.

2024-04-07 17:57 UTC, ryota-ka commented
@roberth Unlike the files like `/etc/{group,passwd}` that is created with `shadowSetup`, the existence of `/tmp` is considered essential in POSIX/Linux systems.
Here are some facts:

- The `/tmp` directory *shall exist* on POSIX-conforming systems, according to IEEE Std 1003.1-2017[^1]
- Linux Foundation stipulates that *the `/tmp` directory must be made available for programs that require temporary files.* in File System Hierarchy 3.0[^2]

So in my opinion it isn't one of such feature requests but a bug fix.

Here, two questions seem to be clarified:

- a) Should `pkgs.dockerTools` continue to ship POSIX-incompatible Docker images lacking the `/tmp` directory?
- b) If it is undesirable that all the image have the `/tmp` directory in the perspective of security, should #260063 be also reverted?

[^1]: https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap10.html#tag_10_01
[^2]: https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s18.html

2024-04-07 18:37 UTC, roberth commented
Containers are not required to comply with anything except their runtime's requirements and the requirements of the application.

> * a) Should `pkgs.dockerTools` continue to ship POSIX-incompatible Docker images lacking the `/tmp` directory?

Yes, but _you_ are responsible for the shipping part. `streamLayeredImage` is just a tool, which is at the bottom of the "stack", so it should be flexible rather than opinionated.


> * b) If it is undesirable that all the image have the `/tmp` directory in the perspective of security, should

Thank you for bringing this up. I would prefer for it to be removed. I'll cross-post.

2024-04-08 05:59 UTC, ryota-ka commented
Okay, then I'll closing this. Let's keep the discussion in #257172.
Anyway, thank you for your review and being a good shepherd!

2024-04-08 05:59 UTC, closed without merging