hypseus-singe: init at 2.11.2
NixOS/nixpkgs pull request #301821
Opened 2024-04-05 12:03 UTC by TomaSajt

## Description of changes

Closes https://github.com/NixOS/nixpkgs/issues/301113

This is still WIP, but the hardest thing (the compilation) is done.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-11 17:58 UTC, TomaSajt commented
@keenanweaver should be ready for testing
Of course, you'll need to put the `vldp` `vldp_dl` and `roms` directories inside `~/.daphne`

2024-04-11 19:18 UTC, keenanweaver commented
I will get back to you once I figure out how to get this emulator working at all! Very confusing.

2024-04-11 19:44 UTC, TomaSajt commented
You have to aquire the roms and place the directories into ~/.daphne

Then you can run `hypseus <gamename>`

2024-04-18 14:01 UTC, keenanweaver commented
Result of `nixpkgs-review pr 301821` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hypseus-singe</li>
  </ul>
</details>

Alright, after struggling a little bit, I finally was able to get this working. The gist was I couldn't use `hypseus`, as it always resulted in a failure:

```
hypseus singe vldp -framefile /home/keenan/.daphne/singe/johnnyrock/johnnyrock.txt -script /home/keenan/.daphne/singe/johnnyrock/johnnyrock.singe -fullscreen -volume_nonvldp 5 -volume_vldp 20 -js_range 5 -manymouse -homedir ~/.daphne/ -datadir ~/.daphne/

Invalid game selected
```
I had to use `hypseus.bin` instead:

```
hypseus.bin singe vldp -framefile /home/keenan/.daphne/singe/johnnyrock/johnnyrock.txt -script /home/keenan/.daphne/singe/johnnyrock/johnnyrock.singe -fullscreen -volume_nonvldp 5 -volume_vldp 20 -js_range 5 -manymouse -homedir ~/.daphne/ -datadir ~/.daphne/
[version] Hypseus Singe: v2.11.2
[console] Setting alternate home dir: /home/keenan/.daphne/
2024-04-18 08:53:29.890 INFO  [242393] [reset_logfile@343] Version v2.11.2
2024-04-18 08:53:29.890 INFO  [242393] [reset_logfile@347] Command line: /nix/store/ga9fgvz3amrpi51635s33qxnlkj51728-hypseus-singe-2.11.2/share/hypseus-singe/hypseus.bin singe vldp -framefile /home/keenan/.daphne/singe/johnnyrock/johnnyrock.txt -script /home/keenan/.daphne/singe/johnnyrock/johnnyrock.singe -fullscreen -volume_nonvldp 5 -volume_vldp 20 -js_range 5 -manymouse -homedir /home/keenan/.daphne/ -datadir /home/keenan/.daphne/
2024-04-18 08:53:29.890 INFO  [242393] [reset_logfile@348] CPU : AMD || Mem : 32000 megs
sh: line 1: lspci: command not found
2024-04-18 08:53:29.896 INFO  [242393] [reset_logfile@349] OS : Linux 6.8 || Video : Unknown video
2024-04-18 08:53:29.903 INFO  [242393] [reset_logfile@350] RGB2YUV Function: C
2024-04-18 08:53:29.903 INFO  [242393] [reset_logfile@356] Line Blending Function: C
2024-04-18 08:53:29.903 INFO  [242393] [reset_logfile@363] Audio Mixing Function: C
2024-04-18 08:53:34.219 INFO  [242393] [SDL_input_init@505] No joysticks detected
2024-04-18 08:53:34.219 WARN  [242393] [CFG_Keys@330] hypinput.ini not found, using defaults
2024-04-18 08:53:34.219 INFO  [242393] [manymouse_init_mice@335] Using ManyMouse for mice input.
2024-04-18 08:53:34.478 INFO  [242393] [manymouse_init_mice@356] Found 2 mice devices:
2024-04-18 08:53:34.478 INFO  [242393] [manymouse_init_mice@365] #0: 8BitDo 8BitDo Retro Keyboard
2024-04-18 08:53:34.478 INFO  [242393] [manymouse_init_mice@365] #1: Logitech G502 X LS
2024-04-18 08:53:37.700 INFO  [242393] [video::notify_stats@2108] Viewport Stats:|w:640x480|v:640x480|o:320x240|l:2560x1440|o
2024-04-18 08:53:38.700 INFO  [242393] [ldp_vldp::read_frame_conversions@1031] Framefile parse succeeded. Video/Audio directory is: /home/keenan/.daphne/singe/johnnyrock/./
2024-04-18 08:53:38.700 WARN  [242393] [printnotice@70] Parsing video file(s). This may take a while.
2024-04-18 08:53:54.953 INFO  [242393] [printline@95] Starting Singe version 1.88
2024-04-18 08:53:55.004 INFO  [242393] [printline@95] SINGE: Singe version compatible with ratio adjustment.
2024-04-18 08:53:55.878 INFO  [242393] [video::notify_stats@2108] Viewport Stats:|w:640x480|v:720x480|o:360x240|l:2560x1440|o
2024-04-18 08:53:57.965 INFO  [242393] [printline@95] SINGE: Playing CDROM version 1.0b
```

Something with wrapping?

Before this worked, though, I had to do a few prerequisite steps:

- Create the data directories:
``` bash
mkdir -p ~/.daphne/roms ~/.daphne/ram ~/.daphne/vldp
mkdir -p ~/.daphne/vldp_dl ~/.daphne/singe
```
- Copy the stuff from the nix store /share/hypseus-singe to .daphne, otherwise it'd complain about missing files, specifically the pics directory. Any combination of --datadir and --homedir didn't resolve it. It seemingly has to be in the user's home directory.
- Download and extract the hypseus singe data '00-singe1' directory contents to ~/.daphne/singe
- Drop in the _stuff_ to make the game work.

Did not try other games. Definitely an emulator to use with a frontend.

2024-04-18 16:59 UTC, TomaSajt commented
Okay, I did some testing, and it looks like `singe` based games don't really respect the `homedir` property, which means that they try to load from the `pwd`, which is inside the nix store.

I could do a few things about this:
1: delegate the installation of game files to the user
2: patch all usages of `pics` `sound` `fonts` and `screenshots` to point to the nix store regardless of the `datadir` setting.

I'll do the first one for now.

2024-04-29 20:32 UTC, keenanweaver commented
> Now you'll just be able to run `singe <gamename>` or `hypseus <gamename>` without manual calls to `hypseus.bin`

Only running with hypseus.bin for me, unless I'm missing something:

```
┌───────────────────>
│keenan in .cache/nixpkgs-review/pr-301821-5 via ❄️  impure (review-shell)
❄️ bsh ›
└─>hypseus singe vldp -framefile /home/keenan/.daphne/singe/johnnyrock/johnnyrock.txt -script /home/keenan/.daphne/singe/johnnyrock/johnnyrock.singe -fullscreen -volume_nonvldp 5 -volume_vldp 20 -js_range 5 -manymouse -homedir ~/.daphne/ -datadir ~/.daphne/

Invalid game selected
```

2024-04-29 20:55 UTC, TomaSajt commented
> > Now you'll just be able to run `singe <gamename>` or `hypseus <gamename>` without manual calls to `hypseus.bin`
> 
> Only running with hypseus.bin for me, unless I'm missing something:
> 
> ```
> ┌───────────────────>
> │keenan in .cache/nixpkgs-review/pr-301821-5 via ❄️  impure (review-shell)
> ❄️ bsh ›
> └─>hypseus singe vldp -framefile /home/keenan/.daphne/singe/johnnyrock/johnnyrock.txt -script /home/keenan/.daphne/singe/johnnyrock/johnnyrock.singe -fullscreen -volume_nonvldp 5 -volume_vldp 20 -js_range 5 -manymouse -homedir ~/.daphne/ -datadir ~/.daphne/
> 
> Invalid game selected
> ```

I think it just `singe johnnyrock` (or `hypesus someothergame` for non-singe stuff)
`hypseus` is just a helper to populate all those field needed by `hypseus.bin`

2024-04-29 21:00 UTC, keenanweaver commented
> I think it just `singe johnnyrock` (or `hypesus someothergame` for non-singe stuff) `hypseus` is just a helper to populate all those field needed by `hypseus.bin`

Right you are! Working great with `singe johnnyrock`. I'll try to find further issues and report back.

2024-05-06 13:13 UTC, keenanweaver approved these changes
No further things have caught my eye. Thank you for all your work on this!

2024-10-17 14:14 UTC, FliegendeWurst approved these changes
Result of `nixpkgs-review pr 301821` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>hypseus-singe</li>
  </ul>
</details>

2024-10-17 15:30 UTC, keenanweaver requested changes
v2.11.3 was released

2024-10-17 15:30 UTC, keenanweaver commented on pkgs/by-name/hy/hypseus-singe/package.nix
> +  version = "2.11.2";
```suggestion
  version = "2.11.3";
```

2024-10-17 15:30 UTC, keenanweaver commented on pkgs/by-name/hy/hypseus-singe/package.nix
> +    hash = "sha256-ZAEoQJRSi6DHIqltl8y3+tLEBZsJglhiagzJzpVuqzY=";
```suggestion
    hash = "sha256-hLl+/tJrBXo6m/cJxmn2bSLXcNLM8B6SKrM702Z8K8E=";
```

2024-10-17 22:23 UTC, TomaSajt commented on pkgs/by-name/hy/hypseus-singe/package.nix
> +  version = "2.11.2";
Updated

2024-10-17 22:51 UTC, keenanweaver commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 301821`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>hypseus-singe</li>
  </ul>
</details>

2024-10-17 22:52 UTC, keenanweaver approved these changes

2024-12-05 16:09 UTC, FliegendeWurst commented
Build fails on Darwin. Please fix or mark as broken.
```
[  7%] Building C object manymouse/CMakeFiles/manymouse.dir/linux_evdev.c.o
[  7%] Building C object manymouse/CMakeFiles/manymouse.dir/macosx_hidmanager.c.o
/tmp/nix-build-hypseus-singe-2.11.3.drv-0/source/src/manymouse/macosx_hidmanager.c:24:10: fatal error: 'IOKit/hid/IOHIDLib.h' file not found
#include <IOKit/hid/IOHIDLib.h>
         ^~~~~~~~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [manymouse/CMakeFiles/manymouse.dir/build.make:104: manymouse/CMakeFiles/manymouse.dir/macosx_hidmanager.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:519: manymouse/CMakeFiles/manymouse.dir/all] Error 2
make: *** [Makefile:111: all] Error 2
error: boost::bad_format_string: format-string is ill-formed
```

2025-04-19 00:11 UTC, TomaSajt commented
The build worked on `x86_64-darwin`, hopefully it's magically fixed.

2025-04-19 00:39 UTC, keenanweaver approved these changes
```
[version] Hypseus Singe: v2.11.3
[console] Setting alternate home dir: /home/keenan/.daphne
[console] Setting sound buffer size to 2048
2025-04-18 19:38:50.718 INFO  [959805] [reset_logfile@343] Version v2.11.3
2025-04-18 19:38:50.718 INFO  [959805] [reset_logfile@347] Command line: /nix/store/r45f0j06iq1r0d7rr72cbmwjvflkg0yl-hypseus-singe-2.11.3/bin/hypseus.bin singe vldp -framefile /home/keenan/.daphne/singe/johnnyrock/johnnyrock.txt -script /home/keenan/.daphne/singe/johnnyrock/johnnyrock.singe -homedir /home/keenan/.daphne -datadir /home/keenan/.daphne -fullscreen -sound_buffer 2048 -volume_nonvldp 5 -volume_vldp 20
2025-04-18 19:38:50.718 INFO  [959805] [reset_logfile@348] CPU : AMD || Mem : 63872 megs
2025-04-18 19:38:50.722 INFO  [959805] [reset_logfile@349] OS : Linux 6.14 || Video : Advanced Micro Devices, Inc. [AMD/ATI] Navi 31 [Radeon RX 7900 XT/7900 XTX/790
2025-04-18 19:38:51.104 INFO  [959805] [reset_logfile@350] RGB2YUV Function: C
2025-04-18 19:38:51.104 INFO  [959805] [reset_logfile@356] Line Blending Function: C
2025-04-18 19:38:51.104 INFO  [959805] [reset_logfile@363] Audio Mixing Function: C
2025-04-18 19:38:51.674 INFO  [959805] [SDL_input_init@543] No joysticks detected
2025-04-18 19:38:51.676 WARN  [959805] [CFG_Keys@354] hypinput.ini not found, using defaults
2025-04-18 19:38:54.544 INFO  [959805] [video::notify_stats@2191] Viewport Stats:|w:640x480|v:640x480|o:320x240|l:2560x1440|o
2025-04-18 19:38:55.544 INFO  [959805] [ldp_vldp::read_frame_conversions@1030] Framefile parse succeeded. Video/Audio directory is: /home/keenan/.daphne/singe/johnnyrock/./
2025-04-18 19:38:55.565 INFO  [959805] [printline@95] Starting Singe version 1.90
2025-04-18 19:38:55.617 INFO  [959805] [printline@95] SINGE: Singe version compatible with ratio adjustment.
2025-04-18 19:38:55.828 INFO  [959805] [video::notify_stats@2191] Viewport Stats:|w:640x480|v:720x480|o:360x240|l:2560x1440|o
```
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 301821`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>hypseus-singe</li>
  </ul>
</details>

2025-04-19 08:54 UTC, FliegendeWurst approved these changes
Builds on x64 Linux and aarch64 Darwin

2025-04-19 08:55 UTC, merged