python310Packages.json5: Disable flaky test
NixOS/nixpkgs pull request #303252
Opened 2024-04-11 01:12 UTC by l0b0

## Description of changes

Closes  #245656.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-12 05:24 UTC, siraben approved these changes
Approved but would like to get another Python maintainer's opinion if possible.

2024-04-13 16:10 UTC, siraben commented
Result of `nixpkgs-review pr 303252` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.jupyter-contrib-nbextensions</li>
    <li>python311Packages.jupyter-contrib-nbextensions.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.pynitrokey</li>
    <li>python311Packages.pynitrokey.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.spsdk</li>
    <li>python311Packages.spsdk.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python312Packages.pynitrokey</li>
    <li>python312Packages.pynitrokey.dist</li>
    <li>python312Packages.spsdk</li>
    <li>python312Packages.spsdk.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>
<details>
  <summary>74 packages failed to build:</summary>
  <ul>
    <li>cantor (libsForQt5.cantor ,plasma5Packages.cantor)</li>
    <li>heroic</li>
    <li>heroic-unwrapped</li>
    <li>labplot</li>
    <li>manim</li>
    <li>manim-slides</li>
    <li>manim-slides.dist</li>
    <li>manim.dist</li>
    <li>nbqa</li>
    <li>nbqa.dist</li>
    <li>nitrokey-app2</li>
    <li>nitrokey-app2.dist</li>
    <li>pynitrokey</li>
    <li>pynitrokey.dist</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.augmax</li>
    <li>python311Packages.augmax.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.encodec</li>
    <li>python311Packages.encodec.dist</li>
    <li>python311Packages.graphtage</li>
    <li>python311Packages.graphtage.dist</li>
    <li>python311Packages.jupyter-collaboration</li>
    <li>python311Packages.jupyter-collaboration.dist</li>
    <li>python311Packages.jupytext</li>
    <li>python311Packages.jupytext.dist</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.layoutparser.dist</li>
    <li>python311Packages.manim-slides</li>
    <li>python311Packages.manim-slides.dist</li>
    <li>python311Packages.mkdocs-jupyter</li>
    <li>python311Packages.mkdocs-jupyter.dist</li>
    <li>python311Packages.nbdev</li>
    <li>python311Packages.nbdev.dist</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.pdfplumber.dist</li>
    <li>python311Packages.phik</li>
    <li>python311Packages.phik.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python311Packages.pymoo</li>
    <li>python311Packages.pymoo.dist</li>
    <li>python312Packages.experiment-utilities</li>
    <li>python312Packages.experiment-utilities.dist</li>
    <li>python312Packages.graphtage</li>
    <li>python312Packages.graphtage.dist</li>
    <li>python312Packages.jupyter-collaboration</li>
    <li>python312Packages.jupyter-collaboration.dist</li>
    <li>python312Packages.jupytext</li>
    <li>python312Packages.jupytext.dist</li>
    <li>python312Packages.layoutparser</li>
    <li>python312Packages.layoutparser.dist</li>
    <li>python312Packages.manim-slides</li>
    <li>python312Packages.manim-slides.dist</li>
    <li>python312Packages.mkdocs-jupyter</li>
    <li>python312Packages.mkdocs-jupyter.dist</li>
    <li>python312Packages.nbdev</li>
    <li>python312Packages.nbdev.dist</li>
    <li>python312Packages.pdfplumber</li>
    <li>python312Packages.pdfplumber.dist</li>
    <li>python312Packages.qgrid</li>
    <li>python312Packages.qgrid.dist</li>
    <li>python312Packages.tsfresh</li>
    <li>python312Packages.tsfresh.dist</li>
    <li>quarto</li>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
    <li>sage</li>
    <li>sageWithDoc</li>
    <li>wolfram-notebook</li>
  </ul>
</details>
<details>
  <summary>135 packages built:</summary>
  <ul>
    <li>djlint</li>
    <li>djlint.dist</li>
    <li>fortls</li>
    <li>fortls.dist</li>
    <li>ihaskell</li>
    <li>jinja2-cli</li>
    <li>jinja2-cli.dist</li>
    <li>jupyter</li>
    <li>jupyter-all</li>
    <li>nile</li>
    <li>nile.dist</li>
    <li>powerhub</li>
    <li>powerhub.dist</li>
    <li>python311Packages.ansible-kernel</li>
    <li>python311Packages.ansible-kernel.dist</li>
    <li>python311Packages.batchspawner</li>
    <li>python311Packages.batchspawner.dist</li>
    <li>python311Packages.bqplot</li>
    <li>python311Packages.bqplot.dist</li>
    <li>python311Packages.bqscales</li>
    <li>python311Packages.bqscales.dist</li>
    <li>python311Packages.dalle-mini</li>
    <li>python311Packages.dalle-mini.dist</li>
    <li>python311Packages.dm-haiku</li>
    <li>python311Packages.dm-haiku.dist</li>
    <li>python311Packages.dockerspawner</li>
    <li>python311Packages.dockerspawner.dist</li>
    <li>python311Packages.einops</li>
    <li>python311Packages.einops.dist</li>
    <li>python311Packages.experiment-utilities</li>
    <li>python311Packages.experiment-utilities.dist</li>
    <li>python311Packages.flax</li>
    <li>python311Packages.flax.dist</li>
    <li>python311Packages.ipytablewidgets</li>
    <li>python311Packages.ipytablewidgets.dist</li>
    <li>python311Packages.ipyvuetify</li>
    <li>python311Packages.ipyvuetify.dist</li>
    <li>python311Packages.json5</li>
    <li>python311Packages.json5.dist</li>
    <li>python311Packages.jupyter</li>
    <li>python311Packages.jupyter-contrib-core</li>
    <li>python311Packages.jupyter-contrib-core.dist</li>
    <li>python311Packages.jupyter-nbextensions-configurator</li>
    <li>python311Packages.jupyter-nbextensions-configurator.dist</li>
    <li>python311Packages.jupyter.dist</li>
    <li>python311Packages.jupyterhub</li>
    <li>python311Packages.jupyterhub-ldapauthenticator</li>
    <li>python311Packages.jupyterhub-ldapauthenticator.dist</li>
    <li>python311Packages.jupyterhub-systemdspawner</li>
    <li>python311Packages.jupyterhub-systemdspawner.dist</li>
    <li>python311Packages.jupyterhub-tmpauthenticator</li>
    <li>python311Packages.jupyterhub-tmpauthenticator.dist</li>
    <li>python311Packages.jupyterhub.dist</li>
    <li>python311Packages.jupyterlab</li>
    <li>python311Packages.jupyterlab-git</li>
    <li>python311Packages.jupyterlab-git.dist</li>
    <li>python311Packages.jupyterlab-lsp</li>
    <li>python311Packages.jupyterlab-lsp.dist</li>
    <li>python311Packages.jupyterlab-server</li>
    <li>python311Packages.jupyterlab-server.dist</li>
    <li>python311Packages.jupyterlab.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.nbdime</li>
    <li>python311Packages.nbdime.dist</li>
    <li>python311Packages.nikola</li>
    <li>python311Packages.nikola.dist</li>
    <li>python311Packages.nix-kernel</li>
    <li>python311Packages.nix-kernel.dist</li>
    <li>python311Packages.notebook</li>
    <li>python311Packages.notebook.dist</li>
    <li>python311Packages.notedown</li>
    <li>python311Packages.notedown.dist</li>
    <li>python311Packages.oauthenticator</li>
    <li>python311Packages.oauthenticator.dist</li>
    <li>python311Packages.pyannote-audio</li>
    <li>python311Packages.pyannote-audio.dist</li>
    <li>python311Packages.pydeck</li>
    <li>python311Packages.pydeck.dist</li>
    <li>python311Packages.pytest-notebook</li>
    <li>python311Packages.pytest-notebook.dist</li>
    <li>python311Packages.qgrid</li>
    <li>python311Packages.qgrid.dist</li>
    <li>python311Packages.rotary-embedding-torch</li>
    <li>python311Packages.rotary-embedding-torch.dist</li>
    <li>streamlit (python311Packages.streamlit)</li>
    <li>streamlit.dist (python311Packages.streamlit.dist)</li>
    <li>python311Packages.tsfresh</li>
    <l [...]

2024-04-14 11:15 UTC, imincik requested changes
`hypothesis` should be removed from the function parameters (line 3).

Otherwise I am OK with this change. According my test this PR removes only one test (number of tests went down from 68 to 67).

2024-04-15 08:35 UTC, imincik approved these changes
Thanks for updates. It is good to go now.

2024-04-15 08:35 UTC, merged