insync 3.8.7.50516 -> 3.9.0 | insync-emblem-icons: init at 3.8.7.50516 | insync-nautilus: fixes
NixOS/nixpkgs pull request #305780
Opened 2024-04-21 16:28 UTC by hellwolf

## Description of changes

- insync: 3.8.7.50516 -> 3.9.0.60000-
- insync-emblem-icons: init at 3.8.7.50516
  - insync-nautilus: use insync-emblem-icons

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-21 16:29 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/3819

2024-04-22 12:13 UTC, drupol requested changes

2024-04-25 19:49 UTC, SuperSandro2000 commented on pkgs/by-name/in/insync/package.nix
>      name = "${pname}-pkg-${version}";
```suggestion
    pname = "${pname}-pkg";
    inherit version;
```
we should properly set pname+version

2024-04-25 19:50 UTC, SuperSandro2000 commented on pkgs/by-name/in/insync-emblem-icons/package.nix
> +  name = "insync-emblem-icons";
```suggestion
  pname = "insync-emblem-icons";
```

2024-04-30 12:18 UTC, hellwolf commented on pkgs/by-name/in/insync-emblem-icons/package.nix
> +  unpackPhase = ''
done

2024-04-30 12:18 UTC, hellwolf commented on pkgs/by-name/in/insync/package.nix
>      unpackPhase = ''
done

2024-04-30 12:18 UTC, hellwolf commented on pkgs/by-name/in/insync-emblem-icons/package.nix
> +  name = "insync-emblem-icons";
done

2024-04-30 12:18 UTC, hellwolf commented on pkgs/by-name/in/insync/package.nix
>      name = "${pname}-pkg-${version}";
done

2024-04-30 12:19 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1611

2024-05-12 15:06 UTC, hellwolf commented
@drupol  could you have a look again?

2024-06-22 14:07 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/1016/150

2024-06-22 14:09 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1769

2024-06-22 18:05 UTC, hellwolf commented
I have just upgraded it to 3.9.1, can any of you please review again and maybe merge? @SuperSandro2000 @drupol

2024-06-22 20:57 UTC, drupol approved these changes

2024-06-22 20:57 UTC, merged