pkgsForCross: add a way to create custom cross system package set
NixOS/nixpkgs pull request #306625
Opened 2024-04-24 19:59 UTC by Cynerd

Package set pkgsCross provides a lot of platforms but still that is not enough. My use case is for armv7e-m but instead of adding that this might be more generic approach. The less used platforms can be just simply declared on demand.

## Description of changes

This adds option to declare custom cross system. The example of usage:

```
          gcc-armv7e-m =
            (final.pkgsForCross {
              config = "arm-none-eabihf";
              libc = "newlibc";
              gcc = {
                arch = "armv7e-m";
                fpu = "vfpv3-d16";
              };
              inherit (final) overlays;
            })
            .buildPackages
            .gccWithoutTargetLibc;
```

The advantage over doing `import final.path` is that overlays (and other configs) are the same as in the original set without explicitly passing them.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-28 20:58 UTC, Artturin reviewed
-1 on adding a function for this when `import pkgs.path { inherit (pkgs) config overlays; }` works fine.

2024-04-29 15:21 UTC, Cynerd commented
> -1 on adding a function for this when `import pkgs.path { inherit (pkgs) config overlays; }` works fine.

Don't forget that there are also `crossOverlays` and `stdenvStages` that, as far as I see, are not as easilly available. I agree that in the end, it is the same, but this ensures that you really use the same setting except those inherited even in the future if some argument gets added or removed. There might also be an option to include all initialization arguments to some attribute set and could be just used to reinitialize the same package set (such as `import pkgs.path (pkgs.args // {crossSystem= ...;})`).

Just for reference this is what I am using right now and this function would be improvement in my eyes:
```
          pkgsBuildNuttx =
            (import final.path {
              localSystem = final.buildPlatform.system;
              crossSystem = {
                config = "arm-none-eabihf";
                libc = "newlib";
                gcc = {
                  arch = "armv7e-m";
                  fpu = "vfpv3-d16";
                };
                inherit (final) overlays;
              };
            })
            .buildPackages;
```

My primary argument is that it just makes sense to me to have something like this available when `pkgCross` for example already is. You can use the same argument for that as well: you can take `lib.systems.examples`, and that works fine, so why have that `map` in the code?

2024-04-29 15:29 UTC, Ericson2314 requested changes
`pkgsCross` is already a mistake. This is doubling down on it. Agree with @Artturin

2024-04-29 15:30 UTC, Ericson2314 commented
You don't need to import Nixpkgs twice like in your example. Just import it once for cross, and use `pkgsBuildBuild` for native things.

2024-04-29 15:49 UTC, Cynerd commented
> You don't need to import Nixpkgs twice like in your example. Just import it once for cross, and use `pkgsBuildBuild` for native things.

I am using flakes, I have it already imported technically :wink: . This is also an example from overlay that builds firmware for embedded device alongside other tools, and thus, having a native package set with neighboring for different architectures as needed is a better pattern for this.

2025-04-29 14:17 UTC, closed without merging