pythonPackages.ipv8-rust-tunnels: init at 0.1.18
NixOS/nixpkgs pull request #306832
Opened 2024-04-25 18:24 UTC by RaghavSood

## Description of changes

Packages [ipv8-rust-tunnels](https://github.com/Tribler/ipv8-rust-tunnels) for nixpkgs.

This is a prerequisite to updating the tribler package to 7.14.0

I can't seem to run pytests on this - if I add the pytest hook it fails with the following.

<details><summary>Test log</summary>
<pre>
Executing pytestCheckPhase
============================= test session starts ==============================
platform darwin -- Python 3.11.9, pytest-8.1.1, pluggy-1.4.0
rootdir: /private/tmp/nix-build-python3.11-ipv8-rust-tunnels-0.1.18.drv-0/source
configfile: pyproject.toml
collected 0 items / 1 error                                                    

==================================== ERRORS ====================================
______ ERROR collecting ipv8_rust_tunnels/tests/test_tunnel_community.py _______
ImportError while importing test module '/private/tmp/nix-build-python3.11-ipv8-rust-tunnels-0.1.18.drv-0/source/ipv8_rust_tunnels/tests/test_tunnel_community.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/kqsqlfvvr4gr3q83vl43gprk47rbsc5d-python3-3.11.9/lib/python3.11/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ipv8_rust_tunnels/tests/test_tunnel_community.py:3: in <module>
    from ipv8_rust_tunnels.endpoint import RustEndpoint
ipv8_rust_tunnels/endpoint.py:13: in <module>
    import ipv8_rust_tunnels.rust_endpoint as rust
E   ModuleNotFoundError: No module named 'ipv8_rust_tunnels.rust_endpoint'
=========================== short test summary info ============================
ERROR ipv8_rust_tunnels/tests/test_tunnel_community.py
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.07s ===============================
/nix/store/h3f3f6z54p6rkkvs104mbsqz7izp1ips-stdenv-darwin/setup: line 1588: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/i119hjm3f664l3gnsjrfrfskfnnjxgxg-python3.11-ipv8-rust-tunnels-0.1.18.drv' failed with exit code 2;
       last 10 log lines:
       > ipv8_rust_tunnels/tests/test_tunnel_community.py:3: in <module>
       >     from ipv8_rust_tunnels.endpoint import RustEndpoint
       > ipv8_rust_tunnels/endpoint.py:13: in <module>
       >     import ipv8_rust_tunnels.rust_endpoint as rust
       > E   ModuleNotFoundError: No module named 'ipv8_rust_tunnels.rust_endpoint'
       > =========================== short test summary info ============================
       > ERROR ipv8_rust_tunnels/tests/test_tunnel_community.py
       > !!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
       > =============================== 1 error in 0.07s ===============================
       > /nix/store/h3f3f6z54p6rkkvs104mbsqz7izp1ips-stdenv-darwin/setup: line 1588: pop_var_context: head of shell_variables not a function context
       For full logs, run 'nix-store -l /nix/store/i119hjm3f664l3gnsjrfrfskfnnjxgxg-python3.11-ipv8-rust-tunnels-0.1.18.drv'.

</pre>
</details> 

Would appreciate any feedback on the packaging - I don't normally do rust or python packages, most of this is lifted from [pyheck](https://github.com/NixOS/nixpkgs/blob/9603f963f5014cff024b519445f3381113642be2/pkgs/development/python-modules/pyheck/default.nix) and [qcs-sdk-python](https://github.com/NixOS/nixpkgs/blob/9603f963f5014cff024b519445f3381113642be2/pkgs/development/python-modules/qcs-sdk-python/default.nix).

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-15 14:38 UTC, RaghavSood commented
@GrahamcOfBorg build python311Packages.ipv8-rust-tunnels python312Packages.ipv8-rust-tunnels

2024-11-09 22:29 UTC, KiaraGrouwstra commented
Result of `nixpkgs-review pr 306832` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.ipv8-rust-tunnels</li>
    <li>python311Packages.ipv8-rust-tunnels.dist</li>
    <li>python312Packages.ipv8-rust-tunnels</li>
    <li>python312Packages.ipv8-rust-tunnels.dist</li>
  </ul>
</details>

2024-11-22 11:06 UTC, FliegendeWurst requested changes

2026-04-10 16:26 UTC, GraysonTinker commented
Done in #388333.

2026-04-10 16:26 UTC, closed without merging