miniz: 2.2.0 → 3.0.2
NixOS/nixpkgs pull request #307371
Opened 2024-04-28 02:22 UTC by nicoonoclaste

## Description of changes

In `miniz`:
- update from 2.2.0 to 3.0.2,
- add `updateScript`,
- add `meta.pkgConfigModules` and `tests.pkg-config`,
- add the `validatePkgConfig` hook.

cc @astro

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- [x] Tested, as applicable:
  - new [package test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
- [ ] Tested compilation of all packages that depend on this change using `nixpkgs-review`.
  Currently running
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-28 02:45 UTC, AndersonTorres requested changes

2024-04-28 02:45 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
> +    sha256 = "sha256-3J0bkr2Yk+MJXilUqOCHsWzuykySv5B1nepmucvA4hg=";
```suggestion
    hash = "sha256-3J0bkr2Yk+MJXilUqOCHsWzuykySv5B1nepmucvA4hg=";
```

2024-04-28 02:45 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
> +  passthru.updateScript = nix-update-script {};
```suggestion
```

2024-04-28 02:45 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
> +  passthru.tests.pkg-config = testers.testMetaPkgConfig finalAttrs.finalPackage;
```suggestion
  passthru = {
    updateScript = nix-update-script { };
    tests = {
      pkg-config = testers.testMetaPkgConfig finalAttrs.finalPackage;
    };
  };
```

2024-04-28 02:45 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
>      platforms = platforms.unix;
```suggestion
  meta = {
    description = "Single C source file zlib-replacement library";
    homepage = "https://github.com/richgel999/miniz";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ astro ];
    platforms = lib.platforms.unix;
```

2024-04-28 02:45 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
> +}:
```suggestion
{
  lib,
  cmake,
  fetchFromGitHub,
  nix-update-script,
  stdenv,
  testers,
  validatePkgConfig,
}:
```

New formatter rules.

2024-04-28 02:45 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
> +    repo = finalAttrs.pname;
```suggestion
    repo = "miniz";
```

2024-04-28 02:45 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
```suggestion

  strictDeps = true;

```

2024-04-28 03:12 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
>      platforms = platforms.unix;
- Tracking issue:  https://github.com/NixOS/nixpkgs/issues/208242
- Best Practices: https://nix.dev/guides/best-practices#with-scopes
- A real-life bug: https://github.com/NixOS/nixpkgs/pull/295975
- A rather complicated real-life bug: https://github.com/NixOS/nixpkgs/issues/292468#issuecomment-2016454242

2024-04-28 03:14 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
> +  passthru.tests.pkg-config = testers.testMetaPkgConfig finalAttrs.finalPackage;
- "Keeping next" is not relevant. This is not an imperative language, the order of attributes does not matter.
- Scattered `passthru` attributes is strictly less legible.
- Hammering Guide: https://github.com/jtojnar/nixpkgs-hammering/blob/main/explanations/attribute-ordering.md

----------

- I concede the unfurling point. My intention is that usually other tests can be added in the future, but indeed it is less legible as it stands now.

2024-04-28 21:39 UTC, mkg20001 approved these changes
change looks good, passes formatting ci

2024-04-28 22:11 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
https://nixos.org/manual/nixpkgs/stable/#ssec-stdenv-dependencies-reference

2024-04-29 15:23 UTC, merged

2024-04-29 16:06 UTC, AndersonTorres commented on pkgs/development/libraries/miniz/default.nix
The reference was removed, I still don't know why. I will search the commit logs.

Summarizing a bit, `strictDeps =  true` enforces a clearer separation between the various `*buildInputs`. It is helpful e.g. in cross-compilation and porting to other environments.

```
 By default, the run-time/build-time distinction is just a hint for mental clarity, but with strictDeps set it is mostly enforced even in the native case.
```