python312Packages.busylight-for-humans: init at 0.28.0
NixOS/nixpkgs pull request #307469
Opened 2024-04-28 13:37 UTC by Conni2461

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-15 15:24 UTC, Scriptkiddi commented
@NixOS/nixpkgs-merge-bot merge

2024-07-15 15:39 UTC, mweinelt requested changes

2024-07-15 15:39 UTC, mweinelt commented on pkgs/development/python-modules/bitvector-for-humans/default.nix
> +  format = "pyproject";
```suggestion
  pyproject = true
```

2024-07-15 15:39 UTC, mweinelt commented on pkgs/development/python-modules/bitvector-for-humans/default.nix
> +  ];
```suggestion
  build-system = [ poetry-core ];
  
  nativeCheckInputs = [ pytestCheckHook ];
```

2024-07-15 15:39 UTC, mweinelt commented on pkgs/development/python-modules/bitvector-for-humans/default.nix
> +      --replace-fail 'poetry.masonry.api' 'poetry.core.masonry.api'
Please send this change upstream.

2024-07-15 15:39 UTC, mweinelt commented on pkgs/development/python-modules/busylight-for-humans/default.nix
> +    pytest-mock
These two are test dependencies, they go into `nativeCheckInputs`.

2024-07-15 15:39 UTC, mweinelt commented on pkgs/development/python-modules/busylight-for-humans/default.nix
> +  propagatedBuildInputs = [
```suggestion
  dependencies = [
```

Newer lingo for propagatedBuildInputs in python packages.

2024-07-15 15:39 UTC, mweinelt commented on pkgs/development/python-modules/busylight-for-humans/default.nix
> +    description = "Control USB connected presence lights from multiple vendors via the command-line or web API.";
missing mainProgram

2024-07-17 08:23 UTC, 0x4A6F commented
Could you also utilize `busylight udev-rules` to generate these [udev Rules](https://github.com/JnyJny/busylight?tab=readme-ov-file#linux-post-install-activities) and provide it from this package?

2024-07-22 09:47 UTC, 0x4A6F approved these changes

2024-07-22 12:24 UTC, mweinelt approved these changes

2024-07-22 12:32 UTC, merged