tdnf: init at 3.5.6
NixOS/nixpkgs pull request #307698
Opened 2024-04-29 09:16 UTC by malt3

## Description of changes

Add tdnf, a dnf variant similar to microdnf.
This package manager is used to assemble the linux distributions VMWare Photon OS and Microsoft's cbl-mariner / Azure Linux.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-04-29 09:21 UTC, msanft requested changes

2024-04-29 09:21 UTC, msanft commented on pkgs/by-name/td/tdnf/package.nix
> +      --replace 'SYSCONFDIR /etc' 'SYSCONFDIR $out/etc' \
Any reason for not using `--replace-fail` here? Seems brittle to me..

2024-04-29 09:21 UTC, msanft commented on pkgs/by-name/td/tdnf/package.nix
> +  meta = with lib; {
Using `with lib;` is an anti-pattern.

2024-04-29 09:21 UTC, msanft commented on pkgs/by-name/td/tdnf/package.nix
> +    license = [ licenses.gpl2 licenses.lgpl21 ];
```suggestion
    license = with lib.licenses; [ gpl2 lgpl21 ];
```

2024-04-29 09:21 UTC, msanft commented on pkgs/by-name/td/tdnf/package.nix
> +    maintainers = with maintainers; [ malt3 ];
```suggestion
    maintainers = [ lib.maintainers.malt3 ];
```

2024-04-29 09:21 UTC, msanft commented on pkgs/by-name/td/tdnf/package.nix
> +    platforms = platforms.unix;
```suggestion
    platforms = lib.platforms.unix;
```

2024-04-29 09:23 UTC, msanft commented
Result of `nixpkgs-review pr 307698` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>tdnf</li>
  </ul>
</details>

2024-04-29 09:24 UTC, msanft commented
Package seems to function properly

2024-04-29 17:55 UTC, msanft approved these changes
Thank you!

2024-05-02 08:24 UTC, katexochen reviewed
I think we should remove `bin/jsondumptest`, seems to be a test output?

2024-05-02 12:47 UTC, katexochen approved these changes

2024-05-02 12:47 UTC, merged