joker: init at 0.8.5
NixOS/nixpkgs pull request #30942
Opened 2017-10-29 23:54 UTC by andrestylianos

###### Motivation for this change

Adding Joker, a Clojure interpreter/linter written in go.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-10-30 00:38 UTC, orivej requested changes

2017-10-30 00:38 UTC, orivej commented on pkgs/development/interpreters/joker/default.nix
> +    inherit rev;
Prefer git tag: `rev = "v${version}"`

2017-10-30 00:38 UTC, orivej commented on pkgs/development/interpreters/joker/default.nix
> +    platforms = stdenv.lib.platforms.all;
Please delete `stdenv.lib` here and below.

2017-11-04 05:22 UTC, andrestylianos commented
I've opened an issue at upstream as v0.8.5 had a problem that was preventing it from building correctly. Now v0.8.6 has been released, builds correctly here and I've updated the PR. Should I update the PR name or commit message to correctly reflect that it's v0.8.6?

2017-11-04 05:27 UTC, orivej commented
Sure, could you squash the commits into one with `0.8.6` in it?

2017-11-04 07:09 UTC, orivej commented
Additionally I've prevented the installation of generators that were not meant to be installed into `bin`.

2017-11-04 07:09 UTC, merged