hdf5: 1.14.3 -> 1.14.4.3
NixOS/nixpkgs pull request #309595
Opened 2024-05-06 16:02 UTC by markuskowa

## Description of changes

Changelog: https://github.com/HDFGroup/hdf5/releases/tag/hdf5_1.14.4.2

Switch downloads to GitHub. It appears that the new prefered download location is now GitHub

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-07 13:14 UTC, sheepforce commented
@GrahamcOfBorg build blender h5py openmolcas trexio hdf5-mpi

2024-05-07 13:45 UTC, imincik commented
Running nixpkgs-review now ...

2024-05-07 19:00 UTC, imincik commented
Result of `nixpkgs-review pr 309595` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>74 packages marked as broken and skipped:</summary>
  <ul>
    <li>caffeWithCuda</li>
    <li>caffeWithCuda.bin</li>
    <li>deepin.deepin-camera</li>
    <li>deepin.deepin-image-viewer</li>
    <li>deepin.deepin-screen-recorder</li>
    <li>deepin.image-editor</li>
    <li>ezminc</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
    <li>opentoonz</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>python311Packages.clifford</li>
    <li>python311Packages.clifford.dist</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.farm-haystack</li>
    <li>python311Packages.farm-haystack.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.shazamio</li>
    <li>python311Packages.shazamio.dist</li>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
    <li>python311Packages.tensorflow-datasets</li>
    <li>python311Packages.tensorflow-datasets.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.clifford</li>
    <li>python312Packages.clifford.dist</li>
    <li>python312Packages.farm-haystack</li>
    <li>python312Packages.farm-haystack.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.shazamio</li>
    <li>python312Packages.shazamio.dist</li>
    <li>python312Packages.sunpy</li>
    <li>python312Packages.sunpy.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages_6.mivisionx</li>
    <li>rocmPackages_6.mivisionx-cpu</li>
    <li>rocmPackages_6.mivisionx-hip</li>
    <li>shaq</li>
    <li>shaq.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
    <li>worldengine-cli</li>
    <li>worldengine-cli.dist</li>
  </ul>
</details>
<details>
  <summary>1101 packages failed to build:</summary>
  <ul>
    <li>MIDIVisualizer</li>
    <li>ansel</li>
    <li>ants</li>
    <li>apacheHttpdPackages.mod_tile (apacheHttpdPackages_2_4.mod_tile)</li>
    <li>appcsxcad</li>
    <li>audiobookshelf</li>
    <li>backgroundremover</li>
    <li>backgroundremover.dist</li>
    <li>blender</li>
    <li>blender-hip</li>
    <li>caffe</li>
    <li>caffe.bin</li>
    <li>cctag</li>
    <li>cctag.dev</li>
    <li>cctag.lib</li>
    <li>cdo</li>
    <li>citrix_workspace (citrix_workspace_24_02_0)</li>
    <li>citrix_workspace_23_09_0</li>
    <li>citrix_workspace_23_11_0</li>
    <li>cloudcompare</li>
    <li>cp2k</li>
    <li>crystfel</li>
    <li>crystfel-headless</li>
    <li>csxcad</li>
    <li>darktable</li>
    <li>deepin.deepin-ocr-plugin-manager</li>
    <li>deface</li>
    <li>deface.dist</li>
    <li>deltatouch</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>digikam</li>
    <li>easyocr (python311Packages.easyocr)</li>
    <li>easyocr.dist (python311Packages.easyocr.dist)</li>
    <li>elastix</li>
    <li>enblend-enfuse</li>
    <li>entwine</li>
    <li>escrotum</li>
    <li>escrotum.dist</li>
    <li>escrotum.man</li>
    <li>facedetect</li>
    <li>ffcast</li>
    <li>ffmpeg-full (ffmpeg_6-full)</li>
    <li>ffmpeg-full.bin (ffmpeg_6-full.bin)</li>
    <li>ffmpeg-full.data (ffmpeg_6-full.data)</li>
    <li>ffmpeg-full.dev (ffmpeg_6-full.dev)</li>
    <li>ffmpeg-full.doc (ffmpeg_6-full.doc)</li>
    <li>ffmpeg-full.lib (ffmpeg_6-full.lib)</li>
    <li>ffmpeg-full.man (ffmpeg_6-full.man)</li>
    <li>ffmpeg_7-full</li>
    <li>ffmpeg_7-full.bin</li>
    <li>ffmpeg_7-full.data</li>
    <li>ffmpeg_7-full.dev</li>
    <li>ffmpeg_7-full.doc</li>
    <li>ffmpeg_7-full.lib</li>
    <li>ffmpeg_7-full.man</li>
    <li>ffsubsync</li>
    <li>ffsubsync.dist</li>
    <li>fgallery</li>
    <li>flowblade</li>
    <li>freecad</li>
    <li>frigate</li>
    <li>gama</li>
    <li>gdal (python311Packages.gdal)</li>
    <li>gimp-with-plugins</li>
    <li>gimpPlugins.gmic</li>
    <li>glaxnimate</li>
    <li>gmic</li>
    <li>gmic-qt</li>
    <li>gmic.dev</li>
    <li>gmic.lib</li>
    <li>gmic.man</li>
    <li>gmt</li>
    <li>gnss-sdr</li>
    <li>gnudatalanguage</li>
    <li>gplates</li>
    <li>gpt2tc</li>
    <li>grass</li>
    <li>gyroflow</li>
    <li>handbrake</li>
    <li>haskellPackages.hgdal</li>
    <li>haskellPackages.hgdal.doc</li>
    <li>hikounomizu</li>
    <li>home-assistant-component-tests.dremel_3d_printer</li>
    <li>home-assistant-component-tests.environment_canada</li>
    <li>hugin</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>ib-controller</li>
    <li>imagination</li>
    <li>in-formant</li>
    <li>intensity-normalization (python311Packages.intensity-normalization)</li>
    <li>intensity-normalization.dist (python311Packages.intensity-normalization.dist)</li>
    <li>jellyfin</li>
    <li>jellyfin-ffmpeg</li>
    <li>jellyfin-ffmpeg.bin</li>
    <li>jellyfin-ffmpeg.data</li>
    <li>jellyfin-ffmpeg.dev</li>
    <li>jellyfin-ffmpeg.doc</li>
    <li>jellyfin-ffmpeg.lib</li>
    <li>jellyfin-ffmpeg.man</li>
    <li>jupyter-all</li>
    <li>kdePackages.kdenlive</li>
    <li>kdePackages.kdenlive.debug</li>
    <li>kdePackages.kdenlive.dev</li>
    <li>kdePackages.kdenlive.devtools</li>
    <li>kdePackages.mlt (qt6Packages.mlt)</li>
    <li>kdePackages.mlt.dev (qt6Packages.mlt.dev)</li>
    <li>krita</li>
    <li>krita-plugin-gmic</li>
    <li>labplot</li>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>librsb</li>
    <li>libsForQt5.kdenlive (plasma5Packages.kdenlive)</li>
    <li>libsForQt5.mauikit-imagetools (plasma5Packages.mauikit-imagetools)</li>
    <li>libsForQt5.mlt (plasma5Packages.mlt)</li>
    <li>libsForQt5.mlt.dev (plasma5Packages.mlt.dev)</li>
    <li>libsForQt5.pix (plasma5Packages.pix)</li>
    <li>libsForQt5.qcsxcad (plasma5Packages.qcsxcad)</li>
    <li>libsForQt5.qcsxcad.dev (plasma5Packages.qcsxcad.dev)</li>
    <li>soundkonverter (libsForQt5.soundkonverter)</li>
    <li>libtensorflow (libtensorflow.python)</li>
    <li>liquidsoap</li>
    <li>local-ai</li>
    <li>maa-assistant-arknights</li>
    <li>maa-cli</li>
    <li>magnetophonDSP.VoiceOfFaust</li>
    <li>manim (python311Packages.manim)</li>
    <li>manim-slides</li>
    <li>manim-slides.dist</li>
    <li>manim.dist (python311Packages.manim.dist)</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>mathematica</li>
    <li>mathematica-cuda</li>
    <li>mathematica-webdoc</li>
    <li>mathematica-webdoc-cuda</li>
    <li>mavproxy</li>
    <li>mavproxy.dist</li>
    <li>medfile</li>
    <li>meerk40t</li>
    <li>meerk40t-camera</li>
    <li>meerk40t-camera.dist</li>
    <li>meerk40t.dist</li>
     [...]

2024-05-08 08:22 UTC, imincik commented
> Result of `nixpkgs-review pr 309595` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
> 
> 74 packages marked as broken and skipped:
> 1101 packages failed to build:
> 96 packages built:

My 128 GB memory + 50GB swap machine went out of memory :). Restarted now.

2024-05-08 19:23 UTC, imincik approved these changes
Changes are good.

I was not able to finish `nixpkgs-review` due too many packages required to be built.

2024-05-09 12:23 UTC, sheepforce commented
> I was not able to finish nixpkgs-review due too many packages required to be built.

Mine is still running and nearly done. 140 packages to go, 1400 done :crossed_fingers: Majority seems to build fine.

2024-05-13 08:31 UTC, sheepforce commented
Alright, here is my full nixpkgs-review, finally finished

Result of `nixpkgs-review pr 309595` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>78 packages marked as broken and skipped:</summary>
  <ul>
    <li>caffeWithCuda</li>
    <li>caffeWithCuda.bin</li>
    <li>deepin.deepin-camera</li>
    <li>deepin.deepin-image-viewer</li>
    <li>deepin.deepin-screen-recorder</li>
    <li>deepin.image-editor</li>
    <li>ezminc</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
    <li>opentoonz</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>python311Packages.clifford</li>
    <li>python311Packages.clifford.dist</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.farm-haystack</li>
    <li>python311Packages.farm-haystack.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.shazamio</li>
    <li>python311Packages.shazamio.dist</li>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
    <li>python311Packages.tensorflow-datasets</li>
    <li>python311Packages.tensorflow-datasets.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.clifford</li>
    <li>python312Packages.clifford.dist</li>
    <li>python312Packages.farm-haystack</li>
    <li>python312Packages.farm-haystack.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.shazamio</li>
    <li>python312Packages.shazamio.dist</li>
    <li>python312Packages.sunpy</li>
    <li>python312Packages.sunpy.dist</li>
    <li>python312Packages.tensordict</li>
    <li>python312Packages.tensordict.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages_6.mivisionx</li>
    <li>rocmPackages_6.mivisionx-cpu</li>
    <li>rocmPackages_6.mivisionx-hip</li>
    <li>shaq</li>
    <li>shaq.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
    <li>worldengine-cli</li>
    <li>worldengine-cli.dist</li>
  </ul>
</details>
<details>
  <summary>656 packages failed to build:</summary>
  <ul>
    <li>ansel</li>
    <li>apacheHttpdPackages.mod_tile (apacheHttpdPackages_2_4.mod_tile)</li>
    <li>appcsxcad</li>
    <li>backgroundremover</li>
    <li>backgroundremover.dist</li>
    <li>cctag</li>
    <li>cctag.dev</li>
    <li>cctag.lib</li>
    <li>citrix_workspace (citrix_workspace_24_02_0)</li>
    <li>citrix_workspace_23_09_0</li>
    <li>citrix_workspace_23_11_0</li>
    <li>cloudcompare</li>
    <li>csxcad</li>
    <li>darktable</li>
    <li>deface</li>
    <li>deface.dist</li>
    <li>deltatouch</li>
    <li>digikam</li>
    <li>easyocr (python311Packages.easyocr)</li>
    <li>easyocr.dist (python311Packages.easyocr.dist)</li>
    <li>entwine</li>
    <li>freecad</li>
    <li>frigate</li>
    <li>gdal (python311Packages.gdal)</li>
    <li>gmt</li>
    <li>gnudatalanguage</li>
    <li>gplates</li>
    <li>gpt2tc</li>
    <li>grass</li>
    <li>haskellPackages.hgdal</li>
    <li>haskellPackages.hgdal.doc</li>
    <li>home-assistant-component-tests.dremel_3d_printer</li>
    <li>home-assistant-component-tests.environment_canada</li>
    <li>hugin</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>ib-controller</li>
    <li>intensity-normalization (python311Packages.intensity-normalization)</li>
    <li>intensity-normalization.dist (python311Packages.intensity-normalization.dist)</li>
    <li>jupyter-all</li>
    <li>labplot</li>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>libsForQt5.pix (plasma5Packages.pix)</li>
    <li>libsForQt5.qcsxcad (plasma5Packages.qcsxcad)</li>
    <li>libsForQt5.qcsxcad.dev (plasma5Packages.qcsxcad.dev)</li>
    <li>libtensorflow (libtensorflow.python)</li>
    <li>manim (python311Packages.manim)</li>
    <li>manim-slides</li>
    <li>manim-slides.dist</li>
    <li>manim.dist (python311Packages.manim.dist)</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>mathematica</li>
    <li>mathematica-cuda</li>
    <li>mathematica-webdoc</li>
    <li>mathematica-webdoc-cuda</li>
    <li>mavproxy</li>
    <li>mavproxy.dist</li>
    <li>medfile</li>
    <li>meerk40t</li>
    <li>meerk40t.dist</li>
    <li>merkaartor</li>
    <li>mysql-workbench</li>
    <li>napari (python311Packages.napari)</li>
    <li>napari.dist (python311Packages.napari.dist)</li>
    <li>obs-studio-plugins.obs-webkitgtk</li>
    <li>octavePackages.mapping</li>
    <li>ome_zarr (python311Packages.ome-zarr)</li>
    <li>ome_zarr.dist (python311Packages.ome-zarr.dist)</li>
    <li>openems</li>
    <li>openmvs</li>
    <li>openorienteering-mapper</li>
    <li>opensplat</li>
    <li>opensplatWithCuda</li>
    <li>paperless-ngx</li>
    <li>paraview</li>
    <li>pdal</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>perl538Packages.Tirex</li>
    <li>perl538Packages.Tirex.devdoc</li>
    <li>photoprism</li>
    <li>printrun</li>
    <li>printrun.dist</li>
    <li>python311Packages.accelerate</li>
    <li>python311Packages.accelerate.dist</li>
    <li>python311Packages.albumentations</li>
    <li>python311Packages.albumentations.dist</li>
    <li>python311Packages.aplpy</li>
    <li>python311Packages.aplpy.dist</li>
    <li>python311Packages.apptools</li>
    <li>python311Packages.apptools.dist</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argos-translate-files.dist</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.argostranslate.dist</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.atomman</li>
    <li>python311Packages.atomman.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.baselines</li>
    <li>python311Packages.baselines.dist</li>
    <li>python311Packages.batchgenerators</li>
    <li>python311Packages.batchgenerators.dist</li>
    <li>python311Packages.bayespy</li>
    <li>python311Packages.bayespy.dist</li>
    <li>python311Packages.boltztrap2</li>
    <li>python311Packages.boltztrap2.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.caffe</li>
    <li>python311Packages.caffe.bin</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python311Packages.clarifai</li>
    <li>python311Packages.clarifai.dist</li>
    <li>python311Packages.cleanlab</li>
    <li>python311Packages.cleanlab.dist</li>
    <li>python311Packages.ctranslate2</li>
    <li>python [...]

2024-05-13 09:44 UTC, sheepforce approved these changes
Some failures in my nixpkgs-review seem to false negatives, e.g. hugin and darktable build just fine. Overall looks good.

2024-05-13 15:24 UTC, markuskowa commented
The result are better when I apply the patch to master and run nixpkgs-review.

Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>72 packages marked as broken and skipped:</summary>
  <ul>
    <li>caffeWithCuda</li>
    <li>caffeWithCuda.bin</li>
    <li>ezminc</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>python311Packages.clifford</li>
    <li>python311Packages.clifford.dist</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.farm-haystack</li>
    <li>python311Packages.farm-haystack.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.shazamio</li>
    <li>python311Packages.shazamio.dist</li>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
    <li>python311Packages.tensorflow-datasets</li>
    <li>python311Packages.tensorflow-datasets.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.clifford</li>
    <li>python312Packages.clifford.dist</li>
    <li>python312Packages.farm-haystack</li>
    <li>python312Packages.farm-haystack.dist</li>
    <li>python312Packages.mayavi</li>
    <li>python312Packages.mayavi.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.shazamio</li>
    <li>python312Packages.shazamio.dist</li>
    <li>python312Packages.sunpy</li>
    <li>python312Packages.sunpy.dist</li>
    <li>python312Packages.tensordict</li>
    <li>python312Packages.tensordict.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>shaq</li>
    <li>shaq.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>
<details>
  <summary>284 packages failed to build:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile</li>
    <li>appcsxcad</li>
    <li>cctag</li>
    <li>cctag.dev</li>
    <li>cctag.lib</li>
    <li>citrix_workspace</li>
    <li>citrix_workspace_23_09_0</li>
    <li>citrix_workspace_23_11_0</li>
    <li>cloudcompare</li>
    <li>csxcad</li>
    <li>entwine</li>
    <li>freecad</li>
    <li>gdal (python311Packages.gdal)</li>
    <li>gmt</li>
    <li>gplates</li>
    <li>grass</li>
    <li>ib-controller</li>
    <li>labplot</li>
    <li>libretranslate (python311Packages.libretranslate)</li>
    <li>libretranslate.dist (python311Packages.libretranslate.dist)</li>
    <li>libsForQt5.pix</li>
    <li>libsForQt5.qcsxcad</li>
    <li>libsForQt5.qcsxcad.dev</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>mathematica</li>
    <li>mathematica-cuda</li>
    <li>mathematica-webdoc</li>
    <li>mathematica-webdoc-cuda</li>
    <li>medfile</li>
    <li>meerk40t</li>
    <li>meerk40t.dist</li>
    <li>merkaartor</li>
    <li>mysql-workbench</li>
    <li>octavePackages.mapping</li>
    <li>openems</li>
    <li>openmvs</li>
    <li>openorienteering-mapper</li>
    <li>paraview</li>
    <li>pdal</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>perl538Packages.Tirex</li>
    <li>perl538Packages.Tirex.devdoc</li>
    <li>pixinsight</li>
    <li>private-gpt</li>
    <li>private-gpt.dist</li>
    <li>python311Packages.accelerate</li>
    <li>python311Packages.accelerate.dist</li>
    <li>python311Packages.argos-translate-files</li>
    <li>python311Packages.argos-translate-files.dist</li>
    <li>python311Packages.argostranslate</li>
    <li>python311Packages.argostranslate.dist</li>
    <li>python311Packages.arviz</li>
    <li>python311Packages.arviz.dist</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.bayespy</li>
    <li>python311Packages.bayespy.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python311Packages.cleanlab</li>
    <li>python311Packages.cleanlab.dist</li>
    <li>python311Packages.dask-image</li>
    <li>python311Packages.dask-image.dist</li>
    <li>python311Packages.dcmstack</li>
    <li>python311Packages.dcmstack.dist</li>
    <li>python311Packages.diffusers</li>
    <li>python311Packages.diffusers.dist</li>
    <li>python311Packages.django-bootstrap4</li>
    <li>python311Packages.django-bootstrap4.dist</li>
    <li>python311Packages.django-bootstrap5</li>
    <li>python311Packages.django-bootstrap5.dist</li>
    <li>python311Packages.fairseq</li>
    <li>python311Packages.fairseq.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.gpt-2-simple</li>
    <li>python311Packages.gpt-2-simple.dist</li>
    <li>python311Packages.grad-cam</li>
    <li>python311Packages.grad-cam.dist</li>
    <li>python311Packages.gradio</li>
    <li>python311Packages.gradio-client</li>
    <li>python311Packages.gradio-client.dist</li>
    <li>python311Packages.gradio-pdf</li>
    <li>python311Packages.gradio-pdf.dist</li>
    <li>python311Packages.gradio.dist</li>
    <li>python311Packages.h5netcdf</li>
    <li>python311Packages.h5netcdf.dist</li>
    <li>python311Packages.heudiconv</li>
    <li>python311Packages.heudiconv.dist</li>
    <li>python311Packages.k-diffusion</li>
    <li>python311Packages.k-diffusion.dist</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.layoutparser.dist</li>
    <li>python311Packages.manifest-ml</li>
    <li>python311Packages.manifest-ml.dist</li>
    <li>python311Packages.mhcflurry</li>
    <li>python311Packages.mhcflurry.dist</li>
    <li>python311Packages.mne-python</li>
    <li>python311Packages.mne-python.dist</li>
    <li>python311Packages.n3fit</li>
    <li>python311Packages.n3fit.dist</li>
    <li>python311Packages.nipype</li>
    <li>python311Packages.nipype.dist</li>
    <li>python311Packages.niworkflows</li>
    <li>python311Packages.niworkflows.dist</li>
    <li>python311Packages.open-clip-torch</li>
    <li>python311Packages.open-clip-torch.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.pdf2docx</li>
    <li>python311Packages.pdf2docx.dist</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.pdfplumber.dist</li>
    <li>python311Packages.peft</li>
    <li>python311Packages.peft.dist</li>
    <li>python311Packages.plotnine</li>
   [...]

2024-05-13 15:25 UTC, markuskowa commented
@imincik note that this may break `gdal`.

2024-05-14 07:15 UTC, imincik commented
> @imincik note that this may break `gdal`.

Great thanks for notification. Can you share the log output of `python311Packages.gdal` build ?

2024-05-14 07:17 UTC, imincik commented
Please don't merge this PR until we investigate and fix the breakages caused by this PR (if any).

2024-05-14 09:00 UTC, markuskowa commented
@imincik  This is the relevant tail of the build log:
```
gdrivers/gxf.py ..ssssss                                                 [ 61%]
gdrivers/hdf5.py ..........ssFE..Fatal Python error: Floating point exception

Current thread 0x00007ffff7696740 (most recent call first):
  File "/nix/store/5jd0c9xi99hviq92h3xvm0nmzlvmzam7-gdal-3.8.5/lib/python3.11/site-packages/osgeo/gdal.py", line 5538 in Checksum
  File "/build/source/build/autotest/gdrivers/hdf5.py", line 454 in test_hdf5_17
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/python.py", line 195 in pytest_pyfunc_call
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/python.py", line 1772 in runtest
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 172 in pytest_runtest_call
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 240 in <lambda>
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 340 in from_call
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 239 in call_and_report
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 134 in runtestprotocol
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 115 in pytest_runtest_protocol
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/main.py", line 364 in pytest_runtestloop
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/main.py", line 339 in _main
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/main.py", line 285 in wrap_session
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/main.py", line 332 in pytest_cmdline_main
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
  File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 174 in main
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 197 in console_main
  File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/pytest/__main__.py", line 7 in <module>
  File "<frozen runpy>", line 88 in _run_code
  File "<frozen runpy>", line 198 in _run_module_as_main

Extension modules: osgeo._gdal, osgeo._gdalconst, osgeo._ogr, osgeo._osr, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, osgeo._gdal_array, osgeo._gnm, lxml._elementpath, lxml.etree, _gdal_python_driver (total: 22)
/nix/store/0hh52fb06c14cnzyhxk0nlhr9ws4d8lx-pytest-check-hook/nix-support/setup-hook: line 53: 15425 Floating point exception(core dumped) /nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/bin/python3.11 -m pytest -k "not test_jp2openjpeg_45 and not test_transformer_dem_overrride_srs and not test_osr_ct_options_area_of_interest and not test_sentinel2_zipped and not test_SetPROJAuxDbPaths and not test_visoss_6 and not test_osr_esri_28" --ignore="gcore/vsis3.py" --ignore="gdrivers/gdalhttp.py" --ignore="gdrivers/wms.py" --benchmark-disable
/nix/store/wq046wv3s3h4m2n9ak3j534di2pzra93-stdenv-linux/setup: line 1579: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/xdinkla57lwm3x60dk6hvqn3rmzh2iih-gdal-3.8.5.drv' failed with exit code 136;
       last 10 log lines:
       >   File "/nix/store/725kzy1ql7a7vkngmnr3r0s87ag820p8-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
       >   File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 174 in main
       >   File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 197 in console_main
       >   File "/nix/store/4w47qwmh7j66pf7qls7ri088zz9hv3pk-python3.11-pytest-8.1.1/lib/python3.11/site-packages/pytest/__main__.py", line 7 in <module>
       >   File "<frozen runpy>", line 88 in _run_code
       >   File "<frozen runpy>", line 198 in _run_module_as_main
       >
       > Extension modules: osgeo._gdal, osgeo._gdalconst, osgeo._ogr, osgeo._osr, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, osgeo._gdal_array, osgeo._gnm, lxml._elementpath, lxml.etree, _gdal_python_driver (total: 22)
       > /nix/store/0hh52fb06c14cnzyhxk0nlhr9ws4d8lx-pytest-check-hook/nix-support/setup-hook: line 53: 15425 Floating point exception(core dumped) /nix/store/k3701zl6gmx3la7y4dnflcvf3xfy88kh-python3-3.11.9/bin/python3.11 -m pytest -k "not test_jp2openjpeg_45 and not test_transformer_dem_overrride_srs and not test_osr_ct [...]

2024-05-23 08:21 UTC, afh requested changes
Thank you @markuskowa for putting up this PR for review.

Please find attached a few suggestions for general improvement.
I've summarised a few additional points below where I wasn't able to comment on the code directly:

* Updating this package provides an opportunity to move it to `pkgs/by-name/hd/hdf5/package.nix`
* ` ++ lib.optionals mpiSupport [ "-DHDF5_ENABLE_PARALLEL=ON" ]`
  could be simplifed to ` ++ lib.optional mpiSupport "-DHDF5_ENABLE_PARALLEL=ON"`
* `with lib;` should probably be removed from `meta` (see #208242)

2024-05-23 12:45 UTC, markuskowa commented on pkgs/tools/misc/hdf5/default.nix
> +    sha256 = "sha256-nKrKGL/bMphJAm8OxvMV5hpBWBhHVNXANqtNv7ouvV0=";
I could have changed, but simply forgot. In general, I think this should be done by automatic tooling and a tree-wide cleanup action.

2024-05-23 13:44 UTC, afh commented
Thank you for considering the suggestions, @markuskowa, and taking the time to respond. I'm happy to put up a refactor PR, unless you as a maintainer feel inclined to do so.

2024-05-23 14:08 UTC, markuskowa commented
> Thank you for considering the suggestions, @markuskowa, and taking the time to respond. I'm happy to put up a refactor PR, unless you as a maintainer feel inclined to do so.

Feel free to open a PR. I am bit short on time at the moment, but I can review it. Just ping me.

2024-05-23 18:43 UTC, afh commented
ℹ️ [HDF5 14.4.3](https://github.com/HDFGroup/hdf5/releases/tag/hdf5_1.14.4.3) was recently released. Would you be okay with updating this PR accordingly, @markuskowa?

I'll put up a refactoring PR, once this has landed, unless someone can tell me how I can create a PR here that will have `markuskowa:upd-hdf5` as the merge target.

2024-05-24 06:40 UTC, imincik commented
> ℹ️ [HDF5 14.4.3](https://github.com/HDFGroup/hdf5/releases/tag/hdf5_1.14.4.3) was recently released. Would you be okay with updating this PR accordingly, @markuskowa?
> 
> I'll put up a refactoring PR, once this has landed, unless someone can tell me how I can create a PR here that will have `markuskowa:upd-hdf5` as the merge target.

+1 for updating this PR.

2024-05-24 06:44 UTC, markuskowa commented
> ℹ️ [HDF5 14.4.3](https://github.com/HDFGroup/hdf5/releases/tag/hdf5_1.14.4.3) was recently released. Would you be okay with updating this PR accordingly, @markuskowa?

Fixes a problem with h5py, and fixes CVEs: https://github.com/HDFGroup/hdf5/releases

I am running nixpkgs-review currently. Will push when finished.

@imincik does not resolve the gdal build failure though.

2024-05-24 06:55 UTC, imincik commented
> @imincik does not resolve the gdal build failure though.

Thanks for checking. I should report this, but not sure where - gdal or hdf5 ?

2024-05-24 10:52 UTC, markuskowa commented
> Thanks for checking. I should report this, but not sure where - gdal or hdf5 ?

gdal-3.9.0 has been released in beginning of May. Is it an option to update to 3.9.0 instead (and hope that the issue disapears)?

2024-05-24 20:21 UTC, markuskowa commented
Result of `nixpkgs-review` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review) (tested against master, not staging to keep build time realistic). 
<details>
  <summary>86 packages marked as broken and skipped:</summary>
  <ul>
    <li>caffeWithCuda</li>
    <li>caffeWithCuda.bin</li>
    <li>ezminc</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>python311Packages.clifford</li>
    <li>python311Packages.clifford.dist</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.farm-haystack</li>
    <li>python311Packages.farm-haystack.dist</li>
    <li>python311Packages.n3fit</li>
    <li>python311Packages.n3fit.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.shazamio</li>
    <li>python311Packages.shazamio.dist</li>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
    <li>python311Packages.tensorflow-datasets</li>
    <li>python311Packages.tensorflow-datasets.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.argos-translate-files</li>
    <li>python312Packages.argos-translate-files.dist</li>
    <li>python312Packages.argostranslate</li>
    <li>python312Packages.argostranslate.dist</li>
    <li>python312Packages.clifford</li>
    <li>python312Packages.clifford.dist</li>
    <li>python312Packages.ctranslate2</li>
    <li>python312Packages.ctranslate2.dist</li>
    <li>python312Packages.farm-haystack</li>
    <li>python312Packages.farm-haystack.dist</li>
    <li>python312Packages.faster-whisper</li>
    <li>python312Packages.faster-whisper.dist</li>
    <li>python312Packages.mayavi</li>
    <li>python312Packages.mayavi.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.shazamio</li>
    <li>python312Packages.shazamio.dist</li>
    <li>python312Packages.sunpy</li>
    <li>python312Packages.sunpy.dist</li>
    <li>python312Packages.tensordict</li>
    <li>python312Packages.tensordict.dist</li>
    <li>python312Packages.tensorflow-bin</li>
    <li>python312Packages.tensorflow-bin.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>python312Packages.translatehtml</li>
    <li>python312Packages.translatehtml.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>shaq</li>
    <li>shaq.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>
<details>
  <summary>193 packages failed to build:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile</li>
    <li>appcsxcad</li>
    <li>citrix_workspace</li>
    <li>citrix_workspace_23_09_0</li>
    <li>citrix_workspace_23_11_0</li>
    <li>cloudcompare</li>
    <li>csxcad</li>
    <li>deltatouch</li>
    <li>entwine</li>
    <li>freecad</li>
    <li>gdal (python311Packages.gdal)</li>
    <li>gmt</li>
    <li>gplates</li>
    <li>grass</li>
    <li>hydrus</li>
    <li>hydrus.doc</li>
    <li>ib-controller</li>
    <li>labplot</li>
    <li>libsForQt5.pix</li>
    <li>libsForQt5.qcsxcad</li>
    <li>libsForQt5.qcsxcad.dev</li>
    <li>mapcache</li>
    <li>mapnik</li>
    <li>mapproxy</li>
    <li>mapproxy.dist</li>
    <li>mapserver</li>
    <li>mathematica</li>
    <li>mathematica-cuda</li>
    <li>mathematica-webdoc</li>
    <li>mathematica-webdoc-cuda</li>
    <li>medfile</li>
    <li>merkaartor</li>
    <li>monero-gui</li>
    <li>mysql-workbench</li>
    <li>octavePackages.mapping</li>
    <li>openems</li>
    <li>openmvs</li>
    <li>openorienteering-mapper</li>
    <li>paraview</li>
    <li>pdal</li>
    <li>perl536Packages.Tirex</li>
    <li>perl536Packages.Tirex.devdoc</li>
    <li>perl538Packages.Tirex</li>
    <li>perl538Packages.Tirex.devdoc</li>
    <li>pixinsight</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.bsuite</li>
    <li>python311Packages.bsuite.dist</li>
    <li>python311Packages.cartopy</li>
    <li>python311Packages.cartopy.dist</li>
    <li>python311Packages.cleanlab</li>
    <li>python311Packages.cleanlab.dist</li>
    <li>python311Packages.django-bootstrap4</li>
    <li>python311Packages.django-bootstrap4.dist</li>
    <li>python311Packages.django-bootstrap5</li>
    <li>python311Packages.django-bootstrap5.dist</li>
    <li>python311Packages.fairseq</li>
    <li>python311Packages.fairseq.dist</li>
    <li>python311Packages.fiona</li>
    <li>python311Packages.fiona.dist</li>
    <li>python311Packages.folium</li>
    <li>python311Packages.folium.dist</li>
    <li>python311Packages.geopandas</li>
    <li>python311Packages.geopandas.dist</li>
    <li>python311Packages.gpt-2-simple</li>
    <li>python311Packages.gpt-2-simple.dist</li>
    <li>python311Packages.grad-cam</li>
    <li>python311Packages.grad-cam.dist</li>
    <li>python311Packages.layoutparser</li>
    <li>python311Packages.layoutparser.dist</li>
    <li>python311Packages.mhcflurry</li>
    <li>python311Packages.mhcflurry.dist</li>
    <li>python311Packages.mne-python</li>
    <li>python311Packages.mne-python.dist</li>
    <li>python311Packages.morecantile</li>
    <li>python311Packages.morecantile.dist</li>
    <li>python311Packages.osmnx</li>
    <li>python311Packages.osmnx.dist</li>
    <li>python311Packages.pdf2docx</li>
    <li>python311Packages.pdf2docx.dist</li>
    <li>python311Packages.pdfplumber</li>
    <li>python311Packages.pdfplumber.dist</li>
    <li>python311Packages.plotnine</li>
    <li>python311Packages.plotnine.dist</li>
    <li>python311Packages.pydicom-seg</li>
    <li>python311Packages.pydicom-seg.dist</li>
    <li>python311Packages.pygmt</li>
    <li>python311Packages.pygmt.dist</li>
    <li>python311Packages.python-csxcad</li>
    <li>python311Packages.python-csxcad.dist</li>
    <li>python311Packages.python-mapnik</li>
    <li>python311Packages.python-mapnik.dist</li>
    <li>python311Packages.python-openems</li>
    <li>python311Packages.python-openems.dist</li>
    <li>python311Packages.rasterio</li>
    <li>python311Packages.rasterio.dist</li>
    <li>python311Packages.rio-tiler</li>
    <li>python311Packages.rio-tiler.dist</li>
    <li>python311Packages.rioxarray</li>
    <li>python311Packages.rioxarray.dist</li>
    <li>python311Packages.shimmy</li>
    <li>python311Packages.shimmy.dist</li>
    <li>python311Packages.tensordict</li>
    <li>python311Packages.tensordict.dist</li>
    <li>python311Packages.tf2onnx</li>
    <li>python311Packages.tf2onnx.dist</li>
    <li>python311Packages.torchrl</li>
    <li>python311Packages.torchrl.dist</li>
    <li>python311Packages.trfl</li>
    <li>python311Packages.trfl.dist</li>
    <li>python311Packages.wktutils</li>
    <li>python311Pack [...]

2024-05-28 06:28 UTC, imincik commented
> > Thanks for checking. I should report this, but not sure where - gdal or hdf5 ?
> 
> gdal-3.9.0 has been released in beginning of May. Is it an option to update to 3.9.0 instead (and hope that the issue disapears)?

Unfortunately, GDAL 3.9.0 is breaking some packages (https://github.com/NixOS/nixpkgs/pull/311310). But it can be worth of checking if it fails with hdf5 1.14.4.3. I'll try to build it now and will report back.

2024-05-28 06:41 UTC, imincik commented
Unfortunately GDAL 3.9.0 fails as well:

```
gdal> gdrivers/hdf5.py ..........ssFE..Fatal Python error: Floating point exception
gdal>
gdal> Current thread 0x00007ffff7eae740 (most recent call first):
gdal>   File "/nix/store/si8whavfph3mc7z5in8vps01087lf0ar-gdal-3.9.0/lib/python3.11/site-packages/osgeo/gdal.py", line 7831 in Checksum
gdal>   File "/build/source/build/autotest/gdrivers/hdf5.py", line 458 in test_hdf5_17
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/python.py", line 195 in pytest_pyfunc_call
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/python.py", line 1772 in runtest
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 172 in pytest_runtest_call
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 240 in <lambda>
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 340 in from_call
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 239 in call_and_report
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 134 in runtestprotocol
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/runner.py", line 115 in pytest_runtest_protocol
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/main.py", line 364 in pytest_runtestloop
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/main.py", line 339 in _main
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/main.py", line 285 in wrap_session
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/main.py", line 332 in pytest_cmdline_main
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_callers.py", line 102 in _multicall
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_manager.py", line 119 in _hookexec
gdal>   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 174 in main
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 197 in console_main
gdal>   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/pytest/__main__.py", line 7 in <module>
gdal>   File "<frozen runpy>", line 88 in _run_code
gdal>   File "<frozen runpy>", line 198 in _run_module_as_main
gdal>
gdal> Extension modules: osgeo._gdal, osgeo._gdalconst, osgeo._ogr, osgeo._osr, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, osgeo._gdal_array, osgeo._gnm, lxml._elementpath, lxml.etree, _gdal_python_driver (total: 22)
gdal> /nix/store/0mizxybbcmki7gnmazmn4vkj9xj2sgnj-pytest-check-hook/nix-support/setup-hook: line 53: 16273 Floating point exception(core dumped) /nix/store/7hnr99nxrd2aw6lghybqdmkckq60j6l9-python3-3.11.9/bin/python3.11 -m pytest -k "not test_jp2openjpeg_45 and not test_transformer_dem_overrride_srs and not test_osr_ct_options_area_of_interest and not test_sentinel2_zipped and not test_SetPROJAuxDbPaths and not test_visoss_6 and not test_osr_esri_28" --ignore="gcore/vsis3.py" --ignore="gdrivers/gdalhttp.py" --ignore="gdrivers/wms.py" --benchmark-disable
gdal> /nix/store/xfhkjnpqjwlf6hlk1ysmq3aaq80f3bjj-stdenv-linux/setup: line 1579: pop_var_context: head of shell_variables not a function context
error: builder for '/nix/store/r2y637ic4wvyynzbdp992kxgks5d3s7b-gdal-3.9.0.drv' failed with exit code 136;
       last 10 log lines:
       >   File "/nix/store/bc5iy2ky85k1v46hfs4myhd0c35i2rmi-python3.11-pluggy-1.4.0/lib/python3.11/site-packages/pluggy/_hooks.py", line 501 in __call__
       >   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 174 in main
       >   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/_pytest/config/__init__.py", line 197 in console_main
       >   File "/nix/store/59clyj18mvjxbkig5z76m0b40pxkxkfq-python3.11-pytest-8.1.1/lib/python3.11/site-packages/pytest/__main__.py", line 7 in <module>
       >   File "<frozen runpy>", line 88 in _run_code
       >   File "<frozen runpy>", line 198 in _run_module_as_main
       >
       > Extension modules: osgeo._gdal, osgeo._gdalconst, osgeo._ogr, osgeo._osr, numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, osgeo._gdal_array, osgeo._gnm, lxml._elementpath, lxml.etree, _gdal_python_driver (total: 22)
       > /nix/store/0mizxybbcmki7gnmazmn4vkj9xj2sgnj-pytest-check-hook/nix-support/setup-hook: line 53: 16273 Floating point exception(core dumped) /nix/store/7hnr99nxrd2a [...]

2024-05-28 06:49 UTC, imincik commented
GDAL build issue reported to HDF5 https://github.com/HDFGroup/hdf5/issues/4527

2024-05-28 20:36 UTC, imincik commented
Both GDAL 3.8 and GDAL 3.9 are building successfully when HDF5 is built with `HDF5_ENABLE_NONSTANDARD_FEATURE_FLOAT16=OFF`.

Patch: 
```
Author: Ivan Mincik <ivan.mincik@gmail.com>
Date:   Tue May 28 22:16:39 2024 +0200

    hdf5: disable _float16 type

diff --git a/pkgs/tools/misc/hdf5/default.nix b/pkgs/tools/misc/hdf5/default.nix
index c279581705b3..503746a2177d 100644
--- a/pkgs/tools/misc/hdf5/default.nix
+++ b/pkgs/tools/misc/hdf5/default.nix
@@ -71,6 +71,7 @@ stdenv.mkDerivation rec {
   cmakeFlags = [
     "-DHDF5_INSTALL_CMAKE_DIR=${placeholder "dev"}/lib/cmake"
     "-DBUILD_STATIC_LIBS=${lib.boolToString enableStatic}"
+    "-DHDF5_ENABLE_NONSTANDARD_FEATURE_FLOAT16=OFF"
   ] ++ lib.optional stdenv.isDarwin "-DHDF5_BUILD_WITH_INSTALL_NAME=ON"
     ++ lib.optional cppSupport "-DHDF5_BUILD_CPP_LIB=ON"
     ++ lib.optional fortranSupport "-DHDF5_BUILD_FORTRAN=ON"
```

Do we want to accept it as the workaround or should we ask GDAL devs for some better solution ?

2024-05-29 07:37 UTC, imincik commented
GDAL fix - https://github.com/OSGeo/gdal/pull/10052

2024-05-29 08:22 UTC, imincik commented
> > GDAL fix - [OSGeo/gdal#10052](https://github.com/OSGeo/gdal/pull/10052)
> 
> That means you could apply the upstream patch to gdal-3.8.5? If so, should we merge this PR then?

Unfortunately,

1. There is still some review process for this patch
2. And it doesn't work for GDAL 3.8

2024-05-29 08:35 UTC, markuskowa commented
@imincik An alternative could be to make the float16 feature optional in HDF5 and turn it off by default. I assume that this feature targets AI workloads. I could give it a try.

2024-05-29 09:26 UTC, markuskowa commented
> An alternative could be to make the float16 feature optional in HDF5 and turn it off by default.

Unfortunately, that breaks `python3Packages.h5py`, which is not good.

2024-05-29 16:33 UTC, jhendersonHDF commented
> > An alternative could be to make the float16 feature optional in HDF5 and turn it off by default.
> 
> Unfortunately, that breaks `python3Packages.h5py`, which is not good.

Hi @markuskowa, it's likely that https://github.com/h5py/h5py/pull/2422 will need to be merged for builds of h5py to work when float16 support is disabled in HDF5.

2024-05-29 16:44 UTC, imincik commented
> @imincik An alternative could be to make the float16 feature optional in HDF5 and turn it off by default. I assume that this feature targets AI workloads. I could give it a try.

I suggest to wait for fix in GDAL (https://github.com/OSGeo/gdal/pull/10052)

2024-06-11 09:05 UTC, imincik commented
[GDAL 3.9](https://github.com/NixOS/nixpkgs/pull/311310) is ready for review  now.

2024-06-19 15:33 UTC, markuskowa commented
Now that GDAL 3.9.0 is merged, should we move forward with merging this PR?

2024-06-20 08:06 UTC, imincik commented
> Now that GDAL 3.9.0 is merged, should we move forward with merging this PR?

Yes !

2024-06-20 09:20 UTC, markuskowa commented
Looks much better now:
Result of `nixpkgs-review` run on x86_64-linux against **master** [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>98 packages marked as broken and skipped:</summary>
  <ul>
    <li>caffeWithCuda</li>
    <li>caffeWithCuda.bin</li>
    <li>ezminc</li>
    <li>khoj</li>
    <li>khoj.dist</li>
    <li>octavePackages.fem-fenics</li>
    <li>octavePackages.image-acquisition</li>
    <li>octavePackages.level-set</li>
    <li>octavePackages.parallel</li>
    <li>octavePackages.sparsersb</li>
    <li>octavePackages.tisean</li>
    <li>octavePackages.vibes</li>
    <li>octavePackages.vrml</li>
    <li>python311Packages.bambi</li>
    <li>python311Packages.bambi.dist</li>
    <li>python311Packages.caffeWithCuda</li>
    <li>python311Packages.caffeWithCuda.bin</li>
    <li>python311Packages.clifford</li>
    <li>python311Packages.clifford.dist</li>
    <li>python311Packages.distrax</li>
    <li>python311Packages.distrax.dist</li>
    <li>python311Packages.dm-sonnet</li>
    <li>python311Packages.dm-sonnet.dist</li>
    <li>python311Packages.elegy</li>
    <li>python311Packages.elegy.dist</li>
    <li>python311Packages.farm-haystack</li>
    <li>python311Packages.farm-haystack.dist</li>
    <li>python311Packages.mhcflurry</li>
    <li>python311Packages.mhcflurry.dist</li>
    <li>python311Packages.n3fit</li>
    <li>python311Packages.n3fit.dist</li>
    <li>python311Packages.openllm</li>
    <li>python311Packages.openllm.dist</li>
    <li>python311Packages.rlax</li>
    <li>python311Packages.rlax.dist</li>
    <li>python311Packages.shazamio</li>
    <li>python311Packages.shazamio.dist</li>
    <li>python311Packages.stytra</li>
    <li>python311Packages.stytra.dist</li>
    <li>python311Packages.sunpy</li>
    <li>python311Packages.sunpy.dist</li>
    <li>python311Packages.tensorflow-datasets</li>
    <li>python311Packages.tensorflow-datasets.dist</li>
    <li>python311Packages.tf2onnx</li>
    <li>python311Packages.tf2onnx.dist</li>
    <li>python311Packages.treex</li>
    <li>python311Packages.treex.dist</li>
    <li>python311Packages.trfl</li>
    <li>python311Packages.trfl.dist</li>
    <li>python311Packages.vllm</li>
    <li>python311Packages.vllm.dist</li>
    <li>python311Packages.worldengine</li>
    <li>python311Packages.worldengine.dist</li>
    <li>python312Packages.argos-translate-files</li>
    <li>python312Packages.argos-translate-files.dist</li>
    <li>python312Packages.argostranslate</li>
    <li>python312Packages.argostranslate.dist</li>
    <li>python312Packages.clifford</li>
    <li>python312Packages.clifford.dist</li>
    <li>python312Packages.ctranslate2</li>
    <li>python312Packages.ctranslate2.dist</li>
    <li>python312Packages.farm-haystack</li>
    <li>python312Packages.farm-haystack.dist</li>
    <li>python312Packages.faster-whisper</li>
    <li>python312Packages.faster-whisper.dist</li>
    <li>python312Packages.mayavi</li>
    <li>python312Packages.mayavi.dist</li>
    <li>python312Packages.mmcv</li>
    <li>python312Packages.mmcv.dist</li>
    <li>python312Packages.mmengine</li>
    <li>python312Packages.mmengine.dist</li>
    <li>python312Packages.pettingzoo</li>
    <li>python312Packages.pettingzoo.dist</li>
    <li>python312Packages.shazamio</li>
    <li>python312Packages.shazamio.dist</li>
    <li>python312Packages.tensordict</li>
    <li>python312Packages.tensordict.dist</li>
    <li>python312Packages.tensorflow-bin</li>
    <li>python312Packages.tensorflow-bin.dist</li>
    <li>python312Packages.torchrl</li>
    <li>python312Packages.torchrl.dist</li>
    <li>python312Packages.translatehtml</li>
    <li>python312Packages.translatehtml.dist</li>
    <li>python312Packages.txtai</li>
    <li>python312Packages.txtai.dist</li>
    <li>python312Packages.worldengine</li>
    <li>python312Packages.worldengine.dist</li>
    <li>rocmPackages.mivisionx</li>
    <li>rocmPackages.mivisionx-cpu</li>
    <li>rocmPackages.mivisionx-hip</li>
    <li>rocmPackages_5.mivisionx</li>
    <li>rocmPackages_5.mivisionx-cpu</li>
    <li>rocmPackages_5.mivisionx-hip</li>
    <li>rocmPackages_5.mivisionx-opencl</li>
    <li>shaq</li>
    <li>shaq.dist</li>
    <li>tts</li>
    <li>tts.dist</li>
  </ul>
</details>
<details>
  <summary>50 packages failed to build:</summary>
  <ul>
    <li>apacheHttpdPackages.mod_tile</li>
    <li>citrix_workspace</li>
    <li>citrix_workspace_23_09_0</li>
    <li>citrix_workspace_23_11_0</li>
    <li>citrix_workspace_24_02_0</li>
    <li>ib-controller</li>
    <li>libsForQt5.pix</li>
    <li>mathematica</li>
    <li>mathematica-cuda</li>
    <li>mathematica-webdoc</li>
    <li>mathematica-webdoc-cuda</li>
    <li>meerk40t</li>
    <li>meerk40t.dist</li>
    <li>mrtrix</li>
    <li>mysql-workbench</li>
    <li>pixinsight</li>
    <li>python311Packages.fairseq</li>
    <li>python311Packages.fairseq.dist</li>
    <li>python311Packages.mne-python</li>
    <li>python311Packages.mne-python.dist</li>
    <li>python311Packages.pdf2docx</li>
    <li>python311Packages.pdf2docx.dist</li>
    <li>python311Packages.pydicom-seg</li>
    <li>python311Packages.pydicom-seg.dist</li>
    <li>python311Packages.pymc</li>
    <li>python311Packages.pymc.dist</li>
    <li>python312Packages.atomman</li>
    <li>python312Packages.atomman.dist</li>
    <li>python312Packages.boltztrap2</li>
    <li>python312Packages.boltztrap2.dist</li>
    <li>python312Packages.ffcv</li>
    <li>python312Packages.ffcv.dist</li>
    <li>python312Packages.mne-python</li>
    <li>python312Packages.mne-python.dist</li>
    <li>python312Packages.opensfm</li>
    <li>python312Packages.opensfm.dist</li>
    <li>python312Packages.pdf2docx</li>
    <li>python312Packages.pdf2docx.dist</li>
    <li>python312Packages.pydicom-seg</li>
    <li>python312Packages.pydicom-seg.dist</li>
    <li>python312Packages.simple-dftd3</li>
    <li>python312Packages.simple-dftd3.dist</li>
    <li>python312Packages.sumo</li>
    <li>python312Packages.sumo.dist</li>
    <li>python312Packages.wrf-python</li>
    <li>python312Packages.wrf-python.dist</li>
    <li>sasview</li>
    <li>sasview.dist</li>
    <li>wolfram-engine</li>
    <li>wolfram-notebook</li>
  </ul>
</details>
<details>
  <summary>1284 packages built:</summary>
  <ul>
    <li>LPCNet</li>
    <li>actiona</li>
    <li>aitrack</li>
    <li>alembic</li>
    <li>alembic.bin</li>
    <li>alembic.dev</li>
    <li>alembic.lib</li>
    <li>ansel</li>
    <li>ants</li>
    <li>appcsxcad</li>
    <li>armadillo</li>
    <li>audiobookshelf</li>
    <li>auto-multiple-choice</li>
    <li>avogadro2</li>
    <li>backgroundremover</li>
    <li>backgroundremover.dist</li>
    <li>bicgl</li>
    <li>bicpl</li>
    <li>blender</li>
    <li>blender-hip</li>
    <li>c3d</li>
    <li>caffe</li>
    <li>caffe.bin</li>
    <li>cctag</li>
    <li>cctag.dev</li>
    <li>cctag.lib</li>
    <li>cdo</li>
    <li>cloudcompare</li>
    <li>conglomerate</li>
    <li>cp2k</li>
    <li>crystfel</li>
    <li>crystfel-headless</li>
    <li>csxcad</li>
    <li>darktable</li>
    <li>deepin.deepin-ocr-plugin-manager</li>
    <li>deface</li>
    <li>deface.dist</li>
    <li>deltatouch</li>
    <li>diffoscope</li>
    <li>diffoscope.dist</li>
    <li>diffoscope.man</li>
    <li>digikam</li>
    <li>easyocr (python311Packages.easyocr)</li>
    <li>easyocr.dist (python311Packages.easyocr.dist)</li>
    <li>ebtks</li>
    <li>eccodes</li>
    <li>elastix</li>
    <li>enblend-enfuse</li>
    <li>entwine</li>
    <li>escrotum</li>
    <li>escrotum.dist</li>
    <li>escrotum.man</li>
    <li>facedetect</li>
    <li>faust2jack</li>
    <li>ffcast</li>
    <li>ffmpeg-full (ffmpeg_6-full)</li>
    <li>ffmpeg-full.bin (ffmpeg_6-full.bin)</li>
    <li>ffmpeg-full.data (ffmpeg_6-full.data)</li>
    <li>ffmpeg-full.dev (ffmpeg_6-full.dev)</li>
    <li>ffmpeg-full.doc (ffmpeg_6-full.doc)</li>
    <li>ffmpeg-full.lib (ffmpeg_6-full.lib)</li>
    <li>ffmpeg-full.man (ffmpeg_6-full.man)</li>
    <li>ffmpeg_4-full</li>
    <li>ffmpeg_4-full.bin</ [...]

2024-06-20 09:58 UTC, merged

2024-06-20 10:32 UTC, imincik commented
Great thanks @markuskowa

2024-07-03 06:42 UTC, vcunat commented
FYI, this or something else recent broke x86_64-darwin build (only that one, I think)
https://hydra.nixos.org/build/264567971

2024-07-04 20:29 UTC, vcunat commented
Worked around in 1a386e193d1a19e3e176f4642697f5abae60b126 + 1549705430e31d7e1485db67b51335ce5915d1e7.  I hope `_Float16` isn't important for us.