python3Packages.pipetools: init at 1.1.0
NixOS/nixpkgs pull request #309716
Opened 2024-05-07 03:02 UTC by RmiTtro

## Description of changes

Added python lib: https://0101.github.io/pipetools/doc/

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-07 03:03 UTC, DontEatOreo commented on pkgs/development/python-modules/pipetools/default.nix
> +    license = licenses.mit;
```suggestion
  meta = {
    description = "A library that enables function composition similar to using Unix pipes";
    homepage = https://0101.github.io/pipetools/;
    license = lib.licenses.mit;
```

2024-05-07 03:06 UTC, DontEatOreo requested changes

2024-05-07 03:06 UTC, DontEatOreo commented on pkgs/development/python-modules/pipetools/default.nix
> +}:
```suggestion
{
  lib,
  buildPythonPackage,
  fetchFromGitHub,
  pytestCheckHook,
  setuptools,
}:
```

2024-05-07 03:06 UTC, DontEatOreo commented on pkgs/development/python-modules/pipetools/default.nix
> +  ];
```suggestion
  nativeCheckInputs = [ pytestCheckHook ];
```

2024-05-07 03:06 UTC, DontEatOreo commented on pkgs/development/python-modules/pipetools/default.nix
> +  ];
```suggestion
  propagatedBuildInputs = [ setuptools ];
```

2024-05-07 03:06 UTC, DontEatOreo commented on pkgs/development/python-modules/pipetools/default.nix
> +  ];
```suggestion
  pythonImportsCheck = [ "pipetools" ];
```

2024-05-07 03:07 UTC, DontEatOreo commented
For the formatting changes please run `nix run nixpkgs#nixfmt-rfc-style -- pkgs/development/python-modules/pipetools/default.nix`

2024-05-07 03:19 UTC, RmiTtro commented
> For the formatting changes please run `nix run nixpkgs#nixfmt-rfc-style -- pkgs/development/python-modules/pipetools/default.nix`

Will do, thank you for the quick review.

2024-05-07 03:44 UTC, RmiTtro commented
Result of `nixpkgs-review pr 309716` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.pipetools</li>
    <li>python311Packages.pipetools.dist</li>
    <li>python312Packages.pipetools</li>
    <li>python312Packages.pipetools.dist</li>
  </ul>
</details>

2024-05-07 19:50 UTC, DontEatOreo commented on pkgs/development/python-modules/pipetools/default.nix
> +    license = licenses.mit;
```suggestion
  meta = {
    description = "A library that enables function composition similar to using Unix pipes";
    homepage = "https://0101.github.io/pipetools/";
    license = lib.licenses.mit;
```

2024-05-07 19:51 UTC, DontEatOreo commented
Please rebase and squash 31ef449727d9e1ea4526d7df269f7ab485d891fb into a19e956b340d22dc27f64765dfec8736f9e9af14

2024-05-08 01:01 UTC, DontEatOreo commented
Result of `nixpkgs-review pr 309716` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.pipetools</li>
    <li>python311Packages.pipetools.dist</li>
    <li>python312Packages.pipetools</li>
    <li>python312Packages.pipetools.dist</li>
  </ul>
</details>

2024-05-08 01:03 UTC, DontEatOreo commented
Result of `nixpkgs-review pr 309716` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.pipetools</li>
    <li>python311Packages.pipetools.dist</li>
    <li>python312Packages.pipetools</li>
    <li>python312Packages.pipetools.dist</li>
  </ul>
</details>

2024-05-08 01:03 UTC, DontEatOreo approved these changes

2024-05-16 16:23 UTC, matthiasbeyer approved these changes

2024-05-16 17:21 UTC, matthiasbeyer commented
Result of `nixpkgs-review pr 309716` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.pipetools</li>
    <li>python311Packages.pipetools.dist</li>
    <li>python312Packages.pipetools</li>
    <li>python312Packages.pipetools.dist</li>
  </ul>
</details>

2024-05-16 17:47 UTC, merged