Add parinfer-rust-emacs v0.4.6
NixOS/nixpkgs pull request #310468
Opened 2024-05-10 01:20 UTC by brsvh

## Description of changes

Add parinfer-rust-emacs v0.4.6, which is a fork of parinfer-rust (`kakounePlugins.parinfer-rust`).

It will be useful for people who use `emacsPackages.parinfer-rust-mode`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-12 12:46 UTC, jian-lin requested changes
Please change the commit message from `parinfer-rust-emacs: init at v0.4.6` to `parinfer-rust-emacs: init at 0.4.6`.

https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions

2024-05-12 12:46 UTC, jian-lin commented on pkgs/by-name/pa/parinfer-rust-emacs/package.nix
> +  ];
Not needed now.

https://github.com/ubolonton/emacs-module-rs/commit/cad972872c61ad2b402a309d2c787b5195e0d503

2024-05-12 12:46 UTC, jian-lin commented on pkgs/by-name/pa/parinfer-rust-emacs/package.nix
> +  meta = with lib; {
Please remove empty lines in `meta`.

2024-05-13 02:34 UTC, brsvh commented
@jian-lin All suggestions have been resolved, thanks for your guidance :)

2024-05-13 03:16 UTC, jian-lin commented on maintainers/maintainer-list.nix
> +        fingerprint = "7B740DB9F2AC6D3B226BC53078D74502D92E0218";
Still not correct

2024-05-13 08:23 UTC, nicoonoclaste reviewed
Looks good, aside from the fingerprint formatting issue

2024-05-15 08:11 UTC, jian-lin requested changes
All good except the format of fingerprint.

2024-05-15 08:11 UTC, jian-lin commented on maintainers/maintainer-list.nix
> +        fingerprint = "7B74 0DB9 F2AC6 D3B22 6BC53 078D7 4502 D92E 0218";
still not correct (comment here again in case you missed [my last comment](https://github.com/NixOS/nixpkgs/pull/310468#discussion_r1597822279))

2024-05-16 07:42 UTC, jian-lin requested changes

2024-05-16 09:54 UTC, brsvh commented on maintainers/maintainer-list.nix
> +    keys = [ { fingerprint = "7B74 0DB9 F2AC 6D3B 226B C530 78D7 4502 D92E 0218"; } ];
Fixed. Sorry, I'm too careless.

2024-05-16 15:27 UTC, jian-lin approved these changes
LGTM

Thanks and welcome to the Nix family!

2024-05-16 15:29 UTC, jian-lin commented on maintainers/maintainer-list.nix
> +    keys = [ { fingerprint = "7B74 0DB9 F2AC 6D3B 226B C530 78D7 4502 D92E 0218"; } ];
No worries, we all make mistakes.

2024-05-16 15:29 UTC, merged

2024-06-09 01:08 UTC, juuyokka commented
Great work @brsvh, I'm happy to see this package exists now. One thing I may add is on Darwin, `emacsPackages.parinfer-rust-mode` expects the library file to have an extension of `.so`, but the rust toolchain compiles dynamic libraries with the extension `.dylib`. Since this package was made solely to be used with `parinfer-rust-mode`, it would make sense to change the extension for Darwin.

2024-06-09 11:24 UTC, brsvh commented
> `emacsPackages.parinfer-rust-mode` expects the library file to have the extension `.so`, but the rust toolchain compiles dynamic libraries with the extension `.dylib`.

The problem you said stems from here.

https://github.com/justinbarclay/parinfer-rust-mode/blob/32559238058d0a5dc874d63b6d6de6637aacf73f/parinfer-rust-mode.el#L200

 However, it seems that directly set `parinfer-rust-library` to use `.dylib` might solve this problem. 

https://github.com/justinbarclay/parinfer-rust-mode/blob/32559238058d0a5dc874d63b6d6de6637aacf73f/parinfer-rust-mode.el#L215-L216

Have you tried this approach?