python311Packages.dask-yarn: mark as unsupported on python 3.12
NixOS/nixpkgs pull request #310935
Opened 2024-05-11 21:25 UTC by GaetanLepage

## Description of changes

It seems to rely on `versioneer` stuff that is incompatible with python 3.12.
Note: There has been no releases since April 2021, so this package might be unmaintained (last commit from June 2022).

cc @illustris 

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-11 21:31 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 310935` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

2024-05-11 21:31 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 310935` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)

2024-05-11 21:31 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 310935` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)

2024-05-11 21:32 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 310935` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)

2024-05-12 03:31 UTC, illustris commented
Versioneer supports python 3.12. The issue here is that the bundled versioneer.py in the repo is outdated. This can be fixed similar to this PR for skein: https://github.com/NixOS/nixpkgs/pull/310218/files#diff-86ca46f8580a8a9246614cee5e1fdba5b0a78aef74ab8ae283fe9fa6b588d2feR51

2024-05-12 03:50 UTC, illustris requested changes

2024-05-12 03:50 UTC, illustris commented on pkgs/development/python-modules/dask-yarn/default.nix
> +, pythonAtLeast
```suggestion
, versioneer
```

2024-05-12 03:50 UTC, illustris commented on pkgs/development/python-modules/dask-yarn/default.nix
> +  disabled = pythonOlder "3.7" || pythonAtLeast "3.12";
```suggestion
  disabled = pythonOlder "3.7";
  postPatch = "rm versioneer.py";
  build-system = [ versioneer ];
```

2024-05-12 09:33 UTC, GaetanLepage commented on pkgs/development/python-modules/dask-yarn/default.nix
> +, pythonAtLeast
Indeed it works ! Thanks @illustris

2024-05-12 09:39 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 310935` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.dask-yarn</li>
    <li>python311Packages.dask-yarn.dist</li>
    <li>python312Packages.dask-yarn</li>
    <li>python312Packages.dask-yarn.dist</li>
  </ul>
</details>

2024-05-12 09:39 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 310935` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.dask-yarn</li>
    <li>python311Packages.dask-yarn.dist</li>
    <li>python312Packages.dask-yarn</li>
    <li>python312Packages.dask-yarn.dist</li>
  </ul>
</details>

2024-05-12 09:40 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 310935` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.dask-yarn</li>
    <li>python311Packages.dask-yarn.dist</li>
    <li>python312Packages.dask-yarn</li>
    <li>python312Packages.dask-yarn.dist</li>
  </ul>
</details>

2024-05-12 09:40 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 310935` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.dask-yarn</li>
    <li>python311Packages.dask-yarn.dist</li>
    <li>python312Packages.dask-yarn</li>
    <li>python312Packages.dask-yarn.dist</li>
  </ul>
</details>

2024-05-12 12:27 UTC, illustris approved these changes
Thanks!

2024-05-12 15:21 UTC, merged