cppman: init at unstable-2024-02-15
NixOS/nixpkgs pull request #311178
Opened 2024-05-12 21:30 UTC by LamprosPitsillos

https://github.com/aitjcize/cppman

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-21 19:47 UTC, pluiedev requested changes
Result of `nixpkgs-review pr 311178` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>cppman</li>
    <li>cppman.dist</li>
  </ul>
</details>

2024-05-21 19:47 UTC, pluiedev commented on pkgs/by-name/cp/cppman/package.nix
> +  version = "unstable-2024-02-15";
```suggestion
  version = "0-unstable-2024-02-15";
```
[See `pkgs/README.md` for more info about the version format](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-naming)

2024-05-21 19:47 UTC, pluiedev commented on pkgs/by-name/cp/cppman/package.nix
> +  meta = with lib; {
[Avoid `with lib;`](https://github.com/NixOS/nixpkgs/issues/208242)

2024-06-04 19:33 UTC, LamprosPitsillos commented
Anything else blocking this ?

2024-06-05 06:05 UTC, pluiedev approved these changes

2024-06-10 14:05 UTC, pbsds commented
I found an upstream issue with cppman, please `fetchpatch` this https://github.com/aitjcize/cppman/pull/173

2024-06-26 00:50 UTC, Dich0tomy commented
I fear this won't suffice. When using the code from this page we run into a problem when doing `cppman -m true`. It tries to install the manpages globally by changing the `.manpath` file, but this file is typically managed externally through home manager. Can there be anything done about that?

2024-06-26 03:49 UTC, LamprosPitsillos commented
> I fear this won't suffice. When using the code from this page we run into a problem when doing `cppman -m true`. It tries to install the manpages globally by changing the `.manpath` file, but this file is typically managed externally through home manager. Can there be anything done about that?

Thanks for reminding me, i will try in the weekend to address the issues and finish the pr.

Usually a patch is created removing any functionality that modifys the filesystem that is managed by nix.

2024-07-30 18:42 UTC, JohnRTitor reviewed
I have updated the package since 0.5.7 is released

2025-06-21 15:16 UTC, ryan4yin commented on pkgs/by-name/cp/cppman/package.nix
> +    python3Packages.wheel
Fix the error `ModuleNotFoundError: No module named 'distutils'`:

```suggestion
    python3Packages.wheel
    python3Packages.distutils
```

2025-06-21 15:26 UTC, ryan4yin commented
@LamprosPitsillos I think we can merge this PR first after fix the build error via my suggestion.
`cppman -m true` is not a big problem, we can use cppman without it.

2025-07-28 14:40 UTC, ryan4yin commented
Closed due to inactivity and as #426830 has been merged.

@LamprosPitsillos If you're still using cppman, feel free to join as a maintainer

2025-07-28 14:40 UTC, closed without merging