dbgate: init at 5.2.7
NixOS/nixpkgs pull request #311405
Opened 2024-05-13 16:13 UTC by luftmensch-luftmensch

## Description of changes
Closes #306756

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-13 16:13 UTC, luftmensch-luftmensch commented
```
> nix build .#dbgate
> tree result/
 result
└──  bin
   └──  dbgate
```

2024-05-16 22:38 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/3950

2024-05-17 16:57 UTC, Misterio77 approved these changes

2024-05-17 17:01 UTC, luftmensch-luftmensch commented on pkgs/by-name/db/dbgate/package.nix
> +    ];
Done!

@Misterio77 Did you also have the capability to merge it?

2024-05-17 17:28 UTC, Misterio77 commented on pkgs/by-name/db/dbgate/package.nix
> +    ];
Sadly no, I might nominate myself for the commit bit at some point tho haha.

2024-05-17 17:29 UTC, Misterio77 approved these changes
LGTM!

2024-05-18 12:03 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1649

2024-05-20 12:38 UTC, luftmensch-luftmensch commented
@Misterio77 Since the package had a new release and the PR is still opened I thought it was a good idea to bump the version to 5.2.8 (without the need to make a new pr in a hopefully short time)

The approval should be fast enought

2024-05-20 15:13 UTC, Misterio77 commented
Result of `nixpkgs-review pr 311405` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dbgate</li>
  </ul>
</details>

2024-05-20 15:13 UTC, Misterio77 approved these changes

2024-05-20 18:31 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1661

2024-06-02 14:46 UTC, SuperSandro2000 requested changes

2024-06-02 14:46 UTC, SuperSandro2000 commented on pkgs/by-name/db/dbgate/package.nix
> +          url = "https://github.com/${pname}/${pname}/releases/download/v${version}/${pname}-${version}-mac_x64.dmg";
```suggestion
        aarch64-linux = {
          url = "https://github.com/dbgate/dbgate/releases/download/v${version}/dbgate-${version}-linux_arm64.AppImage";
          hash = "sha256-gxojSSk7prhnd9fy56B9H+Cj6COBLc7xPfV8dTvSO0c=";
        };
        x86_64-linux = {
          url = "https://github.com/dbgate/dbgate/releases/download/v${version}/dbgate-${version}-linux_x86_64.AppImage";
          hash = "sha256-/Vfd0R+Mzx1CJKkC7dj99pbuuyh8PJtbYlH3wtwVxSM=";
        };
        x86_64-darwin = {
          url = "https://github.com/dbgate/dbgate/releases/download/v${version}/dbgate-${version}-mac_x64.dmg";
```
substituting pname is an anti pattern

2024-06-02 14:47 UTC, SuperSandro2000 commented on pkgs/by-name/db/dbgate/package.nix
> +      .${stdenv.system} or (throw "${pname}-${version}: ${stdenv.system} is unsupported.");
```suggestion
      .${stdenv.system} or (throw "dbgate: ${stdenv.system} is unsupported.");
```

2024-06-02 14:52 UTC, luftmensch-luftmensch commented on pkgs/by-name/db/dbgate/package.nix
> +          url = "https://github.com/${pname}/${pname}/releases/download/v${version}/${pname}-${version}-mac_x64.dmg";
Didn't know that. Applied suggestion

2024-06-02 17:28 UTC, SuperSandro2000 approved these changes

2024-06-02 17:28 UTC, merged