Miracode: init at 1.0
NixOS/nixpkgs pull request #311743
Opened 2024-05-14 20:46 UTC by Coca162

## Description of changes

Miracode is a vectorized version of the [Monocraft](https://github.com/IdreesInc/Monocraft) font. 

Since this is my first contribution I am also adding myself to maintainer list!

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-15 16:42 UTC, misuzu requested changes
Welcome! I've added some suggestions, but LGTM otherwise.

2024-05-15 16:42 UTC, misuzu commented on pkgs/by-name/mi/miracode/package.nix
> +
```suggestion
  dontUnpack = true;
```

2024-05-15 16:42 UTC, misuzu commented on pkgs/by-name/mi/miracode/package.nix
> +    install -Dm644 -t $out/share/fonts/truetype *.ttf
```suggestion
    mkdir -p $out/share/fonts/truetype
    ln -s $src $out/share/fonts/truetype/Miracode.ttf
```

2024-05-15 17:18 UTC, misuzu approved these changes

2024-05-16 08:32 UTC, Aleksanaa commented on pkgs/by-name/mi/miracode/package.nix
> +stdenv.mkDerivation {
```suggestion
stdenvNoCC.mkDerivation {
```

2024-05-16 08:32 UTC, Aleksanaa commented on pkgs/by-name/mi/miracode/package.nix
> +    ln -s $src $out/share/fonts/truetype/Miracode.ttf
```suggestion
    install -Dm644 $src $out/share/fonts/truetype/Miracode.ttf
```

(No need to mkdir)

Don't use `ln`, as we don't want the final package to depend on `src`

2024-05-17 02:13 UTC, RaghavSood approved these changes

2024-05-17 03:17 UTC, merged

2024-05-19 03:06 UTC, Hellodan1 commented
excellent work coca162