sfml: 2.5.1 -> 2.6.1; csfml: 2.5.2 -> 2.6.0
NixOS/nixpkgs pull request #312161
Opened 2024-05-16 09:02 UTC by drawbu

## Description of changes

Just updated the packages

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-16 09:03 UTC, drawbu commented
@ofborg build sfml csfml

2024-05-16 09:58 UTC, Sigmanificient requested changes

2024-05-16 09:58 UTC, Sigmanificient commented on pkgs/development/libraries/csfml/default.nix
> -    sha256 = "sha256-A5C/4SnxUX7mW1wkPWJWX3dwMhrJ79DkBuZ7UYzTOqE=";
use `finalAttrs.version`

2024-05-16 10:16 UTC, Sigmanificient requested changes

2024-05-16 10:16 UTC, Sigmanificient commented on pkgs/development/libraries/sfml/default.nix
> +    ++ lib.optionals (!stdenv.isDarwin) [ libX11 libXrandr libXrender xcbutilimage libXcursor]
```suggestion
    ++ lib.optionals (!stdenv.isDarwin) [ libX11 libXrandr libXrender xcbutilimage libXcursor ]
```

2024-05-16 10:27 UTC, drawbu commented
@ofborg build sfml csfml

2024-05-17 19:00 UTC, Sigmanificient approved these changes

2024-05-18 13:33 UTC, drawbu commented
Result of `nixpkgs-review pr 312161` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages marked as broken and skipped:</summary>
  <ul>
    <li>dolphin-emu-primehack</li>
    <li>libretro.dolphin</li>
    <li>retroarchFull</li>
  </ul>
</details>
<details>
  <summary>9 packages built:</summary>
  <ul>
    <li>antsimulator</li>
    <li>cutecapture</li>
    <li>dolphin-emu</li>
    <li>openrw</li>
    <li>python311Packages.nocturne</li>
    <li>python311Packages.nocturne.dist</li>
    <li>python312Packages.nocturne</li>
    <li>python312Packages.nocturne.dist</li>
    <li>sfml</li>
  </ul>
</details>

2024-05-20 10:56 UTC, drawbu commented
Result of `nixpkgs-review pr 312161` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>shadered</li>
  </ul>
</details>
<details>
  <summary>25 packages built:</summary>
  <ul>
    <li>EmptyEpsilon</li>
    <li>antsimulator</li>
    <li>attract-mode</li>
    <li>csfml</li>
    <li>cutecapture</li>
    <li>dolphin-emu</li>
    <li>dolphin-emu-primehack</li>
    <li>extremetuxracer</li>
    <li>guvcview</li>
    <li>libretro.dolphin</li>
    <li>lutris</li>
    <li>lutris-free</li>
    <li>marble-marcher-ce</li>
    <li>mars</li>
    <li>opendungeons</li>
    <li>openrw</li>
    <li>python311Packages.nocturne</li>
    <li>python311Packages.nocturne.dist</li>
    <li>python312Packages.nocturne</li>
    <li>python312Packages.nocturne.dist</li>
    <li>qstopmotion</li>
    <li>retroarchFull</li>
    <li>sfml</li>
    <li>simplenes</li>
    <li>vbam</li>
  </ul>
</details>

2024-05-21 07:05 UTC, drawbu commented
pkg-config is broken upsream.
See https://github.com/SFML/SFML/pull/2835

2024-05-21 07:10 UTC, Sigmanificient commented
> pkg-config is broken upsream. See [SFML/SFML#2835](https://github.com/SFML/SFML/pull/2835)

Maybe you would do a revert pr upstream explaining the issue, since it was originally done to improve nix support

2024-05-21 07:46 UTC, Sigmanificient commented
When building the `csfml` package without the patches, nix gives the following error:

```
Broken paths found in a .pc file! /nix/store/g230r8pdkgzfwjn7a2c9r7vapidg2dkg-csfml-2.6.1/lib/pkgconfig/csfml-network.pc
The following lines have issues (specifically '//' in paths).
3:libdir=${exec_prefix}//nix/store/g230r8pdkgzfwjn7a2c9r7vapidg2dkg-csfml-2.6.1/lib
It is very likely that paths are being joined improperly.
ex: "${prefix}/@CMAKE_INSTALL_LIBDIR@" should be "@CMAKE_INSTALL_FULL_LIBDIR@"
Please see https://github.com/NixOS/nixpkgs/issues/144170 for more details.
```

Following nix advise, I tried to build with these changes:
```diff
--- a/pkgs/by-name/cs/csfml/package.nix    2024-05-21 09:41:18.068576345 +0200
+++ b/pkgs/by-name/cs/csfml/package.nix    2024-05-21 09:40:58.865882958 +0200
@@ -20,7 +20,11 @@
   nativeBuildInputs = [ cmake ];
   buildInputs = [ sfml ];
   cmakeFlags = [ "-DCMAKE_MODULE_PATH=${sfml}/share/SFML/cmake/Modules/" ];
-  patches = [ ./pkgconfig.patch ];
+
+  prePatch = ''
+   substituteInPlace tools/pkg-config/* \
+     --replace-fail 'libdir=''${exec_prefix}/@CMAKE_INSTALL_LIBDIR@' "libdir=@CMAKE_INSTALL_FULL_LIBDIR@"
+  '';
 
   meta = {
     homepage = "https://www.sfml-dev.org/";
```
It produces a valid `pkg-config` file:

![image](https://github.com/NixOS/nixpkgs/assets/53050011/7f390491-cada-43ad-aaa5-1c3b5cfeabef)

This always work for the `sfml` package itself:
```diff
--- pkgs/by-name/sf/sfml/package.nix	2024-05-21 09:43:51.753121811 +0200
+++ pkgs/by-name/sf/sfml/package2.nix	2024-05-21 09:45:15.739780043 +0200
@@ -66,18 +66,14 @@
   ];
 
   patches = [
-    # Fix pkg-config
-    # See https://github.com/SFML/SFML/issues/2815
-    # Also, too much changes in CMakeLists.txt and changelog.md,
-    # so we patchin cmake ourself
-    (fetchpatch {
-      url = "https://patch-diff.githubusercontent.com/raw/SFML/SFML/pull/2835.patch";
-      hash = "sha256-kdOAXR9YPQllx64z9dgwCV+vy0cJvIsZZboZKFc4Q8Q=";
-      excludes = [ "changelog.md" "CMakeLists.txt" ];
-    })
     ./CMakeLists.txt-pkgconfig.patch
   ];
 
+  prePatch = ''
+   substituteInPlace tools/pkg-config/* \
+     --replace-fail 'libdir=''${exec_prefix}/@CMAKE_INSTALL_LIBDIR@' "libdir=@CMAKE_INSTALL_FULL_LIBDIR@"
+  '';
+
   meta = {
     homepage = "https://www.sfml-dev.org/";
     description = "Simple and fast multimedia library";
```

This approach would avoid storing the custom version of the patch within the package folder

2024-05-21 07:57 UTC, Sigmanificient requested changes

2024-05-21 07:57 UTC, Sigmanificient commented on pkgs/by-name/sf/sfml/package.nix
> +
Lets split the package between `out` & `dev`
```suggestion

  outputs = [ "out" "dev" ];
```

2024-05-21 07:57 UTC, Sigmanificient commented on pkgs/by-name/cs/csfml/package.nix
Lets split the package between `out` & `dev`
```suggestion

  outputs = [ "out" "dev" ];
```

2024-05-21 09:33 UTC, drawbu commented
dev out change broke csfml. Currently trying to fix the issue

2024-05-22 12:21 UTC, drawbu commented
https://github.com/ofborg build sfml csfml

2024-05-22 12:23 UTC, drawbu commented
When the build end, the pr should be good to go. Waiting for review by maintainers

2024-05-23 07:54 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/3979

2024-05-23 11:50 UTC, Sigmanificient approved these changes

2024-06-06 12:28 UTC, drawbu commented
We still have no answer from the maintainers of both sfml and csfml after 3 weeks. I'm adding myself as maintainer

2024-06-06 14:08 UTC, SuperSandro2000 commented on pkgs/by-name/cs/csfml/package.nix
> +  prePatch = ''
```suggestion
  postPatch = ''
```

2024-10-13 09:31 UTC, drawbu commented
fixed merge conflict with e0464e47880a69896f0fb1810f00e0de469f770a

2024-10-13 09:34 UTC, drawbu commented
One this pr is good to go, i will squash all that mess

2024-10-13 10:23 UTC, drawbu commented on pkgs/by-name/cs/csfml/package.nix
> +      --replace-fail 'libdir=''${exec_prefix}/@CMAKE_INSTALL_LIBDIR@' "libdir=@CMAKE_INSTALL_FULL_LIBDIR@"
Sorry for late response
https://github.com/SFML/CSFML/pull/374

2024-10-13 11:07 UTC, drawbu commented
When my PR gets merged upstream in the CSFML repo, all patches can be deleted when the `3.0.0` (works for the moment at least)

2025-03-23 15:05 UTC, closed without merging