pgx_ulid: init at 0.1.5
NixOS/nixpkgs pull request #312398
Opened 2024-05-17 08:28 UTC by k0001

## Description of changes

Initial packaging of the `pgx_ulid` extension for PostgreSQL.

https://github.com/pksunkara/pgx_ulid

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-27 08:40 UTC, k0001 commented
Version `0.1.5` of `pgx_ulid` came out, so I updated this pull-request to use that newer version.

2024-07-03 02:53 UTC, steadygaze commented
This PR seems stalled; is there anything I can do to help get it merged?

2024-09-18 08:33 UTC, pksunkara commented
What's blocking this from being merged? Who needs to approve?

2024-09-27 18:26 UTC, wolfgangwalther requested changes
Since the "init" commit is not merged, yet, you can squash both commits and "init at 0.1.5" instead of updating immediately after.

2025-01-02 03:56 UTC, steadygaze commented
FYI v0.2.0 has just recently released:
- https://github.com/pksunkara/pgx_ulid/releases/tag/v0.2.0
- https://github.com/pksunkara/pgx_ulid/compare/v0.1.5...v0.2.0

2025-01-02 03:57 UTC, pksunkara commented
As mentioned [here](https://github.com/pksunkara/pgx_ulid/pull/57#discussion_r1899885911), the build process needs to be updated.

2025-01-02 22:25 UTC, myypo commented
Minimal building example for the new version. Could not trick pgrx tests into using the already built extension with the running postgres instance.

```nix
{
  buildPgrxExtension,
  fetchFromGitHub,
  postgresql,
}:
buildPgrxExtension rec {
  inherit postgresql;

  pname = "pgx_ulid";
  version = "0.2.0";

  src = fetchFromGitHub {
    owner = "pksunkara";
    repo = "pgx_ulid";
    tag = "v${version}";
    hash = "sha256-VdLWwkUA0sVs5Z/Lyf5oTRhcHVzPmhgnYQhIM8MWJ0c=";
  };

  cargoHash = "sha256-Gn+SjzGaxnGKJYI9+WyE1+TzlF/2Ne43aKbXrSzfQKM=";

  # Upstream renames the extension when packaging
  # https://github.com/pksunkara/pgx_ulid/blob/084778c3e2af08d16ec5ec3ef4e8f345ba0daa33/.github/workflows/release.yml#L81
  postInstall =
    let
      installDir = "$out/share/postgresql/extension";
    in
    ''
      mv ${installDir}/${pname}.control ${installDir}/ulid.control
      mv ${installDir}/${pname}--${version}.sql ${installDir}/ulid--${version}.sql
    '';

  # pgrx tests try to install the extension into nix store
  doCheck = false;
}
```

2025-01-03 03:02 UTC, pksunkara commented
> mv ${installDir}/${pname}--${version}.sql ${installDir}/ulid--${version}.sql

I think it should move all `${pname}--*.sql`. That is how postgres upgrades extensions. We currently don't have them because I have an open issue to add those. pksunkara/pgx_ulid#49

2025-01-04 08:43 UTC, myypo commented
@k0001 If you don't have time, I could pick up this package in a new PR as I am currently using it myself either way

2025-01-06 14:49 UTC, myypo commented
Superseded by #371463

2025-01-06 14:49 UTC, closed without merging