wldash: init at 0.3.0
NixOS/nixpkgs pull request #313098
Opened 2024-05-20 10:42 UTC by bbenno

## Description of changes

Add package `wldash`. Most of the package code has been taken from [`nixpkgs-wayland`](https://github.com/nix-community/nixpkgs-wayland/blob/master/pkgs/wldash/default.nix). Although the upstream repository did not receive much attention lately, the application remains pretty useful for my daily work.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-22 22:21 UTC, nicoonoclaste approved these changes

2024-05-23 05:07 UTC, bbenno commented on pkgs/by-name/wl/wldash/package.nix
> +    ];
Yeah, I thought of this as well. AFAIK, nothing specific to x86. However, I am uncertain about whether it builds and runs on other Linux platforms, such as ARM and PPC. Additionally, I question whether it is reasonable to proceed with this uncertainty and risk, including those platforms. Any suggestion?

2024-05-23 06:28 UTC, pluiedev requested changes

2024-05-23 06:28 UTC, pluiedev commented on pkgs/by-name/wl/wldash/package.nix
> +    ];
I think the general approach is to assume it works, unless it doesn't, or couldn't — such as, when the derivation uses pre-built binaries that are only built for some platform.

2024-05-23 07:37 UTC, pluiedev commented on pkgs/by-name/wl/wldash/package.nix
> +    ];
Assume it works unless it doesn't, or couldn't (e.g. missing deps or upstream binary releases don't target this platform)

2024-05-26 13:10 UTC, nicoonoclaste approved these changes

2024-05-26 13:10 UTC, merged