fjordlauncher: init at 8.3.1
NixOS/nixpkgs pull request #313011
Opened 2024-05-20 00:00 UTC by evan-goode

## Description of changes

[Fjord Launcher](https://github.com/unmojang/FjordLauncher) is a libre [Minecraft](https://minecraft.net) launcher and a fork of [Prism Launcher](https://github.com/PrismLauncher/PrismLauncher) that:

- Reduces dependence on non-free network services
- Adds support for alternative Minecraft API servers, such as [Ely.by](https://github.com/elyby)
- Adds back the ability to download FTB modpacks from within the launcher

This PR supersedes https://github.com/NixOS/nixpkgs/pull/270815, PollyMC was unmaintained so I forked it to Fjord Launcher.

Builds on macOS or aarch64 have not been tested, but this derivation is almost identical to Prism Launcher, which is already in nixpkgs. 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-20 03:13 UTC, getchoo requested changes
disclaimer: i am one of the maintainers for both `prismlauncher` in nixpkgs, and prism launcher itself

i think it's important to note a "feature" of this launcher that has been glossed over in the PR description, but mentioned in the README

> Offline mode doesn't require a Microsoft account

per [mojang's EULA](https://www.minecraft.net/en-us/eula):

> When you buy our games, that means you can download, install, and play them.  For the server version of Minecraft: Java Edition, you can install it on a server and host online play.
>
> However, you must not distribute anything we've made unless we specifically agree to it. By "distribute anything we've made" what we mean is:
>
> - give copies of our game software or content to anyone else;
> - make commercial use of anything we've made;
> - try to make money from anything we've made; or
> - **let other people get access to anything we've made in a way that is unfair or unreasonable.**
>
> And so that we are crystal clear, "the game" or "what we have made" includes, but is not limited to, the  Services, plus any other games we might publish in the future. It also includes updates, patches, downloadable or Marketplace content, add-ons, or modified versions of a game, part of those things, merchandise, audio-visual content, or anything else we've made.

i feel giving access to the game itself with no verification of ownership most definitely falls under letting others get access to it "in a way that is unfair or unreasonable." 

i'm sure you're aware of this as well, as in a [previous statement](https://github.com/PrismLauncher/PrismLauncher/pull/543#issuecomment-1363610459), you specifically said that the DRM lock of prism launcher (that verifies users have an account that owns the game) would help stay "solidly on the side of respecting this rule". this DRM lock is not present in this version of the launcher, and the only real blocker for someone intending to play the game without owning it is the following prompt

![image](https://github.com/NixOS/nixpkgs/assets/48872998/0ee3887d-04ca-4afd-9e84-256a9baf6fad)

IANAL, nor am i trying to endorse taking this project down or anything like that. however, the removal of DRM, admittance that this launcher allows you to easily break local laws, and the clear violation of mojang's EULA (which applies regardless of jurisdiction and is the responsibility of the launcher in this case) leads me to highly recommend against this being merged.

at best, this launcher (and distributing it on cache.nixos.org) is in a legal grey area. at worst, this launcher and it's inclusion would be enabler for those wishing to pirate minecraft. this could be quite a risk for nixpkgs that i don't think is worth the benefits; after all, you have inherited a [flake](https://github.com/unmojang/FjordLauncher/blob/2778fe760bfb1042511cffb481d90cc1ad06910f/flake.nix) from the fork that nix users can easily take advantage of

2024-05-20 03:54 UTC, evan-goode commented
Hey @getchoo, thanks for the respectful reply.

> 
> i think it's important to note a "feature" of this launcher that has been glossed over in the PR description, but mentioned in the README
> 
> > Offline mode doesn't require a Microsoft account
> 

Yes, I should have noted that clearly.

> at best, this launcher (and distributing it on cache.nixos.org) is in a legal grey area. at worst, this launcher and it's inclusion would be enabler for those wishing to pirate minecraft. this could be quite a risk for nixpkgs that i don't think is worth the benefits; after all, you have inherited a [flake](https://github.com/unmojang/FjordLauncher/blob/2778fe760bfb1042511cffb481d90cc1ad06910f/flake.nix) from the fork that nix users can easily take advantage of

Yeah, I have been on the fence myself about adding DRM back to Fjord Launcher. I forked Fjord Launcher from [PollyMC](https://github.com/fn2006/PollyMC) (since PollyMC has been unmaintained recently), and the PollyMC developer was the one who originally stripped out the DRM check.

My primary goal with Fjord Launcher, and the reason for the fork from Prism, is to support users who don't want to interact with network services that are proprietary and can't be controlled by the user, or to do so as little as possible (downloading the game necessitates interacting with Mojang's servers). The main thing I want to do is support alternative auth servers, but that initial authentication with Microsoft is not a big concern, we could add back the DRM check and it wouldn't matter much to me.

IANAL either, but in my view, PollyMC was in a similar legal gray area as youtube-dl. Could youtube-dl allow users to break YouTube's EULA and download copyrighted material against YouTube's terms? Yes, but publishing youtube-dl itself is (under current norms) not illegal, and many people agree that it serves a public good. Granted, Minecraft feels different since it's a "paid" product and YouTube videos are generally gratis.

I'm curious what other people have to say. If the DRM check prevents Fjord Launcher from being accepted into major repositories like nixpkgs or Flathub, I would rather just add back in the DRM.

2024-05-20 16:55 UTC, evan-goode commented
After talking with some other people in the community, I've decided to add back the Microsoft DRM check to Fjord Launcher, but it may take some time to get Fjord working with Microsoft accounts. I'm going to close this PR now, and re-open it again for a later version of Fjord once I've added back in the DRM. I'll ping you @getchoo on that new PR.

Thanks.

2024-05-20 16:55 UTC, closed without merging

2025-04-20 15:57 UTC, nyabinary commented
> After talking with some other people in the community, I've decided to add back the Microsoft DRM check to Fjord Launcher, but it may take some time to get Fjord working with Microsoft accounts. I'm going to close this PR now, and re-open it again for a later version of Fjord once I've added back in the DRM. I'll ping you @getchoo on that new PR.
> 
> Thanks.

The DRM checker is back in iirc