emacsPackages.emacs-conflict: init at 9f236b
NixOS/nixpkgs pull request #313309
Opened 2024-05-21 05:36 UTC by ibizaman

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-21 12:03 UTC, jian-lin requested changes

2024-05-21 12:03 UTC, jian-lin commented on pkgs/applications/editors/emacs/elisp-packages/manual-packages/emacs-conflict/default.nix
> +  buildInputs = [ emacs ];
Not needed.

```suggestion
```

2024-05-21 12:03 UTC, jian-lin commented on pkgs/applications/editors/emacs/elisp-packages/manual-packages/emacs-conflict/default.nix
> +    description = " Resolve conflicts happening when using file synchronization tools";
```suggestion
    description = "Resolve conflicts happening when using file synchronization tools";
```

2024-05-21 12:03 UTC, jian-lin commented on pkgs/applications/editors/emacs/elisp-packages/manual-packages/emacs-conflict/default.nix
> +trivialBuild {
`trivialBuild` is fine here because this package does not use autoloads.

2024-05-21 12:03 UTC, jian-lin commented on pkgs/applications/editors/emacs/elisp-packages/manual-packages/emacs-conflict/default.nix
> +  version = "9f236b93930f3ceb4cb0258cf935c99599191de3";
Could you change it according the doc here: https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-naming

2024-05-22 04:37 UTC, ibizaman commented
@jian-lin Thank you for the review. FYI I copy/pasted most of it from the sibling `youtube-dl/default.nix` file.

2024-05-22 13:25 UTC, jian-lin approved these changes
LGTM

> I copy/pasted most of it from the sibling youtube-dl/default.nix file

Some of those manual packages need improvement and the best practice of Nixpkgs, such as the version for unstable packages I comment above, also evolves.

2024-05-22 13:25 UTC, merged