Iterm2
NixOS/nixpkgs pull request #313708
Opened 2024-05-22 15:21 UTC by sikmir

## Description of changes
[Changelog](https://iterm2.com/downloads.html)

## Things done
- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://nixos.org/manual/nixpkgs/unstable/#sec-package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) (or backporting [23.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2305.section.md) and [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-22 16:56 UTC, zarthross requested changes
> - Using OpenAI's ChatGPT API, iTerm2 can now write
>   commands for you, interpret the output of
>   commands, and guide you towards a goal. See the
>   AI section below for details.

There is serious debate in the Issue boards for iterm2 to disable these features by default, and it seems that even if you provide an invalid API key, some details about the terminal input is making its way to OpenAI.... I recommend we don't merge this release into Nix.

https://gitlab.com/gnachman/iterm2/-/issues/11475

2024-05-24 23:10 UTC, LeSuisse commented
Includes the security fixes for the issues described in https://vin01.github.io/piptagole/escape-sequences/iterm2/hyper/url-handlers/code-execution/2024/05/21/arbitrary-url-schemes-terminal-emulators.html

2024-06-15 13:08 UTC, LeSuisse commented
An additional security issue has been fixed in 3.5.2, see https://www.openwall.com/lists/oss-security/2024/06/15/1

The OpenAI part has been moved into a dedicated plugin in 3.5.1.

@sikmir Can you please bump this PR to 3.5.2 so can move forward?

https://iterm2.com/downloads/stable/iTerm2-3_5_2.changelog

2024-06-20 20:51 UTC, LeSuisse approved these changes
Took the opportunity to test this while I had my aarch64 laptop booted on macOS.  Looks fine.


Flagging this to be backported since we cannot patch it.

2024-06-20 20:51 UTC, merged

2024-06-20 22:02 UTC, LeSuisse commented
CVE-2024-38395 & CVE-2024-38396 have been assigned to the security issues.

https://www.openwall.com/lists/oss-security/2024/06/17/1