mpdas: init at 0.4.4
NixOS/nixpkgs pull request #31398
Opened 2017-11-08 16:14 UTC by taketwo

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2017-11-08 16:38 UTC, yegortimoshenko commented
Builds :+1:

2017-11-08 16:45 UTC, lukateras requested changes
Builds! :+1: But `meta.maintainers` should be fixed.

2017-11-08 16:45 UTC, yegortimoshenko commented on pkgs/tools/audio/mpdas/default.nix
> +    maintainers = [ maintainers.taketwo ];
You need to add yourself to `lib/maintainers.nix` to do that:
https://github.com/NixOS/nixpkgs/blob/master/lib/maintainers.nix

2017-11-08 16:45 UTC, yegortimoshenko commented on pkgs/tools/audio/mpdas/default.nix
> +    rev = "${version}";
Nitpick: could be just `rev = version;`

2017-11-08 16:45 UTC, yegortimoshenko commented on pkgs/tools/audio/mpdas/default.nix
> +  makeFlags = "DESTDIR= PREFIX=$(out)";
Nitpick: lists are more easily overridable and semantically better:

```
makeFlags = [ "DESTDIR=" "PREFIX=$(out)" ];
```

2017-11-08 16:45 UTC, taketwo commented
I noticed that one of the Travis builds failed with:

```
error: attribute ‘taketwo’ missing, at /home/travis/build/NixOS/nixpkgs/pkgs/tools/audio/mpdas/default.nix:24:21
```

This is from the maintainer property in meta. Seems like I should add myself to [maintainers.nix](https://github.com/NixOS/nixpkgs/blob/master/lib/maintainers.nix), right? Should I make an extra commit or amend this one?

2017-11-08 16:50 UTC, yegortimoshenko commented
Changes are typically amended, but I'm not sure about the policy on `lib/maintainers.nix` specifically. See file history: https://github.com/NixOS/nixpkgs/commits/master/lib/maintainers.nix

2017-11-08 16:52 UTC, lukateras approved these changes

2017-11-08 16:53 UTC, taketwo commented
@yegortimoshenko Thanks for nitpicking :) Should be good to go now. From the history it seems like maintainer updates are usually combined with package updates, so I put it in the same commit.

2017-11-08 17:38 UTC, Mic92 commented
The program currently looks in $out/etc for configuration. `/etc` might be a better default.

```console
$ mpdas
(17:37:41) [INFO] Cannot parse config file (/nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4/etc/mpdasrc).
(17:37:41) [ERROR] AudioScrobbler username or password not set
$ strings $(which mpdas) | grep etc
/nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4/etc
```

2017-11-08 19:41 UTC, grahamc commented
@GrahamcOfBorg mpdas

2017-11-08 19:42 UTC, GrahamcOfBorg approved these changes
Success for system: x86_64-linux

```
install -m 644 mpdas.1 /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4/man/man1/mpdas.1
post-installation fixup
moving /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4/man to /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4/share/man
shrinking RPATHs of ELF executables and libraries in /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4
shrinking /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4/bin/mpdas
gzipping man pages under /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4/share/man/
stripping (with flags -S) in /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4/bin
patching script interpreter paths in /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4
checking for references to /tmp/nix-build-mpdas-0.4.4.drv-0 in /nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4...
/nix/store/xcfmrnnqfi50hiaymxixcfvivdfqnlkw-mpdas-0.4.4
```

2017-11-08 19:51 UTC, yegortimoshenko commented
Yeah, `/etc` is probably better as Nix store is read-only. There is a `CONFIG` variable for that:

```
makeFlags = [ "CONFIG=/etc" "DESTDIR=" "PREFIX=$(out)" ];
```

2017-11-08 21:28 UTC, merged

2017-11-08 21:31 UTC, taketwo commented
I was about to push a fix, but @Mic92 was faster! Thank you guys for quick responses and suggestions.

2017-11-08 21:40 UTC, taketwo commented
BTW, can you please clarify when this package will become installable with `nix-env -i mpdas`?

2017-11-08 21:48 UTC, Mic92 commented
On unstable with the next channel update: https://howoldis.herokuapp.com/

2017-11-08 21:48 UTC, Mic92 commented
Can be also monitored here: https://hydra.nixos.org/jobset/nixpkgs/trunk/evals

2017-11-08 22:27 UTC, taketwo commented
Thanks for the pointers. If I understood correctly, no particular schedule, maybe tomorrow, maybe in a week, as soon as certain important failing packages turn green.

2017-11-09 10:47 UTC, Mic92 commented
@taketwo hydra has build it already, but the complete evaluation is not finished yet: https://hydra.nixos.org/eval/1408888?filter=mpdas&compare=1408845&full=