lib/eval-config: document NIXOS_EXTRA_MODULE_PATH
NixOS/nixpkgs pull request #31418
Opened 2017-11-09 06:01 UTC by ryantm

This adds some documentation about importing modules external to
Nixpkgs, which provides context for documenting
NIXOS_EXTRA_MODULE_PATH.

Closes #30376

###### Motivation for this change

NIXOS_EXTRA_MODULE_PATH was undocumented.

###### Things done

Built manual and proofread the new section.

2017-11-12 21:32 UTC, FRidh requested changes
Thanks for the PR. I think the text needs to be more neutral.

2017-11-12 21:32 UTC, FRidh commented on nixos/doc/manual/development/importing-modules.xml
> +<para>Sometimes NixOS modules exist outside of Nixpkgs, and you want
Avoid using "you".
> Modules that exist outside of Nixpkgs can be imported in a NixOS configuration.

2017-11-12 21:32 UTC, FRidh commented on nixos/doc/manual/development/importing-modules.xml
> +The simplest way to do this is to import the module:
> The module can be imported as follows:

2017-11-12 21:32 UTC, FRidh commented on nixos/doc/manual/development/importing-modules.xml
> +If the list of modules you need to import grows large, you can move
Whether the list grows large or not is irrelevant; it's always possible to keep it outside. I would drop this example as it doesn't add anything.

2017-11-12 21:32 UTC, FRidh commented on nixos/doc/manual/development/importing-modules.xml
> +example, you could do:
Drop
> Using the same module list as the previous example, you could do:

2017-11-13 05:17 UTC, ryantm commented
@FRidh Thanks for the feedback. I think I've incorporated all of your review suggestions. Please take another look. I will squash the commits together when the reviewers are satisfied.

2017-11-19 22:09 UTC, ryantm commented
@FRidh Are you okay with it now?

2018-01-21 16:59 UTC, ryantm commented
@FRidh bump

2018-02-19 21:06 UTC, ryantm commented
bump

2018-02-20 15:27 UTC, ryantm commented
Since I haven't received any feedback in a while, I went ahead and squashed the commits.

2018-04-02 04:54 UTC, ryantm commented
@FRidh nudge

2018-04-28 01:26 UTC, merged

2018-04-28 01:30 UTC, grahamc commented
merged and backported while boarding a plane. thanks!