commitlint-rs: init at 0.1.11
NixOS/nixpkgs pull request #314696
Opened 2024-05-25 22:27 UTC by croissong

## Description of changes

[commitlint-rs](https://github.com/KeisukeYamashita/commitlint-rs) is a command-line tool to lint commit messages with conventional commit messages.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-30 07:44 UTC, getchoo requested changes

2024-05-30 07:44 UTC, getchoo commented on pkgs/by-name/co/commitlint-rs/package.nix
> +  cargoSha256 = "sha256-W6HkLCUoylgQQc2fFprmJeLH8KtpVUD4+BXWbNECVZ4=";
```suggestion

  cargoHash = "sha256-W6HkLCUoylgQQc2fFprmJeLH8KtpVUD4+BXWbNECVZ4=";
```

2024-05-30 07:44 UTC, getchoo commented on pkgs/by-name/co/commitlint-rs/package.nix
> +    sha256 = "sha256-FrYXEh75H0u1rE1YNDL/B1gMYMG43jPDJGUMv9y5/3g=";
```suggestion
    hash = "sha256-FrYXEh75H0u1rE1YNDL/B1gMYMG43jPDJGUMv9y5/3g=";
```

2024-05-30 07:44 UTC, getchoo commented on pkgs/by-name/co/commitlint-rs/package.nix
> +  passthru.updateScript = nix-update-script {};
```suggestion
  passthru = {
    updateScript = nix-update-script { };
    tests.version = testers.testVersion {
      package = commitlint-rs;
    };
  };
```
it's good to have a test here

2024-05-30 07:44 UTC, getchoo commented on pkgs/by-name/co/commitlint-rs/package.nix
> +    changelog = "https://github.com/KeisukeYamashita/commitlint-rs/releases/tag/v${version}";
```suggestion
    changelog = "https://github.com/KeisukeYamashita/commitlint-rs/releases/tag/${src.rev}";
```

2024-05-30 07:44 UTC, getchoo commented on pkgs/by-name/co/commitlint-rs/package.nix
> +    license = with licenses; [mit asl20];
```suggestion
    license = with licenses; [ mit asl20 ];
```

2024-05-30 07:44 UTC, getchoo commented on pkgs/by-name/co/commitlint-rs/package.nix
> +    maintainers = [maintainers.croissong];
```suggestion
    maintainers = with maintainers; [ croissong getchoo ];
```
i'd love to help out here :)

2024-05-30 07:44 UTC, getchoo commented on pkgs/by-name/co/commitlint-rs/package.nix
> +    repo = pname;
```suggestion
    repo = "commitlint-rs;
```
https://github.com/NixOS/nixpkgs/issues/277994

2024-05-30 18:58 UTC, croissong commented on pkgs/by-name/co/commitlint-rs/package.nix
> +    maintainers = [maintainers.croissong];
gladly :)

2024-05-30 19:00 UTC, croissong commented
@getchoo thanks so much for your review!

2024-06-13 11:32 UTC, croissong commented
@getchoo Do you maybe have any experience or recommendations on how to keep this PR (and other PRs in general) from getting "forgotten"?

Is it ok to bump it via commented every once in a while, or is there anything else I can do from my side (labels, etc)?

2024-06-13 22:57 UTC, h7x4 commented on pkgs/by-name/co/commitlint-rs/package.nix
> +    platforms = platforms.linux;
```suggestion
    platforms = with platforms; unix ++ windows;
```

2024-06-13 23:10 UTC, h7x4 commented
> [...] how to keep this PR (and other PRs in general) from getting "forgotten"?

I think this is a very common problem in nixpkgs. There's a ton of inactionable PRs flooding the list, making it hard to find ones that are ready.

You could always post the PR in the nixpkgs review requests channel on matrix, the "PRs ready for review/merge" threads on discourse, just add random committers and people you think might be interested as reviewers, or ask people. Many maintainers and committers especially, are completely okay with and used to being added as reviewer on random PRs. Sometimes, people will tell you they're not available at the moment by removing their review request.

2024-06-13 23:27 UTC, getchoo commented
> You could always post the PR in the nixpkgs review requests channel on matrix, the "PRs ready for review/merge" threads on discourse, just add random committers and people you think might be interested as reviewers, or ask people. Many maintainers and committers especially, are completely okay with and used to being added as reviewer on random PRs. Sometimes, people will tell you they're not available at the moment by removing their review request.

+1, these were my thoughts exactly. don't ever be afraid to reach out and let people know it's been a while :)

2024-06-14 15:25 UTC, h7x4 approved these changes
Built and tested basic functionality. Cool stuff :+1:

2024-06-14 15:25 UTC, merged