dopamine: init at 3.0.0-preview.26
NixOS/nixpkgs pull request #315465
Opened 2024-05-28 23:53 UTC by Guanran928

## Description of changes

The audio player that keeps it simple 
https://github.com/digimezzo/dopamine

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-05-29 00:44 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/3999

2024-05-29 01:43 UTC, lelgenio commented
Working fine

---

Result of `nixpkgs-review pr 315465` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dopamine</li>
  </ul>
</details>

2024-05-29 01:50 UTC, lelgenio commented on pkgs/by-name/do/dopamine/package.nix
> +    platforms = lib.platforms.all;
```suggestion
    platforms = [ "x86_64-linux" ];
```

The Appimage only works in `x86_64-linux`, right?

2024-06-02 15:14 UTC, SuperSandro2000 requested changes, later dismissed

2024-06-02 15:14 UTC, SuperSandro2000 commented on pkgs/by-name/do/dopamine/package.nix
> +    url = "https://github.com/digimezzo/dopamine/releases/download/v3.0.0-preview.25/Dopamine-3.0.0-preview.25.AppImage";
```suggestion
    url = "https://github.com/digimezzo/dopamine/releases/download/v${version}/Dopamine-${version}.AppImage";
```

2024-06-02 15:14 UTC, SuperSandro2000 commented on pkgs/by-name/do/dopamine/package.nix
> +        --replace 'Exec=AppRun' 'Exec=${meta.mainProgram}'
```suggestion
        --replace-fail 'Exec=AppRun' 'Exec=dopamine'
```

2024-07-04 18:56 UTC, pinpox commented
Result of `nixpkgs-review pr 315465` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>dopamine</li>
  </ul>
</details>

2024-07-04 18:56 UTC, pinpox approved these changes

2024-07-05 05:06 UTC, merged