stdenv: Allow user to supply their bootstrapFiles set of tools
NixOS/nixpkgs pull request #317119
Opened 2024-06-04 06:32 UTC by wh0

## Description of changes

This adds a config option `replaceBootstrapFiles`. It's a function that takes the normal bootstrap files and returns your custom bootstrap files.

Example nixpkgs/config.nix:

```nix
{
  replaceBootstrapFiles = prevFiles:
    let replacements = {
      "sha256-YQlr088HPoVWBU2jpPhpIMyOyoEDZYDw1y60SGGbUM0=" = import <nix/fetchurl.nix> {
        url = "(custom glibc linux x86_64 bootstrap-tools.tar.xz)";
        hash = "(...)";
      };
      "sha256-QrTEnQTBM1Y/qV9odq8irZkQSD9uOMbs2Q5NgCvKCNQ=" = import <nix/fetchurl.nix> {
        url = "(custom glibc linux x86_64 busybox)";
        hash = "(...)";
      };
    };
    in builtins.mapAttrs (name: prev: replacements.${prev.outputHash} or prev) prevFiles;
}
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-06-04 06:34 UTC, wh0 commented
- would something like this be ok?
- would this be ok to backport into nixos 24.05?

and if so, I can try applying similar changes to the darwin stdenv and adding some docs

2024-06-04 06:37 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/overlay-for-bootstrap-files/46417/3

2024-06-05 04:25 UTC, wh0 commented
applied to the darwin stdenv too

2024-08-29 12:51 UTC, philiptaron requested changes
The two changes to the stdenv look correct for an undeclared `config` option.

Could you please add the appropriate changes to `pkgs/top-level/config.nix` so that it's documented?

2024-08-30 00:44 UTC, wh0 commented
ya let me take a look

2024-08-30 02:32 UTC, wh0 commented
alright added

2024-08-30 03:07 UTC, philiptaron commented
> alright added

Would you mind re-verifying that the scenario works now that the option is added?

2024-08-30 03:55 UTC, wh0 commented
I don't have nixos, I've been using a ~/.config/nixpkgs/nix.conf file. didn't even know there was this option declaration

2024-08-30 04:02 UTC, wh0 commented
confirming that it works from non-nixos with ~/.config/nixpkgs/config.nix though

2024-09-04 18:34 UTC, philiptaron approved these changes

2024-09-04 18:34 UTC, merged

2024-09-05 01:50 UTC, wh0 commented
thanks! 

can I get the backport release-24.05 label on this?

2024-09-05 02:54 UTC, philiptaron commented
I don't know whose call that is; I'm a little leery of it, personally.

2024-09-05 03:43 UTC, wh0 commented
the label runs a GitHub action to create the backport automatically, and it's another PR that the stable maintainers review.