php: tidySupport option
NixOS/nixpkgs pull request #31849
Opened 2017-11-20 06:38 UTC by elitak

###### Motivation for this change

I had something that needed the libtidy bindings in php, so I added this.

###### Things done

 I only tested this in a very basic way: build and check phpinfo()

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-11-20 08:31 UTC, fpletz commented
@GrahamcOfBorg build php

2017-11-20 08:38 UTC, GrahamcOfBorg reviewed
Success for system: x86_64-darwin

```
/nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/bin/peardev: interpreter directive changed from "/bin/sh" to "/nix/store/hh833qm6lgb6cgr7z9vxkb72wikr4wwz-bash-4.4-p12/bin/sh"
/nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/bin/pecl: interpreter directive changed from "/bin/sh" to "/nix/store/hh833qm6lgb6cgr7z9vxkb72wikr4wwz-bash-4.4-p12/bin/sh"
/nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/bin/php-config: interpreter directive changed from " /bin/sh" to "/nix/store/hh833qm6lgb6cgr7z9vxkb72wikr4wwz-bash-4.4-p12/bin/sh"
/nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/bin/phpize: interpreter directive changed from "/bin/sh" to "/nix/store/hh833qm6lgb6cgr7z9vxkb72wikr4wwz-bash-4.4-p12/bin/sh"
/nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/lib/build/config.guess: interpreter directive changed from " /bin/sh" to "/nix/store/hh833qm6lgb6cgr7z9vxkb72wikr4wwz-bash-4.4-p12/bin/sh"
/nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/lib/build/config.sub: interpreter directive changed from " /bin/sh" to "/nix/store/hh833qm6lgb6cgr7z9vxkb72wikr4wwz-bash-4.4-p12/bin/sh"
/nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/lib/build/shtool: interpreter directive changed from "/bin/sh" to "/nix/store/hh833qm6lgb6cgr7z9vxkb72wikr4wwz-bash-4.4-p12/bin/sh"
moving /nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/sbin/* to /nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11/bin
patching script interpreter paths in /nix/store/70bjq2a33knd3vp25ng415wzwy81cmsq-php-7.1.11-dev
/nix/store/vlyg8qls440lkxyxiiqdvwyxdnxayixn-php-7.1.11
```

2017-11-20 12:29 UTC, GrahamcOfBorg reviewed
Success for system: x86_64-linux

```
/nix/store/dqlakxs7ff29cvrxrnmhmv8ln9b28hly-php-7.1.11/bin/peardev: interpreter directive changed from "/bin/sh" to "/nix/store/4ada72n7785wwazv42fhsnxjvilaa3aj-bash-4.4-p12/bin/sh"
/nix/store/dqlakxs7ff29cvrxrnmhmv8ln9b28hly-php-7.1.11/lib/build/config.sub: interpreter directive changed from " /bin/sh" to "/nix/store/4ada72n7785wwazv42fhsnxjvilaa3aj-bash-4.4-p12/bin/sh"
/nix/store/dqlakxs7ff29cvrxrnmhmv8ln9b28hly-php-7.1.11/lib/build/config.guess: interpreter directive changed from " /bin/sh" to "/nix/store/4ada72n7785wwazv42fhsnxjvilaa3aj-bash-4.4-p12/bin/sh"
/nix/store/dqlakxs7ff29cvrxrnmhmv8ln9b28hly-php-7.1.11/lib/build/shtool: interpreter directive changed from "/bin/sh" to "/nix/store/4ada72n7785wwazv42fhsnxjvilaa3aj-bash-4.4-p12/bin/sh"
checking for references to /tmp/nix-build-php-7.1.11.drv-0 in /nix/store/dqlakxs7ff29cvrxrnmhmv8ln9b28hly-php-7.1.11...
moving /nix/store/dqlakxs7ff29cvrxrnmhmv8ln9b28hly-php-7.1.11/sbin/* to /nix/store/dqlakxs7ff29cvrxrnmhmv8ln9b28hly-php-7.1.11/bin
shrinking RPATHs of ELF executables and libraries in /nix/store/m0ar953fffyz9knbr48fckdhbdmq6dsp-php-7.1.11-dev
patching script interpreter paths in /nix/store/m0ar953fffyz9knbr48fckdhbdmq6dsp-php-7.1.11-dev
checking for references to /tmp/nix-build-php-7.1.11.drv-0 in /nix/store/m0ar953fffyz9knbr48fckdhbdmq6dsp-php-7.1.11-dev...
/nix/store/dqlakxs7ff29cvrxrnmhmv8ln9b28hly-php-7.1.11
```

2018-04-21 19:38 UTC, matthewbauer requested changes
fix merge conflicts

2018-07-23 15:31 UTC, matthewbauer commented
@grahamcorborg build php

2018-07-23 15:42 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.31849&attempt_id=9a16448b-6915-431a-a2cc-036e6fa5c6a6)

Attempted: php

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/93yxka58l369rw2h1fik7ybk2dg4dqva-php-7.2.7/lib/build/config.guess: interpreter directive changed from " /bin/sh" to "/nix/store/8i8hqj3hg3axirbp7f990s1x50mnmq73-bash-4.4-p23/bin/sh"
/nix/store/93yxka58l369rw2h1fik7ybk2dg4dqva-php-7.2.7/lib/build/shtool: interpreter directive changed from "/bin/sh" to "/nix/store/8i8hqj3hg3axirbp7f990s1x50mnmq73-bash-4.4-p23/bin/sh"
/nix/store/93yxka58l369rw2h1fik7ybk2dg4dqva-php-7.2.7/lib/build/config.sub: interpreter directive changed from " /bin/sh" to "/nix/store/8i8hqj3hg3axirbp7f990s1x50mnmq73-bash-4.4-p23/bin/sh"
checking for references to /build in /nix/store/93yxka58l369rw2h1fik7ybk2dg4dqva-php-7.2.7...
moving /nix/store/93yxka58l369rw2h1fik7ybk2dg4dqva-php-7.2.7/sbin/* to /nix/store/93yxka58l369rw2h1fik7ybk2dg4dqva-php-7.2.7/bin
shrinking RPATHs of ELF executables and libraries in /nix/store/dbglkjbwnxvfji6zp5f1d73qp71jiw9v-php-7.2.7-dev
strip is /nix/store/fzsyclvxz1p2ia83caniy93v8cwarg0j-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/dbglkjbwnxvfji6zp5f1d73qp71jiw9v-php-7.2.7-dev
checking for references to /build in /nix/store/dbglkjbwnxvfji6zp5f1d73qp71jiw9v-php-7.2.7-dev...
/nix/store/93yxka58l369rw2h1fik7ybk2dg4dqva-php-7.2.7
```
</p></details>

2018-07-23 15:44 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.31849&attempt_id=1ce5f8b2-09e5-4453-9237-d53003a9f741)

Attempted: php

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/2ixijnda7dyr7dkdk432z3mclywsnjs5-php-7.2.7/bin/pear: interpreter directive changed from "/bin/sh" to "/nix/store/xlv8nwq2cbxm2yancb3yk3424ziyb91q-bash-4.4-p23/bin/sh"
/nix/store/2ixijnda7dyr7dkdk432z3mclywsnjs5-php-7.2.7/bin/php-config: interpreter directive changed from " /bin/sh" to "/nix/store/xlv8nwq2cbxm2yancb3yk3424ziyb91q-bash-4.4-p23/bin/sh"
/nix/store/2ixijnda7dyr7dkdk432z3mclywsnjs5-php-7.2.7/bin/phpize: interpreter directive changed from "/bin/sh" to "/nix/store/xlv8nwq2cbxm2yancb3yk3424ziyb91q-bash-4.4-p23/bin/sh"
checking for references to /build in /nix/store/2ixijnda7dyr7dkdk432z3mclywsnjs5-php-7.2.7...
moving /nix/store/2ixijnda7dyr7dkdk432z3mclywsnjs5-php-7.2.7/sbin/* to /nix/store/2ixijnda7dyr7dkdk432z3mclywsnjs5-php-7.2.7/bin
shrinking RPATHs of ELF executables and libraries in /nix/store/nis9vb9qj1ygrs9ibf0fll16qk6bna7g-php-7.2.7-dev
strip is /nix/store/h0nc84ybvb8g724fwysvcghh1675wjli-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/nis9vb9qj1ygrs9ibf0fll16qk6bna7g-php-7.2.7-dev
checking for references to /build in /nix/store/nis9vb9qj1ygrs9ibf0fll16qk6bna7g-php-7.2.7-dev...
/nix/store/2ixijnda7dyr7dkdk432z3mclywsnjs5-php-7.2.7
```
</p></details>

2018-07-23 16:02 UTC, GrahamcOfBorg commented
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.31849&attempt_id=68849f99-6baa-46ec-ae48-fa161a28a2ec)

Attempted: php

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7/bin/pecl: interpreter directive changed from "/bin/sh" to "/nix/store/6mhkwk1yvbrncacxk2zasvn4jzivpf3c-bash-4.4-p23/bin/sh"
/nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7/bin/php-config: interpreter directive changed from " /bin/sh" to "/nix/store/6mhkwk1yvbrncacxk2zasvn4jzivpf3c-bash-4.4-p23/bin/sh"
/nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7/bin/phpize: interpreter directive changed from "/bin/sh" to "/nix/store/6mhkwk1yvbrncacxk2zasvn4jzivpf3c-bash-4.4-p23/bin/sh"
/nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7/lib/build/config.guess: interpreter directive changed from " /bin/sh" to "/nix/store/6mhkwk1yvbrncacxk2zasvn4jzivpf3c-bash-4.4-p23/bin/sh"
/nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7/lib/build/config.sub: interpreter directive changed from " /bin/sh" to "/nix/store/6mhkwk1yvbrncacxk2zasvn4jzivpf3c-bash-4.4-p23/bin/sh"
/nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7/lib/build/shtool: interpreter directive changed from "/bin/sh" to "/nix/store/6mhkwk1yvbrncacxk2zasvn4jzivpf3c-bash-4.4-p23/bin/sh"
moving /nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7/sbin/* to /nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7/bin
strip is /nix/store/qvj6bdvy7vdaxi3my0nq8ghf14njh8wk-cctools-binutils-darwin/bin/strip
patching script interpreter paths in /nix/store/wgys792d3ha1njw4vkfysrwrbyn2l3d1-php-7.2.7-dev
/nix/store/lw6jm5gg1rqpw70fwfkhcqxm3gncx3lv-php-7.2.7
```
</p></details>

2018-07-23 16:25 UTC, merged