vndr: migrate to buildGoModule
NixOS/nixpkgs pull request #318798
Opened 2024-06-10 13:32 UTC by msanft

## Description of changes

Migrating to `buildGoModule` so `buildGoPackage` can be deprecated as per https://github.com/NixOS/nixpkgs/issues/318069. Project needs an upstream patch to do so, as it does not have a vendor directory, nor is a module.

Also moved to `by-name`.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-06-11 12:57 UTC, msanft commented
@vdemeester I think this might should've gone to https://github.com/NixOS/nixpkgs/pull/318922

2024-06-11 13:20 UTC, vdemeester commented
> @vdemeester I think this should've gone to #318922

Indeed.. wrong tab.. 🤦🏼

2024-06-13 17:31 UTC, katexochen requested changes

2024-06-13 17:31 UTC, katexochen commented on pkgs/by-name/vn/vndr/package.nix
> +
```suggestion
```

2024-06-13 17:31 UTC, katexochen commented on pkgs/by-name/vn/vndr/package.nix
> +
```suggestion

  postPatch = ''
    go mod init github.com/LK4D4/vndr
  '';
```
Patch isn't really needed, we can just init the module postPatch.

2024-06-22 12:45 UTC, katexochen approved these changes

2024-06-22 12:45 UTC, merged