minio-exporter: remove
NixOS/nixpkgs pull request #318841
Opened 2024-06-10 15:58 UTC by msanft

## Description of changes

Please review this carefully, it is my first module deprecation.

Remove the minio-exporter module, as Minio has built-in Prometheus metrics for a while: https://min.io/docs/minio/linux/operations/monitoring/collect-minio-metrics-using-prometheus.html.

The minio-exporter package doesn't use Go modules, and can't be ported without rewriting of a lot of the source, as it has very outdated dependencies.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-06-10 19:11 UTC, SuperSandro2000 commented on pkgs/top-level/aliases.nix
> +  libranixfmt = lib.warn "nixfmt was renamed to nixfmt-classic. The nixfmt attribute may be used for the new RFC 166-style formatter in the future, which is currently available as nixfmt-rfc-style" n
That seems unintended

2024-06-10 19:11 UTC, SuperSandro2000 commented on pkgs/top-level/aliases.nix
> +    mozart = throw "'mozart' has been renamed to/replaced by 'mozart2-binary'"; # Converted to throw 2023-09-10
this, too

2024-06-10 19:11 UTC, SuperSandro2000 commented on nixos/modules/services/monitoring/prometheus/exporters.nix
> +      '' ))
Lets drop those very old mkRemovedOptionModule

2024-06-11 20:15 UTC, bachp approved these changes
For me this looks OK.

2024-06-24 20:52 UTC, katexochen requested changes, later dismissed

2024-06-24 20:52 UTC, katexochen commented on nixos/modules/services/monitoring/prometheus/exporters.nix
minio is still in the list of exporterOpts, remove L55.

2024-06-25 08:45 UTC, SuperSandro2000 commented on nixos/doc/manual/release-notes/rl-2411.section.md
> +  Minio now has built-in [Prometheus metrics exposure](https://min.io/docs/minio/linux/operations/monitoring/collect-minio-metrics-using-prometheus.html), which can be used instead.
I don't think that's worth the effort.

2024-06-25 08:45 UTC, SuperSandro2000 approved these changes

2024-06-25 09:03 UTC, SuperSandro2000 approved these changes

2024-06-25 10:51 UTC, merged