hunspell: adopt; modernize; add tests
NixOS/nixpkgs pull request #319218
Opened 2024-06-12 04:42 UTC by getchoo

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-06-12 07:16 UTC, getchoo commented
rebase onto staging due to the number of rebuilds this triggers

2024-11-16 01:38 UTC, getchoo commented
Was able to build this for all tier 1 platforms against master

2025-03-08 08:24 UTC, uninsane commented
@getchoo if you still have interest in being maintainer of hunspell, i'd be happy to review this & get it over the line. looks like it just needs a rebase: tag me if/when you have the time to fix the merge conflicts & i'll give it a closer look.

2025-03-08 13:09 UTC, getchoo commented
Thanks @uninsane! I've rebased :)

2025-03-08 22:14 UTC, uninsane requested changes
LGTM except for `hunspellWithDicts`

2025-03-08 22:14 UTC, uninsane commented on pkgs/by-name/hu/hunspell/wrapper.nix
> +    wrapProgram $out/bin/hunspell --prefix DICPATH : ${lib.escapeShellArg searchPath}
i think this change is wrong. e.g. this command is buildable on master, but not on this PR branch:
```
echo ':l\n :b hunspellWithDicts [ hunspellDicts.en_US ]' | nix repl
```

2025-03-15 16:39 UTC, getchoo commented on pkgs/by-name/hu/hunspell/wrapper.nix
> +    wrapProgram $out/bin/hunspell --prefix DICPATH : ${lib.escapeShellArg searchPath}
Should be fixed

2025-03-15 16:42 UTC, getchoo commented on pkgs/by-name/hu/hunspell/wrapper.nix
> +    wrapProgram $out/bin/hunspell --prefix DICPATH : ${lib.escapeShellArg searchPath}
I also added a test for the wrapper in the main package to catch anything like this in the future

2025-03-15 22:43 UTC, uninsane approved these changes

2025-03-15 22:52 UTC, merged