nixos/restic: ensure newline in --files-from
NixOS/nixpkgs pull request #319807
Opened 2024-06-14 12:01 UTC by hellodword

## Description of changes

Add a newline after the result of `concatStringsSep "\n" backup.paths` to prevent it from being incorrectly concatenated with the output of the subsequent command
```nix
:b pkgs.writeScript "hello" ''
    filesFromTmpFile="$(mktemp)"
    cat ${pkgs.writeText "staticPaths" (lib.concatStringsSep "\n" ["/path/to/file1" "/path/to/file2"])} >> "$filesFromTmpFile"
    ${pkgs.writeScript "dynamicFilesFromScript" "echo /path/to/file3"} >> "$filesFromTmpFile"
    cat "$filesFromTmpFile"
''
```
The result is:

```
/path/to/file1
/path/to/file2/path/to/file3
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [x] [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-06-22 09:23 UTC, robryk commented
Please amend the test in nixos/tests/restic.nix so that it checks that the backup produced by `remote-from-file-backup` has correct contents: we actually have a test that exercises `paths` and `dynamicFilesFrom` at the same time, but that one didn't check backup's contents.

Other than that, this change seems fine.

2024-06-23 17:15 UTC, robryk commented on nixos/tests/restic.nix
> +          'restic-remote-from-file-backup snapshots --json | ${pkgs.jq}/bin/jq -r ".[0].paths[]" | grep "/opt/a_dir/a_file_2"',
Why not replicate the `diff` invocation as seen in line 139?

2024-07-27 07:34 UTC, robryk approved these changes

2024-07-31 19:21 UTC, emilylange requested changes

2024-07-31 19:21 UTC, emilylange commented on nixos/modules/services/backup/restic.nix
> +                cat ${pkgs.writeText "staticPaths" ((concatStringsSep "\n" backup.paths) + "\n")} >> ${filesFromTmpFile}
`lib.concatLines` does what we need out of the box:

https://github.com/NixOS/nixpkgs/blob/c68bae316281af1b80a1d12c6f56d2b92b6f2d3a/lib/strings.nix#L272-L298

```suggestion
                cat ${pkgs.writeText "staticPaths" (concatLines backup.paths)} >> ${filesFromTmpFile}
```

2024-08-01 10:31 UTC, emilylange commented
@ofborg test restic

2024-08-01 13:50 UTC, emilylange approved these changes

2024-08-02 16:18 UTC, merged