cjdns: update version (fixes pkg on aarch64)
NixOS/nixpkgs pull request #322643
Opened 2024-06-26 13:48 UTC by virtu

## Description of changes

A while back this package was marked as broken on aarch64 because of compilation errors. Some looking into revealed that some non-portable code was to blame: some minor parts of cjdns relied on char pointers being equivalent to signed integer pointers (which is the default on x86). I proposed a [PR](https://github.com/cjdelisle/cjdns/pull/1264) to fix the issue, which got merged today.

This PR updates the cjdns package to latest master, thereby making the package usable on aarch64 again.

## Things done

- Built on platform(s)
  - x86_64-linux
  - aarch64-linux
- Tested functionality on platform(s)
  - x86_64-linux
  - aarch64-linux

2024-07-23 10:18 UTC, dotlambda requested changes
Please update to version 22 and make sure your commit message follows the guidelines in https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions.

2024-07-25 08:39 UTC, virtu commented
> Please update to version 22 and make sure your commit message follows the guidelines in https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions.

Will adjust the commit message. Can you explain what you mean by "update to version 22"? Should I use the 22 release instead of git master?

2024-07-25 11:40 UTC, dotlambda commented
> > Please update to version 22 and make sure your commit message follows the guidelines in https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#commit-conventions.
> 
> Will adjust the commit message. Can you explain what you mean by "update to version 22"? Should I use the 22 release instead of git master?

Oops, I didn't see that you're using an unstable version.
Is there a reason? Using an official version is preferred if possible.

2025-01-25 18:58 UTC, SuperSandro2000 commented
Closing as stale

2025-01-25 18:58 UTC, closed without merging