metadata: init at 0.1.9
NixOS/nixpkgs pull request #322773
Opened 2024-06-26 23:29 UTC by myclevorname

## Description of changes

Info about `metadata` can be found at #322243.

Hopefully, `metadata` should build, but requires libavutil, whose request is #322243.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-06-26 23:45 UTC, pinpox commented on pkgs/by-name/me/metadata/package.nix
> +  BuildInputs = [ ffmpeg libavutil ];
```suggestion
  buildInputs = [ ffmpeg libavutil ];
```
`buidInputs` is lowercase. Also unnessary explanation, maintainers should know what this does.

2024-06-26 23:46 UTC, pinpox commented on pkgs/by-name/me/metadata/package.nix
> +  # Build-time
```suggestion
```

2024-06-26 23:55 UTC, pinpox requested changes

2024-06-26 23:55 UTC, pinpox commented on pkgs/by-name/me/metadata/package.nix
> +{ stdenv, lib, fetchFromGitHub, pkg-config, ffmpeg, rustPlatform, asciidoc, libavutil }:
`libavutil` does not exist here.

2024-06-27 00:16 UTC, pinpox commented
I tried playing around with this, this package should work:

```nix
{ clang
, libclang
, stdenv
, lib
, fetchFromGitHub
, pkg-config
, ffmpeg
, rustPlatform
, asciidoc
, glib
, llvmPackages
}:
rustPlatform.buildRustPackage rec {
  pname = "metadata";
  version = "0.1.9";

  src = fetchFromGitHub {
    owner = "zmwangx";
    repo = pname;
    rev = "v${version}";
    hash = "sha256-OFWdCV9Msy/mNaSubqoJi4tBiFqL7RuWWQluSnKe4fU=";
  };

  cargoHash = "sha256-F5jXS/W600nbQtu1FD4+DawrFsO+5lJjvAvTiFKT840=";

  nativeBuildInputs = [
    pkg-config
    asciidoc
    clang
    libclang.lib
    llvmPackages.libcxxClang
    clang
  ];

  postBuildHook = "a2x --doctype manpage --format manpage man/metadata.1.adoc";
  postInstallHook = ''
    mkdir -p $out/share/man
    cp man/metadata.1 $out/share/man/
  '';

  buildInputs = [
    ffmpeg
    clang
    glib
    llvmPackages.libclang
    stdenv.cc.libc
  ];

  env.LIBCLANG_PATH = "${libclang.lib}/lib";
  env.FFMPEG_DIR = ffmpeg.dev;

  meta = {
    description = "Media file metadata for human consumption";
    longDescription = ''
      metadata is a media metadata parser and formatter designed for human consumption.
      Powered by FFmpeg.
    '';
    maintainers = with lib.maintainers; [ clevor ];
    license = lib.licenses.mit;
    homepage = "https://github.com/zmwangx/metadata";
    platforms = lib.platforms.linux;
    mainProgram = "metadata";
  };
}
```

Compilation will still fail though, because of this issue which has to be fixed upstream: https://github.com/zmwangx/metadata/issues/9

2024-06-28 09:29 UTC, pinpox commented
Result of `nixpkgs-review pr 322773` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>metadata</li>
  </ul>
</details>

2024-06-28 09:29 UTC, pinpox approved these changes

2024-06-28 11:18 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    cp man/metadata.1 $out/share/man/
Please use `installManpage`: `installManpage man/metadata.1`. No need to mkdir.

2024-06-28 11:18 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    stdenv.cc.libc
```suggestion
```

2024-06-28 11:18 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    clang
Please try adding `rustPlatform.bindgenHook` and removing all "clang" stuff.

2024-06-28 11:18 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    description = "Media file metadata for human consumption";
```suggestion
    description = "Media metadata parser and formatter designed for human consumption, powered by FFmpeg";
```

No need to add `longDescription`.

2024-06-28 11:18 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    platforms = lib.platforms.linux;
```suggestion
```

`rustPlatform` comes with a platform by default. Seems this is also available on macOS.

2024-06-28 11:18 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    repo = pname;
```suggestion
    repo = "metadata";
```

2024-06-28 11:28 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    cp man/metadata.1 $out/share/man/
It's in `installShellFiles`. Add this to `nativeBuildInputs` first.

2024-06-28 17:58 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +  postInstallHook = ''
```suggestion
  postInstall = ''
```

2024-06-28 17:58 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +  postBuildHook = "a2x --doctype manpage --format manpage man/metadata.1.adoc";
```suggestion
  postBuild = ''
    a2x --doctype manpage --format manpage man/metadata.1.adoc
  '';

```

2024-06-28 18:00 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    clang
It should be in `nativeBuildInputs`

2024-06-28 18:03 UTC, Aleksanaa commented on pkgs/by-name/me/metadata/package.nix
> +    clang
Try removing that LIBCLANG after you apply this change. It should work

2024-06-29 10:53 UTC, Aleksanaa requested changes, later dismissed
Please try moving `rustPlatform.bindgenHook` to `nativeBuildInputs` and removing `LIBCLANG_PATH`.

2024-06-30 12:38 UTC, pinpox commented
Result of `nixpkgs-review pr 322773` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>metadata</li>
  </ul>
</details>

2024-06-30 12:38 UTC, pinpox approved these changes

2024-07-02 15:41 UTC, Aleksanaa commented
Have to pin to a higher darwin toolchain stdenv? Not sure

2024-07-02 15:42 UTC, Aleksanaa commented
```
libavdevice/avfoundation.m:765:41: error: must use 'enum' tag to refer to type 'AVMediaType'
static NSArray* getDevicesWithMediaType(AVMediaType mediaType) {
                                        ^
                                        enum 
libavdevice/avfoundation.m:816:50: error: incompatible integer to pointer conversion sending 'enum AVMediaType' to parameter of type 'NSString *' [-Wint-conversion]
    return [AVCaptureDevice devicesWithMediaType:mediaType];
                                                 ^~~~~~~~~
/nix/store/aq7sq7iwahdkzxn00ksxhpx81pd3aaw3-apple-framework-AVFoundation/Library/Frameworks/AVFoundation.framework/Headers/AVCaptureDevice.h:110:47: note: passing argument to parameter 'mediaType' here
+ (NSArray *)devicesWithMediaType:(NSString *)mediaType;
                                              ^
libavdevice/avfoundation.m:829:54: error: incompatible pointer to integer conversion passing 'NSString *const' to parameter of type 'enum AVMediaType' [-Wint-conversion]
    NSArray *devices       = getDevicesWithMediaType(AVMediaTypeVideo);
                                                     ^~~~~~~~~~~~~~~~
libavdevice/avfoundation.m:765:53: note: passing argument to parameter 'mediaType' here
static NSArray* getDevicesWithMediaType(AVMediaType mediaType) {
                                                    ^
libavdevice/avfoundation.m:830:54: error: incompatible pointer to integer conversion passing 'NSString *const' to parameter of type 'enum AVMediaType' [-Wint-conversion]
    NSArray *devices_muxed = getDevicesWithMediaType(AVMediaTypeMuxed);
                                                     ^~~~~~~~~~~~~~~~
libavdevice/avfoundation.m:765:53: note: passing argument to parameter 'mediaType' here
static NSArray* getDevicesWithMediaType(AVMediaType mediaType) {
                                                    ^
libavdevice/avfoundation.m:865:43: error: incompatible pointer to integer conversion passing 'NSString *const' to parameter of type 'enum AVMediaType' [-Wint-conversion]
        devices = getDevicesWithMediaType(AVMediaTypeAudio);
                                          ^~~~~~~~~~~~~~~~
libavdevice/avfoundation.m:765:53: note: passing argument to parameter 'mediaType' here
static NSArray* getDevicesWithMediaType(AVMediaType mediaType) {
                                                    ^
```

2024-07-02 15:49 UTC, wegank commented
Not the fault of this PR: https://hydra.nixos.org/job/nixpkgs/trunk/ffmpeg_7.x86_64-darwin

2024-07-02 15:50 UTC, Aleksanaa commented
Sorry, didn't look up the logs carefully

2024-07-02 15:51 UTC, Aleksanaa approved these changes

2024-07-02 15:51 UTC, merged