tmux: apply upstream sixel patch
NixOS/nixpkgs pull request #323347
Opened 2024-06-29 10:47 UTC by leana8959

This fixes the issue where tmux would exit unexpectedly, when using neovim 0.10.0 over SSH.

Upstream issues:
https://github.com/tmux/tmux/issues/3983
https://github.com/neovim/neovim/issues/28082

## Description of changes

I have included the upstream patch in https://github.com/tmux/tmux/commit/aa17f0e0c1c8b3f1d6fc8617613c74f07de66fae.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-06-29 11:20 UTC, leana8959 commented
Result of `nixpkgs-review pr 323347` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>18 packages built:</summary>
  <ul>
    <li>arsenal</li>
    <li>arsenal.dist</li>
    <li>byobu</li>
    <li>fzf-git-sh</li>
    <li>germinal</li>
    <li>hostmux</li>
    <li>overmind</li>
    <li>python311Packages.libtmux</li>
    <li>python311Packages.libtmux.dist</li>
    <li>python312Packages.libtmux</li>
    <li>python312Packages.libtmux.dist</li>
    <li>tmux</li>
    <li>tmux-cssh</li>
    <li>tmux.man</li>
    <li>tmuxp</li>
    <li>tmuxp.dist</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>wemux</li>
  </ul>
</details>

2024-06-29 11:45 UTC, leana8959 commented
I've vaguely heard about the migration to "by-name", should I move this there too ?

2024-06-29 16:16 UTC, Sigmanificient requested changes

2024-06-29 16:16 UTC, Sigmanificient commented on pkgs/tools/misc/tmux/default.nix
> +    (fetchpatch{
```suggestion
    (fetchpatch {
```

2024-06-30 17:31 UTC, fpletz approved these changes

2024-06-30 17:31 UTC, merged