emmy-lua-code-style: init at 1.5.4
NixOS/nixpkgs pull request #323401
Opened 2024-06-29 15:26 UTC by NobbZ

## Description of changes

Add the package.

This formatter is already used by the lua-language-server (vendored and as lib). This standalone version makes it easier to create commit hooks to keep the formatting in line with the formatting produced by the LSP.

PS: I'd be happy for actual testing by darwin users, I can not do that, and have to assume it builds as is.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-01 11:37 UTC, FliegendeWurst reviewed
LGTM

2024-11-01 11:37 UTC, FliegendeWurst commented on pkgs/by-name/em/emmy-lua-code-style/package.nix
> +    description = "fast, powerful, and feature-rich Lua formatting and checking tool.";
```suggestion
    description = "Fast, powerful, and feature-rich Lua formatting and checking tool";
```

2025-01-05 15:44 UTC, mrcjkb commented on pkgs/by-name/em/emmy-lua-code-style/package.nix
> +    platforms = lib.platforms.linux ++ lib.platforms.darwin;
question: Can this only be built on linux and darwin, or can we enable it for all unix platforms?

```suggestion
    platforms = lib.platforms.unix;

2025-01-05 15:46 UTC, FliegendeWurst commented on pkgs/by-name/em/emmy-lua-code-style/package.nix
> +    platforms = lib.platforms.linux ++ lib.platforms.darwin;
I would image it was only ever tested on Linux and Darwin, but might work elsewhere too.

2025-01-05 16:03 UTC, mrcjkb commented on pkgs/by-name/em/emmy-lua-code-style/package.nix
> +    platforms = lib.platforms.linux ++ lib.platforms.darwin;
In that case, let's set this to `unix`, and we can change it if we discover it's broken on other platforms.

2025-11-14 07:49 UTC, FliegendeWurst commented on pkgs/by-name/em/emmy-lua-code-style/package.nix
> +  version = "1.5.4";
The latest release is 1.5.7.

2025-11-14 11:17 UTC, mrcjkb requested changes
todo: Commit message and PR title need to be updated to reflect the version bump.

2025-11-14 11:26 UTC, mrcjkb approved these changes

2025-11-16 12:05 UTC, merged