wastebin: fix build on darwin
NixOS/nixpkgs pull request #323545
Opened 2024-06-30 08:52 UTC by Guanran928

## Description of changes
https://hydra.nixos.org/build/262432621/nixlog/3

I also saw `Compiling core-foundation-sys v0.8.6` in build log, but it seems to be working fine without `darwin.apple_sdk.frameworks.CoreFoundation`

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-06-30 08:53 UTC, Guanran928 commented
for https://github.com/NixOS/nixpkgs/issues/323144

2024-06-30 12:38 UTC, pinpox commented
Result of `nixpkgs-review pr 323545` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package failed to build:</summary>
  <ul>
    <li>wastebin</li>
  </ul>
</details>

2024-06-30 12:40 UTC, pinpox requested changes
Fails to build for me, see above

2024-06-30 12:40 UTC, Guanran928 commented
> Result of `nixpkgs-review pr 323545` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> <details>
>   <summary>1 package failed to build:</summary>
>   <ul>
>     <li>wastebin</li>
>   </ul>
> </details>
> 

Hmm, it does build fine for me on x86_64-linux. should I add CoreFoundation?

2024-06-30 12:41 UTC, pinpox commented
I have not much experience on darwin, this is the error output:
```
[nix-shell:~/nixpkgs]$ nixpkgs-review pr 323545
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/323545/head:refs/nixpkgs-review/1
$ git worktree add /Users/pinpox/.cache/nixpkgs-review/pr-323545-1/nixpkgs 7e00526b3e30803309e621d24d54ec7d7b902a36
Preparing worktree (detached HEAD 7e00526b3e30)
Updating files: 100% (41913/41913), done.
HEAD is now at 7e00526b3e30 Merge pull request #323528 from r-ryantm/auto-update/emacsPackages.lsp-bridge
$ git merge --no-commit --no-ff 233d98f3ba66313fe8ffab1345ec519ada260b06
Automatic merge went well; stopped before committing as requested
$ nix build --file /nix/store/6gmdjp21pz16fd0ddyk13fa7bpwjlchy-nixpkgs-review-2.10.5/lib/python3.11/site-packages/nixpkgs_review/nix/review-shell.nix --nix-path 'nixpkgs=/Users/pinpox/.cache/nixpkgs-review/pr-323545-1/nixpkgs nixpkgs-overlays=/tmp/tmpk648n39d' --extra-experimental-features 'nix-command no-url-literals' --no-link --keep-going --no-allow-import-from-derivation --argstr system aarch64-darwin --argstr nixpkgs-path /Users/pinpox/.cache/nixpkgs-review/pr-323545-1/nixpkgs --argstr nixpkgs-config-path /tmp/tmptc1ldqqt.nix --argstr attrs-path /Users/pinpox/.cache/nixpkgs-review/pr-323545-1/attrs.nix
error: builder for '/nix/store/qqyzyf5n07slvv4v31mk91vcmmijjkry-wastebin-2.4.3.drv' failed with exit code 101;
       last 10 log lines:
       >     routes::tests::delete_via_link
       >     routes::tests::download
       >     routes::tests::insert_via_form
       >     routes::tests::insert_via_json
       >     routes::tests::insert_via_json_encrypted
       >     routes::tests::unknown_paste
       >
       > test result: FAILED. 7 passed; 8 failed; 0 ignored; 0 measured; 0 filtered out; finished in 2.01s
       >
       > error: test failed, to rerun pass `--bin wastebin`
       For full logs, run 'nix log /nix/store/qqyzyf5n07slvv4v31mk91vcmmijjkry-wastebin-2.4.3.drv'.
error: 1 dependencies of derivation '/nix/store/lgd11r546rfp6cda1n66cx7v2n5f4n7y-review-shell.drv' failed to build
```

2024-06-30 12:41 UTC, Guanran928 commented
> Result of `nixpkgs-review pr 323545` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> <details>
>   <summary>1 package failed to build:</summary>
>   <ul>
>     <li>wastebin</li>
>   </ul>
> </details>
> 

Can you share logs?

2024-06-30 12:44 UTC, pinpox commented
> > Result of `nixpkgs-review pr 323545` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> > 
> >   1 package failed to build:
> >   
> >     * wastebin
> 
> Can you share logs?

Sure, here you go:
<details>
```
[nix-shell:~/.cache/nixpkgs-review/pr-323545-1]$ nix log /nix/store/qqyzyf5n07slvv4v31mk91vcmmijjkry-wastebin-2.4.3.drv | cat
warning: The interpretation of store paths arguments ending in `.drv` recently changed. If this command is now failing try again with '/nix/store/qqyzyf5n07slvv4v31mk91vcmmijjkry-wastebin-2.4.3.drv^*'
@nix { "action": "setPhase", "phase": "unpackPhase" }
Running phase: unpackPhase
unpacking source archive /nix/store/684dmh8g0q98wba8cfa111dlah3i11gn-source
source root is source
Executing cargoSetupPostUnpackHook
unpacking source archive /nix/store/rdgh4dw4qwbkqis5f1jwjl1djhgp9zcf-wastebin-2.4.3-vendor.tar.gz
Finished cargoSetupPostUnpackHook
@nix { "action": "setPhase", "phase": "patchPhase" }
Running phase: patchPhase
Executing cargoSetupPostPatchHook
Validating consistency between /private/tmp/nix-build-wastebin-2.4.3.drv-0/source/Cargo.lock and /private/tmp/nix-build-wastebin-2.4.3.drv-0/wastebin-2.4.3-vendor.tar.gz/Cargo.lock
Finished cargoSetupPostPatchHook
@nix { "action": "setPhase", "phase": "updateAutotoolsGnuConfigScriptsPhase" }
Running phase: updateAutotoolsGnuConfigScriptsPhase
@nix { "action": "setPhase", "phase": "configurePhase" }
Running phase: configurePhase
@nix { "action": "setPhase", "phase": "buildPhase" }
Running phase: buildPhase
Executing cargoBuildHook
++ env CC_AARCH64_APPLE_DARWIN=/nix/store/9g8qxz6r8x7g01hkzy739m5j6bawk4d5-clang-wrapper-16.0.6/bin/cc CXX_AARCH64_APPLE_DARWIN=/nix/store/9g8qxz6r8x7g01hkzy739m5j6bawk4d5-clang-wrapper-16.0.6/bin/c++ CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=/nix/store/9g8qxz6r8x7g01hkzy739m5j6bawk4d5-clang-wrapper-16.0.6/bin/cc CC_AARCH64_APPLE_DARWIN=/nix/store/9g8qxz6r8x7g01hkzy739m5j6bawk4d5-clang-wrapper-16.0.6/bin/cc CXX_AARCH64_APPLE_DARWIN=/nix/store/9g8qxz6r8x7g01hkzy739m5j6bawk4d5-clang-wrapper-16.0.6/bin/c++ CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=/nix/store/9g8qxz6r8x7g01hkzy739m5j6bawk4d5-clang-wrapper-16.0.6/bin/cc CARGO_BUILD_TARGET=aarch64-apple-darwin HOST_CC=/nix/store/9g8qxz6r8x7g01hkzy739m5j6bawk4d5-clang-wrapper-16.0.6/bin/cc HOST_CXX=/nix/store/9g8qxz6r8x7g01hkzy739m5j6bawk4d5-clang-wrapper-16.0.6/bin/c++ cargo build -j 8 --target aarch64-apple-darwin --offline --profile release
warning: `/private/tmp/nix-build-wastebin-2.4.3.drv-0/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
warning: `/private/tmp/nix-build-wastebin-2.4.3.drv-0/.cargo/config` is deprecated in favor of `config.toml`
note: if you need to support cargo 1.38 or earlier, you can symlink `config` to `config.toml`
   Compiling libc v0.2.152
   Compiling version_check v0.9.4
   Compiling cfg-if v1.0.0
   Compiling proc-macro2 v1.0.76
   Compiling unicode-ident v1.0.12
   Compiling once_cell v1.19.0
   Compiling autocfg v1.1.0
   Compiling itoa v1.0.10
   Compiling typenum v1.17.0
   Compiling bytes v1.5.0
   Compiling pin-project-lite v0.2.13
   Compiling smallvec v1.11.2
   Compiling log v0.4.20
   Compiling generic-array v0.14.7
   Compiling ahash v0.8.7
   Compiling zerocopy v0.7.32
   Compiling futures-core v0.3.30
   Compiling fnv v1.0.7
   Compiling lock_api v0.4.11
   Compiling tracing-core v0.1.32
   Compiling serde v1.0.195
   Compiling parking_lot_core v0.9.9
   Compiling allocator-api2 v0.2.16
   Compiling pkg-config v0.3.28
   Compiling hashbrown v0.14.3
   Compiling http v1.0.0
   Compiling quote v1.0.35
   Compiling getrandom v0.2.12
   Compiling jobserver v0.1.27
   Compiling scopeguard v1.2.0
   Compiling syn v2.0.48
   Compiling rand_core v0.6.4
   Compiling futures-task v0.3.30
   Compiling cc v1.0.83
   Compiling crypto-common v0.1.6
   Compiling memchr v2.7.1
   Compiling pin-utils v0.1.0
   Compiling futures-util v0.3.30
   Compiling mio v0.8.10
   Compiling parking_lot v0.12.1
   Compiling signal-hook-registry v1.4.1
   Compiling num_cpus v1.16.0
   Compiling socket2 v0.5.5
   Compiling subtle v2.5.0
   Compiling rustversion v1.0.14
   Compiling http-body v1.0.0
   Compiling unicase v2.7.0
   Compiling percent-encoding v2.3.1
   Compiling equivalent v1.0.1
   Compiling zstd-sys v2.0.9+zstd.1.5.5
   Compiling indexmap v2.1.0
   Compiling block-buffer v0.10.4
   Compiling slab v0.4.9
   Compiling futures-sink v0.3.30
   Compiling digest v0.10.7
   Compiling tower-service v0.3.2
   Compiling base64 v0.21.7
   Compiling tower-layer v0.3.2
   Compiling time-core v0.1.2
   Compiling crc32fast v1.3.2
   Compiling httparse v1.8.0
   Compiling powerfmt v0.2.0
   Compiling async-trait v0.1.77
   Compiling time-macros v0.2.16
   Compiling http-body-util v0.1.0
   Compiling mime_guess v2.0.4
   Compiling cpufeatures v0.2.12
   Compiling axum-core v0.4.3
   Compiling httpdate v1.0.3
   Compiling serde_json v1.0.111
   Compiling minimal-lexical v0.2.1
   Compiling libm v0.2.8
   Compiling ryu v1.0.16
   Compiling mime v0.3.17
   Compiling vcpkg v0.2.15
   Compiling alloc-no-stdlib v2.0.4
   Compiling zstd-safe v7.0.0
   Compiling adler v1.0.2
   Compiling miniz_oxide v0.7.1
   Compiling alloc-stdlib v0.2.2
   Compiling nom v7.1.3
   Compiling libsqlite3-sys v0.27.0
   Compiling form_urlencoded v1.2.1
   Compiling aho-corasick v1.1.2
   Compiling futures-channel v0.3.30
   Compiling num-traits v0.2.17
   Compiling tinyvec_macros v0.1.1
   Compiling ppv-lite86 v0.2.17
   Compiling sync_wrapper v0.1.2
   Compiling regex-syntax v0.8.2
   Compiling rand_chacha v0.3.1
   Compiling serde_derive v1.0.195
   Compiling tracing-attributes v0.1.27
   Compiling tokio-macros v2.2.0
   Compiling pin-project-internal v1.1.3
   Compiling askama_parser v0.2.0
   Compiling tokio v1.35.1
   Compiling regex-automata v0.4.3
   Compiling pin-project v1.1.3
   Compiling tracing v0.1.40
   Compiling tinyvec v1.6.0
   Compiling flate2 v1.0.28
   Compiling brotli-decompressor v2.5.1
   Compiling axum v0.7.4
   Compiling inout v0.1.3
   Compiling cookie v0.18.0
   Compiling safemem v0.3.3
   Compiling tokio-util v0.7.10
   Compiling thiserror v1.0.56
   Compiling zeroize v1.7.0
   Compiling h2 v0.4.1
   Compiling bit-vec v0.6.3
   Compiling bitflags v2.4.1
   Compiling deranged v0.3.11
   Compiling basic-toml v0.1.8
   Compiling serde_urlencoded v0.7.1
   Compiling serde_path_to_error v0.1.15
   Compiling bit-set v0.5.3
   Compiling askama_derive v0.12.4
   Compiling time v0.3.31
   Compiling cipher v0.4.4
   Compiling line-wrap v0.1.1
   Compiling tower v0.4.13
   Compiling brotli v3.4.0
   Compiling regex v1.10.2
   Compiling humansize v2.1.3
   Compiling unicode-normalization v0.1.22
   Compiling zstd v0.13.0
   Compiling thiserror-impl v1.0.56
   Compiling hyper v1.1.0
   Compiling rand v0.8.5
   Compiling sha1 v0.10.6
   Compiling sha2 v0.10.8
   Compiling hyper-util v0.1.2
   Compiling hmac v0.12.1
   Compiling universal-hash v0.5.1
   Compiling quick-xml v0.31.0
   Compiling headers-core v0.3.0
   Compiling hashlink v0.8.4
   Compiling matchit v0.7.3
   Compiling fallible-iterator v0.3.0
   Compiling rusqlite_migration v1.1.0
   Compiling askama_escape v0.10.3
   Compiling constant_time_eq v0.3.0
   Compiling fallible-streaming-iterator v0.1.9
   Compiling lazy_static v1.4.0
   Compiling arrayref v0.3.7
   Compiling arrayvec v0.7.4
   Compiling opaque-debug v0.3.0
   Compiling unicode-bidi v0.3.14
   Compiling overload v0.1.1
   Compiling same-file v1.0.6
   Compiling blake2b_simd v1.0.2
   Compiling walkdir v2.4.0
   Compiling idna v0.5.0
   Compiling async-compression v0.4.5
   Compiling nu-ansi-term v0.46.0
   Compiling poly1305 v0.8.0
   Compiling sharded-slab v0.1.7
   Compiling askama v0.12.1
   Compiling plist v1.6.0
   Compiling headers v0.4.0
   Compiling fancy-regex v0.11.0
   Compiling chacha20 v0.9.1
   Compiling bincode v1.3.3
   Compiling aead v0.5.2
   Com [...]

2024-06-30 13:03 UTC, Guanran928 commented
Hmm, I don't really have any idea what's going on. In my build log, all tests does pass: https://pb.ny4.dev/CWzVhc#L267

@wegank can you help?

2024-06-30 14:56 UTC, wegank commented
Result of `nixpkgs-review pr 323545` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>wastebin</li>
  </ul>
</details>

2024-06-30 14:58 UTC, wegank commented
Can't reproduce the failure on ofborg or on my machine.

2024-06-30 15:08 UTC, matthiasbeyer approved these changes
Diff LGTM

2024-06-30 16:44 UTC, pinpox commented
> Can't reproduce the failure on ofborg or on my machine.

Strange. My build result above is done on the darwin community builder machine, if you want I can try again?

2024-06-30 21:54 UTC, wegank commented
I have no idea how darwin community builder is configured, it's possible that the sandbox is enabled, and you need to add `__darwinAllowLocalNetworking = true;`.

2024-07-01 05:14 UTC, Aleksanaa commented
> I have no idea how darwin community builder is configured, it's possible that the sandbox is enabled, and you need to add `__darwinAllowLocalNetworking = true;`.

Does that affect hydra?

2024-07-01 21:41 UTC, wegank commented
No.

2024-07-01 21:42 UTC, merged