j-mc-2-obj: init at 125
NixOS/nixpkgs pull request #323556
Opened 2024-06-30 10:14 UTC by hatch01

## Description of changes

Add j-mc-2-obj.

## Things done

Packaged j-mc-2-obj

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

@Xeon0X please confirm that everything seems to work.
I am also not sure about the name of the app because it is sometime called j-mc-2-obj, sometime jMc2Obj, sometime jMc2Obj-version.
The app also has no license, is it ok to just keep the license field unset? 

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-24 07:43 UTC, FliegendeWurst requested changes
Commit message should be `jmc2obj: init at ...`

2024-10-24 07:43 UTC, FliegendeWurst commented on pkgs/by-name/jm/jmc2obj/package.nix
> +    makeWrapper ${jre}/bin/java $out/bin/jMc2Obj \
```suggestion
    makeWrapper ${lib.getExe jre} $out/bin/jMc2Obj \
```

2024-10-24 07:43 UTC, FliegendeWurst commented on pkgs/by-name/jm/jmc2obj/package.nix
> +    # license = ; # this project has still no license
```suggestion
    license = lib.licenses.unfree; # this project has still no license
```

2024-10-24 07:43 UTC, FliegendeWurst commented on pkgs/by-name/jm/jmc2obj/package.nix
> +  version = "125";
```suggestion
  version = "126";
```

2024-10-24 07:43 UTC, FliegendeWurst commented on pkgs/by-name/jm/jmc2obj/package.nix
> +  mvnHash = "sha256-UGKDrrfoVnHe8rHOm1/NU38vNkSIpQbEnkF3yQVdGqM=";
hash does not match

2024-10-24 20:21 UTC, FliegendeWurst requested changes

2024-10-24 20:21 UTC, FliegendeWurst commented on .direnv/bin/nix-direnv-reload
> +#!/usr/bin/env bash
Should not be here, probably added accidentally

2024-10-24 20:22 UTC, FliegendeWurst commented on pkgs/by-name/jm/jmc2obj/package.nix
> +  mvnHash = "sha256-UGKDrrfoVnHe8rHOm1/NU38vNkSIpQbEnkF3yQVdGqM=";
```suggestion
  mvnHash = "sha256-ya8E/6tOxyW+AO7v9p0dg72qFpQjWwvntZOw+TEKq0k=";
```

2024-10-24 20:48 UTC, FliegendeWurst reviewed
LGTM overall

2024-10-24 20:48 UTC, FliegendeWurst commented on pkgs/by-name/jm/jmc2obj/package.nix
> +    maintainers = with lib.maintainers; [ eymeric ];
```suggestion
    maintainers = with lib.maintainers; [ eymeric ];
    mainProgram = "jMc2Obj";
```

2024-10-24 20:48 UTC, FliegendeWurst commented on pkgs/by-name/jm/jmc2obj/package.nix
> +  installPhase = ''
```suggestion
  installPhase = ''
    runHook preInstall
```

2024-10-24 20:48 UTC, FliegendeWurst commented on pkgs/by-name/jm/jmc2obj/package.nix
> +  '';
```suggestion
    runHook postInstall
  '';
```

2024-10-24 21:05 UTC, FliegendeWurst approved these changes

2024-10-24 21:11 UTC, hatch01 commented
Thank you for your usefull reviews !

2024-12-02 17:37 UTC, wolfgangwalther requested changes
Since the license is in a sub-folder, I don't think this applies for the whole project. This should be clarified.

2024-12-02 17:42 UTC, FliegendeWurst commented
Fairly certain the "conf" folder is just where random files are stored (.obj, .mtl, ...)

2024-12-02 20:16 UTC, hatch01 commented
Ok, my bad, I will open an issue to fix it upstream

2024-12-07 10:43 UTC, hatch01 commented
I asked about this issue, and it seems that the license that I found was the right one
https://github.com/jmc2obj/j-mc-2-obj/issues/272

2024-12-07 19:40 UTC, wolfgangwalther approved these changes

2024-12-07 19:40 UTC, merged