geo: init at 1.1
NixOS/nixpkgs pull request #323744
Opened 2024-07-01 07:39 UTC by oluceps

## Description of changes
Add https://github.com/MetaCubeX/geo

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-01 12:25 UTC, AndersonTorres requested changes

2024-07-01 12:25 UTC, AndersonTorres commented on pkgs/by-name/ge/geo/package.nix
> +  };
```suggestion
  meta = {
    description = "Easy way to manage all your Geo resources. Available as both a CLI and a Go library";
    homepage = "https://github.com/MetaCubeX/geo";
    license = lib.licenses.gpl3Only;
    maintainers = with lib.maintainers; [ oluceps ];
    mainProgram = "geo";
  };
```

2024-07-03 00:43 UTC, getchoo requested changes

2024-07-03 00:43 UTC, getchoo commented on pkgs/by-name/ge/geo/package.nix
> +    homepage = "https://github.com/MetaCubeX/geo";
```suggestion
    homepage = "https://github.com/MetaCubeX/geo";
    changelog = "https://github.com/MetaCubeX/geo/releases/tag/v${version}";
```

2024-07-03 00:43 UTC, getchoo commented on pkgs/by-name/ge/geo/package.nix
> +
```suggestion

  passthru = {
    updateScript = nix-update-script { };
    tests.version = testers.testVersion { package = geo; };
  };

```

and a simple test and update script will help make this a bit more maintainable

2024-07-03 00:43 UTC, getchoo commented on pkgs/by-name/ge/geo/package.nix
> +  fetchFromGitHub,
```suggestion
  fetchFromGitHub,
  nix-update-script,
  testers,
  geo
```

2024-07-03 03:57 UTC, Aleksanaa commented on pkgs/by-name/ge/geo/package.nix
> +    description = "Easy way to manage all your Geo resources. Available as both a CLI and a Go library";
```suggestion
    description = "Easy way to manage all your Geo resources";
```

We cannot actually consume that Go library for now, so not really worth mentioning

2024-07-03 21:05 UTC, getchoo requested changes

2024-07-03 21:05 UTC, getchoo commented on pkgs/by-name/ge/geo/package.nix
> +    tests.version = testers.testVersion { package = geo; };
```suggestion
    tests.version = testers.testVersion {
      package = geo;
      command = "${lib.getExe geo} --help";
      version = "v${version}";
    };
```
it looks like `geo` doesn't actually have a `--version` argument. we can get it from the output of `--help` instead, though

2024-07-07 06:55 UTC, Aleksanaa approved these changes

2024-07-07 06:58 UTC, Aleksanaa commented
wait

2024-07-07 07:08 UTC, Aleksanaa commented
Looks like [we cannot change the constant version](https://github.com/golang/go/issues/63372) in https://github.com/MetaCubeX/geo/blob/d76155814f3ad4668dce36cabfb536f373683262/constant.go#L4

Just sed it?

2024-07-07 07:17 UTC, Aleksanaa commented on pkgs/by-name/ge/geo/package.nix
> +
```nix
  postPatch = ''
    sed -iE 's/^[[:blank:]]*Version.*/Version = "${version}"/' constant.go
  '';
```

2024-08-11 01:38 UTC, AndersonTorres approved these changes

2024-09-09 02:30 UTC, merged