arma3-unix-launcher: init at 383-unstable-2024-04-18
NixOS/nixpkgs pull request #324452
Opened 2024-07-04 01:16 UTC by DrymarchonShaun

## Description of changes

A clean, intuitive Arma 3 + DayZ SA Launcher for GNU/Linux and MacOS.

homepage URL: [https://github.com/muttleyxd/arma3-unix-launcher/](https://github.com/muttleyxd/arma3-unix-launcher/)
licenses: mit, unfree 
platforms: linux, darwin

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-06 15:22 UTC, keenanweaver requested changes
Looks great. Here are some changes I'll suggest: 

1) Move the default.nix and the patch files from `pkgs/games/arma3-unix-launcher` to `pkgs/by-name/ar/arma3-unix-launcher`, remove the change to all-packages.nix (This is the older methodology, and the newer one is what I'm suggesting) You'd also want to rename `default.nix` to `package.nix`.
2) DayZ build is working now, but it looks like it replaces arma3 instead of being an additional executable that is compiled. Are there build flags or steps that can be taken so that DayZ & Arma are built together and not overlapping each other?

2024-07-06 15:24 UTC, keenanweaver requested changes
Some syntax changes

2024-07-06 15:24 UTC, keenanweaver commented on pkgs/games/arma3-unix-launcher/default.nix
> +stdenv.mkDerivation rec {
```suggestion
stdenv.mkDerivation (finalAttrs: {
```

2024-07-06 15:24 UTC, keenanweaver commented on pkgs/games/arma3-unix-launcher/default.nix
> +    repo = pname;
```suggestion
    repo = finalAttrs.pname;
```

2024-07-06 15:24 UTC, keenanweaver commented on pkgs/games/arma3-unix-launcher/default.nix
> +}
```suggestion
})
```

2024-07-06 17:36 UTC, DrymarchonShaun commented
> 1. Move the default.nix and the patch files from `pkgs/games/arma3-unix-launcher` to `pkgs/by-name/ar/arma3-unix-launcher`, remove the change to all-packages.nix (This is the older methodology, and the newer one is what I'm suggesting) You'd also want to rename `default.nix` to `package.nix`.

Hmm. building after Moving everything as suggested errors out with
```
evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "wrapQtAppsHook" at /nix/store/97j69f0w2ld7bn5067q962b5z05mfj5a-source/pkgs/by-name/ar/arma3-unix-launcher/package.nix:15, did you mean "wrapGAppsHook"?'
```
I was using `libsForQt5.callpackage` before, I'm assuming that's the cause?

> 2. DayZ build is working now, but it looks like it replaces arma3 instead of being an additional executable that is compiled. Are there build flags or steps that can be taken so that DayZ & Arma are built together and not overlapping each other?

As far as I can tell, the way cmake is set up, it's build one or the other. I did just test and this seems to work fine ```nix
  home.packages = [
    pkgs.arma3-unix-launcher
    (pkgs.arma3-unix-launcher.override { buildDayZLauncher = true; })
  ];
```
The executables are separate, `arma3-unix-launcher` and `dayz-linux-launcher`.

2024-07-06 17:44 UTC, keenanweaver commented
> ```
> evaluation aborted with the following error message: 'lib.customisation.callPackageWith: Function called without required argument "wrapQtAppsHook" at /nix/store/97j69f0w2ld7bn5067q962b5z05mfj5a-source/pkgs/by-name/ar/arma3-unix-launcher/package.nix:15, did you mean "wrapGAppsHook"?'
> ```

Weird, shouldn't be doing that. Try building it with `nix-build -E 'with import <nixpkgs> {}; qt5.callPackage ./package.nix { buildDayZLauncher = true; }'`

> ```nix
>   home.packages = [
>     pkgs.arma3-unix-launcher
>     (pkgs.arma3-unix-launcher.override { buildDayZLauncher = true; })
>   ];
> ```

Interesting. I didn't think to include two instances of the package. My thought was `(pkgs.arma3-unix-launcher.override { buildDayZLauncher = true; })` would do both. New nix knowledge unlocked.

2024-07-06 17:54 UTC, DrymarchonShaun commented
> nix-build -E 'with import <nixpkgs> {}; qt5.callPackage ./package.nix { buildDayZLauncher = true; }'

That works fine. Is `qt5.callPackage` what packages in `pkgs/by-name/` are called by, though?

> Interesting. I didn't think to include two instances of the package. My thought was `(pkgs.arma3-unix-launcher.override { buildDayZLauncher = true; })` would do both. New nix knowledge unlocked.

I think multiple instances of packages works fine as long as the executables don't overlap?

2024-07-06 18:03 UTC, DrymarchonShaun commented
Ah, I figured it out. `wrapQtAppsHook` needs to be `qt5.wrapQtAppsHook`

2024-07-06 18:03 UTC, keenanweaver commented
> That works fine. Is `qt5.callPackage` what packages in `pkgs/by-name/` are called by, though?

Honestly, I really don't know how it works or if there's something special with Qt5 apps and packaging. https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/by-name/fo/fooyin/package.nix#L55 This is a Qt6 package and it looks like it's just using `kdePackages`

Your method will work for sure, but I always see PRs that place in `by-name`. Definitely need someone more knowledgeable than me to help out here.

2024-07-06 19:45 UTC, keenanweaver commented
Result of `nixpkgs-review pr 324452` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>arma3-unix-launcher</li>
  </ul>
</details>

2024-07-06 19:45 UTC, keenanweaver approved these changes

2024-07-15 20:01 UTC, eclairevoyant requested changes

2024-07-15 20:01 UTC, eclairevoyant commented on pkgs/by-name/ar/arma3-unix-launcher/package.nix
> +  cmakeFlags = [ "-Wno-dev" ] ++ lib.optional buildDayZLauncher [ "-DBUILD_DAYZ_LAUNCHER=ON" ];
```suggestion
  cmakeFlags = [ "-Wno-dev" ] ++ lib.optionals buildDayZLauncher [ "-DBUILD_DAYZ_LAUNCHER=ON" ];
```

`optional` would make it a nested list

2024-07-15 20:17 UTC, DrymarchonShaun commented on pkgs/by-name/ar/arma3-unix-launcher/package.nix
> +    repo = finalAttrs.pname;
What is considered the proper way to resolve suggestions? For the previous ones I committed the changes locally, squashed the commit into the original commit and then force pushed, I have a feeling that isn't the proper way, but I also assume using GitHub's "commit suggestion" button results in messy commits?

2024-07-15 20:18 UTC, eclairevoyant commented on pkgs/by-name/ar/arma3-unix-launcher/package.nix
> +    repo = finalAttrs.pname;
squashing/rebasing + force-pushing is the standard in nixpkgs

2024-07-15 20:23 UTC, eclairevoyant commented
> > That works fine. Is `qt5.callPackage` what packages in `pkgs/by-name/` are called by, though?
> 
> Honestly, I really don't know how it works or if there's something special with Qt5 apps and packaging.

Packages in `by-name` are always called with the top-level `callPackage`; the `libsForQt5.callPackage` is (IMO) fairly useless, as all it does is add the corresponding `libsForQt5.wrapQtAppsHook` (which we can just do ourselves instead).

> Weird, shouldn't be doing that. Try building it with `nix-build -E 'with import <nixpkgs> {}; qt5.callPackage ./package.nix { buildDayZLauncher = true; }'`

Normally to do a proper test of a package in nixpkgs, we'd use `nix-build -A attrname` (or if you want to override it, something like `nix-build -E '(import ./. {}).attrname.override { foo = "bar"; }`)

2024-07-15 20:31 UTC, eclairevoyant commented on pkgs/by-name/ar/arma3-unix-launcher/package.nix
> +  cmakeFlags = [ "-Wno-dev" ] ++ lib.optional buildDayZLauncher [ "-DBUILD_DAYZ_LAUNCHER=ON" ];
actually since we have `lib.cmakeBool`, the latter could also be `lib.cmakeBool "BUILD_DAYZ_LAUNCHER" buildDayZLauncher`

2024-07-15 21:04 UTC, DrymarchonShaun commented
Version was updated as a few of my pull requests were merged upstream, one of which makes the dayz version build without requiring a patch.

2024-07-28 22:00 UTC, SuperSandro2000 commented on pkgs/by-name/ar/arma3-unix-launcher/package.nix
> +    description = "A clean, intuitive Arma 3 + DayZ SA Launcher for GNU/Linux and MacOS";
```suggestion
    description = "Clean & intuitive Arma 3 + DayZ SA Launcher";
```

2024-07-28 22:16 UTC, eclairevoyant commented on pkgs/by-name/ar/arma3-unix-launcher/package.nix
please rebase on `master` and format with nixfmt as per https://github.com/NixOS/nixpkgs/actions/runs/10134732520/job/28021315616?pr=324452

2024-07-28 22:17 UTC, eclairevoyant commented on pkgs/by-name/ar/arma3-unix-launcher/package.nix
> +  cmakeFlags = [ "-Wno-dev" ] ++ lib.optionals buildDayZLauncher [ "-DBUILD_DAYZ_LAUNCHER=ON" ];
formatting nit

2024-07-28 22:25 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/satisfaction-survey-from-the-new-rfc-166-formatting/49758/7

2024-07-29 00:55 UTC, eclairevoyant approved these changes
Don't have the game available to test this, but it does at least run

2024-08-17 15:05 UTC, merged