Init: chromium-bin
NixOS/nixpkgs pull request #324701
Opened 2024-07-05 01:09 UTC by lrworth

## Description of changes

(This is a resubmission of https://github.com/NixOS/nixpkgs/pull/244152 with some simplifications applied).

Provides the binary release of Chromium as `chromium-bin`. Note that `chromium` already exists, but would require a lot of work to add support for `*-darwin` systems. For that reason the `chromium-bin` added in this PR only supports `darwin`, but it would be simple to add other systems as desired.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin (**from `aarch64-darwin` with Rosetta 2**)
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2024-07-05 01:14 UTC, lrworth commented
@michaelCTS in response to https://github.com/NixOS/nixpkgs/pull/244152#issuecomment-2208312058 I've replaced your handle with mine in the maintainers list. Let me know if you'd prefer to remain on the list.

2024-07-05 07:29 UTC, michaelCTS commented
@lrworth that's fine. I'll actually get myself off of the maintainers list. Cheers

2024-11-17 15:56 UTC, FliegendeWurst requested changes
Please also make sure your commit messages follow the guidelines.

2024-11-17 15:56 UTC, FliegendeWurst commented on pkgs/applications/networking/browsers/chromium-bin/default.nix
Should be in pkgs/by-name

2024-11-17 15:56 UTC, FliegendeWurst commented on pkgs/applications/networking/browsers/chromium-bin/default.nix
> +, fetchzip
Please format with the new formatter.

2024-11-17 15:56 UTC, FliegendeWurst commented on pkgs/applications/networking/browsers/chromium-bin/default.nix
> +    description = "An open source web browser from Google (binary release)";
```suggestion
    description = "Open source web browser from Google (binary release)";
```

2025-01-15 19:09 UTC, martinjlowm commented
Just stumbled upon this and it looks a little stale. @lrworth can you do another iteration and account for Arne's feedback?

2025-01-16 23:34 UTC, closed without merging

2025-01-16 23:34 UTC, lrworth commented
Thanks for the feedback, everyone. I don't have time to maintain this so I'll host it as a flake elsewhere and close the PR.

2025-01-17 00:13 UTC, kkimdev commented
@lrworth this would be super useful for us, could you share the link once you host your flake somewhere? Thanks!

2025-01-17 01:38 UTC, lrworth commented
Here you go: https://github.com/lrworth/chromium-bin-flake

`nix run github:lrworth/chromium-bin-flake` launches chromium.