mypy: 1.10.0 → 1.10.1
NixOS/nixpkgs pull request #324867
Opened 2024-07-05 17:24 UTC by nicoonoclaste

## Description of changes

In `mypy`:
- add `passthru.updateScript`
  otherwise, automatic update (with `update.nix`) did not work
- update to [v1.10.1](https://github.com/python/mypy/compare/v1.10.0...v1.10.1)
  backports an error-reporting bugfix

In `cwltool` and `python3Packages.schema-salad`, fix the version constraint of the `mypy` dependency.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- [x] Tested `mypy.passthru.tests`, i.e. `nixosTests.nixos-test-driver`
- [x] Tested compilation of all affected packages using `nixpkgs-review`
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
  ran `mypy` under CPython 3.12, on a Python project I was just working on, it reports the same output
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-10 17:34 UTC, mkg20001 requested changes

2024-07-10 17:34 UTC, mkg20001 commented on pkgs/development/python-modules/schema-salad/default.nix
> +    url = "https://patch-diff.githubusercontent.com/raw/common-workflow-language/schema_salad/pull/840.patch";
this is referencing a pull request instead of a commit, which can have it's contents changed.

2024-07-11 15:41 UTC, mkg20001 approved these changes

2024-07-11 15:41 UTC, merged

2024-07-11 19:24 UTC, vcunat commented
Why did you merge directly to master?  It looks like ~18k rebuilds, at a glance.

2024-07-11 20:22 UTC, vcunat commented
Probably something contained in PR #322145