python312Packages.gstools: init at 1.5.2; python312Packages.hankel: init at 1.2.2; python312Packages.pyevtk: init at 1.2.0
NixOS/nixpkgs pull request #325617
Opened 2024-07-08 19:03 UTC by Sigmanificient

## Description of changes

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-26 07:59 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4321

2024-07-26 18:14 UTC, gador commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 325617` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>

  <summary>4 packages failed to build and are new build failures:</summary>
  <ul>
<li>python311Packages.gstools: log was empty</li>
<li>python311Packages.gstools.dist: log was empty</li>
<li>python312Packages.gstools: log was empty</li>
<li>python312Packages.gstools.dist: log was empty</li>
  </ul>
</details>
<details>
<summary>
8 packages built:
</summary>
<ul>
<li>python311Packages.hankel</li>
<li>python311Packages.hankel.dist</li>
<li>python311Packages.pyevtk</li>
<li>python311Packages.pyevtk.dist</li>
<li>python312Packages.hankel</li>
<li>python312Packages.hankel.dist</li>
<li>python312Packages.pyevtk</li>
<li>python312Packages.pyevtk.dist</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
python311Packages.gstools.dist:
<details>


warning: unclear-gpl
`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/gstools/default.nix:61:5:

```
   |
61 |     license = lib.licenses.lgpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
python311Packages.gstools:
<details>


warning: unclear-gpl
`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/gstools/default.nix:61:5:

```
   |
61 |     license = lib.licenses.lgpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
python312Packages.gstools.dist:
<details>


warning: unclear-gpl
`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/gstools/default.nix:61:5:

```
   |
61 |     license = lib.licenses.lgpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
python312Packages.gstools:
<details>


warning: unclear-gpl
`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/gstools/default.nix:61:5:

```
   |
61 |     license = lib.licenses.lgpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
</details>

2024-07-26 18:15 UTC, gador requested changes

2024-07-26 18:15 UTC, gador commented on pkgs/development/python-modules/gstools/default.nix
> +  version = "1.5.2";
version `1.6.0` is out since last week and there seems to be a hash mismatch now with the tag of version `1.5.2`

2024-07-26 21:46 UTC, SuperSandro2000 commented on pkgs/development/python-modules/pyevtk/default.nix
> +  nativeCheckInputs = [ pytestCheckHook pytest-cov ];
```suggestion
  build-system = [ setuptools ];

  dependencies = [ numpy ];

  nativeCheckInputs = [ pytestCheckHook pytest-cov ];

  pythonImportsCheck = [ "pyevtk" ];
```
those deps are rather useless in nixpkgs

2024-07-27 05:16 UTC, gador commented
Could you please run `nixfmt` on the files?

2024-07-27 13:01 UTC, gador approved these changes

2024-07-27 13:04 UTC, gador commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 325617` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
13 packages built:
</summary>
<ul>
<li>nixpkgs-manual</li>
<li>python311Packages.gstools</li>
<li>python311Packages.gstools.dist</li>
<li>python311Packages.hankel</li>
<li>python311Packages.hankel.dist</li>
<li>python311Packages.pyevtk</li>
<li>python311Packages.pyevtk.dist</li>
<li>python312Packages.gstools</li>
<li>python312Packages.gstools.dist</li>
<li>python312Packages.hankel</li>
<li>python312Packages.hankel.dist</li>
<li>python312Packages.pyevtk</li>
<li>python312Packages.pyevtk.dist</li>
</ul>
</details>

The following issues got detected with the above build packages.
Please fix at least the ones listed with your changed packages:

<details>
nixpkgs-manual:
<details>

Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

</details>
python311Packages.gstools.dist:
<details>

got build log for '/nix/store/dys4krjzwybkihg14bzb05r2s83kqkbx-python3.11-gstools-1.6.0-dist' from 'daemon'
When evaluating attribute ‘python311Packages.gstools.dist’:
warning: unclear-gpl
`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/gstools/default.nix:61:5:

```
   |
61 |     license = lib.licenses.lgpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
python311Packages.gstools:
<details>

got build log for '/nix/store/v2p0kciwidf7r2nwn08g3xf6sm9985na-python3.11-gstools-1.6.0' from 'daemon'
When evaluating attribute ‘python311Packages.gstools’:
warning: unclear-gpl
`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/gstools/default.nix:61:5:

```
   |
61 |     license = lib.licenses.lgpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
python312Packages.gstools.dist:
<details>

got build log for '/nix/store/xm4vcypzybrn74rzk0ww3dfjks5p7dpk-python3.12-gstools-1.6.0-dist' from 'daemon'
When evaluating attribute ‘python312Packages.gstools.dist’:
warning: unclear-gpl
`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/gstools/default.nix:61:5:

```
   |
61 |     license = lib.licenses.lgpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
python312Packages.gstools:
<details>

got build log for '/nix/store/iynzw1b0g6csnyg77n0nm1rqs4y813ja-python3.12-gstools-1.6.0' from 'daemon'
When evaluating attribute ‘python312Packages.gstools’:
warning: unclear-gpl
`lgpl3` is a deprecated license, please check if project uses `lgpl3Plus` or `lgpl3Only` and change `meta.license` accordingly.

Near pkgs/development/python-modules/gstools/default.nix:61:5:

```
   |
61 |     license = lib.licenses.lgpl3;
   |     ^
```

See: https://github.com/jtojnar/nixpkgs-hammering/blob/master/explanations/unclear-gpl.md
</details>
</details>

2024-07-27 13:08 UTC, Sigmanificient commented
hmm :sweat_smile: 
> nixpkgs-manual: 
Package is missing maintainers.
If the package is using runCommand please make sure to inherit or list one or more maintainers.

2024-07-27 13:09 UTC, gador commented
> hmm 😅
> 
> > nixpkgs-manual:
> > Package is missing maintainers.
> > If the package is using runCommand please make sure to inherit or list one or more maintainers.

I'm not sure why this even rebuilt `nixpkgs-manual`. This shouldn't have anything to do with these 3 new packages.

On another note: Could you change the license to `lgpl3Only` for `gstools`? (I assume that should be the correct license)

2024-07-27 13:10 UTC, Sigmanificient commented
@gador done

2024-07-27 13:25 UTC, gador commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 325617` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
12 packages built:
</summary>
<ul>
<li>python311Packages.gstools</li>
<li>python311Packages.gstools.dist</li>
<li>python311Packages.hankel</li>
<li>python311Packages.hankel.dist</li>
<li>python311Packages.pyevtk</li>
<li>python311Packages.pyevtk.dist</li>
<li>python312Packages.gstools</li>
<li>python312Packages.gstools.dist</li>
<li>python312Packages.hankel</li>
<li>python312Packages.hankel.dist</li>
<li>python312Packages.pyevtk</li>
<li>python312Packages.pyevtk.dist</li>
</ul>
</details>

2024-07-27 14:31 UTC, merged