azuki: init at 1.21
NixOS/nixpkgs pull request #325611
Opened 2024-07-08 18:22 UTC by nyadiia

## Description of changes

azuki is a monospace handwritten font with a few variants ( proportional, without emoji, and bold )
[azukifont.com/font/azuki.html](http://azukifont.com/font/azuki.html)

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-15 08:17 UTC, Aleksanaa commented on pkgs/by-name/az/azuki-b/package.nix
> +    url = "https://azukifont.com/font/azukifont${downloadVersion}.zip";
They are all from the same source and installing the same files? If it’s not big, there’s actually no need to unpack it.

2024-07-15 08:17 UTC, Aleksanaa commented on pkgs/by-name/az/azuki-b/package.nix
> +    description = "Azuki Monospace Font Bold with Emoji";
missing `license`

2024-07-15 08:17 UTC, Aleksanaa commented on pkgs/by-name/az/azuki-b/package.nix
> +  meta = with lib; {
Better to avoid `with lib`

2024-07-16 14:59 UTC, nyadiia commented
rewrote this package, fixing the different version across all variations by just using the date of the latest one. all variations have been put into the same azuki package. license is unfree because the [terms of use on the site](https://azukifont.com/kiyaku.html) says no redistribution.

2024-07-16 15:09 UTC, nyadiia commented on pkgs/by-name/az/azuki/package.nix
> +    lib.maintainers = with lib.maintainers; [ nyadiia ];
i'm not using `with lib;` at the beginning ( may add it back tho i don't see a huge issue with it )

2024-07-16 15:20 UTC, nyadiia commented
actually i am going to use `with lib;` i don't see an issue with it and it makes it look far nicer

2024-07-16 15:27 UTC, nyadiia commented
ok now things should be good :)

2024-07-16 15:35 UTC, remexre approved these changes

2024-08-02 06:06 UTC, tomodachi94 requested changes
A bit of pedantry, but otherwise this looks good.

2024-08-07 05:30 UTC, tomodachi94 approved these changes
Lgtm. :heart:

2024-09-07 04:16 UTC, remexre approved these changes

2024-10-04 23:43 UTC, merged

2024-10-04 23:44 UTC, tomodachi94 commented
Merged, thank you for your patience 💖

2024-10-05 00:06 UTC, nyadiia commented
thank you so much! <3