rana: init at 0.5.4
NixOS/nixpkgs pull request #325911
Opened 2024-07-09 18:46 UTC by jigglycrumb

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-09 19:02 UTC, ocfox commented on pkgs/top-level/all-packages.nix
> +
```suggestion
```

2024-07-09 19:02 UTC, ocfox commented on pkgs/by-name/ra/rana/default.nix
pkgs/by-name/ra/rana/package.nix

2024-07-09 19:04 UTC, ocfox commented
You can test it by run 'nix run .#rana' in your branch.

2024-07-09 19:10 UTC, ocfox commented
Not needed to callPackage if use by-name, remove it.

2024-07-09 19:13 UTC, jigglycrumb commented
> nix run .#rana

Done, this works for me :+1:

2024-07-09 19:18 UTC, ocfox commented
And don't forget to remove useless commits, only need `add maintainer` and `init`.

2024-07-09 19:42 UTC, jigglycrumb commented
@ocfox Thank you for your help so far, this was a great first experience with this repo! I will remove the useless commits tomorrow - I have to jump out now for today, and I need some peer help to actually do it (not experienced with rebase and scared to break things :sweat_smile:)

Looking forward to get this merged :grin:

2024-07-09 19:45 UTC, ocfox commented
It's okay. I'm glad to help you. Be assured to use force push.

2024-07-10 15:42 UTC, ocfox requested changes

2024-07-10 15:42 UTC, ocfox commented on pkgs/by-name/ra/rana/package.nix
> +    repo = pname;
```suggestion
    repo = "rana";
```

2024-07-10 15:42 UTC, ocfox commented on pkgs/by-name/ra/rana/package.nix
> +  };
```suggestion
    mainProgram = "rana";
  };
```

2024-07-10 15:42 UTC, ocfox commented on pkgs/by-name/ra/rana/package.nix
> +{ lib, fetchFromGitHub, rustPlatform }:
Try use `nixfmt-rfc-style` format.

2024-07-10 17:02 UTC, ocfox commented
Result of `nixpkgs-review pr 325911` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rana</li>
  </ul>
</details>

2024-07-10 17:04 UTC, ocfox approved these changes

2024-07-10 17:33 UTC, jigglycrumb commented
@ocfox Should I remove the last commit again or is it fine like this? I guess you'd have to approve again if I do this.

2024-07-10 17:38 UTC, ocfox commented
I think no problem to keep it.

2024-07-15 08:14 UTC, jigglycrumb commented
Hello :) Just wondering if there is anything left that I should do? I don't want to block this without knowing 😅

2024-07-21 07:15 UTC, marcusramberg commented
> Hello :) Just wondering if there is anything left that I should do? I don't want to block this without knowing 😅 

Please squash your fix commit into the init one. Otherwise lgtm.

2024-07-24 12:42 UTC, Aleksanaa commented on pkgs/by-name/ra/rana/package.nix
> +  meta = with lib; {
Better to avoid `with lib`.

2024-08-19 18:17 UTC, jigglycrumb commented
Any news? :pray:

2024-09-25 20:26 UTC, jigglycrumb commented
Bump

2024-09-26 02:40 UTC, Aleksanaa commented
@ofborg build rana

2024-09-26 02:41 UTC, Aleksanaa commented
I'm very sorry for ignorance. Just rebuilding it to avoid rust 1.80 breakage

2024-09-26 07:43 UTC, merged

2024-09-26 13:29 UTC, jigglycrumb commented
No problem, thanks for merging!