liquibase-3.5.3 (update) adding PostgreSQL support
NixOS/nixpkgs pull request #32688
Opened 2017-12-15 01:14 UTC by nyarly

2017-12-15 03:59 UTC, Profpatsch requested changes
Have you tested calling postgres from a liquibase specification?

It should be possible to create an automated test for postgresql, see https://gitlab.techcultivation.org/sangha/sangha-deployment/blob/master/containers/helpers/postgres-template.nix#L31 for an example on how to run postgres inside the build.
If you don’t want to invest the time, a manual test would be enough as well for now.

2017-12-15 03:59 UTC, Profpatsch commented on pkgs/development/tools/database/liquibase/default.nix
> +, postgresSupport ? true, postgresql_jdbc ? null }:
Would rename to `postgresqlSupport` to keep the same naming.

2017-12-15 17:28 UTC, nyarly commented
@Profpatsch Do you have a liquibase changelog to work from? I've been trying to get this working for my own purposes (and if I can, I'll report it as manually tested), but as a result I don't have anything I can actually test *with*.

2017-12-15 17:54 UTC, Profpatsch commented
> Do you have a liquibase changelog to work from?

No, sorry. I’m not sure I even did use liquibase back then. :)

2017-12-17 02:23 UTC, grahamc commented
@GrahamcOfBorg eval

2017-12-18 20:01 UTC, nyarly commented
This has been manually tested now. I'd like to puzzle out how to do the automated testing... time limits forbid at the moment.

2017-12-19 03:28 UTC, Profpatsch approved these changes

2017-12-19 03:28 UTC, Profpatsch commented on pkgs/top-level/all-packages.nix
> +    };
nitpick: should be dedented by two spaces.

2019-05-21 00:25 UTC, aanderse commented
@nyarly are you able to continue with this PR?

2019-06-15 23:31 UTC, Ekleog commented
(triage) Closing for now due to lack of activity, @nyarly feel free to react if you want to continue working on this!

2019-06-15 23:31 UTC, closed without merging