ffmpeg: add lcms2 option
NixOS/nixpkgs pull request #326926
Opened 2024-07-13 21:19 UTC by al3xtjames

## Description of changes

FFmpeg 5.1 introduced optional support for ICC profiles using lcms2[^1]. Enable it by default in ffmpeg-full.

[^1]: https://github.com/FFmpeg/FFmpeg/commit/b9a25963f7232433c9370ac369fb668ac0d5cb53

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-13 23:42 UTC, jopejoe1 requested changes
Needs to Target staging

2024-07-14 01:29 UTC, Atemu commented
How can we test this?

Is this something that should perhaps be enabled in regular ffmpeg?

2024-07-14 03:02 UTC, al3xtjames commented
> Is this something that should perhaps be enabled in regular ffmpeg?

I'm not sure. Here's what I found in other distros:

- Arch: [not mentioned in the PKGBUILD](https://gitlab.archlinux.org/archlinux/packaging/packages/ffmpeg/-/blob/main/PKGBUILD?ref_type=heads), so presumably disabled by default; [ffmpeg-full in the AUR does have it enabled](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ffmpeg-full#n220)
- Debian: [not mentioned in the control files](https://packages.debian.org/bookworm/ffmpeg), so I'm guessing it's disabled by default; this is also the case on [Ubuntu](https://packages.ubuntu.com/noble/ffmpeg)- Gentoo: [has a USE flag to enable it](https://gitweb.gentoo.org/repo/gentoo.git/tree/media-video/ffmpeg/ffmpeg-7.0.1.ebuild), but doesn't seem to be enabled by default (I think, I'm not familiar with ebuilds)
- Fedora: [seems to be enabled by default](https://src.fedoraproject.org/rpms/ffmpeg/blob/rawhide/f/ffmpeg.spec#_50), excluding RHEL 9
- SUSE:

2024-07-14 07:59 UTC, al3xtjames commented
> How can we test this?

Here's an example using [`-flags2 icc_profiles`](https://trac.ffmpeg.org/ticket/9672#comment:8):

```
$ nix run 'github:al3xtjames/nixpkgs/ffmpeg-lcms2#ffmpeg-full' -- -filter_complex color=red:s=640x480 -frames 1 -q:v 1 -color_primaries bt709 -colorspace bt470bg -color_range pc -color_trc iec61966-2-1 -pix_fmt yuv420p -flags2 icc_profiles red.jpg
$ nix run 'nixpkgs#exiftool' -- red.jpg
ExifTool Version Number         : 12.84
File Name                       : red.jpg
Directory                       : .
File Size                       : 2.6 kB
File Modification Date/Time     : 2024:07:14 02:37:16-05:00
File Access Date/Time           : 2024:07:14 02:37:16-05:00
File Inode Change Date/Time     : 2024:07:14 02:37:16-05:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.02
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Profile CMM Type                : Little CMS
Profile Version                 : 4.4.0
Profile Class                   : Display Device Profile
Color Space Data                : RGB
Profile Connection Space        : XYZ
Profile Date Time               : 2024:07:14 07:37:16
Profile File Signature          : acsp
Primary Platform                : Apple Computer Inc.
CMM Flags                       : Not Embedded, Independent
Device Manufacturer             :
Device Model                    :
Device Attributes               : Reflective, Glossy, Positive, Color
Rendering Intent                : Perceptual
Connection Space Illuminant     : 0.9642 1 0.82491
Profile Creator                 : Little CMS
Profile ID                      : 0
Profile Description             : RGB built-in
Profile Copyright               : No copyright, use freely
Media White Point               : 0.9642 1 0.82491
Chromatic Adaptation            : 1.04788 0.02292 -0.05022 0.02959 0.99048 -0.01707 -0.00925 0.01508 0.75168
Red Matrix Column               : 0.43604 0.22249 0.01392
Blue Matrix Column              : 0.14305 0.06061 0.71391
Green Matrix Column             : 0.38512 0.7169 0.09706
Red Tone Reproduction Curve     : (Binary data 32 bytes, use -b option to extract)
Green Tone Reproduction Curve   : (Binary data 32 bytes, use -b option to extract)
Blue Tone Reproduction Curve    : (Binary data 32 bytes, use -b option to extract)
Chromaticity Channels           : 3
Chromaticity Colorant           : Unknown
Chromaticity Channel 1          : 0.64 0.33
Chromaticity Channel 2          : 0.3 0.60001
Chromaticity Channel 3          : 0.14999 0.06
Comment                         : Lavc60.31.102
Image Width                     : 640
Image Height                    : 480
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 640x480
Megapixels                      : 0.307
```

And without this change:
```
$ nix run 'nixpkgs#ffmpeg-full' -- -filter_complex color=red:s=640x480 -frames 1 -q:v 1 -color_primaries bt709 -colorspace bt470bg -color_range pc -color_trc iec61966-2-1 -pix_fmt yuv420p -flags2 icc_profiles red.jpg
$ nix run 'nixpkgs#exiftool' -- red.jpg
ExifTool Version Number         : 12.84
File Name                       : red.jpg
Directory                       : .
File Size                       : 2.0 kB
File Modification Date/Time     : 2024:07:14 00:26:58-05:00
File Access Date/Time           : 2024:07:14 00:29:07-05:00
File Inode Change Date/Time     : 2024:07:14 00:26:58-05:00
File Permissions                : -rw-r--r--
File Type                       : JPEG
File Type Extension             : jpg
MIME Type                       : image/jpeg
JFIF Version                    : 1.02
Resolution Unit                 : None
X Resolution                    : 1
Y Resolution                    : 1
Comment                         : Lavc60.31.102
Image Width                     : 640
Image Height                    : 480
Encoding Process                : Baseline DCT, Huffman coding
Bits Per Sample                 : 8
Color Components                : 3
Y Cb Cr Sub Sampling            : YCbCr4:2:0 (2 2)
Image Size                      : 640x480
Megapixels                      : 0.307
```

2024-07-14 10:01 UTC, Atemu commented
It looks like you accidentally mass-pinged a bunch of people, which are now subscribed
and getting notifications for everything in this pull request. Unfortunately, they
cannot be automatically unsubscribed from the issue (removing review request does not
unsubscribe), therefore development cannot continue in this pull request anymore.

Please open a new pull request with your changes, link back to this one and ping the
people actually involved in here over there.

In order to avoid this in the future, there are instructions for how to properly
rebase between branches in our [contribution guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging).
Setting your pull request to draft prior to rebasing is strongly recommended.
In draft status, you can preview the list of people that are about to be requested
for review, which allows you to sidestep this issue.
This is not a bulletproof method though, as OfBorg still does review requests even on draft PRs.

2024-07-14 10:01 UTC, closed without merging