python312Packages.htmltools: init at 0.5.2
NixOS/nixpkgs pull request #326910
Opened 2024-07-13 20:36 UTC by Sigmanificient

## Description of changes

Fix:
- #325433

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-14 09:27 UTC, applePrincess requested changes

2024-07-14 09:27 UTC, applePrincess commented on pkgs/development/python-modules/htmltools/default.nix
> +  dependencies = [ typing-extensions ];
`packaging` is missing from dependencies.

2024-07-14 09:29 UTC, applePrincess commented on pkgs/development/python-modules/shiny/default.nix
> +    changelog = "https://github.com/py-shiny/py-shiny/blob/${src.rev}/CHANGELOG.md";
```suggestion
    changelog = "https://github.com/posit-dev/py-shiny/blob/${src.rev}/CHANGELOG.md";
```

2024-07-20 17:07 UTC, Sigmanificient commented on pkgs/development/python-modules/shiny/default.nix
> +    changelog = "https://github.com/py-shiny/py-shiny/blob/${src.rev}/CHANGELOG.md";
whoops, copy paste owner fail, i guess

2024-07-25 01:32 UTC, applePrincess commented
Since #321316 has been merged, could you remove htmltools related commit?

2024-07-25 12:24 UTC, Sigmanificient commented
oh well that pr was mislabeled :sweat_smile:

2024-07-28 14:10 UTC, applePrincess commented
Result of `nixpkgs-review pr 326910` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.shiny</li>
    <li>python311Packages.shiny.dist</li>
    <li>python312Packages.shiny</li>
    <li>python312Packages.shiny.dist</li>
  </ul>
</details>

2024-07-28 14:13 UTC, applePrincess approved these changes

2024-07-30 03:48 UTC, natsukium commented on pkgs/development/python-modules/shiny/default.nix
> +    changelog = "https://github.com/posit-dev/py-shiny/py-shiny/blob/${src.rev}/CHANGELOG.md";
```suggestion
    changelog = "https://github.com/posit-dev/py-shiny/blob/${src.rev}/CHANGELOG.md";
```

2024-07-30 03:48 UTC, natsukium commented on pkgs/development/python-modules/shiny/default.nix
> +    pytest-cov
```suggestion
```
Please remove the coverage-related package.

2024-07-30 03:48 UTC, natsukium commented on pkgs/development/python-modules/shiny/default.nix
> +  pytest-cov,
```suggestion
```

2024-07-31 03:05 UTC, natsukium approved these changes
LGTM, thanks.

2024-07-31 03:05 UTC, merged