python312Packages.jianpu-ly: init at 1.801
NixOS/nixpkgs pull request #328894
Opened 2024-07-21 12:23 UTC by ifurther

## Description of changes

Add jianpu-ly application

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-03 01:20 UTC, Sigmanificient requested changes

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +  format = "setuptools";
- #253154
```suggestion
  pyproject = true;
```

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +
```suggestion

  build-system = [ setuptools ];

```

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +    sha256 = "sha256-piK9Ym94cKdaHGz/ogX7ylyAF1ww0jCdRXnHN6lu2MI=";
- #325892

```suggestion
    hash = "sha256-piK9Ym94cKdaHGz/ogX7ylyAF1ww0jCdRXnHN6lu2MI=";
```

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +  nativeBuildInputs = [ lilypond ];
```suggestion
  dependencies = [ lilypond ];
```

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +  meta = with lib; {
- #208242
```suggestion
  meta = {
```

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +    maintainers = with maintainers; [ ifurther ];
```suggestion
    license = lib.licenses.asl20;
    maintainers = with lib.maintainers; [ ifurther ];
```

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +    platforms = platforms.all;
Uneeded for `buildPythonPackage`
```suggestion
```

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +  # no tests in shipped with upstream
nit
```suggestion
  pythonImportsCheck = [ "jianpu_ly" ];

  # no tests in shipped with upstream
```

2024-08-03 01:20 UTC, Sigmanificient commented on pkgs/development/python-modules/jianpu-ly/default.nix
> +    description = "jianpu-ly is a Python program that assists with printing jianpu";
*`meta.description` must: [...] Not start with the package name. *
> https://github.com/NixOS/nixpkgs/tree/master/pkgs#meta-attributes

```suggestion
    description = "Assists with printing jianpu";
```

2024-08-13 09:05 UTC, SuperSandro2000 commented on pkgs/development/python-modules/check-manifest/default.nix
This got already fixed in #325567 Please rebase your branch on master

2024-08-13 09:05 UTC, SuperSandro2000 commented on pkgs/development/python-modules/scalene/default.nix
> +  ] ++ lib.optionals stdenv.hostPlatform.isDarwin [ "nvidia-ml-py" ];
```suggestion
  ] ++ lib.optionals (!stdenv.hostPlatform.isLinux) [ "nvidia-ml-py" ];

```

2024-11-22 11:39 UTC, FliegendeWurst approved these changes

2024-11-22 13:32 UTC, merged