google-cloud-speech: init at 0.30.0
NixOS/nixpkgs pull request #32890
Opened 2017-12-20 12:25 UTC by vanschelven

###### Motivation for this change

Google Cloud Speech API enables developers to convert audio to text;
The provided package is the Python client.

###### Things done

pkgs/development/python-modules/google_cloud_speech/default.nix is the actual goal of the present commit; the other packages are required dependencies.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2017-12-20 12:55 UTC, FRidh requested changes
Note the comments I made apply to all expressions.

2017-12-20 12:55 UTC, FRidh commented on pkgs/development/python-modules/google_api_core/default.nix
> +  buildInputs = [ setuptools mock pytest ];
checkInputs

2017-12-20 12:55 UTC, FRidh commented on pkgs/development/python-modules/google_api_core/default.nix
> +    license = "apache";
which specifically? Use `lib.licences`

2017-12-20 12:55 UTC, FRidh commented on pkgs/development/python-modules/google_api_core/default.nix
> +  };
maintainer?

2017-12-20 12:55 UTC, FRidh commented on pkgs/development/python-modules/google_api_core/default.nix
> +  };
homepage?

2017-12-20 12:55 UTC, FRidh commented on pkgs/development/python-modules/google_api_core/default.nix
> +  name = "google-api-core-${version}";
```
pname = "google-api-core";
version = "0.1.2";
```
drop `name`

2017-12-20 12:55 UTC, FRidh commented on pkgs/development/python-modules/google_auth/default.nix
> +  version = "1.2.1";
same here

2017-12-20 12:55 UTC, FRidh commented on pkgs/development/python-modules/google_auth/default.nix
> +  buildInputs = [ pytest mock oauth2client flask requests urllib3 pytest-localserver ];
checkInputs

2017-12-20 12:55 UTC, FRidh commented on pkgs/development/python-modules/google_auth/default.nix
> +    license = "apache";
use `lib.licenses`

2017-12-20 12:56 UTC, FRidh commented
Also, a commit per expression is needed.

2017-12-28 10:05 UTC, vanschelven commented
@FRidh anything I can do to get this PR accepted? I've implemented the changes you requested. I'd rather have it merged now that it still has no conflicts with master.

2017-12-28 10:56 UTC, merged