project_lemonlime: init at 0.3.5
NixOS/nixpkgs pull request #329904
Opened 2024-07-25 13:30 UTC by Sigmanificient

## Description of changes

Fixes:
- #329546

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-26 11:16 UTC, Sigmanificient commented
Well we cant really control anything outside the package, but the compiler path would not change unless the user changes its version

2024-07-26 11:26 UTC, Sigmanificient commented
I dont understand what you are referring by `wrap shell`

2024-08-20 00:52 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4434

2024-08-21 00:56 UTC, Pandapip1 requested changes
Your fixes isn't written in a way that GitHub recognizes it. It should be written:

Fixes https://github.com/NixOS/nixpkgs/issues/329546

The filename, like the pname, should be hyphenated instead of underscored.

2024-08-21 00:56 UTC, Pandapip1 commented on pkgs/by-name/pr/project_lemonlime/package.nix
> +  pname = "project_lemonlime";
```suggestion
  pname = "project-lemonlime";
```

As per the naming guidelines, hyphens should be used instead of underscores.

2024-08-21 00:56 UTC, Pandapip1 commented on pkgs/by-name/pr/project_lemonlime/package.nix
> +  meta = {
Missing `platforms`?

2024-08-21 00:58 UTC, Sigmanificient commented on pkgs/by-name/pr/project_lemonlime/package.nix
> +  meta = {
No sure what to set

2024-08-21 01:07 UTC, Pandapip1 approved these changes
LGTM. I don't think a `meta.homepage` is required?

2024-08-22 09:29 UTC, SuperSandro2000 commented on pkgs/by-name/pr/project-lemonlime/package.nix
> +  meta = {
homepage is missing

2024-09-04 12:22 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1942

2024-09-05 01:44 UTC, Aleksanaa commented on pkgs/by-name/pr/project-lemonlime/package.nix
> +    qt5.wrapQtAppsHook
Qt 6 should be preferred if there are no issues with it. Upstream provided https://github.com/Project-LemonLime/Project_LemonLime/blob/master/CMakeLists.txt#L47

(Also qt6.qtwayland!)

2024-10-06 08:28 UTC, closed without merging