[WIP] linux-steam-integration: init at 0.7.2
NixOS/nixpkgs pull request #33051
Opened 2017-12-25 14:04 UTC by etu

###### Motivation for this change
[Linux Steam Integration](https://github.com/solus-project/linux-steam-integration) is the foundation of the work that the Solus Project have done to get steam to "work better" on their OS. It seems like they solve a lot of problems with their wrappers and things.

Things to solve:
 - [ ] 32bit build

Here's the script used by archlinux to see how they build it both as 64 and 32 bit. https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=linux-steam-integration

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2017-12-25 15:29 UTC, FRidh commented on pkgs/games/steam/linux-steam-integration.nix
> +  zenityBinPath = "${stdenv.lib.makeBinPath (with pkgs; [ zenity ])}/zenity";
these two can go in a let expression since they're not actual arguments for `mkDerivation`

2017-12-27 12:08 UTC, etu commented
Since I got the 32bit parts  to build I think this PR is ready. It at least works on my 64bit systems and don't complain about missing 32bit libraries when running lsi-steam.

2017-12-28 20:10 UTC, etu commented
cc @jagajaga, any opinions on this?

2017-12-28 20:22 UTC, jagajaga commented
Cc @abbradar

2018-01-03 20:49 UTC, adisbladis requested changes

2018-01-03 20:49 UTC, adisbladis commented on pkgs/games/steam/linux-steam-integration.nix
> +    platforms = platforms.linux;
Should be `platforms = [ "x86_64-linux" ];`. 
`stdenv.lib.platforms.linux` includes mips and arm arches where steam does not run.

2018-01-03 20:49 UTC, adisbladis commented on pkgs/games/steam/linux-steam-integration.nix
> +  buildInputs = [ pkgs.gtk3 libressl ];
It is better to take `gtk3` as an argument rather than using `gtk3` from the `pkgs` attribute set.

2018-01-03 23:30 UTC, merged