python3Packages.discum: init at 1.4.1
NixOS/nixpkgs pull request #330881
Opened 2024-07-29 15:20 UTC by jokatzke

## Description of changes

Add https://github.com/Merubokkusu/Discord-S.C.U.M

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
  - [x] with `--sandbox` flag
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-31 12:48 UTC, Sigmanificient requested changes

2024-07-31 13:08 UTC, Sigmanificient approved these changes

2024-08-06 05:07 UTC, gador commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 330881` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>python311Packages.discum</li>
<li>python311Packages.discum.dist</li>
<li>python312Packages.discum</li>
<li>python312Packages.discum.dist</li>
</ul>
</details>

2024-08-06 05:08 UTC, gador commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).

Result of `nixpkgs-review pr 330881` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
4 packages built:
</summary>
<ul>
<li>python311Packages.discum</li>
<li>python311Packages.discum.dist</li>
<li>python312Packages.discum</li>
<li>python312Packages.discum.dist</li>
</ul>
</details>

2024-08-06 05:08 UTC, gador approved these changes

2024-08-06 05:08 UTC, merged