certbot-dns-linode: init at 2.11.0
NixOS/nixpkgs pull request #331147
Opened 2024-07-30 19:40 UTC by chovine

## Description of changes

Add the [Linode DNS plugin for certbot](https://github.com/certbot/certbot/tree/master/certbot-dns-linode).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-07-31 12:18 UTC, Sigmanificient requested changes

2024-07-31 12:18 UTC, Sigmanificient commented on pkgs/development/python-modules/certbot-dns-linode/default.nix
> +
```suggestion
pyproject = true;
```

2024-07-31 12:18 UTC, Sigmanificient commented on pkgs/development/python-modules/certbot-dns-linode/default.nix
> +
```suggestion

buid-system = [ setuptools ];

```

2024-07-31 12:18 UTC, Sigmanificient commented on pkgs/development/python-modules/certbot-dns-linode/default.nix
> +  pythonPackages,
```suggestion
  pythonPackages,
  setuptools,
```

2024-07-31 12:18 UTC, Sigmanificient commented on pkgs/development/python-modules/certbot-dns-linode/default.nix
> +";
```suggestion
    description = "Linode DNS Authenticator plugin for Certbot";
```

2024-11-10 20:12 UTC, FliegendeWurst requested changes
Please squash commits into a single "python312Packages.certbot-dns-linode: init at 2.11.0"

2024-11-10 21:25 UTC, FliegendeWurst requested changes
Tests fail
```
==================================== ERRORS ====================================
_ ERROR collecting certbot-dns-linode/certbot_dns_linode/_internal/tests/dns_linode_test.py _
certbot_dns_linode/_internal/tests/dns_linode_test.py:11: in <module>
    from certbot.plugins import dns_test_common
/nix/store/mxsrq0lx57yfhcwx75268yaxacaifafk-python3.12-certbot-2.11.0/lib/python3.12/site-packages/certbot/plugins/dns_test_common.py:8: in <module>
    import josepy as jose
/nix/store/iimq2ascq1rq25pg2kin24c78ix2b9yh-python3.12-josepy-1.14.0/lib/python3.12/site-packages/josepy/__init__.py:40: in <module>
    from josepy.json_util import (
/nix/store/iimq2ascq1rq25pg2kin24c78ix2b9yh-python3.12-josepy-1.14.0/lib/python3.12/site-packages/josepy/json_util.py:26: in <module>
    from josepy import b64, errors, interfaces, util
/nix/store/iimq2ascq1rq25pg2kin24c78ix2b9yh-python3.12-josepy-1.14.0/lib/python3.12/site-packages/josepy/util.py:18: in <module>
    class ComparableX509:
/nix/store/iimq2ascq1rq25pg2kin24c78ix2b9yh-python3.12-josepy-1.14.0/lib/python3.12/site-packages/josepy/util.py:26: in ComparableX509
    def __init__(self, wrapped: Union[crypto.X509, crypto.X509Req]) -> None:
/nix/store/pll7q0yp0y9dkj90iv97q8dv045k9x8v-python3.12-cryptography-43.0.1/lib/python3.12/site-packages/cryptography/utils.py:70: in __getattr__
    warnings.warn(obj.message, obj.warning_class, stacklevel=2)
E   DeprecationWarning: CSR support in pyOpenSSL is deprecated. You should use the APIs in cryptography.
```

2024-11-29 07:41 UTC, FliegendeWurst approved these changes

2024-12-19 14:03 UTC, natsukium requested changes

2024-12-19 14:03 UTC, natsukium commented on pkgs/development/python-modules/certbot-dns-linode/default.nix
> +  propagatedBuildInputs = [
```suggestion
  dependencies = [
```

2024-12-19 14:03 UTC, natsukium commented on pkgs/development/python-modules/certbot-dns-linode/default.nix
> +    pythonPackages.dns-lexicon
```suggestion
    dns-lexicon
```

2024-12-19 14:03 UTC, natsukium commented on pkgs/development/python-modules/certbot-dns-linode/default.nix
> +  pythonPackages,
```suggestion
```

2025-02-28 09:32 UTC, FliegendeWurst commented
There is a merge conflict in `all-packages.nix`. Other than that I think this is ready to merge.

2025-04-07 20:03 UTC, closed without merging