vapoursynth-bestsource: init at R6
NixOS/nixpkgs pull request #331874
Opened 2024-08-03 00:04 UTC by snaakey

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-03 00:15 UTC, Sigmanificient requested changes

2024-08-03 00:15 UTC, Sigmanificient commented on pkgs/development/libraries/vapoursynth-bestsource/default.nix
> +stdenv.mkDerivation rec {
```suggestion
stdenv.mkDerivation (finalAttrs: {
```

2024-08-03 00:15 UTC, Sigmanificient commented on pkgs/development/libraries/vapoursynth-bestsource/default.nix
> +}
```suggestion
})
```

2024-08-03 00:15 UTC, Sigmanificient commented on pkgs/development/libraries/vapoursynth-bestsource/default.nix
> +  };
- #208242
```suggestion
  meta = {
    description = "Wrapper library around FFmpeg that ensures sample and frame accurate access to audio and video";
    homepage = "https://github.com/vapoursynth/bestsource";
    license = with lib.licenses; [
      mit
      wtfpl
      gpl2Plus
    ];
    maintainers = with lib.maintainers; [ snaki ];
  };
```

2024-08-03 00:15 UTC, Sigmanificient commented on pkgs/development/libraries/vapoursynth-bestsource/default.nix
> +    rev = version;
```suggestion
    rev = "refs/tags/${finalAttrs.version}";
```

2024-08-03 00:16 UTC, Sigmanificient commented
Can you please define your package within `pkgs/by-name/va/vapoursynth-bestsource/package.nix`?

2024-08-03 00:30 UTC, Sigmanificient requested changes

2024-08-03 00:30 UTC, Sigmanificient commented on pkgs/by-name/va/vapoursynth-bestsource/package.nix
> +  };
Oh, the `R` shouldn't be feature in the derivation, only within the tag. Not sure if version should be set to `6` or `6.0.0` though

```suggestion
  version = "6";

  outputs = [
    "out"
    "dev"
  ];

  src = fetchFromGitHub {
    fetchSubmodules = true;
    owner = "vapoursynth";
    repo = "bestsource";
    rev = "refs/tags/R${finalAttrs.version}";
    hash = "sha256-ICkdIomlkHUdK6kMeui45fvUn4OMxSrP8svB2IN+GCg=";
  };
```

2024-08-03 00:41 UTC, illdefined commented
Result of `nixpkgs-review pr 331874` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vapoursynth-bestsource</li>
    <li>vapoursynth-bestsource.dev</li>
  </ul>
</details>

2024-08-03 00:42 UTC, Sigmanificient approved these changes

2024-08-03 00:44 UTC, illdefined approved these changes

2024-08-05 09:48 UTC, illdefined commented
Result of `nixpkgs-review pr 331874` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vapoursynth-bestsource</li>
    <li>vapoursynth-bestsource.dev</li>
  </ul>
</details>

2024-08-05 09:49 UTC, illdefined commented on pkgs/by-name/va/vapoursynth-bestsource/package.nix
> +      --replace-fail "vapoursynth_dep.get_variable(pkgconfig: 'libdir')" "get_option('libdir')"
I personally like this approach a lot better than a patch.

2024-08-05 09:50 UTC, illdefined approved these changes

2024-11-13 10:52 UTC, FliegendeWurst approved these changes

2024-11-17 14:48 UTC, leona-ya commented on pkgs/by-name/va/vapoursynth-bestsource/package.nix
> +  meta = {
This should have a `platforms` attribute limited to x86_64, as this is (according to ofborg) the only supported platform for vapoursynth.

2024-11-17 16:07 UTC, leona-ya approved these changes

2024-11-17 16:07 UTC, merged