insta: 1.33.0 -> 1.40.0-unstable
NixOS/nixpkgs pull request #332299
Opened 2024-08-04 17:16 UTC by a-kenji

Updates insta to latest unstable release.
Insta vendored their lockfiles again, fixing: #317404.

Because it is not released yet, I have pulled from the unstable main for now.

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-04 20:13 UTC, oxalica requested changes

2024-08-04 20:13 UTC, oxalica commented on pkgs/development/tools/rust/cargo-insta/default.nix
> +    # rev = "refs/tags/${version}";
Leaving this in comment has no use for either Nix or human. I'd remove it. One can `git blame` to get its history anyway.

2024-08-04 20:13 UTC, oxalica commented on pkgs/development/tools/rust/cargo-insta/default.nix
> +  doCheck = false;
```suggestion
  # Requires dependency to `rustfmt` but does not matter for packaging.
  checkFlags = [ "--skip=utils::test_format_rust_expression" ];
```

2024-08-05 00:13 UTC, oxalica approved these changes
LGTM. Tested basic `cargo insta review`.

---

Result of `nixpkgs-review pr 332299` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cargo-insta</li>
  </ul>
</details>

2024-08-06 05:11 UTC, donovanglover commented
Let's wait a little since 1.40 is being [prepped for release](https://github.com/mitsuhiko/insta/commit/827277f13a8e65cb32db950ccdaaf2221efaabfe).

2024-08-23 10:35 UTC, a-kenji commented
@donovanglover 
How long does the prep take?

2024-08-24 17:45 UTC, donovanglover commented
Thanks for the ping. I'll go ahead and merge this and insta can be updated again when the new release comes out.

2024-08-24 18:00 UTC, donovanglover commented
Commit message should be `cargo-insta` so ofborg builds it. Could also use the latest commit if wanted.

2024-08-26 16:31 UTC, donovanglover approved these changes

2024-08-26 17:32 UTC, merged