nixos/httpd: add logging related options
NixOS/nixpkgs pull request #332935
Opened 2024-08-07 07:41 UTC by bbenno

## Description of changes

1. Add option `logLevel` to control the verbosity of the ErrorLog.
2. Change option `logFormat` to either accept the name of a predefined log format (combined, common, referer, agent, or none) or a custom log format string.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2025-12-27 23:40 UTC, shelvacu requested changes
`logLevel` option looks good

for `logFormat`, mixing enum-of-strings and arbitrary strings in the same option is not a good idea. If someone mistypes `logFormat = "aggent", then instead of a helpful error message at eval time, they get logs filled with "aggent".

Instead should use either `types.coercedTo types.attrTag` or have another option `customLogFormat` that's used when `logFormat = "custom"`

2025-12-27 23:40 UTC, shelvacu commented on nixos/modules/services/web-servers/apache-httpd/default.nix
> +    if
not a blocker: would be less confusing if the `logFormat = "none"` case was handled here along with everything else.

2025-12-29 16:41 UTC, bbenno commented
Thank you, @shelvacu, for the review and for highlighting this issue.

The point is addressed. `logFormat` is now restricted to a fixed enumeration, including `custom`, and a separate `customLogFormat` option is used for user-defined formats.

2025-12-31 02:58 UTC, shelvacu requested changes

2025-12-31 02:58 UTC, shelvacu commented on nixos/modules/services/web-servers/apache-httpd/default.nix
> +    ${optionalString (cfg.logFormat == "custom") "LogFormat \"${cfg.comstomLogFormat}\" custom"}
This needs some sort of escaping. As it is now if I set 

```nix
customLogFormat = ''The X-Forwarded-For header was "%{X-Forwarded-For}", and here's some other stuff in quotes: "%l %u %t"'';
```

it will produce a syntactically invalid config.

Sorry I didn't catch this on the first review.

2026-01-02 02:01 UTC, shelvacu approved these changes

2026-02-02 00:19 UTC, h7x4 approved these changes

2026-02-02 00:25 UTC, merged