visp: init at 3.6.0
NixOS/nixpkgs pull request #333473
Opened 2024-08-09 14:45 UTC by nim65s

## Description of changes

Visp is an open source visual servoing library: https://visp.inria.fr/

Nix support & CI was added upstream in https://github.com/lagadic/visp/pull/1416.
This PR is based on that work, plus darwin fixes.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-09 14:56 UTC, nim65s commented
Result of `nixpkgs-review pr 333473` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>visp</li>
  </ul>
</details>

2024-08-09 15:01 UTC, nim65s commented
Result of `nixpkgs-review pr 333473` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>visp</li>
  </ul>
</details>

2024-11-02 13:53 UTC, FliegendeWurst requested changes

2024-11-02 17:09 UTC, nim65s commented on pkgs/by-name/vi/visp/package.nix
> +      url = "https://github.com/lagadic/visp/pull/1310/commits/9ed0300507e13dddd83fd62a799f5039025ea44e.patch";
Why would we want that ? I think having the pull request reference is a good thing.

2024-11-02 17:10 UTC, nim65s commented on pkgs/by-name/vi/visp/package.nix
> +    rev = "v${finalAttrs.version}";
Why ?

2024-11-02 17:12 UTC, FliegendeWurst commented on pkgs/by-name/vi/visp/package.nix
> +      url = "https://github.com/lagadic/visp/pull/1310/commits/9ed0300507e13dddd83fd62a799f5039025ea44e.patch";
You can always include the PR in the comment above. I suppose it doesn't matter whether the url contains pull/xxx..

2024-11-02 17:13 UTC, FliegendeWurst commented on pkgs/by-name/vi/visp/package.nix
> +    rev = "v${finalAttrs.version}";
If there is a branch with the same name, the fetch would fail.

2024-11-18 17:48 UTC, FliegendeWurst approved these changes

2024-12-02 18:55 UTC, nim65s commented
@ofborg build visp

2024-12-21 15:49 UTC, merged