mp4fpsmod: init at 0.27
NixOS/nixpkgs pull request #333636
Opened 2024-08-10 09:10 UTC by makeding

## Description of changes

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-19 18:41 UTC, Sigmanificient requested changes

2024-08-19 18:41 UTC, Sigmanificient commented on pkgs/by-name/mp/mp4fpsmod/package.nix
> +}@args:
```suggestion
}:
```

2024-08-19 18:41 UTC, Sigmanificient commented on pkgs/by-name/mp/mp4fpsmod/package.nix
> +    sha256 = "sha256-54pkjlvLLi4pLlQA/l+v4Mx5HlloR6GiB2GP71A0x/g=";
- #325892
```suggestion
    hash = "sha256-54pkjlvLLi4pLlQA/l+v4Mx5HlloR6GiB2GP71A0x/g=";
```

2024-08-19 18:41 UTC, Sigmanificient commented on pkgs/by-name/mp/mp4fpsmod/package.nix
> +  meta = with lib; {
- #208242

```suggestion
  meta = {
```

2024-08-20 01:37 UTC, Sigmanificient commented
Missing a
`platforms = platforms.all;` -> `platforms = lib.platforms.all;`

2024-08-20 02:11 UTC, makeding commented
Thanks for the guidance of my code.
:)

2024-11-02 14:53 UTC, FliegendeWurst requested changes

2024-11-02 14:53 UTC, FliegendeWurst commented on pkgs/by-name/mp/mp4fpsmod/package.nix
> +      # All files are distributed as Public Domain, except for the followings:
```suggestion
      # All files are distributed as Public Domain, except for the followings:
      publicDomain
```

2024-11-02 14:53 UTC, FliegendeWurst commented on pkgs/by-name/mp/mp4fpsmod/package.nix
> +    maintainers = with lib.maintainers; [ huggy ];
```suggestion
    maintainers = with lib.maintainers; [ huggy ];
    mainProgram = "mp4fpsmod";
```

2024-11-02 15:29 UTC, FliegendeWurst approved these changes

2024-12-15 18:13 UTC, FliegendeWurst commented
Please squash all package-related commits.

2025-01-01 14:47 UTC, Sigmanificient commented on pkgs/by-name/mp/mp4fpsmod/package.nix
> +    homepage = "https://github.com/nu774/mp4fpsmod";
```suggestion
    interhit (src.meta) homepage;
```

2025-01-01 15:43 UTC, Guanran928 approved these changes
built on x86_64-linux: `/nix/store/sz0wwccxpqkzdvcs6gr705558b9yk6r0-mp4fpsmod-0.27-unstable-2023-12-30`

2025-01-03 10:28 UTC, FliegendeWurst commented on pkgs/by-name/mp/mp4fpsmod/package.nix
> +    platforms = platforms.all;
```suggestion
    platforms = platforms.unix;
```
Does not cross-compile to Windows: `error: #error Please define `_WIN32_WINNT` to at least Windows 7.`

2025-01-03 10:37 UTC, FliegendeWurst approved these changes

2025-01-28 21:28 UTC, merged