go-outline: init at 20170804-9e9d089
NixOS/nixpkgs pull request #33428
Opened 2018-01-04 18:09 UTC by vdemeester

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

###### Motivation for this change

`go-outline` is an utility to extract JSON representation of declarations from a Go source file. Mainly used by `vsdcode` and other editor (with go support).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-02-13 18:13 UTC, nlewo requested changes
Can you also rebase it?
Otherwise, LGTM

2018-02-13 18:13 UTC, nlewo commented on pkgs/development/tools/go-outline/default.nix
> +  src = fetchgit {
Can you use fetchFromGitHub?
https://nixos.org/nixpkgs/manual/#sec-sources

2018-02-14 06:42 UTC, vdemeester commented
@nlewo updated 😉

2018-02-14 07:47 UTC, nlewo commented
@GrahamcOfBorg build go-outline

2018-02-14 07:47 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.33428&attempt_id=1cfbf06c-6c8c-47e1-93ef-36674549acb1)

<details><summary>Partial log (click to expand)</summary><p>

```
strip is /nix/store/5qj61lcvzlap87rf6blvf8p577d482bv-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/hqr47kfl1dxr4bpj1c71ldgfn6ga6335-go-outline-unstable-2017-08-04-bin/bin
patching script interpreter paths in /nix/store/hqr47kfl1dxr4bpj1c71ldgfn6ga6335-go-outline-unstable-2017-08-04-bin
checking for references to /build in /nix/store/hqr47kfl1dxr4bpj1c71ldgfn6ga6335-go-outline-unstable-2017-08-04-bin...
cannot find section .dynamic
shrinking RPATHs of ELF executables and libraries in /nix/store/023zay2ic3xxcy7wg0j45wppiw743lbh-go-outline-unstable-2017-08-04
strip is /nix/store/5qj61lcvzlap87rf6blvf8p577d482bv-binutils-2.28.1/bin/strip
patching script interpreter paths in /nix/store/023zay2ic3xxcy7wg0j45wppiw743lbh-go-outline-unstable-2017-08-04
checking for references to /build in /nix/store/023zay2ic3xxcy7wg0j45wppiw743lbh-go-outline-unstable-2017-08-04...
/nix/store/hqr47kfl1dxr4bpj1c71ldgfn6ga6335-go-outline-unstable-2017-08-04-bin
```
</p></details>

2018-02-14 07:47 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.33428&attempt_id=a0abbed1-7cd3-4779-9160-34d6f7cd5442)

<details><summary>Partial log (click to expand)</summary><p>

```
strip is /nix/store/xmpjypwjmp2qi1chs5kr0hacnh161ls4-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/9f4crcdlh98dh0cr6nzk726dyi8nwds4-go-outline-unstable-2017-08-04-bin/bin
patching script interpreter paths in /nix/store/9f4crcdlh98dh0cr6nzk726dyi8nwds4-go-outline-unstable-2017-08-04-bin
checking for references to /build in /nix/store/9f4crcdlh98dh0cr6nzk726dyi8nwds4-go-outline-unstable-2017-08-04-bin...
cannot find section .dynamic
shrinking RPATHs of ELF executables and libraries in /nix/store/wvpjnh7ymlx0qdigzwsrqlj0g8pk3v36-go-outline-unstable-2017-08-04
strip is /nix/store/xmpjypwjmp2qi1chs5kr0hacnh161ls4-binutils-2.28.1/bin/strip
patching script interpreter paths in /nix/store/wvpjnh7ymlx0qdigzwsrqlj0g8pk3v36-go-outline-unstable-2017-08-04
checking for references to /build in /nix/store/wvpjnh7ymlx0qdigzwsrqlj0g8pk3v36-go-outline-unstable-2017-08-04...
/nix/store/9f4crcdlh98dh0cr6nzk726dyi8nwds4-go-outline-unstable-2017-08-04-bin
```
</p></details>

2018-02-14 07:55 UTC, merged

2018-02-14 07:55 UTC, nlewo commented
Thanks