iamb: 0.0.9 -> 0.0.9-unstable-2024-08-15
NixOS/nixpkgs pull request #334910
Opened 2024-08-15 17:30 UTC by aktaboot

## Description of changes

Fixes iamb failing to build

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-20 05:19 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4436

2024-08-20 05:33 UTC, Nanotwerp approved these changes
LGTM! Tested with `nix repl`:

```
nix-repl> :b inputs.test.legacyPackages.x86_64-linux.iamb

This derivation produced the following outputs:
  out -> /nix/store/23c6lczn83qhcggi58qccb62c5aq25kn-iamb-0.0.9-unstable-2024-08-15
```

2024-08-21 07:22 UTC, a-kenji commented
There has been a release now:  #336278

2024-08-21 07:37 UTC, Nanotwerp requested changes
Version [`0.0.10`](https://github.com/ulyssa/iamb/releases/tag/v0.0.10) of `iamb` has just been released, so let's bump it to that.

2024-08-21 07:37 UTC, Nanotwerp commented on pkgs/applications/networking/instant-messengers/iamb/default.nix
> +  version = "0.0.9-unstable-2024-08-15";
```suggestion
  version = "0.0.10";
```

2024-08-21 07:37 UTC, Nanotwerp commented on pkgs/applications/networking/instant-messengers/iamb/default.nix
> +    rev = "54cb7991be526e2b8cd45e0a5b7cdb4a6d2e310b";
```suggestion
    rev = "v${version}";
```

2024-08-21 07:37 UTC, Nanotwerp commented on pkgs/applications/networking/instant-messengers/iamb/default.nix
> +    hash = "sha256-CepMojqLh0VUnHkagMKGHnEJfA8/EIoGBVN2rRNyFko=";
```suggestion
    hash = "sha256-cjBSWUBgfwdLnpneJ5XW2TdOFkNc+Rc/wyUp9arZzwg=";
```

2024-08-21 07:37 UTC, Nanotwerp commented on pkgs/applications/networking/instant-messengers/iamb/default.nix
> +  cargoHash = "sha256-MBi6R/hyIvPvTet4IohgFWgRZQQTnxuS2JV3kfqxoyA=";
```suggestion
  cargoHash = "sha256-a5y8nNFixOxJPNDOzvFFRqVrY2jsirCud2ZJJ8OvRhQ=";
```

2024-08-21 14:48 UTC, meain commented
https://github.com/NixOS/nixpkgs/pull/336278 might be a better option.

2024-08-21 20:08 UTC, Nanotwerp commented
#336278 has been merged!

2024-08-21 22:24 UTC, closed without merging