lib.systems.doubles: add aarch64-windows double
NixOS/nixpkgs pull request #335067
Opened 2024-08-16 09:09 UTC by getchoo

## Description of changes

This introduces initial support for cross compiling to Windows on Arm in nixpkgs

It adds a new example system (and `pkgsCross` target) in `ucrtAarch64`. It is modeled after MSYS2's CLANGARM64 [environment](https://www.msys2.org/docs/environments/#overview), which is based on LLVM. Windows-specific fixes for a few LLVM packages have been applied due to this

Currently `stdenv.cc` builds but doesn't seem to work all too well -- `hello` errors out early, reporting `C compiler cannot create executables`. Help would be appreciated here!

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-16 09:09 UTC, getchoo commented
![image](https://github.com/user-attachments/assets/194b92b7-b882-40ee-a862-de475ede395f)

2024-08-16 10:49 UTC, alyssais requested changes, later dismissed
Very nice.  Thanks for keeping the commits so small and easy to read!

2024-08-16 10:49 UTC, alyssais commented on lib/tests/systems.nix
> +  testwindows = mseteq windows [ "i686-cygwin" "x86_64-cygwin" "i686-windows" "x86_64-windows" "aarch64-windows" ];
Please keep these alphabetical.

2024-08-16 21:39 UTC, getchoo commented
Resolved a merge conflict from #334470

2024-11-06 22:32 UTC, Ericson2314 commented
Oh very cool!

2024-11-07 15:05 UTC, Ericson2314 approved these changes
Fantastic work!!

2024-11-07 15:07 UTC, merged

2024-11-08 04:02 UTC, HurricanePootis commented
@getchoo awesome project