python312Packages.genson: init at 1.3.0
NixOS/nixpkgs pull request #335221
Opened 2024-08-16 20:54 UTC by Tochiaha

Release: https://github.com/wolverdude/GenSON/releases/tag/v1.3.0

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-16 21:08 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4416

2024-08-17 10:02 UTC, natsukium commented on pkgs/development/python-modules/genson/default.nix
> +  doCheck = false;
`schema` exists [here](https://github.com/wolverdude/GenSON/tree/v1.3.0/genson), so if it is not found, it is probably not packaged correctly.

2025-01-17 19:08 UTC, Tochiaha commented on pkgs/development/python-modules/genson/default.nix
> +  doCheck = false;
genson.schema is not in the setup tools so sourcing from python repo for better result.

2025-01-17 20:36 UTC, SuperSandro2000 commented on pkgs/development/python-modules/genson/default.nix
> +  ];
```suggestion
  disabledTests = [
    "not test_no_input"
  ];
```

2025-01-17 20:36 UTC, SuperSandro2000 commented on pkgs/development/python-modules/genson/default.nix
> +    coverage
```suggestion
```
please patch out that we need this

2025-01-17 20:43 UTC, Tochiaha commented on pkgs/development/python-modules/genson/default.nix
> +  ];
Thank you

2025-01-18 05:59 UTC, Tochiaha commented on pkgs/development/python-modules/genson/default.nix
> +  ];
Problem now solved/

2025-01-20 23:51 UTC, ethancedwards8 requested changes

2025-01-20 23:51 UTC, ethancedwards8 commented on pkgs/development/python-modules/genson/default.nix
> +  };
prefer fetchFromGitHub

2025-01-20 23:52 UTC, ethancedwards8 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 335221`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python312Packages.genson</li>
    <li>python312Packages.genson.dist</li>
    <li>python313Packages.genson</li>
    <li>python313Packages.genson.dist</li>
  </ul>
</details>

2025-01-21 14:20 UTC, Tochiaha commented on pkgs/development/python-modules/genson/default.nix
> +  };
their is a bit of an issue with genson.schema module which was solved in PyPI so it becam best option for fetching code.

2025-01-21 14:24 UTC, merged