rain-bittorrent: init at 1.12.17
NixOS/nixpkgs pull request #335455
Opened 2024-08-17 20:31 UTC by justinrubek

## Description of changes

Added package https://github.com/cenkalti/rain

This package is a bittorrent client. It provides an RPC server that other applications can connect to in order to initiate a download as well as a command-line client in the same binary.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-23 19:59 UTC, FliegendeWurst commented on pkgs/by-name/ra/rain-bittorrent/package.nix
> +    description = "🌧 BitTorrent client and library in Go";
```suggestion
    description = "BitTorrent client and library in Go";
```

2024-10-23 19:59 UTC, FliegendeWurst commented on pkgs/by-name/ra/rain-bittorrent/package.nix
> +  version = "1.12.17";
```suggestion
  version = "1.13.0";
```
New version has been released by now.

2024-10-26 08:07 UTC, FliegendeWurst requested changes

2024-10-26 08:07 UTC, FliegendeWurst commented on pkgs/by-name/ra/rain-bittorrent/package.nix
> +  version = "1.30.0";
does not match the fetch below

2024-10-29 07:06 UTC, Aleksanaa commented on pkgs/by-name/ra/rain-bittorrent/package.nix
> +    rev = "v1.13.0";
```suggestion
    rev = "refs/tags/v${version}";
```

2024-10-29 07:06 UTC, Aleksanaa commented on pkgs/by-name/ra/rain-bittorrent/package.nix
> +    sha256 = "sha256-pz20vhr3idXja7wYIdVr1dosSpqYiQfeho66rqd718I=";
```suggestion
    hash = "sha256-pz20vhr3idXja7wYIdVr1dosSpqYiQfeho66rqd718I=";
```

2024-10-29 07:06 UTC, Aleksanaa commented on pkgs/by-name/ra/rain-bittorrent/package.nix
> +  };
```suggestion
  meta = {
    description = "BitTorrent client and library in Go";
    homepage = "https://github.com/cenkalti/rain";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ justinrubek ];
    mainProgram = "rain";
  };
```

2024-12-10 13:29 UTC, FliegendeWurst approved these changes

2024-12-12 09:24 UTC, Aleksanaa approved these changes

2024-12-12 09:24 UTC, merged