python3Packages.dragonmapper: init at 0.2.7
NixOS/nixpkgs pull request #335514
Opened 2024-08-18 05:23 UTC by ShamrockLee

## Description of changes

This pull request packages `pyhon3Packages.dragonmapper` and its dependencies.

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [X] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2025-02-16 22:00 UTC, ethancedwards8 requested changes
Small nitpicks. Otherwise LGTM.

2025-02-16 22:00 UTC, ethancedwards8 commented on pkgs/development/python-modules/dragonmapper/default.nix
> +
```suggestion
passthru.updateScript = nix-update-script { };
```

2025-02-16 22:00 UTC, ethancedwards8 commented on pkgs/development/python-modules/hanzidentifier/default.nix
> +
```suggestion
passthru.updateScript = nix-update-script { };
```

2025-02-16 22:00 UTC, ethancedwards8 commented on pkgs/development/python-modules/zhon/default.nix
> +
```suggestion
passthru.updateScript = nix-update-script { };
```

2025-02-16 22:18 UTC, kirillrdy commented on pkgs/development/python-modules/dragonmapper/default.nix
> +
this is not necessary as python modules all get default updateScript

2025-02-16 22:24 UTC, ethancedwards8 commented on pkgs/development/python-modules/dragonmapper/default.nix
> +
good to know. Thanks!

2025-03-01 18:52 UTC, ShamrockLee commented
@ethancedwards8 Thank you for reviewing and sorry for late reply. Your suggestions require rebasing this feature branch. I'll rebase and apply them.

2025-03-01 19:03 UTC, ShamrockLee commented
@ethancedwards8 I applied all your suggestions and built them again.

2025-03-01 19:09 UTC, ethancedwards8 approved these changes

2025-03-02 19:01 UTC, merged