update to freeoffice/softmaker-office 2024
NixOS/nixpkgs pull request #335639
Opened 2024-08-18 17:01 UTC by AlisterH

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://nixos.org/manual/nixpkgs/unstable/#ssec-nixos-tests-linking) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-18 17:04 UTC, AlisterH commented
With this change I am able to build freeoffice to /nix/store/9556bgzam9v1qrqk9gdsxihw5idg82lh-freeoffice-2024.1216 and softmaker-office to /nix/store/j4y6x5az601x17p32mcb214iwkv5g7xs-softmaker-office-2024.1214
To be honest, I'm not sure how to test actually running them, so if someone can tell me it would be much appreciated.

2024-08-18 17:16 UTC, AlisterH commented
> With this change I am able to build freeoffice to /nix/store/9556bgzam9v1qrqk9gdsxihw5idg82lh-freeoffice-2024.1216 and softmaker-office to /nix/store/j4y6x5az601x17p32mcb214iwkv5g7xs-softmaker-office-2024.1214 To be honest, I'm not sure how to test actually running them, so if someone can tell me it would be much appreciated.

OK, it was as simple as adding this to configuration.nix: `(callPackage /home/alister/devel/nixpkgs/pkgs/applications/office/softmaker/freeoffice.nix {})`
So it all seems to work OK.

2024-11-11 16:08 UTC, FliegendeWurst requested changes
Please make sure your commit message follows CONTRIBUTING.md

LGTM otherwise.

2024-11-12 03:11 UTC, AlisterH commented
Hopefully it's better now... unless I should be squeezing the description of the FreeOffice change into the summary too?

2024-11-12 13:32 UTC, FliegendeWurst commented
Ideally they'd be two commits, but this is fine too.

2024-12-03 13:48 UTC, FliegendeWurst commented on pkgs/applications/office/softmaker/freeoffice.nix
> +  hash = "sha256-F1Srm3/4UPifYls21MhjbpxSyLaT0gEVzEMQF0gIzi0=";
Perhaps they sneakily hot-fixed a bug.

2025-06-16 11:55 UTC, closed without merging