ayano: init at 0.0.10
NixOS/nixpkgs pull request #335919
Opened 2024-08-19 21:02 UTC by undefined-moe

## Description of changes

Added [ayano](https://github.com/taoky/ayano)

cc @taoky for review

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-20 06:04 UTC, s0me1newithhand7s commented
there is a problem with `meta.maintainers`. can you fix it?

2024-08-21 04:28 UTC, s0me1newithhand7s approved these changes
LGTM, ~~now waiting for OfBorg.~~ congrats!

2024-11-11 17:11 UTC, FliegendeWurst requested changes

2024-11-11 17:11 UTC, FliegendeWurst commented on pkgs/by-name/ay/ayano/package.nix
> +    license = "MIT";
```suggestion
    license = lib.licenses.mit;
```

2024-11-11 17:11 UTC, FliegendeWurst commented on pkgs/by-name/ay/ayano/package.nix
> +    description = "Follow nginx log, and find out bad guys!";
```suggestion
    description = "Shows clients eating most bandwidth based on web server logs";
```

2024-11-11 17:12 UTC, FliegendeWurst commented on maintainers/maintainer-list.nix
> +  taoky = {
This should be you, not the upstream developer..

2024-11-13 06:33 UTC, taoky commented on pkgs/by-name/ay/ayano/package.nix
> +  version = "0.0.10";
Hi, ayano released `0.1.0` version in Sep 30 and I believe that the version could be updated, with:

```
sha256 = "sha256-W6kwPedeOXZGAUjRmFfNIMJW3vpiRZkRIs1q+GsvJcM=";
```

and

```
vendorHash = "sha256-6C4RYatXcMZxqNiw6nIs3dEdro2S2vL8F8c+t5QeXUs=";
```

Also ayano now requires Go 1.23, though it does not look like an issue in unstable ([as it already uses 1.23 now](https://github.com/NixOS/nixpkgs/blob/081cc2c431912460a96f4b34c3dd9f54eec9597c/pkgs/top-level/all-packages.nix#L11433)).

2026-01-02 16:17 UTC, marcin-serwin commented
This PR is packaging an outdated version and the reported problems were not addressed for over a year. I'll close it now but feel free to reopen or create a new PR if you still want to package this.

2026-01-02 16:17 UTC, closed without merging