siyuan: add desktop entry & icon, enable wayland ime
NixOS/nixpkgs pull request #337021
Opened 2024-08-24 14:32 UTC by j4ger

## Description of changes

Added a desktop entry for siyuan-note, with the right icon;
Enabled Wayland IME support for stuff like fcitx.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-24 23:52 UTC, TomaSajt requested changes
There's no need to fetch the icon separately, since it's already fetched for `src` and copied into the build environment.

Also, using `pname` just for substitution is discouraged.

2024-08-24 23:52 UTC, TomaSajt commented on pkgs/by-name/si/siyuan/package.nix
> +stdenv.mkDerivation (finalAttrs: rec {
```suggestion
stdenv.mkDerivation (finalAttrs: {
```

2024-08-24 23:52 UTC, TomaSajt commented on pkgs/by-name/si/siyuan/package.nix
> +  '';
```suggestion
  postInstall = ''
    for i in 16 24 48 64 96 128 256 512; do
      mkdir -p $out/share/icons/hicolor/''${i}x''${i}/apps
      convert -background none -resize ''${i}x''${i} src/assets/icon.svg $out/share/icons/hicolor/''${i}x''${i}/apps/siyuan.png
    done
  '';
```

2024-08-24 23:54 UTC, TomaSajt commented on pkgs/by-name/si/siyuan/package.nix
> +stdenv.mkDerivation (finalAttrs: rec {
Note:
`finalAttrs` is used for recursion.
You can achieve recursion by just writing `finalAttrs.foobar` instead of just writing `foobar`.

2024-08-24 23:56 UTC, TomaSajt commented on pkgs/by-name/si/siyuan/package.nix
> +  '';
Also, maybe instead of putting this in `postInstall` you could just put this inside `installPhase` before `runHook postInstall`.

2024-08-25 00:02 UTC, TomaSajt commented on pkgs/by-name/si/siyuan/package.nix
> +  '';
```suggestion
  postInstall = ''
    install -Dm644 src/assets/icon.svg $out/share/icons/hicolor/scalable/apps/siyuan.svg
  '';
```

This is probably much easier, no need to generate pngs

2024-08-25 01:24 UTC, j4ger commented
Thanks for the corrections. I've made the changes and I'm wondering if I should make another commit to this branch, or am I supposed to amend the previous one and force push instead?

2024-08-25 01:48 UTC, TomaSajt commented
> Thanks for the corrections. I've made the changes and I'm wondering if I should make another commit to this branch, or am I supposed to amend the previous one and force push instead?


Having multiple commits in a nixpkgs PR is usually only needed when separating out different parts of the PR changes (e.g. one commit per package added).
Here, it's just some small changes to one file, so one commit should be optimal.

2024-08-25 13:06 UTC, TomaSajt commented on pkgs/by-name/si/siyuan/package.nix
> +    desktopName = "Siyuan";
```suggestion
    desktopName = "SiYuan";
```

Not very important, but upstream also capitalizes the letter Y.

Here's upstream's .desktop file:
```
[Desktop Entry]
Name=SiYuan
Exec=/opt/SiYuan/siyuan %U
Terminal=false
Type=Application
Icon=siyuan
StartupWMClass=SiYuan
Comment=Refactor your thinking
Categories=Utility;
```

If you want to, you can change the category / comment too. Those being different is not a huge deal, so it's fine to leave it as is IMO.

2024-08-25 13:52 UTC, j4ger commented
I just changed it to follow the upstream version, but you are right, it's not a big deal :D

2024-08-25 15:05 UTC, TomaSajt approved these changes
LGTM

2024-09-01 13:37 UTC, merged