lprobe: init at 0.1.3
NixOS/nixpkgs pull request #337174
Opened 2024-08-25 06:26 UTC by cageyv

https://github.com/fivexl/lprobe/releases/tag/v0.1.3

## Description of changes

- LProbe: A command-line tool to perform Local Health Check Probes inside Container Images (ECS, Docker)
- [Blog post with more info LProbe: A One-Stop-Shop Tool for Secure, Local Health Checks](https://fivexl.io/blog/lprobe/ )

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [ ] aarch64-darwin
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---
<img width="1173" alt="Screenshot 2024-08-25 at 13 25 11" src="https://github.com/user-attachments/assets/f9d32e5b-da53-460d-abe0-13373b76b612">

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-08-28 16:55 UTC, cageyv commented
@ofborg build

2024-08-28 17:02 UTC, cageyv commented
cc @wineee @vbgl @matteo-pacini
It works as expected. Screenshot attached. 

Long story short. Docker Desktop Debug uses NixOS. Lprobe is my default tool for Health Checks inside containers.

2024-08-29 06:58 UTC, matteo-pacini requested changes
Thank you for your first contribution,  I just left a few comments.

Happy to help / elaborate further if requested changes are not clear 🙏🏻

2024-08-29 06:58 UTC, matteo-pacini commented on maintainers/team-list.nix
> +
Do we need a team to maintain a single package?

I would expect a team for things like GNOME, GPU drivers, etc.

2024-08-29 06:58 UTC, matteo-pacini commented on maintainers/maintainer-list.nix
> +  };
This needs to be in a separate commit as per Nixpkgs convention, i.e. `maintainers: add cageyv`

2024-08-29 06:58 UTC, matteo-pacini commented on pkgs/tools/networking/lprobe/default.nix
> +}
This file is a duplicate, please remove it - `pkgs/by-name` should be preferred when creating new packages

2024-08-29 06:58 UTC, matteo-pacini commented on pkgs/by-name/lp/lprobe/package.nix
> +    sha256 = "sha256-q7lH0aLgQNM4jrrrq2ua+pt4/VknxlzKzDH5J4MwjfA=";
```suggestion
    hash = "sha256-q7lH0aLgQNM4jrrrq2ua+pt4/VknxlzKzDH5J4MwjfA=";
```

2024-08-29 06:58 UTC, matteo-pacini commented on pkgs/by-name/lp/lprobe/package.nix
> +  };
```suggestion
  meta = {
    description = "A command-line tool to perform Local Health Check Probes inside Container Images (ECS, Docker)";
    homepage = "https://github.com/fivexl/lprobe";
    license = lib.licenses.asl20;
    maintainers = with lib.maintainers; [ cageyv ];
    mainProgram = "lprobe";
  };
```
As suggested in: https://github.com/NixOS/nixpkgs/issues/208242

`platforms` is missing also, that should be added.

2024-09-01 15:25 UTC, cageyv commented
@matteo-pacini 

Thank you for your suggestions and guidelines. 🙏🏻

- team removed
- maintainer in separate commit 
- duplicate removed
- platforms added
- hash fixed

2024-09-04 11:58 UTC, matteo-pacini approved these changes
LGTM, thanks for addressing my comments

2024-09-04 16:05 UTC, wineee approved these changes

2024-09-05 01:37 UTC, merged