codelldb: init at 1.10.0
NixOS/nixpkgs pull request #337849
Opened 2024-08-28 03:13 UTC by Coosis

## Description of changes

The package contains a binary of codelldb, used for DAP protocol for debugging purposes. This was packaged in a similar way as Mason(A neovim package manager) did. This is solely for DAP protocol, for advanced usages, check out [vscode-extensions.vadimcn.vscode-lldb](https://search.nixos.org/packages?channel=24.05&show=vscode-extensions.vadimcn.vscode-lldb&from=0&size=50&sort=relevance&type=packages&query=vscode-lldb).

## Things done
Install the 1.10.0 version of codelldb, unzip to expose the binary, create a symlink for accessing the binary.
Homepage is at https://github.com/vadimcn/codelldb.

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2024-08-29 13:40 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4486

2024-09-03 21:31 UTC, SuperSandro2000 requested changes

2024-09-03 21:31 UTC, SuperSandro2000 commented on pkgs/by-name/co/codelldb/default.nix
> +  };
This must use an attrset instead of if else chains.

2024-09-03 21:31 UTC, SuperSandro2000 commented on pkgs/by-name/co/codelldb/default.nix
> +  lib = pkgs.lib;
```suggestion
```

2024-09-03 21:31 UTC, SuperSandro2000 commented on pkgs/by-name/co/codelldb/default.nix
> +  nativeBuildInputs = [ pkgs.unzip ];
```suggestion
  nativeBuildInputs = [ unzip ];
```

2024-09-03 21:31 UTC, SuperSandro2000 commented on pkgs/by-name/co/codelldb/default.nix
> +  src = pkgs.fetchurl {
```suggestion
  src = fetchurl {
```

2024-09-03 21:31 UTC, SuperSandro2000 commented on pkgs/by-name/co/codelldb/default.nix
> +    sha256 = binary.sha256;
```suggestion
    inherit (binary) url hash;
```

2024-09-03 21:31 UTC, SuperSandro2000 commented on pkgs/by-name/co/codelldb/default.nix
> +    ln -s $out/bin/extension/adapter/codelldb $out/bin/codelldb
The bin directory should not contain subdirectories

2024-09-04 01:25 UTC, Coosis commented
@SuperSandro2000 Some problems were already addressed by later commits, please check them, others I have changed the .nix accordingly, please let me know if more changes are needed

2024-09-12 04:32 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4567

2024-09-21 13:48 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4597

2024-09-26 09:20 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/why-is-it-taking-so-long-to-handle-pr-adding-package/52734/2

2024-09-28 02:46 UTC, closed without merging

2024-09-28 11:41 UTC, Coosis commented
visit `https://github.com/Coosis/coosis-nix` if you really need codelldb.