security-wrapper: Fix dependencies
NixOS/nixpkgs pull request #338432
Opened 2024-08-30 16:19 UTC by tu-maurice

## Description of changes

The wrapper program only needs the linuxHeaders during build, not as a dependency on the target system.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-04 05:12 UTC, Aleksanaa requested changes
I'm afraid this is not correct. See https://nixos.org/manual/nixpkgs/unstable/#ssec-stdenv-dependencies-overview

2024-09-04 06:46 UTC, Mic92 commented
I also think the current approach is correct and it cross-compiles fine. Is there any case where this fixed the build for you?

2024-09-04 18:08 UTC, tu-maurice commented
> I also think the current approach is correct and it cross-compiles fine. Is there any case where this fixed the build for you?

It's not a build issue. It's a dependency issue. Nix treats the linux headers like a library and enforces their presence at runtime, which is bogus. The security wrappers don't require the linux headers at runtime.

Maybe buildInputs is right, but linuxHeaders has to produce a "dev" output instead of an "out" output?

2024-09-07 19:57 UTC, Mic92 commented
> > I also think the current approach is correct and it cross-compiles fine. Is there any case where this fixed the build for you?
> 
> It's not a build issue. It's a dependency issue. Nix treats the linux headers like a library and enforces their presence at runtime, which is bogus. The security wrappers don't require the linux headers at runtime.
> 
> Maybe buildInputs is right, but linuxHeaders has to produce a "dev" output instead of an "out" output?

Is there any string reference inside the wrappers that may cause this top happen? This is not normal behavior of buildInputs. You can run `strings` on the binaries.

2024-09-08 13:24 UTC, tu-maurice commented
> Is there any string reference inside the wrappers that may cause this top happen? This is not normal behavior of buildInputs. You can run `strings` on the binaries.

The only store path strings shows is the binary that is wrapped, i.e. su in the case I am looking at.

The linux-headers are listed in nix-support/propagated-build-inputs though. Not sure if that's the offending reference or just meta information for the nix-store that there is a reference.

2024-09-08 15:21 UTC, Aleksanaa commented
> The linux-headers are listed in nix-support/propagated-build-inputs though. Not sure if that's the offending reference or just meta information for the nix-store that there is a reference.

It's probably because `security-wrapper` is `pkgsStatic` I guess. It's putting all `buildInputs` in `propagatedBuildInputs` to be able to find dependencies when linked as a static library. That's not the case here so you can safely delete `$out/nix-support/propagated-build-inputs`.

2024-09-15 12:02 UTC, tu-maurice commented
> It's probably because `security-wrapper` is `pkgsStatic` I guess. It's putting all `buildInputs` in `propagatedBuildInputs` to be able to find dependencies when linked as a static library.

Okay but neither security-wrapper nor linuxHeaders are libraries, so why should it be propagated? In other words why would propagating _every_ buildInput when building static sound like the right approach? I would image this generates a huge amount of wrong runtime depdencies. Does it not?

2024-09-15 21:54 UTC, Mic92 commented
> You are aware we don't need to hot patch this, right? There's no time pressure to fix this in nixpkgs by yesterday.

I think there is a misunderstanding here. This wouldn't be a hot patch but the proper solution to fix the propagation issue and reduce the runtime closure.

2024-09-15 22:14 UTC, tu-maurice commented
Let me maybe explain why I called the idea a hot patch and you can tell me where I misunderstood.

As far as I understand it @Aleksanaa 's suggestion to remove nix-support/propagated-build-inputs concerns only the security-wrappers derivation, which imho **is** a hot patch at best, since it just mitigates the issue here, but nowhere else. Unless only the security-wrappers ever use  pkgStatic, which I tend to doubt, there are probably more such incorrect runtime dependencies.

So imho there seems to be underlying issue here in which statically build derivations for linking reasons need to assume all buildInputs have to be propagated instead of just those that are libraries and propagated by all derivations instead of just those that are libraries.

So I am asking: does this all-inclusive propagation include all types of outputs or maybe just those named "out" or "lib", because then my earlier idea of linuxHeaders having only a dev output might not be so wrong after all, right?

2024-09-16 08:13 UTC, Aleksanaa commented
> Unless only the security-wrappers ever use pkgStatic, which I tend to doubt, there are probably more such incorrect runtime dependencies.

Yes, not a lot of packages make use of `pkgsStatic` by default, and it's somehow considered as exotic (which means, we may not guarantee it to work from time to time, because of our limited time, energy and infrastructure resources). One of exceptions is security-wrappers. It may be risky to dynamically link against glibc as we've dealt with some glibc vulnerabilities that occur at runtime due to over-design, such as dependency injection through environment variables, etc. (The other is binfmt emulation by qemu, as we want to make it pass through containers.)

As you can see, it's indeed not dynamic:

```
=> sudo ldd /run/wrappers/bin/gnome-keyring-daemon 
[sudo: authenticate] Password: 
        not a dynamic executable
```

> since it just mitigates the issue here, but nowhere else.

This is due to how static linking works. When a library is linked dynamically, its dependencies should be found by its elf header. In static linking, the runtime dependencies of a library must be provided in the build time, hence propagation works. One of the solutions would be not propagating dependencies for stuff that's obviously not a library. I'll take a look at it later.

2025-09-04 12:35 UTC, closed without merging