mrtrix3: init at 0.3.16
NixOS/nixpkgs pull request #33892
Opened 2018-01-15 08:06 UTC by ashgillman

###### Motivation for this change
Add MRTrix3

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-01-23 01:27 UTC, ashgillman commented
Not sure of an appropriate reviewer, perhaps @ttuegel as I am unsure I have correctly assigned qt dependencies as buildInputs vs. nativeBuildInputs.

2018-01-23 12:15 UTC, ttuegel requested changes

2018-01-23 12:15 UTC, ttuegel commented on pkgs/top-level/all-packages.nix
> +  mrtrix3 = callPackage ../applications/science/biology/mrtrix { };
You should use `qt56.callPackage` here instead of `callPackage`.

2018-01-23 12:15 UTC, ttuegel commented on pkgs/applications/science/biology/mrtrix/default.nix
> +    qt56.qmake
You can remove the `qt56.` prefix from `qmake`, `qtscript`, and `qtsvg`.

2018-01-23 12:15 UTC, ttuegel commented on pkgs/applications/science/biology/mrtrix/default.nix
> +    qt56.qtscript
`qmake` is a `nativeBuildInput` because it is a build tool, but `qtscript` is a runtime dependency that should go in `buildInputs`.

2018-01-24 05:17 UTC, ashgillman commented
Thanks for the review. I have made all suggested changes.

I also created a new category: science/imaging. If accepted, I will make a new PR to move science/biology/ants to science/imaging/ants also, as it is a more appropriate classification. I also have some other packages to contribute upstream that would belong there.

2018-06-11 06:58 UTC, 7c6f434c commented
Tried to merge — a strange build problem about `operator []`

2020-04-03 04:03 UTC, bcdarwin commented
`mrtrix` was added in 80292.

2020-04-06 05:32 UTC, ashgillman commented
Looks better to me, thanks @bcdarwin

2020-04-06 05:32 UTC, closed without merging