ente-auth: init at 3.1.3
NixOS/nixpkgs pull request #339059
Opened 2024-09-02 17:13 UTC by niklaskorz

## Description of changes

Closes #336291

I'm aware there already is an open PR at #333514 but this PR inits ente-auth as a from-source build.
The appimage wrapped in #333514 has issues detecting OpenGL libraries at least on my system, while the from-source builds works without issues on my setup.
I added @schnow265 as maintainer, assuming he's willing to help maintain a from-source flutter build as well. If not, please notify me if I should remove you from the list.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-02 17:15 UTC, schnow265 commented
Of course I want to help.

2024-09-02 18:54 UTC, schnow265 approved these changes

2024-09-03 03:00 UTC, schnow265 approved these changes

2024-09-08 08:51 UTC, niklaskorz commented
Added `updateScript` and `tests.version`.

2024-09-08 10:34 UTC, schnow265 approved these changes

2024-09-25 11:53 UTC, gepbird commented
I attempted to package ente-auth a few weeks before, but got stuck: one of the flutter dependencies called [sqlite3_flutter_libs](https://github.com/ente-io/ente/blob/auth-v3.1.3/auth/pubspec.yaml#L97) tries to download the native sqlite3, even though `sqlite` is specified in the build input. I'm surprised you don't have this in `pubspec.lock.json`, how did you generate this file?

Also I'd be happy to be a maintainer too :)

2024-09-25 12:06 UTC, gepbird requested changes
Running it on x86_64-linux in an x11 wm results in a black window, it prints the following:
`[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPlatformDirectoryException(Unable to get application documents directory)`
I made sure `~/Documents` exists, I'll troubleshoot this later.

Apart from the update script, code lgtm.

2024-09-25 12:54 UTC, niklaskorz commented
Thanks for all the feedback, I'll address it shortly!

2024-09-25 15:12 UTC, Flo2410 commented
> Running it on x86_64-linux in an x11 wm results in a black window, it prints the following: `[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: MissingPlatformDirectoryException(Unable to get application documents directory)` I made sure `~/Documents` exists, I'll troubleshoot this later.
> 
> Apart from the update script, code lgtm.
> 
> Also 4.0.2 got released recently.

I had the same issue installing ente-auth. 
I figured out that you have to install the `xdg-user-dirs` package to fix this issue.
Unforunatly I can't rember were I read this.

2024-09-25 15:56 UTC, gepbird commented
> I had the same issue installing ente-auth.
> I figured out that you have to install the xdg-user-dirs package to fix this issue.
> Unforunatly I can't rember were I read this.

Upstream issue on arch: https://github.com/ente-io/ente/issues/2046
Going into a nix shell with `xdg-user-dirs` fixes this error, but then there's a new error:
`** (ente_auth:42549): WARNING **: 17:51:53.995: libsecret_error: Failed to unlock the keyring
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Lib
secret error, Failed to unlock the keyring, null, null) `
On arch this is fixed by installing `gnome-keyring`, on NixOS going into a nix-shell with `gnome-keyring` doesn't fix it.
A weird thing is putting `xdg-user-dirs` into `buildInputs` doesn't fix the first error.

I'll check what keyring related NixOS options are later, thanks everyone for the help!

2024-09-25 16:15 UTC, Flo2410 commented
> > I had the same issue installing ente-auth.
> > I figured out that you have to install the xdg-user-dirs package to fix this issue.
> > Unforunatly I can't rember were I read this.
> 
> Upstream issue on arch: [ente-io/ente#2046](https://github.com/ente-io/ente/issues/2046) Going into a nix shell with `xdg-user-dirs` fixes this error, but then there's a new error: `** (ente_auth:42549): WARNING **: 17:51:53.995: libsecret_error: Failed to unlock the keyring [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(Lib secret error, Failed to unlock the keyring, null, null) ` On arch this is fixed by installing `gnome-keyring`, on NixOS going into a nix-shell with `gnome-keyring` doesn't fix it. A weird thing is putting `xdg-user-dirs` into `buildInputs` doesn't fix the first error.
> 
> I'll check what keyring related NixOS options are later, thanks everyone for the help!

Oh ya, that issue is where I found that fix.
I'm using the kde wallet and it works fine.

2024-09-26 05:27 UTC, gepbird commented
The libsecret error can be fixed by using the gnome-keyring (or I assume kwallet) module, not just the package.

I think we should make a module with `programs.ente-auth.enable` option that does `environment.systemPackages = [ ente-auth xdg-user-dirs ];` and `services.gnome.gnome-keyring.enable = true;`.

2024-09-26 12:54 UTC, MithicSpirit commented
> I think we should make a module with `programs.ente-auth.enable` option that does `environment.systemPackages = [ ente-auth xdg-user-dirs ];` and `services.gnome.gnome-keyring.enable = true;`.

Not sure if that's a good idea since it'll restrict it to one particular provider, which is also the most intrusive (requires PAM integration). I think that we just need upstream to emit a clearer error message here.

2024-09-27 12:32 UTC, gepbird commented on pkgs/by-name/en/ente-auth/package.nix
> +  postInstall = ''
Tested it and works, thanks!

2024-09-27 12:34 UTC, gepbird commented
> Not sure if that's a good idea since it'll restrict it to one particular provider, which is also the most intrusive (requires PAM integration). I think that we just need upstream to emit a clearer error message here.

Yeah, a module for this can be intrusive and overkill, what about mentioning it in `meta.longDescription` or somewhere else?

2024-09-29 15:03 UTC, niklaskorz commented on pkgs/by-name/en/ente-auth/package.nix
> +      D=$ICO/hicolor/''${s}x''${s}/apps
Fixed

2024-09-29 15:03 UTC, niklaskorz commented on pkgs/by-name/en/ente-auth/package.nix
> +    rm -r assets/simple-icons
Thanks!

2024-09-29 15:03 UTC, niklaskorz commented on pkgs/by-name/en/ente-auth/package.nix
> +  };
The new update script now filters out `sqlite3_flutter_libs`.

2024-09-29 15:21 UTC, niklaskorz commented on pkgs/by-name/en/ente-auth/package.nix
> +  postInstall = ''
Applied the wrapper as well. Works with and without for me, on both KDE and Gnome, but if this fixes issues with other desktop environments I'm happy to keep it.

2024-09-29 15:22 UTC, niklaskorz commented
I implemented a custom update script that takes care of updating the pubspec lock JSON as well as the simple-icons rev and hash. If there's anything else, let me know!

2024-09-29 16:43 UTC, schnow265 approved these changes

2024-09-29 22:18 UTC, gepbird approved these changes
Tested the binary and update script on x86_64-linux, diff looks good :+1:

2024-09-30 20:27 UTC, zi3m5f approved these changes
LGTM.

Result of `nixpkgs-review pr 339059` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>3 packages built:</summary>
  <ul>
    <li>ente-auth</li>
    <li>ente-auth.debug</li>
    <li>ente-auth.pubcache</li>
  </ul>
</details>

2024-09-30 20:45 UTC, niklaskorz commented on pkgs/by-name/en/ente-auth/package.nix
> +  };
Sparse checkout means a git clone though instead of a tarball fetch. No idea if the quicker tarball fetch merits the size increase though.

2024-09-30 21:20 UTC, niklaskorz commented on pkgs/by-name/en/ente-auth/package.nix
> +  };
Considering the potential future size increase of the ente monorepo, I agree it's worth switching to sparse checkout instead.

2024-10-01 03:05 UTC, schnow265 approved these changes

2024-10-01 04:28 UTC, zi3m5f approved these changes

2024-10-01 05:48 UTC, gepbird approved these changes

2024-10-01 08:14 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/1993

2024-10-01 14:56 UTC, SuperSandro2000 commented on pkgs/by-name/en/ente-auth/update.sh
> +version="$(curl --silent "https://api.github.com/repos/ente-io/ente/releases" | gojq 'map(select(.draft == false and .prerelease == false and (.tag_name | startswith("auth-v")))) | first | .tag_name'
This should optionally take a GITHUB_TOKEN https://github.com/NixOS/nixpkgs/blob/21576aba43e604a95cc45c25248f39f3989ebe36/pkgs/applications/finance/denaro/update.sh#L7

2024-10-01 14:56 UTC, SuperSandro2000 commented on pkgs/by-name/en/ente-auth/package.nix
> +
```suggestion
```

2024-10-01 14:56 UTC, SuperSandro2000 commented on pkgs/by-name/en/ente-auth/package.nix
> +      --prefix PATH : ${lib.makeBinPath runtimeInputs}
```suggestion
      --prefix PATH : ${lib.makeBinPath [ xdg-user-dirs ]}
```

2024-10-01 14:57 UTC, SuperSandro2000 commented on pkgs/by-name/en/ente-auth/package.nix
> +  simple-icons = fetchFromGitHub (builtins.fromJSON (builtins.readFile ./simple-icons.json));
```suggestion
  simple-icons = fetchFromGitHub (lib.importJSON ./simple-icons.json);
```

2024-10-01 16:30 UTC, zi3m5f approved these changes

2024-10-01 16:31 UTC, schnow265 approved these changes

2024-10-01 17:35 UTC, merged

2024-10-01 20:55 UTC, dotlambda commented on pkgs/by-name/en/ente-auth/package.nix
> +  desktopItems = makeDesktopItem {
```suggestion
  desktopItems = [ (makeDesktopItem {

2024-10-01 20:55 UTC, dotlambda commented on pkgs/by-name/en/ente-auth/package.nix
> +  patchPhase = ''
```suggestion
  postPatch = ''
```

2024-10-01 21:18 UTC, h7x4 commented on pkgs/by-name/en/ente-auth/package.nix
> +  desktopItems = makeDesktopItem {
Addressed in #345778