inputstream-adaptive: add symlink to libcdm_aarch64_loader
NixOS/nixpkgs pull request #339580
Opened 2024-09-04 16:27 UTC by chaoticryptidz

## Description of changes

Adds a symlink to libcdm_aarch64_loader to allow using widevine on arm64.

The widevine downloaded by inputstreamhelper won't work directly without using `https://github.com/AsahiLinux/widevine-installer/` or such as otherwise would need a patch to glibc, but inputstream won't even load widevine without that library, even if the widevine is patched with the missing symbols libcdm_aarch64_loader would provide.

It's basically impossible to overlay something in kodiPackages so I have to make the change here. On non-arm64 it's just a dangling symlink with no harm.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x]  `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-04 17:16 UTC, eclairevoyant commented
Please use the commit message format as mentioned in the contributing guidelines, rebase, and force-push

2024-09-04 17:20 UTC, chaoticryptidz commented
> Please use the commit message format as mentioned in the contributing guidelines, rebase, and force-push
would whoever merges it be able to squash the commits and do a correct commit message?

2024-09-04 17:23 UTC, eclairevoyant commented
https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#writing-good-commit-messages
> Pull requests should not be squash merged in order to keep complete commit messages and GPG signatures intact and must not be when the change doesn't make sense as a single commit.

Also rebasing is a common flow in PRs to nixpkgs, so this should not be too out-of-the-ordinary.

2024-09-04 17:24 UTC, eclairevoyant commented
@ofborg build inputstream-adaptive

The point of having commit messages that follow the standard format is so that reviewers don't have to explicitly comment the above every time a PR branch gets pushed to.

2024-09-04 17:29 UTC, chaoticryptidz commented
should be fixed now?

2024-09-04 17:52 UTC, nvmd requested changes

2024-09-04 17:52 UTC, nvmd commented on pkgs/applications/video/kodi/addons/inputstream-adaptive/default.nix
> +    ln -s $out/lib/addons/${n}/libcdm_aarch64_loader.so $out/${addonDir}/${n}/libcdm_aarch64_loader.so
As for the harmless dangling link on non-aarch64, maybe you could use `stdenv.hostPlatform.isAarch64` check to avoid it.

2024-09-07 13:27 UTC, dschrempf commented
Is it possible to only create this symlink when the host platform is arm64? I guess, we need an optional input or the like.

2024-09-07 13:43 UTC, chaoticryptidz commented
> Is it possible to only create this symlink when the host platform is arm64? I guess, we need an optional input or the like.
> 
> Did you test if widevine works on non-arm64 with this change?

check latest commits, and yes widevine still works on all other platforms, this is only needed to let it load widevine on arm64, though still needs a binary patch to the widevine library due to glibc problems, asahi's widevine installer patches this so that python script can be used for the latest widevine downloaded by inputstreamhelper, which we have also working on a nix derivation for latest patched widevine extracted from chromeos images

2024-09-13 15:01 UTC, chaoticryptidz commented
should be ready to merge

2024-09-13 18:00 UTC, nvmd commented
I've tested this on aarch64-linux (rpi5) with the latest kodi, inputstreamhelper, inputstream-adaptive: widevine-cdm library loads as expected; haven't noticed any regressions. For me, this was the missing puzzle piece to finally get widevine working, thanks!
I don't have any objections functionality-wise.

Could you please maybe squash at least 2 of those 3 separate commits in this PR? I don't think there will be any value in keeping this small change split across 3 commits in a common history.

2024-12-04 11:35 UTC, FliegendeWurst approved these changes

2024-12-06 02:37 UTC, merged