salt: Prefer to load Nix libcrypto
NixOS/nixpkgs pull request #33971
Opened 2018-01-17 07:45 UTC by aneeshusa

Prefer to load the static Nix version,
but still fallback to the normal loading pathway if needed.

Being more aggressive about using the Nix dependency
improves stability and means Salt works more often,
namely in cases where find_library/LoadLibrary don't work
even though we have the Nix libcrypto available.

We still need to keep the fallback for usage with salt-ssh.

###### Motivation for this change

Better fix than what was in #29020.
See also #29723 cc @danbst.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-01-17 08:49 UTC, danbst commented
While I'm all for this patch, I still don't like that master Salt update, even without version bump, (Nix Salt) can cause minion side breakages (when using Nix minion Salt). This probably doesn't happen often because of delayed garbage collection on minions, but if minions remove garbage ASAP, the breakage threat is real.

Also, now I think this isn't Salt issue (Salt can compare library versions for integrity check), and it isn't Nix issue (it does it's job - perfect dependency specification).

The patch in https://github.com/NixOS/nixpkgs/pull/33972 looks interesting, but which `libcrypto` version does it return?

2018-01-17 09:12 UTC, FRidh commented
Why are you not hardcoding the path to the library?

2018-01-17 09:36 UTC, danbst commented
@FRidh there is hardcode `+            return cdll.LoadLibrary('@libcrypto@')`

2018-01-17 16:51 UTC, aneeshusa commented
I don't see a good way to have Salt copy over the whole libcrypto closure, since the target machine may have a different architecture, so I thnk it's reasonable to fallback to impure libcrypto on the target.

@danbst agreed that this patch isn't perfect, but maybe we should just say it doesn't make sense to use salt-ssh to minions with Nix Salt already installed since it reduces purity?

Or maybe extend upstream Salt to learn how to re-use an existing Salt installation,
instead of always copying over modules. They do some magic bits with wrapping certain functions that normally rely on the fileserver since during SSH they instead need to preload files with scp, but that shouldn't affect this crypto module, so maybe a combination of use preinstalled-version + have wrappers would work best.

I'll need to double-check which version of libcrypto #33972 returns (build closure or runtime libcrypto), but I can say it's one that seems to work for me :)
For most cases (not `salt-ssh` to a Nix minion that GC'd or doesn't have the client's hardcoded libcrypto) IIRC either patch should be sufficient

2018-01-17 22:08 UTC, danbst commented
I'm talking about setup when Nix Salt master makes commands via `salt-ssh` to NixOS minion host. Without https://github.com/NixOS/nixpkgs/pull/33972 it would be pain to do this (but probably better tool here is NixOps).

But I'm all for this patch, it is simpler than my previous one.

2018-01-17 22:08 UTC, danbst approved these changes

2018-01-18 10:38 UTC, FRidh commented
Thanks for the explanation. I don't know what Salt is, but considering this is quite specific/special behavior, I think this should be documented in the expression.

2018-04-21 19:42 UTC, matthewbauer requested changes
See @FRidh's comments

2019-08-03 14:41 UTC, mmahut commented
What is the status of this pull request?

2019-10-05 20:37 UTC, mmahut commented
Closing due to lack of activity, feel free to re-open this if needed.

2019-10-05 20:37 UTC, closed without merging