tanka: disable GOWORK
NixOS/nixpkgs pull request #340060
Opened 2024-09-06 11:31 UTC by theSuess

## Description of changes

With the addition of a `go.work` file in https://github.com/grafana/tanka/pull/1040, newer versions were no longer able to be built. The `go.work` file is only needed for acceptance tests, so `GOWORK=off` can safely be set during builds.

Previous changes of a similar nature: https://github.com/NixOS/nixpkgs/pull/301928

## Things done

- Built on platform(s)
  - [X] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [X] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-12 11:38 UTC, nevivurn requested changes
Can you also bump the tanka version while we're at it?

The upstream change only landed around 0.28.0, makes little sense to add fixes for some version we have not packaged yet. I can at least confirm that the build is broken as you explained on 0.28.1: [r-ryantm logs](https://nixpkgs-update-logs.nix-community.org/tanka/2024-09-06.log).

2024-09-12 11:38 UTC, nevivurn commented on pkgs/applications/networking/cluster/tanka/default.nix
> +  env.GOWORK = "off";
We should also add a short comment as to why we're disabling gowork.

2024-09-17 07:29 UTC, theSuess commented
I've now also bumped the version to `0.28.0`. Initially wanted to split the version update to a separate PR to keep changes minimal but happy to do it in this PR as well

2024-09-17 13:36 UTC, nevivurn approved these changes

2024-09-21 01:24 UTC, merged