linux-steam-integration: Append "Settings" to launcher menu item
NixOS/nixpkgs pull request #34020
Opened 2018-01-18 18:48 UTC by benley

###### Motivation for this change

It just shows up as "Linux Steam Integration" otherwise, which is confusing.  The actual LSI launcher's name in the menu is "LSI Steam", right next to this one.

###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-01-18 23:49 UTC, dtzWill requested changes
`postInstall` doesn't run since this defines a custom `installPhase` (and as a result, this change does nothing).

Probably simplest to just append this to the existing `installPhase`.  Alternatively there's some magic hook invocation that "should" be executed at the beginning of custom installPhase definitions to run these things.

2018-01-19 01:41 UTC, adisbladis commented
cc @etu

2018-01-19 12:19 UTC, etu commented
@benley As @dtzWill said, the `postInstall` isn't executed. So this patch doesn't actually do anything.

But you can put your sed line in the postPatch and change the filename from `$out/share/applications/lsi-settings.desktop` to `data/lsi-settings.desktop.in`. I haven't tested this but I'm pretty sure it will work.

2018-01-19 21:29 UTC, benley commented
Oh, good point.  I'm putting it in the postPatch phase, that sounds right.

2018-01-24 18:26 UTC, merged