nixos/ckb: Add option to restrict access to the devices to a particu...
NixOS/nixpkgs pull request #34064
Opened 2018-01-20 00:00 UTC by Nadrieril

…ar group

###### Motivation for this change

By default, the ckb daemon allows acces to its controlling socket to any process (chmod 666), which is kinda crazy. This PR allows to restrict access to a unix group.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-01-22 22:10 UTC, kierdavis requested changes
The feature itself works; however I have a niggle about the metadata of the new option (see line comment).

2018-01-22 22:10 UTC, kierdavis commented on nixos/modules/hardware/ckb.nix
> +        type = types.nullOr types.str;
It appears that ckb-daemon only accepts actual GIDs and not group names, so please could we change the type of this option to `types.int` and update the example to reflect this?

2018-01-23 02:37 UTC, Nadrieril commented
You're right, I changed that. Thanks for the fast feedback !

2018-01-23 08:06 UTC, kierdavis approved these changes
Thanks. Looks good to me now.

2018-11-15 16:51 UTC, Mic92 commented
merged in 99a8c45bdde5c59f5a7a7b7d57813f20fbb70a92

2018-11-15 16:51 UTC, closed without merging