cosmic-calculator: init at 0-unstable-2024-09-07
NixOS/nixpkgs pull request #340725
Opened 2024-09-09 09:37 UTC by callumio

## Description of changes

Adds a calculator application for the COSMIC Desktop.

Fixes #337554 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-09 10:03 UTC, callumio commented
Result of `nixpkgs-review pr 340725` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>cosmic-calculator</li>
  </ul>
</details>

2024-10-23 16:09 UTC, Pandapip1 requested changes

2024-10-23 16:09 UTC, Pandapip1 commented on pkgs/by-name/co/cosmic-calculator/package.nix
> +      }"
Can't the `LD_LIBRARY_PATH` prefix wrap be replaced by `autoPatchelfHook`?

2024-12-24 05:32 UTC, HeitorAugustoLN requested changes

2024-12-24 05:32 UTC, HeitorAugustoLN commented on pkgs/by-name/co/cosmic-calculator/package.nix
> +  };
It would be better to set `useFetchCargoVendor = true` instead of vendoring the `Cargo.lock`.

2024-12-24 05:32 UTC, HeitorAugustoLN commented on pkgs/by-name/co/cosmic-calculator/package.nix
> +  ];
`vulkan-loader` and `libGL` are generally needed by libcosmic applications too
```suggestion
  buildInputs = [
    wayland
    libxkbcommon
    vulkan-loader
    libGL
  ];
```

2024-12-24 05:32 UTC, HeitorAugustoLN commented on pkgs/by-name/co/cosmic-calculator/package.nix
> +
Also disable `just` check.
```suggestion
  dontUseJustBuild = true;
  dontUseJustCheck = true;
```

2024-12-24 05:32 UTC, HeitorAugustoLN commented on pkgs/by-name/co/cosmic-calculator/package.nix
> +  pname = "cosmic-calculator";
The package name is `cosmic-ext-calculator` in upstream, so I think this should be renamed to it

2025-02-13 17:49 UTC, HeitorAugustoLN commented
Superseeded by #379412

2025-02-13 17:49 UTC, closed without merging