rucola: init at 0.4.0
NixOS/nixpkgs pull request #341286
Opened 2024-09-12 03:53 UTC by donovanglover

## Description of changes

Adds [rucola](https://github.com/Linus-Mussmaecher/rucola), a terminal-based markdown note manager.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-10 13:44 UTC, devhell commented
Result of `nixpkgs-review pr 341286` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>rucola</li>
  </ul>
</details>

Can this be merged?

2024-10-18 01:19 UTC, donovanglover commented
I set `platforms = lib.platforms.linux;` since it was failing on Darwin. Contributions welcome if anyone knows how to add Darwin support.

2024-10-26 09:30 UTC, devhell commented
I have no way of testing for Darwin, but until someone can, perhaps this can be merged now?

2024-10-26 09:33 UTC, afh commented
I'll have a look @devhell

2024-10-26 09:55 UTC, afh requested changes
The following suggestions below are necessary in order to build rucola on darwin.

Not sure why but the 
`test io::file_tracker::tests::test_watcher_rename` test fails.
Any ideas?

2024-10-26 09:55 UTC, afh commented on pkgs/by-name/ru/rucola/package.nix
> +    platforms = lib.platforms.linux;
```suggestion
    platforms = lib.platforms.linux ++ lib.platforms.darwin;
```

2024-10-26 09:55 UTC, afh commented on pkgs/by-name/ru/rucola/package.nix
> +  ];
```suggestion
  ] ++ lib.optionals stdenv.hostPlatform.isDarwin (with darwin.apple_sdk.frameworks; [
    CoreServices SystemConfiguration
  ]);
```

2024-10-26 09:55 UTC, afh commented on pkgs/by-name/ru/rucola/package.nix
> +  oniguruma,
```suggestion
  oniguruma,
  darwin,
  stdenv,
```

2024-10-27 01:45 UTC, donovanglover commented
No idea but upstream doesn't seem to test Darwin in CI so I'm fine with skipping it

2024-10-27 05:06 UTC, Aleksanaa commented
> No idea but upstream doesn't seem to test Darwin in CI so I'm fine with skipping it

Could you mark it as broken?

2024-10-27 05:06 UTC, Aleksanaa approved these changes
Others seems fine

2024-10-27 06:49 UTC, afh commented
@donovanglover is there a way to disable the faulty test in the rucola nixpkg when building on darwin? I'd prefer that over marking it as broken.

Any objections, @Aleksanaa?

2024-10-27 06:52 UTC, Aleksanaa commented
I'll take a look

2024-11-22 22:49 UTC, devhell commented
What's the status on this PR?

2024-11-24 08:16 UTC, Aleksanaa commented on pkgs/by-name/ru/rucola/package.nix
> +      ]
```suggestion
      [
        apple_sdk_11
        (darwinMinVersionHook "10.13")
      ]
```

2024-11-24 21:00 UTC, donovanglover commented on pkgs/by-name/ru/rucola/package.nix
> +      ]
Used `apple-sdk_11`

2024-11-25 17:20 UTC, donovanglover commented
Looks like the build passes on darwin now :tada:

2024-12-01 10:40 UTC, Aleksanaa approved these changes

2024-12-01 10:40 UTC, merged