luaPackages: update on 2024-09-16
NixOS/nixpkgs pull request #342196
Opened 2024-09-16 03:01 UTC by khaneliman

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-16 03:18 UTC, khaneliman commented
Result of `nixpkgs-review pr 342196` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lua-lsp</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.plenary-nvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
    <li>vimPlugins.sg-nvim</li>
  </ul>
</details>
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.tiktoken_core</li>
    <li>lua52Packages.teal-language-server</li>
    <li>lua52Packages.tiktoken_core</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tiktoken_core</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tiktoken_core</li>
    <li>luajitPackages.teal-language-server</li>
    <li>luajitPackages.tiktoken_core</li>
  </ul>
</details>
<details>
  <summary>379 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.dkjson</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.lua-lsp</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.plenary-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>lua52Packages.argparse</li>
    <li>lua52Packages.busted</li>
    <li>lua52Packages.compat53</li>
    <li>lua52Packages.cyan</li>
    <li>lua52Packages.dkjson</li>
    <li>lua52Packages.fzf-lua</li>
    <li>lua52Packages.fzy</li>
    <li>lua52Packages.haskell-tools-nvim</li>
    <li>lua52Packages.http</li>
    <li>lua52Packages.llscheck</li>
    <li>lua52Packages.lua-lsp</li>
    <li>lua52Packages.luacheck</li>
    <li>lua52Packages.luaprompt</li>
    <li>lua52Packages.luarocks-build-treesitter-parser</li>
    <li>lua52Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua52Packages.luasystem</li>
    <li>lua52Packages.lush-nvim</li>
    <li>lua52Packages.lz-n</li>
    <li>lua52Packages.lzn-auto-require</li>
    <li>lua52Packages.moonscript</li>
    <li>lua52Packages.pathlib-nvim</li>
    <li>lua52Packages.plenary-nvim</li>
    <li>lua52Packages.rest-nvim</li>
    <li>lua52Packages.rocks-config-nvim</li>
    <li>lua52Packages.rocks-dev-nvim</li>
    <li>lua52Packages.rocks-git-nvim</li>
    <li>lua52Packages.rocks-nvim</li>
    <li>lua52Packages.rtp-nvim</li>
    <li>lua52Packages.rustaceanvim</li>
    <li>lua52Packages.sqlite</li>
    <li>lua52Packages.tl</li>
    <li>lua52Packages.tree-sitter-norg</li>
    <li>lua52Packages.vusted</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.dkjson</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.lua-lsp</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.plenary-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.dkjson</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.dkjson</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.lua-lsp</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.lush-nvim</li>
    <li>luajitPackages.lz-n</li>
    <li>luajitPackages.lze</li>
    <li>luajitPackages.lzn-auto-require</li>
    <li>luajitPackages.moonscript</li>
    <li>luajitPackages.nfd</li>
    <li>luajitPackages.pathlib-nvim</li>
    <li>luajitPackages.plenary-nvim</li>
    <li>luajitPackages.res [...]

2024-09-16 03:56 UTC, khaneliman commented
Result of `nixpkgs-review pr 342196` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>25 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lua-lsp</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.plenary-nvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
    <li>vimPlugins.sg-nvim</li>
  </ul>
</details>
<details>
  <summary>383 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.dkjson</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.lua-lsp</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.plenary-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>lua52Packages.argparse</li>
    <li>lua52Packages.busted</li>
    <li>lua52Packages.compat53</li>
    <li>lua52Packages.cyan</li>
    <li>lua52Packages.dkjson</li>
    <li>lua52Packages.fzf-lua</li>
    <li>lua52Packages.fzy</li>
    <li>lua52Packages.haskell-tools-nvim</li>
    <li>lua52Packages.http</li>
    <li>lua52Packages.llscheck</li>
    <li>lua52Packages.lua-lsp</li>
    <li>lua52Packages.luacheck</li>
    <li>lua52Packages.luaprompt</li>
    <li>lua52Packages.luarocks-build-treesitter-parser</li>
    <li>lua52Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua52Packages.luasystem</li>
    <li>lua52Packages.lush-nvim</li>
    <li>lua52Packages.lz-n</li>
    <li>lua52Packages.lzn-auto-require</li>
    <li>lua52Packages.moonscript</li>
    <li>lua52Packages.pathlib-nvim</li>
    <li>lua52Packages.plenary-nvim</li>
    <li>lua52Packages.rest-nvim</li>
    <li>lua52Packages.rocks-config-nvim</li>
    <li>lua52Packages.rocks-dev-nvim</li>
    <li>lua52Packages.rocks-git-nvim</li>
    <li>lua52Packages.rocks-nvim</li>
    <li>lua52Packages.rtp-nvim</li>
    <li>lua52Packages.rustaceanvim</li>
    <li>lua52Packages.sqlite</li>
    <li>lua52Packages.teal-language-server</li>
    <li>lua52Packages.tl</li>
    <li>lua52Packages.tree-sitter-norg</li>
    <li>lua52Packages.vusted</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.dkjson</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.lua-lsp</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.plenary-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.dkjson</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.dkjson</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.lua-lsp</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.lush-nvim</li>
    <li>luajitPackages.lz-n</li>
    <li>luajitPackages.lze</li>
    <li>luajitPackages.lzn-auto-require</li>
    <li>luajitPackages.moonscript</li>
    <li>luajitPackages.nfd</li>
    <li>luajitPackages.pathlib-nvim</li>
    <li>luajitPackages.plenary-nvim</li>
    <li>luajitPackages.rest-nvim</li>
    <li>luajitPackages.rocks-config-nvim</li>
    <li>luajitPackages.rocks-dev-nvim</li>
    <li>luajitPackages.rocks-git-nvim</li>
    <li>luajitPackages.rocks-nvim</li>
    <li>luajitPackages.rtp-nvim</li>
    <li>luajitPackages.rustaceanvim</li>
    <li>luajitPackages.sqlite</li>
    <li>luajitPackages.teal-language-server</ [...]

2024-09-16 14:15 UTC, khaneliman commented
Rest-nvim works for me 
![image](https://github.com/user-attachments/assets/bdbee67a-437c-4d4c-97f4-c41c7f10cbec)

2024-09-16 14:54 UTC, khaneliman commented
@PerchunPak what was the plenary regression you tested before?

2024-09-16 14:58 UTC, mrcjkb commented
:thinking: what's the build output of `luaPackages.sqlite` on aarch64-darwin?

2024-09-16 14:59 UTC, khaneliman commented
> 🤔 what's the build output of `luaPackages.sqlite` on aarch64-darwin?

I get local failures from tests, @GaetanLepage an hydra don't seem to get them

2024-09-16 15:19 UTC, mrcjkb commented
As it's Darwin, could it be related to sandboxing in your nix config (see the issue template check list)?
If it builds on hydra, I guess it's fine.

2024-09-16 15:20 UTC, khaneliman commented
> As it's Darwin, could it be related to sandboxing in your nix config (see the issue template check list)? If it builds on hydra, I guess it's fine.

Yeah, darwin sandbox support is terrible... I can't enable it in my config due to serialization errors and nixpkgs-review doesn't allow sandbox command on darwin.

2024-09-16 21:48 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 342196` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>30 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.plenary-nvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luaPackages.digestif</li>
    <li>luaPackages.gitsigns-nvim</li>
    <li>luaPackages.neotest</li>
    <li>luaPackages.nfd</li>
    <li>luaPackages.telescope-manix</li>
    <li>luaPackages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
    <li>vimPlugins.sg-nvim</li>
  </ul>
</details>
<details>
  <summary>376 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.plenary-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.argparse (lua52Packages.argparse)</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.compat53 (lua52Packages.compat53)</li>
    <li>luaPackages.cyan (lua52Packages.cyan)</li>
    <li>luaPackages.fzf-lua (lua52Packages.fzf-lua)</li>
    <li>luaPackages.fzy (lua52Packages.fzy)</li>
    <li>luaPackages.haskell-tools-nvim (lua52Packages.haskell-tools-nvim)</li>
    <li>luaPackages.http (lua52Packages.http)</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luaprompt (lua52Packages.luaprompt)</li>
    <li>luaPackages.luarocks-build-treesitter-parser (lua52Packages.luarocks-build-treesitter-parser)</li>
    <li>luaPackages.luarocks-build-treesitter-parser-cpp (lua52Packages.luarocks-build-treesitter-parser-cpp)</li>
    <li>luaPackages.luasystem (lua52Packages.luasystem)</li>
    <li>luaPackages.lush-nvim (lua52Packages.lush-nvim)</li>
    <li>luaPackages.lz-n (lua52Packages.lz-n)</li>
    <li>luaPackages.lzn-auto-require (lua52Packages.lzn-auto-require)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.pathlib-nvim (lua52Packages.pathlib-nvim)</li>
    <li>luaPackages.plenary-nvim (lua52Packages.plenary-nvim)</li>
    <li>luaPackages.rest-nvim (lua52Packages.rest-nvim)</li>
    <li>luaPackages.rocks-config-nvim (lua52Packages.rocks-config-nvim)</li>
    <li>luaPackages.rocks-dev-nvim (lua52Packages.rocks-dev-nvim)</li>
    <li>luaPackages.rocks-git-nvim (lua52Packages.rocks-git-nvim)</li>
    <li>luaPackages.rocks-nvim (lua52Packages.rocks-nvim)</li>
    <li>luaPackages.rtp-nvim (lua52Packages.rtp-nvim)</li>
    <li>luaPackages.rustaceanvim (lua52Packages.rustaceanvim)</li>
    <li>luaPackages.sqlite (lua52Packages.sqlite)</li>
    <li>luaPackages.teal-language-server (lua52Packages.teal-language-server)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.tree-sitter-norg (lua52Packages.tree-sitter-norg)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.plenary-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
 [...]

2024-09-17 06:44 UTC, GaetanLepage commented
`luaPackages.sqlite` does indeed fail on `darwin`.

2024-09-17 06:50 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 342196` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>29 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.plenary-nvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luaPackages.digestif</li>
    <li>luaPackages.gitsigns-nvim</li>
    <li>luaPackages.neotest</li>
    <li>luaPackages.nfd</li>
    <li>luaPackages.telescope-manix</li>
    <li>luaPackages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>7 packages failed to build:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.sqlite</li>
    <li>luaPackages.sqlite (lua52Packages.sqlite)</li>
    <li>lua53Packages.sqlite</li>
    <li>luajitPackages.sqlite</li>
  </ul>
</details>
<details>
  <summary>356 packages built:</summary>
  <ul>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.plenary-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.argparse (lua52Packages.argparse)</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.compat53 (lua52Packages.compat53)</li>
    <li>luaPackages.cyan (lua52Packages.cyan)</li>
    <li>luaPackages.fzf-lua (lua52Packages.fzf-lua)</li>
    <li>luaPackages.fzy (lua52Packages.fzy)</li>
    <li>luaPackages.haskell-tools-nvim (lua52Packages.haskell-tools-nvim)</li>
    <li>luaPackages.http (lua52Packages.http)</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luaprompt (lua52Packages.luaprompt)</li>
    <li>luaPackages.luarocks-build-treesitter-parser (lua52Packages.luarocks-build-treesitter-parser)</li>
    <li>luaPackages.luarocks-build-treesitter-parser-cpp (lua52Packages.luarocks-build-treesitter-parser-cpp)</li>
    <li>luaPackages.luasystem (lua52Packages.luasystem)</li>
    <li>luaPackages.lush-nvim (lua52Packages.lush-nvim)</li>
    <li>luaPackages.lz-n (lua52Packages.lz-n)</li>
    <li>luaPackages.lzn-auto-require (lua52Packages.lzn-auto-require)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.pathlib-nvim (lua52Packages.pathlib-nvim)</li>
    <li>luaPackages.plenary-nvim (lua52Packages.plenary-nvim)</li>
    <li>luaPackages.rest-nvim (lua52Packages.rest-nvim)</li>
    <li>luaPackages.rocks-config-nvim (lua52Packages.rocks-config-nvim)</li>
    <li>luaPackages.rocks-dev-nvim (lua52Packages.rocks-dev-nvim)</li>
    <li>luaPackages.rocks-git-nvim (lua52Packages.rocks-git-nvim)</li>
    <li>luaPackages.rocks-nvim (lua52Packages.rocks-nvim)</li>
    <li>luaPackages.rtp-nvim (lua52Packages.rtp-nvim)</li>
    <li>luaPackages.rustaceanvim (lua52Packages.rustaceanvim)</li>
    <li>luaPackages.teal-language-server (lua52Packages.teal-language-server)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.tree-sitter-norg (lua52Packages.tree-sitter-norg)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.plenary-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-buil [...]

2024-09-17 07:01 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 342196` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>29 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.plenary-nvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luaPackages.digestif</li>
    <li>luaPackages.gitsigns-nvim</li>
    <li>luaPackages.neotest</li>
    <li>luaPackages.nfd</li>
    <li>luaPackages.telescope-manix</li>
    <li>luaPackages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.sqlite</li>
    <li>luaPackages.sqlite (lua52Packages.sqlite)</li>
    <li>lua53Packages.sqlite</li>
    <li>luajitPackages.sqlite</li>
    <li>rehex</li>
    <li>vimPlugins.ddc-filter-matcher_head</li>
    <li>vimPlugins.ddc-filter-sorter_rank</li>
    <li>vimPlugins.ddc-source-lsp</li>
    <li>vimPlugins.ddc-ui-native</li>
    <li>vimPlugins.ddc-ui-pum</li>
    <li>vimPlugins.ddc-vim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.vim-pluto</li>
  </ul>
</details>
<details>
  <summary>347 packages built:</summary>
  <ul>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.plenary-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.argparse (lua52Packages.argparse)</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.compat53 (lua52Packages.compat53)</li>
    <li>luaPackages.cyan (lua52Packages.cyan)</li>
    <li>luaPackages.fzf-lua (lua52Packages.fzf-lua)</li>
    <li>luaPackages.fzy (lua52Packages.fzy)</li>
    <li>luaPackages.haskell-tools-nvim (lua52Packages.haskell-tools-nvim)</li>
    <li>luaPackages.http (lua52Packages.http)</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luaprompt (lua52Packages.luaprompt)</li>
    <li>luaPackages.luarocks-build-treesitter-parser (lua52Packages.luarocks-build-treesitter-parser)</li>
    <li>luaPackages.luarocks-build-treesitter-parser-cpp (lua52Packages.luarocks-build-treesitter-parser-cpp)</li>
    <li>luaPackages.luasystem (lua52Packages.luasystem)</li>
    <li>luaPackages.lush-nvim (lua52Packages.lush-nvim)</li>
    <li>luaPackages.lz-n (lua52Packages.lz-n)</li>
    <li>luaPackages.lzn-auto-require (lua52Packages.lzn-auto-require)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.pathlib-nvim (lua52Packages.pathlib-nvim)</li>
    <li>luaPackages.plenary-nvim (lua52Packages.plenary-nvim)</li>
    <li>luaPackages.rest-nvim (lua52Packages.rest-nvim)</li>
    <li>luaPackages.rocks-config-nvim (lua52Packages.rocks-config-nvim)</li>
    <li>luaPackages.rocks-dev-nvim (lua52Packages.rocks-dev-nvim)</li>
    <li>luaPackages.rocks-git-nvim (lua52Packages.rocks-git-nvim)</li>
    <li>luaPackages.rocks-nvim (lua52Packages.rocks-nvim)</li>
    <li>luaPackages.rtp-nvim (lua52Packages.rtp-nvim)</li>
    <li>luaPackages.rustaceanvim (lua52Packages.rustaceanvim)</li>
    <li>luaPackages.teal-language-server (lua52Packages.teal-language-server)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.tree-sitter-norg (lua52Packages.tree-sitter-norg)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.plenary-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>lua [...]

2024-09-17 07:14 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 342196` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>29 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.plenary-nvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luaPackages.digestif</li>
    <li>luaPackages.gitsigns-nvim</li>
    <li>luaPackages.neotest</li>
    <li>luaPackages.nfd</li>
    <li>luaPackages.telescope-manix</li>
    <li>luaPackages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>16 packages failed to build:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.sqlite</li>
    <li>luaPackages.sqlite (lua52Packages.sqlite)</li>
    <li>lua53Packages.sqlite</li>
    <li>luajitPackages.sqlite</li>
    <li>rehex</li>
    <li>vimPlugins.ddc-filter-matcher_head</li>
    <li>vimPlugins.ddc-filter-sorter_rank</li>
    <li>vimPlugins.ddc-source-lsp</li>
    <li>vimPlugins.ddc-ui-native</li>
    <li>vimPlugins.ddc-ui-pum</li>
    <li>vimPlugins.ddc-vim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.vim-pluto</li>
  </ul>
</details>
<details>
  <summary>347 packages built:</summary>
  <ul>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.plenary-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.argparse (lua52Packages.argparse)</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.compat53 (lua52Packages.compat53)</li>
    <li>luaPackages.cyan (lua52Packages.cyan)</li>
    <li>luaPackages.fzf-lua (lua52Packages.fzf-lua)</li>
    <li>luaPackages.fzy (lua52Packages.fzy)</li>
    <li>luaPackages.haskell-tools-nvim (lua52Packages.haskell-tools-nvim)</li>
    <li>luaPackages.http (lua52Packages.http)</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luaprompt (lua52Packages.luaprompt)</li>
    <li>luaPackages.luarocks-build-treesitter-parser (lua52Packages.luarocks-build-treesitter-parser)</li>
    <li>luaPackages.luarocks-build-treesitter-parser-cpp (lua52Packages.luarocks-build-treesitter-parser-cpp)</li>
    <li>luaPackages.luasystem (lua52Packages.luasystem)</li>
    <li>luaPackages.lush-nvim (lua52Packages.lush-nvim)</li>
    <li>luaPackages.lz-n (lua52Packages.lz-n)</li>
    <li>luaPackages.lzn-auto-require (lua52Packages.lzn-auto-require)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.pathlib-nvim (lua52Packages.pathlib-nvim)</li>
    <li>luaPackages.plenary-nvim (lua52Packages.plenary-nvim)</li>
    <li>luaPackages.rest-nvim (lua52Packages.rest-nvim)</li>
    <li>luaPackages.rocks-config-nvim (lua52Packages.rocks-config-nvim)</li>
    <li>luaPackages.rocks-dev-nvim (lua52Packages.rocks-dev-nvim)</li>
    <li>luaPackages.rocks-git-nvim (lua52Packages.rocks-git-nvim)</li>
    <li>luaPackages.rocks-nvim (lua52Packages.rocks-nvim)</li>
    <li>luaPackages.rtp-nvim (lua52Packages.rtp-nvim)</li>
    <li>luaPackages.rustaceanvim (lua52Packages.rustaceanvim)</li>
    <li>luaPackages.teal-language-server (lua52Packages.teal-language-server)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.tree-sitter-norg (lua52Packages.tree-sitter-norg)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.plenary-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>lua [...]

2024-09-17 09:27 UTC, PerchunPak commented
> @PerchunPak what was the plenary regression you tested before?

Tests were failing on plenary, if they run simultaneously. I added `sequential = true` flag for debugging and it started to work correctly

2024-09-17 14:16 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 342196` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>29 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.plenary-nvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luaPackages.digestif</li>
    <li>luaPackages.gitsigns-nvim</li>
    <li>luaPackages.neotest</li>
    <li>luaPackages.nfd</li>
    <li>luaPackages.telescope-manix</li>
    <li>luaPackages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>363 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.plenary-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.argparse (lua52Packages.argparse)</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.compat53 (lua52Packages.compat53)</li>
    <li>luaPackages.cyan (lua52Packages.cyan)</li>
    <li>luaPackages.fzf-lua (lua52Packages.fzf-lua)</li>
    <li>luaPackages.fzy (lua52Packages.fzy)</li>
    <li>luaPackages.haskell-tools-nvim (lua52Packages.haskell-tools-nvim)</li>
    <li>luaPackages.http (lua52Packages.http)</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luaprompt (lua52Packages.luaprompt)</li>
    <li>luaPackages.luarocks-build-treesitter-parser (lua52Packages.luarocks-build-treesitter-parser)</li>
    <li>luaPackages.luarocks-build-treesitter-parser-cpp (lua52Packages.luarocks-build-treesitter-parser-cpp)</li>
    <li>luaPackages.luasystem (lua52Packages.luasystem)</li>
    <li>luaPackages.lush-nvim (lua52Packages.lush-nvim)</li>
    <li>luaPackages.lz-n (lua52Packages.lz-n)</li>
    <li>luaPackages.lzn-auto-require (lua52Packages.lzn-auto-require)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.pathlib-nvim (lua52Packages.pathlib-nvim)</li>
    <li>luaPackages.plenary-nvim (lua52Packages.plenary-nvim)</li>
    <li>luaPackages.rest-nvim (lua52Packages.rest-nvim)</li>
    <li>luaPackages.rocks-config-nvim (lua52Packages.rocks-config-nvim)</li>
    <li>luaPackages.rocks-dev-nvim (lua52Packages.rocks-dev-nvim)</li>
    <li>luaPackages.rocks-git-nvim (lua52Packages.rocks-git-nvim)</li>
    <li>luaPackages.rocks-nvim (lua52Packages.rocks-nvim)</li>
    <li>luaPackages.rtp-nvim (lua52Packages.rtp-nvim)</li>
    <li>luaPackages.rustaceanvim (lua52Packages.rustaceanvim)</li>
    <li>luaPackages.sqlite (lua52Packages.sqlite)</li>
    <li>luaPackages.teal-language-server (lua52Packages.teal-language-server)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.tree-sitter-norg (lua52Packages.tree-sitter-norg)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.plenary-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasyste [...]

2024-09-18 07:37 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 342196` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luaPackages.digestif</li>
    <li>luaPackages.gitsigns-nvim</li>
    <li>luaPackages.neotest</li>
    <li>luaPackages.nfd</li>
    <li>luaPackages.telescope-manix</li>
    <li>luaPackages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>374 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.argparse (lua52Packages.argparse)</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.compat53 (lua52Packages.compat53)</li>
    <li>luaPackages.cyan (lua52Packages.cyan)</li>
    <li>luaPackages.fzf-lua (lua52Packages.fzf-lua)</li>
    <li>luaPackages.fzy (lua52Packages.fzy)</li>
    <li>luaPackages.haskell-tools-nvim (lua52Packages.haskell-tools-nvim)</li>
    <li>luaPackages.http (lua52Packages.http)</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luaprompt (lua52Packages.luaprompt)</li>
    <li>luaPackages.luarocks-build-treesitter-parser (lua52Packages.luarocks-build-treesitter-parser)</li>
    <li>luaPackages.luarocks-build-treesitter-parser-cpp (lua52Packages.luarocks-build-treesitter-parser-cpp)</li>
    <li>luaPackages.luasystem (lua52Packages.luasystem)</li>
    <li>luaPackages.lush-nvim (lua52Packages.lush-nvim)</li>
    <li>luaPackages.lz-n (lua52Packages.lz-n)</li>
    <li>luaPackages.lzn-auto-require (lua52Packages.lzn-auto-require)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.pathlib-nvim (lua52Packages.pathlib-nvim)</li>
    <li>luaPackages.rest-nvim (lua52Packages.rest-nvim)</li>
    <li>luaPackages.rocks-config-nvim (lua52Packages.rocks-config-nvim)</li>
    <li>luaPackages.rocks-dev-nvim (lua52Packages.rocks-dev-nvim)</li>
    <li>luaPackages.rocks-git-nvim (lua52Packages.rocks-git-nvim)</li>
    <li>luaPackages.rocks-nvim (lua52Packages.rocks-nvim)</li>
    <li>luaPackages.rtp-nvim (lua52Packages.rtp-nvim)</li>
    <li>luaPackages.rustaceanvim (lua52Packages.rustaceanvim)</li>
    <li>luaPackages.sqlite (lua52Packages.sqlite)</li>
    <li>luaPackages.teal-language-server (lua52Packages.teal-language-server)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.tree-sitter-norg (lua52Packages.tree-sitter-norg)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.lush-nvim</li>
    <li>luajitPackages.lz-n</li>
    <li>luajitPackages.lze</li>
    <li>luajitPackages.lzn-auto-require</li>
    <li>luajitPackages.moonscript [...]

2024-09-18 08:41 UTC, PerchunPak requested changes
Also, PR name should be `luaPackages, vimPlugins: update on 2024-09-16`, but it is just a nitpick

2024-09-18 08:41 UTC, PerchunPak commented on pkgs/applications/editors/vim/plugins/deprecated.json
> -    },
Drop 72447c33ed32c437992496936848fc9b0e7a6b26 please, it is useless (or squash it with 28bc9ba3c6158ed3d92242184e2e5468168ff6c2). The functionality, that is done by this commit is broken and will be fixed by #336137

2024-09-19 08:50 UTC, PerchunPak commented on pkgs/applications/editors/vim/plugins/deprecated.json
> -    },
Unfortunately, yes. It is broken

2024-09-19 08:51 UTC, PerchunPak approved these changes
If `nixpkgs-review` passes, LGTM

2024-09-19 13:34 UTC, khaneliman commented
Result of `nixpkgs-review pr 342196` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luaPackages.digestif</li>
    <li>luaPackages.gitsigns-nvim</li>
    <li>luaPackages.neotest</li>
    <li>luaPackages.nfd</li>
    <li>luaPackages.telescope-manix</li>
    <li>luaPackages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>374 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.argparse (lua52Packages.argparse)</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.compat53 (lua52Packages.compat53)</li>
    <li>luaPackages.cyan (lua52Packages.cyan)</li>
    <li>luaPackages.fzf-lua (lua52Packages.fzf-lua)</li>
    <li>luaPackages.fzy (lua52Packages.fzy)</li>
    <li>luaPackages.haskell-tools-nvim (lua52Packages.haskell-tools-nvim)</li>
    <li>luaPackages.http (lua52Packages.http)</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luaprompt (lua52Packages.luaprompt)</li>
    <li>luaPackages.luarocks-build-treesitter-parser (lua52Packages.luarocks-build-treesitter-parser)</li>
    <li>luaPackages.luarocks-build-treesitter-parser-cpp (lua52Packages.luarocks-build-treesitter-parser-cpp)</li>
    <li>luaPackages.luasystem (lua52Packages.luasystem)</li>
    <li>luaPackages.lush-nvim (lua52Packages.lush-nvim)</li>
    <li>luaPackages.lz-n (lua52Packages.lz-n)</li>
    <li>luaPackages.lzn-auto-require (lua52Packages.lzn-auto-require)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.pathlib-nvim (lua52Packages.pathlib-nvim)</li>
    <li>luaPackages.rest-nvim (lua52Packages.rest-nvim)</li>
    <li>luaPackages.rocks-config-nvim (lua52Packages.rocks-config-nvim)</li>
    <li>luaPackages.rocks-dev-nvim (lua52Packages.rocks-dev-nvim)</li>
    <li>luaPackages.rocks-git-nvim (lua52Packages.rocks-git-nvim)</li>
    <li>luaPackages.rocks-nvim (lua52Packages.rocks-nvim)</li>
    <li>luaPackages.rtp-nvim (lua52Packages.rtp-nvim)</li>
    <li>luaPackages.rustaceanvim (lua52Packages.rustaceanvim)</li>
    <li>luaPackages.sqlite (lua52Packages.sqlite)</li>
    <li>luaPackages.teal-language-server (lua52Packages.teal-language-server)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.tree-sitter-norg (lua52Packages.tree-sitter-norg)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.lush-nvim</li>
    <li>luajitPackages.lz-n</li>
    <li>luajitPackages.lze</li>
    <li>luajitPackages.lzn-auto-require</li>
    <li>luajitPackages.moonscript [...]

2024-09-20 06:05 UTC, GaetanLepage commented
Result of `nixpkgs-review pr 342196` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>28 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luaPackages.digestif</li>
    <li>luaPackages.gitsigns-nvim</li>
    <li>luaPackages.neotest</li>
    <li>luaPackages.nfd</li>
    <li>luaPackages.telescope-manix</li>
    <li>luaPackages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>5 packages failed to build:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.sqlite</li>
    <li>luaPackages.sqlite (lua52Packages.sqlite)</li>
  </ul>
</details>
<details>
  <summary>356 packages built:</summary>
  <ul>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>luaPackages.argparse (lua52Packages.argparse)</li>
    <li>luaPackages.busted (lua52Packages.busted)</li>
    <li>luaPackages.compat53 (lua52Packages.compat53)</li>
    <li>luaPackages.cyan (lua52Packages.cyan)</li>
    <li>luaPackages.fzf-lua (lua52Packages.fzf-lua)</li>
    <li>luaPackages.fzy (lua52Packages.fzy)</li>
    <li>luaPackages.haskell-tools-nvim (lua52Packages.haskell-tools-nvim)</li>
    <li>luaPackages.http (lua52Packages.http)</li>
    <li>luaPackages.llscheck (lua52Packages.llscheck)</li>
    <li>luaPackages.luacheck (lua52Packages.luacheck)</li>
    <li>luaPackages.luaprompt (lua52Packages.luaprompt)</li>
    <li>luaPackages.luarocks-build-treesitter-parser (lua52Packages.luarocks-build-treesitter-parser)</li>
    <li>luaPackages.luarocks-build-treesitter-parser-cpp (lua52Packages.luarocks-build-treesitter-parser-cpp)</li>
    <li>luaPackages.luasystem (lua52Packages.luasystem)</li>
    <li>luaPackages.lush-nvim (lua52Packages.lush-nvim)</li>
    <li>luaPackages.lz-n (lua52Packages.lz-n)</li>
    <li>luaPackages.lzn-auto-require (lua52Packages.lzn-auto-require)</li>
    <li>luaPackages.moonscript (lua52Packages.moonscript)</li>
    <li>luaPackages.pathlib-nvim (lua52Packages.pathlib-nvim)</li>
    <li>luaPackages.rest-nvim (lua52Packages.rest-nvim)</li>
    <li>luaPackages.rocks-config-nvim (lua52Packages.rocks-config-nvim)</li>
    <li>luaPackages.rocks-dev-nvim (lua52Packages.rocks-dev-nvim)</li>
    <li>luaPackages.rocks-git-nvim (lua52Packages.rocks-git-nvim)</li>
    <li>luaPackages.rocks-nvim (lua52Packages.rocks-nvim)</li>
    <li>luaPackages.rtp-nvim (lua52Packages.rtp-nvim)</li>
    <li>luaPackages.rustaceanvim (lua52Packages.rustaceanvim)</li>
    <li>luaPackages.teal-language-server (lua52Packages.teal-language-server)</li>
    <li>luaPackages.tl (lua52Packages.tl)</li>
    <li>luaPackages.tree-sitter-norg (lua52Packages.tree-sitter-norg)</li>
    <li>luaPackages.vusted (lua52Packages.vusted)</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.lush-nvim</li>
    <li>luajitPackages.lz-n</li>
    <li>luajitPackages. [...]

2024-09-20 06:11 UTC, GaetanLepage commented
> Result of `nixpkgs-review pr 342196` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)

We still have some failures on darwin unfortunately.
Even trying to build those packages sequentially does not solve the issue.

Logs (`sqlite`)

<detail>

```
Fail    ||      sqlite.db :open/:close creates new persistence database.
            ./lua/sqlite/stmt.lua:35: sqlite.lua: sql statement parse, , stmt: `insert into todo(title, desc, created) values(:title, :desc, :created) `, err: `(`table todo has no c>

            stack traceback:
                ./lua/sqlite/stmt.lua:35: in function 'parse'
                ./lua/sqlite/db.lua:278: in function 'eval'
                ...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:85: in function <...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:79>

Fail    ||      sqlite.db :open/:close connects to pre-existent database.
            ...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:99: attempt to index a nil value

            stack traceback:
                ...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:99: in function <...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:94>

Success ||      sqlite.db :open/:close returns data and time of creation
Success ||      sqlite.db :open/:close should accept pargma options
Fail    ||      sqlite.db :open/:close reopen db object.
            ./lua/sqlite/assert.lua:47: sqlite.lua: eval has failed to execute statement, ERRMSG: attempt to write a readonly database

            stack traceback:
                ./lua/sqlite/assert.lua:47: in function 'should_eval'
                ./lua/sqlite/db.lua:320: in function 'eval'
                ...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:126: in function <...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:122>

Fail    ||      sqlite.db :open_with works with initalized sql objects.
            ./lua/sqlite/assert.lua:47: sqlite.lua: eval has failed to execute statement, ERRMSG: attempt to write a readonly database

            stack traceback:
                ./lua/sqlite/assert.lua:47: in function 'should_eval'
                ./lua/sqlite/db.lua:320: in function 'eval'
                ...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:145: in function <...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:141>

Fail    ||      sqlite.db :open_with works without initalizing sql objects. (via uri)
            ./lua/sqlite/assert.lua:47: sqlite.lua: eval has failed to execute statement, ERRMSG: attempt to write a readonly database

            stack traceback:
                ./lua/sqlite/assert.lua:47: in function 'should_eval'
                ./lua/sqlite/db.lua:320: in function 'eval'
                ...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:162: in function 'func'
                ./lua/sqlite/db.lua:209: in function 'with_open'
                ...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:159: in function <...ua5.2-sqlite-v1.2.2-0.drv-0/source/test/auto/db_spec.lua:158>
```

</details>

2024-09-20 07:47 UTC, mrcjkb commented
How about we disable checks for `luaPackages.sqlite` on darwin for now and open an issue to get them fixed (either here or upstream)?

2024-09-20 08:59 UTC, GaetanLepage commented
> How about we disable checks for `luaPackages.sqlite` on darwin for now and open an issue to get them fixed (either here or upstream)?

Sure, good idea.

2024-09-20 13:07 UTC, khaneliman commented
Result of `nixpkgs-review pr 342196` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>22 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>374 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>lua52Packages.argparse</li>
    <li>lua52Packages.busted</li>
    <li>lua52Packages.compat53</li>
    <li>lua52Packages.cyan</li>
    <li>lua52Packages.fzf-lua</li>
    <li>lua52Packages.fzy</li>
    <li>lua52Packages.haskell-tools-nvim</li>
    <li>lua52Packages.http</li>
    <li>lua52Packages.llscheck</li>
    <li>lua52Packages.luacheck</li>
    <li>lua52Packages.luaprompt</li>
    <li>lua52Packages.luarocks-build-treesitter-parser</li>
    <li>lua52Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua52Packages.luasystem</li>
    <li>lua52Packages.lush-nvim</li>
    <li>lua52Packages.lz-n</li>
    <li>lua52Packages.lzn-auto-require</li>
    <li>lua52Packages.moonscript</li>
    <li>lua52Packages.pathlib-nvim</li>
    <li>lua52Packages.rest-nvim</li>
    <li>lua52Packages.rocks-config-nvim</li>
    <li>lua52Packages.rocks-dev-nvim</li>
    <li>lua52Packages.rocks-git-nvim</li>
    <li>lua52Packages.rocks-nvim</li>
    <li>lua52Packages.rtp-nvim</li>
    <li>lua52Packages.rustaceanvim</li>
    <li>lua52Packages.sqlite</li>
    <li>lua52Packages.teal-language-server</li>
    <li>lua52Packages.tl</li>
    <li>lua52Packages.tree-sitter-norg</li>
    <li>lua52Packages.vusted</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.lush-nvim</li>
    <li>luajitPackages.lz-n</li>
    <li>luajitPackages.lze</li>
    <li>luajitPackages.lzn-auto-require</li>
    <li>luajitPackages.moonscript</li>
    <li>luajitPackages.nfd</li>
    <li>luajitPackages.pathlib-nvim</li>
    <li>luajitPackages.rest-nvim</li>
    <li>luajitPackages.rocks-config-nvim</li>
    <li>luajitPackages.rocks-dev-nvim</li>
    <li>luajitPackages.rocks-git-nvim</li>
    <li>luajitPackages.rocks-nvim</li>
    <li>luajitPackages.rtp-nvim</li>
    <li>luajitPackages.rustaceanvim</li>
    <li>luajitPackages.sqlite</li>
    <li>luajitPackages.teal-language-server</li>
    <li>luajitPackages.telescope-manix</li>
    <li>luajitPackages.telescope-nvim</li>
    <li>luajitPackages.tl</li>
    <li>luajitPackages.tree-sitter-norg</li>
    <li>luajitPackages.vusted</li>
    <li>mpvScripts.mpv-webm</li>
    <li>nelua</li>
    <li>nvimpager</li>
    <li>rehex</li>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.CopilotChat-nvim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.advanced-git-search-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li>vi [...]

2024-09-20 13:11 UTC, khaneliman commented
Result of `nixpkgs-review pr 342196` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>374 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>lua52Packages.argparse</li>
    <li>lua52Packages.busted</li>
    <li>lua52Packages.compat53</li>
    <li>lua52Packages.cyan</li>
    <li>lua52Packages.fzf-lua</li>
    <li>lua52Packages.fzy</li>
    <li>lua52Packages.haskell-tools-nvim</li>
    <li>lua52Packages.http</li>
    <li>lua52Packages.llscheck</li>
    <li>lua52Packages.luacheck</li>
    <li>lua52Packages.luaprompt</li>
    <li>lua52Packages.luarocks-build-treesitter-parser</li>
    <li>lua52Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua52Packages.luasystem</li>
    <li>lua52Packages.lush-nvim</li>
    <li>lua52Packages.lz-n</li>
    <li>lua52Packages.lzn-auto-require</li>
    <li>lua52Packages.moonscript</li>
    <li>lua52Packages.pathlib-nvim</li>
    <li>lua52Packages.rest-nvim</li>
    <li>lua52Packages.rocks-config-nvim</li>
    <li>lua52Packages.rocks-dev-nvim</li>
    <li>lua52Packages.rocks-git-nvim</li>
    <li>lua52Packages.rocks-nvim</li>
    <li>lua52Packages.rtp-nvim</li>
    <li>lua52Packages.rustaceanvim</li>
    <li>lua52Packages.sqlite</li>
    <li>lua52Packages.teal-language-server</li>
    <li>lua52Packages.tl</li>
    <li>lua52Packages.tree-sitter-norg</li>
    <li>lua52Packages.vusted</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.lush-nvim</li>
    <li>luajitPackages.lz-n</li>
    <li>luajitPackages.lze</li>
    <li>luajitPackages.lzn-auto-require</li>
    <li>luajitPackages.moonscript</li>
    <li>luajitPackages.nfd</li>
    <li>luajitPackages.pathlib-nvim</li>
    <li>luajitPackages.rest-nvim</li>
    <li>luajitPackages.rocks-config-nvim</li>
    <li>luajitPackages.rocks-dev-nvim</li>
    <li>luajitPackages.rocks-git-nvim</li>
    <li>luajitPackages.rocks-nvim</li>
    <li>luajitPackages.rtp-nvim</li>
    <li>luajitPackages.rustaceanvim</li>
    <li>luajitPackages.sqlite</li>
    <li>luajitPackages.teal-language-server</li>
    <li>luajitPackages.telescope-manix</li>
    <li>luajitPackages.telescope-nvim</li>
    <li>luajitPackages.tl</li>
    <li>luajitPackages.tree-sitter-norg</li>
    <li>luajitPackages.vusted</li>
    <li>mpvScripts.mpv-webm</li>
    <li>nelua</li>
    <li>nvimpager</li>
    <li>rehex</li>
    <li>vimPlugins.ChatGPT-nvim</li>
    <li>vimPlugins.CopilotChat-nvim</li>
    <li>vimPlugins.LeaderF</li>
    <li>vimPlugins.SchemaStore-nvim</li>
    <li>vimPlugins.YouCompleteMe</li>
    <li>vimPlugins.advanced-git-search-nvim</li>
    <li>vimPlugins.aerial-nvim</li>
    <li> [...]

2024-09-20 13:40 UTC, khaneliman commented
Result of `nixpkgs-review pr 342196` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>21 packages marked as broken and skipped:</summary>
  <ul>
    <li>lua51Packages.digestif</li>
    <li>lua52Packages.digestif</li>
    <li>lua52Packages.gitsigns-nvim</li>
    <li>lua52Packages.neotest</li>
    <li>lua52Packages.nfd</li>
    <li>lua52Packages.telescope-manix</li>
    <li>lua52Packages.telescope-nvim</li>
    <li>lua53Packages.gitsigns-nvim</li>
    <li>lua53Packages.neotest</li>
    <li>lua53Packages.nfd</li>
    <li>lua53Packages.telescope-manix</li>
    <li>lua53Packages.telescope-nvim</li>
    <li>lua54Packages.gitsigns-nvim</li>
    <li>lua54Packages.http</li>
    <li>lua54Packages.lush-nvim</li>
    <li>lua54Packages.neotest</li>
    <li>lua54Packages.nfd</li>
    <li>lua54Packages.telescope-manix</li>
    <li>lua54Packages.telescope-nvim</li>
    <li>luajitPackages.digestif</li>
    <li>luajitPackages.neotest</li>
  </ul>
</details>
<details>
  <summary>9 packages failed to build:</summary>
  <ul>
    <li>rehex</li>
    <li>vimPlugins.ddc-filter-matcher_head</li>
    <li>vimPlugins.ddc-filter-sorter_rank</li>
    <li>vimPlugins.ddc-source-lsp</li>
    <li>vimPlugins.ddc-ui-native</li>
    <li>vimPlugins.ddc-ui-pum</li>
    <li>vimPlugins.ddc-vim</li>
    <li>vimPlugins.denops-vim</li>
    <li>vimPlugins.vim-pluto</li>
  </ul>
</details>
<details>
  <summary>365 packages built:</summary>
  <ul>
    <li>knot-resolver</li>
    <li>knot-resolver.dev</li>
    <li>lua51Packages.argparse</li>
    <li>lua51Packages.busted</li>
    <li>lua51Packages.compat53</li>
    <li>lua51Packages.cyan</li>
    <li>lua51Packages.fzf-lua</li>
    <li>lua51Packages.fzy</li>
    <li>lua51Packages.gitsigns-nvim</li>
    <li>lua51Packages.haskell-tools-nvim</li>
    <li>lua51Packages.http</li>
    <li>lua51Packages.llscheck</li>
    <li>lua51Packages.luacheck</li>
    <li>lua51Packages.luaprompt</li>
    <li>lua51Packages.luarocks-build-treesitter-parser</li>
    <li>lua51Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua51Packages.luasystem</li>
    <li>lua51Packages.lush-nvim</li>
    <li>lua51Packages.lz-n</li>
    <li>lua51Packages.lze</li>
    <li>lua51Packages.lzn-auto-require</li>
    <li>lua51Packages.moonscript</li>
    <li>lua51Packages.neotest</li>
    <li>lua51Packages.nfd</li>
    <li>lua51Packages.pathlib-nvim</li>
    <li>lua51Packages.rest-nvim</li>
    <li>lua51Packages.rocks-config-nvim</li>
    <li>lua51Packages.rocks-dev-nvim</li>
    <li>lua51Packages.rocks-git-nvim</li>
    <li>lua51Packages.rocks-nvim</li>
    <li>lua51Packages.rtp-nvim</li>
    <li>lua51Packages.rustaceanvim</li>
    <li>lua51Packages.sqlite</li>
    <li>lua51Packages.teal-language-server</li>
    <li>lua51Packages.telescope-manix</li>
    <li>lua51Packages.telescope-nvim</li>
    <li>lua51Packages.tl</li>
    <li>lua51Packages.tree-sitter-norg</li>
    <li>lua51Packages.vusted</li>
    <li>lua52Packages.argparse</li>
    <li>lua52Packages.busted</li>
    <li>lua52Packages.compat53</li>
    <li>lua52Packages.cyan</li>
    <li>lua52Packages.fzf-lua</li>
    <li>lua52Packages.fzy</li>
    <li>lua52Packages.haskell-tools-nvim</li>
    <li>lua52Packages.http</li>
    <li>lua52Packages.llscheck</li>
    <li>lua52Packages.luacheck</li>
    <li>lua52Packages.luaprompt</li>
    <li>lua52Packages.luarocks-build-treesitter-parser</li>
    <li>lua52Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua52Packages.luasystem</li>
    <li>lua52Packages.lush-nvim</li>
    <li>lua52Packages.lz-n</li>
    <li>lua52Packages.lzn-auto-require</li>
    <li>lua52Packages.moonscript</li>
    <li>lua52Packages.pathlib-nvim</li>
    <li>lua52Packages.rest-nvim</li>
    <li>lua52Packages.rocks-config-nvim</li>
    <li>lua52Packages.rocks-dev-nvim</li>
    <li>lua52Packages.rocks-git-nvim</li>
    <li>lua52Packages.rocks-nvim</li>
    <li>lua52Packages.rtp-nvim</li>
    <li>lua52Packages.rustaceanvim</li>
    <li>lua52Packages.sqlite</li>
    <li>lua52Packages.teal-language-server</li>
    <li>lua52Packages.tl</li>
    <li>lua52Packages.tree-sitter-norg</li>
    <li>lua52Packages.vusted</li>
    <li>lua53Packages.argparse</li>
    <li>lua53Packages.busted</li>
    <li>lua53Packages.compat53</li>
    <li>lua53Packages.cyan</li>
    <li>lua53Packages.digestif</li>
    <li>lua53Packages.fzf-lua</li>
    <li>lua53Packages.fzy</li>
    <li>lua53Packages.haskell-tools-nvim</li>
    <li>lua53Packages.http</li>
    <li>lua53Packages.llscheck</li>
    <li>lua53Packages.luacheck</li>
    <li>lua53Packages.luaprompt</li>
    <li>lua53Packages.luarocks-build-treesitter-parser</li>
    <li>lua53Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua53Packages.luasystem</li>
    <li>lua53Packages.lush-nvim</li>
    <li>lua53Packages.lz-n</li>
    <li>lua53Packages.lzn-auto-require</li>
    <li>lua53Packages.moonscript</li>
    <li>lua53Packages.pathlib-nvim</li>
    <li>lua53Packages.rest-nvim</li>
    <li>lua53Packages.rocks-config-nvim</li>
    <li>lua53Packages.rocks-dev-nvim</li>
    <li>lua53Packages.rocks-git-nvim</li>
    <li>lua53Packages.rocks-nvim</li>
    <li>lua53Packages.rtp-nvim</li>
    <li>lua53Packages.rustaceanvim</li>
    <li>lua53Packages.sqlite</li>
    <li>lua53Packages.teal-language-server</li>
    <li>lua53Packages.tl</li>
    <li>lua53Packages.tree-sitter-norg</li>
    <li>lua53Packages.vusted</li>
    <li>lua54Packages.argparse</li>
    <li>lua54Packages.busted</li>
    <li>lua54Packages.compat53</li>
    <li>lua54Packages.cyan</li>
    <li>lua54Packages.digestif</li>
    <li>lua54Packages.fzf-lua</li>
    <li>lua54Packages.fzy</li>
    <li>lua54Packages.haskell-tools-nvim</li>
    <li>lua54Packages.llscheck</li>
    <li>lua54Packages.luacheck</li>
    <li>lua54Packages.luaprompt</li>
    <li>lua54Packages.luarocks-build-treesitter-parser</li>
    <li>lua54Packages.luarocks-build-treesitter-parser-cpp</li>
    <li>lua54Packages.luasystem</li>
    <li>lua54Packages.lz-n</li>
    <li>lua54Packages.lzn-auto-require</li>
    <li>lua54Packages.moonscript</li>
    <li>lua54Packages.pathlib-nvim</li>
    <li>lua54Packages.rest-nvim</li>
    <li>lua54Packages.rocks-config-nvim</li>
    <li>lua54Packages.rocks-dev-nvim</li>
    <li>lua54Packages.rocks-git-nvim</li>
    <li>lua54Packages.rocks-nvim</li>
    <li>lua54Packages.rtp-nvim</li>
    <li>lua54Packages.rustaceanvim</li>
    <li>lua54Packages.sqlite</li>
    <li>lua54Packages.teal-language-server</li>
    <li>lua54Packages.tl</li>
    <li>lua54Packages.tree-sitter-norg</li>
    <li>lua54Packages.vusted</li>
    <li>luajitPackages.argparse</li>
    <li>luajitPackages.busted</li>
    <li>luajitPackages.compat53</li>
    <li>luajitPackages.cyan</li>
    <li>luajitPackages.fzf-lua</li>
    <li>luajitPackages.fzy</li>
    <li>luajitPackages.gitsigns-nvim</li>
    <li>luajitPackages.haskell-tools-nvim</li>
    <li>luajitPackages.http</li>
    <li>luajitPackages.llscheck</li>
    <li>luajitPackages.luacheck</li>
    <li>luajitPackages.luaprompt</li>
    <li>luajitPackages.luarocks-build-treesitter-parser</li>
    <li>luajitPackages.luarocks-build-treesitter-parser-cpp</li>
    <li>luajitPackages.luasystem</li>
    <li>luajitPackages.lush-nvim</li>
    <li>luajitPackages.lz-n</li>
    <li>luajitPackages.lze</li>
    <li>luajitPackages.lzn-auto-require</li>
    <li>luajitPackages.moonscript</li>
    <li>luajitPackages.nfd</li>
    <li>luajitPackages.pathlib-nvim</li>
    <li>luajitPackages.rest-nvim</li>
    <li>luajitPackages.rocks-config-nvim</li>
    <li>luajitPackages.rocks-dev-nvim</li>
    <li>luajitPackages.rocks-git-nvim</li>
    <li>luajitPackages.rocks-nvim</li>
    <li>luajitPackages.rtp-nvim</li>
    <li>luajitPackages.rustaceanvim</li>
    <li>luajitPackages.sqlite</li>
    <li>luajitPackages.teal-language-server</li>
    <li>luajitPackages.telescope-manix</li>
    <li>luajitPackages.telescope-nvim</li>
    <li>luajitPackages.tl</li>
    <li>luajitPackages.tree-sitter-norg</li>
 [...]

2024-09-20 13:41 UTC, khaneliman commented
> Result of `nixpkgs-review pr 342196` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
> 21 packages marked as broken and skipped:
> 
> 
> 9 packages failed to build:
> 
>     * rehex
> 
>     * vimPlugins.ddc-filter-matcher_head
> 
>     * vimPlugins.ddc-filter-sorter_rank
> 
>     * vimPlugins.ddc-source-lsp
> 
>     * vimPlugins.ddc-ui-native
> 
>     * vimPlugins.ddc-ui-pum
> 
>     * vimPlugins.ddc-vim
> 
>     * vimPlugins.denops-vim
> 
>     * vimPlugins.vim-pluto
> 
> 
> 365 packages built:

Failures I saw were due to already broken dependencies on master.

2024-09-20 16:32 UTC, GaetanLepage approved these changes
Thanks for this nice effort @khaneliman !

2024-09-20 16:33 UTC, merged

2024-09-23 11:38 UTC, linsui commented
This PR renamed render-markdown-nvim to render-markdown because the script was run before https://github.com/NixOS/nixpkgs/pull/340286 was merged. Shuold I fix it with a PR? Or you will run the script soon?

2024-09-23 11:47 UTC, GaetanLepage commented
Yes indeed, I am working on it in https://github.com/NixOS/nixpkgs/pull/343557.

2025-03-15 11:27 UTC, vcunat commented
FYI, this merge broke `lua.tests.checkPropagatedBuildInputs`  (and the same with luajit)

2025-03-15 14:08 UTC, khaneliman commented
> FYI, this merge broke `lua.tests.checkPropagatedBuildInputs` (and the same with luajit)

Thanks, looks like we coded a check for a dependency that was removed with the rest.nvim bump. will update soon.