ninjabrain-bot: init at 1.4.3
NixOS/nixpkgs pull request #342187
Opened 2024-09-16 01:54 UTC by EmilioBarradas

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-17 13:47 UTC, FliegendeWurst requested changes
Result of `nixpkgs-review pr 342187` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

2024-10-17 22:52 UTC, EmilioBarradas commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +    maintainers = with lib.maintainers; [ emilio-barradas ];
Hey, from looking at this program's repository, it seems like it doesn't have a license. Does this mean I should set `meta.license` to `unfree`?

2024-10-18 06:31 UTC, FliegendeWurst commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +    maintainers = with lib.maintainers; [ emilio-barradas ];
In that case, unfree is correct. You could also ask Ninjabrain to provide a license. But then all 20 contributors have to agree on a license..

2024-10-19 22:18 UTC, EmilioBarradas commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +    maintainers = with lib.maintainers; [ emilio-barradas ];
I've gone ahead and set the license to unfree.

2024-10-19 22:27 UTC, EmilioBarradas commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 342187`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

2024-10-20 08:22 UTC, FliegendeWurst commented
Please rebase your commits on master instead of merging.

2024-10-20 15:57 UTC, FliegendeWurst requested changes

2024-10-20 15:57 UTC, FliegendeWurst commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +    description = "Accurate stronghold calculator for Minecraft speedrunning.";
```suggestion
    description = "Accurate stronghold calculator for Minecraft speedrunning";
```

2024-10-20 15:57 UTC, FliegendeWurst commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +      comment = "Accurate stronghold calculator for Minecraft speedrunning.";
```suggestion
      comment = "Accurate stronghold calculator for Minecraft speedrunning";
```

2024-10-20 15:57 UTC, FliegendeWurst commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +    makeWrapper ${jre}/bin/java $out/bin/ninjabrain-bot \
```suggestion
    makeWrapper ${lib.getExe jre} $out/bin/ninjabrain-bot \
```

2024-10-24 05:49 UTC, FliegendeWurst approved these changes

2024-10-24 05:50 UTC, FliegendeWurst commented
It would be good to squash all packaging commits into a single "ninjabrain-bot: init at 1.4.3"

2024-12-15 16:06 UTC, wolfgangwalther requested changes
Please rebase, so you end up with two commits in this order:
- maintainers: add emilio-barradas
- ninjabrain-bot: init at 1.5.1

2026-01-01 18:05 UTC, EmilioBarradas commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +  pkgs,
Updated

2026-01-07 11:30 UTC, wolfgangwalther commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 342187`
Commit: `d7a9a0a08f017f24901d23e62cba624191c791c2`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>

2026-01-07 11:30 UTC, wolfgangwalther commented
Build appears to be failing because of a wrong hash.

2026-01-08 05:25 UTC, EmilioBarradas commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 342187`
Commit: `f10298c9115f11c5c51353c96a08e3d4c3124b4d`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

2026-01-08 05:25 UTC, EmilioBarradas commented
> Build appears to be failing because of a wrong hash.

oof... I've gone ahead and updated the hash and posted my nixpkgs-review result

2026-01-08 09:21 UTC, wolfgangwalther submitted a review, later dismissed
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 342187`
Commit: `f10298c9115f11c5c51353c96a08e3d4c3124b4d`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

2026-01-15 05:27 UTC, EmilioBarradas commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 342187`
Commit: `6dd1cec62bf185aa5176b21944c3092e08991491`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ninjabrain-bot</li>
  </ul>
</details>

2026-01-15 08:19 UTC, wolfgangwalther commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +  doCheck = false;
Alternatively you could just bump the version to `1.5.1-unstable-XXXX`, aka use the latest commit on their main branch instead of the test.

2026-01-31 16:35 UTC, D4ndellion commented on pkgs/by-name/ni/ninjabrain-bot/package.nix
> +  doCheck = false;
Doing this would also allow changing the license to GPL, rather than unfree which would be nice

2026-01-31 17:59 UTC, D4ndellion commented
Tests fail again for me

2026-06-14 15:40 UTC, Misaka13514 commented
1.5.2 is available

2026-07-27 05:32 UTC, llakala commented
Done in #531299

2026-07-27 05:32 UTC, closed without merging