Pyrseas: init at 0.8.0
NixOS/nixpkgs pull request #34225
Opened 2018-01-24 13:42 UTC by P-E-Meunier

Pyrseas is a declarative tool for managing PostgreSQL schemas.

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-01-24 15:24 UTC, FRidh requested changes

2018-01-24 15:24 UTC, FRidh commented on pkgs/development/tools/database/pyrseas/default.nix
> +{ stdenv, python27Packages, fetchFromGitHub }:
Don't use `python27Packages`. If it works with both 2 and 3, then use `pythonPackages`. If it only works with 2, then `python2Packages`. We don't support `< 2.7` anymore.

2018-01-24 15:24 UTC, FRidh commented on pkgs/development/tools/database/pyrseas/default.nix
> +let
how about using a `with pythonPackages` on the top? It would remove a lot of noise.

2018-01-24 15:24 UTC, FRidh commented on pkgs/development/tools/database/pyrseas/default.nix
> +    name = "pgdbconn-${version}";
`pname` and `version` instead of `name`

2018-01-24 15:24 UTC, FRidh commented on pkgs/development/tools/database/pyrseas/default.nix
> +    doCheck = false;
can you include a comment explaining why the tests are disabled

2018-01-24 15:24 UTC, FRidh commented on pkgs/development/tools/database/pyrseas/default.nix
> +python27Packages.buildPythonPackage rec {
This is an application, so `buildPythonApplication`

2018-01-24 15:24 UTC, FRidh commented on pkgs/development/tools/database/pyrseas/default.nix
> +  name = "pyrseas-${version}";
`pname` and version` instead of `name`

2018-01-24 15:24 UTC, FRidh commented on pkgs/development/tools/database/pyrseas/default.nix
> +  doCheck = false;
comment with explanation

2018-01-24 20:29 UTC, jtojnar commented on pkgs/development/tools/database/pyrseas/default.nix
> +python2Packages.buildPythonPackage rec {
Does not it work with python 3? Python 2.7 or higher is listed in the README.

2018-01-29 17:14 UTC, FRidh commented
@GrahamcOfBorg build pyrseas

2018-01-29 17:15 UTC, GrahamcOfBorg reviewed
Success on x86_64-linux [(full log)](https://logs.nix.gsc.io/?key=nixos/nixpkgs.34225)

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0
strip is /nix/store/mdyy001q67hiks0g24ra53z7ckm4jfr4-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0/lib  /nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0/bin 
patching script interpreter paths in /nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0
checking for references to /tmp/nix-build-pyrseas-0.8.0.drv-0 in /nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0...
wrapping `/nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0/bin/dbaugment'...
wrapping `/nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0/bin/dbtoyaml'...
wrapping `/nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0/bin/yamltodb'...
/nix/store/hj7byq7fhnv4a38zsdi5zrn2xwddmp3c-pyrseas-0.8.0
```
</p></details>

2018-01-29 17:15 UTC, GrahamcOfBorg reviewed
Success on aarch64-linux [(full log)](https://logs.nix.gsc.io/?key=nixos/nixpkgs.34225)

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0
strip is /nix/store/jwz859pxqj7sl2dbwvmxkx68jp774izb-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0/lib  /nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0/bin
patching script interpreter paths in /nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0
checking for references to /build in /nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0...
wrapping `/nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0/bin/dbaugment'...
wrapping `/nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0/bin/yamltodb'...
wrapping `/nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0/bin/dbtoyaml'...
/nix/store/1y5agz75k2hrv6wligbmpdhfazfhpdkr-pyrseas-0.8.0
```
</p></details>

2018-01-29 17:16 UTC, GrahamcOfBorg reviewed
Success on x86_64-darwin [(full log)](https://logs.nix.gsc.io/?key=nixos/nixpkgs.34225)

<details><summary>Partial log (click to expand)</summary><p>

```
Successfully installed Pyrseas-0.8.0
/private/tmp/nix-build-pyrseas-0.8.0.drv-0/source
post-installation fixup
strip is /nix/store/i1zz228nl3bljcbb83fq0rq7lr7nvv4y-cctools-binutils-darwin/bin/strip
stripping (with command strip and flags -S) in /nix/store/bia63icr92q8m7bf6kqy2q2j3ydyjdkj-pyrseas-0.8.0/lib  /nix/store/bia63icr92q8m7bf6kqy2q2j3ydyjdkj-pyrseas-0.8.0/bin
patching script interpreter paths in /nix/store/bia63icr92q8m7bf6kqy2q2j3ydyjdkj-pyrseas-0.8.0
wrapping `/nix/store/bia63icr92q8m7bf6kqy2q2j3ydyjdkj-pyrseas-0.8.0/bin/dbaugment'...
wrapping `/nix/store/bia63icr92q8m7bf6kqy2q2j3ydyjdkj-pyrseas-0.8.0/bin/dbtoyaml'...
wrapping `/nix/store/bia63icr92q8m7bf6kqy2q2j3ydyjdkj-pyrseas-0.8.0/bin/yamltodb'...
/nix/store/bia63icr92q8m7bf6kqy2q2j3ydyjdkj-pyrseas-0.8.0
```
</p></details>

2018-01-29 17:17 UTC, merged