sov: adopt and nixfmt-rfc-style
NixOS/nixpkgs pull request #342841
Opened 2024-09-18 16:51 UTC by AndersonTorres

## Description of changes

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-21 16:29 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4598

2024-11-03 19:55 UTC, FliegendeWurst requested changes
ofborg build fails for Mac
```
> [52/125] Compiling C object sov.p/src_kinetic_ui_ku_connector_wayland.c.o
> FAILED: sov.p/src_kinetic_ui_ku_connector_wayland.c.o
> clang -Isov.p -I. -I.. -I../src/mt_math -I../src/mt_core -I../src/kinetic_ui -I../src/kinetic_ui/egl -I../src/kinetic_ui/handler -I../src/kinetic_ui/texture -I../src/sov -I../src/mt_core_ext -I/nix/store/4sab8cjjn6m7f54hr0ay22g8ym2b810j-wayland-1.23.1-dev/include -I/nix/store/i5zfm1vbiw6b5yjhgq7cpmfbjglj6dxl-libpng-apng-1.6.43-dev/include/libpng16 -I/nix/store/4cfmry9jix68f315fzvr5arrwjp63php-freetype-2.13.2-dev/include/freetype2 -I/nix/store/js42yl78d8d4xriz81xkj5vah9lcmrmq-libglvnd-1.7.0-dev/include -I/nix/store/gr8kxqrgvajx66n3p0pqymf2mji60kxy-libxkbcommon-1.7.0-dev/include -fdiagnostics-color=always -Wall -Winvalid-pch -Wextra -Wpedantic -std=gnu99 '-DPKG_DATADIR="/nix/store/7sxm5i5fn996vgychk8azkfhrf56wsmc-sov-0.94/share/sov"' '-DSOV_VERSION="0.93"' -Wno-unused-parameter -MD -MQ sov.p/src_kinetic_ui_ku_connector_wayland.c.o -MF sov.p/src_kinetic_ui_ku_connector_wayland.c.o.d -o sov.p/src_kinetic_ui_ku_connector_wayland.c.o -c ../src/kinetic_ui/ku_connector_wayland.c
> ../src/kinetic_ui/ku_connector_wayland.c:21:10: fatal error: 'sys/timerfd.h' file not found
> #include <sys/timerfd.h>
>          ^~~~~~~~~~~~~~~
> 1 error generated.
> ninja: build stopped: subcommand failed.
```

2024-11-07 02:36 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4809

2024-11-07 02:36 UTC, Aleksanaa approved these changes

2024-11-18 21:13 UTC, merged