Updated thelounge to 4.4.3
NixOS/nixpkgs pull request #343550
Opened 2024-09-21 19:02 UTC by Duckle29

## Description of changes
Increased version to 4.4.3 which adds auto log culling.

Had to pin python to 3.11, as distutil is removed in 3.12, and setuptools to nativebuildtools didn't seem to help.

Changelog: https://github.com/thelounge/thelounge/releases/tag/v4.4.3

## Things done

It was tested via overrides.
This is currently building and running 
https://github.com/Duckle29/NixOS-homeserver/blob/main/modules/thelounge.nix (this is pinning to 3.10, but recently also just tested with 3.11 and it works too)

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-21 20:23 UTC, Duckle29 commented
Sorry for the force push spam. Trying to get co-authored to work.

2024-09-21 20:24 UTC, quatquatt commented
> Sorry for the force push spam. Trying to get co-authored to work.

Indeed, and IT DOESN'T WANT TO!!!

2024-09-21 20:26 UTC, quatquatt approved these changes

2024-09-22 20:29 UTC, drupol requested changes
Hash mismatch.

```
unpacking source archive /build/v4.4.3.tar.gz
error: hash mismatch in fixed-output derivation '/nix/store/igz2hq97gdhijns4xgncg7np4mbkhn2a-source.drv':
         specified: sha256-csVrgsEy9HjSBXxtgNG0hcBrR9COlcadhMQrw6BWPc4=
            got:    sha256-lDbyqVFjhF2etRx31ax7KiQ1QKgVhD8xkTog/E3pUlA=
```

2024-09-22 22:24 UTC, Duckle29 commented
> Hash mismatch.
> 
> ```
> unpacking source archive /build/v4.4.3.tar.gz
> error: hash mismatch in fixed-output derivation '/nix/store/igz2hq97gdhijns4xgncg7np4mbkhn2a-source.drv':
>          specified: sha256-csVrgsEy9HjSBXxtgNG0hcBrR9COlcadhMQrw6BWPc4=
>             got:    sha256-lDbyqVFjhF2etRx31ax7KiQ1QKgVhD8xkTog/E3pUlA=
> ```

Huh, somehow I copied the yarn cache twice. Thanks.
Should be fixed now

2024-09-25 19:36 UTC, drupol requested changes
Merge conflicts.

2024-09-25 19:48 UTC, Duckle29 commented
Thanks, should be resolved 😃

2024-09-25 20:06 UTC, drupol commented on pkgs/applications/networking/irc/thelounge/default.nix
> +  nativeBuildInputs = [ nodejs yarn fixup-yarn-lock python311 npmHooks.npmInstallHook ] ++ lib.optional stdenv.hostPlatform.isDarwin cctools;
Opinionated, but visually and semantically better:

```suggestion
  nativeBuildInputs = [ nodejs yarn fixup-yarn-lock python311 npmHooks.npmInstallHook ] ++ lib.optionals stdenv.hostPlatform.isDarwin [ cctools ];
```

2024-09-26 08:03 UTC, drupol approved these changes

2024-09-26 16:00 UTC, merged