Update client.nix
NixOS/nixpkgs pull request #344335
Opened 2024-09-25 02:10 UTC by Damage6969

Update fah-client from version 8.3.7 to 8.3.18. No other changes

## Description of changes

## Things done

- Built on platform(s)
  - [ X] x86_64-linux

  - [NixOS test(s)] - None 
  - 

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-27 04:17 UTC, lelgenio requested changes
Thanks for your first contribution!
There's two things that block this from being merged right now:

1. Please read [this](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging) for instructions on how to change the target branch on your PR without **spamming hundreds of contributors**, and getting this PR locked. Follow the linked instructions to change the target branch to `master`.

2. Also the commit message should follow the repositories' convention:
`fahclient: 8.3.7 -> 8.3.18`

2024-09-28 16:10 UTC, Atemu commented
@lelgenio Unstable can always be changed to master safely as it's, by definition, always behind or at worst equal to master ;)

@Damage6969 please change the commit and PR title though.

2024-10-01 14:48 UTC, merged

2024-10-01 14:49 UTC, zimbatm commented
thanks!

2024-10-01 16:42 UTC, Atemu commented
Uhm, the commit title wasn't changed, I only changed the PR title.

2024-10-01 19:21 UTC, Atemu commented
Ah, it was rebase-"merged". That's a bit unusual which threw me off but not unheard of either.