rPackages.{sf, terra, vapour}: fix builds on darwin
NixOS/nixpkgs pull request #344498
Opened 2024-09-25 18:35 UTC by b-rodrigues

## Description of changes

These three packages need their definitions overridden to build successfully on darwin. This doesn't impact them on linux-x86. I tested on darwin, but would like someone with actual apple hardware to review this PR: pinging @philipp-baumann for this :)

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-25 21:40 UTC, philipp-baumann commented
Confirm it works on Apple Silicon (aarch64-darwin).

```sh
nixpkgs on  pr-344498 [$?] took 1m 16.2s 
➜ nix-shell -I nixpkgs=. -p rPackages.terra R

[nix-shell:~/git/nixpkgs]$ R

R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: aarch64-apple-darwin23.6.0

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

[Previously saved workspace restored]

> .libPaths()
[1] "/nix/store/by00zpyy1kvgkxdm3wbi1sirh3831ik5-r-terra-1.7-78/library"                       
[2] "/nix/store/ix1w8f10h1mpc9nhamrj2fdni4gks4ll-r-Rcpp-1.0.13/library"                        
[3] "/nix/store/kcn9w36a573nhkbl5ci7aa2vdk2q5k16-apple-framework-CoreFoundation-11.0.0/Library"
[4] "/nix/store/l5hm8k0r79bk1j2556wp1l4cmmrvza7v-R-4.4.1/lib/R/library"                        
> library(terra)
code for methods in class “Rcpp_SpatCategories” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatCategories” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatDataFrame” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatDataFrame” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatExtent” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatExtent” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatFactor” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatFactor” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatGraph” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatGraph” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatMessages” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatMessages” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatOptions” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatOptions” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRaster” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRaster” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRasterCollection” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRasterCollection” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRasterStack” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRasterStack” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatSRS” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatSRS” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatTime_v” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatTime_v” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVector” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVector” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVectorCollection” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVectorCollection” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVectorProxy” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVectorProxy” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
terra 1.7.78
```

2024-09-25 21:42 UTC, philipp-baumann commented
Output of `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`

```sh
➜ nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"
these 17 paths will be fetched (10.01 MiB download, 67.12 MiB unpacked):
  /nix/store/m0xxxwbvmfkpr2xl8xglp6pdcy2b32yr-git-2.44.0
  /nix/store/ixfyjbvrvcgjd6pvlmwd837n7gpacpsh-git-2.44.0-doc
  /nix/store/0g8hn5vicg6d2dqm4kdwdn6pfq9lhzcq-nixpkgs-review-2.10.4
  /nix/store/i18n870vd4llrmml4bbdhrxi2v6f7kkc-perl5.38.2-Authen-SASL-2.1700
  /nix/store/42knfpq1555ixls2qzskmfh5amrv5x00-perl5.38.2-CGI-4.59
  /nix/store/rfjm5lb16c0420z3k7gndj20cvnqz960-perl5.38.2-CGI-Fast-2.16
  /nix/store/500hhsq5nmyx04k8a7l8pqpjmfjgkz4h-perl5.38.2-Digest-HMAC-1.04
  /nix/store/8fgnamk1x5qv5bfsh03n0cv3s73qjpzf-perl5.38.2-FCGI-0.82
  /nix/store/p53f9kd5rg0k6yfw3q9mp32q48lrn6wf-perl5.38.2-FCGI-ProcManager-0.28
  /nix/store/p54x4bd4ary9mdp6nji2577py4r2pda0-perl5.38.2-HTML-TagCloud-0.38
  /nix/store/njjxsha30fsi0bqvzjspv0pl63fymyck-perl5.38.2-IO-Socket-SSL-2.083
  /nix/store/jx0dwd5vw93vjq5mc83hhl16clwi59nl-perl5.38.2-Mozilla-CA-20230821
  /nix/store/aldp5p07jydl75hf180lxmhq3m590aqb-perl5.38.2-Net-SMTP-SSL-1.04
  /nix/store/k1kmdqcs2m4v390w1gikvl8xrbhn68iy-perl5.38.2-Net-SSLeay-1.92
  /nix/store/8g5dd1199m3nm3dw495iz402gq7308id-perl5.38.2-TermReadKey-2.38
  /nix/store/dqmifv8llpk1r951fjzvlgf6gda0znf5-perl5.38.2-libnet-3.15
  /nix/store/isj1mv0h5ww5yg5kx3w3r40kha968iqx-python3.11-argcomplete-3.2.3
copying path '/nix/store/ixfyjbvrvcgjd6pvlmwd837n7gpacpsh-git-2.44.0-doc' from 'https://cache.nixos.org'...
copying path '/nix/store/500hhsq5nmyx04k8a7l8pqpjmfjgkz4h-perl5.38.2-Digest-HMAC-1.04' from 'https://cache.nixos.org'...
copying path '/nix/store/8fgnamk1x5qv5bfsh03n0cv3s73qjpzf-perl5.38.2-FCGI-0.82' from 'https://cache.nixos.org'...
copying path '/nix/store/p53f9kd5rg0k6yfw3q9mp32q48lrn6wf-perl5.38.2-FCGI-ProcManager-0.28' from 'https://cache.nixos.org'...
copying path '/nix/store/p54x4bd4ary9mdp6nji2577py4r2pda0-perl5.38.2-HTML-TagCloud-0.38' from 'https://cache.nixos.org'...
copying path '/nix/store/8g5dd1199m3nm3dw495iz402gq7308id-perl5.38.2-TermReadKey-2.38' from 'https://cache.nixos.org'...
copying path '/nix/store/dqmifv8llpk1r951fjzvlgf6gda0znf5-perl5.38.2-libnet-3.15' from 'https://cache.nixos.org'...
copying path '/nix/store/42knfpq1555ixls2qzskmfh5amrv5x00-perl5.38.2-CGI-4.59' from 'https://cache.nixos.org'...
copying path '/nix/store/jx0dwd5vw93vjq5mc83hhl16clwi59nl-perl5.38.2-Mozilla-CA-20230821' from 'https://cache.nixos.org'...
copying path '/nix/store/isj1mv0h5ww5yg5kx3w3r40kha968iqx-python3.11-argcomplete-3.2.3' from 'https://cache.nixos.org'...
copying path '/nix/store/k1kmdqcs2m4v390w1gikvl8xrbhn68iy-perl5.38.2-Net-SSLeay-1.92' from 'https://cache.nixos.org'...
copying path '/nix/store/i18n870vd4llrmml4bbdhrxi2v6f7kkc-perl5.38.2-Authen-SASL-2.1700' from 'https://cache.nixos.org'...
copying path '/nix/store/rfjm5lb16c0420z3k7gndj20cvnqz960-perl5.38.2-CGI-Fast-2.16' from 'https://cache.nixos.org'...
copying path '/nix/store/njjxsha30fsi0bqvzjspv0pl63fymyck-perl5.38.2-IO-Socket-SSL-2.083' from 'https://cache.nixos.org'...
copying path '/nix/store/aldp5p07jydl75hf180lxmhq3m590aqb-perl5.38.2-Net-SMTP-SSL-1.04' from 'https://cache.nixos.org'...
copying path '/nix/store/m0xxxwbvmfkpr2xl8xglp6pdcy2b32yr-git-2.44.0' from 'https://cache.nixos.org'...
copying path '/nix/store/0g8hn5vicg6d2dqm4kdwdn6pfq9lhzcq-nixpkgs-review-2.10.4' from 'https://cache.nixos.org'...
$ git -c fetch.prune=false fetch --no-tags --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0
remote: Enumerating objects: 162, done.
remote: Counting objects: 100% (153/153), done.
remote: Compressing objects: 100% (84/84), done.
remote: Total 162 (delta 86), reused 105 (delta 66), pack-reused 9 (from 1)
Receiving objects: 100% (162/162), 802.39 KiB | 6.58 MiB/s, done.
Resolving deltas: 100% (87/87), completed with 25 local objects.
From https://github.com/NixOS/nixpkgs
   feeff83e610f..1f3453492079  master     -> refs/nixpkgs-review/0
$ git worktree add /Users/philipp/.cache/nixpkgs-review/rev-3b2590eee2b057ada39066e536c3a0ebe66d2f8d/nixpkgs 1f3453492079bec1f9da77b4031de6dcaab99bd7
Preparing worktree (detached HEAD 1f3453492079)
Updating files: 100% (43407/43407), done.
HEAD is now at 1f3453492079 Systemd tpm fixes (#343307)
$ nix-env --extra-experimental-features no-url-literals --option system aarch64-darwin -f <nixpkgs> --nix-path nixpkgs=/Users/philipp/.cache/nixpkgs-review/rev-3b2590eee2b057ada39066e536c3a0ebe66d2f8d/nixpkgs nixpkgs-overlays=/tmp/tmppbbmjvj0 -qaP --xml --out-path --show-trace --no-allow-import-from-derivation

$ git merge --no-commit --no-ff 3b2590eee2b057ada39066e536c3a0ebe66d2f8d
Automatic merge went well; stopped before committing as requested
$ nix-env --extra-experimental-features no-url-literals --option system aarch64-darwin -f <nixpkgs> --nix-path nixpkgs=/Users/philipp/.cache/nixpkgs-review/rev-3b2590eee2b057ada39066e536c3a0ebe66d2f8d/nixpkgs nixpkgs-overlays=/tmp/tmppbbmjvj0 -qaP --xml --out-path --show-trace --no-allow-import-from-derivation --meta
    


Nothing to be built.
$ /nix/store/qplid9wf2bfbl3i7w6xyh0769gz7v3a2-nix-2.18.2/bin/nix-shell --argstr system aarch64-darwin --argstr nixpkgs-path /Users/philipp/.cache/nixpkgs-review/rev-3b2590eee2b057ada39066e536c3a0ebe66d2f8d/nixpkgs --argstr nixpkgs-config-path /tmp/tmpolfj_f2w.nix --argstr attrs-path /Users/philipp/.cache/nixpkgs-review/rev-3b2590eee2b057ada39066e536c3a0ebe66d2f8d/attrs.nix --nix-path nixpkgs=/Users/philipp/.cache/nixpkgs-review/rev-3b2590eee2b057ada39066e536c3a0ebe66d2f8d/nixpkgs nixpkgs-overlays=/tmp/tmppbbmjvj0 /nix/store/0g8hn5vicg6d2dqm4kdwdn6pfq9lhzcq-nixpkgs-review-2.10.4/lib/python3.11/site-packages/nixpkgs_review/nix/review-shell.nix
```

2024-09-25 21:46 UTC, philipp-baumann approved these changes
LGTM! tested on Apple Silicon

2024-09-25 23:25 UTC, jbedo commented
I think you're fixing the issue in the wrong place, the problem is `PROJ`'s pkg-config configuration file. Pkg-config on linux is patched to ignore `Requires.private` (except for static building) as all those libraries are in the rpath, not sure why this isn't ignored here on darwin though. No idea who to ping here, pkg-config has no listed maintainers.

2024-09-27 14:21 UTC, saghirb commented
Confirm it works on Intel (i386-darwin).

```
% nix-shell -I nixpkgs=. -p rPackages.terra R

[nix-shell:~/NixStuff/nixpkgs]$ R

R version 4.4.1 (2024-06-14) -- "Race for Your Life"
Copyright (C) 2024 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin23.6.0

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

During startup - Warning messages:
1: Setting LC_COLLATE failed, using "C" 
2: Setting LC_TIME failed, using "C" 
3: Setting LC_MESSAGES failed, using "C" 
4: Setting LC_MONETARY failed, using "C" 
> .libPaths()
[1] "/nix/store/hxgvhidbik7xx9v1v039vaiajb44i6bk-r-terra-1.7-78/library"                
[2] "/nix/store/ck4qmasnsr9wzwnmczpx8mr3r10fhqrn-r-Rcpp-1.0.13/library"                 
[3] "/nix/store/bbca51k12iax7zp7g9sih8j1704i0hl8-apple-framework-CoreFoundation/Library"
[4] "/nix/store/hdnr7prpixpcwwcgv24c8wa6h2qymmrf-R-4.4.1/lib/R/library"                 
> library(terra)
code for methods in class “Rcpp_SpatCategories” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatCategories” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatDataFrame” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatDataFrame” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatExtent” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatExtent” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatFactor” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatFactor” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatGraph” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatGraph” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatMessages” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatMessages” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatOptions” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatOptions” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRaster” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRaster” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRasterCollection” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRasterCollection” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRasterStack” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatRasterStack” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatSRS” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatSRS” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatTime_v” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatTime_v” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVector” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVector” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVectorCollection” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVectorCollection” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVectorProxy” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
code for methods in class “Rcpp_SpatVectorProxy” was not checked for suspicious field assignments (recommended package ‘codetools’ not available?)
terra 1.7.78
```

2024-09-27 14:33 UTC, saghirb commented
Output of `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`

```
$ nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"
these 46 paths will be fetched (15.64 MiB download, 95.18 MiB unpacked):
  /nix/store/vxqvlcc03rqpil05s2wwjzxa5c0gkaws-aws-sdk-cpp-1.11.336
  /nix/store/9ix8dhq7bi7blwf3zcd855bj2layj187-boehm-gc-8.2.6
  /nix/store/dpv2a5zca2dd8zxbp2cphypgv103n23g-editline-1.17.1
  /nix/store/lfb5ngmzsmnbqw41wm11i7hjnrkii7ic-git-2.46.0
  /nix/store/kcgzncw4plawrs6fw524dprbscqdl78n-git-2.46.0-doc
  /nix/store/7g59xcmzzpl7i4jhayrw7jmx0dbqbmh6-libarchive-3.7.4-lib
  /nix/store/5fa2ns1cd0j8dym2wll38irra8y5ygp5-libcpuid-0.7.0
  /nix/store/wkn35lg99z83sf9x4qwncx0vyzx6r716-libsodium-1.0.20
  /nix/store/cg8vpdzvi1v6g5699350gqb88s6iwgv1-lowdown-1.1.0-lib
  /nix/store/6vljpf4rwy7g24pkn39m5f86lci3kxxz-nix-2.18.7
  /nix/store/ax7r5w2rlzvs4vdn78yc1w5i7s8a0lv6-nix-2.18.7-man
  /nix/store/wy4ixpqa4fhpq7f4ph5nwda4dxihzl6v-nixpkgs-review-2.10.5
  /nix/store/lfdlfarvm34iy86ifpa1xx44vrrlc52k-nlohmann_json-3.11.3
  /nix/store/d6jfrpk3l1h5hkl2srcigyl18bjjdc6x-nss-cacert-3.101.1
  /nix/store/dg9jnhfm9wx8c0ikw1f04g5zf53jgmnm-perl5.38.2-Authen-SASL-2.1700
  /nix/store/xqxqsvp334ynqh83x8alq7ib39bjmz4h-perl5.38.2-CGI-4.59
  /nix/store/41w0lrhni3l19iy4ckzfyn3ww1mrbqkq-perl5.38.2-CGI-Fast-2.16
  /nix/store/c2wai0kxiyxfv2h183jk342rq9i51x7i-perl5.38.2-Clone-0.46
  /nix/store/dv5j7jbkpm64fyxl3kyn2lk4r734mziw-perl5.38.2-Digest-HMAC-1.04
  /nix/store/c17ggdffn04g3xx2d5q8267hr9phw06z-perl5.38.2-Encode-Locale-1.05
  /nix/store/8mpb10h7kai39pr1phjij2l7d4ara39l-perl5.38.2-FCGI-0.82
  /nix/store/fkr12kagmi0j6var9crfvsgvq1nilgk8-perl5.38.2-FCGI-ProcManager-0.28
  /nix/store/dacgpcqzj3c1mhrq5c0df7bdlbkym50s-perl5.38.2-File-Listing-6.16
  /nix/store/qfj6vczh1wa1zkzrhjaq6ay325vhc10m-perl5.38.2-HTML-Parser-3.81
  /nix/store/qpbf8jaz91b1cqki1zxi5nvic0a5vplv-perl5.38.2-HTML-TagCloud-0.38
  /nix/store/q1n6wkzdqr65j6hdp4si69q288msrn72-perl5.38.2-HTML-Tagset-3.20
  /nix/store/ql2syc0pvclcvn6sma29rz6v788rkxip-perl5.38.2-HTTP-CookieJar-0.014
  /nix/store/fy45cxp2g8d1i1wdqgy9f9cryd923rkl-perl5.38.2-HTTP-Cookies-6.10
  /nix/store/qwgpxxl9z29br46iind60rbpj2y3afr8-perl5.38.2-HTTP-Date-6.06
  /nix/store/2z0pdg381247fghw1h8a3f19gf5jajbl-perl5.38.2-HTTP-Message-6.45
  /nix/store/0rbdng7l95a5x2kxlsi6h3w4zclpq6zk-perl5.38.2-HTTP-Negotiate-6.01
  /nix/store/l5w1ppbqhzs22ginvnqf00q92m96kprx-perl5.38.2-IO-HTML-1.004
  /nix/store/qm4z902wqlhd3k431imksmvppqvihz1c-perl5.38.2-IO-Socket-SSL-2.083
  /nix/store/15g48jvsgk8gy3fdazxd5iir97h1piqz-perl5.38.2-LWP-MediaTypes-6.04
  /nix/store/a8qkfxgjmia2clq3yb960xm90fbna4f3-perl5.38.2-Mozilla-CA-20230821
  /nix/store/ha6r90h5q68kcppxxl8gr5cmkdja8byf-perl5.38.2-Net-HTTP-6.23
  /nix/store/6xd9lzi4gds14pvkan9jj2wzb0zknidh-perl5.38.2-Net-SMTP-SSL-1.04
  /nix/store/bqxcsiz56d08s5ybzqn79xlhq4kvyscy-perl5.38.2-Net-SSLeay-1.92
  /nix/store/zm2dz8zgyc77bafxz1w5f5gr1f9f5pvm-perl5.38.2-TermReadKey-2.38
  /nix/store/cxh5d8rpb096xbcqqjci987hw62mbw56-perl5.38.2-TimeDate-2.33
  /nix/store/v30w3ykk9kvpq4wspjyak291r0a8x2dq-perl5.38.2-Try-Tiny-0.31
  /nix/store/2i7j61jvqlhkiwa9mnb8gpzfhjdjh56m-perl5.38.2-URI-5.21
  /nix/store/1vayp94j6v6n04nqxl5nsvjjxlh32lra-perl5.38.2-WWW-RobotRules-6.02
  /nix/store/rak7s4ixpjh78whmlkk2wsmy02c0i3f0-perl5.38.2-libnet-3.15
  /nix/store/hccf089kbdk780zkf0q30zic4hishxp5-perl5.38.2-libwww-perl-6.72
  /nix/store/vamvhaqjwbghlnnyam1721nxm1jf269b-python3.12-argcomplete-3.4.0
copying path '/nix/store/d6jfrpk3l1h5hkl2srcigyl18bjjdc6x-nss-cacert-3.101.1' from 'https://cache.nixos.org/'...
copying path '/nix/store/dpv2a5zca2dd8zxbp2cphypgv103n23g-editline-1.17.1' from 'https://cache.nixos.org/'...
copying path '/nix/store/kcgzncw4plawrs6fw524dprbscqdl78n-git-2.46.0-doc' from 'https://cache.nixos.org/'...
copying path '/nix/store/5fa2ns1cd0j8dym2wll38irra8y5ygp5-libcpuid-0.7.0' from 'https://cache.nixos.org/'...
copying path '/nix/store/wkn35lg99z83sf9x4qwncx0vyzx6r716-libsodium-1.0.20' from 'https://cache.nixos.org/'...
copying path '/nix/store/cg8vpdzvi1v6g5699350gqb88s6iwgv1-lowdown-1.1.0-lib' from 'https://cache.nixos.org/'...
copying path '/nix/store/lfdlfarvm34iy86ifpa1xx44vrrlc52k-nlohmann_json-3.11.3' from 'https://cache.nixos.org/'...
copying path '/nix/store/ax7r5w2rlzvs4vdn78yc1w5i7s8a0lv6-nix-2.18.7-man' from 'https://cache.nixos.org/'...
copying path '/nix/store/dv5j7jbkpm64fyxl3kyn2lk4r734mziw-perl5.38.2-Digest-HMAC-1.04' from 'https://cache.nixos.org/'...
copying path '/nix/store/8mpb10h7kai39pr1phjij2l7d4ara39l-perl5.38.2-FCGI-0.82' from 'https://cache.nixos.org/'...
copying path '/nix/store/fkr12kagmi0j6var9crfvsgvq1nilgk8-perl5.38.2-FCGI-ProcManager-0.28' from 'https://cache.nixos.org/'...
copying path '/nix/store/qpbf8jaz91b1cqki1zxi5nvic0a5vplv-perl5.38.2-HTML-TagCloud-0.38' from 'https://cache.nixos.org/'...
copying path '/nix/store/zm2dz8zgyc77bafxz1w5f5gr1f9f5pvm-perl5.38.2-TermReadKey-2.38' from 'https://cache.nixos.org/'...
copying path '/nix/store/2i7j61jvqlhkiwa9mnb8gpzfhjdjh56m-perl5.38.2-URI-5.21' from 'https://cache.nixos.org/'...
copying path '/nix/store/rak7s4ixpjh78whmlkk2wsmy02c0i3f0-perl5.38.2-libnet-3.15' from 'https://cache.nixos.org/'...
copying path '/nix/store/9ix8dhq7bi7blwf3zcd855bj2layj187-boehm-gc-8.2.6' from 'https://cache.nixos.org/'...
copying path '/nix/store/vxqvlcc03rqpil05s2wwjzxa5c0gkaws-aws-sdk-cpp-1.11.336' from 'https://cache.nixos.org/'...
copying path '/nix/store/c2wai0kxiyxfv2h183jk342rq9i51x7i-perl5.38.2-Clone-0.46' from 'https://cache.nixos.org/'...
copying path '/nix/store/c17ggdffn04g3xx2d5q8267hr9phw06z-perl5.38.2-Encode-Locale-1.05' from 'https://cache.nixos.org/'...
copying path '/nix/store/7g59xcmzzpl7i4jhayrw7jmx0dbqbmh6-libarchive-3.7.4-lib' from 'https://cache.nixos.org/'...
copying path '/nix/store/dg9jnhfm9wx8c0ikw1f04g5zf53jgmnm-perl5.38.2-Authen-SASL-2.1700' from 'https://cache.nixos.org/'...
copying path '/nix/store/q1n6wkzdqr65j6hdp4si69q288msrn72-perl5.38.2-HTML-Tagset-3.20' from 'https://cache.nixos.org/'...
copying path '/nix/store/l5w1ppbqhzs22ginvnqf00q92m96kprx-perl5.38.2-IO-HTML-1.004' from 'https://cache.nixos.org/'...
copying path '/nix/store/15g48jvsgk8gy3fdazxd5iir97h1piqz-perl5.38.2-LWP-MediaTypes-6.04' from 'https://cache.nixos.org/'...
copying path '/nix/store/a8qkfxgjmia2clq3yb960xm90fbna4f3-perl5.38.2-Mozilla-CA-20230821' from 'https://cache.nixos.org/'...
copying path '/nix/store/bqxcsiz56d08s5ybzqn79xlhq4kvyscy-perl5.38.2-Net-SSLeay-1.92' from 'https://cache.nixos.org/'...
copying path '/nix/store/cxh5d8rpb096xbcqqjci987hw62mbw56-perl5.38.2-TimeDate-2.33' from 'https://cache.nixos.org/'...
copying path '/nix/store/v30w3ykk9kvpq4wspjyak291r0a8x2dq-perl5.38.2-Try-Tiny-0.31' from 'https://cache.nixos.org/'...
copying path '/nix/store/vamvhaqjwbghlnnyam1721nxm1jf269b-python3.12-argcomplete-3.4.0' from 'https://cache.nixos.org/'...
copying path '/nix/store/ha6r90h5q68kcppxxl8gr5cmkdja8byf-perl5.38.2-Net-HTTP-6.23' from 'https://cache.nixos.org/'...
copying path '/nix/store/1vayp94j6v6n04nqxl5nsvjjxlh32lra-perl5.38.2-WWW-RobotRules-6.02' from 'https://cache.nixos.org/'...
copying path '/nix/store/qwgpxxl9z29br46iind60rbpj2y3afr8-perl5.38.2-HTTP-Date-6.06' from 'https://cache.nixos.org/'...
copying path '/nix/store/qm4z902wqlhd3k431imksmvppqvihz1c-perl5.38.2-IO-Socket-SSL-2.083' from 'https://cache.nixos.org/'...
copying path '/nix/store/6vljpf4rwy7g24pkn39m5f86lci3kxxz-nix-2.18.7' from 'https://cache.nixos.org/'...
copying path '/nix/store/dacgpcqzj3c1mhrq5c0df7bdlbkym50s-perl5.38.2-File-Listing-6.16' from 'https://cache.nixos.org/'...
copying path '/nix/store/ql2syc0pvclcvn6sma29rz6v788rkxip-perl5.38.2-HTTP-CookieJar-0.014' from 'https://cache.nixos.org/'...
copying path '/nix/store/2z0pdg381247fghw1h8a3f19gf5jajbl-perl5.38.2-HTTP-Message-6.45' from 'https://cache.nixos.org/'...
copying path '/nix/store/6xd9lzi4gds14pvkan9jj2wzb0zknidh-perl5.38.2-Net-SMTP-SSL-1.04' from 'https://cache.nixos.org/'...
copying path '/nix/store/fy45cxp2g8d1i1wdqgy9f9cryd923rkl-perl [...]

2024-09-27 21:50 UTC, jbedo requested changes
This is working around an issue with pkg-config including the Requires.private dependencies. It would be better to work out the issue with pkg-config rather than avoiding pkg-config by directly specifying the dependency, as this issue may affect other packages.

2024-10-04 12:54 UTC, b-rodrigues commented
I opened an issue https://github.com/NixOS/nixpkgs/issues/346425

to see if we can get help with this.

2024-10-09 07:12 UTC, b-rodrigues commented
So thanks to some input I got on the issue, it looks like the fix, at least for `rPackages.terra` and `rPackages.vapour` is this: https://github.com/b-rodrigues/nixpkgs/commit/812fef336e2c1eacccba4e893e0338e65adb3e21

However, that doesn’t help with `rPackages.sf` which fails with:

```
checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
configure: error: libproj or sqlite3 not found in standard or given locations.
ERROR: configuration failed for package ‘sf’
* removing ‘/nix/store/090rqzxk9dlm3001ksvsnsrp6mh6nsvq-r-sf-1.0-16/library/sf’
error: builder for '/nix/store/80gp841mb76m9rx208l4nxcmppkqpknc-r-sf-1.0-16.drv' failed with exit code 1;
       last 25 log lines:
       > checking whether the compiler supports GNU C... yes
       > checking whether clang accepts -g... yes
       > checking for clang option to enable C11 features... none needed
       > checking for stdio.h... yes
       > checking for stdlib.h... yes
       > checking for string.h... yes
       > checking for inttypes.h... yes
       > checking for stdint.h... yes
       > checking for strings.h... yes
       > checking for sys/stat.h... yes
       > checking for sys/types.h... yes
       > checking for unistd.h... yes
       > checking for gdal.h... yes
       > checking GDAL: linking with --libs only... yes
       > checking GDAL: /nix/store/vdl5cxnbm7n02kf9mn3417glarvik1r6-gdal-3.8.5/share/gdal/pcs.csv readable... no
       > checking GDAL: checking whether PROJ is available for linking:... yes
       > checking GDAL: checking whether PROJ is available for running:... yes
       > configure: GDAL: 3.8.5
       > configure: pkg-config proj exists, will use it
       > configure: using proj.h.
       > configure: PROJ: 9.4.1
       > checking PROJ: checking whether PROJ and sqlite3 are available for linking:... no
       > configure: error: libproj or sqlite3 not found in standard or given locations.
       > ERROR: configuration failed for package ‘sf’
       > * removing ‘/nix/store/090rqzxk9dlm3001ksvsnsrp6mh6nsvq-r-sf-1.0-16/library/sf’
       For full logs, run 'nix log /nix/store/80gp841mb76m9rx208l4nxcmppkqpknc-r-sf-1.0-16.drv'.
error: 1 dependencies of derivation '/nix/store/fnd6sjisbfzambjmnpwd3pc602b68cnz-nix-shell.drv' failed to build
```

any ideas what might be wrong? If not, I could amend this PR and to only fix `sf` with 

```
    sf = old.sf.overrideAttrs (attrs: {
      configureFlags = [
        "--with-proj-lib=${pkgs.lib.getLib pkgs.proj}/lib"
      ];
    });
```

and open another PR to submit the fix for `proj`. What do you think @jbedo ?

2024-10-11 12:17 UTC, jbedo commented
After some testing on a Darwin system it seems there's no issue with `pkg-config`:
```
; nix-shell -p proj pkg-config --command 'pkg-config proj --exists'
-L/nix/store/jbaggmcq0gl5ax8h9j66vz46c4kz586g-proj-9.4.1/lib -lproj
; nix-shell -p proj pkg-config --command 'pkg-config proj --cflags'
-I/nix/store/86xp4sgwkx9gnr00q88hz0z5bv3j2900-proj-9.4.1-dev/include
```
Digging into the terra configure script revealed this:
https://github.com/rspatial/terra/blob/4e62696b86a1cc96c65adb04008c9fc819e1bab2/configure.ac#L398C1-L399C53
which explains the behaviour (as it adds `--static`).

I need to check the other packages but if it's a similar case then I'm happy with this PR as is.

2024-10-11 20:20 UTC, jbedo commented
@ofborg build rPackages.sf rPackages.terra rPackages.vapour

2024-10-11 22:09 UTC, jbedo approved these changes

2024-10-11 22:09 UTC, merged

2024-11-08 05:40 UTC, shriv commented
@b-rodrigues This error occurs on darwin for packages that depend on `lwgeom`. So far, I see it for `stplanr` and `tmap`. i can build `sf` and `terra` just fine after your fixes 👍 

```
error: builder for '/nix/store/xx9vvypn3yqqzzli9khqr2p775p4ifgs-r-lwgeom-0.2-14.drv' failed with exit code 1;
       last 10 log lines:
       > configure: using proj.h.
       > Package libtiff-4 was not found in the pkg-config search path.
       > Perhaps you should add the directory containing `libtiff-4.pc'
       > to the PKG_CONFIG_PATH environment variable
       > Package 'libtiff-4', required by 'proj', not found
       > configure: PROJ: 9.5.0
       > checking PROJ: checking whether linking against PROJ works:... no
       > configure: error: libproj not found in standard or given locations.
       > ERROR: configuration failed for package ‘lwgeom’
       > * removing ‘/nix/store/n2s1ih6zx5dljqqzagdancxs99lyki0k-r-lwgeom-0.2-14/library/lwgeom’
       For full logs, run 'nix log /nix/store/xx9vvypn3yqqzzli9khqr2p775p4ifgs-r-lwgeom-0.2-14.drv'.
error: 1 dependencies of derivation '/nix/store/l3lzs10jgq6z80gpqisagcxhp1pvqv34-r-tmaptools-3.1-1.drv' failed to build
error: 1 dependencies of derivation '/nix/store/7yprav96017jxyfi2rqkj0c4vbrravld-r-tmap-3.3-4.drv' failed to build
error: 1 dependencies of derivation '/nix/store/f6xvns2l99vy2gvs8jzr646z2yimmgsq-R-4.4.1-wrapper.drv' failed to build
error: 1 dependencies of derivation '/nix/store/byx5v73vzkbw4pl3bifvdizzsn8q12k4-nix-shell-env.drv' failed to build
```

Flake error when running `nix develop`
```
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixpkgs-unstable";
    flake-utils.url = "github:numtide/flake-utils";
  };
  outputs = { self, nixpkgs, flake-utils }:

  flake-utils.lib.eachDefaultSystem (system:
    let
	allow-unfree = pkg: builtins.elem (nixpkgs.lib.getName pkg) [ "positron-bin" ];
	pkgs = import nixpkgs { inherit system;
							config.allowUnfreePredicate = allow-unfree;
							};
	R-dev = pkgs.rWrapper.override {
        packages = with pkgs.rPackages; [
          tmap
        ];
      };
    in {
      devShells.default = pkgs.mkShell {
        buildInputs = with pkgs; [
          R-dev
        ];
      };
    });
}
```

2024-11-08 06:26 UTC, b-rodrigues commented
thanks I have got my hands on a second hand macbook, will take a look 👍