riseup-vpn: 0.21.11 -> 0.24.5-unstable-2024-07-08
NixOS/nixpkgs pull request #344549
Opened 2024-09-26 00:00 UTC by vigneshpai2003

## Description of changes

This is the same PR raised [here](https://github.com/NixOS/nixpkgs/pull/327838) with the merge conflicts and other issues fixed.

riseup-vpn was updated from the unusable 21.11 version (details in this https://github.com/NixOS/nixpkgs/issues/321132) to track the main branch. The package was ported to qt6.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-09-26 06:18 UTC, cleeyv requested changes
There has been another bitmask release (0.24.8) since your PR started, so it will be cleaner to upgrade to this one instead. I tested and it works without further changes other than the rev and sha.

2024-09-26 09:38 UTC, vigneshpai2003 commented on pkgs/tools/networking/bitmask-vpn/default.nix
> +    sha256 = "sha256-eOd/Yej1iuWxhR/jKrAJ7+Zb2QpXuaVWhV008tKijag=";
Thanks for the suggestion, I have commited the changes

2024-09-26 14:43 UTC, ju1m approved these changes
LGTM

2024-09-27 03:14 UTC, cleeyv approved these changes

2024-10-04 20:11 UTC, merged