sacad: init at 2.0.6
NixOS/nixpkgs pull request #34458
Opened 2018-01-31 15:04 UTC by ayyjayess

SACAD is a multi platform command line tool to download album covers without manual intervention, ideal for integration in scripts, audio players, etc.

Also includes: web_cache: init at 1.0.2

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-01-31 16:26 UTC, FRidh requested changes

2018-01-31 16:26 UTC, FRidh commented on pkgs/development/python-modules/web_cache/default.nix
> +  doCheck = false;
Why are the tests disabled? Please include a comment.

2018-01-31 16:26 UTC, FRidh commented on pkgs/tools/misc/sacad/default.nix
> +{ pkgs, jpegoptim, optipng }:
Don't pass in the whole package set. Instead, pass in the exact dependencies.

2018-01-31 16:26 UTC, FRidh commented on pkgs/tools/misc/sacad/default.nix
> +{ pkgs, jpegoptim, optipng }:
In case of Python and its packages, you can pass in `python3`.

2018-01-31 16:26 UTC, FRidh commented on pkgs/tools/misc/sacad/default.nix
> +let
`with python3.pkgs;`

2018-01-31 16:26 UTC, FRidh commented on pkgs/tools/misc/sacad/default.nix
> +  doCheck = false;
Why are the tests disabled? Please include a comment.

2018-01-31 20:04 UTC, grahamc commented
I introduced a failure in the evaluator today, sorry about that. Testing for a fix:

@GrahamcOfBorg eval

2018-02-03 08:07 UTC, FRidh requested changes

2018-02-03 08:07 UTC, FRidh commented on pkgs/development/python-modules/web_cache/default.nix
> +  name = "${pname}-${version}";
The `name` attribute is added by `buildPython*` and should therefore be removed.

2018-02-03 08:07 UTC, FRidh commented on pkgs/development/python-modules/web_cache/default.nix
> +  # ModuleNotFoundError: No module named 'tests'
That's because it's not included in the tarball. Can you replace this with
```
# No tests in archive
```

2018-02-03 08:07 UTC, FRidh commented on pkgs/tools/misc/sacad/default.nix
> +  inherit (python3.pkgs) buildPythonApplication fetchPypi;
because you have `with python3.pkgs`  above here this line is not needed.

2018-02-03 08:07 UTC, FRidh commented on pkgs/tools/misc/sacad/default.nix
> +  name = "${pname}-${version}";
The `name` attribute is added by `buildPython*` and should therefore be removed.

2018-02-03 08:07 UTC, FRidh commented on pkgs/tools/misc/sacad/default.nix
> +  propagatedBuildInputs = with python3.pkgs; [
`with python3.pkgs;` can be dropped

2019-05-21 00:39 UTC, aanderse commented
@ayyjayess any interest in continuing with this PR?

2019-08-08 22:30 UTC, jonringer commented
This has been sitting idle for 18 months, close? @FRidh @ayyess

2019-08-09 01:25 UTC, closed without merging