infamousPlugins: init at 0.2.03
NixOS/nixpkgs pull request #34522
Opened 2018-02-02 11:14 UTC by magnetophon

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-02-02 18:40 UTC, infinisil requested changes
Builds fine, but I have no idea what this can be used for, would be nice to have some more info on that.

2018-02-02 18:40 UTC, Infinisil commented on pkgs/applications/audio/infamousPlugins/default.nix
> +  buildInputs = [ cairomm cmake lv2 libpthreadstubs libXdmcp libXft ntk pcre fftwFloat zita-resampler ];
Shouldn't cmake be in nativeBuildInputs too?

2018-02-02 18:40 UTC, Infinisil commented on pkgs/top-level/all-packages.nix
> +infamousPlugins = callPackage ../applications/audio/infamousPlugins { };
indentation off

2018-02-02 18:40 UTC, Infinisil commented on pkgs/applications/audio/infamousPlugins/default.nix
> +    homepage = http://ssj71.github.io/infamousPlugins;
s/http/https

2018-02-03 00:14 UTC, magnetophon commented
@Infinisil Thanks for the feedback, all done.

2018-02-03 10:12 UTC, infinisil approved these changes

2018-02-10 11:27 UTC, merged