hyprland/waybar: fix programs not found error in scripts
NixOS/nixpkgs pull request #345841
Opened 2024-10-02 04:38 UTC by JohnRTitor

## Things done

This commit forcefully changes the Environment/PATH of the service unit and points it to commonly used ones like user packages and environment packages.

Starting Waybar using Systemd is convenient but it also brings up the problem of executables not being found, as their PATH is not imported to the systemd service's environment. This broke custom scripts used for Waybar modules, as they were not able to find the executables they were calling.

Ex:
```log
Oct 01 20:52:01 Ainz-NIX waybar[609010]: /usr/bin/env: ‘bash’: No such file or directory
Oct 01 20:52:02 Ainz-NIX waybar[609012]: /usr/bin/env: ‘bash’: No such file or directory
Oct 01 20:55:59 Ainz-NIX waybar[658271]: /usr/bin/env: ‘bash’: No such file or directory
```

Tested in https://github.com/JohnRTitor/nix-conf/commit/c05cf68c7d7f6425b75d76f007b5efa2b5dcc137

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-02 07:35 UTC, r-vdp commented
Do we need to use `mkForce` here? Why can't we just add the necessary entries to the unit's path with the normal priority?

Using `mkForce` adds friction if people want to add additional things in their own config.

2024-10-02 07:50 UTC, Scrumplex requested changes
If your actual `PATH` variable is not being imported into your systemd user environment, then you didn't configure your session correctly.

I personally would recommend setting up [uwsm](https://github.com/Vladimir-csp/uwsm) to start (and end) your session. It will import variables into systemd user environment (among many other useful things) and also clean them up once your session ends.

See https://search.nixos.org/options?channel=unstable&query=programs.uwsm

Feel free to take inspiration from my setup: 
https://codeberg.org/Scrumplex/flake/commit/8d9786b6408e237badb6898c6ad51b5b2973c28b and https://codeberg.org/Scrumplex/flake/commit/5bb9536755a1a0e500a6ccce843fb3cb561b93c9

2024-10-02 07:53 UTC, JohnRTitor commented
> Do we need to use `mkForce` here? Why can't we just add the necessary entries to the unit's path with the normal priority?

It will just conflict if we don't assign a high priority like `lib.mkForce`
```log
┃        error: The option `systemd.user.services.waybar.environment.PATH' has conflicting definition values:
┃        - In `/nix/store/r2hk87rfvc5fpfbl2bj64a3x7mcq9f6c-source/nixos/modules/system/boot/systemd/user.nix': "/nix/store/0kg70s…
┃        - In `/nix/store/af6yhh8isjs196cxy3p6yxb8i1la1vwr-source/system/hyprland': "/run/wrappers/bin:/etc/profiles/per-user/%u/…
┃        Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
```

Though I believe we could assign a lower priority than mkForce but still higher than normal like 200.

2024-10-02 08:02 UTC, JohnRTitor commented
> If your actual `PATH` variable is not being imported into your systemd user environment, then you didn't configure your session correctly.

This should really work out of the box. Since we are providing an NixOS option.

2024-10-02 13:08 UTC, Scrumplex commented
> > If your actual `PATH` variable is not being imported into your systemd user environment, then you didn't configure your session correctly.
> 
> This should really work out of the box. Since we are providing an NixOS option.

Considering that many other things also depend on certain environment variables being set in the sytemd user environment, I would argue that it is already inherently broken if you don't import your session variables. Another symptom of not properly importing your session variables into systemd is that icons are broken in Waybar's tray.

All of these problems (and probably more) will also apply to any application that is started by Waybar, as those will inherit a limited set of environment variables from the service.

2024-10-02 19:33 UTC, r-vdp commented
Yeah, I also feel that this isn't the right fix. I just checked and my compositor runs `systemctl --user import-environment` on startup to pull things into the user environment before launching its systemd service.

Maybe there's an issue with how your compositor is being launched?

2024-10-27 14:16 UTC, JohnRTitor commented
> Feel free to take inspiration from my setup:
> https://codeberg.org/Scrumplex/flake/commit/8d9786b6408e237badb6898c6ad51b5b2973c28b and https://codeberg.org/Scrumplex/flake/commit/5bb9536755a1a0e500a6ccce843fb3cb561b93c9

As someone who added the uwsm module, how would I configure this without HM? Genuinely want to know.

2024-10-27 19:06 UTC, Scrumplex commented
> As someone who added the uwsm module, how would I configure this without HM? Genuinely want to know.

The only part of my configuration that *requires* HM is declaratively setting the default session.

The following snippet should work if you are using Sway/Hyprland's NixOS modules:

```nix
{
  services.displayManager.enable = true;
  programs.uwsm = {
    enable = true;
    waylandCompositors = {
      sway = {
        prettyName = "Sway";
        comment = "Sway with systemd";
        binPath = lib.getExe config.programs.sway.package;
      };
      hyprland = {
        prettyName = "Hyprland";
        comment = "Hyprland with systemd";
        binPath = lib.getExe config.programs.hyprland.package;
      };
    };
  };
}
```

Though you would need to make sure to run `uwsm finalize` after Sway/Hyprland have started (i.e. add `exec uwsm finalize` to the config for Sway)

2025-01-07 08:38 UTC, closed without merging