odoo: fix tests and update take 2
NixOS/nixpkgs pull request #346397
Opened 2024-10-04 10:31 UTC by phanirithvij

redo #344173
depends on 222d7063940ddf7d60b86ad81d54663b4357254a

```shell
git cherry-pick 222d7063940ddf7d60b86ad81d54663b4357254a
echo nixosTests.odoo{15,16,} | xargs -n1 nix-build --no-out-link -A
```

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

2024-10-09 06:34 UTC, siriobalmelli requested changes
I get a merge conflict with `master`:

```
Auto-merging pkgs/by-name/od/odoo15/package.nix
CONFLICT (content): Merge conflict in pkgs/by-name/od/odoo15/package.nix
Auto-merging pkgs/development/python-modules/aiohttp/default.nix
Automatic merge failed; fix conflicts and then commit the result.
```

2024-10-09 08:38 UTC, phanirithvij commented
fixed the conflict, try again

2024-10-09 10:38 UTC, Erethon commented
I tried this yesterday (before the newest changes) by cherry-picking the commits and applying them on master. It pretty much worked, Odoo 17 was functional, although some smaller features of it weren't working (like QR code generation), but I believe these weren't working in the past either. From my point of view, this fixes the issues of the existing package, so thank you!

2024-10-09 14:41 UTC, siriobalmelli commented
<img width="876" alt="Screenshot 2024-10-09 at 4 40 38 PM" src="https://github.com/user-attachments/assets/750c4254-6200-483d-a0cc-d050ae7f6aaa">

... still running nixpkgs-review ... 🔢

2024-10-09 20:02 UTC, siriobalmelli commented
Result of `nixpkgs-review pr 346397` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages failed to build:</summary>
  <ul>
    <li>stig</li>
    <li>stig.dist</li>
  </ul>
</details>

2024-10-09 20:11 UTC, SuperSandro2000 commented
I don't think the PR needs to target staging.

2024-10-09 20:22 UTC, SuperSandro2000 commented on pkgs/development/python-modules/aiohttp/default.nix
> +    ++ lib.optionals isPy310 [ "test_https_proxy_unsupported_tls_in_tls" ]
Would be nice to have a short comment here

2024-10-09 20:22 UTC, SuperSandro2000 commented on pkgs/by-name/od/odoo16/package.nix
>      name = "${pname}-${version}";
```suggestion
    name = "odoo-${version}";
```

2024-10-09 20:22 UTC, SuperSandro2000 commented on pkgs/by-name/od/odoo16/package.nix
> +, odoo_release ? "20240924"
```suggestion
```
I don't think we should have those in inputs. The hashes are not updated so things don't work as expected and we generally have overrides for that.

2024-10-09 20:22 UTC, SuperSandro2000 commented on pkgs/by-name/od/odoo15/package.nix
>      name = "${pname}-${version}";
```suggestion
    name = "odoo15-${version}";
```

2024-10-09 20:22 UTC, SuperSandro2000 commented on pkgs/by-name/od/odoo15/package.nix
> +        nativeBuildInputs = [ self.setuptools ];
```suggestion
        dependencies = [ self.setuptools ];
```

2024-10-09 20:22 UTC, SuperSandro2000 commented on pkgs/by-name/od/odoo15/package.nix
> +, odoo_release ? "20240924"
```suggestion
```
same as below

2024-10-09 20:22 UTC, SuperSandro2000 commented on pkgs/by-name/od/odoo/package.nix
>      name = "${pname}-${version}";
```suggestion
    name = "odoo-${version}";
```

2024-10-09 20:22 UTC, SuperSandro2000 commented on pkgs/by-name/od/odoo/package.nix
> +, odoo_release ? "20240925"
and same as below

2024-10-09 22:13 UTC, siriobalmelli commented
> I don't think the PR needs to target staging.

That might explain how long it's taking me to build everything:

<img width="1585" alt="Screenshot 2024-10-10 at 12 12 08 AM" src="https://github.com/user-attachments/assets/14f11ed5-8142-40c7-8e6a-5f9c00ba4ad3">

2024-10-09 22:28 UTC, SuperSandro2000 commented
Your rebuild is taking so long because you are targeting staging which has almost no cache. There is no reason to target staging because the rebuild count is almost nothing.

2024-10-10 05:51 UTC, siriobalmelli commented
Result of `nixpkgs-review pr 346397` run on aarch64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>10 packages failed to build:</summary>
  <ul>
    <li>odoo</li>
    <li>odoo.dist</li>
    <li>odoo15</li>
    <li>odoo15.dist</li>
    <li>odoo16</li>
    <li>odoo16.dist</li>
    <li>pytrainer</li>
    <li>pytrainer.dist</li>
    <li>stig</li>
    <li>stig.dist</li>
  </ul>
</details>

2024-10-10 19:59 UTC, phanirithvij commented
Seems like odoo has dropped 15.0 for their docker images and released 18 as well, see https://github.com/odoo/docker and https://github.com/docker-library/docs/tree/master/odoo

- I updated the target branch to master
- updated odoo to 18
- added `odoo17/package.nix`
- modified the update script to handle updating all versions not just the latest version
- made changes suggested by sandro

Should we remove odoo 15 or still keep it?

2024-10-10 21:03 UTC, mkg20001 commented
>Should we remove odoo 15 or still keep it?

Given that odoo is now at version 18 I'd say we should drop it on master. I think that's a breaking change according to releease scheudle? In that case we can simply drop it after release branch-off.

2024-10-10 21:06 UTC, mkg20001 commented
I'm seeing a lot of unresolved conversations for old diffs, please mark the resolved conversations as resolved. Also note that applying a code suggestion via github ui automatically marks the conversation as resolved and adds a commit to the branch (that can be squashed into others if it's not wanted as stand alone commit).

2024-10-11 08:22 UTC, siriobalmelli commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 346397`

---
### `aarch64-linux`
<details>
  <summary>:x: 10 packages failed to build:</summary>
  <ul>
    <li>odoo15</li>
    <li>odoo15.dist</li>
    <li>odoo16</li>
    <li>odoo16.dist</li>
    <li>odoo17</li>
    <li>odoo17.dist</li>
    <li>pytrainer</li>
    <li>pytrainer.dist</li>
    <li>stig</li>
    <li>stig.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>odoo</li>
    <li>odoo.dist</li>
  </ul>
</details>

2024-10-13 05:39 UTC, phanirithvij commented
I tried `nix-build -A pkgsCross.aarch64-multiplatform.odoo15` on my x86_64-linux but can't do it with 16GB ram + 16GB swap.

2024-10-14 19:09 UTC, mweinelt commented on pkgs/development/python-modules/aiohttp/default.nix
> +    ++ lib.optionals isPy310 [
What about 3.9?

2024-10-15 02:58 UTC, phanirithvij commented on pkgs/development/python-modules/aiohttp/default.nix
> +    ++ lib.optionals isPy310 [
```nix
$ for i in python3{9,10,11,12,13}Packages.aiohttp; do nix-build --no-out-link -A $i; done
       (stack trace truncated; use '--show-trace' to show the full trace)

       error: ipython-8.27.0 not supported for interpreter python3.9
/nix/store/j55np66p2kgj7m76g0kfbafb1wycxnnm-python3.10-aiohttp-3.10.5
/nix/store/i99cdds80c0f84bzsrmrwy2k6ik9crji-python3.11-aiohttp-3.10.5
/nix/store/i1csas85j560pbv182h9wkxlxqjscgqi-python3.12-aiohttp-3.10.5
       (stack trace truncated; use '--show-trace' to show the full trace)

       error: mypy-1.11.2 not supported for interpreter python3.13
```
py39 is already incompatible it seems?

2024-10-16 02:44 UTC, phanirithvij commented
This is ready, but the update scripts are duplicated, since the pkgs/by-name doesn't allow accessing files outside the tree. https://github.com/NixOS/nixpkgs/pull/292214
I doubt we want to move these back to all-packages. So I think we have to live with this duplication.

Can everyone test it once, try to use odoo18 (if possible older versions too) for a few days and report any breakages here. I hope to get this in before 24.11 freeze. (< 2 weeks)

2024-10-24 10:29 UTC, siriobalmelli commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 346397`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 14 packages built:</summary>
  <ul>
    <li>circus</li>
    <li>circus.dist</li>
    <li>odoo</li>
    <li>odoo.dist</li>
    <li>odoo15</li>
    <li>odoo15.dist</li>
    <li>odoo16</li>
    <li>odoo16.dist</li>
    <li>odoo17</li>
    <li>odoo17.dist</li>
    <li>pytrainer</li>
    <li>pytrainer.dist</li>
    <li>stig</li>
    <li>stig.dist</li>
  </ul>
</details>

2024-10-24 11:29 UTC, mkg20001 commented
Any objections to merge? Would merge in a few days

2024-10-24 15:24 UTC, siriobalmelli approved these changes

2024-10-24 15:24 UTC, siriobalmelli commented
LGTM; I'll circle back to the aarch64-linux builds failures later as needed.

2024-10-25 12:43 UTC, phanirithvij commented
Cross compilation works tho

```console
$ echo pkgsCross.aarch64-multiplatform.odoo{15,16,17,} | xargs -n1 nix build -f . --print-out-paths
/nix/store/7m2j0svg34vjnhqm8gyb21l3fz9fyyjm-odoo-15.0.20241010-aarch64-unknown-linux-gnu
/nix/store/68jbpcb3620kg5cw338zwbvax5yjzqnh-odoo-16.0.20241010-aarch64-unknown-linux-gnu
/nix/store/x0wq3s1dfbmwhgn519jw3mhxgizcmyh7-odoo-17.0.20241010-aarch64-unknown-linux-gnu
/nix/store/gagv0a46hbw8lg639y9fx0djjl67cksh-odoo-18.0.20241010-aarch64-unknown-linux-gnu
```

2024-10-25 23:21 UTC, merged