freecad: work around https://github.com/FreeCAD/FreeCAD/issues/10514
NixOS/nixpkgs pull request #346740
Opened 2024-10-05 21:31 UTC by hzeller

* Fixes #284880
  * Also discussed on https://discourse.nixos.org/t/freecad-failed-to-compute-left-right-minimum-bearings-for-cursor-pcf/35266

Symptom is that failure to load a fixed font is followed by a flood of
 'Failed to compute left/right minimum bearings for "cursor.pcf"'
messages that can freeze up the machine.

Isssue FreeCAD issue tracker https://github.com/FreeCAD/FreeCAD/issues/10514

Is not yet fixed, but with a working solution, which has not made it into the repo yet: https://github.com/FreeCAD/FreeCAD/issues/10514#issuecomment-1849176386 The hotfix from that comment is added here slightly adated as freecad-font-10514.patch

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-06 00:46 UTC, AndersonTorres requested changes

2024-10-06 00:46 UTC, AndersonTorres commented on pkgs/by-name/fr/freecad/package.nix
> +    ./freecad-font-issue10514.patch
```suggestion
    ./0003-freecad-font-issue-10514.patch
```

2024-10-06 00:50 UTC, hzeller commented on pkgs/by-name/fr/freecad/package.nix
> +    ./freecad-font-issue10514.patch
Done.

2024-10-06 00:50 UTC, hzeller commented on pkgs/by-name/fr/freecad/package.nix
> +    ./freecad-font-issue10514.patch
ah, wait, dash missing, one sec.

2024-10-06 00:52 UTC, hzeller commented on pkgs/by-name/fr/freecad/package.nix
> +    ./freecad-font-issue10514.patch
Done.

2024-10-08 15:10 UTC, hzeller commented
Looks good ? Would be good to get it merged to make freecad usable in Nix.

2024-10-12 20:12 UTC, hzeller commented
Ready to approve and merge ?

2024-10-16 03:10 UTC, hzeller commented
Can you review this change @AndersonTorres ?

This would be really good to have to have a usable freecad that does not lock up and use 100% resources.

2024-10-19 15:58 UTC, hzeller commented
widening the audience to @kirillrdy who merged the 0.21 -> 1.0rc2 #343592 PR

2024-10-19 16:02 UTC, merged

2024-10-19 16:05 UTC, Artturin commented
@srounce If you want to get review requests for packages you maintain you need to join the https://github.com/orgs/NixOS/teams/nixpkgs-maintainers team

2024-10-19 16:10 UTC, hzeller commented
Yeah, but I ( @hzeller ) am not a maintainer of this package, just someone who had a fix.

2024-10-19 16:11 UTC, hzeller commented
oh, I see, you mean that @srounce gets the notifications for this PR.

2024-11-09 10:16 UTC, evils commented
i'm still getting this on current `nixos-unstable` with `freecad-wayland` (on sway) which should include this workaround

deftdawg's workaround mentioned [here](https://github.com/FreeCAD/FreeCAD/issues/10514#issuecomment-2439839079) (and launching FreeCAD from the same shell i did that in) indeed got rid of the spam and made FreeCAD usable