rpm: fix build on Darwin
NixOS/nixpkgs pull request #346967
Opened 2024-10-06 23:55 UTC by reckenrode

RPM needs a 13.x SDK or newer.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-07 00:06 UTC, emilazy commented
Finally, macOS Nix users can have a decent package manager.

2024-10-11 01:11 UTC, emilazy requested changes
Could you try bumping to 4.20 instead, which includes these fixes? Otherwise we need to adjust the commit hashes.

2024-10-11 01:11 UTC, emilazy commented on pkgs/tools/package-management/rpm/default.nix
> +    })
This is included in 4.19 and 4.20; we should probably bump the version instead. If not, we should at least point to `b960c0b43a080287a7c13533eeb2d9f288db1414`, which is the version of the commit that was landed and won’t get GC’d.

2024-10-11 01:11 UTC, emilazy commented on pkgs/tools/package-management/rpm/default.nix
> +    })
This PR was also rebased for merge and is in 4.20.

2024-10-11 22:52 UTC, emilazy commented on pkgs/tools/package-management/rpm/default.nix
> +    platforms = platforms.linux ++ platforms.darwin;
BTW, I’m guessing this can be `platforms.unix`.

2024-10-13 22:34 UTC, reckenrode commented
RPM 4.20 is a non-trivial effort to package. That’s way beyond what I want to do to update it for Darwin. If this isn’t mergable, I’d rather leave Darwin marked broken.

2024-10-13 22:38 UTC, emilazy commented
I think it’s fine to merge this and let someone else handle RPM 4.20 as long as we can point the fetches to the copies of the commits that were actually merged rather than the potentially ephemeral ones from the PRs.

2024-10-13 23:00 UTC, reckenrode commented
I fixed the commit to be the one from the repo.

2024-10-13 23:32 UTC, emilazy commented
The other PR needs its commits changing too (it seems like they do rebase merges).

2024-11-04 18:18 UTC, paparodeo approved these changes

2024-11-04 23:52 UTC, reckenrode commented
No changes except I retargeted to master due to the low number of rebuilds.

2024-11-06 15:08 UTC, reckenrode commented
@emilazy Is this good to merge? It’s blocked currently.

2024-11-06 18:44 UTC, emilazy approved these changes
Forgot I had a blocking review on this, sorry. Seems fine, hopefully someone else can figure out the new build system another time.

2024-11-06 18:44 UTC, merged