pythonPackages.rtf-tokenize: init at 1.0.0
NixOS/nixpkgs pull request #347510
Opened 2024-10-09 15:16 UTC by Twey

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-09 16:40 UTC, natsukium commented
see my comment https://github.com/NixOS/nixpkgs/pull/347354#issuecomment-2402784140

2024-10-09 17:05 UTC, Twey commented
I realized I missed a `pyproject` on this one — I've added it and hopefully it's now ready for review. :slightly_smiling_face:

2024-10-13 19:53 UTC, Twey commented
Hi @natsukium, any further thoughts on this?

2024-11-01 15:05 UTC, FliegendeWurst requested changes

2024-11-01 15:05 UTC, FliegendeWurst commented on pkgs/development/python-modules/rtf-tokenize/default.nix
> +    license = licenses.gpl2Plus;
```suggestion
  meta = {
    description = "Simple RTF tokenizer";
    maintainers = with lib.maintainers; [ twey ];
    license = lib.licenses.gpl2Plus;
```

2024-11-01 15:05 UTC, FliegendeWurst commented on pkgs/development/python-modules/rtf-tokenize/default.nix
> +  python3Packages,
```suggestion
  buildPythonPackage,
```

2024-11-01 15:05 UTC, FliegendeWurst commented on pkgs/development/python-modules/rtf-tokenize/default.nix
> +python3Packages.buildPythonPackage rec {
```suggestion
buildPythonPackage rec {
```

2025-07-29 23:57 UTC, Twey commented
Closing in favour of https://github.com/NixOS/nixpkgs/pull/419593.

2025-07-29 23:57 UTC, closed without merging