objection: init at 1.11.0-unstable-2024-09-13
NixOS/nixpkgs pull request #347930
Opened 2024-10-11 13:40 UTC by exploitoverload

Runtime mobile exploration toolkit, powered by Frida.

https://github.com/sensepost/objection

Related to #81418 

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-11 14:44 UTC, exploitoverload commented
Result of `nixpkgs-review pr 347930` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>objection</li>
    <li>objection.dist</li>
  </ul>
</details>

2024-11-01 18:28 UTC, FliegendeWurst requested changes
`objection signapk /tmp/app-release.apk` does not work out of the box. It would be good to wrap the program to have aapt & co. in PATH

2024-11-01 18:28 UTC, FliegendeWurst commented on pkgs/by-name/ob/objection/package.nix
> +    maintainers = with maintainers; [ exploitoverload ];
```suggestion
  meta = {
    description = "Runtime mobile exploration toolkit, powered by Frida";
    homepage = "https://github.com/sensepost/objection";
    license = lib.licenses.gpl3;
    maintainers = with lib.maintainers; [ exploitoverload ];
```

2024-11-26 11:32 UTC, exploitoverload commented
@FliegendeWurst I have made some changes, I have included the build-tools path in the package as it was necessary to include zipalign. I have tested it and there should be no more problems when signing or patching apks. I have a doubt if it is the best option to specify directly the version of the android build-tools in the package itself or if there is another better option. Another thing to mention, is that now when using android build-tools it is necessary to accept the license either through nixpkgs configuration or through environment variables:

```
       You must accept the following licenses:
         - android-sdk-license

       a)
         by setting nixpkgs config option 'android_sdk.accept_license = true;'.
       b)
         by an environment variable for a single invocation of the nix tools.
           $ export NIXPKGS_ACCEPT_ANDROID_SDK_LICENSE=1
```

2024-11-26 11:46 UTC, exploitoverload commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 347930`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>objection</li>
    <li>objection.dist</li>
  </ul>
</details>

2024-11-26 20:29 UTC, fabaff commented on pkgs/by-name/ob/objection/package.nix
> +    license = lib.licenses.gpl3;
No mentioning about "...any later version".

```suggestion
    license = lib.licenses.gpl3Only;
```

2024-11-29 07:42 UTC, FliegendeWurst approved these changes

2026-08-27 19:02 UTC, Letgamer commented
Done in https://github.com/NixOS/nixpkgs/pull/436279

2026-08-27 19:02 UTC, closed without merging