trilium-next: init at 0.90.4
NixOS/nixpkgs pull request #348144
Opened 2024-10-12 20:26 UTC by eliandoran

This PR adds [TriliumNext Notes](https://github.com/TriliumNext/Notes) which is a fork of Trilium Notes, which has entered maintenance mode.

Basically I've taken the original package description for Trilium and adapted it for the fork. I've also changed the server module to take in a `package` attribute.

Note: I am also the upstream maintainer of TriliumNext Notes.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-21 14:49 UTC, SuperSandro2000 commented on nixos/modules/services/web-apps/trilium.nix
> +        ExecStart = "${cfg.package}/bin/trilium-server";
```suggestion
        ExecStart = lib.getExe cfg.package;
```

2024-10-21 14:50 UTC, SuperSandro2000 commented on pkgs/applications/office/trilium-next/default.nix
> +}
```suggestion
{ lib, callPackage }:

let
  meta = with lib; {
    description = "Hierarchical note taking application with focus on building large personal knowledge bases";
    homepage = "https://github.com/TriliumNext/Notes";
    license = licenses.agpl3Plus;
    sourceProvenance = with sourceTypes; [ binaryNativeCode ];
    platforms = [ "x86_64-linux" ];
    maintainers = with maintainers; [ eliandoran ];
  };
  version = "0.90.4";
in
{
  trilium-next-desktop = callPackage ./desktop.nix {
    inherit meta version;
  };

  trilium-next-server = callPackage ./server.nix {
    inherit meta version;
  };
}
```

2024-10-21 14:51 UTC, SuperSandro2000 commented on pkgs/applications/office/trilium-next/desktop.nix
> +    # TODO: migrate off autoPatchelfHook and use nixpkgs' electron
so, what's blocking that?

2024-10-21 14:51 UTC, SuperSandro2000 commented on pkgs/applications/office/trilium-next/server.nix
> +    cat > $out/bin/trilium-server <<EOF
Please use makeWrapper

2024-10-31 08:15 UTC, FliegendeWurst requested changes

2024-10-31 08:15 UTC, FliegendeWurst commented on pkgs/applications/office/trilium-next/desktop.nix
> +if stdenv.isDarwin then darwin else linux
```suggestion
if stdenv.hostPlatform.isDarwin then darwin else linux
```

2024-10-31 08:15 UTC, FliegendeWurst commented on pkgs/top-level/all-packages.nix
> +    ;
should be in pkgs/by-name

2024-11-17 21:41 UTC, fabian-mv commented
sadly this wont be coming out in 24.11, since [branch out was 4 days ago](https://github.com/NixOS/nixpkgs/issues/339153). this is very bad, as trilium next is now more important as sync became incompatible.

this means that trilium next won't be in nixpkgs until mid-2025 (since releases are very 6months). pretty sad if you ask me

@eliandoran i can help if you need

2024-11-17 21:46 UTC, FliegendeWurst commented
New packages can always be backported. No problem there.

2024-11-18 08:23 UTC, FliegendeWurst commented
I tried to package using nixpkgs' electron instead: https://github.com/FliegendeWurst/nixpkgs/blob/trilium-next/pkgs/applications/office/trilium-next/desktop.nix

... but for some reason, locale data is missing:

![Screenshot_20241118_092017](https://github.com/user-attachments/assets/ce0c6df6-ecc6-45b8-830f-3a0fe4741979)

@eliandoran do you know how this could be fixed? Do I need to add some more flags to my electron invocation?

2024-11-18 11:37 UTC, FliegendeWurst commented
I fixed the above issue and created #356930

2024-11-18 11:54 UTC, eliandoran commented
Closing in favor of https://github.com/NixOS/nixpkgs/pull/356930.

2024-11-18 11:54 UTC, closed without merging