msbuild-structured-log-viewer: init at 2.2.356
NixOS/nixpkgs pull request #348353
Opened 2024-10-13 21:10 UTC by js6pak

An Avalonia-based viewer for the MSBuild binary log format, which allows you to inspect basically every aspect of a .NET build
https://github.com/KirillOsenkov/MSBuildStructuredLog

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [x] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-13 21:12 UTC, js6pak commented on pkgs/by-name/ms/msbuild-structured-log-viewer/package.nix
> +      wrapDotnetProgram $out/lib/${finalAttrs.pname}/StructuredLogViewer.Avalonia $out/bin/${meta.mainProgram}
I'm renaming the executable name from upstream's `StructuredLogViewer.Avalonia` to `msbuild-structured-log-viewer` here, but is that something we should/can do?

2024-10-13 21:35 UTC, Daholli requested changes

2024-10-13 21:35 UTC, Daholli commented on pkgs/by-name/ms/msbuild-structured-log-viewer/package.nix
> +  meta = with lib; {
```suggestion
  meta = {
```

2024-10-13 21:35 UTC, Daholli commented on pkgs/by-name/ms/msbuild-structured-log-viewer/package.nix
> +    license = licenses.mit;
```suggestion
    license = lib.licenses.mit;
```

2024-10-13 21:35 UTC, Daholli commented on pkgs/by-name/ms/msbuild-structured-log-viewer/package.nix
> +    sourceProvenance = with sourceTypes; [
```suggestion
    sourceProvenance = with lib.sourceTypes; [
```

2024-10-13 21:35 UTC, Daholli commented on pkgs/by-name/ms/msbuild-structured-log-viewer/package.nix
> +    maintainers = with maintainers; [ js6pak ];
```suggestion
    maintainers = with lib.maintainers; [ js6pak ];
```

2024-11-18 11:59 UTC, FliegendeWurst approved these changes

2024-12-19 06:14 UTC, merged