froide-govplan: init
NixOS/nixpkgs pull request #349750
Opened 2024-10-19 11:41 UTC by onny

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2025-03-06 11:53 UTC, mweinelt commented on pkgs/development/python-modules/psycopg/default.nix
That's not going to fly.

2025-03-06 13:29 UTC, onny commented on pkgs/development/python-modules/psycopg/default.nix
fixed :)

2025-03-21 12:35 UTC, drupol commented on nixos/modules/services/web-apps/froide-govplan.nix
> +  froide-govplan = pkgs.writeScriptBin "froide-govplan" ''
You could use `writeShellApplication` so that it automatically run `shellCheck` on the script.

2025-03-21 12:35 UTC, drupol commented on nixos/tests/all-tests.nix
> +  froide-govplan = handleTest ./web-apps/froide-govplan.nix {};
Use `runTest` instead please.

2025-03-21 12:36 UTC, drupol commented on pkgs/by-name/fr/froide-govplan/package.nix
> +
Why those blank lines in all the files?

2025-03-23 15:29 UTC, drupol commented on pkgs/by-name/fr/froide-govplan/package.nix
> +  makeWrapper,
Let's use makeBinaryWrapper

2025-03-23 17:03 UTC, drupol requested changes

2025-03-23 17:03 UTC, drupol commented on pkgs/by-name/fr/froide-govplan/package.nix
> +        nativeBuildInputs = [ makeWrapper ];
```suggestion
        nativeBuildInputs = [ makeBinaryWrapper ];
```

2025-03-23 17:03 UTC, drupol commented on pkgs/by-name/fr/froide-govplan/package.nix
> +    makeBinaryWrapper $out/${python.sitePackages}/froide_govplan/manage.py $out/bin/froide-govplan \
```suggestion
    makeWrapper $out/${python.sitePackages}/froide_govplan/manage.py $out/bin/froide-govplan \
```

2025-03-23 17:16 UTC, onny commented
@drupol Thank you for reviewing :)

2025-03-26 06:37 UTC, onny commented
@drupol Is this ready to merge? :)

2025-03-26 06:39 UTC, drupol commented on nixos/modules/services/web-apps/froide-govplan.nix
> +    users.users.govplan = {
Why a user is needed ? Can't you use a systemd dynamicUser ?

2025-03-26 13:19 UTC, onny commented on nixos/modules/services/web-apps/froide-govplan.nix
> +    users.users.govplan = {
i use it for socket authentication to the psql db

2025-03-26 13:20 UTC, drupol commented on nixos/modules/services/web-apps/froide-govplan.nix
> +    users.users.govplan = {
Fair enough.

2025-03-26 13:21 UTC, drupol approved these changes
I'll mark this as LGTM, but I haven't tested it, I trust @onny for that.

2025-03-26 13:27 UTC, merged

2025-03-26 13:32 UTC, onny commented
thank you @drupol