{shoko-webui,shokoserver,nixos/shokoserver}: init
NixOS/nixpkgs pull request #350065
Opened 2024-10-20 17:19 UTC by diniamo

Adds a NixOS module for https://github.com/ShokoAnime/ShokoServer, along with derivations for the module's dependencies.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-20 17:27 UTC, diniamo commented
The formatting check fails for the generated dependencies file, which I don't believe should be formatted.

2024-11-14 14:43 UTC, diniamo commented
To be fair, I like its formatting way more. But I guess it should be formatted then?

2024-11-14 14:48 UTC, dasJ requested changes, later dismissed

2024-11-14 14:48 UTC, dasJ commented on nixos/modules/misc/ids.nix
> +      shoko = 328;
Please don't do that and just let it auto-allocate a UID from the regular pool (`isSystemUser=true` and no uid in actual user)

2024-11-14 14:48 UTC, dasJ commented
For the nuget thing: what about:
```
diff --git a/pkgs/build-support/dotnet/add-nuget-deps/default.nix b/pkgs/build-support/dotnet/add-nuget-deps/default.nix
index bf3df815af8a..12810e092d03 100644
--- a/pkgs/build-support/dotnet/add-nuget-deps/default.nix
+++ b/pkgs/build-support/dotnet/add-nuget-deps/default.nix
@@ -8,6 +8,7 @@
   cacert,
   fetchNupkg,
   callPackage,
+  nixfmt-rfc-style,
 }:

 {
@@ -67,6 +68,7 @@ attrs
             isExecutable = true;
             inherit cacert;
             nugetToNix = nuget-to-nix;
+            nixfmt = nixfmt-rfc-style;
           };

           defaultDepsFile =
diff --git a/pkgs/build-support/dotnet/add-nuget-deps/fetch-deps.sh b/pkgs/build-support/dotnet/add-nuget-deps/fetch-deps.sh
index af560b96fcd5..47731b29cd59 100644
--- a/pkgs/build-support/dotnet/add-nuget-deps/fetch-deps.sh
+++ b/pkgs/build-support/dotnet/add-nuget-deps/fetch-deps.sh
@@ -7,5 +7,6 @@ genericBuild
     @nugetToNix@/bin/nuget-to-nix "${NUGET_PACKAGES%/}"
 ) > deps.nix

+@nixfmt@/bin/nixfmt deps.nix
 mv deps.nix "$1"
 echo "Succesfully wrote lockfile to $1"
```

2024-11-14 15:08 UTC, dasJ commented
Sorry, that was unclear. I was suggesting that solution to the formatting team you pinged, not to you for this very PR ;)

2024-11-15 21:58 UTC, diniamo commented
The test fails because Shoko is trying to access its settings file (`/var/lib/shoko/settings-server.json`), but fails. Not sure how I can fix that.

2025-01-15 16:05 UTC, gepbird commented on pkgs/by-name/sh/shoko-webui/package.nix
> +  pnpm,
Most likely you need to change `pnpm` to `pnpm_9`. Since #371832, it points to `pnpm_10` instead of `pnpm_9`.

2025-01-17 05:05 UTC, diniamo commented on pkgs/by-name/sh/shoko-webui/package.nix
> +  pnpm,
Seems to work with 10 after a rebase

2025-01-17 09:51 UTC, gepbird commented on pkgs/by-name/sh/shoko-webui/package.nix
> +  pnpm,
Indeed it works, thanks for trying it out, you can mark this as resolved.

2025-01-17 10:11 UTC, gepbird requested changes
`nixosTests.shoko` is hanging, the relevant error there: 
 > The server failed to start: System.UnauthorizedAccessException: Access to the path '/var/lib/shoko/settings-server.json' is denied.

Also adding an update script would be nice, for the webui package `passthru.updateSript = nix-update-script { };` should be sufficient, the shoko package uses dotnet which doesn't have a clean solution yet, but this should work:
```nix
  passthru.updateScript = _experimental-update-script-combinators.sequence [
    (gitUpdater { }).command
    (finalAttrs.passthru.fetch-deps)
  ];
```

2025-01-17 10:11 UTC, gepbird commented on pkgs/by-name/sh/shoko/package.nix
> +    rev = "refs/tags/v${finalAttrs.version}";
Nit
```suggestion
    tag = "v${finalAttrs.version}";
```

2025-01-17 10:11 UTC, gepbird commented on pkgs/by-name/sh/shoko/package.nix
> +    homepage = "https://github.com/ShokoAnime/ShokoServer";
You could add a changelog

```suggestion
    homepage = "https://github.com/ShokoAnime/ShokoServer";
    changelog = "https://github.com/ShokoAnime/ShokoServer/releases/tag/v${finalAttrs.version}";
```

2025-01-17 10:11 UTC, gepbird commented on pkgs/by-name/sh/shoko-webui/package.nix
> +    homepage = "https://github.com/ShokoAnime/Shoko-WebUI";
```suggestion
    homepage = "https://github.com/ShokoAnime/Shoko-WebUI";
    changelog = "https://github.com/ShokoAnime/Shoko-WebUI/releases/tag/v${finalAttrs.version}";
```

2025-01-18 05:12 UTC, diniamo commented
That should be most of the stuff, except
- the test fail, which I have no clue why it exists, nor how to fix it
- I'd rather not add a hacky update script to the main program

2025-01-20 04:37 UTC, diniamo commented
Updated to 5.1.0

2025-01-20 11:25 UTC, gepbird commented
> the test fail, which I have no clue why it exists, nor how to fix it

### Explanation of how can you debug it

This could be useful to run commands in the VM without having to rebuild it every time: https://wiki.nixos.org/wiki/NixOS_VM_tests#Connecting_to_an_interactive_VM_via_SSH
After copying the ssh config from that wiki into `nodes.machines` in the shoko nixos test, for some reason I can't connect to it when the machine is ran by `nixbld` (this happens when you do `nix-build -A nixosTests.shoko` or the same with `nix build ...`). To fix that I can build the VM, and run it as my user with `$($(nix-build -A nixosTests.shoko.driver)/bin/nixos-test-driver)`. Then I can get a shell inside the VM with `ssh root@localhost -p 2000`.

Inside the VM, the shoko service throws `Access to the path '/var/lib/shoko/settings-server.json' is denied.`. This file doesn't exists, there are only webui files:

```console
[root@machine:~]# find -L /var/lib/shoko
/var/lib/shoko
/var/lib/shoko/webui
/var/lib/shoko/webui/favicon.ico
/var/lib/shoko/webui/version.json
/var/lib/shoko/webui/assets
/var/lib/shoko/webui/assets/sora-latin-100-normal-wz_LKC25.woff2
/var/lib/shoko/webui/assets/sora-latin-400-normal-DZtuNFrm.woff2
/var/lib/shoko/webui/assets/sora-latin-200-normal-CSO-6fll.woff2
/var/lib/shoko/webui/assets/sora-latin-500-normal-D6ntt6OU.woff2
/var/lib/shoko/webui/assets/sora-latin-300-normal-sH7t8am-.woff2
/var/lib/shoko/webui/assets/sora-latin-600-normal-C1m6bnBo.woff2
/var/lib/shoko/webui/assets/sora-latin-700-normal-CcRYJWjj.woff2
/var/lib/shoko/webui/assets/sora-latin-800-normal-B4rKiZhk.woff2
/var/lib/shoko/webui/assets/OnePiece-CCVDVjBa.png
/var/lib/shoko/webui/assets/sora-latin-100-normal-Db8iwt7l.woff
/var/lib/shoko/webui/assets/sora-latin-200-normal-E31gOQMh.woff
/var/lib/shoko/webui/assets/sora-latin-500-normal-CmPS9DAJ.woff
/var/lib/shoko/webui/assets/sora-latin-600-normal-DC-VVm69.woff
/var/lib/shoko/webui/assets/sora-latin-700-normal-7BwG48_h.woff
/var/lib/shoko/webui/assets/sora-latin-800-normal-PDlJt_sS.woff
/var/lib/shoko/webui/assets/sora-latin-400-normal-woMVPSgH.woff
/var/lib/shoko/webui/assets/monaco-editor-CWFJhXPe.css
/var/lib/shoko/webui/assets/index-CjvHA5ht.css
/var/lib/shoko/webui/assets/sora-latin-300-normal-_gcayfTt.woff
/var/lib/shoko/webui/assets/shoko_mascot-BxR7aIJM.png
/var/lib/shoko/webui/assets/@monaco-editor
/var/lib/shoko/webui/assets/@monaco-editor/react-CmuKTs2V.js
/var/lib/shoko/webui/assets/@monaco-editor/react-CmuKTs2V.js.map
/var/lib/shoko/webui/assets/common-0jV1spn5.js
/var/lib/shoko/webui/assets/monaco-editor-gpLA3-Rd.js
/var/lib/shoko/webui/assets/vendor-DsPoBL21.js
/var/lib/shoko/webui/assets/index-s1tCB-Bw.js
/var/lib/shoko/webui/assets/RenamerEditor-BgClqkFS.js
/var/lib/shoko/webui/assets/javascript-BrYQgcVz.js
/var/lib/shoko/webui/assets/lua-nf6ki56Z.js
/var/lib/shoko/webui/assets/typescript-Bu_7SVrm.js
/var/lib/shoko/webui/assets/yaml-CqiVQN8T.js
/var/lib/shoko/webui/assets/typescript-Bu_7SVrm.js.map
/var/lib/shoko/webui/assets/yaml-CqiVQN8T.js.map
/var/lib/shoko/webui/assets/lua-nf6ki56Z.js.map
/var/lib/shoko/webui/assets/RenamerEditor-BgClqkFS.js.map
/var/lib/shoko/webui/assets/javascript-BrYQgcVz.js.map
/var/lib/shoko/webui/assets/common-0jV1spn5.js.map
/var/lib/shoko/webui/assets/index-s1tCB-Bw.js.map
/var/lib/shoko/webui/assets/vendor-DsPoBL21.js.map
/var/lib/shoko/webui/assets/monaco-editor-gpLA3-Rd.js.map
/var/lib/shoko/webui/assets/editor.worker-oRlJJsnX.js.map
/var/lib/shoko/webui/assets/editor.worker-oRlJJsnX.js
/var/lib/shoko/webui/index.html
```

Since the file doesn't exist and dotnet throws an access denied error, most likely the parent directory has permission issues:

```console
[root@machine:/]# stat /var/lib/shoko/
  File: /var/lib/shoko/
  Size: 4096      	Blocks: 8          IO Block: 4096   directory
Device: 253,0	Inode: 168         Links: 2
Access: (0700/drwx------)  Uid: (    0/    root)   Gid: (    0/    root)
Access: 2025-01-20 11:03:11.662780450 +0000
Modify: 2025-01-20 11:01:03.098375196 +0000
Change: 2025-01-20 11:01:03.098375196 +0000
 Birth: 2025-01-20 11:01:03.085373543 +0000
```

### Conclusion/TLDR

`/var/lib/shoko` is only accessible by root, when the service is running with the shoko user and group correctly. To fix this, you can set the user and group for the directory:
```diff
diff --git a/nixos/modules/services/misc/shoko.nix b/nixos/modules/services/misc/shoko.nix
index de000171f828..ebc7ed82e19d 100644
--- a/nixos/modules/services/misc/shoko.nix
+++ b/nixos/modules/services/misc/shoko.nix
@@ -70,7 +70,7 @@ in
     #    imperative plugins as well), then symlink the specified plugins.
     system.activationScripts.shoko =
       ''
-        install -dm700 '${cfg.dataDir}'
+        install -dm700 -o shoko -g shoko '${cfg.dataDir}'
       ''
       + optionalString (cfg.webui != null) ''
         rm -rf '${cfg.dataDir}/webui'

```

2025-01-20 13:35 UTC, diniamo commented
Yeah, I've found it since, but the fix won't be that simple since I gotta redo some stuff anyway

2025-01-22 05:50 UTC, diniamo commented
Alright, that should do it. @gepbird I'd appreciate some testing, if you have the time.

2025-01-22 10:06 UTC, gepbird approved these changes
Test works now and changes LGTM, thanks!

I was a bit bothered by making filesystem changes in `systemd.activationScript` and tried to replace it with `systemd.tmpfiles.rules` and `systemd.services.shoko.serviceConfig.ExecStartPre` but failed. Your solution with `StateDirectory` and `preStart` is much cleaner, nicely done.

2025-04-23 07:13 UTC, typedrat commented
I'd really appreciate having a module for this, is there anything I can do to nudge this along?

2025-04-23 10:22 UTC, diniamo commented
I'm still here, but we don't have a committer.

(Just noticed the conflicts, will resolve when I get to my computer)

2025-04-26 20:36 UTC, gepbird requested changes
Still looks good, but I noticed some improvements, thanks for fixing the merge conflict.

You can also try to reach out to mergers, or the easiest is posting the PR link in https://discourse.nixos.org/t/prs-ready-for-review or other places.

2025-04-26 20:36 UTC, gepbird commented on nixos/tests/all-tests.nix
> +  shoko = handleTest ./shoko.nix {};
nixfmt-check is failing, to fix:
```suggestion
  shoko = handleTest ./shoko.nix { };
```

2025-04-26 20:36 UTC, gepbird commented on pkgs/by-name/sh/shoko/package.nix
> +  passthru.tests.shoko = nixosTests.shoko;
Since https://github.com/Mic92/nix-update/releases/tag/1.10.0, `nix-update-script` can also update `deps.json`
```suggestion
  passthru = {
    tests.shoko = nixosTests.shoko;
    updateScript = nix-update-script { };
  };
```

2025-04-26 20:36 UTC, gepbird commented on nixos/modules/services/misc/shoko.nix
> +        StateDirectoryMode = 750;
It's a good practice to add some hardening flags, see https://nixos.wiki/wiki/Systemd_Hardening.

But I don't want to further delay this PR so feel free to skip it.

2025-04-27 01:14 UTC, typedrat commented
My only thought is potentially adding an option for a service that will sync the local cache with the [Shoko XML cache](https://docs.shokoanime.com/shoko-server/understanding-anidb-ban#utilize-the-xml-cache) ensuring it runs on launch and on a `systemd` timer, to help prevent AniDB bans for those of us with large (11 TiB in my case) collections.

2025-04-27 08:28 UTC, revam commented
1. that cache is not updated frequently
2. it's not supposed to be programmatically fetched on a timer (but we can't stop you if you do, but please don't)

2025-04-27 20:53 UTC, typedrat commented
Ah, then I retract my request.

2025-04-29 04:18 UTC, diniamo commented on nixos/modules/services/misc/shoko.nix
> +        StateDirectoryMode = 750;
Yeah sorry, not looking into this right now. Can be done in a follow-up PR by me or someone else. Or if this doesn't get merged for a while, I'll do it at some point.

2025-04-29 11:28 UTC, gepbird requested changes

2025-04-29 11:28 UTC, gepbird commented on pkgs/by-name/sh/shoko/package.nix
> +  nix-update-script
`nixfmt-check` is complaining again:
```suggestion
  nix-update-script,
```

In the future you could try running `nix fmt` inside the `nixpkgs` folder to format every file. At first it can takes a few minutes but after that its ~300ms.

2025-04-29 12:49 UTC, gepbird approved these changes

2025-06-06 18:53 UTC, nanoyaki requested changes
Apart from this one comment, everything LGTM! Tests runs after removing the import mentioned and rebasing. Thanks for packaging this!

2025-06-06 18:53 UTC, nanoyaki commented on nixos/tests/shoko.nix
> +import ./make-test-python.nix (
This import is redundant and unwanted. See [handleTest -> runTest](https://github.com/NixOS/nixpkgs/issues/386873#:~:text=Remove%20any%20import,the%20callback%20function.).

2025-06-07 03:27 UTC, diniamo commented on nixos/tests/shoko.nix
> +import ./make-test-python.nix (
Thanks, that was my fault.

2025-08-01 21:01 UTC, Mojken commented
What's the current status on this? Has anything happened the last two months?

2025-08-02 00:07 UTC, gepbird requested changes
Other than that, it looks good and the NixOS test passes

2025-08-02 03:30 UTC, diniamo commented
> What's the current status on this? Has anything happened the last two months?

We are almost at a 1 year anniversary :partying_face: :partying_face: :partying_face:

2025-08-02 12:33 UTC, gepbird approved these changes

2025-08-02 12:34 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/2493

2025-10-24 21:02 UTC, typedrat commented
Anything that can be done to nudge this back along? I've been using this with great success on my server for a few months, but I'd love to stop having a whole second `nixpkgs` as a flake input just to purloin the module out of it.

2025-10-25 05:12 UTC, diniamo commented
I can't do much more. Personally, I run my own Nixpkgs branch, since there are constantly several unmerged PRs that I need.

2025-10-25 07:45 UTC, gepbird commented
> I can't do much more. Personally, I run my own Nixpkgs branch, since there are constantly several unmerged PRs that I need.

Yeah it's unfortunate that some PRs get neglected for months or years.

I made a tool where you can include a nixpkgs PR as a flake input, because I got bored of maintaining  my nixpkgs branch with the PRs I'd like to be merged, it could be helpful to you too: http://github.com/gepbird/nixpkgs-patcher :)

2025-10-25 07:54 UTC, diniamo commented
Neat, I'll consider it. I'm really just waiting for native flake input patching in Nix - I don't want to introduce an IFD for example.

2025-10-25 07:54 UTC, Mojken commented
Omg I love this. I tried to figure something like this out myself, but couldn't work it out. I'll be adding this (and this PR) to my system shortly, thank you very much.


On 25 October 2025 16:45:31 GMT+09:00, "Gergő Gutyina" ***@***.***> wrote:
>gepbird left a comment (NixOS/nixpkgs#350065)
>
>> I can't do much more. Personally, I run my own Nixpkgs branch, since there are constantly several unmerged PRs that I need.
>
>Yeah it's unfortunate that same PRs get neglected for months or years.
>
>I made a tool where you can include a nixpkgs PR as a flake input, because I got bored of maintaining  my nixpkgs branch with the PRs I'd like to be merged, it could be helpful to you too: http://github.com/gepbird/nixpkgs-patcher :)
>
>-- 
>Reply to this email directly or view it on GitHub:
>https://github.com/NixOS/nixpkgs/pull/350065#issuecomment-3446106410
>You are receiving this because you are subscribed to this thread.
>
>Message ID: ***@***.***>

2025-10-30 21:28 UTC, nanoyaki approved these changes

2025-12-20 08:59 UTC, gepbird reviewed
Can you rebase to master and create a release note entry for the new module?

I recently got commit access, so the long wait for this PR could be over :)

2025-12-21 10:48 UTC, diniamo commented
@gepbird do you want to be a maintainer perhaps? Honestly, I didn't really use Shoko after trying it for a short while, so I'm not sure how long I'll want to maintain a package for it.

2025-12-21 10:57 UTC, gepbird commented
> @gepbird do you want to be a maintainer perhaps? Honestly, I didn't really use Shoko after trying it for a short while, so I'm not sure how long I'll want to maintain a package for it.

I don't plan to be a maintainer of shoko. if you want to remove yourself from the maintainers, I hope someone else can pick it up as there are 11 more people interested in it.

2025-12-21 20:33 UTC, nanoyaki commented
I'd be willing to maintain the package as I've been maintaining a nightly updated version of it in [nanopkgs](https://git.theless.one/nanoyaki/nanopkgs)

2025-12-21 22:05 UTC, gepbird commented
For the release notes, adding a line for the NixOS module should be fine. For example in `nixos/doc/manual/release-notes/rl-2605.section.md` you could add something like:
```
- [shoko](https://shokoanime.com/), an anime management system. Available as [services.shoko](#opt-services.shoko.enable).
```

2025-12-22 07:57 UTC, diniamo commented
@nanoyaki thanks, added you.

2025-12-22 09:35 UTC, gepbird reviewed
One last thing: CI complains about formatting: https://github.com/NixOS/nixpkgs/actions/runs/20425516100/job/58684979664?pr=350065
You can run `nix fmt` to auto fix but it can take a few seconds/minutes.

2025-12-22 11:24 UTC, diniamo commented
Sigh... Already done that, but I forgot to push.

2025-12-22 17:00 UTC, gepbird commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 350065 --package nixosTests.shoko`
Commit: `59406af63f84ed09f51de4e39f0d643e1ecf1c3d`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.shoko</li>
  </ul>
</details>

2025-12-22 17:01 UTC, gepbird approved these changes

2025-12-22 17:08 UTC, merged