virtualbox: 7.0.20 -> 7.0.22
NixOS/nixpkgs pull request #350707
Opened 2024-10-23 13:01 UTC by LeSuisse

Fixes CVE-2024-21248, CVE-2024-21253, CVE-2024-21259, CVE-2024-21263 and CVE-2024-21273.

Changelog:
https://www.virtualbox.org/wiki/Changelog-7.0#v22

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-23 16:36 UTC, blitz approved these changes
Looks good from the changes. Can't test it right now though.

2024-10-24 09:01 UTC, FriedrichAltheide approved these changes

2024-10-24 09:03 UTC, FriedrichAltheide requested changes
Please remove the second commit

2024-10-24 09:04 UTC, FriedrichAltheide commented
@blitz Could you please create a PR once, you have released a (official) virtualboxKVM patch for the 7.0.22 version

2024-10-24 14:49 UTC, LeSuisse commented
> Please remove the second commit

As you wish but this need to be backported to stable so I would have preferred to not a break a package.

2024-10-24 15:14 UTC, FriedrichAltheide approved these changes

2024-10-24 17:17 UTC, FriedrichAltheide approved these changes

2024-10-25 09:27 UTC, merged

2024-10-28 12:08 UTC, bjornfor commented
Is virtualboxKvm an unimportant package that we're OK with breaking? Because this PR breaks it, and now I wonder whether the [backport to stable](https://github.com/NixOS/nixpkgs/pull/351261) should wait until virtualboxKvm is fixed, or not?