mem-encryption-tests: init at 0-master-2022-12-07
NixOS/nixpkgs pull request #351062
Opened 2024-10-25 01:37 UTC by lynatic1337

## Things done
Add https://github.com/AMDESE/mem-encryption-tests to nixpkgs. This adds a kernel module that allows to check whether TSME is enabled and working as intended on supported systems while booted.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-26 10:23 UTC, FliegendeWurst requested changes
Just some general suggestions. Unfortunately I can't test the module.

2024-10-26 10:23 UTC, FliegendeWurst commented on pkgs/os-specific/linux/mem-encryption-tests/default.nix
> +  version = "0-master-2022-12-07";
```suggestion
  version = "0-unstable-2022-12-07";
```

2024-10-26 10:23 UTC, FliegendeWurst commented on pkgs/os-specific/linux/mem-encryption-tests/default.nix
> +  '';
```suggestion
  installPhase = ''
    runHook preInstall

    mkdir -p $out/lib/modules/${kernel.modDirVersion}/extra
    cp tsme-test.ko $out/lib/modules/${kernel.modDirVersion}/extra

    runHook postInstall
  '';
```

2024-10-26 10:23 UTC, FliegendeWurst commented on pkgs/os-specific/linux/mem-encryption-tests/default.nix
> +    license = licenses.gpl2;
```suggestion
    license = licenses.gpl2Only;
```

2024-10-26 10:23 UTC, FliegendeWurst commented on pkgs/os-specific/linux/mem-encryption-tests/default.nix
> +{ lib, stdenv, fetchFromGitHub, linuxPackages, kernel ? linuxPackages.kernel }:
```suggestion
{
  lib,
  stdenv,
  fetchFromGitHub,
  linuxPackages,
  kernel ? linuxPackages.kernel,
}:
```

2024-10-26 17:18 UTC, zi3m5f requested changes

2024-10-27 00:55 UTC, lynatic1337 commented
Thanks for the suggestions and fixes @zi3m5f @FliegendeWurst, I've included them all in this new revision <3
Additionally I fixed the wrong attributes that somehow made it into this file by accident, the revision before would build the module for **some** kernel but not the kernel used in the system configuration.

2024-10-27 11:51 UTC, zi3m5f requested changes
- [x] Checked `githubId`

I think the package name should contain `tsme` to be easier to find.

2024-10-27 22:01 UTC, lynatic1337 commented
@zi3m5f thanks for the other suggestions, implemented them as well. Package is now renamed to tsme-test, in case AMD decides to add separate modules/tools for other memory-encryption systems we have to change the name back but considering the fact they haven't added any other modules in years...

INSTALL_MOD_PATH was left over from an old version and does nothing, apologies for not noticing.

2024-10-27 22:44 UTC, zi3m5f approved these changes
Thanks, LGTM :)

Build with latest kernel and checked with `modinfo`:
> filename:       result/lib/modules/6.11.5/extra/tsme-test.ko
description:    TSME test module
license:        GPL
author:         Advanced Micro Devices, Inc.
depends:        
retpoline:      Y
name:           tsme_test
vermagic:       6.11.5 SMP preempt mod_unload 
parm:           debug: print extra debug information - any non-zero value (uint)

2025-01-08 21:54 UTC, FliegendeWurst approved these changes

2025-01-08 21:54 UTC, merged