xpar: init at 0.5
NixOS/nixpkgs pull request #351259
Opened 2024-10-25 19:38 UTC by mrbenjadmin

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-10-26 10:11 UTC, FliegendeWurst requested changes

2024-10-26 10:11 UTC, FliegendeWurst commented on pkgs/by-name/xp/xpar/package.nix
> +  }
There should be another newline here

2024-10-26 10:11 UTC, FliegendeWurst commented on pkgs/by-name/xp/xpar/package.nix
> +      description = "An error/erasure code system guarding data integrity.";
```suggestion
      description = "Error/erasure code system guarding data integrity";
```

2024-10-26 10:11 UTC, FliegendeWurst commented on pkgs/by-name/xp/xpar/package.nix
> +      platforms = lib.platforms.unix;
```suggestion
      platforms = lib.platforms.all;
      mainProgram = "xpar";
```
It seems to compile for Windows too.

2024-10-27 05:10 UTC, Aleksanaa approved these changes
Looks good. Please squash commits into `maintainers: add mrbenjadmin` and `xpar: init at 0.5`

2024-10-27 05:10 UTC, Aleksanaa commented on pkgs/by-name/xp/xpar/package.nix
> +  };
Better:
```suggestion

stdenv.mkDerivation (finalAttrs: {
  pname = "xpar";
  version = "0.5";

  src = fetchFromGitHub {
    owner = "kspalaiologos";
    repo = "xpar";
    rev = finalAttrs.version;
    hash = "sha256-DMUDWQqYSQjGxYOpcfwNaaM21avcZ1w3IqEhuOaabrw=";
  };
```

2024-10-29 21:42 UTC, FliegendeWurst commented on maintainers/maintainer-list.nix
Please drop the extra changes here

2024-10-29 22:57 UTC, mrbenjadmin commented on maintainers/maintainer-list.nix
I apologise, that was an embarassing mistake! Thank you for your patience.

2024-10-30 07:45 UTC, FliegendeWurst approved these changes

2024-11-01 02:40 UTC, Aleksanaa commented
@ofborg build xpar

2024-11-01 14:36 UTC, merged