portmod: 2.6.2 -> 2.8.0
NixOS/nixpkgs pull request #353324
Opened 2024-11-03 09:58 UTC by marius851000

## Things done

Updated to 2.8.0, and adapted change for the fact it now fetch some binaries (and their deps) from it’s own repo.

portmod-gui doesn’t work (but presumably didn’t previously too). This might be the subject of another PR.

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

I see there is another already opened PR regarding this: https://github.com/NixOS/nixpkgs/pull/353046
only tried with openmw. I’ll update this PR with some idea from there. And make it run on my hydra. And update my hydra for portmod package CI ( at https://hydra.mariusdavid.fr/jobset/portmod/openmw-mods )
---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-04 02:04 UTC, zimward reviewed
Maybe we could also move this package to `by-name`

2024-11-04 02:04 UTC, zimward commented on pkgs/games/portmod/default.nix
>    };
```suggestion
  meta = {
    description = "mod manager for openMW based on portage";
    homepage = "https://gitlab.com/portmod/portmod";
    license = lib.licenses.gpl3Only;
    maintainers = with lib.maintainers; [ marius851000 ];
    mainProgram = "portmod";
  };
```
See #208242

2024-11-06 18:52 UTC, marius851000 commented
@zimward regardig moving it to treewide, wasn’t it supposed to be an automated process? Or has the green light been given for manually moving it?

2024-11-16 09:31 UTC, gepbird approved these changes
Changes lgtm, builds on x86_64-linux and portmod binary works, thanks!

ZHF: https://github.com/NixOS/nixpkgs/issues/352882

2024-11-16 09:47 UTC, gepbird commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353324`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>portmod</li>
    <li>portmod.dist</li>
  </ul>
</details>

2024-11-19 15:39 UTC, LennyPenny approved these changes

2024-11-20 17:48 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4866

2024-11-21 00:30 UTC, LennyPenny commented
Actually I'm getting an error when imagemagick is needed (I see it got removed in the package here)

```
>>> Unpacking package…
>>> Unpacking bittercoastsounds.zip
>>> Unpacking bcsounds-umopp-3.2.0.2.tar.xz
>>> Preparing source in "/tmp/portmod/media-audio/bitter-coast-sounds-1.0/work/bittercoastsounds"…
INFO Applying patch /tmp/portmod/media-audio/bitter-coast-sounds-1.0/work/bcsounds-umopp-3.2.0.2/bcsounds-patch.yaml to bcsounds.esp
Could not start dynamically linked executable: magick
NixOS cannot run dynamically linked executables intended for generic
linux environments out of the box. For more information, see:
https://nix.dev/permalink/stub-ld
Traceback (most recent call last):
  File "/home/lenny/.local/share/portmod/repos/openmw/media-audio/bitter-coast-sounds/bitter-coast-sounds-1.0-r3.pybuild", line 41, in src_prepare
    self.execute("magick convert Textures/Photodragon.tga Textures/Photodragon.dds")
  File "/nix/store/3phz01ydhpjdwala2zm2k0ci4qdjvvg3-portmod-2.8.0/lib/python3.12/site-packages/portmodlib/execute.py", line 34, in execute
    proc = subprocess.run(  # nosec B603
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/nix/store/901c80rlps5q05bnjk1sj4zaz5k736nc-python3-3.12.7/lib/python3.12/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['magick', 'convert', 'Textures/Photodragon.tga', 'Textures/Photodragon.dds']' returned non-zero exit status 127.
Successfully merged 9 packages before failure.
Error occurred when attempting to merge media-audio/bitter-coast-sounds-1.0-r3::openmw
ERROR: The prepare phase of the pybuild /home/lenny/.local/share/portmod/repos/openmw/media-audio/bitter-coast-sounds/bitter-coast-sounds-1.0-r3.pybuild failed.
Do not report this error message by itself. There will be another error message from the sandboxed code for the actual problem, probably directly above this one.
```

2024-12-14 08:52 UTC, FliegendeWurst requested changes

2024-12-14 08:52 UTC, FliegendeWurst commented on pkgs/by-name/po/portmod/package.nix
> -    imagemagick
Still required https://github.com/NixOS/nixpkgs/pull/353324#issuecomment-2489821369

2024-12-14 08:52 UTC, FliegendeWurst commented on pkgs/by-name/po/portmod/package.nix
>      description = "mod manager for openMW based on portage";
```suggestion
    description = "Mod manager for OpenMW based on portage";
```

2025-01-11 17:27 UTC, gbtb commented
> Actually I'm getting an error when imagemagick is needed (I see it got removed as a dependency in the package here)
> 
> ```
> >>> Unpacking package…
> >>> Unpacking bittercoastsounds.zip
> >>> Unpacking bcsounds-umopp-3.2.0.2.tar.xz
> >>> Preparing source in "/tmp/portmod/media-audio/bitter-coast-sounds-1.0/work/bittercoastsounds"…
> INFO Applying patch /tmp/portmod/media-audio/bitter-coast-sounds-1.0/work/bcsounds-umopp-3.2.0.2/bcsounds-patch.yaml to bcsounds.esp
> Could not start dynamically linked executable: magick
> NixOS cannot run dynamically linked executables intended for generic
> linux environments out of the box. For more information, see:
> https://nix.dev/permalink/stub-ld
> Traceback (most recent call last):
>   File "/home/lenny/.local/share/portmod/repos/openmw/media-audio/bitter-coast-sounds/bitter-coast-sounds-1.0-r3.pybuild", line 41, in src_prepare
>     self.execute("magick convert Textures/Photodragon.tga Textures/Photodragon.dds")
>   File "/nix/store/3phz01ydhpjdwala2zm2k0ci4qdjvvg3-portmod-2.8.0/lib/python3.12/site-packages/portmodlib/execute.py", line 34, in execute
>     proc = subprocess.run(  # nosec B603
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/nix/store/901c80rlps5q05bnjk1sj4zaz5k736nc-python3-3.12.7/lib/python3.12/subprocess.py", line 571, in run
>     raise CalledProcessError(retcode, process.args,
> subprocess.CalledProcessError: Command '['magick', 'convert', 'Textures/Photodragon.tga', 'Textures/Photodragon.dds']' returned non-zero exit status 127.
> Successfully merged 9 packages before failure.
> Error occurred when attempting to merge media-audio/bitter-coast-sounds-1.0-r3::openmw
> ERROR: The prepare phase of the pybuild /home/lenny/.local/share/portmod/repos/openmw/media-audio/bitter-coast-sounds/bitter-coast-sounds-1.0-r3.pybuild failed.
> Do not report this error message by itself. There will be another error message from the sandboxed code for the actual problem, probably directly above this one.
> ```

Did it work for you on a previous version of portmod? As far as I remember, when I tried to use portmod couple of years ago, the problem with bundled imagemagick was present already, and I had to manually delete it from portmod prefix to unblock myself.
I opened an [issue](https://gitlab.com/portmod/openmw-mods/-/issues/695) upstream, and hopefully soon more idiomatic solution to force usage of system-provided imagemagick will be added to portmod repository.

2025-06-27 21:12 UTC, closed without merging