python312Packages.facedancer: 2019.3.2 -> 3.0.4
NixOS/nixpkgs pull request #353404
Opened 2024-11-03 14:46 UTC by carlossless

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-05 17:21 UTC, carlossless commented
Result of `nixpkgs-review pr 353404` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.facedancer</li>
    <li>python311Packages.facedancer.dist</li>
    <li>python312Packages.facedancer</li>
    <li>python312Packages.facedancer.dist</li>
  </ul>
</details>

2024-11-06 20:56 UTC, sarahec commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353404`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.facedancer</li>
    <li>python311Packages.facedancer.dist</li>
    <li>python312Packages.facedancer</li>
    <li>python312Packages.facedancer.dist</li>
  </ul>
</details>

2024-11-06 21:03 UTC, sarahec requested changes

2024-11-06 21:03 UTC, sarahec commented on pkgs/development/python-modules/facedancer/default.nix
>    src = fetchPypi {
It's better to build this from source, see https://github.com/greatscottgadgets/facedancer

2024-11-06 21:03 UTC, sarahec commented on pkgs/development/python-modules/facedancer/default.nix
> +    homepage = "https://github.com/greatscottgadgets/facedancer";
Homepage is good, please add a changelog

2024-11-06 21:26 UTC, sarahec commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353404`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.facedancer</li>
    <li>python311Packages.facedancer.dist</li>
    <li>python312Packages.facedancer</li>
    <li>python312Packages.facedancer.dist</li>
  </ul>
</details>

2024-11-06 21:32 UTC, sarahec commented
Result of `nixpkgs-review pr 353404` run on aarch64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>4 packages built:</summary>
  <ul>
    <li>python311Packages.facedancer</li>
    <li>python311Packages.facedancer.dist</li>
    <li>python312Packages.facedancer</li>
    <li>python312Packages.facedancer.dist</li>
  </ul>
</details>

2024-11-06 21:33 UTC, sarahec approved these changes
Thank you. LGTM.

2024-11-07 10:51 UTC, merged

2024-11-07 12:45 UTC, carlossless commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353404`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.facedancer</li>
    <li>python311Packages.facedancer.dist</li>
    <li>python312Packages.facedancer</li>
    <li>python312Packages.facedancer.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.facedancer</li>
    <li>python311Packages.facedancer.dist</li>
    <li>python312Packages.facedancer</li>
    <li>python312Packages.facedancer.dist</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.facedancer</li>
    <li>python311Packages.facedancer.dist</li>
    <li>python312Packages.facedancer</li>
    <li>python312Packages.facedancer.dist</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.facedancer</li>
    <li>python311Packages.facedancer.dist</li>
    <li>python312Packages.facedancer</li>
    <li>python312Packages.facedancer.dist</li>
  </ul>
</details>