nixos/nebula: add CAP_NET_BIND_SERVICE when lighthouse node serves DNS
NixOS/nixpkgs pull request #353665
Opened 2024-11-04 16:15 UTC by siriobalmelli

Serving DNS fails in the absence of CAP_NET_BIND_SERVICE.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-06 07:10 UTC, siriobalmelli commented
@numinit I would appreciate your review on this 🙏

2024-11-17 06:50 UTC, numinit requested changes

2024-11-17 06:50 UTC, numinit commented on nixos/modules/services/networking/nebula.nix
> +        ] ++ (optionals (settings.lighthouse.serve_dns or false) [
This condition should probably be:

```
let
  nebulaPort = settings.listen.port;
  dnsPort = if (settings.lighthouse.serve_dns or false) then settings.lighthouse.dns.port or -1 else -1;
in nebulaPort > 0 && nebulaPort < 1024 || dnsPort > 0 && dnsPort < 1024;
```

Do you mind adding `services.nebula.networks.<name>.dns.{enable,port,host}` as well? The port should likely default to 5353 so we don't need the extra capability.

2024-11-17 06:51 UTC, numinit commented
May be worth updating the NixOS test too.

2024-12-21 23:53 UTC, numinit commented
Hey, thanks for taking this btw! Let me know if you need any help getting it across the finish line.

2025-01-06 09:56 UTC, siriobalmelli commented
Thanks :)

Got it done and working well on my own nebula network.

A bit stumped about how to extend the tests to cover this however, any help there is appreciated.

2025-01-13 07:37 UTC, numinit requested changes

2025-01-13 07:37 UTC, numinit commented on nixos/modules/services/networking/nebula.nix
> +            (lib.optional (!settings.tun.disabled) "CAP_NET_ADMIN")
You can get rid of the parens around (lib.optional ..) - ++ is higher precedence than the function call.

2025-01-13 07:37 UTC, numinit commented on nixos/modules/services/networking/nebula.nix
> +                default = 53;
Maybe default this to something like `5353`

2025-01-13 07:37 UTC, numinit commented
For the tests, maybe make a `dig` query to the other hosts in the network that we test. It's mostly optional though.

2025-01-13 08:10 UTC, siriobalmelli commented on nixos/modules/services/networking/nebula.nix
> +            (lib.optional (!settings.tun.disabled) "CAP_NET_ADMIN")
Thank you, TIL

2025-01-20 00:03 UTC, numinit requested changes

2025-01-20 00:03 UTC, numinit commented on nixos/modules/services/networking/nebula.nix
> +                default = "0.0.0.0";
Better default is possibly localhost.

2025-01-20 00:10 UTC, numinit commented
NixOS tests all pass, looks good except for the above unless @Jaculabilis has any more changes. Thanks for the contribution!

2025-01-20 00:15 UTC, numinit commented on nixos/tests/nebula.nix
> +        allowAny.succeed("dig @10.0.100.1 allowToLighthouse")
`dig` returns 0 if there's a NXDOMAIN. Recommend `dig @10.0.100.1 allowToLighthouse | grep -E 'allowToLighthouse\.\s+[0-9]+\s+IN\s+A\s+10\.0\.100\.4'`

2025-01-20 05:10 UTC, Jaculabilis commented on nixos/modules/services/networking/nebula.nix
> +                default = "0.0.0.0";
I agree `localhost` is better as a "secure defaults" choice, so the default doesn't listen on public interfaces. The description may want a callout, though, or have an example value of some nebula address like "10.0.0.5".

2025-01-20 07:01 UTC, siriobalmelli commented
Respun with requested changes. Unable to run nixos tests at the moment to verify DNS grep, apologies.

2025-01-20 07:16 UTC, numinit commented
Indeed it works :-)

```
allowAny: must succeed: dig @10.0.100.1 allowToLighthouse | tee /dev/stderr | grep -E 'allowToLighthouse\.\s+[0-9]+\s+IN\s+A\s+10\.0\.100\.4'
allowAny # 
allowAny # ; <<>> DiG 9.18.28 <<>> @10.0.100.1 allowToLighthouse
allowAny # ; (1 server found)
allowAny # ;; global options: +cmd
allowAny # ;; Got answer:
allowAny # ;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 41232
allowAny # ;; flags: qr rd; QUERY: 1, ANSWER: 1, AUTHORITY: 0, ADDITIONAL: 0
allowAny # ;; WARNING: recursion requested but not available
allowAny # 
allowAny # ;; QUESTION SECTION:
allowAny # ;allowToLighthouse.          IN      A
allowAny # 
allowAny # ;; ANSWER SECTION:
allowAny # allowToLighthouse.   3600    IN      A       10.0.100.4
allowAny # 
allowAny # ;; Query time: 3 msec
allowAny # ;; SERVER: 10.0.100.1#53(10.0.100.1) (UDP)
allowAny # ;; WHEN: Mon Jan 20 07:12:50 UTC 2025
allowAny # ;; MSG SIZE  rcvd: 68
allowAny # 
```

2025-01-20 07:34 UTC, numinit approved these changes

2025-01-25 21:27 UTC, numinit commented
This looks good and should be fine to merge.

2025-02-02 04:00 UTC, numinit approved these changes

2025-02-02 04:01 UTC, numinit commented on nixos/modules/services/networking/nebula.nix
> +              lighthouse.serveDns = lib.mkOption {
May be a good idea to move this to `lighthouse.dns.enable` so it's all under the same set of options.

2025-02-04 08:33 UTC, siriobalmelli commented on nixos/modules/services/networking/nebula.nix
> +              lighthouse.serveDns = lib.mkOption {
ok, respun

2025-02-04 16:16 UTC, numinit approved these changes

2025-02-09 21:42 UTC, numinit commented on nixos/modules/services/networking/nebula.nix
> +              nebulaPort = if settings.tun.disabled then settings.listen.port else 0;
This should  be `(!settings.tun.disabled)`

2025-02-09 21:43 UTC, numinit requested changes
Missed the not on disabled, that will be a bug :-)

2025-02-17 04:15 UTC, numinit commented
@siriobalmelli I think this is good except for that one bug :-)

2025-03-06 09:55 UTC, siriobalmelli commented
Apologies, I was on leave. Respinnning and testing.

2025-03-15 07:46 UTC, numinit approved these changes
LGTM, tests run just fine.

2025-03-22 03:30 UTC, numinit commented
Howdy. If you re-push, we likely have to re-test. I don't currently have merge, but will try to get someone who does.

2025-03-24 07:46 UTC, siriobalmelli commented
> Howdy. If you re-push, we likely have to re-test. I don't currently have merge, but will try to get someone who does.

oh, derp.

I have a script which rebases all my open branches on top of `master`, and this of course is no exception.

I can try to exclude PR branches from the script, but then I'd effectively be maintaining two branches for each I/P PR ... since I dogfood these PRs and e.g. am actually running Nebula in production so I need my version of the changes to be rebased on top of `master` so I can update my systems.

I haven't had trouble with this in the past, usually things eventually get merged.

@numinit do you have any advice for me on how to best deal with this without causing annoyance to anyone else in the review process? Is this just a case of needing to get someone's attention be able to merge?

2025-03-24 08:02 UTC, numinit commented
Basically, yeah. GH isn't exactly obvious with what changed. I'd have merged it since it looked good, but my commit is pending.

2025-03-25 09:04 UTC, siriobalmelli commented
Ok, will hold the updates until this goes through 🤞

2025-04-07 23:16 UTC, siriobalmelli commented
Bump. Any chance this can get merged? 😄

2025-04-07 23:35 UTC, numinit commented
@rosscomputerguy another one for you

2025-04-08 00:03 UTC, RossComputerGuy commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353665`

---
### `aarch64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>

2025-04-08 00:26 UTC, RossComputerGuy approved these changes
Had to run the tests myself and it succeeded.
![image0](https://github.com/user-attachments/assets/7dbcd236-370a-49fc-82ff-4f5529c129f9)

2025-04-08 00:27 UTC, merged