nanoboyadvance: Build the Darwin app bundle
NixOS/nixpkgs pull request #353773
Opened 2024-11-05 08:09 UTC by nadiaholmquist

This enables the CMake options for building the macOS app bundle for the emulator and applies my patch from upstream that fixes the installation path so that NanoBoyAdvance can be installed into /Applications.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-05 17:06 UTC, ambroisie commented on pkgs/by-name/na/nanoboyadvance/package.nix
> +    })
Add a comment with a link to the PR please.

2024-11-05 17:09 UTC, ambroisie commented on pkgs/by-name/na/nanoboyadvance/package.nix
> +    })
Should be fine then.

2024-11-05 23:13 UTC, matteo-pacini approved these changes, later dismissed
LGTM

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 353773`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>nanoboyadvance</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>nanoboyadvance</li>
  </ul>
</details>

2025-05-11 14:45 UTC, TomaSajt reviewed
Sorry for the wait, this went under my radar...
I'll leave a review soon.

2025-05-11 15:09 UTC, TomaSajt requested changes
Please apply the following changes:

```patch
-    ++ lib.optionals stdenv.isDarwin [
+    ++ lib.optionals stdenv.hostPlatform.isDarwin [
       (lib.cmakeBool "MACOS_BUILD_APP_BUNDLE" true)
       (lib.cmakeBool "MACOS_BUNDLE_QT" false)
     ];

+  # make the app runnable from the terminal or via `nix run`
+  postInstall = lib.optionals stdenv.hostPlatform.isDarwin ''
+    mkdir -p "$out/bin"
+    ln -s "$out/Applications/NanoBoyAdvance.app/Contents/MacOS/NanoBoyAdvance" "$out/bin/NanoBoyAdvance"
+  '';
+
```

Note: `stdenv.is*` has been deprecated in favour of `stdenv.hostPlatform.is*`
Note: `nix run .#nanoboyadvance` would look at `meta.mainProgram` and try to run a binary named that in `$out/bin/`

2025-05-12 19:18 UTC, TomaSajt approved these changes
LGTM

2025-05-16 08:06 UTC, merged