mangojuice: init at 0.7.8
NixOS/nixpkgs pull request #354321
Opened 2024-11-07 20:44 UTC by pluiedev

Fixes #354175

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-09 21:05 UTC, KiaraGrouwstra commented
Result of `nixpkgs-review pr 354321` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mangojuice</li>
  </ul>
</details>

2024-11-09 21:05 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/2109

2024-11-29 08:07 UTC, FliegendeWurst approved these changes

2024-12-08 02:16 UTC, getchoo requested changes

2024-12-08 02:16 UTC, getchoo commented on pkgs/by-name/ma/mangojuice/package.nix
> +
```suggestion

  strictDeps = true;

```
Good for cross comp since we need some native and host versions of dependencies at once (like glib)

2024-12-08 02:16 UTC, getchoo commented on pkgs/by-name/ma/mangojuice/package.nix
> +    makeBinaryWrapper
```suggestion
    glib # For glib-complie-schemas
    meson
    ninja
    vala
    pkg-config
    makeBinaryWrapper
```
Doesn't seem we need CMake as we're using a shared vulkan-tools (unlike upstream)

2024-12-08 02:16 UTC, getchoo commented on pkgs/by-name/ma/mangojuice/package.nix
> +    mangohud
```suggestion
```
We shouldn't need this here as upstream is only calling the binary, not the library or anything

2024-12-08 02:16 UTC, getchoo commented on pkgs/by-name/ma/mangojuice/package.nix
> +    maintainers = with lib.maintainers; [ pluiedev ];
```suggestion
    maintainers = with lib.maintainers; [
      pluiedev
      getchoo
    ];
```
This project seems cool. Feel free to add me

2024-12-08 02:16 UTC, getchoo commented on pkgs/by-name/ma/mangojuice/package.nix
> +
```suggestion

  passthru = {
    updateScript = nix-update-script { };
  };

```
This will also help with maintenance

2024-12-09 18:40 UTC, getchoo commented
@ofborg build mangojuice mangojuice.passthru.tests

2024-12-09 18:49 UTC, getchoo approved these changes

2024-12-09 18:50 UTC, merged