janeStreet: 0.9.0 -> 0.10.0 [WIP]
NixOS/nixpkgs pull request #35439
Opened 2018-02-24 02:44 UTC by mt-caret

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-02-25 10:14 UTC, vbgl requested changes

2018-02-25 10:14 UTC, vbgl commented on pkgs/development/ocaml-modules/janestreet/default.nix
>    } // (if lib.versionAtLeast ocaml.version "4.06"
This test should be dropped.

2018-02-25 10:14 UTC, vbgl commented on pkgs/development/ocaml-modules/janestreet/default.nix
> +  # opens a world of pain)
See  #35418

2018-02-25 10:14 UTC, vbgl commented on pkgs/development/ocaml-modules/janestreet/default.nix
> +    meta.broken = !lib.versionAtLeast ocaml.version "4.05";
This line should be removed.

2018-02-25 10:14 UTC, vbgl commented on pkgs/development/ocaml-modules/janestreet/default.nix
> +    version = "0.9.0";
Does it make sense to keep this package?

2018-02-27 14:11 UTC, mt-caret commented on pkgs/development/ocaml-modules/janestreet/default.nix
> +  # opens a world of pain)
I'll fix this when the PR gets merged.

2018-03-01 08:13 UTC, vbgl commented
`ctypes` has been updated. Can you please rebase?

2018-03-02 02:39 UTC, mt-caret commented
Hmm, did I mess up rebase? :cry:

2018-03-02 20:01 UTC, Ericson2314 commented
hehe yes. Use `git rebase -i` and try again.

2018-03-03 02:58 UTC, mt-caret commented
I think I got it right this time.
@vbgl Sorry for the delay.

2018-03-03 09:56 UTC, vbgl commented on pkgs/development/ocaml-modules/janestreet/janePackage.nix
>  if !stdenv.lib.versionAtLeast ocaml.version "4.03"
Did you test with 4.03 ? I think 4.04 or above is required.

2018-03-03 15:11 UTC, vbgl commented
@GrahamcOfBorg build ocamlPackages.bap

2018-03-03 15:14 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35439&attempt_id=01c785e1-9e73-4179-9278-caa983eddcb9)

<details><summary>Partial log (click to expand)</summary><p>

```
checking for references to /tmp/nix-build-ocaml4.04.2-core_kernel-0.10.0.drv-0 in /nix/store/v99rbljycd5b3p63kpp7qsqkbg2jzphg-ocaml4.04.2-core_kernel-0.10.0...
building path(s) ‘/nix/store/yqks4kxpgbmpnf9lq3sggad8nspldiih-ocaml-bap-1.4.0’
unpacking sources
unpacking source archive /nix/store/gch8cxi2xhh3dvjdd7nnza7708p9rd1q-source
source root is source
patching sources
configuring
configure flags: --prefix=/nix/store/yqks4kxpgbmpnf9lq3sggad8nspldiih-ocaml-bap-1.4.0 --enable-everything --disable-ida --disable-fsi-benchmark --with-llvm-config=/nix/store/9pylfc5v0a5mlg75i5wmd6sq2idfiya9-llvm-3.8.1/bin/llvm-config
builder for ‘/nix/store/ykjzvri5598i4kn1hx61rb833xyc082x-ocaml-bap-1.4.0.drv’ failed with exit code 1
error: build of ‘/nix/store/ykjzvri5598i4kn1hx61rb833xyc082x-ocaml-bap-1.4.0.drv’ failed
```
</p></details>

2018-03-03 15:17 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35439&attempt_id=3e8e47a5-c052-4147-a899-c974d979aa71)

<details><summary>Partial log (click to expand)</summary><p>

```
building '/nix/store/ns3bsw9nc0ni02k37li6d9wn3fpxqxwa-ocaml-bap-1.4.0.drv'...
unpacking sources
unpacking source archive /nix/store/gch8cxi2xhh3dvjdd7nnza7708p9rd1q-source
source root is source
patching sources
updateAutotoolsGnuConfigScriptsPhase
configuring
configure flags: --prefix=/nix/store/63zbi3rydzzfn1nasy72v99qc6pv42i3-ocaml-bap-1.4.0 --enable-everything --disable-ida --disable-fsi-benchmark --with-llvm-config=/nix/store/9f58zhm11iq8ja3y5d2lwhzkgcrfvm7z-llvm-3.8.1/bin/llvm-config
builder for '/nix/store/ns3bsw9nc0ni02k37li6d9wn3fpxqxwa-ocaml-bap-1.4.0.drv' failed with exit code 1
[31;1merror:[0m build of '/nix/store/ns3bsw9nc0ni02k37li6d9wn3fpxqxwa-ocaml-bap-1.4.0.drv' failed
```
</p></details>

2018-03-03 15:29 UTC, vbgl commented
This PR breaks `bad`. That’s an annoying regression.

2018-03-03 16:13 UTC, mt-caret commented
I guess the solution is to keep the 0.9.0 versions around (under a different name like janeStreet_0_9_0, perhaps) and have use that version for all of bap's dependencies (and all of their dependencies, and so on). I have no idea how one will go about doing that or if that's even possible.

I've tried to inject the 0.9.0 versions of core_kernel and ppx_jane for bap, but of course that ends up with errors about other dependencies dependent on core_kernel/ppx_jane/etc. 0.10.0.

How should we proceed?

2018-03-03 17:20 UTC, vbgl commented
Maybe ask upstream (`bap`) plans about compatibility with `core_kernel-0.10.0`?

2018-03-05 16:42 UTC, vbgl commented
Possible solution: keep the old `janestreet/default.nix` file around (under a new name, fixing a few version strings that used to be implicit), import it (as before) under a specific attribute (say `janeStreet_0_9_0`) and use this attribute to feed the `bap` derivation (as in `inherit (janeStreet_0_9_0) core_kernel ppx_jane parsexp`).

This shouldn’t introduce regression and allow to update the whole bunch of janestreet libraries.

2018-03-06 14:23 UTC, mt-caret commented
I think just keeping the old janestreet/default.nix works as a temporary workaround while we wait for bap upstream to upgrade to 0.10.0 (https://github.com/BinaryAnalysisPlatform/bap/issues/786). As a bonus, if any other regressions pop up we can also fix them with janestreet/old.nix pretty easily.

2018-03-06 19:30 UTC, vbgl commented
@GrahamcOfBorg build patdiff

2018-03-06 19:40 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35439&attempt_id=feb60de8-f05a-4ff9-bf9a-859d074d0124)

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking /nix/store/ajlvy8hj05ph50a47zvysvc0v5zn50bg-ocaml4.04.2-re2-0.10.1/lib/ocaml/4.04.2/site-lib/stubslibs/dllre2_stubs.so
shrinking /nix/store/ajlvy8hj05ph50a47zvysvc0v5zn50bg-ocaml4.04.2-re2-0.10.1/lib/ocaml/4.04.2/site-lib/re2/c/re2_c.cmxs
shrinking /nix/store/ajlvy8hj05ph50a47zvysvc0v5zn50bg-ocaml4.04.2-re2-0.10.1/lib/ocaml/4.04.2/site-lib/re2/re2.cmxs
strip is /nix/store/lvx1acn1ig1j2km8jds5x3ggh3f2wa8v-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/ajlvy8hj05ph50a47zvysvc0v5zn50bg-ocaml4.04.2-re2-0.10.1/lib
patching script interpreter paths in /nix/store/ajlvy8hj05ph50a47zvysvc0v5zn50bg-ocaml4.04.2-re2-0.10.1
checking for references to /build in /nix/store/ajlvy8hj05ph50a47zvysvc0v5zn50bg-ocaml4.04.2-re2-0.10.1...
cannot build derivation '/nix/store/nhh77gxxaajlq4lqc5k4xrpjc7ry6d39-ocaml4.04.2-core_extended-0.10.0.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/3h2568z057h71chsxk7g63k7kvczkrv6-ocaml4.04.2-patdiff-0.10.0.drv': 2 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/3h2568z057h71chsxk7g63k7kvczkrv6-ocaml4.04.2-patdiff-0.10.0.drv' failed
```
</p></details>

2018-03-06 19:40 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35439&attempt_id=56738f09-2545-44ba-9ca1-76817323c030)

<details><summary>Partial log (click to expand)</summary><p>

```
         | `Word of Core.String.t ] Patience_diff_lib__Patience_diff.Hunk.t
         list
       but an expression was expected of type
         'a Patdiff_lib.Import.Patience_diff.Hunks.t =
           'a Patience_diff_lib__Patience_diff.Hunk.t list

Waiting for 1 job to finish.
make: *** [Makefile:5: default] Error 1
builder for ‘/nix/store/df30fid1ygkpfd0cb3ly4fvqa39614mn-ocaml4.04.2-patdiff-0.10.0.drv’ failed with exit code 2
error: build of ‘/nix/store/df30fid1ygkpfd0cb3ly4fvqa39614mn-ocaml4.04.2-patdiff-0.10.0.drv’ failed
```
</p></details>

2018-03-06 20:20 UTC, ivg commented
FYI, BAP has a half-a-year release cycle, so we will unlikely upgrade to the core.v0.10 earlier than that. Looping in @maurer.

2018-03-06 20:22 UTC, vbgl commented
I guess `patdiff` needs to be updated too.

2018-03-07 05:27 UTC, mt-caret commented
@vbgl Done.

2018-03-07 08:05 UTC, vbgl approved these changes

2018-03-07 08:06 UTC, merged

2018-03-07 08:10 UTC, mt-caret commented
:tada: