haskell.packages.ghc983.haskell-language-server: unbreak
NixOS/nixpkgs pull request #354305
Opened 2024-11-07 19:40 UTC by mpscholten

Applies the yet unreleased patch to get HLS working on GHC9.8.3

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-08 15:01 UTC, sternenseemann requested changes
That patch should be applied globally, not conditional on GHC version.

2024-11-08 17:40 UTC, mpscholten commented
@sternenseemann good point, just applied it globally 👍

2024-11-09 15:05 UTC, sternenseemann commented
It appears your change was largely untested. The patch was applied to the wrong package (HLS instead of ghcide) and wouldn't apply due to an extra prefix from the monorepo it lives in. I've made the necessary change in d76940773adeff338d47b2d7c79a23da0d96e282.

2024-11-09 15:05 UTC, closed without merging

2024-11-09 18:02 UTC, mpscholten commented
I ran the following to test locally:

```bash
cd nixpkgs
nix build .#haskell.packages.ghc98.haskell-language-server
```

after a long while it produced a working binary. That got me to think that this patch works.

How did you test this patch / what commands do you typically run to test a PR like this? This way I'll try to test it more carefully next time.

(Now from reading over it, I guess `ghc98` is not ghc 9.8.3 but ghc 9.8.2. But then the patch should still have failed, right?)

2024-11-10 14:33 UTC, sternenseemann commented
> (Now from reading over it, I guess `ghc98` is not ghc 9.8.3 but ghc 9.8.2. But then the patch should still have failed, right?)

Yes, you would have tested GHC 9.8.2, though I can't explain why the patch would apply in that case…