pythonPackages.jupyterhub-oauthenticator: init at 1.1
NixOS/nixpkgs pull request #35467
Opened 2018-02-24 12:18 UTC by ixxie

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-02-24 16:10 UTC, dotlambda requested changes

2018-02-24 16:10 UTC, dotlambda commented on pkgs/development/python-modules/jupyterhub-ldapauthenticator/default.nix
> +  disabled = pythonOlder "3.4";
Why that? The README says

> I've only tested with python3 - anyone willing to test with python2 is welcome to do so! There's no reason it shouldn't work.

2018-02-24 16:10 UTC, dotlambda commented on pkgs/development/python-modules/jupyterhub-ldapauthenticator/default.nix
> +  # No tests in archive
There aren't even any on GitHub, so this should say something like `No tests implemented`

2018-02-24 16:10 UTC, dotlambda commented on pkgs/development/python-modules/jupyterhub-ldapauthenticator/default.nix
> +
whitespace

2018-02-24 20:39 UTC, ixxie commented
@dotlambda  - whoopsy, been a little sloppy there! Fixed now, hopefully.

2018-02-25 09:23 UTC, dotlambda commented
@GrahamcOfBorg build python3.pkgs.python3.pkgs.jupyterhub-ldapauthenticator

@ixxie You might want to add `disabled = !isPy3k`.

2018-02-25 09:23 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35467&attempt_id=af442c68-ff21-4572-990d-63d4d0da8af7)

<details><summary>Partial log (click to expand)</summary><p>

```
error: attribute ‘python3’ in selection path ‘python3.pkgs.python3.pkgs.jupyterhub-ldapauthenticator’ not found
```
</p></details>

2018-02-25 09:23 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35467&attempt_id=f9efe6d1-438f-4b7f-84c0-96fc8e2046db)

<details><summary>Partial log (click to expand)</summary><p>

```
[31;1merror:[0m attribute 'python3' in selection path 'python3.pkgs.python3.pkgs.jupyterhub-ldapauthenticator' not found
```
</p></details>

2018-02-25 09:23 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35467&attempt_id=97077e10-babe-4909-a135-1bf7e92b26ee)

<details><summary>Partial log (click to expand)</summary><p>

```
Installing collected packages: jupyterhub-ldapauthenticator
Successfully installed jupyterhub-ldapauthenticator-1.1
/tmp/nix-build-python3.6-jupyterhub-ldapauthenticator-1.1.drv-0/jupyterhub-ldapauthenticator-1.1
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/s708qhd4ryxiz0azlsjpab52yk43z3n2-python3.6-jupyterhub-ldapauthenticator-1.1
strip is /nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/s708qhd4ryxiz0azlsjpab52yk43z3n2-python3.6-jupyterhub-ldapauthenticator-1.1/lib 
patching script interpreter paths in /nix/store/s708qhd4ryxiz0azlsjpab52yk43z3n2-python3.6-jupyterhub-ldapauthenticator-1.1
checking for references to /tmp/nix-build-python3.6-jupyterhub-ldapauthenticator-1.1.drv-0 in /nix/store/s708qhd4ryxiz0azlsjpab52yk43z3n2-python3.6-jupyterhub-ldapauthenticator-1.1...
/nix/store/s708qhd4ryxiz0azlsjpab52yk43z3n2-python3.6-jupyterhub-ldapauthenticator-1.1
```
</p></details>

2018-02-25 09:28 UTC, dotlambda requested changes

2018-02-25 09:28 UTC, dotlambda commented on pkgs/development/python-modules/jupyterhub-ldapauthenticator/default.nix
> +    description = "Simple LDAP Authenticator Plugin for JupyterHub.";
No `.`

2018-02-25 09:28 UTC, dotlambda commented on pkgs/development/python-modules/jupyterhub-ldapauthenticator/default.nix
> +, pythonOlder
Isn't used

2018-02-25 09:30 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35467&attempt_id=1062382f-45d5-4ac9-9c47-ecc86cd715dc)

<details><summary>Partial log (click to expand)</summary><p>

```
Installing collected packages: jupyterhub-ldapauthenticator
Successfully installed jupyterhub-ldapauthenticator-1.1
/build/jupyterhub-ldapauthenticator-1.1
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/a95dawf4zpxfmy9qcdlf084fsrgznpw7-python3.6-jupyterhub-ldapauthenticator-1.1
strip is /nix/store/lvx1acn1ig1j2km8jds5x3ggh3f2wa8v-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/a95dawf4zpxfmy9qcdlf084fsrgznpw7-python3.6-jupyterhub-ldapauthenticator-1.1/lib
patching script interpreter paths in /nix/store/a95dawf4zpxfmy9qcdlf084fsrgznpw7-python3.6-jupyterhub-ldapauthenticator-1.1
checking for references to /build in /nix/store/a95dawf4zpxfmy9qcdlf084fsrgznpw7-python3.6-jupyterhub-ldapauthenticator-1.1...
/nix/store/a95dawf4zpxfmy9qcdlf084fsrgznpw7-python3.6-jupyterhub-ldapauthenticator-1.1
```
</p></details>

2018-02-25 18:11 UTC, ixxie commented
@dotlambda - I applied the requested changes. I didn't use the `disabled = !isPy3k` because the github page for the package says this could in principle work on python2 but simply wasn't tested.

2018-02-25 21:53 UTC, dotlambda approved these changes

2018-02-26 07:00 UTC, merged