pythonPackages.py_stringmatching: init at 0.4.0
NixOS/nixpkgs pull request #35471
Opened 2018-02-24 14:46 UTC by ixxie

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-02-24 16:06 UTC, dotlambda requested changes

2018-02-24 16:06 UTC, dotlambda commented on pkgs/development/python-modules/py_stringmatching/default.nix
> +  # No tests in archive
Wrong! Just look in `py_stringmatching/tests/`.
Please enable tests and use `nosetests` in the `checkPhase`.

2018-02-24 16:06 UTC, dotlambda commented on pkgs/development/python-modules/py_stringmatching/default.nix
> +    description = "This project seeks to build a Python software package that consists of a comprehensive and scalable set of string tokenizers (such as alphabetical tokenizers, whitespace tokenizers
Too long. This could be a `longDescription`. Also please split it into multiple lines.

2018-02-24 16:06 UTC, dotlambda commented on pkgs/development/python-modules/py_stringmatching/default.nix
> +
unnecessary whitespace

2018-02-24 20:51 UTC, ixxie commented
@dotlambda should be alright now!

2018-02-25 09:26 UTC, dotlambda requested changes

2018-02-25 09:26 UTC, dotlambda commented on pkgs/development/python-modules/py_stringmatching/default.nix
> +    description = "A Python string matching library including string tokenizers and string similarity measures.";
No period. See https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes.

2018-02-25 09:26 UTC, dotlambda commented on pkgs/development/python-modules/py_stringmatching/default.nix
> +    description = "A Python string matching library including string tokenizers and string similarity measures.";
Also, you can keep the previous `description` as `longDescription` if you want.

2018-02-25 18:12 UTC, ixxie commented
@dotlambda - I applied the requested changes.

2018-02-25 21:54 UTC, dotlambda approved these changes

2018-02-26 07:05 UTC, merged