geckodriver: use devel version with slog fix
NixOS/nixpkgs pull request #35507
Opened 2018-02-25 00:28 UTC by mguentner

###### Motivation for this change

geckodriver does not compile. see #35301

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-02-25 14:28 UTC, matthiasbeyer commented
Does this build?

2018-02-25 14:32 UTC, dotlambda commented
@GrahamcOfBorg build geckodriver

2018-02-25 14:37 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35507&attempt_id=1816ed94-2380-4a15-bee5-c62818107898)

<details><summary>Partial log (click to expand)</summary><p>

```
cp: -r not specified; omitting directory 'target/release/native'
cp: -r not specified; omitting directory 'target/release/examples'
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/ibb375pk56sj5hm1n1maya8ma6w6xcws-geckodriver-0.19.x-devel
shrinking /nix/store/ibb375pk56sj5hm1n1maya8ma6w6xcws-geckodriver-0.19.x-devel/bin/geckodriver
strip is /nix/store/b0zlxla7dmy1iwc3g459rjznx59797xy-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/ibb375pk56sj5hm1n1maya8ma6w6xcws-geckodriver-0.19.x-devel/bin 
patching script interpreter paths in /nix/store/ibb375pk56sj5hm1n1maya8ma6w6xcws-geckodriver-0.19.x-devel
checking for references to /tmp/nix-build-geckodriver-0.19.x-devel.drv-0 in /nix/store/ibb375pk56sj5hm1n1maya8ma6w6xcws-geckodriver-0.19.x-devel...
/nix/store/ibb375pk56sj5hm1n1maya8ma6w6xcws-geckodriver-0.19.x-devel
```
</p></details>

2018-02-25 14:43 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.35507&attempt_id=eef282dd-5ff8-4ee3-95bc-04b72c5d3b87)

<details><summary>Partial log (click to expand)</summary><p>

```
cp: -r not specified; omitting directory 'target/release/native'
cp: -r not specified; omitting directory 'target/release/deps'
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/xnqk300jnvcqv7vp98f7zgv9h2jiar72-geckodriver-0.19.x-devel
shrinking /nix/store/xnqk300jnvcqv7vp98f7zgv9h2jiar72-geckodriver-0.19.x-devel/bin/geckodriver
strip is /nix/store/lvx1acn1ig1j2km8jds5x3ggh3f2wa8v-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/xnqk300jnvcqv7vp98f7zgv9h2jiar72-geckodriver-0.19.x-devel/bin
patching script interpreter paths in /nix/store/xnqk300jnvcqv7vp98f7zgv9h2jiar72-geckodriver-0.19.x-devel
checking for references to /build in /nix/store/xnqk300jnvcqv7vp98f7zgv9h2jiar72-geckodriver-0.19.x-devel...
/nix/store/xnqk300jnvcqv7vp98f7zgv9h2jiar72-geckodriver-0.19.x-devel
```
</p></details>

2018-02-25 20:37 UTC, mguentner commented
I already made a screenshot with selenium :snake:

2018-02-26 23:45 UTC, jraygauthier requested changes
Other than that, seems fine.

2018-02-26 23:45 UTC, jraygauthier commented on pkgs/development/tools/geckodriver/default.nix
> +  version = "0.19.x-devel";
From <https://nixos.org/nixpkgs/manual/#sec-package-naming>:

> If a package is not a release but a commit from a repository, then the version part of the name must be the date of that (fetched) commit. The date must be in "YYYY-MM-DD" format. Also append "unstable" to the name - e.g., "pkgname-unstable-2014-09-23".

2018-02-27 00:16 UTC, mguentner commented on pkgs/development/tools/geckodriver/default.nix
> +  version = "0.19.x-devel";
force pushed :fire:

2018-02-27 22:15 UTC, jraygauthier requested changes
Nitpick

2018-02-27 22:15 UTC, jraygauthier commented on pkgs/development/tools/geckodriver/default.nix
> +  version = "0.19-unstable-2018-02-24";
`version = "unstable-2018-02-24";`

2018-03-01 13:58 UTC, merged