macskk: init at 1.4.1
NixOS/nixpkgs pull request #355636
Opened 2024-11-13 10:06 UTC by wattmto

This PR adds a new package of macSKK.

macSKK is a Japanese input method for macOS.

https://github.com/mtgto/macSKK

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-14 16:24 UTC, pluiedev reviewed
Overall pretty good, just some minor nitpicks (sorry for the brevity of comments, reviewing this on my phone right now)

2024-11-14 16:24 UTC, pluiedev commented on pkgs/by-name/ma/macskk/package.nix
> +    7zz x $src
I think you can use pkgs.undmg instead

2024-11-14 16:24 UTC, pluiedev commented on pkgs/by-name/ma/macskk/package.nix
> +  meta = with lib; {
Avoid `with lib;`

2024-11-14 16:24 UTC, pluiedev commented on pkgs/by-name/ma/macskk/package.nix
> +    license = licenses.gpl3;
gpl3 is deprecated, either use gpl3Only or gpl3Plus

2024-11-14 16:24 UTC, pluiedev commented on pkgs/by-name/ma/macskk/package.nix
> +    url = "https://github.com/mtgto/macSKK/releases/download/${version}/macSKK-${version}.dmg";
Consider using the finalAttrs pattern

2024-11-14 23:28 UTC, wattmto commented
@pluiedev Thank you for your review! I think I fixed all parts that has you suggested.

2024-11-15 00:19 UTC, pluiedev commented
What about using undmg? You can grep for other packages that use it in the repo

2024-11-15 05:32 UTC, wattmto commented
Sorry, I forgot to reply. undmg does not supports the .dmg file released by upstream, because the dmg has APFS in it and undmg seems only supports HFS.

```
nix run nixpkgs#undmg -- macSKK-1.4.1.dmg
error: only HFS file systems are supported.
```

2024-12-01 09:48 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/4899

2024-12-09 16:33 UTC, SuperSandro2000 commented on pkgs/by-name/ma/macskk/package.nix
> +    cp -a "Library/Containers/net.mtgto.inputmethod.macSKK" "$out/Library/Containers"
```suggestion
    mkdir -p "$out/Library/{Containers,Input Methods}"
    cp -a Library/Input Methods/macSKK.app "$out/Library/Input Methods"
    cp -a Library/Containers/net.mtgto.inputmethod.macSKK "$out/Library/Containers"
```

2024-12-11 06:17 UTC, wattmto commented on pkgs/by-name/ma/macskk/package.nix
> +    cp -a "Library/Containers/net.mtgto.inputmethod.macSKK" "$out/Library/Containers"
Done.

2024-12-11 06:20 UTC, wattmto commented
@SuperSandro2000 Thank you for your review! I fixed your suggestion. Are there anything else I can fix?

2025-01-12 01:49 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/2187

2025-01-12 02:21 UTC, natsukium requested changes

2025-01-12 02:21 UTC, natsukium commented on pkgs/by-name/ma/macskk/package.nix
> +    sha256 = "sha256-lLIFVGwt3VDsXRRGczY5VeqUyUgkX+G9tB3SGrO0voM=";
```suggestion
    hash = "sha256-lLIFVGwt3VDsXRRGczY5VeqUyUgkX+G9tB3SGrO0voM=";
```
nits

2025-01-12 02:21 UTC, natsukium commented on pkgs/by-name/ma/macskk/package.nix
> +    homepage = "https://github.com/mtgto/macSKK";
```suggestion
    homepage = "https://github.com/mtgto/macSKK";
    changelog = "https://github.com/mtgto/macSKK/blob/${finalAttrs.version}/CHANGELOG.md";
```
Adding `meta.changelog` is useful for future updates.

2025-01-12 02:21 UTC, natsukium commented on pkgs/by-name/ma/macskk/package.nix
> +    cp -a "Library/Containers/net.mtgto.inputmethod.macSKK" "$out/Library/Containers/"
```suggestion
    cp -a "Library/Containers/net.mtgto.inputmethod.macSKK" "$out/Library/Containers/"
    ln -s `$out/Library/Inputs` Methods/macSKK.app/Contents/MacOS/macSKK" "$out/bin/macSKK"
```
We could link the binary to `$out/bin` and add `meta.mainProgram = "macSKK"`.

2025-01-12 02:44 UTC, wattmto commented on pkgs/by-name/ma/macskk/package.nix
> +    license = lib.licenses.gpl3Only;
Done.

2025-01-12 02:44 UTC, wattmto commented on pkgs/by-name/ma/macskk/package.nix
> +    sha256 = "sha256-lLIFVGwt3VDsXRRGczY5VeqUyUgkX+G9tB3SGrO0voM=";
Done.

2025-01-12 02:44 UTC, wattmto commented on pkgs/by-name/ma/macskk/package.nix
> +    homepage = "https://github.com/mtgto/macSKK";
Done.

2025-01-12 02:44 UTC, wattmto commented on pkgs/by-name/ma/macskk/package.nix
> +    cp -a "Library/Containers/net.mtgto.inputmethod.macSKK" "$out/Library/Containers/"
Done.

2025-01-12 02:44 UTC, wattmto commented
@natsukium Thank you for your review!

2025-01-12 02:52 UTC, natsukium commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355636`

---
### `x86_64-linux`

---
### `aarch64-linux`

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>macskk</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>macskk</li>
  </ul>
</details>

2025-01-12 03:01 UTC, natsukium approved these changes
LGTM, thank you.

2025-01-12 03:01 UTC, merged