semgrep{,-core}: 1.74.0 -> 1.104.0
NixOS/nixpkgs pull request #355763
Opened 2024-11-13 22:33 UTC by andrew-myer

Update semgrep to 1.96.0

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-14 13:40 UTC, ambroisie commented on pkgs/development/python-modules/semgrep/default.nix
> -    ln -s $out/bin/semgrep ./bin/semgrep
Has it been removed?

2024-11-14 13:40 UTC, ambroisie commented on pkgs/development/python-modules/semgrep/default.nix
> -    ln -s $out/bin/semgrep ./bin/semgrep
(The `postInstall` still mentions a `$out/bin/semgrep`.)

2024-12-04 11:11 UTC, ambroisie commented
I'd like @06kellyjac to take a look as well before merging.

2024-12-04 16:03 UTC, 06kellyjac commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 355763`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 13 packages built:</summary>
  <ul>
    <li>python311Packages.semgrep</li>
    <li>python311Packages.semgrep.dist</li>
    <li>python311Packages.whispers</li>
    <li>python311Packages.whispers.dist</li>
    <li>semgrep (python312Packages.semgrep)</li>
    <li>semgrep.dist (python312Packages.semgrep.dist)</li>
    <li>whispers (python312Packages.whispers)</li>
    <li>whispers.dist (python312Packages.whispers.dist)</li>
    <li>route-detect</li>
    <li>route-detect.dist</li>
    <li>semgrep-core</li>
    <li>swaggerhole</li>
    <li>swaggerhole.dist</li>
  </ul>
</details>

2024-12-04 16:20 UTC, 06kellyjac requested changes
```
[nix-shell:~/.cache/nixpkgs-review/pr-355763]$ semgrep scan --metrics=off --config 'r/generic.unicode.security.bidi.contains-bidirectional-characters'

┌──── ○○○ ────┐
│ Semgrep CLI │
└─────────────┘

Traceback (most recent call last):
  File "/nix/store/2dv3sdczmkg6wjkn5ama5lgzrzhvj22v-python3.11-semgrep-1.96.0/bin/.pysemgrep-wrapped", line 9, in <module>
    sys.exit(main())
             ^^^^^^
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/console_scripts/pysemgrep.py", line 52, in main
    sys.exit(semgrep.main.main())
             ^^^^^^^^^^^^^^^^^^^
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/main.py", line 115, in main
    from semgrep.cli import cli
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/cli.py", line 5, in <module>
    from semgrep.commands.ci import ci
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/commands/ci.py", line 21, in <module>
    import semgrep.app.auth as auth
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/app/auth.py", line 8, in <module>
    from semgrep.state import get_state
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/state.py", line 13, in <module>
    from semgrep.metrics import Metrics
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/metrics.py", line 36, in <module>
    from semgrep.rule import Rule
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/rule.py", line 17, in <module>
    from semgrep.rule_lang import EmptySpan
  File "/nix/store/4h5y43skn5ra645n818176zdqs17c0b4-python3.12-semgrep-1.96.0/lib/python3.12/site-packages/semgrep/rule_lang.py", line 19, in <module>
    import jsonschema.exceptions
  File "/nix/store/pw8i005sif9wi9v539x7hlyll9f0ykcn-python3.12-jsonschema-4.23.0/lib/python3.12/site-packages/jsonschema/__init__.py", line 13, in <module>
    from jsonschema._format import FormatChecker
  File "/nix/store/pw8i005sif9wi9v539x7hlyll9f0ykcn-python3.12-jsonschema-4.23.0/lib/python3.12/site-packages/jsonschema/_format.py", line 11, in <module>
    from jsonschema.exceptions import FormatError
  File "/nix/store/pw8i005sif9wi9v539x7hlyll9f0ykcn-python3.12-jsonschema-4.23.0/lib/python3.12/site-packages/jsonschema/exceptions.py", line 15, in <module>
    from referencing.exceptions import Unresolvable as _Unresolvable
  File "/nix/store/qh6pxc98061rqx2v6rs057s6c5dbcw4q-python3.12-referencing-0.35.1/lib/python3.12/site-packages/referencing/__init__.py", line 5, in <module>
    from referencing._core import Anchor, Registry, Resource, Specification
  File "/nix/store/qh6pxc98061rqx2v6rs057s6c5dbcw4q-python3.12-referencing-0.35.1/lib/python3.12/site-packages/referencing/_core.py", line 9, in <module>
    from rpds import HashTrieMap, HashTrieSet, List
  File "/nix/store/qbpa6qshrwiljpqszmf4ppv0zbnjfhyk-python3.12-rpds-py-0.18.1/lib/python3.12/site-packages/rpds/__init__.py", line 1, in <module>
    from .rpds import *
ModuleNotFoundError: No module named 'rpds.rpds'
```

Do we need to add `rpds-py`?

---

Edit: ah it's `rpds-py` which is broken based on the stack trace

cc: @fabaff

2025-01-09 14:18 UTC, slackerbob commented
There is a message in the existing live version, 1.74.0, that it will stop working tomorrow, Jan 10 2025:

```
1.74.0

⏫  A new version of Semgrep is available. See https://semgrep.dev/docs/upgrading

⏫  Versions prior to 1.76.0 will cease to work with Semgrep.dev after Jan 10th 2025, please upgrade.
```

2025-01-24 13:33 UTC, 06kellyjac commented
Thanks for pushing this forwards @andrew-myer 
I'll try test this a bit later.

What are your thoughts on just getting this 1.96.0 update merged as-is to get something out there vs trying to update to 1.104.0 now in this PR?

---

Also FYI https://www.opengrep.dev/

2025-01-25 11:38 UTC, 06kellyjac commented
If you rebase on the latest copy of master it might introduce the issue for your build which is working. If it continues to work I'm not sure how else the issue could be occurring 

Also sorry to be a pain but your other commits should either be squashed together or prefixed with `semgrep:` (and the bump one formatted like other update commits)

2025-03-08 09:24 UTC, 06kellyjac commented
I could try test again but I think we're good. Need someone to merge

2025-03-08 10:12 UTC, merged