itgmania: init at 0.9.0
NixOS/nixpkgs pull request #355725
Opened 2024-11-13 18:20 UTC by ftsimas

## Description of changes

Adds [ITGmania](https://www.itgmania.com), a fork of StepMania 5.1 improved for the post-ITG community.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-13 18:33 UTC, thtrf commented
Please squash. More info: [commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)

2024-11-14 06:23 UTC, Sigmanificient requested changes

2024-11-14 06:23 UTC, Sigmanificient commented on pkgs/by-name/it/itgmania/package.nix
> +    rev = "v${version}";
can you use `finalAttrs.version`?

2024-11-14 06:23 UTC, Sigmanificient commented on pkgs/by-name/it/itgmania/package.nix
> +    xorg.libXtst
you should be able to import `libXtst` directly
```suggestion
    libXtst
```

2024-11-14 06:23 UTC, Sigmanificient commented on pkgs/by-name/it/itgmania/package.nix
> +    description = "A fork of StepMania 5.1, improved for the post-ITG community";
```suggestion
    description = "Fork of StepMania 5.1, improved for the post-ITG community";
```

2024-11-24 13:34 UTC, Aleksanaa commented on pkgs/by-name/it/itgmania/package.nix
> +    copyDesktopItems
```suggestion
```

2024-11-24 13:34 UTC, Aleksanaa commented on pkgs/by-name/it/itgmania/package.nix
> +    git
```suggestion
```

2024-11-24 13:34 UTC, Aleksanaa commented on pkgs/by-name/it/itgmania/package.nix
> +    pkg-config
```suggestion
```

2024-11-24 13:34 UTC, Aleksanaa commented on pkgs/by-name/it/itgmania/package.nix
> +    nasm
```suggestion
    nasm
    pkg-config
    copyDesktopItems
```

2024-12-29 14:52 UTC, uninsane commented
works well for me, if i `cd ./result/bin` before running it, otherwise it exits w/o saying why. have you seen that before? it can be fixed by wrapping `itgmania` like so:

```diff
--- pkgs/by-name/it/itgmania/package.nix
+++ pkgs/by-name/it/itgmania/package.nix
@@ -18,6 +18,7 @@
   libXtst,
   udev,
   makeDesktopItem,
+  makeWrapper,
 }:

 stdenv.mkDerivation (finalAttrs: {
@@ -37,6 +38,7 @@ stdenv.mkDerivation (finalAttrs: {
     nasm
     pkg-config
     copyDesktopItems
+    makeWrapper
   ];

   buildInputs = [
@@ -57,7 +59,9 @@ stdenv.mkDerivation (finalAttrs: {

   postInstall = ''
     mkdir -p $out/bin
-    ln -s $out/itgmania/itgmania $out/bin/itgmania
+    makeWrapper $out/itgmania/itgmania $out/bin/itgmania \
+      --run "cd $out/itgmania"

     mkdir -p $out/share/icons/hicolor/scalable/apps/
     ln -s $out/itgmania/Data/logo.svg $out/share/icons/hicolor/scalable/apps/itgmania.svg
```

2025-01-05 18:20 UTC, ftsimas commented
> works well for me, if i `cd ./result/bin` before running it, otherwise it exits w/o saying why. have you seen that before? it can be fixed by wrapping `itgmania` like so:

Thanks for testing it out! I had no problems running it from the terminal or launching it through a frontend (i.e. [emulationstation-de](https://search.nixos.org/packages?channel=unstable&show=emulationstation-de)). I couldn't however get it to launch through Plasma's application launcher, which showcased the same symptoms you are describing.

Your suggested fix seems to remedy the issue above and is certainly getting included. Thank you for your contribution!

2025-01-05 22:18 UTC, uninsane approved these changes

2025-01-12 00:10 UTC, merged