changeset: init at 2.27.9
NixOS/nixpkgs pull request #355820
Opened 2024-11-14 04:17 UTC by t-monaghan

Introduces the `changeset` cli package. This is a tool used by developers of Github projects to streamline releases by managing the version numbering and changelogs. The cli is used by developers to generate the "changeset" files which contain this data. More information can be found at the official repository here: https://github.com/changesets/changesets

My changes were made following the instructions at: https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/javascript.section.md#adding-and-updating-javascript-packages-in-nixpkgs-javascript-adding-or-updating-packages

Only one question. The instructions describe committing all files generated, however I'm unsure that the changes to the below files are intended to be included in these changes: 
- [pkgs/development/node-packages/composition.nix](https://github.com/NixOS/nixpkgs/compare/master...t-monaghan:nixpkgs:changesets?expand=1#diff-5321c2ed516e91902a95de8847a3ddd5e1d8bd60fef6d3c96dbafebbfa1d02cf)
- [pkgs/development/node-packages/node-env.nix](https://github.com/NixOS/nixpkgs/compare/master...t-monaghan:nixpkgs:changesets?expand=1#diff-e8627bff876cca02274a5c844f509e0bd78a7abf99b2a6343f1ae38847cc3502)

If it is the case that they are unintended changes, I am happy to open up a follow up PR amending the documentation.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [24.11 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) (or backporting [23.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2311.section.md) and [24.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2405.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-25 19:57 UTC, FliegendeWurst requested changes

2024-11-25 19:57 UTC, FliegendeWurst commented on pkgs/development/node-packages/composition.nix
> +    libtool = if pkgs.stdenv.isDarwin then pkgs.cctools or pkgs.darwin.cctools else null;
Please revert this change.

2024-11-25 19:57 UTC, FliegendeWurst commented on pkgs/development/node-packages/node-env.nix
> +  # Workaround to cope with utillinux in Nixpkgs 20.09 and util-linux in Nixpkgs master
I think this was fixed a while ago. Please revert all changes to this file.

2024-11-25 22:30 UTC, t-monaghan commented
Thanks for the review @FliegendeWurst, I've made those changes.

2024-11-29 07:37 UTC, FliegendeWurst commented
Oh, it seems that modifying the list of packages additionally causes all packages to update. I'll defer to the node maintainers for further review.

2024-12-16 01:06 UTC, t-monaghan commented
@wegank I have now resolved the merge conflict

2024-12-16 05:27 UTC, FliegendeWurst commented
Seems like another conflict has emerged. Must be a high-traffic file.

(btw, wegank uses a script to mark PRs - no need to tag unless they already commented)

2025-01-16 23:39 UTC, closed without merging