gitlab-runner: 17.2.0 -> 17.5.3
NixOS/nixpkgs pull request #356040
Opened 2024-11-15 00:15 UTC by bkp5190

Changelog:

https://gitlab.com/gitlab-org/gitlab-runner/blob/v17.5.3/CHANGELOG.md

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-15 00:26 UTC, bkp5190 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356040`

---
### `aarch64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>gitlab-runner</li>
  </ul>
</details>

2024-11-15 00:27 UTC, bkp5190 commented
Mentioning https://github.com/NixOS/nixpkgs/pull/349268. A newer version has been released, some of the dependencies in 17.2.0 contain known vulnerabilities.

cc @zimbatm @globin @krav @talyz @yayayayaka

2024-11-15 00:29 UTC, bkp5190 commented
> ## `nixpkgs-review` result
> Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).
> 
> Command: `nixpkgs-review pr 356040`
> 
> ### `aarch64-darwin`
> ❌ 1 package failed to build:

Not sure why nixpkgs-review is failing to build when nix-build directly on the package.nix worked as expected. Investigating now

2024-11-27 11:55 UTC, leona-ya requested changes
Thank you for your contribution!

In #359329 we update to 17.6.1, then we can also continue here. Can you please update this PR to 17.6.0 and then we should be able to merge this then :)

2024-11-27 14:47 UTC, bkp5190 commented
> Thank you for your contribution!
> 
> In #359329 we update to 17.6.1, then we can also continue here. Can you please update this PR to 17.6.0 and then we should be able to merge this then :)

17.6.0 or 17.6.1?

2024-11-27 16:20 UTC, leona-ya commented
AFAIK there is no gitlab-runner 17.6.1 release, so 17.6.0 should be fine.

2024-11-27 23:12 UTC, bkp5190 commented
Updated to version 17.6.0

2024-11-27 23:56 UTC, bkp5190 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356040`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>gitlab-runner</li>
  </ul>
</details>

2024-11-28 01:04 UTC, bkp5190 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 356040`

---
### `aarch64-darwin`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>gitlab-runner</li>
  </ul>
</details>

2024-12-08 16:54 UTC, gabyx commented
@bkp5190 : Some strange test fails:

```
       >              Error Trace:    /build/source/helpers/homedir/homedir_test.go:44
       >                                                       /build/source/helpers/homedir/homedir_test.go:82
       >               Error:          Target error should be in err chain:
       >                                   expected: "homedir variable is not set"
       >                                in chain:
       >              Test:           TestFix/HOME_variable_is_not_set_and_homedir_value_is_empty
       > FAIL
       > FAIL gitlab.com/gitlab-org/gitlab-runner/helpers/homedir     0.005s
       > FAIL
       For full logs, run 'nix-store -l /nix/store/yg45yixbwa94mql6n0jxvvyrgzk9n13d-gitlab-runner-17.6.0.drv'.
 ```
 
 on linux x86... do these passthru test work on your machine?

2024-12-08 19:34 UTC, bkp5190 commented
> @bkp5190 : Some strange test fails:
> 
> 
> 
> ```
> 
>        >              Error Trace:    /build/source/helpers/homedir/homedir_test.go:44
> 
>        >                                                       /build/source/helpers/homedir/homedir_test.go:82
> 
>        >               Error:          Target error should be in err chain:
> 
>        >                                   expected: "homedir variable is not set"
> 
>        >                                in chain:
> 
>        >              Test:           TestFix/HOME_variable_is_not_set_and_homedir_value_is_empty
> 
>        > FAIL
> 
>        > FAIL gitlab.com/gitlab-org/gitlab-runner/helpers/homedir     0.005s
> 
>        > FAIL
> 
>        For full logs, run 'nix-store -l /nix/store/yg45yixbwa94mql6n0jxvvyrgzk9n13d-gitlab-runner-17.6.0.drv'.
> 
>  ```
> 
>  
> 
>  on linux x86... do these passthru test work on your machine?
> 
>  

Yes they do, the other run is attached from linux x86

2025-03-15 01:25 UTC, digitalrane commented
@bkp5190 17.9.1 is out now with a few security fixes, so it would be good to get this PR updated to 17.9.1. If you don't have time, I'm happy to provide a diff?

@leona-ya gitlab-runner is significantly out of date (we're on 17.2 from 2024-10-22, 4+ months) - it would be great if you could re-review this, so that this package can be updated, especially given recent runner security updates in 17.9.0/17.9.1.

2025-03-15 11:09 UTC, leona-ya commented
Last time I checked this was very broken on darwin :c I tried to fix it, but it needed like 5+ fixes. Maybe now it's right to first merge this and then fix on darwin..

2025-03-15 13:08 UTC, leona-ya commented
I propose a switch to make as upstream does: https://github.com/leona-ya/nixpkgs/commit/020b08c9c443e85f0440316b8b24c3cd36003df9

2025-03-15 13:53 UTC, bkp5190 commented
> @bkp5190 17.9.1 is out now with a few security fixes, so it would be good to get this PR updated to 17.9.1. If you don't have time, I'm happy to provide a diff?
> 
> 
> 
> @leona-ya gitlab-runner is significantly out of date (we're on 17.2 from 2024-10-22, 4+ months) - it would be great if you could re-review this, so that this package can be updated, especially given recent runner security updates in 17.9.0/17.9.1.

Yea a diff would be greatly appreciated! I have not looked at these changes in a while, thanks.

2025-03-16 21:05 UTC, digitalrane commented
> I propose a switch to make as upstream does: [leona-ya@9bb4e9b](https://github.com/leona-ya/nixpkgs/commit/9bb4e9bf362f5edb9688df6c88ba2fde59784111)

@leona-ya Thank you! I think  this change makes a lot of sense! do you think it would be best to open a new PR with those changes (I can take care of this)?

perhaps if @bkp5190 has the spare time we could push that change to this branch and then update the title?

either way, I definitely think using make and mirroring more closely the upstream build approach would be good for reducing nixpkgs maintainer burden

2025-03-22 13:10 UTC, leona-ya commented
I opened a PR with my changes + a few patches to fix build on aarch64-linux and darwin

2025-04-08 02:30 UTC, closed without merging