python3Packages.qiskit*: update qiskit and remove deprecated packages
NixOS/nixpkgs pull request #357208
Opened 2024-11-19 09:24 UTC by kilianar

This pull request is an attempt to fix the broken qiskit package in nixpkgs. It removes deprecated Qiskit-related Python packages from `nixpkgs` and updates `python3Packages.qiskit` from version 1.2.2 to 1.2.4. The upstream changes consolidated functionality from `qiskit-terra` into `qiskit`, so the update primarily involved migrating the `qiskit-terra` definition into `qiskit` and making minor adjustments.

Due to time constraints, I was unable to adjust the extensive list of currently disabled tests, which must be extended to account for new test failures. As a temporary measure, I have removed the `pytestCheckHook`.

I performed some quick manual testing with qiskit, and everything appears to be working as expected.

Other `qiskit-*` packages still fail to build and should be addressed in future pull requests.
## Things done
- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-20 14:07 UTC, kilianar commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357208`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 20 packages marked as broken and skipped:</summary>
  <ul>
    <li>python311Packages.qiskit-aer</li>
    <li>python311Packages.qiskit-aer.dist</li>
    <li>python311Packages.qiskit-finance</li>
    <li>python311Packages.qiskit-finance.dist</li>
    <li>python311Packages.qiskit-machine-learning</li>
    <li>python311Packages.qiskit-machine-learning.dist</li>
    <li>python311Packages.qiskit-nature</li>
    <li>python311Packages.qiskit-nature.dist</li>
    <li>python311Packages.qiskit-optimization</li>
    <li>python311Packages.qiskit-optimization.dist</li>
    <li>python312Packages.qiskit-aer</li>
    <li>python312Packages.qiskit-aer.dist</li>
    <li>python312Packages.qiskit-finance</li>
    <li>python312Packages.qiskit-finance.dist</li>
    <li>python312Packages.qiskit-machine-learning</li>
    <li>python312Packages.qiskit-machine-learning.dist</li>
    <li>python312Packages.qiskit-nature</li>
    <li>python312Packages.qiskit-nature.dist</li>
    <li>python312Packages.qiskit-optimization</li>
    <li>python312Packages.qiskit-optimization.dist</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python311Packages.qiskit</li>
    <li>python311Packages.qiskit.dist</li>
    <li>python312Packages.qiskit</li>
    <li>python312Packages.qiskit.dist</li>
  </ul>
</details>

2024-12-07 02:16 UTC, nomeata commented
Builds and loads into jupyter here, thanks!

2025-01-15 12:00 UTC, FliegendeWurst requested changes, later dismissed

2025-01-15 12:00 UTC, FliegendeWurst commented on pkgs/top-level/python-packages.nix
> -  qiskit-ignis = callPackage ../development/python-modules/qiskit-ignis { };
You need to add entries for these in the aliases list.

2025-01-15 12:00 UTC, FliegendeWurst commented on pkgs/development/python-modules/qiskit-machine-learning/default.nix
> +    broken = true;
Please add a comment explaining why it is broken

2025-09-16 12:28 UTC, kilianar commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357208`
Commit: `e1b6f52228caa5e07a4d657b18159396fb6200f9`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>python312Packages.qiskit</li>
    <li>python312Packages.qiskit.dist</li>
    <li>python313Packages.qiskit</li>
    <li>python313Packages.qiskit.dist</li>
  </ul>
</details>

2025-09-16 15:31 UTC, SuperSandro2000 requested changes

2025-09-16 15:31 UTC, SuperSandro2000 commented on pkgs/development/python-modules/qiskit/default.nix
> +  format = "setuptools";
```suggestion
  pyproject = true;
```
we want to keep using the new pyproject variable

2025-09-16 15:31 UTC, SuperSandro2000 commented on pkgs/development/python-modules/qiskit/default.nix
> +    rev = "refs/tags/${version}";
```suggestion
    tag = version;
```
tag is doing that already

2025-09-16 15:31 UTC, SuperSandro2000 commented on pkgs/development/python-modules/qiskit/default.nix
> -    "qiskit.providers.ibmq"
Why remove the other imports?

2025-09-16 15:31 UTC, SuperSandro2000 commented on pkgs/development/python-modules/qiskit/default.nix
>    propagatedBuildInputs = [
```suggestion
  dependencies = [
```

2025-09-16 15:31 UTC, SuperSandro2000 commented on pkgs/development/python-modules/qiskit/default.nix
> +
```suggestion
  ];

  build-system = [
    setuptools
    setuptools-rust
  ];
```

2025-11-12 09:20 UTC, kilianar commented
Bumped qiskit to the latest upstream release: [2.2.3](https://github.com/Qiskit/qiskit/releases/tag/2.2.3)

2025-11-25 12:04 UTC, kilianar commented
Resolved a conflict in `pkgs/development/python-modules/qiskit-terra/default.nix`

2025-11-25 12:24 UTC, SuperSandro2000 commented on pkgs/development/python-modules/qiskit/default.nix
> +  cspLayoutPackages = [ python-constraint ];
Are those optional features? If so we should place them under optional-dependencies.

2025-11-26 13:11 UTC, SuperSandro2000 approved these changes

2025-11-26 17:14 UTC, SuperSandro2000 commented
Can you take a look at the failed builds? Thanks!

2025-11-26 17:32 UTC, kilianar commented
The build of `qiskit-nature`, `qiskit-finance`, and `qiskit-optimization` fails due to a missing dependency: `qiskit-algorithms` (not currently in nixpkgs). This likely went unnoticed during updates because these packages were already broken when qiskit itself was marked as broken.

I don't have time to package `qiskit-algorithms` and fix all the builds right now. Should I mark these packages as broken for now? This would essentially maintain the status quo, as they've been broken for the past few years anyway.

Regarding `qiskit-aer` failing to build on darwin: unfortunately, I don't have access to a darwin machine for testing, so I'm unable to diagnose the issue.

2025-11-26 18:59 UTC, SuperSandro2000 commented
Yeah, just mark all the failing things broken with a short comment and then we are fine

2025-11-27 10:59 UTC, kilianar commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357208`
Commit: `cf8099f71fd4909c12a267ae0696c12bc4e9c2f4`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 8 packages built:</summary>
  <ul>
    <li>python312Packages.qiskit</li>
    <li>python312Packages.qiskit-aer</li>
    <li>python312Packages.qiskit-aer.dist</li>
    <li>python312Packages.qiskit.dist</li>
    <li>python313Packages.qiskit</li>
    <li>python313Packages.qiskit-aer</li>
    <li>python313Packages.qiskit-aer.dist</li>
    <li>python313Packages.qiskit.dist</li>
  </ul>
</details>

2025-11-28 13:26 UTC, SuperSandro2000 approved these changes

2025-11-28 13:31 UTC, merged