tuned: init at 2.24.0
NixOS/nixpkgs pull request #357480
Opened 2024-11-20 06:44 UTC by getchoo

[Tuned](https://tuned-project.org/) is a system tuning service for Linux

Closes https://github.com/NixOS/nixpkgs/issues/305919

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-25 02:00 UTC, getchoo commented
This is going to need a module to go with it before inclusion, as the binaries are basically useless without certain things like the config file being present in /etc. Haven't used this before though, so we'll see how it goes 😆

2025-04-27 11:41 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/what-is-the-best-option-for-power-management/63406/6

2025-05-28 19:39 UTC, jalil-salame commented
Hi, I'd like to take this PR over, what needs to be done still?

2025-06-12 11:31 UTC, agvantibo-again commented
> Hi, I'd like to take this PR over, what needs to be done still?

A NixOS module for declaring the configuration, maybe tuned-ppd support but that probably should be a separate PR and package

2025-07-19 14:28 UTC, sokai commented
FYI (if overseen): @Bright-Shard [made](https://github.com/NixOS/nixpkgs/issues/305919#issuecomment-2924345970) all _puzzle pieces_ (in the _original_ issue #305919)
BR

2025-07-19 15:23 UTC, jalil-salame commented
Thanks for linking that! If I have the energy I'd gladly package all of it together!

2025-07-20 01:29 UTC, getchoo commented
Tested in the NixOS test environment. The base service seems to work fine, along with the GUI, vendored profiles, and user profiles. Would appreciate some testing on an actual laptop though, as I don't have access to one on NixOS ATM

2025-07-21 04:58 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/5691

2025-07-21 08:37 UTC, jalil-salame requested changes
TuneD should conflict with `power-profiles-daemon`: https://wiki.archlinux.org/title/CPU_frequency_scaling#tuned

2025-07-21 08:37 UTC, jalil-salame commented on nixos/modules/services/hardware/tuned.nix
> +    assertions = [
Should conflict with [`services.power-profiles-daemon.enable`](https://search.nixos.org/options?channel=25.05&show=services.power-profiles-daemon.enable&from=0&size=50&sort=relevance&type=packages&query=power-profiles) as they are incompatible, people need `services.power-profiles-daemon` then they should use `tuned-ppd`. Maybe we can setup `tuned-ppd` if `services.power-profiles-daemon` is enabled?

AFAIK some DEs (like GNOME and KDE) automatically enable `services.power-profiles-daemon` so this would create a conflict.

2025-07-22 01:13 UTC, getchoo commented on nixos/modules/services/hardware/tuned.nix
> +    assertions = [
>  Maybe we can setup tuned-ppd if services.power-profiles-daemon is enabled?

Not possible, since if `services.power-profiles-daemon` is enabled, so are its effects

I've set the `enable` option of it to `false` here though, so it should override the `mkDefault true` in GNOME, Plasma, etc. and (assuming you haven't explicitly enabled `services.power-profiles-daemon`) make everything Just Work with only `services.tuned.enable`. This does have the side effect of showing an option declaration error before the nicer assertion message if you *have* explicitly enabled PPD though, which isn't great but probably worth it?

2025-07-22 06:18 UTC, HHR2020 requested changes

2025-07-22 08:26 UTC, HHR2020 commented on nixos/modules/services/hardware/tuned.nix
> +        default = { };
I think we need the default value copied from the [ppd.conf](https://github.com/redhat-performance/tuned/blob/master/tuned/ppd/ppd.conf), which is also consistent with the config below. @getchoo

2025-07-23 01:30 UTC, getchoo commented on nixos/modules/services/hardware/tuned.nix
> +        default = { };
This is already done in the submodule declaration above

```
nix-repl> machine = nixos { services.tuned.enable = true; }

nix-repl> :p machine.config.services.tuned.ppdSettings
{
  battery = { balanced = "balanced-battery"; };
  main = {
    battery_detection = true;
    default = "balanced";
  };
  profiles = {
    balanced = "balanced";
    performance = "throughput-performance";
    power-saver = "powersave";
  };
}
```

2025-07-23 05:15 UTC, HHR2020 approved these changes

2025-07-25 05:49 UTC, jalil-salame approved these changes

2025-07-27 18:36 UTC, anna328p commented
I'm currently using the tuned package and module from the PR branch and it's working great on my system. Can't wait until this is merged!

2025-07-27 20:59 UTC, agvantibo-again approved these changes

2025-07-28 04:28 UTC, getchoo commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357480 --package nixosTests.tuned`
Commit: `1a312fd402838b66f33de12e997483e8170c377b`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.tuned</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.tuned</li>
  </ul>
</details>

2025-08-01 11:28 UTC, getchoo commented
Have been running this on my machine for the last few days with GNOME and all seems well. Fixed one last remaining issue with `/etc/tuned/profiles` not being created due to a tmpfiles.d config file conflict with the package itself. I think we're good to go!

Feel free to ping me directly if there any issues

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 357480 --package nixosTests.tuned`
Commit: `3eeb7ad06ae14a2ab58399d5e9ef0c693096a474`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.tuned</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.tuned</li>
  </ul>
</details>

2025-08-01 11:28 UTC, merged

2025-08-27 12:17 UTC, Kranzes commented
Is it expected that `tuned-adm verify` does not pass?

2025-08-27 15:15 UTC, jalil-salame commented
> Is it expected that `tuned-adm verify` does not pass?
Looking at the man page, it might fail if aome of the settings controlled by tuned were changed by something else. It also says to look at the log if it failed.

2025-08-29 00:41 UTC, getchoo commented
Yeah in my case it's failing for pretty benign reasons: the `vm.swapiness` value I declared with `boot.kernel.sysctl` can't be overridden