circt: 1.87.0 -> 1.93.1
NixOS/nixpkgs pull request #357594
Opened 2024-11-20 16:40 UTC by unlsycn

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-20 17:36 UTC, xokdvium requested changes
Aren't you missing a hash bump?

```nix
hash = "sha256-UzSWw28y9l7N9wGDxWMk+adFnh5l9XlSTM6ru0oUOQg=";
```

2024-11-20 18:02 UTC, xokdvium commented
I tried to build with the correct hash and got some failing tests:

```
********************
Testing:  0.. 10.. 20.. 30.. 40.. 50.. 60.. 70.. 80.. 90..
********************
Failed Tests (3):
  CIRCT :: Dialect/FIRRTL/SFCTests/ExtractSeqMems/Compose.fir
  CIRCT :: Dialect/FIRRTL/SFCTests/ExtractSeqMems/Simple2.fir
  CIRCT :: Dialect/FIRRTL/extract-instances.mlir


Testing Time: 8.57s

Total Discovered Tests: 869
  Unsupported      :  23 (2.65%)
  Passed           : 837 (96.32%)
  Expectedly Failed:   6 (0.69%)
  Failed           :   3 (0.35%)
```

There are some segfaults:

```
 #9 0x00007ffff5e36859 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, un
#10 0x00007ffff5e37773 mlir::PassManager::run(mlir::Operation*) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-lib/lib/libM
#11 0x000000000041ca1b processBuffer(mlir::MLIRContext&, circt::firtool::FirtoolOptions&, mlir::TimingScope&, llvm::SourceMgr&, std::option
#12 0x000000000041d6fe processInputSplit(mlir::MLIRContext&, circt::firtool::FirtoolOptions&, mlir::TimingScope&, std::unique_ptr<llvm::Mem
#13 0x000000000040f75f main (/build/source/build/bin/firtool+0x40f75f)
#14 0x00007ffff521e27e __libc_start_call_main (/nix/store/pacbfvpzqz2mksby36awvbcn051zcji3-glibc-2.40-36/lib/libc.so.6+0x2a27e)
#15 0x00007ffff521e339 __libc_start_main@GLIBC_2.2.5 (/nix/store/pacbfvpzqz2mksby36awvbcn051zcji3-glibc-2.40-36/lib/libc.so.6+0x2a339)
#16 0x000000000040f935 _start (/build/source/build/bin/firtool+0x40f935)
/build/source/build/test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Output/Simple2.fir.script: line 7: 13325 Segmentation fault      (core dump

--

********************
Testing:  0.. 10.. 20..
FAIL: CIRCT :: Dialect/FIRRTL/SFCTests/ExtractSeqMems/Compose.fir (266 of 869)
******************** TEST 'CIRCT :: Dialect/FIRRTL/SFCTests/ExtractSeqMems/Compose.fir' FAILED ********************
Exit Code: 139

Command Output (stderr):
--
RUN: at line 3: rm -rf /build/source/build/test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Output/Compose.fir.tmp
+ rm -rf /build/source/build/test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Output/Compose.fir.tmp
RUN: at line 4: /build/source/build/bin/firtool --repl-seq-mem --repl-seq-mem-file=mems.conf --split-verilog --emit-omir -o=/build/source/b
+ /build/source/build/bin/firtool --repl-seq-mem --repl-seq-mem-file=mems.conf --split-verilog --emit-omir -o=/build/source/build/test/Dial
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump:
0.      Program arguments: /build/source/build/bin/firtool --repl-seq-mem --repl-seq-mem-file=mems.conf --split-verilog --emit-omir -o=/bui
 #0 0x00007ffff5945ace llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-l
 #1 0x00007ffff5942f0b SignalHandler(int) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-lib/lib/libLLVMSupport.so.20.0git+
 #2 0x00007ffff5234620 __restore_rt (/nix/store/pacbfvpzqz2mksby36awvbcn051zcji3-glibc-2.40-36/lib/libc.so.6+0x40620)
 #3 0x00007ffff7c6b06c (anonymous namespace)::ExtractInstancesPass::createTraceFiles(circt::firrtl::ClassOp&) ExtractInstances.cpp:0:0
 #4 0x00007ffff7c746ed (anonymous namespace)::ExtractInstancesPass::runOnOperation() ExtractInstances.cpp:0:0
 #5 0x00007ffff5e3635e mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/nix
 #6 0x00007ffff5e36859 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, un
 #7 0x00007ffff5e35840 mlir::detail::OpToOpPassAdaptor::runOnOperationAsyncImpl(bool) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-ll
 #8 0x00007ffff5e3607e mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/nix
 #9 0x00007ffff5e36859 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-lib/lib/libMLIRPass.so.20.0git+0x22859)
#10 0x00007ffff5e37773 mlir::PassManager::run(mlir::Operation*) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-lib/lib/libMLIRPass.so.20.0git+0x23773)
#11 0x000000000041ca1b processBuffer(mlir::MLIRContext&, circt::firtool::FirtoolOptions&, mlir::TimingScope&, llvm::SourceMgr&, std::optional<std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>>&) firtool.cpp:0:0
#12 0x000000000041d6fe processInputSplit(mlir::MLIRContext&, circt::firtool::FirtoolOptions&, mlir::TimingScope&, std::unique_ptr<llvm::MemoryBuffer, std::default_delete<llvm::MemoryBuffer>>, std::optional<std::unique_ptr<llvm::ToolOutputFile, std::default_delete<llvm::ToolOutputFile>>>&) firtool.cpp:0:0
#13 0x000000000040f75f main (/build/source/build/bin/firtool+0x40f75f)
#14 0x00007ffff521e27e __libc_start_call_main (/nix/store/pacbfvpzqz2mksby36awvbcn051zcji3-glibc-2.40-36/lib/libc.so.6+0x2a27e)
#15 0x00007ffff521e339 __libc_start_main@GLIBC_2.2.5 (/nix/store/pacbfvpzqz2mksby36awvbcn051zcji3-glibc-2.40-36/lib/libc.so.6+0x2a339)
#16 0x000000000040f935 _start (/build/source/build/bin/firtool+0x40f935)
/build/source/build/test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Output/Compose.fir.script: line 11: 13305 Segmentation fault      (core dumped) /build/source/build/bin/firtool --repl-seq-mem --repl-seq-mem-file=mems.conf --split-verilog --emit-omir -o=/build/source/build/test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Output/Compose.fir.tmp /build/source/test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Compose.fir
```

```
FAIL: CIRCT :: Dialect/FIRRTL/SFCTests/ExtractSeqMems/Simple2.fir (265 of 869)
******************** TEST 'CIRCT :: Dialect/FIRRTL/SFCTests/ExtractSeqMems/Simple2.fir' FAILED ********************
Exit Code: 139

Command Output (stderr):
--
RUN: at line 3: rm -rf /build/source/build/test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Output/Simple2.fir.tmp
+ rm -rf /build/source/build/test/Dialect/FIRRTL/SFCTests/ExtractSeqMems/Output/Simple2.fir.tmp
RUN: at line 4: /build/source/build/bin/firtool --repl-seq-mem --repl-seq-mem-file=mems.conf --split-verilog -o=/build/source/build/test/Di
+ /build/source/build/bin/firtool --repl-seq-mem --repl-seq-mem-file=mems.conf --split-verilog -o=/build/source/build/test/Dialect/FIRRTL/S
PLEASE submit a bug report to https://github.com/llvm/circt and include the crash backtrace.
Stack dump:
0.      Program arguments: /build/source/build/bin/firtool --repl-seq-mem --repl-seq-mem-file=mems.conf --split-verilog -o=/build/source/bu
 #0 0x00007ffff5945ace llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-l
 #1 0x00007ffff5942f0b SignalHandler(int) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-lib/lib/libLLVMSupport.so.20.0git+
 #2 0x00007ffff5234620 __restore_rt (/nix/store/pacbfvpzqz2mksby36awvbcn051zcji3-glibc-2.40-36/lib/libc.so.6+0x40620)
 #3 0x00007ffff7c6b06c (anonymous namespace)::ExtractInstancesPass::createTraceFiles(circt::firrtl::ClassOp&) ExtractInstances.cpp:0:0
 #4 0x00007ffff7c746ed (anonymous namespace)::ExtractInstancesPass::runOnOperation() ExtractInstances.cpp:0:0
 #5 0x00007ffff5e3635e mlir::detail::OpToOpPassAdaptor::run(mlir::Pass*, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-lib/lib/libMLIRPass.so.20.0git+0x2235e)
 #6 0x00007ffff5e36859 mlir::detail::OpToOpPassAdaptor::runPipeline(mlir::OpPassManager&, mlir::Operation*, mlir::AnalysisManager, bool, unsigned int, mlir::PassInstrumentor*, mlir::PassInstrumentation::PipelineParentInfo const*) (/nix/store/khzvb5gx9cksklr76z3swn7j2d51gvqq-circt-llvm-1.93.1-lib/lib/libMLIRPass.so.20.0git+0x22859)
 #7 0x00007ffff5e35840 mlir::d [...]

2024-11-24 02:36 UTC, pineapplehunter commented
I tried building an updated version of circt `1.95.1`, and it seems to have more issues with tests.
We may have to change some build steps to build the newer versions.
I will check on this later when I have some time.

2024-11-24 05:46 UTC, closed without merging

2024-11-24 18:00 UTC, unlsycn commented
> I tried building an updated version of circt `1.95.1`, and it seems to have more issues with tests. We may have to change some build steps to build the newer versions. I will check on this later when I have some time.

The integration test in 1.95.1 is broken by https://github.com/llvm/circt/pull/7884 and https://github.com/llvm/circt/pull/7886. I will bump it once they get merged.

2024-12-16 00:43 UTC, sequencer commented
@unlsycn You can add patches at the nixpkgs side and bump it.