vimPlugins: Remove the nvim-cmp dependency on cmp-sources
NixOS/nixpkgs pull request #358809
Opened 2024-11-24 21:25 UTC by traxys

The `blink.cmp` neovim plugin provides a shim to use sources initially developped for `nvim-cmp` by using the `blink.compat` plugin.

This plugin implements a `cmp` lua module, so that `nvim-cmp` sources register with `blink.cmp` instead of registering with `nvim-cmp`.

If we have a hard dependency on nvim-cmp for cmp sources this means we can't use them with `blink.cmp`

This also means that we can't easily require the plugin in the check phase, as we would need to add nvim-cmp (or blink.compat) to provide the 'cmp' lua module.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-24 21:27 UTC, khaneliman approved these changes

2024-11-24 21:28 UTC, khaneliman commented
Looks like it just needs formatting @traxys

2024-11-24 21:34 UTC, traxys commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358809`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 39 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-ai</li>
    <li>vimPlugins.cmp-async-path</li>
    <li>vimPlugins.cmp-beancount</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-conjure</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-ctags</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-nixpkgs-maintainers</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-lua</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-nvim-ultisnips</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-pandoc-references</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tabby</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-vsnip</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.codeium-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

2024-11-24 21:42 UTC, PerchunPak requested changes
If someone uses cmp plugin, I would assume they have already installed and configured cmp itself. Though, we should prevent adding `nvim-cmp` to dependencies somehow for the future.

2024-11-24 21:47 UTC, traxys commented
> Though, we should prevent adding `nvim-cmp` to dependencies somehow for the future.

Not sure how to do that :/

2024-11-24 21:47 UTC, khaneliman commented
> If someone uses cmp plugin, I would assume they have already installed and configured cmp itself. Though, we should prevent adding `nvim-cmp` to dependencies somehow for the future.

I wouldn't worry about it here. I can add them as notes in https://github.com/NixOS/nixpkgs/pull/352277 when I flag them to not be checked because it will fail the automatic check.

2024-11-24 21:48 UTC, PerchunPak commented
Also, it would create problems for #352277. Maybe count this as edge-case, for which you have to use an overlay? It feels counter-intuitive to remove cmp from dependencies for plugins that were initially created for cmp, because of some another plugin that also implements cmp module.

The overlay would be something like this:

```nix
final: prev:
{
  vimPlugins = prev.vimPlugins // {
    nvim-cmp = final.vimPlugins.blink-cmp;
  };
}

2024-11-24 21:49 UTC, khaneliman commented
> Also, it would create problems for #352277. Maybe count this as edge-case, for which you have to use an overlay? It feels counter-intuitive to remove cmp from dependencies for plugins that were initially created for cmp, because of some another plugin that also implements cmp module.
> 
> The overlay would be something like this:
> 
> ```nix
> final: prev:
> {
>   vimPlugins = prev.vimPlugins // {
>     nvim-cmp = final.vimPlugins.blink-cmp;
>   };
> }
> ```

It would just be a note about why we have to ignore it, I already thought about it for another plugin that has a requirement for `nvim-web-devicons` but `mini.icons` can be used instead.

2024-11-24 21:55 UTC, traxys commented
> Also, it would create problems for #352277. Maybe count this as edge-case, for which you have to use an overlay? It feels counter-intuitive to remove cmp from dependencies for plugins that were initially created for cmp, because of some another plugin that also implements cmp module.
> 
> The overlay would be something like this:
> 
> ```nix
> final: prev:
> {
>   vimPlugins = prev.vimPlugins // {
>     nvim-cmp = final.vimPlugins.blink-compat;
>   };
> }
> ```

That could be an OK workaround

2024-11-26 15:11 UTC, khaneliman commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 358809`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 39 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-ai</li>
    <li>vimPlugins.cmp-async-path</li>
    <li>vimPlugins.cmp-beancount</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-conjure</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-ctags</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-nixpkgs-maintainers</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-lua</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-nvim-ultisnips</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-pandoc-references</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tabby</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-vsnip</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.codeium-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 38 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-ai</li>
    <li>vimPlugins.cmp-async-path</li>
    <li>vimPlugins.cmp-beancount</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-conjure</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-ctags</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-nixpkgs-maintainers</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-lua</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-nvim-ultisnips</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-pandoc-references</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tabby</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-vsnip</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.codeium-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 39 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-ai</li>
    <li>vimPlugins.cmp-async-path</li>
    <li>vimPlugins.cmp-beancount</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-conjure</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-ctags</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-nixpkgs-maintainers</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-lua</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-nvim-ultisnips</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-pandoc-references</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tabby</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-vsnip</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.codeium-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 39 packages built:</summary>
  <ul>
    <li>vimPlugins.cmp-ai</li>
    <li>vimPlugins.cmp-async-path</li>
    <li>vimPlugins.cmp-beancount</li>
    <li>vimPlugins.cmp-clippy</li>
    <li>vimPlugins.cmp-cmdline</li>
    <li>vimPlugins.cmp-conjure</li>
    <li>vimPlugins.cmp-copilot</li>
    <li>vimPlugins.cmp-ctags</li>
    <li>vimPlugins.cmp-dap</li>
    <li>vimPlugins.cmp-dictionary</li>
    <li>vimPlugins.cmp-digraphs</li>
    <li>vimPlugins.cmp-fish</li>
    <li>vimPlugins.cmp-fuzzy-buffer</li>
    <li>vimPlugins.cmp-fuzzy-path</li>
    <li>vimPlugins.cmp-git</li>
    <li>vimPlugins.cmp-greek</li>
    <li>vimPlugins.cmp-look</li>
    <li>vimPlugins.cmp-neosnippet</li>
    <li>vimPlugins.cmp-nixpkgs-maintainers</li>
    <li>vimPlugins.cmp-npm</li>
    <li>vimPlugins.cmp-nvim-lsp-signature-help</li>
    <li>vimPlugins.cmp-nvim-lua</li>
    <li>vimPlugins.cmp-nvim-tags</li>
    <li>vimPlugins.cmp-nvim-ultisnips</li>
    <li>vimPlugins.cmp-pandoc-nvim</li>
    <li>vimPlugins.cmp-pandoc-references</li>
    <li>vimPlugins.cmp-path</li>
    <li>vimPlugins.cmp-rg</li>
    <li>vimPlugins.cmp-snippy</li>
    <li>vimPlugins.cmp-tabby</li>
    <li>vimPlugins.cmp-tabnine</li>
    <li>vimPlugins.cmp-tmux</li>
    <li>vimPlugins.cmp-vim-lsp</li>
    <li>vimPlugins.cmp-vimwiki-tags</li>
    <li>vimPlugins.cmp-vsnip</li>
    <li>vimPlugins.cmp-zsh</li>
    <li>vimPlugins.cmp_luasnip</li>
    <li>vimPlugins.codeium-nvim</li>
    <li>vimPluginsUpdater</li>
  </ul>
</details>

2024-11-26 15:12 UTC, merged