handheld-daemon: 3.4.1 -> 3.5.7
NixOS/nixpkgs pull request #359282
Opened 2024-11-26 13:10 UTC by toast003

Also install hhd's hwdb file, since it is needed for buttons to work properly on the MSI Claw, among other things

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-28 21:07 UTC, getchoo approved these changes
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359282`

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>handheld-daemon</li>
    <li>handheld-daemon.dist</li>
  </ul>
</details>

2024-12-01 15:02 UTC, GaetanLepage requested changes

2024-12-01 15:02 UTC, GaetanLepage commented on pkgs/by-name/ha/handheld-daemon/package.nix
>    python3,
```suggestion
  python3Packages,
```

2024-12-01 15:02 UTC, GaetanLepage commented on pkgs/by-name/ha/handheld-daemon/package.nix
>  python3.pkgs.buildPythonApplication rec {
```suggestion
python3Packages.buildPythonApplication rec {
```

2024-12-01 15:02 UTC, GaetanLepage commented on pkgs/by-name/ha/handheld-daemon/package.nix
>    propagatedBuildInputs = with python3.pkgs; [
```suggestion
  dependencies = with python3Packages; [
```

2024-12-01 15:02 UTC, GaetanLepage commented on pkgs/by-name/ha/handheld-daemon/package.nix
>    meta = with lib; {
```suggestion
  meta = {
```

2024-12-02 19:52 UTC, getchoo commented
@GaetanLepage: None of these suggestions are for changes introduced by this PR. They would be nice to have definitely, but we shouldn't be blocking on this

2024-12-03 07:44 UTC, GaetanLepage commented
> @GaetanLepage: None of these suggestions are for changes introduced by this PR. They would be nice to have definitely, but we shouldn't be blocking on this

No definitely. Usually, I think that it is good to "clean" stuff when updating packages. I won't block your PR for this though.

2024-12-03 07:44 UTC, GaetanLepage approved these changes

2024-12-03 07:45 UTC, GaetanLepage commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 359282`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>handheld-daemon</li>
    <li>handheld-daemon.dist</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>handheld-daemon</li>
    <li>handheld-daemon.dist</li>
  </ul>
</details>

2024-12-03 07:45 UTC, merged