pythonPackages.pygerber: init at 2.4.2
NixOS/nixpkgs pull request #359437
Opened 2024-11-26 22:24 UTC by clemjvdm

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-26 22:47 UTC, steeleduncan requested changes

2024-11-26 22:47 UTC, steeleduncan commented on pkgs/development/python-modules/pygerber/default.nix
> +  meta = with lib; {
`with lib` is deprecated #208242

2024-11-26 22:47 UTC, steeleduncan commented on pkgs/development/python-modules/pygerber/default.nix
> +  pillow_10_4 = pillow.overrideAttrs (prev: {
does it make sense to supply some variables for the `pillow` dependency as well, or is it likely to be at 10.4 forever?

Its personal of course, but I'd suggest not having the version in the variable name

2024-11-26 22:48 UTC, steeleduncan requested changes

2024-11-26 22:48 UTC, steeleduncan commented on maintainers/maintainer-list.nix
> +  clemjvdm = {
please split the maintainer list change into a separate commit, preceeding the commit that introduces the package

2024-12-15 15:26 UTC, clemjvdm commented
do I need to do anything else? Sorry it's my first PR so I'm not sure. @steeleduncan

2024-12-15 18:30 UTC, steeleduncan reviewed
I am not familiar enough with python derivations to leave an approving review, but I certainly wouldn't want to block it

If you can find someone who has merged some python commits recently and ping them for a review that is probably the best approach to get it merged

2024-12-17 17:14 UTC, clemjvdm commented
> I am not familiar enough with python derivations to leave an approving review, but I certainly wouldn't want to block it
> 
> If you can find someone who has merged some python commits recently and ping them for a review that is probably the best approach to get it merged

@natsukium Hello, hope it's ok for me to ping you here. I opened this PR about 3 weeks ago and I wasn't sure if I had to do anything else to get it merged.

2025-01-01 11:55 UTC, FliegendeWurst commented on pkgs/development/python-modules/pygerber/default.nix
> +    hash = "sha256-+s89tHNTNP+0VMilfDczbOBG/e3DuUBu0113US69KKM=";
```suggestion
    hash = "sha256-N+9I59WiWXSXr7RrPzb7GFSqfjrd0q51AzalNFV4xEQ=";
```

2025-01-01 11:55 UTC, FliegendeWurst commented on pkgs/development/python-modules/pygerber/default.nix
> +  format = "pyproject";
```suggestion
  pyproject = true;
```

2025-01-01 11:55 UTC, FliegendeWurst commented on pkgs/development/python-modules/pygerber/default.nix
> +in
```suggestion
```
Upstream supports newer Pillow versions https://github.com/Argmaster/pygerber/blob/9c2eeb4099822a9ef9a00938e43fef9d65dc638b/pyproject.toml#L58-L61

2025-01-01 11:55 UTC, FliegendeWurst commented on pkgs/development/python-modules/pygerber/default.nix
> +  nativeBuildInputs = [ poetry-core ];
```suggestion
  build-system = [ poetry-core ];
```

2025-01-01 11:55 UTC, FliegendeWurst commented on pkgs/development/python-modules/pygerber/default.nix
> +  propagatedBuildInputs = [
```suggestion
  dependencies = [
```

2025-01-01 11:55 UTC, FliegendeWurst commented on pkgs/development/python-modules/pygerber/default.nix
> +    description = "PyGerber is a Python implementation of Gerber X3/X2 format. It is based on Ucamco's The Gerber Layer Format Specification.";
```suggestion
    description = "Implementation of the Gerber X3/X2 format, based on Ucamco's The Gerber Layer Format Specification";
```

2025-01-04 03:19 UTC, clemjvdm commented
@FliegendeWurst Just committed your suggestions, fixed a little error and squashed them, hopefully this is how I was supposed to do this. Anything else I should do?

2025-01-04 08:28 UTC, FliegendeWurst commented
Yes. So far you only activated the import check. It would be good to run the real test suite, if the project has one. Add pytestCheckHook (or another hook, depending on the framework) to nativeCheckInputs for that.

2025-01-04 14:08 UTC, clemjvdm commented
@FliegendeWurst I looked into it, but I can't test because `pytest-lsp` doesn't yet exist on nixpkgs :(

2025-01-04 14:16 UTC, FliegendeWurst commented
Here you go. Untested.

```
{
  lib,
  fetchPypi,
  buildPythonPackage,
  hatchling,
  pygls,
  pytestCheckHook,
  pytest-asyncio,
}:

buildPythonPackage rec {
  pname = "pytest-lsp";
  version = "0.4.3";
  pyproject = true;

  src = fetchPypi {
    inherit version;
    pname = "pytest_lsp";
    hash = "sha256-ND9r2i+qMg7V/Ld8lCDScDzlZdHRRP6CfjGYp9wpkRw=";
  };

  build-system = [
    hatchling
  ];

  dependencies = [
    pygls
    pytest-asyncio
  ];

  nativeCheckInputs = [
    pytestCheckHook
  ];

  pythonImportsCheck = [ "pytest_lsp" ];

  meta = {
    homepage = "https://github.com/swyddfa/lsp-devtools";
    changelog = "https://github.com/swyddfa/lsp-devtools/blob/develop/lib/pytest-lsp/CHANGES.md";
    description = "Pytest plugin for writing end-to-end tests for language servers";
    license = lib.licenses.mit;
    maintainers = with lib.maintainers; [ clemjvdm ];
  };
}
```

2025-01-04 17:11 UTC, clemjvdm commented
@FliegendeWurst Uhh sorry, I'm not sure how I should go about this?. Open a new PR with pytest_lsp, or just write this somewhere in this PR?

2025-01-04 17:15 UTC, FliegendeWurst commented
You can put it in this PR. Ideally it would be done in a commit before the pygerber package is added.

2025-01-04 17:21 UTC, clemjvdm commented
@FliegendeWurst Just to be sure before I do this, pygerber documentation states that to run tests one should do:
```
poetry shell
poe run-unit-tests
```
I assumed this wasn't the right way to do this here since this would imply letting poetry manage dependencies. I also tried just installing the required dependencies and doing `poe run-unit-tests` but this requires poetry and nix will only let me use `poetry-core`:
```
error: poetry was promoted to a top-level attribute, use poetry-core to build Python packages
```

Which is why I figured maybe using pytests (which poepoet refers to) directly was the right approach. But in hindsight I'm not sure.

2025-01-04 17:22 UTC, clemjvdm commented
I think either way we'll need `pytest-lsp`.

2025-01-04 17:23 UTC, FliegendeWurst commented
I think pytestCheckHook will work. You may need to add some more plugins though:

https://github.com/Argmaster/pygerber/blob/main/pyproject.toml#L84-L89

2025-01-04 17:24 UTC, clemjvdm commented
@FliegendeWurst Yeah I figured, I'll try that then. Thanks :)

2025-01-04 19:23 UTC, clemjvdm commented
@FliegendeWurst New issue! Yay! I was able to get everything working with `pytest-lsp` (thanks again). But it seems pygerber's tests pull assets from github (which isn't allowed by the nix build phase).

Is there a good way of solving this? I presume maybe we can fetch them in nix and then patch the tests but I don't have time nor am I qualified to do that I think.

2025-01-04 19:24 UTC, FliegendeWurst commented
If it's only some tests you can disable them using disabledTests = [ .... ].

2025-01-04 19:40 UTC, clemjvdm commented
@FliegendeWurst Ok that worked! Do we care about skipped, xfailed and xpassed tests?
```
============= 427 passed, 2 skipped, 8 xfailed, 1 xpassed in 7.08s =============
```

Otherwise I'll commit.

2025-01-04 19:41 UTC, FliegendeWurst commented
That looks good to me :+1:

2025-01-04 19:59 UTC, clemjvdm commented
@FliegendeWurst All done. Thanks you sm for the help :)

2025-01-06 17:52 UTC, FliegendeWurst commented on pkgs/development/python-modules/pygerber/default.nix
> +    rev = "refs/tags/v${version}";
```suggestion
    repo = "pygerber;
    tag = "v${version}";
```
Avoid using pname #277994.
The tag parameter saves some boilerplate. (you may need to rebase if your branch does not support it)

2025-01-06 17:52 UTC, FliegendeWurst commented on pkgs/development/python-modules/pygerber/default.nix
> +  ];
```suggestion
  disabledTestPaths = [
    # require network access
    "test/gerberx3/test_assets.py"
    "test/gerberx3/test_language_server/tests.py"
  ];
```
Always good to explain why certain tests are disabled.

2025-01-09 08:51 UTC, FliegendeWurst approved these changes

2025-01-09 08:55 UTC, merged