openbsd.{pathDefinesHook,init,mount}: init
NixOS/nixpkgs pull request #359419
Opened 2024-11-26 21:15 UTC by artemist

Add some basic OpenBSD tools along with `pathDefinesHook`, which makes it easy to override the contents of `paths.h`

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
  - [x] x86_64-openbsd
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2025-02-22 16:19 UTC, Ericson2314 commented
Can you prepend some "commit messages" to the patches? @rhelmot figured out that the full email-like format isn't even necessary, mostly freeform text above the `---\n+++` is allowed.

2025-12-28 00:55 UTC, shelvacu requested changes

2025-12-28 00:55 UTC, shelvacu commented on pkgs/os-specific/bsd/openbsd/pkgs/pathDefinesHook/setup-hook.sh
> +        while IFS='=' read -r -d '' envName envValue; do
I don't think iterating through every environment variable is a good idea. Instead you should copy what most of the `*Flags` attrs do; have `pathDefines` as a list of `name=value` you can pass to `mkDerivation`, and then in your hook:

```bash
local allPathDefines=()

concatTo allPathDefines pathDefines pathDefinesArray

shopt -s extglob
local define
for define in "${allPathDefines[@]}"; do
  if [[ $define != *=* ]]; then
    printf 'Error: every pathDefine must be of the form name=value; got %s\n' "$define" >&2
    exit 1
  fi
  local defineName="${define%%=*}"
  local defineValue="${define#*=}"

  if [[ $defineName != [[:alpha:]_]*([[:word]]) ]]; then
    printf 'Error: in pathDefines, %s is not a valid identifier\n' "$defineName" >&2
    exit 1
  fi
  # and don't forget to escape any special chars in defineValue:
  defineValue="${defineValue//'\'/'\\'}"
  defineValue="${defineValue//'"'/'\"'}"
  defineValue="${defineValue//$'\n'/'\n'}"
  defineValue="${defineValue//$'\r'/'\r'}"
  defineValue="${defineValue//$'\t'/'\t'}"
  # ....
  printf '#define %s "%s"\n' "$defineName" "$defineValue"
done
```

This allows space-separated defines to be provided thru an attr you can pass to `mkDerivation`, and defines with spaces can be passed with a hook that runs:

```bash
pathDefinesArray+=("SOME_DEFINE=value with spaces")
```

2026-06-25 15:35 UTC, artemist commented
I think this might be bitrotted, I'm going to close this and someone (possibly even me in the future) can pick this up in the future.

2026-06-25 15:35 UTC, closed without merging