(rio): 0.1.17 -> 0.2.2
NixOS/nixpkgs pull request #359621
Opened 2024-11-27 16:55 UTC by soanvig

https://github.com/raphamorim/rio/releases/tag/v0.2.0
https://github.com/raphamorim/rio/releases/tag/v0.2.1
https://github.com/raphamorim/rio/releases/tag/v0.2.2

Extracted note from 0.2.0:
> Breaking: Minimum MacOS version went from El Captain to Big Sur on ARM64 and Catalina on Intel x86.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-28 11:03 UTC, TornaxO7 commented
> On linux my system it builds, and tests pass, however for whatever reason the builder exists with 129 status code, and there is no other error in the logs...
> 
> This was already raised: https://discourse.nixos.org/t/getting-build-error-from-nix-build-although-theres-no-error/54561/2 by @TornaxO7

![peepoYes](https://github.com/user-attachments/assets/91196d7f-630c-4254-ae60-7c1dcc561c18)

Here's what I've found (yet):
1. It starts to fail when it reached this test:
```
rio> test sugarloaf/src/font/loader/mod.rs - font::loader::Database::with_face_data (line 397) ... ignored
```
2. During the execution of this test, my memory consumption increased non-stop. I assume that the process got killed then afterwards which returned to the exit code 129.

Would be awesome if anyone else has got an idea how to fix that.

2024-11-28 11:23 UTC, soanvig commented
Regarding comment on the forums, I noticed that indeed their nix build failed with this error, but on master new "Nix build" CI work properly. I tried using that commit with no success

2024-11-28 14:10 UTC, TornaxO7 commented
> Note, that CI in this PR succeeded - false positive or something is wrong with our machines?

Wait, you're right.

![monkaW](https://github.com/user-attachments/assets/e9f4d407-2f05-4170-bfe5-ffbbe3e071cb)

Huh? How?

2024-12-02 09:51 UTC, soanvig commented
Latest nixos packages, using unstable, still failing on `nix-build -k -A rio`

2024-12-08 06:12 UTC, NovaViper commented
Just tried it with my flake and also experienced the same error 129 failure.
```
rio> test context::grid::test::test_single_context_respecting_margin_and_no_quad_creation ... ok
error: builder for '/nix/store/rgj7x2d45zy5hf44nm3rkga1byhrri15-rio-0.2.2.drv' failed with exit code 129;
       last 25 log lines:
       > test event_loop_proxy_send ... ok
       > test window_builder_sync ... ok
       > test window_sync ... ok
       >
       > test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s
       >
       >      Running unittests src/main.rs (target/x86_64-unknown-linux-gnu/release/deps/rio-a84fdce5a2408e08)
       >
       > running 47 tests
       > test bindings::tests::binding_matches_different_action ... ok
       > test bindings::tests::binding_matches_identical_mode ... ok
       > test bindings::tests::binding_matches_mode_notmode ... ok
       > test bindings::tests::binding_matches_itself ... ok
       > test bindings::tests::binding_matches_modes ... ok
       > test bindings::tests::binding_matches_notmodes ... ok
       > test bindings::tests::binding_matches_partial_intersection ... ok
       > test bindings::tests::binding_mismatches_notmode ... ok
       > test bindings::tests::binding_mismatches_unrelated ... ok
       > test bindings::tests::binding_trigger_modes ... ok
       > test bindings::tests::binding_trigger_notmodes ... ok
       > test bindings::tests::binding_with_mode_matches_empty_mode ... ok
       > test bindings::tests::binding_without_mode_matches_any_mode ... ok
       > test bindings::tests::bindings_overwrite ... ok
       > test bindings::tests::mods_binding_requires_strict_match ... ok
       > test context::grid::test::test_single_context_respecting_margin_and_no_quad_creation ... ok
       For full logs, run 'nix log /nix/store/rgj7x2d45zy5hf44nm3rkga1byhrri15-rio-0.2.2.drv'.
error: 1 dependencies of derivation '/nix/store/3qbkhb7xpl9b8rjszlrjc4v24v4qhbi2-home-manager-path.drv' failed to build
error: 1 dependencies of derivation '/nix/store/q5lpfpr8snml2jlq8dfbx1d9hvqi775f-home-manager-generation.drv' failed to build
error: 1 dependencies of derivation '/nix/store/a4vb54ydh5ghb6ph03qrjmlfh35hfh26-user-environment.drv' failed to build
error: 1 dependencies of derivation '/nix/store/rz6yfmz1dp9977f5sk56l78mpfkdh6fq-etc.drv' failed to build
error: 1 dependencies of derivation '/nix/store/fddagg7jp7r4601h0si4mpkvq49ws6rm-nixos-system-yoganova-25.05.20241205.d0797a0.drv' failed to build
┏━ 1 Errors:
┃ error: builder for '/nix/store/rgj7x2d45zy5hf44nm3rkga1byhrri15-rio-0.2.2.drv' failed with exit code…
┃        last 25 log lines:
┃        > test event_loop_proxy_send ... ok
┃        > test window_builder_sync ... ok
┃        > test window_sync ... ok
┃        >
┃        > test result: ok. 4 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.0…
┃        >
┃        >      Running unittests src/main.rs (target/x86_64-unknown-linux-gnu/release/deps/rio-a84fdc…
┃        >
┃        > running 47 tests
┃        > test bindings::tests::binding_matches_different_action ... ok
┃        > test bindings::tests::binding_matches_identical_mode ... ok
┃        > test bindings::tests::binding_matches_mode_notmode ... ok
┃        > test bindings::tests::binding_matches_itself ... ok
┃        > test bindings::tests::binding_matches_modes ... ok
┃        > test bindings::tests::binding_matches_notmodes ... ok
┃        > test bindings::tests::binding_matches_partial_intersection ... ok
┃        > test bindings::tests::binding_mismatches_notmode ... ok
┃        > test bindings::tests::binding_mismatches_unrelated ... ok
┃        > test bindings::tests::binding_trigger_modes ... ok
┃        > test bindings::tests::binding_trigger_notmodes ... ok
┃        > test bindings::tests::binding_with_mode_matches_empty_mode ... ok
┃        > test bindings::tests::binding_without_mode_matches_any_mode ... ok
┃        > test bindings::tests::bindings_overwrite ... ok
┃        > test bindings::tests::mods_binding_requires_strict_match ... ok
┃        > test context::grid::test::test_single_context_respecting_margin_and_no_quad_creation ... ok
┃        For full logs, run 'nix log /nix/store/rgj7x2d45zy5hf44nm3rkga1byhrri15-rio-0.2.2.drv'.
┣━ Dependency Graph:
┃                ┌─ ⏸ hm_fontconfigconf.d10hmfonts.conf waiting for 1 ⚠
┃             ┌─ ⏸ home-manager-files
┃          ┌─ ⏸ home-manager-generation
┃       ┌─ ⏸ unit-home-manager-novaviper.service
┃    ┌─ ⏸ system-units
┃    │     ┌─ ⚠ rio-0.2.2 failed with exit code 129 after ⏱ 12m14s in checkPhase
┃    │  ┌─ ⏸ home-manager-path
┃    ├─ ⏸ user-environment
┃ ┌─ ⏸ etc
┃ ⏸ nixos-system-yoganova-25.05.20241205.d0797a0
┣━━━ Builds
┗━ ∑ ⏵ 0 │ ✔ 0 │ ⏸ 9 │ ⚠ Exited after 1 build failures at 00:08:03 after 13m18s
Error:
   0: Command exited with status Exited(1)

Location:
   src/commands.rs:151
```

Build log
[build-fail.txt](https://github.com/user-attachments/files/18050938/build-fail.txt)

Nix info:
```
❯ nix-info -m
 - system: `"x86_64-linux"`
 - host os: `Linux 6.12.1, NixOS, 25.05 (Warbler), 25.05.20241205.d0797a0`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.25.2`
 - nixpkgs: `/nix/store/nr5nl3zwzl02x3rnikjbry3s5xy7bm1d-source`
```

2024-12-18 00:49 UTC, raphamorim commented
I re-enabled the checks on Rio term, I will try to do a bisect of split PR that broke this pipeline.

2024-12-19 12:13 UTC, raphamorim commented
Ok, my guess is that after the split PR got merged, I introduced a test that's flaky.

The grid tests have a lot of unsafe calls of libc and if it breaks will not be logged properly because it's ub, and the test will just close.

My guess is that ci have a pointer alignment different than our machines, I will try to figure this out.

2024-12-19 18:39 UTC, jcdickinson commented
I got it building on my machine/PR by disabling a subset of the tests, it seems the `context::grid` tests are somehow to blame.  It's the one linked above.

2024-12-19 19:20 UTC, raphamorim commented
@jcdickinson disable the grid tests fixed for you? Will give a try but looks everything is connected to the resize fn not working properly in the sandbox

2024-12-19 22:05 UTC, jcdickinson commented
> @jcdickinson disable the grid tests fixed for you? Will give a try but looks everything is connected to the resize fn not working properly in the sandbox 

Yeah, I ran the tests without parallelism plus --nocapture and it consistently crashed on those. Disabling them resulted in a complete build.

2024-12-20 02:07 UTC, raphamorim commented
aha, ok. yea i imagine there's something off in the created context on nix "sandbox" i need to investigate how to normalize it

2024-12-22 01:44 UTC, raphamorim commented
Ok, took a while sorry about that. Fixed this issue here -> https://github.com/raphamorim/rio/pull/853

2024-12-22 11:49 UTC, soanvig commented
Tested with `67e64aeb4216eb4656386ef7cedef5456f0d42ff` commit. Now there is no error.

That being said, let's wait for rio 0.2.3 to include that change, and it will be done

2025-01-14 15:13 UTC, soanvig commented
@TornaxO7 @oluceps @otavio 
Build works locally with 0.2.3.  Please test it by yourself. PR is updated to 0.2.3

2025-01-14 15:22 UTC, SuperSandro2000 requested changes
Why are there () around the package name?

2025-01-14 15:31 UTC, soanvig commented on pkgs/by-name/ri/rio/package.nix
> +    rev = "v0.2.3";
@SuperSandro2000 ah, good spot. I also merged all commits into one without parens around name

2025-01-14 15:35 UTC, TornaxO7 approved these changes

2025-01-14 16:34 UTC, otavio approved these changes

2025-01-15 09:10 UTC, soanvig commented
Rio 0.2.3 requires Rust 1.84 and that's why the build fails: https://logs.ofborg.org/?key=nixos/nixpkgs.359621&attempt_id=5b3f6784-0ab6-4564-87e2-1c459244839f

2025-01-17 21:20 UTC, SuperSandro2000 commented
How about you downgrade to the latest version that works with our rust version? Otherwise we need to wait a bit for 1.84 to be available.

2025-01-17 22:34 UTC, raphamorim commented
v0.2.4 released with MSRV back to 1.80.1 https://github.com/raphamorim/rio/releases/tag/v0.2.4

2025-01-18 00:31 UTC, soanvig commented
> How about you downgrade to the latest version that works with our rust version? Otherwise we need to wait a bit for 1.84 to be available.

@SuperSandro2000 I cannot. Older versions of Rio 2.x had a bug leading to builds not passing.

@raphamorim splendid. Testing right now

2025-01-18 00:42 UTC, soanvig commented
@raphamorim works locally, now let's see how nixpks pipelines feel

2025-01-18 01:43 UTC, TornaxO7 approved these changes

2025-01-18 02:56 UTC, SuperSandro2000 approved these changes

2025-01-18 02:56 UTC, merged