switch-to-configuration-ng: Better handling of socket-activated units
NixOS/nixpkgs pull request #359724
Opened 2024-11-28 02:46 UTC by antifuchs

Previously, if any unit had a socket associated with it, stc-ng counted it as "socket-activated", meaning that the unit would get stopped and the socket get restarted. That can wreak havoc on units like systemd-udevd and systemd-networkd.

Instead, let units set the new flag notSocketActivated, which sets a boolean on the unit indicating to stc-ng that the unit wants to be treated like any other non-socket-activated unit instead. That will stop/start or restart these units on upgrades, without unnecessarily tearing down any machinery that the system needs to run.

This addresses what @ElvishJerricco and I thought was a systemd bug (https://github.com/systemd/systemd/issues/35371) but is really a bug in how socket-activated services are handled in stc (and -ng).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-11-28 13:51 UTC, antifuchs commented
I believe this doesn't 100% entirely resolve the issue: While on one machine, explicitly starting udevd & networkd again did allow the switch to go through without issue, on another, the original problem occurred: tailscale0 turned pending (from unmanaged).

Maybe the logic around stopping/starting these critical services is wrong entirely?

2024-11-29 13:53 UTC, jmbaur commented
Can you please implement the perl side of this as well? We will need to have both prior to merge.

2024-11-30 05:40 UTC, fpletz approved these changes

2024-12-08 22:42 UTC, ElvishJerricco requested changes
Looks good, but probably needs to update `nixos/doc/manual/development/unit-handling.section.md`.

2024-12-09 13:58 UTC, antifuchs commented
> Looks good, but probably needs to update nixos/doc/manual/development/unit-handling.section.md.
Updated, thanks for the pointer!

2024-12-17 16:12 UTC, ElvishJerricco reviewed
Just a few little nitpicks but otherwise seems fine to me.

2025-01-04 15:48 UTC, phaer approved these changes

2025-01-04 16:51 UTC, ElvishJerricco approved these changes

2025-01-04 16:51 UTC, merged