obs-studio-plugins.obs-color-monitor: init 0.8.2
NixOS/nixpkgs pull request #361501
Opened 2024-12-03 18:06 UTC by hlad

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin

2024-12-03 18:13 UTC, hlad commented
closes #360113

2024-12-12 17:30 UTC, pluiedev requested changes

2024-12-12 17:30 UTC, pluiedev commented on pkgs/applications/video/obs-studio/plugins/obs-color-monitor.nix
> +{ stdenv, lib, fetchFromGitHub, cmake, obs-studio, qtbase }:
Please reformat with `nixfmt-rfc-style`

2024-12-12 17:30 UTC, pluiedev commented on pkgs/applications/video/obs-studio/plugins/obs-color-monitor.nix
> +    rev = finalAttrs.version;
```suggestion
    tag = finalAttrs.version;
```

2024-12-12 17:30 UTC, pluiedev commented on pkgs/applications/video/obs-studio/plugins/obs-color-monitor.nix
> +  meta = with lib; {
Avoid `with lib;`

2024-12-12 17:30 UTC, pluiedev commented on pkgs/applications/video/obs-studio/plugins/obs-color-monitor.nix
> +    maintainers = with maintainers; [ ];
We don't allow new orphaned packages in Nixpkgs anymore

2024-12-17 13:18 UTC, pluiedev approved these changes

2025-01-03 15:05 UTC, merged