glpi-agent: init at 1.11
NixOS/nixpkgs pull request #361746
Opened 2024-12-04 12:45 UTC by liberodark

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-04 14:48 UTC, liberodark commented
Also this need a backport to 24.11 if is possible is tested and used on 24.11

2024-12-07 22:29 UTC, GaetanLepage requested changes
Minor comments. I am not too familiar with the perl ecosystem.

2024-12-07 22:29 UTC, GaetanLepage commented on pkgs/by-name/gl/glpi-agent/package.nix
> +    rev = version;
```suggestion
    tag = version;
```

2024-12-07 22:29 UTC, GaetanLepage commented on pkgs/by-name/gl/glpi-agent/package.nix
> +    license = lib.licenses.gpl2Plus;
```suggestion
    description = "GLPI unified Agent for UNIX, Linux, Windows and MacOSX";
    changelog = "https://github.com/glpi-project/glpi-agent/releases/tag/${version}";
    license = lib.licenses.gpl2Plus;
```

2024-12-12 11:03 UTC, SuperSandro2000 commented on pkgs/by-name/gl/glpi-agent/package.nix
> +      --replace /sbin/ip ${iproute2}/sbin/ip
```suggestion
      --replace-fail /sbin/ip ${iproute2}/sbin/ip
```

2024-12-12 11:04 UTC, SuperSandro2000 commented on pkgs/by-name/gl/glpi-agent/package.nix
> +      --replace /sbin/ip ${iproute2}/sbin/ip
```suggestion
      --replace-fail /sbin/ip ${iproute2}/sbin/ip
```

2024-12-12 11:04 UTC, SuperSandro2000 commented on pkgs/by-name/gl/glpi-agent/package.nix
> +  buildTools = [ ];
```suggestion
```

2024-12-20 08:33 UTC, GaetanLepage requested changes

2024-12-20 09:01 UTC, GaetanLepage requested changes

2024-12-20 09:06 UTC, liberodark commented on pkgs/by-name/gl/glpi-agent/package.nix
> +
Yes

2024-12-20 09:07 UTC, liberodark commented on pkgs/by-name/gl/glpi-agent/package.nix
> +  doInstallCheck = true;
I think is not necessary.

2024-12-20 09:11 UTC, liberodark commented on pkgs/by-name/gl/glpi-agent/package.nix
> +    mainProgram = "glpi-agent";
Why ?

2024-12-20 09:15 UTC, liberodark commented on pkgs/by-name/gl/glpi-agent/package.nix
> +  doInstallCheck = true;
Have fix issue on your can build on your side.

2024-12-20 10:41 UTC, GaetanLepage approved these changes

2024-12-20 10:42 UTC, merged