tdf: unstable-2024-10-09 -> 0.2.0
NixOS/nixpkgs pull request #361832
Opened 2024-12-04 18:21 UTC by DieracDelta

This PR:

- Adds me as a maintainer for tdf
- Adds MacOS to tdf's platform list
- Bumps tdf to the [newly released 0.2.0 version](https://github.com/itsjunetime/tdf/commit/a2b728fae3c5b0addfa64e8d3e44eac6fd50f1d9) of tdf

I tested with ghostty on aarch64-darwin and x86_64-linux. Seems to work.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-05 13:28 UTC, luftmensch-luftmensch approved these changes

2024-12-05 13:36 UTC, luftmensch-luftmensch approved these changes

2024-12-10 04:53 UTC, getchoo requested changes, later dismissed

2024-12-10 04:53 UTC, getchoo commented on pkgs/by-name/td/tdf/Cargo.lock
We should be using [fetchCargoVendor](https://nixos.org/manual/nixpkgs/unstable/#importing-a-cargo.lock-file) now instead of having the entire Cargo.lock in-tree

2024-12-10 12:41 UTC, Aleksanaa approved these changes

2024-12-10 12:41 UTC, Aleksanaa commented on pkgs/by-name/td/tdf/package.nix
> +  version = "0.2.0";
(note: 0.2.0 has no tag as of now)

2024-12-11 00:27 UTC, getchoo commented on pkgs/by-name/td/tdf/package.nix
>    };
```suggestion
  useFetchCargoVendor = true;
  cargoHash = "sha256-krIPfi4SM4uCw7NLauudwh1tgAaB8enDWnMC5X16n48=";
```

2024-12-11 00:56 UTC, getchoo approved these changes
Diff LGTM

2024-12-11 00:57 UTC, getchoo commented
@ofborg build tdf tdf.passthru.tests

2024-12-11 18:20 UTC, merged