rstudio: build the electron app instead of the qt app
NixOS/nixpkgs pull request #362637
Opened 2024-12-07 00:46 UTC by TomaSajt

Depends on https://github.com/NixOS/nixpkgs/pull/357034

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-08 01:22 UTC, TomaSajt commented
@ofborg build rstudio

2025-01-03 23:25 UTC, TomaSajt commented
Electron is not cached ATM, so we need to wait for a bit to test it.

2025-01-10 20:56 UTC, emilylange commented
> Electron is not cached ATM, so we need to wait for a bit to test it.

Just as a fyi:

You can usually base your PR on `nixos-unstable-small` or even `nixos-unstable`, target `master` and not run into merge-conflicts.

In this case, for electron to be cached, you would use `nixos-unstable`.

You can also rebase onto `nixos-unstable` locally, keep the remote as is, iterate and do your tests or whatever, and then rollback locally to the original base again.

2025-01-26 15:31 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/missing-symbols-when-packaging-electron-based-app-with-native-deps/59402/6

2025-02-02 20:29 UTC, TomaSajt commented
Another boost version (1.87), another breakage:
https://www.boost.io/doc/libs/latest/doc/html/boost_asio/history.html
the `io_service` alias no longer exists, will probably have to subsituted with `io_context`

2025-02-17 20:18 UTC, Kupac approved these changes
RStudio server and desktop build and run well for me on x86_64-linux.

I got a few errors in the terminal for the desktop version, not sure if it's relevant, but I copy it below. As mentioned before, it was working fine, so looks good to me. Great work with the Electron build! \o/

```
[72802:0217/211223.395160:ERROR:gl_factory.cc(113)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default)].
[72802:0217/211223.398717:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
[72849:0217/211224.204516:ERROR:gl_factory.cc(113)] Requested GL implementation (gl=none,angle=none) not found in allowed implementations: [(gl=egl-angle,angle=default)].
[72849:0217/211224.207168:ERROR:viz_main_impl.cc(166)] Exiting GPU process due to errors during initialization
MESA-LOADER: failed to open dri: /run/opengl-driver/lib/gbm/dri_gbm.so: cannot open shared object file: No such file or directory (search paths /run/opengl-driver/lib/gbm, suffix _gbm)
(electron) 'webContents.clearHistory' is deprecated and will be removed. Please use 'webContents.navigationHistory.clear' instead.
```

2025-02-17 20:44 UTC, TomaSajt commented
Btw, master doesn't have `electron_32` cached ATM, so don't try to nixpkgs-review.

Not sure what's up with the darwin ofborg build, though. Is it supposed to try to run the NixOS tests?

2025-02-17 20:47 UTC, TomaSajt commented
Also, the version of electron used, `electron_32`, will be EOL in about 3 weeks, so ideally I should figure out a way to use `electron_33` and above.

Note: upstream still uses `electron_31`

2025-02-17 21:29 UTC, TomaSajt commented
Okay, figured out how to do later electron versions.
I was just encountering a known issue with nan:
https://github.com/nodejs/nan/issues/978

2025-02-17 21:35 UTC, TomaSajt commented
I see upstream itself has also solved this problem: https://github.com/rstudio/rstudio/pull/15471

2025-02-19 15:43 UTC, b-rodrigues commented
Tried to build on `aarch64-darwin` and got the following:

```


BUILD SUCCESSFUL
Total time: 2 minutes 23 seconds
[100%] Built target gwt_build
[100%] Building desktop (Electron arm64)
no such file or directory
make[2]: *** [src/node/desktop/CMakeFiles/electron_build.dir/build.make:150: /tmp/nix-build-RStudio-2024.04.2+764.drv-0/source/src/node/desktop/out] Error 1
make[1]: *** [CMakeFiles/Makefile2:1074: src/node/desktop/CMakeFiles/electron_build.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
error: builder for '/nix/store/vmihfyyqybrks3ls30fm8dnv5jyqfbbl-RStudio-2024.04.2+764.drv' failed with exit code 2;
       last 25 log lines:
       >      [exec] ✓ 2726 modules transformed.
       >      [exec] rendering chunks...
       >      [exec] dist-rstudio/panmirror.js   4888.97 KiB / gzip: 997.13 KiB
       >      [exec] dist-rstudio/panmirror.js.map 8575.87 KiB
       >      [exec] Done in 11.74s.
       >      [copy] Copying 2 files to /private/tmp/nix-build-RStudio-2024.04.2+764.drv-0/source/src/gwt/www/js/panmirror
       >      [java] Compiling module org.rstudio.studio.RStudio
       >      [java]    Compiling 1 permutation
       >      [java]       Compiling permutation 0...
       >      [java]    Compile of permutations succeeded
       >      [java]    Compilation succeeded -- 112,059s
       >      [java] Linking into /private/tmp/nix-build-RStudio-2024.04.2+764.drv-0/source/src/gwt/www/rstudio; Writing extras to /private/tmp/nix-build-RStudio-2024.04.2+764.drv-0/source/src/gwt/extras/rstudio
       >      [java]    Link succeeded
       >      [java]    Linking succeeded -- 1,358s
       >
       > build:
       >
       > BUILD SUCCESSFUL
       > Total time: 2 minutes 23 seconds
       > [100%] Built target gwt_build
       > [100%] Building desktop (Electron arm64)
       > no such file or directory
       > make[2]: *** [src/node/desktop/CMakeFiles/electron_build.dir/build.make:150: /tmp/nix-build-RStudio-2024.04.2+764.drv-0/source/src/node/desktop/out] Error 1
       > make[1]: *** [CMakeFiles/Makefile2:1074: src/node/desktop/CMakeFiles/electron_build.dir/all] Error 2
       > make: *** [Makefile:156: all] Error 2
       For full logs, run:
         nix log /nix/store/vmihfyyqybrks3ls30fm8dnv5jyqfbbl-RStudio-2024.04.2+764.drv
```

2025-02-19 20:04 UTC, TomaSajt commented
It works for me on x86_64-darwin, don't know where it would differ for `aarch64`.

Can you perhaps run the build with `--keep-failed` (to keep the build tree in a temporary directory inside `/tmp`) and share the structure of `src/node/desktop/out` (if it even exists)?

The contents of `src/node/desktop/CMakeFiles/electron_build.dir/build.make` might also help.

Btw this is what's supposed to happen after it failed for you:
```
BUILD SUCCESSFUL
Total time: 3 minutes 11 seconds
[100%] Built target gwt_build
[100%] Building desktop (Electron x86_64)

> rstudio@99.9.9 package
> electron-forge package
...
```

2025-02-19 20:06 UTC, TomaSajt commented
@ofborg build rstudio

2025-02-20 20:42 UTC, b-rodrigues commented
`out` is indeed not there:

```
macbruno@MacBookAir desktop % pwd
/tmp/nix-build-RStudio-2024.04.2+764.drv-0/source/src/node/desktop
macbruno@MacBookAir desktop % ls -la
total 1429712
drwxr-xr-x@  35 _nixbld1  nixbld       1120 20 Feb 21:28 .
drwxr-xr-x@   6 _nixbld1  nixbld        192 20 Feb 21:28 ..
-rw-r--r--@   1 _nixbld1  nixbld        150  1 Jan  1970 .eslintignore
-rw-r--r--@   1 _nixbld1  nixbld       1887  1 Jan  1970 .eslintrc.js
-rw-r--r--@   1 _nixbld1  nixbld       2264  1 Jan  1970 .gitignore
-rw-r--r--@   1 _nixbld1  nixbld         81  1 Jan  1970 .lintstagedrc
-rw-r--r--@   1 _nixbld1  nixbld        106  1 Jan  1970 .prettierrc
drwxr-xr-x@   4 _nixbld1  nixbld        128  1 Jan  1970 .vscode
-rw-r--r--@   1 _nixbld1  nixbld      10625 20 Feb 21:28 CMakeLists.txt
-rw-r--r--@   1 _nixbld1  nixbld      10511 20 Feb 21:28 Info.plist
-rw-r--r--@   1 _nixbld1  nixbld      10604  1 Jan  1970 Info.plist.in
-rw-r--r--@   1 _nixbld1  nixbld       3161  1 Jan  1970 NEWS-electron.md
-rw-r--r--@   1 _nixbld1  nixbld       1447  1 Jan  1970 README.md
drwxr-xr-x@   3 _nixbld1  nixbld         96 20 Feb 21:28 bin
-rw-r--r--@   1 _nixbld1  nixbld       1659  1 Jan  1970 binding.gyp
drwxr-xr-x@  11 _nixbld1  nixbld        352 20 Feb 21:28 build
drwxr-xr-x@   6 _nixbld1  nixbld        192  1 Jan  1970 docs
drwxr-xr-x@   3 _nixbld1  nixbld         96 20 Feb 21:28 electron-headers
-rw-r--r--@   1 _nixbld1  nixbld  731366755 20 Feb 21:28 electron.zip
-rw-r--r--@   1 _nixbld1  nixbld        817  1 Jan  1970 envvars.bat
-rwxr-xr-x@   1 _nixbld1  nixbld        307  1 Jan  1970 envvars.sh
-rw-r--r--@   1 _nixbld1  nixbld       2285  1 Jan  1970 forge.config.js
drwxr-xr-x@ 807 _nixbld1  nixbld      25824 20 Feb 21:27 node_modules
-rw-r--r--@   1 _nixbld1  nixbld     530428 20 Feb 21:27 package-lock.json
-rw-r--r--@   1 _nixbld1  nixbld       3129 20 Feb 21:28 package.json
drwxr-xr-x@   6 _nixbld1  nixbld        192  1 Jan  1970 resources
-rw-r--r--@   1 _nixbld1  nixbld       2052  1 Jan  1970 rstudio-backtrace.sh.in
drwxr-xr-x@   8 _nixbld1  nixbld        256  1 Jan  1970 scripts
drwxr-xr-x@  11 _nixbld1  nixbld        352 20 Feb 21:28 src
drwxr-xr-x@   3 _nixbld1  nixbld         96  1 Jan  1970 test
-rw-r--r--@   1 _nixbld1  nixbld        549  1 Jan  1970 tsconfig.json
-rw-r--r--@   1 _nixbld1  nixbld        717  1 Jan  1970 webpack.main.config.js
-rw-r--r--@   1 _nixbld1  nixbld        419  1 Jan  1970 webpack.plugins.js
-rw-r--r--@   1 _nixbld1  nixbld        660  1 Jan  1970 webpack.renderer.config.js
-rw-r--r--@   1 _nixbld1  nixbld        804  1 Jan  1970 webpack.rules.js
```

there’s also no CMakeFiles folder, but there’s this file:

```
macbruno@MacBookAir desktop % cat CMakeLists.txt
#
# CMakeLists.txt
#
# Copyright (C) 2022 by Posit Software, PBC
#
# Unless you have received this program directly from Posit Software pursuant
# to the terms of a commercial license agreement with Posit Software, then
# this program is licensed to you under the terms of version 3 of the
# GNU Affero General Public License. This program is distributed WITHOUT
# ANY EXPRESS OR IMPLIED WARRANTY, INCLUDING THOSE OF NON-INFRINGEMENT,
# MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. Please refer to the
# AGPL (http://www.gnu.org/licenses/agpl-3.0.txt) for more details.
#
#

cmake_minimum_required(VERSION 3.6.3)
project(ELECTRON_DESKTOP)

if (LINUX)

   # add rstudio icon to root (so people installing from source or tar.gz can find it
   install(FILES ${CMAKE_CURRENT_SOURCE_DIR}/resources/freedesktop/icons/48x48/rstudio.png
         DESTINATION ${RSTUDIO_INSTALL_SUPPORTING})

   # install configured backtrace utility on linux
   configure_file(${CMAKE_CURRENT_SOURCE_DIR}/rstudio-backtrace.sh.in
                  ${CMAKE_CURRENT_BINARY_DIR}/rstudio-backtrace.sh)
   install(PROGRAMS ${CMAKE_CURRENT_BINARY_DIR}/rstudio-backtrace.sh
                  DESTINATION ${RSTUDIO_INSTALL_BIN})
endif()


# install desktop integration files on linux
if(RSTUDIO_INSTALL_FREEDESKTOP)

   # define freedesktop dirs
   set(RSTUDIO_FREEDESKTOP_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/resources/freedesktop)
   set(RSTUDIO_FREEDESKTOP_BINARY_DIR ${CMAKE_CURRENT_BINARY_DIR}/resources/freedesktop)

   # desktop file (dynamically configured with paths)
   configure_file (${RSTUDIO_FREEDESKTOP_SOURCE_DIR}/rstudio.desktop.in
                  ${RSTUDIO_FREEDESKTOP_BINARY_DIR}/rstudio.desktop)
   install(FILES ${RSTUDIO_FREEDESKTOP_BINARY_DIR}/rstudio.desktop
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/applications)

   # mime types
   install(FILES ${RSTUDIO_FREEDESKTOP_SOURCE_DIR}/rstudio.xml
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/mime/packages)

   # define icon dirs
   set(RSTUDIO_ICONS_16 ${RSTUDIO_FREEDESKTOP_SOURCE_DIR}/icons/16x16)
   set(RSTUDIO_ICONS_24 ${RSTUDIO_FREEDESKTOP_SOURCE_DIR}/icons/24x24)
   set(RSTUDIO_ICONS_32 ${RSTUDIO_FREEDESKTOP_SOURCE_DIR}/icons/32x32)
   set(RSTUDIO_ICONS_48 ${RSTUDIO_FREEDESKTOP_SOURCE_DIR}/icons/48x48)
   set(RSTUDIO_ICONS_256 ${RSTUDIO_FREEDESKTOP_SOURCE_DIR}/icons/256x256)

   # application icon
   install(FILES ${RSTUDIO_ICONS_32}/rstudio.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/pixmaps)
   install(FILES ${RSTUDIO_ICONS_16}/rstudio.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/16x16/apps)
   install(FILES ${RSTUDIO_ICONS_24}/rstudio.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/24x24/apps)
   install(FILES ${RSTUDIO_ICONS_32}/rstudio.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/32x32/apps)
   install(FILES ${RSTUDIO_ICONS_48}/rstudio.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/48x48/apps)
   install(FILES ${RSTUDIO_ICONS_256}/rstudio.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/256x256/apps)

   # .RData icon
   install(FILES ${RSTUDIO_ICONS_16}/application-x-r-data.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/16x16/mimetypes)
   install(FILES ${RSTUDIO_ICONS_24}/application-x-r-data.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/24x24/mimetypes)
   install(FILES ${RSTUDIO_ICONS_32}/application-x-r-data.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/32x32/mimetypes)
   install(FILES ${RSTUDIO_ICONS_48}/application-x-r-data.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/48x48/mimetypes)
   install(FILES ${RSTUDIO_ICONS_256}/application-x-r-data.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/256x256/mimetypes)

   # .Rproj icon
   install(FILES ${RSTUDIO_ICONS_16}/application-x-r-project.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/16x16/mimetypes)
   install(FILES ${RSTUDIO_ICONS_24}/application-x-r-project.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/24x24/mimetypes)
   install(FILES ${RSTUDIO_ICONS_32}/application-x-r-project.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/32x32/mimetypes)
   install(FILES ${RSTUDIO_ICONS_48}/application-x-r-project.png
         DESTINATION /nix/store/pawrc2qjsxpxm6h3s60rx9n96fp18bc6-RStudio-2024.04.2+764/share/icons/hicolor/48x48/mimetypes)
   install(FILES ${RSTUDIO_ICONS_256}/application-x-r-project.png
         DESTINATION /nix [...]

2025-02-20 23:29 UTC, TomaSajt commented
Ah I was mistaken: the generated cmake files are put inside a directory named `build/` in the source root. So the correct path would be `build/src/node/desktop/CMakeFiles/electron_build.dir/build.make`

2025-02-20 23:46 UTC, TomaSajt commented
@ofborg build rstudio

2025-02-21 06:07 UTC, TomaSajt commented
@ofborg build rstudio

2025-02-21 08:25 UTC, b-rodrigues commented
with the latest commit, this is what I get:

```
       > -- Installing: /nix/store/00mi4m8iwldvl5xaag1srlvb47bciqh5-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/app/bin/../../RMarkdown.icns
       > -- Installing: /nix/store/00mi4m8iwldvl5xaag1srlvb47bciqh5-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/app/bin/../../RPresentation.icns
       > -- Installing: /nix/store/00mi4m8iwldvl5xaag1srlvb47bciqh5-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/app/bin/../../RProject.icns
       > -- Installing: /nix/store/00mi4m8iwldvl5xaag1srlvb47bciqh5-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/app/bin/../../RSource.icns
       > -- Installing: /nix/store/00mi4m8iwldvl5xaag1srlvb47bciqh5-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/app/bin/../../RStudio.icns
       > -- Installing: /nix/store/00mi4m8iwldvl5xaag1srlvb47bciqh5-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/app/bin/../../RSweave.icns
       > -- Installing: /nix/store/00mi4m8iwldvl5xaag1srlvb47bciqh5-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/app/bin/../../RTex.icns
       > CMake Error at src/node/desktop/cmake_install.cmake:61 (file):
       >   file INSTALL cannot find
       >   "/tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/src/node/desktop/out/RStudio-darwin-x64":
       >   No such file or directory.
       > Call Stack (most recent call first):
       >   src/node/cmake_install.cmake:42 (include)
       >   src/cmake_install.cmake:44 (include)
       >   cmake_install.cmake:63 (include)
       >
       >
       > make: *** [Makefile:120: install] Error 1
```

this is the make file that I find in the path you mention:

```
macbruno@MacBookAir desktop % cd CMakeFiles
macbruno@MacBookAir CMakeFiles % ls
CMakeDirectoryInformation.cmake	electron_build.dir		progress.marks
electron.dir			electron_fuses.dir
macbruno@MacBookAir CMakeFiles % cd electron.dir
macbruno@MacBookAir electron.dir % ls
DependInfo.cmake	cmake_clean.cmake	compiler_depend.ts
build.make		compiler_depend.make	progress.make
macbruno@MacBookAir electron.dir % cat build.make
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/38920hcwdp3aygvj4mp3fvv5q5rqbywb-cmake-3.31.3/bin/cmake

# The command to remove a file.
RM = /nix/store/38920hcwdp3aygvj4mp3fvv5q5rqbywb-cmake-3.31.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build

# Utility rule file for electron.

# Include any custom commands dependencies for this target.
include src/node/desktop/CMakeFiles/electron.dir/compiler_depend.make

# Include the progress variables for this target.
include src/node/desktop/CMakeFiles/electron.dir/progress.make

src/node/desktop/CMakeFiles/electron.dir/codegen:
.PHONY : src/node/desktop/CMakeFiles/electron.dir/codegen

electron: src/node/desktop/CMakeFiles/electron.dir/build.make
.PHONY : electron

# Rule to build all files generated by this target.
src/node/desktop/CMakeFiles/electron.dir/build: electron
.PHONY : src/node/desktop/CMakeFiles/electron.dir/build

src/node/desktop/CMakeFiles/electron.dir/clean:
	cd /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build/src/node/desktop && $(CMAKE_COMMAND) -P CMakeFiles/electron.dir/cmake_clean.cmake
.PHONY : src/node/desktop/CMakeFiles/electron.dir/clean

src/node/desktop/CMakeFiles/electron.dir/depend:
	cd /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/src/node/desktop /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build/src/node/desktop /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build/src/node/desktop/CMakeFiles/electron.dir/DependInfo.cmake "--color=$(COLOR)"
.PHONY : src/node/desktop/CMakeFiles/electron.dir/depend

macbruno@MacBookAir electron.dir % pwd
/tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build/src/node/desktop/CMakeFiles/electron.dir
macbruno@MacBookAir electron.dir % cat build.make
# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Delete rule output on recipe failure.
.DELETE_ON_ERROR:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /nix/store/38920hcwdp3aygvj4mp3fvv5q5rqbywb-cmake-3.31.3/bin/cmake

# The command to remove a file.
RM = /nix/store/38920hcwdp3aygvj4mp3fvv5q5rqbywb-cmake-3.31.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build

# Utility rule file for electron.

# Include any custom commands dependencies for this target.
include src/node/desktop/CMakeFiles/electron.dir/compiler_depend.make

# Include the progress variables for this target.
include src/node/desktop/CMakeFiles/electron.dir/progress.make

src/node/desktop/CMakeFiles/electron.dir/codegen:
.PHONY : src/node/desktop/CMakeFiles/electron.dir/codegen

electron: src/node/desktop/CMakeFiles/electron.dir/build.make
.PHONY : electron

# Rule to build all files generated by this target.
src/node/desktop/CMakeFiles/electron.dir/build: electron
.PHONY : src/node/desktop/CMakeFiles/electron.dir/build

src/node/desktop/CMakeFiles/electron.dir/clean:
	cd /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build/src/node/desktop && $(CMAKE_COMMAND) -P CMakeFiles/electron.dir/cmake_clean.cmake
.PHONY : src/node/desktop/CMakeFiles/electron.dir/clean

src/node/desktop/CMakeFiles/electron.dir/depend:
	cd /tmp/nix-build-RStudio-2024.04.2+764.drv-1/source/build && $(CMAKE_COMMAND) -E cmake_depends "Unix Makefiles" /tmp/nix-build-RStudi [...]

2025-02-21 10:48 UTC, TomaSajt commented
@ofborg build rstudio

2025-02-21 10:57 UTC, TomaSajt commented
@ofborg build rstudio

2025-02-21 11:17 UTC, TomaSajt commented
Okay, aarch64-darwin is working now, the issue was that `uname -m` returns `aarch64` on linux, but `arm64` on darwin.

2025-02-21 11:17 UTC, TomaSajt commented
@ofborg build rstudio

2025-02-21 11:18 UTC, TomaSajt commented
Now the only question is: does it build on aarch64-linux. Ofborg seems to get stuck on linux builds currently.
If anyone has an `aarch64-linux` machine, I'd appreciate if they tried building the package.

2025-02-21 11:22 UTC, b-rodrigues commented
> Okay, aarch64-darwin is working now, the issue was that `uname -m` returns `aarch64` on linux, but `arm64` on darwin.

it builds, but fails when trying to execute it

![Screenshot 2025-02-21 at 12 21 33 PM](https://github.com/user-attachments/assets/6013f242-443d-4650-b2aa-41eb324169fb)

2025-02-21 11:38 UTC, TomaSajt commented
does that file exist? I assume no, and it's just called `rsession`.

2025-02-21 11:48 UTC, b-rodrigues commented
> does that file exist? I assume no, and it's just called `rsession`.

yep, exactly!

2025-02-21 11:50 UTC, TomaSajt commented
> yep, exactly!

I have pushed a commit trying to fix it. Hopefully it works.

2025-02-21 12:30 UTC, b-rodrigues commented
![Screenshot 2025-02-21 at 1 29 57 PM](https://github.com/user-attachments/assets/cbde3b0e-b79b-4fe3-9f0c-4e2f95da917f)

let’s goooooooooooooooo



> Now the only question is: does it build on aarch64-linux. Ofborg seems to get stuck on linux builds currently. If anyone has an `aarch64-linux` machine, I'd appreciate if they tried building the package.

currently building on my rpi5!

2025-02-21 12:32 UTC, b-rodrigues commented
> ![Screenshot 2025-02-21 at 1 29 57 PM](https://private-user-images.githubusercontent.com/2998834/415643069-cbde3b0e-b79b-4fe3-9f0c-4e2f95da917f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NDAxNDEzNDgsIm5iZiI6MTc0MDE0MTA0OCwicGF0aCI6Ii8yOTk4ODM0LzQxNTY0MzA2OS1jYmRlM2IwZS1iNzliLTRmZTMtOWYwYy00ZTJmOTVkYTkxN2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI1MDIyMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNTAyMjFUMTIzMDQ4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGVkMzcxMTlhMzkzYmYxMGYwNmVhOGNmNjYzYTU2NGNjZGZiZTllYmFjY2E3ZGEyOTU2NmM4Y2U5N2Y0Mjg4OCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.py9EKCrwkVdAKj2nX6misJcEqOOIp_Ef0B4VWMGiKDI)

i just saw that BLAS is from the system, and not nix blas.

2025-02-21 12:36 UTC, b-rodrigues commented
Visual markdown mode (made possible by panmirror?) doesn’t work however:

![Screenshot 2025-02-21 at 1 35 02 PM](https://github.com/user-attachments/assets/858df98b-d337-4eef-b9ef-0d9adb8f2cc6)

but editing from source is ok

2025-02-21 12:41 UTC, TomaSajt commented
> i just saw that BLAS is from the system, and not nix blas.

Is that not just R's issue? Can you run `sessionInfo()` on the R repl?

2025-02-21 12:42 UTC, b-rodrigues commented
![Screenshot 2025-02-21 at 1 42 37 PM](https://github.com/user-attachments/assets/4afcc3d4-eb5a-456f-a192-d5b00792bd8d)

in the repl the correct blas is there

2025-02-21 12:43 UTC, TomaSajt commented
> Visual markdown mode (made possible by panmirror?) doesn’t work however:


I think it's quarto which makes it work.

2025-02-21 12:50 UTC, TomaSajt commented
Can you check if the blas thing is also an issue on x86_64-darwin? I can only check once I get home (~6 hours).

2025-02-21 13:18 UTC, b-rodrigues commented
>Now the only question is: does it build on aarch64-linux. Ofborg seems to get stuck on linux builds currently.
If anyone has an `aarch64-linux` machine, I'd appreciate if they tried building the package.

I'm getting this on my rpi5

```
[nix-shell:~/Documents/nixpkgs]$ rstudio
[25808:0221/141354.206907:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/w2xhxkwg02hy5494q2vyj48s9qkspid3-electron-33.4.0/libexec/electron/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
```

2025-02-21 13:18 UTC, b-rodrigues commented
> > Visual markdown mode (made possible by panmirror?) doesn’t work however:
> 
> I think it's quarto which makes it work.

installing quarto and the quarto r Package doesn't fix the issue

2025-02-21 13:38 UTC, TomaSajt commented
> > Now the only question is: does it build on aarch64-linux. Ofborg seems to get stuck on linux builds currently.
> > If anyone has an `aarch64-linux` machine, I'd appreciate if they tried building the package.
> 
> I'm getting this on my rpi5
> 
> ```
> [nix-shell:~/Documents/nixpkgs]$ rstudio
> [25808:0221/141354.206907:FATAL:setuid_sandbox_host.cc(163)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /nix/store/w2xhxkwg02hy5494q2vyj48s9qkspid3-electron-33.4.0/libexec/electron/chrome-sandbox is owned by root and has mode 4755.
> Trace/breakpoint trap (core dumped)
> ```

NixOS or not?

2025-02-21 13:42 UTC, TomaSajt commented
> installing quarto and the quarto r Package doesn't fix the issue

Quarto is supposed to be embedded into the rstudio package, I wonder why it's not working.

2025-02-21 13:42 UTC, b-rodrigues commented
that’s ubuntu on my rpi5

2025-02-21 13:43 UTC, TomaSajt commented
It's a known issue I think. Some issues:
https://github.com/NixOS/nixpkgs/issues/121694
https://github.com/NixOS/nixpkgs/issues/340553

2025-02-21 13:52 UTC, b-rodrigues commented
> Can you check if the blas thing is also an issue on x86_64-darwin? I can only check once I get home (~6 hours).

I don't have x86_64-darwin on hand, but on x86 non-nixos linux I get the right libs in rstudio:

```
> sessionInfo()
R version 4.4.2 (2024-10-31)
Platform: x86_64-pc-linux-gnu
Running under: openSUSE Tumbleweed-Slowroll

Matrix products: default
BLAS/LAPACK: /nix/store/lvriqwx4ampgndg088jfy8g1n4l5hf07-blas-3/lib/libblas.so.3;  LAPACK version 3.12.0

locale:
[1] C

time zone: Europe/Luxembourg
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

loaded via a namespace (and not attached):
[1] compiler_4.4.2 tools_4.4.2  
```

2025-02-21 13:55 UTC, b-rodrigues commented
> It's a known issue I think. Some issues: #121694 #340553

using this fix works!

https://github.com/NixOS/nixpkgs/issues/121694#issuecomment-2159420924

![image](https://github.com/user-attachments/assets/19aa08e5-1719-4a46-a251-32147a7a76c0)

2025-02-21 14:00 UTC, TomaSajt commented
If you try running the R repl with `/usr/bin/arch -arm64 /path/to/R/bin/R` does it still find the correct libs?

2025-02-21 14:20 UTC, b-rodrigues commented
> If you try running the R repl with `/usr/bin/arch -arm64 /path/to/R/bin/R` does it still find the correct libs?

this is what I’m getting

```
macbruno@MacBookAir bin % pwd
/nix/store/yi63qpgraylsrn2za7f15za1fxj9y9wd-R-4.4.2/bin
macbruno@MacBookAir bin % /usr/bin/arch ./R
arch: Can't find any plists for R
```

2025-02-21 17:08 UTC, TomaSajt commented
I have disabled the `/usr/bin/arch` code path. Could you check if it detects the correct libs now?

2025-02-21 17:32 UTC, b-rodrigues commented
here’s what happens 

![Screenshot 2025-02-21 at 6 31 29 PM](https://github.com/user-attachments/assets/a9727d71-9de4-4eb0-8c83-4c074d13d3be)

2025-02-21 18:07 UTC, TomaSajt commented
I'm starting to run out of ideas. At least it kinda works.

Just for the record could you run `otool -L rsession`?

(rsession is found inside app/bin/ as mentioned earlier when rsession-arm64 was giving an error)

2025-02-21 19:47 UTC, b-rodrigues commented
```
macbruno@MacBookAir bin % otool -L rsession
rsession:
	/System/Library/Frameworks/AppKit.framework/Versions/C/AppKit (compatibility version 45.0.0, current version 2022.44.149)
	/System/Library/Frameworks/ApplicationServices.framework/Versions/A/ApplicationServices (compatibility version 1.0.0, current version 54.0.0)
	/System/Library/Frameworks/CoreFoundation.framework/Versions/A/CoreFoundation (compatibility version 150.0.0, current version 1775.118.101)
	/System/Library/Frameworks/Foundation.framework/Versions/C/Foundation (compatibility version 300.0.0, current version 1775.118.101)
	/System/Library/Frameworks/IOKit.framework/Versions/A/IOKit (compatibility version 1.0.0, current version 275.0.0)
	/System/Library/Frameworks/Security.framework/Versions/A/Security (compatibility version 1.0.0, current version 59754.100.106)
	/usr/lib/libbsm.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_chrono.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_date_time.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_filesystem.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_atomic.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_iostreams.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_program_options.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_random.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_regex.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_system.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/sclps4dydfixafi0ycl1j83jiar8ppy1-boost-1.86.0/lib/libboost_thread.dylib (compatibility version 0.0.0, current version 0.0.0)
	/nix/store/qwrfb4sa49j8vgmy1cwjp2lfxbvjnw93-soci-4.0.2/lib/libsoci_sqlite3.4.0.dylib (compatibility version 4.0.0, current version 4.0.2)
	/nix/store/b69y2x9qchlnc74cn0f6q2yl5cbdgilq-sqlite-3.47.2/lib/libsqlite3.0.dylib (compatibility version 9.0.0, current version 9.6.0)
	/nix/store/qwrfb4sa49j8vgmy1cwjp2lfxbvjnw93-soci-4.0.2/lib/libsoci_core.4.0.dylib (compatibility version 4.0.0, current version 4.0.2)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1292.100.5)
	/nix/store/hzq48n4hmcwsgccab7djxxxj2m8h4cxb-zlib-1.3.1/lib/libz.dylib (compatibility version 1.0.0, current version 1.3.1)
	/System/Library/Frameworks/CoreServices.framework/Versions/A/CoreServices (compatibility version 1.0.0, current version 1122.33.0)
	/nix/store/xyyrhzi79jag316qbydnfh4sxm6bw95r-openssl-3.3.2/lib/libssl.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/nix/store/xyyrhzi79jag316qbydnfh4sxm6bw95r-openssl-3.3.2/lib/libcrypto.3.dylib (compatibility version 3.0.0, current version 3.0.0)
	/nix/store/nay4rncz32b14y7z26hh9xc332sbw9x8-yaml-cpp-0.8.0/lib/libyaml-cpp.0.8.dylib (compatibility version 0.8.0, current version 0.8.0)
	/nix/store/ad9j570pg9i32id8li4f6sibg2mjghi6-libcxx-19.1.7/lib/libc++.1.0.dylib (compatibility version 1.0.0, current version 1.0.0)
	/usr/lib/libobjc.A.dylib (compatibility version 1.0.0, current version 228.0.0)
```

2025-02-21 21:12 UTC, TomaSajt commented
checked on x86_64-darwin, the BLAS path is also not in the nix store.

Pushed a new commit which should ideally get rid of `arch` usage, but I don't expect it do anything now that I've researched what the used env vars mean.

2025-02-21 22:13 UTC, TomaSajt commented
Visual mode also doesn't seem to work on x86_64-darwin (same Error Error message)

2025-02-21 22:58 UTC, b-rodrigues commented
yep, latest commit still shows blas outside of the nix store

2025-02-21 23:15 UTC, TomaSajt commented
I don't think I want to track the BLAS thing down in this PR.
I think I also have the solution to the visual mode issue now.
I'll re-check x86_64-linux first, since it was a bigger change and if it works I'll check x86_64-darwin.

2025-02-21 23:16 UTC, TomaSajt commented
Should I keep the `arch` patch? It's not necessary, but keeps the program a bit more "pure".

2025-02-21 23:31 UTC, TomaSajt commented
> I don't think I want to track the BLAS thing down in this PR. I think I also have the solution to the visual mode issue now. I'll re-check x86_64-linux first, since it was a bigger change and if it works I'll check x86_64-darwin.

Okay, x86_64-linux still works, would appreciate if you tried if aarch64-darwin works now

2025-02-21 23:51 UTC, b-rodrigues commented
> > I don't think I want to track the BLAS thing down in this PR. I think I also have the solution to the visual mode issue now. I'll re-check x86_64-linux first, since it was a bigger change and if it works I'll check x86_64-darwin.
> 
> Okay, x86_64-linux still works, would appreciate if you tried if aarch64-darwin works now

visual mode works now :)

I guess we can live with the system BLAS being used on Darwin, it’s not the 100%, but I doubt it’ll have much impact in practice.

2025-02-22 10:54 UTC, b-rodrigues commented
To summarise my testing:

on aarch64-darwin, it builds and runs. Visual markdown mode as well. The only hiccup is that the system BLAS is used instead of the nix BLAS.

on aarch64-linux (non NixOS, Ubunut), it builds, but needs https://github.com/NixOS/nixpkgs/issues/121694#issuecomment-2159420924 to run. Visual markdown mode runs.

2025-02-22 19:52 UTC, Kupac reviewed
We are so close... I was about to write that everyting works 100% on x86_64-linux:
- rstudio and rserver
- Visual mode
- Using the BLAS from the nix store
 but then I saw this in the terminal of rserver:
 
![image](https://github.com/user-attachments/assets/7a8da01b-5935-4059-b18d-a521560d080a)

It renders the terminal unusable, but it may be just my weird fonts or something. Can somebody double check this?

2025-02-22 21:48 UTC, Kupac approved these changes
OK, I found the culprit. In the Global options -> Terminal, I can disable hardware acceleration, and then it looks normal. It was Librewolf that garbled the fonts, probably some privacy protection feature. I checked in Chromium, and it looks good with or without hardware acc. LGTM!

2025-02-22 21:52 UTC, TomaSajt commented on pkgs/applications/editors/rstudio/default.nix
>      mkdir -p dependencies/common/node
```suggestion
```
this line is unnecessary, I have removed it in the next PR. (don't really want to cause more rebuilds with this PR)

2025-02-24 01:08 UTC, jbedo commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 362637`

---
### `aarch64-darwin`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>rstudio</li>
    <li>rstudioWrapper</li>
  </ul>
</details>

2025-02-24 01:10 UTC, jbedo commented
the rstudio-server error on aarch64-darwin:
```
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/en_AU.dic
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/eu_ES.dic
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/id_ID.dic
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_CR.dic
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_AR.aff
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_CL.aff
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_VE.dic
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_MX.dic
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/sv_SE.dic
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/en_US.dic
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/en_CA.aff
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/mathjax-27
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/MacOS/node
       > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/MacOS/quarto
       > CMake Error at src/cpp/session/cmake_install.cmake:262 (file):
       >   file INSTALL cannot find
       >   "/tmp/nix-build-RStudio-2024.04.2+764.drv-0/source/dependencies/quarto/share":
       >   No such file or directory.
       > Call Stack (most recent call first):
       >   src/cpp/cmake_install.cmake:48 (include)
       >   src/cmake_install.cmake:43 (include)
       >   cmake_install.cmake:63 (include)
       >
       > 
       > make: *** [Makefile:120: install] Error 1
```

2025-02-24 01:17 UTC, jbedo commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 362637`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
  </ul>
</details>

2025-02-24 01:29 UTC, jbedo requested changes
This looks great in general, only the rstudio-server build on mac to fix. Other builds tested fully functional.

2025-02-24 01:29 UTC, jbedo commented on pkgs/applications/editors/rstudio/default.nix
> +      (lib.cmakeBool "RSTUDIO_CRASHPAD_ENABLED" false) # need to explicitly disable for x86_64-darwin
This is disabled for all architectures not just x86_64-darwin, should this be a conditional based on platform?

2025-02-24 07:11 UTC, TomaSajt commented on pkgs/applications/editors/rstudio/default.nix
> +      (lib.cmakeBool "RSTUDIO_CRASHPAD_ENABLED" false) # need to explicitly disable for x86_64-darwin
This should option should be disabled on all platforms.
The comment is there because the cmake variable is only ON by default on x86_64-darwin.
I'll re-check it once I get to a computer, but that's what I remember.

2025-02-24 08:39 UTC, TomaSajt commented on pkgs/applications/editors/rstudio/default.nix
> +      (lib.cmakeBool "RSTUDIO_CRASHPAD_ENABLED" false) # need to explicitly disable for x86_64-darwin
Reworded the comment

2025-02-24 08:39 UTC, TomaSajt commented
> the rstudio-server error on aarch64-darwin:
> 
> ```
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/en_AU.dic
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/eu_ES.dic
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/id_ID.dic
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_CR.dic
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_AR.aff
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_CL.aff
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_VE.dic
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/es_MX.dic
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/sv_SE.dic
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/en_US.dic
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/dictionaries/en_CA.aff
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/Resources/resources/mathjax-27
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/MacOS/node
>        > -- Installing: /nix/store/qfzf9qqqjvb1qamncx6kdw8knibfjr20-RStudio-2024.04.2+764/Applications/RStudio.app/Contents/MacOS/quarto
>        > CMake Error at src/cpp/session/cmake_install.cmake:262 (file):
>        >   file INSTALL cannot find
>        >   "/tmp/nix-build-RStudio-2024.04.2+764.drv-0/source/dependencies/quarto/share":
>        >   No such file or directory.
>        > Call Stack (most recent call first):
>        >   src/cpp/cmake_install.cmake:48 (include)
>        >   src/cmake_install.cmake:43 (include)
>        >   cmake_install.cmake:63 (include)
>        >
>        > 
>        > make: *** [Makefile:120: install] Error 1
> ```

Should be fixed in theory

2025-02-25 12:00 UTC, TomaSajt commented
@ofborg build rstudio rstudio-server

2025-02-26 22:40 UTC, jbedo commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 362637`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>rstudio</li>
    <li>rstudio-server</li>
    <li>rstudioServerWrapper</li>
    <li>rstudioWrapper</li>
  </ul>
</details>

2025-02-26 22:47 UTC, jbedo approved these changes

2025-02-27 06:25 UTC, b-rodrigues commented
getting

```
       error: Package ‘positron-bin-2024.11.0-116’ in /home/cbrunos/Documents/nixpkgs/pkgs/by-name/po/positron-bin/package.nix:123 is not available on the requested hostPlatform:
         hostPlatform.config = "aarch64-unknown-linux-gnu"
         package.meta.platforms = [
           "x86_64-linux"
           "x86_64-darwin"
           "i686-darwin"
           "aarch64-darwin"
           "armv7a-darwin"
         ]
         package.meta.badPlatforms = [ ]
       , refusing to evaluate.

```

this is on ubuntu arm where it needed  https://github.com/NixOS/nixpkgs/issues/121694#issuecomment-2159420924 to run I think that this is acceptable, no? I'll try to set up a nixOS arm vm on my macbook and try there as well and see if the solution in the linked comment is also needed

2025-02-27 06:39 UTC, TomaSajt commented
@ofborg build rstuidoWrapper rstudioServerWrapper

2025-02-27 12:37 UTC, TomaSajt commented
All 4 platforms built it successfully. If anyone wants to merge, go ahead.

2025-02-27 17:08 UTC, b-rodrigues commented
> on aarch64-linux (non NixOS, Ubuntu), it builds, but needs [#121694 (comment)](https://github.com/NixOS/nixpkgs/issues/121694#issuecomment-2159420924) to run. Visual markdown mode runs.

working well on aarch64-linux (ubuntu) using the trick in the comment

2025-02-27 17:10 UTC, b-rodrigues approved these changes

2025-02-27 20:38 UTC, merged