nixos/nginx: setup logrotate to run postrotate only once
NixOS/nixpkgs pull request #362733
Opened 2024-12-07 08:52 UTC by jbgi

with `sharedscripts = true`: nginx need to receive the kill USR1
 signal only once at the end, instead of once per log file.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-08 09:02 UTC, jbgi commented
An alternative fix would be to set `sharedscripts = true;` but there may be people relying on `postrotate` running for each log file. Though this pr would also be a breaking change for people currently using `lastaction`, but probably much less common.

2026-07-03 16:38 UTC, leona-ya requested changes
From what I can see, `lastaction` seems to not be the correct way to do this. I agree that with `delaycompress = true` we can just signal `USR1` once to NGINX and save some time.
After some minutes of research I found out, ~nobody seems to use `lastaction` for NGINX and it's intent is more about post-processing stuff. The semantically more correct way to do this is by setting `sharedscripts = true`, that's also how our Apache httpd modules does it.

As the PR is quite old, please tell me if you want to proceed with this or whether I should open a new one (I need to do some tests however if I understood everything correctly that this works).

2026-07-05 14:00 UTC, jbgi commented
> The semantically more correct way to do this is by setting `sharedscripts = true`

agreed. Updated the PR.

>  with `delaycompress = true` we can just signal USR1 once to NGINX and save some time.

From what I have seen, even with `delaycompress = false` and `sharedscripts = true`, the `postrotate` script is run before compression of the newly rotated log files (only the old logs files may be compressed before  `postrotate`).

2026-07-26 15:48 UTC, leona-ya approved these changes
Sorry for the long wait time! I'm busy with moving and my university thesis..
Thank you for the change, looks now good!

2026-07-26 15:53 UTC, merged