nixos/xen: declarative `libxenlight`, part I
NixOS/nixpkgs pull request #363388
Opened 2024-12-08 22:33 UTC by SigmaSquadron

- Splits up the Xen module into smaller files.
- Creates the `xl` format generator.
- Makes `/etc/xl.conf` configurable.

No guest stuff yet. That's part II.

I would like to apologise in advance to whoever reviews `formats.nix`.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-10 07:02 UTC, hehongbo commented on nixos/modules/virtualisation/xen/xl.nix
> +        assertion = cfg.dom0Resources.memory != 0 -> !cfg.settings.autoballoon == "on";
The type and the default value of this `autoballoon` is not defined, so if I have `dom0Resources` I will receive `error: attribute 'autoballoon' missing`, and if I set `autoballoon = "off";` I will get `error: expected a Boolean but found a string: "off"`

2024-12-11 01:27 UTC, SigmaSquadron commented
Commits have been fixed. It should now be much easier to review commit by commit.

2024-12-11 02:12 UTC, hehongbo approved these changes

2024-12-11 04:40 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/2144

2025-01-20 22:39 UTC, Stunkymonkey requested changes

2025-01-20 22:39 UTC, Stunkymonkey commented on pkgs/pkgs-lib/formats.nix
if you want to add something to `pkgs/pkgs-lib/*` please provide docs at `nixos/doc/manual/development/settings-options.section.md`

2025-01-20 23:22 UTC, SigmaSquadron commented on pkgs/pkgs-lib/formats.nix
Done! There's now documentation for all of the quirks of this function.

2025-01-20 23:23 UTC, SigmaSquadron commented
Something is wrong with the CI, and I'm not entirely sure why. The manual fails because it tries to connect to the internet for some reason, and I got emails about the basic Nix parsing checks failing, even though this is valid Nix.

2025-02-15 22:05 UTC, CertainLach approved these changes

2025-02-19 00:54 UTC, hehongbo approved these changes

2025-05-16 17:59 UTC, SigmaSquadron commented
@Stunkymonkey: may I ask you for a re-review?

2025-07-18 10:43 UTC, last-genius commented on nixos/modules/virtualisation/xen/oxenstored.nix
> +# Used in dom0 by default, but can also be used in a stubdomain.
This comment slightly confused me.

Only C-xenstored can run as a stubdomain at the moment, hence this language in `sysconfig/xencommons`:
```
## Type: string
## Default: xenstored
#
# Select xenstore implementation, this can be either
# of these below.
# Only evaluated if XENSTORETYPE is "daemon". <------ (i.e. if "domain", then only cxenstored)
#
# This can be either of:
#  * /usr/sbin/oxenstored
#  * /usr/sbin/xenstored
```

I don't think the current config allows choosing XENSTORETYPE either, unless I'm missing something (I hope you'll excuse me, I'm coming at this from the xen side, and not terribly familiar with nix. This is a great and much appreciated effort, eventually being able to declaratively declare domains in nix would be great!)

2025-07-19 10:03 UTC, SigmaSquadron commented on nixos/modules/virtualisation/xen/oxenstored.nix
> +# Used in dom0 by default, but can also be used in a stubdomain.
Hey, thanks for reviewing! I'm a bit busy with other projects at the moment, and I haven't gotten around to fixing the Xen Store config yet.

You're right, this is probably very wrong as it stands, and so far I don't think anyone is running the store in a NixOS stubdom. When I have more time again, I'll look into this PR again.

2025-07-29 10:02 UTC, jackrosenberg commented on pkgs/pkgs-lib/formats.nix
> +                  0
```suggestion
                else if v then
                  1
                else if !v then
                  0
```
or will this break?

2026-01-23 23:00 UTC, SigmaSquadron commented
This PR has gotten really hard to rebase over the years, and I'm opening smaller PRs like #483205 to make it easier to review and merge.

- [x] General improvements https://github.com/NixOS/nixpkgs/pull/483205
- [ ] `formats.xenLight` https://github.com/NixOS/nixpkgs/pull/483278
- [ ] Oxenstored settings
- [ ] `xl.conf` settings

2026-02-07 06:21 UTC, closed without merging