soulseekqt: init at 2016-1-17 (last official stable)
NixOS/nixpkgs pull request #36343
Opened 2018-03-05 14:22 UTC by bignaux

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-03-05 17:58 UTC, nlewo requested changes

2018-03-05 17:58 UTC, nlewo commented on pkgs/applications/networking/p2p/soulseekqt/default.nix
> +  mainbin = "SoulseekQt-" + (version) +"-"+ (if stdenv.is64bit then "64bit" else "32bit");
Could you move this attribute out of the derivation attributes (by using `let ... in mkDerivation ...`) since it is not used by the builder.

2018-03-05 17:58 UTC, nlewo commented on pkgs/applications/networking/p2p/soulseekqt/default.nix
> +  src = fetchurl ({
I think readability could be improved by moving some parts of this in the let block.

2018-03-05 17:58 UTC, nlewo commented on pkgs/applications/networking/p2p/soulseekqt/default.nix
> +  libPath = stdenv.lib.makeLibraryPath
Not required by the builder also.

2018-03-06 11:13 UTC, nlewo commented
Thanks for these improvments:)

@GrahamcOfBorg build soulseekqt

2018-03-06 11:13 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.36343&attempt_id=7a35c81f-c68c-4a44-9fa5-4a19cbfc0282)

<details><summary>Partial log (click to expand)</summary><p>

```
Package ‘soulseekqt-2016-1-17’ in /var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/builder-0-gustav.ewr1.nix.ci/pkgs/applications/networking/p2p/soulseekqt/default.nix:50 has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

```
</p></details>

2018-03-06 11:13 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.36343&attempt_id=ce9b0843-9257-4521-ab28-856c2e90c49b)

<details><summary>Partial log (click to expand)</summary><p>

```
Package ‘soulseekqt-2016-1-17’ in /var/lib/gc-of-borg/nix-test-rs-5/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/grahamc-aarch64-community-5/pkgs/applications/networking/p2p/soulseekqt/default.nix:50 has an unfree license (‘unfree’), refusing to evaluate.

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.

```
</p></details>

2018-03-06 11:16 UTC, nlewo commented
Could you squash your commits and rewrite the first commit since it is no longer a "wip" commit.

2018-03-06 11:23 UTC, bignaux commented
sorry i was trying to squash commit and look for some deeper test since i don't see any Qt in ldd, i fear it call it dynamically from my non-nixos path.

2018-03-06 11:40 UTC, bignaux commented
qt is hardlinked, so i think we are good now. Thanks for review.

2018-03-06 14:07 UTC, nlewo commented
Ok. It've tryied and it works well on my NixOS machine. Indeed, it can't use libraries from your host since it doen't use the ld program of your host.
@bignaux one last thing, can you just clean the commit message (just keep the first line)?

2018-03-06 17:10 UTC, bignaux commented
@nlewo : done. I use rebase + "push -f", i'm not very satisfied with this workflow.

2018-03-06 18:01 UTC, nlewo commented
@bignaux since it's nice to have a clean history for public branches, you need to rewrite the history of your private branch and then you must `push --force`.

Thanks for your contribution.

2018-03-06 18:01 UTC, merged