fotema: init at 1.18.2
NixOS/nixpkgs pull request #364392
Opened 2024-12-11 23:44 UTC by pluiedev

Closes #364318

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-11 23:56 UTC, ddogfoodd requested changes
got a hash mismatch

```sh
error: hash mismatch in fixed-output derivation '/nix/store/rwvz4crqpm93xi8fbv11hbnkq6bd06k8-source.drv':
        likely URL: https://github.com/blissd/fotema/archive/refs/tags/v1.18.2.tar.gz
         specified: sha256-JLyJjL1g9H1DZMJE/sDEorUoC1mPks/mTCz3ILTUPY4=
            got:    sha256-5TWvxuktNWx2DJ1NeKaxO2mjZ/QVEYNWsvK36FGAkU0=
error: 1 dependencies of derivation '/nix/store/zm6xp7f9fyqhjpyiaild1h40qzsb1ikk-fotema-1.18.2-vendor-staging.drv' failed to build
error: 1 dependencies of derivation '/nix/store/1q59qkx1d08gy7wd9sa6js5m5lfkmwir-fotema-1.18.2-vendor.drv' failed to build
```

2024-12-12 12:29 UTC, pluiedev commented
Oops, looks like I had the 1.18.0 hash in there. Fixing

2024-12-12 13:15 UTC, pluiedev commented
Converting to draft for now due to depending on #364572

2025-12-15 08:25 UTC, MatthewCroughan commented
@pluiedev I saw this on fedi recently https://mamot.fr/@thibaultamartin/115717794572041368 and was wondering if there's any interest in renewing this PR since v2.x is out now, and maybe things build better

2026-02-23 16:06 UTC, pluiedev commented
Just updated this to 2.4.1 after https://github.com/NixOS/nixpkgs/pull/481377 got merged :)

2026-02-24 02:35 UTC, merged