nixos: add option `hardware.enableAllHardware`
NixOS/nixpkgs pull request #364479
Opened 2024-12-12 05:25 UTC by DavHau

This allows users to simply enable support for all hardware by enabling the option `hardware.enableAllHardware`, instead of having to import `modules/profiles/all-hardware.nix`.

This is better, as the enableAllHardware option will be discoverable via search.nixos.org, while the `all-hardware.nix` is hidden inside nixpkgs and hard to discover.

Backward compatibility is provided by replacing the old `profiles/all-hardware.nix` with a file that sets the `enableAllHardware` option to true.

The diff of this change is quite small if you review the individual commits.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-12 09:13 UTC, jopejoe1 requested changes
This would currently force everyone that sets `hardware.enableRedistributableFirmware` to true to switch over to using `lib.mkForce`, just setting the options when the module is enabled would be better.

2024-12-12 09:13 UTC, jopejoe1 commented on nixos/modules/hardware/all-hardware.nix
> +  config = {
```suggestion
  config = lib.mkIf config.hardware.enableAllHardware {
```

2024-12-12 09:13 UTC, jopejoe1 commented on nixos/modules/hardware/all-hardware.nix
> +    boot.initrd.availableKernelModules = lib.mkIf config.hardware.enableAllHardware (
```suggestion
    boot.initrd.availableKernelModules = (
```

2024-12-12 09:13 UTC, jopejoe1 commented on nixos/modules/hardware/all-hardware.nix
> +    hardware.enableRedistributableFirmware = config.hardware.enableAllHardware;
```suggestion
    hardware.enableRedistributableFirmware = true;
```

2024-12-12 09:49 UTC, DavHau commented
@jopejoe1 Thanks, good catch. Fixed it!

2024-12-12 14:38 UTC, jopejoe1 approved these changes

2024-12-12 14:38 UTC, jopejoe1 commented on nixos/modules/profiles/all-hardware.nix
Maybe want to convert this into a warning.

2024-12-12 14:41 UTC, jopejoe1 commented on nixos/modules/hardware/all-hardware.nix
> +      ++ lib.optional platform.isx86 "vmw_balloon"
Note: Only place in the file that makes use of the `platform` alias for `pkgs.stdenv.hostPlatform`, the other ones just use it directly.

2024-12-13 05:10 UTC, DavHau commented on nixos/modules/profiles/all-hardware.nix
I lean towards not doing that, as this would make a lot of noise, while there is no real need to deprecate it.

2024-12-14 00:03 UTC, merged