Add pyspark
NixOS/nixpkgs pull request #36529
Opened 2018-03-08 15:23 UTC by shlevy

2018-03-08 15:35 UTC, FRidh requested changes

2018-03-08 15:35 UTC, FRidh commented on pkgs/development/python-modules/py4j/default.nix
> +  src = fetchurl {
fetchPypi with `extension = "zip"`;

2018-03-08 15:35 UTC, FRidh commented on pkgs/development/python-modules/py4j/default.nix
> +    license = licenses.bsd;
maintainer?

2018-03-08 15:35 UTC, FRidh commented on pkgs/development/python-modules/pyspark/default.nix
> +  src = fetchurl {
fetchPypi

2018-03-08 15:37 UTC, shlevy commented
@FRidh Sorry about this, I guess python2nix needs updating... Fix incoming.

2018-03-08 16:01 UTC, shlevy commented
@FRidh Fixed.

2018-03-17 12:29 UTC, FRidh approved these changes

2018-03-17 13:56 UTC, shlevy commented
@GrahamcOfBorg build pythonPackages.pyspark

2018-03-17 13:57 UTC, GrahamcOfBorg commented
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.36529&attempt_id=f4ad038a-8f82-42cd-9038-774ae3eceebc)

Attempted: pythonPackages.pyspark

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/pyspark: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/8hdxjv3m14jgdnawi5l0mz2h59qkk2g9-bash-4.4-p19/bin/bash"
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/sparkR: interpreter directive changed from "/bin/bash" to "/nix/store/8hdxjv3m14jgdnawi5l0mz2h59qkk2g9-bash-4.4-p19/bin/bash"
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/docker-image-tool.sh: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/8hdxjv3m14jgdnawi5l0mz2h59qkk2g9-bash-4.4-p19/bin/bash"
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-submit: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/8hdxjv3m14jgdnawi5l0mz2h59qkk2g9-bash-4.4-p19/bin/bash"
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/beeline: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/8hdxjv3m14jgdnawi5l0mz2h59qkk2g9-bash-4.4-p19/bin/bash"
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-class: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/8hdxjv3m14jgdnawi5l0mz2h59qkk2g9-bash-4.4-p19/bin/bash"
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/run-example: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/8hdxjv3m14jgdnawi5l0mz2h59qkk2g9-bash-4.4-p19/bin/bash"
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/find-spark-home: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/8hdxjv3m14jgdnawi5l0mz2h59qkk2g9-bash-4.4-p19/bin/bash"
wrapping `/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0/bin/find_spark_home.py'...
/nix/store/jhzpnwfln32x1alplnls4xx0vznpldiy-python2.7-pyspark-2.3.0
```
</p></details>

2018-03-17 13:58 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.36529&attempt_id=1f9d360e-9c2a-419d-938e-f75943f61ebf)

Attempted: pythonPackages.pyspark

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/pyspark: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/3gg2p6n4kv2f0lsxd41f5iz1ivkbzyzr-bash-4.4-p19/bin/bash"
/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/run-example: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/3gg2p6n4kv2f0lsxd41f5iz1ivkbzyzr-bash-4.4-p19/bin/bash"
/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-class: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/3gg2p6n4kv2f0lsxd41f5iz1ivkbzyzr-bash-4.4-p19/bin/bash"
/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-shell: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/3gg2p6n4kv2f0lsxd41f5iz1ivkbzyzr-bash-4.4-p19/bin/bash"
/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-sql: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/3gg2p6n4kv2f0lsxd41f5iz1ivkbzyzr-bash-4.4-p19/bin/bash"
/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-submit: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/3gg2p6n4kv2f0lsxd41f5iz1ivkbzyzr-bash-4.4-p19/bin/bash"
/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/sparkR: interpreter directive changed from "/bin/bash" to "/nix/store/3gg2p6n4kv2f0lsxd41f5iz1ivkbzyzr-bash-4.4-p19/bin/bash"
checking for references to /build in /nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0...
wrapping `/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0/bin/find_spark_home.py'...
/nix/store/slpqdah8k1sp06gnydymgknqn7i0pbm0-python2.7-pyspark-2.3.0
```
</p></details>

2018-03-17 14:11 UTC, merged

2018-03-17 17:20 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.36529&attempt_id=27a8115a-a650-4108-acdc-777471c8e170)

Attempted: pythonPackages.pyspark

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/beeline: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/q1g0rl8zfmz7r371fp5p42p4acmv297d-bash-4.4-p19/bin/bash"
/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-sql: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/q1g0rl8zfmz7r371fp5p42p4acmv297d-bash-4.4-p19/bin/bash"
/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/find-spark-home: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/q1g0rl8zfmz7r371fp5p42p4acmv297d-bash-4.4-p19/bin/bash"
/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-shell: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/q1g0rl8zfmz7r371fp5p42p4acmv297d-bash-4.4-p19/bin/bash"
/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/spark-submit: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/q1g0rl8zfmz7r371fp5p42p4acmv297d-bash-4.4-p19/bin/bash"
/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/sparkR: interpreter directive changed from "/bin/bash" to "/nix/store/q1g0rl8zfmz7r371fp5p42p4acmv297d-bash-4.4-p19/bin/bash"
/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0/lib/python2.7/site-packages/pyspark/bin/run-example: interpreter directive changed from "/usr/bin/env bash" to "/nix/store/q1g0rl8zfmz7r371fp5p42p4acmv297d-bash-4.4-p19/bin/bash"
checking for references to /build in /nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0...
wrapping `/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0/bin/find_spark_home.py'...
/nix/store/55j9ry57v71qjhv99bcrx61x4gf455ng-python2.7-pyspark-2.3.0
```
</p></details>