chirpstack-gateway-mesh: init at 4.0.0
NixOS/nixpkgs pull request #366030
Opened 2024-12-18 00:49 UTC by stv0g

ChirpStack Gateway Mesh is a software component that can turn a LoRa® gateway into a relay. This makes it possible to extend the LoRa coverage, without the need to connect each LoRa gateway to the internet.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2025-07-31 06:24 UTC, Iamanaws requested changes

2025-07-31 06:24 UTC, Iamanaws commented on pkgs/by-name/ch/chirpstack-gateway-mesh/package.nix
> +  version = "4.0.0";
update to 4.0.1

2025-07-31 06:24 UTC, Iamanaws commented on pkgs/by-name/ch/chirpstack-gateway-mesh/package.nix
> +    rev = "v${version}";
```suggestion
    tag = "v${version}";
```

2025-08-15 13:21 UTC, stv0g commented
@lamanaws I have addressed your comments and rebased the PR on a current Nixpkgs master branch.

2025-08-15 13:21 UTC, stv0g commented
I also verified and tested a build on aarch64-linux

2025-08-16 03:31 UTC, Iamanaws commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review-gha`](https://github.com/Defelo/nixpkgs-review-gha)

Command: `nixpkgs-review pr 366030`

Logs: https://github.com/Iamanaws/nixpkgs-review-gha/actions/runs/17003688902


---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>chirpstack-gateway-mesh</li>
  </ul>
</details>


---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>chirpstack-gateway-mesh</li>
  </ul>
</details>


---
### `x86_64-darwin` (sandbox = true)
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>chirpstack-gateway-mesh</li>
  </ul>
</details>


---
### `aarch64-darwin` (sandbox = true)
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>chirpstack-gateway-mesh</li>
  </ul>
</details>

2025-08-16 03:33 UTC, iamanaws approved these changes
Just update the PR title to match 4.0.1, and that's it

2025-08-16 06:49 UTC, stv0g commented
> Just update the PR title to match 4.0.1, and that's it

Done

2025-08-29 05:08 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/5811

2025-10-26 10:11 UTC, closed without merging