conjure-tor: init at 0-unstable-2024-12-22
NixOS/nixpkgs pull request #367417
Opened 2024-12-22 17:52 UTC by mksafavi

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-22 17:56 UTC, mksafavi commented
There's a name conflict with another package. I renamed this to conjure-tor. If you have any suggestions for the name let me know.

2024-12-22 18:02 UTC, PerchunPak requested changes
`conjure-tor` is fine

2024-12-22 18:02 UTC, PerchunPak commented on pkgs/by-name/co/conjure-tor/package.nix
> +  version = "0-unstable-2024-12-22";
```suggestion
  pname = "conjure-tor";
  version = "0-unstable-2024-11-11";
```

The date in unstable releases should be the date of commit, not today

2024-12-22 18:02 UTC, PerchunPak commented on pkgs/by-name/co/conjure-tor/package.nix
> +    description = "Conjure is a refraction networking system that routes traffic to endpoints in an ISP's unused IP address space";
```suggestion
    description = "Refraction networking system that routes traffic to endpoints in an ISP's unused IP address space";
```

2024-12-22 18:08 UTC, PerchunPak approved these changes
Exits with `retrying conjure registration, station is under high load`, assuming works

2024-12-22 18:10 UTC, PerchunPak commented
How about [`updateScript`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#automatic-package-updates)? (it is applied automatically to all python packages, but not go)

2024-12-22 18:13 UTC, mksafavi commented
> How about [`updateScript`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#automatic-package-updates)? (it is applied automatically to all python packages, but not go)

What should I set it to? Is `passthru.updateScript = nix-update-script { };` enough?

2024-12-22 18:14 UTC, PerchunPak commented
> > How about [`updateScript`](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#automatic-package-updates)? (it is applied automatically to all python packages, but not go)
> 
> What should I set it to? Is `passthru.updateScript = nix-update-script { };` enough?

Yes

2024-12-22 18:48 UTC, PerchunPak commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 367417`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>conjure-tor</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>conjure-tor</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>conjure-tor</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>conjure-tor</li>
  </ul>
</details>

2024-12-23 18:55 UTC, mksafavi commented
Hi @wegank 
Is there anything needed for this PR?

2024-12-23 21:30 UTC, PerchunPak approved these changes

2024-12-25 19:48 UTC, PerchunPak commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 367417`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>conjure-tor</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>conjure-tor</li>
  </ul>
</details>

---
### `x86_64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>conjure-tor</li>
  </ul>
</details>

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>conjure-tor</li>
  </ul>
</details>

2025-01-30 09:05 UTC, FliegendeWurst approved these changes

2025-01-30 09:05 UTC, merged