resilio-sync: 2.8.1 -> 3.0.1
NixOS/nixpkgs pull request #367595
Opened 2024-12-23 10:13 UTC by yesbox

https://help.resilio.com/hc/en-us/articles/31386579044755-Resilio-Sync-3-0-change-log

No more support for 32-bit architectures. Tested manually by using the service.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-24 02:23 UTC, rhoriguchi approved these changes
Works on `x86_64-linux` with and without ui and `aarch64-linux` without ui.

2025-01-11 22:08 UTC, FliegendeWurst requested changes
Builds on x64 Linux, did not test functionality.

Putting blocking review due to previous comment.

2025-01-12 20:49 UTC, SuperSandro2000 commented on pkgs/by-name/re/resilio-sync/package.nix
> +        sha256 = "sha256-WJi9KVGqI0oAaBaldcVGuQmyXuqaCFFm9VyI6PB4CkA=";
We should use hash here instead

2025-02-22 14:47 UTC, yesbox commented
Version 3.0.2 has been released since I had time to get back to this. This change now updates to it instead of 3.0.1.

I've yet to have a problem with 3.0.1 or 3.0.2 on x64. I cannot comment on aarch64.

@rhoriguchi Do you want to try again?

2025-02-22 23:58 UTC, rhoriguchi approved these changes
I'm not seeing any issues with this version. Thank you for updating.

2025-02-23 09:39 UTC, FliegendeWurst approved these changes

2025-02-23 09:40 UTC, merged