More string fixes
NixOS/nixpkgs pull request #367757
Opened 2024-12-23 22:03 UTC by piegamesde

Oh well. So turns out due to a silly mistake, my script previously only ran onto the `pkgs` subfolder. So here's the remaining fixes for the rest of Nixpkgs. Follow-up to #350296, #350774 and #365186.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-31 13:42 UTC, pbsds commented on nixos/modules/services/mail/dovecot.nix
> +  configContainsSetting = lines: term: (match "^[^#]*\\b${term}\\b.*=" lines) != null;
```
nix-repl> "^[^#]*\b${term}\b.*="
"^[^#]*bfoobarb.*="

nix-repl> "^[^#]*\\b${term}\\b.*="
"^[^#]*\\bfoobar\\b.*="
```

2024-12-31 14:02 UTC, pbsds commented on nixos/modules/hardware/video/nvidia.nix
> +  busIDType = lib.types.strMatching "([[:print:]]+[\\:\\@][0-9]{1,3}\\:[0-9]{1,2}\\:[0-9])?";
not a valid regex
```
nix-repl> "([[:print:]]+[\:\@][0-9]{1,3}\:[0-9]{1,2}\:[0-9])?"
"([[:print:]]+[:@][0-9]{1,3}:[0-9]{1,2}:[0-9])?"

nix-repl> "([[:print:]]+[\\:\\@][0-9]{1,3}\\:[0-9]{1,2}\\:[0-9])?"
"([[:print:]]+[\\:\\@][0-9]{1,3}\\:[0-9]{1,2}\\:[0-9])?"

nix-repl> builtins.match "([[:print:]]+[\\:\\@][0-9]{1,3}\\:[0-9]{1,2}\\:[0-9])?" ""
error:
       … while calling the 'match' builtin
         at «string»:1:1:
            1| builtins.match "([[:print:]]+[\\:\\@][0-9]{1,3}\\:[0-9]{1,2}\\:[0-9])?" ""
             | ^

       error: invalid regular expression '([[:print:]]+[\:\@][0-9]{1,3}\:[0-9]{1,2}\:[0-9])?'
```

2024-12-31 14:04 UTC, pbsds commented
@infinisil, i remember you onboarding someone new to help with `lib`, but i don't remember who. Please CC them :)

2024-12-31 14:07 UTC, pbsds commented on nixos/modules/services/web-apps/onlyoffice.nix
> +            "~ ^(\\/[\\d]+\\.[\\d]+\\.[\\d]+[\\.|-][\\d]+)?\\/(web-apps\\/apps\\/api\\/documents\\/api\\.js)$".extraConfig =
@SuperSandro2000  via https://github.com/NixOS/nixpkgs/pull/181258

2025-01-04 19:43 UTC, piegamesde commented on nixos/modules/services/mail/dovecot.nix
> +  configContainsSetting = lines: term: (match "^[^#]*\\b${term}\\b.*=" lines) != null;
@2xsaiko what's the intent of the regex here?

2025-01-04 23:48 UTC, 2xsaiko requested changes

2025-01-04 23:48 UTC, 2xsaiko commented on nixos/modules/services/mail/dovecot.nix
> +  configContainsSetting = lines: term: (match "^[^#]*${term}[[:blank:]]*=.*" lines) != null;
@piegamesde:
> @2xsaiko Nix does not know about `\b` (or any other escape sequence), what's the intent of the regex here?

I didn't write that, but I think this now almost does what is intended. It matches "xfoo =" for term="foo" though. I would write

```suggestion
  configContainsSetting = lines: term: (match "[[:blank:]]*${term}[[:blank:]]*=.*" lines) != null;
```

@RaitoBezarius what do you think? Looks like you wrote this originally.

Good to know it doesn't support these escapes.

2025-01-07 18:24 UTC, piegamesde commented on nixos/modules/services/mail/dovecot.nix
> +  configContainsSetting = lines: term: (match "^[^#]*${term}[[:blank:]]*=.*" lines) != null;
So my version more closely matches the original regex which has the same over-matching, but I'm unsure if it is intended like that or not. I read up on the dovecot configuration docs, still unclear.

2025-01-08 13:18 UTC, infinisil commented on nixos/modules/services/web-apps/onlyoffice.nix
> +            "~ ^(\\/[\\d]+\\.[\\d]+\\.[\\d]+[\\.|-][\\d]+)?\\/(web-apps\\/apps\\/api\\/documents\\/api\\.js)$".extraConfig =
Apparently that's how it is in the source, see `$(nix-build '<nixpkgs>' -A onlyoffice-documentserver)/etc/nginx/includes/ds-docservice.conf`:

```nginx
#disable caching for api.js
location ~ ^(\/[\d]+\.[\d]+\.[\d]+[\.|-][\d]+)?\/(web-apps\/apps\/api\/documents\/api\.js)$ {
  expires -1;
  # gzip_static on;
  alias  /var/www/onlyoffice/documentserver/$2;
}
```

2025-01-08 13:23 UTC, infinisil approved these changes
Should ideally hook up CI to check for future regressions, but this seems fine

2025-01-08 19:12 UTC, merged

2025-01-11 16:34 UTC, piegamesde commented
@infinisil Until there is a CI check (pretty please), I'll do a fixup run every release cycle before branch-off. The check I currently do for this is not complicated btw, just a handful of Lix patches and a shell script that runs the parser over all files.

Backport at #372975 btw.

2025-01-13 19:56 UTC, infinisil commented
Frankly this goes fairly directly against [automation over toil](https://nixos.org/values/#community-values-automation). The problem is not just that your time is used for toil, but also the reviewers time. So if you or anybody else could work on automation instead, that would be so much more worthwhile.

2025-01-13 22:05 UTC, pbsds commented
I think automating the migration is not possible. For example the uncertainty of `"\."` could mask the intention of the author. Should the period really be escaped or not? We uncovered multiple regexes that proved to be unsound due to this.

We need to remove all errors in the tree then enforce that no new ones are introduced with a CI check