spacefm: fix segfault by exporting shared-mime-info/share in XDG_DATA_DIRS
NixOS/nixpkgs pull request #36797
Opened 2018-03-11 12:27 UTC by nioncode

###### Motivation for this change
Fixes #31797.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-03-11 23:51 UTC, jtojnar requested changes

2018-03-11 23:51 UTC, jtojnar commented on pkgs/applications/misc/spacefm/default.nix
> +      wrapProgram $out/bin/spacefm \
`wrapGAppsHook` already wraps the executable, please use

https://github.com/NixOS/nixpkgs/blob/532bd714bac656e38c3ef5f6d447efb9ffd6792d/pkgs/applications/graphics/gthumb/default.nix#L26-L28

2018-03-12 08:27 UTC, nioncode commented
I'm now using `gappsWrapperArgs` as requested and rebased the branch and force pushed the changes. Is this the correct approach or do you like to merge the whole history usually to keep the reviews working?

2018-03-12 08:42 UTC, jtojnar commented
For larger pull requests, it is usually better to delay rebasing until before the merge; for smaller ones like this one, force pushing is fine and leads to less round trips.

2018-03-12 08:42 UTC, jtojnar approved these changes

2018-03-18 12:12 UTC, merged