ocamlPackages.odds: init at 1.2
NixOS/nixpkgs pull request #368180
Opened 2024-12-25 20:23 UTC by Denommus

https://github.com/raphael-proust/odds

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [X] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [X] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-25 23:00 UTC, steeleduncan requested changes

2024-12-25 23:00 UTC, steeleduncan commented on pkgs/development/ocaml-modules/odds/default.nix
> +    rev = version;
`tag = `

2024-12-26 01:29 UTC, Denommus commented
@steeleduncan comments addressed

2024-12-26 10:05 UTC, ulrikstrid commented on pkgs/development/ocaml-modules/odds/default.nix
> +  duneVersion = "3";
This is the default, please remove

2024-12-26 11:35 UTC, Denommus commented
@ulrikstrid done

2024-12-26 11:47 UTC, ulrikstrid approved these changes

2024-12-27 12:52 UTC, thiagokokada commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368180`

2024-12-27 12:53 UTC, thiagokokada commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368180`

2024-12-27 12:54 UTC, thiagokokada approved these changes

2024-12-27 12:54 UTC, merged

2024-12-31 09:31 UTC, vbgl reviewed
Can someone please fix this package?

2024-12-31 09:31 UTC, vbgl commented on pkgs/development/ocaml-modules/odds/default.nix
> +  minimalOcamlVersion = "5.0.0";
This is wrongly spelled.

2024-12-31 09:31 UTC, vbgl commented on pkgs/development/ocaml-modules/odds/default.nix
> +  ];
This must not be propagated.

2025-01-06 07:05 UTC, vbgl commented
Done in #371357.