{ecwolf,lzwolf}: fix build with gcc-14, cleanup
NixOS/nixpkgs pull request #368178
Opened 2024-12-25 20:07 UTC by xokdvium

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-26 16:10 UTC, Jayman2000 requested changes
This PR mostly looks good to me. I tried building `ecwolf` without the changes in this PR, and it failed. The changes in this commit fix that failure which is good. (I didn’t test `lzwolf`, though).

I only really have two critiques:

- “ecwolf: use finalAttrs” does more than just switch to using `finalAttrs`. It also switches from using `rev = <tag-name>;` to `rev = "refs/tags/<tag-name>;`.
- [`CONTRIBUTING.md` says:](https://github.com/NixOS/nixpkgs/blob/1557114798a3951db0794379f26b68a5fdf68b12/CONTRIBUTING.md#writing-good-commit-messages)

    > In addition to writing properly formatted commit messages, it's important to include relevant information so other developers can later understand *why* a change was made. While this information usually can be found by digging code, mailing list/Discourse archives, pull request discussions or upstream changes, it may require a lot of work.

    I think that the “fix build with gcc-14” commits are self-explanitory, and I think that the commit message for “ecwolf: don't use pname in fetchFromBitbucket” does a good job at explaining why the change was made. I think that the other commits should have longer commit messages that explain why the changes were made.

I created [a branch named `dev/fix-ecwolf-suggestions`](https://github.com/Jayman2000/nixpkgs-pr/tree/dev/fix-ecwolf-suggestions). In that branch, I split “ecwolf: use finalAttrs” into two separate commits, and expanded the commit messages that I felt were lacking. If you agree with my changes, then you can push the `dev/fix-ecwolf-suggestions` branch to your PR branch.

2024-12-26 16:39 UTC, xokdvium commented
Rebased and cherry-picked commits with the improved descriptions. Thanks for taking the time to fix them up!

2024-12-26 18:05 UTC, Jayman2000 approved these changes
Looks good to me. `ecwolf` works fine. I haven’t tested `lzwolf`.

2024-12-26 18:25 UTC, xokdvium commented
I've checked that `lzwolf` launches on `x86_64-linux`:

![image](https://github.com/user-attachments/assets/9310b873-f876-4b41-96cf-80eadd24bdac)

Though in the long run I think we should consider dropping `lzwolf`, as it seems abandoned: https://beta.wolf3d.net/engines/LZWolf.

> Unfortunately, LZWolf's development has been discontinued as of the 5th of March, 2023. The engine is still a fantastic source port for the building of mods, with a lot of cool features to take advantage of, but will not be following ECWolf to a 1.4 release.

Now it's pretty easy to get it working, but further breakages will be harder to fix and continuing to carry downstream patches is always a burden.

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368178`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>ecwolf</li>
    <li>lzwolf</li>
  </ul>
</details>

2024-12-27 21:37 UTC, keenanweaver commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368178`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>ecwolf</li>
    <li>lzwolf</li>
  </ul>
</details>

2024-12-27 21:40 UTC, keenanweaver approved these changes
[Before this PR](https://www.youtube.com/watch?v=WL_cFatMW7E)
[After this PR](https://www.youtube.com/watch?v=F6EfE4ok35g)

2025-01-01 23:28 UTC, merged