lipo-go: init at 0.9.3
NixOS/nixpkgs pull request #368367
Opened 2024-12-26 15:55 UTC by xiaoxiangmoe

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [x] `sandbox = true`
- [x] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-29 07:12 UTC, xiaoxiangmoe commented on pkgs/by-name/li/lipo-go/package.nix
> +    platforms = go.meta.platforms;
Removed now.
But I want to know why we should remove this line.

2024-12-29 12:42 UTC, ghost approved these changes

2025-01-04 22:27 UTC, GaetanLepage requested changes

2025-01-05 03:43 UTC, xiaoxiangmoe commented on pkgs/by-name/li/lipo-go/package.nix
> +    rev = "9d9d62f6d849922028a1aa4abde23fe29dc707ee";
I need rev for get `REVISION=${CI_COMMIT_SHORT_SHA}`

2025-01-05 09:23 UTC, xiaoxiangmoe commented on pkgs/by-name/li/lipo-go/package.nix
> +    rev = "9d9d62f6d849922028a1aa4abde23fe29dc707ee";
If I fake this value
Then the version will be wired.
For example:
```
1.2.3/
```

2025-01-05 10:55 UTC, xiaoxiangmoe commented on pkgs/by-name/li/lipo-go/package.nix
> +    rev = "9d9d62f6d849922028a1aa4abde23fe29dc707ee";
Ok, I'll change to this

2025-01-05 11:07 UTC, xiaoxiangmoe commented on pkgs/by-name/li/lipo-go/package.nix
> +    rev = "9d9d62f6d849922028a1aa4abde23fe29dc707ee";
Done

2025-01-05 11:37 UTC, xiaoxiangmoe commented on pkgs/by-name/li/lipo-go/package.nix
> +    # Remove the test case that is not compatible with nix-build
Thats a good idea.

But also I don't know what should I do If I have a script more than one line. Should I put comment out of script string?

2025-01-05 12:28 UTC, GaetanLepage approved these changes
LGTM thanks !

2025-01-05 12:42 UTC, merged