capypdf: init at 0.14.0
NixOS/nixpkgs pull request #368446
Opened 2024-12-27 00:22 UTC by jtojnar

Inkscape will start using it: https://nibblestew.blogspot.com/2024/12/capypdf-014-is-out.html

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2025-01-01 15:22 UTC, Sigmanificient requested changes

2025-01-01 15:22 UTC, Sigmanificient commented on pkgs/by-name/ca/capypdf/package.nix
> +    description = "A fully color managed PDF generation library";
```suggestion
    description = "Fully color managed PDF generation library";
```

2025-01-01 15:22 UTC, Sigmanificient commented on pkgs/by-name/ca/capypdf/package.nix
> +    homepage = "https://github.com/jpakkane/capypdf";
```suggestion
    inherit (finalAttrs.src.meta) homepage;
```

2025-01-01 19:49 UTC, jtojnar commented on pkgs/by-name/ca/capypdf/package.nix
> +    description = "A fully color managed PDF generation library";
Done, thanks.

2025-01-01 19:50 UTC, jtojnar commented on pkgs/by-name/ca/capypdf/package.nix
> +    homepage = "https://github.com/jpakkane/capypdf";
I prefer the former, as it allows opening the homepage directly from GitHub or text editor.

2025-01-05 17:22 UTC, ethancedwards8 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368446`

---
### `aarch64-darwin`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>capypdf</li>
    <li>capypdf.dev</li>
  </ul>
</details>

2025-01-05 19:32 UTC, merged