python312Packages.copykitten: init at 1.2.3
NixOS/nixpkgs pull request #368748
Opened 2024-12-28 07:40 UTC by Samasaur1

Added copykitten. Closes #355856

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [x] x86_64-darwin
  - [x] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2025-01-05 03:26 UTC, Sigmanificient requested changes

2025-01-05 03:26 UTC, Sigmanificient commented on pkgs/development/python-modules/copykitten/default.nix
> +    repo = pname;
```suggestion
    repo = "copykitten";
```
- #277994

2025-01-05 03:26 UTC, Sigmanificient commented on pkgs/development/python-modules/copykitten/default.nix
> +  ];
This probably should go within `dependencies`, can you also move it below `build-system`?

2025-01-05 03:26 UTC, Sigmanificient commented on pkgs/development/python-modules/copykitten/default.nix
> +  ];
If `doCheck` is set to false, `nativeCheckInputs` shouldn't be populated

2025-01-05 11:36 UTC, Samasaur1 commented on pkgs/development/python-modules/copykitten/default.nix
> +    repo = pname;
I also switched to using a literal string for `pythonImportsCheck`

2025-01-18 23:39 UTC, GaetanLepage approved these changes
LGTM

2025-01-18 23:47 UTC, merged