cockpit: 330 -> 331
NixOS/nixpkgs pull request #368886
Opened 2024-12-28 18:49 UTC by lucasew

- **cockpit: 330 -> 331**
- **tests/cockpit: each wait with its own waiter, treat /nonexistent case**

Basically, cockpit was having some FHS assuming issues. This PR bumps to the latest version and fixes them.

When merged, this should be backported because stable is also broken.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-28 18:50 UTC, lucasewd commented
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12528977197
**Extra args**: ``

2024-12-28 19:06 UTC, lucasewd commented
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow finished

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12528977197


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368886`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 1 package blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>cockpit</li>
  </ul>
</details>

2024-12-28 19:06 UTC, lucasewd commented
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow started

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12529066881
**Extra args**: `-p cockpit -p nixosTests.cockpit`

2024-12-28 19:11 UTC, lucasew commented
The new iteration is just nixfmt

2024-12-28 19:21 UTC, lucasewd commented
# [nixpkgs-reviewd](https://github.com/nixosbrasil/nixpkgs-reviewd) workflow finished

**Status and logs**: https://github.com/nixosbrasil/nixpkgs-reviewd/actions/runs/12529066881


## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 368886`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.cockpit</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>cockpit</li>
  </ul>
</details>

2024-12-29 16:12 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/cockpit-dashboard-management-interface-package-does-not-work-properly/57403/16

2024-12-29 20:28 UTC, GaetanLepage requested changes
Can you try adding `versionCheckHook` (see `typst/package.nix` for an example) ?

Also, for `meta`:
- remove `with lib;`,
- Add `changelog = "https://cockpit-project.org/blog/cockpit-${finalAttrs.version}.html";

I haven't looked at the module.

2024-12-29 22:13 UTC, lucasew commented on pkgs/by-name/co/cockpit/package.nix
> +    python3Packages.pytestCheckHook
Moved to nativeCheckInputs

2024-12-29 22:34 UTC, thiagokokada approved these changes

2024-12-29 22:43 UTC, GaetanLepage approved these changes
LGTM

2024-12-29 22:48 UTC, GaetanLepage approved these changes
I trust you on the nixos module aspect

2024-12-29 22:48 UTC, merged

2024-12-30 00:15 UTC, lucasew commented
Going to backport this as the stable version is also broken

2024-12-30 00:37 UTC, lucasew commented
Backport PR  https://github.com/NixOS/nixpkgs/pull/369266