Use raptor2 for Ardour
NixOS/nixpkgs pull request #369048
Opened 2024-12-29 09:26 UTC by korrat

Recently, the raptor library stopped building in nixpkgs (#368134). This is likely due to an incompatible function declaration brought to light by the recent switch to GCC14.

This means that ardour fails to build as well. However, based on [nightly CI builds](https://nightly.ardour.org/list.php#build_deps), ardour is no longer using raptor 1.4.21, but raptor 2.0.14. Therefore, this PR updates ardour to use raptor 2.0.16 in nixpkgs, fixing the build.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [x] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-29 10:34 UTC, wentasah commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369048`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ardour</li>
  </ul>
</details>

2024-12-29 10:34 UTC, wentasah approved these changes
Looks good. Thanks!

2024-12-29 12:40 UTC, SigmaSquadron requested changes
Looks good overall, but please rename the commit so that it follows the [Commit Conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions).

Something like this should work: `ardour: switch to librdf_raptor2`

2024-12-29 12:59 UTC, emilazy commented
It seems like Ardour and Sonic Visualiser are the only remaining references to the old version. Looking at the upstream build scripts for the latter, the latest version works with Raptor 2.

I take it Ardour 7 will continue to fail to compile? Can it be made to work with Raptor 2 as well, perhaps by backporting upstream commits from the Ardour 8 branch? Otherwise, perhaps 25.05 is the release to remove Ardour 7 and Raptor 1 in; cc @magnetophon due to the discussion in https://github.com/NixOS/nixpkgs/pull/336093.

2024-12-29 14:03 UTC, korrat commented
@SigmaSquadron, sorry, fixed.

@emilazy, based on [Fedora packages](https://packages.fedoraproject.org/pkgs/ardour7/ardour7/fedora-40.html), ardour7 should also be able to compile with raptor2.

2024-12-29 14:07 UTC, emilazy commented
Same PR (but a separate commit, `ardour_7: …`) is perfectly fine.

2024-12-29 14:30 UTC, korrat commented
I tried building ardour_7 with the same fix, but it seems something else is broken in the build as well.

2024-12-29 15:44 UTC, magnetophon commented
Sorry to be absent from the discussion.
I can't test due to https://github.com/Mic92/nixpkgs-review/issues/445

2024-12-30 16:09 UTC, khaneliman commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369048`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ardour</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>ardour</li>
  </ul>
</details>

2025-01-01 05:04 UTC, khaneliman approved these changes
> I tried building ardour_7 with the same fix, but it seems something else is broken in the build as well.

Apologies, I missed this comment and thought we were waiting on appending that to this PR. Going to merge so we can get this fixed, at least.

2025-01-01 05:06 UTC, merged