umu-launcher: init at 1.1.4
NixOS/nixpkgs pull request #369259
Opened 2024-12-29 23:33 UTC by diniamo

Closes #297662

This was a tough one, but my version still turned out miles better than what they have in their repo (do not look at it if you care about your eyesight).

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-29 23:35 UTC, diniamo commented
Oh yeah, the build fails because of #366359, I've been working on this with `doCheck = false` in the hatch package definition.

2025-01-04 00:16 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/makefile-installer-prefix.patch
> ++	$(PYTHON_INTERPRETER)  -m installer --prefix=$(DESTDIR) $(OBJDIR)/*.whl
Can this be upstreamed, or does it only make sense in nixpkgs?

2025-01-04 00:16 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/no-umu-version-json.patch
> ++	sed 's|##UMU_VERSION##|@version@|g' -i $(<).tmp
Could we upstream a change where `UMU_VERSION` can be specified as a make flag (defaulting to using `git describe`) so that we can just specify that flag instead of patching the makefile?

Of course, this is fine for now.

2025-01-04 06:56 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/makefile-installer-prefix.patch
> ++	$(PYTHON_INTERPRETER)  -m installer --prefix=$(DESTDIR) $(OBJDIR)/*.whl
Probably not upstreamed, as it changes the behavior significantly, and I also don't want to mess with python build tooling more than I have to; but if someone has a better solution, then I can change it.

2025-01-04 06:56 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/no-umu-version-json.patch
> ++	sed 's|##UMU_VERSION##|@version@|g' -i $(<).tmp
If they accept the PR, then yes, but I won't be the one to do it.

2025-01-04 06:56 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +      "SHELL_INTERPRETER=${lib.getExe bash}"
I'm actually _not_ providing python in `nativeBuildInputs`. And this is generally not the case either, because absolute store paths are preferred where possible.

2025-01-04 06:56 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  '';
What? They're make flags. I used the makeFlagsArray instead of the makeFlags attribute because one of the flags requires the `out` environment variable.

2025-01-04 06:56 UTC, diniamo commented on pkgs/by-name/um/umu-launcher/package.nix
> +  pname = "umu-run";
Not in the scope of those PR. Changing basic builders probably also has a convoluted process so I don't think I will bother.

2025-01-06 00:53 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  '';
> because one of the flags requires the out environment variable.

That is what [`placeholder`](https://noogle.dev/f/builtins/placeholder) is for.

```nix
"DESTDIR=${placeholder "out"}"
```

2025-01-06 07:51 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  '';
I know, but I don't like placeholder.

2025-01-07 19:27 UTC, beh-10257 commented
> do not look at it if you care about your eyesight

instead of saying this type of stuff why don't you tell me what are your complaints and actually make an improvement

2025-01-07 19:40 UTC, diniamo commented
Sorry. The improvement is this package, since I saw more value in upstreaming a proper package to nixpkgs compared to fixing the problems in the flake.

2025-01-07 19:43 UTC, diniamo commented
On another note, @MattSturgeon please mark the threads as resolved if they are.

Also, should I add you and @beh-10257 as maintainers to the package (assuming you're already in the maintainers list)?

2025-01-07 19:45 UTC, beh-10257 commented
the flake is always gonna be more up to date so there is value in that
yes add me to the maintainers list
can you list the improvements so I can make the flake better like I'm trying to make things better here so cooporate

2025-01-07 19:50 UTC, MattSturgeon commented
> On another note, @MattSturgeon please mark the threads as resolved if they are.

I don't have permission to do that. I think as PR author you can? Otherwise someone with write-access must do it.

2025-01-07 19:51 UTC, diniamo commented
Huh? You should be able to resolve your own reviews. Well in that case, do you want to add anything else or can I resolve them?

2025-01-07 20:38 UTC, MattSturgeon commented
> Also, should I add you and \@beh-10257 as maintainers

Sorry I missed that question. Feel free to add me 👍

2025-01-11 17:08 UTC, LovingMelody commented
Please add me to the maintainers list as well (fuzen)

2025-01-11 18:03 UTC, diniamo commented
Added the 2 of you, but I couldn't find @beh-10257

2025-01-14 22:15 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher/package.nix
> +  pname = "umu-run";
`executableName` is now merged

2025-01-17 05:00 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher/package.nix
> +{ buildFHSEnv, umu-launcher-unwrapped }:
To make it easier for end-users to add extra packages to the FHS environment by overriding.

This could be done in a follow-up PR if preferred

2025-01-17 05:06 UTC, diniamo commented on pkgs/by-name/um/umu-launcher/package.nix
> +{ buildFHSEnv, umu-launcher-unwrapped }:
Yes I what the code does, but in what scenario would that be useful

I assume heroic launcher also supports native games, in which case it would make sense, but as far as I know, umu is for windows games only

2025-01-17 05:08 UTC, diniamo commented
Fixed formatting

2025-01-17 05:12 UTC, LovingMelody commented on pkgs/by-name/um/umu-launcher/package.nix
> +{ buildFHSEnv, umu-launcher-unwrapped }:
Needed for passing graphics and [fixing a cursor issue](https://github.com/Open-Wine-Components/umu-launcher/issues/323). Graphics is needed for dxvk-nvapi to work

https://github.com/NixOS/nixpkgs/blob/e24b4c09e963677b1beea49d411cd315a024ad3a/nixos/modules/programs/steam.nix#L51-L57

2025-01-17 11:59 UTC, MattSturgeon reviewed
> Oh yeah, the build fails because of #366359, I've been working on this with `doCheck = false` in hatch's package definition.

The fix (#371743) is currently in staging-next. Not sure how long until that'll be merged into master.

2025-01-17 11:59 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/no-umu-version-json.patch
> ++RELEASEDIR := $(PROJECT)-@version@
This patch could be avoided by overriding `RELEASEDIR` explicitly in `makeFlags`.

If it matters, we know `$(PROJECT)` should always be `umu-launcher`. But I think for our purposes `RELEASEDIR` could be any string?

2025-01-17 11:59 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    ./makefile-installer-prefix.patch
Could you add a comment to explain why this patch is needed? And/or a TODO/FIXME if you think there's a better approach?

(personally, I don't really understand why we need `--prefix` instead of `--destdir` here)

2025-01-17 11:59 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  # The Makefile variables are a big mess, but this combination (and the patches) more or less do what we want
Nit: could we avoid vague negativity in comments? It could be helpful to list issues we have with the upstream variables, but I think this comment as-is may be counter-productive.

2025-01-17 11:59 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  '';
I know we touched on this before, but my preference would be to set this via `makeFlags` instead of having a `preBuild` script.

I think this would make the package easier to override. Probably not a big deal, but it feels cleaner.

This could be done by _either_
- setting `DESTDIR` to some local path, then _later_ during the `installPhase` moving the files to `$out`,
- _or_ by setting `DESTDIR=${placeholder "out"}`.

2025-01-17 11:59 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher/package.nix
> +  runScript = "${umu-launcher-unwrapped}/bin/umu-run";
```suggestion
  runScript = lib.getExe umu-launcher-unwrapped;
```

2025-01-17 11:59 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher/package.nix
> +  executableName = "umu-run";
IDK if this is good practice, but this could be set as:
```suggestion
  executableName = umu-launcher-unwrapped.meta.mainProgram;
```

2025-01-17 12:09 UTC, MattSturgeon commented
> > > Also, should I add you and @beh-10257 as maintainers to the package (assuming you're already in the maintainers list)?
> >
> > yes add me to the maintainers list
>
> Added the 2 of you, but I couldn't find @beh-10257

It seems they aren't in the list. It'd be great to have them, but that'll have to do that themselves in a follow up PR.

@beh-10257 see the relevant documentation:
- [How to become a maintainer](https://github.com/NixOS/nixpkgs/blob/master/maintainers/README.md#how-to-become-a-maintainer)
- comments at the top of [`maintainer-list.nix`](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix)
- [Commit conventions](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#commit-conventions)

2025-01-18 05:14 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/no-umu-version-json.patch
> ++	sed 's|##UMU_VERSION##|@version@|g' -i $(<).tmp
Pointless, the patch will simply fail when updating, and the person updating the package can just remove it

2025-01-18 05:28 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  '';
It would be by no means more easily overridable. The same way you would override `makeFlags`, you can override `preBuild` and change it there.

2025-01-18 05:32 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    ./makefile-installer-prefix.patch
Because it doesn't work otherwise, simple as

2025-01-18 05:43 UTC, diniamo commented on pkgs/by-name/um/umu-launcher/package.nix
> +{ buildFHSEnv, umu-launcher-unwrapped }:
I don't know, I feel like these make more sense to be done via overrides.

2025-01-18 05:44 UTC, LovingMelody commented on pkgs/by-name/um/umu-launcher-unwrapped/makefile-installer-prefix.patch
> ++	$(PYTHON_INTERPRETER)  -m installer --prefix=$(DESTDIR) $(OBJDIR)/*.whl
Believe this is for Open-Wine-Components/umu-launcher#296 ? We fix this upstream with a patch several dependencies are vendored

2025-01-18 08:55 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  '';
The difference is `makeFlags` can be manipulated as a nix value, while `makeFlagsArray` must be manipulated using bash.

2025-01-18 09:15 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    ./makefile-installer-prefix.patch
Reading up a little on `prefix` and `destdir`, my interpretation is:
- `prefix` is where the package will be installed and ran from. On a FHS system this might be `/usr` or `/usr/local`, for us this is `$out`
- `DESTDIR` should be where the files are installed to (e.g. a chroot, temp build dir, archive root, etc). This is a packaging detail.
- The actual path where make writes files should be `DESTDIR/prefix/files`
- The actual path where the app is run from should be `prefix/files`

Are we patching this because the upstream package is mishandling DESTDIR/prefix, perhaps treating DESTDIR as if it is a prefix?

> Because it doesn't work otherwise, simple as

I don't think that adds much clarity.

> HACK: I didn't look too far into the Python installer, but I couldn't find a way to get a proper output directory structure without a patch

This does at least draw attention to the issue and clarify that we're unsure of the best approach, thanks for adding the comments :slightly_smiling_face:

2025-01-18 15:39 UTC, khaneliman commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    ./makefile-installer-prefix.patch
> Because it doesn't work otherwise, simple as

That's not helpful to anyone who comes by the code to further maintain the derivation. When you contribute to a large scale repository, you need to add comments and commit messages that give context to the decisions made to aid in maintaining it.

2025-01-18 15:49 UTC, khaneliman commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  '';
> It would be by no means more easily overridable. The same way you would override `makeFlags`, you can override `preBuild` and change it there.

It's objectively easier to override when you actually use the nix language instead of bash.

2025-01-18 16:39 UTC, diniamo commented
Sigh... that should be fine for the remaining reviews.

I'm not willing to add the extra* stuff however, unless another another committer wants them, as I really don't think they make sense, when they are only required for workarounds (that can also just as easily be done with overrideAttrs).

2025-01-18 19:05 UTC, NullCub3 commented on pkgs/by-name/um/umu-launcher/package.nix
> +{ buildFHSEnv, umu-launcher-unwrapped }:
I’m pretty new to nixpkgs and all but I’m going to second @LovingMelody on this one, I think adding the options to enable easier overrides would be a good thing, particularly since I suspect that will be something done often as shown with steam there. As mentioned though having it be in a separate PR is fine I think.

2025-01-18 19:09 UTC, NullCub3 commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +  '';
Also going to third this, it’s not really that it *can’t* be done with the regular overrides but using the actual nix object makes it a lot easier to do those overrides which I think is a good thing in general. I mean, why do we use nix in the first place after all?

2025-01-19 04:43 UTC, MattSturgeon requested changes

2025-01-19 04:45 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher/package.nix
> +{ buildFHSEnv, umu-launcher-unwrapped }:
(resolved)

2025-01-19 05:05 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    ./makefile-installer-prefix.patch
I feel like that makes things more ambiguous, since, I assume, it relies on flags that are set by the builder. It's slightly better though, so I'll more or less apply it.

2025-01-19 05:09 UTC, diniamo commented
@MattSturgeon does that look ok?

2025-01-19 05:16 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    ./makefile-installer-prefix.patch
> I assume, it relies on flags that are set by the builder.

It relies on the configure script, which the builder calls with `--prefix=$out` resulting in the following makefile:

```make
# Generated by: ./configure.sh --prefix=/nix/store/gy10mqspzr7fcymi573iij6d8jg3r6ws-python3.12-umu-launcher-unwrapped-1.1.4

PREFIX          := /nix/store/gy10mqspzr7fcymi573iij6d8jg3r6ws-python3.12-umu-launcher-unwrapped-1.1.4

include Makefile.in
```

2025-01-19 05:18 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    # if their respective variables are set.
```suggestion
    # See https://github.com/Open-Wine-Components/umu-launcher/pull/343
```

I've opened an upstream PR, so let's link to it :upside_down_face:

2025-01-19 05:21 UTC, diniamo commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    ./makefile-installer-prefix.patch
Yeah, not obvious, but should be fine I guess

2025-01-19 05:53 UTC, MattSturgeon commented on pkgs/by-name/um/umu-launcher-unwrapped/package.nix
> +    # if their respective variables are set.
```diff
diff --git a/pkgs/by-name/um/umu-launcher-unwrapped/makefile-installer-prefix.patch b/pkgs/by-name/um/umu-launcher-unwrapped/makefile-installer-prefix.patch
deleted file mode 100644
index 890d6537e33c..000000000000
--- a/pkgs/by-name/um/umu-launcher-unwrapped/makefile-installer-prefix.patch
+++ /dev/null
@@ -1,13 +0,0 @@
-diff --git a/Makefile.in b/Makefile.in
-index b82053d..3e4379e 100644
---- a/Makefile.in
-+++ b/Makefile.in
-@@ -90,7 +90,7 @@ umu-dist: $(OBJDIR)/.build-umu-dist
- umu-dist-install: umu-dist
- 	$(info :: Installing umu )
- 	install -d $(DESTDIR)$(PYTHONDIR)/$(INSTALLDIR)
--	$(PYTHON_INTERPRETER)  -m installer --destdir=$(DESTDIR) $(OBJDIR)/*.whl
-+	$(PYTHON_INTERPRETER) -m installer --prefix=$(PREFIX) $(OBJDIR)/*.whl
- 
- ifeq ($(FLATPAK), xtrue)
- umu-install: version-install umu-dist-install
diff --git a/pkgs/by-name/um/umu-launcher-unwrapped/package.nix b/pkgs/by-name/um/umu-launcher-unwrapped/package.nix
index 357ef7a5d806..1f97d0c31580 100644
--- a/pkgs/by-name/um/umu-launcher-unwrapped/package.nix
+++ b/pkgs/by-name/um/umu-launcher-unwrapped/package.nix
@@ -1,6 +1,7 @@
 {
   python3Packages,
   fetchFromGitHub,
+  fetchpatch2,
   lib,
   bash,
   hatch,
@@ -22,10 +23,12 @@ python3Packages.buildPythonPackage rec {
     # This should fail, and be removed for releases after 1.1.4,
     # see https://github.com/Open-Wine-Components/umu-launcher/pull/289
     (replaceVars ./no-umu-version-json.patch { inherit version; })
-    # Patch the python installer call to use --prefix instead of --destdir
-    # Ideally, a change should be upstreamed, that adds both arguments
-    # if their respective variables are set.
-    ./makefile-installer-prefix.patch
+    # Patch the python installer call to support PREFIX
+    # See https://github.com/Open-Wine-Components/umu-launcher/pull/343
+    (fetchpatch2 {
+      url = "https://github.com/Open-Wine-Components/umu-launcher/pull/343.diff";
+      hash = "sha256-+h0ao2WUVUUR/AHEtGj5IAIUVivfAc+asnr0632hN74=";
+    })
   ];
 
   nativeBuildInputs = [
```

2025-01-19 09:04 UTC, MattSturgeon commented
> > Oh yeah, the build fails because of #366359, I've been working on this with `doCheck = false` in hatch's package definition.
> 
> The fix (#371743) is currently in staging-next. Not sure how long until that'll be merged into master.

#371743 has finally made it to master :tada:

2025-01-19 15:13 UTC, MattSturgeon approved these changes
Installed & tested locally, seems to be working.

Thanks for your efforts on this!

2025-01-19 15:15 UTC, MattSturgeon commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369259`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>umu-launcher</li>
    <li>umu-launcher-unwrapped</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:x: 2 packages failed to build:</summary>
  <ul>
    <li>umu-launcher</li>
    <li>umu-launcher-unwrapped</li>
  </ul>
</details>

2025-01-19 15:56 UTC, khaneliman commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369259`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>umu-launcher</li>
    <li>umu-launcher-unwrapped</li>
  </ul>
</details>

---
### `aarch64-linux`
<details>
  <summary>:white_check_mark: 2 packages built:</summary>
  <ul>
    <li>umu-launcher</li>
    <li>umu-launcher-unwrapped</li>
  </ul>
</details>

2025-01-19 15:57 UTC, khaneliman approved these changes

2025-01-19 15:58 UTC, merged

2025-01-19 16:20 UTC, diniamo commented
Thanks