anytype: 0.43.8 -> 0.44.0; build from source
NixOS/nixpkgs pull request #369346
Opened 2024-12-30 10:20 UTC by autrimpo

Upstream has no aarch64-linux builds :/

Either supersedes or follows #366778. Personally, I'd prefer rebasing after that PR is merged so that the packaging changes are isolated. I tried splitting the rewrite and update and packaging `0.43.8` from source, but `anytype-heart` at `0.37.4` uses go 1.23 iterators but `go.mod` declares they use 1.22, so that'd need some extra patching and is probably not worth the effort.

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [x] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [x] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-30 14:23 UTC, Adda0 commented
Hey. I thought that, since Anytype is a proprietary application, the build will not be cached by Hydra, right? That would mean that we would force every user to compile the entirety of Anytype themselves each update. If that is the case, I am not sure if the source Anytype version should entirely replace the existing binary package. Maybe create a new package, something like `anytype` and `anytype-bin`, then?

2025-01-03 11:52 UTC, autrimpo commented
That's a good point. I think for nixpkgs, packages built from source are preferred to consuming upstream builds, except in cases where it is very difficult or time consuming. In this case, the build doesn't take very long, however it pulls in both Rust and Go toolchains, which is a bit unfortunate.

I originally copied the license from the existing package, but reading through the [text in the repository](https://github.com/anyproto/anytype-ts/blob/0d6042fde4a159f43d190a55a3e5e85b79cfc7f9/LICENSE.md), it seems to me that it would fall under nixpkgs' `unfreeRedistributable`, in which case we can cache it just fine.

2025-01-17 19:47 UTC, Adda0 commented
IANAL. I have read through the Anytype licence again and I agree with you. Redistribution such as this is allowed. And therefore we should be OK with using unfreeRedistributable. Anytype gave explicit permission to redistribute Anytype as Flatpak (https://github.com/anyproto/anytype-ts/issues/74#issuecomment-2354593310), even marked our community-maintained Flatpak distribution as official. Therefore, there should be no issues caching the Anytype build in Hydra.

2025-01-17 20:31 UTC, Adda0 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369346`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>anytype</li>
  </ul>
</details>

##### Reviewed points

- [x] package path fits guidelines
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package builds on x86_64-linux
- [x] executables tested on x86_64-linux
- [x] `meta.description` is set and fits guidelines
- [x] `meta.license` fits upstream license
- [x] `meta.platforms` is set
- [x] `meta.maintainers` is set
- [x] `meta.mainProgram` is set, if applicable.
- [x] build time only dependencies are declared in `nativeBuildInputs`
- [x] source is fetched using the appropriate function
- [x] the list of `phases` is not overridden
- [x] when a phase (like `installPhase`) is overridden it starts with `runHook preInstall` and ends with `runHook postInstall`.
- [x] patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed
- [x] patches that are remotely available are fetched rather than vendored

##### Possible improvements

##### Comments

2025-01-17 20:42 UTC, Adda0 commented on pkgs/by-name/an/anytype/tantivy-go/default.nix
> +    repo = pname;
Do not specify repo name by the package name

It is considered an antipattern, AFAIK.
```suggestion
    repo = "tantivy-go";
```

2025-01-17 20:42 UTC, Adda0 commented on pkgs/by-name/an/anytype/package.nix
> +      ];
Note: It is a valid warning, but I think given the scope of Anytype, that it is acceptable in this case. 
```
Anytype.desktop> /nix/store/m29w56wv1bawarmqd6c1zigwpa7k8l7d-Anytype.desktop/share/applications/Anytype.desktop:
hint: value "Utility;Office;Calendar;ProjectManagement" for key "Categories" in group "Desktop Entry" contains more than one main category;
application might appear more than once in the application menu
```

2025-01-17 20:42 UTC, Adda0 commented on pkgs/by-name/an/anytype/anytype-heart/default.nix
> +    repo = pname;
Do not specify repo name by the package name

It is considered an antipattern, AFAIK.
```suggestion
    repo = "anytype-heart";
```

2025-01-17 20:42 UTC, Adda0 commented on pkgs/by-name/an/anytype/anytype-heart/default.nix
> +  meta = with lib; {
Using `with lib;` is considered an antipattern, AFAIK.

2025-01-17 20:42 UTC, Adda0 commented on pkgs/by-name/an/anytype/tantivy-go/default.nix
> +  meta = with lib; {
Using `with lib;` is considered an antipattern, AFAIK.

2025-01-17 20:42 UTC, Adda0 commented on pkgs/by-name/an/anytype/package.nix
>    meta = with lib; {
Using `with lib;` is considered an antipattern, AFAIK.

2025-01-19 07:25 UTC, Adda0 commented
#366778 has been merged. I also added an update script to the Anytype GUI package. Since the additional packages are taken from GitHub, we should be able to add those to all of them.

2025-01-19 07:32 UTC, Adda0 commented on pkgs/by-name/an/anytype/package.nix
> +    sha256 = "sha256-a2ZnTEAFzzTb+lxtQkC6QLG5SP1+gDSjI9dqUNZWfCg=";
Can we use `tag` and `hash` here since we are using the tag version releases?
```suggestion
    tag = "v${version}";
    hash = "sha256-a2ZnTEAFzzTb+lxtQkC6QLG5SP1+gDSjI9dqUNZWfCg=";
```

2025-01-19 07:32 UTC, Adda0 commented on pkgs/by-name/an/anytype/anytype-heart/default.nix
> +    sha256 = "sha256-0MRtzPSUxbCBJQLJbHsdEpf6GEFoS4ud1S6j9GZWzAE=";
Ditto.

2025-01-19 07:32 UTC, Adda0 commented on pkgs/by-name/an/anytype/tantivy-go/default.nix
> +    hash = "sha256-IlGtyTjOAvmrbgmvy4NelTOgOWopxNta3INq2QcMEqY=";
Ditto.

2025-02-03 17:31 UTC, autrimpo commented on pkgs/by-name/an/anytype/package.nix
> +      ];
These are taken from the [upstream entry](https://github.com/anyproto/anytype-ts/blob/e65998ee87875a70f3ec4e6c17ed984cc6870964/package.json#L706).

2025-02-03 17:32 UTC, autrimpo commented
Thank you for the review! I've rebased on top of master and addressed your comments.

2025-02-06 17:15 UTC, hexadecimalDinosaur commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369346`

---
### `x86_64-linux`
<details>
  <summary>:x: 1 package failed to build:</summary>
  <ul>
    <li>anytype</li>
  </ul>
</details>

2025-02-06 17:39 UTC, hexadecimalDinosaur commented
![image](https://github.com/user-attachments/assets/71e71867-d17b-4672-aa49-5ddb9b63b0f6)
that's odd...

2025-02-06 17:42 UTC, hexadecimalDinosaur requested changes

2025-02-06 17:42 UTC, hexadecimalDinosaur commented on pkgs/by-name/an/anytype/tantivy-go/default.nix
> +  cargoHash = "sha256-2fprQHpepF6n+aovq3U4JQue7xmTDUZMnzDLEgc7ock=";
might have a cargoHash mismatch

2025-02-06 18:14 UTC, autrimpo commented on pkgs/by-name/an/anytype/tantivy-go/default.nix
> +  cargoHash = "sha256-2fprQHpepF6n+aovq3U4JQue7xmTDUZMnzDLEgc7ock=";
I think what's happening is the problem described in #377996 and other similar recent PRs. I've enabled `useFetchCargoVendor` which seems to be the recommended way to solve this.

2025-02-07 04:41 UTC, hexadecimalDinosaur commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369346`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>anytype</li>
  </ul>
</details>

2025-02-07 04:43 UTC, hexadecimalDinosaur approved these changes

2025-02-07 06:44 UTC, Adda0 commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369346`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>anytype</li>
  </ul>
</details>

### Reviewed points
<details>
  <summary>:white_check_mark: Correct: 25 | :grey_question: Not reviewed: 0 | :red_circle: Needs changes: 0</summary>

  - [x] All package paths [fit the guidelines](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#file-naming-and-organisation) (e.g., `pkgs/by-name/so/some-package/package.nix` for top-level packages).
  - [x] Package name fits guidelines.
  - [x] Package version fits [guidelines](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#versioning).
  - [x] The packages sources are fetched using the appropriate functions (e.g., packages from GitHub should use `fetchFromGitHub`).
  - [x] The package sources use `mirror://` URLs when available.
  - [x] `tag` is used instead of `rev` for tag versions.
  - [ ] :red_circle: `hash` is used instead of `sha256` for hashes.
  - [x] Build time only dependencies are declared in `nativeBuildInputs` or its equivalent in the used builder.
  - [x] The list of `phases` is not overridden.
  - [x] When a phase (like `installPhase`) is overridden, it starts with `runHook preInstall` and ends with `runHook postInstall`.
  - [x] Patches have a comment describing either the upstream URL or a reason why the patch wasn't upstreamed.
  - [x] Patches that are remotely available are fetched rather than vendored.
  - [x] Package builds on x86_64-linux.
  - [x] Executables tested on x86_64-linux.
  - [x] All the meta fields [fit the guidelines](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#meta-attributes) and contain the correct information:
    - [x] `meta.description` is set and fits guidelines.
	  - Description should not contain complete sentences and should consist of phrases that fill the blank in " is a/an/the ____" (starting with a capital letter).
    - [x] `meta.license` fits upstream license.
    - [x] `meta.platforms` should be set (or the package will not get binary substitutes).
    - [x] Maintainers in `meta.maintainers` must be set.
      - This can be the package submitter or a community member that accepts taking up maintainership of the package.
    - [x] The `meta.mainProgram` must be set if a main executable exists.
  - [x] Whatever is needed is brought into scope instead of using top-level pkgs to make it easier to override.
  - [x] General `with lib;` is not used.
  - [x] If possible, update script is provided.
  - [x] If possible, tests are provided.
  - [x] The code contains no typos, and all typos have been reported.

</details>

### Possible improvements

### Comments

Looks good to me. Compiles, runs and works as expected.

2025-02-07 06:45 UTC, Adda0 commented on pkgs/by-name/an/anytype/package.nix
> +    sha256 = "sha256-evSB0ohHm++tZiazXRMR4vj34IfW3HIkfZ2gwsi/2dk=";
We could use `hash` here instead of `sha256`.
```suggestion
    hash = "sha256-evSB0ohHm++tZiazXRMR4vj34IfW3HIkfZ2gwsi/2dk=";
```

2025-02-07 16:50 UTC, Adda0 approved these changes

2025-02-07 21:33 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/2237

2025-02-11 19:36 UTC, minijackson approved these changes
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369346`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>anytype</li>
  </ul>
</details>

2025-02-11 19:37 UTC, merged

2025-03-10 23:11 UTC, SuperSandro2000 commented on pkgs/by-name/an/anytype/anytype-heart/default.nix
> +    .${stdenv.hostPlatform.system};
This is missing an or throw otherwise we get a syntax error on other platforms.

2025-03-15 15:19 UTC, Adda0 commented on pkgs/by-name/an/anytype/anytype-heart/default.nix
> +    .${stdenv.hostPlatform.system};
That is a good point that we missed. We should fix this.

2025-03-15 16:12 UTC, Adda0 commented on pkgs/by-name/an/anytype/anytype-heart/default.nix
> +    .${stdenv.hostPlatform.system};
Fixed in https://github.com/NixOS/nixpkgs/pull/390170.