k2pdfopt: disable tesseract support
NixOS/nixpkgs pull request #369368
Opened 2024-12-30 11:45 UTC by PatrickDaG

- **k2pdfopt: disable tesseract-support**
fixes: #368349

Turns out k2pdfopt is quite broken. I've tried to get tesseract to work, but couldn't figure it out. This is now in line
with arch and debian, both of which also disable support for it.
Doesn't inspire confidence that no ones able to get the compile to work, but the precompiled binaries work.
Debian contains another 9 patches for various things, most of which im not sure if we need or not, so I've excluded them for
now.

## Things done

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2025-01-15 18:08 UTC, mschwaig requested changes
Thanks for fixing the issue that I ran into!

Your first commit (48153930b86ccd37b0b31fa6002ace688d94c772) looks good.

You should not comment out all of that code in your second commit.
I cleaned that up a bit at https://github.com/NixOS/nixpkgs/commit/5fde3e12446853966124d79b42e75e0d5f01caf2, which replaces your second commit.

Feel free to just cherry-pick that commit or make the changes yourself.

I also think the following is better than having two independent flags, like in your second commit, assuming `tesseract` needs `leptonica`, but I'd be happy to here other opinions on that.

```diff
@@ -225,10 +227,8 @@ stdenv.mkDerivation rec {
     ++ lib.optional enableMuPDF mupdf_modded
     ++ lib.optional enableDJVU djvulibre
     ++ lib.optional enableGOCR gocr
-    ++ lib.optionals enableTesseract [
-      leptonica_modded
-      tesseract_modded
-    ];
+    ++ lib.optional enableTesseract tesseract_modded
+    ++ lib.optional (enableLeptonica || enableTesseract) leptonica_modded;

   dontUseCmakeBuildDir = true;
  ```

2025-01-16 20:36 UTC, mschwaig requested changes
Functionally, this looks good to me. I have tested it with `leptonica` enabled for the first review, and with `leptonica` disabled now, so either way is fine as long as it agrees with the commit message.

2025-01-16 20:36 UTC, mschwaig commented on pkgs/by-name/k2/k2pdfopt/package.nix
> +  enableLeptonica ? false,
Does this mean `leptonica` should actually stay disabled instead, or is this a typo?

I'm asking, because I don't know anything about those dependencies.

Also the commit message still says that we're re-enabling it.

2025-01-16 20:36 UTC, mschwaig commented on pkgs/by-name/k2/k2pdfopt/package.nix
> +  enableGOCR ? false, # Disabled by default due to crashes
Thanks, I get that comment now.

2025-01-16 21:01 UTC, PatrickDaG commented on pkgs/by-name/k2/k2pdfopt/package.nix
> +  enableGOCR ? false, # Disabled by default due to crashes
Yeah. The package has a few things that don't work right.

2025-01-17 00:17 UTC, mschwaig approved these changes
Great! LGTM

2025-01-29 21:15 UTC, mschwaig commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369368 --checkout commit`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>k2pdfopt</li>
  </ul>
</details>

---

This report looks good. Somehow without the `--checkout commit`, I cannot build `mupdf` locally, but hat seems unrelated.
`mupdf` by itself builds fine on `master`, as well as in hydra: https://hydra.nixos.org/build/285863431

2025-05-14 11:23 UTC, mschwaig commented
This still looks good. I just re-tested the fix, it still works. LGTM

I will try to find some committers to review.

## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369368 --checkout commit`

---
### `x86_64-linux`
I just re-tested this, this is still a valid fix, 

<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>k2pdfopt</li>
  </ul>
</details>

2025-05-14 13:15 UTC, mschwaig approved these changes

2025-05-14 13:59 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/2375

2025-05-15 13:35 UTC, merged