rasdaemon: 0.8.0 -> 0.8.2
NixOS/nixpkgs pull request #369375
Opened 2024-12-30 12:22 UTC by matdibu

Update rasdaemon from 0.8.0 to 0.8.2

https://github.com/mchehab/rasdaemon/blob/v0.8.2/ChangeLog

## Things done

- update to 0.8.2
- remove patch that is now upstream
- use nix-update-script
- enable strictDeps

- Built on platform(s)
  - [ ] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-30 13:38 UTC, matdibu commented
`0.8.1` passes `nix-build -A rasdaemon.passthru.tests`
but `0.8.2` fails with
```
machine # DBD::SQLite::db prepare failed: no such table: mc_event at /run/current-system/sw/bin/ras-mc-ctl line 1751.
machine # ras-mc-ctl: Error: mc_event table missing from /var/lib/rasdaemon/ras-mc_event.db. Run 'rasdaemon --record'.
```

2024-12-30 14:27 UTC, matdibu commented
I'm trying to figure out why `/var/lib/rasdaemon/ras-mc_event.db` is missing on `0.8.2` but not `0.8.1`

2024-12-30 17:04 UTC, matdibu commented
I'm looking through https://github.com/mchehab/rasdaemon/compare/v0.8.1...v0.8.2 and I can't find anything that pops out

2024-12-30 17:37 UTC, matdibu commented
bisected it to https://github.com/mchehab/rasdaemon/commit/d22ed5ef1880f81cafe0b18fe4c121da4ea4950f

```shellsession
$ nix run nixpkgs#nix-update -- --version 7575b78d3ca7ea53c41ba34d168e43e13da6652e rasdaemon
$ nix-build -A rasdaemon.passthru.tests
/nix/store/a9n3wqcg05hmch2gima90wic4qsh0m8k-vm-test-run-rasdaemon
```

```shellsession
$ nix run nixpkgs#nix-update -- --version d22ed5ef1880f81cafe0b18fe4c121da4ea4950f rasdaemon
$ nix-build -A rasdaemon.passthru.tests
...
machine: must succeed: ls -alh /var/lib/rasdaemon/ | tee /dev/stderr
machine # total 8.0K
machine # drwxr-xr-x 2 root root 4.0K Dec 30 17:36 .
machine # drwxr-xr-x 9 root root 4.0K Dec 30 17:36 ..
...
machine: must succeed: ras-mc-ctl --errors | tee /dev/stderr | grep -q 'No .* errors.'
machine # DBD::SQLite::db prepare failed: no such table: mc_event at /run/current-system/sw/bin/ras-mc-ctl line 1751.
machine # ras-mc-ctl: Error: mc_event table missing from /var/lib/rasdaemon/ras-mc_event.db. Run 'rasdaemon --record'.
```

2024-12-30 19:53 UTC, matdibu commented
```
--------- Impacted packages on 'x86_64-linux' ---------
1 package updated:
rasdaemon (0.8.0 → 0.8.2)

--------- Report for 'x86_64-linux' ---------
4 packages built:
rasdaemon rasdaemon.dev rasdaemon.inject rasdaemon.man
```

2024-12-30 20:17 UTC, matdibu commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369375`

---
### `x86_64-linux`
<details>
  <summary>:fast_forward: 2 packages blacklisted:</summary>
  <ul>
    <li>nixos-install-tools</li>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>:white_check_mark: 4 packages built:</summary>
  <ul>
    <li>rasdaemon</li>
    <li>rasdaemon.dev</li>
    <li>rasdaemon.inject</li>
    <li>rasdaemon.man</li>
  </ul>
</details>

2024-12-30 20:19 UTC, matdibu commented
@evils it's now ready to review

2024-12-31 08:44 UTC, lucasew commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369375`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 test built:</summary>
  <ul>
    <li>nixosTests.rasdaemon</li>
  </ul>
</details>

2025-01-03 18:18 UTC, matdibu commented
it does build and run on `aarch64-linux` as well
```shellsession
[mateidibu@rockpro64:~]$ ras-mc-ctl --mainboard
ras-mc-ctl: mainboard: PINE64 model ROCKPro64

[mateidibu@rockpro64:~]$ ras-mc-ctl --errors
No Memory errors.

No PCIe AER errors.

No ARM processor errors.

No CXL AER uncorrectable errors.

No CXL AER correctable errors.

No CXL overflow errors.

No CXL poison errors.

No CXL generic errors.

No CXL general media errors.

No CXL DRAM errors.

No CXL memory module errors.

No Extlog errors.

No devlink errors.

No disk errors.

No Memory failure errors.

No MCE errors.
```

2025-01-15 11:27 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/5091

2025-01-15 12:41 UTC, PerchunPak requested changes

2025-01-15 15:41 UTC, matdibu commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    repo = finalAttrs.pname;
oh nice, I wasn't aware of that

2025-01-15 15:46 UTC, matdibu commented
@PerchunPak I've rebased and applied your suggestions

2025-01-15 15:52 UTC, matdibu commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    repo = finalAttrs.pname;
should I revert this as well?
```
changelog = "${finalAttrs.meta.homepage}/releases/tag/v${finalAttrs.version}";
```

2025-01-15 16:00 UTC, PerchunPak commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    repo = finalAttrs.pname;
This is the first time I see something like this, so I don't have a strong opinion on this. Feel free to revert or keep it

2025-01-15 16:01 UTC, PerchunPak approved these changes
LGTM

2025-01-15 17:03 UTC, matdibu commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    repo = finalAttrs.pname;
I'll remove it if there's a single person that objects to it, otherwise we can leave it there

2025-01-16 17:13 UTC, lucasew commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    rev = "refs/tags/v${finalAttrs.version}";
`tag = "v${finalAttrs.version}"`

2025-01-16 17:16 UTC, lucasew commented
Only a detail, the rest of diff LGTM

2025-01-16 17:25 UTC, matdibu commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    rev = "refs/tags/v${finalAttrs.version}";
done

2025-01-24 19:10 UTC, PerchunPak commented
Not sure why wegank removed the label, almost nothing changed since my review

2025-02-17 02:39 UTC, zowoq commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    # these 3 patches fix nixosTests.rasdaemon for v0.8.2
The only reason these patches are reverted is to fix `nixosTests.rasdaemon`?

If the test is broken and isn't currently fixable I'd expect the test to be marked as broken instead of reverting upstream commits? Keeping these reverted may prove to be impractical with new upstream releases anyway?

2025-02-19 11:22 UTC, matdibu commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    # these 3 patches fix nixosTests.rasdaemon for v0.8.2
the test itself (https://github.com/NixOS/nixpkgs/blob/4f0dadbf38ee4cf4cc38cbc232b7708fddf965bc/nixos/tests/rasdaemon) is pretty trivial though, I'm not sure how I could fix it

but I'll give it another try in a few days, maybe I'll find something I missed

2025-02-28 06:31 UTC, zowoq commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    # these 3 patches fix nixosTests.rasdaemon for v0.8.2
It takes almost five minutes but the test does eventually pass:

```diff
diff --git a/nixos/tests/rasdaemon.nix b/nixos/tests/rasdaemon.nix
index 7eeb8b0aa6a1..c7b147a1ca52 100644
--- a/nixos/tests/rasdaemon.nix
+++ b/nixos/tests/rasdaemon.nix
@@ -29,7 +29,7 @@ import ./make-test-python.nix (
       machine.wait_for_unit("multi-user.target")
       # confirm rasdaemon is running and has a valid database
       # some disk errors detected in qemu for some reason ¯\_(ツ)_/¯
-      machine.succeed("ras-mc-ctl --errors | tee /dev/stderr | grep -q 'No .* errors.'")
+      machine.wait_until_succeeds("ras-mc-ctl --errors | tee /dev/stderr | grep -q 'No .* errors.'")
       # confirm the supplied labels text made it into the system
       machine.succeed("grep -q 'vendor: none' /etc/ras/dimm_labels.d/labels >&2")
       machine.shutdown()
diff --git a/pkgs/by-name/ra/rasdaemon/package.nix b/pkgs/by-name/ra/rasdaemon/package.nix
index b8376b1bf0df..27f80748b727 100644
--- a/pkgs/by-name/ra/rasdaemon/package.nix
+++ b/pkgs/by-name/ra/rasdaemon/package.nix
@@ -1,7 +1,6 @@
 {
   autoreconfHook,
   fetchFromGitHub,
-  fetchpatch,
   lib,
   libtraceevent,
   nix-update-script,
@@ -26,31 +25,6 @@ stdenv.mkDerivation (finalAttrs: {
     hash = "sha256-veaqAbSJvoUzkn1OLYY3t3y9Bh8dzuenpLGO2yz/yaM=";
   };
 
-  patches = [
-    # these 3 patches fix nixosTests.rasdaemon for v0.8.2
-    # see https://github.com/NixOS/nixpkgs/pull/369375 for the investigation
-    (fetchpatch {
-      name = "revert eafd51d859a91fcee4509dd7abab3c449b4830ab";
-      url = "https://github.com/mchehab/rasdaemon/commit/eafd51d859a91fcee4509dd7abab3c449b4830ab.patch";
-      hash = "sha256-mwtl3QWqALgiQSo6h8DGTQEdurCNNSWQ3rKtTvgRAH4=";
-      includes = [ "ras-events.c" ];
-      revert = true;
-    })
-    (fetchpatch {
-      name = "revert dc1233045d023708047320bf722b1f52fd797c58";
-      url = "https://github.com/mchehab/rasdaemon/commit/dc1233045d023708047320bf722b1f52fd797c58.patch";
-      hash = "sha256-K2PCgtF+/zS5JO/uxBTDbJY9Rol8j/nJ2TwPgJCtc68=";
-      includes = [ "ras-events.c" ];
-      revert = true;
-    })
-    (fetchpatch {
-      name = "revert d22ed5ef1880f81cafe0b18fe4c121da4ea4950f";
-      url = "https://github.com/mchehab/rasdaemon/commit/d22ed5ef1880f81cafe0b18fe4c121da4ea4950f.patch";
-      hash = "sha256-5x51fyGWluYok+0UYUEYiBpTi5kaSO3J/fh2AzZozTc=";
-      revert = true;
-    })
-  ];
-
   strictDeps = true;
 
   enableParallelBuilding = true;

```

2025-02-28 09:11 UTC, matdibu commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    # these 3 patches fix nixosTests.rasdaemon for v0.8.2
```
machine # [   37.960110] rasdaemon[692]: wait_access failed, /sys/kernel/debug/tracing/instances/rasdaemon/events/cxl/cxl_poison/format not created in 30000 ms
machine # [   37.961758] rasdaemon[692]: rasdaemon: wait_access failed, /sys/kernel/debug/tracing/instances/rasdaemon/events/cxl/cxl_poison/format not created in 30000 ms
machine # [   37.963206] rasdaemon[692]: rasdaemon: Can't get cxl:cxl_poison traces: Operation not permitted
machine # [   37.964146] rasdaemon[692]: rasdaemon: Can't get traces from cxl:cxl_poison
machine # [   37.964941] rasdaemon[692]: Can't get traces from cxl:cxl_poison
```
the same error appears for:
* `cxl:cxl_aer_uncorrectable_error`
* `cxl:cxl_aer_correctable_error`
* `cxl:cxl_overflow`
* `cxl:cxl_generic_event`
* `cxl:cxl_general_media`
* `cxl:cxl_dram`
* `cxl:memory_module`

which comes up to a total timeout of `30s * 8 = 240s`
seeings as `test script finished in 268.35s`, that checks out

I'll see if I can make it skip CXL during the tests, I'm not a fan of waiting and hoping for `wait_until_succeeds` to finish

2025-02-28 09:18 UTC, matdibu commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    # these 3 patches fix nixosTests.rasdaemon for v0.8.2
that `--enable-all` we're using makes it so I can't disable cxl support

```ac
AS_IF([test "x$enable_cxl" = "xyes" || test "x$enable_all" == "xyes"], [
  AC_DEFINE(HAVE_CXL,1,"have CXL events collect")
  AC_SUBST([WITH_CXL])
])
AM_CONDITIONAL([WITH_CXL], [test x$enable_cxl = xyes || test x$enable_all == xyes])
```

2025-02-28 09:47 UTC, matdibu commented on pkgs/by-name/ra/rasdaemon/package.nix
> +    # these 3 patches fix nixosTests.rasdaemon for v0.8.2
I've rebased and pushed with your suggestions

2025-02-28 09:55 UTC, matdibu commented
Latest run of `nixosTests.rasdaemon` (successful, but there's a 240s delay):

```
(finished: run the VM test script, in 267.35 seconds)
test script finished in 267.35s
cleanup
kill vlan (pid 9)
(finished: cleanup, in 0.00 seconds)
/nix/store/498kcyfzwvnw55723af92yr0jj9bvspi-vm-test-run-rasdaemon
```

2025-02-28 11:47 UTC, merged