epson-escpr: 1.7.20 -> 1.8.6
NixOS/nixpkgs pull request #369304
Opened 2024-12-30 05:18 UTC by Arjun31415

Also fixed gcc14 build issues
Got patches from Gentoo repo : https://gitweb.gentoo.org/repo/gentoo.git/tree/net-print/epson-inkjet-printer-escpr/files

## Things done

- Built on platform(s)
  - [x] x86_64-linux
  - [ ] aarch64-linux
  - [ ] x86_64-darwin
  - [ ] aarch64-darwin
- For non-Linux: Is sandboxing enabled in `nix.conf`? (See [Nix manual](https://nixos.org/manual/nix/stable/command-ref/conf-file.html))
  - [ ] `sandbox = relaxed`
  - [ ] `sandbox = true`
- [ ] Tested, as applicable:
  - [NixOS test(s)](https://nixos.org/manual/nixos/unstable/index.html#sec-nixos-tests) (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
  - and/or [package tests](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#package-tests)
  - or, for functions and "core" functionality, tests in [lib/tests](https://github.com/NixOS/nixpkgs/blob/master/lib/tests) or [pkgs/test](https://github.com/NixOS/nixpkgs/blob/master/pkgs/test)
  - made sure NixOS tests are [linked](https://github.com/NixOS/nixpkgs/blob/master/pkgs/README.md#linking-nixos-module-tests-to-a-package) to the relevant packages
- [ ] Tested compilation of all packages that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review rev HEAD"`. Note: all changes have to be committed, also see [nixpkgs-review usage](https://github.com/Mic92/nixpkgs-review#usage)
- [ ] Tested basic functionality of all binary files (usually in `./result/bin/`)
- [25.05 Release Notes](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) (or backporting [24.11](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2411.section.md) and [25.05](https://github.com/NixOS/nixpkgs/blob/master/nixos/doc/manual/release-notes/rl-2505.section.md) Release notes)
  - [ ] (Package updates) Added a release notes entry if the change is major or breaking
  - [ ] (Module updates) Added a release notes entry if the change is significant
  - [ ] (Module addition) Added a release notes entry if adding a new NixOS module
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md).

---

Add a :+1: [reaction] to [pull requests you find important].

[reaction]: https://github.blog/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/
[pull requests you find important]: https://github.com/NixOS/nixpkgs/pulls?q=is%3Aopen+sort%3Areactions-%2B1-desc

2024-12-30 16:57 UTC, PedroHLC commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369304`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>epson-escpr</li>
  </ul>
</details>

2024-12-30 16:58 UTC, PedroHLC approved these changes
The resulting file looks good to me.

2024-12-30 17:09 UTC, Shawn8901 commented
i am not having a escpr(1) compatible printer so i can not test, sorry

2025-01-02 14:49 UTC, Arjun31415 commented
If review is successful, could this be merged please

2025-01-02 18:24 UTC, JuliusFreudenberger commented
I'm also waiting for this to land, however 2 approvals are needed. That is why this is not merged yet. All we can do afaik is wait patiently.

2025-01-02 18:29 UTC, Shawn8901 commented
> I'm also waiting for this to land, however 2 approvals are needed. That is why this is not merged yet. All we can do afaik is wait patiently.

fyi: a person with commit rights is needed for merging a pr, not actually a specific number of approvals.

2025-01-02 19:12 UTC, JuliusFreudenberger commented
Thanks for the clarification. I was misleaded by the '1 pending reviewer' part.

2025-01-02 20:05 UTC, Shawn8901 commented
> Thanks for the clarification. I was misleaded by the '1 pending reviewer' part.

github visualizes that as there is no approval by a person with commiter rights.

2025-01-02 23:20 UTC, SigmaSquadron requested changes

2025-01-02 23:20 UTC, SigmaSquadron commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
```suggestion
    (fetchpatch {
      url = "https://gitweb.gentoo.org/repo/gentoo.git/plain/net-print/epson-inkjet-printer-escpr/files/1.8.6-warnings.patch";
      hash = lib.fakeHash;
    })
    ...
```
If those patches are all from Gentoo, please use [`fetchpatch`](https://nixos.org/manual/nixpkgs/unstable/#fetchpatch) instead of copying them in-tree.

2025-01-03 02:53 UTC, Arjun31415 commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
This fails because of different line-endings error in patchPhase
```nix
    (fetchpatch {
        url="https://gitweb.gentoo.org/repo/gentoo.git/plain/net-print/epson-inkjet-printer-escpr/files/epson-inkjet-printer-escpr-1.8-missing-include.patch";
        hash="sha256-L4WhaxPQnJYyqCH00wiKIlFNMmCEXoGe5d7hJ5TMyEI=";
      })
    (fetchpatch {
      url = "https://gitweb.gentoo.org/repo/gentoo.git/plain/net-print/epson-inkjet-printer-escpr/files/1.8.6-warnings.patch";
      hash = "sha256-wSY0LZv2b+1kF7TfPolt554g79y2Ce6N/JqgjJyd3Ag=";
    })
```

```
@nix { "action": "setPhase", "phase": "patchPhase" }
applying patch /nix/store/x5gfirhz3sl53qf12cx38hp7ymxykjp6-cups-filter-ppd-dirs.patch
patching file configure
applying patch /nix/store/5cmxn3w61k1dk33x672vcpxczc6fkzwi-epson-inkjet-printer-escpr-1.8-missing-include.patch
patching file lib/epson-escpage.h
applying patch /nix/store/v72wz3lbds19xhqjv9gwkh94biliq43b-1.8.6-warnings.patch
patching file lib/epson-escpr-api.h
Hunk #1 FAILED at 111 (different line endings).
1 out of 1 hunk FAILED -- saving rejects to file lib/epson-escpr-api.h.rej
patching file src/filter.c
patching file src/mem.c
patching file src/wrapper.c
```

2025-01-03 03:00 UTC, SigmaSquadron commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
The `-l` flag might fix this depending on where the line ending is in the patch file, but it might be better to use the `decode` attr to pipe the patch through `dos2unix` (or `unix2dos`)

2025-01-03 03:02 UTC, Arjun31415 commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
The issue is that the [warnings patch](https://gitweb.gentoo.org/repo/gentoo.git/tree/net-print/epson-inkjet-printer-escpr/files/1.8.6-warnings.patch) patches files in /lib with CRLF and files in /src with LF in a single patch file. 
So I have to do unix2dos on only a part of the file, which I do not know how to do with nix

2025-01-03 03:05 UTC, SigmaSquadron commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
Oh. That's... weird. Is `fetchpatch` converting Gentoo's correct line endings then? If so, then it can still be fetched with `fetchurl`.

2025-01-03 03:12 UTC, Arjun31415 commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
No, gentoo is using dos2unix 
https://gitweb.gentoo.org/repo/gentoo.git/tree/net-print/epson-inkjet-printer-escpr/epson-inkjet-printer-escpr-1.8.6.ebuild#n31

2025-01-03 03:22 UTC, SigmaSquadron commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
I won't block this further, but it might be a good idea to do the same in a `postUnpack` hook.

2025-01-03 03:25 UTC, Arjun31415 commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
Yeah I'm trying that thing out.

2025-01-03 04:27 UTC, Arjun31415 commented on pkgs/by-name/ep/epson-escpr/package.nix
> +    ./1.8-missing-include.patch
Done

2025-01-03 04:41 UTC, SigmaSquadron approved these changes

2025-01-03 04:43 UTC, SigmaSquadron commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369304`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>epson-escpr</li>
  </ul>
</details>

2025-01-03 04:46 UTC, Arjun31415 commented
The only issue I can see right now is that in postUnpackPhase the `cd` command directory is hardcoded.

2025-01-03 04:49 UTC, SigmaSquadron commented
> The only issue I can see right now is that in postUnpackPhase the `cd` command directory is hardcoded.

Could use `lib.take 5 version` there.

2025-01-03 04:53 UTC, Arjun31415 commented
> `builtins.substring 0 5 version`

Is there a way to get it the directory from the `$src` variable. The `$src` variable just has the tar.gz file ending extra

2025-01-03 05:04 UTC, SigmaSquadron commented
I'm sorry, I have no idea how string manipulation works in bash. It's way too many `%`s and `{{/#}}` and `^@^` for me to make any sense of it.

Still, what an opportunity for me to shill for `fish`:
```console
$ string replace '.tar.gz' '' 'epson-inkjet-printer-escpr-1.8.6.tar.gz'
epson-inkjet-printer-escpr-1.8.6
```

2025-01-03 05:17 UTC, SigmaSquadron commented
Wait, isn't it just `${src//.tar.gz/}`?

2025-01-03 05:29 UTC, Arjun31415 commented
> Wait, isn't it just `${src//.tar.gz/}`?

That is what I did first 
```nix
    set -x
    echo $src
    cd \$\{src//.tar.gz/\};
```
but that fails - 
```
@nix { "action": "setPhase", "phase": "unpackPhase" }
unpacking source archive /nix/store/972jwlhgjhxq3gq3xmcbzqlw8gzjqfry-epson-inkjet-printer-escpr-1.8.6-1.tar.gz
source root is epson-inkjet-printer-escpr-1.8.6
++++ echo /nix/store/972jwlhgjhxq3gq3xmcbzqlw8gzjqfry-epson-inkjet-printer-escpr-1.8.6-1.tar.gz
/nix/store/972jwlhgjhxq3gq3xmcbzqlw8gzjqfry-epson-inkjet-printer-escpr-1.8.6-1.tar.gz
++++ cd '${src//.tar.gz/}'
/nix/store/d0gfdcag8bxzvg7ww4s7px4lf8sxisyx-stdenv-linux/setup: line 229: cd: ${src//.tar.gz/}: No such file or directory
+ exitHandler
+ exitCode=1
```

2025-01-03 05:29 UTC, SigmaSquadron commented
> That is what I did first

Don't escape it.

2025-01-03 05:31 UTC, Arjun31415 commented
That won't work 
```
       error: syntax error, unexpected '.'
       at /nix/store/p8ckw6jagsw4ng12ramzv50limcllkvl-source/pkgs/by-name/ep/epson-escpr/package.nix:38:15:
           37|     echo $src
           38|     cd ${src//.tar.gz/};
```

2025-01-03 05:32 UTC, SigmaSquadron commented
Oh! Right. Try escaping it like this: `''${src//.tar.gz/};`

2025-01-03 05:35 UTC, Arjun31415 commented
Ok that works but unfortunately the source root is epson-inkjet-printer-escpr-1.8.6, but the stripped directory becomes /nix/store/972jwlhgjhxq3gq3xmcbzqlw8gzjqfry-epson-inkjet-printer-escpr-1.8.6-1

The extra `-1`. 
Epson and their weird naming schemes

2025-01-03 05:42 UTC, SigmaSquadron commented
We will need temporary variables.

Try this:
```nix
{
  postUnpack = ''
    a=''${src//.tar.gz/}
    b=''${a#-*}
    cd ''${b#*-}
  '';
}
```

2025-01-03 05:45 UTC, Arjun31415 commented
yeah, but then i also need to find how to remove the /nix store prefix along with the hash also

2025-01-03 05:46 UTC, SigmaSquadron commented
That's what `${b#*-}` does.

2025-01-03 05:48 UTC, SigmaSquadron commented
Actually, now that I think about it, the first substitution is unnecessary.

2025-01-03 05:51 UTC, SigmaSquadron commented
Try this:
```
dir=''${src%-*}
cd ''${dir#*-}
```

2025-01-03 05:56 UTC, Arjun31415 commented
Something else came up,  I'll get back to it later today

On Fri, 3 Jan 2025, 11:18 Fernando Rodrigues, ***@***.***>
wrote:

> Actually, now that I think about it, the first substitution is unnecessary.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/369304#issuecomment-2568721938>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARHQXWYSE2L6XGIQKLIC7R32IYQEJAVCNFSM6AAAAABULQICXGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDKNRYG4ZDCOJTHA>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2025-01-03 18:03 UTC, SigmaSquadron approved these changes

2025-01-03 22:26 UTC, PedroHLC commented
## `nixpkgs-review` result

Generated using [`nixpkgs-review`](https://github.com/Mic92/nixpkgs-review).

Command: `nixpkgs-review pr 369304`

---
### `x86_64-linux`
<details>
  <summary>:white_check_mark: 1 package built:</summary>
  <ul>
    <li>epson-escpr</li>
  </ul>
</details>

2025-01-04 15:23 UTC, PedroHLC commented
![photo_2025-01-04_12-22-24](https://github.com/user-attachments/assets/ce3c4da5-898b-4ae0-8765-030459116549)

[Cherry-picked over nixos-unstable](https://github.com/PedroHLC/nixpkgs/commit/2a4c2b263ad108d6e63578d8cea9d029a1fa3204)

2025-01-04 15:24 UTC, PedroHLC approved these changes

2025-01-04 15:52 UTC, Ekleog approved these changes
People reported this working, the diff looks safe to me, and the CI failure seems like a misconfiguration of CI (it looks like CI is trying to automatically request a review from a non-committer?).

@artuuge Considering you didn't answer since the issue was opened I'm landing this to unbreak nixos-unstable; if you don't have commit rights and have a better fix please ping me on any follow-up PR and I'll do my best to review it :)

2025-01-04 15:54 UTC, Ekleog commented
Actually the last-minute check reminded me I still need to wait for ofborg to finish eval before landing, and to run this test too:

@ofborg build epson-escpr

Hopefully this can land soon!

2025-01-04 15:58 UTC, Ekleog commented
Oh weird, apparently ofborg is down? PRs from 14 hours ago don't even have it as pending at all, and this is not the only relatively old-ish PR to not have the eval results back yet.

Welp, guess I'd be very surprised if this broke eval, so I'll just cross my fingers and land as is :crossed_fingers:

2025-01-04 15:58 UTC, merged

2025-01-04 18:58 UTC, SigmaSquadron commented
>  the CI failure seems like a misconfiguration of CI

Yes. Infinisil is working on fixing the review requests. https://github.com/NixOS/nixpkgs/pull/370456#issuecomment-2569942227

> Oh weird, apparently ofborg is down?

Not just down, but [dead](https://discourse.nixos.org/t/infrastructure-announcement-the-future-of-ofborg-your-help-needed/56025) and [buried](https://discourse.nixos.org/t/ofborg-migration-very-soon/58064). The Equinix Metal sponsorship that financed OfBorg's build machines ended on 2025-01-01. OfBorg no longer has any builders to run CI on PRs.

2025-01-04 20:21 UTC, Ekleog commented
Thank you for the information ! I completely distanced myself from most of the communication channels, and have been only following from very far away recently, for lack of time

2025-01-07 00:38 UTC, andrevmatos commented
Package is not good: `ensure-printers.service` errors, `cups.service` complains that `File "/nix/store/sg1cmrdpdj1z3h0s7d076g2jawmxfj2l-cups-progs/lib/cups/filter/epson-escpr-wrapper" not available: No
 such file or directory`, while `epson-escpr-wrapper` is only found inside a `/nix/store/d0rilfvqd699fkzl2r0n8g95c7pzb938-epson-escpr-1.8.6-1/store/26fb46gwc5sbd045nj3dxw4zqpml359i-cups-2.4.11/lib/cups/filter/` folder, so it looks like wrapper is putting a `store/` folder in escpr's `$out`

2025-01-11 04:33 UTC, jerith666 commented
I won't have time to open a PR until tomorrow at the earliest, but this fixes the layout problem cited by @andrevmatos:

https://github.com/jerith666/nixpkgs/commit/5b07eccc77ea29f040abf98450d8524840ec4fd1

2025-01-11 11:29 UTC, andrevmatos commented
I can confirm @jerith666 's fix solves the issue and I could print again. Thank you

2025-01-11 13:17 UTC, Ekleog commented
@jerith666 Please ping me on the PR once you make it, I'll try to land it quickly :)