Fix tablib
NixOS/nixpkgs pull request #37247
Opened 2018-03-17 13:25 UTC by Ma27

###### Motivation for this change

`openpyxl` v5 broke `tablib`: https://github.com/kennethreitz/tablib/issues/324

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-03-17 13:25 UTC, Ma27 commented
starting `nox-review` to check possile further breackage

2018-03-17 13:44 UTC, dotlambda commented
Did you try applying https://github.com/kennethreitz/tablib/pull/296 instead of reverting the openpyxl update?

2018-03-17 14:13 UTC, Ma27 commented
@dotlambda you're right, this seems to be more suitable %)

2018-03-17 14:16 UTC, dotlambda requested changes

2018-03-17 14:16 UTC, dotlambda commented on pkgs/development/python-modules/tablib/default.nix
> +  buildInputs = [ pytest unicodecsv pandas ];
`checkInputs`? (at least `pytest`)

2018-03-17 14:16 UTC, dotlambda commented on pkgs/development/python-modules/tablib/default.nix
> +  };
Please add the correct license.

2018-03-17 18:29 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.tablib python3.pkgs.tablib

2018-03-17 19:30 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37247&attempt_id=30f504fa-3e61-4eb1-8a2c-754f5d8f0621)

Attempted: python2.pkgs.tablib, python3.pkgs.tablib

<details><summary>Partial log (click to expand)</summary><p>

```
.....                                                                    [ 67%]
../../nix/store/x1ck7girhc5xwzd7wgr2kzj26gq5r9p2-python2.7-pandas-0.22.0/lib/python2.7/site-packages/pandas/tests/io/formats/test_eng_formatting.py . [ 67%]
.....                                                                    [ 67%]
../../nix/store/x1ck7girhc5xwzd7wgr2kzj26gq5r9p2-python2.7-pandas-0.22.0/lib/python2.7/site-packages/pandas/tests/io/formats/test_format.py . [ 67%]
........................................................................ [ 66%]
building of '/nix/store/rc8nf3sl2vr780kdalllkgfkcsgbn8a9-python2.7-pandas-0.22.0.drv' timed out after 3600 seconds
cannot build derivation '/nix/store/p5hmrz270b1dv18zpwxdsajcb9f3ggqc-python2.7-tablib-0.12.1.drv': 1 dependencies couldn't be built
building of '/nix/store/223j1d7rmawq7jlv48v489lnrky6cisa-python3.6-pandas-0.22.0.drv' timed out after 3600 seconds
cannot build derivation '/nix/store/vlb9imhhk0rvi87y6vbnd5hr5w8zysaj-python3.6-tablib-0.12.1.drv': 1 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/p5hmrz270b1dv18zpwxdsajcb9f3ggqc-python2.7-tablib-0.12.1.drv', '/nix/store/vlb9imhhk0rvi87y6vbnd5hr5w8zysaj-python3.6-tablib-0.12.1.drv' failed
```
</p></details>

2018-03-17 19:45 UTC, merged

2018-03-17 19:47 UTC, dotlambda commented
Cherry-picked in 039365d20f4f00426901668ff99187498eda8ba6

2018-03-18 01:07 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37247&attempt_id=add06d26-b3a2-44de-a1eb-95100ecc4239)

Attempted: python2.pkgs.tablib, python3.pkgs.tablib

<details><summary>Partial log (click to expand)</summary><p>

```
copying path '/nix/store/a6s07mmbq5m2hnbk8mdj424ws6c5g2d9-python3.6-lxml-4.1.1' from 'https://cache.nixos.org'...
copying path '/nix/store/yi0qifn42qvk03mcsgslxw2b5k9siwgh-python2.7-openpyxl-2.5.0' from 'https://cache.nixos.org'...
copying path '/nix/store/8xq1m9glc79ycffh0mfgfc9dyk6z3419-python3.6-odfpy-1.3.6' from 'https://cache.nixos.org'...
copying path '/nix/store/cai896am72mpamqnd7mk060vbxwwn9vq-python3.6-xlrd-0.9.4' from 'https://cache.nixos.org'...
copying path '/nix/store/wzv1kkmk5r5vg3ldfdr04ba52l5pfgxy-python3.6-xlwt-1.3.0' from 'https://cache.nixos.org'...
copying path '/nix/store/7vzc731hh64hq5pq2g92w5bc5y5rkhrg-python2.7-tablib-0.12.1' from 'https://cache.nixos.org'...
copying path '/nix/store/fn5nrpwsabwc04q4099whf18fvsz9ksv-python3.6-openpyxl-2.5.0' from 'https://cache.nixos.org'...
copying path '/nix/store/bnx916lm0ckj4d2h390kiig2zknlqbgh-python3.6-tablib-0.12.1' from 'https://cache.nixos.org'...
/nix/store/7vzc731hh64hq5pq2g92w5bc5y5rkhrg-python2.7-tablib-0.12.1
/nix/store/bnx916lm0ckj4d2h390kiig2zknlqbgh-python3.6-tablib-0.12.1
```
</p></details>