toml: init at 0.9.4
NixOS/nixpkgs pull request #37469
Opened 2018-03-20 17:08 UTC by Twey

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-03-20 17:36 UTC, FRidh requested changes

2018-03-20 17:36 UTC, FRidh commented on pkgs/development/python-modules/toml/default.nix
> +  name = "${pname}-${version}";
The `name` attribute is added by `buildPython*` and should therefore be removed.

2018-03-20 17:36 UTC, FRidh commented
@GrahamcOfBorg build python.pkgs.toml python3.pkgs.toml

2018-03-20 17:36 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37469&attempt_id=62a3d6a5-52bc-4c07-b89a-a4ab022f9af8)

Attempted: python.pkgs.toml, python3.pkgs.toml

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest template 'MANIFEST.in'
writing manifest file 'toml.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/x284lir9a4crd99fvkwarvn5li4khkfh-python2.7-toml-0.9.4
/nix/store/ri7a0h2a49d4agl0kk8cywqqmcnbfmcq-python3.6-toml-0.9.4
```
</p></details>

2018-03-20 17:37 UTC, GrahamcOfBorg commented
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37469&attempt_id=47b7adca-a019-4e36-a02f-9230d15e176c)

Attempted: python.pkgs.toml, python3.pkgs.toml

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest template 'MANIFEST.in'
writing manifest file 'toml.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/wml4cm5rx86wxbk74y6psxhmymrx8ry4-python2.7-toml-0.9.4
/nix/store/kciffc34ndnq8cdx5h94kwk0qp5zjxjx-python3.6-toml-0.9.4
```
</p></details>

2018-03-20 17:37 UTC, FRidh commented
```
Ran 0 tests in 0.000s
```
No tests are found. Either the test runner cannot find tests and needs to be patched, or there simply are no tests in which case the tests need to be disabled. Do include a comment explaining why the tests are disabled.

2018-03-20 17:39 UTC, FRidh commented on pkgs/development/python-modules/toml/default.nix
> +    platforms = platforms.all;
should be removed

2018-03-20 22:04 UTC, Twey commented
Thanks!

There is a test suite but it's not very Nix-friendly.  I've disabled it for the time being.  Maybe we could add separate packages for `tox` and `toml-test` and make a tester that runs it that way.

2018-03-22 08:08 UTC, FRidh approved these changes

2018-03-25 06:45 UTC, merged