pythonPackages.wordfreq and dependencies
NixOS/nixpkgs pull request #37784
Opened 2018-03-25 18:58 UTC by ixxie

Initialized the python wordfreq module at 2.0, with dependencies.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-03-27 07:46 UTC, ixxie commented
@dotlambda  - got time to review this?

2018-04-03 08:16 UTC, dotlambda requested changes
Sorry for the late reply! I was on vacation.

2018-04-03 08:16 UTC, dotlambda commented on pkgs/development/python-modules/langcodes/default.nix
> +    description = "langcodes is a toolkit for working with and comparing the standardized codes for languages, such as ‘en’ for English, ‘es’ for Spanish, and ‘zh-Hant’ for Traditional Chinese.";
https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes

2018-04-03 08:16 UTC, dotlambda commented on pkgs/development/python-modules/mecab-python3/default.nix
> +   };
indentation

2018-04-03 08:16 UTC, dotlambda commented on pkgs/development/python-modules/mecab-python3/default.nix
> +
whitespace

2018-04-03 08:16 UTC, dotlambda commented on pkgs/development/python-modules/wordfreq/default.nix
> +  patches = [ ./relax-regex-dep.patch ];
I'd prefer using `substituteInPlace` in `postPatch`. Something like
```
postPatch = ''
  substituteInPlace setup.py \
    --replace "regex ==" "regex >="
'';
```

2018-04-03 08:20 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.wordfreq python3.pkgs.wordfreq python3.pkgs.langcodes python2.pkgs.mecab-python3 python3.pkgs.mecab-python3 python2.pkgs.marisa-trie python3.pkgs.marisa-trie

2018-04-03 08:21 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37784&attempt_id=a9cdaaa0-b402-452e-b744-04bc842fff40)

Attempted: python3.pkgs.wordfreq, python3.pkgs.langcodes, python2.pkgs.mecab-python3, python3.pkgs.mecab-python3, python2.pkgs.marisa-trie, python3.pkgs.marisa-trie

The following builds were skipped because they don't evaluate on aarch64-linux: python2.pkgs.wordfreq

<details><summary>Partial log (click to expand)</summary><p>

```
writing manifest file 'mecab_python3.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-aarch64-3.6/_MeCab.cpython-36m-aarch64-linux-gnu.so ->

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
cannot build derivation '/nix/store/vnjrbmk6zkxgck2d2p85q9l4vnqjvpwz-python3.6-wordfreq-2.0.drv': 1 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/0hdq6pv5gihb02yq49hm0v64ri2xkh5y-python3.6-marisa-trie-0.7.4.drv', '/nix/store/bxgif1ihrmk15mfianiw26yc290sv0qz-python3.6-langcodes-1.4.1.drv', '/nix/store/vnjrbmk6zkxgck2d2p85q9l4vnqjvpwz-python3.6-wordfreq-2.0.drv', '/nix/store/wwilj8w8r96sfzrfpdkmvxxjya5m0h80-python2.7-marisa-trie-0.7.4.drv' failed
```
</p></details>

2018-04-03 08:21 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37784&attempt_id=dc12b27a-c712-4b65-90f8-7b96aa687ce7)

Attempted: python3.pkgs.wordfreq, python3.pkgs.langcodes, python2.pkgs.mecab-python3, python3.pkgs.mecab-python3, python2.pkgs.marisa-trie, python3.pkgs.marisa-trie

The following builds were skipped because they don't evaluate on x86_64-linux: python2.pkgs.wordfreq

<details><summary>Partial log (click to expand)</summary><p>

```
-

1
0
.
2
M

cannot build derivation ‘/nix/store/wyjqq931z4yfd6bx5bajc147l0hfc68b-python3.6-wordfreq-2.0.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/l7rm4d50cxs0a7xmm2zly1wz41dhp9fg-python2.7-marisa-trie-0.7.4.drv’, ‘/nix/store/rqfsbiqlv0l0rw5hy9a97vz3nswy3q44-python3.6-marisa-trie-0.7.4.drv’, ‘/nix/store/sxfmzhb0l10dxmlys5mz6p5kfmqsmlaf-python3.6-langcodes-1.4.1.drv’, ‘/nix/store/wyjqq931z4yfd6bx5bajc147l0hfc68b-python3.6-wordfreq-2.0.drv’ failed
```
</p></details>

2018-04-03 08:25 UTC, dotlambda commented
> Ran 0 tests in 0.000s

Please make sure every package has an appropriate `checkPhase` if it provides tests. Otherwise, please set `doCheck = false` and add an inline comment with the reason.

2018-04-04 21:02 UTC, ixxie commented
@dotlambda I think I managed to address all your concerns but one: I tried to get wordfreq's tests going by switching to `fetchFromGitHub` and triggering nose tests like you instructed me to do for `hdbscan`. However the tests fail due to a missing `mecab-ko-dic` dependency, and [the first hit on Google](https://bitbucket.org/eunjeon/mecab-ko-dic) is all in Korean, which makes sense for a Korean dictionary package. I am not sure how to proceed at the moment, perhaps you have an idea?

2018-04-04 22:11 UTC, dotlambda commented
I updated all expressions so that the tests pass and so that all packages are tested. Please have a look.

2018-04-05 08:31 UTC, ixxie commented
Awesome, so I guess we are done :)

2018-04-05 08:38 UTC, merged