linuxPackages.evdi: 1.5.0 -> 1.5.0.2
NixOS/nixpkgs pull request #37791
Opened 2018-03-25 19:55 UTC by ryantm

Semi-automatic update generated by https://github.com/ryantm/nix-update tools.

This update was made based on information from https://repology.org/metapackage/evdi/versions.

These checks were done:

- built on NixOS
- Warning: no binary found that responded to help or version flags. (This warning appears even if the package isn't expected to have binaries.)
- found 1.5.0.2 with grep in /nix/store/hngckzkz4hn1qx4v6j50kdxkd775nfhr-evdi-1.5.0.2
- directory tree listing: https://gist.github.com/47526fd1bae00c70366d3fceb27b8b49

2018-03-25 20:16 UTC, GrahamcOfBorg commented
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37791&attempt_id=7136510a-69eb-4bc6-9de5-6437a173b95d)

The following builds were skipped because they don't evaluate on x86_64-darwin: linuxPackages.evdi

<details><summary>Partial log (click to expand)</summary><p>

```
while evaluating the attribute 'linux_4_14' at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/top-level/all-packages.nix[0m:13333:3:
while evaluating 'callPackageWith' at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix[0m:113:35, called from [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/top-level/all-packages.nix[0m:13333:16:
while evaluating 'makeOverridable' at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix[0m:72:24, called from [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix[0m:117:8:
while evaluating anonymous function at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/os-specific/linux/kernel/linux-4.14.nix[0m:1:1, called from [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix[0m:74:12:
while evaluating 'buildLinux' at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/top-level/all-packages.nix[0m:13614:16, called from [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/os-specific/linux/kernel/linux-4.14.nix[0m:5:1:
while evaluating 'callPackageWith' at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix[0m:113:35, called from [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/top-level/all-packages.nix[0m:13614:23:
while evaluating 'makeOverridable' at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix[0m:72:24, called from [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix[0m:117:8:
while evaluating anonymous function at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/os-specific/linux/kernel/generic.nix[0m:1:1, called from [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/lib/customisation.nix[0m:74:12:
assertion failed at [1m/private/var/lib/ofborg/checkout/repo/38dca4e3aa6bca43ea96d2fcc04e8229/builder/lnl7-mac/pkgs/os-specific/linux/kernel/generic.nix[0m:45:1

```
</p></details>

2018-03-25 20:42 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37791&attempt_id=412ca431-7bb7-4c53-a4da-09dcef94a177)

Attempted: linuxPackages.evdi

<details><summary>Partial log (click to expand)</summary><p>

```
make[5]: *** [/nix/store/ppa9alxarcg75ps2xwpky5x88jc93ncy-linux-4.14.30-dev/lib/modules/4.14.30/source/scripts/Makefile.build:329: /build/source/module/evdi_drv.o] Error 1
make[4]: *** [/nix/store/ppa9alxarcg75ps2xwpky5x88jc93ncy-linux-4.14.30-dev/lib/modules/4.14.30/source/Makefile:1519: _module_/build/source/module] Error 2
make[3]: *** [Makefile:146: sub-make] Error 2
make[2]: *** [Makefile:24: __sub-make] Error 2
make[2]: Leaving directory '/nix/store/ppa9alxarcg75ps2xwpky5x88jc93ncy-linux-4.14.30-dev/lib/modules/4.14.30/build'
make[1]: *** [Makefile:57: module] Error 2
make[1]: Leaving directory '/build/source/module'
make: *** [Makefile:8: all] Error 2
builder for '/nix/store/9v6pgaclsagqmv0lxz75za74bs8q198i-evdi-1.5.0.2.drv' failed with exit code 2
[31;1merror:[0m build of '/nix/store/9v6pgaclsagqmv0lxz75za74bs8q198i-evdi-1.5.0.2.drv' failed
```
</p></details>

2018-03-25 20:57 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.37791&attempt_id=fb80c647-a328-4064-903b-91e33f2fb1c4)

Attempted: linuxPackages.evdi

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking RPATHs of ELF executables and libraries in /nix/store/yxv7p3c0i9lsrklz3p059igp70finbfw-evdi-1.5.0.2
shrinking /nix/store/yxv7p3c0i9lsrklz3p059igp70finbfw-evdi-1.5.0.2/lib/modules/4.14.30/kernel/drivers/gpu/drm/evdi/evdi.ko
wrong ELF type
shrinking /nix/store/yxv7p3c0i9lsrklz3p059igp70finbfw-evdi-1.5.0.2/lib/libevdi.so
strip is /nix/store/fzcs0fn6bb04m82frhlb78nc03ny3w55-binutils-2.28.1/bin/strip
stripping (with command strip and flags -S) in /nix/store/yxv7p3c0i9lsrklz3p059igp70finbfw-evdi-1.5.0.2/lib
patching script interpreter paths in /nix/store/yxv7p3c0i9lsrklz3p059igp70finbfw-evdi-1.5.0.2
checking for references to /build in /nix/store/yxv7p3c0i9lsrklz3p059igp70finbfw-evdi-1.5.0.2...
wrong ELF type
/nix/store/yxv7p3c0i9lsrklz3p059igp70finbfw-evdi-1.5.0.2
```
</p></details>

2018-04-23 16:36 UTC, matthewbauer requested changes
See @GrahamcOfBorg log

2018-09-02 00:26 UTC, ryantm commented
Closing in favor of @r-ryantm doing these.

2018-09-02 00:26 UTC, closed without merging