pythonPackages.mrbob: fix build
NixOS/nixpkgs pull request #37950
Opened 2018-03-27 22:57 UTC by Ma27

###### Motivation for this change

Tests broke on Hydra as the `checkPhase` wasn't configured properly. By
explicitly relying on `nosetests` and injecting `LC_ALL` into the
`checkPhase` the tests work again.

The license (bsd3) according to `LICENSE` distributed with the upstream
package wasn't specified in the meta section which could've caused legal
issues.

The expression has been moved into its own file to reduce the length and
complexity of `pkgs/top-level/python-packages.nix`.

See https://hydra.nixos.org/build/70689499/log
See #36453

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-03-30 15:32 UTC, dotlambda requested changes

2018-03-30 15:32 UTC, dotlambda commented on pkgs/development/python-modules/mrbob/default.nix
> +    ++ (lib.optionals isPy26 [ importlib ordereddict ]);
This line can be dropped as Python 2.6 is no longer supported.

2018-03-30 15:32 UTC, dotlambda commented on pkgs/development/python-modules/mrbob/default.nix
> +  buildInputs = [ glibcLocales mock ];
`checkInputs`

2018-03-30 15:32 UTC, dotlambda commented on pkgs/development/python-modules/mrbob/default.nix
> +    homepage = https://github.com/domenkozar/mr.bob.git;
Drop the `.git` suffix here.

2018-03-31 08:18 UTC, Ma27 commented
@dotlambda fine now?

2018-03-31 14:57 UTC, merged

2018-03-31 14:57 UTC, dotlambda commented
@Ma27 Thanks for fixing so much stuff!

2018-03-31 15:06 UTC, dotlambda commented
Backported in cde1f31f28cff9cf0a471d9ef0ba7c9b69e7b340