python-docx: init at 0.8.6
NixOS/nixpkgs pull request #38722
Opened 2018-04-11 05:08 UTC by AJChapman

###### Motivation for this change
This library is a required dependency for something I need to build.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-04-11 05:38 UTC, FRidh requested changes

2018-04-11 05:38 UTC, FRidh commented on pkgs/development/python-modules/python-docx/default.nix
> +  name = "${pname}-${version}";
The `name` attribute is added by `buildPython*` and should therefore be removed.

2018-04-11 05:38 UTC, FRidh commented
@GrahamcOfBorg build python3.pkgs.python-docx

2018-04-11 05:38 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38722&attempt_id=17d85b55-9904-48cf-9cd6-3d7042129e84)

Attempted: python3.pkgs.python-docx

<details><summary>Partial log (click to expand)</summary><p>

```
Reading https://pypi.python.org/simple/pytest/
Download error on https://pypi.python.org/simple/pytest/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'pytest' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for pytest
error: Could not find suitable distribution for Requirement.parse('pytest')
builder for '/nix/store/dimjbvxwszqizm73l14wprfhcg6akls6-python3.6-python-docx-0.8.6.drv' failed with exit code 1
[31;1merror:[0m build of '/nix/store/dimjbvxwszqizm73l14wprfhcg6akls6-python3.6-python-docx-0.8.6.drv' failed
```
</p></details>

2018-04-11 05:39 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38722&attempt_id=d74c78ab-fb6b-408e-81c5-2e895d3dab2f)

Attempted: python3.pkgs.python-docx

<details><summary>Partial log (click to expand)</summary><p>

```
Reading https://pypi.python.org/simple/pytest/
Download error on https://pypi.python.org/simple/pytest/: [Errno -2] Name or service not known -- Some packages may not be found!
Couldn't find index page for 'pytest' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.python.org/simple/
Download error on https://pypi.python.org/simple/: [Errno -2] Name or service not known -- Some packages may not be found!
No local packages or working download links found for pytest
error: Could not find suitable distribution for Requirement.parse('pytest')
builder for '/nix/store/dwp9vg65yjwsxw4qsr2kdgg8hqac5rq3-python3.6-python-docx-0.8.6.drv' failed with exit code 1
[31;1merror:[0m build of '/nix/store/dwp9vg65yjwsxw4qsr2kdgg8hqac5rq3-python3.6-python-docx-0.8.6.drv' failed
```
</p></details>

2018-04-11 05:39 UTC, GrahamcOfBorg commented
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38722&attempt_id=ecdf96d7-c5f2-441d-9b0c-22e95ed9df0c)

Attempted: python3.pkgs.python-docx

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest file 'python_docx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_docx.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/4vbr4mknj177smwa1zp4frs54syj62fv-python3.6-python-docx-0.8.6
```
</p></details>

2018-04-11 05:42 UTC, FRidh commented
Test dependencies are missing.

2018-04-11 11:07 UTC, AJChapman commented
I may have fixed these, not sure if my nix.useSandbox = true is working...

2018-04-11 11:07 UTC, AJChapman commented
@GrahamcOfBorg build python3.pkgs.python-docx

2018-04-12 06:13 UTC, AJChapman commented
Ok @FRidh, I think I have it working now.

2018-04-13 08:43 UTC, dotlambda requested changes
Please squash the commits and use
```
pythonPackages.python-docx: init at 0.8.6
```
as the commit message.

2018-04-13 08:43 UTC, dotlambda commented on pkgs/development/python-modules/python-docx/default.nix
> +  buildInputs = [ behave lxml pytest pyparsing mock ];
lxml belongs into `propagatedBuildInputs`, the rest into `checkInputs`

2018-04-13 08:43 UTC, dotlambda commented on pkgs/development/python-modules/python-docx/default.nix
> +    homepage = "https://python-docx.readthedocs.io/en/latest/";
no quotes

2018-04-13 08:44 UTC, dotlambda commented
@GrahamcOfBorg build python3.pkgs.python-docx

2018-04-13 08:45 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38722&attempt_id=ec01984c-26da-406c-8ad0-ae3f942a4012)

Attempted: python3.pkgs.python-docx

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest file 'python_docx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_docx.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.002s

OK
/nix/store/yb8p86g2j1qhh5r80a1fmkhpfh2vgki5-python3.6-python-docx-0.8.6
```
</p></details>

2018-04-13 08:45 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38722&attempt_id=7a596b80-3752-40a8-90f0-be95da8b6268)

Attempted: python3.pkgs.python-docx

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest file 'python_docx.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'python_docx.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/hv5qp66hvnh0k9nwzxny6siiwanznc81-python3.6-python-docx-0.8.6
```
</p></details>

2018-04-13 08:47 UTC, dotlambda commented
> Ran 0 tests in 0.000s

Please specify an appropriate `checkPhase`, e.g.
```
checkPhase = ''
  py.test
'';
```

2018-04-15 00:45 UTC, AJChapman commented
checkPhase added, dependencies updated, commits squashed, and commit message updated. Thanks for the thorough review!

2018-04-15 05:59 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.python-docx python3.pkgs.python-docx

2018-04-15 06:00 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38722&attempt_id=5a616a60-5f09-4ca1-91e5-83a685d5d16c)

Attempted: python2.pkgs.python-docx, python3.pkgs.python-docx

<details><summary>Partial log (click to expand)</summary><p>

```

=============================== warnings summary ===============================
tests/styles/test_styles.py::DescribeStyles::()::it_can_get_a_style_by_id[getitem_id_fixture0]
  /build/python-docx-0.8.6/docx/styles/styles.py:54: UserWarning: style lookup by style_id is deprecated. Use style name as key instead.
    warn(msg, UserWarning)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=================== 1354 passed, 1 warnings in 5.45 seconds ====================
/nix/store/k2prjffaa6kggi2sskgncy1l059pwi9x-python2.7-python-docx-0.8.6
/nix/store/dnqkqpmz84zws4ysb1fw7ja86lspbdj9-python3.6-python-docx-0.8.6
```
</p></details>

2018-04-15 06:01 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38722&attempt_id=d90e24bf-3914-40c2-a135-da1f0bea6906)

Attempted: python2.pkgs.python-docx, python3.pkgs.python-docx

<details><summary>Partial log (click to expand)</summary><p>

```

=============================== warnings summary ===============================
tests/styles/test_styles.py::DescribeStyles::()::it_can_get_a_style_by_id[getitem_id_fixture0]
  /build/python-docx-0.8.6/docx/styles/styles.py:54: UserWarning: style lookup by style_id is deprecated. Use style name as key instead.
    warn(msg, UserWarning)

-- Docs: http://doc.pytest.org/en/latest/warnings.html
=================== 1354 passed, 1 warnings in 38.85 seconds ===================
/nix/store/aiphsx26j5xzg5r4v83xld7np6qpj65k-python2.7-python-docx-0.8.6
/nix/store/i3nr5wlvyzzbpq7i7fz53wn24fjpxxbg-python3.6-python-docx-0.8.6
```
</p></details>

2018-04-15 06:03 UTC, merged