pythonPackages.fpylll: init at 0.3.0dev
NixOS/nixpkgs pull request #38790
Opened 2018-04-11 17:09 UTC by timokau

###### Motivation for this change

Package `fpylll`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-04-12 16:50 UTC, dotlambda commented on pkgs/development/python-modules/fpylll/default.nix
> +    description = "A Python interface for fpylll";
A Python interface for fplll

2018-04-12 16:52 UTC, dotlambda requested changes
The website says

> fpylll also relies on py.test for testing Python

Please specify an appropriate `checkPhase`.

2018-04-13 15:38 UTC, timokau commented
I added the `checkPhase`, added a fplll upgrade that is necessary for fpylll and added a numpy dependency to pass the tests.

2018-04-13 15:40 UTC, dotlambda commented on pkgs/development/python-modules/fpylll/default.nix
> +    maintainers = with lib.maintainers; [ timokau ];
License?

2018-04-13 15:40 UTC, dotlambda commented on pkgs/development/python-modules/fpylll/default.nix
> +    numpy
Some of these belong in `propagatedBuildInputs`.

2018-04-13 15:50 UTC, timokau commented on pkgs/development/python-modules/fpylll/default.nix
> +    maintainers = with lib.maintainers; [ timokau ];
Added.

2018-04-13 15:52 UTC, dotlambda commented on pkgs/development/python-modules/fpylll/default.nix
> +    license = lib.licenses.gpl2;
> fpylll is licensed under the GPLv2+

https://github.com/fplll/fpylll#attribution--license

2018-04-14 07:30 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.fpyll python3.pkgs.fpyll

2018-04-14 07:30 UTC, GrahamcOfBorg commented
No attempt on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38790&attempt_id=c8b684b9-be73-4cfe-a592-350f5f3f89f4)

The following builds were skipped because they don't evaluate on x86_64-linux: python2.pkgs.fpyll, python3.pkgs.fpyll

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `python2.pkgs.fpyll' because:
error: attribute ‘fpyll’ in selection path ‘python2.pkgs.fpyll’ not found

Cannot nix-instantiate `python3.pkgs.fpyll' because:
error: attribute ‘fpyll’ in selection path ‘python3.pkgs.fpyll’ not found

```
</p></details>

2018-04-14 07:30 UTC, GrahamcOfBorg commented
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38790&attempt_id=d48c9a22-2ba0-4156-9a71-3a08a577a663)

The following builds were skipped because they don't evaluate on aarch64-linux: python2.pkgs.fpyll, python3.pkgs.fpyll

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `python2.pkgs.fpyll' because:
[31;1merror:[0m attribute 'fpyll' in selection path 'python2.pkgs.fpyll' not found

Cannot nix-instantiate `python3.pkgs.fpyll' because:
[31;1merror:[0m attribute 'fpyll' in selection path 'python3.pkgs.fpyll' not found

```
</p></details>

2018-04-14 07:32 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.fpyll python3.pkgs.fpylll

2018-04-14 07:35 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38790&attempt_id=53e1a5fc-be9e-4b77-9dcd-5e12774fc47b)

Attempted: python3.pkgs.fpylll

The following builds were skipped because they don't evaluate on x86_64-linux: python2.pkgs.fpyll

<details><summary>Partial log (click to expand)</summary><p>

```
tests/test_numpy.py ..                                                   [ 70%]
tests/test_precision.py .                                                [ 75%]
tests/test_pruner.py .                                                   [ 79%]
tests/test_random.py .                                                   [ 83%]
tests/test_simple_bkz.py ..                                              [ 91%]
tests/test_strategies.py .                                               [ 95%]
tests/test_util.py .                                                     [100%]

========================== 24 passed in 21.62 seconds ==========================
/nix/store/zmkqa0y4dqba09z2wppw5dssnm4qpgc6-python3.6-fpylll-0.3.0dev
```
</p></details>

2018-04-14 07:38 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.fpylll python3.pkgs.fpylll

2018-04-14 07:40 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38790&attempt_id=770fdd99-1ae9-4746-b923-e94852433a02)

Attempted: python2.pkgs.fpylll, python3.pkgs.fpylll

<details><summary>Partial log (click to expand)</summary><p>

```
tests/test_precision.py .                                                [ 75%]
tests/test_pruner.py .                                                   [ 79%]
tests/test_random.py .                                                   [ 83%]
tests/test_simple_bkz.py ..                                              [ 91%]
tests/test_strategies.py .                                               [ 95%]
tests/test_util.py .                                                     [100%]

========================== 24 passed in 20.36 seconds ==========================
/nix/store/fxxl73a71kq1kr7naxx0g4hf63zq4a9k-python2.7-fpylll-0.3.0dev
/nix/store/zmkqa0y4dqba09z2wppw5dssnm4qpgc6-python3.6-fpylll-0.3.0dev
```
</p></details>

2018-04-14 08:33 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38790&attempt_id=7b415674-8b09-4b5c-87c7-fdd7019dc19b)

Attempted: python3.pkgs.fpylll

The following builds were skipped because they don't evaluate on aarch64-linux: python2.pkgs.fpyll

<details><summary>Partial log (click to expand)</summary><p>

```
                 from memoryviewattrs.cpp:580:
/nix/store/i8py6fv0irvkl3s3kndqpw8szl1rzcic-python3.6-numpy-1.14.2/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
acquired default
acquired Global_A
building of '/nix/store/l60jan1mgs2yd0lnkmsprzjapx4rynv9-python3.6-Cython-0.28.1.drv' timed out after 3600 seconds
cannot build derivation '/nix/store/bc3rqbznfssmzrpc90wgm6aygjqpb60v-python3.6-cysignals-1.6.9.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nmrkn3c8lb7yvvkd4a42g90grba3qyrg-python3.6-fpylll-0.3.0dev.drv': 2 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/nmrkn3c8lb7yvvkd4a42g90grba3qyrg-python3.6-fpylll-0.3.0dev.drv' failed
```
</p></details>

2018-04-14 08:41 UTC, timokau commented
```
building of '/nix/store/l60jan1mgs2yd0lnkmsprzjapx4rynv9-python3.6-Cython-0.28.1.drv' timed out after 3600 seconds
```

Maybe ofBorg should indicate when a failure is due to a timeout.

2018-04-14 09:33 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38790&attempt_id=7ef58368-d418-45fa-b3ba-f3e096325527)

Attempted: python2.pkgs.fpylll, python3.pkgs.fpylll

<details><summary>Partial log (click to expand)</summary><p>

```
                 from memoryviewattrs.cpp:580:
/nix/store/i8py6fv0irvkl3s3kndqpw8szl1rzcic-python3.6-numpy-1.14.2/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:15:2: warning: #warning "Using deprecated NumPy API, disable it by " "#defining NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
 #warning "Using deprecated NumPy API, disable it by " \
  ^~~~~~~
acquired default
acquired Global_A
building of '/nix/store/l60jan1mgs2yd0lnkmsprzjapx4rynv9-python3.6-Cython-0.28.1.drv' timed out after 3600 seconds
cannot build derivation '/nix/store/bc3rqbznfssmzrpc90wgm6aygjqpb60v-python3.6-cysignals-1.6.9.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/nmrkn3c8lb7yvvkd4a42g90grba3qyrg-python3.6-fpylll-0.3.0dev.drv': 2 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/ibiqnqwa42cjpi1bpnfvvdclmjnzicfm-python2.7-fpylll-0.3.0dev.drv', '/nix/store/nmrkn3c8lb7yvvkd4a42g90grba3qyrg-python3.6-fpylll-0.3.0dev.drv' failed
```
</p></details>

2018-04-14 10:19 UTC, merged