nixos/prosody: add user/group options, fix pidfile path
NixOS/nixpkgs pull request #38820
Opened 2018-04-12 05:02 UTC by brainrape

###### Motivation for this change

Prosody service options needed improvement
- There were no user/group setting
- The pidfile was in the `dataDir`, not under `/run` as usual

###### Things done

- added `services.prosody.user` and `services.prosody.group` options and implementation
- changed pidfile path, added `RuntimeDirectory` to systemd service config

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-04-12 05:04 UTC, brainrape commented
@GrahamcOfBorg test prosody

2018-04-12 05:04 UTC, brainrape commented
@GrahamcOfBorg test prosody

2018-04-12 05:08 UTC, brainrape commented
related: #35540 #38643
thanks @gnidorah

2018-04-12 06:03 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38820&attempt_id=9fc74c28-260f-4a60-803c-5d87669f9fcb)

Attempted: tests.prosody

<details><summary>Partial log (click to expand)</summary><p>

```
building '/nix/store/wzd2arnq16jp33l7lbvvckgh7aahn6dp-system-units.drv'...
building '/nix/store/ipdc5nicy3p22gsd3w90h3x4nrg6w3wy-user-units.drv'...
cannot build derivation '/nix/store/0arjcl48hdh3rr07c9mxwzzjg89n2rp0-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/79hyj98whlr68vjjradzfzv41p8daiir-nixos-system-machine-18.09.git.6fffa53.drv': 5 dependencies couldn't be built
cannot build derivation '/nix/store/vmj1xn1l7b741islzcg27sn1c3g0yh6w-closure-info.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z5g4a260v69jh8l2907rqib59l8jz4pv-run-nixos-vm.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/76ba55ra44rp9f0p0v06jpiy8cpfjd78-nixos-vm.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/h0c0jdgd1pax56z6as4in6a4qniv3h83-nixos-test-driver-prosody.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dc3wj6s4bxpz8xzaxd6zjy2pl7l1rvv7-vm-test-run-prosody.drv': 1 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/dc3wj6s4bxpz8xzaxd6zjy2pl7l1rvv7-vm-test-run-prosody.drv' failed
```
</p></details>

2018-04-12 06:03 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38820&attempt_id=673b951e-275e-4548-9199-5d67f7ed8587)

Attempted: tests.prosody

<details><summary>Partial log (click to expand)</summary><p>

```
cannot build derivation '/nix/store/nv3dwh11bbql7afchzcammcchbfk96xj-stage-1-init.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fgvp327kx0ahh3k7hxlmvkmnd2fwar4m-initrd.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0arjcl48hdh3rr07c9mxwzzjg89n2rp0-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/79hyj98whlr68vjjradzfzv41p8daiir-nixos-system-machine-18.09.git.6fffa53.drv': 5 dependencies couldn't be built
cannot build derivation '/nix/store/vmj1xn1l7b741islzcg27sn1c3g0yh6w-closure-info.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z5g4a260v69jh8l2907rqib59l8jz4pv-run-nixos-vm.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/76ba55ra44rp9f0p0v06jpiy8cpfjd78-nixos-vm.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/h0c0jdgd1pax56z6as4in6a4qniv3h83-nixos-test-driver-prosody.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dc3wj6s4bxpz8xzaxd6zjy2pl7l1rvv7-vm-test-run-prosody.drv': 1 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/dc3wj6s4bxpz8xzaxd6zjy2pl7l1rvv7-vm-test-run-prosody.drv' failed
```
</p></details>

2018-04-12 06:03 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38820&attempt_id=6261fe8f-1168-49b1-9f88-cb9e6267513f)

Attempted: tests.prosody

<details><summary>Partial log (click to expand)</summary><p>

```
cannot build derivation '/nix/store/nv3dwh11bbql7afchzcammcchbfk96xj-stage-1-init.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/fgvp327kx0ahh3k7hxlmvkmnd2fwar4m-initrd.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/0arjcl48hdh3rr07c9mxwzzjg89n2rp0-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/79hyj98whlr68vjjradzfzv41p8daiir-nixos-system-machine-18.09.git.6fffa53.drv': 5 dependencies couldn't be built
cannot build derivation '/nix/store/vmj1xn1l7b741islzcg27sn1c3g0yh6w-closure-info.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/z5g4a260v69jh8l2907rqib59l8jz4pv-run-nixos-vm.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/76ba55ra44rp9f0p0v06jpiy8cpfjd78-nixos-vm.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/h0c0jdgd1pax56z6as4in6a4qniv3h83-nixos-test-driver-prosody.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/dc3wj6s4bxpz8xzaxd6zjy2pl7l1rvv7-vm-test-run-prosody.drv': 1 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/dc3wj6s4bxpz8xzaxd6zjy2pl7l1rvv7-vm-test-run-prosody.drv' failed
```
</p></details>

2018-04-12 07:08 UTC, brainrape commented
@GrahamcOfBorg build prosody

2018-04-12 07:09 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38820&attempt_id=b452f99a-a6af-4c1c-83f8-516f50c4f384)

Attempted: prosody

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/idvkqv2vjwzycp3kmd9lhdz0ai7vgka3-prosody-0.10.0
```
</p></details>

2018-04-12 17:07 UTC, ghost approved these changes
Thanks! Works for me, `nixos/prosody: fix pidfile path` change fixed working when `dataDir` is put under home directory, say `/home/user/prosody`. Before there was an error `Couldn't write pidfile at /home/gnidorah/prosody/prosody.pid; /home/gnidorah/prosody/prosody.pid: Permission denied`

2018-04-12 17:12 UTC, dotlambda requested changes

2018-04-12 17:12 UTC, dotlambda commented on nixos/modules/services/networking/prosody.nix
> +      group = "${cfg.group}";
`inherit (cfg) group`

2018-04-12 17:12 UTC, dotlambda commented on nixos/modules/services/networking/prosody.nix
> +        Group = "${cfg.user}";
```
User = cfg.user;
Group = cfg.group;
```

2018-04-12 17:12 UTC, dotlambda commented on nixos/modules/services/networking/prosody.nix
> +    users.extraUsers."${cfg.user}" = {
I think the user should only be created if `cfg.user == prosody`. Same for the group.

2018-04-13 09:34 UTC, brainrape commented
Fixed, thanks for the review!

2018-04-13 09:36 UTC, dotlambda commented on nixos/modules/services/networking/prosody.nix
> +    users.extraUsers.prosody = mkIf (cfg.user == prosody) {
prosody should be in quotes

2018-04-13 09:41 UTC, brainrape commented
Fixed, tested. Thanks!

2018-04-13 09:42 UTC, dotlambda approved these changes

2018-04-13 09:46 UTC, brainrape commented
@GrahamcOfBorg test prosody

2018-04-13 09:47 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38820&attempt_id=89dddab0-960b-4a7f-bfae-7965b613da38)

Attempted: tests.prosody

<details><summary>Partial log (click to expand)</summary><p>

```
building path(s) ‘/nix/store/005gypcy0fqpzsrkfvpqfkzxz8fv9dwi-etc’
building path(s) ‘/nix/store/p5gshmjb1m7kf47y94yar6cijkrdjnhs-nixos-system-machine-18.09.git.f7fdeaf’
building path(s) ‘/nix/store/40w1d9khqv1v622jg574nw3z7k5c6w92-closure-info’
/nix/store/aj9rz4k3xvg8q9fzqfnb0q123707zp0n-builder: line 1: .attrs.sh: No such file or directory
builder for ‘/nix/store/2g4pspqm1dpw2262rqwkzh34x3i40q69-closure-info.drv’ failed with exit code 1
cannot build derivation ‘/nix/store/c5s0dp21mk9pl2nz1kaf7jdnybs7f13l-run-nixos-vm.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/bdbv1466rpl66h9d8shf1s96pmx7lyy1-nixos-vm.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/v7qsizw9vxfjn61pjmz7p90sj1sqkm38-nixos-test-driver-prosody.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/n74kisayrc2q0fcmlrrl64f32py360r8-vm-test-run-prosody.drv’: 1 dependencies couldn't be built
error: build of ‘/nix/store/n74kisayrc2q0fcmlrrl64f32py360r8-vm-test-run-prosody.drv’ failed
```
</p></details>

2018-04-13 09:53 UTC, dotlambda commented
Ran the test manually and can confirm it works.

2018-04-13 09:55 UTC, merged

2018-04-13 09:57 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.38820&attempt_id=c30ec0ce-7db2-41ca-8813-4eabfa9910ed)

Attempted: tests.prosody

<details><summary>Partial log (click to expand)</summary><p>

```
cannot build derivation '/nix/store/1qfxxq5zknf36r503979xk3xb4s7wn0q-etc.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/p70rjwwi7y6k2gxh0wprsaard4pa0wh1-stage-1-init.sh.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/7md0p3072i2bylq4r66cq7gkablm52kh-initrd.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/il8pcycpb0azyg27jscfg71ggajyj6sv-nixos-system-machine-18.09.git.c301075.drv': 5 dependencies couldn't be built
cannot build derivation '/nix/store/5nf5g9hs465snp61n206fr3hfybxn62y-closure-info.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/9i2gjvh8nspdhd27q67jvx55dfw0ih9n-run-nixos-vm.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/05g18a4ldkw9avaijqhr6vkdskc396xk-nixos-vm.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/ii5wr7rr08ckz9rj91mvqvj4k9srxhhc-nixos-test-driver-prosody.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/k3r7j4903flvvhh61j251f88gbyc7cb2-vm-test-run-prosody.drv': 1 dependencies couldn't be built
[31;1merror:[0m build of '/nix/store/k3r7j4903flvvhh61j251f88gbyc7cb2-vm-test-run-prosody.drv' failed
```
</p></details>