oauth2_proxy: refactor service
NixOS/nixpkgs pull request #39002
Opened 2018-04-16 12:13 UTC by yorickvP

###### Motivation for this change

This service was missing some options (and mandating some others). I refactored it to use types to determine how to pass arguments, and added a `keyFile` option to optionally pass sensitive information.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-04-17 12:02 UTC, mkaito requested changes

2018-04-17 12:02 UTC, mkaito commented on nixos/modules/services/security/oauth2_proxy.nix
> +    };
Document the fact that `null` means not passing the option to the binary in order to let it use the upstream default.

2018-04-27 15:02 UTC, mkaito approved these changes

2018-04-27 19:15 UTC, lukateras approved these changes

2018-04-27 19:15 UTC, merged