bonzomatic: init at 2018-03-29
NixOS/nixpkgs pull request #39171
Opened 2018-04-19 19:18 UTC by nocent

###### Motivation for this change
Adds Bonzomatic, a live-coding tool for writing 2D fragment/pixel shaders.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I added the unfreeRedistributable license, as the upstream repo contains [libbass.so](https://www.un4seen.com/bass.html#license) which is only free for non-commercial use.

2018-04-20 09:57 UTC, infinisil approved these changes
Built and tested this locally, works without problems. It need a simple `config.json` file in the current working directory to get started though. Here's one:

```json
{
  "window":{
    "width":1440,
    "height":900,
    "fullscreen":false
  },
  "font":{
    "file":"/nix/store/h17zrpn0zfgx0p65ic457kb9plwll3n0-nerdfonts-1.1.0/share/fonts/truetype/NerdFonts/Iosevka Nerd Font Complete.ttf",
  }
}
```

(I got the font path with `fc-list`)

2018-04-20 09:59 UTC, Infinisil commented
@GrahamcOfBorg build bonzomatic

2018-04-20 09:59 UTC, GrahamcOfBorg commented
No attempt on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.39171&attempt_id=ab44fee1-6008-45c8-8915-b86933339828)

The following builds were skipped because they don't evaluate on x86_64-linux: bonzomatic

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-04-20 10:00 UTC, GrahamcOfBorg commented
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.39171&attempt_id=f2740ed8-4b2c-4d78-a99e-e3f059fae064)

The following builds were skipped because they don't evaluate on aarch64-linux: bonzomatic

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnfree = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnfree = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-04-24 14:44 UTC, nlewo requested changes

2018-04-24 14:44 UTC, nlewo commented on pkgs/applications/editors/bonzomatic/default.nix
> +  inherit name;
Please add a version in this package (the version is used by nix-env to upgarde). Something such as:
```
name = "${pname}-${version}"
pname = "bonzomatic";
version = "2018-03-29";
```

2018-04-24 14:44 UTC, nlewo commented on pkgs/applications/editors/bonzomatic/default.nix
> +  name = "bonzomatic";
By using a recursive attribute set as derivation argument, this is not required. You can see the `rec` keyword.

2018-04-24 15:58 UTC, nlewo commented
It would be nice to provide a default configuration file since it is not trivial to create it. This would be useful for reviewers to test future updates. This could be addressed in another PR.
Thanks.

2018-04-24 15:58 UTC, merged