Add nix-prefetch-github
NixOS/nixpkgs pull request #39214
Opened 2018-04-20 09:34 UTC by seppeljordan

###### Motivation for this change
This PR adds an application to nixpkgs to "prefetch" sources from github.  For this purpose I also added a python package called "effect", because it is a dependency of "nix-prefetch-github"

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-04-20 10:12 UTC, dotlambda requested changes

2018-04-20 10:12 UTC, dotlambda commented on pkgs/build-support/nix-prefetch-github/default.nix
> +    description = "prefetch sources from github";
https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes

2018-04-20 10:12 UTC, dotlambda commented on pkgs/build-support/nix-prefetch-github/default.nix
> +  name = "nix-prefetch-github-${version}";
Please use `pname` and `version` instead.

2018-04-20 10:12 UTC, dotlambda commented on pkgs/build-support/nix-prefetch-github/default.nix
> +    rev = "b12ab7fe187924d8536d27b2ddf3bcccd2612b32";
It would be nicer to create releases/tags in the GitHub repo.

2018-04-20 10:12 UTC, dotlambda commented on pkgs/development/python-modules/effect/default.nix
> +    description = "pure effects for Python";
https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes

2018-04-20 10:12 UTC, dotlambda commented on pkgs/development/python-modules/effect/default.nix
> +  doCheck = false;
Why?

2018-04-20 10:12 UTC, dotlambda commented on pkgs/top-level/all-packages.nix
> +  nix-prefetch-github = callPackages ../build-support/nix-prefetch-github {
`callPackage`

2018-04-20 10:12 UTC, dotlambda commented on pkgs/build-support/nix-prefetch-github/default.nix
> +{ buildPythonApplication
Please pass `python3` or `python3Packages` instead.

2018-04-20 10:36 UTC, FRidh commented on pkgs/development/python-modules/effect/default.nix
> +pname = "effect";
no need to keep these out

2018-05-16 13:49 UTC, seppeljordan commented
Hi, I think that I included all the suggestions that were given.  Please tell me if there is more that I should change with this PR

2018-05-22 11:11 UTC, dotlambda requested changes

2018-05-22 11:11 UTC, dotlambda commented on pkgs/development/python-modules/effect/default.nix
> +  buildInputs = [
`checkInputs`

2018-05-22 11:11 UTC, dotlambda commented on pkgs/development/python-modules/effect/default.nix
> +in
Drop this `let in`.

2018-05-22 11:11 UTC, dotlambda commented on pkgs/build-support/nix-prefetch-github/default.nix
> +    rev = "b12ab7fe187924d8536d27b2ddf3bcccd2612b32";
Please create tags in your GitHub repo.

2018-05-22 18:27 UTC, seppeljordan commented
@dotlambda thx for the review

2018-05-22 21:07 UTC, yegortimoshenko commented
Maybe, let's phase out `fetchFromGitHub` in favor of `fetchzip`? This needs an RFC.

2018-05-23 15:33 UTC, merged