backup (gem) : remove
NixOS/nixpkgs pull request #40308
Opened 2018-05-10 22:55 UTC by mrVanDalo

###### Motivation for this change

It is not working since 18.03 and nobody than me seems to use it, because I couldn't find a package.
Also I'm not willing to continue maintaining this package.

2018-05-10 23:21 UTC, xeji requested changes
Eval fails, please remove the package from `pkgs/top-level/all-packages.nix`.

2018-05-11 02:32 UTC, mrVanDalo commented
lalalala, (facepalm)

2018-05-11 02:34 UTC, mrVanDalo commented
I don't understand the outpout of borg-eval

2018-05-11 07:48 UTC, xeji approved these changes

2018-05-11 11:17 UTC, merged