rPackages: fix binutils path on Darwin
NixOS/nixpkgs pull request #40360
Opened 2018-05-11 15:06 UTC by mnacamura

###### Motivation for this change

Recent nixpkgs seems to have changed the package in which `otool` and `install_name_tools` are living.

###### Things done

Changed the relevant package paths.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-05-11 23:10 UTC, LnL7 commented
@Ericson2314 is this intensional?

If so what's the difference between `binutils`, `darwin.binutils` and `darwin.cctools`?

2018-05-12 00:23 UTC, Ericson2314 requested changes
I'd just make them all `darwin.binutils`, because that was how it evaluated before. But the bottom two substitutions are fine.

2018-05-12 11:57 UTC, mnacamura commented
@Ericson2314 Thank you for clarification!

2018-05-12 14:28 UTC, matthewbauer commented
Are the subs necessary in the first place? install_name_tool is aleeady in stdenv.

2018-05-12 15:16 UTC, mnacamura commented
They are required. See #34766

2018-05-12 15:49 UTC, mnacamura commented
Right. Adding `which` to the test in #34766 works. My bad.
However, this does not solve another problem in which `which otool` calls `/usr/bin/otool` in a user environment. I think we have two options: to add the subs or to use `propagatedUserEnvPkgs`, maybe?

2018-05-12 15:52 UTC, matthewbauer commented
Oh sorry! I didn't realize this was needed in the user environment. Either this or wrapping the runtime is probably the best route.

2018-05-12 15:52 UTC, merged