nms: init at 0.3.3
NixOS/nixpkgs pull request #40707
Opened 2018-05-17 22:43 UTC by Infinisil

###### Motivation for this change
Saw this one on reddit too, pretty cool tool :)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-05-17 22:58 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.40707&attempt_id=59149731-d455-4e56-96f0-eaf78670c490)

Attempted: nms

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/mp7d9r5v7yfnj78jyxw7lqacw5dbrb0z-nms-0.3.3
shrinking /nix/store/mp7d9r5v7yfnj78jyxw7lqacw5dbrb0z-nms-0.3.3/bin/sneakers
shrinking /nix/store/mp7d9r5v7yfnj78jyxw7lqacw5dbrb0z-nms-0.3.3/bin/nms
gzipping man pages under /nix/store/mp7d9r5v7yfnj78jyxw7lqacw5dbrb0z-nms-0.3.3/share/man/
strip is /nix/store/jk6j4lh9v5mvjdbdc35sj0zffhhf6s56-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/mp7d9r5v7yfnj78jyxw7lqacw5dbrb0z-nms-0.3.3/bin
patching script interpreter paths in /nix/store/mp7d9r5v7yfnj78jyxw7lqacw5dbrb0z-nms-0.3.3
checking for references to /build in /nix/store/mp7d9r5v7yfnj78jyxw7lqacw5dbrb0z-nms-0.3.3...
/nix/store/mp7d9r5v7yfnj78jyxw7lqacw5dbrb0z-nms-0.3.3
```
</p></details>

2018-05-19 09:52 UTC, xeji requested changes
Please add a `meta` attribute with the usual info.

2018-05-19 21:19 UTC, Infinisil commented
Totally forgot about that, added!

2018-05-19 21:25 UTC, xeji approved these changes

2018-05-19 21:26 UTC, merged