m-cli: init at 0.2.5
NixOS/nixpkgs pull request #40724
Opened 2018-05-18 14:07 UTC by yurrriq

###### Motivation for this change

Package the self-described [Swiss Army Knife for macOS](https://github.com/rgcr/m-cli).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2018-05-18 14:31 UTC, yurrriq commented
/ping @lnl7

2018-05-18 19:02 UTC, xeji requested changes
Please add the package to `pkgs/top-level/all-packages.nix`.

2018-05-19 18:53 UTC, yurrriq commented
Thanks, @xeji, I've amended and force pushed.

2018-05-19 19:32 UTC, LnL7 approved these changes

2018-05-19 19:32 UTC, merged