purple-lurch: init 0.6.7
NixOS/nixpkgs pull request #40795
Opened 2018-05-19 21:42 UTC by emmanuelrosa

###### Motivation for this change

This change adds the pidgin/libpurple plugin lurch, which provides an implementation for XEP-0384: OMEMO Encryption. As long as the XMPP server of both parties supports OMEMO, this plugin allows for encrypted messaging. See https://github.com/gkdr/lurch

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `build-use-sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - ~[ ] macOS~ Technically should build on macOS, but I have no way of confirming.
   - [ ] other Linux distributions
- ~[ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))~
- ~[ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`~
- [X] Tested execution of plugin using `pidgin`
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

![omemo-1](https://user-images.githubusercontent.com/13485450/40273287-84f19366-5b8b-11e8-93b2-c7e4a494a8f0.png)
![ememo-2](https://user-images.githubusercontent.com/13485450/40273286-84dbdc24-5b8b-11e8-83f4-67f32c429955.png)

---

2018-05-19 21:49 UTC, emmanuelrosa commented
To add plugin, add `pidgin` as follows:

```
environment.systemPackages = with pkgs; [
    (pidgin.override { plugins = [ purple-lurch]; })
];
```

2018-05-20 01:20 UTC, disassembler requested changes
Thanks for the PR! Just some minor changes and I think this is ready.

2018-05-20 01:20 UTC, disassembler commented on pkgs/applications/networking/instant-messengers/pidgin-plugins/purple-lurch/default.nix
> +  name = "purple-lurch-0.6.7";
split version into it's separate variable

2018-05-20 01:20 UTC, disassembler commented on pkgs/applications/networking/instant-messengers/pidgin-plugins/purple-lurch/default.nix
> +    rev = "3156e14c2dcf9968438aceb7fda8f82eae6f552d";
Since is a release on upstream github repo, just do "v${version}" instead of specifying rev manually.

2018-05-20 22:45 UTC, merged