taffybar: work around repeated arguments bug
NixOS/nixpkgs pull request #41408
Opened 2018-06-03 09:25 UTC by puffnfresh

Fixes #40013

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-06-03 09:28 UTC, peti commented
@GrahamcOfBorg build.haskell.packages.ghc822.taffybar build.haskell.packages.ghc843.taffybar

2018-06-03 09:28 UTC, peti commented
@GrahamcOfBorg build haskell.packages.ghc822.taffybar haskell.packages.ghc843.taffybar

2018-06-03 09:28 UTC, GrahamcOfBorg commented
No attempt on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=61cc9db6-8049-4c34-bcb1-2c30c06aabe7)

The following builds were skipped because they don't evaluate on x86_64-linux: .haskell.packages.ghc822.taffybar, build.haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `.haskell.packages.ghc822.taffybar' because:
error: empty attribute name in selection path '.haskell.packages.ghc822.taffybar'

Cannot nix-instantiate `build.haskell.packages.ghc843.taffybar' because:
error: attribute 'build' in selection path 'build.haskell.packages.ghc843.taffybar' not found

```
</p></details>

2018-06-03 09:28 UTC, GrahamcOfBorg commented
No attempt on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=63569bbf-e5f9-4fb5-a86e-5737da690f61)

The following builds were skipped because they don't evaluate on x86_64-linux: .haskell.packages.ghc822.taffybar, build.haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `.haskell.packages.ghc822.taffybar' because:
error: empty attribute name in selection path '.haskell.packages.ghc822.taffybar'

Cannot nix-instantiate `build.haskell.packages.ghc843.taffybar' because:
error: attribute 'build' in selection path 'build.haskell.packages.ghc843.taffybar' not found

```
</p></details>

2018-06-03 09:29 UTC, GrahamcOfBorg commented
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=a51b41c4-b775-47eb-8d38-236e9504f2c1)

The following builds were skipped because they don't evaluate on x86_64-darwin: .haskell.packages.ghc822.taffybar, build.haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `.haskell.packages.ghc822.taffybar' because:
error: empty attribute name in selection path '.haskell.packages.ghc822.taffybar'

Cannot nix-instantiate `build.haskell.packages.ghc843.taffybar' because:
error: attribute 'build' in selection path 'build.haskell.packages.ghc843.taffybar' not found

```
</p></details>

2018-06-03 09:30 UTC, GrahamcOfBorg commented
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=5b3ee40f-838e-4657-ab53-36cf61f6a97f)

The following builds were skipped because they don't evaluate on x86_64-darwin: haskell.packages.ghc822.taffybar, haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-06-03 09:31 UTC, GrahamcOfBorg commented
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=c2d5841b-ce55-4481-8e01-4463dc7cd7d4)

The following builds were skipped because they don't evaluate on x86_64-darwin: .haskell.packages.ghc822.taffybar, build.haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `.haskell.packages.ghc822.taffybar' because:
error: empty attribute name in selection path '.haskell.packages.ghc822.taffybar'

Cannot nix-instantiate `build.haskell.packages.ghc843.taffybar' because:
error: attribute 'build' in selection path 'build.haskell.packages.ghc843.taffybar' not found

```
</p></details>

2018-06-03 10:11 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=22285040-6a87-48aa-82e3-17544d8aa86c)

Attempted: haskell.packages.ghc822.taffybar, haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
stripping (with command strip and flags -S) in /nix/store/r6sba9zqwp344hlf0y87agqvwzwm81a3-gi-gtk-hs-0.3.6.1/lib
patching script interpreter paths in /nix/store/r6sba9zqwp344hlf0y87agqvwzwm81a3-gi-gtk-hs-0.3.6.1
checking for references to /build in /nix/store/r6sba9zqwp344hlf0y87agqvwzwm81a3-gi-gtk-hs-0.3.6.1...
wrong ELF type
shrinking RPATHs of ELF executables and libraries in /nix/store/4ga474xanbz28gj69jkn0vwkvbn96zhw-gi-gtk-hs-0.3.6.1-doc
strip is /nix/store/92d2ifxcni4n3zx9s8wnkcjlvnx5ajlc-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/4ga474xanbz28gj69jkn0vwkvbn96zhw-gi-gtk-hs-0.3.6.1-doc
checking for references to /build in /nix/store/4ga474xanbz28gj69jkn0vwkvbn96zhw-gi-gtk-hs-0.3.6.1-doc...
cannot build derivation '/nix/store/bhibqr8f02blxd0vimkdqrvhnm8n112w-taffybar-2.1.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/4066c7kansf796rv50alv1aq0f82y6mx-taffybar-2.1.0.drv', '/nix/store/bhibqr8f02blxd0vimkdqrvhnm8n112w-taffybar-2.1.0.drv' failed
```
</p></details>

2018-06-03 12:39 UTC, GrahamcOfBorg commented
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=97e312e4-3977-4ece-a6d1-ea7d88b75bf6)

The following builds were skipped because they don't evaluate on aarch64-linux: .haskell.packages.ghc822.taffybar, build.haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `.haskell.packages.ghc822.taffybar' because:
error: empty attribute name in selection path '.haskell.packages.ghc822.taffybar'

Cannot nix-instantiate `build.haskell.packages.ghc843.taffybar' because:
error: attribute 'build' in selection path 'build.haskell.packages.ghc843.taffybar' not found

```
</p></details>

2018-06-03 12:39 UTC, GrahamcOfBorg commented
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=680b960d-4619-4b00-83fa-82a8a2439719)

The following builds were skipped because they don't evaluate on aarch64-linux: .haskell.packages.ghc822.taffybar, build.haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `.haskell.packages.ghc822.taffybar' because:
error: empty attribute name in selection path '.haskell.packages.ghc822.taffybar'

Cannot nix-instantiate `build.haskell.packages.ghc843.taffybar' because:
error: attribute 'build' in selection path 'build.haskell.packages.ghc843.taffybar' not found

```
</p></details>

2018-06-03 12:41 UTC, GrahamcOfBorg commented
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=df0ae910-294c-42bc-a399-035ff1ad8e32)

The following builds were skipped because they don't evaluate on aarch64-linux: haskell.packages.ghc822.taffybar, haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-06-03 14:05 UTC, peti reviewed
According to https://github.com/NixOS/nixpkgs/pull/41408#issuecomment-394151445 taffybar can't be compiled (due to broken dependencies). Did you test this PR?

2018-06-03 16:48 UTC, Ericson2314 commented on pkgs/development/haskell-modules/configuration-common.nix
> +    strictDeps = true;
Yes!

2018-06-03 16:56 UTC, Ericson2314 commented
I opened #41420 to set this in all haskell derivations. I've been meaning to write an RFC to set it everywhere (and then remove it.)

2018-06-03 17:04 UTC, Ericson2314 approved these changes
While I prefer #41420 as a more permanent solution, this is great if that proves too ambitious.

2018-06-04 12:27 UTC, peti requested changes
According to https://github.com/NixOS/nixpkgs/pull/41408#issuecomment-394151445 taffybar can't be compiled (due to broken dependencies). Did you test this PR?

2018-06-17 18:51 UTC, xeji commented
@GrahamcOfBorg  build taffybar

2018-06-17 18:52 UTC, GrahamcOfBorg commented
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=e53ba8c5-061f-4e8f-98ab-7c42126cc72b)

The following builds were skipped because they don't evaluate on x86_64-darwin: taffybar

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-06-17 18:56 UTC, GrahamcOfBorg commented
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=f613b804-c38d-471d-bc5f-5c788b0340cb)

The following builds were skipped because they don't evaluate on aarch64-linux: taffybar

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-06-17 19:14 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=6686f0df-c0d4-427b-be20-3ec5c70d76aa)

Attempted: taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
Warning: haddock-interfaces: /nix/store/j2k151dmalrlybgccjkxw9i63kxxang5-gi-atk-2.0.15/share/doc/x86_64-linux-ghc-8.2.2/gi-atk-2.0.15/html/gi-atk.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/j2k151dmalrlybgccjkxw9i63kxxang5-gi-atk-2.0.15/share/doc/x86_64-linux-ghc-8.2.2/gi-atk-2.0.15/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /nix/store/9fd03cvs7nbdc8zd77fkiva0nsbjc7nl-gi-gdkx11-3.0.2/share/doc/x86_64-linux-ghc-8.2.2/gi-gdkx11-3.0.2/html/gi-gdkx11.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/9fd03cvs7nbdc8zd77fkiva0nsbjc7nl-gi-gdkx11-3.0.2/share/doc/x86_64-linux-ghc-8.2.2/gi-gdkx11-3.0.2/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /nix/store/8r3rfyclp2i6w5scfhxblwj6ppkihsxm-gi-gtk-3.0.23/share/doc/x86_64-linux-ghc-8.2.2/gi-gtk-3.0.23/html/gi-gtk.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/8r3rfyclp2i6w5scfhxblwj6ppkihsxm-gi-gtk-3.0.23/share/doc/x86_64-linux-ghc-8.2.2/gi-gtk-3.0.23/html doesn't exist or isn't a directory
Warning: haddock-interfaces: /nix/store/3cxws1bxj3sm8ma81zyazrr67i9fx37s-gi-dbusmenugtk3-0.4.2/share/doc/x86_64-linux-ghc-8.2.2/gi-dbusmenugtk3-0.4.2/html/gi-dbusmenugtk3.haddock doesn't exist or isn't a file
Warning: haddock-html: /nix/store/3cxws1bxj3sm8ma81zyazrr67i9fx37s-gi-dbusmenugtk3-0.4.2/share/doc/x86_64-linux-ghc-8.2.2/gi-dbusmenugtk3-0.4.2/html doesn't exist or isn't a directory
building '/nix/store/9iwk6cv3279px9nx1yvpp3s1civq8jr1-taffybar-with-packages.drv'...
/nix/store/2ldqdjxv430033dsgq5i293w8njfbqnl-taffybar-with-packages
```
</p></details>

2018-06-17 19:14 UTC, xeji commented
@GrahamcOfBorg build haskell.packages.ghc822.taffybar haskell.packages.ghc843.taffybar

2018-06-17 19:15 UTC, GrahamcOfBorg commented
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=ec255dce-e288-4d5e-b66c-5ca720ba9992)

The following builds were skipped because they don't evaluate on x86_64-darwin: haskell.packages.ghc822.taffybar, haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-06-17 19:19 UTC, GrahamcOfBorg commented
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=076986bc-6074-4ed3-9e9a-b4d434fcec0d)

The following builds were skipped because they don't evaluate on aarch64-linux: haskell.packages.ghc822.taffybar, haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-06-17 20:02 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41408&attempt_id=94a9b715-66f3-4df9-bc5c-dd7a16d8a3e6)

Attempted: haskell.packages.ghc822.taffybar, haskell.packages.ghc843.taffybar

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking RPATHs of ELF executables and libraries in /nix/store/vfqqj3yzmz5x8wm1nnji20j67h2xfa45-taffybar-2.1.2-data
strip is /nix/store/4mf2xm9p32lzrim927yk92xhx35yaz62-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/vfqqj3yzmz5x8wm1nnji20j67h2xfa45-taffybar-2.1.2-data
checking for references to /build in /nix/store/vfqqj3yzmz5x8wm1nnji20j67h2xfa45-taffybar-2.1.2-data...
shrinking RPATHs of ELF executables and libraries in /nix/store/y02c5p9zqhqwvilj0j8l2dg5vdxmfal7-taffybar-2.1.2-doc
strip is /nix/store/4mf2xm9p32lzrim927yk92xhx35yaz62-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/y02c5p9zqhqwvilj0j8l2dg5vdxmfal7-taffybar-2.1.2-doc
checking for references to /build in /nix/store/y02c5p9zqhqwvilj0j8l2dg5vdxmfal7-taffybar-2.1.2-doc...
/nix/store/8r6cj4v19nyjv98yfhw0vpi0lqcl22px-taffybar-2.1.2
/nix/store/y7asn3p0gs50agkaj3zfwwy5k45193kz-taffybar-2.1.2
```
</p></details>

2018-06-17 20:11 UTC, xeji commented
Seems to build fine.

2018-06-17 20:11 UTC, merged