unixcw : init at 3.5.1
NixOS/nixpkgs pull request #41747
Opened 2018-06-09 11:09 UTC by MarcFontaine

###### Motivation for this change

I would like to add the unixcw package to nixpkgs

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-06-09 15:40 UTC, ryantm requested changes
Also please squash your commits into one commit.

2018-06-09 15:40 UTC, ryantm commented on pkgs/applications/misc/unixcw/default.nix
> +    url = mirror://sourceforge/unixcw/unixcw_3.5.1.orig.tar.gz;
Please use ${version} in the URL so the package can be updated more easily.

2018-06-09 15:40 UTC, ryantm commented on pkgs/applications/misc/unixcw/default.nix
> +    ./remove-use-of-dlopen.patch.gz
gzipping this patch seems excessive to me; how about we just have the .patch file unzipped.

2018-06-09 20:39 UTC, MarcFontaine commented
Hi Ryan,
Thanks for looking at my pull request. I'm still new to this.
Is it possible to update a pull request with a squashed commit
or to I have to close this pull request and open a new one?

2018-06-10 13:37 UTC, ryantm commented
@GrahamcOfBorg build unixcw

2018-06-10 13:38 UTC, GrahamcOfBorg commented
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41747&attempt_id=bd161abf-9613-4280-af1b-a102e25c5733)

The following builds were skipped because they don't evaluate on x86_64-darwin: unixcw

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-06-10 13:38 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41747&attempt_id=0193ff0d-986c-41ab-81f3-dfdfe75c75d3)

Attempted: unixcw

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking /nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1/bin/cwgen
shrinking /nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1/bin/cw
shrinking /nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1/lib/libcw.so.6.6.1
gzipping man pages under /nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1/share/man/
strip is /nix/store/21ymadblbmsbb2bk4q7gl4kjasp8zmgd-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1/lib  /nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1/bin
patching script interpreter paths in /nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1
checking for references to /build in /nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1...
postPatchMkspecs
/nix/store/z28slb8zadw796n7hmg7vx16a2sjzfmn-unixcw-3.5.1
```
</p></details>

2018-06-10 13:40 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.41747&attempt_id=927844b8-d7c9-4d54-9cf0-4dc48cc59056)

Attempted: unixcw

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking /nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1/bin/cwgen
shrinking /nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1/bin/cw
shrinking /nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1/lib/libcw.so.6.6.1
gzipping man pages under /nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1/share/man/
strip is /nix/store/qg2agrqkf240s656d207zqhipl0bc2id-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1/lib  /nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1/bin
patching script interpreter paths in /nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1
checking for references to /build in /nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1...
postPatchMkspecs
/nix/store/rlnyxyhfinmxk59jdasi7rrmx8k54xb7-unixcw-3.5.1
```
</p></details>

2018-06-10 23:07 UTC, merged