rainloop: Init at 1.12.0
NixOS/nixpkgs pull request #42740
Opened 2018-06-28 19:56 UTC by dasJ

###### Motivation for this change

I'm using rainloop webmail on my legacy (non-NixOS) servers.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-06-28 20:28 UTC, Mic92 commented on pkgs/servers/rainloop/default.nix
> +  edition ? "", hash ? "bf558752ce5035dc036702878f453fa4ba3da68c25e77271a079ac285d8acf76" }: stdenv.mkDerivation rec {
I don't think we need to expose `edition` or `hash`.

It is easy to enough to override them with:

```
rainloop.overrideAttrs (old: {
  src = fetchurl {
    url = "https://github.com/RainLoop/rainloop-webmail/releases/download/v${version}/rainloop-professional${version}.zip";
    sha256 = "<new-hash>";
  };
})
```

2018-06-28 20:34 UTC, Mic92 requested changes

2018-06-28 20:34 UTC, Mic92 commented on pkgs/servers/rainloop/default.nix
> +  };
Can you add a `common` function like here? https://github.com/NixOS/nixpkgs/blob/master/pkgs/servers/sql/postgresql/default.nix

2018-06-28 20:34 UTC, Mic92 commented on pkgs/top-level/all-packages.nix
> +  rainloop-standard = callPackage ../servers/rainloop { };
Then this would be become:

```
inherit (callPackages ../servers/rainloop { }) rainloop-community rainloop-standard;
```

2018-08-07 19:42 UTC, dasJ commented
@Mic92 Thank you for that great suggestion! I rewrote and rebased it according to your proposal

2018-08-17 15:05 UTC, merged