pass "exclude" args to mksquashfs for storage-deficient devices
NixOS/nixpkgs pull request #42795
Opened 2018-06-29 23:36 UTC by telent

###### Motivation for this change

This is debatable and I do not claim that the current behaviour is wrong.  But: when building NixWRT images for storage-starved systems (one of my routers has 4MB flash) it is convenient to be able to say, for example, "exclude lib*.a and man pages" without having to hack  every derivation that currently installs them.

```
  squashfs = pkgs.callPackage <nixpkgs/nixos/lib/make-squashfs.nix> {
    storeContents = packagesToInstall ;
    excludeWildcards = [ "... lib*.a" "... man/man[1-9]" ];
  };
```

Maybe it's generally useful, maybe it's a bit niche.  If the latter, would you accept a more general patch to add any options at all to the `mksquashfs` call?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-07-01 14:18 UTC, infinisil requested changes
While I never used this, it seems to be pretty useful. It's also nice how this can be done with just a flag to `mksquashfs`. Other than my suggested change I'm in favor of adding this.

2018-07-01 14:18 UTC, Infinisil commented on nixos/lib/make-squashfs.nix
> +        -wildcards ${stdenv.lib.concatStringsSep " " (map (f: "-e '${f}' ") excludeWildcards)}
There's `lib.escapeShellArg` you can use to handle escaping properly.

2018-08-13 18:08 UTC, Infinisil commented
Ping?

2018-12-27 14:54 UTC, danbst commented
I'm adding another hack to `make-squashfs.nix` in https://github.com/NixOS/nixpkgs/pull/52967/commits/e9775e5ca42ddd069fccfde6aadd3d0dc30f24bc. If it is merged, you can implement your niche request by overriding `comp` argument:
```
  squashfs = pkgs.callPackage <nixpkgs/nixos/lib/make-squashfs.nix> {
    storeContents = packagesToInstall ;
    comp = "xz -Xdict-size 100% -wildcards ${stdenv.lib.concatStringsSep " " (map (f: "-e '${f}' ") excludeWildcards)}";
  };
```

2019-08-13 08:13 UTC, mmahut commented
Are there any updates on this pull request, please?

2019-08-13 09:13 UTC, danbst commented
I'd say, this is pretty niche usecase. My PR https://github.com/NixOS/nixpkgs/pull/52967/files is merged, so workaround using `comp` argument can be used instead.

I regret now I've named the argument so narrow-scoped... It should have been called `extraSquashfsArgs`... But it should work here.

2019-08-13 09:13 UTC, closed without merging