grpcio-tools: init at 1.13.0
NixOS/nixpkgs pull request #42939
Opened 2018-07-03 20:14 UTC by mmlb

###### Motivation for this change

The seemingly only [documented](https://grpc.io/docs/tutorials/basic/python.html#generating-client-and-server-code) way of generating python grpc code is via the protoc python module, which is contained in this package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-07-03 20:14 UTC, mmlb commented
I've coped most of this from `grpcio`, and I've kept @vanschelven as the maintainer (ping), let me know if I should change it.

2018-07-03 20:27 UTC, dotlambda requested changes
Please add a `pythonPackages.` prefix to your commit message.

2018-07-03 20:32 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.42939&attempt_id=1a27df69-b9d8-4d02-9671-0cc3714fb76e)

Attempted: python2.pkgs.grpcio-tools, python3.pkgs.grpcio-tools

<details><summary>Partial log (click to expand)</summary><p>

```
Ran 0 tests in 0.000s

OK

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/zr9lwgs68hxadpgs6grba6rh3iikavfa-python2.7-grpcio-tools-1.13.0
/nix/store/v2yx61pnwj23xjvpgfm1mysjqqgirayp-python3.6-grpcio-tools-1.13.0
```
</p></details>

2018-07-03 20:44 UTC, mmlb commented on pkgs/development/python-modules/grpcio-tools/default.nix
> +    license = lib.licenses.bsd3;
oops. I checked and grpcio is also apache2. Will open separate pr for it.

2018-07-03 20:44 UTC, mmlb commented on pkgs/development/python-modules/grpcio-tools/default.nix
> +    description = "Package for gRPC Python tools";
done

2018-07-03 20:45 UTC, mmlb commented on pkgs/development/python-modules/grpcio-tools/default.nix
> +    license = lib.licenses.bsd3;
fixed

2018-07-03 20:51 UTC, dotlambda commented
> Ran 0 tests in 0.000s

Please provide an appropriate `checkPhase`.

2018-07-03 20:54 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.42939&attempt_id=410d7b73-5b90-44f1-bd22-a522b0a73c1b)

Attempted: python2.pkgs.grpcio-tools, python3.pkgs.grpcio-tools

<details><summary>Partial log (click to expand)</summary><p>

```
writing manifest file 'grpcio_tools.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-aarch64-3.6/grpc_tools/_protoc_compiler.cpython-36m-aarch64-linux-gnu.so -> grpc_tools

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/2h9wpkl4jss3hh1d516fjrmd2ph6yvry-python2.7-grpcio-tools-1.13.0
/nix/store/7hl2y4rij2frsq3imnjizgph2frvr9s8-python3.6-grpcio-tools-1.13.0
```
</p></details>

2018-07-03 20:59 UTC, mmlb commented
@dotlambda I don't think I can? There does not seem to be any python tests in the package, any suggestions?

2018-07-03 21:09 UTC, dotlambda commented
In that case, please set `doCheck = false` and add a comment that there are no tests.

2018-07-03 21:11 UTC, closed without merging

2018-07-04 13:54 UTC, mmlb commented
@dotlambda I was cleaning up branches on my fork and mistakenly deleted this branch... and GH closed. Will open a new one up.

2018-07-04 13:57 UTC, mmlb commented
@dotlambda seems like admin/owner/authorized member can reopen the PR, can you do so?

2018-07-04 13:59 UTC, dotlambda commented
No, I think you can't reopen it after altering the branch.

2018-07-04 14:28 UTC, mmlb commented
oic, well new PR coming in a moment.

2018-07-08 08:57 UTC, vanschelven commented
ping acknowledged; I'm fine with being the maintainer.