nixos/display-managers: fix loading of module-x11-publish
NixOS/nixpkgs pull request #43610
Opened 2018-07-16 12:58 UTC by jfrankenau

###### Motivation for this change

Fix #11970

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-08-02 22:24 UTC, infinisil requested changes

2018-08-03 06:05 UTC, jfrankenau commented on nixos/modules/services/x11/display-managers/default.nix
> +          "${config.hardware.pulseaudio.package.out}/bin/pactl load-module module-x11-publish 'display=$DISPLAY'"
Yes, that is a better way. Thank you.

2018-08-03 10:17 UTC, jfrankenau commented on nixos/modules/services/x11/display-managers/default.nix
> +          "${config.hardware.pulseaudio.package.out}/bin/pactl load-module module-x11-publish 'display=$DISPLAY'"
Actually, wait. This doesn't get rid of the error message. What about using `pulseaudio --dump-modules` to check if `module-x11-publish` is available?

2018-08-03 15:00 UTC, infinisil approved these changes
Ah very neat, thanks!

2018-08-03 15:00 UTC, merged