ksonnet: init at 0.11.0
NixOS/nixpkgs pull request #43644
Opened 2018-07-16 21:33 UTC by flokli

###### Motivation for this change
This adds ksonnet like #42596, addressing the changes suggested there.

/cc @nlewo 

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-07-16 21:51 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.43644&attempt_id=c04ee9c1-0b27-4629-8bd6-44204ad87b43)

Attempted: ksonnet

<details><summary>Partial log (click to expand)</summary><p>

```
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/281is3gff2z7vrn09wsn90zhsji725mm-ksonnet-0.11.0-bin
shrinking /nix/store/281is3gff2z7vrn09wsn90zhsji725mm-ksonnet-0.11.0-bin/bin/ks
shrinking /nix/store/281is3gff2z7vrn09wsn90zhsji725mm-ksonnet-0.11.0-bin/bin/generate
strip is /nix/store/0pjsgkxz0rp5baycq5sp2s72lrr5q9sg-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/281is3gff2z7vrn09wsn90zhsji725mm-ksonnet-0.11.0-bin/bin
patching script interpreter paths in /nix/store/281is3gff2z7vrn09wsn90zhsji725mm-ksonnet-0.11.0-bin
checking for references to /build in /nix/store/281is3gff2z7vrn09wsn90zhsji725mm-ksonnet-0.11.0-bin...
strip is /nix/store/0pjsgkxz0rp5baycq5sp2s72lrr5q9sg-binutils-2.30/bin/strip
```
</p></details>

2018-07-16 21:57 UTC, GrahamcOfBorg commented
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.43644&attempt_id=8e56c895-055c-44ef-9159-c106aab25a1f)

Attempted: ksonnet

<details><summary>Partial log (click to expand)</summary><p>

```
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
find: '/nix/store/5d8lix09in579djy8f4h3djigizilrnp-ksonnet-0.11.0': No such file or directory
/nix/store/zjnbr1xa698kgpr61li5s26mb0w424w1-ksonnet-0.11.0-bin
```
</p></details>

2018-07-16 22:07 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.43644&attempt_id=8c73c789-e72f-4825-b138-bad7187f302a)

Attempted: ksonnet

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/fy0kir0ypzrqc7v1c6fiapyl61i2w73h-ksonnet-0.11.0-bin
shrinking /nix/store/fy0kir0ypzrqc7v1c6fiapyl61i2w73h-ksonnet-0.11.0-bin/bin/generate
shrinking /nix/store/fy0kir0ypzrqc7v1c6fiapyl61i2w73h-ksonnet-0.11.0-bin/bin/ks
strip is /nix/store/4qvrxzxa535y8304mk195x50b6p9607d-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/fy0kir0ypzrqc7v1c6fiapyl61i2w73h-ksonnet-0.11.0-bin/bin
patching script interpreter paths in /nix/store/fy0kir0ypzrqc7v1c6fiapyl61i2w73h-ksonnet-0.11.0-bin
checking for references to /build in /nix/store/fy0kir0ypzrqc7v1c6fiapyl61i2w73h-ksonnet-0.11.0-bin...
strip is /nix/store/4qvrxzxa535y8304mk195x50b6p9607d-binutils-2.30/bin/strip
/nix/store/fy0kir0ypzrqc7v1c6fiapyl61i2w73h-ksonnet-0.11.0-bin
```
</p></details>

2018-07-17 11:24 UTC, nlewo requested changes

2018-07-17 12:38 UTC, flokli commented on pkgs/applications/networking/cluster/ksonnet/default.nix
> +let version = "0.11.0"; in
right, stripped that one :-)

2018-07-17 12:56 UTC, GrahamcOfBorg commented
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.43644&attempt_id=ccd402e4-7944-40ea-a45e-743ce59a6868)

Attempted: ksonnet

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/cvbxh8d4fmdx2nmsz4h0fjf388fgdrzs-ksonnet-0.11.0-bin
shrinking /nix/store/cvbxh8d4fmdx2nmsz4h0fjf388fgdrzs-ksonnet-0.11.0-bin/bin/generate
shrinking /nix/store/cvbxh8d4fmdx2nmsz4h0fjf388fgdrzs-ksonnet-0.11.0-bin/bin/ks
strip is /nix/store/7iyn7gn33i7xxjgmwf25k20246y6nd9d-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/cvbxh8d4fmdx2nmsz4h0fjf388fgdrzs-ksonnet-0.11.0-bin/bin
patching script interpreter paths in /nix/store/cvbxh8d4fmdx2nmsz4h0fjf388fgdrzs-ksonnet-0.11.0-bin
checking for references to /build in /nix/store/cvbxh8d4fmdx2nmsz4h0fjf388fgdrzs-ksonnet-0.11.0-bin...
strip is /nix/store/7iyn7gn33i7xxjgmwf25k20246y6nd9d-binutils-2.30/bin/strip
/nix/store/cvbxh8d4fmdx2nmsz4h0fjf388fgdrzs-ksonnet-0.11.0-bin
```
</p></details>

2018-07-17 12:58 UTC, GrahamcOfBorg commented
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.43644&attempt_id=985de45f-34a5-4683-b00f-5dbf8f92045b)

Attempted: ksonnet

<details><summary>Partial log (click to expand)</summary><p>

```
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
find: '/nix/store/mjqy8wrrzs0blxd47c98sm31inyflxd7-ksonnet-0.11.0': No such file or directory
/nix/store/6hzavb1f9kgpnwxjxs8jsbh0ab9ncpjl-ksonnet-0.11.0-bin
```
</p></details>

2018-07-17 13:04 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.43644&attempt_id=a7b585c8-4ec8-4f75-8140-edd24a694da1)

Attempted: ksonnet

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/j71gyc58hvfbid3r1pn25w9bpdlsivbg-ksonnet-0.11.0-bin
shrinking /nix/store/j71gyc58hvfbid3r1pn25w9bpdlsivbg-ksonnet-0.11.0-bin/bin/ks
shrinking /nix/store/j71gyc58hvfbid3r1pn25w9bpdlsivbg-ksonnet-0.11.0-bin/bin/generate
strip is /nix/store/90vmpr41dzsx350k5argycaf693hnl1l-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/j71gyc58hvfbid3r1pn25w9bpdlsivbg-ksonnet-0.11.0-bin/bin 
patching script interpreter paths in /nix/store/j71gyc58hvfbid3r1pn25w9bpdlsivbg-ksonnet-0.11.0-bin
checking for references to /tmp/nix-build-ksonnet-0.11.0.drv-0 in /nix/store/j71gyc58hvfbid3r1pn25w9bpdlsivbg-ksonnet-0.11.0-bin...
strip is /nix/store/90vmpr41dzsx350k5argycaf693hnl1l-binutils-2.30/bin/strip
/nix/store/j71gyc58hvfbid3r1pn25w9bpdlsivbg-ksonnet-0.11.0-bin
```
</p></details>

2018-07-17 13:08 UTC, nlewo commented
Thx!

2018-07-17 13:08 UTC, merged