alacritty: add terminfo and man
NixOS/nixpkgs pull request #43814
Opened 2018-07-19 15:03 UTC by bricewge

###### Motivation for this change

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-07-24 21:44 UTC, infinisil requested changes
Merge conflicts need to be fixed

2018-07-24 21:44 UTC, Infinisil commented on pkgs/applications/misc/alacritty/default.nix
> +    tic -x -o "$terminfo/usr/share/terminfo" alacritty.info
Should be just `$terminfo/share/terminfo`

2018-07-25 16:09 UTC, Infinisil commented
Merge conflicts still need to be fixed, just rebasing on master should do it

2018-07-29 18:56 UTC, infinisil approved these changes

2018-07-29 18:56 UTC, Infinisil commented
Thanks!

2018-07-29 18:56 UTC, merged