Add initial support to create a powerpc64le boostrap
NixOS/nixpkgs pull request #44092
Opened 2018-07-25 14:48 UTC by adevress

- ppc64le is the architecture used for POWER8 / POWER9 machines
- ppc64le implies a bit of trickery for long long double being 128bits

###### Motivation for this change

- Initial request to add POWER9 architecture support

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-07-25 15:07 UTC, Ericson2314 requested changes
A few things to do, but very excited people are adding more platforms!

2018-07-25 15:07 UTC, Ericson2314 commented on lib/systems/inspect.nix
> +    isppc64le      = { cpu = cpuTypes.powerpc64le; };
Hmm since this shorthand exists just at the nix level (in this PR) at least, can you capitalize it?

2018-07-25 15:07 UTC, Ericson2314 commented on pkgs/development/compilers/gcc/7/default.nix
> +	"--enable-softfloat"
See what I did with the ABIs in the nixpkgs lib to lessen the cominatorial explosion in GCC. Can you use the existing functionality for soft floats, and make a new one for longer floats?

2018-07-25 15:07 UTC, Ericson2314 commented on pkgs/os-specific/linux/musl/default.nix
> +
Please make this conditional on the nix level to avoid rebuilds and be easier to read. Also use `+=` in bash.

2018-07-25 15:07 UTC, Ericson2314 commented on pkgs/stdenv/generic/default.nix
> +        isi686 isx86_64 is64bit isArm isAarch64 isMips isBigEndian isppc64le;
Looks like an `isArm` snuck back in there? Please switch back to `isAarch32`.

2018-07-25 19:21 UTC, adevress commented on lib/systems/parse.nix
> +    powerpc64le  = { bits = 64; significantByte = littleEndian;    family = "power"; };
No, powerpc64 is a different architecture ( POWER <= 7 ) that I do not own any hardware for. powerle does not exist I think.
powerpc64le is the usual code name used by distribution for OpenPOWER power8/9 generation. meaning PowerPC architecture, 64 bits, little endian

2018-07-25 19:22 UTC, adevress commented on lib/systems/examples.nix
> +    arch = "ppc64le";
I started to do this support on a nixpkgs of some month ago... let me remove that

2018-07-26 18:32 UTC, Ericson2314 commented on lib/systems/parse.nix
> +    powerpc64le  = { bits = 64; significantByte = littleEndian;    family = "power"; };
hehe the http://llvm.org/doxygen/Triple_8cpp_source.html is inconsistent (see the `get*Variant` functions).

2018-08-22 07:47 UTC, Ericson2314 commented
#45340 is now merged. We should see what is left here that isn't included in that.

2018-08-31 14:17 UTC, closed without merging