pybitmessage: 0.6.2 -> 0.6.3.2
NixOS/nixpkgs pull request #44510
Opened 2018-08-05 16:36 UTC by fgaz

###### Motivation for this change

Fixes a RCE vulnerability

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

/cc @jgillich

2018-08-05 19:05 UTC, xeji commented
@dotlambda should this explicitly use python3 as well?

2018-08-05 20:00 UTC, dotlambda requested changes

2018-08-05 20:02 UTC, dotlambda commented
> should this explicitly use python3 as well?

No, PyBitmessage is python2 only: https://github.com/Bitmessage/PyBitmessage/blob/b0446ab4ab08def782b7f6fb6b7ca5c8d3d7f0c0/setup.py#L103
@fgaz Please replace `pythonPackages` by `python2Packages` in the entire expression. It makes sense to do so in a separate commit.

2018-08-05 22:36 UTC, dotlambda commented
@GrahamcOfBorg build pybitmessage

2018-08-05 23:07 UTC, GrahamcOfBorg commented
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.44510&attempt_id=e31ee419-f6bb-44f8-b196-545ff5e410cd)

Attempted: pybitmessage

<details><summary>Partial log (click to expand)</summary><p>

```
cannot build derivation '/nix/store/ic0mn4b0wsv5ghir1r9g6cdqrsmqhm31-python2.7-PyQt-x11-gpl-4.12.drv': 2 dependencies couldn't be built

trying https://github.com/bitmessage/PyBitmessage/archive/0.6.3.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   132    0   132    0     0    349      0 --:--:-- --:--:-- --:--:--   349
100 1091k    0 1091k    0     0   788k      0 --:--:--  0:00:01 --:--:-- 1195k
unpacking source archive /build/0.6.3.2.tar.gz
cannot build derivation '/nix/store/y132wssb1x71w0d6hqk6mfnbb4fidcb0-pybitmessage-0.6.3.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/y132wssb1x71w0d6hqk6mfnbb4fidcb0-pybitmessage-0.6.3.2.drv' failed
```
</p></details>

2018-08-05 23:37 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.44510&attempt_id=dd62d6c3-eb95-479e-84fb-b084b137ddad)

Attempted: pybitmessage

<details><summary>Partial log (click to expand)</summary><p>

```
                 from ../../WebCore/generated/JSSVGSwitchElement.cpp:25:
../../JavaScriptCore/wtf/NullPtr.h:48:1: warning: identifier 'nullptr' is a keyword in C++11 [-Wc++11-compat]
 extern std::nullptr_t nullptr;
 ^~~~~~
g++ -c -pipe -Wall -Wextra -Wreturn-type -fno-strict-aliasing -Wcast-align -Wchar-subscripts -Wformat-security -Wreturn-type -Wno-unused-parameter -Wno-sign-compare -Wno-switch -Wno-switch-enum -Wundef -Wmissing-noreturn -Winit-self -fpermissive -I/nix/store/wqd6c3rv2im1agqgj82mnld997jrjk92-sqlite-3.24.0-dev/include -ffunction-sections -fdata-sections -O2 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -pthread -pthread -pthread -pthread -pthread -pthread -pthread -I/nix/store/qvccjikwxwv59chymvk9dz9inmyffxs2-fontconfig-2.12.6-dev/include -I/nix/store/vry4f5mwbasrrcgikx7ki6j4s8495zp1-expat-2.2.5-dev/include -I/nix/store/2gzbxrjx0rgcyj2cbf12bvmi4gn62gsk-freetype-2.9-dev/include/freetype2 -fPIC -DQT_SHARED -DBUILDING_WEBKIT -DNDEBUG -DBUILDING_QT__=1 -DNDEBUG -DQT_ASCII_CAST_WARNINGS -DBUILDING_JavaScriptCore -DBUILDING_WTF -DENABLE_XSLT=0 -DENABLE_WEB_TIMING=0 -DENABLE_JAVASCRIPT_DEBUGGER=1 -DENABLE_DATABASE=1 -DENABLE_EVENTSOURCE=1 -DENABLE_OFFLINE_WEB_APPLICATIONS=1 -DENABLE_DOM_STORAGE=1 -DENABLE_ICONDATABASE=1 -DENABLE_CHANNEL_MESSAGING=1 -DENABLE_DIRECTORY_UPLOAD=0 -DENABLE_FILE_SYSTEM=0 -DENABLE_QUOTA=0 -DENABLE_SQLITE=1 -DENABLE_DASHBOARD_SUPPORT=0 -DENABLE_FILTERS=1 -DENABLE_XPATH=1 -DENABLE_WCSS=0 -DENABLE_SHARED_WORKERS=1 -DENABLE_WORKERS=1 -DENABLE_XHTMLMP=0 -DENABLE_DETAILS=1 -DENABLE_METER_TAG=1 -DENABLE_PROGRESS_TAG=1 -DENABLE_BLOB=1 -DENABLE_NOTIFICATIONS=1 -DENABLE_INPUT_SPEECH=0 -DENABLE_INSPECTOR=1 -DENABLE_3D_RENDERING=1 -DENABLE_WEB_AUDIO=0 -DENABLE_WEBGL=0 -DENABLE_MEDIA_STATISTICS=0 -DENABLE_VIDEO_TRACK=0 -DENABLE_TOUCH_ICON_LOADING=0 -DENABLE_ANIMATION_API=0 -DENABLE_SVG=1 -DENABLE_SVG_FONTS=1 -DENABLE_SVG_FOREIGN_OBJECT=1 -DENABLE_SVG_ANIMATION=1 -DENABLE_SVG_AS_IMAGE=1 -DENABLE_SVG_USE=1 -DENABLE_DATALIST=1 -DENABLE_TILED_BACKING_STORE=1 -DENABLE_NETSCAPE_PLUGIN_API=1 -DENABLE_WEB_SOCKETS=1 -DWTF_USE_QT_BEARER=1 -DENABLE_TOUCH_EVENTS=1 -DENABLE_VIDEO=1 -DWTF_USE_GSTREAMER=1 -DXP_UNIX -DENABLE_NETSCAPE_PLUGIN_METADATA_CACHE=1 -DENABLE_GLIB_SUPPORT=1 -DENABLE_XSLT=0 -DENABLE_WEB_TIMING=0 -DQT_NO_CAST_TO_ASCII -DQT3_SUPPORT -DQT_MOC_COMPAT -DQT_USE_QSTRINGBUILDER -DQT_MAKEDLL -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I../../../../../../mkspecs/linux-g++ -I. -I../../../../../../include/QtCore -I../../../../../../include/QtNetwork -I../../../../../../include/QtGui -I../../../../../../include -I../../WebCore/bridge/qt -I../../WebCore/page/qt -I../../WebCore/platform/graphics/qt -I../../WebCore/platform/network/qt -I../../WebCore/platform/qt -IApi -IWebCoreSupport -I../../WebCore -I../../WebCore/accessibility -I../../WebCore/bindings -I../../WebCore/bindings/generic -I../../WebCore/bridge -I../../WebCore/css -I../../WebCore/dom -I../../WebCore/dom/default -I../../WebCore/editing -I../../WebCore/fileapi -I../../WebCore/history -I../../WebCore/html -I../../WebCore/html/canvas -I../../WebCore/html/parser -I../../WebCore/html/shadow -I../../WebCore/inspector -I../../WebCore/loader -I../../WebCore/loader/appcache -I../../WebCore/loader/archive -I../../WebCore/loader/cache -I../../WebCore/loader/icon -I../../WebCore/mathml -I../../WebCore/notifications -I../../WebCore/page -I../../WebCore/page/animation -I../../WebCore/platform -I../../WebCore/platform/animation -I../../WebCore/platform/audio -I../../WebCore/platform/graphics -I../../WebCore/platform/graphics/filters -I../../WebCore/platform/graphics/filters/arm -I../../WebCore/platform/graphics/texmap -I../../WebCore/platform/graphics/transforms -I../../WebCore/platform/image-decoders -I../../WebCore/platform/leveldb -I../../WebCore/platform/mock -I../../WebCore/platform/network -I../../WebCore/platform/sql -I../../WebCore/platform/text -I../../WebCore/platform/text/transcoder -I../../WebCore/plugins -I../../WebCore/rendering -I../../WebCore/rendering/mathml -I../../WebCore/rendering/style -I../../WebCore/rendering/svg -I../../WebCore/storage -I../../WebCore/svg -I../../WebCore/svg/animation -I../../WebCore/svg/graphics -I../../WebCore/svg/graphics/filters -I../../WebCore/svg/properties -I../../WebCore/testing -I../../WebCore/webaudio -I../../WebCore/websockets -I/build/qt-everywhere-opensource-src-4.8.7/src/3rdparty/webkit/Source/WebCore/wml -I../../WebCore/workers -I../../WebCore/xml -I../../WebCore/bridge/jsc -I../../WebCore/bindings/js -I/build/qt-everywhere-opensource-src-4.8.7/src/3rdparty/webkit/Source/WebCore/bindings/js/specialization -I../../WebCore/bridge/c -I../../WebCore/testing/js -I../../WebCore/generated -I../../JavaScriptCore -I../../../Source -I../../ThirdParty -I../../JavaScriptCore/assembler -I../../JavaScriptCore/bytecode -I../../JavaScriptCore/bytecompiler -I../../JavaScriptCore/heap -I../../JavaScriptCore/dfg -I../../JavaScriptCore/debugger -I../../JavaScriptCore/interpreter -I../../JavaScriptCore/jit -I../../JavaScriptCore/parser -I../../JavaScriptCore/profiler -I../../JavaScriptCore/runtime -I../../JavaScriptCore/wtf -I../../JavaScriptCore/wtf/gobject -I/build/qt-everywhere-opensource-src-4.8.7/src/3rdparty/webkit/Source/JavaScriptCore/wtf/symbian -I../../JavaScriptCore/wtf/unicode -I../../JavaScriptCore/yarr -I../../JavaScriptCore/API -I../../JavaScriptCore/ForwardingHeaders -I../../JavaScriptCore/generated -I../../../Source -I../../../include -I/include/QtWebKit -I/include -I../../WebCore/platform/graphics/gstreamer -I../../../../../../include/QtWebKit -I.rcc/release-shared -I.moc/release-shared -I/nix/store/1pny9qi7xhig3a5rqc4x113kz4n6ic30-glib-2.56.0-dev/include/glib-2.0 -I/nix/store/m9ag8a55mp1a8mj1qll7vma95z2db3y1-glib-2.56.0/lib/glib-2.0/include -I/nix/store/vznf3rr02rr67x1s8i3dqf1jnx3ld536-gstreamer-0.10.36-dev/include/gstreamer-0.10 -I/nix/store/wnhfavfz94s8y4lzm7z56a495j25viwz-libxml2-2.9.8-dev/include/libxml2 -I/nix/store/g8l7f8zkildmk4kllxldhf14qsanwyc3-gst-plugins-base-0.10.36-dev/include/gstreamer-0.10 -I/var/empty/X11R6/include -o .obj/release-shared/HTMLElementFactory.o ../../WebCore/generated/HTMLElementFactory.cpp
g++ -c -pipe -Wall -Wextra -Wreturn-type -fno-strict-aliasing -Wcast-align -Wchar-subscripts -Wformat-security -Wreturn-type -Wno-unused-parameter -Wno-sign-compare -Wno-switch -Wno-switch-enum -Wundef -Wmissing-noreturn -Winit-self -fpermissive -I/nix/store/wqd6c3rv2im1agqgj82mnld997jrjk92-sqlite-3.24.0-dev/include -ffunction-sections -fdata-sections -O2 -fvisibility=hidden -fvisibility-inlines-hidden -Wall -W -D_REENTRANT -pthread -pthread -pthread -pthread -pthread -pthread -pthread -I/nix/store/qvccjikwxwv59chymvk9dz9inmyffxs2-fontconfig-2.12.6-dev/include -I/nix/store/vry4f5mwbasrrcgikx7ki6j4s8495zp1-expat-2.2.5-dev/include -I/nix/store/2gzbxrjx0rgcyj2cbf12bvmi4gn62gsk-freetype-2.9-dev/include/freetype2 -fPIC -DQT_SHARED -DBUILDING_WEBKIT -DNDEBUG -DBUILDING_QT__=1 -DNDEBUG -DQT_ASCII_CAST_WARNINGS -DBUILDING_JavaScriptCore -DBUILDING_WTF -DENABLE_XSLT=0 -DENABLE_WEB_TIMING=0 -DENABLE_JAVASCRIPT_DEBUGGER=1 -DENABLE_DATABASE=1 -DENABLE_EVENTSOURCE=1 -DENABLE_OFFLINE_WEB_APPLICATIONS=1 -DENABLE_DOM_STORAGE=1 -DENABLE_ICONDATABASE=1 -DENABLE_CHANNEL_MESSAGING=1 -DENABLE_DIRECTORY_UPLOAD=0 -DENABLE_FILE_SYSTEM=0 -DENABLE_QUOTA=0 -DENABLE_SQLITE=1 -DENABLE_DASHBOARD_SUPPORT=0 -DENABLE_FILTERS=1 -DENABLE_XPATH=1 -DENABLE_WCSS=0 -DENABLE_SHARED_WORKERS=1 -DENABLE_WORKERS=1 -DENABLE_XHTMLMP=0 -DENABLE_DETAILS=1 -DENABLE_METER_TAG=1 -DENABLE_PROGRESS_TAG=1 -DENABLE_BLOB=1 -DENABLE_NOTIFICATIONS=1 -DENABLE_INPUT_SPEECH=0 -DENABLE_INSPECTOR=1 -DENABLE_3D_RENDERING=1 -DENABLE_WEB_AUDIO=0 -DENABLE_WEBGL=0 -DENABLE_MEDIA_STAT [...]

2018-08-06 09:45 UTC, fgaz commented
Someone broke qt in the meantime :-/

2018-08-06 09:57 UTC, dotlambda commented
It's not broken. We'll just have to wait until `qt` is built by Hydra: https://hydra.nixos.org/build/79044311

2018-08-07 21:57 UTC, dotlambda commented
@GrahamcOfBorg build pybitmessage

2018-08-07 21:58 UTC, GrahamcOfBorg commented
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.44510&attempt_id=4c0afdc4-8600-45f3-a461-cc466ce281ae)

Attempted: pybitmessage

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest file 'pybitmessage.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'pybitmessage.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/pybitmessage/bitmsghash/bitmsghash.so -> src/bitmsghash

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```
</p></details>

2018-08-07 21:59 UTC, merged

2018-08-07 22:00 UTC, dotlambda commented
Backported in ad664942690.

2018-08-07 22:59 UTC, GrahamcOfBorg commented
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.44510&attempt_id=a929b6e6-82f2-4841-88ab-75fdfbc1edb5)

Attempted: pybitmessage

<details><summary>Partial log (click to expand)</summary><p>

```
../../WebCore/page/FrameTree.h:37:29:   required from here
../../JavaScriptCore/wtf/RefCounted.h:141:13: warning: deleting object of polymorphic class type 'WebCore::Frame' which has non-virtual destructor might cause undefined behavior [-Wdelete-non-virtual-dtor]
             delete static_cast<T*>(this);
             ^~~~~~
rm -f libQtWebKit.so.4.9.4 libQtWebKit.so libQtWebKit.so.4 libQtWebKit.so.4.9
g++ -Wl,-rpath-link,/build/qt-everywhere-opensource-src-4.8.7/lib -Wl,--gc-sections -Wl,--no-undefined -Wl,--no-undefined -Wl,-O1 -Wl,-rpath,/nix/store/8a19vsn1wdp2875h17g5gp7fmgcg6z1b-qt-4.8.7/lib -Wl,-rpath,/nix/store/8a19vsn1wdp2875h17g5gp7fmgcg6z1b-qt-4.8.7/lib -shared -Wl,-soname,libQtWebKit.so.4 -o libQtWebKit.so.4.9.4 .obj/release-shared/MathMLNames.o .obj/release-shared/MathMLElementFactory.o .obj/release-shared/SVGNames.o .obj/release-shared/SVGElementFactory.o .obj/release-shared/JSSVGElementWrapperFactory.o .obj/release-shared/XLinkNames.o .obj/release-shared/CSSPropertyNames.o .obj/release-shared/CSSValueKeywords.o .obj/release-shared/JSCounter.o .obj/release-shared/JSCSSCharsetRule.o .obj/release-shared/JSCSSFontFaceRule.o .obj/release-shared/JSCSSImportRule.o .obj/release-shared/JSCSSMediaRule.o .obj/release-shared/JSCSSPageRule.o .obj/release-shared/JSCSSPrimitiveValue.o .obj/release-shared/JSCSSRule.o .obj/release-shared/JSCSSRuleList.o .obj/release-shared/JSCSSStyleDeclaration.o .obj/release-shared/JSCSSStyleRule.o .obj/release-shared/JSCSSStyleSheet.o .obj/release-shared/JSCSSValue.o .obj/release-shared/JSCSSValueList.o .obj/release-shared/JSMediaList.o .obj/release-shared/JSMediaQueryList.o .obj/release-shared/JSRect.o .obj/release-shared/JSRGBColor.o .obj/release-shared/JSStyleMedia.o .obj/release-shared/JSStyleSheet.o .obj/release-shared/JSStyleSheetList.o .obj/release-shared/JSWebKitCSSKeyframeRule.o .obj/release-shared/JSWebKitCSSKeyframesRule.o .obj/release-shared/JSWebKitCSSMatrix.o .obj/release-shared/JSWebKitCSSTransformValue.o .obj/release-shared/JSAttr.o .obj/release-shared/JSBeforeLoadEvent.o .obj/release-shared/JSBeforeProcessEvent.o .obj/release-shared/JSCharacterData.o .obj/release-shared/JSClientRect.o .obj/release-shared/JSClientRectList.o .obj/release-shared/JSClipboard.o .obj/release-shared/JSCDATASection.o .obj/release-shared/JSComment.o .obj/release-shared/JSCompositionEvent.o .obj/release-shared/JSCustomEvent.o .obj/release-shared/JSDataTransferItem.o .obj/release-shared/JSDataTransferItems.o .obj/release-shared/JSDeviceMotionEvent.o .obj/release-shared/JSDeviceOrientationEvent.o .obj/release-shared/JSDocumentFragment.o .obj/release-shared/JSDocument.o .obj/release-shared/JSDocumentType.o .obj/release-shared/JSDOMCoreException.o .obj/release-shared/JSDOMImplementation.o .obj/release-shared/JSDOMStringList.o .obj/release-shared/JSDOMStringMap.o .obj/release-shared/JSElement.o .obj/release-shared/JSEntity.o .obj/release-shared/JSEntityReference.o .obj/release-shared/JSErrorEvent.o .obj/release-shared/JSEvent.o .obj/release-shared/JSEventException.o .obj/release-shared/JSHashChangeEvent.o .obj/release-shared/JSKeyboardEvent.o .obj/release-shared/JSMouseEvent.o .obj/release-shared/JSMessageChannel.o .obj/release-shared/JSMessageEvent.o .obj/release-shared/JSMessagePort.o .obj/release-shared/JSMutationEvent.o .obj/release-shared/JSNamedNodeMap.o .obj/release-shared/JSNode.o .obj/release-shared/JSNodeFilter.o .obj/release-shared/JSNodeIterator.o .obj/release-shared/JSNodeList.o .obj/release-shared/JSNotation.o .obj/release-shared/JSOverflowEvent.o .obj/release-shared/JSPageTransitionEvent.o .obj/release-shared/JSPopStateEvent.o .obj/release-shared/JSProcessingInstruction.o .obj/release-shared/JSProgressEvent.o .obj/release-shared/JSRangeException.o .obj/release-shared/JSRange.o .obj/release-shared/JSStringCallback.o .obj/release-shared/JSText.o .obj/release-shared/JSTextEvent.o .obj/release-shared/JSTouch.o .obj/release-shared/JSTouchEvent.o .obj/release-shared/JSTouchList.o .obj/release-shared/JSTreeWalker.o .obj/release-shared/JSUIEvent.o .obj/release-shared/JSWebKitAnimationEvent.o .obj/release-shared/JSWebKitTransitionEvent.o .obj/release-shared/JSWheelEvent.o .obj/release-shared/JSBlob.o .obj/release-shared/JSDirectoryEntry.o .obj/release-shared/JSDirectoryEntrySync.o .obj/release-shared/JSDirectoryReader.o .obj/release-shared/JSDirectoryReaderSync.o .obj/release-shared/JSDOMFileSystem.o .obj/release-shared/JSDOMFileSystemSync.o .obj/release-shared/JSEntriesCallback.o .obj/release-shared/JSEntry.o .obj/release-shared/JSEntryArray.o .obj/release-shared/JSEntryArraySync.o .obj/release-shared/JSEntryCallback.o .obj/release-shared/JSEntrySync.o .obj/release-shared/JSErrorCallback.o .obj/release-shared/JSFile.o .obj/release-shared/JSFileCallback.o .obj/release-shared/JSFileEntry.o .obj/release-shared/JSFileEntrySync.o .obj/release-shared/JSFileError.o .obj/release-shared/JSFileException.o .obj/release-shared/JSFileList.o .obj/release-shared/JSFileReader.o .obj/release-shared/JSFileReaderSync.o .obj/release-shared/JSFileSystemCallback.o .obj/release-shared/JSFileWriter.o .obj/release-shared/JSFileWriterCallback.o .obj/release-shared/JSWebKitFlags.o .obj/release-shared/JSMetadata.o .obj/release-shared/JSMetadataCallback.o .obj/release-shared/JSWebKitBlobBuilder.o .obj/release-shared/JSArrayBufferView.o .obj/release-shared/JSArrayBuffer.o .obj/release-shared/JSDataView.o .obj/release-shared/JSInt8Array.o .obj/release-shared/JSFloat32Array.o .obj/release-shared/JSCanvasGradient.o .obj/release-shared/JSInt32Array.o .obj/release-shared/JSCanvasPattern.o .obj/release-shared/JSCanvasRenderingContext.o .obj/release-shared/JSCanvasRenderingContext2D.o .obj/release-shared/JSOESStandardDerivatives.o .obj/release-shared/JSOESTextureFloat.o .obj/release-shared/JSOESVertexArrayObject.o .obj/release-shared/JSWebGLActiveInfo.o .obj/release-shared/JSWebGLBuffer.o .obj/release-shared/JSWebGLContextAttributes.o .obj/release-shared/JSWebGLFramebuffer.o .obj/release-shared/JSWebGLProgram.o .obj/release-shared/JSWebGLRenderbuffer.o .obj/release-shared/JSWebGLRenderingContext.o .obj/release-shared/JSWebGLShader.o .obj/release-shared/JSInt16Array.o .obj/release-shared/JSWebGLTexture.o .obj/release-shared/JSWebGLUniformLocation.o .obj/release-shared/JSWebGLVertexArrayObjectOES.o .obj/release-shared/JSWebKitLoseContext.o .obj/release-shared/JSUint8Array.o .obj/release-shared/JSUint32Array.o .obj/release-shared/JSUint16Array.o .obj/release-shared/JSDOMFormData.o .obj/release-shared/JSDOMSettableTokenList.o .obj/release-shared/JSDOMTokenList.o .obj/release-shared/JSDOMURL.o .obj/release-shared/JSHTMLAllCollection.o .obj/release-shared/JSHTMLAudioElement.o .obj/release-shared/JSHTMLAnchorElement.o .obj/release-shared/JSHTMLAppletElement.o .obj/release-shared/JSHTMLAreaElement.o .obj/release-shared/JSHTMLBaseElement.o .obj/release-shared/JSHTMLBaseFontElement.o .obj/release-shared/JSHTMLBlockquoteElement.o .obj/release-shared/JSHTMLBodyElement.o .obj/release-shared/JSHTMLBRElement.o .obj/release-shared/JSHTMLButtonElement.o .obj/release-shared/JSHTMLCanvasElement.o .obj/release-shared/JSHTMLCollection.o .obj/release-shared/JSHTMLDataListElement.o .obj/release-shared/JSHTMLDetailsElement.o .obj/release-shared/JSHTMLDirectoryElement.o .obj/release-shared/JSHTMLDivElement.o .obj/release-shared/JSHTMLDListElement.o .obj/release-shared/JSHTMLDocument.o .obj/release-shared/JSHTMLElement.o .obj/release-shared/JSHTMLEmbedElement.o .obj/release-shared/JSHTMLFieldSetElement.o .obj/release-shared/JSHTMLFontElement.o .obj/release-shared/JSHTMLFormElement.o .obj/release-shared/JSHTMLFrameElement.o .obj/release-shared/JSHTMLFrameSetElement.o .obj/release-shared/JSHTMLHeadElement.o .obj/release-shared/JSHTMLHeadingElement.o .obj/release-share [...]