pmdk: init at 1.4.1
NixOS/nixpkgs pull request #45381
Opened 2018-08-20 13:50 UTC by barakb

pmdk is a persistent memory development kit

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x ] NixOS
   - [ ] macOS
   - [x] other Linux distributions (Ubuntu)
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-08-21 08:05 UTC, srhb requested changes

2018-08-21 08:05 UTC, srhb commented on pkgs/development/libraries/pmdk/default.nix
> +            maintainers = [ maintainers.barakb ];
All of these live in `stdenv.lib`: `stdenv.lib.licenses.bsd3`, `stdenv.lib.platforms.unix`, `stdenv.lib.maintainers.barakb`

2019-08-10 12:57 UTC, mmahut commented
Are there any updates on this pull request, please?

2019-12-04 10:48 UTC, yorickvP commented
added in #59093

2019-12-04 10:49 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review-may-2019/3032/87

2019-12-04 10:54 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/76

2019-12-04 19:07 UTC, closed without merging