thonny: init at 3.0.0b3
NixOS/nixpkgs pull request #45632
Opened 2018-08-25 17:41 UTC by leenaars

###### Motivation for this change

Good Python IDE for beginners.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-08-31 04:00 UTC, ryantm requested changes

2018-09-03 21:37 UTC, leenaars commented on pkgs/applications/editors/thonny/default.nix
> +{ stdenv, fetchFromBitbucket, python3 }:
The homepage states that it 'comes with Python 3", I could not find any reference of support for Python 2 in the documentation or anywhere else.

2018-09-04 04:07 UTC, ryantm commented
@GrahamcOfBorg build thonny

2018-09-04 04:08 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=82708b7b-49a2-42f1-83c8-7ca9ba423b26-->
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.45632&attempt_id=d414c57f-cad8-4955-a87d-8a9a7ee8ed6c)

The following builds were skipped because they don't evaluate on x86_64-darwin: thonny

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-09-04 04:08 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=82708b7b-49a2-42f1-83c8-7ca9ba423b26-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.45632&attempt_id=3e06ed6d-dd43-4128-8faf-061649f4f66d)

Attempted: thonny

<details><summary>Partial log (click to expand)</summary><p>

```
Installing collected packages: thonny
Successfully installed thonny-3.0.0b3
/build/source
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/2l2v27bcq4f9a0h0sffnwkxl8facdd0g-thonny-3.0.0b3
strip is /nix/store/h0lbngpv6ln56hjj59i6l77vxq25flbz-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/2l2v27bcq4f9a0h0sffnwkxl8facdd0g-thonny-3.0.0b3/lib  /nix/store/2l2v27bcq4f9a0h0sffnwkxl8facdd0g-thonny-3.0.0b3/bin
patching script interpreter paths in /nix/store/2l2v27bcq4f9a0h0sffnwkxl8facdd0g-thonny-3.0.0b3
checking for references to /build in /nix/store/2l2v27bcq4f9a0h0sffnwkxl8facdd0g-thonny-3.0.0b3...
wrapping `/nix/store/2l2v27bcq4f9a0h0sffnwkxl8facdd0g-thonny-3.0.0b3/bin/.thonny-wrapped'...
```
</p></details>

2018-09-04 04:08 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=82708b7b-49a2-42f1-83c8-7ca9ba423b26-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.45632&attempt_id=8a390334-9a14-4c4f-9afc-072e6732a0e3)

Attempted: thonny

<details><summary>Partial log (click to expand)</summary><p>

```
Successfully installed thonny-3.0.0b3
/build/source
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/g6af0dwpp3h35d6h1wpvl3rpr96szgqi-thonny-3.0.0b3
strip is /nix/store/y4ymnvgxygpq05h03kyzbj572zmh6zla-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/g6af0dwpp3h35d6h1wpvl3rpr96szgqi-thonny-3.0.0b3/lib  /nix/store/g6af0dwpp3h35d6h1wpvl3rpr96szgqi-thonny-3.0.0b3/bin
patching script interpreter paths in /nix/store/g6af0dwpp3h35d6h1wpvl3rpr96szgqi-thonny-3.0.0b3
checking for references to /build in /nix/store/g6af0dwpp3h35d6h1wpvl3rpr96szgqi-thonny-3.0.0b3...
wrapping `/nix/store/g6af0dwpp3h35d6h1wpvl3rpr96szgqi-thonny-3.0.0b3/bin/.thonny-wrapped'...
/nix/store/g6af0dwpp3h35d6h1wpvl3rpr96szgqi-thonny-3.0.0b3
```
</p></details>

2018-09-04 04:41 UTC, ryantm approved these changes

2018-09-10 20:04 UTC, merged