pythonPackages.dependency_injector: init at 3.13.1
NixOS/nixpkgs pull request #45871
Opened 2018-08-31 15:01 UTC by Gerschtli

###### Motivation for this change

Adds `dependency_injector` python package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-08-31 15:19 UTC, dotlambda requested changes

2018-08-31 15:19 UTC, dotlambda commented on pkgs/top-level/python-packages.nix
> +  dependency_injector = callPackage ../development/python-modules/dependency_injector { };
https://github.com/NixOS/nixpkgs/blob/master/doc/languages-frameworks/python.section.md#contributing-guidelines

2018-08-31 15:19 UTC, dotlambda commented on pkgs/development/python-modules/dependency_injector/default.nix
> +    platforms = platforms.all;
`platforms` is set automatically

2018-08-31 15:19 UTC, dotlambda commented on pkgs/development/python-modules/dependency_injector/default.nix
> +  pname = "dependency_injector";
This should be the same as below.

2018-09-01 11:36 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.dependency-injector python3.pkgs.dependency-injector

2018-09-01 11:37 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=1f7a62af-b328-437c-a1f9-33fa931c1e42-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.45871&attempt_id=c017a7cb-a6a0-4fa9-8014-6b7be57c17ec)

Attempted: python2.pkgs.dependency-injector, python3.pkgs.dependency-injector

<details><summary>Partial log (click to expand)</summary><p>

```
running build_ext
copying build/lib.macosx-10.6-x86_64-3.6/dependency_injector/containers.cpython-36m-darwin.so -> src/dependency_injector
copying build/lib.macosx-10.6-x86_64-3.6/dependency_injector/providers.cpython-36m-darwin.so -> src/dependency_injector

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/7xzihvdw9y5r0y738v7rzyypfl26h76i-python2.7-dependency-injector-3.13.1
/nix/store/6xix3c9ajx387kdl37mjqi8x157y8vbk-python3.6-dependency-injector-3.13.1
```
</p></details>

2018-09-01 11:38 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=1f7a62af-b328-437c-a1f9-33fa931c1e42-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.45871&attempt_id=a8fd01dd-22f0-4104-a7b6-efea31a26628)

Attempted: python2.pkgs.dependency-injector, python3.pkgs.dependency-injector

<details><summary>Partial log (click to expand)</summary><p>

```
running build_ext
copying build/lib.linux-x86_64-3.6/dependency_injector/containers.cpython-36m-x86_64-linux-gnu.so -> src/dependency_injector
copying build/lib.linux-x86_64-3.6/dependency_injector/providers.cpython-36m-x86_64-linux-gnu.so -> src/dependency_injector

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/wxzp3679gl3p5qqlrqfky9n39fwn1a2l-python2.7-dependency-injector-3.13.1
/nix/store/y6bl1pl38gy4bx65g4q4c81sb2kzfm9n-python3.6-dependency-injector-3.13.1
```
</p></details>

2018-09-01 11:38 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=1f7a62af-b328-437c-a1f9-33fa931c1e42-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.45871&attempt_id=908efc77-60e0-4d47-a03a-ad31e0e5b7b8)

Attempted: python2.pkgs.dependency-injector, python3.pkgs.dependency-injector

<details><summary>Partial log (click to expand)</summary><p>

```
running build_ext
copying build/lib.linux-aarch64-3.6/dependency_injector/containers.cpython-36m-aarch64-linux-gnu.so -> src/dependency_injector
copying build/lib.linux-aarch64-3.6/dependency_injector/providers.cpython-36m-aarch64-linux-gnu.so -> src/dependency_injector

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/00aspi2kl4k5468yanlgf8can6g96ckl-python2.7-dependency-injector-3.13.1
/nix/store/r7105s9gsimn903qw3xdcbb686blbfx9-python3.6-dependency-injector-3.13.1
```
</p></details>

2018-09-01 11:39 UTC, dotlambda commented
> Ran 0 tests in 0.000s

Please provide an appropriate `checkPhase`. If there are no tests, please set `doCheck = false` and add a comment with the reason.

2018-09-01 11:52 UTC, Gerschtli commented
It seems that the tests directory doesn't exist when running the checkPhase.. Do you know why the directory is removed?

2018-09-01 11:56 UTC, dotlambda commented
Because it's not uploaded to PyPI. You can open an upstream PR to include it in `MANIFEST.in`.

2018-09-01 15:29 UTC, merged