noti: init at 3.1.0
NixOS/nixpkgs pull request #46111
Opened 2018-09-05 18:27 UTC by stites

###### Motivation for this change
Add a new, works-out-of-the-box notifier

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions: Ubunt17.04
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-09-06 08:22 UTC, srhb requested changes

2018-09-06 14:28 UTC, stites commented on pkgs/tools/misc/noti/default.nix
> +    url = "https://github.com/variadico/noti/releases/download/${version}/noti${version}.linux-amd64.tar.gz";
Nope, I just figured that prebuilt binaries were preferable to the source code -- I'll fix that now!

2018-09-06 17:59 UTC, stites commented
@srhb -- Please take a look! I'm a bit iffy on the proper way to set up documentation -- I think the `postInstall` is correct (as in "works on my machine"), but I'm not sure if there's a better way to do this.

I'm also a bit iffy on go in general, but luckily nix makes it easy to figure out the build process. : )

2018-09-06 20:04 UTC, srhb requested changes

2018-09-06 20:04 UTC, srhb commented on pkgs/tools/misc/noti/default.nix
> +  goDeps = ./deps.nix;
The deps appear to be vendored in the tarball fetched by `fetchFromGitHub`. Can you check if `goDeps` are really necessary?

2018-09-07 02:26 UTC, stites commented
noti, especially, has a decently sized Makefile which originally lead me to believe it had a non-standard build. This repo doesn't seem to output the man pages, anyhow, and they come pre-build in the repo.

2018-09-07 07:17 UTC, srhb commented
Thanks@stites. One last thing: Please squash this into one commit following the rules at https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes (ie. "noti: init at 3.1.0") or two commits, one for this addition and one "add stites to maintainer list" :)

Thanks a lot for your effort, and welcome to the nixpkgs maintainers list. :smiley:

2018-09-07 14:34 UTC, stites commented
Thank you for the guidance, this was a lot of fun!

2018-09-07 14:35 UTC, merged