pythonPackages.gpgme: enable python3 support
NixOS/nixpkgs pull request #46304
Opened 2018-09-07 09:02 UTC by teto

when calling python3Packages.gpgme, it was still picking python2.
Changed withPython into pythonSupport since it's the convention.

I had to enable ncurses too because of this error when configuring:

configure:19978: checking python extra libraries
configure:19985: result: -lpthread -ldl -lcrypt -lncurses -lutil -lm
configure:19992: checking python extra linking flags
configure:19999: result: -Xlinker -export-dynamic
configure:20006: checking consistency of all components of python development environment
configure:20032: gcc -o conftest -g -O2  -I/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/include/python3.6m  conftest.c  -L/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/lib -lpython3.6m -Xlinker -export-dynamic -lpthread -ldl -lcrypt -lncurses -lutil -lm >&5
/nix/store/h0lbngpv6ln56hjj59i6l77vxq25flbz-binutils-2.30/bin/ld: cannot find -lncurses
collect2: error: ld returned 1 exit status
configure:20032: $? = 1

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-09-25 16:10 UTC, teto commented
@FRidh should I put this into staging ?

2018-10-10 04:32 UTC, dtzWill commented
LGTM! I actually did largely the same thing to get gpgme working w/py3 for use with recent `alot`:

https://github.com/dtzWill/nixpkgs/commit/70c4b8fff75e9d9c5c7e0a042af91742bcf37cfa

(commit not intended for upstream inclusion as-is, but even so it's what I've been using and works for me--yours looks the same but better ;))

2018-10-15 07:47 UTC, teto commented
GrahamcOfBorg build python3Packages.gpgme

2018-10-15 07:48 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=08a95ef3-a684-44e5-a412-a458666a78fd-->
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46304&attempt_id=30ab8ec7-8860-4de9-867f-81b8280142e4)

Attempted: python3Packages.gpgme

<details><summary>Partial log (click to expand)</summary><p>

```
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

configure: error:
***
*** Please install the python development packages.
***
builder for '/nix/store/7y8pxhs5r15h4fp23zjrndr6ka9mi8kh-gpgme-1.12.0.drv' failed with exit code 1
error: build of '/nix/store/7y8pxhs5r15h4fp23zjrndr6ka9mi8kh-gpgme-1.12.0.drv' failed
```
</p></details>

2018-10-15 07:48 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=08a95ef3-a684-44e5-a412-a458666a78fd-->
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46304&attempt_id=b1a07142-b674-4d5b-a7b7-d9fd522e9e91)

Attempted: python3Packages.gpgme

<details><summary>Partial log (click to expand)</summary><p>

```
   You probably have to install the development version of the Python package
   for your distribution.  The exact name of this package varies among them.
  ============================================================================

configure: error:
***
*** Please install the python development packages.
***
builder for '/nix/store/xvviaf9nfjbxy49z5qm9329z1kwz7cvs-gpgme-1.12.0.drv' failed with exit code 1
error: build of '/nix/store/xvviaf9nfjbxy49z5qm9329z1kwz7cvs-gpgme-1.12.0.drv' failed
```
</p></details>

2018-10-18 07:12 UTC, teto commented
Needed to test master version of alot with python3 support @Fuuzetsu @primeos

2018-10-18 12:00 UTC, primeos commented
> Needed to test master version of alot with python3 support @Fuuzetsu @primeos

What do you mean with this comment? According to `GrahamcOfBorg` `gpgme` doesn't build with Python(3) support, that should be fixed first. Also: I'm happy to help with `gpgme` but I'm neither using nor maintaining `alot`.

2018-10-18 12:32 UTC, teto commented
@GrahamcOfBorg build python3Packages.gpgme

2018-10-18 12:35 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=5aff3555-04f7-4d32-b411-455ddeb9de6b-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46304&attempt_id=4739a43f-baac-402c-b3c7-57f9f4990d02)

Attempted: python3Packages.gpgme

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking /nix/store/72wfnshv009a5m211l0zmgfmlsrpss6q-gpgme-1.12.0-dev/bin/gpgme-tool
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/72wfnshv009a5m211l0zmgfmlsrpss6q-gpgme-1.12.0-dev/bin
patching script interpreter paths in /nix/store/72wfnshv009a5m211l0zmgfmlsrpss6q-gpgme-1.12.0-dev
/nix/store/72wfnshv009a5m211l0zmgfmlsrpss6q-gpgme-1.12.0-dev/bin/gpgme-config: interpreter directive changed from "/bin/sh" to "/nix/store/dsyc1z7ck08ga7l0b1jcxx35wj69qcii-bash-4.4-p23/bin/sh"
checking for references to /build in /nix/store/72wfnshv009a5m211l0zmgfmlsrpss6q-gpgme-1.12.0-dev...
shrinking RPATHs of ELF executables and libraries in /nix/store/b3x9nskcp09jjg51fxcgp49gkdnxqi1z-gpgme-1.12.0-info
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/b3x9nskcp09jjg51fxcgp49gkdnxqi1z-gpgme-1.12.0-info
checking for references to /build in /nix/store/b3x9nskcp09jjg51fxcgp49gkdnxqi1z-gpgme-1.12.0-info...
```
</p></details>

2018-10-18 12:42 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=5aff3555-04f7-4d32-b411-455ddeb9de6b-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46304&attempt_id=69517e90-2a8e-498e-b21a-865208f5dd24)

Attempted: python3Packages.gpgme

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking /nix/store/p265lww9xk8lzg0fbjlvwg936w67bny9-gpgme-1.12.0-dev/bin/gpgme-json
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/p265lww9xk8lzg0fbjlvwg936w67bny9-gpgme-1.12.0-dev/bin
patching script interpreter paths in /nix/store/p265lww9xk8lzg0fbjlvwg936w67bny9-gpgme-1.12.0-dev
/nix/store/p265lww9xk8lzg0fbjlvwg936w67bny9-gpgme-1.12.0-dev/bin/gpgme-config: interpreter directive changed from "/bin/sh" to "/nix/store/r47p5pzx52m3n34vdgqpk5rvqgm0m24m-bash-4.4-p23/bin/sh"
checking for references to /build in /nix/store/p265lww9xk8lzg0fbjlvwg936w67bny9-gpgme-1.12.0-dev...
shrinking RPATHs of ELF executables and libraries in /nix/store/lbrvq1bw203d0939c2n16x2ns6gaja13-gpgme-1.12.0-info
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/lbrvq1bw203d0939c2n16x2ns6gaja13-gpgme-1.12.0-info
checking for references to /build in /nix/store/lbrvq1bw203d0939c2n16x2ns6gaja13-gpgme-1.12.0-info...
```
</p></details>

2018-10-18 12:45 UTC, teto commented
@primeos true my comment was a bit cryptic. I just looked for the gpgme maintainers to see if I could do anything to merge this. GrahamcOfBorg  didn't trigger on my force push but it now compiles (and works with the mail client `alot`)

2018-10-18 22:21 UTC, primeos requested changes

2018-10-19 06:09 UTC, teto commented on pkgs/development/libraries/gpgme/default.nix
> +, pythonSupport ? false, swig2 ? null, python ? null
I remember a PR to improve python docs where I suggested to add it but can't find it again. Another suggestion is https://github.com/NixOS/nixpkgs/commit/39e9de1b85f1bec437333ed684cb0dc8cfe715c8#r29184438 .
I am for changing the parameter name as my main grip with nixpkgs is its lack of consistency (across languages mainly).
People needing the python support must have been using pythonPackages.gpgme so it should impact 0 or few people. 

I am not sure quite why we need ncurses except for this command line done by gpgme.
```
configure:20006: checking consistency of all components of python development environment
configure:20032: gcc -o conftest -g -O2  -I/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/include/python3.6m  conftest.c  -L/nix/store/hy65mn4wjswqih75gfr6g4q3xgqdm325-python3-3.6.6/lib -lpython3.6m -Xlinker -export-dynamic -lpthread -ldl -lcrypt -lncurses -lutil -lm >&5
/nix/store/h0lbngpv6ln56hjj59i6l77vxq25flbz-binutils-2.30/bin/ld: cannot find -lncurses
```
anyway I request ncurses only when python is used.

2018-10-19 19:59 UTC, primeos commented on pkgs/development/libraries/gpgme/default.nix
> +, pythonSupport ? false, swig2 ? null, python ? null
Ok, thanks for elaborating. You're right, due to `pythonPackages.gpgme` this shouldn't cause much problems :)

2018-10-19 20:15 UTC, primeos approved these changes
Thanks, all rebuilds still succeed :)

2018-10-19 20:17 UTC, merged