mage: init at 1.2.4
NixOS/nixpkgs pull request #46407
Opened 2018-09-08 23:54 UTC by swdunlop

###### Motivation for this change

add mage, a make-like tool using Go

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-09-23 08:03 UTC, nlewo requested changes

2018-09-23 08:03 UTC, nlewo commented on pkgs/development/tools/build-managers/mage/default.nix
> +  buildFlagsArray = ("-ldflags=-X github.com/magefile/mage/mage.gitTag=${rev}");
And use `version` here.

2018-11-18 16:32 UTC, c0bw3b commented
@GrahamcOfBorg build mage

2018-11-18 16:32 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=60d4309d-af3f-4b8d-9cb3-c218c598a9bc-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46407&attempt_id=2be271d6-e920-4d82-853a-1938e34afd13)

Attempted: mage

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking RPATHs of ELF executables and libraries in /nix/store/ghz94488wan8z2rarm742lyc7s7w2cmg-mage-1.7.1-bin
shrinking /nix/store/ghz94488wan8z2rarm742lyc7s7w2cmg-mage-1.7.1-bin/bin/mage
cannot find section .dynamic
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/ghz94488wan8z2rarm742lyc7s7w2cmg-mage-1.7.1-bin/bin
patching script interpreter paths in /nix/store/ghz94488wan8z2rarm742lyc7s7w2cmg-mage-1.7.1-bin
checking for references to /build in /nix/store/ghz94488wan8z2rarm742lyc7s7w2cmg-mage-1.7.1-bin...
cannot find section .dynamic
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
/nix/store/ghz94488wan8z2rarm742lyc7s7w2cmg-mage-1.7.1-bin
```
</p></details>

2018-11-18 16:33 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=60d4309d-af3f-4b8d-9cb3-c218c598a9bc-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46407&attempt_id=ae523d85-75f7-4b6a-aa83-7228e516c15b)

Attempted: mage

<details><summary>Partial log (click to expand)</summary><p>

```
shrinking RPATHs of ELF executables and libraries in /nix/store/xi34ywzf20kf7kq091ali3x9l4gmvhcf-mage-1.7.1-bin
shrinking /nix/store/xi34ywzf20kf7kq091ali3x9l4gmvhcf-mage-1.7.1-bin/bin/mage
cannot find section .dynamic
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/xi34ywzf20kf7kq091ali3x9l4gmvhcf-mage-1.7.1-bin/bin
patching script interpreter paths in /nix/store/xi34ywzf20kf7kq091ali3x9l4gmvhcf-mage-1.7.1-bin
checking for references to /build in /nix/store/xi34ywzf20kf7kq091ali3x9l4gmvhcf-mage-1.7.1-bin...
cannot find section .dynamic
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
/nix/store/xi34ywzf20kf7kq091ali3x9l4gmvhcf-mage-1.7.1-bin
```
</p></details>

2018-11-18 16:35 UTC, merged