mako: init at 1.1
NixOS/nixpkgs pull request #46606
Opened 2018-09-13 13:51 UTC by dywedir

`mako` currently works on Sway 1.0 alpha.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-09-13 14:04 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=19f98751-8987-45fb-a117-2b419c9e6c80-->
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46606&attempt_id=5ddd0f72-2968-4e04-8df2-b4b27b3bc0d9)

The following builds were skipped because they don't evaluate on aarch64-linux: mako

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-09-13 14:04 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=19f98751-8987-45fb-a117-2b419c9e6c80-->
No attempt on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46606&attempt_id=a61a0b77-b53c-4cd6-bfb0-af5b21139cda)

The following builds were skipped because they don't evaluate on x86_64-linux: mako

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowBroken = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowBroken = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-09-13 17:58 UTC, xeji requested changes
I don't think we should add a new package in a broken state. Should not be merged until non-broken.

2018-09-13 18:45 UTC, dywedir commented
Just a note that `mako` is not broken per se, but just useless without a compositor that supports `zwlr_layer_shell_v1` protocol

2018-09-13 18:52 UTC, xeji commented
Thank you for clarifying. I suggest to leave this PR open and mark it as WIP until that compositor is available. Unfortunately there seems to be no published timeline for the sway 1.0 release.

2018-10-23 19:03 UTC, dywedir commented
@GrahamcOfBorg build mako

2018-10-23 19:03 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=00c5a747-1af0-443a-8177-f15cc77b3276-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46606&attempt_id=29361232-3908-4ea5-906f-ca82b2e39674)

Attempted: mako

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/9hvcyv9gm3cg41y40b6cs9vbgxfni9md-mako-1.1
shrinking /nix/store/9hvcyv9gm3cg41y40b6cs9vbgxfni9md-mako-1.1/bin/mako
gzipping man pages under /nix/store/9hvcyv9gm3cg41y40b6cs9vbgxfni9md-mako-1.1/share/man/
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/9hvcyv9gm3cg41y40b6cs9vbgxfni9md-mako-1.1/bin
patching script interpreter paths in /nix/store/9hvcyv9gm3cg41y40b6cs9vbgxfni9md-mako-1.1
/nix/store/9hvcyv9gm3cg41y40b6cs9vbgxfni9md-mako-1.1/bin/makoctl: interpreter directive changed from "/bin/sh" to "/nix/store/dsyc1z7ck08ga7l0b1jcxx35wj69qcii-bash-4.4-p23/bin/sh"
checking for references to /build in /nix/store/9hvcyv9gm3cg41y40b6cs9vbgxfni9md-mako-1.1...
/nix/store/9hvcyv9gm3cg41y40b6cs9vbgxfni9md-mako-1.1
```
</p></details>

2018-10-23 19:04 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=00c5a747-1af0-443a-8177-f15cc77b3276-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.46606&attempt_id=72536175-f7ea-480c-bc7a-cc506faeb8f8)

Attempted: mako

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/p96gppkch1b5bb84s662mcdn3gdkax3y-mako-1.1
shrinking /nix/store/p96gppkch1b5bb84s662mcdn3gdkax3y-mako-1.1/bin/mako
gzipping man pages under /nix/store/p96gppkch1b5bb84s662mcdn3gdkax3y-mako-1.1/share/man/
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/p96gppkch1b5bb84s662mcdn3gdkax3y-mako-1.1/bin
patching script interpreter paths in /nix/store/p96gppkch1b5bb84s662mcdn3gdkax3y-mako-1.1
/nix/store/p96gppkch1b5bb84s662mcdn3gdkax3y-mako-1.1/bin/makoctl: interpreter directive changed from "/bin/sh" to "/nix/store/r47p5pzx52m3n34vdgqpk5rvqgm0m24m-bash-4.4-p23/bin/sh"
checking for references to /build in /nix/store/p96gppkch1b5bb84s662mcdn3gdkax3y-mako-1.1...
/nix/store/p96gppkch1b5bb84s662mcdn3gdkax3y-mako-1.1
```
</p></details>

2018-10-23 19:07 UTC, dywedir commented
@xeji since we have `sway-beta`, this is probably good to go

2018-10-23 20:12 UTC, xeji approved these changes

2018-10-23 20:12 UTC, merged