Remove dontCheck on Hasktags
NixOS/nixpkgs pull request #47111
Opened 2018-09-21 11:32 UTC by jhenahan

https://github.com/MarcWeber/hasktags/issues/52 has been closed and a new version (0.71.1) has been released. Will need to wait for the Hackage update before this can be merged, but then it should be AOK.

###### Motivation for this change

Cleaning up exceptions in `configuration-common.nix`.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-09-21 12:37 UTC, basvandijk commented
Could you target the `haskell-updates` branch instead of `master`? Then it will be merged together with the Hackage update.

2018-09-21 12:38 UTC, basvandijk commented
BTW in case you don't know how to do this from an existing PR: press the "Edit" button beside the title and use the "base" combobox.

2018-09-21 12:55 UTC, jhenahan commented
Done!

2018-09-21 15:11 UTC, jhenahan commented
Should be all squared, now.

2018-09-21 15:40 UTC, basvandijk commented
Great, could you also rename your commit according to [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md). Maybe something like:

"haskellPackages.hasktags: remove dontCheck"

2018-09-21 16:11 UTC, jhenahan commented
Done and done.

2018-09-21 17:02 UTC, ryantm commented
@GrahamcOfBorg build haskellPackages.hasktags

2018-09-21 17:03 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=2b53a09b-4160-4dc7-9930-c594ef3319ba-->
No attempt on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47111&attempt_id=40de6cf7-f94c-4018-b4a6-58e3523539fb)

The following builds were skipped because they don't evaluate on aarch64-linux: haskellPackages.hasktags

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-09-21 17:03 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=2b53a09b-4160-4dc7-9930-c594ef3319ba-->
Failure on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47111&attempt_id=5e935bc1-ff75-4247-b69d-efa1e498be1b)

Attempted: haskellPackages.hasktags

<details><summary>Partial log (click to expand)</summary><p>

```
### Failure in: 6:16.hs:0:these were not found
tests/Test.hs:39
expected: ["t2","t3","t4","t5"]
 but got: []
Cases: 156  Tried: 156  Errors: 0  Failures: 1
Test suite testsuite: FAIL
Test suite logged to: dist/test/hasktags-0.70.1-testsuite.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/pcy1yb2xd05wxsvyv3z7v9raws6cm3f7-hasktags-0.70.1.drv' failed with exit code 1
error: build of '/nix/store/pcy1yb2xd05wxsvyv3z7v9raws6cm3f7-hasktags-0.70.1.drv' failed
```
</p></details>

2018-09-21 17:09 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=2b53a09b-4160-4dc7-9930-c594ef3319ba-->
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47111&attempt_id=b4e42c7e-3a38-4b4d-93e9-d7b5f77e14f4)

Attempted: haskellPackages.hasktags

<details><summary>Partial log (click to expand)</summary><p>

```
### Failure in: 21:16.hs:0:these were not found
tests/Test.hs:39
expected: ["t2","t3","t4","t5"]
 but got: []
Cases: 156  Tried: 156  Errors: 0  Failures: 1
Test suite testsuite: FAIL
Test suite logged to: dist/test/hasktags-0.70.1-testsuite.log
0 of 1 test suites (0 of 1 test cases) passed.
builder for '/nix/store/x0lljz9qj0gbmj7r09ban8pldrf1flw0-hasktags-0.70.1.drv' failed with exit code 1
error: build of '/nix/store/x0lljz9qj0gbmj7r09ban8pldrf1flw0-hasktags-0.70.1.drv' failed
```
</p></details>

2018-09-21 17:12 UTC, ryantm reviewed
Looks like the new version isn't on the `haskell-updates` branch yet, so we should still wait to merge.

2018-10-12 12:57 UTC, Infinisil commented
Will build fine with current haskell-updates, for reference, assuming your upstream is named upstream, this is how to update this branch:
```bash
git fetch upstream
git reset --hard upstream/haskell-updates
git cherry-pick 231a2b3eba214d037538e2eccd367f3cc1fbfe47
```

2018-10-14 16:51 UTC, peti requested changes
Please don't edit `hackage-packages.nix`. See the comment at the top of the file.

2018-10-14 17:33 UTC, Infinisil commented
@peti Again, it seems that this user has some git trouble, they only meant to include the last commit

2018-10-15 08:52 UTC, peti commented
> It seems that this user has some git trouble, they only meant to include the last commit

Whatever caused this change, it needs to be fixed before we can merge this PR.

2018-10-15 13:38 UTC, jhenahan commented
Fixed.

2018-10-15 16:09 UTC, ryantm commented
@GrahamcOfBorg build haskellPackages.hasktags

2018-10-15 16:11 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=26d77aa0-05e8-4285-ac98-21fd44e14d14-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47111&attempt_id=10653403-ee4a-48cb-bd6a-0ee8a4d885a6)

Attempted: haskellPackages.hasktags

<details><summary>Partial log (click to expand)</summary><p>

```
Warning: The directory
/nix/store/3qmdslrs6anbxvvzs5dkqs94p0kmsk06-hasktags-0.71.2/bin is not in the
system search path.
post-installation fixup
strip is /nix/store/53nysl8bqwxihwzs1pgwka20nf8mbvlp-cctools-binutils-darwin/bin/strip
stripping (with command strip and flags -S) in /nix/store/3qmdslrs6anbxvvzs5dkqs94p0kmsk06-hasktags-0.71.2/lib  /nix/store/3qmdslrs6anbxvvzs5dkqs94p0kmsk06-hasktags-0.71.2/bin
patching script interpreter paths in /nix/store/3qmdslrs6anbxvvzs5dkqs94p0kmsk06-hasktags-0.71.2
strip is /nix/store/53nysl8bqwxihwzs1pgwka20nf8mbvlp-cctools-binutils-darwin/bin/strip
patching script interpreter paths in /nix/store/m2w0gp5ins7vqixd01m774xh40h7pa2b-hasktags-0.71.2-doc
/nix/store/3qmdslrs6anbxvvzs5dkqs94p0kmsk06-hasktags-0.71.2
```
</p></details>

2018-10-15 16:11 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=26d77aa0-05e8-4285-ac98-21fd44e14d14-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47111&attempt_id=83f24a0e-8599-40d5-9241-cdad950055f2)

Attempted: haskellPackages.hasktags

<details><summary>Partial log (click to expand)</summary><p>

```
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/n50l8paa0jdlgp806mzrgqj759y4wdd0-hasktags-0.71.2/lib  /nix/store/n50l8paa0jdlgp806mzrgqj759y4wdd0-hasktags-0.71.2/bin
patching script interpreter paths in /nix/store/n50l8paa0jdlgp806mzrgqj759y4wdd0-hasktags-0.71.2
checking for references to /build in /nix/store/n50l8paa0jdlgp806mzrgqj759y4wdd0-hasktags-0.71.2...
wrong ELF type
shrinking RPATHs of ELF executables and libraries in /nix/store/f00l2zkqjny6n359qkrfr2bh2vg3l0s3-hasktags-0.71.2-doc
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/f00l2zkqjny6n359qkrfr2bh2vg3l0s3-hasktags-0.71.2-doc
checking for references to /build in /nix/store/f00l2zkqjny6n359qkrfr2bh2vg3l0s3-hasktags-0.71.2-doc...
/nix/store/n50l8paa0jdlgp806mzrgqj759y4wdd0-hasktags-0.71.2
```
</p></details>

2018-10-15 16:13 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=26d77aa0-05e8-4285-ac98-21fd44e14d14-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47111&attempt_id=9744343d-b754-4164-b6d0-fe1d9a251a35)

Attempted: haskellPackages.hasktags

<details><summary>Partial log (click to expand)</summary><p>

```
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/7vcbnhiajlapx5cm20kx4f3h9b49wacw-hasktags-0.71.2/lib  /nix/store/7vcbnhiajlapx5cm20kx4f3h9b49wacw-hasktags-0.71.2/bin
patching script interpreter paths in /nix/store/7vcbnhiajlapx5cm20kx4f3h9b49wacw-hasktags-0.71.2
checking for references to /build in /nix/store/7vcbnhiajlapx5cm20kx4f3h9b49wacw-hasktags-0.71.2...
wrong ELF type
shrinking RPATHs of ELF executables and libraries in /nix/store/k37qpqym5bm50kljd4b53f9g9gb9iami-hasktags-0.71.2-doc
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/k37qpqym5bm50kljd4b53f9g9gb9iami-hasktags-0.71.2-doc
checking for references to /build in /nix/store/k37qpqym5bm50kljd4b53f9g9gb9iami-hasktags-0.71.2-doc...
/nix/store/7vcbnhiajlapx5cm20kx4f3h9b49wacw-hasktags-0.71.2
```
</p></details>

2018-10-15 17:45 UTC, merged

2018-10-15 17:45 UTC, ryantm commented
Thanks!