aws-env: init at 0.4
NixOS/nixpkgs pull request #47414
Opened 2018-09-27 04:15 UTC by ento

###### Motivation for this change

This PR adds aws-env, a useful tool for pulling environment-specific variables from AWS Systems Manager Parameter Store.

The contributing guide requires that `meta.maintainers` be set; I'm not really good at being a maintainer - what'd be the protocol in that case?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-09-28 07:19 UTC, srhb commented
@GrahamcOfBorg build aws-env

@ento I don't believe it's a hard requirement that new packages absolutely *must* have a maintainer, but it certainly is preferable by a large margin, so that people at least have someone to ping on github to ask for reviews of version bumps etc.

2018-09-28 07:20 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=2cc0ae52-0fc6-4f9e-a652-5536e820bc33-->
No attempt on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47414&attempt_id=aeb58aa6-f7c3-4e25-b1b7-ce0ad468b8bc)

The following builds were skipped because they don't evaluate on x86_64-linux: aws-env

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `aws-env' because:
error: attribute 'aws-env' in selection path 'aws-env' not found

```
</p></details>

2018-09-28 07:20 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=2cc0ae52-0fc6-4f9e-a652-5536e820bc33-->
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47414&attempt_id=cb221d74-a894-472e-8b85-77db77597925)

The following builds were skipped because they don't evaluate on x86_64-darwin: aws-env

<details><summary>Partial log (click to expand)</summary><p>

```
Cannot nix-instantiate `aws-env' because:
error: attribute 'aws-env' in selection path 'aws-env' not found

```
</p></details>

2018-09-28 07:21 UTC, srhb requested changes

2018-09-28 21:29 UTC, ento commented on pkgs/tools/admin/aws-env/default.nix
> +  src = fetchgit {
Done: 0e1e742

2018-09-28 21:32 UTC, ento commented
D'oh, added to all-packages.nix in 6e8a5b0. I can squash the commits if that's preferable.

re: maintainer - got it. Is the ping more for Nix expertise or for knowledge of the package content itself?

2018-09-29 07:35 UTC, srhb commented
@ento I'd say in this case where it's a relative simple package, the question that people will mostly be aiming at the maintainer is probably "hey, I updated this package, is that OK?"

And yes please, squash 'em. :)

2018-09-29 07:36 UTC, srhb commented
@GrahamcOfBorg build aws-env

2018-09-29 07:36 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=18b20f54-74b4-4681-8711-e4765d159c1e-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47414&attempt_id=fe777c11-2c3b-4f65-935c-2d00d2c1296c)

Attempted: aws-env

<details><summary>Partial log (click to expand)</summary><p>

```
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/hirysfpkgwbmkjjqyrnahn48mnd3gyq8-aws-env-0.4-bin
shrinking /nix/store/hirysfpkgwbmkjjqyrnahn48mnd3gyq8-aws-env-0.4-bin/bin/aws-env
strip is /nix/store/y4ymnvgxygpq05h03kyzbj572zmh6zla-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/hirysfpkgwbmkjjqyrnahn48mnd3gyq8-aws-env-0.4-bin/bin
patching script interpreter paths in /nix/store/hirysfpkgwbmkjjqyrnahn48mnd3gyq8-aws-env-0.4-bin
checking for references to /build in /nix/store/hirysfpkgwbmkjjqyrnahn48mnd3gyq8-aws-env-0.4-bin...
strip is /nix/store/y4ymnvgxygpq05h03kyzbj572zmh6zla-binutils-2.30/bin/strip
/nix/store/hirysfpkgwbmkjjqyrnahn48mnd3gyq8-aws-env-0.4-bin
```
</p></details>

2018-09-29 07:37 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=18b20f54-74b4-4681-8711-e4765d159c1e-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47414&attempt_id=bf7cf68e-3a2d-41cf-8325-54aea57d4356)

Attempted: aws-env

<details><summary>Partial log (click to expand)</summary><p>

```
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
find: '/nix/store/110sbxhjfa87a3pd1y2w3bgxqg12plbl-aws-env-0.4': No such file or directory
/nix/store/fsvk8f3qrhmgn21wzn848iriymdcm269-aws-env-0.4-bin
```
</p></details>

2018-09-29 07:37 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=18b20f54-74b4-4681-8711-e4765d159c1e-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.47414&attempt_id=90bf9b3c-1f5d-4b12-a35d-fd26f663ab41)

Attempted: aws-env

<details><summary>Partial log (click to expand)</summary><p>

```
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/7gi1dcjvdhfh3v60d0ikckf54vi5imnl-aws-env-0.4-bin
shrinking /nix/store/7gi1dcjvdhfh3v60d0ikckf54vi5imnl-aws-env-0.4-bin/bin/aws-env
strip is /nix/store/h0lbngpv6ln56hjj59i6l77vxq25flbz-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/7gi1dcjvdhfh3v60d0ikckf54vi5imnl-aws-env-0.4-bin/bin
patching script interpreter paths in /nix/store/7gi1dcjvdhfh3v60d0ikckf54vi5imnl-aws-env-0.4-bin
checking for references to /build in /nix/store/7gi1dcjvdhfh3v60d0ikckf54vi5imnl-aws-env-0.4-bin...
strip is /nix/store/h0lbngpv6ln56hjj59i6l77vxq25flbz-binutils-2.30/bin/strip
/nix/store/7gi1dcjvdhfh3v60d0ikckf54vi5imnl-aws-env-0.4-bin
```
</p></details>

2018-10-02 22:52 UTC, ento commented
They've been squashed.

> "hey, I updated this package, is that OK?"

Being a mere user of aws-env, I'll only be able to say "I guess?" and double-check any open issues for aws-env at most. So I'll cc @orfin for any interest in having your name listed as a maintainer / point of contact for aws-env in [Nix](https://nixos.org/nix/) (if there's interest, we can update the package metadata in a separate PR), and ask the good reviewer(s) of nixpkgs to consider it a non-blocker to have no maintainer listed for this package for now.

2018-10-03 08:40 UTC, srhb commented
@ento Alright, but I'd feel bad adding a package with no maintainer, so can you please add me (`stdenv.lib.maintainers.srhb`) for now and resquash, and I'll take it upon me to forward any request that requires deeper knowledge of the tool to relevant people.

2018-10-03 08:40 UTC, srhb approved these changes

2018-10-08 02:48 UTC, ento commented
@srhb Thank you, much appreciated. I've updated `maintainers` and force-pushed.

2018-10-08 09:52 UTC, srhb commented
Thank you. :)

2018-10-08 09:52 UTC, merged