cedille: init at v1.0.0
NixOS/nixpkgs pull request #48288
Opened 2018-10-12 21:30 UTC by mpickering

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-10-12 21:46 UTC, mpickering commented
I should also probably package the elisp code but that can be a separate PR I think? I need to check what agda does.

2018-10-13 17:07 UTC, mpickering commented
I packaged the elisp now as well.

Here's an example of how to set up emacs to use this modes.

https://gist.github.com/0971d372954137c4578ae9c06d31414c

```
let
  np = import <nixpkgs> {};
  myEmacsConfig = np.writeText "default.el" ''
;; initialize package
(require 'package)
(package-initialize 'noactivate)
;; load some packages
(setq cedille-path "${np.cedille}/bin")
(require 'cedille-mode)
    '';
    myEmacs = np.emacsWithPackages (epkgs: (with epkgs; [
      (np.runCommand "default.el" {} ''
mkdir -p $out/share/emacs/site-lisp
cp ${myEmacsConfig} $out/share/emacs/site-lisp/default.el
'')
      np.emacsPackages.cedille
      melpaStablePackages.use-package
    ]));
in
  np.mkShell { buildInputs = [ myEmacs ];}
```

2018-10-14 15:12 UTC, infinisil requested changes
Would be nice to have the emacs mode patched so that it finds the cedille binary by default, see https://github.com/cedille/cedille/blob/0cac62eef32b49af77c475f1b3f4d271f83a0b4b/cedille-mode.el#L32

Also, eval error needs to be fixed, not sure what's up with that

2018-10-14 15:12 UTC, Infinisil commented on pkgs/applications/science/logic/cedille/default.nix
> +in
empty let in

2018-10-14 17:13 UTC, mpickering commented
I have no idea why CI fails.

2018-10-14 17:57 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=b1ef2340-d58c-4619-a3c8-fe320fb7bded-->
Unexpected error: command failed with exit code 1 on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=39bb5606-e4a8-4227-886d-409e60f0e89a)

Attempted: cedille

<details><summary>Partial log (click to expand)</summary><p>

```
copying path '/nix/store/sxmgwq3dj5lfxifjsynz62hr9bxw4hzz-Agda-2.5.4.1' from 'https://cache.nixos.org'...

trying https://github.com/cedille/ial/archive/v1.4.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   119    0   119    0     0    252      0 --:--:-- --:--:-- --:--:--   251
100 57443    0 57443    0     0  48312      0 --:--:--  0:00:01 --:--:-- 3015k
unpacking source archive /private/tmp/nix-build-source.drv-1/v1.4.0.tar.gz
cannot build derivation '/nix/store/d2f78hp4z3ydysyhgpqg46iw5g88nbgx-cedille-1.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/d2f78hp4z3ydysyhgpqg46iw5g88nbgx-cedille-1.0.0.drv' failed
```
</p></details>

2018-10-14 18:01 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=b1ef2340-d58c-4619-a3c8-fe320fb7bded-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=6dfacd8c-8b50-4a33-be33-08452f52dbc7)

Attempted: cedille

<details><summary>Partial log (click to expand)</summary><p>

```
mv src/main cedille
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/hhbys81xvj0fsxz4gi4v8kf09mq06cp4-cedille-1.0.0
shrinking /nix/store/hhbys81xvj0fsxz4gi4v8kf09mq06cp4-cedille-1.0.0/bin/cedille
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/hhbys81xvj0fsxz4gi4v8kf09mq06cp4-cedille-1.0.0/bin
patching script interpreter paths in /nix/store/hhbys81xvj0fsxz4gi4v8kf09mq06cp4-cedille-1.0.0
checking for references to /build in /nix/store/hhbys81xvj0fsxz4gi4v8kf09mq06cp4-cedille-1.0.0...
/nix/store/hhbys81xvj0fsxz4gi4v8kf09mq06cp4-cedille-1.0.0
```
</p></details>

2018-10-14 18:12 UTC, mpickering commented
Should be good to merge now.

2018-10-14 18:15 UTC, Infinisil commented
Why the hash mismatch on Darwin though?

2018-10-14 18:56 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=b1ef2340-d58c-4619-a3c8-fe320fb7bded-->
Timed out, unknown build status on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=965c6541-b18c-4d90-87eb-ce3371f5390f)

Attempted: cedille

<details><summary>Partial log (click to expand)</summary><p>

```
cannot build derivation '/nix/store/529sabir90d9s37qhm8pfdnqmchl5q3d-unordered-containers-0.2.9.0.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/mvyh0yjafc7zjc23clyx8ad3s6r2qywk-tasty-1.1.0.3.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/cwbn2i2n3pdp96mpscdakxgn0fv3frxv-uri-encode-1.5.0.5.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/gi91g8hngmma5lri66gciqz9r73wfp9i-tasty-hunit-0.10.0.1.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/cvmlb04njlzy6vbx1wf3dll0shjp97fq-tasty-quickcheck-0.10.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/i23wf2yjnil909myxa651grc4wwa0194-blaze-markup-0.8.2.2.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/l86hjyxf6zngsr8nv7cfdcd316ib8mdm-blaze-html-0.9.1.1.drv': 10 dependencies couldn't be built
cannot build derivation '/nix/store/pvzymxfsckb6i7rkhx5w1zyawcncj64d-Agda-2.5.4.1.drv': 24 dependencies couldn't be built
cannot build derivation '/nix/store/drc00psxyr5a0q2nky7zzx6zi4v5ysap-cedille-1.0.0.drv': 4 dependencies couldn't be built
error: build of '/nix/store/drc00psxyr5a0q2nky7zzx6zi4v5ysap-cedille-1.0.0.drv' failed
```
</p></details>

2018-10-14 18:57 UTC, mpickering commented
I don't know but it's a standard use of `fetchFromGitHub`.

2018-10-14 19:00 UTC, Infinisil commented
Let's just try again, maybe it'll work now

@GrahamcOfBorg build cedille

2018-10-14 19:01 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=7aca8659-f0c4-4365-929b-ff3784359946-->
Unexpected error: command failed with exit code 1 on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=eb40855e-a234-4aaf-bb16-f2c0cc677ca4)

Attempted: cedille

<details><summary>Partial log (click to expand)</summary><p>

```

trying https://github.com/cedille/cedille/archive/v1.0.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   123    0   123    0     0    247      0 --:--:-- --:--:-- --:--:--   247
100 1892k    0 1892k    0     0  1074k      0 --:--:--  0:00:01 --:--:-- 3724k
unpacking source archive /private/tmp/nix-build-source.drv-0/v1.0.0.tar.gz
fixed-output derivation produced path '/nix/store/3zp53g8817gc224ydbwjd1xy26cs771n-source' with sha256 hash '0csbi1mp72na5j5ymy2fhkn6bcyxp443dxwl1aphcq4inwy0r95g' instead of the expected hash '08c2vgg8i6l3ws7hd5gsj89mki36lxm7x7s8hi1qa5gllq04a832'
cannot build derivation '/nix/store/d2f78hp4z3ydysyhgpqg46iw5g88nbgx-cedille-1.0.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/d2f78hp4z3ydysyhgpqg46iw5g88nbgx-cedille-1.0.0.drv' failed
```
</p></details>

2018-10-14 19:01 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=7aca8659-f0c4-4365-929b-ff3784359946-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=84ff9b46-cc17-4c98-991f-ab6ee0157282)

Attempted: cedille

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/hhbys81xvj0fsxz4gi4v8kf09mq06cp4-cedille-1.0.0
```
</p></details>

2018-10-14 19:10 UTC, infinisil approved these changes
@LnL7 mentioned in #nixos-borg that it might be unicode normalization on macOS, see also https://github.com/NixOS/nixpkgs/pull/48128#issuecomment-429195465

Seems fine to me then :)

2018-10-14 19:14 UTC, Infinisil commented
Oh actually, one last thing: The commits are named a bit unconventional. First one should be `agdaIowaStdlib: 18734 -> 1.4.0`, second should be `cedille: init at 1.0.0`, third should be `emacsPackages.cedille: init at 1.0.0`

2018-10-14 19:30 UTC, merged

2018-10-14 19:34 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=18b94dd7-83ed-4771-8873-68de530d3cb9-->
Unexpected error: command failed with exit code 1 on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=e2b1ff06-d55b-4869-a5a5-87912218dc76)

Attempted: agdaIowaStdlib, cedille

<details><summary>Partial log (click to expand)</summary><p>

```
agda  -v 0 sum-thms.agda
agda  -v 0 tree-test.agda
agda  -v 0 trie-thms.agda
agda  -v 0 vector-test.agda
agda  -v 0 vector-sort.agda
installing
post-installation fixup
strip is /nix/store/53nysl8bqwxihwzs1pgwka20nf8mbvlp-cctools-binutils-darwin/bin/strip
patching script interpreter paths in /nix/store/fv8y6qwxywlljnca4yq8p490drl6shr0-agda-iowa-stdlib-1.4.0
error: build of '/nix/store/d2f78hp4z3ydysyhgpqg46iw5g88nbgx-cedille-1.0.0.drv' failed
```
</p></details>

2018-10-14 19:34 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=18b94dd7-83ed-4771-8873-68de530d3cb9-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=c32d8644-6731-49b0-88b7-57d194cbba8b)

Attempted: agdaIowaStdlib, cedille

<details><summary>Partial log (click to expand)</summary><p>

```
agda  -v 0 vector-test.agda
agda  -v 0 vector-sort.agda
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/x4grq4nk1z3p49zlnbqhy3yqdmaai9bb-agda-iowa-stdlib-1.4.0
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
patching script interpreter paths in /nix/store/x4grq4nk1z3p49zlnbqhy3yqdmaai9bb-agda-iowa-stdlib-1.4.0
checking for references to /build in /nix/store/x4grq4nk1z3p49zlnbqhy3yqdmaai9bb-agda-iowa-stdlib-1.4.0...
/nix/store/x4grq4nk1z3p49zlnbqhy3yqdmaai9bb-agda-iowa-stdlib-1.4.0
/nix/store/hhbys81xvj0fsxz4gi4v8kf09mq06cp4-cedille-1.0.0
```
</p></details>

2018-10-14 20:01 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=7aca8659-f0c4-4365-929b-ff3784359946-->
Timed out, unknown build status on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=64152d5c-5b88-479b-bdc2-c1b4b46cb0db)

Attempted: cedille

<details><summary>Partial log (click to expand)</summary><p>

```
cannot build derivation '/nix/store/529sabir90d9s37qhm8pfdnqmchl5q3d-unordered-containers-0.2.9.0.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/mvyh0yjafc7zjc23clyx8ad3s6r2qywk-tasty-1.1.0.3.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/cwbn2i2n3pdp96mpscdakxgn0fv3frxv-uri-encode-1.5.0.5.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/gi91g8hngmma5lri66gciqz9r73wfp9i-tasty-hunit-0.10.0.1.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/cvmlb04njlzy6vbx1wf3dll0shjp97fq-tasty-quickcheck-0.10.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/i23wf2yjnil909myxa651grc4wwa0194-blaze-markup-0.8.2.2.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/l86hjyxf6zngsr8nv7cfdcd316ib8mdm-blaze-html-0.9.1.1.drv': 10 dependencies couldn't be built
cannot build derivation '/nix/store/pvzymxfsckb6i7rkhx5w1zyawcncj64d-Agda-2.5.4.1.drv': 24 dependencies couldn't be built
cannot build derivation '/nix/store/drc00psxyr5a0q2nky7zzx6zi4v5ysap-cedille-1.0.0.drv': 4 dependencies couldn't be built
error: build of '/nix/store/drc00psxyr5a0q2nky7zzx6zi4v5ysap-cedille-1.0.0.drv' failed
```
</p></details>

2018-10-14 21:01 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=18b94dd7-83ed-4771-8873-68de530d3cb9-->
Timed out, unknown build status on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48288&attempt_id=622d523b-552a-40f1-9a6c-076b45d30ded)

Attempted: agdaIowaStdlib, cedille

<details><summary>Partial log (click to expand)</summary><p>

```
cannot build derivation '/nix/store/mvyh0yjafc7zjc23clyx8ad3s6r2qywk-tasty-1.1.0.3.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/cwbn2i2n3pdp96mpscdakxgn0fv3frxv-uri-encode-1.5.0.5.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/gi91g8hngmma5lri66gciqz9r73wfp9i-tasty-hunit-0.10.0.1.drv': 4 dependencies couldn't be built
cannot build derivation '/nix/store/cvmlb04njlzy6vbx1wf3dll0shjp97fq-tasty-quickcheck-0.10.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/i23wf2yjnil909myxa651grc4wwa0194-blaze-markup-0.8.2.2.drv': 9 dependencies couldn't be built
cannot build derivation '/nix/store/l86hjyxf6zngsr8nv7cfdcd316ib8mdm-blaze-html-0.9.1.1.drv': 10 dependencies couldn't be built
cannot build derivation '/nix/store/pvzymxfsckb6i7rkhx5w1zyawcncj64d-Agda-2.5.4.1.drv': 24 dependencies couldn't be built
cannot build derivation '/nix/store/fnxapyxihdfp03a91h0npyy9hs8rirs6-agda-iowa-stdlib-1.4.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/drc00psxyr5a0q2nky7zzx6zi4v5ysap-cedille-1.0.0.drv': 4 dependencies couldn't be built
error: build of '/nix/store/drc00psxyr5a0q2nky7zzx6zi4v5ysap-cedille-1.0.0.drv', '/nix/store/fnxapyxihdfp03a91h0npyy9hs8rirs6-agda-iowa-stdlib-1.4.0.drv' failed
```
</p></details>

2020-05-16 09:53 UTC, adisbladis commented
@mpickering The `cedille` build is failing both on unstable and 20.03.

2020-05-16 09:55 UTC, mpickering commented
@adisbladis Perhaps something which should be fixed by #76653 ? I have not used this package since I packaged it.

2020-05-16 11:45 UTC, adisbladis commented
@mpickering Nope, it's not fixed by #76653.