Pipenv: remove uncessary dependencies
NixOS/nixpkgs pull request #48403
Opened 2018-10-14 13:09 UTC by patjouk

###### Motivation for this change

`invoke`, `parver` and `flake8` are not necessary to install and run pipenv. I replaced `requests` by `certifi`. @domenkozar Do you remember why you added them?

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-10-14 14:09 UTC, FRidh requested changes
See `setup.py`: 
```
    setup_requires=["invoke", "parver"],
```

Please test with sandboxing enabled otherwise pip/setuptools will fetch dependencies from PyPI.

2018-10-14 14:09 UTC, FRidh commented
They should be added as `buildInputs`.

2019-08-09 07:16 UTC, mmahut commented
Any updates on this pull request, please?

2019-10-27 22:33 UTC, prusnak commented
@patjouk ping?

2019-10-28 07:56 UTC, FRidh commented
This has been taken care of in an earlier commit of mine. Closing.

2019-10-28 07:56 UTC, closed without merging