skaffold: init at 0.16.0
NixOS/nixpkgs pull request #48578
Opened 2018-10-16 17:27 UTC by vdemeester

Signed-off-by: Vincent Demeester <vincent@sbr.pm>

###### Motivation for this change

Add [`skaffold`](https://github.com/GoogleContainerTools/skaffold) package to nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-10-19 07:09 UTC, nlewo requested changes

2018-10-19 07:09 UTC, nlewo commented on pkgs/development/tools/skaffold/default.nix
> +{ stdenv, lib, buildGoPackage, fetchFromGitHub }:
`stdenv` is not used

2018-10-19 07:09 UTC, nlewo commented on pkgs/development/tools/skaffold/default.nix
> +    homepage = "https://github.com/GoogleContainerTools/skaffold";
Quote are not necessary for urls.

2018-10-23 08:38 UTC, vdemeester commented
@nlewo updated :angel:

2018-10-23 17:15 UTC, nlewo commented
@GrahamcOfBorg build skaffold

2018-10-23 17:16 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=df30e741-b264-4133-8d3d-14abe05fc5ff-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48578&attempt_id=5d6363d6-7820-45fc-afeb-ba40eaf85100)

Attempted: skaffold

<details><summary>Partial log (click to expand)</summary><p>

```
github.com/GoogleContainerTools/skaffold/cmd/skaffold
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/5qr9wpzjm2lcc475qkgikx2970byw3z5-skaffold-0.16.0-bin
shrinking /nix/store/5qr9wpzjm2lcc475qkgikx2970byw3z5-skaffold-0.16.0-bin/bin/skaffold
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/5qr9wpzjm2lcc475qkgikx2970byw3z5-skaffold-0.16.0-bin/bin
patching script interpreter paths in /nix/store/5qr9wpzjm2lcc475qkgikx2970byw3z5-skaffold-0.16.0-bin
checking for references to /build in /nix/store/5qr9wpzjm2lcc475qkgikx2970byw3z5-skaffold-0.16.0-bin...
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
```
</p></details>

2018-10-23 17:16 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=df30e741-b264-4133-8d3d-14abe05fc5ff-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48578&attempt_id=509887cc-70af-4040-921e-98311433464b)

Attempted: skaffold

<details><summary>Partial log (click to expand)</summary><p>

```
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
find: '/nix/store/dvkhf43zgflh665ivradvy3nkl0rw8jw-skaffold-0.16.0': No such file or directory
```
</p></details>

2018-10-23 17:16 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=df30e741-b264-4133-8d3d-14abe05fc5ff-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48578&attempt_id=3a2b9547-88c5-4641-b84d-9920b801ade7)

Attempted: skaffold

<details><summary>Partial log (click to expand)</summary><p>

```
installing
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/snl7mm7gj0kr7gy8pg4hak0nscakzspm-skaffold-0.16.0-bin
shrinking /nix/store/snl7mm7gj0kr7gy8pg4hak0nscakzspm-skaffold-0.16.0-bin/bin/skaffold
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/snl7mm7gj0kr7gy8pg4hak0nscakzspm-skaffold-0.16.0-bin/bin
patching script interpreter paths in /nix/store/snl7mm7gj0kr7gy8pg4hak0nscakzspm-skaffold-0.16.0-bin
checking for references to /build in /nix/store/snl7mm7gj0kr7gy8pg4hak0nscakzspm-skaffold-0.16.0-bin...
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
/nix/store/snl7mm7gj0kr7gy8pg4hak0nscakzspm-skaffold-0.16.0-bin
```
</p></details>

2018-10-23 18:55 UTC, merged