homely: init at 0.15.3
NixOS/nixpkgs pull request #48837
Opened 2018-10-22 20:09 UTC by lokke-me

Added package meta

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-10-22 21:01 UTC, bhipple requested changes

2018-10-22 21:01 UTC, bhipple commented on pkgs/applications/misc/homely/default.nix
> +                        pythondaemon
As a heads up, I may rename this to its pypi name in https://github.com/NixOS/nixpkgs/pull/47897, pending feedback from @FRidh.

It's cosmetic, but I'd also put requests on the newline to fixup your whitespace a little.

2018-10-22 21:01 UTC, bhipple commented on pkgs/top-level/all-packages.nix
> +  homely = callPackage ../applications/misc/homely {};
We generally try to keep this file somewhat sorted within sections.

2018-10-24 10:00 UTC, xeji requested changes
I see a lot of commits that don't belong here. Please rebase your branch on current master to get rid of them.

2018-10-24 16:40 UTC, closed without merging