pythonPackages.sh: 1.11 -> 1.12.14
NixOS/nixpkgs pull request #48892
Opened 2018-10-23 15:34 UTC by sveitser

###### Motivation for this change
Package update. 

###### Things done

- "Modernize" to the best of my knowledge. 
- Enable unit tests.
- Add MIT license.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS (python2 and 3)
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-10-24 13:29 UTC, FRidh requested changes
We are moving Python expressions out of `pkgs/top-level/python-packages.nix` into `pkgs/development/python-modules/<module>/default.nix`. 

Please move the expression there, and call it from `pkgs/top-level/python-packages.nix` using `callPackage ../development/python-modules/<package> { };`.

2018-10-24 13:29 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    buildInputs = with self; [ coverage ];
checkInputs

2018-10-24 13:29 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +    HOME=$(mktemp -d)
indentation

2018-10-24 14:14 UTC, sveitser commented
@FRidh thanks. I made the changes.

2018-10-29 13:04 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.sh python3.pkgs.sh

2018-10-29 13:05 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=17ff1c5c-21ad-4879-9033-1ae869e510c6-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48892&attempt_id=f049c417-eaa7-4f4b-a34d-80aa32e73de9)

Attempted: python2.pkgs.sh, python3.pkgs.sh

<details><summary>Partial log (click to expand)</summary><p>

```
test_chunk_buffered (test.StreamBuffererTests) ... ok
test_newline_buffered (test.StreamBuffererTests) ... ok
test_unbuffered (test.StreamBuffererTests) ... ok

----------------------------------------------------------------------
Ran 156 tests in 51.859s

OK (skipped=2)
/nix/store/7gf2vp1ldjbx7wypzgmb5nf521k36vdv-python2.7-sh-1.12.14
/nix/store/5qzzgxphwpgbh9l7gqwv20b2yi5g6rcy-python3.6-sh-1.12.14
```
</p></details>

2018-10-29 13:06 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=17ff1c5c-21ad-4879-9033-1ae869e510c6-->
Failure on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48892&attempt_id=87e52997-fa6a-4a20-9509-6aad5ccd66ad)

Attempted: python2.pkgs.sh, python3.pkgs.sh

<details><summary>Partial log (click to expand)</summary><p>

```


----------------------------------------------------------------------
Ran 156 tests in 44.960s

FAILED (errors=2, skipped=2)
Test failed: <unittest.runner.TextTestResult run=156 errors=2 failures=0>
error: Test failed: <unittest.runner.TextTestResult run=156 errors=2 failures=0>
builder for '/nix/store/rahc98r5xahc3kqinrwka5ryci996v8r-python3.6-sh-1.12.14.drv' failed with exit code 1
error: build of '/nix/store/4id5h3wyijxph7w3b3v8g2k4sgcjb6c3-python2.7-sh-1.12.14.drv', '/nix/store/rahc98r5xahc3kqinrwka5ryci996v8r-python3.6-sh-1.12.14.drv' failed
```
</p></details>

2018-10-29 13:06 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=17ff1c5c-21ad-4879-9033-1ae869e510c6-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.48892&attempt_id=e46b8586-bdc1-4c89-b24c-25bb020c0390)

Attempted: python2.pkgs.sh, python3.pkgs.sh

<details><summary>Partial log (click to expand)</summary><p>

```
test_chunk_buffered (test.StreamBuffererTests) ... ok
test_newline_buffered (test.StreamBuffererTests) ... ok
test_unbuffered (test.StreamBuffererTests) ... ok

----------------------------------------------------------------------
Ran 156 tests in 62.206s

OK (skipped=2)
/nix/store/y3x907vyy31rckcnbrjdbdk93249x9p1-python2.7-sh-1.12.14
/nix/store/051rnspbsyzxn0q6rkzb96xmn82mr0n6-python3.6-sh-1.12.14
```
</p></details>

2018-10-29 13:21 UTC, merged