python36Packages.imageio: 1.6 -> 2.4.1
NixOS/nixpkgs pull request #49147
Opened 2018-10-26 11:47 UTC by pmiddend

###### Motivation for this change

A normal update. I tried to keep the nix expression like it was before, although I'm not sure why there's a `checkPhase` and even check dependencies when `doCheck` is false.

I've tested the library itself.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-10-26 11:48 UTC, pmiddend commented
@GrahamcOfBorg build python36Packages.imageio

2018-10-26 11:49 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=c7b45380-d3c7-48d5-ab29-eca546d3fad4-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=7e99fd6f-05e3-43a6-831c-479f7dc643ce)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1/lib  /nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1/bin
patching script interpreter paths in /nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1
checking for references to /build in /nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1...
wrapping `/nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1/bin/imageio_remove_bin'...
wrapping `/nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1/bin/imageio_download_bin'...
pytestcachePhase
/nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1
```
</p></details>

2018-10-26 11:49 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=c7b45380-d3c7-48d5-ab29-eca546d3fad4-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=e58e23ad-f731-4d52-b0af-3307b09b8b10)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/sfnlxf8bk5m15pzd1qhy5zvhzcd0wbk2-python3.6-imageio-2.4.1
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/sfnlxf8bk5m15pzd1qhy5zvhzcd0wbk2-python3.6-imageio-2.4.1/lib  /nix/store/sfnlxf8bk5m15pzd1qhy5zvhzcd0wbk2-python3.6-imageio-2.4.1/bin
patching script interpreter paths in /nix/store/sfnlxf8bk5m15pzd1qhy5zvhzcd0wbk2-python3.6-imageio-2.4.1
checking for references to /build in /nix/store/sfnlxf8bk5m15pzd1qhy5zvhzcd0wbk2-python3.6-imageio-2.4.1...
wrapping `/nix/store/sfnlxf8bk5m15pzd1qhy5zvhzcd0wbk2-python3.6-imageio-2.4.1/bin/imageio_download_bin'...
wrapping `/nix/store/sfnlxf8bk5m15pzd1qhy5zvhzcd0wbk2-python3.6-imageio-2.4.1/bin/imageio_remove_bin'...
pytestcachePhase
/nix/store/sfnlxf8bk5m15pzd1qhy5zvhzcd0wbk2-python3.6-imageio-2.4.1
```
</p></details>

2018-10-26 12:03 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=ae7d106b-be58-4423-bd76-499e1caa48bc-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=48796df2-c30f-4079-a621-ff019edeea3b)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/jlqlmj58m55vm9c8jpmr7zjjq7dasm1f-python3.6-imageio-2.4.1
```
</p></details>

2018-10-26 12:33 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=5f0c9224-70d8-41cc-a73f-43607975df65-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=36f6be4b-7e97-4358-9d3e-44d1a661c2f4)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/1kb1ihsbddffnrzqi6fg1ar1f6ix5rg6-python3.6-imageio-2.4.1
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/1kb1ihsbddffnrzqi6fg1ar1f6ix5rg6-python3.6-imageio-2.4.1/lib  /nix/store/1kb1ihsbddffnrzqi6fg1ar1f6ix5rg6-python3.6-imageio-2.4.1/bin
patching script interpreter paths in /nix/store/1kb1ihsbddffnrzqi6fg1ar1f6ix5rg6-python3.6-imageio-2.4.1
checking for references to /build in /nix/store/1kb1ihsbddffnrzqi6fg1ar1f6ix5rg6-python3.6-imageio-2.4.1...
wrapping `/nix/store/1kb1ihsbddffnrzqi6fg1ar1f6ix5rg6-python3.6-imageio-2.4.1/bin/imageio_download_bin'...
wrapping `/nix/store/1kb1ihsbddffnrzqi6fg1ar1f6ix5rg6-python3.6-imageio-2.4.1/bin/imageio_remove_bin'...
pytestcachePhase
/nix/store/1kb1ihsbddffnrzqi6fg1ar1f6ix5rg6-python3.6-imageio-2.4.1
```
</p></details>

2018-10-26 12:33 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=5f0c9224-70d8-41cc-a73f-43607975df65-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=db60b4fd-cef9-4518-87e5-9e5711628376)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/gyykd3cznrflddljqyqhkgglaaxxh10b-python3.6-imageio-2.4.1
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/gyykd3cznrflddljqyqhkgglaaxxh10b-python3.6-imageio-2.4.1/lib  /nix/store/gyykd3cznrflddljqyqhkgglaaxxh10b-python3.6-imageio-2.4.1/bin
patching script interpreter paths in /nix/store/gyykd3cznrflddljqyqhkgglaaxxh10b-python3.6-imageio-2.4.1
checking for references to /build in /nix/store/gyykd3cznrflddljqyqhkgglaaxxh10b-python3.6-imageio-2.4.1...
wrapping `/nix/store/gyykd3cznrflddljqyqhkgglaaxxh10b-python3.6-imageio-2.4.1/bin/imageio_remove_bin'...
wrapping `/nix/store/gyykd3cznrflddljqyqhkgglaaxxh10b-python3.6-imageio-2.4.1/bin/imageio_download_bin'...
pytestcachePhase
/nix/store/gyykd3cznrflddljqyqhkgglaaxxh10b-python3.6-imageio-2.4.1
```
</p></details>

2018-10-27 13:05 UTC, dotlambda commented
> `# Tries to write in /var/tmp/.imageio`
> `doCheck = false;`

Maybe we can patch the tests to make them run? Or maybe it's sufficient to set some environment variable like `$TMP`.

2018-10-27 16:06 UTC, pmiddend commented
@dotlambda It's a good point. I found out that setting `IMAGEIO_USERDIR="$TMP"` solves the problem, _but_ then the tests begin downloading images from the web. Now, one might be able to download the images in the nix derivation, but...that seems a bit overkill, in my opinion.

2018-10-29 12:08 UTC, pmiddend commented
I'm conversing with the author, let's keep the PR open until that's cleared up.

2018-10-31 11:44 UTC, pmiddend commented
Okay, I've updated the build so the tests work. This can be merged now.

2018-10-31 12:01 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=dcbbcda9-1500-4d62-80e8-989efe57e7c5-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=da6fd0aa-da09-412e-8781-e21e75ffb33d)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
    warnings.warn("%s%s" % (e, warn))

tests/test_pillow.py::test_png
  /nix/store/rbm37a199q06x786xvjh0kp2lid0vjcm-python3.6-imageio-2.4.1/lib/python3.6/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 37.30 seconds =========
pytestcachePhase
/nix/store/rbm37a199q06x786xvjh0kp2lid0vjcm-python3.6-imageio-2.4.1
```
</p></details>

2018-10-31 12:01 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=dcbbcda9-1500-4d62-80e8-989efe57e7c5-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=f66b7819-4b7e-4936-bb55-29a636bd2ff6)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
    warnings.warn("%s%s" % (e, warn))

tests/test_pillow.py::test_png
  /nix/store/98kbqyhh0f1wrg48lkras7fpncvfkjaw-python3.6-imageio-2.4.1/lib/python3.6/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 41.71 seconds =========
pytestcachePhase
/nix/store/98kbqyhh0f1wrg48lkras7fpncvfkjaw-python3.6-imageio-2.4.1
```
</p></details>

2018-10-31 15:39 UTC, dotlambda commented on pkgs/development/python-modules/imageio/default.nix
> +  patches = [ ./xml-extra-module.patch ];
Please use `postPatch` and `substituteInPlace` instead as a patch is rather overkill.

Maybe @FRidh has an idea why `xml` is imported.

2018-11-02 14:09 UTC, pmiddend commented
@dotlambda I removed the patch and replaced with with a `postPatch` phase.

2018-11-03 14:36 UTC, dotlambda requested changes

2018-11-03 14:36 UTC, dotlambda commented on pkgs/development/python-modules/imageio/default.nix
> +  doCheck = true;
No need for this as it is the default for `buildPython*`.

2018-11-03 21:46 UTC, pmiddend commented
@dotlambda Fixed the `doCheck`

2018-11-03 22:02 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=dfcaca30-400d-486d-a049-89563a321973-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=06fcb205-5da7-49b0-b6f4-92dcb790e899)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/m019mqrfs0xhbrrr5dpscm32gdk2fcdf-python3.6-imageio-2.4.1
```
</p></details>

2018-11-03 22:02 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=dfcaca30-400d-486d-a049-89563a321973-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=6aa1b597-4b72-47f2-be70-88e048f458b7)

Attempted: python36Packages.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
    warnings.warn("%s%s" % (e, warn))

tests/test_pillow.py::test_png
  /nix/store/5w6p7s9xvrd8akk3z40bbqwasfhqamv2-python3.6-imageio-2.4.1/lib/python3.6/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 37.31 seconds =========
pytestcachePhase
/nix/store/5w6p7s9xvrd8akk3z40bbqwasfhqamv2-python3.6-imageio-2.4.1
```
</p></details>

2018-11-04 14:01 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.imageio python3.pkgs.imageio

2018-11-04 14:02 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=9e60d47f-8729-4a00-bbfc-0d0beeb1ed25-->
Failure on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=317a519e-e200-4c5f-bbff-b5f26fa2fd0e)

Attempted: python2.pkgs.imageio, python3.pkgs.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
    warnings.warn("%s%s" % (e, warn))

tests/test_pillow.py::test_png
  /nix/store/077iha76h2x7xxyzw2anm2fcyvbgikpk-python3.6-imageio-2.4.1/lib/python3.6/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 19.98 seconds =========
pytestcachePhase
error: build of '/nix/store/kq1rx2miv93b8x3n1d2fiachj7rxbcp3-python2.7-imageio-2.4.1.drv' failed
```
</p></details>

2018-11-04 14:02 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=9e60d47f-8729-4a00-bbfc-0d0beeb1ed25-->
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=b834b155-b36f-4efe-829b-fec5b488f6d5)

Attempted: python2.pkgs.imageio, python3.pkgs.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
    warnings.warn("%s%s" % (e, warn))

tests/test_pillow.py::test_png
  /nix/store/5w6p7s9xvrd8akk3z40bbqwasfhqamv2-python3.6-imageio-2.4.1/lib/python3.6/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 37.25 seconds =========
pytestcachePhase
error: build of '/nix/store/wl2y9g8vv65c2mkp0cdkyhq7qq4k4bhx-python2.7-imageio-2.4.1.drv' failed
```
</p></details>

2018-11-04 14:03 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=9e60d47f-8729-4a00-bbfc-0d0beeb1ed25-->
Failure on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=6c1e8988-6b21-4855-b04f-04f6a23062d5)

Attempted: python2.pkgs.imageio, python3.pkgs.imageio

<details><summary>Partial log (click to expand)</summary><p>

```
    warnings.warn("%s%s" % (e, warn))

tests/test_pillow.py::test_png
  /nix/store/m019mqrfs0xhbrrr5dpscm32gdk2fcdf-python3.6-imageio-2.4.1/lib/python3.6/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 26.34 seconds =========
pytestcachePhase
error: build of '/nix/store/97mni974n1qa17y0rvznnv33wwn9pakx-python2.7-imageio-2.4.1.drv' failed
```
</p></details>

2018-11-04 17:10 UTC, pmiddend commented
@dotlambda I fixed the failures with Python 2. Two more dependencies were needed.

2018-11-04 17:29 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.imageio python3.pkgs.imageio

2018-11-04 17:30 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=261ab32b-458d-4495-b0f6-cfc6e7fed931-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=c62fced9-ad7d-4d2e-8c9e-aa22c510c90c)

Attempted: python2.pkgs.imageio, python3.pkgs.imageio

<details><summary>Partial log (click to expand)</summary><p>

```

tests/test_pillow.py::test_png
  /nix/store/hgv4vl4l2m81d4wx1pw7jcrmfjx0h3jx-python2.7-imageio-2.4.1/lib/python2.7/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 35.68 seconds =========
pytestcachePhase
/nix/store/hgv4vl4l2m81d4wx1pw7jcrmfjx0h3jx-python2.7-imageio-2.4.1
/nix/store/5w6p7s9xvrd8akk3z40bbqwasfhqamv2-python3.6-imageio-2.4.1
```
</p></details>

2018-11-04 17:31 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=261ab32b-458d-4495-b0f6-cfc6e7fed931-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=edcddd08-f207-4309-a064-3ab7418285e8)

Attempted: python2.pkgs.imageio, python3.pkgs.imageio

<details><summary>Partial log (click to expand)</summary><p>

```

tests/test_pillow.py::test_png
  /nix/store/077iha76h2x7xxyzw2anm2fcyvbgikpk-python3.6-imageio-2.4.1/lib/python3.6/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 25.71 seconds =========
pytestcachePhase
/nix/store/q41fa6vb5kmsi7sn7kjnsmq142nf513y-python2.7-imageio-2.4.1
/nix/store/077iha76h2x7xxyzw2anm2fcyvbgikpk-python3.6-imageio-2.4.1
```
</p></details>

2018-11-04 17:31 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=261ab32b-458d-4495-b0f6-cfc6e7fed931-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49147&attempt_id=87723124-0bf7-4c72-be91-c4ecfa7fd788)

Attempted: python2.pkgs.imageio, python3.pkgs.imageio

<details><summary>Partial log (click to expand)</summary><p>

```

tests/test_pillow.py::test_png
  /nix/store/m019mqrfs0xhbrrr5dpscm32gdk2fcdf-python3.6-imageio-2.4.1/lib/python3.6/site-packages/imageio/plugins/pillow.py:317: UserWarning: PIL PNG writer cannot produce interlaced images.
    warn("PIL PNG writer cannot produce interlaced images.")

-- Docs: https://docs.pytest.org/en/latest/warnings.html
======== 56 passed, 67 skipped, 3 xfailed, 5 warnings in 41.79 seconds =========
pytestcachePhase
/nix/store/mf4m78grgdf9ciz751i3x4h3giv8g4b7-python2.7-imageio-2.4.1
/nix/store/m019mqrfs0xhbrrr5dpscm32gdk2fcdf-python3.6-imageio-2.4.1
```
</p></details>

2018-11-04 17:32 UTC, merged