Add pre-commit and its dependencies
NixOS/nixpkgs pull request #49163
Opened 2018-10-26 16:05 UTC by jfroche

pre-commit is "a framework for managing and maintaining multi-language
pre-commit hooks". More info here: https://pre-commit.com

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-10-26 16:41 UTC, worldofpeace requested changes
Please split up these changes into multiple commits.

Precisely like:

- add yourself to the maintainers list
```
maintainers: add name
```

- one each for package initialization 
```
pkg-name: init at version
```
Also preferably with its dependents preceding pre-commit.

##### More can be seen in [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)

2018-10-27 12:55 UTC, dotlambda requested changes

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/importlib-metadata/default.nix
> +  name = "importlib_metadata";
drop this line

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/importlib-metadata/default.nix
> +  pythonPath = [ recursivePthLoader ];
Why is this needed? Why don't you use `propagatedBuildInputs` or `nativeBuildInputs`?

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/importlib-metadata/default.nix
> +  doCheck = false;
Why? Add a comment.

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/importlib-metadata/default.nix
> +  propagatedBuildInputs = [ ];
remove

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/importlib-resources/default.nix
> +  name = "importlib_resources";
remove

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/importlib-resources/default.nix
> +  propagatedBuildInputs = [ ];
same as above

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/pre-commit/default.nix
> +  name = "${pname}-${version}";
drop this line

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/pre-commit/default.nix
> +buildPythonPackage rec {
Is this a library or an application? Please read https://nixos.org/nixpkgs/manual/#building-packages-and-applications.

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/pre-commit/default.nix
> +  doCheck = false;
Why?

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/pre-commit/default.nix
> +, python36
Do not import a specific version!

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/pre-commit/default.nix
> +    description = "A framework for managing and maintaining multi-language pre-commit hooks.";
No period: https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes

2018-10-27 12:55 UTC, dotlambda commented on pkgs/top-level/python-packages.nix
> +  pre-commit = callPackage ../development/python-modules/pre-commit { };
This file should be sorted alphabetically.

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/setuptools-markdown/default.nix
> +  doCheck = false;
same as above

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/setuptools-markdown/default.nix
> +  name = "setuptools_markdown";
drop this line

2018-10-27 12:55 UTC, dotlambda commented on pkgs/development/python-modules/setuptools-markdown/default.nix
> +  pname = "setuptools-markdown";
Are you sure that this works? Pypandoc is broken.

2018-10-27 12:57 UTC, dotlambda commented
I only found out after reviewing that this package already exists: https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/version-management/git-and-tools/pre-commit/default.nix

2018-10-27 12:57 UTC, closed without merging