jq: 1.5 -> 1.6 (!!!!)
NixOS/nixpkgs pull request #49649
Opened 2018-11-02 17:33 UTC by dtzWill

###### Motivation for this change

WOOOOOOO

Also, no longer requires specifying '.' when using in a chain/piping it!!

Unsure impact on rebuilds, and looks to be used in a few scripts in-tree
which should be checked to work as expected.

But first, let's see what borg says :).

(oh and I checked commit history and there are indeed commits that (claim)
to fix the issue we had the Darwin strptime patch for)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-11-02 17:47 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=02ff7e47-6802-4120-8e6c-166ab528fd59-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=45eaa67b-6e20-4091-803b-a4a5511ef714)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/build/jq-1.6'
make[3]: Leaving directory '/build/jq-1.6'
make[2]: Leaving directory '/build/jq-1.6'
make[1]: Leaving directory '/build/jq-1.6'
/nix/store/0ryssnf6lql8ir09dr1kz8fiv08shx9f-jq-1.6-bin
```
</p></details>

2018-11-02 17:47 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=02ff7e47-6802-4120-8e6c-166ab528fd59-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=071f5a99-f624-482f-83c0-9b93707094a1)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/build/jq-1.6'
make[3]: Leaving directory '/build/jq-1.6'
make[2]: Leaving directory '/build/jq-1.6'
make[1]: Leaving directory '/build/jq-1.6'
/nix/store/106vvd5g5i9z0p6h4zfch5qa886657p7-jq-1.6-bin
```
</p></details>

2018-11-02 17:51 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=02ff7e47-6802-4120-8e6c-166ab528fd59-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=c5bff602-f2b2-4432-b1e1-71f0a65fea94)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[3]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[2]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[1]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
/nix/store/qpi120f4406yjg39k2imd10zjqa3bvdd-jq-1.6-bin
```
</p></details>

2018-11-02 18:17 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=48543cb3-a2c5-48b1-b999-df16c6b1fbc9-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=a37f01e6-91c1-4662-95fa-ef0be4e2406f)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/build/jq-1.6'
make[3]: Leaving directory '/build/jq-1.6'
make[2]: Leaving directory '/build/jq-1.6'
make[1]: Leaving directory '/build/jq-1.6'
/nix/store/2ixjip8qlqdkhain2i3yhfqdj9zgk4xl-jq-1.6
```
</p></details>

2018-11-02 18:17 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=48543cb3-a2c5-48b1-b999-df16c6b1fbc9-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=3bb18c5d-2ef2-460b-8904-209ba2a4f967)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/build/jq-1.6'
make[3]: Leaving directory '/build/jq-1.6'
make[2]: Leaving directory '/build/jq-1.6'
make[1]: Leaving directory '/build/jq-1.6'
/nix/store/00qrmnsr8a2bh9l6w98kd8d3qb0ij4m0-jq-1.6
```
</p></details>

2018-11-02 18:18 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=48543cb3-a2c5-48b1-b999-df16c6b1fbc9-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=9704b227-ab7a-4fa3-9a46-186e61f14a5a)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[3]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[2]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[1]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
/nix/store/m00iwfbm65abdd9sdf7l0s54dcy5gyax-jq-1.6
```
</p></details>

2018-11-02 19:15 UTC, dtzWill commented
In-tree uses of the utility appear to be mostly in update scripts
which IMO are lower priority than build breakage or broken packages :).

On Fri, 02 Nov 2018 19:01:34 +0000 (UTC), GrahamC of Borg <notifications@github.com> wrote:
> <!--REQUEST_ID=02ff7e47-6802-4120-8e6c-166ab528fd59-->
> Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=c5bff602-f2b2-4432-b1e1-71f0a65fea94)
> 
> Attempted: jq
> 
> <details><summary>Partial log (click to expand)</summary><p>
> 
> ```
> # XFAIL: 0
> # FAIL:  0
> # XPASS: 0
> # ERROR: 0
> ============================================================================
> make[4]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
> make[3]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
> make[2]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
> make[1]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
> /nix/store/qpi120f4406yjg39k2imd10zjqa3bvdd-jq-1.6-bin
> ```
> </p></details>
> 
> 
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/49649#issuecomment-435458846Non-text part: text/html

2018-11-02 23:01 UTC, Profpatsch commented
cc @aszlig @fpletz

2018-11-02 23:06 UTC, Profpatsch requested changes
The bin changes should be reverted, the rationale is somewhere in the manual.

2018-11-02 23:06 UTC, Profpatsch commented on pkgs/development/tools/jq/default.nix
> +  outputs = [ "out" "doc" "man" "dev" "lib" ];
`bin` should be the first output, the original was as intended.

2018-11-02 23:06 UTC, Profpatsch commented on pkgs/development/tools/jq/default.nix
> +    $out/bin/jq --help >/dev/null
As above, this should stay `bin`.

2018-11-02 23:06 UTC, Profpatsch commented on pkgs/development/tools/jq/default.nix
> -    ++ stdenv.lib.optional stdenv.isDarwin ./darwin-strptime-test.patch;
Are you sure these patches can just be removed for 1.6?

2018-11-02 23:08 UTC, Profpatsch commented
From the changelog [here](https://github.com/stedolan/jq/releases/tag/jq-1.6) it sounds like the new version should be backwards compatible with 1.5?

2018-11-03 00:11 UTC, dtzWill commented
On Fri, 02 Nov 2018 16:06:57 -0700, Profpatsch <notifications@github.com> wrote:
> Profpatsch requested changes on this pull request.
> 
> The bin changes should be reverted, the rationale is somewhere in the manual.
> 
> >    };
>  
> -  outputs = [ "bin" "doc" "man" "dev" "lib" "out" ];
> +  outputs = [ "out" "doc" "man" "dev" "lib" ];
> 
> `bin` should be the first output, the original was as intended.
> 
> >  
>    doInstallCheck = true;
>    installCheckTarget = "check";
>  
>    postInstallCheck = ''
> -    $bin/bin/jq --help >/dev/null
> +    $out/bin/jq --help >/dev/null
> 
> As above, this should stay `bin`.

I thought I remembered there being a reason
but didn't think to check the manual, whoops.

Will refresh without these two changes shortly.

> 
> >  
>    buildInputs = [ oniguruma ];
>  
> -  patches = [
> -    (fetchpatch {
> -      name = "CVE-2015-8863.patch";
> -      url = https://github.com/stedolan/jq/commit/8eb1367ca44e772963e704a700ef72ae2e12babd.diff;
> -      sha256 = "18bjanzvklfzlzzd690y88725l7iwl4f6wnr429na5pfmircbpvh";
> -    })
> -    (fetchpatch {
> -      name = "CVE-2016-4074.patch";
> -      url = https://patch-diff.githubusercontent.com/raw/stedolan/jq/pull/1214.diff;
> -      sha256 = "1w8bapnyp56di6p9casbfczfn8258rw0z16grydavdjddfm280l9";
> -    })
> -  ]
> -    ++ stdenv.lib.optional stdenv.isDarwin ./darwin-strptime-test.patch;
> 
> Are you sure these patches can just be removed for 1.6? 


I didn't thoroughly investigate but they both are from upstream
and seem merged (and not reverted) so I'd say it's safe.

The Darwin patch I mention in the PR text, or I meant to :).

> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/49649#pullrequestreview-171298397Non-text part: text/html

2018-11-03 00:14 UTC, dtzWill commented
Honestly it'd be surprising if it wasn't, but first release in X years
made it seem worth at least discussing.  Glad it's compat! :)

On Fri, 02 Nov 2018 16:08:58 -0700, Profpatsch <notifications@github.com> wrote:
> From the changelog [here](https://github.com/stedolan/jq/releases/tag/jq-1.6) it sounds like the new version should be backwards compatible with 1.5?
> 
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/49649#issuecomment-435534958Non-text part: text/html

2018-11-03 00:48 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=4c889b5f-888a-4d89-8346-fd04686d9a60-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=81aaaf9d-c848-45e5-b9e2-9f0477a5b9ef)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/106vvd5g5i9z0p6h4zfch5qa886657p7-jq-1.6-bin
```
</p></details>

2018-11-03 00:49 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=4c889b5f-888a-4d89-8346-fd04686d9a60-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=d6b7c473-8bce-440d-9d5f-ef7c814cf5fe)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[3]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[2]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
make[1]: Leaving directory '/private/tmp/nix-build-jq-1.6.drv-0/jq-1.6'
/nix/store/qpi120f4406yjg39k2imd10zjqa3bvdd-jq-1.6-bin
```
</p></details>

2018-11-03 00:50 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=4c889b5f-888a-4d89-8346-fd04686d9a60-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49649&attempt_id=9e6febb6-a78e-4733-bb37-1b675930ae7c)

Attempted: jq

<details><summary>Partial log (click to expand)</summary><p>

```
# XFAIL: 0
# FAIL:  0
# XPASS: 0
# ERROR: 0
============================================================================
make[4]: Leaving directory '/build/jq-1.6'
make[3]: Leaving directory '/build/jq-1.6'
make[2]: Leaving directory '/build/jq-1.6'
make[1]: Leaving directory '/build/jq-1.6'
/nix/store/0ryssnf6lql8ir09dr1kz8fiv08shx9f-jq-1.6-bin
```
</p></details>

2018-11-03 10:46 UTC, Profpatsch approved these changes

2018-11-03 10:47 UTC, merged

2018-11-03 10:47 UTC, Profpatsch commented
Looking good!