pythonPackages.prettytable: 0.7.1 -> 0.7.2
NixOS/nixpkgs pull request #49675
Opened 2018-11-03 09:01 UTC by asymmetric

###### Motivation for this change

Upgrade to 0.7.2

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-11-03 09:03 UTC, FRidh requested changes
All expressions have been merged to to `python-modules/`. Please rebase onto staging.

2018-11-03 09:32 UTC, asymmetric commented
So I should close this PR and reopen one against `stable`?

2018-11-03 09:33 UTC, FRidh commented
You can force push to your branch the fixed version.

2018-11-03 09:43 UTC, asymmetric commented
The problem is that the PR is opened against master, so I don't think it makes sense to rebase onto `staging` - as you can see, hundreds of commits are pulled in.

2018-11-03 09:43 UTC, FRidh commented
Not anymore.

2018-11-07 12:41 UTC, asymmetric commented
Can this be merged?

2018-11-07 16:09 UTC, FRidh commented
@GrahamcOfBorg build pythonPackages.prettytable python3Packages.prettytable

2018-11-07 16:09 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=7f78842c-da39-4cda-90c8-de308dd76ed2-->
Unexpected error: command failed with exit code 1 on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49675&attempt_id=a99f303e-6558-49b4-8342-7385f3335456)

Attempted: pythonPackages.prettytable, python3Packages.prettytable

<details><summary>Partial log (click to expand)</summary><p>

```

trying https://files.pythonhosted.org/packages/source/p/prettytable/prettytable-0.7.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24784  100 24784    0     0  95323      0 --:--:-- --:--:-- --:--:-- 95323
fixed-output derivation produced path '/nix/store/gv08n8xwm1xcf63l4fdxlk6i3hhd86vf-prettytable-0.7.2.tar.gz' with sha256 hash '1ndckiniasacfqcdafzs04plskrcigk7vxprr2y34jmpkpf60m1d' instead of the expected hash '0diwsicwmiq2cpzpxri7cyl5fmsvicafw6nfqf6p6p322dji2g45'
cannot build derivation '/nix/store/0a3c5fdqgy96iycwf2gh2my2862jn40x-python2.7-prettytable-0.7.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/x00ady2wh6mx6kkbgmhjzw6l6d7y12ak-python3.7-prettytable-0.7.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/0a3c5fdqgy96iycwf2gh2my2862jn40x-python2.7-prettytable-0.7.2.drv', '/nix/store/x00ady2wh6mx6kkbgmhjzw6l6d7y12ak-python3.7-prettytable-0.7.2.drv' failed
```
</p></details>

2018-11-07 16:09 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=7f78842c-da39-4cda-90c8-de308dd76ed2-->
Unexpected error: command failed with exit code 1 on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49675&attempt_id=cfcde60f-b462-40f4-b40e-9457bc4ffedd)

Attempted: pythonPackages.prettytable, python3Packages.prettytable

<details><summary>Partial log (click to expand)</summary><p>

```

trying https://files.pythonhosted.org/packages/source/p/prettytable/prettytable-0.7.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24784  100 24784    0     0  74876      0 --:--:-- --:--:-- --:--:-- 74876
fixed-output derivation produced path '/nix/store/gv08n8xwm1xcf63l4fdxlk6i3hhd86vf-prettytable-0.7.2.tar.gz' with sha256 hash '1ndckiniasacfqcdafzs04plskrcigk7vxprr2y34jmpkpf60m1d' instead of the expected hash '0diwsicwmiq2cpzpxri7cyl5fmsvicafw6nfqf6p6p322dji2g45'
cannot build derivation '/nix/store/bn83l83b4qzy5fmw62sdz6vjkmvyva2g-python2.7-prettytable-0.7.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/gad5s3irp0cfx28la35gm9acp52r9y22-python3.7-prettytable-0.7.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/bn83l83b4qzy5fmw62sdz6vjkmvyva2g-python2.7-prettytable-0.7.2.drv', '/nix/store/gad5s3irp0cfx28la35gm9acp52r9y22-python3.7-prettytable-0.7.2.drv' failed
```
</p></details>

2018-11-07 16:09 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=7f78842c-da39-4cda-90c8-de308dd76ed2-->
Unexpected error: command failed with exit code 1 on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49675&attempt_id=2492e070-73ac-49e0-b7ab-6b253c2c03a9)

Attempted: pythonPackages.prettytable, python3Packages.prettytable

<details><summary>Partial log (click to expand)</summary><p>

```

trying https://files.pythonhosted.org/packages/source/p/prettytable/prettytable-0.7.2.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 24784  100 24784    0     0   249k      0 --:--:-- --:--:-- --:--:--  249k
fixed-output derivation produced path '/nix/store/gv08n8xwm1xcf63l4fdxlk6i3hhd86vf-prettytable-0.7.2.tar.gz' with sha256 hash '1ndckiniasacfqcdafzs04plskrcigk7vxprr2y34jmpkpf60m1d' instead of the expected hash '0diwsicwmiq2cpzpxri7cyl5fmsvicafw6nfqf6p6p322dji2g45'
cannot build derivation '/nix/store/yhca10zixn2ihrd6fas96a8sij2f8icg-python2.7-prettytable-0.7.2.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/4wb3sk9ivfsc3687c5qb64kxra1c290n-python3.7-prettytable-0.7.2.drv': 1 dependencies couldn't be built
error: build of '/nix/store/4wb3sk9ivfsc3687c5qb64kxra1c290n-python3.7-prettytable-0.7.2.drv', '/nix/store/yhca10zixn2ihrd6fas96a8sij2f8icg-python2.7-prettytable-0.7.2.drv' failed
```
</p></details>

2018-11-07 16:10 UTC, FRidh commented
Incorrect hash it seems.

2018-11-09 13:31 UTC, asymmetric commented
Yup, looks like it. PTALA.

2018-11-11 01:29 UTC, worldofpeace commented
cc @Infinisil

2018-11-11 01:32 UTC, merged

2018-11-11 17:53 UTC, asymmetric commented
When's the `staging` branch merged into `master`?

2018-11-11 18:18 UTC, worldofpeace commented
@asymmetric I think this is the current [staging workflow](https://github.com/NixOS/rfcs/blob/49325193ff71462960e8ea88a97bad89b3928fb6/rfcs/0026-staging-workflow.md#detailed-design) in place.

2018-11-14 16:59 UTC, asymmetric commented
Doesn't seem like it's being followed though - the PR still hasn't landed in master.

2018-11-14 17:11 UTC, asymmetric commented
[This](https://github.com/NixOS/nixpkgs/pull/49742) looks relevant.

2018-11-14 17:17 UTC, FRidh commented
There are too many failures on `staging-next` to merge.