zathura-pdf-mupdf: 0.3.3 -> 0.3.4
NixOS/nixpkgs pull request #49823
Opened 2018-11-06 13:04 UTC by Profpatsch

Support for mupdf 1.14.

2018-11-06 13:14 UTC, 7c6f434c commented
@GrahamcOfBorg build zathura

2018-11-06 13:39 UTC, 7c6f434c commented
Just in case, @cstrahan

2018-11-06 22:29 UTC, Synthetica9 commented on pkgs/applications/misc/zathura/pdf-mupdf/default.nix
> +    rev = "0.3.4";
```suggestion
    rev = version;
```

2018-11-06 22:30 UTC, Synthetica9 requested changes
See suggested change

2018-11-07 04:37 UTC, 7c6f434c commented
@GrahamcOfBorg build zathura

2018-11-07 08:10 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=6eae5995-63c1-4d9b-8fd3-8a8f03ae374a-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=40485b7c-2f40-4843-ac40-37da7c95d353)

Attempted: zathura

<details><summary>Partial log (click to expand)</summary><p>

```
glibPreFixupPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4
shrinking /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4/lib/zathura/libpdf-mupdf.so
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4/lib
patching script interpreter paths in /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4
checking for references to /build in /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4...
building '/nix/store/ii60q5kgaav1xza87ggfy4yglb5glah5-zathura-with-plugins-0.4.1.drv'...
/nix/store/14smh0hj1383nrq5k6vs9jrpvs556x3v-zathura-with-plugins-0.4.1
```
</p></details>

2018-11-07 08:16 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=c2fd2621-92ef-43f9-93ce-07ce890ec0c5-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=82d8ebba-d06a-4632-9261-b6dd9ee64782)

Attempted: zathura

<details><summary>Partial log (click to expand)</summary><p>

```
glibPreFixupPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4
shrinking /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4/lib/zathura/libpdf-mupdf.so
strip is /nix/store/vcc4svb8gy29g4pam2zja6llkbcwsyiq-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4/lib
patching script interpreter paths in /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4
checking for references to /build in /nix/store/0gwk05gl6c38nfm33sm8bvdkk9l1yjx8-zathura-pdf-mupdf-0.3.4...
building '/nix/store/ii60q5kgaav1xza87ggfy4yglb5glah5-zathura-with-plugins-0.4.1.drv'...
/nix/store/14smh0hj1383nrq5k6vs9jrpvs556x3v-zathura-with-plugins-0.4.1
```
</p></details>

2018-11-07 08:35 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=6eae5995-63c1-4d9b-8fd3-8a8f03ae374a-->
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=9a7322a6-4a65-4cf7-aeb7-f5fb24129096)

The following builds were skipped because they don't evaluate on x86_64-darwin: zathura

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-11-07 09:34 UTC, Profpatsch commented on pkgs/applications/misc/zathura/pdf-mupdf/default.nix
> +    rev = "0.3.4";
Good catch!

2018-11-07 09:35 UTC, Profpatsch commented
@GrahamcOfBorg build zathura

2018-11-07 09:35 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=540f0278-2a1c-4098-8607-9f4a5c0624af-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=854c8cfa-b259-46a4-b57e-f312d46b372d)

Attempted: zathura

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/14smh0hj1383nrq5k6vs9jrpvs556x3v-zathura-with-plugins-0.4.1
```
</p></details>

2018-11-07 09:46 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=c2fd2621-92ef-43f9-93ce-07ce890ec0c5-->
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=003e9a3d-4593-48a4-b7d7-94f834ed9a0f)

The following builds were skipped because they don't evaluate on x86_64-darwin: zathura

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-11-07 09:46 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=540f0278-2a1c-4098-8607-9f4a5c0624af-->
No attempt on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=fcecb7a0-1374-4912-a573-a42972e4b35a)

The following builds were skipped because they don't evaluate on x86_64-darwin: zathura

<details><summary>Partial log (click to expand)</summary><p>

```

a) For `nixos-rebuild` you can set
  { nixpkgs.config.allowUnsupportedSystem = true; }
in configuration.nix to override this.

b) For `nix-env`, `nix-build`, `nix-shell` or any other Nix command you can add
  { allowUnsupportedSystem = true; }
to ~/.config/nixpkgs/config.nix.


```
</p></details>

2018-11-07 10:01 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=540f0278-2a1c-4098-8607-9f4a5c0624af-->
Failure on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=0b331d2b-a460-40c4-815d-1161aa66afef)

Attempted: zathura

<details><summary>Partial log (click to expand)</summary><p>

```
failed to run: /build/rustc-1.30.0-src/build/bootstrap/debug/bootstrap build --jobs 64
Build completed unsuccessfully in 0:17:46
make: *** [Makefile:28: all] Error 1
builder for '/nix/store/8s0hyyww0yilnvkq7n8xgpbmg7x43x04-rustc-1.30.0.drv' failed with exit code 2
cannot build derivation '/nix/store/2dljjg4a97rjvmiaj4bv34g92gzya3zf-cargo-1.30.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/n0wz0d2if77aj1cy0h2wv37cnzqqj38q-librsvg-2.42.4.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/jv4na1yywkpx41yz73v3hqn1k48xbxs8-djvulibre-3.5.27.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vqrwfg0bmrzbv1gy6n0h14ri46ljyq1q-zathura-djvu-0.2.8.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/v69y5j3skica2lha7s4cskp1pcwblqpa-zathura-with-plugins-0.4.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/v69y5j3skica2lha7s4cskp1pcwblqpa-zathura-with-plugins-0.4.1.drv' failed
```
</p></details>

2018-11-07 11:02 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=c2fd2621-92ef-43f9-93ce-07ce890ec0c5-->
Timed out, unknown build status on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=190a7c22-77ab-4937-b91c-0e1010a98555)

Attempted: zathura

<details><summary>Partial log (click to expand)</summary><p>

```
   Compiling xz2 v0.1.5
   Compiling installer v0.0.0 (file:///build/rustc-1.30.0-src/src/tools/rust-installer)
    Finished release [optimized] target(s) in 57.91s
building of '/nix/store/8s0hyyww0yilnvkq7n8xgpbmg7x43x04-rustc-1.30.0.drv' timed out after 3600 seconds
cannot build derivation '/nix/store/2dljjg4a97rjvmiaj4bv34g92gzya3zf-cargo-1.30.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/n0wz0d2if77aj1cy0h2wv37cnzqqj38q-librsvg-2.42.4.drv': 2 dependencies couldn't be built
cannot build derivation '/nix/store/jv4na1yywkpx41yz73v3hqn1k48xbxs8-djvulibre-3.5.27.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vqrwfg0bmrzbv1gy6n0h14ri46ljyq1q-zathura-djvu-0.2.8.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/v69y5j3skica2lha7s4cskp1pcwblqpa-zathura-with-plugins-0.4.1.drv': 1 dependencies couldn't be built
error: build of '/nix/store/v69y5j3skica2lha7s4cskp1pcwblqpa-zathura-with-plugins-0.4.1.drv' failed
```
</p></details>

2018-11-07 12:08 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=6eae5995-63c1-4d9b-8fd3-8a8f03ae374a-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.49823&attempt_id=4d7145eb-1d54-417a-b34a-eecae7d6f041)

Attempted: zathura

<details><summary>Partial log (click to expand)</summary><p>

```
glibPreFixupPhase
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/rimndnzysdza9iixiaz1fqnx2yfz6f5s-zathura-djvu-0.2.8
shrinking /nix/store/rimndnzysdza9iixiaz1fqnx2yfz6f5s-zathura-djvu-0.2.8/lib/zathura/libdjvu.so
strip is /nix/store/p9akxn2sfy4wkhqdqa3li97pc6jaz3r1-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/rimndnzysdza9iixiaz1fqnx2yfz6f5s-zathura-djvu-0.2.8/lib
patching script interpreter paths in /nix/store/rimndnzysdza9iixiaz1fqnx2yfz6f5s-zathura-djvu-0.2.8
checking for references to /build in /nix/store/rimndnzysdza9iixiaz1fqnx2yfz6f5s-zathura-djvu-0.2.8...
building '/nix/store/v69y5j3skica2lha7s4cskp1pcwblqpa-zathura-with-plugins-0.4.1.drv'...
/nix/store/mwayydr8rg3a2lc4fdr22p6zlq0v1d6i-zathura-with-plugins-0.4.1
```
</p></details>

2018-11-07 15:07 UTC, merged