metrics.nix: add a metrick for the current number of packages as seen by nix-env
NixOS/nixpkgs pull request #49863
Opened 2018-11-07 09:01 UTC by oxij

###### Motivation for this change

A tiny piece of #45841 I would like to be applied anyway.

###### Things done

It is a bit hacky, but

- [X] I using this for quite a while and I'm very happy about it.

2018-11-11 01:31 UTC, infinisil requested changes

2018-11-11 01:31 UTC, Infinisil commented on pkgs/top-level/metrics.nix
> +    echo "nix-env.qaDrv.number $num" >> $out/nix-support/hydra-metrics
How about just `nix-env -f ${nixpkgs} -qa | wc -l`

Also, I'd prefer the name "count" instead of "number"

2018-11-17 10:38 UTC, oxij commented
> How about just nix-env -f ${nixpkgs} -qa | wc -l

The results differ slightly, but that is not particularly important. Changed.

> Also, I'd prefer the name "count" instead of "number"

Done.

2018-11-17 11:07 UTC, infinisil approved these changes

2018-11-22 08:25 UTC, merged

2018-11-22 09:50 UTC, oxij commented
Thanks!