fixes #49870
NixOS/nixpkgs pull request #50232
Opened 2018-11-11 13:29 UTC by wucke13

###### Motivation for this change
The `.desktop` referenced a non existent script to run `QGroundControl`. This commits adds a `sed` command, which replaces the non existent script by the name of the `QGroundControl` binary in the relevant `.desktop` file.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-11-11 13:30 UTC, FRidh requested changes
Fix commit message and title to describe respectively what the change is about and what derivation is being modified.

2018-11-14 16:45 UTC, Mic92 commented
Does this also affect the 18.09 release?

2018-11-14 17:10 UTC, merged

2018-11-14 19:04 UTC, worldofpeace commented
@Mic92 I checked the output of this from 18.09 and this is needed.

2018-11-14 19:16 UTC, Mic92 commented
backported: bedbba61380