Add flexmock, sqlalchemy-utils, pgpy, and py-gfm
NixOS/nixpkgs pull request #50328
Opened 2018-11-13 21:44 UTC by bsima

###### Motivation for this change

Trying to build [core.sr.ht](https://git.sr.ht/~sircmpwn/core.sr.ht) for NixOS and running into missing packages, figured I would add them upstream. I tested each one with `nix-build -A pythonPackages.<pkgname>` to make sure they built.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-11-14 08:23 UTC, lsix requested changes
Hi,

Thanks for the PR.

Could you add `meta` attributes for `flexmock`, `PGPy` and `py-gfm` ?

2018-11-14 18:37 UTC, bsima commented
Lancelot SIX <notifications@github.com> writes:

> lsix requested changes on this pull request.
>
> Hi,
>
> Thanks for the PR.
>
> Could you add `meta` attributes for `flexmock`, `PGPy` and `py-gfm` ?

Okay, I added the `meta` attributes, and added one more package,
'sshpubkeys'. Let me know if you need any more changes :)

2018-11-14 22:54 UTC, worldofpeace commented on pkgs/development/python-modules/py-gfm/default.nix
> +    description = "This is an implementation of GitHub-Flavored Markdown written as an extension to the Python Markdown library. It aims for maximal compatibility with GitHub's rendering.";
This description is too long.

2018-11-15 16:33 UTC, bsima commented
worldofpeace <notifications@github.com> writes:

> +  meta = with lib; {
> +    homepage = https://github.com/zopieux/py-gfm;
> +    description = "This is an implementation of GitHub-Flavored Markdown written as an extension to the Python Markdown library. It aims for maximal compatibility with GitHub's rendering.";
>
> This description is too long.

Fixed in 9e0430cb919

2018-11-16 13:15 UTC, dotlambda requested changes
The requested changes should be done for the packages I didn't comment on as well.
You might want to read through https://nixos.org/nixpkgs/manual/#python again.

2018-11-16 13:15 UTC, dotlambda commented on pkgs/development/python-modules/flexmock/default.nix
> +  buildInputs = [ nose pytest ];
```suggestion
  checkInputs = [ nose pytest ];
```

2018-11-16 13:15 UTC, dotlambda commented on pkgs/development/python-modules/flexmock/default.nix
> +  };
`maintainers`?

2018-11-16 13:15 UTC, dotlambda commented on pkgs/development/python-modules/pgpy/default.nix
> +  buildInputs = [ cryptography pyasn1 six singledispatch ];
```suggestion
  propagatedBuildInputs = [ cryptography pyasn1 six singledispatch ];
```

2018-11-16 13:15 UTC, dotlambda commented on pkgs/development/python-modules/pgpy/default.nix
> +    description = "PGPy is a Python (2 and 3) library for implementing Pretty Good Privacy into Python programs, conforming to the OpenPGP specification per RFC 4880.";
https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes

2018-11-16 13:15 UTC, dotlambda commented on pkgs/development/python-modules/pgpy/default.nix
> +  };
`maintainers`?

2018-11-16 13:15 UTC, dotlambda commented on pkgs/development/python-modules/flexmock/default.nix
> +    description = "flexmock is a testing library for Python.";
https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes

2018-11-16 18:30 UTC, bsima commented
Robert Schütz <notifications@github.com> writes:

> dotlambda requested changes on this pull request.
>
> The requested changes should be done for the packages I didn't comment on as well.

Okay, I think I covered all of them. They all have meta, metaintainers, etc.

> You might want to read through https://nixos.org/nixpkgs/manual/#python again.

Looking at the contributing guidelines, this is what I see:

> Python libraries are called from python-packages.nix and packaged with
> buildPythonPackage. The expression of a library should be in
> pkgs/development/python-modules/<name>/default.nix. Libraries in
> pkgs/top-level/python-packages.nix are sorted quasi-alphabetically to
> avoid merge conflicts.

Check.

> Python applications live outside of python-packages.nix and are packaged
> with buildPythonApplication.

None of these are apps.

> Make sure libraries build for all Python interpreters.

I think they all succeed. I'll look into testing this thoroughly over
the weekend or next week.

> By default we enable tests. Make sure the tests are found and, in the
> case of libraries, are passing for all interpreters. If certain tests
> fail they can be disabled individually. Try to avoid disabling the tests
> altogether. In any case, when you disable tests, leave a comment
> explaining why.

Only one package failed to find the tests, and I added a comment
explaining that.

> Commit names of Python libraries should reflect that they are Python
> libraries, so write for example pythonPackages.numpy: 1.11 -> 1.12.

Check.

> Attribute names in python-packages.nix should be normalized according to
> PEP 0503. This means that characters should be converted to lowercase
> and . and _ should be replaced by a single - (foo-bar-baz instead of
> Foo__Bar.baz )

Check.

Okay, anything else I can do?

2018-11-28 23:21 UTC, bsima commented
@dotlambda Anything I can do to help move this along?

2018-11-29 00:01 UTC, worldofpeace requested changes
You don`t need to set any of these meta attributes

```
downloadPage = foo;
priority = 0;
broken = false;
updateWalker = true;
```

`downloadPage` could be useful but we already know where we can download python packages from (pypi.org).

Additionally you've set `platforms` to `all`. This is already set to automatically to https://github.com/NixOS/nixpkgs/blob/1b6a4d3979f13f990617d32ee9ec99b1f02673ec/pkgs/development/interpreters/python/mk-python-derivation.nix#L106
which should be sufficient.

2018-11-29 00:04 UTC, worldofpeace commented
@bsima 
Could you also `fixup` these additional commits with an interactive rebase?
It would make reviewing commit by commit possible.

2018-12-04 00:39 UTC, bsima commented
worldofpeace <notifications@github.com> writes:

> @bsima 
> Could you also `fixup` these additional commits with an interactive rebase?
> It would make reviewing commit by commit possible.

Yes, I rebased to make things more clear, and updated the meta
info. Thanks for the feedback, and let me know if there is anything else
I can do.

2018-12-04 18:07 UTC, worldofpeace commented on pkgs/development/python-modules/flexmock/default.nix
> +
Noticed the tests weren't being ran.

This should fix that:
```suggestion
  checkPhase = ''
    pytest tests/
  '';
```

2018-12-04 18:10 UTC, worldofpeace commented on pkgs/development/python-modules/flexmock/default.nix
> +    description = "flexmock is a testing library for Python.";
`description` should not have the name of said software in it or a period at the end.
> https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
> Don’t include a period at the end. Don’t include newline characters. Capitalise the first character. For brevity, don’t repeat the name of package — just describe what it does. 

```suggestion
    description = "A testing library for Python that makes it easy to create mocks, stubs, and fakes";
```

2018-12-04 18:11 UTC, worldofpeace commented on pkgs/development/python-modules/flexmock/default.nix
> +    longDescription = ''
This description isn't long so we don't need it.

2018-12-04 18:12 UTC, worldofpeace commented on pkgs/development/python-modules/pgpy/default.nix
> +  pname = "PGPy";
I think we're normalizing `pname` now so this should be
```suggestion
  pname = "pgpy";
```

2018-12-04 18:13 UTC, worldofpeace commented on pkgs/development/python-modules/pgpy/default.nix
> +    inherit pname version;
Changing the `pname` will most likely make this not work here.
So we might need:
```suggestion
    pname = "PGPy";
    inherit version;
```

2018-12-04 18:13 UTC, worldofpeace commented on pkgs/development/python-modules/pgpy/default.nix
> +    description = "Pretty Good Privacy for Python 2 and 3.";
```suggestion
    description = "Pretty Good Privacy for Python 2 and 3";
```

2018-12-04 18:17 UTC, worldofpeace commented on pkgs/development/python-modules/pgpy/default.nix
> +  propogatedBuildInputs = [ cryptography pyasn1 six singledispatch ];
See https://github.com/SecurityInnovation/PGPy/blob/f1c3d68e32c334f5aa14c34580925e97f17f4fde/setup.py#L36
> only depend on enum34 if Python is older than 3.4

We can constrain the addition of that with
```suggestion
  propogatedBuildInputs = [ cryptography pyasn1 six singledispatch ] ++ lib.optional (pythonOlder "3.4") enum34;
```

2018-12-04 18:32 UTC, worldofpeace commented on pkgs/development/python-modules/py-gfm/default.nix
> +  buildInputs = [ markdown ];
```suggestion
  propagatedBuildInputs = [ markdown ];
```

2018-12-04 18:33 UTC, worldofpeace commented on pkgs/development/python-modules/sqlalchemy-utils/default.nix
> +  pname = "SQLAlchemy-Utils";
I think we're normalizing pname now so this should be
```suggestion
  pname = "sqlalchemy-utils";
```

2018-12-04 18:34 UTC, worldofpeace commented on pkgs/development/python-modules/sqlalchemy-utils/default.nix
> +    inherit pname version;
Changing the pname will most likely make this not work here.
So we might need:
```suggestion
    pname = "SQLAlchemy-Utils";
    inherit version;
```

2018-12-04 18:34 UTC, worldofpeace commented on pkgs/development/python-modules/sqlalchemy-utils/default.nix
> +  buildInputs = [ six sqlalchemy ];
```suggestion
  propagatedBuildInputs = [ six sqlalchemy ];
```

2018-12-04 18:34 UTC, worldofpeace commented on pkgs/development/python-modules/sqlalchemy-utils/default.nix
> +    description = "Various utility functions and datatypes for SQLAlchemy.";
```suggestion
    description = "Various utility functions and datatypes for SQLAlchemy";
```

2018-12-04 18:35 UTC, worldofpeace commented on pkgs/development/python-modules/sshpubkeys/default.nix
> +  buildInputs = [ cryptography ecdsa ];
```suggestion
  propagatedBuildInputs = [ cryptography ecdsa ];
```

2018-12-04 18:52 UTC, worldofpeace commented on pkgs/development/python-modules/sshpubkeys/default.nix
> +  doCheck = false;
Seems somethings not right with the pypi tarball.
Everything works fine when I use the github repo.

```nix
src = fetchFromGitHub {
    owner = "ojarva";
    repo = "python-sshpubkeys";
    rev = "v${version}";
    sha256 = "0000000000000000000000000000000000000000000000000000"; # change this
};
```

2018-12-04 18:57 UTC, worldofpeace requested changes
Additionally tests need aren't running or are missing `checkInputs` for:
 - py-gfm
- pgpy

2018-12-04 19:02 UTC, worldofpeace commented on pkgs/development/python-modules/sshpubkeys/default.nix
> +  doCheck = false;
Please also add a comment above it explaining why we have to use github.

2019-01-29 22:47 UTC, bsima commented
Closing in lieu of #54425 - much more progress and better code in that one :)

2019-01-29 22:47 UTC, closed without merging