nixos-version: use version_ instead of version
NixOS/nixpkgs pull request #50364
Opened 2018-11-14 20:14 UTC by Synthetica9

Related: 1e99582eaff5605947b8e9cdef7d440df8cf7ba3

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-11-14 20:21 UTC, matthewbauer commented
I don't think we should have to do this. Doesn't version still get in the derivation attrs?

2018-11-14 21:29 UTC, matthewbauer commented
Can’t we just fix mkDerivation to not throw that error?

2018-11-28 17:18 UTC, hedning commented
This should probably be targeted at staging-next, as it's a blocker.

2018-11-28 20:49 UTC, Synthetica9 commented
@hedning Done :+1:

2018-11-30 16:48 UTC, FRidh requested changes
Instead of only pointing in a commit message, actually describe what the commit is about.

2018-11-30 16:56 UTC, FRidh commented
I agree here with @matthewbauer. I like it that `name` is automatically composed of `pname` and `version`, but throwing an exception goes too far. As is seen here, `version` is a perfectly fine parameter and there are cases where one doesn't want to include the version in the name and so just pass in `name`. In my opinion one should have the freedom to do that and so I would like to see the exception part being removed.

2018-11-30 17:19 UTC, Synthetica9 commented
> I agree here with @matthewbauer. I like it that `name` is automatically composed of `pname` and `version`, but throwing an exception goes too far. As is seen here, `version` is a perfectly fine parameter and there are cases where one doesn't want to include the version in the name and so just pass in `name`. In my opinion one should have the freedom to do that and so I would like to see the exception part being removed.

Maybe a nice middle ground would be to trace a warning message, but allow it?

2018-12-05 22:14 UTC, closed without merging