kakoune: Prefix version with 'v'
NixOS/nixpkgs pull request #50617
Opened 2018-11-18 19:07 UTC by utdemir

Turns out there's some tooling parsing the version number and having a
'v' prefix works better in that case.

See: https://github.com/ul/kak-lsp/issues/99

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-11-18 19:09 UTC, Infinisil commented on pkgs/applications/editors/kakoune/default.nix
> +    rev = "${version}";
Can do `rev = version` directly.

2018-11-18 19:09 UTC, c0bw3b requested changes
No that's wrong. In nixpkgs a version **must** start with a number
https://nixos.org/nixpkgs/manual/#sec-package-naming

>  The version part of the name attribute must start with a digit (following a dash) — e.g., "hello-0.3.1rc2".

2018-11-18 19:10 UTC, utdemir commented
Oh, I did not know that. Thank you @c0bw3b , closign the PR.

2018-11-18 19:20 UTC, c0bw3b commented
To be more informative here, the reason is because nix will parse that to find the package name on one side, and the version number on the other.

With what you were doing it would have ended like this :
```nix
nix-repl> test = "kakoune-unstable-v2018.10.27"
nix-repl> builtins.parseDrvName test
{ name = "kakoune-unstable-v2018.10.27"; version = ""; }
```

2018-11-18 22:57 UTC, Mic92 commented
@utdemir it is used in nix-env for updating packages.

2018-11-20 21:18 UTC, dpc approved these changes

2018-11-20 22:04 UTC, c0bw3b approved these changes

2018-11-20 22:05 UTC, c0bw3b commented
@GrahamcOfBorg build kakoune

2018-11-20 22:09 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=3a76fcde-9e02-40f5-9c19-bdf3c06ced00-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50617&attempt_id=b043e996-94a9-4267-bbc2-43a6390036e7)

Attempted: kakoune

<details><summary>Partial log (click to expand)</summary><p>

```
install -m 0644 ../doc/kak.1.gz /nix/store/4zhf8j5dpdbfizlwfp05bvxrv9l7fsah-kakoune-unstable-2018.10.27/share/man/man1
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/4zhf8j5dpdbfizlwfp05bvxrv9l7fsah-kakoune-unstable-2018.10.27
shrinking /nix/store/4zhf8j5dpdbfizlwfp05bvxrv9l7fsah-kakoune-unstable-2018.10.27/bin/kak
gzipping man pages under /nix/store/4zhf8j5dpdbfizlwfp05bvxrv9l7fsah-kakoune-unstable-2018.10.27/share/man/
strip is /nix/store/rpbg8gmqxhz8g61p1plz5d2srs84pvmv-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/4zhf8j5dpdbfizlwfp05bvxrv9l7fsah-kakoune-unstable-2018.10.27/bin
patching script interpreter paths in /nix/store/4zhf8j5dpdbfizlwfp05bvxrv9l7fsah-kakoune-unstable-2018.10.27
checking for references to /build in /nix/store/4zhf8j5dpdbfizlwfp05bvxrv9l7fsah-kakoune-unstable-2018.10.27...
/nix/store/4zhf8j5dpdbfizlwfp05bvxrv9l7fsah-kakoune-unstable-2018.10.27
```
</p></details>

2018-11-20 22:12 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=3a76fcde-9e02-40f5-9c19-bdf3c06ced00-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50617&attempt_id=e7a0ddd4-8b55-45c5-a0d7-d354ecd693cb)

Attempted: kakoune

<details><summary>Partial log (click to expand)</summary><p>

```
install -m 0644 ../doc/kak.1.gz /nix/store/rm0764hpb2md5zcmwdv2jh8i2ngnw38v-kakoune-unstable-2018.10.27/share/man/man1
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/rm0764hpb2md5zcmwdv2jh8i2ngnw38v-kakoune-unstable-2018.10.27
shrinking /nix/store/rm0764hpb2md5zcmwdv2jh8i2ngnw38v-kakoune-unstable-2018.10.27/bin/kak
gzipping man pages under /nix/store/rm0764hpb2md5zcmwdv2jh8i2ngnw38v-kakoune-unstable-2018.10.27/share/man/
strip is /nix/store/6dpnd5aniypn8124mmy8f88s4mq2zl07-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/rm0764hpb2md5zcmwdv2jh8i2ngnw38v-kakoune-unstable-2018.10.27/bin
patching script interpreter paths in /nix/store/rm0764hpb2md5zcmwdv2jh8i2ngnw38v-kakoune-unstable-2018.10.27
checking for references to /build in /nix/store/rm0764hpb2md5zcmwdv2jh8i2ngnw38v-kakoune-unstable-2018.10.27...
/nix/store/rm0764hpb2md5zcmwdv2jh8i2ngnw38v-kakoune-unstable-2018.10.27
```
</p></details>

2018-11-20 22:13 UTC, c0bw3b commented
@utdemir this is complete for you? You don't have more additions to bring to this PR?

2018-11-20 22:24 UTC, utdemir commented
@c0bw3b Yes, this is complete for me; I think we can merge it if everything is good. Thank you very much!

2018-11-20 22:57 UTC, merged