pythonPackages.sqlite-web: init at 0.3.5
NixOS/nixpkgs pull request #50955
Opened 2018-11-23 14:40 UTC by costrouc

###### Motivation for this change

Request for new python package sqlite-web https://github.com/NixOS/nixpkgs/issues/50949

###### Things done

pythonPackages.sqlite-web: init at 0.3.5

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-11-23 14:41 UTC, costrouc commented
I am happy to be the maintainer of this package since it is pure python.

2018-11-23 14:41 UTC, costrouc commented
@GrahamcOfBorg build python27Packages.sqlite-web python37Packages.sqlite-web

2018-11-23 14:42 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=27e8d282-0b1e-4d3f-b3d7-09a1bac2a416-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=f53a1853-044a-40bc-803c-431f16bd4e9e)

Attempted: python27Packages.sqlite-web, python37Packages.sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
/build/sqlite-web-0.3.5
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5
strip is /nix/store/6dpnd5aniypn8124mmy8f88s4mq2zl07-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5/lib  /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5/bin
patching script interpreter paths in /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5
checking for references to /build in /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5...
wrapping `/nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5/bin/sqlite_web'...
/nix/store/zfpfsfzpbv3cl2yz0kfyafbgirzdhfk9-sqlite-web-0.3.5
/nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5
```
</p></details>

2018-11-23 14:43 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=27e8d282-0b1e-4d3f-b3d7-09a1bac2a416-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=3aaf9150-cb87-4cb6-8549-28adc23619fa)

Attempted: python27Packages.sqlite-web, python37Packages.sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
/build/sqlite-web-0.3.5
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
strip is /nix/store/rpbg8gmqxhz8g61p1plz5d2srs84pvmv-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/lib  /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/bin
patching script interpreter paths in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
checking for references to /build in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5...
wrapping `/nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/bin/sqlite_web'...
/nix/store/5xrqn0vxjvjwfpq1a6w9pvpbrajaz053-sqlite-web-0.3.5
/nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
```
</p></details>

2018-11-23 14:51 UTC, FRidh commented
This is an application and should therefore be called directly from `all-packages.nix`, and not via `python-packages.nix`.

2018-11-23 14:52 UTC, FRidh commented
Unless one is interested in the Python modules, then this is fine. But then `buildPythonPackage` needs to be used, and one might then have an entry in `all-packages.nix` as well.

2018-11-23 15:03 UTC, costrouc commented
This is exactly the question I was going to ask. In this case this package is an application and is not used as a python module nor do I see it ever being used as one. Fixed.

2018-11-23 15:05 UTC, costrouc commented
@GrahamcOfBorg build sqlite-web

2018-11-23 15:06 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=a0ea72da-8a44-4a64-81ee-ca6b52c3d48f-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=e1b233ce-b097-4d63-a3af-f836cfd4393a)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5
```
</p></details>

2018-11-23 15:06 UTC, FRidh commented
In that case the whole expression needs to be moved out of `python-modules/python-packages.nix` and elsewhere in Nixpkgs. Also, pass in `python3Packages` instead of the individual packages.

2018-11-23 15:06 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=a0ea72da-8a44-4a64-81ee-ca6b52c3d48f-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=ba005940-ad8c-432a-a04e-d15bcdab4d61)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
Successfully installed sqlite-web-0.3.5
/build/sqlite-web-0.3.5
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
strip is /nix/store/rpbg8gmqxhz8g61p1plz5d2srs84pvmv-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/lib  /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/bin
patching script interpreter paths in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
checking for references to /build in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5...
wrapping `/nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/bin/sqlite_web'...
/nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
```
</p></details>

2018-11-23 15:12 UTC, costrouc commented
Fixed. Moved to `development/tools/database/`. This is the same directory that `sqlitebrowser` is in.

2018-11-23 15:21 UTC, costrouc commented
@GrahamcOfBorg build sqlite-web

2018-11-23 15:21 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=2ab72da8-7fb5-4adf-b0ac-d2d592e4540f-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=96dccad1-540a-4bc6-b098-d5568a8d09b8)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
/nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5
```
</p></details>

2018-11-23 15:43 UTC, dotlambda requested changes

2018-11-23 15:43 UTC, dotlambda commented on pkgs/top-level/all-packages.nix
> +    pythonPackages = python3Packages;
drop this line

2018-11-23 15:43 UTC, dotlambda commented on pkgs/development/tools/database/sqlite-web/default.nix
> +, pythonPackages
```suggestion
, python3Packages
```

2018-11-23 15:43 UTC, dotlambda commented on pkgs/development/tools/database/sqlite-web/default.nix
> +    description = "Web-based SQLite database browser.";
https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes

2018-11-24 13:29 UTC, c0bw3b commented
@GrahamcOfBorg eval

2018-11-24 13:42 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=0853181a-e057-4d9b-8677-7f44fefdbae2-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=264630f4-3955-4d29-b0fd-bd3404e61c20)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
Successfully installed sqlite-web-0.3.5
/build/sqlite-web-0.3.5
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5
strip is /nix/store/6dpnd5aniypn8124mmy8f88s4mq2zl07-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5/lib  /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5/bin
patching script interpreter paths in /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5
checking for references to /build in /nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5...
wrapping `/nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5/bin/sqlite_web'...
/nix/store/wwz3rxv8q5sfci6sj2xpd29bng7q1lm3-sqlite-web-0.3.5
```
</p></details>

2018-11-24 13:43 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=0853181a-e057-4d9b-8677-7f44fefdbae2-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=2b5e4047-567a-49d7-bcf6-eb868b88aab8)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
Successfully installed sqlite-web-0.3.5
/build/sqlite-web-0.3.5
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
strip is /nix/store/rpbg8gmqxhz8g61p1plz5d2srs84pvmv-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/lib  /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/bin
patching script interpreter paths in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
checking for references to /build in /nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5...
wrapping `/nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5/bin/sqlite_web'...
/nix/store/l9s2kjxyfj0srn1d1fs684j0mkjikbhj-sqlite-web-0.3.5
```
</p></details>

2018-11-26 02:44 UTC, costrouc commented on pkgs/top-level/all-packages.nix
> +    pythonPackages = python3Packages;
Done

2018-11-26 02:44 UTC, costrouc commented on pkgs/development/tools/database/sqlite-web/default.nix
> +, pythonPackages
Done

2018-11-26 02:45 UTC, costrouc commented on pkgs/development/tools/database/sqlite-web/default.nix
> +    description = "Web-based SQLite database browser.";
Fixed

2018-11-26 02:46 UTC, costrouc commented
@GrahamcOfBorg eval

2018-11-26 02:53 UTC, costrouc commented
Fixed. Ready for merge.

2018-11-26 03:44 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=037962ab-a05d-4510-9f07-3e7c79b953de-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=5ee8666d-bf93-4803-9963-5574925866ce)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
Successfully installed sqlite-web-0.3.5
/build/sqlite-web-0.3.5
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/zfr6jzz5md6q5gml3h94ichav4wsdss3-sqlite-web-0.3.5
strip is /nix/store/qjrnv0qw44bw1hc23zhfh26xd1c25dfs-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/zfr6jzz5md6q5gml3h94ichav4wsdss3-sqlite-web-0.3.5/lib  /nix/store/zfr6jzz5md6q5gml3h94ichav4wsdss3-sqlite-web-0.3.5/bin
patching script interpreter paths in /nix/store/zfr6jzz5md6q5gml3h94ichav4wsdss3-sqlite-web-0.3.5
checking for references to /build in /nix/store/zfr6jzz5md6q5gml3h94ichav4wsdss3-sqlite-web-0.3.5...
wrapping `/nix/store/zfr6jzz5md6q5gml3h94ichav4wsdss3-sqlite-web-0.3.5/bin/sqlite_web'...
/nix/store/zfr6jzz5md6q5gml3h94ichav4wsdss3-sqlite-web-0.3.5
```
</p></details>

2018-11-26 03:44 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=e257e184-1c7f-4398-88ba-8297a01ddc9d-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=2a2f989c-0b6b-4fde-b968-0b03cc0c4f11)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
  /nix/store/6jvkndb0jqsi7f290an3nvzr5kwzsdys-python3.7-Werkzeug-0.14.1.drv
  /nix/store/wrxa6p9c7ldkj6vgxzy0n2wyy16jnz54-openblas-0.3.3.drv
  /nix/store/myyqrf26yqd6pd13myl415c36jzdab8r-site.cfg.drv
  /nix/store/y62wlviklwd3zabbp1k6jah17lkfyasl-python3.7-numpy-1.15.3.drv
  /nix/store/9rvfslg11ryixz3m33654f9rpis6kjha-python3.7-Cython-0.29.drv
  /nix/store/nhbvj0hmh6h5ibglmhg5658xm5inyfyp-python3.7-Flask-1.0.2.drv
  /nix/store/izvvvi7n5kjmhsb98k8x21sh744xfl6j-python3.7-peewee-3.7.1.drv
  /nix/store/vhal6xicsarfbr69gdw7lfm8kkkbsgpd-sqlite-web-0.3.5.drv
waiting for locks or build slots...
/nix/store/zfr6jzz5md6q5gml3h94ichav4wsdss3-sqlite-web-0.3.5
```
</p></details>

2018-11-26 04:38 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=e257e184-1c7f-4398-88ba-8297a01ddc9d-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=1dddc1f9-01ed-4b06-95ec-67e606e67316)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```
Successfully installed sqlite-web-0.3.5
/build/sqlite-web-0.3.5
post-installation fixup
shrinking RPATHs of ELF executables and libraries in /nix/store/rl9dpdxbxhzdfb8p5kzjm6rkq8c74jbk-sqlite-web-0.3.5
strip is /nix/store/n4hb93w6j076xcjw5pm09rdmc09s075b-binutils-2.30/bin/strip
stripping (with command strip and flags -S) in /nix/store/rl9dpdxbxhzdfb8p5kzjm6rkq8c74jbk-sqlite-web-0.3.5/lib  /nix/store/rl9dpdxbxhzdfb8p5kzjm6rkq8c74jbk-sqlite-web-0.3.5/bin
patching script interpreter paths in /nix/store/rl9dpdxbxhzdfb8p5kzjm6rkq8c74jbk-sqlite-web-0.3.5
checking for references to /build in /nix/store/rl9dpdxbxhzdfb8p5kzjm6rkq8c74jbk-sqlite-web-0.3.5...
wrapping `/nix/store/rl9dpdxbxhzdfb8p5kzjm6rkq8c74jbk-sqlite-web-0.3.5/bin/sqlite_web'...
/nix/store/rl9dpdxbxhzdfb8p5kzjm6rkq8c74jbk-sqlite-web-0.3.5
```
</p></details>

2018-11-26 04:41 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=037962ab-a05d-4510-9f07-3e7c79b953de-->
Timed out, unknown build status on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.50955&attempt_id=31c3cbfa-12b4-44e4-87ec-ffd82480f55f)

Attempted: sqlite-web

<details><summary>Partial log (click to expand)</summary><p>

```

#### 2018-11-26 04:41:07.729698

#### 2018-11-26 04:41:18.224781

#### 2018-11-26 04:41:28.247956
building of '/nix/store/z1c9pp31zajv3gfcpfcp41mazqff6p62-python3.7-Cython-0.29.drv' timed out after 3600 seconds
cannot build derivation '/nix/store/yhq41ld4vmcdpfqq28w9hkvb86dvsnm1-python3.7-peewee-3.7.1.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/h8f59vs5r48vn96pzllfm7vhmjmnl9g4-sqlite-web-0.3.5.drv': 1 dependencies couldn't be built
error: build of '/nix/store/h8f59vs5r48vn96pzllfm7vhmjmnl9g4-sqlite-web-0.3.5.drv' failed
```
</p></details>

2018-11-26 10:30 UTC, wmertens commented
Nice and concise!

![LGTM](https://i.imgur.com/S5Zm9e2.png)

2018-11-26 10:37 UTC, merged