pew: fix build
NixOS/nixpkgs pull request #51051
Opened 2018-11-25 23:09 UTC by alyssais

###### Motivation for this change

https://github.com/NixOS/nixpkgs/issues/51034

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I had a quick go at getting the tests to run, but they didn't seem to work out of the box, and it's out of the scope of getting the build working anyway.

2018-11-25 23:33 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=e4e24ce6-e7b6-4540-9eba-13d7a9e9dd7b-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.51051&attempt_id=a2fcc7f6-aef9-47bd-8a48-cd8a239112c3)

Attempted: pew

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found under directory 'pew'
writing manifest file 'pew.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/cwix3h6n1lxyjrh3l5lz2v90l5aykqyf-pew-1.1.2
```
</p></details>

2018-11-26 03:27 UTC, worldofpeace requested changes
I think we'll need `glibcLocales` as a `buildInputs` also.

2018-11-26 06:54 UTC, Mic92 commented
@GrahamcOfBorg build pew

2018-11-26 06:55 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=caf175fb-8a77-473f-ae32-5641ffc0ae59-->
Success on aarch64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.51051&attempt_id=173f7117-c2e7-4c65-8a18-88c83c8c265a)

Attempted: pew

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found under directory 'pew'
writing manifest file 'pew.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/cwix3h6n1lxyjrh3l5lz2v90l5aykqyf-pew-1.1.2
```
</p></details>

2018-11-26 06:55 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=caf175fb-8a77-473f-ae32-5641ffc0ae59-->
Success on x86_64-linux [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.51051&attempt_id=aac60de4-4436-424e-8ffa-f76b8dd1f7cf)

Attempted: pew

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found under directory 'pew'
writing manifest file 'pew.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/f3377ag4m9lxpv9payliwf2c7hnbjl4j-pew-1.1.2
```
</p></details>

2018-11-26 06:57 UTC, GrahamcOfBorg commented
<!--REQUEST_ID=caf175fb-8a77-473f-ae32-5641ffc0ae59-->
Success on x86_64-darwin [(full log)](https://logs.nix.ci/?key=nixos/nixpkgs.51051&attempt_id=41065eab-2166-4fa9-977d-77352d48fe7c)

Attempted: pew

<details><summary>Partial log (click to expand)</summary><p>

```
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*~' found under directory 'pew'
writing manifest file 'pew.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
/nix/store/3f4509q6was8bah3ryjlfaqqs08kvagi-pew-1.1.2
```
</p></details>

2018-11-26 06:59 UTC, merged

2018-11-26 07:00 UTC, Mic92 commented
does not seem to be required in this case.