msmtp: 1.6.8 -> 1.8.0
NixOS/nixpkgs pull request #51693
Opened 2018-12-08 02:35 UTC by dtzWill

https://marlam.de/msmtp/news/msmtp-1-8-0/

Uses libidn2 now instead of libidn.

###### Motivation for this change

Seems to work for me, configured via home-manager FWIW.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-12-08 09:28 UTC, c0bw3b requested changes
Same as `mpop` : only `gnutls` lib should be used for TLS support (upstream recommendation)

2018-12-16 00:20 UTC, dtzWill commented
Fixed and similarly minor bump :).

2018-12-16 01:39 UTC, rasendubi approved these changes

2018-12-16 18:06 UTC, c0bw3b approved these changes

2018-12-16 18:06 UTC, merged