xpra:  2.3.4 -> 2.4.2
NixOS/nixpkgs pull request #51877
Opened 2018-12-11 18:56 UTC by deepfire

###### Motivation for this change

XPRA is broken as of now (https://github.com/NixOS/nixpkgs/issues/41106 and https://github.com/NixOS/nixpkgs/issues/30822), here's hoping the bump fixes it.

There was another curious artifact in 2.3.4, by the way -- the features file had this:
```
$ ag LOCAL_SERVERS_SUPPORTED /nix/store/kfrnj33702mfa8y8629adh894ccn731z-xpra-2.3.4/lib/python3.6/site-packages/xpra/
/nix/store/kfrnj33702mfa8y8629adh894ccn731z-xpra-2.3.4/lib/python3.6/site-packages/xpra/platform/features.py
14:LOCAL_SERVERS_SUPPORTED = PYTHON2
```
..which resulted in `xpra` having no `start` subcommand.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-12-11 18:56 UTC, deepfire commented
cc @bgamari

2018-12-11 20:38 UTC, c0bw3b commented
Previous "unbreaking" attempts and/or related : #48872 and #50365

2018-12-11 22:07 UTC, deepfire commented
Thank you for the context, @c0bw3b!

2019-02-24 04:52 UTC, ryantm commented
@GrahamcOfBorg build xpra

2019-02-24 04:58 UTC, ryantm requested changes
If this unbreaks xpra, it should remove the `broken=true;` meta attribute. When I run `nix-review pr 51877`, it says 

```
4 package are marked as broken and were skipped:
ib-controller run-scaled winswitch xpra
```
so there might be more broken things to contend with.

2019-05-12 12:09 UTC, aanderse commented
For any interested parties: https://github.com/NixOS/nixpkgs/pull/58151#issuecomment-491589727

> Results of nix-review:
1 package failed to build:
winswitch
2 package were build:
run-scaled xpra

2019-05-12 13:04 UTC, c0bw3b commented
Closing in favor of #58151

2019-05-12 13:04 UTC, closed without merging