duplicacy: init at 2.1.2
NixOS/nixpkgs pull request #52409
Opened 2018-12-16 22:59 UTC by ffinkdevs

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2018-12-17 10:34 UTC, Mic92 requested changes
Looks good to. I only left some nitpicks. Could not test the package because of my flacky connectivity.

2018-12-17 10:34 UTC, Mic92 commented on pkgs/tools/backup/duplicacy/default.nix
> +  name = "duplicacy-${version}";
```suggestion
  pname = "duplicacy";
```

2018-12-17 10:34 UTC, Mic92 commented on pkgs/tools/backup/duplicacy/default.nix
> +    mkdir -p $bin/bin
```suggestion
```

2018-12-17 10:34 UTC, Mic92 commented on pkgs/tools/backup/duplicacy/default.nix
> +    cp duplicacy_main $bin/bin/duplicacy
```suggestion
    install -D duplicacy_main $bin/bin/duplicacy
```

2018-12-17 10:34 UTC, Mic92 commented
@GrahamcOfBorg build duplicacy

2018-12-17 11:55 UTC, ffinkdevs commented
@Mic92  you sure its pname when using go packages?, i pretty much just copied restic's derivation and changed it to duplicacy needs

2018-12-18 02:59 UTC, Mic92 commented
Indeed this was a limitation of `buildGoPackage` to not exposing this feature of stdenv.

2018-12-18 04:55 UTC, Mic92 commented
@GrahamcOfBorg eval

2019-03-21 22:08 UTC, Ralith commented
What's the status of this?

2019-03-22 11:29 UTC, merged

2019-03-22 11:29 UTC, Mic92 commented
Sorry. I forgot about this one.