cpython: Un-remove some test data
NixOS/nixpkgs pull request #53479
Opened 2019-01-06 05:15 UTC by MostAwesomeDude

These certificates are used in asyncio's tests in a way that doesn't
affect CPython directly, but does affect some dependencies, in
particular txaio.

Fixes NixOS/nixpkgs#53474.

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-01-06 08:00 UTC, FRidh requested changes
This needs to be rebased onto staging. Also, build all interpreters twice with the second time using `--check` to see if the build is still reproducible. I would expect so.

2019-01-06 08:02 UTC, FRidh commented
Actually, no, all that it needs is a `*pem` file. I don't think we should include that. Just disable the test or provide an alternative `*pem` file.

2019-01-06 08:02 UTC, closed without merging

2019-01-07 03:38 UTC, andrew-d commented
@FRidh - Sorry, do you mind clarifying your proposed solution here? My understanding is that the standard library has a module called `asyncio.test_utils`, which relies on the `.pem` file existing. Code that uses the Python standard library will thus break if we don't include these files. This feels like we're doing the wrong thing here, not a problem with Python.

2019-01-07 08:34 UTC, andrew-d commented
Sure, that’s fair, though so is `pipes.quote` in Python 2, which also used
by real code. To be clear: if NixOS/nixpkgs wants to remove this or other
stuff from the Python standard library, that’s a choice that can be made -
I was just clarifying that this wasn’t some third party project with an
error, but a choice that was made by us 😃

On Mon, Jan 7, 2019 at 12:28 AM Frederik Rietdijk <notifications@github.com>
wrote:

> asyncio.test_utils is undocumented and not part of the public API as far
> as I know.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/53479#issuecomment-451857280>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABB3hcRGVyzOUarnRcCuMYeuXetk-zLvks5vAwUpgaJpZM4ZyRJR>
> .
>