update wavesurfer
NixOS/nixpkgs pull request #53584
Opened 2019-01-07 17:55 UTC by MarcWeber

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-01-09 21:59 UTC, veprbl reviewed
You need to fix meta:

* `snack.meta.broken = true` needs to be removed
* `wavesurfer.meta.license` needs to be set as a value from `stdenv.lib.licenses.*`
* `snack.meta.platforms` and `wavesurfer.meta.platforms` need to be set

See https://nixos.org/nixpkgs/manual/#chap-meta for more information

2019-01-09 21:59 UTC, veprbl commented on pkgs/applications/misc/audio/wavesurfer/default.nix
> +    url = mirror://sourceforce/wavesurfer/wavesurfer/1.8.8p5/wavesurfer-1.8.8p5-src.tgz;
sourceforge?

2019-02-24 21:42 UTC, ryantm requested changes
Please review veprbl's comments and change the commit message to match https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md

2019-05-14 00:55 UTC, aanderse commented
@MarcWeber are you able to address the above comments?

2019-12-27 21:09 UTC, veprbl commented
Since there is no activity, let's close.

2019-12-27 21:09 UTC, closed without merging