treewide: use ${stdenv.shell} instead of /bin/sh where possible
NixOS/nixpkgs pull request #54094
Opened 2019-01-16 19:59 UTC by rnhmjoj

###### Motivation for this change
Trying to close #183

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change (working on it)
- [ ] Tested execution of all binary files
- [ ] Determined the impact on package closure size
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

This is the list of matches in the original issue

unsure what to do about these:
- [ ] pkgs/applications/misc/keepass/extractWinRscIconsToStdFreeDesktopDir.sh
- [ ] pkgs/build-support/fetchcvs/nix-prefetch-cvs
- [ ] pkgs/build-support/fetchsvn/nix-prefetch-svn
- [ ] pkgs/build-support/icon-conv-tools/bin/extractWinRscIconsToStdFreeDesktopDir.sh
- [ ] pkgs/build-support/icon-conv-tools/bin/icoFileToHiColorTheme
- [ ] pkgs/games/ue4/generate-expr-from-cdn.sh
- [ ] pkgs/stdenv/cygwin/wrap-exes-to-find-dlls.sh
- [ ] pkgs/tools/misc/debootstrap/default.nix

fixed:
- [x] pkgs/applications/editors/standardnotes/default.nix
- [x] pkgs/applications/editors/sublime/3/common.nix
- [x] pkgs/applications/graphics/alchemy/default.nix
- [x] pkgs/applications/graphics/wings/default.nix
- [x] pkgs/applications/graphics/zgrviewer/default.nix
- [x] pkgs/applications/misc/curabydagoma/default.nix
- [x] pkgs/applications/misc/freemind/default.nix
- [x] pkgs/applications/misc/hello-unfree/default.nix
- [x] pkgs/applications/misc/jbidwatcher/default.nix
- [x] pkgs/applications/misc/multibootusb/default.nix
- [x] pkgs/applications/misc/openjump/default.nix
- [x] pkgs/applications/misc/thinking-rock/default.nix
- [x] pkgs/applications/networking/instant-messengers/pidgin-plugins/purple-facebook/default.nix
- [x] pkgs/applications/networking/instant-messengers/telegram/telegram-cli/default.nix
- [x] pkgs/applications/science/logic/hol_light/default.nix
- [x] pkgs/applications/science/logic/iprover/default.nix
- [x] pkgs/applications/version-management/nbstripout/default.nix
- [x] pkgs/applications/version-management/smartgithg/install_freedesktop_items.sh
- [x] pkgs/applications/video/zdfmediathk/default.nix
- [x] pkgs/applications/virtualization/xen/generic.nix
- [x] pkgs/build-support/docker/store-path-to-layer.sh
- [x] pkgs/build-support/singularity-tools/default.nix
- [x] pkgs/build-support/vm/default.nix
- [x] pkgs/data/misc/geolite-legacy/builder.sh
- [x] pkgs/development/compilers/cmdstan/default.nix
- [x] pkgs/development/compilers/fsharp41/default.nix
- [x] pkgs/development/compilers/fsharp/default.nix
- [x] pkgs/development/compilers/ghc/gcc-clang-wrapper.sh
- [x] pkgs/development/compilers/openjdk/8.nix
- [x] pkgs/development/interpreters/guile/2.0.nix
- [x] pkgs/development/libraries/libguestfs/default.nix
- [x] pkgs/development/lisp-modules/define-package.nix
- [x] pkgs/development/misc/avr8-burn-omat/default.nix
- [x] pkgs/development/pharo/vm/build-vm.nix
- [x] pkgs/development/python-modules/clustershell/default.nix
- [x] pkgs/development/python-modules/cmd2/default.nix
- [x] pkgs/development/python-modules/cmd2/old.nix
- [x] pkgs/development/python-modules/pandas/default.nix
- [x] pkgs/games/andyetitmoves/default.nix
- [x] pkgs/games/eduke32/default.nix
- [x] pkgs/games/freeorion/fix-paths.sh
- [x] pkgs/games/gargoyle/darwin.sh
- [x] pkgs/games/mars/default.nix
- [x] pkgs/games/minecraft-server/default.nix
- [x] pkgs/games/oilrush/default.nix
- [x] pkgs/games/openra/default.nix
- [x] pkgs/games/openttd/default.nix
- [x] pkgs/games/tremulous/default.nix
- [x] pkgs/games/trigger/default.nix
- [x] pkgs/games/vessel/default.nix
- [x] pkgs/games/worldofgoo/default.nix
- [x] pkgs/games/zangband/default.nix
- [x] pkgs/misc/cups/drivers/mfcj6510dwlpr/default.nix
- [x] pkgs/misc/drivers/foomatic-filters/default.nix
- [x] pkgs/misc/emulators/retrofe/default.nix
- [x] pkgs/misc/vim-plugins/vim-utils.nix
- [x] pkgs/os-specific/linux/alsa-plugins/wrapper.nix
- [x] pkgs/os-specific/linux/bbswitch/default.nix
- [x] pkgs/os-specific/linux/ofp/default.nix
- [x] pkgs/os-specific/linux/rfkill/rfkill-hook.sh
- [x] pkgs/os-specific/linux/rfkill/udev.nix
- [x] pkgs/os-specific/linux/service-wrapper/service-wrapper.sh
- [x] pkgs/os-specific/linux/tp_smapi/default.nix
- [x] pkgs/servers/mail/system-sendmail/default.nix
- [x] pkgs/servers/web-apps/codimd/default.nix
- [x] pkgs/tools/archivers/rpmextract/rpmextract.sh
- [x] pkgs/tools/backup/flockit/default.nix
- [x] pkgs/tools/backup/store-backup/default.nix
- [x] pkgs/tools/compression/gzip/default.nix
- [x] pkgs/tools/graphics/briss/default.nix
- [x] pkgs/tools/graphics/povray/default.nix
- [x] pkgs/tools/misc/fzf/default.nix
- [x] pkgs/tools/misc/grub/2.0x.nix
- [x] pkgs/tools/misc/grub/trusted.nix
- [x] pkgs/tools/misc/qjoypad/default.nix
- [x] pkgs/tools/misc/xfstests/default.nix
- [x] pkgs/tools/networking/airfield/default.nix
- [x] pkgs/tools/networking/zap/default.nix
- [x] pkgs/tools/security/eid-mw/eid-nssdb.in
- [x] pkgs/tools/text/gnugrep/default.nix
- [x] pkgs/tools/typesetting/lout/builder.sh
- [x] pkgs/tools/virtualization/google-compute-engine-oslogin/default.nix
- [x] pkgs/tools/X11/xnee/default.nix

false positives:
- [x] pkgs/applications/audio/yasr/30_conf
- [x] pkgs/applications/editors/music/tuxguitar/default.nix
- [x] pkgs/applications/graphics/qscreenshot/default.nix
- [x] pkgs/applications/graphics/sane/backends/generic.nix
- [x] pkgs/applications/graphics/shutter/default.nix
- [x] pkgs/applications/graphics/swingsane/default.nix
- [x] pkgs/applications/misc/cdrtools/fix-paths.patch
- [x] pkgs/applications/misc/mysql-workbench/hardcode-paths.patch
- [x] pkgs/applications/misc/qdirstat/default.nix
- [x] pkgs/applications/misc/redshift/575.patch
- [x] pkgs/applications/networking/browsers/chromium/update.sh
- [x] pkgs/applications/networking/cluster/mesos/default.nix
- [x] pkgs/applications/networking/cluster/mesos/nixos.patch
- [x] pkgs/applications/science/astronomy/gildas/wrapper.patch
- [x] pkgs/applications/science/geometry/drgeo/struct.patch
- [x] pkgs/applications/science/misc/openmodelica/update-src-libs-git.sh
- [x] pkgs/applications/science/misc/openmodelica/update-src-libs-svn.sh
- [x] pkgs/applications/video/shotcut/default.nix
- [x] pkgs/applications/video/simplescreenrecorder/fix-paths.patch
- [x] pkgs/applications/virtualization/qemu/fix-qemu-ga.patch
- [x] pkgs/build-support/fetchbzr/nix-prefetch-bzr
- [x] pkgs/build-support/setup-hooks/patch-shebangs.sh
- [x] pkgs/build-support/upstream-updater/create-src-info-git.sh
- [x] pkgs/build-support/upstream-updater/create-src-info.sh
- [x] pkgs/build-support/upstream-updater/update-upstream-data.sh
- [x] pkgs/build-support/upstream-updater/update-walker.sh
- [x] pkgs/build-support/upstream-updater/urls-from-page.sh
- [x] pkgs/build-support/vm/windows/default.nix
- [x] pkgs/desktops/enlightenment/enlightenment.suid-exes.patch
- [x] pkgs/desktops/gnustep/make/wrapper.sh
- [x] pkgs/desktops/plasma-5/plasma-workspace/plasma-workspace.patch
- [x] pkgs/development/compilers/ocaml/configure-3.08.0
- [x] pkgs/development/interpreters/perl/no-sys-dirs-5.26.patch
- [x] pkgs/development/libraries/aqbanking/update.sh
- [x] pkgs/development/libraries/cloog/0.18.0.nix
- [x] pkgs/development/libraries/cloog/default.nix
- [x] pkgs/development/libraries/cloog-ppl/default.nix
- [x] pkgs/development/libraries/flatpak/fix-test-paths.patch
- [x] pkgs/development/libraries/flatpak/use-flatpak-from-path.patch
- [x] pkgs/development/libraries/glibc/common.nix
- [x] pkgs/development/libraries/icu/base.nix
- [x] pkgs/development/libraries/libav/default.nix
- [x] pkgs/development/libraries/libg [...]

2019-01-17 08:22 UTC, FRidh approved these changes
Looks good. Waiting for ofborg after branch changing to merge.

2019-01-17 09:40 UTC, rnhmjoj commented
Ok, these packages failed. I'm looking into it:
  - DisnixWebService 
  - R 
  - aacskeys 
  - abcl 
  - adobe_flex_sdk 
  - airwave 
  - alchemy 
  - alloy 
  - alloy5 
  - ammonite 
  - antlr 
  - antlr3 
  - antlr3_4 
  - antlr4 
  - apache-directory-studio 
  - apache-jena 
  - fuseki 
  - apacheKafka 
  - apacheKafka_0_10 
  - apacheKafka_0_11 
  - apacheKafka_0_9 
  - apacheKafka_1_0 
  - apacheKafka_1_1 
  - apacheKafka_2_0 
  - ape 
  - apeClex 
  - arduino 
  - arduino-core 
  - areca 
  - asciidocFull 
  - asciidoc-full-with-plugins 
  - aspectj 
  - astah-community 
  - astrolabe-generator 
  - atlassian-cli 
  - avian 
  - aws_mturk_clt 
  - awstats 
  - axis2 
  - axoloti 
  - azureus 
  - basex 
  - bazel 
  - bazel-deps 
  - bazel-watcher 
  - beegfs 
  - belle-sip 
  - bfg-repo-cleaner 
  - bftools 
  - bgnet 
  - bitwig-studio 
  - bitwig-studio1 
  - bloop 
  - boot 
  - briss 
  - btrbk 
  - buck 
  - burpsuite 
  - cassandra 
  - cassandra_2_1 
  - cassandra_2_2 
  - cassandra_3_0 
  - ccemux 
  - cfr 
  - charles 
  - checkstyle 
  - chromiumBeta 
  - chromiumDev 
  - clojure 
  - clooj 
  - closurecompiler 
  - collectd 
  - collectd-data 
  - confluent 
  - coursier 
  - crashplan 
  - cvc4 
  - cytoscape 
  - davmail 
  - dbeaver 
  - dbus_java 
  - dbvisualizer 
  - disorderfs 
  - ditaa 
  - dotnetPackages.ExtCore 
  - dotnetPackages.FSharpAutoComplete 
  - dotnetPackages.FSharpCompilerService 
  - dotty 
  - drip 
  - dwarf-fortress-packages.dwarf-fortress-full 
  - dwarf-fortress-packages.legends-browser 
  - ec2_api_tools 
  - elasticmq 
  - elasticsearch 
  - elasticsearch-oss 
  - elasticsearch5 
  - elasticsearchPlugins.discovery-ec2 
  - elasticsearchPlugins.elasticsearch_analysis_lemmagen 
  - elasticsearchPlugins.search_guard 
  - emem 
  - emscripten 
  - emscriptenPackages.json_c 
  - emscriptenPackages.libxml2 
  - emscriptenPackages.xmlmirror 
  - emscriptenPackages.zlib 
  - erlang_javac 
  - erlang_odbc_javac 
  - exhibitor 
  - faust 
  - faust2alqt 
  - faust2alsa 
  - faust2csound 
  - faust2firefox 
  - faust2jack 
  - faust2jaqt 
  - faust2ladspa 
  - faust2lv2 
  - faustlive 
  - flink 
  - flink_1_5 
  - flyway 
  - fop 
  - foundationdb 
  - foundationdb51 
  - foundationdb52 
  - freemind 
  - freenet 
  - freetts 
  - frostwire 
  - frostwire-bin 
  - galen 
  - ganttproject-bin 
  - gcs 
  - geogebra 
  - geoipjava 
  - gephi 
  - gitAndTools.subgit 
  - global-platform-pro 
  - gogui 
  - gpsprune 
  - gradle 
  - gradle_2_14 
  - gradle_2_5 
  - gradle_3_5 
  - gradle_4_10 
  - graylog 
  - gremlin-console 
  - groovy 
  - h2 
  - hadoop 
  - hadoop_2_8 
  - hadoop_2_9 
  - hadoop_3_0 
  - hadoop_3_1 
  - haxePackages.hxjava 
  - hdf_java 
  - hdfview 
  - hydraAntLogger 
  - i2p 
  - icedtea8_web 
  - igv 
  - imagej 
  - ino 
  - isabelle 
  - jabref 
  - jameica 
  - javaCup 
  - javaPackages.junit_4_12 
  - javaPackages.mavenHello_1_0 
  - javaPackages.mavenHello_1_1 
  - jbake 
  - jbidwatcher 
  - jd-gui 
  - jdepend 
  - jdiskreport 
  - jdk 
  - jedit 
  - jflex 
  - jing 
  - jitsi 
  - jmeter 
  - jmol 
  - jnetmap 
  - jre 
  - jre8_headless 
  - jruby 
  - jython 
  - jzmq 
  - kodi 
  - kodiPlain 
  - kodiPlugins.joystick 
  - kodiPlugins.kodi-platform 
  - kodiPlugins.pvr-hdhomerun 
  - kodiPlugins.pvr-hts 
  - kodiPlugins.pvr-iptvsimple 
  - kodiPlugins.steam-controller 
  - kotlin 
  - languagetool 
  - lattice-diamond 
  - leiningen 
  - libmatthew_java 
  - libreoffice 
  - libreoffice-fresh 
  - libreoffice-fresh-unwrapped 
  - libreoffice-still-unwrapped 
  - linphone 
  - linuxPackages-libre.bbswitch 
  - linuxPackages-libre.tp_smapi 
  - liquibase 
  - logisim 
  - logstash 
  - logstash5 
  - logstash6-oss 
  - lumo 
  - marathon 
  - martyr 
  - maven 
  - mediathekview 
  - megacli 
  - meguca 
  - mercury 
  - mesos 
  - metabase 
  - mill 
  - minecraft 
  - minecraft-server 
  - monosat 
  - msgviewer 
  - mucommander 
  - multimc 
  - munin 
  - mxisd 
  - mysqlWorkbench 
  - nailgun 
  - nco 
  - neo4j 
  - netalyzr 
  - netbeans 
  - netlogo 
  - nexus 
  - notmuch-bower 
  - ntopng 
  - odpdown 
  - omegat 
  - opa 
  - open-ecard 
  - opengrok 
  - opentsdb 
  - oracleXE 
  - pakcs 
  - perl528Packages.InlineJava 
  - perl528Packages.NetZooKeeper 
  - perldevelPackages.InlineJava 
  - perldevelPackages.NetZooKeeper 
  - picard-tools 
  - picolisp 
  - pig 
  - plantuml 
  - polymake 
  - projectlibre 
  - prometheus-jmx-httpserver 
  - purePackages.faust 
  - pyload 
  - pyre 
  - python27Packages.foundationdb51 
  - python27Packages.foundationdb52 
  - python27Packages.foundationdb60 
  - python27Packages.kazoo 
  - python27Packages.neurotools 
  - python27Packages.plantuml 
  - python27Packages.pystringtemplate 
  - python27Packages.rpy2 
  - python27Packages.sphinxcontrib_plantuml 
  - python27Packages.zake 
  - python37Packages.foundationdb51 
  - python37Packages.foundationdb52 
  - python37Packages.foundationdb60 
  - python37Packages.kazoo 
  - python37Packages.monosat 
  - python37Packages.plantuml 
  - python37Packages.rpy2 
  - python37Packages.sphinxcontrib_plantuml 
  - python37Packages.zake 
  - quantomatic 
  - rWrapper 
  - rabbitmq-java-client 
  - rambox 
  - rapid-photo-downloader 
  - rascal 
  - rhino 
  - riemann 
  - rstudio 
  - rstudio-preview 
  - rstudioWrapper 
  - runelite 
  - sage 
  - sageWithDoc 
  - saxon 
  - saxon-he 
  - saxonb 
  - saxonb_9_1 
  - sbt 
  - sbt-extras 
  - sbt-with-scala-native 
  - scala 
  - scala_2_10 
  - scala_2_11 
  - scalafix 
  - scalafmt 
  - schemaspy 
  - selendroid 
  - selenium-server-standalone 
  - seyren 
  - smartgithg 
  - smc 
  - snpeff 
  - soapui 
  - solr 
  - souffle 
  - spark 
  - spring 
  - springLobby 
  - sqldeveloper 
  - sqlitebrowser 
  - squirrel-sql 
  - srcml 
  - ssvnc 
  - storm 
  - subsonic 
  - swagger-codegen 
  - sweethome3d.application 
  - sweethome3d.furniture-editor 
  - sweethome3d.textures-editor 
  - swiProlog 
  - swingsane 
  - swt 
  - tabula 
  - tambura 
  - teensyduino 
  - tlaplus 
  - tlaplusToolbox 
  - tlaps 
  - tomcat_connectors 
  - trigger 
  - tuxguitar 
  - tvbrowser-bin 
  - udiskie 
  - udisks1 
  - udisks_glue 
  - umlet 
  - ums 
  - unoconv 
  - varscan 
  - vassal 
  - vessel 
  - vimPlugins.vim-grammarous 
  - visualvm 
  - vue 
  - vuze 
  - weka 
  - welkin 
  - workcraft 
  - worldofgoo 
  - worldofgoo_demo 
  - xfstests 
  - xmind 
  - xmloscopy 
  - xtreemfs 
  - yandex-disk 
  - yed 
  - youtrack 
  - yuicompressor 
  - zap 
  - zdfmediathk 
  - zgrviewer 
  - zipkin 
  - zk-shell 
  - zkfuse 
  - zookeeper 
  - zookeeper_mt 
  - zxing

2019-01-17 10:43 UTC, FRidh requested changes
Until there are no more failures.

2019-01-18 11:42 UTC, joachifm commented
I see this also injects `stdenv.shell` into runtime scripts; does that Just Work when cross-compiling?

2019-01-18 12:21 UTC, Mic92 commented
@joachifm good point. This will not work: 

```console
$ nix-repl> pkgsCross.aarch64-multiplatform.stdenv.shell
"/nix/store/vs6d2fjkl4kb3jb7rwibsd76k9v2n4xy-bash-4.4-p23/bin/bash"
$ nix-repl> "${pkgsCross.aarch64-multiplatform.bash}"
"/nix/store/simfkjybzgiza8hvd0gfzafblkap1046-bash-4.4-p23-aarch64-unknown-linux-gnu"
```

2019-01-18 12:22 UTC, FRidh commented
I think fixing expressions for cross is out of scope. Using `/bin/sh` means its broken already.

2019-01-18 12:23 UTC, Mic92 commented
It should be `runtimeShell` in that case:

```
nix-repl> pkgsCross.aarch64-multiplatform.runtimeShell
"/nix/store/simfkjybzgiza8hvd0gfzafblkap1046-bash-4.4-p23-aarch64-unknown-linux-gnu/bin/bash"
```

2019-01-19 00:17 UTC, rnhmjoj commented
So, I got everything to build. The failures were simply timed out or running out of space.

2019-01-19 13:15 UTC, merged

2019-03-05 20:04 UTC, baracoder commented
I think my issue https://github.com/NixOS/nixpkgs/issues/56878 is related to this change, but I am not sure. Could it be that `substituteAll` does not preserve the executable attribute of the source files?

2019-03-05 20:37 UTC, Mic92 commented
substituteInPlace does since it just truncates the same file with `>`. `substituteAll` creates a new file with `>` and therefore should ignore the permissions on the source attribute.