pythonPackages.python-gnupg: 0.4.3 -> 0.4.4
NixOS/nixpkgs pull request #54553
Opened 2019-01-24 21:13 UTC by stigtsp

###### Motivation for this change

Fixes CVE-2019-6690

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-01-24 21:16 UTC, dotlambda requested changes

2019-01-24 21:16 UTC, dotlambda commented on pkgs/development/python-modules/python-gnupg/default.nix
>    name    = "${pname}-${version}";
Remove this line.

2019-01-24 21:21 UTC, dotlambda requested changes
Please mention the fixed vuln (+ link) in the commit description.

2019-01-24 21:21 UTC, dotlambda commented on pkgs/development/python-modules/python-gnupg/default.nix
>    propagatedBuildInputs = [ gnupg1 ];
It seems this is not needed. Should be removed.

2019-01-24 21:39 UTC, stigtsp commented
> Please mention the fixed vuln (+ link) in the commit description.

Sure. Would you like a single squashed commit?

2019-01-24 22:09 UTC, dotlambda commented
Actually, I think the update and the improvements should be two separate commits so that we can backport only one of them.

2019-01-24 23:42 UTC, stigtsp commented
> Actually, I think the update and the improvements should be two separate commits so that we can backport only one of them.

Done

2019-01-25 07:00 UTC, merged

2019-01-25 07:00 UTC, dotlambda commented
Thanks a lot!

2019-01-25 07:13 UTC, dotlambda commented
Backported in 119a93190a86794179e13ec38d51140e953a8ca9.