nixos/grafana: add provisioning of pre-configured Grafana  with dashb…
NixOS/nixpkgs pull request #54561
Opened 2019-01-24 22:46 UTC by dlifanov

###### Motivation for this change

Grafana is deployed without pre-configured dashboard and datasource.
Add configuration to get already working dashboard.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-01-30 11:21 UTC, dlifanov commented
Is there something to change here or add?

2019-02-04 15:58 UTC, mkaito approved these changes

2019-02-04 21:36 UTC, infinisil requested changes

2019-02-04 21:36 UTC, Infinisil commented on nixos/modules/services/monitoring/grafana.nix
> +    dashboardConfigText = mkOption {
Why are there json and yaml configs? Do they serve the same purpose? If so, there's no need to allow config for both of them, only the yaml one will be enough.

2019-02-04 21:36 UTC, Infinisil commented on nixos/modules/services/monitoring/grafana.nix
> +        apiVersion: 1
Examples should go as an `example = ` attribute, and for this you'll need `literalExample` (see nixpkgs for examples)

2019-02-04 21:36 UTC, Infinisil commented on nixos/modules/services/monitoring/grafana.nix
> +        or replace to double quote, because it interfere with Nix syntax!
No need to point this out, people should be familiar with Nix syntax and not need a reminder in the options.

2019-02-04 21:36 UTC, Infinisil commented on nixos/modules/services/monitoring/grafana.nix
> +    datasourceConfigText = mkOption {
Same feedback as for `dashboardConfigText`

2019-02-04 21:36 UTC, Infinisil commented on maintainers/maintainer-list.nix
> +  };
You should put this change into a separate commit (so this PR has 2 commits)

2019-02-04 21:36 UTC, Infinisil commented on nixos/modules/services/monitoring/grafana.nix
> +        cat ${dashboardFile} > ${cfg.dataDir}/provisioning/dashboards/dashboard.json
Useless use of cat, you can just `ln -s` these. Also, doesn't this break backwards compatibility for people that had these files specified already?

2019-02-05 19:00 UTC, Ma27 commented
This is a duplicate to #53874. Also I prefer #53874 since it provides config options for NixOS, so no need to write tons of config in multiline strings.

2019-02-05 19:38 UTC, dlifanov commented
> This is a duplicate to #53874. Also I prefer #53874 since it provides config options for NixOS, so no need to write tons of config in multiline strings.

That one just points to dashboards path. The dashboard will consist of over hundred variables not viable for separate options. Here dashboard changes are under version control and it is deployed with Grafana.

2019-02-05 19:49 UTC, Ma27 commented
I'm sorry that I wasn't clear enough: the datasource can be configured declaratively (which isn't that complex, right?) which is why I prefer it.

The PR I pointed to also links to the dashboard config file rather than implementing tons of options. In that case you're absolutely right, implementing dashboard config entirely in Nix wouldn't be appropriate.

2019-02-06 11:49 UTC, Ma27 commented
@dlifanov @Infinisil @mkaito FYI, #53874 seems ready. Unless there are any reasons I'm missing why this PR should be preferred, I'd merge it this afternoon.

2019-02-06 23:02 UTC, Ma27 commented
I merged #53874 now because of the the reasons I expressed earlier.

2019-02-26 07:42 UTC, Ma27 commented
Closing for now as it's superseded by #53874, feel free to reopen or ping me if needed.

2019-02-26 07:42 UTC, closed without merging