nixos/pam: refactor U2F, docs about u2f_keys path
NixOS/nixpkgs pull request #54756
Opened 2019-01-28 03:25 UTC by kalbasit

###### Motivation for this change

* change enableU2F option to u2f.* set
* add few u2f options (not all) to customize pam-u2f module
* document default u2f_keys locations

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] ~~macOS~~
   - [ ] ~~other Linux distributions~~
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

Replaces #40455 and #11886.

2019-01-28 04:18 UTC, kalbasit commented
@GrahamcOfBorg test pam-u2f

2019-01-28 07:20 UTC, kalbasit commented
@spinus this PR is heavily based on your submission #11886. Please let me know if there's anything else you would like to add.
@Infinisil I've been using this PR for a few days now, and I have not had any issues, Do you have some time for a review? I will wait at least another week before merging to get a chance for more testing.

2019-01-28 09:30 UTC, infinisil requested changes

2019-01-28 16:16 UTC, kalbasit commented
@Infinisil I've updated the PR and addressed all of your comments, PTAL.

2019-01-28 19:03 UTC, infinisil requested changes

2019-01-28 19:03 UTC, Infinisil commented on nixos/modules/security/pam.nix
> +      authfile = mkOption {
Nitpick: `authfile` -> `authFile`

2019-01-28 19:03 UTC, Infinisil commented on nixos/modules/security/pam.nix
> +          Path can be changed using <literal>authfile</literal> option.
As per the other comments: `<literal>authfile</literal>` -> `<option>authFile</option>`

2019-01-29 03:08 UTC, kalbasit commented
@Infinisil PTAL.

2019-01-29 08:30 UTC, infinisil approved these changes

2019-01-29 08:34 UTC, Infinisil commented
Commit message should be changed to have the `nixos/...:` prefix. Feel free to merge this after that :)

2019-01-29 16:45 UTC, merged

2019-01-30 09:13 UTC, spinus commented
@kalbasit thank you for pushing that forward!