pythonPackages.shodan: init at 1.10.4
NixOS/nixpkgs pull request #54871
Opened 2019-01-29 04:43 UTC by lihop

Python library and command-line interface for Shodan.

###### Motivation for this change

Library missing from nixpkgs.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-01-29 08:04 UTC, dotlambda requested changes

2019-01-29 08:04 UTC, dotlambda commented on pkgs/development/python-modules/shodan/default.nix
> +    pname = "shodan";
```suggestion
  pname = "shodan";
```

2019-01-29 08:04 UTC, dotlambda commented
@GrahamcOfBorg build python2.pkgs.shodan python3.pkgs.shodan

2019-02-07 11:09 UTC, Lassulus approved these changes
Tested with nix-review, supplied my api key and ran some queries with the shodan executable

2019-02-07 12:14 UTC, merged