python3Packages.sly: init at 0.3
NixOS/nixpkgs pull request #55093
Opened 2019-02-02 18:17 UTC by costrouc

tests will be included with the next release
https://github.com/dabeaz/sly/pull/25
this is why I have not disabled tests (currently they pass with 0
tests run).

###### Motivation for this change

Saw a great talk on this package. Looking to toy around with an LALR parser.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-02-02 23:55 UTC, dotlambda requested changes
> this is why I have not disabled tests

Even when using `fetchFromGitHub`, no tests are run. Hence, a `checkPhase` will have to be added once they are published on PyPI and should be disabled for now.

2019-02-02 23:55 UTC, dotlambda commented on pkgs/development/python-modules/sly/default.nix
> +    license = licenses.bsdOriginal;
https://github.com/dabeaz/sly/blob/master/LICENSE is not the 4-clause variant

2019-02-02 23:55 UTC, dotlambda commented on pkgs/development/python-modules/sly/default.nix
> +    description = "Sly Lex Yacc";
```suggestion
    description = "An implementation of lex and yacc for Python 3";
```

2019-02-03 15:15 UTC, dotlambda commented
> > this is why I have not disabled tests
> 
> Even when using `fetchFromGitHub`, no tests are run. Hence, a `checkPhase` will have to be added once they are published on PyPI and should be disabled for now.

This has not been addressed.

2019-02-07 12:45 UTC, dotlambda commented
You are. I tested this by using `fetchFromGitHub` and it turned out no tests were run without setting an appropriate `checkPhase`.

2019-02-07 19:10 UTC, costrouc commented
@dotlambda I have disabled tests via `doCheck = false;`. Should be ready for merge

2019-02-07 22:54 UTC, dotlambda commented
@GrahamcOfBorg build python3Packages.sly

2019-02-07 22:57 UTC, merged