mkdocs-exclude: Init at 1.0.1
NixOS/nixpkgs pull request #55487
Opened 2019-02-09 18:24 UTC by spacefrogg

###### Motivation for this change

Adds the mkdocs-exclude plugin, a plugin for, well, mkdocs.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-02-13 11:17 UTC, FRidh requested changes
also include the package set in the commit name

2019-02-13 11:17 UTC, FRidh commented on pkgs/development/python-modules/mkdocs-exclude/default.nix
> +  buildInputs = [ setuptools mkdocs ];
`mkdocs` is a `propagatedBuildInputs` and `setuptools` a `nativeBuildInputs`.

2019-03-11 17:15 UTC, spacefrogg commented
Should be ready to merge now.

2019-07-31 09:06 UTC, spacefrogg commented
@FRidh poke.

2020-06-18 11:36 UTC, closed without merging