ctrtool: init at 0.15
NixOS/nixpkgs pull request #56402
Opened 2019-02-26 08:14 UTC by marius851000

###### Motivation for this change
A tool I use for 3ds modding

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-03-25 01:44 UTC, aanderse requested changes

2019-03-25 01:44 UTC, aanderse commented on maintainers/maintainer-list.nix
> +  marius851000 = {
Please have this in a separate commit.

2019-03-26 10:49 UTC, marius851000 commented on pkgs/tools/archivers/ctrtool/default.nix
> +  preConfigure = "cd ctrtool";
It say it change the sourceRoot, but he say he have an error with chmod after. Will take a look at the documentation.

2019-03-26 10:53 UTC, marius851000 commented on pkgs/tools/archivers/ctrtool/default.nix
> +  preConfigure = "cd ctrtool";
ok. I should have added source/ctrtool

2019-03-26 11:04 UTC, aanderse approved these changes
LGTM

2019-04-06 14:10 UTC, aanderse approved these changes

2019-04-06 14:10 UTC, aanderse commented on pkgs/tools/archivers/ctrtool/default.nix
> +    rev    = "${version}";
Sorry missed this first time around. Should be `rev = version;`, no need for quoting.

2019-05-10 10:55 UTC, marius851000 commented
@aanderse It's ready for merge

2019-05-10 11:12 UTC, aanderse requested changes
Here are some things I missed reviewing last time around. Please let me know if you have any questions.

2019-05-10 11:12 UTC, aanderse commented on pkgs/tools/archivers/ctrtool/default.nix
> +  name = "ctrtool";
This should be `pname` instead of `name`

2019-05-10 11:12 UTC, aanderse commented on pkgs/tools/archivers/ctrtool/default.nix
> +    description = "tool to extract data from a 3ds rom";
> Don’t include a period at the end. Don’t include newline characters. Capitalise the first character. For brevity, don’t repeat the name of package — just describe what it does. 

I would suggest `description = "A tool to extract data from a 3ds rom";`

2019-05-10 11:12 UTC, aanderse commented on pkgs/tools/archivers/ctrtool/default.nix
> +  meta = with stdenv.lib; {
Missing `meta.platforms`

2019-05-13 11:32 UTC, aanderse commented
@marius851000 given your comment about not receiving notification in the other PR I thought I'd ping you here to be sure.

2019-05-14 09:04 UTC, marius851000 commented
@aanderse that's done.

2019-05-14 09:34 UTC, aanderse commented
@GrahamcOfBorg build ctrtool

2019-05-14 10:15 UTC, aanderse approved these changes

2019-05-14 10:16 UTC, merged

2019-05-14 10:16 UTC, aanderse commented
@marius851000 thank you for your contribution! :tada: