nixos/jupyter: Fix documentation example for `jupyter.kernels`
NixOS/nixpkgs pull request #56415
Opened 2019-02-26 16:43 UTC by BenSchZA

###### Motivation for this change

The environment variable loading fails when using the example for `kernels` config, due to incorrect syntax. The error being something along the lines of `path not found`. The same is true for the loading of the relevant icons from path.

This change is a simple update of the service documentation.

###### Things done

- Built on platform(s)
   - [x] NixOS
- [x] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2019-03-03 08:22 UTC, FRidh requested changes
The variables need to be escaped correctly. This is an example, so we don't want it to actually evaluate them.

2019-03-03 08:23 UTC, FRidh commented
If I am correct, it's indeed removing the spaces like you did, and replacing the single $ with $$.

2019-03-04 21:14 UTC, Infinisil commented on nixos/modules/services/development/jupyter/default.nix
> +              "${env.interpreter}"
You need `"''${env.interpreter}"` for it not to be evaluated

2020-01-31 13:50 UTC, layus commented
@BenSchZA Triage ping. Are you still interested in updating and getting this merged ?

2020-01-31 13:54 UTC, BenSchZA commented
@layus Thanks for checking in. I've just seen the updates you made. Happy to update and get this merged.

2020-01-31 14:21 UTC, layus approved these changes
@FRidh I think this is ready

2020-01-31 14:30 UTC, merged