nixos/kubernetes: minor module fixes
NixOS/nixpkgs pull request #56589
Opened 2019-03-01 19:34 UTC by johanot

###### Motivation for this change

While testing the revamped kubernetes module on our existing staging cluster with `easyCerts` disabled, I discovered some minor flaws in the module:

1. The name of the etcd instance must be `mkDefault`'ed, because otherwise we risk overriding existing etcd cluster names, and that *could* potentially lead to cluster re-initiation on existing setups.

2. It's currently not possible to use the `kubernetes.lib.mkKubeConfig` function to generate a kubeconfig with a custom ca. It will always use the toplevel ca cert. This is fine for current easyCerts setup, where we don't have multiple CA's, but in existing setups this might cause problems. We

3. Turns out adding TLS-server certs to the controller manager was never done as part of the revamp and therefore we never discovered that the `--tls-key-file` flag on kube-controller-manager was named incorrectly. Similar flag names differ across various k8s components, but in this case it must be `--tls-private-key-file`. We should add TLS-serving certs to the controller-manager in another PR.

cc @fpletz for review
**please backport to 19.03** :)

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [X] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-03-05 10:58 UTC, johanot commented
re-ping @fpletz @calbrecht :-)

2019-03-06 18:08 UTC, calbrecht commented
He, the changes apply and it does not even rebuild the tests :) but i think they are sane nevertheless.
Confirming the flag has to be `--tls-private-key-file` from https://kubernetes.io/docs/reference/command-line-tools-reference/kube-controller-manager/
:+1:

2019-03-08 00:58 UTC, infinisil requested changes

2019-03-08 00:58 UTC, Infinisil commented on nixos/modules/services/cluster/kubernetes/default.nix
> +      cluster.certificate-authority = if (hasAttr "caFile" conf) then conf.caFile else cfg.caFile;
Same as just `conf.caFile or cfg.caFile`

2019-03-08 08:19 UTC, johanot commented on nixos/modules/services/cluster/kubernetes/default.nix
> +      cluster.certificate-authority = if (hasAttr "caFile" conf) then conf.caFile else cfg.caFile;
@Infinisil Right, thanks. Fixed now.

2019-03-08 14:47 UTC, infinisil approved these changes

2019-03-08 14:47 UTC, merged

2019-03-08 14:57 UTC, johanot commented
Thanks @Infinisil . Do you mind cherry-picking this to 19.03 please? Or should I create a new PR?

2019-03-08 15:25 UTC, Infinisil commented
Cherry-picked to release-19.03 in 5831fe1f4a32391389d186f46daad6055252b426 :)