tamsyn: init at 1.11
NixOS/nixpkgs pull request #57482
Opened 2019-03-12 03:36 UTC by robertseaton

###### Motivation for this change

Wanting to look like a l33t hackerman at Starbucks, needing a suitable bitmap font. 

###### Things done

- Created build file `fonts/tamsyn/default.nix`
- Edited `all-packages.nix`to add package
- Edited `maintainer-list.nix` to add self as maintainer

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-03-12 04:18 UTC, dtzWill commented
LGTM! :)

2019-03-12 14:12 UTC, ryantm requested changes

2019-03-12 14:12 UTC, ryantm commented on pkgs/data/fonts/tamsyn/default.nix
> +in stdenv.mkDerivation rec {
```suggestion
in stdenv.mkDerivation {
```
If you are going to have version in the let block, you probably don't need a recursive attrset.

2019-03-12 14:12 UTC, ryantm commented on pkgs/data/fonts/tamsyn/default.nix
> +  name = "tamsyn-font-${version}";
```suggestion
  pname = "tamsyn-font";
  inherit version;
```

2019-03-12 14:12 UTC, ryantm commented on pkgs/data/fonts/tamsyn/default.nix
> +    longDescription = '' Tamsyn is a monospace bitmap font, primarily aimed at
```suggestion
    longDescription = ''Tamsyn is a monospace bitmap font, primarily aimed at
```

2019-03-12 14:38 UTC, ryantm commented
@GrahamcOfBorg build tamsyn

2019-03-13 03:09 UTC, ryantm approved these changes

2019-03-13 03:09 UTC, ryantm commented
@GrahamcOfBorg build tamsyn

2019-03-13 03:45 UTC, merged

2019-03-13 03:45 UTC, ryantm commented
thanks!