junkie: init at 2.8.0
NixOS/nixpkgs pull request #57510
Opened 2019-03-12 12:05 UTC by rixed

###### Motivation for this change

Addition of a new networking tool: a programmable sniffer/DPI

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [X] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-03-14 19:12 UTC, infinisil requested changes

2019-03-14 19:12 UTC, Infinisil commented on pkgs/tools/networking/junkie/default.nix
> +  name = "junkie-${version}";
You can just set `pname = "junkie"` instead

2019-03-14 19:12 UTC, Infinisil commented on pkgs/tools/networking/junkie/default.nix
> +    sha256 = "c9b57bd6e06d4f90e6a88b775f33fa00f66313ba0f663df70198eddf1d4be298";
Use `fetchFromGitHub` instead with `rev = "v${version}"`

2019-03-14 19:12 UTC, Infinisil commented on pkgs/tools/networking/junkie/default.nix
> +  buildInputs = [ pkgconfig libpcap guile openssl ];
`pkgconfig` should be in `nativeBuildInputs` because it's only used at build time

2019-03-14 19:12 UTC, Infinisil commented on pkgs/tools/networking/junkie/default.nix
> +    maintainers = [ "rixed-github@happyleptic.org" ];
Add yourself to [maintainer-list.nix](https://github.com/NixOS/nixpkgs/blob/master/maintainers/maintainer-list.nix) instead in a separate first commit in this PR.

2019-03-15 07:23 UTC, rixed commented
Thank you so much for all the comments. That was my first attempt at packaging anything for Nix since I tested Nix about 7 or 8 years ago :)

2019-03-15 13:54 UTC, Infinisil commented
Nice :D 

Only thing I could complain about now is that the commits should be switched around, adding yourself to maintainers should come first because otherwise the package commit would reference your name which isn't present at that point yet

2019-03-15 14:21 UTC, rixed commented
> Only thing I could complain about now is that the commits should be switched around, adding yourself to maintainers should come first 

Yes, I think that's how it is, at least according to my `git log`. Also according to github commit tab, assuming it displays the commit in the same order than `git log`. Am I missing something?

2019-03-15 14:30 UTC, Infinisil commented
Ohh damn, it's GitHub's weird behavior where it doesn't display the commits in the right order sometimes when force pushing, see https://help.github.com/en/articles/why-are-my-commits-in-the-wrong-order

Alright everything good then :)

2019-03-15 14:30 UTC, infinisil approved these changes

2019-03-15 15:19 UTC, rixed commented
Oh I see. I was unaware of this behaviour.

2019-03-15 15:31 UTC, merged

2019-03-15 23:41 UTC, Infinisil commented
Does not build..

```
these derivations will be built:
  /nix/store/7p2h5w4glas3qx62grf80rd0svjmxqdg-source.drv
  /nix/store/1fqiw4zl8wm2rv4z99h61jj3v5qhmf19-junkie-2.8.0.drv
building '/nix/store/7p2h5w4glas3qx62grf80rd0svjmxqdg-source.drv'...

trying https://github.com/rixed/junkie/archive/v2.8.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   120    0   120    0     0    217      0 --:--:-- --:--:-- --:--:--   217
100 1233k    0 1233k    0     0   548k      0 --:--:--  0:00:02 --:--:--  997k
unpacking source archive /build/v2.8.0.tar.gz
hash mismatch in fixed-output derivation '/nix/store/rlyg71knykygmb5w3x4vvirl8x1jy8ik-source':
  wanted: sha256:16729cfxzvcq07vksrhgp89n7xh0z8rmyxwbm3k90kvdw3b7pdf9
  got:    sha256:0kfdjgch667gfb3qpiadd2dj3fxc7r19nr620gffb1ahca02wq31
cannot build derivation '/nix/store/1fqiw4zl8wm2rv4z99h61jj3v5qhmf19-junkie-2.8.0.drv': 1 dependencies couldn't be built
error: build of '/nix/store/1fqiw4zl8wm2rv4z99h61jj3v5qhmf19-junkie-2.8.0.drv' failed
```

2019-03-16 02:25 UTC, rixed commented
OMG. Fixed in https://github.com/NixOS/nixpkgs/pull/57737

I would swear it used to work but now of course I failed to repro it.