emacs-all-the-icons-fonts: 3.1.1 -> 3.2.0
NixOS/nixpkgs pull request #57644
Opened 2019-03-14 15:29 UTC by romildo

###### Motivation for this change

Update to version [3.2.0](https://github.com/domtronn/all-the-icons.el/releases/tag/3.2.0)

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2019-03-14 18:47 UTC, xeji requested changes
fix hash mismatches

2019-03-15 15:55 UTC, xeji commented
Now only the version number is updated but the sha256 remains unchanged. Is this correct?

2019-03-17 14:55 UTC, romildo commented
> Now only the version number is updated but the sha256 remains unchanged. Is this correct?

It happens that only the fonts are installed in this derivation, and it looks like they have not been changed from the prior version. The emacs part is installed by other means.

I would update only to keep the version number up to date.

2019-03-17 22:20 UTC, xeji commented
Fine, let's do that.

2019-03-17 22:20 UTC, xeji approved these changes

2019-03-17 22:20 UTC, merged