programs.gnupg: Support setting the gnupg program
NixOS/nixpkgs pull request #57782
Opened 2019-03-17 08:50 UTC by bkchr

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nox --run "nox-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-03-27 07:56 UTC, bkchr commented
@Infinisil ping.

2019-03-27 07:57 UTC, bkchr commented
@peti @fpletz as you are maintainers of gpg22

2019-03-27 13:52 UTC, peti requested changes

2019-03-27 13:52 UTC, peti commented on nixos/modules/programs/gnupg.nix
> +    program = mkOption {
I believe it's customary to call these kind of attributes `package`.

2019-04-01 08:52 UTC, bkchr commented
@peti Addressed your comment.

2019-04-01 15:44 UTC, infinisil requested changes

2019-04-01 15:44 UTC, Infinisil commented on nixos/modules/programs/gnupg.nix
> +      type = types.path;
Type should be `types.package`

2019-04-01 15:44 UTC, Infinisil commented on nixos/modules/programs/gnupg.nix
> +      default = pkgs.gnupg;
You need to add `defaultText = "pkgs.gnupg";`

2019-04-05 06:56 UTC, bkchr commented
@Infinisil fixed.

2019-04-05 13:43 UTC, infinisil approved these changes

2019-04-05 13:43 UTC, merged

2019-04-22 16:23 UTC, nixos-discourse commented
This pull request has been mentioned on **Nix community**. There might be relevant details there:

https://discourse.nixos.org/t/gpg-version-warning-when-using-gpg-agent-from-nixos-but-gnupg-from-user/2740/4