Giada2
NixOS/nixpkgs pull request #58233
Opened 2019-03-25 01:09 UTC by Zer0-

###### Motivation for this change
Giada is not in nixpkgs, it is one of the more capable sound looping programs on linux right now.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-03-25 10:57 UTC, jtojnar requested changes

2019-03-25 10:57 UTC, jtojnar commented on pkgs/applications/audio/giada/default.nix
> +      license = lib.licenses.gpl3;
```suggestion
      license = lib.licenses.gpl3Plus;
```

https://github.com/monocasual/giada/blob/251c67c3431b85ef3ac634e7348136cf8843b06d/src/main.cpp#L11-L14

2019-03-25 10:57 UTC, jtojnar commented on pkgs/applications/audio/giada/default.nix
> +    rev = "0e9a7aa5184dc73c6d39e2e5ee6c088c46b28aa6";
```suggestion
    rev = "v${version}";
```

2019-03-25 10:57 UTC, jtojnar commented on pkgs/applications/audio/giada/default.nix
> +  buildPhase = ''
You should not be overriding phases unless you know what you are doing. It breaks many features of generic builder like pre/post phase hooks and `configureFlags`.

Instead you should use

```nix
preConfigure = ''
  ${stdenv.shell} ./autogen.sh
'';

configureFlags = [
  "--target=linux"
];
```

The generic builder will take care of running `configure`, `make` and `make install`.

You can also try adding `doCheck = true` to run `make check`.

Also do not forget to add `--enable-system-catch` to `configureFlags`, see https://www.giadamusic.com/documentation-compiling-from-source

2019-03-25 10:57 UTC, jtojnar commented on pkgs/applications/audio/giada/default.nix
> +    autoconf
Programs run during build should go to `nativeBuildInputs`.

2019-03-25 10:57 UTC, jtojnar commented on pkgs/applications/audio/giada/default.nix
> +  name = "${pname}-${version}";
This is no longer necessary, `mkDerivation` does it by default.

2019-03-25 22:34 UTC, Zer0- commented
@jtojnar OK, Thank you for the feedback. I've made changes towards good practices.

2019-05-02 14:16 UTC, Zer0- commented
"This PR breaks listing of package outputs after merging. " what does this mean?

2019-07-16 02:28 UTC, aanderse commented
@GrahamcOfBorg eval

2019-07-17 01:47 UTC, aanderse requested changes
@Zer0- looks like an evaluation error. Please correct.

2019-07-17 01:47 UTC, aanderse commented on pkgs/applications/audio/giada/default.nix
> +      license = lib.licenses.gpl3Plus;
remove `lib.`.

2020-05-09 11:02 UTC, prusnak commented
Giada has been packaged since cb0b0e93a380d85d901b056b5df3570841899678

2020-05-09 11:02 UTC, closed without merging