beamPackages.hex: 0.17.1 -> 0.19.0
NixOS/nixpkgs pull request #58343
Opened 2019-03-26 09:23 UTC by peterromfeldhk

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-03-26 09:24 UTC, peterromfeldhk commented
@ericbmerritt for some reason i did not get sha mismatch when trying it out (that how i usually get the actual one :) ). i did update it using `nix-shell -p nix-prefetch-github --run 'nix-prefetch-github --rev 9fa9de6a54f8c0c712d656638a305da9291f2326 hexpm hex'`, but not sure why it did not complain about wrong sha?

2019-06-19 08:12 UTC, cw789 commented
Latest Version is now: v0.20.1 ([Source](https://github.com/hexpm/hex/releases))

2019-06-19 08:53 UTC, cw789 requested changes
Changes to edit PR to update hex to new v0.20.1.

2019-06-19 08:53 UTC, cw789 commented on pkgs/development/beam-modules/hex/default.nix
> +    version = "0.19.0";
`version = "0.20.1";`

2019-06-19 08:53 UTC, cw789 commented on pkgs/development/beam-modules/hex/default.nix
> +        sha256 = "0flzn0khs9vvphygghhcb2l67v1b4ya9zrjdm5sfznfp7n9g2pvb";
`sha256 = "0yxw7r31kk45b1nk48pajwwv9zl746kc9pwqfb73za8b1g8bgxd3";`

2019-06-21 08:32 UTC, cw789 commented
I've tested this now as an overlay on my Alpine Linux + Nix setup.
Should be fine to merge.

2019-07-03 09:43 UTC, cw789 commented
@NeQuissimus: Hello Tim, as you where the one who merged the last beamPackages.hex version upgrade PR, am I allowed to ask you how I can help to get this one merged?

2019-07-03 11:24 UTC, NeQuissimus approved these changes

2019-07-03 11:24 UTC, merged