cgit: add support for default filters
NixOS/nixpkgs pull request #58565
Opened 2019-03-30 00:39 UTC by pacien

###### Motivation for this change

This adds support for source code and about page filters that are shipped with cgit.
The new module options default to the previous behaviour.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

CC package maintainer: @bjornfor

2019-03-30 08:00 UTC, bjornfor approved these changes

2019-06-10 22:24 UTC, bjornfor requested changes
Please split into two commits, one to fix the cgit filters and the other to add the nixos options.

2019-06-10 22:38 UTC, bjornfor commented
I'm actually not sure adding the nixos options is a good idea. It's just feels like the start of a lot of maintenance work: why not add more and more options (eventually all)? For example, I personally use "about-filter", "source-filter" and "commit-filter", but this change only adds options for the first two. I guess I prefer to manage this directly in the transparent configText option.

2019-06-10 23:13 UTC, pacien commented
@bjornfor wrote:
> Please split into two commits, one to fix the cgit filters and the other to add the nixos options.

Sure, it's done.

> I'm actually not sure adding the nixos options is a good idea. It's just feels like the start of a lot of maintenance work: why not add more and more options (eventually all)? For example, I personally use "about-filter", "source-filter" and "commit-filter", but this change only adds options for the first two. I guess I prefer to manage this directly in the transparent configText option.

I agree, the two configuration lines generated by the added options could alternatively be put as an example for the `configText` attribute. What do you think about it?

2019-06-11 06:55 UTC, bjornfor commented
Yes, having those lines as examples is a good idea.

The 2nd commit should have prefix "nixos/cgit: [...]".

2019-06-11 12:31 UTC, pacien commented
Filters moved to example and module commit reworded.

2019-06-11 13:27 UTC, bjornfor approved these changes

2019-06-11 13:27 UTC, merged

2019-06-11 13:28 UTC, bjornfor commented
Thanks!