perl: substitute /bin/pwd with host pwd
NixOS/nixpkgs pull request #58979
Opened 2019-04-04 17:44 UTC by illegalprime

###### Motivation for this change

`/bin/pwd` is replaced during the build with nix's version.
it was incorrectly set to the build-time `pwd`, this would set it to the host's `pwd`

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-04-04 17:52 UTC, benley submitted a review, later dismissed

2019-04-04 17:56 UTC, benley commented
This definitely looks like a good fix but I'm not 100% sure if it's safe to merge; maybe it had something to do with perl being a bootstrapping dependency? @edolstra introduced this quirk so perhaps he should take a look.

2019-04-04 17:57 UTC, illegalprime commented
btw: should I be putting PRs into staging?

2019-04-04 18:00 UTC, benley commented
Master is fine for most things; staging is for changes that are going to require massive rebuilds, as it gives hydra a chance to catch up before things hit the nixos channels.  Perl may actually be one of those things :-P

btw, here is a comment I found about the `$pwd` thing in git blame history:

```
    # There's an annoying bug on sandboxed Darwin in Perl's Cwd.pm where it looks for pwd
    # in /bin/pwd and /usr/bin/pwd and then falls back on just "pwd" if it can't get them
    # while at the same time erasing the PATH environment variable so it unconditionally
    # fails. The code in question is guarded by a check for Mac OS, but the patch below
    # doesn't have any runtime effect on other platforms.
    postPatch = optional stdenv.isDarwin ''
      pwd="$(type -P pwd)"
      substituteInPlace dist/PathTools/Cwd.pm \
        --replace "/bin/pwd" "$pwd"
    '';
```

2019-04-04 18:05 UTC, illegalprime commented
yeah, :( the motivation here is to not bring along build-time dependencies when cross compiling

2019-04-04 18:16 UTC, illegalprime commented
I'm not sure why ofborg isn't building, it's building on my machine...  will investigate more

2019-04-05 13:04 UTC, edolstra commented on pkgs/development/interpreters/perl/default.nix
> +        --replace "/bin/pwd" "${coreutils}/bin/pwd"
Change to `$(type -P pwd`)`? That way you don't need an explicit dependency on coreutils.

2019-04-05 13:04 UTC, edolstra commented on pkgs/development/interpreters/perl/default.nix
> +        --replace "/bin/pwd" "${coreutils}/bin/pwd"
Oh wait, that's what it already did :-)

2019-04-05 15:03 UTC, volth commented
```grep```ing for ```type -P ``` reveals 62 more cases like this on

2019-05-24 21:33 UTC, Ekleog commented
@GrahamcOfBorg eval

@GrahamcOfBorg build perl gitFull

2019-05-24 21:54 UTC, Ekleog commented
@illegalprime This change appears to break evaluation on darwin: https://github.com/NixOS/nixpkgs/pull/58979/checks?check_run_id=135801652

2019-05-24 21:55 UTC, Ekleog requested changes
@illegalprime This change appears to break evaluation on at least darwin: https://github.com/NixOS/nixpkgs/pull/58979/checks?check_run_id=135801652

2019-08-03 16:09 UTC, lopsided98 commented
See https://github.com/NixOS/nixpkgs/pull/65761 for my PR that fixes the Darwin issue and another accidental reference.

2019-09-15 10:34 UTC, illegalprime commented
closing in favor of #65761

2019-09-15 10:34 UTC, closed without merging