python3Packages.poetry: 0.12.10 -> 0.12.12
NixOS/nixpkgs pull request #59506
Opened 2019-04-14 18:42 UTC by dtzWill

###### Motivation for this change

https://github.com/sdispater/poetry/releases/tag/0.12.12
https://github.com/sdispater/poetry/releases/tag/0.12.11

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-04-14 20:16 UTC, costrouc approved these changes

2019-04-14 20:19 UTC, costrouc requested changes
Don't know now to remove approval. Does not build on python 2.7. Used nix-review. 

```
builder for '/nix/store/4b9x2hgl7xvrwrpxkm3589mz7nabjqb8-python2.7-poetry-0.12.12.drv' failed with exit code 1; last 10 log lines:
  Successfully built poetry
  Finished creating a wheel...
  installing
  /build/poetry-0.12.12/dist /build/poetry-0.12.12
  DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
  Processing ./poetry-0.12.12-py2-none-any.whl
  Requirement already satisfied: virtualenv<17.0,>=16.0; python_version >= "2.7" and python_version < "2.8" in /nix/store/3h3n6yqjp1jjbl8jd4nibpk8vmv68px6-python2.7-virtualenv-16.4.1/lib/python2.7/site-packages (from poetry==0.12.12) (16.4.1)
  Collecting glob2<0.7,>=0.6; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.4" and python_version < "3.5" (from poetry==0.12.12)
    Could not find a version that satisfies the requirement glob2<0.7,>=0.6; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.4" and python_version < "3.5" (from poetry==0.12.12) (from versions: )
  No matching distribution found for glob2<0.7,>=0.6; python_version >= "2.7" and python_version < "2.8" or python_version >= "3.4" and python_version < "3.5" (from poetry==0.12.12)
cannot build derivation '/nix/store/ap9jvbak0nzba2gd56j82dyq1vahj6m7-env.drv': 1 dependencies couldn't be built
[2 built (1 failed), 150 copied (402.1 MiB), 86.2 MiB DL]
```

2019-04-14 23:45 UTC, costrouc commented
Looks great to me. Passed nix-review.

2019-04-15 15:37 UTC, worldofpeace commented
jsonschema has a `3.0.1` release so we shouldn't need to have it privately here anymore.
Though I don't know what changes are in `2 -> 3` so maybe the bump won't be easy.

2019-05-28 07:04 UTC, FRidh commented on pkgs/development/python-modules/poetry/default.nix
> +  format = "pyproject";
:tada:

2019-07-03 01:48 UTC, jbaum98 commented
This also looks good to me, what needs to happen to merge this?

2019-07-03 03:18 UTC, worldofpeace commented
@jbaum98 I suggested https://github.com/NixOS/nixpkgs/pull/59506#issuecomment-483304061

2019-07-03 06:17 UTC, jbaum98 commented
I upgraded `jsonschema` and ran `nix-review`.

----------------------------------------------------

Result of `nix-review` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>163 package failed to build:</summary>

  - aws-sam-cli (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - buildbot (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - buildbot-full (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - buildbot-ui (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - csvs-to-sqlite (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - devpi-server (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - flexget (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - jupyter (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - matrix-synapse (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - nbstripout (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - poretools (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.Quandl (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.altair (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.ansible-kernel (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.atomman (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.awkward (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.aws-sam-translator (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.bkcharts (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.bokeh (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.celery (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.cfn-lint (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.csvs-to-sqlite (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.cufflinks (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.dask (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.dask-glm (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbot-full ,python37Packages.buildbot-ui ,python37Packages.credstash ,python37Packages.csvs-to-sqlite ,python37Packages.poetry ,python37Packages.quandl ,python37Packages.tensorflowWithoutCuda)
  - python27Packages.dask-image (docker_compose ,python27Packages.quandl ,python37Packages.buildbot ,python37Packages.buildbo [...]

2019-07-03 06:55 UTC, worldofpeace commented
This would be the only case where I'd actually see packages already failing to build being positive :rofl: 

As I suspected the bump probably causes breakages.
@FRidh Think it be reasonable to merge and we can work to bumping jsonschema separately?

2019-07-03 07:12 UTC, FRidh commented
pushed 5102201ba4f22e6d91e5a13d9b1e89eb4b8e4eb5

2019-07-03 07:12 UTC, closed without merging

2019-07-03 07:13 UTC, FRidh commented
For jsonschema (and other packages) we should run a job using `python-unstable` branch again.