pythonPackages.pikepdf: init at 1.2.0
NixOS/nixpkgs pull request #59908
Opened 2019-04-19 23:13 UTC by leenaars

###### Motivation for this change

Dependency for e.g. ocrmypdf

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-04-22 20:26 UTC, infinisil requested changes

2019-04-22 20:26 UTC, Infinisil commented on pkgs/development/python-modules/pikepdf/default.nix
> +{ stdenv, buildPythonPackage, python3Packages, fetchPypi, qpdf, pythonOlder }:
Don't take version specific arguments, use `pythonPackages` instead

2019-04-22 20:36 UTC, infinisil requested changes

2019-04-22 20:36 UTC, Infinisil commented on pkgs/development/python-modules/pikepdf/default.nix
> +  checkInputs = with python3Packages; [ nose pytest hypothesis pillow ];
Oh actually, don't take dependencies from pythonPackages at all, put all these packages in the argument list instead, see how other packages in nixpkgs do this.

2019-04-22 20:36 UTC, Infinisil commented on pkgs/development/python-modules/pikepdf/default.nix
> +                                        setuptools setuptools_scm
These should be in `propagatedBuildInputs`

2019-04-22 20:36 UTC, Infinisil commented on pkgs/development/python-modules/pikepdf/default.nix
> +  checkInputs = with python3Packages; [ nose pytest hypothesis pillow ];
This is the error you get if you don't have this:

```bash
$ nix-shell -p 'python3.withPackages (p: [ p.pikepdf ])' -I nixpkgs=$PWD --pure --run 'python3 -c "import pikepdf"'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/nix/store/697ghwi4qfnl90r1km0566bjcqhjgn3c-python3-3.7.3-env/lib/python3.7/site-packages/pikepdf/__init__.py", line 24, in <module>
    from .models import (
  File "/nix/store/697ghwi4qfnl90r1km0566bjcqhjgn3c-python3-3.7.3-env/lib/python3.7/site-packages/pikepdf/models/__init__.py", line 11, in <module>
    from .metadata import PdfMetadata
  File "/nix/store/697ghwi4qfnl90r1km0566bjcqhjgn3c-python3-3.7.3-env/lib/python3.7/site-packages/pikepdf/models/metadata.py", line 16, in <module>
    from defusedxml.lxml import parse
ModuleNotFoundError: No module named 'defusedxml'
```

2019-07-20 11:25 UTC, FRidh requested changes

2019-07-20 11:25 UTC, FRidh commented on pkgs/development/python-modules/pikepdf/default.nix
> +{ stdenv, buildPythonPackage, python3Packages, fetchPypi, qpdf, pythonOlder }:
don't use `pythonXXPackages` at all :)

2019-07-20 11:25 UTC, FRidh commented
Closing due to inactivity.

2019-07-20 11:25 UTC, closed without merging