jupyterlab: Fix build
NixOS/nixpkgs pull request #60159
Opened 2019-04-24 13:41 UTC by matthiasbeyer

The build was broken by updating the underlying python library.
This is the quickfix.

Fixes: ca67a7200cf ("python37Packages.jupyterlab_server: 0.2.0 -> 0.3.0")

Closes #60154

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] other Linux distributions (centos7)
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-04-24 13:42 UTC, matthiasbeyer commented
@dotlambda and https://github.com/tcosmo might be interested in this.

2019-04-24 14:30 UTC, tcosmo commented
Thank you!

2019-04-24 15:30 UTC, dotlambda requested changes
The commit message should start with `python3Packages.jupyterlab`.

2019-04-24 15:30 UTC, dotlambda commented on pkgs/development/python-modules/jupyterlab/default.nix
> +      url = "https://github.com/jupyterlab/jupyterlab/commit/3b8d451e6f9a4c609e60cde5fbb3cc84aae79951.patch";
```suggestion
      url = https://github.com/jupyterlab/jupyterlab/commit/3b8d451e6f9a4c609e60cde5fbb3cc84aae79951.patch;
```

2019-04-24 15:30 UTC, dotlambda commented on pkgs/development/python-modules/jupyterlab/default.nix
> +      name = "Bump-jupyterlab_server-version";
```suggestion
      name = "bump-jupyterlab_server-version.patch";
```

2019-04-24 19:57 UTC, veprbl commented
@GrahamcOfBorg build python37Packages.jupyterlab

2019-04-25 05:59 UTC, matthiasbeyer commented
Rebased on latest master and squashed the commits. Ready for merge from my side.

2019-04-25 07:32 UTC, FRidh commented
@GrahamcOfBorg build python3.pkgs.jupyterlab

2019-04-25 07:41 UTC, merged