waifu2x-converter-cpp: init at 5.2.4
NixOS/nixpkgs pull request #60399
Opened 2019-04-29 01:21 UTC by xzfc

###### Motivation for this change

Add waifu2x-converter-cpp, an anime image superresolution tool.
Tested on NVIDIA CUDA, and CPU. Not tested on OpenCL/AMDGPU.
Previous PR: #50398.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-04-29 20:14 UTC, c0bw3b requested changes
Minor changes, otherwise LGTM

2019-04-29 20:14 UTC, c0bw3b commented on pkgs/tools/graphics/waifu2x-converter-cpp/default.nix
> +  name = "waifu2x-converter-cpp-${version}";
```suggestion
  pname = "waifu2x-converter-cpp";
```
Nix will do the rest on its own

2019-04-29 20:14 UTC, c0bw3b commented on pkgs/tools/graphics/waifu2x-converter-cpp/default.nix
> +    repo = "waifu2x-converter-cpp";
```suggestion
    repo = pname;
```

2019-04-29 20:14 UTC, c0bw3b commented on pkgs/tools/graphics/waifu2x-converter-cpp/default.nix
> +    repo = "waifu2x-converter-cpp";
```suggestion
    repo = pname;
```

2019-04-30 11:57 UTC, xzfc commented
Updated.

2019-04-30 16:30 UTC, c0bw3b commented
@GrahamcOfBorg build waifu2x-converter-cpp

2019-04-30 20:55 UTC, c0bw3b approved these changes

2019-04-30 20:55 UTC, merged