pythonPackages.faker: fix build
NixOS/nixpkgs pull request #61110
Opened 2019-05-07 22:33 UTC by mmlb

###### Motivation for this change
pythonPackages.faker no longer builds

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-05-07 22:46 UTC, worldofpeace requested changes
Build has a requirement for `freezegun` and why the build seems to be now failing.

Though this did fix the `rm: missing operand`.

2019-05-07 23:05 UTC, mmlb commented
@worldofpeace yep I noticed that after a little bit, I've fixed that locally but have now run into a problem that I don't know how to solve. `Faker` depends on `more-itertools<6.0.0` which I can handle here, but then I run into an issue that `pytest` depends on `more-itertools` too and will cause a clash because its using the packaged 6.0.0. I'm stumped on how to fix.

Pushing what I have now.

2019-05-07 23:24 UTC, risicle commented
You could try feeding the `checkInputs` an ad-hoc `pytest` which has been overridden with your `more-itertools5`:

`(pytest.override { more-itertools = more-itertools5; })`

and if `pytest` won't accept `more-itertools5` as it's too old you could try your luck with `pytest_3`. If you do this you'll probably need to thread this new `pytest` back in to the `pytestrunner` you use.

2019-05-07 23:27 UTC, worldofpeace commented
> @worldofpeace yep I noticed that after a little bit, I've fixed that locally but have now run into a problem that I don't know how to solve. `Faker` depends on `more-itertools<6.0.0` which I can handle here, but then I run into an issue that `pytest` depends on `more-itertools` too and will cause a clash because its using the packaged 6.0.0. I'm stumped on how to fix.
> 
> Pushing what I have now.

`more-itertools` is just a testing dependency if I'm understanding this correctly.
What kind of failures would result if we used the `6.0.0`, assuming that's why they've enforced the pin.

I'm partial to just patching this away because it's just for tests. Also note we've already patched the pin for `pytest` in `postPatch` so we couldn't do worse.

2019-05-08 00:22 UTC, mmlb commented
patched to ignore the version specifier (with some notes). @worldofpeace PTAL.

2019-05-08 00:31 UTC, worldofpeace approved these changes
Perfect :+1: 

Builds again for all interpreters.
Please squash your commits and we can merge.

2019-05-08 01:36 UTC, mmlb commented
done @worldofpeace thanks for help!

2019-05-08 01:38 UTC, merged

2019-05-08 01:39 UTC, worldofpeace commented
> done @worldofpeace thanks for help!

You're very welcome. Thanks for contributing :sparkles: