Add documentation for recent permitUserSite change
NixOS/nixpkgs pull request #61502
Opened 2019-05-14 16:39 UTC by thomasjm

###### Motivation for this change

Add a couple lines to the Python documentation for the new `permitUserSite` option, as requested in #51641. CC @FRidh 

Documentation-only change.

2019-05-14 19:07 UTC, FRidh requested changes

2019-05-14 19:07 UTC, FRidh commented on doc/languages-frameworks/python.section.md
> +* `permitUserSite ? false`: Skip setting the PYTHONNOUSERSITE environment variable in wrapped programs.
use backticks, `PYTHONNOUSERSITE`

2019-05-14 19:07 UTC, FRidh commented on doc/languages-frameworks/python.section.md
> +* `permitUserSite`: Skip setting the PYTHONNOUSERSITE environment variable in wrapped binaries in the environment.
same

2019-05-15 03:43 UTC, thomasjm commented
Done

2019-05-15 06:28 UTC, merged