kind: 0.2.1 -> v0.3.0
NixOS/nixpkgs pull request #61964
Opened 2019-05-23 15:03 UTC by j0xaf

###### Motivation for this change

Upgrade kind from 0.2.1 to v0.3.0.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] other Linux distributions
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-05-23 15:04 UTC, j0xaf commented
cc @gilligan and @thoughtpolice who may be interested in this

2019-05-23 15:19 UTC, gilligan commented
@GrahamcOfBorg build kind

2019-05-23 18:52 UTC, nlewo requested changes

2019-05-23 18:52 UTC, nlewo commented on pkgs/development/tools/kind/default.nix
> +  version = "v0.3.0";
According to the manual, the version should start by a digit.
```suggestion
  version = "0.3.0";
```

2019-05-23 18:52 UTC, nlewo commented on pkgs/development/tools/kind/default.nix
>      rev    = "${version}";
```suggestion
    rev    = "v${version}";
```

2019-05-24 01:03 UTC, thoughtpolice commented
LGTM.

2019-05-24 01:04 UTC, merged