ytcc: init at 1.8.1
NixOS/nixpkgs pull request #61998
Opened 2019-05-24 10:57 UTC by marius851000

###### Motivation for this change
found this software, which appear to be really interessing. modified the gallery-dl installation instruction

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
Tested the ability to list unwatched video with this software.

2019-05-24 10:58 UTC, marius851000 commented
@GrahamcOfBorg build ytcc

2019-05-25 01:58 UTC, aanderse requested changes

2019-05-25 01:58 UTC, aanderse commented on pkgs/tools/networking/ytcc/default.nix
> +  doCheck = false;
Always nice if you can include a comment why.

2019-05-25 01:58 UTC, aanderse commented on pkgs/tools/networking/ytcc/default.nix
> +    description = "Command Line tool to keep track of your favourite YouTube channels without signing up for a Google account.";
No period at end please.

2019-05-26 15:01 UTC, marius851000 commented
@aanderse

2019-05-26 16:09 UTC, aanderse commented
@GrahamcOfBorg build ytcc

2019-05-26 16:09 UTC, aanderse approved these changes

2019-05-26 16:27 UTC, merged

2019-05-26 16:28 UTC, aanderse commented
@marius851000 Thanks for your contribution! :tada: