nixos/cadvisor: expose interval options
NixOS/nixpkgs pull request #62071
Opened 2019-05-25 22:26 UTC by tilpner

###### Motivation for this change

Options are described here: https://github.com/google/cadvisor/blob/master/docs/runtime_options.md

If Prometheus only queries every 10s, there's no point for cadvisor to query the system every second. These options allow to disable that unnecessary work.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-05-25 22:27 UTC, tilpner commented
cc @basvandijk @offlinehacker

2019-05-25 22:28 UTC, tilpner commented
These are `nullOr str` so that we don't hardcode their defaults in nixpkgs. I would usually choose a nested structure for shorter names, but that didn't fit with the rest of the options.

2019-05-27 16:23 UTC, infinisil requested changes

2019-05-27 16:23 UTC, Infinisil commented on nixos/modules/services/monitoring/cadvisor.nix
> +        description = "Interval between global housekeepings";
Nitpick: Descriptions should have a `.` at the end

2019-05-27 16:23 UTC, Infinisil commented on nixos/modules/services/monitoring/cadvisor.nix
> +        example = "1m0s";
Can you put the format for this in the description?

2019-05-27 21:05 UTC, infinisil approved these changes

2019-05-27 21:06 UTC, Infinisil commented
Hmm although, if there are even more options in the CLI, it might make more sense to just have an `extraOptions` NixOS option to pass additional CLI options.

2019-05-28 12:30 UTC, tilpner commented
@Infinisil That's a style question, for which there doesn't seem to be a consensus. I'd be in favor of adding less structured catch-all options (`attrs` usually), but that's out of scope for this PR.

2019-05-28 12:33 UTC, Infinisil commented
Well I'm very much in favor of that, see NixOS/rfcs#42, advantages are listed there

2019-05-28 12:40 UTC, tilpner commented
@Infinisil You don't have to convince me, I already agree. But that's not for this PR, and I probably won't send another one for a few days. Close this PR if you feel an unstructured option will be accepted and is reasonably easy to implement.

2019-05-28 13:22 UTC, Infinisil commented
I think it would be rather easy to implement, but I don't mind this PR either

2019-08-18 21:30 UTC, tilpner commented
How do we proceed with this?

2019-08-18 21:30 UTC, closed without merging