abbaye-des-morts: init at 2.0.1
NixOS/nixpkgs pull request #62124
Opened 2019-05-27 16:25 UTC by marius851000

###### Motivation for this change
A fun game I discovered and wanted to play. Packaged it BTW.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-05-27 18:53 UTC, mmahut requested changes
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg eval succeeded
- [X] run nix-review without any failures
- [X] run and tested the binaries

2019-05-27 18:53 UTC, mmahut commented on pkgs/games/abbaye-des-morts/default.nix
> +  meta = with stdenv.lib; {
meta.maintainers is missing

2019-05-27 20:15 UTC, matthewbauer commented
@grahamcofborg build abbaye-des-morts

2019-05-28 06:34 UTC, marius851000 commented
I don't know how to solve this mac problem...

2019-05-28 06:34 UTC, marius851000 commented on pkgs/games/abbaye-des-morts/default.nix
> +  meta = with stdenv.lib; {
thank

2019-05-28 07:01 UTC, marius851000 commented
How can I test with clang ?

2019-05-28 07:15 UTC, mmahut commented
> I don't know how to solve this mac problem...

If you are not able to solve this for darwin, you need to specify the platforms as per https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes

2019-05-29 11:08 UTC, marius851000 commented
I've corrected the problem with mac

2019-05-29 13:32 UTC, c0bw3b commented
@GrahamcOfBorg build abbaye-des-morts

2019-05-30 16:14 UTC, marius851000 commented
it doesn't appear to be a problem coming from me

2019-06-01 14:37 UTC, fpletz commented
Since the mac building the package seems to have been our of resources:

@GrahamcOfBorg build abbaye-des-morts

2019-06-01 14:39 UTC, fpletz approved these changes
:heavy_check_mark:

2019-06-01 14:39 UTC, merged