dedup: 1.0 -> 2.0
NixOS/nixpkgs pull request #62199
Opened 2019-05-29 01:48 UTC by dtzWill

###### Motivation for this change

Update deps, enable tests.

https://git.2f30.org/dedup/file/CHANGELOG.html

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-05-29 06:33 UTC, mmahut requested changes
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg build succeeded for all applicable platforms
- [X] run nix-review without any failures
- [X] run and tested the binaries

2019-05-29 06:33 UTC, mmahut commented on pkgs/tools/backup/dedup/default.nix
>      description = "data deduplication program";
According to CONTRIBUTING this needs to be capitalized.

2019-05-30 08:04 UTC, Ma27 commented
Built and tested locally as described in the [project's README](https://git.2f30.org/dedup/file/README.html) and fixed the description as requested by @mmahut.

Let's wait for ofborg and merge then.

2019-05-30 08:35 UTC, merged

2019-05-30 08:36 UTC, Ma27 commented
@dtzWill @mmahut thanks!