pythonPackages.pyworld: init at 0.2.8
NixOS/nixpkgs pull request #62231
Opened 2019-05-29 20:28 UTC by hyphon81

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-05-30 09:08 UTC, Ma27 requested changes

2019-05-30 09:08 UTC, Ma27 commented on pkgs/development/python-modules/pyworld/default.nix
> +    stdenv.cc
This should't be needed, `stdenv.cc` should be available in each build environment (unless `stdenvNoCC` is used).

2019-05-30 09:08 UTC, Ma27 commented on pkgs/development/python-modules/pyworld/default.nix
> +  src = fetchPypi {
The PyPI tarball does't contain any tests, hence `0 tests` will be logged in the build output. If there are any tests in the Git tarball (e.g. from GitHub), it's fine to use that one to have some tests running during the build. If there aren't any tests (or mostly impure ones that will break during `nix-build`), please set `doCheck = false`.

2020-02-09 09:18 UTC, FRidh commented
Merge conflict

2021-03-12 07:53 UTC, Mindavi commented
Has been packaged since: pkgs/development/python-modules/pyworld/default.nix. You could consider adding yourself as maintainer.

2021-03-12 07:53 UTC, closed without merging