python.pkgs.pip: 9.0.3 -> 9.1.1
NixOS/nixpkgs pull request #62316
Opened 2019-05-31 15:16 UTC by jonringer

###### Motivation for this change
Remove pip version warning when installing packages. I know this will cause a lot of rebuilds, sorry.

Building tensorflow from scratch, and haven't hit any issues.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---
```
$ nix path-info -Sh /nix/store/vcdwhk6w6syjx3hwb4ifkqcrsp4w7h3j-python3.5-pip-19.1.1
/nix/store/vcdwhk6w6syjx3hwb4ifkqcrsp4w7h3j-python3.5-pip-19.1.1         102.0M
```

2019-05-31 15:25 UTC, FRidh requested changes
version in commit msg is incorrect

2019-05-31 15:31 UTC, jonringer commented
@FRidh yep, sorry, still waking up

2019-05-31 15:57 UTC, jonringer commented
was about to build tensorflow1.13.1 and firefox with the changes.

2019-06-15 00:17 UTC, jonringer commented
bump @FRidh , feel bad constantly bugging you

2019-06-15 07:14 UTC, merged

2019-06-15 07:16 UTC, FRidh commented
This was not supposed to go in so reverted it directly. It's instead in `python-unstable` which I'll merge in `staging` this weekend so hopefully we have it on `master` the next weekend.

2019-06-15 18:10 UTC, jonringer commented
Sounds good. Thanks for visiting again :)