Add rusty-tags 3.5.1 release
NixOS/nixpkgs pull request #62557
Opened 2019-06-03 01:22 UTC by danielakhterov

###### Motivation for this change
I wanted to be able to install rusty-tags via nix instead of `cargo install`.

###### Things done
Added myself to  the list of maintainers. Added a simple nix derivation for [rusty-tags](https://github.com/dan-t/rusty-tags) v3.5.1.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-07-18 12:50 UTC, joachifm commented
Needs to be rebased. Superficially looks okay to me otherwise.

2020-11-28 02:08 UTC, SuperSandro2000 requested changes

2020-11-28 02:08 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +  danielakhterov = {
Please put this into a separate commit with the message ``maintainers: add danielakhterov``.

2020-11-28 02:08 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  rusty-tags = callPackage ../development/tools/misc/rusty-tags { };
Please don't add packages add the end but in their right categories.

2020-11-28 02:08 UTC, SuperSandro2000 commented on pkgs/development/tools/misc/rusty-tags/default.nix
> +  name = "rusty-tags-${version}";
```suggestion
  pname = "rusty-tags";
```

2020-11-28 02:08 UTC, SuperSandro2000 commented on pkgs/development/tools/misc/rusty-tags/default.nix
> +    platforms = platforms.all;
This is not required here.

2022-08-08 23:17 UTC, closed without merging