aerc: init at 0.1.0
NixOS/nixpkgs pull request #62648
Opened 2019-06-04 06:16 UTC by Mic92

###### Motivation for this change

Fully tested and works, but since I will not switch to aerc in the near future, I just leave this as a draft until somebody wants to actually maintain this package.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-06-04 15:00 UTC, kalbasit requested changes
By default all `buildGoModule` are assigned to me, feel free to remove the entire `maintainers` block.

2019-06-04 15:00 UTC, kalbasit commented on pkgs/applications/networking/mailreaders/aerc/default.nix
> +    platforms = platforms.unix;
homepage?

2019-06-04 15:00 UTC, kalbasit requested changes
By default all `buildGoModule` are assigned to me, feel free to remove the entire `maintainers` block.

2019-06-07 04:59 UTC, tadeokondrak commented
I'd be willing to maintain this package.

2019-06-07 10:47 UTC, Mic92 commented
@tadeokondrak feel free to open a pull request with my code.

2019-06-07 14:41 UTC, commando-crypto commented
I've been using aerc built from this branch for 2 days now. Happy to open a PR with myself as maintainer.

2019-06-07 14:54 UTC, Mic92 commented
Multiple maintainers are also welcome.

2019-06-08 03:51 UTC, closed without merging