joker: 0.12.2 -> 0.12.4
NixOS/nixpkgs pull request #63013
Opened 2019-06-12 03:46 UTC by andrestylianos

###### Motivation for this change

Version bump

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-06-12 07:07 UTC, mmahut approved these changes
- [X] reviewed the diff and commit messages
- [X] made sure ofBorg evals
- [X] run nix-review without any failures
- [X] run and tested the binaries

2019-07-13 18:42 UTC, gazally requested changes
I built this and tried out the joker REPL and it works.  The package also installs a binary called `sum256dir` which is one of their build tools.  Can you remove it?

2019-08-01 08:35 UTC, andrestylianos commented
Thanks for the review @gazally, and sorry for the delay in updating this. I've removed `sum256dir` in the `postBuild` step which seemed to be the correct place to do it, but since I'm not very experienced with nix please let me know if I should have done it another way.

2019-08-01 15:19 UTC, nixos-discourse commented
This pull request has been mentioned on **Nix community**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/49

2019-08-01 17:58 UTC, merged