Add NodeJS v10 to nixos-small channel
NixOS/nixpkgs pull request #63605
Opened 2019-06-21 08:59 UTC by wmertens

v10 is the LTS but it is a breaking change to make it the default on 18.03 so it would be good to add it as build.

This will increase the build time and closure size of nixos-small, but it would be useful for at least my servers.

2019-07-27 19:27 UTC, samueldr requested changes
This targets 18.03, which is not supported anymore, and wasn't for a while when this PR was opened! Should this have targeted 19.03 instead?

2019-07-27 21:30 UTC, wmertens commented
Argh! Should we revert on 18.03?

Wout.

On Sat., Jul. 27, 2019, 9:27 p.m. Samuel Dionne-Riel <
notifications@github.com> wrote:

> *@samueldr* requested changes on this pull request.
>
> This targets 18.03, which is not supported anymore, and wasn't for a while
> when this PR was opened! Should this have targeted 19.03 instead?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/63605?email_source=notifications&email_token=AAANNFQS2IXYDA4CTXAE2LTQBSOSFA5CNFSM4H2PBSP2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOB7YWVBI#pullrequestreview-267479685>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AAANNFRJCNACEK7MVCGS543QBSOSFANCNFSM4H2PBSPQ>
> .
>

2019-07-28 00:11 UTC, samueldr commented
I'm not sure I follow.

Adding anything to the small release for 18.03 would be a no-op, since it was last updated 157 days ago, and will not (should not) receive any more updates.

2019-10-25 22:44 UTC, veprbl commented
Closing as this targets the old release-18.03 brach which is not supported anymore.

2019-10-25 22:44 UTC, closed without merging