new:  python-modules/tinytag at 1.2.2
NixOS/nixpkgs pull request #63661
Opened 2019-06-22 16:10 UTC by deepfire

###### Motivation for this change
Adds a python tagging library.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-06-22 17:21 UTC, jonringer reviewed
You'll want your commit title to be `pythonPackages.tinytag: init at 1.2.2` so it conforms to CONTRIBUTING.md, and the CI/CD tool can automatically build it :)

I would also change your PR title to reflect this as well

2019-06-22 21:07 UTC, JohnAZoidberg commented
I'd apply these changes.
- With python packages you can take the python dependencies as arguments and you don't need `with python3Packages; [ ...]`
- The tests are included in the GitHub sources
- `with ...;` is not the best because it's unclear where attributes come from. That's why I try to reduce it's scope in meta

Some tests are still failing. If you've got time, you can figure out why. If not, just disable them again.

```diff
--- i/pkgs/development/python-modules/tinytag/default.nix                                                                                                                                                                                      
+++ w/pkgs/development/python-modules/tinytag/default.nix                                                                                                                                                                                      
@@ -1,25 +1,32 @@                                                                                                                                                                                                                              
-{ stdenv, fetchPypi, substituteAll, python3Packages }:                                                                                                                                                                                        
-                                                                                                                                                                                                                                              
-python3Packages.buildPythonPackage rec {                                                                                                                                                                                                      
-  version = "1.2.2";                                                                                                                                                                                                                          
+{ buildPythonPackage, lib, fetchFromGitHub, twine, pytest, pytestcov, coveralls, flake8, isPy3k }:                                                                                                                                                                          
+buildPythonPackage rec {                                                                                                                                                                                                                      
   pname = "tinytag";                                                                                                                                                                                                                          
+  version = "1.2.2";                                                                                                                                                                                                                          
                                                                                                                                                                                                                                               
-  src = fetchPypi {                                                                                                                                                                                                                           
-    inherit pname version;                                                                                                                                                                                                                    
-    sha256 = "sha256:0r2pazrqq9lxy3an7vvafc6whglnawx2mi8x75gnrr56a02xpr8h";                                                                                                                                                                   
+  src = fetchFromGitHub {
+    owner = "devsnd";
+    repo = pname;
+    rev = version;
+    sha256 = "1728m4dsnzkw3f5xphjkc7vmlnc2lf4px9a69jixsi924bljmw1s";
   };
  
-  propagatedBuildInputs = with python3Packages; [
+  propagatedBuildInputs = [
     twine
   ];
  
-  # No tests
-  doCheck = false;
+  checkInputs = [
+    pytest pytestcov coveralls flake8
+  ];
+
+  doCheck = !isPy3k;
+  postCheck = ''
+    python runtests.py
+  '';
  
-  meta = with stdenv.lib; {
-    description = "Read music meta data and length of MP3, OGG, OPUS, MP4, M4A, FLAC, WMA and Wave files with python 2 or 3";
+  meta = {
+    description = "Read music meta data and length of MP3, OGG, OPUS, MP4, M4A, FLAC, WMA and Wave files";
     homepage = "https://github.com/devsnd/tinytag";
-    license = licenses.mit;
-    maintainers = [ maintainers.deepfire ];
+    license = lib.licenses.mit;
+    maintainers = with lib.maintainers; [ deepfire ];
   };
 }
```

2019-06-22 21:08 UTC, JohnAZoidberg requested changes
I'd apply these changes.
- With python packages you can take the python dependencies as arguments and you don't need `with python3Packages; [ ...]`
- The tests are included in the GitHub sources
- `with ...;` is not the best because it's unclear where attributes come from. That's why I try to reduce it's scope in meta

Some tests are still failing. If you've got time, you can figure out why. If not, just disable them again.

```diff
--- i/pkgs/development/python-modules/tinytag/default.nix                                                                                                                                                                                      
+++ w/pkgs/development/python-modules/tinytag/default.nix                                                                                                                                                                                      
@@ -1,25 +1,32 @@                                                                                                                                                                                                                              
-{ stdenv, fetchPypi, substituteAll, python3Packages }:                                                                                                                                                                                        
-                                                                                                                                                                                                                                              
-python3Packages.buildPythonPackage rec {                                                                                                                                                                                                      
-  version = "1.2.2";                                                                                                                                                                                                                          
+{ buildPythonPackage, lib, fetchFromGitHub, twine, pytest, pytestcov, coveralls, flake8, isPy3k }:                                                                                                                                                                          
+buildPythonPackage rec {                                                                                                                                                                                                                      
   pname = "tinytag";                                                                                                                                                                                                                          
+  version = "1.2.2";                                                                                                                                                                                                                          
                                                                                                                                                                                                                                               
-  src = fetchPypi {                                                                                                                                                                                                                           
-    inherit pname version;                                                                                                                                                                                                                    
-    sha256 = "sha256:0r2pazrqq9lxy3an7vvafc6whglnawx2mi8x75gnrr56a02xpr8h";                                                                                                                                                                   
+  src = fetchFromGitHub {
+    owner = "devsnd";
+    repo = pname;
+    rev = version;
+    sha256 = "1728m4dsnzkw3f5xphjkc7vmlnc2lf4px9a69jixsi924bljmw1s";
   };
  
-  propagatedBuildInputs = with python3Packages; [
+  propagatedBuildInputs = [
     twine
   ];
  
-  # No tests
-  doCheck = false;
+  checkInputs = [
+    pytest pytestcov coveralls flake8
+  ];
+
+  doCheck = !isPy3k;
+  postCheck = ''
+    python runtests.py
+  '';
  
-  meta = with stdenv.lib; {
-    description = "Read music meta data and length of MP3, OGG, OPUS, MP4, M4A, FLAC, WMA and Wave files with python 2 or 3";
+  meta = {
+    description = "Read music meta data and length of MP3, OGG, OPUS, MP4, M4A, FLAC, WMA and Wave files";
     homepage = "https://github.com/devsnd/tinytag";
-    license = licenses.mit;
-    maintainers = [ maintainers.deepfire ];
+    license = lib.licenses.mit;
+    maintainers = with lib.maintainers; [ deepfire ];
   };
 }
```

2019-06-23 16:11 UTC, FRidh requested changes

2019-06-23 16:11 UTC, FRidh commented on pkgs/development/python-modules/tinytag/default.nix
> +{ stdenv, fetchPypi, substituteAll, python3Packages }:
explicit arguments instead of `python3Packages`

2020-06-04 19:11 UTC, jonringer commented
no movement in almost a year, going to close. @deepfire feel free to re-open this if you want the package included in nixpkgs

2020-06-04 19:11 UTC, closed without merging