snscrape: 0.2.0 -> 0.3.0
NixOS/nixpkgs pull request #64054
Opened 2019-07-01 20:07 UTC by ivan

###### Motivation for this change

https://github.com/JustAnotherArchivist/snscrape/commits/v0.3.0

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Assured whether relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

I tested 0.3.0 on twitter and instagram and it worked, unlike 0.2.0 now.

2019-07-01 20:11 UTC, ivan commented
@GrahamcOfBorg build snscrape

2019-07-17 08:40 UTC, FRidh requested changes

2019-07-17 08:40 UTC, FRidh commented on pkgs/development/python-modules/snscrape/default.nix
> +  buildInputs = [ setuptools_scm ];
nativeBuildInputs

2019-07-27 03:12 UTC, ivan commented on pkgs/development/python-modules/snscrape/default.nix
> +  buildInputs = [ setuptools_scm ];
Thanks, fixed.

2019-07-27 03:12 UTC, ivan commented
@GrahamcOfBorg build snscrape

2019-08-16 14:46 UTC, merged