kbfs: 2.11.0 ->  4.1.0
NixOS/nixpkgs pull request #64377
Opened 2019-07-06 10:32 UTC by worldofpeace

The kbfs code has been moved to the same
repo as the keybase package.

###### Motivation for this change
Fixes #64248

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-07-06 10:40 UTC, das-g approved these changes

2019-07-06 10:50 UTC, worldofpeace commented
I will merge this once I've manually tested this on master.

2019-07-06 16:50 UTC, kalbasit requested changes
No modules upstream? 😣

2019-07-06 16:50 UTC, kalbasit commented on pkgs/tools/security/keybase/kbfs.nix
> +  src = keybase.src;
```suggestion
  inherit (keybase) src version;
```

And also remove version assignment above.

2019-07-06 20:56 UTC, worldofpeace commented
Thanks @kalbasit.

> No modules upstream? :persevere:

Yeah unfortunately not. Seems that reorganization and things like that aren't a small task.

2019-07-07 01:46 UTC, kalbasit approved these changes

2019-07-07 01:47 UTC, merged