foliate: init at 1.4.0
NixOS/nixpkgs pull request #64536
Opened 2019-07-09 17:32 UTC by dtzWill

###### Motivation for this change

"A simple and modern GTK eBook reader".

Took some wrangling to get gjs to run without having problems finding
'main' or some resource, see linked issues from code for some details of
similar.  Does seem to work nicely now, though! ^_^

###### Things done

- [x]  Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-07-13 15:00 UTC, MetaDark commented
I was able to run the application but I couldn't load any eBooks.

![foliate](https://user-images.githubusercontent.com/382041/61173161-71b8f880-a55d-11e9-9156-81e923c592eb.png)

```
file:///nix/store/3mggjk8rq27s5cha58xgm7gn4fmsy2c1-foliate-1.4.0/share/com.github.johnfactotum.Foliate/assets/epub.js:3435:10: CONSOLE ERROR Not allowed to load local resource: file:///home/kira/Documents/Outlander%20Series%20by%20Diana%20Gabaldon/EPUB/META-INF/container.xml
file:///nix/store/3mggjk8rq27s5cha58xgm7gn4fmsy2c1-foliate-1.4.0/share/com.github.johnfactotum.Foliate/assets/epub.js:3435:10: CONSOLE ERROR Not allowed to request resource
file:///nix/store/3mggjk8rq27s5cha58xgm7gn4fmsy2c1-foliate-1.4.0/share/com.github.johnfactotum.Foliate/assets/epub.js:3435:10: CONSOLE ERROR XMLHttpRequest cannot load file:///home/kira/Documents/Outlander%20Series%20by%20Diana%20Gabaldon/EPUB/META-INF/container.xml due to access control checks.
file:///nix/store/3mggjk8rq27s5cha58xgm7gn4fmsy2c1-foliate-1.4.0/share/com.github.johnfactotum.Foliate/assets/epub.js:3435:10: CONSOLE ERROR Not allowed to load local resource: file:///home/kira/Documents/Outlander%20Series%20by%20Diana%20Gabaldon/EPUB/META-INF/container.xml
file:///nix/store/3mggjk8rq27s5cha58xgm7gn4fmsy2c1-foliate-1.4.0/share/com.github.johnfactotum.Foliate/assets/epub.js:3435:10: CONSOLE ERROR Not allowed to request resource
file:///nix/store/3mggjk8rq27s5cha58xgm7gn4fmsy2c1-foliate-1.4.0/share/com.github.johnfactotum.Foliate/assets/epub.js:3435:10: CONSOLE ERROR XMLHttpRequest cannot load file:///home/kira/Documents/Outlander%20Series%20by%20Diana%20Gabaldon/EPUB/META-INF/container.xml due to access control checks.
Error sending IPC message: Broken pipe
```

2019-07-19 03:39 UTC, worldofpeace requested changes
Seems development has moved quickly since you've opened this.

https://github.com/johnfactotum/foliate/releases/tag/1.5.0

To adapt to that release you probably should add `espeak` and use `wrapPython` to patch
the python module included.

2019-07-19 03:39 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +  buildInputs = [
```suggestion

  buildInputs = [
```

whitespace

2019-07-19 03:39 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +  buildInputs = [
Please add gdk_pixbuf
* https://github.com/johnfactotum/foliate/blob/master/src/main.js#L30

glib as well.

2019-07-19 03:39 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +    ln -s $out/bin/com.github.johnfactotum.Foliate $out/bin/foliate
I think this would only be appropriate if all applications that RDDN their binaries to have an alias like this.
```suggestion
```

2019-07-19 03:39 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +    meson ninja
multi line this please.

2019-07-19 03:39 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +{ stdenv, fetchFromGitHub, meson, ninja, gettext, pkgconfig, python3
Can you make this one per line?

2019-07-19 03:39 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +    license = licenses.gpl3;
```suggestion
    license = licenses.gpl3Plus;
```

looking at code preambles.

2019-07-19 03:39 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +  nativeBuildInputs = [
I'm seeing a `hicolor/icon-theme.cache` in the output.
Can you add `hicolor-icon-theme` so it gets removed by the setup-hook?

2019-07-19 03:41 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +  doCheck = true;
I don't see any checks in the repo.

2019-07-21 22:05 UTC, MetaDark commented
It looks like the issue I ran into is a problem with foliate and not this package. I was able to reproduce the same issue on my Arch machine trying to open the same ebook. I tried again with some other epub samples and everything seems to be working as expected.

I have no issue opening the book in calibre, so I'm not really sure why foliate has an issue with this specific file...

2019-07-23 05:49 UTC, worldofpeace requested changes
Don't think these deps are needed.

Application still functions when I remove them.

These comments from last review were unaddressed https://github.com/NixOS/nixpkgs/pull/64536#discussion_r305190775 https://github.com/NixOS/nixpkgs/pull/64536#discussion_r305190404

2019-07-23 05:49 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +    cairo
```suggestion
```

2019-07-23 05:49 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +    libgee
```suggestion
```

2019-07-23 05:49 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +    pantheon.granite
```suggestion
```

2019-07-23 05:49 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +    libxml2
```suggestion
```

2019-07-23 05:49 UTC, worldofpeace commented on pkgs/applications/office/foliate/default.nix
> +  ];
```suggestion
  ];

```

2019-07-26 04:21 UTC, dtzWill commented
Thank you @worldofpeace, I got those deps from looking at meson files that were checking for them optionally.... but not seeing them now, so maybe goofed on which repo I was looking at or something :3.

Anyway, outstanding issues / unresolved issues AFAIK:

- [ ] package/wrap the python bits that appear to be useful for interacting with Kindle formats?
- [ ] wrap or patch in path for espeak(-ng)

2019-07-26 04:48 UTC, worldofpeace commented
> Thank you @worldofpeace, I got those deps from looking at meson files that were checking for them optionally.... but not seeing them now, so maybe goofed on which repo I was looking at or something :3.

I can't lie that I've done that very often. I quickly realize I probably should close the other 50 tabs :smile: 

> Anyway, outstanding issues / unresolved issues AFAIK:

It appears you accidentally removed `gdk_pixbuf` in https://github.com/NixOS/nixpkgs/pull/64536/commits/3be211e73e3891b6858bb7924fcc7c2984f11f9c.

> package/wrap the python bits that appear to be useful for interacting with Kindle formats?

This is how they use it 
* https://github.com/johnfactotum/foliate/blob/0eb90a6bddf7452466d0a856da01d8da4f2e77d9/src/main.js#L1799

I think I may have tried this and wasn't a way for `wrapPython` to work for it. (not in site-packages)

>  wrap or patch in path for espeak(-ng)

I think it wants those optional programs like `dict` etc. in $PATH
* https://github.com/johnfactotum/foliate/blob/0eb90a6bddf7452466d0a856da01d8da4f2e77d9/src/main.js#L231

Case of preference to use hardcode patch or a wrapper.

2019-12-06 16:26 UTC, JonathanReeve commented
I just started writing a derivation for this, but then someone told me about this PR. Would love to see this in master. Is anything holding this up? Can I help?

2020-04-07 07:27 UTC, onny commented
Meanwhile version 2.0 is released. It is really a great and cool GTK program!

2020-04-07 07:32 UTC, jtojnar commented
Feel free to take over, we will be glad to review.

2020-06-13 18:22 UTC, sikmir commented
2.2.0 is out.

2020-07-08 06:20 UTC, worldofpeace commented
I'm closing this PR, if anyone wants to continue the work please open a new one.

2020-07-08 06:20 UTC, closed without merging

2020-08-14 16:45 UTC, onny commented
For testing purpose I continued this package in my [NUR](https://github.com/nix-community/NUR) repository. You can try the package ``nur.repos.onny.foliate`` if you want :) I've packaged version 2.4.2. Still not sure which features might be missing or bugs still present.