calls: Initial commit to package the application
NixOS/nixpkgs pull request #65362
Opened 2019-07-25 01:57 UTC by craigem

###### Motivation for this change

The calls application is required to provide phone calls for the Librem 5 phone.
    
This is the initial commit for this application to be packaged for NixOS and the first step to getting NixOS to fully support the Librem 5 phone.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

---

2019-07-25 02:00 UTC, craigem commented
Resolves #65361

2019-07-25 04:17 UTC, peterhoeg requested changes

2019-07-25 04:17 UTC, peterhoeg commented on pkgs/applications/radio/calls/default.nix
> +let
we can get rid of the ```let``` part

2019-07-25 04:17 UTC, peterhoeg commented on pkgs/applications/radio/calls/default.nix
> +  name = "${pname}-${version}";
just assign pname and version here (and drop name)

2019-07-25 04:17 UTC, peterhoeg commented on pkgs/applications/radio/calls/default.nix
> +  outputs = [ "out" ];
not needed

2019-07-25 04:17 UTC, peterhoeg commented on pkgs/applications/radio/calls/default.nix
> +    meson ninja pkgconfig libhandy modemmanager
libhandy is a runtime dependency - should go into ```buildInputs```.

2019-07-25 04:17 UTC, peterhoeg commented on pkgs/applications/radio/calls/default.nix
> +  checkPhase = ''
runHook preCheck (and postCheck at the end)

2019-07-25 04:39 UTC, worldofpeace commented
This and a lot of other Librem software has been packaged as part of #57614.

https://github.com/NixOS/nixpkgs/pull/57614/commits/ddee3c8a7b6fe716dc66417d88d348463be0cfdd looks pretty complete, perhaps out of date.

2019-07-25 05:59 UTC, craigem commented
> This and a lot of other Librem software has been packaged as part of #57614.

I had not found this. I'll make sure I hook everything I'm doing back into that.

Thanks!

2019-07-25 10:27 UTC, craigem commented
I had a read of #57614 and note that he had put it "networking" where as I had put it in "radio".

Any thoughts on the correct location?

2019-07-27 13:49 UTC, worldofpeace commented
A calling application would be a networking application. Additionally all the applications in that directory have to relation to this one.

2019-07-28 10:37 UTC, craigem commented
> A calling application would be a networking application. Additionally all the applications in that directory have no relation to this one.

I can see why that would be applicable, but this application is using modem manager to use operate a mobile phone radio to place phone calls across a mobile phone network.

Happy to switch this to "networking", just wanted to make it clear that this was not a VOIP application.

2019-07-28 21:34 UTC, worldofpeace commented
> I can see why that would be applicable, but this application is using modem manager to use operate a mobile phone radio to place phone calls across a mobile phone network.

Indeed, but I think it has fallen out of fashion to refer to those things as "radio" even though it's correct.

also
>  Additionally all the applications in that directory have no relation to this one.

2019-07-29 23:42 UTC, craigem commented
**calls** has now been moved to **networking**.

2019-07-29 23:46 UTC, worldofpeace requested changes
You need to call this package in `all-packages.nix`.

Additonally, can you match the code style of https://github.com/NixOS/nixpkgs/commit/ddee3c8a7b6fe716dc66417d88d348463be0cfdd and *Inputs?

Currently the dependencies are declared improperly, and we shouldn't have to reference anything under the `gnome3` attribute.

2019-07-30 00:47 UTC, craigem commented
Thanks for your time and input @worldofpeace 

I originally based this work on how the related package, libhandy was packaged so your corrections and guidance have been helpful.

If I've understood your suggestions correctly, this last commit should be what you're looking for.

2019-07-31 11:27 UTC, craigem commented
Finally bumped `all-packages.nix`.

2019-08-07 21:36 UTC, nixos-discourse commented
This pull request has been mentioned on **Nix community**. There might be relevant details there:

https://discourse.nixos.org/t/github-label-for-prs-for-librem-5-related-packages/3653/3

2019-08-23 09:52 UTC, peterhoeg requested changes

2019-08-23 09:52 UTC, peterhoeg commented on pkgs/applications/networking/calls/default.nix
> +    libhandy
libhandy is already in buildInputs, so it should be removed.

2019-08-23 09:52 UTC, peterhoeg commented on pkgs/applications/networking/calls/default.nix
> +    modemmanager
Are you sure this isn't a buildInput?

2019-08-23 15:12 UTC, jtojnar commented on pkgs/applications/networking/calls/default.nix
> +    xlibs.xauth
```suggestion
    xorg.xauth
```

2019-08-23 15:13 UTC, jtojnar commented
What the heck is this commit set:

```ShellSession
~/P/nixpkgs ((3a0f023e…)|…) $ git hub pull checkout 65362
Fetching pull/65362/head from git@github.com:NixOS/nixpkgs.git
~/P/nixpkgs ((6e99182f…)|…) $ git rebase channels/nixos-unstable
First, rewinding head to replay your work on top of it...
Applying: calls: Initial commit to package the application
Applying: Corrected licence
Applying: Corrected licence
Using index info to reconstruct a base tree...
M	pkgs/applications/radio/calls/default.nix
Falling back to patching base and 3-way merge...
Auto-merging pkgs/applications/radio/calls/default.nix
No changes -- Patch already applied.
~/P/nixpkgs ((07e4206a…)|…) $ nix-build -A calls
error: attribute 'calls' in selection path 'calls' not found
```

2019-10-31 13:07 UTC, lheckemann commented
I've pushed a version with a cleaned-up history, upgraded to a recent version from upstream git, and tested the application as far as I could (I haven't managed to bend ModemManager to my will yet, but calls seems fine). Will merge on Monday if nobody objects, or as soon as someone approves :)

2019-10-31 13:39 UTC, worldofpeace commented on pkgs/applications/radio/calls/default.nix
> +  buildInputs = [ libhandy gnome3.gsound gtk3 gnome3.libpeas gom libxml2 evolution_data_server ];
```suggestion
  buildInputs = [ libhandy gsound gtk3 libpeas gom libxml2 evolution-data-server ];
```

old aliases

2019-10-31 13:39 UTC, worldofpeace commented on pkgs/applications/radio/calls/default.nix
> +    meson ninja pkgconfig libhandy modemmanager desktop-file-utils
why is modemanager and libhandy native?

2019-10-31 13:41 UTC, worldofpeace commented
@lheckemann This was never moved to networking https://github.com/NixOS/nixpkgs/pull/65362#issuecomment-516202918.

2019-10-31 13:43 UTC, worldofpeace commented
@lheckemann Can we format the expression as @jtojnar https://github.com/NixOS/nixpkgs/blob/4bc5288ac9f6d99ca595433fcaf9fa4ca9fbe5a5/pkgs/applications/networking/calls/default.nix.
That's a code style we're pretty much going for. You could even push that expression manually.

2019-11-01 10:37 UTC, lheckemann commented
Wow, that was a funky history. Rebase completely failed..? Anyway, here's my second cleanup attempt :)

2019-11-01 10:49 UTC, worldofpeace commented on pkgs/applications/networking/calls/default.nix
> +  version = "2019-10-09-unstable";
`unstable` in `pname`.

https://github.com/NixOS/nixpkgs/issues/68518

2019-11-01 10:49 UTC, worldofpeace commented on pkgs/applications/networking/calls/default.nix
> +    xlibs.xauth
@lheckemann ^

2019-11-01 10:50 UTC, worldofpeace commented on pkgs/applications/networking/calls/default.nix
> +    evolution_data_server
```suggestion
    evolution-data-server
```

2019-11-01 10:50 UTC, worldofpeace commented on pkgs/applications/networking/calls/default.nix
> +  buildInputs = [
```suggestion

    buildInputs = [
```

2019-11-01 10:51 UTC, worldofpeace commented
@lheckemann `libhandy` and `modemanager` are both sill in `nativeBuildInputs`.

2019-11-10 21:59 UTC, merged