python3Packages.datatable: fix darwin build
NixOS/nixpkgs pull request #65613
Opened 2019-07-30 20:34 UTC by jonringer

###### Motivation for this change
Attempt to resolve #65611

Need to be at home before I can verify on my own mac.

Verified it doesn't affect linux derivation.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @kalbasit

2019-07-30 20:36 UTC, jonringer commented
@GrahamcOfBorg build python3Packages.datatable

2019-07-30 20:37 UTC, jonringer commented
keep forgetting that ofBorg doesn't build darwin anymore, darn :(

2019-07-30 23:52 UTC, kalbasit commented
I'm still getting the same error.

2019-07-31 05:11 UTC, worldofpeace commented
> keep forgetting that ofBorg doesn't build darwin anymore, darn :(

I believe that's because you need to be a trusted user to trigger darwin builds.
It may be a good idea to submit that at the ofborg repo if you plan on regularly
contributing to the darwin infrastructure in nixpkgs.

2019-07-31 05:30 UTC, jonringer commented
@worldofpeace I don't trust me. :)

2019-07-31 16:35 UTC, kalbasit commented
@GrahamcOfBorg build python3Packages.datatable

2019-07-31 16:40 UTC, worldofpeace requested changes

2019-07-31 16:40 UTC, worldofpeace commented on pkgs/development/python-modules/datatable/hardcode-library-paths.patch
> ++        resolved = ["@libomp.dylib@", "@libc++.1.dylib@", "@libc++abi.dylib@"]
This is dangerous if they're not super valid bash variables.

Probably better to be `libomp_dylib` etc.

2019-07-31 16:40 UTC, worldofpeace commented on pkgs/development/python-modules/datatable/default.nix
> +    ./hardcode-library-paths.patch
You can actually do
```
(substituteAll {
  src = ./hardcode-library-paths.patch;
  libomp_dylib = "${lib.getLib openmp}/lib/libomp.dylib";
})
```

in patches which I feel works much cleaner

2019-07-31 16:49 UTC, kalbasit commented
@worldofpeace PTAL

@GrahamcOfBorg build python3Packages.datatable

2019-07-31 16:56 UTC, jonringer commented
We may be able to edit/remove the buildInputs addition. Nix should be able to detect that there are store paths. Are you able to run this package with a normal workload?

2019-07-31 16:58 UTC, kalbasit commented
> We may be able to edit/remove the buildInputs addition. Nix should be able to detect that there are store paths. Are you able to run this package with a normal workload?

I have not tried doing that. It was failing for me due to the lack of `shutil` and I noticed that it was attempting to copy native binaries to the build directory which useless anyway.

2019-08-01 17:44 UTC, jonringer commented
Removing openmp breaks the build, but I may the add the others since I'm assuming they will be needed at runtime anyway.

Other than that, I don't have a good way to test this package actually works :(

2019-08-01 17:54 UTC, kalbasit commented
> Removing openmp breaks the build, but I may the add the others since I'm assuming they will be needed at runtime anyway.
> 
> Other than that, I don't have a good way to test this package actually works :(

The tests pass. I've also checked the linked dynamic libraries and they look good.

2019-08-01 17:54 UTC, merged