Ctrtool update
NixOS/nixpkgs pull request #66079
Opened 2019-08-05 14:43 UTC by marius851000

###### Motivation for this change
ctrtool was updated yesterday

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-08-06 15:26 UTC, aanderse requested changes
- please change commit message to `ctrtool: 0.15 -> 0.16` as per [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md)
- please drop the extra `dolphin-emu` commit

2019-08-06 15:26 UTC, aanderse commented on pkgs/tools/archivers/ctrtool/default.nix
> +    owner  = "jakcron";
Please explain why this change can be trusted, preferably citing an official source.

2019-08-10 12:11 UTC, marius851000 reviewed
That's done

2019-08-10 14:17 UTC, aanderse commented
@GrahamcOfBorg build ctrtool

2019-08-10 23:28 UTC, aanderse approved these changes

2019-08-10 23:28 UTC, merged

2019-08-10 23:30 UTC, aanderse commented
@marius851000 thanks! :tada: