qt5.mkDerivation: allow disabling hook insertion
NixOS/nixpkgs pull request #67134
Opened 2019-08-20 22:52 UTC by jtojnar

2019-08-20 22:58 UTC, jtojnar commented
Maybe instead of `includeWrapQtAppsHook` we could add an attribute that would disable Qt’s `mkDerivation` completely, turning it into `stdenv.mkDerivation`

2019-08-20 23:01 UTC, worldofpeace commented
Hmm, this is an interesting topic. When there's optional qt features I'd expect people to add `wrapQtAppsHook` manually and to not use `qt5.mkDerivation`.

2019-08-21 00:11 UTC, worldofpeace requested changes
Should work as intended.

2019-08-21 00:11 UTC, worldofpeace commented on pkgs/os-specific/linux/v4l-utils/default.nix
>  { stdenv, lib, fetchurl, pkgconfig, perl, mkDerivation
```suggestion
{ stdenv, lib, fetchurl, pkgconfig, perl
```

2019-08-21 00:46 UTC, worldofpeace approved these changes

2019-08-21 00:46 UTC, worldofpeace commented
Huh, this is only 100-500 rebuilds according to ofborg. Should we go to master?

2019-08-21 00:55 UTC, jtojnar commented
There would be a merge conflict.

2019-08-21 00:58 UTC, worldofpeace commented
Ah, merging then.

2019-08-21 00:58 UTC, merged