ljsyscall: init at 20180515
NixOS/nixpkgs pull request #67385
Opened 2019-08-24 11:48 UTC by lblasc

#### Motivation for this change

Add LuaJIT syscall library, sadly latest release is unusable.
It is possible to use this library with plain Lua 5.1 with help of `luaffi`.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @teto

2019-08-24 12:21 UTC, disassembler requested changes

2019-08-24 12:21 UTC, disassembler commented on pkgs/development/lua-modules/overrides.nix
> +    version = "20180515";
Needs an unstable in the version since it isn't a release

2019-08-24 12:21 UTC, disassembler commented on pkgs/development/lua-modules/overrides.nix
> +      owner = "justincormack"; repo = "ljsyscall";
Or these on separate lines

2019-08-24 12:34 UTC, lblasc commented
@disassembler thx for looking into it. Applied changes you requested.

2019-08-26 14:27 UTC, lblasc commented
Also enabled ljsyscall on Lua 5.2, it works fine with `luaffi`.

cc @disassembler @teto

2019-08-28 10:58 UTC, merged