linuxPackages.exfat-nofuse: 2018-04-16 -> 2019-09-06
NixOS/nixpkgs pull request #68647
Opened 2019-09-13 11:23 UTC by makefu

###### Motivation for this change

Upstream repository is unmaintained since 2018, maintainership got taken
over by AdrianBan ( https://github.com/dorimanx/exfat-nofuse/issues/145#issuecomment-528632096 )

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [N/A] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers
that would be me, i guess
cc @

2019-09-13 11:33 UTC, makefu commented
@GrahamcOfBorg build linuxPackages.exfat-nofuse

2019-09-14 04:28 UTC, disassembler requested changes

2019-09-14 04:28 UTC, disassembler commented on pkgs/os-specific/linux/exfat/default.nix
>    version = "2018-04-16";
change version to 2019-09-05

2019-09-14 04:28 UTC, disassembler commented on pkgs/os-specific/linux/exfat/default.nix
> +    homepage = https://github.com/AdrianBan/exfat-nofuse;
new trick I learned: `inherit (src.meta) homepage;`

2019-09-16 12:10 UTC, makefu commented on pkgs/os-specific/linux/exfat/default.nix
> +    homepage = https://github.com/AdrianBan/exfat-nofuse;
will do!

2019-09-16 12:10 UTC, makefu commented on pkgs/os-specific/linux/exfat/default.nix
>    version = "2018-04-16";
wupps, that slipped by

2019-09-16 15:07 UTC, makefu commented
This PR should solve all(tm) build errors related to exfat-nofuse in #68361

2019-09-16 15:08 UTC, makefu commented
@GrahamcOfBorg build linuxPackages.exfat-nofuse linuxPackages_4_14.exfat-nofuse linuxPackages_4_19.exfat-nofuse linuxPackages_5_2.exfat-nofuse linuxPackages_5_1.exfat-nofuse linuxPackages_xen_dom0.exfat-nofuse

2019-09-23 08:18 UTC, makefu commented
builds timed out, not sure what happened there. let me retry

2019-09-23 08:18 UTC, makefu commented
@GrahamcOfBorg build linuxPackages.exfat-nofuse linuxPackages_4_14.exfat-nofuse linuxPackages_4_19.exfat-nofuse linuxPackages_5_2.exfat-nofuse linuxPackages_5_1.exfat-nofuse linuxPackages_xen_dom0.exfat-nofuse

2019-09-23 14:39 UTC, makefu commented
mh seems to try to compile all the kernels(tm).

2019-09-24 02:47 UTC, merged

2019-09-24 02:48 UTC, Mic92 commented
[detached HEAD 630bffe451e] linuxPackages.exfat-nofuse: 2018-04-16 -> 2019-09-06
 Author: makefu <github@syntax-fehler.de>
 Date: Fri Sep 13 08:43:15 2019 +0200
 1 file changed, 5 insertions(+), 14 deletions(-)