chiaki: init at 1.0.3
NixOS/nixpkgs pull request #68806
Opened 2019-09-14 16:56 UTC by delroth

###### Motivation for this change

Chiaki is a new open source client for the PS4 remote play protocol.

Note: I put it in `pkgs/games`, it's not a perfect fit but other gaming-centric apps like `steam` are there already, so there's precedent (thought emulators are in `misc`... so there's also negative precedent).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2019-09-14 17:37 UTC, jonringer approved these changes
`nix-review` passes on NixOS
diff LGTM
executable works
leaf package

2019-09-14 23:56 UTC, aanderse requested changes
Just missing one attribute. Looks good otherwise. :+1:

2019-09-14 23:56 UTC, aanderse commented on pkgs/games/chiaki/default.nix
> +  meta = with lib; {
Please include `platforms`.

2019-09-14 23:56 UTC, aanderse commented on pkgs/games/chiaki/default.nix
> +    homepage = https://github.com/thestr4ng3r/chiaki;
Please quote if you don't mind.

2019-09-15 13:23 UTC, aanderse approved these changes

2019-09-15 13:24 UTC, merged

2019-09-15 13:24 UTC, aanderse commented
Thanks @delroth and @jonringer :tada: