Remove pykde4
NixOS/nixpkgs pull request #70264
Opened 2019-10-02 18:39 UTC by ttuegel

###### Motivation for this change

See also: #70102 

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-10-02 20:20 UTC, delroth approved these changes

2019-10-02 20:34 UTC, gnidorah commented
Please don't. I still use and maintain it. You may mark it as broken instead.

2019-10-02 20:35 UTC, ghost requested changes
Please don't. I still use and maintain it. You may mark it as broken instead.

2019-10-02 20:42 UTC, FRidh commented
maintained yet broken? We can mark it as insecure, but really, it's a very old package. I think at this point you better use it from an older Nixpkgs version.

2019-10-02 20:56 UTC, gnidorah commented
@FRidh Since there are no other known users of it... Actually @ttuegel made a patch for that CVE in #70102 that went into 19.03, why not merge it to master too? I would prefer to keep it since pykde5 is an old wip.

2019-10-02 21:33 UTC, ttuegel commented
> Actually @ttuegel made a patch for that CVE in #70102 that went into 19.03, why not merge it to master too?

@gnidorah I didn't make the patch, it comes from upstream. I cherry-picked the changes from `release-19.03`, marked you as maintainer of both packages, and disabled the Hydra build.

2019-10-02 21:35 UTC, delroth commented on pkgs/development/python-modules/pykde4/kdelibs.nix
> +      name = "kdelibs-D22989.patch";
CVE-2019-14744.patch (see https://github.com/NixOS/nixpkgs/issues/70102#issuecomment-537679033)

2019-10-03 01:09 UTC, ghost approved these changes
Thanks!

2019-10-03 10:57 UTC, merged