Added libvmaf + support for it in ffmpeg-full
NixOS/nixpkgs pull request #70797
Opened 2019-10-08 22:02 UTC by cfsmp3

#70593 #### Things done

- Created package libvmaf (Netflix's video quality library)
- Added myself as a mantainer for it
- Added libvmaf support to ffmpeg-full

Tested on Ubuntu Linux. Nothing fancy here though, all quite standard.

###### Notify maintainers

cc @jonringer @Fuuzetsu

2019-10-08 23:20 UTC, jonringer commented
@GrahamcOfBorg build libvmaf ffmpeg-full

2019-10-10 18:32 UTC, cfsmp3 commented
@jonringer  Fuuzetsu Anything else needed from me? (or is there another reviewer I should tag)

2019-10-10 22:44 UTC, jonringer commented
LGTM, I've just been busy. Sorry @marsam does it look good to you?

2019-10-15 05:31 UTC, marsam requested changes
please disable libvmaf for ffmpeg-full on darwin

```diff
diff --git i/pkgs/top-level/all-packages.nix w/pkgs/top-level/all-packages.nix
index 70bd668e4af..7cb69f15a40 100644
--- i/pkgs/top-level/all-packages.nix
+++ w/pkgs/top-level/all-packages.nix
@@ -10802,6 +10802,7 @@ in
     game-music-emu = if stdenv.isDarwin then null else game-music-emu;
     libjack2 = if stdenv.isDarwin then null else libjack2;
     libmodplug = if stdenv.isDarwin then null else libmodplug;
+    libvmaf = if stdenv.isDarwin then null else libvmaf;
     openal = if stdenv.isDarwin then null else openal;
     libmfx = if stdenv.isDarwin then null else intel-media-sdk;
     libpulseaudio = if stdenv.isDarwin then null else libpulseaudio;
```
Besides that, LTGM

2019-10-15 05:31 UTC, marsam commented on pkgs/development/libraries/libvmaf/default.nix
> +
I think you need to add:
```nix
  postFixup = ''
    substituteInPlace "$dev/lib/pkgconfig/libvmaf.pc" \
      --replace "includedir=/usr/local/include" "includedir=$dev"
  '';
```
for pkgconfig to find libvmaf

2019-10-15 05:31 UTC, marsam commented on pkgs/development/libraries/libvmaf/default.nix
> +    description = "Perceptual video quality assessment based on multi-method fusion (VMAF).";
description [should not include a period at the end](https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes):
```suggestion
    description = "Perceptual video quality assessment based on multi-method fusion (VMAF)";
```

2019-10-22 17:36 UTC, cfsmp3 commented
@marsam sorry for the delay in fixing these things, I've been away a few days. All done.

2019-10-23 00:30 UTC, marsam commented
@GrahamcOfBorg build libvmaf ffmpeg-full

2019-10-25 00:36 UTC, cfsmp3 commented
@marsam if it looks good, could you merge? thanks

2019-10-25 13:45 UTC, marsam commented
Sorry for the delay. I've disabled libvmaf for aarch64, I hope you don't mind

@GrahamcOfBorg build libvmaf ffmpeg-full

2019-10-25 14:08 UTC, marsam commented
@GrahamcOfBorg buil ffmpeg-full

2019-10-25 14:09 UTC, marsam commented
@GrahamcOfBorg build ffmpeg-full

2019-10-25 14:11 UTC, merged