pythonPackages.pySMART_smartx: init at 0.3.10
NixOS/nixpkgs pull request #70927
Opened 2019-10-10 18:44 UTC by marenz2569

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-10-10 21:55 UTC, risicle commented
Two problems:

1. This package seems to implicitly depend on `smartctl` being present in the user's `PATH`. To get it properly bound to its dependencies it'll probably require doing a bit of string replacement in the source looking for places it just does a `Popen('smartctl ...`. There are a few of them.

2. Tests don't actually run. Tests require pytest and will probably need a custom `checkPhase` `cd`'ing into `pySMART/test` and running `pytest`.

2019-10-15 18:11 UTC, FRidh requested changes

2019-10-15 18:11 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +  pySMART_smartx = callPackage ../development/python-modules/pySMART_smartx { };
the attribute name needs to be a normalized name, so `pysmart-smartx`.

2019-10-15 18:11 UTC, FRidh commented on pkgs/development/python-modules/pySMART_smartx/default.nix
> +  pname = "pySMART.smartx";
use normalized name here as well

2019-10-15 18:11 UTC, FRidh commented on pkgs/development/python-modules/pySMART_smartx/default.nix
> +    inherit pname version;
and here `pname = "pySMART.smartx"`;

2022-05-15 13:55 UTC, closed without merging