pyscroll: init at 2.19.2
NixOS/nixpkgs pull request #71257
Opened 2019-10-16 20:55 UTC by geistesk

###### Motivation for this change
Add the [pyscroll](https://github.com/bitcraft/pyscroll) library

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-10-17 00:15 UTC, jonringer reviewed
please pull from github so that we can have some tests, just unittests are good  :)

Unfortunately you'll have to match the date to a commit to figure out the version github, as they didn't use a tag/release mechanism there.

2019-10-17 00:15 UTC, jonringer commented on pkgs/development/python-modules/pyscroll/default.nix
> +  meta = {
```suggestion
  meta = with lib; {
```

2019-10-17 00:15 UTC, jonringer commented on pkgs/development/python-modules/pyscroll/default.nix
> +    license = lib.licenses.lgpl3;
```suggestion
    license = licenses.lgpl3;
```

2019-10-17 00:15 UTC, jonringer commented on pkgs/development/python-modules/pyscroll/default.nix
> +    maintainers = with lib.maintainers; [ geistesk ];
```suggestion
    maintainers = with maintainers; [ geistesk ];
```

2019-10-17 15:19 UTC, jonringer commented
I would focus on just unit tests, if they make the distinction.

2019-10-17 15:45 UTC, geistesk commented
I have opened an issue regarding the failing tests in the upstream repository https://github.com/bitcraft/pyscroll/issues/34

2020-02-09 09:40 UTC, FRidh approved these changes
Looks good, merge conflict needs to be resolved though.

2020-02-09 09:40 UTC, FRidh requested changes
Ah, right, the tests...

2020-06-22 11:28 UTC, mweinelt commented
Seems like the upstream has put work into the tests. Can you give it another try @geistesk?

2020-07-19 11:09 UTC, closed without merging