Fix/clean up various ibus-engines
NixOS/nixpkgs pull request #71442
Opened 2019-10-20 14:11 UTC by jtojnar

Closes: https://github.com/NixOS/nixpkgs/issues/68837

2019-10-20 14:56 UTC, laMudri commented
Are these changes relevant to any other IBus input methods?

2019-10-20 15:02 UTC, jtojnar commented
Yes, all input methods should be checked and updated. I already did this in typing booster and some other in the past. Need to run now, will try to continue during the week.

Also did not test this other than by running the setup execs on non-ibus system.

2019-11-07 22:35 UTC, jtojnar commented
The installed tests seem to be failing at the moment:

```
machine: must succeed: gnome-desktop-testing-runner  -d '/nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/share'
machine #
machine # (/nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/libexec/installed-tests/flatpak/ibus-engine-switch:1200): IBUS-CRITICAL **: 22:23:28.055: ibus_bus_call_sync: assertion 'ibus_bus_is_connected (bus)' failed
machine # [   20.040629] do_trap: 1 callbacks suppressed
machine # [   20.040632] traps: ibus-engine-swi[1200] trap int3 ip:7fac2e81dc75 sp:7ffcabaebfc0 error:0 in libglib-2.0.so.0.6200.1[7fac2e7e4000+80000]
machine # [   19.949938] systemd[1]: Created slice system-systemd\x2dcoredump.slice.
machine # [   19.961307] systemd[1]: Started Process Core Dump (PID 1202/UID 0).
machine # [   20.541447] gnome-desktop-testing-runner[1198]: FAIL: flatpak/ibus-engine-switch.test (Child process killed by signal 5)
machine # [   20.566825] systemd-coredump[1203]: Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such process
machine # [   20.573043] systemd-coredump[1203]: Process 1200 (ibus-engine-swi) of user 0 dumped core.
machine # [   20.593256] systemd[1]: systemd-coredump@0-1202-0.service: Succeeded.
machine # (/nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/libexec/installed-tests/flatpak/ibus-inputcontext-create:1205): GLib-GIO-CRITICAL **: 22:23:28.748: g_dbus_connection_call_internal: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
machine #
machine # [   20.734501] traps: ibus-inputconte[1205] trap int3 ip:7ff194fdfc75 sp:7ffe10edcdd0 error:0 in libglib-2.0.so.0.6200.1[7ff194fa6000+80000]
machine # [   20.646789] systemd[1]: Started Process Core Dump (PID 1211/UID 0).
machine # [   21.067351] gnome-desktop-testing-runner[1198]: FAIL: flatpak/ibus-inputcontext-create.test (Child process killed by signal 5)
machine # [   21.089903] systemd-coredump[1212]: Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such process
machine # [   21.095815] systemd-coredump[1212]: Process 1205 (ibus-inputconte) of user 0 dumped core.
machine # [   21.119609] systemd[1]: systemd-coredump@1-1211-0.service: Succeeded.
machine #
machine # (/nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/libexec/installed-tests/flatpak/ibus-factory:1214): IBUS-CRITICAL **: 22:23:29.292: ibus_factory_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
machine # [   21.279024] traps: ibus-factory[1214] trap int3 ip:7fb187562c75 sp:7fff009d63f0 error:0 in libglib-2.0.so.0.6200.1[7fb187529000+80000]
machine # [   21.203275] systemd[1]: Started Process Core Dump (PID 1221/UID 0).
machine # [   21.615804] gnome-desktop-testing-runner[1198]: FAIL: flatpak/ibus-factory.test (Child process killed by signal 5)
machine # [   21.641508] systemd-coredump[1222]: Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such process
machine # [   21.648878] systemd-coredump[1222]: Process 1214 (ibus-factory) of user 0 dumped core.
machine #
machine # (/nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/libexec/installed-tests/flatpak/ibus-configservice:1224): IBUS-CRITICAL **: 22:23:29.820: ibus_config_service_new: assertion 'G_IS_DBUS_CONNECTION (connection)' failed
machine # [   21.805027] traps: ibus-configserv[1224] trap int3 ip:7fb8a2223c75 sp:7ffcbe916da0 error:0 in libglib-2.0.so.0.6200.1[7fb8a21ea000+80000]
machine # [   21.674715] systemd[1]: systemd-coredump@2-1221-0.service: Succeeded.
machine # [   21.716889] systemd[1]: Started Process Core Dump (PID 1227/UID 0).
machine # [   22.160533] gnome-desktop-testing-runner[1198]: FAIL: flatpak/ibus-configservice.test (Child process killed by signal 5)
machine # [   22.186699] systemd-coredump[1231]: Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such process
machine # [   22.192996] systemd-coredump[1231]: Process 1224 (ibus-configserv) of user 0 dumped core.
machine # [   22.211027] systemd[1]: systemd-coredump@3-1227-0.service: Succeeded.
machine #
machine # ** (/nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/libexec/installed-tests/flatpak/ibus-bus:1233): WARNING **: 22:23:30.375: Not connected to ibus-daemon
machine # [   22.360749] traps: ibus-bus[1233] trap int3 ip:7f24f18a4c75 sp:7ffc54d9ceb0 error:0 in libglib-2.0.so.0.6200.1[7f24f186b000+80000]
machine # [   22.287361] systemd[1]: Started Process Core Dump (PID 1239/UID 0).
machine # [   22.801921] gnome-desktop-testing-runner[1198]: FAIL: flatpak/ibus-bus.test (Child process killed by signal 5)
machine # [   22.833272] systemd-coredump[1240]: Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such process
machine # [   22.839758] systemd-coredump[1240]: Process 1233 (ibus-bus) of user 0 dumped core.
machine # [   22.862416] systemd[1]: systemd-coredump@4-1239-0.service: Succeeded.
machine # [   22.877867] gnome-desktop-testing-runner[1198]: PASS: flatpak/ibus-keynames.test
machine # **
machine # IBUS:ERROR:ibusconfig.c:333:ibus_config_new_async: assertion failed: (G_IS_DBUS_CONNECTION (connection))
machine # [   22.979814] systemd[1]: Started Process Core Dump (PID 1250/UID 0).
machine # [   23.398322] gnome-desktop-testing-runner[1198]: FAIL: flatpak/ibus-config.test (Child process killed by signal 6)
machine # [   23.422856] systemd-coredump[1251]: Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such process
machine # [   23.430031] systemd-coredump[1251]: Process 1248 (ibus-config) of user 0 dumped core.
machine # [   23.444975] systemd[1]: systemd-coredump@5-1250-0.service: Succeeded.
machine # [   23.457119] gnome-desktop-testing-runner[1198]: PASS: flatpak/ibus-share.test
machine # [   23.747784] gnome-desktop-testing-runner[1198]: PASS: flatpak/ibus-util.test
machine #
machine # (/nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/libexec/installed-tests/flatpak/ibus-inputcontext:1261): IBUS-CRITICAL **: 22:23:31.933: ibus_bus_call_sync: assertion 'ibus_bus_is_connected (bus)' failed
machine # [   23.917626] traps: ibus-inputconte[1261] trap int3 ip:7ffab6a32c75 sp:7ffc73facc50 error:0 in libglib-2.0.so.0.6200.1[7ffab69f9000+80000]
machine # [   23.819277] systemd[1]: Started Process Core Dump (PID 1263/UID 0).
machine # [   24.215727] gnome-desktop-testing-runner[1198]: FAIL: flatpak/ibus-inputcontext.test (Child process killed by signal 5)
machine # [   24.241155] systemd-coredump[1264]: Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such process
machine # [   24.246436] systemd-coredump[1264]: Process 1261 (ibus-inputconte) of user 0 dumped core.
machine # [   24.264670] systemd[1]: systemd-coredump@6-1263-0.service: Succeeded.
machine # [   24.275318] gnome-desktop-testing-runner[1198]: PASS: flatpak/ibus-serializable.test
machine # [   24.308327] gnome-desktop-testing-runner[1198]: PASS: flatpak/ibus-registry.test
machine #
machine # ** (/nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/libexec/installed-tests/flatpak/ibus-compose:1280): CRITICAL **: 22:23:33.103: ibus-daemon is not running.
machine # [   25.087208] traps: ibus-compose[1280] trap int3 ip:7fde98839c75 sp:7ffd15501ce0 error:0 in libglib-2.0.so.0.6200.1[7fde98800000+80000]
machine # [   24.990614] systemd[1]: Started Process Core Dump (PID 1282/UID 0).
machine # [   25.001409] gnome-desktop-testing-runner[1198]: Executing: flatpak/ibus-compose-locales.test
machine # /nix/store/h95r0bpnf6iwqdrqadvjcvl4zkf08w9r-ibus-1.5.21-installedTests/libexec/installed-tests/flatpak/ibus-compose-locales: line 12:  1280 Trace/breakpoint trap   (core dumped) env $var $BUILDDIR/ibus-compose $SRCDIR $@
machine # ls: cannot access '*.cache': No such file or directory
machine # [   25.581960] systemd-coredump[1283]: Cannot resolve systemd-coredump user. Proceeding to dump core as root: No such proce [...]

2019-11-09 19:50 UTC, jtojnar commented
Apparently, https://github.com/fujiwarat/ibus-anthy/commit/5a9e4858f1a2b6cad02ef1d272fc5bed959ec0bf is not yet merged to a stable release, so no tests for ibus-anthy.

Managed to get `nixosTests.installed-tests.ibus` down to a single failing test case.

2019-11-12 02:52 UTC, jtojnar commented
I manually tested all the engines and they seem to work except for uniemoji and hangul.

Hopefully, the latest push fixes uniemoji but hangul does not seem to print any errors so more debugging will be required.

2019-12-05 23:00 UTC, jtojnar commented
ibus-hangul 1.5.3 seems to have fixed the issue of it stopping:

https://github.com/libhangul/ibus-hangul/releases/tag/1.5.3

Now the newly added NixOS tests are still partially failing but all the input methods seem to work in VM, so I just marked the test as broken and we can fix that later.

2019-12-05 23:06 UTC, jtojnar commented
The merging of the attrsets in f581284 is ugly but until we have https://github.com/NixOS/rfcs/pull/58, there is not much room for improvement.

2019-12-06 02:34 UTC, worldofpeace requested changes
Thanks, any test case would help with keeping up on these packages :+1: 
I went commit by commit, here's what I noticed.

* ibus-engines.libpinyin: 1.10.0 -> 1.11.1
Commit message needs indent fix.

* ibus-engines.anthy: clean up
I believe we should be using fetchFromGitHub for the fetch.
The commit msg has `* 1.5.11 switched from intltool to anthy`. probably meant gettext?

* ibus-engines.uniemoji: modernize
Let's use placeholder

* nixos/ibus: install D-Bus services
Not sure if I'm remembering this correctly, but could we get issues with multiple uses of
`programs.dconf.enable` in our modules?

2019-12-06 02:34 UTC, worldofpeace commented on pkgs/tools/inputmethods/ibus-engines/ibus-uniemoji/default.nix
> +
trail here

2019-12-06 02:41 UTC, worldofpeace commented
> The merging of the attrsets in f581284 is ugly but until we have [NixOS/rfcs#58](https://github.com/NixOS/rfcs/pull/58), there is not much room for improvement.

:+1: Yeah this RFC would make lots of code feel better.

2019-12-06 23:57 UTC, jtojnar commented
>     * ibus-engines.libpinyin: 1.10.0 -> 1.11.1
>       Commit message needs indent fix.

The nested list is intentional as it highlights important changes in each release. There are not many, though.

>     * ibus-engines.anthy: clean up
>       I believe we should be using fetchFromGitHub for the fetch.

I keep confusing it too but `archive` is the VCS tarball, `releases/download` are the uploaded artefacts.

>       The commit msg has `* 1.5.11 switched from intltool to anthy`. probably meant gettext?

Oops, fixed.
 
>     * ibus-engines.uniemoji: modernize
>       Let's use placeholder

:+1:
 
>     * nixos/ibus: install D-Bus services
>       Not sure if I'm remembering this correctly, but could we get issues with multiple uses of
>       `programs.dconf.enable` in our modules?

It should not matter unless someone sets it to something different than `true`. But then it would fail at runtime, so the conflict would be fine.

2019-12-07 02:57 UTC, worldofpeace approved these changes
LGTM :+1: 
Favorite refactor was `pkgs/data/misc/unicode-emoji/default.nix` and `pkgs/tools/inputmethods/ibus/default.nix`.

2019-12-07 11:10 UTC, merged