forge: add
NixOS/nixpkgs pull request #71486
Opened 2019-10-21 02:42 UTC by chessai

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-10-21 07:04 UTC, c0bw3b requested changes
Commit message and PR title

2019-10-21 07:04 UTC, c0bw3b commented on pkgs/development/libraries/forge/default.nix
> +    description = "An OpenGL interop library that can be used with ArrayFire or any other application using CUDA or OpenCL compute backend. The goal of Forge is to provide high performance OpenGL vis
Too long -> split it into a short `description` and a `longDescription`

2019-10-21 07:04 UTC, c0bw3b commented on pkgs/development/libraries/forge/default.nix
> +    homepage = https://arrayfire.com/ ;
```suggestion
    homepage = "https://arrayfire.com/";
```

2019-10-21 07:04 UTC, c0bw3b commented on pkgs/development/libraries/forge/default.nix
> +    maintainers = with stdenv.lib.maintainers; [ chessai ];
```suggestion
    maintainers = with maintainers; [ chessai ];
```

2019-10-21 07:04 UTC, c0bw3b commented on pkgs/development/libraries/forge/default.nix
> +    rev = "650bf611de102a2cc0c32dba7646f8128f0300c8";
You should fetch the `v${version}` tag from upstream repo

2019-10-21 07:21 UTC, chessai commented
applied all suggested changes and rebased

2019-10-21 16:40 UTC, c0bw3b commented on pkgs/development/libraries/forge/default.nix
> +    rev = "ref/tags/v${version}";
```suggestion
    rev = "v${version}";
```
I'm getting `unable to checkout` when testing locally

2019-10-21 16:41 UTC, c0bw3b commented on pkgs/development/libraries/forge/default.nix
> +    description = "An OpenGL interop library that can be used with ArrayFire or any other application using CUDA or OpenCL compute backend.";
(nitpick)
Manual recommends to remove any trailing dot in the short `description`

2019-10-29 12:10 UTC, chessai commented
remaining suggested changes added, rebased

2019-10-31 10:40 UTC, c0bw3b approved these changes
Result of `nix-review pr 71486` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>1 package were build:</summary>

  - forge
</details>

2019-10-31 10:40 UTC, merged

2019-10-31 11:33 UTC, chessai commented
thanks @c0bw3b!