perl5.28.2-Crypt-ECB: init at 2.21
NixOS/nixpkgs pull request #72214
Opened 2019-10-29 06:05 UTC by tekeri

###### Motivation for this change
Add a missing perl package.

This is my first contribution to the open source project. Feel free to teach me anything.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @???

2019-10-29 06:26 UTC, tekeri commented
EDIT: Changed maintainer @??? to @FRidh

2019-11-11 07:27 UTC, tekeri commented
cc @c0bw3b
Could you?

2019-11-11 12:00 UTC, tekeri commented
Fixed name

2019-11-11 13:06 UTC, stigtsp requested changes

2019-11-11 13:06 UTC, stigtsp commented on pkgs/top-level/perl-packages.nix
> +  };
`meta` is missing

2019-11-12 10:50 UTC, tekeri commented on pkgs/top-level/perl-packages.nix
> +  };
Added the description and the license

2019-11-15 12:31 UTC, stigtsp approved these changes
Looks good to me

Result of `nix-review pr 72214` [1](https://github.com/Mic92/nix-review)
<details>
  <summary>2 package were build:</summary>

  - perl528Packages.CryptECB
  - perl530Packages.CryptECB
</details>

2019-11-15 14:53 UTC, c0bw3b commented
@GrahamcOfBorg build perl528Packages.CryptECB perl530Packages.CryptECB

2019-11-15 14:57 UTC, c0bw3b approved these changes

2019-11-15 14:57 UTC, merged