dcpj1100dw-cups: init at 1.0.5-0
NixOS/nixpkgs pull request #72758
Opened 2019-11-04 02:57 UTC by puffnfresh

Unlike past Brother drivers, this contains binaries which reference
absolute /opt paths. I could have added an rpath hack to override
syscalls like stat but I decided the driver should just run in a
simple FHS environment. Works great for me.

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2021-01-18 11:33 UTC, SuperSandro2000 requested changes

2021-01-18 11:33 UTC, SuperSandro2000 commented on pkgs/misc/cups/drivers/dcpj1100dw/default.nix
> +  phases = [ "installPhase" ];
```suggestion
```

2021-01-18 11:33 UTC, SuperSandro2000 commented on pkgs/misc/cups/drivers/dcpj1100dw/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2022-03-17 02:13 UTC, puffnfresh commented
This worked for me for a while but I think it's now a bit broken and I haven't had time to fix it up.

2022-03-17 02:13 UTC, closed without merging