python: npyscreen: init at 4.10.5
NixOS/nixpkgs pull request #72948
Opened 2019-11-06 22:38 UTC by 0x4A6F

###### Motivation for this change
Add python module for tui applications. (e.g. [signal-curses](https://github.com/jwoglom/signal-curses))

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-11-06 23:11 UTC, jonringer commented on pkgs/development/python-modules/npyscreen/default.nix
> +  doCheck = false;
if tests aren't bundled with the pypi tarball, please grab from github https://github.com/npcole/npyscreen.

Tests are crucial to ensure that the package still works. You can disable the tests which don't work well within a sandbox

2019-11-07 06:37 UTC, vyp requested changes

2019-11-07 06:37 UTC, vyp commented on pkgs/development/python-modules/npyscreen/default.nix
> +    license = licenses.bsd3;
```suggestion
    license = licenses.bsd2;
```

https://bitbucket.org/npcole/npyscreen/src/default/LICENCE

2020-01-26 01:18 UTC, Profpatsch commented
(triage) any updates?

2020-05-23 08:25 UTC, doronbehar commented
> (triage) any updates?

I think not. Closing.

2020-05-23 08:25 UTC, closed without merging