Initial stab at making X11 a configurable dependency of intel-media-drivers
NixOS/nixpkgs pull request #73277
Opened 2019-11-12 10:43 UTC by robashton

###### Motivation for this change

Issue #73236

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @jfrankenau ?

2020-03-04 08:18 UTC, doronbehar commented
@vcunat could you review this please?

2020-03-04 08:18 UTC, doronbehar approved these changes

2020-07-12 13:12 UTC, primeos requested changes
Sorry about the delay.

Unfortunately I cannot test this easily as I'm on Wayland but the idea and diff LGTM with my proposed changes (not tested, might contain syntax errors). Could you apply them (if you agree with the changes) and give it a final test before we merge this PR?

2020-07-12 13:12 UTC, primeos commented on pkgs/development/libraries/intel-media-driver/default.nix
> +  postFixup = stdenv.lib.optional enableX11 ''
```suggestion
  postFixup = stdenv.lib.optionalString enableX11 ''
```

Because `optional` is for lists.

2020-07-12 13:49 UTC, robashton commented
I don't have the knowledge/experience to disagree with anything! I'll pull latest tomorrow and make the appropriate change and see what happens  :)

2020-07-12 13:51 UTC, vcunat commented
I _think_ nowadays the generic `packageOverrides` mechanism is preferred to `nixpkgs.config` for this purpose, though it's a bit more chatty and I'm not aware of this preference being written down anywhere.

2021-01-08 16:06 UTC, primeos approved these changes
I decided to finalize this by myself to get this merged/done. Cannot verify if this fixes the other issue but the diff suggests it and I briefly tested that this does still work with mpv on Wayland.

2021-01-08 16:06 UTC, merged