nixos/xserver:services.xserver.xkbOptions is now commas
NixOS/nixpkgs pull request #73394
Opened 2019-11-14 14:11 UTC by pasqui23

###### Motivation for this change
Fixes https://github.com/NixOS/nixpkgs/issues/18646

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-11-17 09:11 UTC, rnhmjoj approved these changes
It doesn't break any functionality (see xkbvalidate) and makes the the option mergable. 👍

2019-11-17 09:48 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/68

2019-11-17 10:43 UTC, timokau commented
This is a breaking change right? If so, maybe a changelog entry would be good.

Also as a minor nitpick: Please use the imperative in your commit message and talk about your intention, not the implementation details (`Make xkbOptions mergable` or similar).

CC @Ericson2314

2019-11-17 10:51 UTC, rnhmjoj commented
> This is a breaking change right? If so, maybe a changelog entry would be good.

No, it shouldn't break any existing module or config:

```
nix-repl> lib.types.str.check "a,b,c"    
true

nix-repl> lib.types.commas.check "a,b,c"
true
```

However if two modules set `xkbOptions` the values will be appended.

2019-11-17 10:58 UTC, timokau commented
Nice. I don't have much experience with NixOS modules, so thanks for clarifying. Since @Ericson2314 raised the initial issue and has merge rights himself, I think its best if he takes a look at this and ultimately merges it. If he's unresponsive for a couple of days feel free to ping me again.

2019-11-20 06:21 UTC, worldofpeace requested changes
@pasqui23 I'm seeing of a lot of your commits getting merged in like
`title:commit description`

when there's a missing space.

Can we do?
```
 nixos/xserver: xkbOptions is now commas
```

2019-12-22 02:25 UTC, nh2 commented
@pasqui23 Do you know how you can change the commit description the way @worldofpeace suggests? If not, `git commit --amend` is what you need.

2020-01-05 22:35 UTC, merged

2020-01-05 22:35 UTC, roberth commented
Thank you @pasqui23 !