helm3: init at 3.0.0 (help wanted)
NixOS/nixpkgs pull request #73916
Opened 2019-11-22 12:21 UTC by novoxudonoser

###### Motivation for this change
Add helm3 version. This version is made as a separate package because helm of version 3 is completely different from version 2 (no tiller, different templates and logic, different go dependencies ). From the user view, there is a need for both versions at the same time, cause most of Kubernetes clusters work with helm2, and new ones with helm3 at the same time. The `default.nix` is copied from the original helm package with modifications.

**Help wanted with rename output binary to helm3.**  I am new to nixpkgs (its my 2nd package, 1st isn't even merged yet). As said upper - both packages helm in nixpkgs (verions2) and helm3 needed. But with this `default.nix` this package produces executable output as 'helm' what conflicts with old helm package. I tried to rename output in different hooks like `fixupPhase`, and overriding `installPhase`  but with no success. I think its quite simple to do, but I can't google anything or find in mans. 
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

P.S. This is my first package build and first pr to nixpkgs, sorry if something wrong.

2019-12-01 19:22 UTC, rlupton20 commented
From the looks of the `buildGoPackage` implementation

https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/go-packages/generic/default.nix

you might want to try implementing a preInstall hook. I'm not terribly familiar with the infrastructure around building Go packages, so I might be a ways off!

2020-05-23 08:50 UTC, doronbehar requested changes

2020-05-23 08:50 UTC, doronbehar commented on pkgs/applications/networking/cluster/helm3/default.nix
> +    homepage = https://github.com/kubernetes/helm;
https://github.com/NixOS/rfcs/pull/45

Please quote the url.

2020-05-23 08:50 UTC, doronbehar commented on pkgs/applications/networking/cluster/helm3/default.nix
> +  modSha256 = "06599w4rvipb669vc5rj62k2kjakz2vmpp270carf204qbm5grk8";
Rebase on top of latest master and switch to `vendorSha256`.

2020-05-23 08:50 UTC, doronbehar commented on pkgs/applications/networking/cluster/helm3/default.nix
> +  goPackagePath = "helm.sh/helm/v3";
I _think_ this is not needed.

2020-05-23 08:50 UTC, doronbehar commented on pkgs/applications/networking/cluster/helm3/default.nix
> +  #goDeps = ./deps.nix;
Remove.

2020-05-23 08:55 UTC, doronbehar commented
> Help wanted with rename output binary to helm3. I am new to nixpkgs (its my 2nd package, 1st isn't even merged yet). As said upper - both packages helm in nixpkgs (verions2) and helm3 needed. But with this default.nix this package produces executable output as 'helm' what conflicts with old helm package. I tried to rename output in different hooks like fixupPhase, and overriding installPhase but with no success. I think its quite simple to do, but I can't google anything or find in mans.

Yea it's a bit hard to explain why this failed, and it's definitely not ideal that you've had this experience - it shouldn't be that hard and not intuitive + undocumented. However, I once saw this working for someone:

https://github.com/NixOS/nixpkgs/pull/86927/files#diff-2663ae5d05323a4fc069b6f0f3e664fbR20

Question: If:
> From the user view, there is a need for both versions at the same time, cause most of Kubernetes clusters work with helm2, and new ones with helm3 at the same time.

Then what's so wrong about having it colliding with the helm2 ?

2020-08-28 11:54 UTC, teto commented
dont we have already kubernetes-helm in the repo ? should we close this ?

2021-01-15 06:25 UTC, yurrriq commented
> should we close this ?

yep

2021-01-15 10:22 UTC, closed without merging