netease-cloud-music: init at 1.2.0
NixOS/nixpkgs pull request #74775
Opened 2019-12-01 09:28 UTC by Ninlives

###### Motivation for this change

Add package for the client of Netease Cloud Music service

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-12-03 07:26 UTC, Ninlives commented
What additional work should I make for this PR to be merged?

2019-12-07 17:45 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review-may-2019/3032/88

2019-12-07 19:01 UTC, Lassulus requested changes
there should also be an entry in `pkgs/top-level/all-packages.nix`

2019-12-08 06:30 UTC, Ninlives commented
@Lassulus Done. Sorry, I think I accidentally discarded some commits when trying to squash -_-||

2019-12-08 10:17 UTC, Lassulus approved these changes
tested with nix-review, seems to work, but I can't read anything

2019-12-08 10:17 UTC, merged