pam_gnupg: init at 363a50820fc00d6af6f6c01b87bacab51b67cda7
NixOS/nixpkgs pull request #75064
Opened 2019-12-05 21:31 UTC by dawidsowa

###### Motivation for this change
This pull request adds [pam_gnupg](https://github.com/cruegge/pam-gnupg), which allows unlocking GnuPG keys at login.
###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-12-05 22:32 UTC, prusnak requested changes

2019-12-05 22:32 UTC, prusnak commented on pkgs/os-specific/linux/pam_gnupg/default.nix
> +  rev = "363a50820fc00d6af6f6c01b87bacab51b67cda7";
this should read:

```
pname = "pam_gnupg";
version = "unstable-2019-10-25";
```

2019-12-05 22:32 UTC, prusnak commented on pkgs/os-specific/linux/pam_gnupg/default.nix
> +    inherit rev;
```
rev = "b2bd2b4f2650cce1bf628413089128721749578e";
```
and change the hash below

2020-01-09 04:22 UTC, ahesford commented
I didn't see this before submitting my own PR [#77002 ](https://github.com/NixOS/nixpkgs/pull/77002) to do the same thing. In addition to a new package, my contribution modifies the NixOS pam.nix module to properly incorporate pam_gnupg.so into the service files; otherwise, the package will not be usable to unlock GPG keys.

2020-01-27 01:25 UTC, closed without merging