hqemu: init at 2.5.2
NixOS/nixpkgs pull request #75705
Opened 2019-12-15 19:08 UTC by risicle

###### Motivation for this change
hqemu (http://csl.iis.sinica.edu.tw/hqemu/) is an interesting research project that grafts LLVM on to qemu's TCG binary translation, allowing it to optimize hotspots. I've managed to get some pretty good results from it, tripling execution speeds in some of my tests.

Package is heavily based on the qemu one, with some features removed and disabled for darwin - I get the feeling linux is the only host that has ever seen any attention.

Also note it has `knownVulnerabilities` set because it's not as though this is a security-maintained application, so isn't really appropriate for production use.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nix-review --run "nix-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2020-02-23 17:51 UTC, doronbehar approved these changes

2020-07-19 16:40 UTC, typetetris commented
Looks like a qemu derivative work, which would be GPL licensed. Don't know if the content of `COPYRIGHT` in the tarball is compatible with GPL.

2020-07-19 16:55 UTC, risicle commented
That's a very good point - hadn't noticed that. Do we have a "license: unclear"?

2020-07-20 05:24 UTC, typetetris commented
I don't think there is `license: unclear`. Maybe try to get the upstream authors to use something more clear?

2020-07-20 17:26 UTC, risicle commented
The upstream project is basically an academic paper and it doesn't seem to really be maintained anymore. The license sounds like one of those "university ip policy" disclaimers and I don't see much hope in getting clarity from "upstream".

2020-12-03 18:57 UTC, prusnak commented
@risicle do you still want to get this in?

2020-12-03 19:02 UTC, risicle commented
Well, the latest status is I'm unclear hqemu's license

2021-06-03 06:16 UTC, doronbehar commented
I think it'd be OK to add this package to NixOS, with the `unfree` license, if upstream doesn't say differently.

2021-06-03 10:38 UTC, SuperSandro2000 requested changes
@ofborg eval

2021-06-03 10:38 UTC, SuperSandro2000 commented on pkgs/applications/virtualization/hqemu/default.nix
> +with stdenv.lib;
```suggestion
with lib;
```

2021-06-03 10:38 UTC, SuperSandro2000 commented on pkgs/applications/virtualization/hqemu/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-06-03 19:34 UTC, risicle commented
TBH I think I'm going to close this PR because I don't want to have to maintain this, or even keep its list of known vulnerabilities up to date. I won't delete the branch, because this at least serves a purpose as a piece of software archaeology - a project that's tricky to build that at least now has a "known good" point in time that it can be reliably built.

2022-12-18 08:34 UTC, Mic92 commented
Closing because of lack of activity from the author. Please re-open if you plan to work on this.

2022-12-18 08:34 UTC, closed without merging