bitwig studio 3.0.3 -> 3.1.1
NixOS/nixpkgs pull request #76384
Opened 2019-12-24 11:12 UTC by bfortz

##### Motivation for this change
Upgrade to the latest version

###### Things done
Fixed dependencies; switched (temporarily) to the provided java engine because it is ahead and incompatible with the system one.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @michalrus @mrVanDalo

2019-12-25 05:27 UTC, mrVanDalo commented
@bfortz I just saw it, don't have time today (but tomorrow) to review it. You changed the package for bitwig 1 2 and 3. I don't know if that is intentional, all of theses versions need to work though.

2019-12-25 23:28 UTC, mrVanDalo requested changes
```
nix-review pr 76384
$ git fetch --force https://github.com/NixOS/nixpkgs master:refs/nix-review/0 pull/76384/head:refs/nix-review/1
remote: Enumerating objects: 288, done.
remote: Counting objects: 100% (288/288), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 415 (delta 280), reused 280 (delta 280), pack-reused 127
Receiving objects: 100% (415/415), 109.15 KiB | 614.00 KiB/s, done.
Resolving deltas: 100% (306/306), completed with 151 local objects.
From https://github.com/NixOS/nixpkgs
   dcd5be4af6a..5dc7050bd66  master               -> refs/nix-review/0
 + 6bff3d8be59...89e4412e9bb refs/pull/76384/head -> refs/nix-review/1  (forced update)
$ git worktree add /home/palo/.cache/nix-review/pr-76384/nixpkgs 5dc7050bd6626bbedc3716e3912c0eeedb7149a5
Preparing worktree (detached HEAD 5dc7050bd66)
Updating files: 100% (20550/20550), done.
HEAD is now at 5dc7050bd66 Merge pull request #75400 from nand0p/ethminer-v18
$ git merge --no-commit 89e4412e9bba0c6533c458dbcc58f10709bb50ff
Automatic merge went well; stopped before committing as requested
$ nix build --no-link --keep-going --max-jobs 4 --option build-use-sandbox true -f /home/palo/.cache/nix-review/pr-76384/build.nix
warning: ignoring the user-specified setting 'sandbox', because it is a restricted setting and you are not a trusted user
warning: unable to download 'https://cache.nixos.org/nar/06lwzzaqaw5pyi9c9hwinciq0z7m9h26fyjcg2jxhrw8zn0r3ypi.nar.xz': HTTP error 200 (curl error: Timeout was reached); retrying from offset 22084587 in 312 ms
builder for '/nix/store/pxha5ssg471f9sp7ksyyfqqhk7dgj62k-bitwig-studio-1.3.16.drv' failed with exit code 1; last 10 log lines:
    libjvm.so -> found: /nix/store/70424c51b4nc4aj8yz9fwx96qk2nil9c-bitwig-studio-1.3.16/libexec/lib/jre/lib/amd64/server/libjvm.so
  setting RPATH to: /nix/store/70424c51b4nc4aj8yz9fwx96qk2nil9c-bitwig-studio-1.3.16/libexec/lib/jre/lib/amd64:/nix/store/70424c51b4nc4aj8yz9fwx96qk2nil9c-bitwig-studio-1.3.16/libexec/lib/jre/lib/amd64/server
  searching for dependencies of /nix/store/70424c51b4nc4aj8yz9fwx96qk2nil9c-bitwig-studio-1.3.16/libexec/lib/jre/lib/amd64/libjava_crw_demo.so
  searching for dependencies of /nix/store/70424c51b4nc4aj8yz9fwx96qk2nil9c-bitwig-studio-1.3.16/libexec/lib/jre/lib/amd64/libj2pkcs11.so
  searching for dependencies of /nix/store/70424c51b4nc4aj8yz9fwx96qk2nil9c-bitwig-studio-1.3.16/libexec/lib/jre/lib/amd64/libavplugin-54.so
    libgstreamer-lite.so -> found: /nix/store/70424c51b4nc4aj8yz9fwx96qk2nil9c-bitwig-studio-1.3.16/libexec/lib/jre/lib/amd64/libgstreamer-lite.so
    libgobject-2.0.so.0 -> found: /nix/store/p89djj12rg449dbmkfbcby5wilb9iyfy-glib-2.62.3/lib/libgobject-2.0.so.0
    libglib-2.0.so.0 -> found: /nix/store/p89djj12rg449dbmkfbcby5wilb9iyfy-glib-2.62.3/lib/libglib-2.0.so.0
    libavcodec.so.54 -> not found!
    libavformat.so.54 -> not found!
builder for '/nix/store/ib0va0kqjdknapjjpy7fcxnlfnnp13wv-bitwig-studio-2.5.drv' failed with exit code 1; last 10 log lines:
    libgstreamer-lite.so -> found: /nix/store/6acz7b5kp1vadd773xjgm7agx09hp410-bitwig-studio-2.5/libexec/lib/jre/lib/amd64/libgstreamer-lite.so
    libgobject-2.0.so.0 -> found: /nix/store/p89djj12rg449dbmkfbcby5wilb9iyfy-glib-2.62.3/lib/libgobject-2.0.so.0
    libglib-2.0.so.0 -> found: /nix/store/p89djj12rg449dbmkfbcby5wilb9iyfy-glib-2.62.3/lib/libglib-2.0.so.0
  setting RPATH to: /nix/store/6acz7b5kp1vadd773xjgm7agx09hp410-bitwig-studio-2.5/libexec/lib/jre/lib/amd64:/nix/store/p89djj12rg449dbmkfbcby5wilb9iyfy-glib-2.62.3/lib:/nix/store/p89djj12rg449dbmkfbcby5wilb9iyfy-glib-2.62.3/lib
  searching for dependencies of /nix/store/6acz7b5kp1vadd773xjgm7agx09hp410-bitwig-studio-2.5/libexec/lib/jre/lib/amd64/libavplugin-55.so
    libgstreamer-lite.so -> found: /nix/store/6acz7b5kp1vadd773xjgm7agx09hp410-bitwig-studio-2.5/libexec/lib/jre/lib/amd64/libgstreamer-lite.so
    libgobject-2.0.so.0 -> found: /nix/store/p89djj12rg449dbmkfbcby5wilb9iyfy-glib-2.62.3/lib/libgobject-2.0.so.0
    libglib-2.0.so.0 -> found: /nix/store/p89djj12rg449dbmkfbcby5wilb9iyfy-glib-2.62.3/lib/libglib-2.0.so.0
    libavcodec.so.55 -> not found!
    libavformat.so.55 -> not found!
cannot build derivation '/nix/store/aksqlhajl7kpk2f266527ljjj06pr6pw-env.drv': 2 dependencies couldn't be built
[4 built (2 failed), 68 copied (376.3 MiB), 97.0 MiB DL]
error: build of '/nix/store/aksqlhajl7kpk2f266527ljjj06pr6pw-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/76384
2 package failed to build:
bitwig-studio1 bitwig-studio2

1 package were build:
bitwig-studio

$ nix-shell /home/palo/.cache/nix-review/pr-76384/shell.nix
```

this pull request breaks `bitwig-studio1` and `bitwig-studio2`.
You have to overwrite or copy `bitwig-studio3.nix`

2019-12-26 06:03 UTC, mrVanDalo commented
@bfortz my private bitwig-studio3.nix looks like this :
```
{ stdenv, fetchurl, bitwig-studio2, xorg, ... }:

bitwig-studio2.overrideAttrs (oldAttrs: rec {
  name = "bitwig-studio-${version}";
  version = "3.1.1";

  src = fetchurl {
    url = "https://downloads.bitwig.com/stable/${version}/bitwig-studio-${version}.deb";
    sha256 = "1mgyyl1mr8hmzn3qdmg77km6sk58hyd0gsqr9jksh0a8p6hj24pk";
  };

  buildInputs = bitwig-studio2.buildInputs ++ [ xorg.libXtst ];

  installPhase = ''
    ${oldAttrs.installPhase}

    # recover commercial jre
    rm -f $out/libexec/lib/jre
    cp -r opt/bitwig-studio/lib/jre $out/libexec/lib
  '';
})
```

2019-12-26 06:37 UTC, Mic92 commented
Independent from this PR. Does someone still use/test the older versions in terms of compatibility with their linked dependencies?

2019-12-26 09:32 UTC, mrVanDalo commented
Independent from this PR. Does someone still use/test the older versions in terms of compatibility with their linked dependencies?

I do test the version 1 but I don't have a license for version 2. This is why I request changes on this pull-request.

2019-12-27 14:16 UTC, bfortz commented
@mrVanDalo sorry for messing up Version 1, I thought these changes would not break it. Anyway, I moved all changes to bitwig-studio3.nix and left bitwig-studio1.nix untouched with this new patch.

2019-12-27 21:43 UTC, mrVanDalo reviewed
Seems to be Ok. I'm not sure why you copied the dependencies for the buildInputs. Because this is an override of bitwig-studio1 you also depend on all its dependencies, so I don't see a benefit on putting them in there again.

2019-12-28 10:21 UTC, bfortz commented
There is an additional dependency (libXtst) that was not present in previous versions. And I had no clue how to just add this one to the set of dependencies imported from v1, so I copied everything...

2019-12-28 12:41 UTC, mrVanDalo commented
this should do the trick.
```
  buildInputs = oldAttrs.buildInputs ++ [ xorg.libXtst ];
```

2019-12-28 23:43 UTC, mrVanDalo approved these changes
Thank you.

2020-01-01 23:02 UTC, Lassulus approved these changes
tested with nix-review

2020-01-01 23:03 UTC, merged