safeclib: init at 08112019
NixOS/nixpkgs pull request #76451
Opened 2019-12-24 21:10 UTC by Beowulf0

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2019-12-26 21:44 UTC, doronbehar approved these changes

2020-06-24 21:20 UTC, Beowulf0 commented
still important to me

2020-11-28 23:06 UTC, SuperSandro2000 requested changes

2020-11-28 23:06 UTC, SuperSandro2000 commented on pkgs/development/libraries/safeclib/default.nix
> +    repo = "${pname}";
```suggestion
    repo = pname;
```

2020-11-28 23:06 UTC, SuperSandro2000 commented on pkgs/development/libraries/safeclib/default.nix
> +    maintainers = with stdenv.lib.maintainers; [ ];
Please add yourself as a maintainer.

2020-11-28 23:49 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 76451` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>safeclib</li>
  </ul>
</details>

2021-06-03 06:35 UTC, doronbehar commented
@Beowulf0 please address the review.

2022-05-01 23:06 UTC, closed without merging