graalvm8: use custom mercurial
NixOS/nixpkgs pull request #76903
Opened 2020-01-03 21:48 UTC by eraserhd

###### Motivation for this change

Commit 88a473fc upgraded mercurial, made it use python3, and removed
support for hg-git, breaking graalvm8.  Since hg-git does not
officially support python3 or the new version of mercurial, this
patch adds back the old version of mercurial, used only by the
graalvm build.

Closes #76427.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @eelco @volth @hlolli

@hlolli I assume the 19.2.1 Graal PR will need to be updated as well?

2020-01-04 01:56 UTC, eraserhd commented
oh, good idea.  I’ll update it in a little bit.

On Fri, Jan 3, 2020 at 7:00 PM volth <notifications@github.com> wrote:

> *@volth* approved this pull request.
>
> I'd better keep mercurial_4 next to mercurial_5 than in graalvm's dir.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/76903?email_source=notifications&email_token=AABD6VHCE72HIREKZPTMUM3Q37GQFA5CNFSM4KCSJBQ2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCQVFWZQ#pullrequestreview-338320230>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AABD6VCMRCDAGQ7HDGNSCYLQ37GQFANCNFSM4KCSJBQQ>
> .
>

2020-01-04 04:09 UTC, eraserhd commented
Alright, made it `mercurial4_9`, changed the PR title and fixed up the commits.

2020-01-04 15:22 UTC, FRidh requested changes

2020-01-04 15:22 UTC, FRidh commented on pkgs/top-level/all-packages.nix
> +  mercurial4_9 = callPackage ../applications/version-management/mercurial/4.9.nix {
`mercurial_4`

2020-01-04 15:22 UTC, FRidh commented on pkgs/applications/version-management/mercurial/4.9.nix
> +    maintainers = [ stdenv.lib.maintainers.eelco ];
Will you maintain this one instead?

2020-01-04 22:41 UTC, eraserhd commented on pkgs/applications/version-management/mercurial/4.9.nix
> +    maintainers = [ stdenv.lib.maintainers.eelco ];
Sure.

2020-01-04 22:43 UTC, eraserhd reviewed
Fixed up.

2020-01-06 18:23 UTC, merged

2021-07-01 04:15 UTC, Artturin commented
any reason you did
```
, mercurialSrc ? fetchurl rec {
    meta.name = "mercurial-${meta.version}";
    meta.version = "4.9.1";
    url = "https://mercurial-scm.org/release/${meta.name}.tar.gz";
    sha256 = "0iybbkd9add066729zg01kwz5hhc1s6lhp9rrnsmzq6ihyxj3p8v";
  }
```
?  #128843