run: init at 0.7.0
NixOS/nixpkgs pull request #77081
Opened 2020-01-06 14:25 UTC by rawkode

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-01-06 14:34 UTC, Br1ght0ne requested changes
Besides the hash mismatch, LGTM

2020-01-06 14:34 UTC, filalex77 commented on pkgs/development/tools/run/default.nix
> +    sha256 = "04p112ciyn1zc86is49rjdvv0a0vbiyhqbhqr468f4iz3ifmfis5";
Having a hash mismatch (double-checked with `nix-prefetch-github --rev v0.7.0 TekWizely run`)

```
hash mismatch in fixed-output derivation '/nix/store/yxv3d0s2ckazjy21xh3m0xla3hi11ind-source':
  wanted: sha256:04p112ciyn1zc86is49rjdvv0a0vbiyhqbhqr468f4iz3ifmfis5
  got:    sha256:0365nvsqrlagrp08sifbdk3rgy7r4hmp3sx5zhizamadfcj2fsv6
```

```suggestion
    sha256 = "0365nvsqrlagrp08sifbdk3rgy7r4hmp3sx5zhizamadfcj2fsv6";
```

2020-01-06 14:44 UTC, Br1ght0ne approved these changes
```
https://github.com/NixOS/nixpkgs/pull/77081
1 package built:
run
```

2020-01-06 16:02 UTC, markuskowa commented on pkgs/development/tools/run/default.nix
> +    homepage    = https://github.com/TekWizely/run;
```suggestion
    homepage    = "https://github.com/TekWizely/run";
```

2020-01-06 16:03 UTC, markuskowa commented
@GrahamcOfBorg build run

2020-01-06 17:39 UTC, misuzu approved these changes
Builds on macOS.

2020-01-11 08:19 UTC, merged

2022-07-03 01:10 UTC, TekWizely commented
TIL my Run project has had a nixpkg for over 2.5 years !

I would have loved a CC on this PR back then, as I would have updated the Installation section of my Readme to include this package.

I will be adding that now that I know it exists.

Q: Is there any way to get statistics on the installation / search count for the package?

Q: Is there an official channel for submitted updates?  Looks like the package has been updated to 0.7.2 but I've had a couple of releases since (and a new one coming).

Thanks for taking the time to make my project into a package - I'm really stoked to see it being accessible to more users!

-TW

---

cc: @rawkode

2022-07-03 07:46 UTC, nlewo commented
Q: Is there any way to get statistics on the installation / search count for the package?

We don't have any installation statistics. Moreoever, i don't think the search.nixos.org website exposes stats.

Q: Is there an official channel for submitting updates?

Here ;)
To contribute to nixpkgs (update a package for instance), we submit PR, such as the current one. You could find more details in the nixpkgs manual: https://nixos.org/manual/nixpkgs/stable/#submitting-changes-making-patches