pythonPackages.pytorch-lightning: init at 0.5.3.2
NixOS/nixpkgs pull request #77155
Opened 2020-01-07 00:29 UTC by tbenst

###### Motivation for this change
Add PyTorch Lightning, the lightweight PyTorch wrapper for ML researchers

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

###### Notify maintainers

cc @

2020-01-07 09:58 UTC, jonringer commented
unfortunately, pytorch is broken right now, so this doesn't build

2020-01-07 19:49 UTC, tbenst commented
No worries, can wait until the major python packages update is merged. It does build on my pull request branch (which is an old commit on master from Dec 12). Also, with [cherry-pick patches](https://github.com/tbenst/nixpkgs/commits/nix-data) we have this [building on latest nixpkgs unstable](https://hydra.nix-data.org/build/109).

2020-01-10 18:33 UTC, jonringer reviewed
otherwise LGTM

failures are from python38Packages.torch
```
[6 built (1 failed), 3 copied (9.1 MiB), 3.6 MiB DL]
error: build of '/nix/store/43mvmb2wnaqii07q1aqyz47jhxha43a4-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/77155
2 package failed to build:
python38Packages.pytorch-lightning python38Packages.test-tube

2 package built:
python37Packages.pytorch-lightning python37Packages.test-tube
```

2020-01-10 18:33 UTC, jonringer commented on pkgs/development/python-modules/pytorch-lightning/default.nix
> +    # maintainers = [ maintainers. ];
please add yourself as a maintainer

2020-01-10 18:33 UTC, jonringer commented on pkgs/development/python-modules/pytorch-lightning/default.nix
> +  #   coverage run --source pytorch_lightning -m py.test pytorch_lightning tests pl_examples -v --doctest-modules
you don't have to run all the tests
```suggestion
  py.test pytorch_lightning tests -k 'not this_network_test'
```

2020-02-04 18:24 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/allow-internet-access-during-checkphase/5754/1

2020-02-16 06:11 UTC, jonringer commented
please squash fix-ups

2020-02-16 06:22 UTC, tbenst commented
Squashed, building overnight. Likely need to exclude additional tests that require internet

2020-05-23 09:52 UTC, doronbehar requested changes
nixpkgs-review fails with:

```
builder for '/nix/store/hpb8g409pf92l2zg1hwz6i9bkzin73r7-python3.7-pytorch-lightning-0.5.3.2.drv' failed with exit code 4; last 10 log lines:
  running install tests
  ============================= test session starts ==============================
  platform linux -- Python 3.7.7, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /nix/store/2dcsn57cgaxs92ha5swihrab0g3l2h6g-python3-3.7.7/bin/python3.7
  cachedir: .pytest_cache
  rootdir: /build/source, inifile: setup.cfg
  collected 0 items                                                              
  
  ============================ no tests ran in 0.00s =============================
  ERROR: file not found: test_running_test_pretrained_model
  
builder for '/nix/store/yray8z3h8lw93zsb5fb3c330zbrcqqzv-python3.8-pytorch-lightning-0.5.3.2.drv' failed with exit code 4; last 10 log lines:
  running install tests
  ============================= test session starts ==============================
  platform linux -- Python 3.8.2, pytest-5.3.5, py-1.8.1, pluggy-0.13.1 -- /nix/store/081w0sp7jnh33548cihj3a9y9jpn9b3s-python3-3.8.2/bin/python3.8
  cachedir: .pytest_cache
  rootdir: /build/source, inifile: setup.cfg
  collected 0 items                                                              
  
  ============================ no tests ran in 0.00s =============================
  ERROR: file not found: test_running_test_pretrained_model
  
cannot build derivation '/nix/store/6ybfn8l8xfcpdbpp7xi57yn6hrlybpk4-env.drv': 2 dependencies couldn't be built
[4 built (2 failed), 65 copied (1083.5 MiB), 202.0 MiB DL]
error: build of '/nix/store/6ybfn8l8xfcpdbpp7xi57yn6hrlybpk4-env.drv' failed
https://github.com/NixOS/nixpkgs/pull/77155
2 packages failed to build:
python37Packages.pytorch-lightning python38Packages.pytorch-lightning

2 packages built:
python37Packages.test-tube python38Packages.test-tube
```

2020-06-17 16:16 UTC, bcdarwin commented
Hi @tbenst -- any chance of updating this?  If not I'll make a new PR.

2020-06-17 21:12 UTC, tbenst commented
Hi @bcdarwin, would welcome the help! Please feel free to push to this PR or make a new PR, I believe the package is fully functional, and I've used it, but getting the tests running will require downloading pre-trained models & data ahead of time, and possibly patching the test code to avoid a download. If you want to chat realtime about this, feel free to ping me on the [nix-data slack channel](https://join.slack.com/t/nix-data/shared_invite/zt-ca8csgcz-N9Fyh~tnoZPY8x5lE_slFA).

2020-06-17 23:24 UTC, bcdarwin requested changes

2020-06-17 23:24 UTC, bcdarwin commented on pkgs/development/python-modules/test-tube/default.nix
> +    # maintainers = [ maintainers. ];
`maintainers` should be set

2020-06-17 23:24 UTC, bcdarwin commented on pkgs/development/python-modules/test-tube/default.nix
> +    homepage = https://github.com/williamFalcon/pytorch-lightning;
homepage URLs should be quoted now (in both packages)

2020-06-17 23:25 UTC, bcdarwin commented
I added a couple cosmetic comments inline, but I guess the main thing is updating the package (0.7.6 is out) so that it can work with Pytorch 1.5.

2020-06-17 23:42 UTC, tbenst commented
@bcdarwin, yes, updating will require adding several packages to nixpkgs: https://github.com/PyTorchLightning/pytorch-lightning/blob/master/environment.yml. In particular, trains, Neptune, wandb, and comet ML, although as I did in 0.5.3.2 we can potentially remove imports that are unused (I maintain mlflow but don’t have interest in the others). But than you for raising this point, doesn’t make sense to add tests right now.

In fact, I might propose that we skip tests on this package for now if others are ok with it, as the maintenance burden is extraordinarily high given the rate of releases, change in testing environment, and high utilization of network to download pre-trained models and datasets

2020-08-23 20:41 UTC, bcdarwin commented
Closing in favour of #96119.

2020-08-23 20:41 UTC, closed without merging