mynewt-newt: 1.3.0 -> 1.7.0, use buildGoModule
NixOS/nixpkgs pull request #77516
Opened 2020-01-11 14:04 UTC by Thra11

###### Motivation for this change
Update mynewt-newt to 1.7.0. Switch from legacy buildGoPackage to buildGoModule

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-01-11 15:58 UTC, Thra11 commented
Looks like 1.7.0 has a bug which prevents `newt upgrade` working with mcuboot (Unreleased workaround/fix is here https://github.com/apache/mynewt-newt/commit/7d4ef3fe65a9a83cc58e7bd973654ad235cc68bc). Not sure if we should patch it or just wait for a release...

2020-01-11 17:34 UTC, kalbasit commented
@Thra11 Does 1.7.0 work well with the patch applied? It's probably ok to update it with the patch if it works well.

2020-01-12 13:14 UTC, Thra11 commented
I had to cherry pick an additional commit for the fix to apply cleanly. Having done that, it builds and seems to work. I tried
1. Removing my existing mynewt installation
2. Switching to the 0.3.0 version of the package and running `newt install`
3. Switching to the patched 0.7.0 version of the package and running `newt upgrade`
It seems to have worked ok, where the unpatched version failed.

2020-01-12 17:48 UTC, kalbasit approved these changes

2020-01-28 23:52 UTC, marsam requested changes

2020-01-31 17:59 UTC, Thra11 commented on pkgs/tools/package-management/mynewt-newt/default.nix
> +    ./0002-Mcuboot-hack-to-prevent-newt-upgrade-failure.patch
Done. Thanks for the review!

2020-02-01 02:25 UTC, kalbasit commented
@GrahamcOfBorg build mynewt-newt

2020-02-01 17:23 UTC, kalbasit approved these changes

2020-02-01 17:24 UTC, merged