hfsutils: init at 3.2.6-14
NixOS/nixpkgs pull request #77866
Opened 2020-01-17 05:10 UTC by dtzWill

###### Motivation for this change

HFS utilities.

* init at 3.2.6-14.  "-14" is debian patchset used.
* touch timestamp files to avoid autoconf
  after patches, which is good because that fails.
  (patches fix the generated files too so all good)
* hfsutils: fix installation commands, fix build

These are especially useful as hfsprogs long since
stopped supporting HFS (as did Apple).

(ours still do, only because they're so very very ancient ;)).

I tackle updating those in 88bf051a78dd774370fade57dbb268633861a34f
(and likely a PR coming shortly after this) but I'm not entirely sure
it's worth upgrading those or not.

But will probably PR it for visibility and in case that does seem
like a good idea to anyone :).

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
  - Superficially they appear okay :).
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-02-23 18:35 UTC, doronbehar commented on pkgs/tools/filesystems/hfsutils/default.nix
> +    # Debian packaging files, for the patches
Please tell us what do the patches fix.

2020-02-23 18:35 UTC, doronbehar commented on pkgs/tools/filesystems/hfsutils/default.nix
> +    for p in $(cat ../debian/patches/series); do
Isn't it possible to use the `patches` attribute instead of this?

2020-12-29 02:15 UTC, SuperSandro2000 requested changes
Please also address the other feedback.

2020-12-29 02:15 UTC, SuperSandro2000 commented on pkgs/tools/filesystems/hfsutils/default.nix
> +                '-DT "$(MANDEST)'
```suggestion
      --replace '"$(BINDEST)/."' '-Dt "$(BINDEST)"' \
      --replace '"$(MANDEST)' '-DT "$(MANDEST)'
```

2021-01-18 00:21 UTC, SuperSandro2000 commented
Closing because author did not address the review feedback in the last year.

2021-01-18 00:21 UTC, closed without merging