pythonPackages.braviarc-homeassistant: init at 0.3.7.dev0
NixOS/nixpkgs pull request #78014
Opened 2020-01-19 08:18 UTC by colemickens

#### Motivation for this change

DO NOT MERGE YET: Please see: https://github.com/home-assistant/home-assistant/issues/30964

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-01-28 10:51 UTC, colemickens commented
This is now ready for review. Please note this is a recent fork of the braviarc lib. I've linked a Home Assistant issue in the initial PR text that explains why this is being done.

2020-01-30 08:29 UTC, colemickens commented
More packaging changes incoming, do not merge for now.

2020-01-31 05:40 UTC, jonringer commented
when you create the PR, you should be able to select "create as draft"

2020-01-31 05:48 UTC, colemickens commented
@jonringer Yes, I'm sorry, I've done that with some. Unfortunately it seems to be a one-time choice.

2020-01-31 06:18 UTC, jonringer commented
> @jonringer Yes, I'm sorry, I've done that with some. Unfortunately it seems to be a one-time choice.

I know :), wish they could allow it to be changed

2020-03-27 23:14 UTC, colemickens commented
This is tested, working e2e with Home-Assistant after running `./parse-requirements.py`. I think it's ready for merge consideration. Would be nice to have it in for the next time HA gets updated so it will be included for the bravia plugin.

2020-03-28 06:54 UTC, Mic92 commented on pkgs/development/python-modules/bravia_tv/default.nix
> +  doCheck = false;
```suggestion
  doCheck = false;
  
  pythonImportsCheck = [ "bravia_tv" ];
```

2020-03-28 07:32 UTC, Mic92 commented
You can also update home-assistant to include this module in its component description.

2020-03-28 08:06 UTC, FRidh requested changes

2020-03-28 08:06 UTC, FRidh commented on pkgs/top-level/python-packages.nix
> +  bravia_tv = callPackage ../development/python-modules/bravia_tv { };
normalized names, so `bravia-tv`

2020-03-28 08:09 UTC, colemickens commented on pkgs/top-level/python-packages.nix
> +  bravia_tv = callPackage ../development/python-modules/bravia_tv { };
attribute name, directory, pname fixed.

2020-03-28 09:22 UTC, merged