morph: add openssh to buildInputs
NixOS/nixpkgs pull request #78107
Opened 2020-01-20 13:01 UTC by 1000101

###### Motivation for this change
Fixes #78106

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-01-20 14:06 UTC, johanot requested changes
openssh is not a build dependency of morph, thus this change will not fix the issue at hand. We either need to put openssh on morph' runtime PATH, or loosen the dependency check at morph startup (since openssh is really not needed at all for the `morph build`-subcommand.)

2020-01-20 14:08 UTC, flokli commented
@johanot is right - and I think morph should work fine for actions not requiring ssh (like `morph build`), but complain if we try to deploy without the `ssh` binary in `$PATH`.

2020-01-20 14:40 UTC, 1000101 commented
> @johanot is right - and I think morph should work fine for actions not requiring ssh (like `morph build`), but complain if we try to deploy without the `ssh` binary in `$PATH`.
Aaah, right, i'm closing this PR then. Sorry for the fuss!

Just for the reference: https://github.com/DBCDK/morph/issues/102

2020-01-21 14:18 UTC, mmahut commented
Until this is fixed upstream, we might want to add ```openssh``` as a runtime dependency.

2020-01-21 15:57 UTC, flokli commented
This won't magically add `openssh` to `$PATH`, though - the binary needs to be wrapped.

See how this is done with `borgbackup`.

2020-01-21 17:39 UTC, johanot commented
Yeah well. We have to agree on what we are actually fixing though? #78106 gives the example of `morph build` (build subcommand) failing because of openssh missing. This is obviously wrong, since morph can build machine expressions just fine without ever needing ssh.

I kinda feel that morph _shouldn't_ be upstream-wrapped with openssh, since it is possible to use morph as a standalone build tool, without ssh. But i _do_ agree that `morph build` should stop failing when openssh is missing on $PATH. See my proposed upstream PR regarding that issue: DBCDK/morph#103

2020-01-21 17:48 UTC, mmahut commented
If a program requires a dependency to work (in any use case), we as ```<nixpkgs>``` should ship it with that dependency.

If that dependency is too large, we can split it into different derivation (example that comes in mind is a server application with GUI support, such as bitcoin{,d}), but in case of morph the majority of use cases are going to use deploy anyway, so I feel it is okay to ship it with openssh as a dependency.

2020-01-22 05:21 UTC, andrew-d commented
FWIW, as someone that was trying out `morph` in a `nix-shell --pure` just now, I would expect that it'd be wrapped so that it "just worked" with SSH. A Go-based SSH implementation is neat, but makes e.g. using SSH keys on a smart card via the SSH agent more annoying, doesn't support everything in my `~/.ssh/config`, etc.

Very +1 to wrapping the binary.

2020-01-26 13:21 UTC, mmahut commented
Right, we are using morph with Trezor to hold our ssh keys and I'm not sure if the gossh will support that.

2020-01-26 13:22 UTC, merged