add missing kubelet dependency for docker container systemd services
NixOS/nixpkgs pull request #78313
Opened 2020-01-22 19:06 UTC by DavHau

###### Motivation for this change
Currently docker container systemd services generated by the option `config.docker-containers` can crash on startup when kubelet is not seeding docker images fast enough. 
I found zero documentation on how to preload docker images via nixos config. But from reading https://github.com/NixOS/nixpkgs/pull/49379 I guess the right way to do it in production is by using `services.kubernetes.kubelet.seedDockerImages` .
Therefore the systemd services of `config.docker-containers` should probably depend on kubelet and wait for it to start.

###### Things done
Extend systemd service in `virtualisation/docker-containers.nix` to depend also on `kubelet.service` in case kubelet is activated via `config.services.kubernetes.kubelet.enable`

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-01-23 08:25 UTC, nlewo requested changes
If I understand well, you would like to load Docker image in order to use them with the `docker-containers` module. There is currently nothing to do this and it seems to me all images used by `docker-containers` have to be fetched from an Docker registry.

In this context, I'm not in favor of adding a dependency to the kubelet service, just to load Docker images.

Instead, I think you could add a `seedDockerImage` option in the `docker-container` module and add some code to load this Docker image in the `ExecStartPre` script of the container systemd service (something similar to the kubelet module).

If you need to load Docker images for testing purpose, you could use the `dockerPreloader` module to speed up your tests since it avoids the Docker load at runtime.

2020-01-23 14:03 UTC, DavHau commented
Good points. I was not aware that loading docker images is so trivial that it can be done in a one liner and has nothing to do with kubelet at all.

But since `docker-containers.nix` creates an individual systemd service for each container and we might want to load multiple images in one go, i would not do the preloading inside these services but in a separated  `docker-images-preloader.service` and make the other services depend on that one.

So after this we would have:
 -  `options.docker-containers` to autorun containers 
 - `options.seed-docker-images` to preload docker images.

With having this, we could also remove `services.kubernetes.kubelet.seedDockerImages` and instead make the kubelet service depend on the new `docker-images-preloader service`. It does the exact same thing anyways and the options would be unnecessarily redundant

What do you think?

2020-01-24 08:35 UTC, nlewo commented
Why would you like to load all images in one go?
I think it would be nicer to let each container associated systemd service manage its own image. Suppose you are running several images and you want to update only one image: all containers would be restarted since they all depend on the same systemd service (the one in charge of loading images). However, if each container systemd service is in charge of loading the image it uses, when you update an image, only this container will be impacted.

Also, I think it would be easier to add a `execPreStart` in this module than creating a new module;)

2020-01-24 09:08 UTC, nlewo commented
Take a look at https://github.com/NixOS/nixpkgs/pull/78366 ;)

2020-01-24 12:34 UTC, mkaito commented
You can always mess with `systemd.services.docker-foo.preStart`, which is `types.lines` and will just append your stuff. However, for this use case, have a look at #78366.

I'm neutral on the changes proposed here, but they seem unnecessary.

2020-01-24 17:58 UTC, DavHau commented
Amazing! #78366 is exactly what i was looking for. This can be closed. Thanks!

2020-01-24 19:00 UTC, closed without merging