PBIS AD login integration
NixOS/nixpkgs pull request #78351
Opened 2020-01-23 10:34 UTC by tekeri

###### Motivation for this change
Bring Active Directory authentication to NixOS.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-01-25 13:05 UTC, aanderse requested changes
I've taken a first pass at review of your module. A number of my comments are just minor points, convention, etc... but there are a few material points I look forward to getting your feedback on. I will test this on one of my servers at some point.

Out of curiosity what are the benefits you saw in this solution compared to others available?

Thanks for contributing this module!

2020-01-25 13:05 UTC, aanderse commented on nixos/modules/services/security/pbis.nix
> +{ config, lib, pkgs, ... }:
I would encourage you to add yourself as a maintainer to this module, if you are interested in doing so.

2020-01-27 06:23 UTC, tekeri commented on nixos/modules/services/security/pbis.nix
> +            # ^ignore errors: pbis's stateful behavior (change PAM module and conf) cause some errors
Sadly, no.

2020-01-27 06:25 UTC, tekeri commented on nixos/modules/services/security/pbis.nix
> +        # This is evil but I could not find any workaround that
Less likely, as they are busy and cannot update their bundled dependencies even.
Instead, made `/opt/pbis` private to the service.

2020-01-27 06:27 UTC, tekeri commented on nixos/modules/services/security/pbis.nix
> +    systemd.services.lwsmd = {
Tried `DynamicUser` and found that
`chown("/var/lib/pbis/db", 0, 0) = -1 EPERM (Operation not permitted)`
... and it also create new user's home directory.

2020-01-27 06:38 UTC, tekeri commented
> Out of curiosity what are the benefits you saw in this solution compared to others available?

Compatibility. PBIS derives uid/gid from users' SID.
Pros: no need to manage IDs.
Cons: it feels like vendor lock-in when I consider uid/gid consistency across different systems or host-container.

2020-01-27 08:10 UTC, tekeri commented on nixos/modules/services/security/pbis.nix
> +        exec ${pbis}/bin/lwsmd --start-as-daemon
It did not work.

2020-01-27 12:25 UTC, aanderse commented
> Pros: no need to manage IDs.

Oh... you could add `map passwd uidNumber objectSid:S-1-5-21-3268520485-1580165246-4160084142` to `users.ldap.daemon.extraConfig` and have the same result. Is that the only reason?

2020-01-28 06:15 UTC, tekeri commented
It is not realistic to manage uids by hand every time people join or leave...
And pbis is needed to make NixOS as Ubuntu replacement.

2020-01-28 12:26 UTC, aanderse commented
@tekeri I think you misunderstand... what that configuration does is compute a **unique** `uid` for each and every user based on the users underlying `objectSid` from AD. That way you don't have to assign or manage a `uid` for anyone as all `uid` values are a calculated function, unique across all members, and consistent across all machines.

See https://www.markturner.net/2019/09/27/ad-ldap-authentication-on-linux-hosts/ for a good explanation.

2020-01-29 03:56 UTC, tekeri commented
@aanderse Umm.. I'm not sure that configuration utilize same hash function defined in pbis? https://github.com/BeyondTrust/pbis-open/blob/master/lwadtool/libadtool/ids.c#L183

2020-01-29 12:24 UTC, aanderse commented on nixos/modules/services/security/pbis.nix
> +            # ^ignore errors: pbis's stateful behavior (change PAM module and conf) cause some errors
:disappointed:

2020-01-29 12:25 UTC, aanderse commented
@tekeri I was just intending to show you that having a stable `uid` (and `gid`) is possible with other solutions. As far as the SID... https://serverfault.com/questions/851864/get-sid-by-its-objectsid-using-ldapsearch

2020-01-29 12:53 UTC, tekeri commented
@aanderse Thanks for the info. But I want to integrate NixOS into the existing network which is out of my control and using pbis there. uid inconsistency cause inconvenience with `rsync`, `ls` from container host, etc.
I've worked hard to avoid pbis and I'm still willing to migrate to any solution if it won't break.

2020-01-29 12:57 UTC, aanderse commented
@tekeri yeah, makes sense to me. I was just trying to provide some information in case it provided any value. I think you've done a very good job on this module so far, which I imagine wasn't easy given the constraints of the software.

I'm happy to give this a test after someone else (possibly @Infinisil?) provides some more review on this.

:+1:

2020-01-29 13:05 UTC, tekeri commented
@aanderse I'm happy to hear that, too.
Package is messy but I hope it should work like a charm :)

2020-04-01 09:56 UTC, tekeri commented
ping, just for remind 😃

2024-10-29 08:28 UTC, closed without merging