linuxPackages: 4.19 -> 5.4
NixOS/nixpkgs pull request #78713
Opened 2020-01-28 15:38 UTC by vcunat

###### Motivation for this change

It's a longterm version that has been out for quite some time:
5.4.15 and 5.5 are current.  I've been using it, so far I'm not aware
of any issues with it.

Feature freeze for the next NixOS release is in two weeks,
so now seems to be high time to decide the default kernel version.
https://discourse.nixos.org/t/nixos-20-03-feature-freeze/5655

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] N/A macOS
   - [ ] N/A other Linux distributions
- [x] (a few) Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested running NixOS with it.
   ~Tested execution of all binary files (usually in `./result/bin/`)~
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date  **FIXME**: if we agree with this, fixup release notes and possibly other docs.
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-01-28 15:40 UTC, vcunat commented
I suppose we should be good even if we stick with 4.19 for 20.03.  Details: EOL for 4.19 [on the web](https://www.kernel.org/category/releases.html) is only Dec 2020, but it seems likely to get extended (I think I have seen that somewhere) and that 20.03 is planned to EOL before that anyway.

2020-01-28 15:41 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/nixos-20-03-feature-freeze/5655/6

2020-01-28 15:54 UTC, mweinelt commented
I haven't had issues with the 5.4 series so far either, so I'd be happy if we could pick that, especially since it provides support for Intels AX200 wifi cards, present in most newer laptops.

2020-01-28 17:07 UTC, jonringer commented
I've been using 5.4 as well, and haven't experienced any issues.

2020-01-28 17:14 UTC, wkral commented
I'll add that I've had no problems with the 5.4 kernel on my laptop. In fact I've been using `linuxPackages_latest` for some time since the 4.20 kernel had some updates that benefited my hardware. So I think this update would help folks with newer hardware.

2020-01-28 17:24 UTC, Frostman commented
I'm running 5.4.x on my homelab (w/ ZFS) since the end of December without any issues.

2020-01-28 17:49 UTC, fpletz approved these changes
My AMD-based laptop only works with 5.0+ kernels and 5.4 finally fixed some lockups that could otherwise only mitigated with some weird kernel parameters.

Also have been running latest on different hardware and environment for quite some time. :+1:

2020-01-28 18:17 UTC, samueldr approved these changes
I was going to do the same, ensure we stick with the "current latest LTS at the moment of release" we've been doing.

2020-01-28 19:43 UTC, Ma27 reviewed
Just wanted to point out 5.4 behaves weird when using VRFs (just run the test from #78476 with `linuxPackages_5_4`). Apart from that, the kernel seems perfectly fine, using it on several setups, so overall :+1:

2020-01-28 22:06 UTC, jonringer approved these changes

2020-01-28 22:08 UTC, andir commented
@Ma27 
> Just wanted to point out 5.4 behaves weird when using VRFs (just run the test from #78476 with `linuxPackages_5_4`). 

If this is the same thing that @WilliButz showed me in Munich then you should probably file an upstream kernel issue about it.

Besides that I am also in favor of upgrading to this kernel as it has been working flawlessly on my systems for a while now.

2020-01-28 22:18 UTC, Ma27 commented
Yeah, I remeber that debugging session and I'm fairly certain that this is related. Let's see qhen I have sufficient time for investigation :)

2020-01-28 22:24 UTC, worldofpeace approved these changes
I also think we should do this :+1: 

cc @disassembler

2020-01-28 22:57 UTC, worldofpeace commented
Ahh I just remembered, there is this bug and I don't think fixes have been backported for it
* https://gitlab.freedesktop.org/drm/intel/issues/614

2020-01-29 00:10 UTC, yrashk commented
5.4 seems to have random freezes with an Intel (i915) driver. My system seems to be affected

https://bugzilla.redhat.com/show_bug.cgi?id=1780800
https://www.reddit.com/r/archlinux/comments/e7tb8i/intel_i915_random_freeze/
https://www.reddit.com/r/archlinux/comments/ed2ml8/latest_kernel_update_545_makes_my_pc_constantly/
https://linuxreviews.org/Linux_Kernel_5.5_Will_Not_Fix_The_Frequent_Intel_GPU_Hangs_In_Recent_Kernels

2020-01-29 00:30 UTC, worldofpeace commented
> 5.4 seems to have random freezes with an Intel (i915) driver. My system seems to be affected
> 
> https://bugzilla.redhat.com/show_bug.cgi?id=1780800
> https://www.reddit.com/r/archlinux/comments/e7tb8i/intel_i915_random_freeze/
> https://www.reddit.com/r/archlinux/comments/ed2ml8/latest_kernel_update_545_makes_my_pc_constantly/
> https://linuxreviews.org/Linux_Kernel_5.5_Will_Not_Fix_The_Frequent_Intel_GPU_Hangs_In_Recent_Kernels

Yeah, my aforementioned issue I believe is just one of the few mentioned.
The experience for (I believe certain?) Intel integrated GPU users is a problem.

2020-01-29 00:34 UTC, samueldr commented
(Something I wanted to write way before people chimed in about issues.)

Anyone's pet issue with the latest kernel is irrelevant to the question of changing the default, I believe. The previous LTS, 4.19, is still available. There will *always* be issues for a subset of users with different kernel versions.

Unless there were egregious regressions or bugs in the newer kernel, waiting until 20.09 is only punting the issue 6 months. There will not be a new LTS to move to in the next 6 months. 4.19 is slated for a December 2020 EOL.

Furthermore, sticking with an older release really hampers adoption on new devices, as new hardware is released, especially on laptops, it often becomes the case we need to point users towards the "new kernel" variant of the ISO.

Though, considering that intel iGPU issue, which I'm pretty sure I faced with 5.2 or 5.3 while test running it, it would be good to list this as an "errata" for the release, or something. It is bound to become a new common grievance.

2020-01-29 00:38 UTC, lovesegfault commented
I have issues with `5.4.x`, some Intel (`i915`) driver bug that causes a freeze. 
c.f. https://gitlab.manjaro.org/packages/core/linux54/issues/5
c.f. https://www.spinics.net/linux/fedora/fedora-users/msg494505.html

2020-01-29 00:47 UTC, worldofpeace commented
> (Something I wanted to write way before people chimed in about issues.)
> 
> Anyone's pet issue with the latest kernel is irrelevant to the question of changing the default, I believe. The previous LTS, 4.19, is still available. There will _always_ be issues for a subset of users with different kernel versions.
> 
> Unless there were egregious regressions or bugs in the newer kernel, waiting until 20.09 is only punting the issue 6 months. There will not be a new LTS to move to in the next 6 months. 4.19 is slated for a December 2020 EOL.
> 
> Furthermore, sticking with an older release really hampers adoption on new devices, as new hardware is released, especially on laptops, it often becomes the case we need to point users towards the "new kernel" variant of the ISO.
> 
> Though, considering that intel iGPU issue, which I'm pretty sure I faced with 5.2 or 5.3 while test running it, it would be good to list this as an "errata" for the release, or something. It is bound to become a new common grievance.

I agree fully and ref https://github.com/NixOS/nixpkgs/issues/69687, punting to another release is a practice that will achieve nothing. I'm pretty sure this particular issue is affecting a lot of people so it's really inevitable people to be aware of it, it just shouldn't be a discussion we're having to why we **shouldn't** upgrade the default.  But as you mentioned, something like an errata or anything is needed.

2020-01-29 01:53 UTC, eadwu commented
Another guy with iGPU issues with 5.4. Managed to regain a suitable system by disabling `picom` and while I still get rcs0 hangs sometimes, they all managed to be recovered. But yeah, 5.4 isn't in a really ideal spot for 5.4. 

Doesn't look like it'll be fixed in 5.4 currently though. Here's my sources,
https://bbs.archlinux.org/viewtopic.php?id=250765
https://gitlab.freedesktop.org/drm/intel/issues/673

2020-01-29 09:00 UTC, vcunat commented
It seems that Intel GPU problems are relatively common with 5.4, I'm afraid (just by looking at a few of the tickets and this thread).  I don't know, it's hard to estimate the overall ratio of fixes vs. regressions... I can imagine adding a line into release notes that iGPU users might want to override version to 4.19 or something, unless upstream mitigates most of the regressions before our release.

2020-01-30 18:42 UTC, samueldr commented
@disassembler, ideally we'd see a green tick from yourself too :).

@disassembler, @worldofpeace one of you hopefully can merge it :D.

2020-01-30 19:34 UTC, jonringer commented
I kind of find it ironic that 5.4 contains a bunch of amd fixes/support and intel regressions

2020-01-30 22:48 UTC, worldofpeace commented
> @disassembler, ideally we'd see a green tick from yourself too :).
> 
> @disassembler, @worldofpeace one of you hopefully can merge it :D.

I believe we need
> f we agree with this, fixup release notes and possibly other docs.

and the errata.

2020-01-30 22:48 UTC, worldofpeace requested changes
See above, I don't think we have any objections.

2020-01-31 15:02 UTC, vcunat commented
OK, I added an entry into release notes.  I don't feel strongly what it should look like; perhaps the release managers will want to consolidate the section somehow before release.

2020-01-31 18:57 UTC, samueldr approved these changes

2020-01-31 19:09 UTC, worldofpeace commented
> OK, I added an entry into release notes. I don't feel strongly what it should look like; perhaps the release managers will want to consolidate the section somehow before release.

Oh, trust that highlights section is going to be a beauty as long as I'm here :smile:

2020-01-31 19:09 UTC, worldofpeace approved these changes

2020-01-31 19:32 UTC, merged

2020-02-01 14:05 UTC, vcunat commented
Regressions:
 - [ ] https://hydra.nixos.org/job/nixos/unstable-small/nixos.tests.misc.x86_64-linux (blocking both channels)

_I expect to edit the post over time._

2020-02-02 01:57 UTC, worldofpeace commented
@vcunat opened https://github.com/NixOS/nixpkgs/issues/79063. I've also ported that test to python, PR incoming.

2020-02-05 17:07 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/january-2020-in-nixos/5771/1

2020-04-08 21:37 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/go-no-go-meeting-nixos-20-03-markhor/6495/19

2020-06-04 10:47 UTC, asymmetric commented
@worldofpeace should we mention the i915 issues in the release notes?