bs-platform: bump to 7.1.0
NixOS/nixpkgs pull request #79106
Opened 2020-02-02 18:52 UTC by anmonteiro

###### Motivation for this change
https://github.com/BuckleScript/bucklescript/pull/4139

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @turboMaCk

2020-02-02 18:54 UTC, anmonteiro commented on pkgs/development/compilers/bs-platform/build-bs-platform.nix
> +  dontConfigure = true;
I tracked down the issue that @bobzhang referred to in [this comment](https://github.com/NixOS/nixpkgs/pull/77726#discussion_r373833252).

Apparently running `node scripts/ninja.js config` will cause the build script to build the development version.

2020-02-02 19:21 UTC, anmonteiro commented
Looks like we can build bs-platform on aarch64 again. Thanks for your help @bobzhang!

2020-02-02 19:22 UTC, jonringer reviewed
commit msg should be:
```
bs-platform: 7.0.1 -> 7.1.0
```

2020-02-02 19:24 UTC, anmonteiro commented
Thanks, updated

2020-02-03 09:51 UTC, turboMaCk commented on pkgs/development/compilers/bs-platform/default.nix
> +    sha256 = "0p0ywb4cjpsrjq0if4s1bsnv9jdycd61r4ryndfzc50gngrpjbqr";
this fails for me:

```
fatal: reference is not a tree: a7f482243fabb38292b81b7bae9cefcb8076237f
Unable to checkout a7f482243fabb38292b81b7bae9cefcb8076237f from https://github.com/BuckleScript/bucklescript.git.
```

2020-02-03 09:54 UTC, turboMaCk commented
@anmonteiro 7.1.0 seems not to be released. Further more git commits of development version are changing so referencing those commits is not safe. We need to wait for the official release of 7.1.0 and commit that will stay in the master.

2020-02-03 09:54 UTC, turboMaCk requested changes
wait for 7.1.0 release

2020-02-03 10:14 UTC, turboMaCk requested changes
I recommend leaving bump of version out from this and merging it **as a fix for arm build**. If you chose to do so please change the commit message. @jonringer 's suggested name follows convention in case of updates but not if we leave it out.

2020-02-03 10:14 UTC, turboMaCk commented on pkgs/development/compilers/bs-platform/default.nix
> +  version = "7.1.0";
revert version bump:
```suggestion
  version = "7.0.1";
```

2020-02-03 10:14 UTC, turboMaCk commented on pkgs/development/compilers/bs-platform/default.nix
> +    rev = "a7f482243fabb38292b81b7bae9cefcb8076237f";
revert to old commit:

```suggestion
    rev = "52770839e293ade2bcf187f2639000ca0a9a1d46";
```

2020-02-03 10:14 UTC, turboMaCk commented on pkgs/development/compilers/bs-platform/default.nix
> +    sha256 = "0p0ywb4cjpsrjq0if4s1bsnv9jdycd61r4ryndfzc50gngrpjbqr";
revert checksum:
```suggestion
    sha256 = "0s7g2zfhshsilv9zyp0246bypg34d294z27alpwz03ws9608yr7k";
```

2020-02-03 19:07 UTC, turboMaCk approved these changes
LGTM thanks

2020-02-04 07:58 UTC, turboMaCk approved these changes

2020-02-04 08:11 UTC, jonringer commented on pkgs/development/compilers/bs-platform/build-bs-platform.nix
> +  dontConfigure = true;
do you mind leaving a comment, so we don't stumble upon this again
```suggestion
  # avoid building the development version, will break aarch64 build
  dontConfigure = true;
```

2020-02-07 13:02 UTC, turboMaCk commented
@anmonteiro can you please rebase and sqush commits in here? It seems to me that once that's done we can start pushing for merge.

2020-02-07 19:50 UTC, anmonteiro commented
Squashed!

2020-02-10 12:05 UTC, merged

2020-02-10 12:06 UTC, marsam commented
Thanks!