hey: init at 0.1.3
NixOS/nixpkgs pull request #79281
Opened 2020-02-05 15:22 UTC by filalex77

###### Motivation for this change
https://github.com/rakyll/hey/releases/tag/v0.1.3

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-02-05 17:13 UTC, Frostman requested changes
`nixpkgs-review` passed ok, binary works correctly.

2020-02-10 17:23 UTC, Frostman commented
Change LGTM, verified with `nixpkgs-review`, binary works correctly (NixOS, x86_64).

2020-02-10 17:24 UTC, Frostman approved these changes

2020-02-21 13:11 UTC, lukateras reviewed
LGTM otherwise!

2020-02-21 13:11 UTC, yegortimoshenko commented on pkgs/tools/networking/hey/default.nix
> +    pname = "hey";
Indentation seems to be off?

2020-02-21 13:11 UTC, yegortimoshenko commented on pkgs/tools/networking/hey/default.nix
> +        platforms = platforms.all;
`buildGoModule` sets default `meta.platforms`: https://github.com/NixOS/nixpkgs/blob/f373ecec8f49b24c3070ab4f66a680bee06980a5/pkgs/development/go-modules/generic/default.nix#L216-217

2020-02-26 19:59 UTC, filalex77 commented
Thanks, @Frostman and @yegortimoshenko!

2020-02-26 23:14 UTC, yegortimoshenko commented
@GrahamcOfBorg build hey

2020-02-26 23:15 UTC, lukateras approved these changes

2020-02-26 23:15 UTC, merged