nixos/syncoid: automatically setup privilege delegation
NixOS/nixpkgs pull request #79759
Opened 2020-02-10 20:06 UTC by lopsided98

###### Motivation for this change

Follow up to #72060. Runs syncoid as an unprivileged user by default and automatically sets up ZFS privilege delegation.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @Infinisil

2020-03-09 10:05 UTC, Mic92 requested changes

2020-03-09 10:05 UTC, Mic92 commented on nixos/tests/sanoid.nix
> +        sshKey = "/tmp/id_ecdsa";
Because people sometimes copy configuration from tests:

```suggestion
        sshKey = "/var/lib/syncoid/id_ecdsa";
```

2020-03-09 10:05 UTC, Mic92 commented on nixos/tests/sanoid.nix
> +        "chown syncoid:syncoid /tmp/id_ecdsa",
```suggestion
        "mkdir -m 700 -p /var/lib/syncoid",
        "cat '${snakeOilPrivateKey}' > /var/lib/syncoid/id_ecdsa",
        "chmod 600 /var/lib/syncoid/id_ecdsa",
        "chown -R syncoid:syncoid /var/lib/syncoid/",
```

2020-03-09 10:06 UTC, Mic92 commented on nixos/tests/sanoid.nix
> +        sshKey = "/tmp/id_ecdsa";
`/tmp/` is not a good location to put fixed filenames.

2020-09-04 05:54 UTC, numinit approved these changes
This looks good to me now. Feel free to request me as a reviewer for any ZFS-related changes.

2020-10-25 14:40 UTC, bhipple commented
Result of `nixpkgs-review pr 79759` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
<br>- tests.nixos-functions.nixos-test
</details>

2020-10-25 14:40 UTC, bhipple approved these changes

2020-10-25 14:40 UTC, merged