cinnamon.xapps: make gobject build input
NixOS/nixpkgs pull request #79780
Opened 2020-02-10 23:22 UTC by mkg20001

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-02-11 00:36 UTC, jtojnar requested changes
Since the bindings are generated using `g-ir-*` tools, this needs to be in `nativeBuildInputs`. If this project also links against `libgirepository-1.0.so` or depends on one of the typelibs shipped along, then it should go to `buildInputs` as well.

Could you mention the reason in the commit message?

Also the message is confusing, as gobject (GLib’s object system) ≠ gobject-introspection (set of tooling for introspecting libraries based on GObject and generating bindable typelib libraries from the introspected data). To add to the confusion, `gobject-introspection` package also does provide typelibs for glib (including `GObject-2.0.typelib`).

2020-02-11 03:20 UTC, mkg20001 commented
I have no idea. It seems to reference glib-object.h in some places, but otherwise I just followed the pattern of @worldofpeace telling me that I should add `gobject-introspection` as a build input, assuming it would always be one.

2020-02-11 03:30 UTC, worldofpeace commented
These are the typelibs it needs to generate girs https://github.com/linuxmint/xapps/blob/31133349e33260659e76c83f6edae57c38b0dc2b/libxapp/meson.build#L106

2020-02-11 03:31 UTC, mkg20001 commented
So build input or not?
I'm still not sure.

2020-02-11 03:34 UTC, worldofpeace commented
I believe it falls under the "generating bindable typelib libraries from the introspected data" so it should be native. But we can confirm this with @jtojnar.

2020-02-11 03:40 UTC, jtojnar commented
Well, that would be for the generator but typelibs itself are runtime dependencies so they should go to regular `buildInputs`. Perhaps even propagated ones since the GIR files include GObject (not sure).

2020-02-11 03:54 UTC, worldofpeace commented
:smile: Ahh, we should probably document this to help people out.

2020-02-11 18:14 UTC, worldofpeace requested changes
Can you fix your commit message?

2020-02-13 03:34 UTC, merged

2020-02-13 03:34 UTC, worldofpeace commented
Thank you @mkg20001.

2020-02-13 06:15 UTC, jtojnar commented
Perhaps I should have been clearer, it should still be in `nativeBPerhaps I should have been clearer, it should still be in `nativeBuildInputs` as well.uildInputs` as well.

2020-02-13 09:14 UTC, mkg20001 commented
This PR:

![confusion 100](https://user-images.githubusercontent.com/7735145/74418835-4bd43900-4e49-11ea-80b8-2f9a2ef926bf.png)

> Perhaps I should have been clearer, it should still be in nativeBuildInputs as well.

So it should be in there twice? Why?

2020-02-13 09:44 UTC, jtojnar commented
The distinction between `buildInputs` and `nativeBuildInputs` stems out from the fact that the packages are built and run on different computers. The computers are usually running on the same platform but that does not have to be the case (see [_cross-compilation_](https://en.wikipedia.org/wiki/Cross_Compiler)).

The build-time platform uses dependencies `nativeBuildInputs`, while run-time platform those from `buildInputs`. For historical reasons, by default, Nix will make `buildInputs` available at build time as well when one is not cross-compiling but proper expressions should distinguish between build-time and run-time environment.

2020-02-13 09:46 UTC, mkg20001 commented
This makes sense

Is this in the docs somewhere? Could be added if not under the gnome packaging section.

2020-02-13 09:55 UTC, jtojnar commented
It is described in https://nixos.org/nixpkgs/manual/#chap-cross and rather hard to digest https://nixos.org/nixpkgs/manual/#ssec-stdenv-dependencies (see https://nixos.org/nixpkgs/manual/#chap-cross for rendered diagrams).

2020-02-13 22:28 UTC, worldofpeace commented
Ohhh, strictDeps would have made this obvious.
@mkg20001 nixpkgs exposes the details of platforms and dependencies in a rather academic way sometimes :rofl:

2020-02-13 22:32 UTC, jtojnar commented
Not entirely academic, lot of people are cross-compiling stuff. Though to be fair `gobject-introspection` is currently borked for cross and `strictDeps` break setup hooks (https://github.com/NixOS/nixpkgs/issues/56943).