Fix indicator path for libindicator
NixOS/nixpkgs pull request #79832
Opened 2020-02-11 14:25 UTC by ilya-fedin

Currently mate-indicator-applet doesn't find indicator-application, this commit fixes that

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-02-11 15:03 UTC, worldofpeace commented
Same thing with the commit message at https://github.com/NixOS/nixpkgs/pull/79830#issuecomment-584678409.

2020-02-11 17:02 UTC, jtojnar commented
How does this affect programs using the key for installation?

2020-02-12 03:09 UTC, ilya-fedin commented
@worldofpeace  fixed
@jtojnar there are no such programs in nixpkgs repo, anyway, if they were, they would not build, since indicatorpath pointed to libdir, and it to the libindicator folder in /nix/store

2020-02-12 03:40 UTC, jtojnar commented
pkg-config actually supports installing relative to a package prefix, so a package would do

```ShellSession
$ libdir=/nix/store/my-app/lib
$ nix-shell -p pkg-config libindicator --run "pkg-config indicator3-0.4 --define-variable=libdir='$libdir' --variable indicatordir"
/nix/store/my-app/lib/indicators3/7/
```

See https://www.bassi.io/articles/2018/03/15/pkg-config-and-paths/

If there are such packages, they would work before but not after this patch removed `${libdir}` from the .pc file.

2020-02-15 20:54 UTC, ilya-fedin commented
> If there are such packages, they would work before but not after this patch removed `${libdir}` from the .pc file.

indicator-application-gtk3 and mate-indicator-applet are working. Which may not work?

2020-06-12 14:44 UTC, ilya-fedin commented
What's needed for this to be merged?

2020-08-10 11:34 UTC, jtojnar commented
I do not like this method since it is inconsistent with how we use other `foodir` pkg-config variables. We typically use it for in-package target paths, not global installation paths – the projects that install stuff to `foodir` usually outnumber projects that try to read from there (though for ancient libs like this one either might be hard to come by).

For that reason, this should be handled in the individual consumers like `mate-indicator-applet` in my opinion.

2021-01-18 12:08 UTC, SuperSandro2000 requested changes

2021-01-18 12:08 UTC, SuperSandro2000 commented on pkgs/development/libraries/libindicator/default.nix
> +      --replace 'indicatordir=''${libdir}' 'indicatordir=/run/current-system/sw/lib'
```suggestion
      --replace 'indicatordir=''${libdir}' 'indicatordir=/run/current-system/sw/lib'
```

2021-01-18 12:29 UTC, closed without merging