pythonPackages.pytes-timeout: disable flaky test
NixOS/nixpkgs pull request #80718
Opened 2020-02-21 11:57 UTC by rnhmjoj

###### Motivation for this change
ZHF: #80379 

I could finally reproduce the failure on hydra by running the test in a i686-linux VM with `stress -c 5`. Only this test seems to fail reliably, so let's disable it!

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox))
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-02-21 12:33 UTC, sugar700 reviewed
I think `test_fix_setup_func_only`, `test_fix_finalizer_func_only`, `test_ini_timeout_func_only` and `test_timeout_marker_inheritance` are also flaky (yes, that's a lot, but as I have said, "it's kinda the entire point of the module to make tests flaky").

However, I will admit that `test_suppresses_timeout_when_pdb_is_entered` is most likely to cause issues as it's doing the most processing (which can cause the scheduler to schedule away), increasing the probability of flakiness being discovered. IMO all of those tests should be disabled, but disabling `test_suppresses_timeout_when_pdb_is_entered` is a big improvement still.

2020-02-21 12:38 UTC, sugar700 requested changes
Please change the commit description to say `pytest-timeout`, not `pytes-timeout`.

2020-02-21 12:40 UTC, xfix commented
@GrahamcOfBorg build python27Packages.pytest-timeout python37Packages.pytest-timeout python38Packages.pytest-timeout

2020-02-21 12:41 UTC, xfix commented
@GrahamcOfBorg build python27Packages.pytest-timeout python37Packages.pytest-timeout python38Packages.pytest-timeout

2020-02-21 12:42 UTC, rnhmjoj commented
> I think test_fix_setup_func_only, test_fix_finalizer_func_only, test_ini_timeout_func_only and test_timeout_marker_inheritance are also flaky (yes, that's a lot, but as I have said, "it's kinda the entire point of the module to make tests flaky").

I would say to try disabling this one first and see how hydra responds.

2020-02-21 21:07 UTC, rnhmjoj commented
Ouch: mass rebuild.

2020-02-21 22:28 UTC, xfix commented
Mass rebuild is fine, this is mostly Python code, so it should take an hour or so.

2020-02-21 22:35 UTC, rnhmjoj commented
Do you think it's ok to push to master directly?

2020-02-22 07:14 UTC, xfix commented
Yes.

2020-02-22 08:33 UTC, merged

2020-02-22 09:23 UTC, rnhmjoj commented
Backported in 142dd6cb5dab. Let's see.