pythonPackages.psutil: 5.6.7 -> 5.7.0
NixOS/nixpkgs pull request #80772
Opened 2020-02-22 04:23 UTC by jonringer

###### Motivation for this change
noticed it was out of date

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-02-22 04:32 UTC, JeffLabonte requested changes
There are tests available in Github. Shouldn't they be ran? :)

2020-02-22 07:21 UTC, FRidh commented
this needs testing on Hydra unless someone does all the rebuilds.

2020-02-22 08:10 UTC, jonringer commented
> There are tests available in Github. Shouldn't they be ran? :)

true

2020-02-22 17:44 UTC, jonringer commented
a lot of the tests were platform specific, or shelled out to a multitude of other utilities.

2020-02-23 04:38 UTC, JeffLabonte requested changes
It doesn't build in python 2.7. It requires mock to be installed for the tests.

```bash
==================================== ERRORS ====================================
_______________________ ERROR collecting test_system.py ________________________
ImportError while importing test module '/nix/store/gbc2846c47iwii1w57xpma8kyiyvkh8n-python2.7-psutil-5.7.0/lib/python2.7/site-packages/psutil/tests/test_system.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/nix/store/gbc2846c47iwii1w57xpma8kyiyvkh8n-python2.7-psutil-5.7.0/lib/python2.7/site-packages/psutil/tests/__init__.py:62: in <module>
    import mock  # NOQA - requires "pip install mock"
E   ImportError: No module named mock
!!!!!!!!!!!!!!!!!!! Interrupted: 1 errors during collection !!!!!!!!!!!!!!!!!!!!
=========================== 1 error in 0.16 seconds ============================
```

2020-02-23 20:02 UTC, jonringer commented
@GrahamcOfBorg build python3Packages.psutil pythonPackages.psutil python38Packages.psutil

2020-02-23 20:08 UTC, jonringer commented
@GrahamcOfBorg build python3Packages.psutil pythonPackages.psutil python38Packages.psutil

2020-02-23 21:20 UTC, JeffLabonte approved these changes

2020-02-23 22:01 UTC, merged