idrisPackages: add tf-random package
NixOS/nixpkgs pull request #81813
Opened 2020-03-05 10:06 UTC by mikesperber

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-03-06 11:03 UTC, infinisil requested changes

2020-03-06 11:03 UTC, Infinisil commented on pkgs/development/idris-modules/tfrandom.nix
> +    homepage = "https://github.com/david-christiansen/idris-tf-random";
License missing, also if you want you can add yourself as a maintainer (see how other packages declare meta)

2020-03-20 12:45 UTC, mikesperber commented
Thanks for the feedback! Better?

2020-03-21 02:31 UTC, infinisil approved these changes
Yup looks good :)

2020-03-21 02:31 UTC, merged