dune: 2.3.1 -> 2.4.0
NixOS/nixpkgs pull request #82069
Opened 2020-03-08 18:01 UTC by anmonteiro

###### Motivation for this change
https://github.com/ocaml/dune/releases/tag/2.4.0

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

cc @marsam @vbgl

2020-03-08 19:38 UTC, vbgl commented
@GrahamcOfBorg build ocaml-ng.ocamlPackages_4_08.phylogenetics

2020-03-09 01:53 UTC, marsam approved these changes

2020-03-09 06:59 UTC, vbgl commented
@GrahamcOfBorg build ocamlPackages.eigen

2020-03-09 07:06 UTC, vbgl requested changes
This breaks `eigen` on darwin.

2020-03-09 14:40 UTC, anmonteiro commented
So what’s the plan generally in cases like this? Wait for a next version of either that makes them work together?

2020-03-09 20:59 UTC, vbgl commented
This might be reported upstream.

You can also look for a workaround or mark the package as broken.

2020-03-11 01:22 UTC, marsam commented
`eigen` is also failing on darwin in master, it should be fixed by https://github.com/NixOS/nixpkgs/pull/82299

2020-03-11 16:14 UTC, vbgl approved these changes

2020-03-11 16:14 UTC, vbgl commented
Apologies for wrongly blaming this PR.

2020-03-11 16:14 UTC, merged