simple-viewer-gl: init at 3.1.7
NixOS/nixpkgs pull request #82273
Opened 2020-03-10 19:21 UTC by caadar

###### Motivation for this change

Add ```simple-viewer-gl``` - tiny image viewer for Linux and macOS, based on OpenGL. Supported formats: PNG, JPEG, PSD, XCF, SVG, GIF, TIFF, TARGA, ICO, BMP, PNM, DDS, BMP, XWD, SCR (ZX-Spectrum screen), XPM, WebP.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-03-28 11:49 UTC, evenbrenden commented on pkgs/applications/graphics/simple-viewer-gl/default.nix
> +  meta = with stdenv.lib; {
Could you add yourself as a maintainer?

2020-03-28 11:51 UTC, evenbrenden reviewed
- [x] package name fits guidelines
- [x] package version fits guidelines
- [x] package build on x86_64
- [x] executables tested on x86_64
- [x] all depending packages build

Tested on NixOS. Tried it on Ubuntu 18.04 too, but it segfaults. That's probably not on you, though.

2020-03-29 08:01 UTC, evenbrenden approved these changes

2020-11-29 00:39 UTC, SuperSandro2000 requested changes

2020-11-29 00:39 UTC, SuperSandro2000 commented on pkgs/applications/graphics/simple-viewer-gl/default.nix
> +    popd >/dev/null
```suggestion
    pushd
    install -D -m0644 -t $out/share/doc/ config.example README.md Copying.txt
    install -D -m0644 -t $out/share/applications/ sviewgl.desktop
    install -D -m0644 -t $out/share/icons/ res/Icon-1024.png
    pop
```

2020-11-29 00:39 UTC, SuperSandro2000 commented on pkgs/applications/graphics/simple-viewer-gl/default.nix
> +}
```suggestion
  };
}
```

2020-11-29 00:46 UTC, SuperSandro2000 commented
```
trying https://bitbucket.org/andreyu/simple-viewer-gl/get/v3.1.7.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  977k  100  977k    0     0   816k      0  0:00:01  0:00:01 --:--:--  816k
unpacking source archive /build/v3.1.7.tar.gz
builder for '/nix/store/0r8h125j1pmds599b1b1pn0qvynq94vn-source.drv' failed to produce output path '/nix/store/1qj8d9j6pb10cijmmm047286pcjl7y90-source'
cannot build derivation '/nix/store/da6lyd0qlglz5aphrd6y8z5krdhmd7np-simple-viewer-gl-3.1.7.drv': 1 dependencies couldn't be built
error: build of '/nix/store/da6lyd0qlglz5aphrd6y8z5krdhmd7np-simple-viewer-gl-3.1.7.drv' failed
```

2021-04-01 15:39 UTC, closed without merging