zoxide: init at 0.1.1
NixOS/nixpkgs pull request #82282
Opened 2020-03-10 21:54 UTC by ysndr

###### Motivation for this change
I started using zoxide as an alternative to `z` and thought it would be nice to have it included in nixpkgs as well.
zoxide seems to be in a very early state though so I'd be fine to include it in my personal nur repo for some time until it proves stable enough to be added here.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-03-10 22:02 UTC, cole-h commented
Might want to wait until v0.2.0 is released, which will remove the fish/zsh/bash init scripts (in your `preFixup`) in favor of evaluating the output of a subcommand. It's currently over on the v0.2.0 branch for now.

2020-03-10 22:10 UTC, ysndr commented
Sure no need to rush that

2020-03-10 23:27 UTC, ajeetdsouza commented
zoxide v0.2.0 has been released!

2020-03-11 15:54 UTC, ysndr commented
Updated to 0.2.0

2020-03-11 16:08 UTC, cole-h requested changes
A minor suggestion, then it's g2g!

2020-03-11 16:08 UTC, cole-h commented on pkgs/tools/misc/zoxide/default.nix
> +    # Example Run-time Additional Dependencies
```suggestion
```

2020-03-11 16:10 UTC, ysndr commented
Changed, thanks

2020-03-11 16:12 UTC, cole-h approved these changes
LGTM. Binary runs as expected. Thanks!

```
[4 built, 2 copied (0.1 MiB), 0.0 MiB DL]
https://github.com/NixOS/nixpkgs/pull/82282
1 package built:
zoxide
```

2020-03-11 23:48 UTC, merged