rtl-sdr: fix cross compilation
NixOS/nixpkgs pull request #82412
Opened 2020-03-12 14:27 UTC by Mindavi

This patch partially fixes #81985.
Cross-compiling rtl-sdr is possible using this patch.
Use nix build -f <nixpkgs-path> -A pkgsCross.raspberryPi.rtl-sdr to build rtl-sdr.

The error that occured when trying to do this before was as follows:

/nix/store/ldb2v2z0198abkp2minr9a9vz5np4mn4-cmake-3.16.4-armv6l-unknown-linux-gnueabihf/nix-support/setup-hook: line 107: cmake: command not found

###### Motivation for this change

###### Things done

- [ ] **Is on by default?** Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] **Seems N/A** Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] **Not sure how this works** Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
  - note: this fails because it's cross-compiled, but the cross-compiled binary is of the correct type (`ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /nix/store/b996ssrajnrjkni0fz3k7ihrp0m77ahr-glibc-2.30-armv6l-unknown-linux-gnueabihf/lib/ld-linux-armhf.so.3, for GNU/Linux 2.6.32, not stripped
`)
- [ ] **Expect low impact** Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] **N/A** Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-03-12 19:05 UTC, bjornfor requested changes
cmake should be moved from buildInputs to nativeBuildInputs. It should not appear both places.

2020-03-12 19:14 UTC, Mindavi commented
I've moved it, thanks for the quick review.

2020-03-13 05:16 UTC, bjornfor approved these changes

2020-03-13 05:17 UTC, merged

2020-03-13 05:17 UTC, bjornfor commented
Thanks!