pyexiv2: 0.3.2 -> 2.1.0
NixOS/nixpkgs pull request #82771
Opened 2020-03-17 08:12 UTC by jchv

###### Motivation for this change
pyexiv2 has been broken for quite a while, but since then it has been rewritten. It no longer has a Boost dependency and now only works on Python 3 (formerly, it only worked on Python 2.)

Only one package depends on pyexiv2, jbrout. However, it is old and broken, so I made a PR to remove it in #82770.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-03-17 23:51 UTC, jonringer commented on pkgs/top-level/python-packages.nix
> +  pyexiv2 = disabledIf isPy27 (toPythonModule (callPackage ../development/python-modules/pyexiv2 {}));
and move disabled logic into expression

toPythonModule isn't needed when using `buildPythonPackage`
```suggestion
  pyexiv2 = callPackage ../development/python-modules/pyexiv2 {};
```

2020-03-17 23:51 UTC, jonringer commented on pkgs/development/python-modules/pyexiv2/default.nix
> +{ stdenv, buildPythonPackage, fetchFromGitHub, python, exiv2, pybind11, pytest, psutil }:
```suggestion
{ stdenv, isPy27, buildPythonPackage, fetchFromGitHub, python, exiv2, pybind11, pytest, psutil }:
```

2020-03-17 23:51 UTC, jonringer commented on pkgs/development/python-modules/pyexiv2/default.nix
> +  version = "2.1.0";
```suggestion
  version = "2.1.0";
  disabled = isPy27;
```

2020-03-17 23:51 UTC, jonringer commented on pkgs/development/python-modules/pyexiv2/default.nix
> +    homepage = https://github.com/LeoHsiao1/pyexiv2/;
rfc 45
```suggestion
    homepage = "https://github.com/LeoHsiao1/pyexiv2";
```

2020-03-19 07:17 UTC, jchv commented
Thanks for the feedback. All suggestions are applied and everything seems to be in working order.

2020-03-27 04:45 UTC, FRidh commented
@GrahamcOfBorg build pyexiv2

2020-03-27 04:47 UTC, FRidh commented
@GrahamcOfBorg build python3Packages.pyexiv2

2020-03-27 04:50 UTC, FRidh requested changes
```
Ran 0 tests in 0.000s
```
No tests are found. Either the test runner cannot find tests and needs to be patched, or there simply are no tests in which case the tests need to be disabled. Do include a comment explaining why the tests are disabled.

2020-03-27 04:50 UTC, FRidh commented on pkgs/development/python-modules/pyexiv2/default.nix
> +  patchPhase = ''
postPatch

2020-03-28 21:48 UTC, jchv commented on pkgs/development/python-modules/pyexiv2/default.nix
> +  patchPhase = ''
Done.

2020-03-30 07:18 UTC, jchv commented
@FRidh 
> ```
> Ran 0 tests in 0.000s
> ```
> 
> No tests are found. Either the test runner cannot find tests and needs to be patched, or there simply are no tests in which case the tests need to be disabled. Do include a comment explaining why the tests are disabled.

I took a look at what was going on. I'll admit I'm not 100% sure what the deal is because I am not overly familiar with how setuptools integrates with stuff like pytest, however, I suspect that it was not able to resolve the tests because its in a non-standard location (`pyexiv2/tests` vs `tests`.) Upstream, it looks like the recommended way of running the tests is by running `pytest` itself inside the folder, so I made a `checkPhase` that does this. May be possible to obsolete this by improving the upstream.

2020-04-08 17:54 UTC, jonringer reviewed
otherwise LGTM, tests run

2020-04-08 17:54 UTC, jonringer commented on pkgs/development/python-modules/pyexiv2/default.nix
> +    popd
```suggestion
    pytest pyexiv2/tests
```

2022-09-07 06:50 UTC, onny commented
Please rebase

2023-01-14 01:30 UTC, wegank commented
Closing since pyexiv2 has been deleted from nixpkgs in #141794. Feel free to create another one to add it again.

2023-01-14 01:30 UTC, closed without merging