openssl: 1.1.1d -> 1.1.1e
NixOS/nixpkgs pull request #82789
Opened 2020-03-17 17:07 UTC by andir

###### Motivation for this change

a "Low severity" [0] security issue:

> Fixed an overflow bug in the x64_64 Montgomery squaring procedure used
> in exponentiation with 512-bit moduli (CVE-2019-1551)

[0] https://www.openssl.org/news/vulnerabilities.html#y2019

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-03-17 17:14 UTC, sugar700 approved these changes

2020-03-23 08:32 UTC, vcunat commented
Even current staging (db1eb191f) still suffers from [the same issue as 19.09](https://github.com/NixOS/nixpkgs/pull/82791#issuecomment-600860264), so this can't be merged as-is.

2020-04-02 07:51 UTC, flokli commented
To recap: pyopenssl fails to build with that, upstream tracking issue is in https://github.com/pyca/pyopenssl/issues/899.

I'll file PRs applying just the CVE-fixing patch. We can probably still "properly" bump `openssl` as soon as `pyopenssl` has updated their code.

2020-04-02 08:03 UTC, flokli commented
Opened PRs to backport the fix for CVE-2019-1551 to master and 20.03 (staging):
https://github.com/NixOS/nixpkgs/pull/84083
https://github.com/NixOS/nixpkgs/pull/84084

2020-04-02 09:23 UTC, sugar700 requested changes
Please update to 1.1.1f. It's like 1.1.1e, but without EOF change (see https://www.openssl.org/news/openssl-1.1.1-notes.html).

2020-04-02 09:54 UTC, vcunat commented
Pushed as 6c8692feb4f

2020-04-02 09:54 UTC, closed without merging