kubelogin: init at 0.0.2
NixOS/nixpkgs pull request #83519
Opened 2020-03-27 18:08 UTC by yurrriq

###### Motivation for this change
Add [kubelogin](https://github.com/Azure/kubelogin)

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-03-27 18:09 UTC, yurrriq commented
@kalbasit, is this the preferred usage of `buildGoModule`?

2020-05-14 15:37 UTC, yurrriq commented
Any traction on this? There's a 0.0.3 release now too.

2020-06-17 15:20 UTC, yurrriq commented
I've updated this to 0.0.4 and `modSha256` -> `vendorSha256`

2020-09-25 07:16 UTC, doronbehar requested changes

2020-09-25 07:16 UTC, doronbehar commented on pkgs/applications/networking/cluster/kubelogin/default.nix
> +  goPackagePath = "github.com/Azure/kubelogin";
Not needed.

2020-09-25 07:16 UTC, doronbehar commented on pkgs/applications/networking/cluster/kubelogin/default.nix
> +{ stdenv, fetchFromGitHub, buildGoModule, go, ... }:
Why ... ?

2020-09-30 03:10 UTC, yurrriq commented on pkgs/applications/networking/cluster/kubelogin/default.nix
> +  goPackagePath = "github.com/Azure/kubelogin";
thanks, will remove

2020-09-30 03:10 UTC, yurrriq commented on pkgs/applications/networking/cluster/kubelogin/default.nix
> +{ stdenv, fetchFromGitHub, buildGoModule, go, ... }:
copy pasta :)

2020-09-30 03:21 UTC, yurrriq commented
Updated to 0.0.6 now, and heeded feedback from @doronbehar, thanks!

2020-09-30 08:07 UTC, doronbehar commented
Result of `nixpkgs-review pr 83519` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>kubelogin</li>
  </ul>
</details>

2020-09-30 08:09 UTC, merged