session-desktop: init at 1.0.5
NixOS/nixpkgs pull request #83698
Opened 2020-03-29 17:05 UTC by mehlon

###### Motivation for this change
Fixes #81927

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-04-02 17:00 UTC, Emantor approved these changes
Builds and starts correctly on NixOS unstable.

2020-06-10 02:54 UTC, LEXUGE commented
Any update here?

2020-07-01 05:12 UTC, billksun commented
What needs to be done for this to be merged?

2020-07-01 14:51 UTC, mehlon commented
This is functional and ready to integrate, although I am personally not satisfied with using a pre-built AppImage.
I would prefer to build it from source, but I have not felt the need for this software, so I haven't worked on it.

2020-09-23 04:40 UTC, ryantm commented
@mehlon Are you willing to add yourself as the maintainer of this?

2021-01-18 13:13 UTC, SuperSandro2000 requested changes

2021-01-18 13:13 UTC, SuperSandro2000 commented on pkgs/applications/networking/instant-messengers/session-desktop/default.nix
> +    license = licenses.gpl3;
plus or Only?

2021-01-18 13:13 UTC, SuperSandro2000 commented on pkgs/applications/networking/instant-messengers/session-desktop/default.nix
> +    #maintainers = with maintainers; [ ];
Please add yourself as a maintainers.

2021-01-20 20:08 UTC, mehlon commented
Sorry, I won't be maintaining this package.

2021-01-21 00:11 UTC, SuperSandro2000 commented
> Sorry, I won't be maintaining this package.

Adding packages without any maintainer basically marks them to be eventually broken. Maybe we shouldn't add the package if no one is planning to maintain it.

2021-01-21 04:49 UTC, ryantm commented
Yes, we can't accept this without a maintainer. If someone wants to pick that up, we can reopen.

2021-01-21 04:49 UTC, closed without merging