ursadb: init at v1.2.0
NixOS/nixpkgs pull request #83905
Opened 2020-03-31 23:06 UTC by msm-code

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux) (AFAIU it's the default on nixos)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"` (n/a - no packages are dependent on this yet. Tried it, "No diff detected, stopping review..."?)
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-04-02 16:56 UTC, Emantor commented
Throws an error when I try to run it:
```
nix-shell:~/.cache/nixpkgs-review/pr-83905/results/ursadb/bin]$ ./ursadb_new ~/tmp/mydb

[nix-shell:~/.cache/nixpkgs-review/pr-83905/results/ursadb/bin]$ ./ursadb ~/tmp/mydb 2048
terminate called after throwing an instance of 'zmq::error_t'
  what():  Invalid argument
Aborted (core dumped)
```

2020-04-02 17:40 UTC, msm-code commented
Hi,

thanks for input, If I knew anyone will test it I'd add more detailed instructions .

Looks like there's one parameter too much:

```
msm@scourge ~/P/nixpkgs> nix-build -A ursadb
/nix/store/8xlnxlm8q8y5bilzwkxviaxzi8cgya1h-ursadb
msm@scourge ~/P/nixpkgs> ./result/bin/ursadb_new /tmp/ursa/test.db
msm@scourge ~/P/nixpkgs> ./result/bin/ursadb /tmp/ursa/test.db
```

And there should be a process listening on `:9281`

I use https://github.com/CERT-Polska/ursadb-cli and https://github.com/CERT-Polska/mquery for testing (and on production), though they're not on nixpkgs (yet?).

2020-04-02 17:48 UTC, Emantor commented
> Hi,
> 
> thanks for input, If I knew anyone will test it I'd add more detailed instructions .
> 
> Looks like you've addded one parameter too much (if you want to specify the bind address you can do it like `tcp://127.0.0.1:9281` - the error message could've been clearer i guess).
> 
> ```
> msm@scourge ~/P/nixpkgs> nix-build -A ursadb
> /nix/store/8xlnxlm8q8y5bilzwkxviaxzi8cgya1h-ursadb
> msm@scourge ~/P/nixpkgs> ./result/bin/ursadb_new /tmp/ursa/test.db
> msm@scourge ~/P/nixpkgs> ./result/bin/ursadb /tmp/ursa/test.db
> ```
> 
> And there should be a process listening on `:9281`

Indeed, somehow I got `[bind_address]` confused with `[socket]` and supplied only a number. With your instructions it starts correctly. 

> I use https://github.com/CERT-Polska/ursadb-cli and https://github.com/CERT-Polska/mquery for testing (and on production), though they're not on nixpkgs (yet?).

Future packaging opportunity? :grin:

2020-04-02 17:55 UTC, msm-code commented
`Future packaging opportunity?`

I'm very much happy to to this in the future (though this service is the `core` so prerequisite for the others).

Maybe not ursadb-cli (I've noticed python package maintainers don't like too niche packages due to maintenance burden), but certainly mquery (right now the only supported installation method is docker, which is very meh).

2020-04-03 04:06 UTC, Emantor requested changes

2020-04-03 04:06 UTC, Emantor commented on pkgs/servers/ursadb/default.nix
> +    homepage = https://github.com/CERT-Polska/ursadb;
```suggestion
    homepage = "https://github.com/CERT-Polska/ursadb";
```

2020-04-03 04:06 UTC, Emantor commented on pkgs/servers/ursadb/default.nix
> +    url = https://github.com/CERT-Polska/ursadb/archive/v1.2.0.tar.gz;
```suggestion
    url = "https://github.com/CERT-Polska/ursadb/archive/v1.2.0.tar.gz";
```

2020-04-03 09:25 UTC, Emantor approved these changes

2020-04-03 09:26 UTC, Emantor commented
Would you kindly squash down the review commits into the `init at` commit? Than this should be ready to go.

2020-04-03 09:28 UTC, msm-code commented
Thanks for your suggestions! The url thing was accidental, I didn't even know that I can have strings without quotes (I assumed that quotes make a string, no quotes but slash == path, variable otherwise).

2020-04-03 09:28 UTC, msm-code commented
Sure, I was not sure if I was supposed to squash it or leave as it is

2020-04-03 14:16 UTC, Emantor commented
> Sure, I was not sure if I was supposed to squash it or leave as it is

The [submission guidelines](https://nixos.org/nixpkgs/manual/#chap-submitting-changes) mention that review fixes should be squashed.

2020-04-03 14:30 UTC, msm-code commented
You're right, I missed that. FWIW I squashed my changes before the first push. Thanks for clarifying!

2020-04-05 16:48 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-already-reviewed/2617/135

2020-04-14 02:18 UTC, bhipple commented on pkgs/servers/ursadb/default.nix
> +    cp ursadb_trim $out/bin/
You could do this on one like, e.g.

```
cp ursadb ursadb_new ursadb_trim $out/bin/
```

2020-04-14 02:18 UTC, bhipple commented
Result of `nixpkgs-review pr 83905` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- ursadb
</details>

2020-04-14 02:18 UTC, bhipple approved these changes

2020-04-14 02:18 UTC, merged