xrdp: 0.9.9 -> 0.9.12, refactor
NixOS/nixpkgs pull request #83922
Opened 2020-04-01 05:36 UTC by offlinehacker

###### Motivation for this change

- Update xrdp
- Simplify package

###### Things done

- xrdp: 0.9.9 -> 0.9.12
- xrdp: enable additional configure options
- xorgxrdp: split into separate package
- xorgxrdp: 0.2.9 -> 0.2.12

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-04-01 07:52 UTC, volth commented
> Simplify package

Better to say: it removes `--conf=` support (https://github.com/neutrinolabs/xrdp/issues/609 fix), so config files will have to be placed to hardcoded paths in /etc.

2020-04-01 08:03 UTC, volth commented
If the only reason to do so was troubles with rebasing the patch to `0.9.12`, I can do that.

2020-04-01 16:06 UTC, jonringer commented
@GrahamcOfBorg eval

2020-04-01 18:17 UTC, offlinehacker commented
@volth patch is still there, but I decided to use original source and pass it as patch, so no fork is needed: https://github.com/NixOS/nixpkgs/pull/83922/files#diff-904abce1afc720f5b9832c46b031c81aR19

2020-11-27 23:59 UTC, SuperSandro2000 commented
Please resolve the merge conflict(s).

2021-01-30 12:40 UTC, dotlambda commented
This fixes https://github.com/NixOS/nixpkgs/issues/93265

2021-06-11 10:24 UTC, mkg20001 commented
There's also this PR https://github.com/NixOS/nixpkgs/pull/83927

Which one is the right PR?

2022-10-26 23:14 UTC, SuperSandro2000 requested changes

2022-10-26 23:14 UTC, SuperSandro2000 commented on pkgs/applications/networking/remote/xrdp/default.nix
> +    ${perl}/bin/perl -i -ne 'print unless /\[(X11rdp|Xvnc|console|vnc-any|sesman-any|rdp-any|neutrinordp-any)\]/ .. /^$/' $out/etc/xrdp/xrdp.ini
```suggestion
    perl -i -ne 'print unless /\[(X11rdp|Xvnc|console|vnc-any|sesman-any|rdp-any|neutrinordp-any)\]/ .. /^$/' $out/etc/xrdp/xrdp.ini
```

2022-10-26 23:14 UTC, SuperSandro2000 commented on pkgs/applications/networking/remote/xrdp/default.nix
> +    ${perl}/bin/perl -i -ne 'print unless /\[(X11rdp|Xvnc|Xorg)\]/ .. /^$/' $out/etc/xrdp/sesman.ini
```suggestion
    perl -i -ne 'print unless /\[(X11rdp|Xvnc|Xorg)\]/ .. /^$/' $out/etc/xrdp/sesman.ini
```

2022-10-26 23:14 UTC, SuperSandro2000 commented on pkgs/applications/networking/remote/xrdp/default.nix
> +  nativeBuildInputs = [ pkgconfig autoconf automake which libtool nasm perl ];
```suggestion
  nativeBuildInputs = [ pkg-config autoconf automake which libtool nasm perl ];
```

2022-10-26 23:14 UTC, SuperSandro2000 commented on pkgs/applications/networking/remote/xrdp/xorgxrdp.nix
> +  nativeBuildInputs = [ pkgconfig autoconf automake which libtool nasm ];
```suggestion
  nativeBuildInputs = [ pkg-config autoconf automake which libtool nasm ];
```

2023-01-14 01:25 UTC, wegank commented
Superseded by #209509.

2023-01-14 01:25 UTC, closed without merging