abseil-cpp: 20191119 -> 20200225.1
NixOS/nixpkgs pull request #84149
Opened 2020-04-03 01:09 UTC by marsam

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-04-03 01:55 UTC, JeffLabonte approved these changes
LGTM

Builds with some error; other tools failed.
```
https://github.com/NixOS/nixpkgs/pull/84149
4 package failed to build:
or-tools python27Packages.ortools python37Packages.ortools python38Packages.ortools

1 package built:
abseil-cpp
```

2020-04-03 02:16 UTC, andersk requested changes
`or-tools` is the whole reason I added `abseil-cpp` to Nixpkgs, and is still its only consumer. If `or-tools` doesn’t build, we’ll need to come up with a different strategy.

2020-04-03 02:58 UTC, marsam commented
Oh, I see. Closing.

2020-04-03 02:58 UTC, closed without merging

2020-05-07 03:44 UTC, andersk commented
I submitted an update for abseil-cpp and or-tools together as #86755.