openblas: Add `singleThreaded` option. Off by default.
NixOS/nixpkgs pull request #84382
Opened 2020-04-05 19:11 UTC by nh2

###### Motivation for this change

In many cases (when called from a program / programming language runtime that uses threads, see https://github.com/xianyi/OpenBLAS/issues/2543 and linked wiki) OpenBLAS needs to be used single-threadedly.

This adds a package flag that allows building it single-threadedly as described in the OpenBLAS wiki.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-04-05 19:13 UTC, nh2 commented
FYI @basvandijk @markuskowa @tobim

2020-04-08 10:46 UTC, ttuegel requested changes
This looks fine to me, but I have one suggestion below.

2020-04-08 10:46 UTC, ttuegel commented on pkgs/development/libraries/science/math/openblas/default.nix
> +  } // (if !singleThreaded then {} else {
```suggestion
  } // (stdenv.lib.optionalAttrs singleThreaded {
```

2020-04-08 11:40 UTC, ttuegel approved these changes

2020-04-08 11:49 UTC, merged

2020-04-08 11:49 UTC, nh2 commented
@ttuegel thanks!