Add terminus_font to installation isos' console.packages
NixOS/nixpkgs pull request #84476
Opened 2020-04-06 14:36 UTC by jakobrs

###### Motivation for this change
On some modern HiDPI laptop displays (in particular, Apple's Retina displays), the default font is absolutely *tiny* due to the high DPI. This adds `pkgs.terminus_font` to `console.packages` in `installation-cd-base.nix` so to make more font sizes of the default Terminus font available.

###### Things done

Built using `nix build -f nixos/release.nix iso_image_new_kernel.x86_64-linux`.

**Note**: I have tested the changes on [`channels/nixos-20.03`](0bb35152be89) instead of master not to have to compile the entire Linux kernel.

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] ~~Tested execution of all binary files (usually in `./result/bin/`)~~ (N/A)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
   - Closure size increased by ~2.1 MiB
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-04-14 13:20 UTC, worldofpeace commented
How about we just use a better default console font in general @jakobrs? 
Last time I checked even ubuntu used terminus. 

It's best not to deviate from user experience in the representative media, and then have it be different on an actual installation.

2020-04-14 13:23 UTC, jakobrs commented
I believe we already use Lat2-Terminus16 by default (8x16 terminus font). This just adds higher-DPI versions.

I should probably mention that the terminus-font package uses a completely different naming scheme:
- Lat2-Terminus16 is called ter-116n
- Lat2-Terminus32 is called ter-132n
and so on

2020-04-14 14:45 UTC, Mic92 requested changes
Looks good; Should be mentioned in the manual as well.

2020-04-14 15:59 UTC, jakobrs commented
Should I include a list of all terminus font sizes, or just `ter-132n`?

2020-04-15 10:24 UTC, Mic92 commented
> Should I include a list of all terminus font sizes, or just `ter-132n`?

Just mention one good one for HiDpi. Less choices makes it less confusing for the reader.

2020-04-15 12:26 UTC, jakobrs commented
For reference, the names of the Terminus fonts are described in `$(nix-build '<nixpkgs>' kbd)/share/consolefonts/README.Lat2-Terminus16`

2020-04-16 10:19 UTC, Mic92 commented
@GrahamcOfBorg test installer

2020-04-29 16:20 UTC, merged