Brother MFC6490CW driver
NixOS/nixpkgs pull request #84798
Opened 2020-04-09 10:44 UTC by NorfairKing

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

I volunteer to maintain this package as long as I have this printer and use NixOS.

This is my first printer driver and also my first real nixpkgs contribution.
Please be nice, but give a lot of feedback.

2020-04-09 12:02 UTC, grahamc commented
@ofborg eval

2020-04-10 15:22 UTC, jraygauthier requested changes
I like this single file packaging. I see this is a hybrid in between the `pkgs/misc/cups/drivers/brother/mfcl3770cdw/default.nix` single nix file and other lpr / cupswrapper multi nix files packages.

Only issue is with the lpr package name. Also, surround bash variable expansion with double quotes.

2020-04-10 15:22 UTC, jraygauthier commented on pkgs/misc/cups/drivers/brother/mfc6490cw/default.nix
> +    name = "${model}drv-${version}";
```
name = "${model}lpr-${version}"
```

To reflect upstream package name and the name exposed in the all-packages.nix module.

2020-04-10 16:18 UTC, NorfairKing commented
@jraygauthier Thanks for the review!

2020-04-10 18:14 UTC, jraygauthier approved these changes
LGTM

2021-03-23 06:32 UTC, veprbl reviewed
Please rebase to fix merge conflict in maintainer-list.nix.

2021-03-23 06:32 UTC, veprbl commented on maintainers/maintainer-list.nix
> +  };
The new entries should not go to the end of maintainer-list.nix. Please put them in their respective place according to the alphabetic ordering.

2022-11-08 00:03 UTC, SuperSandro2000 commented
Closing due to inactivity from author.

2022-11-08 00:03 UTC, closed without merging

2026-04-21 19:58 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/brother-mfc6490cw-drivers/77163/1