openmvg: 1.3 -> 1.5 (unbreak)
NixOS/nixpkgs pull request #85330
Opened 2020-04-15 21:11 UTC by chkno

###### Motivation for this change
Unbreak OpenMVG.  Turns out all that was needed was to bump the version.

###### Things done
I successfully did a 3D photogrammetry reconstruction with this change.

- [x] Tested using sandboxing ([nix.useSandbox](http://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](http://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-22 13:28 UTC, danieldk requested changes
Whoops, seems like this PR fell by the wayside. Seems like a new version of openmvg is out. If you feel like updating this PR, feel free to ping me for a review.

2020-06-22 13:28 UTC, danieldk commented on pkgs/applications/science/misc/openmvg/default.nix
> +  version = "1.5";
Seems like 1.6 is out now.

2020-06-22 13:28 UTC, danieldk commented on pkgs/applications/science/misc/openmvg/default.nix
>      rev = "refs/tags/v${version}";
```suggestion
    rev = "v${version}";
```

2020-08-15 21:37 UTC, mdaiter commented
Looks good to me!

2020-08-16 06:40 UTC, danieldk commented
@ofborg build openmvg

2020-08-16 07:39 UTC, danieldk approved these changes
I amended the commit to use `fetchFromGitHub` and use version 1.6.

2020-08-16 07:39 UTC, merged