vtk: 7.1.1 -> 8.2.0
NixOS/nixpkgs pull request #87544
Opened 2020-05-10 21:08 UTC by bcdarwin

- also create vtk7 as several packages don't build with 8.x:
  - itk5: vtkVersion.h header not found at compile time
  - ants: version in tree (2.2.0) is incompatible with 8.2
  - itk4: ants depends on both vtk and itk4, so use vtk7
  - gdcm: vtk header issue
  - python3Packages.vtk: Python C API compilation error with Python 3.8

- upgrade vtkWithQt4 -> vtkWithQt5

###### Motivation for this change

VTK 9 is out and some packages (e.g., Fury, not yet in Nixpkgs) now require 8 or higher.  

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [NA] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
```
4 package marked as broken and skipped:
linuxPackages_hardkernel_4_14.r8125 linuxPackages_hardkernel_4_14.r8168 qes smi$
esign

13 package built:
cq-editor freecad mirtk opencascade pcl python27Packages.pythonocc-core python3$
Packages.cadquery python37Packages.pythonocc-core python38Packages.pythonocc-co$
e smesh vtk vtk7 vtkWithQt5
```
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-05-10 21:11 UTC, bcdarwin commented
@GrahamcOfBorg build vtk

2020-05-11 20:59 UTC, FRidh requested changes

2020-05-11 20:59 UTC, FRidh commented on pkgs/top-level/all-packages.nix
> +  vtk7 = callPackage ../development/libraries/vtk/7.x.nix {
`vtk_7`

2020-05-11 21:45 UTC, bcdarwin commented on pkgs/top-level/all-packages.nix
> +  vtk7 = callPackage ../development/libraries/vtk/7.x.nix {
Fixed, thanks.

2020-05-26 04:24 UTC, bhipple commented
Result of `nixpkgs-review pr 87544` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>13 packages built:</summary>
<br>- cq-editor
<br>- freecad
<br>- mirtk
<br>- opencascade
<br>- pcl
<br>- python27Packages.pythonocc-core
<br>- python37Packages.cadquery
<br>- python37Packages.pythonocc-core
<br>- python38Packages.pythonocc-core
<br>- smesh
<br>- vtk
<br>- vtkWithQt5
<br>- vtk_7
</details>

2020-05-26 04:24 UTC, bhipple approved these changes

2020-05-26 04:24 UTC, merged