libexif: 0.6.21 -> 0.6.22
NixOS/nixpkgs pull request #88100
Opened 2020-05-18 23:19 UTC by erictapen

###### Motivation for this change

###### Things done

- Bumped libexif
- removed old patches that are now integrated in the release (see also the [NEWS](https://github.com/libexif/libexif/blob/libexif-0_6_22-release/NEWS) for that)
- enabled building from git sources
- made sure cross compilation works

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-05-19 01:07 UTC, jonringer reviewed
since this change causes over 500 rebuilds, do you mind targeting the staging branch

```
git rebase --onto=staging HEAD~1
git push .. ... --force
```
then change the base branch in the github PR from `master` -> `staging`

See https://nixos.org/nixpkgs/manual/#submitting-changes-staging-branch for more details on staging branch

2020-05-19 01:07 UTC, jonringer commented
also, duplicate of #88096

2020-05-19 09:17 UTC, mmilata commented
In #88096 I didn't look into cross compilation so it's probably better to merge this one.

Another difference is that the other PR uses the release archive which doesn't need autoreconf, not sure what is preferable.

2020-05-19 11:16 UTC, erictapen commented
@mmilata Oh sorry, this time I didn't look for duplicates because I felt I'd be early enough. Will check next time definetely.

I'd always prefer building from source, as this leverages the hurdle for upstream contributions.

@jonringer Thanks, I know about the staging branch but first wanted to ask ofBorg how much is going to be rebuilt.

2020-05-31 21:35 UTC, prusnak requested changes

2020-05-31 21:35 UTC, prusnak commented on pkgs/development/libraries/libexif/default.nix
> +  nativeBuildInputs = [ autoreconfHook gettext  ];
```suggestion
  nativeBuildInputs = [ autoreconfHook gettext ];
```

2020-05-31 21:35 UTC, prusnak commented on pkgs/development/libraries/libexif/default.nix
>    meta = {
Please extract stdenv.lib with:

```suggestion
  meta = with stdenv.lib; {
```

afterward you can contract `license`, `platforms`, and `maintainers` fields below to:

```
    license = licenses.lgpl21;
    platforms = platforms.unix;
    maintainers = with maintainers; [ erictapen ];
```

2020-06-01 10:41 UTC, erictapen commented
@prusnak Thanks for the review. I added your suggestions and rebased to latest `staging`.

2020-06-01 10:57 UTC, prusnak approved these changes

2020-06-04 16:23 UTC, merged