Init cohttp-async @ 2.5.1, upgrading cohttp 2.1.3 -> 2.5.1
NixOS/nixpkgs pull request #88886
Opened 2020-05-25 18:07 UTC by bcc32

###### Motivation for this change

Add cohttp-async, upgrading cohttp and conduit to make this possible.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-29 11:01 UTC, sternenseemann commented
You might want to rebase this change against `master`. `conduit`, `ipaddr`, `macaddr`, `tuntap` and `cohttp` have been updated (cohttp is on 2.5.1).

2020-06-29 22:34 UTC, bcc32 commented
Thanks for the heads up, this PR is much cleaner now :)

2020-06-30 09:18 UTC, sternenseemann requested changes
Builds fine for me. A bit of tidying up would be nice though:

* efa7f1dabf4fb591a3943450a4b15369fd6819b9 has a bit of a messy diff seems like some unnecessary indentation changes got commited. Also use the [nixpkgs commit message format](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md#submitting-changes)
* split 8baf77bf2fd1a0a9c3e8b4a21fb5ab6a6ee74c7e into three commits adding the individual packages.

2020-07-10 00:54 UTC, bcc32 commented
Thanks for the feedback!  (I'm still new to nix so a lot of my edits have been guess-work and pattern matching.)

I've split the commit into one for each package.  Do you think it would be good to also squash e76ba09 into d56e12e, or is it fine to keep them separate?

2020-07-10 09:00 UTC, sternenseemann requested changes
Commits should be fine like current, but you can also squash the two if you want.

2020-07-12 03:04 UTC, bcc32 commented on pkgs/development/ocaml-modules/janestreet/0.13.nix
> +    propagatedBuildInputs = [ async ctypes dune-configurator openssl ];
Ok, done.  Is there some guideline as to when a dependency should be in `buildInputs` and not `propagatedBuildInputs`?

2020-07-12 03:15 UTC, bcc32 commented on pkgs/development/ocaml-modules/cohttp/async.nix
> +    buildInputs = [ uri ppx_sexp_conv ];
I modeled this off of `cohttp/lwt.nix`.  I'm not especially clear on the difference, so I didn't make any changes.

2020-07-14 17:28 UTC, sternenseemann commented on pkgs/development/ocaml-modules/janestreet/0.13.nix
> +    propagatedBuildInputs = [ async ctypes dune-configurator openssl ];
Dependency types are documented in the [nixpkgs manual](https://nixos.org/nixpkgs/manual/#ssec-stdenv-dependencies).

In `ocamlPackages` `buildInputs` contains packages that are *only* needed to build the package at hand: `dune-configurator` and `ppx_sexp_conv` for example are just needed to build a package, even only during build time (theoretically they'd belong in `nativeBuildInputs` I think, but I don't know how well `ocamlPackages` can be crosscompiled, I fear not at all).

`propagatedBuildInputs` contain dependencies that also packages that depend on the current package will need to build. This is the case for example, when package A exposes in its API a type of package B. Then a package C that only depends on package A will also need package B at compile time to build. Therefore package B is a propagated build input. I usually propagate all packages that are not obvious build time only dependencies, but I think it is not necessary if package B is only used internally (could be the case with `uri` in `cohttp-async`?), but I have never tested it myself.

2020-07-15 15:05 UTC, bcc32 commented on pkgs/development/ocaml-modules/janestreet/0.13.nix
> +    propagatedBuildInputs = [ async ctypes dune-configurator openssl ];
Got it, and thanks for the link!

2020-07-25 07:52 UTC, sternenseemann requested changes
otherwise lgtm

2020-07-25 07:52 UTC, sternenseemann commented on pkgs/development/ocaml-modules/cohttp/async.nix
> +		buildInputs = [ uri ppx_sexp_conv ];
`uri` should be propagated as well.

2020-07-25 17:01 UTC, bcc32 commented on pkgs/development/ocaml-modules/cohttp/async.nix
> +		buildInputs = [ uri ppx_sexp_conv ];
Thanks, done!

2020-07-25 17:01 UTC, bcc32 commented
Awesome.  Thanks for the careful review and the helpful feedback!

2020-07-25 18:12 UTC, sternenseemann approved these changes

2020-08-15 11:31 UTC, sternenseemann commented
Can you test this against cb2d328479f154e1ac2d23b8b212df32af948ba5?

2020-08-15 20:07 UTC, bcc32 commented
I just rebased against master, and everything seems to be in working order (`nix build -f . ocamlPackages.cohttp-async`, `nixpkgs-review pr 88886`).

2020-08-23 09:54 UTC, vbgl requested changes
It seems that `cohttp-async` won’t build with OCaml 4.07. Can you please set its `minimumOCamlVersion` to 4.08? Thanks.

2020-08-28 00:02 UTC, bcc32 commented
I think this is an issue of a change that happened in Jane Street's async packages (Tcp module was moved from `Async_extra` to `Async_unix`).  Is there a way I can require that the version of the `async` package is at least 0.13?

2020-08-28 06:24 UTC, vbgl commented
There is such a check in bap: https://github.com/NixOS/nixpkgs/blob/1c243af737cb3239cd8e78fbf8275379eb97af00/pkgs/development/ocaml-modules/bap/default.nix#L9-L11

2020-08-28 15:36 UTC, bcc32 commented
Thanks, @vbgl.  I added such a check to cohttp-async.

2020-08-29 04:33 UTC, vbgl approved these changes

2020-08-29 04:33 UTC, merged