imag: init at 0.10.1
NixOS/nixpkgs pull request #89016
Opened 2020-05-27 12:23 UTC by minijackson

###### Motivation for this change

Based on #77362 by @filalex77 

As discussed there, the differences are:

- Update to 0.10.1, which removes the `Cargo.lock` patch
- Run the tests under a created PTY to make them pass
- Install the shell completion scripts

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-05-27 13:03 UTC, Br1ght0ne requested changes

2020-05-27 13:03 UTC, filalex77 commented on pkgs/applications/misc/imag/default.nix
> +  '';
```suggestion
  postInstall = ''
    installShellCompletion target/imag.{bash,fish} --zsh target/_imag
  '';
```

Also add `installShellFiles` to derivation arguments and `nativeBuildInputs`.

2020-05-27 13:06 UTC, filalex77 commented
Checking Darwin build.

@GrahamcOfBorg build imag

2020-05-27 16:23 UTC, minijackson commented
Updated with the usage of installShellFiles (I didn't know about this hook, thanks!), and hopefully fixes the darwin build, which uses BSD-style `script` command.

2020-05-27 17:23 UTC, Br1ght0ne approved these changes
diff LGTM
`nixpkgs-review` passed on NixOS 20.03

2020-05-27 17:24 UTC, filalex77 commented
@GrahamcOfBorg build imag

2020-05-27 18:50 UTC, minijackson commented
The darwin build now passes, but I don't see the tests in the log...

2020-05-27 21:07 UTC, filalex77 commented
@GrahamcOfBorg build imag.passthru.tests

2020-05-28 08:08 UTC, minijackson commented
@filalex77 Isn't `passthru.tests` usually for nixos modules tests?

I can see the tests in the linux build log, so I thought it was the BSD-style `script` that captured the output? Another point that bugs me is that I don't know if the `script` in the darwin build returns the same error code as the command it runs, so it's possible we might not see the darwin tests fail :-/

2020-08-22 15:26 UTC, merged