merge-request-notifier: init at 1.7.0
NixOS/nixpkgs pull request #89203
Opened 2020-05-30 06:51 UTC by robaca

###### Motivation for this change

New package for GitLab [merge-request-notifier](https://github.com/codecentric/merge-request-notifier).

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-05-30 08:33 UTC, doronbehar commented
Is there a chance you could build it from source? Try to use `yarn2nix`

2020-05-30 12:33 UTC, robaca commented
@doronbehar I will give it a try

2021-02-09 00:27 UTC, SuperSandro2000 requested changes

2021-02-09 00:27 UTC, SuperSandro2000 commented on pkgs/applications/version-management/merge-request-notifier/default.nix
> +  name = "merge-request-notifier";
```suggestion
  pname = "merge-request-notifier";
  version = "1.7.0";
```

2021-02-09 00:27 UTC, SuperSandro2000 commented on pkgs/applications/version-management/merge-request-notifier/default.nix
> +    url = "https://github.com/codecentric/merge-request-notifier/releases/download/v1.7.0/merge-request-notifier-${version}.tar.xz";
```suggestion
    url = "https://github.com/codecentric/merge-request-notifier/releases/download/v${version}/merge-request-notifier-${version}.tar.xz";
```

2021-02-09 00:27 UTC, SuperSandro2000 commented on pkgs/applications/version-management/merge-request-notifier/default.nix
> +
```suggestion

```

Please do not overwrite phases like this because it breaks hooks.

2021-02-09 00:27 UTC, SuperSandro2000 commented on pkgs/applications/version-management/merge-request-notifier/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

stdenv.lib got recently deprecated.

2021-08-10 05:23 UTC, doronbehar commented
Closing due to no response from OP.

2021-08-10 05:23 UTC, closed without merging