nixos/prometheus-lnd-exporter: init
NixOS/nixpkgs pull request #89449
Opened 2020-06-03 23:45 UTC by mmilata

###### Motivation for this change

fort-nix/nix-bitcoin#186 + would like to take advantage of the nice prometheus exporters infrastructure that nixpkgs has

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-10 20:02 UTC, mdlayher approved these changes
LGTM with a test nit.

2020-06-11 00:36 UTC, mmilata commented on nixos/tests/prometheus-exporters.nix
> +        succeed("curl -sSf localhost:9092/metrics | grep -q '^promhttp_metric_handler'")
It seems that in order for an actual metric to be exported the lnd daemon needs to be synced with bitcoind and have wallet generated. Although it should be possible to test this without internet access by running both daemons in "regtest" mode, the setup is quite non-trivial:(

2020-06-11 12:58 UTC, WilliButz requested changes
I think running the exporter as root in the test  or as a normal user anywhere else can be avoided by giving it access to the needed files specifying `ReadOnlyPaths` (or if necessary `ReadWritePaths`) in the service configuration.
(See `systemd.exec(5)`)

Otherwise this looks good to me :+1:

2020-06-11 12:58 UTC, WilliButz commented on nixos/modules/services/monitoring/prometheus/exporters/lnd.nix
> +  };
```suggestion
  serviceOpts.serviceConfig = {
    ExecStart = ''
      ${pkgs.prometheus-lnd-exporter}/bin/lndmon \
        --prometheus.listenaddr=${cfg.listenAddress}:${toString cfg.port} \
        --prometheus.logdir=/var/log/prometheus-lnd-exporter \
        --lnd.host=${cfg.lndHost} \
        --lnd.tlspath=${cfg.lndTlsPath} \
        --lnd.macaroondir=${cfg.lndMacaroonDir} \
        ${concatStringsSep " \\\n  " cfg.extraFlags}
    '';
    LogsDirectory = "prometheus-lnd-exporter";
    ReadOnlyPaths = "${cfg.lndTlsPath} ${lndMacaroonDir}";
  };
```

2020-06-11 12:58 UTC, WilliButz commented on nixos/tests/prometheus-exporters.nix
> +        user = "root";
```suggestion
```

2020-06-11 13:04 UTC, WilliButz commented on nixos/tests/prometheus-exporters.nix
> +        succeed("curl -sSf localhost:9092/metrics | grep -q '^promhttp_metric_handler'")
If it is too much overhead to actually bootstrap an environment for the exporter to work as intended, I think it is fine to only check if the module is compatible with the current exporter package. This should make it less likely that someone updates the exporter package without touching the module and thereby unknowingly causing incompatibilities, which has happened before :).

2020-06-11 16:28 UTC, mmilata commented
Thanks @WilliButz, I've applied your suggestions and rebased on master to resolve conflicts.

2020-06-11 16:30 UTC, WilliButz commented
@GrahamcOfBorg test prometheus-exporters.lnd

2020-06-11 16:53 UTC, WilliButz approved these changes
looks good to me :+1:

2020-06-11 16:53 UTC, merged

2020-06-11 17:03 UTC, mmilata commented
Thanks @WilliButz and @mdlayher!