pythonPackages.gast_0_2_2: init for tensorflow
NixOS/nixpkgs pull request #89496
Opened 2020-06-04 18:34 UTC by matthewbauer

It’s been reported that python-gast-0.2.2 is needed for Tensorflow
Autograph. See https://github.com/tensorflow/tensorflow/issues/38734.

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-04 18:38 UTC, jonringer commented
The link you provided just shows an install error. Is there a runtime error with using gast>=0.3?

Generally we try to avoid different versions in `python-modules` as this will create incoherent package sets if a user creates an envrionment with 2 different versions of the same package.

2020-06-04 18:53 UTC, matthewbauer commented
A better description of the issue is here:

https://github.com/tensorflow/tensorflow/issues/32319

2020-06-04 19:14 UTC, jonringer reviewed
cc @FRidh

2020-06-04 19:14 UTC, jonringer commented on pkgs/development/python-modules/gast/0_2_2.nix
> +  version =  "0.2.2";
```suggestion
  version =  "0.2.2";

```

2020-06-04 19:14 UTC, jonringer commented on pkgs/development/python-modules/gast/0_2_2.nix
> +  };
```suggestion
  };

```

2020-06-04 19:14 UTC, jonringer commented on pkgs/development/python-modules/gast/0_2_2.nix
> +  checkInputs = [ astunparse ] ;
```suggestion
  checkInputs = [ astunparse ] ;

```

2020-07-31 06:22 UTC, FRidh requested changes
No this is not possible. We cannot have multiple versions of packages because this will cause runtime conflicts when mixing packages relying on the different versions.

2020-07-31 06:24 UTC, FRidh commented
Simply put, the older tensorflow will no longer work with Nixpkgs, unless the user themselves performs an override to fix it.

2020-07-31 15:45 UTC, closed without merging