pantalaimon: fix build
NixOS/nixpkgs pull request #89694
Opened 2020-06-06 20:23 UTC by symphorien

###### Motivation for this change

pantalaimon does not build on nixos-unstable

Some updates were needed. peewee tests now require psycopg.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-13 09:12 UTC, FRidh commented
many package updates are now in https://github.com/NixOS/nixpkgs/pull/89723. Best rebase this on staging-next once those updates land there.

2020-06-15 20:11 UTC, symphorien commented
rebased on staging-next. I don't know why some r-ryantm and others commits are here, though.

2020-06-15 20:16 UTC, symphorien commented
removed irrelevant commits

2020-06-15 21:15 UTC, dotlambda requested changes

2020-06-15 21:15 UTC, dotlambda commented on pkgs/development/python-modules/janus/default.nix
> +  doCheck = false;
Why not deselect the specific ones?

2020-06-15 21:15 UTC, dotlambda commented on pkgs/development/python-modules/asynctest/default.nix
> -  '';
Why did you remove this?

2020-06-15 21:15 UTC, dotlambda commented on pkgs/development/python-modules/asynctest/default.nix
> +  doCheck = false;
Why not `doCheck = pythonOlder "3.8"`?

2020-06-16 10:45 UTC, symphorien commented on pkgs/development/python-modules/asynctest/default.nix
> -  '';
restored

2020-06-16 10:45 UTC, symphorien commented on pkgs/development/python-modules/janus/default.nix
> +  doCheck = false;
done

2020-06-16 10:46 UTC, symphorien commented on pkgs/development/python-modules/asynctest/default.nix
> +  doCheck = false;
done

2020-06-16 14:46 UTC, simonchatts approved these changes
I've confirmed that this works with my dependencies on `janus`.

2020-06-20 11:26 UTC, symphorien commented
rebased on master, tested that pantalaimon builds and run.

2020-06-20 19:53 UTC, jonringer approved these changes
LGTM

nixpkgs-review freezing on python38Packages.uvloop, failures don't seem to be associated to any of these bumps

2020-06-20 19:53 UTC, merged