caster-soundboard: init at unstable-2019-9-28
NixOS/nixpkgs pull request #89714
Opened 2020-06-07 03:46 UTC by IQubic

###### Motivation for this change
caster-soundboard is a great application, and I noticed it wasn't in nixpkgs, so I packaged it up.

###### Things done
Added a derivation for caster-soundboard in pkg/audio
Added caster-soundboard to all-packages.nix
Added iqubic to the maintainer

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-18 00:30 UTC, worldofpeace requested changes

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +  ];
I believe you should also need `gst_all_1.gstreamer`?

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +  meta = {
```suggestion
  meta = with stdenv.lib; {
```

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +    maintainers = [ stdenv.lib.maintainers.iqubic ];
```suggestion
    maintainers = [ maintainers.iqubic ];
```

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +    license = stdenv.lib.licenses.lgpl3;
```suggestion
    license = licenses.lgpl3;
```

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +    platforms = stdenv.lib.platforms.linux;
```suggestion
    platforms = platforms.linux;
```

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +  src = fetchFromGitHub {
```suggestion

   src = fetchFromGitHub {
```

a newline

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +  name = "caster-soundboard";
```suggestion
  pname = "caster-soundboard";
```

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +  sourceRoot = "source/CasterSoundboard";
```suggestion

  sourceRoot = "source/CasterSoundboard";
```

a newline

2020-06-18 00:30 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +    description = "A soundboard for hot-keying and playing back sounds.";
```suggestion
    description = "A soundboard for hot-keying and playing back sounds";
```

no periods at the end of `description`

2020-06-18 00:31 UTC, worldofpeace commented on pkgs/applications/audio/caster-soundboard/default.nix
> +  ];
Also `qtbase`

2020-06-18 06:21 UTC, IQubic reviewed
This is my first time submitting any PRs to nixpkgs. I'm sorry for getting a lot of the little formatting details slightly wrong. I'll try to do better in the future. All in all, I think these changes are acceptable, and should be made to the commits I've already done.

2020-06-18 09:29 UTC, worldofpeace commented
> This is my first time submitting any PRs to nixpkgs. I'm sorry for getting a lot of the little formatting details slightly wrong. I'll try to do better in the future. All in all, I think these changes are acceptable, and should be made to the commits I've already done.

Cool, that means you'll supply the changes in the coming day/s?

2020-06-28 02:59 UTC, IQubic commented
@worldofpeace I wasn't aware that I had to supply the changes myself, I thought that anyone with push access to the repo could make the changes for me. Sorry about that. I'll get on this right away.

2022-11-07 23:25 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +  iqubic = {
This must be sorted alphabetical

2022-11-07 23:25 UTC, SuperSandro2000 requested changes

2022-11-07 23:25 UTC, SuperSandro2000 commented on pkgs/applications/audio/caster-soundboard/default.nix
> +
```suggestion
```
done by qmake

2022-11-14 01:35 UTC, davidak commented
The project looks abandoned. No commit since [Sep 28, 2019](https://github.com/JupiterBroadcasting/CasterSoundboard/commit/1a84315b3a3d4bdca1a4b784bd19460637f44438).

2023-06-21 18:40 UTC, Janik-Haag commented
Will close the pr since the project is almost definitively stale.

2023-06-21 18:40 UTC, closed without merging