spades: add python dependency
NixOS/nixpkgs pull request #89778
Opened 2020-06-07 23:42 UTC by jbedo

###### Motivation for this change

spades.py requires python.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-08 00:55 UTC, jtojnar requested changes
The commit message tag needs to match the attribute name `SPAdes`.

2020-06-08 00:55 UTC, jtojnar commented on pkgs/applications/science/biology/spades/default.nix
> +  buildInputs = [ zlib bzip2 python ];
Please use either `python2` or `python3`.

2020-06-08 07:00 UTC, bzizou approved these changes

2020-11-28 04:37 UTC, SuperSandro2000 commented
Build in #87494 fine without. Closing.

2020-11-28 06:40 UTC, jbedo commented
Problem was in execution not build, python is a runtime dependency.

2020-11-28 08:36 UTC, jbedo commented
Confirmed, patch still required:

```
~/g/nixpkgs on 8256fc2da56 ⨯ nix shell .#SPAdes -c spades.py
/usr/bin/env: ‘python’: No such file or directory    
```

2020-12-14 23:22 UTC, jbedo commented
SPAdes is unusable without this patch, is there anything further I need to do to get it merged? Might be worth considering backporting to 20.09 since it's also broken there.

2020-12-15 07:40 UTC, bzizou approved these changes
I agree that the python dependency allows spades.py to run in a pure environment without explicitly loading python

2020-12-20 16:06 UTC, SuperSandro2000 commented
I read on their GitHub that they support python3 https://github.com/ablab/spades#installation. Can we please use python3 as we are currently remove python2 from as many packages as possible.

2020-12-20 21:36 UTC, jbedo commented
Changed to python 3, rebased against current master, and verified functional.

2020-12-21 06:08 UTC, bzizou approved these changes

2020-12-21 12:10 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 89778` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>SPAdes</li>
  </ul>
</details>

2020-12-21 17:08 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 89778` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>SPAdes</li>
  </ul>
</details>

2020-12-21 17:25 UTC, merged