confluent-platform: update 5.3.0 -> 5.5.0
NixOS/nixpkgs pull request #91231
Opened 2020-06-21 14:32 UTC by DianaOlympos

##### Motivation for this change

The conluent cli is not open source anymore and now distributed as a binary.

Updated versions and build so that it build again.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-03 15:03 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/358

2020-11-25 01:01 UTC, SuperSandro2000 commented on pkgs/servers/confluent-platform/default.nix
> +    cp -R $confluentCli confluent-cli
This would be a great usecase for install to also make sure the permissions are correct.

2020-11-25 11:06 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 91231` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>confluent-platform</li>
  </ul>
</details>

2020-11-25 12:03 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 91231` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>confluent-platform</li>
  </ul>
</details>

2021-01-18 18:48 UTC, SuperSandro2000 requested changes

2021-01-18 18:48 UTC, SuperSandro2000 commented on pkgs/servers/confluent-platform/default.nix
>    meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-07-21 11:32 UTC, DianaOlympos commented
Closing this as the whole thing moved, i will reopen with a more recent version Soon TM

2021-07-21 11:32 UTC, closed without merging