python3Packages.tlsprofiler: init at 1.0
NixOS/nixpkgs pull request #91380
Opened 2020-06-23 22:13 UTC by veehaitch

###### Motivation for this change

Tlsprofiler allows to test if a TLS server adheres to [Mozzilla's server side TLS recommendations](https://wiki.mozilla.org/Security/Server_Side_TLS#Recommended_configurations). NixOS also relies on these guidelines for [Nginx](https://github.com/NixOS/nixpkgs/blob/release-20.03/nixos/modules/services/web-servers/nginx/default.nix#L89-L103), implementing the "intermediate" profile as a configuration flag. The original authors of Tlsprofiler provide a web version [here](https://tlsprofiler.danielfett.de/).

Tlsprofiler makes use of Nassl/SSLyze, which have been merged [recently](https://github.com/NixOS/nixpkgs/pull/89034). It does, however, rely on a forked version of [Nassl](https://github.com/fabian-hk/nassl/tree/tls_profiler) and [SSLyze](https://github.com/fabian-hk/sslyze/tree/tls_profiler). In contrast to the Nixpgks version of SSLyze, I had to disable the tests as virtually all are online. They passed just fine though: https://gist.github.com/veehaitch/a7eb5164ff1480dd47da3500509897d3

One may use Tlsprofiler as a Python 3 package or as a command line application; see `tlsprofiler -h` for further information.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-24 08:35 UTC, veehaitch commented on pkgs/development/python-modules/tlsprofiler/default.nix
> +  propagatedBuildInputs = [ requests cryptography nasslTlsprofiler sslyzeTlsprofiler ];
Thanks for your review. I agree with your assessment that pinning these versions should be avoided; particularly, as it isn't unlikely that someone who uses `tlsprofiler` in their Python project might also use `sslyze`. I'd propose the following strategy:
1. Ask the authors of TLS Profiler if they think it is possible to make some efforts to merge their fork of Nassl/SSLyze with upstream. To that end, I've created an issue: https://github.com/danielfett/tlsprofiler/issues/6. If this works out, we could include a modified version of this PR without further problems, I guess.
2. If this won't happen for any reason, I'll modify the PR to include the application only (similar to `awscli`).

2021-09-14 04:25 UTC, samuela requested changes

2021-09-14 04:25 UTC, samuela commented on pkgs/development/python-modules/tlsprofiler/default.nix
> +    oldAttrs: rec {
Why is `rec` needed?

2021-09-14 04:25 UTC, samuela commented on pkgs/development/python-modules/tlsprofiler/tlsprofiler-setup-requirements.patch
> +
I think this patch would be easier with just two substituteInPlace's.

2021-09-14 04:25 UTC, samuela commented on pkgs/development/python-modules/tlsprofiler/default.nix
> +    sed -i '1s|^|#!/usr/bin/env python3\n|' run.py
Why is this necessary?

2021-09-14 04:25 UTC, samuela commented on pkgs/development/python-modules/tlsprofiler/default.nix
> +        ./nassl-0001-Fix-test.patch
If this is an upstream patch can we use fetchpatch instead?

2021-09-14 04:25 UTC, samuela commented on pkgs/development/python-modules/tlsprofiler/default.nix
> +    oldAttrs: rec {
I don't think `rec` is necessary.

2021-11-12 16:37 UTC, SuperSandro2000 commented
Closing due to no response from author in a while.

2021-11-12 16:37 UTC, closed without merging