nixos/blockbook-frontend: init
NixOS/nixpkgs pull request #91497
Opened 2020-06-25 14:55 UTC by 1000101

###### Motivation for this change
Initial definition of blockbook-frontend service - blockchain explorer, its test and a small change to the package itself so we can run this as a service with multiple instances and different blockchains.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-06-25 15:12 UTC, prusnak requested changes

2020-06-25 15:12 UTC, prusnak commented on nixos/modules/services/networking/blockbook-frontend.nix
> +      description = "Sepcification of one or more blockbook-frontend instances.";
```suggestion
      description = "Specification of one or more blockbook-frontend instances.";
```

2020-06-25 15:12 UTC, prusnak commented on nixos/modules/services/networking/blockbook-frontend.nix
> +}
Please add newline here

2020-06-25 18:46 UTC, 1000101 commented on nixos/modules/services/networking/blockbook-frontend.nix
> +      description = "Sepcification of one or more blockbook-frontend instances.";
Thanks!

2020-06-26 11:32 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 11:37 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 11:39 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 11:47 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 11:49 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 11:51 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 12:16 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 12:45 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 14:18 UTC, 1000101 commented
@ofborg test blockbook-frontend

2020-06-26 16:13 UTC, mmahut commented
@ofborg test blockbook-frontend

2020-06-26 19:17 UTC, mmahut commented
Thank you, good work.

2020-06-26 19:17 UTC, merged