python3Packages.nmigen: from unstable-2020-02-08 to unstable-2020-04-02
NixOS/nixpkgs pull request #92651
Opened 2020-07-07 22:06 UTC by matthuszagh

Fixes nmigen build due to pyvcd being bumped to v0.2.

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-07-09 12:40 UTC, drewrisinger requested changes
LGTM, one niggle. Can you update the homepage to the new one on GitHub (https://nmigen.info/nmigen). Will submit an approving review after that (pending local build of the package).

2020-07-09 17:23 UTC, matthuszagh commented
Done.

2020-07-09 21:04 UTC, drewrisinger approved these changes
* [x] Diff LGTM
* [x] Commits LGTM
* [x] All packages build clean via ``nix-review``
* [x] self-tested via checkPhase.

2020-07-10 16:35 UTC, bhipple commented
Thank you for the review @drewrisinger !

2020-07-10 16:47 UTC, bhipple commented
Result of `nixpkgs-review pr 92651` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>8 packages built:</summary>
<br>- glasgow (python38Packages.glasgow)
<br>- python37Packages.glasgow
<br>- python37Packages.nmigen
<br>- python37Packages.nmigen-boards
<br>- python37Packages.nmigen-soc
<br>- python38Packages.nmigen
<br>- python38Packages.nmigen-boards
<br>- python38Packages.nmigen-soc
</details>

2020-07-10 16:47 UTC, bhipple approved these changes

2020-07-10 16:47 UTC, merged