Add package asdf-vm & fn-cli
NixOS/nixpkgs pull request #92924
Opened 2020-07-11 12:21 UTC by bolasblack

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [x] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-10 01:33 UTC, toothbrush commented
I'm very keen to have `asdf-vm` in my NixOS, so i tried out your patch rebased on current `master`.  It installs fine, but i'm running into some issues perhaps you know about.  This is running NixOS natively, so Linux, not macOS.

Firstly, it seems there's a dependency missing, because when i try to install Python as follows:

```shellsession
$ asdf plugin add python 
$ asdf install python 3.8.1 
.. lots of output ..
make: ar: No such file or directory
```

I was unable to find a related Nix package providing ar, maybe that's in coreutils?  Anyway, perhaps that should be added as a runtime dependency?  Or perhaps that's not the Nix way -- i'm still learning!

Secondly, i was able to install NodeJS as follows:

```shellsession
$ asdf plugin add nodejs
$ asdf install nodejs 12.18.3 
$ asdf shell nodejs 12.18.3
$ npm
/nix/store/gmkxfwl44lxfr9li8bk9f0qdr5xz8vpv-asdf-vm-0.7.8/asdf-vm/lib/commands/command-exec.bash: line 28: /home/paul/.asdf/installs/nodejs/12.18.3/bin/node: No such file or directory
```

What's really weird is that it seems Zsh is lying -- look at the following:

```shellsession
$ stat /home/paul/.asdf/installs/nodejs/12.18.3/bin/node                                                                                                                              File: /home/paul/.asdf/installs/nodejs/12.18.3/bin/node
  Size: 48646656  	Blocks: 95016      IO Block: 4096   regular file
Device: 1ch/28d	Inode: 1725141     Links: 1
Access: (0755/-rwxr-xr-x)  Uid: ( 1000/    paul)   Gid: (  100/   users)
Access: 2020-09-10 11:31:00.361520349 +1000
Modify: 2020-07-23 01:00:17.000000000 +1000
Change: 2020-09-10 11:27:41.101404973 +1000
 Birth: 2020-09-10 11:27:40.854411014 +1000
```

So it's definitely there :thinking: Here's what i do in my `.zshrc` to make `asdf` available:

```zsh
asdf=$(nix-build --no-out-link '<nixpkgs>' -I nixpkgs=$HOME/nixpkgs -A asdf-vm)
if [[ -d $asdf ]]; then
	. "$asdf/asdf-vm/asdf.sh"
fi
```

Apologies for the long story, but i'm hoping somebody can help please :smile:

2020-09-10 01:45 UTC, toothbrush commented
As an update, installing `binutils` got me further with `asdf install python 3.8.1`, but next `pip` failed next saying it needs `zlib`.  I wonder what would be the "Nix"y way of managing these dependencies?

2020-09-29 07:40 UTC, toothbrush commented
Aha, in reference to my previous message where i couldn't figure out why i was getting `no such file or directory` while the file was definitely there, that was a case of very bad error reporting.  For context see https://unix.stackexchange.com/questions/18061/why-does-sh-say-not-found-when-its-definitely-there.  The thing is that a precompiled NodeJS binary was being downloaded which simply didn't work on NixOS, because of missing `/lib/...` that most Linuxes provide.

I managed to find a workaround to force `asdf` to recompile NodeJS which i hope will work.  We'll see.  The workaround was found here: https://unix.stackexchange.com/questions/18061/why-does-sh-say-not-found-when-its-definitely-there

2021-01-18 17:31 UTC, SuperSandro2000 requested changes

2021-01-18 17:31 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +  c4605 = {
Please put this into a separate commit with the message ``maintainers: add c4605``.

2021-01-18 17:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/cluster/fn-cli/default.nix
> +with pkgs;
```suggestion
{ pkgs ? import <nixpkgs> {} }:

```

please do proper inputs!

2021-01-18 17:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/cluster/fn-cli/default.nix
> +  name = "${pname}-${version}";
```suggestion
```

2021-01-18 17:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/cluster/fn-cli/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

please move this to the end.

2021-01-18 17:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/cluster/fn-cli/default.nix
> +  };
```suggestion
  };
```

redundant

2021-01-18 17:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/cluster/fn-cli/default.nix
> +  buildInputs = with pkgs; [
```suggestion
  buildInputs = [
```

2021-01-18 17:31 UTC, SuperSandro2000 commented on pkgs/applications/networking/cluster/fn-cli/default.nix
> +    rev = "${version}";
```suggestion
    rev = version;
```

2021-01-18 17:31 UTC, SuperSandro2000 commented on pkgs/tools/misc/asdf-vm/default.nix
> +{ pkgs ? import <nixpkgs> {} }:
Same review comments apply here as to the other file.

2021-05-22 14:44 UTC, closed without merging

2021-05-26 02:51 UTC, bolasblack commented
@SuperSandro2000 Hi, thanks for your suggestion, sorry for the so late reply, I finally(😝) has time to fix my PR

I created a new PR just for `fn-cli` #124447 (And also thanks @toothbrush, I will create a new PR for `asdf-vm` later and try to fix the problem you encountered), can you help me check my new PR?

2021-05-26 13:47 UTC, bolasblack commented
Hi @toothbrush , I created another PR #124495 , can you please try again?