config: users-groups: fix mkChangedOptionModule for root password hash
NixOS/nixpkgs pull request #92933
Opened 2020-07-11 13:54 UTC by RaghavSood

###### Motivation for this change

Fixed #92910 

###### Things done

Deployed previously broken machine, deployment succeeded with this fix

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-07-11 21:28 UTC, rnhmjoj requested changes
Can you rename the commit to `nixos/users-groups: fix mkChangedOptionModule for root password hash`?

2020-07-11 21:30 UTC, rnhmjoj commented
Also, thank you for opening the PR.

2020-07-12 02:07 UTC, RaghavSood commented
@rnhmjoj I've updated the commit message, thanks for checking the issue and PR so quickly!

2020-07-12 08:11 UTC, merged

2020-07-12 08:44 UTC, rnhmjoj commented
Thank you @floki and @RaghavSood. Sorry for the trouble.

2020-07-12 08:49 UTC, RaghavSood commented
@rnhmjoj No trouble at all, thanks for the opportunity of making my first non-package PR :)