nwg-launchers: init at 0.2.0
NixOS/nixpkgs pull request #93189
Opened 2020-07-15 15:50 UTC by bbigras

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

`swaylock` needs to be in path. I wonder if we should just wrap `result/bin/nwgbar`.

2020-07-16 14:55 UTC, IvarWithoutBones requested changes
a minor nit, otherwise LGTM :)

2020-07-16 14:55 UTC, IvarWithoutBones commented on pkgs/applications/misc/nwg-launchers/default.nix
> +    maintainers = with stdenv.lib.maintainers; [ bbigras ];
```suggestion
    maintainers = with maintainers; [ bbigras ];
```

2020-07-16 15:01 UTC, bbigras commented
Thanks!

2020-07-17 10:15 UTC, IvarWithoutBones commented
commits should be squashed

2020-07-17 16:57 UTC, bbigras commented
Done. Yeah. AFAIK there's no way to accept a proposed change and squad it.

Mergers could use "the merge and squash button" but I know the policy is to squash manually.

2020-07-17 23:14 UTC, IvarWithoutBones approved these changes

2020-07-19 21:14 UTC, berbiche commented
Relevant comment from the `sgtk-menu` PR https://github.com/NixOS/nixpkgs/pull/93456#issuecomment-660640232

https://github.com/nwg-piotr/nwg-launchers/blob/43f7d5a21715f13f0b5c36529f6f407fc9fbb35a/bar/bar.json#L2-L6

2020-07-21 16:12 UTC, bbigras commented
Thanks @berbiche.

I updated the PR to wrap `nwgbar`. I think it might be simpler that way. It will work if someone is using his own bar.json.

The closure's size doesn't seem to change much:
/nix/store/nrhy46w551h9md9hbk69cckxlg76wwcr-nwg-launchers-0.2.0	 182.1M
/nix/store/i5slffzzkv9fw98r4ybgdpq2mkkmmwix-nwg-launchers-0.2.0	 197.0M (with swaylock)

We could have an option to wrap it optionally. And maybe have 2 version in `all-packages.nix` to ensure it's in the cache for everyone but I think it's simpler to just always wrap.

I'm very open to comments. Especially from people with more experience with Nix than me.

2020-07-21 16:17 UTC, bbigras commented
/marvin opt-in

2020-07-21 16:17 UTC, bbigras commented
/state needs_review

2020-07-21 16:18 UTC, bbigras commented
/status needs_reviewer

2020-07-24 16:43 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/228

2020-07-30 16:03 UTC, infinisil approved these changes
Looking good! I think always wrapping is fine because it doesn't add that much.

2020-07-30 16:03 UTC, merged