edukai: Init at 4.0
NixOS/nixpkgs pull request #93232
Opened 2020-07-16 07:05 UTC by ShamrockLee

Add `edukai` (MOE Standard Kai Font) version 4.0
If approved, users will be able to install
the Standard Chinese Kai Font (教育部標準楷書字形檔) provided by
the Ministry of Education, Republic of China (Taiwan).

###### Motivation for this change
The MOE Standard Kai Font (教育部標準楷書字形檔) is a piece of Chinese Kai font (楷體) distributed by the Ministry of Education, Republic of China (Taiwan).

This piece of fonts follows the standard ("國字標準字體研訂原則") of the Ministry of Education in Taiwan and would be useful in test sheets, especially when the commercial DFKai-SB (標楷體) is not available.

###### Things done

- [X] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [X] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [X] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [X] Tested execution of all binary files (usually in `./result/bin/`) (No execution files)
- [X] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [X] Ensured that relevant documentation is up to date (No document change needed)
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-07-16 07:21 UTC, ShamrockLee commented
/status needs_reviewer

2020-07-28 18:30 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/233

2020-07-30 08:47 UTC, ShamrockLee commented
/marvin opt-in

2020-07-30 08:47 UTC, ShamrockLee commented
/status needs_reviewer

2020-07-30 15:50 UTC, Infinisil commented
Trying to connect to a homepage of the packages I get

> Secure Connection Failed
>
> An error occurred during a connection to language.moe.gov.tw. Cannot communicate securely with peer: no common encryption algorithm(s).
>
> Error code: SSL_ERROR_NO_CYPHER_OVERLAP

So I propose to use HTTP instead of HTTPS for these links instead (both for the homepage and the download URL)

2020-07-30 15:53 UTC, infinisil requested changes

2020-07-31 07:07 UTC, ShamrockLee commented on pkgs/data/fonts/edukai/default.nix
> +  '';
Thanks a lot!
I added that line as `unzip` wasn't available by default when I wrote this.
I'll change them.

2020-07-31 07:11 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/guidelines-on-packaging-fonts/7683/4

2020-07-31 12:05 UTC, ShamrockLee commented on pkgs/data/fonts/edukai/default.nix
> +  '';
I have them renewed.
/status awaiting_reviewer

2020-07-31 12:08 UTC, ShamrockLee commented
I have them simplified.
/status awaiting_reviewer

2020-07-31 12:09 UTC, ShamrockLee commented
/status awaiting_reviewer

2020-07-31 12:45 UTC, Infinisil commented
See also https://github.com/NixOS/nixpkgs/pull/93232#issuecomment-666478905

2020-08-01 00:19 UTC, ShamrockLee commented
> See also [#93232 (comment)](https://github.com/NixOS/nixpkgs/pull/93232#issuecomment-666478905)

Oops! Thanks for reminding.

2020-08-01 01:38 UTC, infinisil approved these changes
Looking good!

2020-08-01 01:39 UTC, merged