checkbashisms: Remove.  Available in debian-devscripts
NixOS/nixpkgs pull request #93665
Opened 2020-07-22 18:57 UTC by chkno

This version was out of date & confusingly emitted perl warnings about
itself along with warnings about the shell scripts it checked.  The
version in debian-devscripts is more recent & doesn't have this problem.

###### Motivation for this change
Make it easier to find the real `checkbashisms` (it's included in `debian-devscripts`) by removing this old, broken copy.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-07-23 07:23 UTC, lsix commented
I wonder if adding a alias to `debian-scripts` could not make sense to “ease transition” (if there is any to be eased).

2020-07-24 19:38 UTC, chkno commented
I don't think this package is widely used, or there would be more complaints or PRs about it emitting 31 lines of warnings about its own perl syntax before doing its real job and emitting similar-looking warnings about shell syntax in the shell scripts it is invoked on.

2020-10-26 21:43 UTC, wamserma approved these changes
LGTM.

2020-10-26 21:46 UTC, wamserma commented on pkgs/top-level/aliases.nix
> -  checkbashism = checkbashisms; # added 2016-08-16
Maybe put a note here that the standalone package has been removed.

2020-11-26 22:49 UTC, SuperSandro2000 requested changes
Please add an alias that throws that the package got removed.

2021-06-06 21:05 UTC, wamserma commented
`pkgs/development/tools/misc/checkbashisms/default.nix` has been rewritten to extract the script from debian-devscripts, so this PR is obsolete.

2021-06-06 21:05 UTC, closed without merging