nixos/chromium: update link in docs
NixOS/nixpkgs pull request #93794
Opened 2020-07-25 01:22 UTC by tnias

###### Motivation for this change

The linked documentation states the following.

> The Chrome Enterprise policy list is moving! Please update your bookmarks [...]

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-07-25 10:46 UTC, prusnak approved these changes

2020-10-03 19:46 UTC, tnias commented
CC person who did a similar fix @davidak

2020-10-04 00:28 UTC, davidak approved these changes
looks good

2020-10-16 17:52 UTC, primeos requested changes
I think https://cloud.google.com/docs/chrome-enterprise/policies would be better. At least for me https://cloud.google.com/docs/chrome-enterprise/policies/?policy=ExtensionInstallForcelist">ExtensionInstallForcelist doesn't seem to render correctly / contains less "extras".

2020-10-16 19:41 UTC, tnias commented
The correct link is https://cloud.google.com/docs/chrome-enterprise/policies/?policy=ExtensionInstallForcelist without the extra `">ExtensionInstallForcelist`.

The argument `?policy=ExtensionInstallForcelist` opens the appropriate policy description. The link without arguments just displays a list of all policy options.

I am using Chromium Version 85.0.4183.121 (Developer Build) (64-bit) and it seems to render fine. What browser are you using?

2020-10-16 21:03 UTC, primeos approved these changes
> The correct link is https://cloud.google.com/docs/chrome-enterprise/policies/?policy=ExtensionInstallForcelist without the extra ">ExtensionInstallForcelist.

Ups, sorry about that, I was stupid and ignored XML while copying the link. That also explains the strange `">` then :facepalm: 

My bad. Thanks for the fix :)

2020-10-16 21:04 UTC, merged