nixos/sshd: change authorizedKeysFiles
NixOS/nixpkgs pull request #94434
Opened 2020-08-01 10:21 UTC by Izorkin

###### Motivation for this change
This update need to correct work this configuration:

`default/services/sshd.nix`
```
{ lib, ... }:
{
  services.openssh = with lib; {
...
    authorizedKeysFiles = [
      "/etc/ssh/authorized_keys.d/%u"
    ];
...
```

`servers/vm-test/services/sshd.nix`
```
    services.openssh = {
      authorizedKeysFiles = [ /var/lib/gitea/.ssh/authorized_keys" ];
    };
```

Result before update:
```
AuthorizedKeysFile /etc/ssh/authorized_keys.d/%u .ssh/authorized_keys .ssh/authorized_keys2 /etc/ssh/authorized_keys.d/%u /var/data/gitea/.ssh/authorized_keys
```
Result after update:
```
AuthorizedKeysFile /etc/ssh/authorized_keys.d/%u /var/data/gitea/.ssh/authorized_keys
```

cc @Ma27 @aanderse @fpletz

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-01 18:06 UTC, aanderse commented
The idea behind the current code is to merge by default and have the user specify `mkForce` if they want to override. I think the current behavior is ideal.

2020-08-01 18:12 UTC, Izorkin commented
If use in `default/services/sshd.nix` `mkForce` configuration not working. Result only
```
AuthorizedKeysFile /etc/ssh/authorized_keys.d/%u
```

2020-08-01 19:56 UTC, Ma27 requested changes
> If use in default/services/sshd.nix mkForce configuration not working. Result only

You should use `mkForce` for *your* values if needed. This is exactly what this was designed for.

2020-08-01 19:56 UTC, Ma27 commented on nixos/modules/services/networking/ssh/sshd.nix
> +      # https://github.com/NixOS/nixpkgs/pull/41745
No they aren't! If those are option-defaults, those will be lost when defining `authorizedKeysFiles`.

2020-08-01 20:29 UTC, aanderse commented
@Izorkin you should set like this:
```
services.openssh.authorizedKeysFile = lib.mkForce [ "/etc/ssh/authorized_keys.d/%u" "/var/data/gitea/.ssh/authorized_keys" ];
```

2020-08-09 14:49 UTC, Izorkin commented
Worked with this variant:
`default/services/sshd.nix`
```
{ lib, ... }:
{
  services.openssh = with lib; {
...
    authorizedKeysFiles = mkForce [
      "/etc/ssh/authorized_keys.d/%u"
    ];
...
```

`servers/vm-test/services/sshd.nix`
```
    services.openssh = with lib; mkForce {
      authorizedKeysFiles = [ /var/lib/gitea/.ssh/authorized_keys" ];
    };
```

2020-08-09 14:49 UTC, closed without merging