go-dqlite: init at 1.7.0
NixOS/nixpkgs pull request #94924
Opened 2020-08-08 07:13 UTC by mt-caret

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-19 08:44 UTC, mt-caret commented
I've used the dqlite-demo for the Jepsen test mentioned here: https://github.com/canonical/dqlite/issues/258, so I'm pretty confident that this works.

2020-08-24 03:22 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/265

2020-09-06 18:57 UTC, tomberek approved these changes

2020-09-06 18:58 UTC, tomberek commented
builds, runs, and functions as expected on NixOS.

2020-12-16 19:32 UTC, doronbehar requested changes

2020-12-16 19:32 UTC, doronbehar commented on pkgs/tools/admin/go-dqlite/default.nix
> +    raft-canonical.dev
Why use `.dev`?

2020-12-16 19:32 UTC, doronbehar commented on pkgs/tools/admin/go-dqlite/default.nix
> +  doCheck = false;
Should explain this.

2021-01-18 19:27 UTC, SuperSandro2000 requested changes

2021-01-18 19:27 UTC, SuperSandro2000 commented on pkgs/tools/admin/go-dqlite/default.nix
> +buildGoModule rec {
```suggestion
}:

buildGoModule rec {
```

2021-07-20 08:11 UTC, doronbehar commented
Closing due to OP not responding to reviews, and deleting their branch.

2021-07-20 08:11 UTC, closed without merging