glibc: Fix _CS_PATH to include default profile
NixOS/nixpkgs pull request #94937
Opened 2020-08-08 11:39 UTC by McDutchie

###### Motivation for this change

The string returned by [`confstr(_CS_PATH)`](http://pubs.opengroup.org/onlinepubs/9699919799/functions/confstr.html), which is also the output of the command [`getconf PATH`](http://pubs.opengroup.org/onlinepubs/9699919799/utilities/getconf.html), contains a default path that is guaranteed to find (at least) all POSIX standard utilities. The current value is:

    /run/current-system/sw/bin:/bin:/usr/bin

There are two problems with this.

1. /bin and /usr/bin should be removed, as NixOS package management never puts anything there. Anything dropped in /bin or /usr/bin under the name of a standard utility would likely be bogus.

2. The default profile binaries directory is not in it. This is a problem because the default NixOS installation lacks several mandatory standard POSIX utilities. The command recommended by the system's error message for a missing command to install a missing package foo is 'nix-env -iA nixos.foo'. When this is done as root, the corresponding binaries are installed for all users in /nix/var/nix/profiles/default/bin.

###### Things done

pkgs/development/libraries/glibc/fix_path_attribute_in_getconf.patch:
- CS_PATH: Replace `/bin:/usr/bin` fallback by default profile path `/nix/var/nix/profiles/default/bin`.

Fixes: https://github.com/NixOS/nixpkgs/issues/65512

2020-08-09 13:13 UTC, McDutchie commented
Could someone rerun the `ofborg` check? Not sure what it does, but the results indicate it timed out before running anything, so that's not a problem with the PR.

2020-08-13 22:27 UTC, McDutchie commented
Ping @peti (who [committed the original value](https://github.com/NixOS/nixpkgs/blame/master/pkgs/development/libraries/glibc/fix_path_attribute_in_getconf.patch)).

2020-12-29 02:05 UTC, SuperSandro2000 commented
@ofborg eval

2021-06-29 14:27 UTC, McDutchie commented
Again, still not stale. See #65512

2021-06-29 23:53 UTC, lheckemann commented
I'm not sure if /bin and /usr/bin should be removed, due to /bin/sh and /usr/bin/env?

2022-01-03 20:38 UTC, McDutchie commented
Yet again, *not* stale. **COULD SOMEONE FINALLY PLEASE TAKE A LOOK AT THIS ALREADY???**

2022-01-04 11:56 UTC, SuperSandro2000 commented
> /bin and /usr/bin are unused in NixOS.

but not when nixpkgs is used in another Distro. I think it is save to add the new entry but not to remove the default entries.

> Yet again, _not_ stale.

It didn't get any attention in the last 6 months which is stale. That does not mean it is irrelevant.

2022-01-04 12:49 UTC, McDutchie commented
> > /bin and /usr/bin are unused in NixOS.
> 
> but not when nixpkgs is used in another Distro. I think it is save to add the new entry but not to remove the default entries.

Surely another distro that uses nixpkgs would use their own libc and not NixOS's version of glibc.

Besides, you cannot know for sure what the correct default directories on any other OS are.

2022-01-21 00:10 UTC, SuperSandro2000 commented
> Surely another distro that uses nixpkgs would use their own libc and not NixOS's version of glibc.

Nope, everything is linked against the libc in nixpkgs.

> Besides, you cannot know for sure what the correct default directories on any other OS are.

But ``/bin:/usr/bin`` is a pretty good guess which works 99% of the time and removing it from the defaults is bound to break things for people that use nixpkgs on none nixos like me.

2023-01-24 01:36 UTC, Et7f3 commented
Non nix-managed tools would most likely be linked agains an external libc.

Do we have a way to query os ? I see `stdenv.isCygwin`, `stdenv.isMips`, `stdenv.isSunOS` but no `stdenv.isNixOS`.

Maybe add this variable in another PR and use it so on non nixos ok we keep impure path but on nixos we can safely remove them.

2025-04-17 09:07 UTC, shelvacu requested changes

2025-04-17 09:07 UTC, shelvacu commented on pkgs/development/libraries/glibc/fix_path_attribute_in_getconf.patch
> ++#define	CS_PATH	"/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin"
```suggestion
+#define	CS_PATH	"/run/current-system/sw/bin:/nix/var/nix/profiles/default/bin:/usr/bin:/bin"
```

Per the other comments, we want to keep `/bin` and `/usr/bin` so that binaries work on linux systems other than NixOS. They do no harm while running on NixOS

2026-01-21 09:16 UTC, doronbehar commented
Since most reviewers don't want to remove `/usr/bin` and `/bin` from this path, and due to no reply from OP, I'm closing this PR to clean up the stdenv backlog.

2026-01-22 23:07 UTC, McDutchie commented
> Since most reviewers don't want to remove `/usr/bin` and `/bin` from this path, and due to no reply from OP, I'm closing this PR to clean up the stdenv backlog.

@doronbehar, I did not realise a reply from me was required, because @shelvacu above already suggested a solution that satisfies both use cases -- do not remove `/usr/bin:/bin` but simply add `/nix/var/nix/profiles/default/bin`, as that is where previously missing standard commands would go using the install method recommended by the OS.

Why is that option not being considered? It creates no disadvantage for either NixOS proper or other distros using nixpkgs, and fixes the default-path situations for those of us who need to build a POSIX-compliant system.

Please reopen.

2026-01-23 00:10 UTC, doronbehar commented
> Why is that option not being considered?

If you had applied that suggestion after it was suggested, maybe the reviewers here would have approved the PR.

> It creates no disadvantage for either NixOS proper or other distros using nixpkgs, and fixes the default-path situations for those of us who need to build a POSIX-compliant system.
> 
> Please reopen.

I'm not sure I understand that part, but I won't mind reopen. Please note that you should target branch `staging`, and read [this](https://github.com/NixOS/nixpkgs/blob/master/CONTRIBUTING.md#rebasing-between-branches-ie-from-master-to-staging) to do that.

2026-01-23 22:56 UTC, McDutchie commented
I have changed the target branch and amended the PR as requested. Thanks for your patience.

2026-01-24 03:00 UTC, shelvacu approved these changes

2026-01-24 17:16 UTC, doronbehar approved these changes

2026-01-28 05:48 UTC, abathur commented
Not sure what @doronbehar hoped I'd bring to this, so I'll just think out loud. (Sorry--I realize this may be frustrating at this point in this PR's life.)

1. The original motivating issue says:

    > The POSIX standard's idea with this is that shell scripts and other programs that invoke commands can set their $PATH to this system default value if they care about security and want to be sure to use only known-good system utilities and not anything a local user might have overridden in their own `$PATH`.
    
    and under bullet 2 in the proposed solution, also adds:
    
    > the default profile binaries directory should be added to `_CS_PATH` – at the end, so it won't be possible to override any system default packages already present.
    
    I think maybe this issue/PR combo just spent so long lost in the couch cushions that this bit wasn't in focus when shelvacu   suggested re-adding `/usr/bin:/bin` to the end of `_CS_PATH`, but I think I agree with your original assessment that the profile path belongs at the end?

    (I haven't convinced myself how much this matters, but the imperatives of NixOS and other Nix-using systems seem to be in tension here. The current location wouldn't override "system default packages" on NixOS, but it would on any other system. I imagine splash damage from this would be fairly small even as implemented, but reordering should address it.)

2. POSIX or not, a grab-bag of unspecified dependencies does seem to be swimming against "the Nix way". 

    (I don't see this as your problem to fix here--the existing patch has already been doing a form of this since 2013--but I do wonder if we should be doing something more opinionated to encourage more determinism. I'd probably be packaging the scripts and patching the getconf invocations out, myself.)

2026-01-28 22:23 UTC, McDutchie commented
> 1. I think maybe this issue/PR combo just spent so long lost in the couch cushions that this bit wasn't in focus when shelvacu   suggested re-adding `/usr/bin:/bin` to the end of `_CS_PATH`, but I think I agree with your original assessment that the profile path belongs at the end?

It would make no difference on NixOS, but on third-party systems with nixpkgs (at least those that put their standard utilities in /bin and /usr/bin) it would mean default utilities take precedence over anything installed in the profile directory. And that does make sense. I've updated the PR accordingly.

2026-01-29 08:06 UTC, doronbehar approved these changes
Changes LGTM and I think @abathur would approve them too :).

2026-01-29 14:22 UTC, abathur approved these changes

2026-01-29 14:33 UTC, merged