neomutt: 20200626 -> 20200807
NixOS/nixpkgs pull request #95095
Opened 2020-08-10 16:10 UTC by Ma27

###### Motivation for this change

:warning: **Caution:** `20200807` is only a development release and not considered stable, so please *don't* merge! I already had to apply a patch to fix a segfault on startup.

This is *only* intended to be used by power-users who want to try out the latest version. I don't consider this mergable until the 20.09 branchoff happened, after that we can discuss how to proceed with this.

ChangeLog: https://github.com/neomutt/neomutt/releases/tag/20200807

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-11 19:57 UTC, Ma27 commented
@GrahamcOfBorg eval

2020-08-14 20:52 UTC, Ma27 commented
Today's release is marked as stable again and thus we could merge this PR now. Already using the new neomutt version on my machine :)

2020-08-15 09:40 UTC, Ma27 commented
cc @flokli who also might want to take a look :)

2020-08-16 13:07 UTC, flokli requested changes
From a quick glance, LGTM otherwise.

2020-08-16 13:07 UTC, flokli commented on pkgs/applications/networking/mailreaders/neomutt/default.nix
> +, glibcLocales, fetchpatch
The `fetchpatch` isn't needed anymore.

2020-08-16 13:09 UTC, Ma27 commented on pkgs/applications/networking/mailreaders/neomutt/default.nix
> +, glibcLocales, fetchpatch
Fixed :-)

2020-08-16 13:18 UTC, alyssais commented
@GrahamcOfBorg build neomutt

2020-08-16 16:44 UTC, merged