nixos/filesystems: don't allow mountpoints with trailing slash
NixOS/nixpkgs pull request #95406
Opened 2020-08-14 07:27 UTC by Mic92

They are semantically the same as the non-slash version and therefore
are potential source of duplicates.

Also fixes https://github.com/NixOS/nixpkgs/issues/78951

Alternative to https://github.com/NixOS/nixpkgs/issues/78951

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-14 07:33 UTC, lheckemann requested changes
I like the principle, but the regexes could be simpler I think.

2020-08-14 07:33 UTC, lheckemann commented on nixos/modules/tasks/filesystems.nix
> +  isNonEmpty = s: (builtins.match ".*[^ \t]+.*" s) != null;
`(builtins.match "[ \t\n]*" s) == null` seems simpler, while we're at it

2020-08-14 07:33 UTC, lheckemann commented on nixos/modules/tasks/filesystems.nix
> +          (s: isNonEmpty s && (builtins.match "(/|/.*[^/])" s) != null);
`(builtins.match ".*/" s) == null`?

2021-01-18 12:04 UTC, SuperSandro2000 commented
@mic92 ping

2021-01-23 16:32 UTC, Mic92 commented
Done.

2021-01-23 16:33 UTC, Mic92 commented on nixos/modules/tasks/filesystems.nix
> +          (s: isNonEmpty s && (builtins.match "(/|/.*[^/])" s) != null);
We need to allow `/`.

2021-01-23 16:56 UTC, lheckemann commented on nixos/modules/tasks/filesystems.nix
> +          (s: isNonEmpty s && (builtins.match ".+/$" s) == null);
nit: I don't think the $ is necessary, since `builtins.match` already requires the whole string to match.

2021-01-23 16:56 UTC, lheckemann approved these changes

2021-01-24 11:21 UTC, Atemu commented
Small nit but your commit message references my issue, not my alternative PR.

Also, hasn't this been merged already? https://github.com/NixOS/nixpkgs/commit/f536901693ef6128cc61030ee74eb4433793b174  
I'm confused.

2021-01-25 10:08 UTC, Mic92 commented
> Small nit but your commit message references my issue, not my alternative PR.
> 
> Also, hasn't this been merged already? [f536901](https://github.com/NixOS/nixpkgs/commit/f536901693ef6128cc61030ee74eb4433793b174)
> I'm confused.

No at some I accidentally push my local staging branch instead of my upstream staging copy where I merged in master to resolve merge conflicts. I reverted those commits.

2021-01-25 10:13 UTC, Mic92 commented
/marvin opt-in
/status needs_reviewer

2021-01-30 18:45 UTC, Mic92 commented
/status needs_reviewer

2021-01-31 11:27 UTC, kevincox approved these changes

2021-01-31 11:28 UTC, merged