vr-video-player and openvr init
NixOS/nixpkgs pull request #95627
Opened 2020-08-16 22:54 UTC by nyanloutre

###### Motivation for this change
There still is a problem with the https://git.dec05eba.com/vr-video-player git repository, so I made this a draft PR.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-24 20:56 UTC, nyanloutre commented
@ofborg build vr-video-player

2021-01-18 12:17 UTC, SuperSandro2000 requested changes

2021-01-18 12:17 UTC, SuperSandro2000 commented on pkgs/applications/video/vr-video-player/default.nix
> +{ stdenv, fetchgit, pkg-config, gcc, glm, glew, SDL2, x11, xorg, openvr
x11 does not exist.

2021-01-18 12:17 UTC, SuperSandro2000 commented on pkgs/applications/video/vr-video-player/default.nix
> +    gcc
nativeBuildInputs.

2022-04-11 23:39 UTC, SuperSandro2000 commented on pkgs/development/libraries/openvr/default.nix
> +    homepage = "http://steamvr.com";
```suggestion
    homepage = "https://www.steamvr.com/";
```

2022-04-11 23:39 UTC, SuperSandro2000 commented on pkgs/development/libraries/openvr/default.nix
> +  nativeBuildInputs = [ cmake pkgconfig ];
```suggestion
  nativeBuildInputs = [ cmake pkg-config ];
```

2022-04-11 23:39 UTC, SuperSandro2000 commented on pkgs/applications/video/vr-video-player/default.nix
> +  '';
```suggestion
      --add-flags $out/bin/.vr-video-player
  '';
```

2022-04-11 23:39 UTC, SuperSandro2000 commented on pkgs/applications/video/vr-video-player/default.nix
> +  nativeBuildInputs = [
Please correctly split nativeBuildInputs and buildInputs.

2022-04-11 23:39 UTC, SuperSandro2000 commented on pkgs/applications/video/vr-video-player/default.nix
> +    ./build.sh
```suggestion
    # shellfile with calls the compiler direct
    ./build.sh
```

2025-02-25 12:49 UTC, closed without merging