fet-sh: init at 1.3
NixOS/nixpkgs pull request #95766
Opened 2020-08-18 20:53 UTC by elkowar

###### Motivation for this change

[fet.sh](https://github.com/6gk/fet.sh) is a simple, pure sh fetch script for Linux.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-18 21:24 UTC, 6gk commented
👍

2020-08-19 20:21 UTC, 6gk commented
when you break a release tag but it doesn't matter because it only breaks for people using a non-POSIX shell for /bin/sh

2020-08-19 20:23 UTC, 6gk commented
(that was a joke btw, 1.5 fixed it, I didn't notice it because I use dash for /bin/sh)

2020-08-19 21:38 UTC, ryantm requested changes

2020-08-19 21:38 UTC, ryantm commented on pkgs/tools/misc/fet-sh/default.nix
> +    license = licenses.mit;
```suggestion
    license = licenses.isc;
```

2020-08-19 21:38 UTC, ryantm commented on pkgs/tools/misc/fet-sh/default.nix
> +    repo = "fet.sh";
```suggestion
    repo = pname;
```

2020-08-19 21:56 UTC, ryantm approved these changes

2020-08-19 21:57 UTC, ryantm commented
@GrahamcOfBorg build fet-sh

2020-08-19 21:59 UTC, 6gk commented
broken; the repo name is not 'fet-sh' like the package man, it's 'fet.sh'

2020-08-19 22:02 UTC, elkowar commented
fixed the package name, i just applied the suggestion without actually thinking if it will work, and then fell victim to nix not actually rebuilding the package if the hash hasn't changed, sorry

2020-08-19 22:05 UTC, ryantm commented
Oops, sorry.
@GrahamcOfBorg build fet-sh

2020-08-19 22:11 UTC, ryantm commented
```
$ ./results/fet-sh/bin/fet.sh

 ryantm@home1
    os ~ nixos
    sh ~ bash
    wm ~ GNOME
    up ~ 7d 18:13
   cpu ~ Intel i5-6500
   mem ~ 32843MB
  host ~ Z170X-Gaming 3
  kern ~ 5.4.57
  term ~ .nixpkgs-review
``

2020-08-19 22:11 UTC, ryantm commented
Result of `nixpkgs-review pr 95766` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- fet-sh
</details>

2020-08-19 22:11 UTC, merged