nixos/logrotate: switch `paths` option type from listOf to attrsOf (submodule ...)
NixOS/nixpkgs pull request #95809
Opened 2020-08-19 16:48 UTC by aanderse

###### Motivation for this change
https://github.com/NixOS/nixpkgs/pull/87702

It was a really bad idea for me to suggest @jslight90 to use a `listOf` instead of `attrsOf` for the `paths` option. I upgraded a server to `unstable` and tried this out... `attrsOf` is a **much** better fit when given a `priority` option to control sort order.

With this PR NixOS modules can actually start providing log rotation for (the very few) services that actually need it using `logrotate`. The user remains in full control with the ability to even disable log rotation via the `enable` option, like so:
```
services.logrotate.paths.httpd.enable = false;
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-20 23:10 UTC, aanderse commented
@Infinisil we had a small conversation about this module and I always appreciate/enjoy your reviews... would you mind taking a look at this?

2020-08-21 02:23 UTC, Infinisil requested changes

2020-08-21 02:31 UTC, aanderse commented on nixos/modules/services/logging/logrotate.nix
> +        type = with types; attrsOf (submodule pathOpts);
This option hasn't been introduced in a stable release yet, so breaking change is fine.

Many options in `logrotate.conf` are single value without a key so I'm thinking using `settings` over `extraConfig` is more confusing than the value it brings. The `logrotate` format uses the last declared value in the case of duplicates so the compelling reasons to use an attribute set aren't there in my opinion.

2020-08-21 02:31 UTC, aanderse commented on nixos/modules/services/logging/logrotate.nix
> +              keep = 7;
Good point. Will do.

2020-08-21 02:32 UTC, aanderse commented on nixos/modules/services/logging/logrotate.nix
> +      { assertion = pathOpts.user != null || pathOpts.group != null -> pathOpts.user != null && pathOpts.group != null;
Thanks.

2020-08-21 21:24 UTC, infinisil approved these changes
The first commit looks good now, but I can't really comment much on the second one as I don't know a lot about httpd. If you think the second one won't cause any problems then feel free to merge it :)

2020-08-21 21:30 UTC, ryantm approved these changes
Looks good to me. Thanks!

2020-08-21 21:31 UTC, merged