valo: init at 0.2.2
NixOS/nixpkgs pull request #95871
Opened 2020-08-20 19:28 UTC by xrelkd

###### Motivation for this change
A Program to Control Backlights (and other Hardware Lights) in GNU/Linux
- https://github.com/xrelkd/valo
###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-22 05:00 UTC, ryantm requested changes
I think it is not typical to make a NixOS module that just installs a package. So I suggest dropping the module.

2020-12-29 02:23 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 95871` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package blacklisted:</summary>
  <ul>
    <li>tests.nixos-functions.nixos-test</li>
  </ul>
</details>
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>valo</li>
  </ul>
</details>

2021-01-18 00:22 UTC, SuperSandro2000 requested changes

2021-01-18 00:22 UTC, SuperSandro2000 commented on pkgs/os-specific/linux/valo/default.nix
> +    license = licenses.gpl3;
gpl3Only or gpl3Plus?

2021-07-25 17:57 UTC, closed without merging