knightos_c: init at 4.0.0
NixOS/nixpkgs pull request #95891
Opened 2020-08-21 06:56 UTC by siraben

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [x] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-21 15:35 UTC, danieldk requested changes
Thanks! I have added some suggested improvements.

2020-08-27 02:55 UTC, siraben commented
I think it's ready to merge.

2020-08-27 06:12 UTC, danieldk requested changes

2020-08-27 06:12 UTC, danieldk commented on pkgs/development/compilers/kcc/default.nix
> +  nativeBuildInputs = [ cmake boost bison flex ];
```suggestion
  nativeBuildInputs = [ cmake bison flex ];

  buildInputs = [ boost ];
```

2020-08-27 06:12 UTC, danieldk commented on pkgs/development/compilers/kcc/default.nix
> +    license     = licenses.gpl2;
```suggestion
    license     = licenses.gpl2Plus;
```

`gpl2` deprecated, use `gpl2Only` or `gpl2Plus`. From a quick look at the source code, they use the 'or later wording', so this should be `gpl2Plus`.

2020-08-28 12:21 UTC, danieldk approved these changes
LGTM

Result of `nixpkgs-review pr 95891` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- knightos-kcc
</details>

2020-08-28 12:21 UTC, merged