viw: init at 20171029
NixOS/nixpkgs pull request #96285
Opened 2020-08-25 13:36 UTC by AndersonTorres

###### Motivation for this change

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-08-25 15:03 UTC, danieldk requested changes
Added some requested changes.

I also wonder if it makes sense to add this to nixpkgs. It does not seem to be maintained anymore (the last commit is ~3 years ago). Also I wonder if it has any users. Perhaps this fits the NUR better?

2020-08-25 15:03 UTC, danieldk commented on pkgs/applications/editors/viw/default.nix
> +# TODO: optional test mem with valgrind
Stray comment

2020-08-25 15:03 UTC, danieldk commented on pkgs/applications/editors/viw/default.nix
> +  version = "20171029";
```suggestion
  version = "unstable-20171029";
```

2020-08-25 15:03 UTC, danieldk commented on pkgs/applications/editors/viw/default.nix
> +  src = fetchFromGitHub{
```suggestion
  src = fetchFromGitHub {
```

Formatting

2020-08-25 17:53 UTC, AndersonTorres commented on pkgs/applications/editors/viw/default.nix
> +    install -m 644 README.md ${placeholder "out"}/share/doc/${pname}
If it does work without placeholder, then I can change it. No problem to me.

2020-08-25 18:20 UTC, AndersonTorres commented
It is not updated because it is very stable and simple I think. 

About the NUR: well, I need to study it! This being the case, maybe I will just reformat the expression locally and drop this PR.

2020-08-25 18:36 UTC, danieldk commented
> It is not updated because it is very stable and simple I think.
> 
> About the NUR: well, I need to study it! This being the case, maybe I will just reformat the expression locally and drop this PR.

I didn't want to discourage submitting anything to nixpkgs. I was just not certain ;).

2020-08-25 19:34 UTC, AndersonTorres commented on pkgs/applications/editors/viw/default.nix
> +  '';
The tests are located in the `tests` directory. How can I instruct it to checkPhase?

2020-08-25 20:20 UTC, AndersonTorres commented on pkgs/applications/editors/viw/default.nix
> +    license = licenses.gpl3;
OK!

2020-08-25 22:07 UTC, AndersonTorres commented
@danieldk ping!

2020-08-26 05:57 UTC, danieldk approved these changes
I cleaned up `installPhase` a little. LGTM.

Result of `nixpkgs-review pr 96285` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
<br>- viw
</details>

2020-08-26 06:23 UTC, merged