f3d: init at 1.0.1
NixOS/nixpkgs pull request #96934
Opened 2020-09-01 22:30 UTC by bcdarwin

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [x] macOS
   - [x] other Linux distributions
- [NA] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [NA] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-02 10:29 UTC, OPNA2608 requested changes

2020-09-02 10:29 UTC, OPNA2608 commented on pkgs/applications/graphics/f3d/default.nix
> +  };
```suggestion
  src = fetchFromGitLab {
    domain = "gitlab.kitware.com";
    owner = "f3d";
    repo = "f3d";
    rev = "v${version}";
    sha256 = "0a6r0jspkhl735f6zmnhby1g4dlmjqd5izgsp5yfdcdhqj4j63mg";
  };
```

2020-09-02 10:29 UTC, OPNA2608 commented on pkgs/applications/graphics/f3d/default.nix
> +  name = "f3d";
```suggestion
  pname = "f3d";
```

2020-09-02 10:29 UTC, OPNA2608 commented on pkgs/applications/graphics/f3d/default.nix
> +{ stdenv, fetchgit, cmake, vtk_9, libX11, libGL, Cocoa, OpenGL }:
```suggestion
{ stdenv, fetchFromGitLab, cmake, vtk_9, libX11, libGL, Cocoa, OpenGL }:
```

2020-09-02 15:51 UTC, bcdarwin commented on pkgs/applications/graphics/f3d/default.nix
> +{ stdenv, fetchgit, cmake, vtk_9, libX11, libGL, Cocoa, OpenGL }:
Changed, thanks.

2020-09-02 15:51 UTC, bcdarwin commented on pkgs/applications/graphics/f3d/default.nix
> +  name = "f3d";
Good catch, done.

2020-09-02 15:51 UTC, bcdarwin commented on pkgs/applications/graphics/f3d/default.nix
> +  };
Changed.

2020-09-03 09:40 UTC, OPNA2608 approved these changes

2020-09-03 09:46 UTC, OPNA2608 commented
LGTM if it runs for you.

Tested on non-NixOS Linux (Ubuntu 18.04). `SIGABRT`s on startup due to libGL, `LD_LIBRARY_PATH`ing the system's libGL libraries works (afaik this is a known problem, see https://github.com/NixOS/nixpkgs/issues/9415). Not tested with any 3D model.
![image](https://user-images.githubusercontent.com/23431373/92099696-1e49df80-eddb-11ea-834c-c06527faaf6d.png)

2020-09-03 16:49 UTC, bcdarwin commented
I have opened some 3d models and it works fine (except that it's compiled without the -r flag for ray tracing due to VTK not being compiled with necessary support).  Same issue on non-NixOS Linux, but works on OS X.

2020-10-10 13:23 UTC, merged