octave: Fix libtool framework link failure on Darwin
NixOS/nixpkgs pull request #96979
Opened 2020-09-02 22:35 UTC by graham33

###### Motivation for this change

This fix moves linker flags of the form `-framework foo` from dependency_libs to
inherited_linker_flags, since libtool doesn't understand them.  See #96977 for
details.

There may be a better way to do this, and it's also possible/likely that we could just drop these args from dependency_libs rather than moving them to inherited_linker_flags (which would simplify the implementation considerably).  Using inherited_linker_flags was advised here: https://bugreports.qt.io/browse/QTBUG-48575.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [X] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [X] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-06 11:11 UTC, ttuegel approved these changes

2020-09-06 11:13 UTC, ttuegel requested changes
For some reason, the GitHub interface won't let me rebase your pull request. Please rebase this against the `staging` branch.

2020-09-06 19:25 UTC, graham33 commented
Rebased on staging.

2020-09-07 19:57 UTC, ttuegel approved these changes

2020-09-07 19:57 UTC, merged