beauties: init at 0.0.14
NixOS/nixpkgs pull request #97476
Opened 2020-09-08 21:17 UTC by RaitoBezarius

##### Motivation for this change

This open the way for a beauties NixOS service, which would enable a little nice web application for minimalist personal services.

This is my first contribution, I'm not sure how to compute the `vendorSha256`, but will do ASAP if possible and will update what I tried.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-12-29 03:58 UTC, SuperSandro2000 requested changes

2020-12-29 03:58 UTC, SuperSandro2000 commented on pkgs/servers/web-apps/beauties/default.nix
> +  };
```suggestion
  src = fetchFromGitHub {
    owner = "dsx";
    repo = pname;
    rev = "e27e7f5ce69afe7ce966edd568d9c2ec219f7864";
    sha256 = "1rzi4x8ik4fiwmwfff2pqsb7nsvjncwbrikqnzzqi9dv4jwraymh";
  };

  vendorSha256 = null;

  nativeBuildInputs = [ go-bindata ];

  subPackages = ["cmd/beauties"];

  preBuild = ''
    go generate github.com/dsx/beauties/cmd/...
  '';

  doCheck = false;
```

2020-12-29 03:58 UTC, SuperSandro2000 commented on pkgs/servers/web-apps/beauties/default.nix
> +    maintainers = with maintainers; [];
Please add yourself as a maintainer.

2020-12-29 03:58 UTC, SuperSandro2000 commented on pkgs/top-level/all-packages.nix
> +  beauties = callPackage ../servers/web-apps/beauties { };
Please sort this.

2020-12-29 04:01 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 97476` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>beauties</li>
  </ul>
</details>

2021-01-18 00:25 UTC, SuperSandro2000 requested changes

2021-01-18 00:25 UTC, SuperSandro2000 commented on pkgs/servers/web-apps/beauties/default.nix
> +    	go generate github.com/dsx/beauties/cmd/...
```suggestion
    go generate github.com/dsx/beauties/cmd/...
```

2021-01-18 00:25 UTC, SuperSandro2000 commented on pkgs/servers/web-apps/beauties/default.nix
> +  src = fetchFromGitHub {
Please move this after version.

2022-01-16 23:38 UTC, RaitoBezarius commented
closing as I am not using this anymore.

2022-01-16 23:38 UTC, closed without merging