nixos/nfsd: run rpc-statd as a normal user (backport)
NixOS/nixpkgs pull request #97493
Opened 2020-09-09 01:14 UTC by peterhoeg

##### Motivation for this change

Run `rpc-statd` as an unprivileged user.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-09 01:14 UTC, peterhoeg commented
Backport of #96844

2020-09-10 06:21 UTC, vcunat requested changes
https://github.com/NixOS/nixpkgs/pull/96844#issuecomment-690015233

2021-07-05 20:08 UTC, mweinelt commented
Unfortunately NixOS 20.09 has reached its end-of-life status on 2021-07-01, one
month after the release of NixOS 21.05.

Since we do not accept any changes to its branches anymore, I'm closing this pull
request.

2021-07-05 20:08 UTC, closed without merging

2021-07-06 01:54 UTC, peterhoeg commented
Thank you for cleaning up. I should have closed this much earlier as "not-valid". It's not the correct way to fix it.