nixos/systemd-boot: Temporarily ignore errors
NixOS/nixpkgs pull request #97689
Opened 2020-09-10 18:36 UTC by TethysSvensson

This is a temporary fix for #97433. A more proper fix has been
implemented upstream in systemd/systemd#17001, however until it gets
backported, we are stuck with ignoring the error.

After the backport lands, this commit should be reverted.

CC: @flokli 

###### Motivation for this change

See [this comment](https://github.com/NixOS/nixpkgs/issues/97433#issuecomment-690284011) on the issue.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-10 18:51 UTC, flokli requested changes
Please also add a comment above linking to the issue as well.

2020-09-10 18:57 UTC, TethysSvensson commented
> Please also add a comment above linking to the issue as well.

Done

2020-09-11 08:53 UTC, flokli commented
LGTM, and tested switching my systems to a version with this PR - (even though on my systems `bootctl` didn't do a nonzero exit before)

2020-09-11 08:53 UTC, merged

2020-09-11 11:25 UTC, flokli commented
@TethysSvensson this also needs to be backported to 20.09, right?

2020-09-11 20:11 UTC, flokli commented
Backported to 20.09 in cda641eb95b8209bacb3fd3146ce5b398d414998.