nixos/spice-usb-redirection: init
NixOS/nixpkgs pull request #97826
Opened 2020-09-12 07:28 UTC by lheckemann

###### Motivation for this change
Fix #39618

###### Things done

- [x] Built system with option enabled
- [x] Tested redirecting a USB device to a VM
- [x] Ensured that relevant documentation is up to date (option is documented)
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-12 07:32 UTC, bjornfor approved these changes

2020-09-12 10:01 UTC, jtojnar requested changes

2020-09-12 10:01 UTC, jtojnar commented on nixos/modules/virtualisation/spice-usb-redirection.nix
> +    environment.systemPackages = [ pkgs.spice_gtk ];
Could you also add a comment that this is for installing polkit actions?

2020-09-12 15:01 UTC, lheckemann commented
Some good points, thanks!

2020-09-19 05:52 UTC, merged

2020-09-19 05:52 UTC, lheckemann commented
Argh, forgot to squash the fixup commit in. Oh well.