add nodePackages.vega-cli: init at version 5.15.0
NixOS/nixpkgs pull request #97908
Opened 2020-09-13 13:35 UTC by MMesch

###### Motivation for this change

Adds the [vega command line tools](https://vega.github.io/vega/usage/#cli) for plotting. This means the binaries:

```
vg2svg
vg2pdf
vg2png
```

This PR _doesn't_ add the [vega-lite cli](https://vega.github.io/vega-lite/usage/compile.html#cli) yet because I had some packaging issues caused by `npx` downloads that are executed on vega-lite runtime.

I tested these tools with:

```
nix-shell --pure -I nixpkgs=./nixpkgs -p busybox -p nodePackages.vega-cli --command "wget -O - https://vega.github.io/vega/examples/bar-chart.vg.json | vg2png"
```

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-14 10:47 UTC, MMesch commented
I tried to run `nixpkgs-review pr --post-result 97908` and stopped it after 2h because I needed the CPU. It somehow seems to hang on `twemoji`, `mojione` and `sagedoc`. `inkscape` also somehow appears there. The output that I got until then is:

```
$ git -c fetch.prune=false fetch --force https://github.com/NixOS/nixpkgs master:refs/nixpkgs-review/0 pull/97908/head:refs/nixpkgs-review/1
$ git worktree add /home/matto/.cache/nixpkgs-review/pr-97908-1/nixpkgs 24fa210e772351f118e5f56e5acbe5eaea38a95f
Preparing worktree (detached HEAD 24fa210e772)
Updating files: 100% (22686/22686), done.
HEAD is now at 24fa210e772 rclone: 1.53.0 -> 1.53.1 (#97953)
$ nix-env -f /home/matto/.cache/nixpkgs-review/pr-97908-1/nixpkgs -qaP --xml --out-path --show-trace
$ git merge --no-commit 690fffccf47b4561013912dd37d5bda8ea8484b7
Automatic merge went well; stopped before committing as requested
$ nix-env -f /home/matto/.cache/nixpkgs-review/pr-97908-1/nixpkgs -qaP --xml --out-path --show-trace --meta
39 packages updated:
bitwarden-cli emojione etcher image_optim lumo node_castnow node_create-cycle-app node_imapnotify joplin (1.0.166 → 1.0.167) node_mirakurun netlify-cli (2.61.0 → 2.62.0) node_redoc-cli node_thelounge node_triton node__at_antora_slash_cli node__at_webassemblyjs_slash_wasm-text-gen parity-ui ripcord sage sage sage slack slack twemoji-color-font vimPlugins.coc-css (1.2.4 → 1.2.5) vimPlugins.coc-eslint (1.2.7 → 1.3.0) vimPlugins.coc-git (1.8.3 → 2.0.0) vimPlugins.coc-go (0.10.0 → 0.11.0) vimPlugins.coc-highlight (1.2.5 → 1.2.6) vimPlugins.coc-jest (1.0.3 → 1.0.4) vimPlugins.coc-json (1.2.6 → 1.3.0) vimPlugins.coc-metals (0.9.2 → 0.9.3) vimplugin-coc-prettier vimPlugins.coc-r-lsp (1.1.1 → 1.2.0) vimPlugins.coc-snippets (2.1.28 → 2.2.0) vimPlugins.coc-solargraph (1.1.6 → 1.1.7) vimplugin-coc-stylelint vimPlugins.coc-tsserver (1.5.5 → 1.5.6) vimPlugins.coc-vetur (1.1.12 → 1.1.13)

$ nix build --no-link --keep-going --option build-use-sandbox relaxed -f /home/matto/.cache/nixpkgs-review/pr-97908-1/build.nix
builder for '/nix/store/b42m79dxaz44gjb4gpg3mmlwdr4zxy4h-node_joplin-1.0.167.drv' failed with exit code 1; last 10 log lines:
  npm ERR! errno 1
  npm ERR! keytar@5.6.0 install: `prebuild-install || node-gyp rebuild`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the keytar@5.6.0 install script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /build/.npm/_logs/2020-09-14T08_13_48_980Z-debug.log
 [...]
```

2020-09-14 11:20 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/prs-ready-for-review/3032/299

2020-09-16 09:44 UTC, doronbehar commented
@MMesch It's almost impossible to merge changes to node packages, unfortunately. Could you please fix them and ping me when you are ready? Preferably, `git add` all the files (don't use `--patch` to select only the changes relevant to you). I promise I'll merge it before there are merge conflicts.

Once that'll be done, I'd be happy to get your help on https://github.com/NixOS/nixpkgs/pull/96961 .

2020-09-16 21:27 UTC, MMesch commented
Hi @doronbehar 

> It's almost impossible to merge changes to node packages, unfortunately

What do you mean with this? Is it possible or not? I looked on your PR and saw that you suggested generating nix expressions for the packages you want to add independently. I have done that equally for vega-cli and vega-lite on my machine. Do you think it would be better to move forward like this?

Also, I already added `git add` everything! Are there files that you are missing?

2020-09-17 06:21 UTC, doronbehar commented
> What do you mean with this?

I mean that as a contributor, with no merge permissions, it's impossible to put out a PR, and when the time comes for a committer to merge it, the PR has no merge conflicts.

> I have done that equally for vega-cli and vega-lite on my machine. Do you think it would be better to move forward like this?

It depends on you. For balena-cli, I realized at a certain point I have to do it because their releases are too frequent for node packages' `generate.sh`. If you'd like to have more influence upon it, I'd suggest to make it have it's own set of generated nix expressions. Plus, for sure you'd probably won't encounter merge conflicts with the generated expressions.

2020-09-17 06:22 UTC, doronbehar commented
> Are there files that you are missing?

I don't think so, but I haven't checked.

2020-09-18 22:10 UTC, MMesch commented
@doronbehar I have rebased and regenerated node-packages.nix for the two relevant commits. Maybe I didn't understand if you wanted to do anything else. Let me know!

In case there are conflicts again, this can be rebased from the nodePackages folder with:

```
git fetch
git rebase origin/master
git checkout --theirs node-packages.nix
./generate.sh
git add .
git rebase --continue
git checkout --theirs node-packages.nix
./generate.sh
git add .
git rebase --continue
```

(takes ~2h on my machine)

2020-09-19 11:41 UTC, doronbehar commented on pkgs/development/node-packages/default.bak
> +{ pkgs, nodejs, stdenv }:
This file is a Git rebase leftover right?

2020-09-19 12:09 UTC, MMesch commented
Right! Sorry. It should be deleted. Do you want me to do it again?

Doron Behar <notifications@github.com> schrieb am Sa., 19. Sep. 2020, 13:41:

> *@doronbehar* commented on this pull request.
> ------------------------------
>
> In pkgs/development/node-packages/default.bak
> <https://github.com/NixOS/nixpkgs/pull/97908#discussion_r491398764>:
>
> > @@ -0,0 +1,200 @@
> +{ pkgs, nodejs, stdenv }:
>
> This file is a Git rebase leftover right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/97908#pullrequestreview-491993335>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAT2HK2QY5ZJI4UQYK3UGZ3SGSKGVANCNFSM4RKVLFJQ>
> .
>

2020-09-19 12:15 UTC, doronbehar commented on maintainers/maintainer-list.nix
> +  mmesch = {
the commit message should be:

```
maintainers: add mmesch
```

2020-09-19 12:17 UTC, doronbehar commented
You should be able to spare yourself running `./generate.sh`, but you should need rewriting history a bit.

2020-09-19 12:30 UTC, MMesch commented
I hope it's ok now @doronbehar . I ran the `vega-cli` and `vega-lite` tests that I posted above and they work.

2020-09-19 12:35 UTC, doronbehar requested changes

2020-09-19 12:35 UTC, doronbehar commented on pkgs/development/node-packages/default.nix
> +	# derivation.
```suggestion
        # npx tries to install vega from scratch at vegalite runtime if it
        # can't find it. We thus replace it with a direct call to the nix
        # derivation.
        postInstall = ''
```

2020-09-19 12:35 UTC, doronbehar commented on pkgs/development/node-packages/default.nix
> +	'';
```suggestion
    '';
```

Mixed indentation.

2020-09-19 13:08 UTC, MMesch commented
Sorry for the formatting issues. How about now @doronbehar ?

2020-09-19 14:34 UTC, doronbehar commented on pkgs/development/node-packages/default.nix
> +    '';
```suggestion
          substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2pdf \
            --replace "npx -p vega vg2pdf"  "${self.vega-cli}/bin/vg2pdf"
          substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2svg \
            --replace "npx -p vega vg2svg"  "${self.vega-cli}/bin/vg2svg"
          substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2png \
            --replace "npx -p vega vg2png"  "${self.vega-cli}/bin/vg2png"
      '';
```

Sorry for the nitpick, but it should be perfect now!

2020-09-19 14:49 UTC, doronbehar commented
@MMesch after fixing once more the indentation, please apply this patch:

```patch
diff --git i/pkgs/development/node-packages/default.nix w/pkgs/development/node-packages/default.nix
index 71b9bd77411..8d8d9fc89ae 100644
--- i/pkgs/development/node-packages/default.nix
+++ w/pkgs/development/node-packages/default.nix
@@ -181,6 +181,8 @@ let
         # https://sharp.pixelplumbing.com/install
         vips
 
+        libsecret
+        self.node-gyp-build
         self.node-pre-gyp
       ];
     };
```

And commit it as: `joplin: fix build by adding libsecret and node-gyp-build`.

It's not related to your PR, but these are new deps that your update to all of node packages require - since you ran `./generate.sh`.

2020-09-19 14:51 UTC, MMesch commented
Ah s... I forgot that one. Unfortunately I can't do it until tomorrow. If
you have the time to amend this and merge go ahead, otherwise it has to
wait.

Thabks for the help and sorry for all the work :( I tried to use nixfmt on
this but it changes a lot of other things.

Doron Behar <notifications@github.com> schrieb am Sa., 19. Sep. 2020, 16:34:

> *@doronbehar* commented on this pull request.
> ------------------------------
>
> In pkgs/development/node-packages/default.nix
> <https://github.com/NixOS/nixpkgs/pull/97908#discussion_r491457458>:
>
> > +        substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2pdf \
>
> +          --replace "npx -p vega vg2pdf"  "${self.vega-cli}/bin/vg2pdf"
>
> +        substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2svg \
>
> +          --replace "npx -p vega vg2svg"  "${self.vega-cli}/bin/vg2svg"
>
> +        substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2png \
>
> +          --replace "npx -p vega vg2png"  "${self.vega-cli}/bin/vg2png"
>
> +    '';
>
>
> ⬇️ Suggested change
>
> -        substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2pdf \
>
> -          --replace "npx -p vega vg2pdf"  "${self.vega-cli}/bin/vg2pdf"
>
> -        substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2svg \
>
> -          --replace "npx -p vega vg2svg"  "${self.vega-cli}/bin/vg2svg"
>
> -        substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2png \
>
> -          --replace "npx -p vega vg2png"  "${self.vega-cli}/bin/vg2png"
>
> -    '';
>
> +          substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2pdf \
>
> +            --replace "npx -p vega vg2pdf"  "${self.vega-cli}/bin/vg2pdf"
>
> +          substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2svg \
>
> +            --replace "npx -p vega vg2svg"  "${self.vega-cli}/bin/vg2svg"
>
> +          substituteInPlace $out/lib/node_modules/vega-lite/bin/vl2png \
>
> +            --replace "npx -p vega vg2png"  "${self.vega-cli}/bin/vg2png"
>
> +      '';
>
>
> Sorry for the nitpick, but it should be perfect now!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/NixOS/nixpkgs/pull/97908#pullrequestreview-492002491>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AAT2HK7AGDYY33KHZW4DWL3SGS6RDANCNFSM4RKVLFJQ>
> .
>

2020-09-19 19:00 UTC, merged

2020-09-20 18:23 UTC, MMesch commented
Many thanks for you help @doronbehar . How can I help with your PR?

2020-09-20 22:00 UTC, doronbehar commented
TBH I only want someone to approve it for the record, and verify that it works. And comments upon meta data or such would be welcome https://github.com/NixOS/nixpkgs/pull/96961 .