akira: version bump 2020-05-01 -> 0.0.13
NixOS/nixpkgs pull request #98007
Opened 2020-09-14 21:23 UTC by neonfuz

###### Motivation for this change
Version bump  2020-05-01 -> 0.0.13

Upstream started using tagged versions so the package is no longer dated snapshots. I added myself as a maintainer because I intend on following the development of this software and I'm willing to maintain the nix package.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [x] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-14 21:27 UTC, worldofpeace requested changes
The commit message should be
```
akira: 2020-05-01 -> 0.0.13
```

See CONTRIBUTING.md and git log

2020-09-14 22:35 UTC, worldofpeace commented
Oops, I should've been `akira-unstable`. Though, now that I think about it, does that mean this shouldn't be `unstable` anymore?

2020-09-15 00:41 UTC, neonfuz commented
I kept unstable because it's still early alpha software, all they did is recently start tagging builds. Does -unstable on nixos just mean an untagged / dated release? If so it should probably be removed, contributing.md doesn't say anything about this but I thought I remember reading somewhere in nix docs what -unstable means

2020-09-15 00:48 UTC, worldofpeace commented
> I kept unstable because it's still early alpha software, all they did is recently start tagging builds. Does -unstable on nixos just mean an untagged / dated release? If so it should probably be removed, contributing.md doesn't say anything about this but I thought I remember reading somewhere in nix docs what -unstable means

`*-unstable` **packages** exists for packages that simultaneously distribute an unstable version with a stable version, or are just strictly alpha software. I can see from the version `0.0.13` (if this is actual semantic version) as a pre-release. So I guess we don't **have** to change this just yet.

2020-09-15 00:53 UTC, merged

2020-09-15 00:53 UTC, worldofpeace commented
Thanks @neonfuz :sparkles: