Update vscode to 1.49.1
NixOS/nixpkgs pull request #98189
Opened 2020-09-18 00:08 UTC by samuela

This PR was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).

Internal tag: cd0d09d9c668c54e4ee93799d6921fff

2020-09-18 01:12 UTC, eadwu approved these changes
Verified hashes.

2020-09-19 13:51 UTC, danieldk requested changes
Please set the change the commit message and PR title according to the [contribution guidelines](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

Also, I realize that this was generated automatically, but it really helps if PRs have a correctly filled PR template:

https://github.com/NixOS/nixpkgs/blob/master/.github/PULL_REQUEST_TEMPLATE.md

2020-09-19 19:32 UTC, samuela commented
@danieldk Ok, I've edited this PR, and I'll upgrade nixpkgs-upkeep to fix this in the future!

2020-09-23 22:06 UTC, samuela commented
friendly ping on this

2020-09-24 06:10 UTC, danieldk approved these changes
Thanks! LGTM.

Result of `nixpkgs-review pr 98189` [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>vscode</li>
    <li>vscode-with-extensions</li>
  </ul>
</details>

Runs as expected.

2020-09-24 06:10 UTC, merged