firmwareLinuxNonFree: 2020-05-19 -> 2020-09-18
NixOS/nixpkgs pull request #98420
Opened 2020-09-21 19:46 UTC by lovesegfault

###### Motivation for this change
I noticed this was out of date and I needed some of the newer firmwares.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-25 15:15 UTC, TredwellGit commented
https://github.com/NixOS/nixpkgs/pull/94133 should be closed in favor of this.

2020-09-25 15:22 UTC, TredwellGit requested changes
`sha256` and `outputHash` need to be updated.

2020-09-26 23:06 UTC, lovesegfault commented
@TredwellGit Updated, not sure how I missed that :D

2020-09-27 01:45 UTC, TredwellGit approved these changes
@fpletz Please merge.
###### Things done
- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-01 06:43 UTC, TredwellGit commented
@NeQuissimus, the maintainer of this package does not appear to be active. Since you update the Linux package, could you please consider merging this or point me towards the right person.

2020-10-01 12:17 UTC, ajs124 commented
> `sha256` and `outputHash` need to be updated.

Why is this a fixed output derivation in the first place? Does the build process need network access?

2020-10-01 12:45 UTC, TredwellGit commented
See: https://github.com/NixOS/nixpkgs/pull/44605

2020-10-01 12:53 UTC, NeQuissimus approved these changes

2020-10-01 12:53 UTC, merged