nixos/gnome3: don't enable modules for excludePackages
NixOS/nixpkgs pull request #98510
Opened 2020-09-23 01:30 UTC by mvnetbiz

###### Motivation for this change
#24667
some packages disabled through environment.gnome3.excludePackages end up enabled anyways by their program module.
example:
```
services.xserver.desktopManager.gnome3.enable = true;
environment.gnome3.excludePackages = [ pkgs.gnome3.sushi ];
```
```
$ which sushi
/run/current-system/sw/bin/sushi
```

###### Things done
Enable program module by default only if it's corresponding program is not listed in "excludedPackages"

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-23 01:37 UTC, mvnetbiz commented
These are confusing options since for these specific programs using `environment.gnome3.excludePackages` doesn't do anything, and if this solution is accepted, then there are two separate ways to configure the same thing. Perhaps a better way would be in each relevant program module (ex. nixos/modules/services/desktops/gnome3/sushi.nix) to have an assertion that the package is not in `excludePackages`?

2020-09-23 01:50 UTC, mvnetbiz commented
I think it actually belongs in gnome3 module since that is what enables it, and the program modules should probably be independent of gnome3, and some people might use them separately. I don't think anyone is relying on the silent ignoring of `excludePackages` that will get left without a program they had been using, so I think it belongs here.

2020-10-01 20:06 UTC, worldofpeace commented
@mvnetbiz This is nice!!! I was wondering of a way to do this, because it would make everything a lot nicer.
I did document the old behavior in https://github.com/NixOS/nixpkgs/pull/86288, and I wasn't happy that excludePackages wouldn't work for modules.

2020-10-01 20:08 UTC, worldofpeace requested changes
Can you make your PR title the same as the commit message?

2020-10-01 20:09 UTC, worldofpeace commented
Maybe we should have integration testing for excludePackages. I wouldn't require it in this PR because our tests for gnome aren't that great.

2020-10-02 04:25 UTC, worldofpeace commented
Sorry about that, it seems what I said could easily been interpreted the other way around. Module changes should have `nixos/`.

2020-10-02 04:25 UTC, worldofpeace approved these changes
I tested in a gnome vm with
```
environment.gnome3.excludePackages = [
  pkgs.gnome3.geary
];
```

and verified that geary wasn't included in the installed system.

2020-10-02 05:03 UTC, mvnetbiz commented
Oh that makes sense. I was confused by GitHub UI I couldn't tell what the suggested review actually was. It doesn't explicitly show in the files/review tab when there is commit message amendment I think.

2020-10-06 05:19 UTC, merged

2020-10-06 05:26 UTC, worldofpeace commented
backported in 3c4e4be5147c9248a849e1dc289c94dd364e48f8
Thanks a lot for this, it feel elegant in that the user doesn't have to care about the silly fact that not everything can be installed with `environment.systemPackages`

2020-10-06 05:40 UTC, mvnetbiz commented
Thanks! I didn't want to overcomplicate it, maybe there will be a more general approach to this kind of situation at some point.

2021-03-15 23:01 UTC, nixos-discourse commented
This pull request has been mentioned on **NixOS Discourse**. There might be relevant details there:

https://discourse.nixos.org/t/debloating-gnome/11975/2