ocamlPackages.csexp: fix minimum OCaml version
NixOS/nixpkgs pull request #98957
Opened 2020-09-27 17:42 UTC by hongchangwu

###### Motivation for this change

Source: https://opam.ocaml.org/packages/csexp/csexp.1.3.2/

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [x] other Linux distributions: Ubuntu
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [x] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-09-28 05:33 UTC, vbgl commented
@GrahamcOfBorg build ocaml-ng.ocamlPackages_4_02.csexp

2020-09-28 05:35 UTC, vbgl requested changes
You need to fix the package before claiming it works!

2020-09-28 16:52 UTC, hongchangwu commented
Apologies for not having done a more thorough test on this. I thought the OCaml 4.08 requirement was just about Dune 1 vs Dune 2. I now realize there is also the issue of the `result` package. I'll update `result` to 1.5 (which is compatible for OCaml >= 4.08) and remove the `postPatch` step here.

2020-10-01 02:21 UTC, hongchangwu commented
@GrahamcOfBorg build ocamlPackages.dune-configurator ocaml-ng.ocamlPackages_4_02.csexp ocaml-ng.ocamlPackages_4_08.csexp

2020-10-01 02:23 UTC, hongchangwu commented
@GrahamcOfBorg build dot-merlin-reader

2020-10-01 07:33 UTC, vbgl commented
@GrahamcOfBorg build ocaml-ng.ocamlPackages_4_02.dune-configurator

2020-10-01 07:37 UTC, vbgl commented
There is something wrong about `dune-configurator`: probably a missing `minumumOCamlVersion`.

2020-10-01 12:52 UTC, hongchangwu commented
Yes, will fix in https://github.com/NixOS/nixpkgs/pull/99265

2020-10-01 13:15 UTC, vbgl approved these changes

2020-10-01 13:16 UTC, merged

2020-10-01 13:17 UTC, vbgl commented
Thanks!