openrct2: 0.3.0 -> 0.3.1
NixOS/nixpkgs pull request #99326
Opened 2020-10-01 20:58 UTC by oxzi

###### Motivation for this change
Update OpenRCT2 to its latest release.

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [x] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-03 19:53 UTC, prusnak approved these changes
Tested, works

2020-11-23 08:23 UTC, prusnak commented
Meanwhile v0.3.2 was released. Will you update this PR please?

2020-11-23 21:06 UTC, prusnak requested changes
Meanwhile v0.3.2 was released. Will you update this PR please?

2020-11-24 10:28 UTC, oxzi commented
@prusnak: Thanks for checking back again. I have updated the PR.

2020-11-24 10:54 UTC, prusnak commented
@GrahamcOfBorg build openrct2

2020-11-24 12:03 UTC, merged