sphinx-intl: init at 2.0.1
NixOS/nixpkgs pull request #99544
Opened 2020-10-04 11:48 UTC by EuAndreh

###### Motivation for this change

###### Things done

- [x] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [x] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [x] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-08 15:35 UTC, IvarWithoutBones requested changes
Just 2 minor nits, otherwise LGTM :+1:

2020-10-08 15:35 UTC, IvarWithoutBones commented on maintainers/maintainer-list.nix
> +  euandreh = {
This should be in a seperate commit.

2020-10-08 15:35 UTC, IvarWithoutBones commented on pkgs/development/python-modules/sphinx-intl/default.nix
> +{ lib
I don't see `lib` being used anywhere.

2020-10-08 17:00 UTC, EuAndreh commented
Ivar <notifications@github.com> writes:

> @IvarWithoutBones requested changes on this pull request.
>
> Just 2 minor nits, otherwise LGTM :+1: 
>
>
>
>> @@ -2705,6 +2705,10 @@
>        fingerprint = "67FE 98F2 8C44 CF22 1828  E12F D57E FA62 5C9A 925F";
>      }];
>    };
> +  euandreh = {
>
> This should be in a seperate commit.

👍, I'll rebase and split the commits.

>> @@ -0,0 +1,27 @@
> +{ lib
>
> I don't see `lib` being used anywhere.

It's used on `with lib.maintainers;`.

2020-10-08 17:07 UTC, EuAndreh commented
I've rebased with master and split the commits.

@IvarWithoutBones could you review again?

2020-10-08 17:27 UTC, IvarWithoutBones commented on pkgs/development/python-modules/sphinx-intl/default.nix
> +    maintainers = with lib.maintainers; [ euandreh ];
`lib` is not required here, as its already in scope due to the `with stdenv.lib;` above.
```suggestion
    maintainers = with maintainers; [ euandreh ];
```

2020-10-08 17:45 UTC, EuAndreh commented
Ivar <notifications@github.com> writes:

> @IvarWithoutBones commented on this pull request.
>
>
>
>> +buildPythonPackage rec {
> +  pname = "sphinx-intl";
> +  version = "2.0.1";
> +
> +  src = fetchPypi {
> +    inherit pname version;
> +    sha256 = "1d1q0sanjp4nkfvhsxi75zf3xjyyi8nzxvl3v7l0jy9ld70nwnmj";
> +  };
> +
> +  propagatedBuildInputs = [ Babel click sphinx ];
> +
> +  meta = with stdenv.lib; {
> +    description = "Translation support for Sphinx";
> +    homepage = "https://github.com/sphinx-doc/sphinx-intl";
> +    license = licenses.bsd2;
> +    maintainers = with lib.maintainers; [ euandreh ];
>
> `lib` is not required here, as its already in scope due to the `with stdenv.lib;` above.

👍

I've rebased again.

> ```suggestion
>     maintainers = with maintainers; [ euandreh ];
> ```
>
> -- 
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/NixOS/nixpkgs/pull/99544#pullrequestreview-505007301

2020-11-25 01:11 UTC, SuperSandro2000 requested changes

2020-11-25 01:11 UTC, SuperSandro2000 commented on pkgs/development/python-modules/sphinx-intl/default.nix
> +  version = "2.0.1";
Please disable it before Python 3.5:

```
ERROR: Package 'sphinx-intl' requires a different Python: 2.7.18 not in '>=3.5'
```

2020-11-25 01:11 UTC, SuperSandro2000 commented on pkgs/development/python-modules/sphinx-intl/default.nix
> +  propagatedBuildInputs = [ Babel click sphinx ];
Please disable tests or fetch from GitHub where maybe tests are included:

```
writing manifest file 'sphinx_intl.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

2020-11-25 01:13 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 99544` run on x86_64-linux [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package marked as broken and skipped:</summary>
  <ul>
    <li>python27Packages.sphinx-intl</li>
  </ul>
</details>
<details>
  <summary>2 packages built:</summary>
  <ul>
    <li>python37Packages.sphinx-intl</li>
    <li>python38Packages.sphinx-intl</li>
  </ul>
</details>

2020-11-25 10:34 UTC, EuAndreh commented
I've disabled for older Python versions and rebased with master.

`nixpkgs-review pr 99544` runs successfully for me now.

2020-11-26 01:27 UTC, SuperSandro2000 requested changes

2020-11-26 01:27 UTC, SuperSandro2000 commented on pkgs/development/python-modules/sphinx-intl/default.nix
> +  propagatedBuildInputs = [ Babel click sphinx ];
```
# package does not contain any tests
doChecks = false;
```

2020-11-26 14:00 UTC, EuAndreh commented
Sandro <notifications@github.com> writes:

> # package does not contain any tests
> doChecks = false;

Done and rebased with master.

2020-11-26 15:13 UTC, EuAndreh commented
BTW, thanks @SuperSandro2000 for the reviews!

2020-12-07 22:51 UTC, SuperSandro2000 commented on maintainers/maintainer-list.nix
> +    name = "EuAndreh";
Please add your github name and id like the entries above and below you.

2020-12-07 22:52 UTC, SuperSandro2000 commented
> Done and rebased with master.

Please do not rebase on master. This is only necessary if there are eval errors. Otherwise I cannot follow the changes you did that easily.

2021-06-29 15:53 UTC, EuAndreh commented
Closing stale pull request.  Future interested parties may pick this up and merge in the future.

2021-06-29 15:53 UTC, closed without merging