mas: init at 1.7.1
NixOS/nixpkgs pull request #99608
Opened 2020-10-05 04:51 UTC by zachcoyle

###### Motivation for this change
mas is a command line interface to the Mac App store, and having this package available will allow automation of interactions with the App Store

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [ ] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [ ] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-11-27 23:53 UTC, SuperSandro2000 requested changes
Please put this under os-specific.

2020-11-27 23:53 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/mas/default.nix
> +, stdenv
```suggestion
{ stdenv
```

2020-11-27 23:53 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/mas/default.nix
> +  buildPhase = "true";
```suggestion
  doBuild = false;
```

2020-11-27 23:53 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/mas/default.nix
> +
```suggestion
```

2020-11-27 23:53 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/mas/default.nix
> +  meta = with lib; {
```suggestion
  meta = with stdenv.lib; {
```

2020-11-28 02:38 UTC, SuperSandro2000 commented
Result of `nixpkgs-review pr 99608` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
  <summary>1 package built:</summary>
  <ul>
    <li>mas</li>
  </ul>
</details>

2021-02-12 19:25 UTC, zachcoyle commented
@SuperSandro2000 Thanks for the feedback! Somehow I didn't see this until now

2021-03-30 15:29 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/mas/default.nix
> +  buildInputs = [ libarchive p7zip ];
```suggestion
  nativeBuildInputs = [ libarchive p7zip ];
```

2021-04-02 16:12 UTC, SuperSandro2000 requested changes

2021-04-02 16:12 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/mas/default.nix
> +  meta = with stdenv.lib; {
```suggestion
  meta = with lib; {
```

2021-04-02 16:12 UTC, SuperSandro2000 commented on pkgs/os-specific/darwin/mas/default.nix
> +{ stdenv
```suggestion
{ lib
, stdenv
```

2021-04-02 19:55 UTC, SuperSandro2000 commented
This is a semi-automatic executed nixpkgs-review with [nixpkgs-review-checks extension](https://github.com/SuperSandro2000/nixpkgs-review-checks). It is checked by a human on a best effort basis and does not build all packages (e.g. lumo, tensorflow or pytorch).
If you have any questions or problems please reach out to SuperSandro2000 on IRC.

Result of `nixpkgs-review pr 99608` run on x86_64-darwin [1](https://github.com/Mic92/nixpkgs-review)
<details>
<summary>
1 package built:
</summary>
<ul>
<li>mas</li>
</ul>
</details>

2021-04-02 19:55 UTC, merged