spotify-unwrapped: 1.1.26.501.gbe11e53b-15 -> 1.1.42.622.gbd112320-37
NixOS/nixpkgs pull request #99924
Opened 2020-10-07 04:48 UTC by samuela

###### Motivation for this change
Upgrades spotify-unwrapped from 1.1.26.501.gbe11e53b-15 to 1.1.42.622.gbd112320-37

This PR was automatically generated by [nixpkgs-upkeep](https://github.com/samuela/nixpkgs-upkeep).
- [CI workflow](https://github.com/samuela/nixpkgs-upkeep/actions/runs/292737839) that created this PR.
- Internal tag: 08bf683e76229c9bff6cc4c2764e4d49.

###### Things done

- [ ] Tested using sandboxing ([nix.useSandbox](https://nixos.org/nixos/manual/options.html#opt-nix.useSandbox) on NixOS, or option `sandbox` in [`nix.conf`](https://nixos.org/nix/manual/#sec-conf-file) on non-NixOS linux)
- Built on platform(s)
   - [ ] NixOS
   - [ ] macOS
   - [x] other Linux distributions
- [ ] Tested via one or more NixOS test(s) if existing and applicable for the change (look inside [nixos/tests](https://github.com/NixOS/nixpkgs/blob/master/nixos/tests))
- [ ] Tested compilation of all pkgs that depend on this change using `nix-shell -p nixpkgs-review --run "nixpkgs-review wip"`
- [ ] Tested execution of all binary files (usually in `./result/bin/`)
- [ ] Determined the impact on package closure size (by running `nix path-info -S` before and after)
- [ ] Ensured that relevant documentation is up to date
- [x] Fits [CONTRIBUTING.md](https://github.com/NixOS/nixpkgs/blob/master/.github/CONTRIBUTING.md).

2020-10-07 07:57 UTC, timokau requested changes
Needs manual intervention

```bash
$ spotify
/nix/store/7q5jvc61dq5di8li9wf7wf7ly4pwjf54-spotify-1.1.42.622.gbd112320-37/bin/.spotify-wrapped: error while loading shared libraries: libdrm.so.2: cannot open shared object file: No such file or directory
```

2020-10-08 21:35 UTC, samuela commented
@timokau Ok, noob question... I have this branch checked out but nix-shell is not doing what I'd expect:
```
nixpkgs on  upkeep-bot/spotify-unwrapped-1.1.42.622.gbd112320-37-1602046083 [?] took 27s 
> nix-shell /home/skainswo/dev/nixpkgs -p spotify --pure         
```
gives me a shell with the old spotify version that still works. What's the right way to drop into a nix-shell with the development version?

2020-10-09 07:51 UTC, Ma27 commented
@samuela `nix-shell -p` always uses the `nixpkgs` from `NIX_PATH`. To open a shell with a package from your branch you have to do sth. like this:

```
$ nix-shell -I nixpkgs=/home/skainswo/dev/nixpkgs -p spotify
```

2020-10-09 08:06 UTC, timokau commented
Alternatives are `nix run -f. spotify` (if you are using the experimental nix command) or `nix-build -A spotify; result/bin/spotify`.

2020-10-09 08:07 UTC, samuela commented
Thanks @Ma27! That's a very confusing interface, but it does the trick.

I fixed the libdrm issue in 03ccf40, but now there's a new one:
```
[nix-shell:~/dev/nixpkgs]$ spotify 
/nix/store/lrqra654hqrk7hdghlhpvzkgnxv0mx1b-spotify-1.1.42.622.gbd112320-37/bin/.spotify-wrapped: error while loading shared libraries: libgbm.so.1: cannot open shared object file: No such file or directory
```
but unfortunately I wasn't able to find `libgbm`: https://search.nixos.org/packages?show=libdrm&query=libgbm&from=0&size=30&sort=relevance&channel=unstable.

2020-10-09 10:39 UTC, timokau commented
If you're looking for a specific file, you can use `nix-locate`. Unfortunately it can't find `libgdm.so.1` either, so its probably not packaged. Most likely its https://github.com/libgm/libgm, though it seems a bit odd that spotify introduces a new dependency on a seemingly unmaintained library in "alpha" status.

2020-10-09 10:41 UTC, timokau commented
Actually never mind. I mistyped the name. `libgbm.so.1` is available in the `mesa` package.

2020-10-09 17:31 UTC, samuela commented
Ok, I added the `mesa` dependency in e771518 and spotify builds and runs for me now.

> If you're looking for a specific file, you can use nix-locate. Unfortunately it can't find libgbm.so.1 either, so its probably not packaged. Most likely its https://github.com/libgm/libgm, though it seems a bit odd that spotify introduces a new dependency on a seemingly unmaintained library in "alpha" status.

I wasn't able to get this to work:
```
nixpkgs on  upkeep-bot/spotify-unwrapped-1.1.42.622.gbd112320-37-1602046083 [?] took 2m10s 
> nix-locate 'libgbm'

nixpkgs on  upkeep-bot/spotify-unwrapped-1.1.42.622.gbd112320-37-1602046083 [?] 
> 
```
Am I using `nix-locate` correctly?

2020-10-09 18:03 UTC, samuela commented
Actually there are still some interesting warnings: 
```
/nix/store/4s9aim1fk1s3npkzfygs7jlby6mg4126-spotify-1.1.42.622.gbd112320-37/bin/.spotify-wrapped: /nix/store/k1bskbhj1843vnrz1sbnzxrb32fp2irz-curl-7.72.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/4s9aim1fk1s3npkzfygs7jlby6mg4126-spotify-1.1.42.622.gbd112320-37/bin/.spotify-wrapped)
/nix/store/i99627w01d7bzp4ij4bqg8m22pwaa760-spotify-unwrapped-1.1.42.622.gbd112320-37/share/spotify/.spotify-wrapped: /nix/store/k1bskbhj1843vnrz1sbnzxrb32fp2irz-curl-7.72.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/i99627w01d7bzp4ij4bqg8m22pwaa760-spotify-unwrapped-1.1.42.622.gbd112320-37/share/spotify/.spotify-wrapped)
/nix/store/i99627w01d7bzp4ij4bqg8m22pwaa760-spotify-unwrapped-1.1.42.622.gbd112320-37/share/spotify/.spotify-wrapped: /nix/store/k1bskbhj1843vnrz1sbnzxrb32fp2irz-curl-7.72.0/lib/libcurl-gnutls.so.4: no version information available (required by /nix/store/i99627w01d7bzp4ij4bqg8m22pwaa760-spotify-unwrapped-1.1.42.622.gbd112320-37/share/spotify/.spotify-wrapped)
/proc/self/exe: /nix/store/k1bskbhj1843vnrz1sbnzxrb32fp2irz-curl-7.72.0/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
```

2020-10-09 19:04 UTC, samuela commented
It plays songs and everything else just fine but "Recently Played", "Liked Songs", and "Albums" are just empty... I think that may be Spotify's fault though...

2020-10-09 19:09 UTC, samuela commented
nvm it all works just fine as long as I quit all the other spotify processes first... software is weird

2020-10-11 13:30 UTC, timokau commented
> Am I using `nix-locate` correctly?

`nix-locate` searches for filenames, so you have to type the exact name of the file you're searching for (including the extension).

2020-10-11 13:32 UTC, timokau commented
Thanks for working on this! There's an ofBorg error, unfortunately I don't have time to look into it right now.

2020-10-11 19:07 UTC, samuela commented
The error is apparently 
```
pkgs/servers/mediatomb/default.nix:1:1 called without required argument 'spidermonkey'
```
but I don't think this has anything to do with spotify?

2020-10-12 08:35 UTC, timokau commented
Right, unrelated (https://github.com/NixOS/nixpkgs/pull/100089, https://github.com/NixOS/nixpkgs/pull/100095).

@GrahamcOfBorg eval

2020-10-12 09:13 UTC, timokau approved these changes
Thank you. I'll take the liberty to squash&merge to keep a working commit history.

2020-10-12 09:13 UTC, merged